### ISSUE TITLE
Running gpt4chan and the only answer is !!!!!!!!!!!!

### ISSUE THREAD

**Issue by baconsalad** [oobabooga/text-generation-webui#1025]
### Describe the bug

Trying to run gpt4chan but the only answer it gives is !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Also tried files from -- python download-model.py EleutherAI/gpt-j-6B --text-only --branch float16
have to copy the files into /models/gpt4chan_model_float16/ as it doesn't autoload.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Start webserver.
Disable do_sample (only crashes when enabled)
All answers are !!!!!!!! every time.

Note in the logs the first failure is with do_sample enabled, second is the !!!!!!!.

### Screenshot

![image](https://user-images.githubusercontent.com/1555055/231015098-0ec557a4-af91-40a2-a14b-21d9313a9144.png)

### Logs

```shell
$ LD_LIBRARY_PATH=/opt/cuda/targets/x86_64-linux/lib/${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}} python server.py --model gpt4chan_model_float16 --threads 24 --auto-devices --gpu-memory 10 --load-in-8bit

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: /opt/cuda/targets/x86_64-linux/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 6.1
CUDA SETUP: Detected CUDA version 121
/storage/text-generation-webui/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary /storage/text-generation-webui/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so...
Loading gpt4chan_model_float16...
Loaded the model in 43.36 seconds.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/storage/text-generation-webui/modules/callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/storage/text-generation-webui/modules/text_generation.py", line 228, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/storage/text-generation-webui/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/storage/text-generation-webui/venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 1485, in generate
    return self.sample(
  File "/storage/text-generation-webui/venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 2560, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
Output generated in 1.75 seconds (0.00 tokens/s, 0 tokens, context 33, seed 864588752)
Output generated in 42.41 seconds (4.69 tokens/s, 199 tokens, context 33, seed 371697069)
```

### System Info

```shell
gpu: nvidia 1080ti, 11G vmram
cpu: 3950X 
ram: 32G
OS: gentoo
installed with venv
```

**Comment by jllllll** [comment]
https://github.com/oobabooga/text-generation-webui/issues/931#issuecomment-1501259027

**Comment by oobabooga** [comment]
I think that the issue in this case is the use of 8-bit mode. It is not officially supported on non RTX cards, but you can get it working with some workarounds 

Maybe @Ph0rk0z can help

**Comment by jllllll** [comment]
> I think that the issue in this case is the use of 8-bit mode. It is not officially supported on non RTX cards (I could be bullshitting, the point is that it only works on newer cards), but you can get it working with some workarounds
> 
> Maybe @Ph0rk0z can help

I've been able to use 8-bit mode on my 1080ti, but it is so slow and lower quality that it just isn't worth using.

**Comment by jllllll** [comment]
I've been able to run gpt4chan, but it wasn't the float16 version and it was on cuda 11.7.

**Comment by baconsalad** [comment]
That was it, I removed --load-in-8bit and it started working. I could have sworn I tested removing that flag but I guess not.

Thanks for you help!

**Comment by catalpaaa** [comment]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by BarfingLemurs** [comment]
It means "friend" in 4hanese

**Comment by Ph0rk0z** [comment]
This really doesn't work natively on RX 20XX?

Well you ask so I deliver.. on an older card too.. had to set llm_int8_threshold=0.8 or I get NaN. I think I will go back to making this a parameter now because it's annoying to edit the code. It's not much "savings" as during generation is asks for ~15gb of vram.

Edited so I don't get banned from github.
![mongirl](https://user-images.githubusercontent.com/59298527/231183997-5e663ccd-0b0e-49d7-a591-d19e5947bc81.png)
