### ISSUE TITLE
not working no cuda extesnion or run time found?

### ISSUE THREAD

**Issue by Disorbs** [oobabooga/text-generation-webui#1037]
### Describe the bug

So i download the repo and installed the first step. 
Installer then module then started the webui bat but i get this.

"CUDA extension not installed"

then i saw someone said to try going into 
"oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa" and run python start_cuda.py install
but i also get this and and now im stuck in a loop i have the right paths in env idk if i have the right versions tho

nvcc --version

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

For me just download the repo
run the installer
then model 
then run start webui bat

### Logs

```shell
Z:\AI-Chat\oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa>python setup_cuda.py install
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1'
running install
c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing quant_cuda.egg-info\PKG-INFO
writing dependency_links to quant_cuda.egg-info\dependency_links.txt
writing top-level names to quant_cuda.egg-info\top_level.txt
reading manifest file 'quant_cuda.egg-info\SOURCES.txt'
writing manifest file 'quant_cuda.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
Traceback (most recent call last):
  File "Z:\AI-Chat\oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa\setup_cuda.py", line 4, in <module>
    setup(
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\setuptools\_distutils\core.py", line 177, in setup
    return run_commands(dist)
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\setuptools\_distutils\core.py", line 193, in run_commands
    dist.run_commands()
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
    super().run_command(command)
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
    cmd_obj.run()
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\setuptools\command\install.py", line 74, in run
    self.do_egg_install()
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\setuptools\command\install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\setuptools\_distutils\cmd.py", line 317, in run_command
    self.distribution.run_command(command)
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
    super().run_command(command)
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
    cmd_obj.run()
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\setuptools\command\bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\setuptools\command\bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\setuptools\_distutils\cmd.py", line 317, in run_command
    self.distribution.run_command(command)
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
    super().run_command(command)
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
    cmd_obj.run()
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\setuptools\_distutils\command\install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\setuptools\_distutils\cmd.py", line 317, in run_command
    self.distribution.run_command(command)
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
    super().run_command(command)
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
    cmd_obj.run()
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
    _check_cuda_version(compiler_name, compiler_version)
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\torch\utils\cpp_extension.py", line 382, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 49, in parse
    return Version(version)
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 264, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```

### System Info

```shell
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Feb__8_05:53:42_Coordinated_Universal_Time_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0
```

**Comment by Disorbs** [comment]
i also did a bit more to get it working by following this but no luck - https://github.com/oobabooga/text-generation-webui/issues/936#issuecomment-1502977389
