### ISSUE TITLE
Windows 1-click installer on 8-bit is broken on Windows 10

### ISSUE THREAD

**Issue by Asais10** [oobabooga/text-generation-webui#1043]
### Describe the bug

Using pygmalion-6b (the regular, not dev nor original build) with oobabooga text generation ui installed via the one click installer in 8bit mode on Windows 10 simply leads to no responses and the error mentioned in the Logs tab.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

call python server.py --load-in-8bit --model pygmalion-6b

Here is the edited line from start-webui.bat, it's probable that it's tied to 8bit but my GPU does not have enough VRAM to run with 16bit precision, and Deepspeed does not work either. 

### Logs

```shell
Traceback (most recent call last):
  File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\gradio\utils.py", line 490, in async_iteration
    return next(iterator)
  File "C:\Program Files\oobabooga-windows\text-generation-webui\modules\api.py", line 28, in generate_reply_wrapper
    for i in generate_reply(params[0], generate_params):
  File "C:\Program Files\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 167, in generate_reply
    input_ids = encode(question, generate_state['max_new_tokens'], add_bos_token=generate_state['add_bos_token'])
KeyError: 'add_bos_token'
```

### System Info

```shell
Nvidia Geforce RTX 2080ti
Windows 10
```

**Comment by Asais10** [comment]
Nevermind this error seems to be tied to SillyTavern, for which I'm using oobabooga as an API. I tried oobabooga by itself again, and this time it did not throw out the error, strange.
