### ISSUE TITLE
Models not working

### ISSUE THREAD

**Issue by springheeledjack66** [oobabooga/text-generation-webui#1058]
### Describe the bug

I followed the online installation guides for the one-click installer but can't get it to run any models, at first it wasn't recognising them but found out the tag lines in the .bat were the cause, but now theses new errors have come up and I can't find any info about it on git. can anyone please point me in the right direction? 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I launched the program and selected a model

### Logs

```shell
for model 1

Starting the web UI...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 6.1
CUDA SETUP: Detected CUDA version 117
D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:141: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117_nocublaslt.dll...
The following models are available:

1. facebook_opt-6.7b
2. gpt4-x-alpaca-13b-native-4bit-128g
3. vicuna-13b-4bit-128g.safetensors

Which one do you want to load? 1-3

1

Loading facebook_opt-6.7b...
Auto-assiging --gpu-memory 5 for your GPU to try to prevent out-of-memory errors.
You can manually set other values.
Loading checkpoint shards:   0%|                                                                 | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 442, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models\\facebook_opt-6.7b\\pytorch_model-00001-of-00002.bin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\text-generation-webui\server.py", line 302, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\text-generation-webui\modules\models.py", line 170, in load_model
    model = AutoModelForCausalLM.from_pretrained(checkpoint, **params)
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2736, in from_pretrained
    ) = cls._load_pretrained_model(
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 3050, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 445, in load_state_dict
    with open(checkpoint_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models\\facebook_opt-6.7b\\pytorch_model-00001-of-00002.bin'
Press any key to continue . . .

for gpt alphca 

Starting the web UI...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 6.1
CUDA SETUP: Detected CUDA version 117
D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:141: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117_nocublaslt.dll...
The following models are available:

1. facebook_opt-6.7b
2. gpt4-x-alpaca-13b-native-4bit-128g
3. vicuna-13b-4bit-128g.safetensors

Which one do you want to load? 1-3

2

Loading gpt4-x-alpaca-13b-native-4bit-128g...
Auto-assiging --gpu-memory 5 for your GPU to try to prevent out-of-memory errors.
You can manually set other values.
Loading checkpoint shards:   0%|                                                                 | 0/6 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 442, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models\\gpt4-x-alpaca-13b-native-4bit-128g\\pytorch_model-00001-of-00006.bin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\text-generation-webui\server.py", line 302, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\text-generation-webui\modules\models.py", line 170, in load_model
    model = AutoModelForCausalLM.from_pretrained(checkpoint, **params)
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2736, in from_pretrained
    ) = cls._load_pretrained_model(
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 3050, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 445, in load_state_dict
    with open(checkpoint_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models\\gpt4-x-alpaca-13b-native-4bit-128g\\pytorch_model-00001-of-00006.bin'
Press any key to continue . . .



for vicuna 
Starting the web UI...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 6.1
CUDA SETUP: Detected CUDA version 117
D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:141: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117_nocublaslt.dll...
The following models are available:

1. facebook_opt-6.7b
2. gpt4-x-alpaca-13b-native-4bit-128g
3. vicuna-13b-4bit-128g.safetensors

Which one do you want to load? 1-3

3

Loading vicuna-13b-4bit-128g.safetensors...
Auto-assiging --gpu-memory 5 for your GPU to try to prevent out-of-memory errors.
You can manually set other values.
Traceback (most recent call last):
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 658, in _get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 745, in _dict_from_json_file
    text = reader.read()
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xee in position 159088: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\text-generation-webui\server.py", line 302, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\text-generation-webui\modules\models.py", line 170, in load_model
    model = AutoModelForCausalLM.from_pretrained(checkpoint, **params)
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 441, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\auto\configuration_auto.py", line 910, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 573, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\Aiimagegeneration\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 661, in _get_config_dict
    raise EnvironmentError(
OSError: It looks like the config file at 'models\vicuna-13b-4bit-128g.safetensors' is not a valid JSON file.
Press any key to continue . . .
```

### System Info

```shell
windows 10
geoforce gtx 1060
32 gb ram
```

**Comment by jllllll** [comment]
What launch arguments did you use? It looks like you didn't fully download all of the model files for the first and third one. The second one looks like you may have used the wrong arguments.

For the second and third one you need to use `--wbits 4 --groupsize 128` to launch them. You can add `--chat` if you want it, but `--auto-devices` won't work with them since they are 4-bit models. For the first one, you don't really need any arguments. Just make sure you have all of the model's files, particularly the config files and the 2 .bin files.

**Comment by springheeledjack66** [comment]
--auto-devices --chat --notebook I used theses, --wbits 4 --groupsize 128 was used as well but some people said it might be the reason why is wasn't recognizing models so I removed them

**Comment by jimi202008** [comment]
I also encountered the same problem, has anyone found a solution?
