### ISSUE TITLE
send_pictures causes crash after loading extensions

### ISSUE THREAD

**Issue by bradharms** [oobabooga/text-generation-webui#1070]
### Describe the bug

Extension appears to load ok, but after all extensions are loaded, an error related to send_pictures occurs and the script fails.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Ran with the following command:

```
python server.py \
  --model "vicuna-13b-GPTQ-4bit-128g" \
  --wbits 4 \
  --groupsize 128 \
  --listen-port 7861 \
  --extensions \
    character_bias \
    llama_prompts \
    sd_pictures_api \
    long_term_memory \
    complex_memory \
;
```

### Logs

```shell
./start-textgen-ui.sh

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: /home/themu/miniconda3/envs/textgen/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/themu/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
Loading vicuna-13b-GPTQ-4bit-128g...
Found the following quantized model: models/vicuna-13b-GPTQ-4bit-128g/vicuna-13b-4bit-128g.safetensors
Loading model ...
/home/themu/miniconda3/envs/textgen/lib/python3.10/site-packages/safetensors/torch.py:99: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
/home/themu/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
/home/themu/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
Done.

Loaded the model in 272.42 seconds.
Loading the extension "character_bias"... Ok.
Loading the extension "send_pictures"... Ok.
Loading the extension "gallery"... Ok.
Loading the extension "llama_prompts"... Ok.
Loading the extension "long_term_memory"...
-----------------------------------------
IMPORTANT LONG TERM MEMORY NOTES TO USER:
-----------------------------------------
Please remember that LTM-stored memories will only be visible to the bot during your NEXT session. This prevents the loaded memory from being flooded with messages from the current conversation which would defeat the original purpose of this module. This can be overridden by pressing 'Force reload memories'
----------
LTM CONFIG
----------
change these values in ltm_config.json
{'ltm_context': {'injection_location': 'BEFORE_NORMAL_CONTEXT',
                 'memory_context_template': "{name2}'s memory log:\n"
                                            '{all_memories}\n'
                                            'During conversations between '
                                            '{name1} and {name2}, {name2} will '
                                            'try to remember the memory '
                                            'described above and naturally '
                                            'integrate it with the '
                                            'conversation.',
                 'memory_template': '{time_difference}, {memory_name} said:\n'
                                    '"{memory_message}"'},
 'ltm_reads': {'max_cosine_distance': 0.6,
               'memory_length_cutoff_in_chars': 1000,
               'num_memories_to_fetch': 2},
 'ltm_writes': {'min_message_length': 100}}
----------
-----------------------------------------
Ok.
Loading the extension "complex_memory"... Ok.
Traceback (most recent call last):
  File "/mnt/f/text-generation-webui/server.py", line 704, in <module>
    create_interface()
  File "/mnt/f/text-generation-webui/server.py", line 682, in create_interface
    extensions_module.create_extensions_block()
  File "/mnt/f/text-generation-webui/modules/extensions.py", line 72, in create_extensions_block
    extension.ui()
  File "/mnt/f/text-generation-webui/extensions/send_pictures/script.py", line 42, in ui
    picture_select.upload(lambda picture, name1, name2: input_hijack.update({"state": True, "value": generate_chat_picture(picture, name1, name2)}), [picture_select, shared.gradio['name1'], shared.gradio['name2']], None)
KeyError: 'name1'
```
```


### System Info

```shell
WSL2/Ubuntu, Windows 11, RTX 3080 Ti
```

**Comment by oobabooga** [comment]
Should be fixed here 

https://github.com/oobabooga/text-generation-webui/commit/80f4eabb2a24c288bd381b368ec7543647534465

**Comment by jackylee1** [comment]
Auto-assiging --gpu-memory 7 for your GPU to try to prevent out-of-memory errors.
You can manually set other values.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 4/4 [00:40<00:00, 10.18s/it]
Loaded the model in 41.39 seconds.
C:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\gradio\helpers.py:642: UserWarning: Unexpected argument. Filling with None.
  warnings.warn("Unexpected argument. Filling with None.")
Traceback (most recent call last):
  File "C:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\gradio\routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "C:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 930, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\gradio\utils.py", line 491, in async_iteration
    return next(iterator)
  File "C:\one-click-installers-oobabooga-windows\text-generation-webui\modules\chat.py", line 229, in cai_chatbot_wrapper
    for history in chatbot_wrapper(text, state):
  File "C:\one-click-installers-oobabooga-windows\text-generation-webui\modules\chat.py", line 131, in chatbot_wrapper
    eos_token = '\n' if state['stop_at_newline'] else None
TypeError: 'NoneType' object is not subscriptable


get this when i send picture

**Comment by ManuXD32** [comment]
The extension doesn't work again:
KeyError: 'name1'

**Comment by valerino** [comment]
found solution: --cai_chat parameter must be used in the command line

`python3 ./server.py --mlock --auto-devices --model_type=llama --model ggml-vicuna-13b-1.1-q4_2.bin --verbose --extension send_pictures --cai-chat`

of course, if the code can be fixed it would be better :)
