### ISSUE TITLE
gallery extension broken?

### ISSUE THREAD

**Issue by bradharms** [oobabooga/text-generation-webui#1071]
### Describe the bug

Error occurs when attempting to load the UI with the gallery extension enabled.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
python server.py \
  --chat \
  --model "vicuna-13b-GPTQ-4bit-128g" \
  --wbits 4 \
  --groupsize 128 \
  --listen-port 7861 \
  --extensions \
    gallery \
    character_bias \
    llama_prompts \
    sd_api_pictures \
    long_term_memory \
;
```

### Logs

```shell
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: /home/themu/miniconda3/envs/textgen/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/themu/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
Loading vicuna-13b-GPTQ-4bit-128g...
Found the following quantized model: models/vicuna-13b-GPTQ-4bit-128g/vicuna-13b-4bit-128g.safetensors
Loading model ...
/home/themu/miniconda3/envs/textgen/lib/python3.10/site-packages/safetensors/torch.py:99: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
/home/themu/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
/home/themu/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
Done.
Loaded the model in 270.44 seconds.
Loading the extension "character_bias"... Ok.
Loading the extension "gallery"... Ok.
Loading the extension "llama_prompts"... Ok.
Loading the extension "long_term_memory"...
-----------------------------------------
IMPORTANT LONG TERM MEMORY NOTES TO USER:
-----------------------------------------
Please remember that LTM-stored memories will only be visible to the bot during your NEXT session. This prevents the loaded memory from being flooded with messages from the current conversation which would defeat the original purpose of this module. This can be overridden by pressing 'Force reload memories'
----------
LTM CONFIG
----------
change these values in ltm_config.json
{'ltm_context': {'injection_location': 'BEFORE_NORMAL_CONTEXT',
                 'memory_context_template': "{name2}'s memory log:\n"
                                            '{all_memories}\n'
                                            'During conversations between '
                                            '{name1} and {name2}, {name2} will '
                                            'try to remember the memory '
                                            'described above and naturally '
                                            'integrate it with the '
                                            'conversation.',
                 'memory_template': '{time_difference}, {memory_name} said:\n'
                                    '"{memory_message}"'},
 'ltm_reads': {'max_cosine_distance': 0.6,
               'memory_length_cutoff_in_chars': 1000,
               'num_memories_to_fetch': 2},
 'ltm_writes': {'min_message_length': 100}}
----------
-----------------------------------------
Ok.
Loading the extension "complex_memory"... Ok.
Traceback (most recent call last):
  File "/mnt/f/text-generation-webui/server.py", line 704, in <module>
    create_interface()
  File "/mnt/f/text-generation-webui/server.py", line 682, in create_interface
    extensions_module.create_extensions_block()
  File "/mnt/f/text-generation-webui/modules/extensions.py", line 72, in create_extensions_block
    extension.ui()
  File "/mnt/f/text-generation-webui/extensions/gallery/script.py", line 96, in ui
    gallery.select(select_character, None, gradio['character_menu'])
KeyError: 'character_menu'
```
```


### System Info

```shell
WSL2/Ubuntu, Windows 11, RTX 3080 Ti
```

**Comment by GalDayan** [comment]
👍 Same here. Specs: Mac M1

**Comment by tdtrumble** [comment]
I have this same error on Linux. I also get this if I disable gallery and add complex memory, although with a different trace.

**Comment by ms-KuroNeko** [comment]
I'm a Chinese, my English is not very well, and the following English parts are automatically generated by Bing Translator
【方便外国兄逮理解的英文都是机翻，你们不用认真看】

这个其实是作者没有写清楚导致的锅，你必须先使用 --chat 参数启动webui，进入对话模式
进入这个模式后 gallery 这个扩展会自动加载

This is actually a problem caused by the author not writing clearly, you must first use the --chat parameter to start WebUI and enter the dialogue mode
After entering this mode, the gallery extension will be loaded automatically

---------------------------

启动之后你们可能无法打开webui，会出现如下错误

> module pil.image has no attribute resampling

这是你们没有正确安装 pillow 或者版本低于10，你们需要

> pip install pillow --upgrade



After booting, you may not be able to open WebUI, and the following error will appear

> module pil.image has no attribute resampling

This is because you guys didn't install Pillow correctly or the version is lower than 10, which you need

> pip install pillow --upgrade

**Comment by mashb1t** [comment]
same for me, Windows 10 + latest Docker version
