### ISSUE TITLE
There is enough VRAM, but the model load is failing (CUDA out of memory)

### ISSUE THREAD

**Issue by stuxnet147** [oobabooga/text-generation-webui#1081]
I am experiencing a issues with text-generation-webui when using it with the following hardware:
```
CPU: Xeon Silver 4216 x 2ea
RAM: 383GB
GPU: RTX 3090 x 4ea
```
[Model]
```
llama 65b hf
```
[Software Env]
```
Python 3.9.16
Ubuntu 22.04
oobabooga/text-generation-webui
```
[Output]
```
(textgen) server@server:/mnt/sda1/one-click-installers-oobabooga-windows/one-click-installers-oobabooga-windows/text-generation-webui$ python server.py --model-dir /mnt/sda1/one-click-installers-oobabooga-windows/one-click-installers-oobabooga-windows/text-generation-webui/models --share --load-in-8bit --gpu-memory 24000MiB 24000MiB 24000MiB 24000MiB

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/home/server/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: /home/server/anaconda3/envs/textgen did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11.7/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/server/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
The following models are available:

1. alpaca-native
2. facebook_galactica-120b
3. llama-30b-hf
4. llama-65b-hf
5. llama_cpp_65b
6. opt-1.3b
7. Salesforce_codegen-16B-multi
8. TianXxx_llama-65b-int4

Which one do you want to load? 1-8

4

Loading llama-65b-hf...
Loading checkpoint shards:  35%|███████████████████▎                                    | 28/81 [02:25<04:34,  5.18s/it]
Traceback (most recent call last):
  File "/mnt/sda1/one-click-installers-oobabooga-windows/one-click-installers-oobabooga-windows/text-generation-webui/server.py", line 302, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/mnt/sda1/one-click-installers-oobabooga-windows/one-click-installers-oobabooga-windows/text-generation-webui/modules/models.py", line 170, in load_model
    model = AutoModelForCausalLM.from_pretrained(checkpoint, **params)
  File "/home/server/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "/home/server/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2736, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/server/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3064, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/home/server/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/modeling_utils.py", line 700, in _load_state_dict_into_meta_model
    set_module_8bit_tensor_to_device(model, param_name, param_device, value=param)
  File "/home/server/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/utils/bitsandbytes.py", line 70, in set_module_8bit_tensor_to_device
    new_value = bnb.nn.Int8Params(new_value, requires_grad=False, has_fp16_weights=has_fp16_weights).to(device)
  File "/home/server/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 196, in to
    return self.cuda(device)
  File "/home/server/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 160, in cuda
    CB, CBt, SCB, SCBt, coo_tensorB = bnb.functional.double_quant(B)
  File "/home/server/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/functional.py", line 1623, in double_quant
    out_row = torch.zeros(A.shape, device=device, dtype=torch.int8)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 172.00 MiB (GPU 0; 23.70 GiB total capacity; 22.04 GiB already allocated; 68.31 MiB free; 22.94 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
[Command]
```
python server.py --model-dir /mnt/sda1/one-click-installers-oobabooga-windows/one-click-installers-oobabooga-windows/text-generation-webui/models --share --load-in-8bit --gpu-memory 24000MiB 24000MiB 24000MiB 24000MiB
```

**Comment by MarlinMr** [comment]
Seems like you are telling server.py that there is 24000MiB of _free VRAM just for the model_. There might be some other stuff in the VRAM, so the VRAM is full before the entire model is loaded into it. 

You only need about 65GB, why are you allocating 24*4 = 96GB?

Instead try giving it 18000MiB on each GPU.

**Comment by practicaldreamer** [comment]
I know what your problem is and how to fix it. I can't tell you why though. 

I'm running a dual gpu setup 2x3090. splitting gpu-memory equally among your GPUs would make logical sense but it doesn't work like that for some reason...

The best balance I've found through painstakingly tweaking is `--gpu-memory 15 19` for 65b-int4

I can't tell you the precise numbers because I don't have 4 GPUS but my general advice is to lower the VRAM allocated to your first GPU because it always throws everything at it till it crashes.

Watch your VRAM usage with `nvidia-smi dmon -s pmc` or windows equivalent. You'll see what I'm talking about.
