### ISSUE TITLE
Config file is not a valid Json file

### ISSUE THREAD

**Issue by Jake36921** [oobabooga/text-generation-webui#1087]
### Describe the bug

Arguments on Start Webui: python server.py --cai-chat --model-dir models/alpaca-13b-lora-int4 --model alpaca-13b-4bit-128g.safetensors --cpu

Invalid Json file

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Tried to load OPT-13B-Erebus-4bit-128g  using the same arguments, it didn't work. tried loading a different model (alpaca-13b-lora-int4) still didn't work.

### Logs

```shell
Starting the web UI...
Warning: --cai-chat is deprecated. Use --chat instead.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: Loading binary E:\Games\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll...
E:\Games\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading alpaca-13b-4bit-128g.safetensors...
Traceback (most recent call last):
  File "E:\Games\oobabooga-windows\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 658, in _get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "E:\Games\oobabooga-windows\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 745, in _dict_from_json_file
    text = reader.read()
  File "E:\Games\oobabooga-windows\installer_files\env\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf7 in position 159083: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Games\oobabooga-windows\text-generation-webui\server.py", line 351, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "E:\Games\oobabooga-windows\text-generation-webui\modules\models.py", line 171, in load_model
    model = AutoModelForCausalLM.from_pretrained(checkpoint, **params)
  File "E:\Games\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 441, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "E:\Games\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\auto\configuration_auto.py", line 913, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "E:\Games\oobabooga-windows\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 573, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "E:\Games\oobabooga-windows\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 661, in _get_config_dict
    raise EnvironmentError(
OSError: It looks like the config file at 'models\alpaca-13b-lora-int4\alpaca-13b-4bit-128g.safetensors' is not a valid JSON file.
Press any key to continue . . .
```

### System Info

```shell
OS Name	Microsoft Windows 11 Pro
Version	10.0.22621 Build 22621
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	JAKE
System Manufacturer	ASUS
System Model	System Product Name
System Type	x64-based PC
System SKU	SKU
Processor	AMD Ryzen 5 5600G with Radeon Graphics, 3901 Mhz, 6 Core(s), 12 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. 2006, 20/03/2021
SMBIOS Version	3.3
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	ASUSTeK COMPUTER INC.
BaseBoard Product	PRIME A520M-K
BaseBoard Version	Rev X.0x
Platform Role	Desktop
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.22621.1413"
User Name	Jake
Time Zone	Malay Peninsula Standard Time
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.3 GB
Available Physical Memory	11.2 GB
Total Virtual Memory	30.6 GB
Available Virtual Memory	16.0 GB
Page File Space	15.3 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Not enabled
Windows Defender Application Control policy	Enforced
Windows Defender Application Control user mode policy	Off
Device Encryption Support	Elevation Required to View
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

Gpu: igpu/AMD Radeon(TM) Graphics
```

**Comment by himansharma21** [comment]
Try running with `python server.py --wbits 4 --groupsize 128 --cpu`, and then select a model. 

4bit models need `--wbits 4` and those models also need `--groupsize 128` it seems.
