### ISSUE TITLE
CUDA out of memory [NVIDIA GeForce RTX 3080 Laptop GPU]

### ISSUE THREAD

**Issue by turkunov** [oobabooga/text-generation-webui#1092]
### Describe the bug

After downloading an alpaca-gpt4 model from https://huggingface.co/anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g I was unable to generate prompts of any lengths or tokens. Whenever I type as simple of a message as "hello", the program thinks for ~10 seconds, throws an error and removes the prompt from chat history. 

I have researched the issue and tried the following:
* Setting the limit of `--gpu-memory` to 7GB (wrote in bytes)
* Scaling down and up both `maximum prompt size in tokens` and `max_new_tokens`
* Experimenting with `--pre_layers` and setting values in range of 10 to 20
* Placing `--auto-devices` with and without memory restriction flags

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Replaced the command in "start-webui.bat" to: `call python server.py --auto-devices --chat --wbits 4 --groupsize 128
`

Downloaded model name from hugginface repo: 
`gpt-x-alpaca-13b-native-4bit-128g-cuda.pt`

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\user\Downloads\oobabooga-windows\text-generation-webui\modules\callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "C:\Users\user\Downloads\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 245, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Users\user\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\user\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1485, in generate
    return self.sample(
  File "C:\Users\user\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 2524, in sample
    outputs = self(
  File "C:\Users\user\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "C:\Users\user\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 577, in forward
    layer_outputs = decoder_layer(
  File "C:\Users\user\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "C:\Users\user\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 243, in forward
    attn_output = self.o_proj(attn_output)
  File "C:\Users\user\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\Downloads\oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 420, in forward
    x = x.float()
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 8.00 GiB total capacity; 7.07 GiB already allocated; 0 bytes free; 7.31 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Output generated in 4.53 seconds (0.00 tokens/s, 0 tokens, context 44, seed 538172630)
```

### System Info

```shell
OS: Windows 10 x64 (10.0, Build 19045)
GPU: NVIDIA GeForce RTX 3080 Laptop GPU
```

**Comment by bloodsign** [comment]
You might need more than 8GB VRAM to run this particular model. Not 100% sure but it works fine on my RTX 3060 12GB GPU

**Comment by ADM8** [comment]
I also have this issue and would like to know if there is a fix.

**Comment by JeroenAdam** [comment]
That should work with the 7b model, maybe also with this model 3-bit quantized (not seen it done yet)

**Comment by turkunov** [comment]
Anyways, for anyone still wondering, the model has been indeed too big for the machine, however it at least started generating tokens when adding the following tags to the line where `server.py` is being run in "start-webui.bat":
* `--no-cache`
* `--threads *number of cores on your PC*`
* removing `auto-devices` and replacing it with `--gpu-memory *memory in bytes*` (GPU VRAM memory in GB can be checked through `dxdiag` by pressing Win+R on Windows)
* `--load-in-8bit`

What may be also optimal tags to add:
* `--compress-weight` 
* `--pre_layer`

**Comment by nurtuganmc** [comment]
I have moblie RTX 3080 and in start-webui.bat i wrote gpu memory in bytes 8421113856. is it correct?
