### ISSUE TITLE
API is broken

### ISSUE THREAD

**Issue by Asais10** [oobabooga/text-generation-webui#1094]
### Describe the bug

API usage breaks every time a new parameter is added to the request body. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Attempting to use --extensions api leads to no responses. 

### Logs

```shell
Traceback (most recent call last):                                                                                        File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\gradio\routes.py", line 393, in run_predict                                                                                                                        output = await app.get_blocks().process_api(                                                                          File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1108, in process_api                                                                                                                       result = await self.call_function(                                                                                    File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 929, in call_function                                                                                                                      prediction = await anyio.to_thread.run_sync(                                                                          File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync                                                                                                                          return await get_asynclib().run_sync_in_worker_thread(                                                                File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread                                                                                               return await future                                                                                                   File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run                                                                                                                     result = context.run(func, *args)                                                                                     File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\gradio\utils.py", line 490, in async_iteration                                                                                                                     return next(iterator)                                                                                                 File "C:\Program Files\oobabooga-windows\text-generation-webui\modules\api.py", line 28, in generate_reply_wrapper        for i in generate_reply(params[0], generate_params):                                                                  File "C:\Program Files\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 175, in generate_reply                                                                                                                           input_ids = encode(question, add_bos_token=state['add_bos_token'], truncation_length=get_max_prompt_length(state))    File "C:\Program Files\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 19, in get_max_prompt_length                                                                                                                     max_length = state['truncation_length'] - state['max_new_tokens']                                                   KeyError: 'truncation_length'
```

### System Info

```shell
Windows 10
Nvidia Geforce RTX 2080ti
```

**Comment by volvalder** [comment]
for me as well here is an error `Traceback (most recent call last):
  File "C:\Users\wutaw\OneDrive\Desktop\T\installer_files\env\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\wutaw\OneDrive\Desktop\T\installer_files\env\lib\site-packages\gradio\blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "C:\Users\wutaw\OneDrive\Desktop\T\installer_files\env\lib\site-packages\gradio\blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\wutaw\OneDrive\Desktop\T\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\wutaw\OneDrive\Desktop\T\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\wutaw\OneDrive\Desktop\T\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\wutaw\OneDrive\Desktop\T\installer_files\env\lib\site-packages\gradio\utils.py", line 490, in async_iteration
    return next(iterator)
  File "C:\Users\wutaw\OneDrive\Desktop\T\text-generation-webui\modules\api.py", line 25, in generate_reply_wrapper
    params = json.loads(string)
  File "C:\Users\wutaw\OneDrive\Desktop\T\installer_files\env\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\wutaw\OneDrive\Desktop\T\installer_files\env\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\wutaw\OneDrive\Desktop\T\installer_files\env\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by zencyon** [comment]
i think the payload method just changed a little, try updating the request to something like this:

def get_raw_reply(prompt, params):

    payload = json.dumps([prompt, params])

    response = requests.post(f"http://{ai_server_ip}:{ai_server_port}/run/textgen", json={
            "data": [payload]}).json()

    reply = ""
    if "data" in response.keys():
        reply = response["data"][0]

**Comment by Asais10** [comment]
Rolling back to yesterday's versionand using SillyTavern 1.3.3 works

**Comment by zencyon** [comment]
latest pull also gives me an error:

  File "/home/****/text-generation-webui/modules/api.py", line 28, in generate_reply_wrapper
    for i in generate_reply(params[0], generate_params):
  File "/home/****/text-generation-webui/modules/text_generation.py", line 175, in generate_reply
    input_ids = encode(question, add_bos_token=state['add_bos_token'], truncation_length=get_max_prompt_length(state))
KeyError: 'add_bos_token'

**Comment by varch1tect** [comment]
Just started using ooba today. Couldn't figure out the API. After enabling --extensions API, the console shows me:

`Starting KoboldAI compatible api at http://127.0.0.1:5000/api`

Meanwhile the 'Use via API' link at the bottom of the page shows:

`To expose an API endpoint of your app in this page, set the api_name parameter of the event listener.`

per py-examply.py, trying to call:

`http://127.0.0.1:7860/run/textgen`

response is: 

`{
    "detail": "Not Found"
}`

the endpoint: `http://127.0.0.1:7860/api/v1/generate`

with the body: `{
  "prompt": "tell me a joke"
}`

does actually get a response:

`{
    "results": [
        {
            "text": "re's a joke for you: Why did the tomato turn red? Because it saw the salad dressing!"
        }
    ]
}`

...but as you can first few characters appear cut off.

What am I missing/doing wrong? hopefully its not the model, the UI Chat appears just fine. Thanks!

**Comment by MichaelSmithAI** [comment]
Running into the same issue as [varch1tect] over here as well

**Comment by Reezlaw** [comment]
I think there is a lot of confusion between the built-in gradio api that listens on 7860 and the api extension that listen to 5000, they are mentioned alternatively at random, the examples use the built-in version, they have different endpoints and it's all very confusing

**Comment by mikolodz** [comment]
I'm getting a similar problem using the built-in API and the Api tester modal that shows after clicking on the "Use via API" in the webui footer. Api is enabled in the settings:

![WebUI settings](https://user-images.githubusercontent.com/8095324/232313340-e7e9a72d-52c7-4abf-8bf4-642611ad2328.png)

Error message I'm getting from the _server.py_:
```
File "/home/administrator/anaconda3/envs/gptq/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/administrator/anaconda3/envs/gptq/lib/python3.9/site-packages/gradio/utils.py", line 491, in async_iteration
    return next(iterator)
  File "/home/administrator/git/text-generation-webui/modules/api.py", line 28, in generate_reply_wrapper
    params = json.loads(string)
  File "/home/administrator/anaconda3/envs/gptq/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/administrator/anaconda3/envs/gptq/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/administrator/anaconda3/envs/gptq/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

![Gradio API error](https://user-images.githubusercontent.com/8095324/232313102-3109cd15-273b-409a-9d07-4c69d0e84ac8.png)

The same happens if I send the request using requests from python script.

**Comment by kireita** [comment]
Hey guys, i am getting the same error here

https://user-images.githubusercontent.com/25864917/232461693-7d34d049-cf14-45d0-bf17-80acab5aa54e.mp4

**Comment by kireita** [comment]
Never mind im stupid, i just saw the api example and did not place the -listen --no-stream flags... my bad

**Comment by TheLustriVA** [comment]
I just started getting `#### { error: 'This app has no endpoint /api/textgen/.' }` yesterday if I plug into the 7*** port and flat-out unable to connect if I try 5000/api.

**Comment by oobabooga** [comment]
Closing as this issue refers to an API that has been replaced

**Comment by xpgx1** [comment]
I fail to understand how this issue can be resolved - I cannot use my current ooba installation as SillyTavern, on all versions or updates, cannot communicate with the API anymore.  The UI reports an unknown issue, the CLI reports the mentioned AttributeError. How is this fixable?

For now I am FORCED to roll back to a previous build of the branch. Call me ignorant or stupid =) - But i don't get how to resolve this seemingly trivial problem.
