### ISSUE TITLE
download_model.py has no permissions at all

### ISSUE THREAD

**Issue by MushMello** [oobabooga/text-generation-webui#1102]
### Describe the bug

If I try to download anything with it, I get a PermissionError. For example with gptj-6B:

```
File "/home/dipper/conda3/envs/textgen/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: 'models/EleutherAI_gpt-j-6B'
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

use "python download-model.py organization/model"

### Logs

```shell
(textgen) dipper@MeinPCXDROFLLOL:/text-generation-webui$ python download-model.py EleutherAI/gpt-j-6B --text-only
Traceback (most recent call last):
  File "/text-generation-webui/download-model.py", line 270, in <module>
    download_model_files(model, branch, links, sha256, output_folder, threads=args.threads)
  File "/text-generation-webui/download-model.py", line 193, in download_model_files
    output_folder.mkdir()
  File "/home/dipper/conda3/envs/textgen/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: 'models/EleutherAI_gpt-j-6B'
```

### System Info

```shell
OS: Win11
GPU: RTX 3090
CPU: i7 12700KF
```

**Comment by MushMello** [comment]
If I put the org/model in parentheses (_python download-model.py "EleutherAI/gpt-j-6B" --text-only_) it gives me this:

Traceback (most recent call last):
  File "/text-generation-webui/download-model.py", line 270, in <module>
    download_model_files(model, branch, links, sha256, output_folder, threads=args.threads)
  File "/text-generation-webui/download-model.py", line 194, in download_model_files
    with open(output_folder / 'huggingface-metadata.txt', 'w') as f:
PermissionError: [Errno 13] Permission denied: 'models/EleutherAI_gpt-j-6B/huggingface-metadata.txt'

**Comment by caterpillarpants** [comment]
First, thanks so much to mr. gooba for making this lovely program. It truly brings the software to the people. Unfortunately, I think I have a similar problem to mr. mushmello.

ISSUE:
When I use the gui to "download custom model or LoRA" or use "bash downloadmodel.sh" I get something like this:
Then type the name of your desired Hugging Face model in the format organization/name.

EXAMPLE:
Input> rahular/itihasa
Traceback (most recent call last):
  File "/home/ana/oobabooga/text-generation-webui/download-model.py", line 267, in <module>
    links, sha256, is_lora = get_download_links_from_huggingface(model, branch, text_only=args.text_only)
  File "/home/ana/oobabooga/text-generation-webui/download-model.py", line 102, in get_download_links_from_huggingface
    r.raise_for_status()
  File "/home/ana/oobabooga/installer_files/env/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/rahular/itihasa/tree/main

TO REPRODUCE:
bash download-model.sh

choose "L" for "manually choose a hugging face model"
type in: "rahular/itihasa"

Or use gui.
