### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by LeyendaV** [oobabooga/text-generation-webui#1105]
### Describe the bug

I've searched for existing issues similar to this, and found 2. One still without a solution that's similar yet different enough to mine, and the other apparently closed, but what worked for that person doesn't seem to be working for me.

My problem is that I can't even open the web UI to try to change the settings from inside, and honestly have not much knowledge to try to modify the component files without asking first what to do.
I'm leaving down here a full copy of what appears on my console when launching _start-webui.bat_. You'll see I have 3 models, the same problem occurs regardless of which one I choose.

If it means something, I can perfectly use Stable Diffusion without any kind of problem whatsoever.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Simply attempting to launch _start-webui.bat_ triggers the problem.

### Logs

```shell
Starting the web UI...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: D:\IA\oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary D:\IA\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
The following models are available:

1. facebook_opt-6.7b
2. gpt4-x-alpaca-13b-native-4bit-128g
3. vicuna-13b-GPTQ-4bit-128g

Which one do you want to load? 1-3

3

Loading vicuna-13b-GPTQ-4bit-128g...
Found the following quantized model: models\vicuna-13b-GPTQ-4bit-128g\vicuna-13b-4bit-128g.safetensors
Loading model ...
D:\IA\oobabooga-windows\installer_files\env\lib\site-packages\safetensors\torch.py:99: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
D:\IA\oobabooga-windows\installer_files\env\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
D:\IA\oobabooga-windows\installer_files\env\lib\site-packages\torch\storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
Done.
Traceback (most recent call last):
  File "D:\IA\oobabooga-windows\text-generation-webui\server.py", line 350, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\IA\oobabooga-windows\text-generation-webui\modules\models.py", line 103, in load_model
    model = load_quantized(model_name)
  File "D:\IA\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 154, in load_quantized
    model = model.to(torch.device('cuda:0'))
  File "D:\IA\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 1896, in to
    return super().to(*args, **kwargs)
  File "D:\IA\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "D:\IA\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "D:\IA\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "D:\IA\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "D:\IA\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 844, in _apply
    self._buffers[key] = fn(buf)
  File "D:\IA\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 14.00 MiB (GPU 0; 6.00 GiB total capacity; 5.18 GiB already allocated; 0 bytes free; 5.35 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Press a key to continue . . .
```

### System Info

```shell
Windows 11 22H2 22621.1555
12th Gen Intel Core i7-12650H 2.30Ghz
NVIDIA GeForce RTX 3060 GDDR6 6GB
16GB DDR5 4800Mhz
Crucial P5 Plus PCIe 4.0 NMVe 2TB
```

**Comment by himansharma21** [comment]
The issue might just be that your GPU does not have the VRAM to load the models. I am not sure about about the rest but vicuna-13b-4b-128 takes up almost exactly 6gb on my GPU. 

Try adding `--pre_layer 12` to your params when running `server.py` to offload some layers to the CPU and RAM. Note higher number means more layers to your GPU. Keep an eye on the GPU VRAM graph in task manager.

**Comment by LeyendaV** [comment]
> The issue might just be that your GPU does not have the VRAM to load the models. I am not sure about about the rest but vicuna-13b-4b-128 takes up almost exactly 6gb on my GPU.
> 
> Try adding `--pre_layer 12` to your params when running `server.py` to offload some layers to the CPU and RAM. Note higher number means more layers to your GPU. Keep an eye on the GPU VRAM graph in task manager.

This seems to be the solution. I tried with a lower number first, but then moved up to 12 and looks like it works the same regardless of the value (as long as it's not an insane number). Basically, most of the workforce was moved to the RAM.

Thanks!

**Comment by kaiokenmaster218** [comment]
I ran mine with `--pre_layer 1`  (I have 8 gigs vram) and it says:

 `CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 8.00 GiB total capacity; 7.08 GiB already allocated; 0 bytes free; 7.32 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Output generated in 3.84 seconds (0.00 tokens/s, 0 tokens, context 44, seed 181863331)`
