### ISSUE TITLE
Error with OPT-13B-4Bit model: "expected scalar type Float but found Half"

### ISSUE THREAD

**Issue by Sekoya78** [oobabooga/text-generation-webui#1116]
### Describe the bug

I've been trying to load the following 4bit models which I found here : [https://huggingface.co/notstoic](https://huggingface.co/notstoic)
- OPT-13B-Nerybus-Mix-4bit-128g
- OPT-13B-Erebus-4bit-128g 

They load correctly, but when asking the model to respond, I'm hit with a **RuntimeError: expected scalar type Float but found Half**

I found another issue #519 with the same error, but figuring out if it's actually related is beyond me (sorry).

EDIT: It seems that loading those models with "--model_type gptj" works (see thread). It's slower than it would normally be, though (and, at least once, I ended up with text generation going on _literally_ forever). Not specifying the model_type at all will also cause the issue.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

- Install model
- Launch with the correct parameters (wbits 4, groupsize 128, model_type opt)
- It loads successfully
- Talk to the "bot" get error (and previous message being yeeted in the UI)

### Logs

```shell
Traceback (most recent call last):
  File "G:\Oobabooga-update\text-generation-webui\modules\text_generation.py", line 224, in generate_reply
    output = shared.model.generate(**generate_params)[0]
  File "G:\Oobabooga-update\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\Oobabooga-update\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1485, in generate
    return self.sample(
  File "G:\Oobabooga-update\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 2524, in sample
    outputs = self(
  File "G:\Oobabooga-update\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\Oobabooga-update\installer_files\env\lib\site-packages\transformers\models\opt\modeling_opt.py", line 938, in forward
    outputs = self.model.decoder(
  File "G:\Oobabooga-update\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\Oobabooga-update\installer_files\env\lib\site-packages\transformers\models\opt\modeling_opt.py", line 704, in forward
    layer_outputs = decoder_layer(
  File "G:\Oobabooga-update\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\Oobabooga-update\installer_files\env\lib\site-packages\transformers\models\opt\modeling_opt.py", line 350, in forward
    hidden_states = self.final_layer_norm(hidden_states)
  File "G:\Oobabooga-update\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\Oobabooga-update\installer_files\env\lib\site-packages\torch\nn\modules\normalization.py", line 190, in forward
    return F.layer_norm(
  File "G:\Oobabooga-update\installer_files\env\lib\site-packages\torch\nn\functional.py", line 2515, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: expected scalar type Float but found Half
Output generated in 0.27 seconds (0.00 tokens/s, 0 tokens, context 251, seed 50685968)
```

### System Info

```shell
Windows 11
Nvidia RTX3060 (12GB)
16GB RAM
Oobabooga up to date at the moment of this post
```

**Comment by peterAIML** [comment]
I am getting the same error when using this model https://huggingface.co/mayaeary/

pygmalion-6b-4bit-128g

**Comment by Slug-Cat** [comment]
I also get this error when trying to use the same models.

**Comment by himansharma21** [comment]
Are you running with `--cpu` by any chance?

**Comment by Nondzu** [comment]
I've same error with TheBloke/galpaca-30B-GPTQ-4bit-128g, 
@himansharma21 on cpu I see error `RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'`

**Comment by Sekoya78** [comment]
> Are you running with `--cpu` by any chance?

I'm not using --cpu. It's running on the GPU. For reference, I can work with the Llama and Alpaca 4bit/g128 models without any issue.

**Comment by Sekoya78** [comment]
> this issue happens because base model is probably set as float16, like facebook/galactica-30b , but loading over GPTQ require float32 I guess. Edit: link to galactica model data type info [paperswithcode/galai#37 (comment)](https://github.com/paperswithcode/galai/issues/37#issuecomment-1323929437)

Dunno if it's the same thing, but the non working OPT-Erebus model's config file has the info "torch_dtype" set to "float16", however pyg (who is working just fine) also has it to float16. 

Sorry at this point, it's way beyond my qualifications in the matter :(

**Comment by Nondzu** [comment]
@Sekoya78 I'll check Pygmalion-6B-dev in free time, can you write your run command for the  Pygmalion-6B-dev ?

**Comment by Nondzu** [comment]
@Sekoya78 that's so fun because when I run mayaeary/pygmalion-6b_dev-4bit-128g model I still see `RuntimeError: expected scalar type Float but found Half`

**Comment by Sekoya78** [comment]
Ok, this is getting crazy if we're getting inconsistent results on the same models.

**Comment by Nondzu** [comment]
awesome, maybe we have different version of text-generation-webui and/or, my webui is 6e19ae4b2f58853ad44adfe8a19672598c62471c

**Comment by Sekoya78** [comment]
(updated to your version to make sure things are equal)

Wait! There's something funky going on with the model_type parameter. I'm just going to reference the new UI tab for the model instead of command line parameters: 

wbits stays at 4, group at 128.

Loading the OPT-Erebus 13B (4b) (which is supposedly OPT as least given the name) but if I play with the model_type params:
- opt : Crash on prompt.
- none: Crash on prompt.
- gtpj: It's slow. Incredibly goddamn slow. But it actually respond to me.

**Comment by kyuu840** [comment]
Well ninja'd :D
Indeed, something seems off. I noticed my VRAM usage is zero while idle, and when I start generating it quickly spikes. I get really fast tokens/s while there's still VRAM, but 2 or 3 seconds later, VRAM gets to around 90% and then everything starts slowing down, until generation is much slower than even the original 8-bit model.
```
Windows 11 (WSL2)
NVIDIA RTX 4090 (24 GB)
64 GB RAM
6e19ae4b2f58853ad44adfe8a19672598c62471c
torch 2.0.0, cuda 117
```

**Comment by Sekoya78** [comment]
Same cuda/torch. Being on a RTX3060 (12gb), it's more like 0.3-0.4 token/sec. GPU VRAM is already close to max during generation, but it barely moves around (i'm not using beam search, but you might). GPU usage, however, yeah it's maxxed nearly all the time during gen, but that's pretty normal. 

Weirdly enough, other 13B-4bit models I tried were a LOT faster, They weren't loaded with the wrong model_type to get them working, though.

**Comment by ChristianCCastro** [comment]
And attention, but I better not make web pages or software or pace codes or
invoices or rows or to transform. b nor the pages that mkt was going to
launch. travel agency. nor hello word I do not receive money and what is
going to happen that they are going to fire me from my job but thanks
  a question I can help but Ami I can not. I wanted to ask if you know of a
robot that operates and does everything in the operation of crypto btc
coins I find that in Google does not let me download or update. and. and
everyone who knows me. they tell me. stop that Christian. and I believe
that it is true. Maybe it's my pure imagination.

**Comment by artemcrum** [comment]
Same issue with Nerybus-13b-4bit. Doesn't work with setting model type to OPT, and works SLOWLY with model type set to GPTJ.

**Comment by Sekoya78** [comment]
> not specifying the model type (removing --model_type) on startup seems to fix the problem for me with https://huggingface.co/mayaeary/pygmalion-6b-4bit-128g

You used "--model_type opt" for pyg? It's a gptj one. You didn't have a bug to begin with. At least check their config file before hijacking someone's else bug report. Or idk, try without the option at all...

On a side note, it feels like OPT models (at least out of the 5 I tried) compress really badly compared to other models, it's already noticeable with 8bit, but with 4bit it's obvious. Feels like running a OPT-13B 4bit on 12GB is mostly an exercise in frustration.

**Comment by artemcrum** [comment]
I've managed to run Nerybus-13B-4bit in KoboldAI environment, but it generates out of the context nonsense text. However in webui it generates pretty good replies (but very slow and in GPT-J mode only).

**Comment by doodooextinction** [comment]
I’m having the same issue with these models. I haven’t tried the base opt 4bit, so I can’t speak on whether it’s a problem loading opt or if it are these two models specifically. 

Also, does anyone know if there is a hugging face alternative/competitor site? I remember finding a link somewhere, but I closed the tab and forgot to save it. Hugging Face is great, just curious to known if there are others.

**Comment by Sekoya78** [comment]
Found the issue with the specific model, the cache is not activated in the config file for some reason, causing generation to be very slow. To fix, go in the model folder, edit config.json, set "use_cache" to true.

I have no idea if it causes issues in the quality of the text long term, but at least I moved from 0.3tk/s to the 2tk/s I'd usually get with said model. 

It's still incorrectly detected, but at least it's working at its normal speed.

**Comment by HorrySheet** [comment]
> Loading the OPT-Erebus 13B (4b) (which is supposedly OPT as least given the name) but if I play with the model_type params:


This prompted me to just try and restart the UI after changing the Model type and it actually started responding again. So maybe when you change model_type params apply changes and restart UI?    I dont really know much about what I'm doing here and it coulda been a fluke.. so keep that in mind. But worth noting I guess..

**Comment by Sekoya78** [comment]
> Is there any news about being able to use it in OPT mode? Because Erebus and Nerybus are currently unusable in GPTJ mode, because they are very slow. :(

Look at my post literally two messages above yours.

**Comment by mykeehu** [comment]
I couldn't find such a parameter in the config, so I added it and will see if it really helps. Thank you very much!

**Comment by Sekoya78** [comment]
@mykeehu You're welcome. Alternatively, you can redownload those models (or just the config.json file and replace yours) from https://huggingface.co/notstoic/OPT-13B-Erebus-4bit-128g/tree/main

They fixed the issue.

**Comment by mykeehu** [comment]
Thank you, I will try again! :)

**Comment by mbecuwe** [comment]
I am trying to finetune a Vicuna model using text generation webui. I followed these steps for install as shown in the documentation:
`# Install miniconda
curl -sL "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh" > "Miniconda3.sh"
bash Miniconda3.sh

# Create conda env
conda create -n textgen python=3.10.9
conda activate textgen

# Install torch
pip3 install torch torchvision torchaudio

# Install text generation webui
git clone https://github.com/oobabooga/text-generation-webui
cd text-generation-webui
pip install -r requirements.txt

# install nvcc
conda install -c conda-forge cudatoolkit-dev

# Install GPTQ for LLaMa
sudo apt install build-essential
mkdir repositories
cd repositories
git clone https://github.com/oobabooga/GPTQ-for-LLaMa.git -b cuda
cd GPTQ-for-LLaMa
python setup_cuda.py install

# Install monkey patch
cd ..
git clone https://github.com/johnsmith0031/alpaca_lora_4bit
pip install git+https://github.com/sterlind/GPTQ-for-LLaMa.git@eaa9955 # Wont work if I dont revert to this specific commit 

# Download model
cd ..
python download-model.py TheBloke/stable-vicuna-13B-GPTQ

# Run server with monkey patch
python server.py --model TheBloke_stable-vicuna-13B-GPTQ --wbits 4 --groupsize 128 --model_type Llama --share --api --listen --auto-devices --monkey-patch --no-stream`
When trying to generate from prompts in the interface, I get the error:
`Traceback (most recent call last):
  File "/home/jupyter/text-generation-webui/modules/callbacks.py", line 73, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/home/jupyter/text-generation-webui/modules/text_generation.py", line 277, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/jupyter/text-generation-webui/repositories/alpaca_lora_4bit/amp_wrapper.py", line 18, in autocast_generate
    return self.model.non_autocast_generate(*args, **kwargs)
  File "/opt/conda/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1565, in generate
    return self.sample(
  File "/opt/conda/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2612, in sample
    outputs = self(
  File "/opt/conda/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/opt/conda/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 688, in forward
    outputs = self.model(
  File "/opt/conda/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/opt/conda/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 578, in forward
    layer_outputs = decoder_layer(
  File "/opt/conda/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/opt/conda/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 293, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/opt/conda/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/opt/conda/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 197, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "/opt/conda/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/jupyter/text-generation-webui/repositories/alpaca_lora_4bit/autograd_4bit.py", line 133, in forward
    out = matmul4bit_with_backend(x, self.qweight, self.scales,
  File "/home/jupyter/text-generation-webui/repositories/alpaca_lora_4bit/autograd_4bit.py", line 89, in matmul4bit_with_backend
    return mm4b.matmul4bit(x, qweight, scales, qzeros, g_idx)
  File "/home/jupyter/text-generation-webui/repositories/alpaca_lora_4bit/matmul_utils_4bit.py", line 131, in matmul4bit
    output = _matmul4bit_v2(x, qweight, scales, zeros, g_idx)
  File "/home/jupyter/text-generation-webui/repositories/alpaca_lora_4bit/matmul_utils_4bit.py", line 70, in _matmul4bit_v2
    quant_cuda.vecquant4matmul_faster(x, qweight, y, scales, zeros, g_idx, x.shape[-1] // 2)
RuntimeError: expected scalar type Float but found Half`
Text generation will work without the monkey patch but then I cannot finetune the model on my dataset. All my tests are using GPU Nvidia P100. Would be a great help if you could help me fix it !

**Comment by ChristianCCastro** [comment]
El vie, 26 de may de 2023, 15:09, Sekoya78 ***@***.***>
escribió:abierto #1116
<https://github.com/oobabooga/text-generation-webui/issues/1116>
