### ISSUE TITLE
Deleted conda env and re-ran installation as readme indicates, getting package conflicts even after this

### ISSUE THREAD

**Issue by korodarn** [oobabooga/text-generation-webui#1126]
### Describe the bug

I deleted conda environment, re-created, then re-ran commands, and I"m getting errors right from the start.  I h ad previously tried to  change versions around like it says but when I've done that I started getting other packages that required the newer versions, and I don't have quite enough experience to resolve. If this is somehow a configuration issue on my end I'm sorry for the bad report. I thought deleting conda env should clear any config specific to me out of the equation and I figure most users are using the windows installer rather than installing manually in linux. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Attempt to follow readme with a fresh conda textgen environment 

### Logs

```shell
   ~/text-generation-webui    main !1 ?1  conda activate textgen                                                                                                                         ✔  6s   base   01:30:18  
    ~/text-generation-webui    main !1 ?1  pip3 install torch torchvision torchaudio                                                                                                          ✔  textgen   01:30:27  
Requirement already satisfied: torch in /home/korodarn/.local/lib/python3.10/site-packages (1.13.1)
Requirement already satisfied: torchvision in /home/korodarn/.local/lib/python3.10/site-packages (0.14.1)
Requirement already satisfied: torchaudio in /home/korodarn/.local/lib/python3.10/site-packages (0.13.1)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /home/korodarn/.local/lib/python3.10/site-packages (from torch) (11.7.99)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /home/korodarn/.local/lib/python3.10/site-packages (from torch) (11.10.3.66)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /home/korodarn/.local/lib/python3.10/site-packages (from torch) (8.5.0.96)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /home/korodarn/.local/lib/python3.10/site-packages (from torch) (11.7.99)
Requirement already satisfied: typing-extensions in /home/korodarn/.local/lib/python3.10/site-packages (from torch) (4.5.0)
Requirement already satisfied: setuptools in /home/korodarn/.conda/envs/textgen/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch) (65.6.3)
Requirement already satisfied: wheel in /home/korodarn/.conda/envs/textgen/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch) (0.38.4)
Collecting requests
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Requirement already satisfied: numpy in /home/korodarn/.local/lib/python3.10/site-packages (from torchvision) (1.23.5)
Collecting pillow!=8.3.*,>=5.3.0
  Using cached Pillow-9.5.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.4 MB)
Requirement already satisfied: certifi>=2017.4.17 in /home/korodarn/.local/lib/python3.10/site-packages (from requests->torchvision) (2022.12.7)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/korodarn/.local/lib/python3.10/site-packages (from requests->torchvision) (2.1.1)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
Installing collected packages: urllib3, pillow, idna, requests
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lora-diffusion 0.1.6 requires transformers>=4.25.1, which is not installed.
gdown 4.7.1 requires six, which is not installed.
fastchat 0.1.0 requires gradio==3.23, which is not installed.
fastchat 0.1.0 requires tokenizers==0.12.1, which is not installed.
fastchat 0.1.0 requires transformers>=4.26.1, which is not installed.
```
```


### System Info

```shell
Nvidia RTX 3080 11 GB 
Linux 6.2.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 07 Apr 2023 02:10:43 +0000 x86_64 GNU/Linux
```

**Comment by korodarn** [comment]
After closing terminal and re-opening, for some reason it works to re-run commands, but I did have to add 
conda install cudatoolkit

Which was mentioned as part of steps to deal with an issue with bitsandbytes in the readme, but not the issue I had. 

That said, I am getting this now 

```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: /home/korodarn/.conda/envs/textgen/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 113
CUDA SETUP: Loading binary /home/korodarn/.conda/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113.so...
Loading pt4-x-alpaca-13b-native-4bit-128g-cuda...
Traceback (most recent call last):
  File "/mnt/16TB_BTRFS/Projects//text-generation-webui/server.py", line 302, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/mnt/16TB_BTRFS/Projects//text-generation-webui/modules/models.py", line 100, in load_model
    from modules.GPTQ_loader import load_quantized
  File "/mnt/16TB_BTRFS/Projects//text-generation-webui/modules/GPTQ_loader.py", line 14, in <module>
    import llama_inference_offload
ModuleNotFoundError: No module named 'llama_inference_offload'

```

**Comment by korodarn** [comment]
Ok I think that is r
