### ISSUE TITLE
Generates 0 tokens on CPU (4-bit), and no errors

### ISSUE THREAD

**Issue by Lissanro** [oobabooga/text-generation-webui#1132]
### Describe the bug

My intension to run 65B model later, but I am trying 7B to get working first. I have GPTQ-for-LLaMa in repositories. I try to run it like this:
```
CUDA_VISIBLE_DEVICES="" python3 server.py --model llama-7b-4bit-128g --wbits 4 --groupsize 128 --cpu --threads 16
```

It seems to start up successfully:

```
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: Required library version not found: libsbitsandbytes_cpu.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading llama-7b-4bit-128g...
Found the following quantized model: models/llama-7b-4bit-128g/llama-7b-4bit-128g.safetensors
Loading model ...
Done.
Loaded the model in 1.98 seconds.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

But when I click generate, I just get the following output in the console:

```
Output generated in 0.32 seconds (0.00 tokens/s, 0 tokens, context 16, seed 1715768980)
```

So nothing is generated, it just copies as is my input to the output text field. Is this a bug, or did I mis-configured something?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Assuming text-generation-webui repository is already cloned to the current directory and llama-7b-4bit-128g is saved to models directory:

mkdir repositories
cd repositories
git clone https://github.com/qwopqwop200/GPTQ-for-LLaMa
cd GPTQ-for-LLaMa
sudo -H pip install -r requirements.txt
cd ../..
CUDA_VISIBLE_DEVICES="" python3 server.py --model llama-7b-4bit-128g --wbits 4 --groupsize 128 --cpu --threads 16

### Logs

```shell
No errors
```

### System Info

```shell
Ubuntu, 16-core CPU, 128 GiB RAM
```

**Comment by sgsdxzy** [comment]
You are mixing up parameters here:
1. GPTQ-for-LLaMa does not support cpu, so you shouldn't specify `--wbits 4 --groupsize 128`;
2. I suppose you want to use llama.cpp to run it on cpu, you need llama.cpp's ggml format file (like `ggml-model-q4_0.bin`), not `llama-7b-4bit-128g.safetensors`, which is for GPTQ.

**Comment by Lissanro** [comment]
Thanks for quick answer! I will try ggml instead, but does 4-bit ggml have the same quality (perplexity) of output as 4-bit gptq? Or will I need 8-bit ggml to reach similar quality, at the cost of higher RAM usage?

**Comment by Lissanro** [comment]
The convert script does not seem to work, perhaps it does not support GPTQ .safetensors format, I tried it first on a small 7B models, and got the following errors:

```
convert-gptq-to-ggml.py llama-7b-4bit-128g.safetensors tokenizer.model llama-7b-4bit-128g.bin
Traceback (most recent call last):
  File "/home/lissanro/pkgs/llama.cpp/convert-gptq-to-ggml.py", line 21, in <module>
    model = torch.load(fname_model, map_location="cpu")
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'Z'.
```

Maybe some kind of additional step is needed to convert .safetensors to a format the convert-gptq-to-ggml.py script understands.

**Comment by sgsdxzy** [comment]
If you convert the gptq file yourself, there should be other conversion scripts in the llama.cpp repo to convert the weight you got to ggml format.
If you downloaded the gptq file somewhere, usually you can also find the ggml file.

**Comment by mashdragon** [comment]
I'm having this same problem with `--cpu` as the only flag for the model `OpenAssistant/oasst-sft-1-pythia-12b`. No output or error messages about 75% of the time, but if I restart the server and reload the WebUI page, 25% of the time it gives me output correctly.
