### ISSUE TITLE
Webui crashes when changing Interface Mode

### ISSUE THREAD

**Issue by TheTerrasque** [oobabooga/text-generation-webui#1140]
### Describe the bug

When going to "Interface Mode" tab, choosing a different interface mode and clicking "Apply and restart the interface", it crashes because the port is still in use.

Start parameters: python server.py --listen --listen-port=8889
Git commit : fbb448ce4fe71af26fad2aaa67786dd51056c511

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Start WebUI with --listen --listen-port=8889
2. Go to "Interface Mode" tab
3. Choose a different interface mode
4. Click "Apply and restart the interface"

### Logs

```shell
text-generation-webui-text-generation-webui-1  | Traceback (most recent call last):
text-generation-webui-text-generation-webui-1  |   File "/opt/conda/lib/python3.10/site-packages/gradio/networking.py", line 119, in start_server
text-generation-webui-text-generation-webui-1  |     s.bind((LOCALHOST_NAME, server_port))
text-generation-webui-text-generation-webui-1  | OSError: [Errno 98] Address already in use
text-generation-webui-text-generation-webui-1  | 
text-generation-webui-text-generation-webui-1  | During handling of the above exception, another exception occurred:
text-generation-webui-text-generation-webui-1  | 
text-generation-webui-text-generation-webui-1  | Traceback (most recent call last):
text-generation-webui-text-generation-webui-1  |   File "/app/server.py", line 831, in <module>
text-generation-webui-text-generation-webui-1  |     create_interface()
text-generation-webui-text-generation-webui-1  |   File "/app/server.py", line 819, in create_interface
text-generation-webui-text-generation-webui-1  |     shared.gradio['interface'].launch(prevent_thread_lock=True, share=shared.args.share, server_name='0.0.0.0', server_port=shared.args.listen_port, inbrowser=shared.args.auto_launch, auth=auth)
text-generation-webui-text-generation-webui-1  |   File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 1512, in launch
text-generation-webui-text-generation-webui-1  |     server_name, server_port, local_url, app, server = networking.start_server(
text-generation-webui-text-generation-webui-1  |   File "/opt/conda/lib/python3.10/site-packages/gradio/networking.py", line 122, in start_server
text-generation-webui-text-generation-webui-1  |     raise OSError(
text-generation-webui-text-generation-webui-1  | OSError: Port 8889 is in use. If a gradio.Blocks is running on the port, you can close() it or gradio.close_all().
```

### System Info

```shell
This is running via a Docker fork : https://github.com/TheTerrasque/text-generation-webui
```

**Comment by tensiondriven** [comment]
This is a general problem how text-generation-ui is using Gradio.  The gradio interface can't close because something in server.py is holding onto a gradio memory structure.  The fix is to decouple the gradio interface, probably by avoiding passing around Gradio stuff in `shared`.
