### ISSUE TITLE
gr.Blocks 'State' object has no attribute 'input_api_info' After loading the model

### ISSUE THREAD

**Issue by sust4in** [oobabooga/text-generation-webui#1152]
### Describe the bug

I run "docker compose up --build" without changing anything;

this is the .env file that i run with. you can see the model included.
```

# by default the Dockerfile specifies these versions: 3.5;5.0;6.0;6.1;7.0;7.5;8.0;8.6+PTX
# however for me to work i had to specify the exact version for my card ( 2060 ) it was 7.5
# https://developer.nvidia.com/cuda-gpus you can find the version for your card here
TORCH_CUDA_ARCH_LIST=7.5

# these commands worked for me with roughly 4.5GB of vram
CLI_ARGS=--model ggml-vicuna-7b-1.1-q4_1 --load-in-8bit --listen --auto-devices

# the following examples have been tested with the files linked in docs/README_docker.md:
# example running 13b with 4bit/128 groupsize        : CLI_ARGS=--model llama-13b-4bit-128g --wbits 4 --listen --groupsize 128 --pre_layer 25
# example with loading api extension and public share: CLI_ARGS=--model llama-7b-4bit --wbits 4 --listen --auto-devices --no-stream --extensions api --share
# example running 7b with 8bit groupsize             : CLI_ARGS=--model llama-7b --load-in-8bit --listen --auto-devices

# the port the webui binds to on the host
HOST_PORT=7860
# the port the webui binds to inside the container
CONTAINER_PORT=7860

# the port the api binds to on the host
HOST_API_PORT=5000
# the port the api binds to inside the container
CONTAINER_API_PORT=5000

# the version used to install text-generation-webui from
WEBUI_VERSION=HEAD

```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

- docker compose up --build

### Screenshot

![image](https://user-images.githubusercontent.com/9083795/231881404-f9176026-da9c-4ab6-bf15-af8d9460ff3e.png)

### Logs

```shell
D:\textgen-ui\text-generation-webui>docker compose up
[+] Running 1/1
 ✔ Container text-generation-webui-text-generation-webui-1  Recreated                                                                                                                                                                  24.5s
Attaching to text-generation-webui-text-generation-webui-1
text-generation-webui-text-generation-webui-1  |
text-generation-webui-text-generation-webui-1  | ==========
text-generation-webui-text-generation-webui-1  | == CUDA ==
text-generation-webui-text-generation-webui-1  | ==========
text-generation-webui-text-generation-webui-1  |
text-generation-webui-text-generation-webui-1  | CUDA Version 11.8.0
text-generation-webui-text-generation-webui-1  |
text-generation-webui-text-generation-webui-1  | Container image Copyright (c) 2016-2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
text-generation-webui-text-generation-webui-1  |
text-generation-webui-text-generation-webui-1  | This container image and its contents are governed by the NVIDIA Deep Learning Container License.
text-generation-webui-text-generation-webui-1  | By pulling and using the container, you accept the terms and conditions of this license:
text-generation-webui-text-generation-webui-1  | https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
text-generation-webui-text-generation-webui-1  |
text-generation-webui-text-generation-webui-1  | A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.
text-generation-webui-text-generation-webui-1  |
text-generation-webui-text-generation-webui-1  | Loading ggml-vicuna-7b-1.1-q4_1...
text-generation-webui-text-generation-webui-1  | llama.cpp weights detected: models/ggml-vicuna-7b-1.1-q4_1/ggml-vicuna-7b-1.1-q4_1.bin
text-generation-webui-text-generation-webui-1  |
text-generation-webui-text-generation-webui-1  | llama.cpp: loading model from models/ggml-vicuna-7b-1.1-q4_1/ggml-vicuna-7b-1.1-q4_1.bin
text-generation-webui-text-generation-webui-1  | llama_model_load_internal: format     = ggjt v1 (latest)
text-generation-webui-text-generation-webui-1  | llama_model_load_internal: n_vocab    = 32000
text-generation-webui-text-generation-webui-1  | llama_model_load_internal: n_ctx      = 2048
text-generation-webui-text-generation-webui-1  | llama_model_load_internal: n_embd     = 4096
text-generation-webui-text-generation-webui-1  | llama_model_load_internal: n_mult     = 256
text-generation-webui-text-generation-webui-1  | llama_model_load_internal: n_head     = 32
text-generation-webui-text-generation-webui-1  | llama_model_load_internal: n_layer    = 32
text-generation-webui-text-generation-webui-1  | llama_model_load_internal: n_rot      = 128
text-generation-webui-text-generation-webui-1  | llama_model_load_internal: f16        = 5
text-generation-webui-text-generation-webui-1  | llama_model_load_internal: n_ff       = 11008
text-generation-webui-text-generation-webui-1  | llama_model_load_internal: n_parts    = 1
text-generation-webui-text-generation-webui-1  | llama_model_load_internal: model size = 7B
text-generation-webui-text-generation-webui-1  | llama_model_load_internal: ggml ctx size =  59.11 KB
text-generation-webui-text-generation-webui-1  | llama_model_load_internal: mem required  = 6612.57 MB (+ 2052.00 MB per state)
text-generation-webui-text-generation-webui-1  | llama_init_from_file: kv self size  = 2048.00 MB
text-generation-webui-text-generation-webui-1  | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
text-generation-webui-text-generation-webui-1  | Traceback (most recent call last):
text-generation-webui-text-generation-webui-1  |   File "/app/server.py", line 827, in <module>
text-generation-webui-text-generation-webui-1  |     create_interface()
text-generation-webui-text-generation-webui-1  |   File "/app/server.py", line 489, in create_interface
text-generation-webui-text-generation-webui-1  |     with gr.Blocks(css=ui.css if not shared.is_chat() else ui.css + ui.chat_css, analytics_enabled=False, title=title) as shared.gradio['interface']:
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1200, in __exit__
text-generation-webui-text-generation-webui-1  |     self.config = self.get_config_file()
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1176, in get_config_file
text-generation-webui-text-generation-webui-1  |     "input": list(block.input_api_info()),  # type: ignore
text-generation-webui-text-generation-webui-1  | AttributeError: 'State' object has no attribute 'input_api_info'
text-generation-webui-text-generation-webui-1 exited with code 1
```

### System Info

```shell
Docker Host: Windows 10
CPU: AMD Ryzen 5800x3d
GPU: Nvidia 1660 TI
Ram: 32gb
```

**Comment by mdegans** [comment]
Seems the issue is gradio. Change the version to `gradio==3.23` in the requirements.txt and reinstall. Worked for me.

**Comment by ZMon3y** [comment]
#1153 may be a dupe issue



> Seems the issue is gradio. Change the version to `gradio==3.23` in the requirements.txt and reinstall. Worked for me.

This seems to solve the problem

**Comment by sust4in** [comment]
@mdegans's comment fixes this issue. thanks

**Comment by lee-b** [comment]
Same `pip install gradio==3.23` fix worked for me, just for extra confirmation.
