### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by Kuchiriel** [oobabooga/text-generation-webui#1162]
### Describe the bug

(textgen) kuchiriel@UTKSVR01:/mnt/e/text-generation-webui$ python server.py
Traceback (most recent call last):
  File "/mnt/e/text-generation-webui/server.py", line 18, in <module>
    import gradio as gr
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/gradio/components.py", line 25, in <module>
    import altair as alt
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/altair/__init__.py", line 4, in <module>
    from .vegalite import *
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/altair/vegalite/__init__.py", line 2, in <module>
    from .v4 import *
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/altair/vegalite/v4/__init__.py", line 2, in <module>
    from .schema import *
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/altair/vegalite/v4/schema/__init__.py", line 2, in <module>
    from .core import *
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/altair/vegalite/v4/schema/core.py", line 4, in <module>
    from altair.utils.schemapi import SchemaBase, Undefined, _subclasses
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/altair/utils/__init__.py", line 1, in <module>
    from .core import (
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/altair/utils/core.py", line 14, in <module>
    import pandas as pd
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/pandas/compat/__init__.py", line 25, in <module>
    from pandas.compat.numpy import (
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/pandas/_libs/tslibs/__init__.py", line 39, in <module>
    from pandas._libs.tslibs.conversion import localize_pydatetime
  File "pandas/_libs/tslibs/conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "pandas/_libs/tslibs/timestamps.pyx", line 1, in init pandas._libs.tslibs.timestamps
  File "pandas/_libs/tslibs/timedeltas.pyx", line 1, in init pandas._libs.tslibs.timedeltas
  File "pandas/_libs/tslibs/timezones.pyx", line 24, in init pandas._libs.tslibs.timezones
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/dateutil/tz/__init__.py", line 2, in <module>
    from .tz import *
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/dateutil/tz/tz.py", line 19, in <module>
    import six
ModuleNotFoundError: No module named 'six'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

python server.py

### Logs

```shell
Traceback (most recent call last):
  File "/mnt/e/text-generation-webui/server.py", line 18, in <module>
    import gradio as gr
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/gradio/components.py", line 25, in <module>
    import altair as alt
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/altair/__init__.py", line 4, in <module>
    from .vegalite import *
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/altair/vegalite/__init__.py", line 2, in <module>
    from .v4 import *
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/altair/vegalite/v4/__init__.py", line 2, in <module>
    from .schema import *
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/altair/vegalite/v4/schema/__init__.py", line 2, in <module>
    from .core import *
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/altair/vegalite/v4/schema/core.py", line 4, in <module>
    from altair.utils.schemapi import SchemaBase, Undefined, _subclasses
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/altair/utils/__init__.py", line 1, in <module>
    from .core import (
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/altair/utils/core.py", line 14, in <module>
    import pandas as pd
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/pandas/compat/__init__.py", line 25, in <module>
    from pandas.compat.numpy import (
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/pandas/_libs/tslibs/__init__.py", line 39, in <module>
    from pandas._libs.tslibs.conversion import localize_pydatetime
  File "pandas/_libs/tslibs/conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "pandas/_libs/tslibs/timestamps.pyx", line 1, in init pandas._libs.tslibs.timestamps
  File "pandas/_libs/tslibs/timedeltas.pyx", line 1, in init pandas._libs.tslibs.timedeltas
  File "pandas/_libs/tslibs/timezones.pyx", line 24, in init pandas._libs.tslibs.timezones
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/dateutil/tz/__init__.py", line 2, in <module>
    from .tz import *
  File "/home/kuchiriel/.local/lib/python3.10/site-packages/dateutil/tz/tz.py", line 19, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

### System Info

```shell
WSL2
```

**Comment by player2I0** [comment]
how did you solve this?

**Comment by Kuchiriel** [comment]
Sorry it was a mistake I am trying to install on Termux and I am having a lot of dep issues because of the cross platform. When I solve it all I will report here.

**Comment by vleeuwenmenno** [comment]
Any progress you can report back on? Would be interesting to see if this could work.
