### ISSUE TITLE
Error generating responses on vicuna-13b-GPTQ-4bit-128g

### ISSUE THREAD

**Issue by Revival8697** [oobabooga/text-generation-webui#1169]
### Describe the bug

I tried running the [vicuna-13b-GPTQ-4bit-128g](https://huggingface.co/anon8231489123/vicuna-13b-GPTQ-4bit-128g) model but it fails at generating response.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Launch the webui with `python server.py --auto-devices --gpu-memory 5 --wbits 4 --groupsize 128`.

Input something.

Hit `Generate`.

### Screenshot

![Screenshot_20230414_144115 cleaned](https://user-images.githubusercontent.com/24849056/231977803-c0d562bf-1773-4d04-b7c3-a5965d029b32.png)

### Logs

```shell
Traceback (most recent call last):
  File "/home/sp1cyf0x/Documents/Git/text-generation-webui/modules/callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/home/sp1cyf0x/Documents/Git/text-generation-webui/modules/text_generation.py", line 251, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/sp1cyf0x/Documents/Git/text-generation-webui/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/sp1cyf0x/Documents/Git/text-generation-webui/venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 1485, in generate
    return self.sample(
  File "/home/sp1cyf0x/Documents/Git/text-generation-webui/venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 2524, in sample
    outputs = self(
  File "/home/sp1cyf0x/Documents/Git/text-generation-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sp1cyf0x/Documents/Git/text-generation-webui/venv/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/sp1cyf0x/Documents/Git/text-generation-webui/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "/home/sp1cyf0x/Documents/Git/text-generation-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sp1cyf0x/Documents/Git/text-generation-webui/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 577, in forward
    layer_outputs = decoder_layer(
  File "/home/sp1cyf0x/Documents/Git/text-generation-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sp1cyf0x/Documents/Git/text-generation-webui/venv/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/sp1cyf0x/Documents/Git/text-generation-webui/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/sp1cyf0x/Documents/Git/text-generation-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sp1cyf0x/Documents/Git/text-generation-webui/venv/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/sp1cyf0x/Documents/Git/text-generation-webui/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 196, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "/home/sp1cyf0x/Documents/Git/text-generation-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sp1cyf0x/Documents/Git/text-generation-webui/venv/lib/python3.10/site-packages/accelerate/hooks.py", line 160, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "/home/sp1cyf0x/Documents/Git/text-generation-webui/venv/lib/python3.10/site-packages/accelerate/hooks.py", line 280, in pre_forward
    set_module_tensor_to_device(module, name, self.execution_device, value=self.weights_map[name])
  File "/home/sp1cyf0x/Documents/Git/text-generation-webui/venv/lib/python3.10/site-packages/accelerate/utils/offload.py", line 123, in __getitem__
    return self.dataset[f"{self.prefix}{key}"]
  File "/home/sp1cyf0x/Documents/Git/text-generation-webui/venv/lib/python3.10/site-packages/accelerate/utils/offload.py", line 170, in __getitem__
    weight_info = self.index[key]
KeyError: 'model.layers.28.self_attn.q_proj.wf'
Output generated in 1.84 seconds (0.00 tokens/s, 0 tokens, context 13, seed 57673555)
```

### System Info

```shell
OS: Arch Linux x86_64.
GPU: NVIDIA GeForce GTX 1660 Ti Mobile.
```

**Comment by Quad-Plex** [comment]
not sure if this is a bug, I'm successfully running `anon8231489123/vicuna-13b-GPTQ-4bit-128g` on my machine here

```
Loading anon8231489123_vicuna-13b-GPTQ-4bit-128g...
Found the following quantized model: models\anon8231489123_vicuna-13b-GPTQ-4bit-128g\vicuna-13b-4bit-128g.safetensors
Loading model ...
Done.
Using the following device map for the quantized model: {'': 0}
Loaded the model in 21.40 seconds.
```
This is on an RTX 3080 with 10GB of VRAM and `--gpu_memory 9200MiB`

**Comment by Ph0rk0z** [comment]
Its the offloading. i noticed it too last night. If the model can't run in the memory you allotted it will do stuff like that.  Hence in 9G it runs.. in 5g it doesn't.

**Comment by sp1cyf0x** [comment]
> Its the offloading. i noticed it too last night. If the model can't run in the memory you allotted it will do stuff like that. Hence in 9G it runs.. in 5g it doesn't.

Is that so? I thought it would error out "out of memory" if that were the case.
My GPU only have 6 GB, can't do anything that. I tried some methods at [Low-VRAM-guide](https://github.com/oobabooga/text-generation-webui/wiki/Low-VRAM-guide) but none seems to work.

**Comment by Ph0rk0z** [comment]
Nope.. it doesn't OOM. It splits layers that it can't split. Before the behavior was that the memory would balloon up on generation. I was testing the commits last night and had that same experience with llama and gpt-neox in 4bit. If I set the memory too low it would fail similarly. 

Maybe someone smarter than me can fix it but accelerate is being called right and all that. Try to use pre-layer since this is a llama model.

**Comment by ZaXk** [comment]
Remove the --gpu-memory 6 and added --pre_layer 35.

**Comment by Drift91** [comment]
> not sure if this is a bug, I'm successfully running `anon8231489123/vicuna-13b-GPTQ-4bit-128g` on my machine here

This is most likely a GPU specific issue I suspect. I'm also on a 1660ti and all 16-series cards require special arguments, `--precision full --no-half`, for StableDiffusion so I can only assume it's the same here.

**Comment by Ph0rk0z** [comment]
it pre_layers on my mix n match generation of gpus
