### ISSUE TITLE
Unable to open webui

### ISSUE THREAD

**Issue by win10ogod** [oobabooga/text-generation-webui#1174]
### Describe the bug

    if '/' in name or '\\' in name:
TypeError: argument of type 'WindowsPath' is not iterable

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Use the latest one-click-installers

### Logs

```shell
WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('D')}
D:\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\paths.py:98: UserWarning: D:\oobabooga\installer_files\env did not contain libcudart.so as expected! Searching further paths...
  warn(
WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/oobabooga/installer_files/env/etc/xml/catalog'), WindowsPath('file'), WindowsPath('/D')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA_SETUP: Loading binary D:\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
Traceback (most recent call last):
  File "D:\oobabooga\text-generation-webui\server.py", line 27, in <module>
    from modules import api, chat, shared, training, ui
  File "D:\oobabooga\text-generation-webui\modules\training.py", line 12, in <module>
    from peft import (LoraConfig, get_peft_model, get_peft_model_state_dict,
  File "D:\oobabooga\installer_files\env\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "D:\oobabooga\installer_files\env\lib\site-packages\peft\mapping.py", line 16, in <module>
    from .peft_model import (
  File "D:\oobabooga\installer_files\env\lib\site-packages\peft\peft_model.py", line 31, in <module>
    from .tuners import LoraModel, PrefixEncoder, PromptEmbedding, PromptEncoder
  File "D:\oobabooga\installer_files\env\lib\site-packages\peft\tuners\__init__.py", line 20, in <module>
    from .lora import LoraConfig, LoraModel
  File "D:\oobabooga\installer_files\env\lib\site-packages\peft\tuners\lora.py", line 36, in <module>
    import bitsandbytes as bnb
  File "D:\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "D:\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\autograd\_functions.py", line 4, in <module>
    import bitsandbytes.functional as F
  File "D:\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\functional.py", line 14, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "D:\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\cextension.py", line 36, in <module>
    lib = CUDALibrary_Singleton.get_instance().lib
  File "D:\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\cextension.py", line 32, in get_instance
    cls._instance.initialize()
  File "D:\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\cextension.py", line 26, in initialize
    self.lib = ct.cdll.LoadLibrary(binary_path)
  File "D:\oobabooga\installer_files\env\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "D:\oobabooga\installer_files\env\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'WindowsPath' is not iterable
```

### System Info

```shell
gpu:3050
cpu:i5-12400F
windows 11 home
```

**Comment by jllllll** [comment]
Bitsandbytes got updated. So I need to recompile for the new version as it doesn't support Windows. It may take a while.

**Comment by jllllll** [comment]
In the mean time, you can try this in `micromamba-cmd.bat`:
```
python -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/raw/main/bitsandbytes-0.37.2-py3-none-any.whl --force-reinstall
```

**Comment by jllllll** [comment]
Compiled a 0.38.1 wheel, kinda scuffed, but it worked for the model I tested it on.

Open `micromamba-cmd.bat` and enter this:
```
python -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/raw/main/bitsandbytes-0.38.1-py3-none-any.whl --force-reinstall
```
