### ISSUE TITLE
Some command line arguments ignored on start

### ISSUE THREAD

**Issue by IJumpAround** [oobabooga/text-generation-webui#1190]
### Describe the bug

Starting the server with the following arguments `--model llama-13b --wbits 4 --gpu-memory 9` results in wbits being set to None instead of 4. Then the model fails to load correctly.

My llama-13b folder has both the quantized 4 bit model and the three part pytorch_model-00001-of-00003.bin files. Not sure if that second part matters. 

I believe some model specific command line arguments are being omitted or not considered by the new __main__ in server.py
In this block model_settings has wbits=None after `get_model_specific_settings(shared.model_name)` runs
```
    if shared.model_name != 'None':

        model_settings = get_model_specific_settings(shared.model_name)
        shared.settings.update(model_settings)  # hijacking the interface defaults
        update_model_parameters(model_settings)  # hijacking the command-line arguments
```

This is on 1901d238e194a6f534fddfc38ef72e25de7f92fd

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Check out 1901d238e194a6f534fddfc38ef72e25de7f92fd and start the server using the arguments I listed.

This might not trigger an error if your GPU can fit the entire model into memory, but wbits will still likely be unset, I can't test that case.

### Logs

```shell
C:\Users\Jump_Around\PycharmProjects\one-click-installers\installer_files\env\python.exe C:\Users\Jump_Around\PycharmProjects\one-click-installers\text-generation-webui\server.py --model llama-13b --wbits 4 --gpu-memory 9 
Loading settings from settings.json...
['notebook: False', 'chat: False', 'cai_chat: False', 'model: llama-13b', 'lora: None', 'model_dir: models/', 'lora_dir: loras/', 'model_menu: False', 'no_stream: False', 'settings: None', 'extensions: None', 'verbose: False', 'cpu: False', 'auto_devices: False', 'gpu_memory: None', 'cpu_memory: None', 'disk: False', 'disk_cache_dir: cache', 'load_in_8bit: False', 'bf16: False', 'no_cache: False', 'xformers: False', 'sdp_attention: False', 'threads: 0', 'wbits: 0', 'model_type: None', 'groupsize: -1', 'pre_layer: 0', 'no_warmup_autotune: False', 'flexgen: False', 'percent: [0, 100, 100, 0, 100, 0]', 'compress_weight: False', 'pin_weight: True', 'deepspeed: False', 'nvme_offload_dir: None', 'local_rank: 0', 'rwkv_strategy: None', 'rwkv_cuda_on: False', 'listen: False', 'listen_host: None', 'listen_port: None', 'share: False', 'auto_launch: False', 'gradio_auth_path: None']
Loading llama-13b...
Traceback (most recent call last):
  File "C:\Users\Jump_Around\PycharmProjects\one-click-installers\text-generation-webui\server.py", line 847, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\Jump_Around\PycharmProjects\one-click-installers\text-generation-webui\modules\models.py", line 51, in load_model
    model = AutoModelForCausalLM.from_pretrained(Path(f"{shared.args.model_dir}/{shared.model_name}"), device_map='auto', load_in_8bit=True)
  File "C:\Users\Jump_Around\PycharmProjects\one-click-installers\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\Jump_Around\PycharmProjects\one-click-installers\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2654, in from_pretrained
    raise ValueError(
ValueError: 
                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you want to dispatch the model on the CPU or the disk while keeping
                        these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom
                        `device_map` to `from_pretrained`. Check
                        https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                        for more details.
                        

Process finished with exit code 1
```

### System Info

```shell
Windows 10
2080TI (don't remember which brand)
```

**Comment by IJumpAround** [comment]
And just to confirm if I edit the file to the following.

```
        model_settings = get_model_specific_settings(shared.model_name)
        model_settings['wbits'] = 4
```

Though obviously not the correct solution, the model loads and the server starts without error

![image](https://user-images.githubusercontent.com/30680324/232119217-9ff108ad-b4d3-4351-b370-33e62598287a.png)

**Comment by oobabooga** [comment]
See if this fixes it https://github.com/oobabooga/text-generation-webui/commit/43e01282b39b2859f8b5c33aa212f577f569a295

**Comment by IJumpAround** [comment]
Yeah that appears to fix it.
