### ISSUE TITLE
AttributeError: function 'clion32bit_g32' not found

### ISSUE THREAD

**Issue by Zensud** [oobabooga/text-generation-webui#1193]
### Describe the bug

I Just installed text-generation-webui and i got this problem when I wanna to load my models

I tried to use --chat but its show the same error

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

python server.py --model pygmalion-6b_dev --cai-chat --load-in-8bit

### Logs

```shell
`Warning: --cai-chat is deprecated. Use --chat instead.
bin C:\Users\Zen\anaconda3\envs\textgen\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll
Traceback (most recent call last):
  File "C:\Windows\System32\text-generation-webui\server.py", line 27, in <module>
    from modules import api, chat, shared, training, ui
  File "C:\Windows\System32\text-generation-webui\modules\training.py", line 12, in <module>
    from peft import (LoraConfig, get_peft_model, get_peft_model_state_dict,
  File "C:\Users\Zen\anaconda3\envs\textgen\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "C:\Users\Zen\anaconda3\envs\textgen\lib\site-packages\peft\mapping.py", line 16, in <module>
    from .peft_model import (
  File "C:\Users\Zen\anaconda3\envs\textgen\lib\site-packages\peft\peft_model.py", line 31, in <module>
    from .tuners import LoraModel, PrefixEncoder, PromptEmbedding, PromptEncoder
  File "C:\Users\Zen\anaconda3\envs\textgen\lib\site-packages\peft\tuners\__init__.py", line 20, in <module>
    from .lora import LoraConfig, LoraModel
  File "C:\Users\Zen\anaconda3\envs\textgen\lib\site-packages\peft\tuners\lora.py", line 36, in <module>
    import bitsandbytes as bnb
  File "C:\Users\Zen\anaconda3\envs\textgen\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\Zen\anaconda3\envs\textgen\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\Zen\anaconda3\envs\textgen\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\Zen\anaconda3\envs\textgen\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\Zen\anaconda3\envs\textgen\lib\site-packages\bitsandbytes\optim\__init__.py", line 8, in <module>
    from .adagrad import Adagrad, Adagrad8bit, Adagrad32bit
  File "C:\Users\Zen\anaconda3\envs\textgen\lib\site-packages\bitsandbytes\optim\adagrad.py", line 5, in <module>
    from bitsandbytes.optim.optimizer import Optimizer1State
  File "C:\Users\Zen\anaconda3\envs\textgen\lib\site-packages\bitsandbytes\optim\optimizer.py", line 12, in <module>
    import bitsandbytes.functional as F
  File "C:\Users\Zen\anaconda3\envs\textgen\lib\site-packages\bitsandbytes\functional.py", line 39, in <module>
    lib.clion32bit_g32,
  File "C:\Users\Zen\anaconda3\envs\textgen\lib\ctypes\__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Zen\anaconda3\envs\textgen\lib\ctypes\__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'clion32bit_g32' not found`
```

### System Info

```shell
Operating system: Windows 10 22h2
Gpu: MX130
```

**Comment by 6ky** [comment]
I got the same issue, did you manage to resolve?

**Comment by GLaN1K** [comment]
`pip install bitsandbytes==0.37.2`
