### ISSUE TITLE
Fails to load model

### ISSUE THREAD

**Issue by Userbingd** [oobabooga/text-generation-webui#1194]
### Describe the bug

I did just about everything in the low Vram guide and it still fails, and is the same message every time.
I'm using this model, [gpt4-x-alpaca-13b-native-4bit-128g](https://huggingface.co/anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Attempt to load model

### Logs

```shell
Traceback (most recent call last):
File “G:\Oobabooga Text UI\oobabooga-windows\oobabooga-windows\text-generation-webui\server.py”, line 84, in load_model_wrapper
shared.model, shared.tokenizer = load_model(shared.model_name)
File “G:\Oobabooga Text UI\oobabooga-windows\oobabooga-windows\text-generation-webui\modules\models.py”, line 103, in load_model
model = load_quantized(model_name)
File “G:\Oobabooga Text UI\oobabooga-windows\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py”, line 151, in load_quantized
model = load_quant(str(path_to_model), str(pt_path), shared.args.wbits, shared.args.groupsize, kernel_switch_threshold=threshold)
File “G:\Oobabooga Text UI\oobabooga-windows\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py”, line 32, in _load_quant
model = AutoModelForCausalLM.from_config(config)
File “G:\Oobabooga Text UI\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py”, line 411, in from_config
return model_class._from_config(config, **kwargs)
File “G:\Oobabooga Text UI\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py”, line 1146, in _from_config
model = cls(config, **kwargs)
File “G:\Oobabooga Text UI\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py”, line 614, in init
self.model = LlamaModel(config)
File “G:\Oobabooga Text UI\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py”, line 445, in init
self.layers = nn.ModuleList([LlamaDecoderLayer(config) for _ in range(config.num_hidden_layers)])
File “G:\Oobabooga Text UI\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py”, line 445, in
self.layers = nn.ModuleList([LlamaDecoderLayer(config) for _ in range(config.num_hidden_layers)])
File “G:\Oobabooga Text UI\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py”, line 255, in init
self.self_attn = LlamaAttention(config=config)
File “G:\Oobabooga Text UI\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py”, line 176, in init
self.q_proj = nn.Linear(self.hidden_size, self.num_heads * self.head_dim, bias=False)
File “G:\Oobabooga Text UI\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\linear.py”, line 96, in init
self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 52428800 bytes.
```

### System Info

```shell
Windows 10
Intel Core I7 860
16GB DDR3 low density RAM
GTX 1650 SUPER
```

**Comment by greynutella** [comment]
i have the same error

**Comment by jllllll** [comment]
4-bit models get loaded into RAM before being sent to VRAM. You need to have enough free RAM for it to load, or it will just fail.
This model will require at least 10gb of unused RAM to load.

**Comment by kickturn** [comment]
> 4-bit models get loaded into RAM before being sent to VRAM. You need to have enough free RAM for it to load, or it will just fail. This model will require at least 10gb of unused RAM to load.

I have 32gb, is that not enough?

**Comment by jllllll** [comment]
@kickturn That should be plenty. Your ram and vram amounts are essentially the same as my system and I'm not getting this issue.

What arguments are you using to launch the webui?

**Comment by kickturn** [comment]
@jllllll Only `--auto-devices --chat --gpu-memory 11` I removed and switched some parameters with no luck

**Comment by jllllll** [comment]
@kickturn `--auto-devices` and `--gpu-memory` don't apply to 4-bit models.

Watch your ram allocation in task manager while you try to load the model. Does your ram fill up completely?

**Comment by kickturn** [comment]
@jllllll Nope, in fact, it did not change with half of it free. I checked both resource monitor and task manager.

I will try different models later and see what I get

**Comment by bloodsign** [comment]
did you load the model without using `--wbits 4 --groupsize 128` ?

**Comment by westraven** [comment]
same error with 16gb ram

**Comment by Csf91** [comment]
Here's mine, same error. Using: --auto-devices --chat --model-menu --wbits 4 --groupsize 128

`Loading vicuna-13b-GPTQ-4bit-128g...
Found the following quantized model: models\vicuna-13b-GPTQ-4bit-128g\vicuna-13b-4bit-128g.safetensors
Traceback (most recent call last):
  File "E:\Proyectos\_AI\ChatGPT\oobabooga-windows\text-generation-webui\server.py", line 905, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "E:\Proyectos\_AI\ChatGPT\oobabooga-windows\text-generation-webui\modules\models.py", line 117, in load_model
    model = load_quantized(model_name)
  File "E:\Proyectos\_AI\ChatGPT\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 172, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.wbits, shared.args.groupsize, kernel_switch_threshold=threshold)
  File "E:\Proyectos\_AI\ChatGPT\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 40, in _load_quant
    model = AutoModelForCausalLM.from_config(config)
  File "E:\Proyectos\_AI\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 411, in from_config
    return model_class._from_config(config, **kwargs)
  File "E:\Proyectos\_AI\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 1146, in _from_config
    model = cls(config, **kwargs)
  File "E:\Proyectos\_AI\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 614, in __init__
    self.model = LlamaModel(config)
  File "E:\Proyectos\_AI\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 445, in __init__
    self.layers = nn.ModuleList([LlamaDecoderLayer(config) for _ in range(config.num_hidden_layers)])
  File "E:\Proyectos\_AI\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 445, in <listcomp>
    self.layers = nn.ModuleList([LlamaDecoderLayer(config) for _ in range(config.num_hidden_layers)])
  File "E:\Proyectos\_AI\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 256, in __init__
    self.mlp = LlamaMLP(
  File "E:\Proyectos\_AI\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 151, in __init__
    self.gate_proj = nn.Linear(hidden_size, intermediate_size, bias=False)
  File "E:\Proyectos\_AI\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\linear.py", line 96, in __init__
    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 141557760 bytes.` 

`Windows 11
Intel Core i7-12700F
16GB DDR4 RAM
Nvidia Geforce RTX 3060ti (8GB)`

**Comment by Userbingd** [comment]
I've done some more tests and still can't load it. No matter what I do. Whether it's CPU or GPU, it fails. Even setting a huge paging file doesn't help. I even tried loading pygmalion, and that fails as well, but unlike gpt4xalpaca it doesn't tell me exactly what went wrong.

**Comment by Csf91** [comment]
> I've done some more tests and still can't load it. No matter what I do. Whether it's CPU or GPU, it fails. Even setting a huge paging file doesn't help. I even tried loading pygmalion, and that fails as well, but unlike gpt4xalpaca it doesn't tell me exactly what went wrong.

Same here, no matter what I've tried, the only thing that might changes is the amount of memory in the last line, as shown in my last message. 
Maybe it is installing the wrong version of some dependencies even if manually running the requirements install from requirements.txt?

**Comment by jllllll** [comment]
I doubt that's what is happening. I've never once had this issue no matter how I install the webui. I can't see anything at all in any of the reports that hints at what the cause could be.

**Comment by Alexs4572** [comment]
> 4-bit models get loaded into RAM before being sent to VRAM. You need to have enough free RAM for it to load, or it will just fail. This model will require at least 10gb of unused RAM to load.

Is there any way to change this? I only have 8GB in my laptop and sadly can't open it because off the waranty, let alone having 10gigs freed.

**Comment by Alexs4572** [comment]
I'm trying to use anon8231489123/vicuna-13b-GPTQ-4bit-128g.  
Specs: 5600h,8GB ram,1650m.
Memory jumps from 50% to 63%(firefox is opened and uses 1GB + tiny 11 using around 3GB ).
Aldo 8GB ram may not be enough to run the model, i'm supprised it hit 63% and not 100 while trying to fill the ram(if it even tryed).
Is 8GB ram and 4GB vram good enough to load and run a model(even if it'll be responding relatively slowly ), or shall i give up on trying to run anything?

**Comment by jllllll** [comment]
@Alexs4572 Your best bet is to use 7b models or smaller. That 13b model uses way more than 4gb vram. Most 13b 4bit models use 7-9gb vram.

**Comment by Csf91** [comment]
> @Alexs4572 Your best bet is to use 7b models or smaller. That 13b model uses way more than 4gb vram. Most 13b 4bit models use 7-9gb vram.
I've tried with https://huggingface.co/TheBloke/vicuna-7B-1.1-GPTQ-4bit-128g/tree/main as well, same exact result. The VRAM and RAM aren't even trying to load it. Seems like a memory allocation issue to me, not the hardware lacking. Here's why:
![image](https://user-images.githubusercontent.com/13738479/233853789-8ccde934-dedb-4fd9-b905-ab0d865c67e0.png)

This image in the background is AI-Generated using A1111 and the 2dn1 sfetensor model, But I've also used bigger models without any kind of issue, at all. 
When they load both RAM and VRAM go up in % of use, sometimes even up to 100% if the model is too big for my pc, and then crash due to lack of memory (just explaining the behaviour it usually has, when it actually lacks resources).

Now, related to the actual issue here: this isn't even attempting to do load it into the memory other than the applet/launcher itself. When it starts to load you can see a peak in the clocks for the GPU memory and a small peak in the PC's RAM, which is just loading the applet. Though, from there it's just a flatline as it fails to load it into the memory.

So, specially after someone with a 12GB video card / 16GB of RAM is getting the same error, I'd point towards a memory allocation / memory management error.
> @made9 Having the same issue. 16gb of RAM, 2080ti. RAM might be slightly cluttered, but it's not even attempting to fill it.

Also, the graphs are small because i've reset them just before opening it, so that they'd only have the data from the moment i've opened it until the crash/bug. 

I hope this helps :)

**Comment by made9** [comment]
> 

Mine is an 11gb version. To be honest, I didn't even know that there's an 8gb version of that thing lol.
But yeah, I have the same issue as you. And I can also use stable diffusion without issues. And just to check, I loaded the non-4-bit version of the same model into the webUI. And yes, that thing DID attempts to load and filled up my RAM and VRAM.
So yeah, this error is related to 4-bit models on my side.

**Comment by Csf91** [comment]
Quick update for everyone in the thread, tried this and it seems to load now, though what a insane amount of memory allocation it does on the pagefile! (i had set it maximum at abound 10gb, but needed to be set as "Managed by the O.S.").

See here for details: https://youtu.be/FOyqcETVUCs?t=564 (9:24)
Got it to run by doing that, proof:
![image](https://user-images.githubusercontent.com/13738479/233909357-5e640a0d-e3f4-4088-9281-3925a8e10881.png)

Can't believe it was such a stupid thing, specially when i had it set up at quite a high amount already...

**Comment by jllllll** [comment]
@Userbingd Setting it to system managed is exactly why it is not big enough. Manually set it to 10 or 20GB.

System managed just means that Windows will decide when it needs to be resized. The issue is that this resizing does not happen instantly and the system does not always know how much memory in total is trying to be loaded. This results in Windows thinking that adding 500MB is enough when you actually need 5GB+ to be added.

**Comment by Csf91** [comment]
> @Userbingd Setting it to system managed is exactly why it is not big enough. Manually set it to 10 or 20GB.
> 
> System managed just means that Windows will decide when it needs to be resized. The issue is that this resizing does not happen instantly and the system does not always know how much memory in total is trying to be loaded. This results in Windows thinking that adding 500MB is enough when you actually need 5GB+ to be added.

Regarding that, mine was originally at 10Gb and seemed not to be enough, so i'd try with at least 20.

**Comment by Userbingd** [comment]
Never mind, I turned --Cpu off and am no longerr getting that... now I'm gutting
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)

**Comment by MillionthOdin16** [comment]
I'm also getting this. 64GB system ram and 24 VRAM. The model is like 18GB, and I have more than enough ram to handle it on both types.

**Comment by Userbingd** [comment]
I'm starting to think it's a problem with some unknown hardware or software incompatibility. My CPU is old, it's a core I7 860, and my GPU is a 1650 super. Though I have no idea where the problem lies in actuality. This is just my guess. I don't think it's a normal problem since a lot of the software to run this is the same or similar to stable diffusion, at least from how it seems with my untrained eyes. And I can run SD just fine, if only at low resolutions. But something about these text gen AI's have an issue with my PC.

**Comment by Syncriix** [comment]
Had the same problem, upon checking file the file hash I realized that it borked the download, re downloading the file 
[gpt-x-alpaca-13b-native-4bit-128g-cuda.pt](https://huggingface.co/anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g/blob/main/gpt-x-alpaca-13b-native-4bit-128g-cuda.pt)
worked, try this
