### ISSUE TITLE
WebUI doesn't start after first installation. json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by TreesPlay** [oobabooga/text-generation-webui#1202]
### Describe the bug

WebUI doesn't start.

Existing Issue but not well explained: https://github.com/oobabooga/text-generation-webui/issues/333

I don't know much about how this works but I am tired of ChatGPT censorship.

During installation I wasn't asked to install a model. So I expect no model is installed.

Edit: I just managed to install GPT4ALL. It works, but refuses to answer most questions for dumb reasons and the interface is just ...

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I have used the one-click installer to install oobabooga and opened start-webui.bat.
Since it didn't work I opened the installer again and it downloaded 2 packages (don't have the logs anymore). Then I tried to start the webui again but it still didn't work.

If I reopen the installer again this message will appear every time:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.2 which is incompatible.

I have attached the files causing the errors into the logs aswell.

### Logs

```shell
Starting the web UI...
Warning: --cai-chat is deprecated. Use --chat instead.
Loading config.yaml...
Auto-assiging --gpu-memory 10 for your GPU to try to prevent out-of-memory errors.
You can manually set other values.
Traceback (most recent call last):
  File "D:\Andere Programme\oobabooga\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 658, in _get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "D:\Andere Programme\oobabooga\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 746, in _dict_from_json_file
    return json.loads(text)
  File "D:\Andere Programme\oobabooga\installer_files\env\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Andere Programme\oobabooga\installer_files\env\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Andere Programme\oobabooga\installer_files\env\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Andere Programme\oobabooga\text-generation-webui\server.py", line 869, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\Andere Programme\oobabooga\text-generation-webui\modules\models.py", line 171, in load_model
    model = AutoModelForCausalLM.from_pretrained(checkpoint, **params)
  File "D:\Andere Programme\oobabooga\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 441, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "D:\Andere Programme\oobabooga\installer_files\env\lib\site-packages\transformers\models\auto\configuration_auto.py", line 916, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\Andere Programme\oobabooga\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 573, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\Andere Programme\oobabooga\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 661, in _get_config_dict
    raise EnvironmentError(
OSError: It looks like the config file at 'models\config.yaml' is not a valid JSON file.
Drücken Sie eine beliebige Taste . . .


****decoder.py******
"""Implementation of JSONDecoder
"""
import re

from json import scanner
try:
    from _json import scanstring as c_scanstring
except ImportError:
    c_scanstring = None

__all__ = ['JSONDecoder', 'JSONDecodeError']

FLAGS = re.VERBOSE | re.MULTILINE | re.DOTALL

NaN = float('nan')
PosInf = float('inf')
NegInf = float('-inf')


class JSONDecodeError(ValueError):
    """Subclass of ValueError with the following additional properties:

    msg: The unformatted error message
    doc: The JSON document being parsed
    pos: The start index of doc where parsing failed
    lineno: The line corresponding to pos
    colno: The column corresponding to pos

    """
    # Note that this exception is used from _json
    def __init__(self, msg, doc, pos):
        lineno = doc.count('\n', 0, pos) + 1
        colno = pos - doc.rfind('\n', 0, pos)
        errmsg = '%s: line %d column %d (char %d)' % (msg, lineno, colno, pos)
        ValueError.__init__(self, errmsg)
        self.msg = msg
        self.doc = doc
        self.pos = pos
        self.lineno = lineno
        self.colno = colno

    def __reduce__(self):
        return self.__class__, (self.msg, self.doc, self.pos)


_CONSTANTS = {
    '-Infinity': NegInf,
    'Infinity': PosInf,
    'NaN': NaN,
}


STRINGCHUNK = re.compile(r'(.*?)(["\\\x00-\x1f])', FLAGS)
BACKSLASH = {
    '"': '"', '\\': '\\', '/': '/',
    'b': '\b', 'f': '\f', 'n': '\n', 'r': '\r', 't': '\t',
}

def _decode_uXXXX(s, pos):
    esc = s[pos + 1:pos + 5]
    if len(esc) == 4 and esc[1] not in 'xX':
        try:
            return int(esc, 16)
        except ValueError:
            pass
    msg = "Invalid \\uXXXX escape"
    raise JSONDecodeError(msg, s, pos)

def py_scanstring(s, end, strict=True,
        _b=BACKSLASH, _m=STRINGCHUNK.match):
    """Scan the string s for a JSON string. End is the index of the
    character in s after the quote that started the JSON string.
    Unescapes all valid JSON string escape sequences and raises ValueError
    on attempt to decode an invalid string. If strict is False then literal
    control characters are allowed in the string.

    Returns a tuple of the decoded string and the index of the character in s
    after the end quote."""
    chunks = []
    _append = chunks.append
    begin = end - 1
    while 1:
        chunk = _m(s, end)
        if chunk is None:
            raise JSONDecodeError("Unterminated string starting at", s, begin)
        end = chunk.end()
        content, terminator = chunk.groups()
        # Content is contains zero or more unescaped string characters
        if content:
            _append(content)
        # Terminator is the end of string, a literal control character,
        # or a backslash denoting that an escape sequence follows
        if terminator == '"':
            break
        elif terminator != '\\':
            if strict:
                #msg = "Invalid control character %r at" % (terminator,)
                msg = "Invalid control character {0!r} at".format(terminator)
                raise JSONDecodeError(msg, s, end)
            else:
                _append(terminator)
                continue
        try:
            esc = s[end]
        except IndexError:
            raise JSONDecodeError("Unterminated string starting at",
                                  s, begin) from None
        # If not a unicode escape sequence, must be in the lookup table
        if esc != 'u':
            try:
                char = _b[esc]
            except KeyError:
                msg = "Invalid \\escape: {0!r}".format(esc)
                raise JSONDecodeError(msg, s, end)
            end += 1
        else:
            uni = _decode_uXXXX(s, end)
            end += 5
            if 0xd800 <= uni <= 0xdbff and s[end:end + 2] == '\\u':
                uni2 = _decode_uXXXX(s, end + 1)
                if 0xdc00 <= uni2 <= 0xdfff:
                    uni = 0x10000 + (((uni - 0xd800) << 10) | (uni2 - 0xdc00))
                    end += 6
            char = chr(uni)
        _append(char)
    return ''.join(chunks), end


# Use speedup if available
scanstring = c_scanstring or py_scanstring

WHITESPACE = re.compile(r'[ \t\n\r]*', FLAGS)
WHITESPACE_STR = ' \t\n\r'


def JSONObject(s_and_end, strict, scan_once, object_hook, object_pairs_hook,
               memo=None, _w=WHITESPACE.match, _ws=WHITESPACE_STR):
    s, end = s_and_end
    pairs = []
    pairs_append = pairs.append
    # Backwards compatibility
    if memo is None:
        memo = {}
    memo_get = memo.setdefault
    # Use a slice to prevent IndexError from being raised, the following
    # check will raise a more specific ValueError if the string is empty
    nextchar = s[end:end + 1]
    # Normally we expect nextchar == '"'
    if nextchar != '"':
        if nextchar in _ws:
            end = _w(s, end).end()
            nextchar = s[end:end + 1]
        # Trivial empty object
        if nextchar == '}':
            if object_pairs_hook is not None:
                result = object_pairs_hook(pairs)
                return result, end + 1
            pairs = {}
            if object_hook is not None:
                pairs = object_hook(pairs)
            return pairs, end + 1
        elif nextchar != '"':
            raise JSONDecodeError(
                "Expecting property name enclosed in double quotes", s, end)
    end += 1
    while True:
        key, end = scanstring(s, end, strict)
        key = memo_get(key, key)
        # To skip some function call overhead we optimize the fast paths where
        # the JSON key separator is ": " or just ":".
        if s[end:end + 1] != ':':
            end = _w(s, end).end()
            if s[end:end + 1] != ':':
                raise JSONDecodeError("Expecting ':' delimiter", s, end)
        end += 1

        try:
            if s[end] in _ws:
                end += 1
                if s[end] in _ws:
                    end = _w(s, end + 1).end()
        except IndexError:
            pass

        try:
            value, end = scan_once(s, end)
        except StopIteration as err:
            raise JSONDecodeError("Expecting value", s, err.value) from None
        pairs_append((key, value))
        try:
            nextchar = s[end]
            if nextchar in _ws:
                end = _w(s, end + 1).end()
                nextchar = s[end]
        except IndexError:
            nextchar = ''
        end += 1

        if nextchar == '}':
            break
        elif nextchar != ',':
            raise JSONDecodeError("Expecting ',' delimiter", s, end - 1)
        end = _w(s, end).end()
        nextchar = s[end:end + 1]
        end += 1
        if nextchar != '"':
            raise JSONDecodeError(
                "Expecting property name enclosed in double quotes", s, end - 1)
    if object_pairs_hook is not None:
        result = object_pairs_hook(pairs)
        return result, end
    pairs = dict(pairs)
    if object_hook is not None:
        pairs = object_hook(pairs)
    return pairs, end

def JSONArray(s_and_end, scan_once, _w=WHITESPACE.match, _ws=WHITESPACE_STR):
    s, end = s_and_end
    values = []
    nextchar = s[end:end + 1]
    if nextchar in _ws:
        end = _w(s, end + 1).end()
        nextchar = s[end:end + 1]
    # Look-ahead for trivial empty array
    if nextchar == ']':
        return values, end + 1
    _append = values.append
    while True:
        try:
            value, end = scan_once(s, end)
        except StopIteration as err:
            raise JSONDecodeError("Expecting value", s, err.value) from None
        _append(value)
        nextchar = s[end:end + 1]
        if nextchar in _ws:
            end = _w(s, end + 1).end()
            nextchar = s[end:end + 1]
        end += 1
        if nextchar == ']':
            break
        elif nextchar != ',':
            raise JSONDecodeError("Expecting ',' delimiter", s, end - 1)
        try:
            if s[end] in _ws:
                end += 1
                if s[end] in _ws:
                    end = _w(s, end + 1).end()
        except IndexError:
            pass

    return values, end


class JSONDecoder(object):
    """Simple JSON <https://json.org> decoder

    Performs the following translations in decoding by default:

    +---------------+-------------------+
    | JSON          | Python            |
    +===============+===================+
    | object        | dict              |
    +---------------+-------------------+
    | array         | list              |
    +---------------+-------------------+
    | string        | str               |
    +---------------+-------------------+
    | number (int)  | int               |
    +---------------+-------------------+
    | number (real) | float             |
    +---------------+-------------------+
    | true          | True              |
    +---------------+-------------------+
    | false         | False             |
    +---------------+-------------------+
    | null          | None              |
    +---------------+-------------------+

    It also understands ``NaN``, ``Infinity``, and ``-Infinity`` as
    their corresponding ``float`` values, which is outside the JSON spec.

    """

    def __init__(self, *, object_hook=None, parse_float=None,
            parse_int=None, parse_constant=None, strict=True,
            object_pairs_hook=None):
        """``object_hook``, if specified, will be called with the result
        of every JSON object decoded and its return value will be used in
        place of the given ``dict``.  This can be used to provide custom
        deserializations (e.g. to support JSON-RPC class hinting).

        ``object_pairs_hook``, if specified will be called with the result of
        every JSON object decoded with an ordered list of pairs.  The return
        value of ``object_pairs_hook`` will be used instead of the ``dict``.
        This feature can be used to implement custom decoders.
        If ``object_hook`` is also defined, the ``object_pairs_hook`` takes
        priority.

        ``parse_float``, if specified, will be called with the string
        of every JSON float to be decoded. By default this is equivalent to
        float(num_str). This can be used to use another datatype or parser
        for JSON floats (e.g. decimal.Decimal).

        ``parse_int``, if specified, will be called with the string
        of every JSON int to be decoded. By default this is equivalent to
        int(num_str). This can be used to use another datatype or parser
        for JSON integers (e.g. float).

        ``parse_constant``, if specified, will be called with one of the
        following strings: -Infinity, Infinity, NaN.
        This can be used to raise an exception if invalid JSON numbers
        are encountered.

        If ``strict`` is false (true is the default), then control
        characters will be allowed inside strings.  Control characters in
        this context are those with character codes in the 0-31 range,
        including ``'\\t'`` (tab), ``'\\n'``, ``'\\r'`` and ``'\\0'``.
        """
        self.object_hook = object_hook
        self.parse_float = parse_float or float
        self.parse_int = parse_int or int
        self.parse_constant = parse_constant or _CONSTANTS.__getitem__
        self.strict = strict
        self.object_pairs_hook = object_pairs_hook
        self.parse_object = JSONObject
        self.parse_array = JSONArray
        self.parse_string = scanstring
        self.memo = {}
        self.scan_once = scanner.make_scanner(self)


    def decode(self, s, _w=WHITESPACE.match):
        """Return the Python representation of ``s`` (a ``str`` instance
        containing a JSON document).

        """
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
        end = _w(s, end).end()
        if end != len(s):
            raise JSONDecodeError("Extra data", s, end)
        return obj

    def raw_decode(self, s, idx=0):
        """Decode a JSON document from ``s`` (a ``str`` beginning with
        a JSON document) and return a 2-tuple of the Python
        representation and the index in ``s`` where the document ended.

        This can be used to decode a JSON document from a string that may
        have extraneous data at the end.

        """
        try:
            obj, end = self.scan_once(s, idx)
        except StopIteration as err:
            raise JSONDecodeError("Expecting value", s, err.value) from None
        return obj, end

****config.yaml****
.*:
  wbits: 'None'
  model_type: 'None'
  groupsize: 'None'
  pre_layer: 0
  mode: 'cai-chat'
llama-[0-9]*b-4bit$:
  wbits: 4
  model_type: 'llama'
.*-(4bit|int4)-(gr128|128g):
  wbits: 4
  groupsize: 128
.*-(gr128|128g)-(4bit|int4):
  wbits: 4
  groupsize: 128
.*-3bit-(gr128|128g):
  wbits: 3
  groupsize: 128
.*-(gr128|128g)-3bit:
  wbits: 3
  groupsize: 128
.*oasst-sft-1-pythia-12b:
  mode: 'instruct'
  instruction_template: 'Open Assistant'
.*vicuna:
  mode: 'instruct'
  instruction_template: 'Vicuna'
.*alpaca:
  mode: 'instruct'
  instruction_template: 'Alpaca'
.*alpaca-native-4bit:
  mode: 'instruct'
  instruction_template: 'Alpaca'
  wbits: 4
  groupsize: 128
```

### System Info

```shell
OS: Windows 10 1909 (WSL not supported in this version)
GPU: PNY XLR8 GeForce 2080 Ti Gaming Overclocked Edition
Driver: 457.30 (newer drivers don't work well in Win 10 1909)
CPU: AMD Ryzen 2700X
```

**Comment by skailHZ** [comment]
I have the same bug

**Comment by disarmyouwitha** [comment]
same

**Comment by CristianPi** [comment]
same

```bash
Traceback (most recent call last):
  File "/home/cristian/text-generation-webui/server.py", line 869, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/cristian/text-generation-webui/modules/models.py", line 53, in load_model
    model = AutoModelForCausalLM.from_pretrained(Path(f"{shared.args.model_dir}/{shared.model_name}"), low_cpu_mem_usage=True, torch_dtype=torch.bfloat16 if shared.args.bf16 else torch.float16)
  File "/home/cristian/.conda/envs/textgen/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 441, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/home/cristian/.conda/envs/textgen/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 916, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/cristian/.conda/envs/textgen/lib/python3.10/site-packages/transformers/configuration_utils.py", line 573, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/cristian/.conda/envs/textgen/lib/python3.10/site-packages/transformers/configuration_utils.py", line 661, in _get_config_dict
    raise EnvironmentError(
OSError: It looks like the config file at 'models/config.yaml' is not a valid JSON file.

```

**Comment by mrvirus9898** [comment]
You need to have a model, otherwise your WebUI is not going to function.
![Sad](https://user-images.githubusercontent.com/19317411/232190403-761d187c-02a0-494e-b2a4-a2d9b488388c.png)

1) Download a compatible model from Huggingface (see README). Do not use a script, just go there with your browser and download it.
2) Place the model in your models folder. The same folder were the offending "models/config.yaml". Recommend just putting the folder with all the model data in there, for example a "llama-13b" folder that has all the config, pytorch.bin files and such.
3) Run "start-webui".

![Now it work](https://user-images.githubusercontent.com/19317411/232190563-c3d8790c-25fb-4a62-b84c-196fa968b302.png)

Remember that this is not commercial software that will solve all your problems. It is work in progress, and research in progress. To engage in AI right now is to engage in research. And research is tough, so you will need to be tough too.

**Comment by disarmyouwitha** [comment]
no, the config.yaml file was added in the last 12hr and breaking things for installs that were working before.

**Comment by TreesPlay** [comment]
Thanks for the honest response. I've installed a model. It works now.

**Comment by mrvirus9898** [comment]
> no, the config.yaml file was added in the last 12hr and breaking things for installs that were working before.

Separate issue from TreesPlay's then. Is it the same error? Mind point out the bug report number?
