### ISSUE TITLE
RuntimeError: CUDA error: the launch timed out and was terminated

### ISSUE THREAD

**Issue by Ketorami** [oobabooga/text-generation-webui#1222]
### Describe the bug

This happens to me every time when I interrogate the AI frequently or more than 10 questions,Or that after I ask the question to get explanation long answer to more than 200 words.

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

Ask the AI to speak to explain what answers are more than 20 sentences or more than 200 words. Sometimes this happens when I frequently ask the AI without clearing the conversation. Most of them are more than 10 to 15 questions. .There may be times when answering a question takes between 3 minutes and 5 minutes while the AI is answering an error occurred

### Screenshot

![Screenshot 2023-04-15 130334](https://user-images.githubusercontent.com/101268214/232187862-98c33661-3ec8-44f3-8dc1-b97bc7fe5c84.png)

### Logs
```shell
Starting the web UI...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: E:\ChatGPT\oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary E:\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
Loading gpt4-x-alpaca-13b-native-4bit-128g...
Found the following quantized model: models\gpt4-x-alpaca-13b-native-4bit-128g\gpt-x-alpaca-13b-native-4bit-128g-cuda.pt
Loading model ...
Done.
Loaded the model in 66.97 seconds.
Loading the extension "gallery"... Ok.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Output generated in 190.32 seconds (0.22 tokens/s, 42 tokens, context 451, seed 1965935182)
Output generated in 13.73 seconds (0.15 tokens/s, 2 tokens, context 491, seed 1765164051)
Traceback (most recent call last):
  File "E:\ChatGPT\oobabooga-windows\text-generation-webui\modules\callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "E:\ChatGPT\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 245, in generate_with_callback
    shared.model.generate(**kwargs)
  File "E:\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1562, in generate
    return self.beam_sample(
  File "E:\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 3136, in beam_sample
    outputs = self(
  File "E:\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "E:\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\ChatGPT\oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa\llama_inference_offload.py", line 176, in forward
    torch.cuda.empty_cache()
  File "E:\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\torch\cuda\memory.py", line 133, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception in thread Thread-5 (gentask):
Traceback (most recent call last):
  File "E:\ChatGPT\oobabooga-windows\installer_files\env\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "E:\ChatGPT\oobabooga-windows\installer_files\env\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "E:\ChatGPT\oobabooga-windows\text-generation-webui\modules\callbacks.py", line 73, in gentask
    clear_torch_cache()
  File "E:\ChatGPT\oobabooga-windows\text-generation-webui\modules\callbacks.py", line 105, in clear_torch_cache
    torch.cuda.empty_cache()
  File "E:\ChatGPT\oobabooga-windows\installer_files\env\lib\site-packages\torch\cuda\memory.py", line 133, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### System Info

```shell
Windows : 11
Ram : 16GB
CPU : i5-11400
GPU : RTX 2060 Super 8GB
```

**Comment by mrvirus9898** [comment]
Okay that's a rough one. A launch timeout generally means the driver is killing the kernel process because it is taking too long to complete. This maybe an optimization issue with the underlying, but before going there can you confirm you are using the latest drivers on your 2060? I know it sounds cheap, but the driver is what's killing the process. 

I want to confirm your bug, but can you tell me how you were inducing the AI to give you greater then 200 word outputs? Mine keeps pausing at ~150 words or 199 tokens. Are you using a particular model?

**Comment by Ketorami** [comment]
I'm using the gpt4-x-alpaca-13b-native-4bit-128g model. 
Similar errors occurred with and it almost explained everything the same way except that only the names were different. The error this time was less than before but it was still look like same error. I took a screenshot of it 

![Screenshot 2023-04-15 124219](https://user-images.githubusercontent.com/101268214/232276385-995ab5ca-c60f-41f3-a413-f8167e6b890a.png)

**Comment by Ketorami** [comment]
after reinstalling I don't have any more problems. But I instinctively feel that the problem might be with my prompts because sometimes errors occur from my prompts being too coercive.
