### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by ameen-roayan** [oobabooga/text-generation-webui#1231]
### Describe the bug

I get this error when first trying to run any text through the system after i click generate 

Traceback (most recent call last):
  File "E:\AI\oobabooga-windows\installer_files\env\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\AI\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "E:\AI\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\AI\oobabooga-windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\AI\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\AI\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\AI\oobabooga-windows\installer_files\env\lib\site-packages\gradio\utils.py", line 490, in async_iteration
    return next(iterator)
  File "E:\AI\oobabooga-windows\text-generation-webui\modules\chat.py", line 218, in cai_chatbot_wrapper
    for history in chatbot_wrapper(text, state):
  File "E:\AI\oobabooga-windows\text-generation-webui\modules\chat.py", line 155, in chatbot_wrapper
    for reply in generate_reply(f"{prompt}{' ' if len(cumulative_reply) > 0 else ''}{cumulative_reply}", state, eos_token=eos_token, stopping_strings=stopping_strings):
  File "E:\AI\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 175, in generate_reply
    input_ids = encode(question, add_bos_token=state['add_bos_token'], truncation_length=get_max_prompt_length(state))
  File "E:\AI\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 31, in encode
    input_ids = shared.tokenizer.encode(str(prompt), return_tensors='pt', add_special_tokens=add_special_tokens)
AttributeError: 'NoneType' object has no attribute 'encode'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Installed as normal, downloaded a model, then this. 

### Screenshot

![image](https://user-images.githubusercontent.com/92278134/232225093-80043c97-a8f3-423c-bf97-604828519698.png)

### Logs

```shell
Starting the web UI...
Warning: --cai-chat is deprecated. Use --chat instead.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: E:\AI\oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary E:\AI\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
Loading the extension "gallery"... Ok.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "E:\AI\oobabooga-windows\installer_files\env\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\AI\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "E:\AI\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\AI\oobabooga-windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\AI\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\AI\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\AI\oobabooga-windows\installer_files\env\lib\site-packages\gradio\utils.py", line 490, in async_iteration
    return next(iterator)
  File "E:\AI\oobabooga-windows\text-generation-webui\modules\chat.py", line 218, in cai_chatbot_wrapper
    for history in chatbot_wrapper(text, state):
  File "E:\AI\oobabooga-windows\text-generation-webui\modules\chat.py", line 155, in chatbot_wrapper
    for reply in generate_reply(f"{prompt}{' ' if len(cumulative_reply) > 0 else ''}{cumulative_reply}", state, eos_token=eos_token, stopping_strings=stopping_strings):
  File "E:\AI\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 175, in generate_reply
    input_ids = encode(question, add_bos_token=state['add_bos_token'], truncation_length=get_max_prompt_length(state))
  File "E:\AI\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 31, in encode
    input_ids = shared.tokenizer.encode(str(prompt), return_tensors='pt', add_special_tokens=add_special_tokens)
AttributeError: 'NoneType' object has no attribute 'encode'
Traceback (most recent call last):
  File "E:\AI\oobabooga-windows\installer_files\env\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\AI\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "E:\AI\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\AI\oobabooga-windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\AI\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\AI\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\AI\oobabooga-windows\installer_files\env\lib\site-packages\gradio\utils.py", line 490, in async_iteration
    return next(iterator)
  File "E:\AI\oobabooga-windows\text-generation-webui\modules\chat.py", line 218, in cai_chatbot_wrapper
    for history in chatbot_wrapper(text, state):
  File "E:\AI\oobabooga-windows\text-generation-webui\modules\chat.py", line 155, in chatbot_wrapper
    for reply in generate_reply(f"{prompt}{' ' if len(cumulative_reply) > 0 else ''}{cumulative_reply}", state, eos_token=eos_token, stopping_strings=stopping_strings):
  File "E:\AI\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 175, in generate_reply
    input_ids = encode(question, add_bos_token=state['add_bos_token'], truncation_length=get_max_prompt_length(state))
  File "E:\AI\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 31, in encode
    input_ids = shared.tokenizer.encode(str(prompt), return_tensors='pt', add_special_tokens=add_special_tokens)
AttributeError: 'NoneType' object has no attribute 'encode'
```

### System Info

```shell
windows 11, python latest, 3090ti
```

**Comment by Klash11** [comment]
Did you fix it? I have the same problem

**Comment by Galactic-Kermit** [comment]
Same problem for me

**Comment by DrMemoryFish** [comment]
same problem for me.

**Comment by Andie-Squirrel** [comment]
I've been having this problem as well. Tried installing from an old commit but the damage was done and nothing changed.

![image](https://user-images.githubusercontent.com/119384539/232245397-bfeeabb1-816a-4778-aac7-cc2ec36e8a71.png)

**Comment by acezhd00123** [comment]
same issue

**Comment by MrJonSwift** [comment]
Same issue here. +1

**Comment by 7801943** [comment]
same problem,windows10 2080ti

**Comment by ionutradu252** [comment]
same problem here.. any fix?

**Comment by Andie-Squirrel** [comment]
> 

Still awaiting responses. I was told it had something to do with bitsandbytes, but that could just be an issue specifically with my installation.

**Comment by Galactic-Kermit** [comment]
Surprisingly, I also saw this name somewhere in the console. Maybe it has something to do with our problem

**Comment by Andie-Squirrel** [comment]
> 

If it's any help, here's the suggestion I got: https://github.com/oobabooga/text-generation-webui/issues/1249#issuecomment-1510030797

**Comment by Galactic-Kermit** [comment]
> > 
> 
> If it's any help, here's the suggestion I got: [#1249 (comment)](https://github.com/oobabooga/text-generation-webui/issues/1249#issuecomment-1509988191)

Gonna try it now and i tell you

**Comment by ameen-roayan** [comment]
sorry guys ! in the tab section you can select the model then everything works fine !

**Comment by Klash11** [comment]
> sorry guys ! in the tab section you can select the model then everything works fine !

tried that but doesnt work still am having the same error code

**Comment by ionutradu252** [comment]
> sorry guys ! in the tab section you can select the model then everything works fine ! 

i was doing that before and got the same error

**Comment by Andie-Squirrel** [comment]
> sorry guys ! in the tab section you can select the model then everything works fine !

Sorry but that doesn't seem to be working. I keep getting a TypeError so I think it may have something to do with bitsandbytes from pytorch for me.
