### ISSUE TITLE
Moddle downloader giving error

### ISSUE THREAD

**Issue by Bennett-Fourr** [oobabooga/text-generation-webui#1247]
### Describe the bug

Giving error when runing downloader

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Use the one click installer. Then run download-model.bat

### Logs

```shell
Input> a
Traceback (most recent call last):
  File "C:\Users\Other_side\Desktop\AI_things\oobabooga-windows\text-generation-webui\download-model.py", line 260, in <module>
    links, sha256, is_lora = get_download_links_from_huggingface(model, branch, text_only=args.text_only)
  File "C:\Users\Other_side\Desktop\AI_things\oobabooga-windows\text-generation-webui\download-model.py", line 98, in get_download_links_from_huggingface
    dict = json.loads(content)
  File "C:\Users\Other_side\Desktop\AI_things\oobabooga-windows\installer_files\env\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Other_side\Desktop\AI_things\oobabooga-windows\installer_files\env\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Other_side\Desktop\AI_things\oobabooga-windows\installer_files\env\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Press any key to continue . . .
```

### System Info

```shell
RTX 3060-Ti
32 GB of DDR4 ram
i711700
```

**Comment by mrvirus9898** [comment]
Download your first model from the Readme section.

**Comment by Bennett-Fourr** [comment]
I alredy have a lot of moddles installed. The auto installer is usfull for mass installing moddles

**Comment by Bennett-Fourr** [comment]
Running git pull seams to have fixed it
