### ISSUE TITLE
AttributeError: module 'quant_cuda' has no attribute 'vecquant4matmul'

### ISSUE THREAD

**Issue by thistleknot** [oobabooga/text-generation-webui#1259]
### Describe the bug

trying to run text-generation-webui

and the server starts up, but when I attempt to derive inference quant_cuda throws an error about not having a function.

hoping
nano /mnt/distvol/text-generation-webui/repositories/GPTQ-for-LLaMa/quant.py

hoping this change
quant_cuda.vecquant4matmul(x, self.qweight, y, self.scales, self.qzeros, self.groupsize)
to
quant_cuda.matvmul4(x, self.qweight, y, self.scales, self.qzeros, self.groupsize)

will work

confirmed that is not the correct approach.

I can only assume that this isn't supported in the version of cuda I have.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Followed instructions here:
https://github.com/oobabooga/text-generation-webui/wiki/LLaMA-model#4-bit-mode

mkdir repositories
cd repositories
git clone https://github.com/oobabooga/GPTQ-for-LLaMa.git -b cuda
cd GPTQ-for-LLaMa
python setup_cuda.py install

then using (after git cloning and git lfs pull)
python /mnt/distvol/text-generation-webui/server.py --model /mnt/distvol/text-generation-webui/models/alpaca-native-4bit --wbits 4 --groupsize 128 --pre_layer 20 --auto-devices --gpu-memory 3840MiB --listen

### Logs

```shell
Error in sys.excepthook:
Traceback (most recent call last):
  File "/mnt/distvol/python_user/python_user/gpt/lib/python3.9/site-packages/rich/console.py", line 1698, in print
    extend(render(renderable, render_options))
  File "/mnt/distvol/python_user/python_user/gpt/lib/python3.9/site-packages/rich/console.py", line 1334, in render
    yield from self.render(render_output, _options)
  File "/mnt/distvol/python_user/python_user/gpt/lib/python3.9/site-packages/rich/console.py", line 1330, in render
    for render_output in iter_render:
  File "/mnt/distvol/python_user/python_user/gpt/lib/python3.9/site-packages/rich/constrain.py", line 29, in __rich_console__
    yield from console.render(self.renderable, child_options)
  File "/mnt/distvol/python_user/python_user/gpt/lib/python3.9/site-packages/rich/console.py", line 1330, in render
    for render_output in iter_render:
  File "/mnt/distvol/python_user/python_user/gpt/lib/python3.9/site-packages/rich/panel.py", line 220, in __rich_console__
    lines = console.render_lines(renderable, child_options, style=style)
  File "/mnt/distvol/python_user/python_user/gpt/lib/python3.9/site-packages/rich/console.py", line 1370, in render_lines
    lines = list(
  File "/mnt/distvol/python_user/python_user/gpt/lib/python3.9/site-packages/rich/segment.py", line 292, in split_and_crop_lines
    for segment in segments:
  File "/mnt/distvol/python_user/python_user/gpt/lib/python3.9/site-packages/rich/console.py", line 1330, in render
    for render_output in iter_render:
  File "/mnt/distvol/python_user/python_user/gpt/lib/python3.9/site-packages/rich/padding.py", line 97, in __rich_console__
    lines = console.render_lines(
  File "/mnt/distvol/python_user/python_user/gpt/lib/python3.9/site-packages/rich/console.py", line 1370, in render_lines
    lines = list(
  File "/mnt/distvol/python_user/python_user/gpt/lib/python3.9/site-packages/rich/segment.py", line 292, in split_and_crop_lines
    for segment in segments:
  File "/mnt/distvol/python_user/python_user/gpt/lib/python3.9/site-packages/rich/console.py", line 1334, in render
    yield from self.render(render_output, _options)
  File "/mnt/distvol/python_user/python_user/gpt/lib/python3.9/site-packages/rich/console.py", line 1330, in render
    for render_output in iter_render:
  File "/mnt/distvol/python_user/python_user/gpt/lib/python3.9/site-packages/rich/syntax.py", line 612, in __rich_console__
    segments = Segments(self._get_syntax(console, options))
  File "/mnt/distvol/python_user/python_user/gpt/lib/python3.9/site-packages/rich/segment.py", line 668, in __init__
    self.segments = list(segments)
  File "/mnt/distvol/python_user/python_user/gpt/lib/python3.9/site-packages/rich/syntax.py", line 640, in _get_syntax
    text = self.highlight(processed_code, self.line_range)
  File "/mnt/distvol/python_user/python_user/gpt/lib/python3.9/site-packages/rich/syntax.py", line 512, in highlight
    text.append_tokens(tokens_to_spans())
  File "/mnt/distvol/python_user/python_user/gpt/lib/python3.9/site-packages/rich/text.py", line 991, in append_tokens
    for content, style in tokens:
  File "/mnt/distvol/python_user/python_user/gpt/lib/python3.9/site-packages/rich/syntax.py", line 498, in tokens_to_spans
    _token_type, token = next(tokens)
  File "/mnt/distvol/python_user/python_user/gpt/lib/python3.9/site-packages/rich/syntax.py", line 484, in line_tokenize
    for token_type, token in lexer.get_tokens(code):
  File "/mnt/distvol/python_user/python_user/gpt/lib/python3.9/site-packages/pygments/lexer.py", line 191, in streamer
    for _, t, v in self.get_tokens_unprocessed(text):
  File "/mnt/distvol/python_user/python_user/gpt/lib/python3.9/site-packages/pygments/lexer.py", line 633, in get_tokens_unprocessed
    m = rexmatch(text, pos)


>>> quant_cuda.matvmul <tab>
quant_cuda.matvmul16(  quant_cuda.matvmul2(   quant_cuda.matvmul3(   quant_cuda.matvmul4(   quant_cuda.matvmul8(
```

### System Info

```shell
python 3.9
oracle linux 8.4
cuda 11.5
```

**Comment by linqian66** [comment]
@thistleknot Maybe you have installed gptq package from pip. Remove gptq from pip and try again.
