### ISSUE TITLE
Triton GPTQ - Model Split doesn't work (MultiGPU)

### ISSUE THREAD

**Issue by practicaldreamer** [oobabooga/text-generation-webui#1298]
### Describe the bug

b57ffc2ec9bc32ff0cc82ba97edf4986ecf426fb says you're supporting GPTQ triton commit c90adef

Does not properly split model across gpus. `gpu-memory` doesn't have any effect.

Found repository aimed at inserting relevant accelerate lines... attempted patching the file myself but didn't help...
`https://github.com/qwopqwop200/GPTQ-for-LLaMa/compare/triton...catid:GPTQ-for-LLaMa-65B-2GPU:triton`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

python server.py --wbits 4 --gpu-memory 15 19 --listen --model llama-65b --verbose --chat --groupsize 128

### Logs

```shell
(textgen1) user@hostname:~/Documents/ooba/1/text-generation-webui$ python server.py --wbits 4 --gpu-memory 15 19 --listen --model llama-65b --verbose --chat --groupsize 128
bin /home/user/anaconda3/envs/textgen1/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
Loading llama-65b...
Found the following quantized model: models/llama-65b-4bit.safetensors
Loading model ...
Found 3 unique KN Linear values.
Warming up autotune cache ...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:26<00:00,  2.23s/it]
Found 1 unique fused mlp KN values.
Warming up autotune cache ...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:45<00:00,  3.77s/it]
Done.
Using the following device map for the quantized model: {'model.embed_tokens': 0, 'model.layers.0': 0, 'model.layers.1': 0, 'model.layers.2': 0, 'model.layers.3': 0, 'model.layers.4': 0, 'model.layers.5': 0, 'model.layers.6': 0, 'model.layers.7': 0, 'model.layers.8': 0, 'model.layers.9': 0, 'model.layers.10': 0, 'model.layers.11': 0, 'model.layers.12': 0, 'model.layers.13': 0, 'model.layers.14': 0, 'model.layers.15': 0, 'model.layers.16': 0, 'model.layers.17': 0, 'model.layers.18': 0, 'model.layers.19': 0, 'model.layers.20': 0, 'model.layers.21': 0, 'model.layers.22': 0, 'model.layers.23': 0, 'model.layers.24': 0, 'model.layers.25': 0, 'model.layers.26': 0, 'model.layers.27': 0, 'model.layers.28': 0, 'model.layers.29': 0, 'model.layers.30': 0, 'model.layers.31': 0, 'model.layers.32': 0, 'model.layers.33': 0, 'model.layers.34': 0, 'model.layers.35': 1, 'model.layers.36': 1, 'model.layers.37': 1, 'model.layers.38': 1, 'model.layers.39': 1, 'model.layers.40': 1, 'model.layers.41': 1, 'model.layers.42': 1, 'model.layers.43': 1, 'model.layers.44': 1, 'model.layers.45': 1, 'model.layers.46': 1, 'model.layers.47': 1, 'model.layers.48': 1, 'model.layers.49': 1, 'model.layers.50': 1, 'model.layers.51': 1, 'model.layers.52': 1, 'model.layers.53': 1, 'model.layers.54': 1, 'model.layers.55': 1, 'model.layers.56': 1, 'model.layers.57': 1, 'model.layers.58': 1, 'model.layers.59': 1, 'model.layers.60': 1, 'model.layers.61': 1, 'model.layers.62': 1, 'model.layers.63': 1, 'model.layers.64': 1, 'model.layers.65': 1, 'model.layers.66': 1, 'model.layers.67': 1, 'model.layers.68': 1, 'model.layers.69': 1, 'model.layers.70': 1, 'model.layers.71': 1, 'model.layers.72': 1, 'model.layers.73': 1, 'model.layers.74': 1, 'model.layers.75': 1, 'model.layers.76': 1, 'model.layers.77': 1, 'model.layers.78': 1, 'model.layers.79': 1, 'model.norm': 1, 'lm_head': 1}
Traceback (most recent call last):
  File "/home/user/Documents/ooba/1/text-generation-webui/server.py", line 905, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/user/Documents/ooba/1/text-generation-webui/modules/models.py", line 117, in load_model
    model = load_quantized(model_name)
  File "/home/user/Documents/ooba/1/text-generation-webui/modules/GPTQ_loader.py", line 189, in load_quantized
    model = accelerate.dispatch_model(model, device_map=device_map, offload_buffers=True)
  File "/home/user/anaconda3/envs/textgen1/lib/python3.10/site-packages/accelerate/big_modeling.py", line 370, in dispatch_model
    attach_align_device_hook_on_blocks(
  File "/home/user/anaconda3/envs/textgen1/lib/python3.10/site-packages/accelerate/hooks.py", line 495, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/home/user/anaconda3/envs/textgen1/lib/python3.10/site-packages/accelerate/hooks.py", line 495, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/home/user/anaconda3/envs/textgen1/lib/python3.10/site-packages/accelerate/hooks.py", line 495, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/home/user/anaconda3/envs/textgen1/lib/python3.10/site-packages/accelerate/hooks.py", line 471, in attach_align_device_hook_on_blocks
    add_hook_to_module(module, hook)
  File "/home/user/anaconda3/envs/textgen1/lib/python3.10/site-packages/accelerate/hooks.py", line 155, in add_hook_to_module
    module = hook.init_hook(module)
  File "/home/user/anaconda3/envs/textgen1/lib/python3.10/site-packages/accelerate/hooks.py", line 244, in init_hook
    set_module_tensor_to_device(module, name, self.execution_device)
  File "/home/user/anaconda3/envs/textgen1/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 147, in set_module_tensor_to_device
    new_value = old_value.to(device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 23.69 GiB total capacity; 22.54 GiB already allocated; 2.81 MiB free; 22.64 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### System Info

```shell
...-:::::-...                 user@hostname 
          .-MMMMMMMMMMMMMMM-.              ------------- 
      .-MMMM`..-:::::::-..`MMMM-.          OS: Linux Mint 21.1 x86_64 
    .:MMMM.:MMMMMMMMMMMMMMM:.MMMM:.        Kernel: 5.15.0-69-generic 
   -MMM-M---MMMMMMMMMMMMMMMMMMM.MMM-       Uptime: 1 hour, 54 mins 
 `:MMM:MM`  :MMMM:....::-...-MMMM:MMM:`    Packages: 2444 (dpkg) 
 :MMM:MMM`  :MM:`  ``    ``  `:MMM:MMM:    Shell: bash 5.1.16 
.MMM.MMMM`  :MM.  -MM.  .MM-  `MMMM.MMM.   Resolution: 2560x1440 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:   DE: Cinnamon 5.6.8 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM:MMM:   WM: Mutter (Muffin) 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:   WM Theme: Mint-Y-Dark-Aqua (Mint-Y) 
.MMM.MMMM`  :MM:--:MM:--:MM:  `MMMM.MMM.   Theme: Mint-Y-Dark-Aqua [GTK2/3] 
 :MMM:MMM-  `-MMMMMMMMMMMM-`  -MMM-MMM:    Icons: Mint-Y-Dark-Aqua [GTK2/3] 
  :MMM:MMM:`                `:MMM:MMM:     Terminal: gnome-terminal 
   .MMM.MMMM:--------------:MMMM.MMM.      CPU: AMD Ryzen 5 5600X (12) @ 3.700GHz 
     '-MMMM.-MMMMMMMMMMMMMMM-.MMMM-'       GPU: NVIDIA GeForce RTX 3090 
       '.-MMMM``--:::::--``MMMM-.'         GPU: NVIDIA GeForce RTX 3090 
            '-MMMMMMMMMMMMM-'              Memory: 9409MiB / 80344MiB 
               ``-:::::-``
```

**Comment by sgsdxzy** [comment]
Seems to work for me
```
CUDA_VISIBLE_DEVICES=0,1 python server.py --model LLM/baize-30b --wbit 8 --gpu-memory 16 16 --model_type llama --listen --no-fused_mlp
bin /home/sgsdxzy/mambaforge/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
Loading settings from settings.json...
Loading LLM/baize-30b...
Found the following quantized model: models/LLM/baize-30b/baize-30b-8bit.safetensors
Loading model ...
Found 4 unique KN Linear values.
Warming up autotune cache ...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:31<00:00,  2.62s/it]
Done.
Using the following device map for the quantized model: {'model.embed_tokens': 0, 'model.layers.0': 0, 'model.layers.1': 0, 'model.layers.2': 0, 'model.layers.3': 0, 'model.layers.4': 0, 'model.layers.5': 0, 'model.layers.6': 0, 'model.layers.7': 0, 'model.layers.8': 0, 'model.layers.9': 0, 'model.layers.10': 0, 'model.layers.11': 0, 'model.layers.12': 0, 'model.layers.13': 0, 'model.layers.14': 0, 'model.layers.15': 0, 'model.layers.16': 0, 'model.layers.17': 0, 'model.layers.18': 0, 'model.layers.19': 0, 'model.layers.20': 0, 'model.layers.21': 0, 'model.layers.22': 0, 'model.layers.23': 0, 'model.layers.24': 0, 'model.layers.25': 0, 'model.layers.26': 0, 'model.layers.27': 0, 'model.layers.28': 0, 'model.layers.29': 0, 'model.layers.30': 1, 'model.layers.31': 1, 'model.layers.32': 1, 'model.layers.33': 1, 'model.layers.34': 1, 'model.layers.35': 1, 'model.layers.36': 1, 'model.layers.37': 1, 'model.layers.38': 1, 'model.layers.39': 1, 'model.layers.40': 1, 'model.layers.41': 1, 'model.layers.42': 1, 'model.layers.43': 1, 'model.layers.44': 1, 'model.layers.45': 1, 'model.layers.46': 1, 'model.layers.47': 1, 'model.layers.48': 1, 'model.layers.49': 1, 'model.layers.50': 1, 'model.layers.51': 1, 'model.layers.52': 1, 'model.layers.53': 1, 'model.layers.54': 1, 'model.layers.55': 1, 'model.layers.56': 1, 'model.layers.57': 1, 'model.layers.58': 1, 'model.layers.59': 1, 'model.norm': 1, 'lm_head': 1}
Loaded the model in 45.46 seconds.
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
```
![image](https://user-images.githubusercontent.com/1655353/232402900-78f0d72e-6e02-4932-b418-7e46fe20b645.png)

`fused_mlp` seems to only work for Ampere and later? Can you try with `--no-fused_mlp`? That looks like to be the only difference.

**Comment by practicaldreamer** [comment]
well I'll be damned... I think that was it...

**Comment by practicaldreamer** [comment]
I can confirm indeed this issue is finally resolved.

`--no-fused_mlp` was **indeed needed** thank's @sgsdxzy 

this https://github.com/qwopqwop200/GPTQ-for-LLaMa/commit/5f1070d660fd43955ab4df724aaf63b4ce6d827f
and this https://github.com/oobabooga/text-generation-webui/commit/b57ffc2ec9bc32ff0cc82ba97edf4986ecf426fb
had something to do with it I think...
