### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory with 24gb vram in short convos

### ISSUE THREAD

**Issue by youngwolf0** [oobabooga/text-generation-webui#1304]
### Describe the bug

I have oobabooga ui working but it only works for a few messages, after a short back and forth it always starts getting memory issues and can't proceed.

I have an RTX 3090 so 24GB of vram which I would have thought would be enough to run this, the model I'm using is: OpenAssistant_oasst-sft-4-pythia-12b-epoch-3.5.

The screenshot shows as far as it can get in a test convo before hitting this issue, it won't respond further than that.  This happens 100% of the time for me.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

- Start up the ui
- Select model (in my case OpenAssistant_oasst-sft-4-pythia-12b-epoch-3.5)
- Have short conversation with assistant, tends to happen roughly after 5 back and fourth messages 

### Screenshot

![wq6tmpjhteua1](https://user-images.githubusercontent.com/3778200/232443394-9d6a7101-163c-4811-894d-22bb218efb8b.png)
![gf1y5n4mteua1](https://user-images.githubusercontent.com/3778200/232443472-b3ab1352-f036-47d0-8c1c-fb7651348a9b.png)

### Logs

```shell
Traceback (most recent call last):
  File "D:\oobabooga-windows\text-generation-webui\modules\callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "D:\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 252, in generate_with_callback
    shared.model.generate(**kwargs)
  File "D:\oobabooga-windows\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\oobabooga-windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1485, in generate
    return self.sample(
  File "D:\oobabooga-windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 2524, in sample
    outputs = self(
  File "D:\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\oobabooga-windows\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "D:\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\gpt_neox\modeling_gpt_neox.py", line 662, in forward
    outputs = self.gpt_neox(
  File "D:\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\oobabooga-windows\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "D:\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\gpt_neox\modeling_gpt_neox.py", line 553, in forward
    outputs = layer(
  File "D:\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\oobabooga-windows\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "D:\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\gpt_neox\modeling_gpt_neox.py", line 320, in forward
    attention_layer_outputs = self.attention(
  File "D:\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\oobabooga-windows\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "D:\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\gpt_neox\modeling_gpt_neox.py", line 147, in forward
    key = torch.cat((past_key, key), dim=-2)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 24.00 GiB total capacity; 23.16 GiB already allocated; 0 bytes free; 23.22 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Output generated in 1.71 seconds (0.58 tokens/s, 1 tokens, context 340, seed 1618296984)
```

### System Info

```shell
Windows 11
Nvidia
MSI GeForce RTX 3090 GAMING X TRIO 24G
```

**Comment by sgsdxzy** [comment]
Are you loaded in 8bit? Default is 16bit and a 12B model would use ~24G, leaving around nothing for storing activations.

**Comment by youngwolf0** [comment]
Yeah, that got it working, thanks a lot :)
