### ISSUE TITLE
No Google T5 based models (including FLAN-T5) work on oobabooga

### ISSUE THREAD

**Issue by raziel2001au** [oobabooga/text-generation-webui#1357]
### Describe the bug

Not sure what the issue is, but no models based on Google's T5 architecture work on oobabooga, which is extremely unfortunate since the FLAN-T5 models (the versions officially fine-tuned by Google) are extremely good. It's basically Google's LLaMA except it's officially released by Google under an extremely permissive Apache 2.0 license.

When loading a T5 based model you get the following error:
```
Traceback (most recent call last):
  File "D:\Development\oobabooga\text-generation-webui\server.py", line 913, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\Development\oobabooga\text-generation-webui\modules\models.py", line 186, in load_model
    model = LoaderClass.from_pretrained(checkpoint, **params)
  File "D:\Development\oobabooga\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 474, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers.models.t5.configuration_t5.T5Config'> for this kind of AutoModel: AutoModelForCausalLM.
Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MvpConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, Speech2Text2Config, TransfoXLConfig, TrOCRConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.
```

This might be a hugging face transformers bug, but I don't think I've ever gotten any T5 models working under oobabooga and using the following test code (official transformers example for T5 models) seems to work:
```
from transformers import T5Tokenizer, T5ForConditionalGeneration

tokenizer = T5Tokenizer.from_pretrained("google/flan-t5-small")
model = T5ForConditionalGeneration.from_pretrained("google/flan-t5-small")

input_text = "translate English to German: I love you"
input_ids = tokenizer(input_text, return_tensors="pt").input_ids

outputs = model.generate(input_ids)
print(tokenizer.decode(outputs[0]))
```
Gives this answer (it's been years since I studied German and this only seems half right to me, it added something weird at the end, but it's probably about what you can expect from using the smallest model in the FLAN-T5 series): Ich liebe Sie, ich wünsche Ihnen.

Fixing this should also fix the following issue (it's not just that one language model that's affected, but ALL models using the Google T5 LLM architecture): https://github.com/oobabooga/text-generation-webui/issues/769

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Just pull any of the models from the Google T5 series, the smallest would be this one here: google/flan-t5-small

It's literally a bit over 300mb so it's not a large model, but it's fine for demonstrating the issue.

### Logs

```shell
Loading flan-t5-small...
Auto-assiging --gpu-memory 15 for your GPU to try to prevent out-of-memory errors.
You can manually set other values.
Traceback (most recent call last):
  File "D:\Development\oobabooga\text-generation-webui\server.py", line 913, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\Development\oobabooga\text-generation-webui\modules\models.py", line 186, in load_model
    model = LoaderClass.from_pretrained(checkpoint, **params)
  File "D:\Development\oobabooga\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 474, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers.models.t5.configuration_t5.T5Config'> for this kind of AutoModel: AutoModelForCausalLM.
Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MvpConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, Speech2Text2Config, TransfoXLConfig, TrOCRConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.
```

### System Info

```shell
NVIDIA RTX 4080
```

**Comment by evangineer** [comment]
I'm having this exact issue with flan-alpaca-xl.

**Comment by evangineer** [comment]
My suspicion is an issue either with the import from transformers in `models.py` or with missing support in the `shared` module.  

I'm going to experiment and see what happens.

**Comment by evangineer** [comment]
Have been poking around the code trying to figure out to add support for a model that is supported by the underlying transformers library.

Just found this, BTW [157](https://github.com/oobabooga/text-generation-webui/issues/157)

**Comment by evangineer** [comment]
Seems to me that the support for DeepSpeed in `modules.models` is a good way to add T5 support.

If I can find time, I will have a go at making a patch and testing it, but if anybody else wants to have a go, I think we now have enough information to do it.

**Comment by raziel2001au** [comment]
I did notice one oddity with the implementation, it only gives new tokens as output, doesn't send the tokens you wrote as well, not sure if that's expected or not. Could be related to the small context size of T5 or perhaps the architecture... But I'm unsure.
