### ISSUE TITLE
Flexgen cannot import name 'Env'

### ISSUE THREAD

**Issue by elwolf6** [oobabooga/text-generation-webui#136]
```
Traceback (most recent call last):
  File "/home/luis/projects/AI/text-generation-webui/server.py", line 13, in <module>
    import modules.chat as chat
  File "/home/luis/projects/AI/text-generation-webui/modules/chat.py", line 15, in <module>
    from modules.text_generation import encode, generate_reply, get_max_prompt_length
  File "/home/luis/projects/AI/text-generation-webui/modules/text_generation.py", line 13, in <module>
    from modules.models import local_rank
  File "/home/luis/projects/AI/text-generation-webui/modules/models.py", line 19, in <module>
    from flexgen.flex_opt import (CompressionConfig, Env, OptLM, Policy,
ImportError: cannot import name 'Env' from 'flexgen.flex_opt' (/home/luis/projects/AI/text-generation-webui/FlexGen/flexgen/flex_opt.py)
```
Flexgen was installed with instructions on the wiki, command i ran was `python server.py --model pygmalion-6b --flexgen`

**Comment by elwolf6** [comment]
nvm i didn't read that it only works with opt models

**Comment by oobabooga** [comment]
This is indeed a bug even with the OPT models. They have changed the API today. I am trying to update it.

**Comment by oobabooga** [comment]
This seems to fix it:

https://github.com/oobabooga/text-generation-webui/commit/8e3e8a070f074282fd286532c9f1785682c7042d

(thanks for reporting, I wouldn't have noticed their update)
