### ISSUE TITLE
I cant install Module

### ISSUE THREAD

**Issue by IdkMaybeGamer** [oobabooga/text-generation-webui#1379]
### Describe the bug

I cant install module and i tried to search for solution from existing issues but i couldnt find any solution for this

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I dont know how to reproduce issue

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\pavli\OneDrive\Plocha\oobabooga_windows\text-generation-webui\download-model.py", line 260, in <module>
    links, sha256, is_lora = get_download_links_from_huggingface(model, branch, text_only=args.text_only)
  File "C:\Users\pavli\OneDrive\Plocha\oobabooga_windows\text-generation-webui\download-model.py", line 103, in get_download_links_from_huggingface
    fname = dict[i]['path']
KeyError: 0
Traceback (most recent call last):
  File "C:\Users\pavli\OneDrive\Plocha\oobabooga_windows\text-generation-webui\server.py", line 17, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
```

### System Info

```shell
Microsoft Windows 10 Home
Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz, 2496 Mhz
```

**Comment by AndreasBurbach** [comment]
Quick and dirty solution:
Change line 96 in download-model.py
```python
content = requests.get(f"{base}{page}{cursor.decode()}").content
```

to

```python
if len(cursor) > 0:
    page = f"/api/models/{model}/tree/{branch}?cursor="
    content = requests.get(f"{base}{page}{cursor.decode()}").content
else:
    page = f"/api/models/{model}/tree/{branch}"
    content = requests.get(f"{base}{page}").content
```
