### ISSUE TITLE
cannot import name 'ExecutionEnv' from 'flexgen.flex_opt'

### ISSUE THREAD

**Issue by poiuty** [oobabooga/text-generation-webui#139]
```
# python3 server.py --model opt-6.7b --gpu-memory 10 --flexgen

Traceback (most recent call last):
  File "/home/chat/text-generation-webui/server.py", line 13, in <module>
    import modules.chat as chat
  File "/home/chat/text-generation-webui/modules/chat.py", line 15, in <module>
    from modules.text_generation import encode, generate_reply, get_max_prompt_length
  File "/home/chat/text-generation-webui/modules/text_generation.py", line 13, in <module>
    from modules.models import local_rank
  File "/home/chat/text-generation-webui/modules/models.py", line 19, in <module>
    from flexgen.flex_opt import (CompressionConfig, ExecutionEnv, OptLM,
ImportError: cannot import name 'ExecutionEnv' from 'flexgen.flex_opt' (/home/chat/.local/lib/python3.10/site-packages/flexgen/flex_opt.py)
```

**Comment by poiuty** [comment]
Update to 0.0.16 fix it.

```
# pip show flexgen
Name: flexgen
Version: 0.1.5

# pip install flexgen -U
Successfully installed flexgen-0.1.6
```
