### ISSUE TITLE
Unable to run with latest git pull, getting triton errors when trying to run a cpu model.

### ISSUE THREAD

**Issue by keninishna** [oobabooga/text-generation-webui#1396]
### Describe the bug

I was able to run ggml models on cpu before I ran a git pull and pip install -r requirements.txt -U because of the newer q4.1 and q4.2 models out now but I am getting a error trying to load anything

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

git pull and try to run a ggml cpu model.

### Logs

```shell
(textgen) user@ubuntu:~/text-generation-webui$ python server.py --model llamacpp-vicuna13b-4b --threads 8
Gradio HTTP request redirected to localhost :)
bin /home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Traceback (most recent call last):
  File "/home/user/text-generation-webui/server.py", line 43, in <module>
    from modules import api, chat, shared, training, ui
  File "/home/user/text-generation-webui/modules/training.py", line 13, in <module>
    from peft import LoraConfig, get_peft_model, set_peft_model_state_dict, prepare_model_for_int8_training
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/peft/__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/peft/mapping.py", line 16, in <module>
    from .peft_model import (
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/peft/peft_model.py", line 31, in <module>
    from .tuners import AdaLoraModel, LoraModel, PrefixEncoder, PromptEmbedding, PromptEncoder
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/peft/tuners/__init__.py", line 20, in <module>
    from .lora import LoraConfig, LoraModel
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/peft/tuners/lora.py", line 40, in <module>
    import bitsandbytes as bnb
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 15, in <module>
    from .nn import modules
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/nn/__init__.py", line 6, in <module>
    from .triton_based_modules import SwitchBackLinear, SwitchBackLinearGlobal, SwitchBackLinearVectorwise, StandardLinear
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/nn/triton_based_modules.py", line 8, in <module>
    from bitsandbytes.triton.dequantize_rowwise import dequantize_rowwise
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/triton/dequantize_rowwise.py", line 10, in <module>
    import triton
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/triton/__init__.py", line 20, in <module>
    from .runtime import (
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/triton/runtime/__init__.py", line 1, in <module>
    from .autotuner import Config, Heuristics, autotune, heuristics
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 7, in <module>
    from ..compiler import OutOfResources
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/triton/compiler.py", line 1888, in <module>
    @static_vars(amdgcn_bitcode_paths = _get_amdgcn_bitcode_paths())
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/triton/compiler.py", line 1867, in _get_amdgcn_bitcode_paths
    gfx_arch = _get_amdgcn_bitcode_paths.discovered_gfx_arch_fulldetails[1]
TypeError: 'NoneType' object is not subscriptable
```

### System Info

```shell
ubuntu 20, 32gb ram, intel server cpu.
```

**Comment by keninishna** [comment]
I was able to make it work with a work around. in /modules/training.py I commented out line 13
#from peft import LoraConfig, get_peft_model, set_peft_model_state_dict, prepare_model_for_int8_training

I also needed to comment out line line 4 in /modules/LoRa.py
#from peft import PeftModel

now it runs fine. Since training on CPU only is pointless there is no downside to this.

**Comment by 748391** [comment]
Hi,

I have the same error on an ubuntu vm running with an AMD Radeon Instinct MI25, when trying to run server.py
Commenting the lines as suggested above didn't work for me.
I'm a beginner in this field and don't know what I could do to fix this.
Does anyone have any ideas?
