### ISSUE TITLE
Port used error 

### ISSUE THREAD

**Issue by HeenLight** [oobabooga/text-generation-webui#1407]
### Describe the bug

After changing type of interface from default to chat or other in web ui. Its crashes saying that port already in use, and suggests to:
OSError: Port {Port Number} is in use. If a gradio.Blocks is running on the port, you can close() it or gradio.close_all().

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Start webui
2.  Change type of interface in web
3.  Check console

### Logs

```shell
Traceback (most recent call last):
  File "/home/roman/.local/lib/python3.10/site-packages/gradio/networking.py", line 119, in start_server
    s.bind((LOCALHOST_NAME, server_port))
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/roman/oobabooga_linux/text-generation-webui/server.py", line 929, in <module>
    create_interface()
  File "/home/roman/oobabooga_linux/text-generation-webui/server.py", line 854, in create_interface
    shared.gradio['interface'].launch(prevent_thread_lock=True, share=shared.args.share, server_name=shared.args.listen_host or '0.0.0.0', server_port=shared.args.listen_port, inbrowser=shared.args.auto_launch, auth=auth)
  File "/home/roman/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1596, in launch
    server_name, server_port, local_url, app, server = networking.start_server(
  File "/home/roman/.local/lib/python3.10/site-packages/gradio/networking.py", line 122, in start_server
    raise OSError(
OSError: Port 5050 is in use. If a gradio.Blocks is running on the port, you can close() it or gradio.close_all().
```

### System Info

```shell
Ubuntu server 22.04
Intel Xeon e5_2620 v2
16GB Ram
```

**Comment by LaaZa** [comment]
I have noticed that on linux the port is not being released immediately. This can happen when doing reload or even after closing the program in other ways. But since reload will try to use the same port again immediately it will fail.

Possibly related to this: [#3675](https://github.com/gradio-app/gradio/issues/3675)

To me it seems to happen if the port was explicitly set and not when it is different from 7860.

**Comment by CyberTimon** [comment]
I have the same issue and would love to get a fix. I'm on linux ubuntu 20.04

**Comment by HeenLight** [comment]
> I have noticed that on linux the port is not being released immediately. This can happen when doing reload or even after closing the program in other ways. But since reload will try to use the same port again immediately it will fail.
> 
> Possibly related to this: [#3675](https://github.com/gradio-app/gradio/issues/3675)
> 
> To me it seems to happen if the port was explicitly set and not just when it is different from 7860.

Yes is et as you see in log custom port, so i think code not release it, dont know why.



> Have you tried a different port? Is another application using port 5050? Try running the following command and sending back the results.
> 
> ```
> sudo netstat -tulpn | grep LISTEN
> ```

There no programs' in my system that use port 5050 or 7680.

**Comment by kenfink** [comment]
WSL Ubuntu.  Same issue.  My only way around it so far is to use a different port on each CLI server start, and can't restart interface from UI.  If I can kill the process in windows sometimes I get the port back, but not consistently.

Can someone advise how to use close_all from command line?  Or a place to add it into ooga code when restarting the server? Can it even reach other processes that haven't released the port?
