### ISSUE TITLE
ModuleNotFoundError: No module named 'llama_inference_offload'

### ISSUE THREAD

**Issue by ItsNickeler** [oobabooga/text-generation-webui#1425]
### Describe the bug

I have an issue where I run text-generation-webui on my Windows PC with CPU mode, but I can't seem to get the link to show up and this message occurs:

Gradio HTTP request redirected to localhost :)
bin D:\oobaboogawindows\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll
D:\oobaboogawindows\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading mayaeary_pygmalion-6b_dev-4bit-128g...
Traceback (most recent call last):
  File "D:\oobaboogawindows\oobabooga_windows\text-generation-webui\server.py", line 917, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\oobaboogawindows\oobabooga_windows\text-generation-webui\modules\models.py", line 125, in load_model
    from modules.GPTQ_loader import load_quantized
  File "D:\oobaboogawindows\oobabooga_windows\text-generation-webui\modules\GPTQ_loader.py", line 14, in <module>
    import llama_inference_offload
ModuleNotFoundError: No module named 'llama_inference_offload'

Done!
Press any key to continue . . .

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I just installed by following the steps found in this video: https://www.youtube.com/watch?v=FOyqcETVUCs

### Screenshot

![image](https://user-images.githubusercontent.com/20646237/233503362-bd80cd9b-ec68-4376-9124-51280eeb7a09.png)

### Logs

```shell
Gradio HTTP request redirected to localhost :)
bin D:\oobaboogawindows\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll
D:\oobaboogawindows\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading mayaeary_pygmalion-6b_dev-4bit-128g...
Traceback (most recent call last):
  File "D:\oobaboogawindows\oobabooga_windows\text-generation-webui\server.py", line 917, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\oobaboogawindows\oobabooga_windows\text-generation-webui\modules\models.py", line 125, in load_model
    from modules.GPTQ_loader import load_quantized
  File "D:\oobaboogawindows\oobabooga_windows\text-generation-webui\modules\GPTQ_loader.py", line 14, in <module>
    import llama_inference_offload
ModuleNotFoundError: No module named 'llama_inference_offload'

Done!
Press any key to continue . . .
```

### System Info

```shell
Windows 10, Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz, 8GB RAM, 64-bit OS, 64-bit processor
```

**Comment by danpizzy** [comment]
try and download a ggml version of the model should probably work except the model is pygmalion

**Comment by catalpaaa** [comment]
pull the new gptq for llama, its fixed

**Comment by xNul** [comment]
you're trying to run a 4bit GPTQ model in CPU mode, but GPTQ only exists in GPU mode. Download a model which can be run in CPU model like a ggml model or a model in the Hugging Face format (for example "llama-7b-hf").

**Comment by yhyu13** [comment]
@ItsNickeler  you need to compile GPTQ cuda from source into wheel and install that whl. See the docker/Dockerfile for reference. You could also simply use the docker file. But If I recall it correctly, there is bug in the Dockerfile. You actually need to first install `pip install wheel` in order to build GPTQ cuda wheel, otherwise the bdist flag is nor recognized @oobabooga

**Comment by aprimostka** [comment]
mkdir repositories
cd repositories
git clone https://github.com/qwopqwop200/GPTQ-for-LLaMa

**Comment by Zengrath** [comment]
> mkdir repositories cd repositories git clone https://github.com/qwopqwop200/GPTQ-for-LLaMa

I tried this now I get error   File "C:\oobabooga_windows\text-generation-webui\repositories\GPTQ-for-LLaMa\gptq.py", line 8, in <module>
    from texttable import Texttable
ModuleNotFoundError: No module named 'texttable'

Any idea how to fix this one as well?

**Comment by xNul** [comment]
Yes because the model name is `mayaeary_pygmalion-6b_dev-4bit-128g` which means it is a GPTQ model. GPTQ uses CUDA and CUDA only works with Nvidia GPUs. The only models that support CPU mode are `ggml` and `hf` models. I agree it should be more clear

**Comment by vmajor** [comment]
> > mkdir repositories cd repositories git clone https://github.com/qwopqwop200/GPTQ-for-LLaMa
> 
> I tried this now I get error File "C:\oobabooga_windows\text-generation-webui\repositories\GPTQ-for-LLaMa\gptq.py", line 8, in from texttable import Texttable ModuleNotFoundError: No module named 'texttable'
> 
> Any idea how to fix this one as well?
> 
> EDIT: Ok I did pipinstall on last missing moduless, now i get error: File "C:\Users*\AppData\Roaming\Python\Python310\site-packages\torch\cuda__init__.py", line 239, in _lazy_init raise AssertionError("Torch not compiled with CUDA enabled") AssertionError: Torch not compiled with CUDA enabled
> 
> My assumption is someone else up above is correct in that this model will not work on CPU mode. It would be probably a good idea for AMD users who are forced to use CPU to provide clarification on which type of models is supported in CPU mode to make this less confusing.

```
cd ~/text-generation-webui/repositories/GPTQ-for-LLaMa
pip install -r requirements.txt
```
