### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ghostinanutshell** [oobabooga/text-generation-webui#1458]
### Describe the bug

(base) C:\Users\sxxxs\Downloads\oobabooga_windows\oobabooga_windows\text-generation-webui>python server.py --chat --model llama-7b --no-stream
Gradio HTTP request redirected to localhost :)
Traceback (most recent call last):
  File "C:\Users\sxxxs\Downloads\oobabooga_windows\oobabooga_windows\text-generation-webui\server.py", line 43, in <module>
    from modules import api, chat, shared, training, ui
  File "C:\Users\sxxxs\Downloads\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\training.py", line 13, in <module>
    from peft import (LoraConfig, get_peft_model, prepare_model_for_int8_training,
  File "C:\Users\sxxxs\miniconda3\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "C:\Users\sxxxs\miniconda3\lib\site-packages\peft\mapping.py", line 16, in <module>
    from .peft_model import (
  File "C:\Users\sxxxs\miniconda3\lib\site-packages\peft\peft_model.py", line 31, in <module>
    from .tuners import AdaLoraModel, LoraModel, PrefixEncoder, PromptEmbedding, PromptEncoder
  File "C:\Users\sxxxs\miniconda3\lib\site-packages\peft\tuners\__init__.py", line 20, in <module>
    from .lora import LoraConfig, LoraModel
  File "C:\Users\sxxxs\miniconda3\lib\site-packages\peft\tuners\lora.py", line 40, in <module>
    import bitsandbytes as bnb
  File "C:\Users\sxxxs\miniconda3\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\sxxxs\miniconda3\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\sxxxs\miniconda3\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\sxxxs\miniconda3\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\sxxxs\miniconda3\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\sxxxs\miniconda3\lib\site-packages\bitsandbytes\cextension.py", line 8, in <module>
    from bitsandbytes.cuda_setup.main import CUDASetup
  File "C:\Users\sxxxs\miniconda3\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 135
    self.lib = ct.cdll.LoadLibrary(str(binary_path))s
                                                    ^
SyntaxError: invalid syntax

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

python server.py --chat --model llama-7b --no-stream

### Logs

```shell
no
```

### System Info

```shell
rtx 3080 intel cpu 10gen windows 11
```

**Comment by ghostinanutshell** [comment]
I RESTARTED THE PC AND IT WORKS NOW.
