### ISSUE TITLE
CUDA OOM with GPTQ-for-LLaMa

### ISSUE THREAD

**Issue by quarterturn** [oobabooga/text-generation-webui#1466]
### Describe the bug

when running the oobabooga fork of GPTQ-for-LLaMa, after about 28 replies a CUDA OOM exception is thrown.

```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 24.00 MiB (GPU 0; 15.89 GiB total capacity; 14.72 GiB already allocated; 18.12 MiB free; 15.21 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Output generated in 20.38 seconds (0.05 tokens/s, 1 tokens, context 1787, seed 1814643300)
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

run:
```
~/text-generation-webui$ python server.py --model llama-30b-4bit-128g  --gpu-memory 10 16  --chat --listen --wbits 4 --groupsize 128
```
using:
```
git show
commit a6ef2429fa5a23de0bb1a28e50361f282daca9a2 (HEAD -> main, origin/main, origin/HEAD)
Author: Lou Bernardi <loufeadmin@gmail.com>
Date:   Fri Apr 21 11:54:50 2023 -0400

    Add "do not download" and "download from HF" to download-model.py (#1439)

diff --git a/download-model.py b/download-model.py
index c35cf83..a095f39 100644
--- a/download-model.py
+++ b/download-model.py
@@ -41,13 +41,17 @@ def select_model_from_default_options():
         char = chr(ord('A') + i)
         choices[char] = name
         print(f"{char}) {name}")
-    char = chr(ord('A') + len(models))
-    print(f"{char}) None of the above")
+    char_hugging = chr(ord('A') + len(models))
+    print(f"{char_hugging}) Manually specify a Hugging Face model")
+    char_exit = chr(ord('A') + len(models) + 1)
+    print(f"{char_exit}) Do not download a model")

     print()
     print("Input> ", end='')
     choice = input()[0].strip().upper()
-    if choice == char:
+    if choice == char_exit:
+        exit()
+    elif choice == char_hugging:
         print("""\nThen type the name of your desired Hugging Face model in the format organization/name.

 Examples:
```

and:
```
commit 57a26292ed583528d9941e79915824c5af012279 (HEAD -> cuda, origin/cuda, origin/HEAD)
Author: oobabooga <112222186+oobabooga@users.noreply.github.com>
Date:   Fri Apr 14 11:28:33 2023 -0300

    Update requirements.txt

diff --git a/requirements.txt b/requirements.txt
index 9c2f17e..12f22ce 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,5 +1,5 @@
 safetensors==0.3.0
 datasets==2.10.1
 sentencepiece
-git+https://github.com/huggingface/transformers
+transformers==4.28.0
 accelerate==0.18.0
```

### Logs

```shell
(textgen) qtrn@pve:~/text-generation-webui$ python server.py --model llama-30b-4bit-128g  --gpu-memory 10 16  --chat --listen --wbits 4 --groupsize 128
Gradio HTTP request redirected to localhost :)
bin /home/qtrn/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
Loading llama-30b-4bit-128g...
Found the following quantized model: models/llama-30b-4bit-128g/llama-30b-4bit-128g.safetensors
Loading model ...
Done.
Using the following device map for the quantized model: {'model.embed_tokens': 0, 'model.layers.0': 0, 'model.layers.1': 0, 'model.layers.2': 0, 'model.layers.3': 0, 'model.layers.4': 0, 'model.layers.5': 0, 'model.layers.6': 0, 'model.layers.7': 0, 'model.layers.8': 0, 'model.layers.9': 0, 'model.layers.10': 0, 'model.layers.11': 0, 'model.layers.12': 0, 'model.layers.13': 0, 'model.layers.14': 0, 'model.layers.15': 0, 'model.layers.16': 0, 'model.layers.17': 0, 'model.layers.18': 0, 'model.layers.19': 0, 'model.layers.20': 0, 'model.layers.21': 0, 'model.layers.22': 0, 'model.layers.23': 0, 'model.layers.24': 0, 'model.layers.25': 0, 'model.layers.26': 0, 'model.layers.27': 0, 'model.layers.28': 0, 'model.layers.29': 0, 'model.layers.30': 0, 'model.layers.31': 0, 'model.layers.32': 0, 'model.layers.33': 0, 'model.layers.34': 1, 'model.layers.35': 1, 'model.layers.36': 1, 'model.layers.37': 1, 'model.layers.38': 1, 'model.layers.39': 1, 'model.layers.40': 1, 'model.layers.41': 1, 'model.layers.42': 1, 'model.layers.43': 1, 'model.layers.44': 1, 'model.layers.45': 1, 'model.layers.46': 1, 'model.layers.47': 1, 'model.layers.48': 1, 'model.layers.49': 1, 'model.layers.50': 1, 'model.layers.51': 1, 'model.layers.52': 1, 'model.layers.53': 1, 'model.layers.54': 1, 'model.layers.55': 1, 'model.layers.56': 1, 'model.layers.57': 1, 'model.layers.58': 1, 'model.layers.59': 1, 'model.norm': 1, 'lm_head': 1}
Loaded the model in 15.29 seconds.
Loading the extension "gallery"... Ok.
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Output generated in 8.03 seconds (1.50 tokens/s, 12 tokens, context 44, seed 583000151)
Output generated in 13.84 seconds (1.59 tokens/s, 22 tokens, context 97, seed 1305679894)
Output generated in 9.87 seconds (1.82 tokens/s, 18 tokens, context 132, seed 2112550698)
Output generated in 11.30 seconds (1.95 tokens/s, 22 tokens, context 163, seed 899431139)
Output generated in 9.83 seconds (1.53 tokens/s, 15 tokens, context 215, seed 1238343898)
Output generated in 10.48 seconds (1.53 tokens/s, 16 tokens, context 250, seed 1975915339)
Output generated in 14.94 seconds (1.87 tokens/s, 28 tokens, context 330, seed 858913677)
Output generated in 12.83 seconds (1.40 tokens/s, 18 tokens, context 414, seed 1072633322)
Output generated in 11.94 seconds (1.09 tokens/s, 13 tokens, context 455, seed 1406978912)
Output generated in 12.51 seconds (1.12 tokens/s, 14 tokens, context 491, seed 1446995168)
Output generated in 15.11 seconds (1.26 tokens/s, 19 tokens, context 540, seed 869863242)
Output generated in 11.58 seconds (0.52 tokens/s, 6 tokens, context 620, seed 1878717127)
Output generated in 12.24 seconds (0.49 tokens/s, 6 tokens, context 668, seed 1775840336)
Output generated in 19.57 seconds (1.07 tokens/s, 21 tokens, context 812, seed 1849932937)
Output generated in 19.70 seconds (0.86 tokens/s, 17 tokens, context 943, seed 1123629311)
Output generated in 16.35 seconds (0.55 tokens/s, 9 tokens, context 989, seed 324918983)
Output generated in 16.81 seconds (0.42 tokens/s, 7 tokens, context 1042, seed 545774759)
Output generated in 24.99 seconds (0.96 tokens/s, 24 tokens, context 1086, seed 826245718)
Output generated in 21.29 seconds (0.70 tokens/s, 15 tokens, context 1148, seed 1270818585)
Output generated in 18.81 seconds (0.43 tokens/s, 8 tokens, context 1192, seed 397990654)
Output generated in 20.61 seconds (0.53 tokens/s, 11 tokens, context 1266, seed 279178270)
Output generated in 23.04 seconds (0.56 tokens/s, 13 tokens, context 1361, seed 1936392796)
Output generated in 26.95 seconds (0.67 tokens/s, 18 tokens, context 1433, seed 394190531)
Output generated in 29.18 seconds (0.72 tokens/s, 21 tokens, context 1534, seed 466998636)
Output generated in 34.32 seconds (0.79 tokens/s, 27 tokens, context 1574, seed 976136029)
Output generated in 54.22 seconds (1.09 tokens/s, 59 tokens, context 1638, seed 2147100625)
Traceback (most recent call last):
  File "/home/qtrn/text-generation-webui/modules/callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/home/qtrn/text-generation-webui/modules/text_generation.py", line 252, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/qtrn/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/qtrn/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1485, in generate
    return self.sample(
  File "/home/qtrn/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2524, in sample
    outputs = self(
  File "/home/qtrn/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/qtrn/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward
    return module._hf_hook.post_forward(module, output)
  File "/home/qtrn/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 292, in post_forward
    output = send_to_device(output, self.input_device)
  File "/home/qtrn/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 133, in send_to_device
    return recursively_apply(_send_to_device, tensor, device, non_blocking, test_type=_has_to_method)
  File "/home/qtrn/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 93, in recursively_apply
    {
  File "/home/qtrn/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 94, in <dictcomp>
    k: recursively_apply(
  File "/home/qtrn/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 82, in recursively_apply
    return honor_type(
  File "/home/qtrn/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 53, in honor_type
    return type(obj)(generator)
  File "/home/qtrn/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 85, in <genexpr>
    recursively_apply(
  File "/home/qtrn/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 82, in recursively_apply
    return honor_type(
  File "/home/qtrn/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 53, in honor_type
    return type(obj)(generator)
  File "/home/qtrn/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 85, in <genexpr>
    recursively_apply(
  File "/home/qtrn/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 101, in recursively_apply
    return func(data, *args, **kwargs)
  File "/home/qtrn/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 126, in _send_to_device
    return t.to(device, non_blocking=non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 24.00 MiB (GPU 0; 15.89 GiB total capacity; 14.72 GiB already allocated; 18.12 MiB free; 15.21 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Output generated in 20.38 seconds (0.05 tokens/s, 1 tokens, context 1787, seed 1814643300)
```

### System Info

```shell
Fri Apr 21 15:49:19 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla P100-PCIE-16GB            On | 00000000:05:00.0 Off |                    0 |
| N/A   42C    P0               44W / 250W|  16238MiB / 16384MiB |     61%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE-16GB            On | 00000000:42:00.0 Off |                    0 |
| N/A   43C    P0               70W / 250W|  11090MiB / 16384MiB |      3%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     51151      C   python                                    16236MiB |
|    1   N/A  N/A     51151      C   python                                    11088MiB |
+---------------------------------------------------------------------------------------+
CPU 1	Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz	Model 62 Stepping 4	2400 MHz	Presence Detected	12	
CPU 2	Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz	Model 62 Stepping 4	2400 MHz	Presence Detected	12
Installed Capacity 	128.00 GB
Linux pve 5.15.85-1-pve #1 SMP PVE 5.15.85-1 (2023-02-01T00:00Z) x86_64 GNU/Linux
Python 3.10.9
```

**Comment by Ph0rk0z** [comment]
Use a non accelerated browser or check with nvtop.  You are so close. Maybe the layer you cannot split is what is putting you over.

**Comment by quarterturn** [comment]
I tried adjusting the GPU memory split to 15/16, but it threw an OOM exception even faster.

```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 228.00 MiB (GPU 0; 15.89 GiB total capacity; 14.59 GiB already allocated; 200.12 MiB free; 15.03 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Output generated in 4.27 seconds (0.00 tokens/s, 0 tokens, context 247, seed 1844804111)
```

here's the GPU state:
```
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      6494      C   python                                    14964MiB |
|    1   N/A  N/A      6494      C   python                                     4224MiB |
+---------------------------------------------------------------------------------------+
```

I think basically GPU parallelism doesn't work properly at the moment.

**Comment by Ph0rk0z** [comment]
Possible.. but certain layers must be on one device.

**Comment by HideLord** [comment]
Yeah, same problem. After the context grows to a certain point, I get the same error.

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.89.02    Driver Version: 525.89.02    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:04:00.0  On |                  N/A |
|  0%   51C    P8    43W / 265W |  19531MiB / 24576MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  On   | 00000000:08:00.0 Off |                  N/A |
|  0%   56C    P8    38W / 265W |      8MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1255      G   /usr/lib/xorg/Xorg                177MiB |
|    0   N/A  N/A      1740      G   ...RendererForSitePerProcess       16MiB |
|    0   N/A  N/A      2217      G   ...615638267902024210,131072      210MiB |
|    0   N/A  N/A     10454      C   python                          19122MiB |
|    1   N/A  N/A      1255      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+
```

```
Traceback (most recent call last):
  File "/home/hidelord/Desktop/LLM/Oobabooga/text-generation-webui/modules/callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/text-generation-webui/modules/text_generation.py", line 252, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/transformers/generation/utils.py", line 1530, in generate
    return self.contrastive_search(
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/transformers/generation/utils.py", line 2023, in contrastive_search
    outputs = self(
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 688, in forward
    outputs = self.model(
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 578, in forward
    layer_outputs = decoder_layer(
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 293, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 211, in forward
    value_states = torch.cat([past_key_value[1], value_states], dim=2)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 23.67 GiB total capacity; 20.76 GiB already allocated; 30.38 MiB free; 21.76 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Output generated in 2.34 seconds (1.28 tokens/s, 3 tokens, context 273, seed 1736422306)
Traceback (most recent call last):
  File "/home/hidelord/Desktop/LLM/Oobabooga/text-generation-webui/modules/callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/text-generation-webui/modules/text_generation.py", line 252, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/transformers/generation/utils.py", line 1530, in generate
    return self.contrastive_search(
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/transformers/generation/utils.py", line 2023, in contrastive_search
    outputs = self(
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 688, in forward
    outputs = self.model(
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 578, in forward
    layer_outputs = decoder_layer(
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 293, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 211, in forward
    value_states = torch.cat([past_key_value[1], value_states], dim=2)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 23.67 GiB total capacity; 20.71 GiB already allocated; 23.62 MiB free; 21.78 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Output generated in 1.34 seconds (0.75 tokens/s, 1 tokens, context 275, seed 1580251560)
Traceback (most recent call last):
  File "/home/hidelord/Desktop/LLM/Oobabooga/text-generation-webui/modules/callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/text-generation-webui/modules/text_generation.py", line 252, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/transformers/generation/utils.py", line 1530, in generate
    return self.contrastive_search(
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/transformers/generation/utils.py", line 2062, in contrastive_search
    item = item[range(batch_size), selected_idx, ...]  # [B, num_head, seq_len, esz]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 23.67 GiB total capacity; 20.74 GiB already allocated; 31.81 MiB free; 21.76 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Output generated in 1.18 seconds (0.00 tokens/s, 0 tokens, context 276, seed 1794854483)
```

Here's my starting script: `python server.py --gpu-memory 20 20 --model_type LLaMA --notebook --model supercot-30b --wbits 4 --groupsize 128 --no-quant_attn --xformers`

Also tried with `--gpu-memory 16 16` and it loads some layers to the second GPU, but it still crashes with OOM after a certain point.

**Comment by Ph0rk0z** [comment]
Something is wrong with accelerate because I think we are using it correctly.
