### ISSUE TITLE
Can't run the triton models with the monkey patch

### ISSUE THREAD

**Issue by BadisG** [oobabooga/text-generation-webui#1469]
### Describe the bug

Hello, 

I can't run my Triton models with the monkey patch for Loras

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

python server.py --monkey-patch --model_type llama 
Successfull load of the gpt-x-alpaca-13b-native-true_sequential-act_order-128g-TRITON model
When I press generate I got the error bellow.

### Logs

```shell
Traceback (most recent call last):
  File "/mnt/d/Large Language Models/text-generation-webui-TRITON/modules/callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/mnt/d/Large Language Models/text-generation-webui-TRITON/modules/text_generation.py", line 252, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/adduser/miniconda3/envs/triton/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/adduser/miniconda3/envs/triton/lib/python3.10/site-packages/transformers/generation/utils.py", line 1485, in generate
    return self.sample(
  File "/home/adduser/miniconda3/envs/triton/lib/python3.10/site-packages/transformers/generation/utils.py", line 2560, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
Output generated in 3.14 seconds (0.00 tokens/s, 0 tokens, context 59, seed 423130691)
```

### System Info

```shell
Windows 10 + WSL2
```

**Comment by ENjoyBlue2021** [comment]
Happens with cuda from oobabooga too for me.
What card are you using? I suspected my pascal gen 1080ti is too old for it maybe.

**Comment by BadisG** [comment]
I have a 3060, and weirdly it works for me on the cuda part

**Comment by mikolodz** [comment]
Having the same problem here using Ubuntu 22.04 + rtx 3090. I have to disable monkey-patch or otherwise I'm not getting any output and the same error:
`probability tensor contains either `inf`, `nan` or element < 0`

**Comment by mikolodz** [comment]
@oobabooga After some more testing it appears that I run the server.py:
```
$ python server.py --monkey-patch --model TheBloke_vicuna-13B-1.1-GPTQ-4bit-128g --lora test-lora
Gradio HTTP request redirected to localhost :)
bin /home/administrator/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
Loading TheBloke_vicuna-13B-1.1-GPTQ-4bit-128g...
Warning: applying the monkey patch for using LoRAs in 4-bit mode.
It may cause undefined behavior outside its intended scope.
Loading Model ...
The safetensors archive passed at models/TheBloke_vicuna-13B-1.1-GPTQ-4bit-128g/vicuna-13B-1.1-GPTQ-4bit-128g.safetensors does not contain metadata. Make sure to save your model with the `save_pretrained` method. Defaulting to 'pt' metadata.
Loaded the model in 6.50 seconds.
Applying the following LoRAs to TheBloke_vicuna-13B-1.1-GPTQ-4bit-128g: test-lora
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

Then I hit generate and get this error:
```
Traceback (most recent call last):
  File "/home/administrator/git/text-generation-webui-train/modules/callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/home/administrator/git/text-generation-webui-train/modules/text_generation.py", line 252, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/administrator/anaconda3/envs/textgen/lib/python3.10/site-packages/peft/peft_model.py", line 721, in generate
    outputs = self.base_model.generate(**kwargs)
  File "/home/administrator/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/administrator/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1485, in generate
    return self.sample(
  File "/home/administrator/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2560, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
Output generated in 1.23 seconds (0.00 tokens/s, 0 tokens, context 16, seed 1170876151)
```

If I disable _do_sample_ option in the Parameters section, I get an empty response (no generated output), but my GPU is working and I get this info in my terminal (no errors..):
```
Output generated in 7.01 seconds (28.38 tokens/s, 199 tokens, context 16, seed 1565739140)
```

I tried also with a regular .pt file with same results (gpt-x-alpaca-13b-native-4bit-128g), although I wasn't getting any metadata info when launching server.py.

**Comment by valine** [comment]
I had this same issue running on my rtx 4090, for me it turned out to be a Nvidia driver issue. Upgrading to the beta driver worked for me, currently running 525.105.17.
