### ISSUE TITLE
RuntimeError (Tensors on wrong device) when using --cpu in Chat interface mode

### ISSUE THREAD

**Issue by mashdragon** [oobabooga/text-generation-webui#1486]
### Describe the bug

I am trying to run the `OpenAssistant/oasst-sft-1-pythia-12b` model. My GPU is not big enough to support the whole model, so I run with the `--cpu` flag.

Regular text generation mode works fine some of the time, although often the Generate button fails to generate text with no errors in the console which is annoying... `{"msg": "process_starts"}` and then immediately `{"msg": "process_completed", "output": {"data": [], "is_generating": false, "duration": 0.00012445449829101562, "average_duration": 0.00012445449829101562}, "success": true}`. So this makes using the interface frustrating, because it doesn't appear like anything is wrong but nothing is produced.

BUT the real bug is when I try to switch to chat interface mode. Then I get this error message, complaining about two devices, which should not happen because I used the `--cpu` flag:
```
/home/ooga/.local/lib/python3.10/site-packages/transformers/generation/utils.py:1405: UserWarning: You are calling .generate() with the `input_ids` being on a device type different than your model's device. `input_ids` is on cuda, whereas the model is on cpu. You may experience unexpected behaviors or slower generation. Please make sure that you have put `input_ids` to the correct device by calling for example input_ids = input_ids.to('cpu') before running `.generate()`.
  warnings.warn(
Traceback (most recent call last):
  File "/home/ooga/text-generation-webui/modules/callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/home/ooga/text-generation-webui/modules/text_generation.py", line 252, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/ooga/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ooga/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 1485, in generate
    return self.sample(
  File "/home/ooga/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 2524, in sample
    outputs = self(
  File "/home/ooga/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ooga/.local/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 662, in forward
    outputs = self.gpt_neox(
  File "/home/ooga/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ooga/.local/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 518, in forward
    inputs_embeds = self.embed_in(input_ids)
  File "/home/ooga/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ooga/.local/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/home/ooga/.local/lib/python3.10/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
Output generated in 1.59 seconds (0.00 tokens/s, 0 tokens, context 12, seed 210366519)
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Command to run:
```sh
python3 ./server.py --cpu
```

Switch to chat interface mode using Interface Mode > Mode -> chat. Go back to Text Generation. Press Generate.

The error message shown above is printed in the console, and nothing is generated.

### Logs

```shell
/home/ooga/.local/lib/python3.10/site-packages/transformers/generation/utils.py:1405: UserWarning: You are calling .generate() with the `input_ids` being on a device type different than your model's device. `input_ids` is on cuda, whereas the model is on cpu. You may experience unexpected behaviors or slower generation. Please make sure that you have put `input_ids` to the correct device by calling for example input_ids = input_ids.to('cpu') before running `.generate()`.
  warnings.warn(
Traceback (most recent call last):
  File "/home/ooga/text-generation-webui/modules/callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/home/ooga/text-generation-webui/modules/text_generation.py", line 252, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/ooga/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ooga/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 1485, in generate
    return self.sample(
  File "/home/ooga/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 2524, in sample
    outputs = self(
  File "/home/ooga/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ooga/.local/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 662, in forward
    outputs = self.gpt_neox(
  File "/home/ooga/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ooga/.local/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 518, in forward
    inputs_embeds = self.embed_in(input_ids)
  File "/home/ooga/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ooga/.local/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/home/ooga/.local/lib/python3.10/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
Output generated in 1.59 seconds (0.00 tokens/s, 0 tokens, context 12, seed 210366519)
```
```


### System Info

```shell
Arch: Linux amd64
GPU: Nvidia GTX 1080
```

**Comment by takeraparterer** [comment]
same problem on win10
