### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorboardX'

### ISSUE THREAD

**Issue by martjay** [oobabooga/text-generation-webui#1499]
### Describe the bug

![888888](https://user-images.githubusercontent.com/44982189/233843978-7a40b265-6801-4f14-bb05-e4094ef3917b.jpg)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

After the installation is completed, I run start_ Windows. bat, and an error occurred

### Logs

```shell
Gradio HTTP request redirected to localhost :) Traceback (most recent call last):
  File "D:\Downloads\2D\AI\LLM\oobabooga_windows\installer_files\env\lib\site-packages\accelerate\tracking.py", line 42, in <module>
    from torch.utils import tensorboard
  File "D:\Downloads\2D\AI\LLM\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\tensorboard\__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "D:\Downloads\2D\AI\LLM\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\tensorboard\writer.py", line 9, in <module>
    from tensorboard.compat.proto.event_pb2 import SessionLog
  File "C:\Users\Enya\AppData\Roaming\Python\Python310\site-packages\tensorboard\compat\proto\event_pb2.py", line 7, in <module>
    from google.protobuf.internal import enum_type_wrapper ModuleNotFoundError: No module named 'google'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Downloads\2D\AI\LLM\oobabooga_windows\text-generation-webui\server.py", line 43, in <module>
    from modules import api, chat, shared, training, ui
  File "D:\Downloads\2D\AI\LLM\oobabooga_windows\text-generation-webui\modules\api.py", line 6, in <module>
    from modules.text_generation import generate_reply
  File "D:\Downloads\2D\AI\LLM\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 16, in <module>
    from modules.models import clear_torch_cache, local_rank
  File "D:\Downloads\2D\AI\LLM\oobabooga_windows\text-generation-webui\modules\models.py", line 12, in <module>
    from accelerate import infer_auto_device_map, init_empty_weights
  File "D:\Downloads\2D\AI\LLM\oobabooga_windows\installer_files\env\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "D:\Downloads\2D\AI\LLM\oobabooga_windows\installer_files\env\lib\site-packages\accelerate\accelerator.py", line 37, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "D:\Downloads\2D\AI\LLM\oobabooga_windows\installer_files\env\lib\site-packages\accelerate\tracking.py", line 44, in <module>
    import tensorboardX as tensorboard ModuleNotFoundError: No module named 'tensorboardX'

Done!
```

### System Info

```shell
OS: WIN11 PRO X64
GPU: NVDIA 2070S
```

**Comment by Rogal80** [comment]
same here :(

**Comment by catowabisabi** [comment]
same

**Comment by dannyp777** [comment]
Same on Ubuntu Lunar

**Comment by dannyp777** [comment]
> Same on Ubuntu Lunar. Hardware: https://linux-hardware.org/?probe=f90de81324 Python/Conda Environment:
> 
> [conda-env.log](https://github.com/oobabooga/text-generation-webui/files/11473191/conda-env.log) [pip-freeze.log](https://github.com/oobabooga/text-generation-webui/files/11473192/pip-freeze.log)
> 
> Log:
> 
> ```
>   File "/home/danny/Downloads/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/accelerate/tracking.py", line 42, in <module>
>     from torch.utils import tensorboard
>   File "/home/danny/Downloads/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/utils/tensorboard/__init__.py", line 12, in <module>
>     from .writer import FileWriter, SummaryWriter  # noqa: F401
>   File "/home/danny/Downloads/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py", line 9, in <module>
>     from tensorboard.compat.proto.event_pb2 import SessionLog
>   File "/home/danny/.local/lib/python3.10/site-packages/tensorboard/compat/proto/event_pb2.py", line 7, in <module>
> 
>     from google.protobuf.internal import enum_type_wrapper
> ModuleNotFoundError: No module named 'google.protobuf'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/danny/Downloads/oobabooga_linux/text-generation-webui/server.py", line 47, in <module>
>     from modules import chat, shared, training, ui, utils
>   File "/home/danny/Downloads/oobabooga_linux/text-generation-webui/modules/chat.py", line 17, in <module>
>     from modules.text_generation import (generate_reply, get_encoded_length,
>   File "/home/danny/Downloads/oobabooga_linux/text-generation-webui/modules/text_generation.py", line 17, in <module>
>     from modules.models import clear_torch_cache, local_rank
>   File "/home/danny/Downloads/oobabooga_linux/text-generation-webui/modules/models.py", line 13, in <module>
>     from accelerate import infer_auto_device_map, init_empty_weights
>   File "/home/danny/Downloads/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/accelerate/__init__.py", line 3, in <module>
>     from .accelerator import Accelerator
>   File "/home/danny/Downloads/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/accelerate/accelerator.py", line 39, in <module>
>     from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
>   File "/home/danny/Downloads/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/accelerate/tracking.py", line 44, in <module>
>     import tensorboardX as tensorboard
> ModuleNotFoundError: No module named 'tensorboardX'
> ```

See my actions here: [https://github.com/oobabooga/text-generation-webui/issues/1806#issuecomment-1547043745](url)

**Comment by Andie-Squirrel** [comment]
Same issue here on Windows 10. Oobabooga was working fine until installing DragYourGan requirements. Tried installing TensorboardX and Tensorboard using Anaconda and pip for all installations of Python to no avail.

**Comment by Andie-Squirrel** [comment]
Alright I have a solution that works for me.
Using Everything search, I found the TensorboardX installation site package in Python3.10.
![image](https://github.com/oobabooga/text-generation-webui/assets/119384539/f90e7f19-5094-4850-b81c-54412bbcfa67)
I opened the location and linked the folder to the oobabooga site packages folder:
oobabooga_windows\installer_files\env\Lib\site-packages
![image](https://github.com/oobabooga/text-generation-webui/assets/119384539/35fb8fe5-b32a-4d6d-832e-8f9298a48d4e)

This should have the same result if pasted instead of linked.

Now Oobabooga opens normally.
![image](https://github.com/oobabooga/text-generation-webui/assets/119384539/f9163fee-47e1-4328-bf5c-912ba6c9f098)
