### ISSUE TITLE
Models cannot be downloaded

### ISSUE THREAD

**Issue by start-life** [oobabooga/text-generation-webui#1514]
### Describe the bug

Traceback (most recent call last):
  File "C:\oobabooga-windows\text-generation-webui\download-model.py", line 260, in <module>
    links, sha256, is_lora = get_download_links_from_huggingface(model, branch, text_only=args.text_only)
  File "C:\oobabooga-windows\text-generation-webui\download-model.py", line 103, in get_download_links_from_huggingface
    fname = dict[i]['path']
KeyError: 0

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Just try to download a model no matter which one this error will appear

### Screenshot

![צילום מסך 2023-04-24 135512](https://user-images.githubusercontent.com/96779864/233976861-c2c0320e-f574-4edd-bd13-34009de2d241.png)

### Logs

```shell
11
```

### System Info

```shell
11
```

**Comment by co7e** [comment]
Same error here running on WSL

**Comment by co7e** [comment]
I tried running off the latest code in main and it works.

**Comment by Praveenku32k** [comment]
> Same error here running on WSL, but then I tried running off the latest code in main and it works.

Hii, can you please share the latest code repo.

**Comment by Praveenku32k** [comment]
I am facing the same issue , please share the update code anyone .
$ python download-model.py anon8231489123/vicuna-13b-GPTQ-4bit-128g
Traceback (most recent call last):
  File "C:\Users\RevealIT\Desktop\test\FastChat\download-model.py", line 196, in <module>
    links, sha256, is_lora = get_download_links_from_huggingface(model, branch)
  File "C:\Users\RevealIT\Desktop\test\FastChat\download-model.py", line 130, in get_download_links_from_huggingface
    fname = dict[i]['path']
KeyError: 0
(chatbot)

**Comment by admiraldaro** [comment]
Problem still exist

**Comment by Woisek** [comment]
And why not download it manually, the best way anyway? 🤷‍♂️
