### ISSUE TITLE
" torch.cuda.is_available() returned False."

### ISSUE THREAD

**Issue by SuccBT** [oobabooga/text-generation-webui#1517]
### Describe the bug

it says a bunch of stuff like "torch.cuda.is_available() returned False." and then makes me press a key to quit out of it

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I try to run it with a model installed and then it breaks

### Screenshot

![image](https://user-images.githubusercontent.com/127024548/234075716-12bbd4d9-6690-47b9-bdb3-550ce71aafc7.png)

### Logs

```shell
Gradio HTTP request redirected to localhost :)
bin C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll
C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading mayaeary_pygmalion-6b_dev-4bit-128g...
Warning: torch.cuda.is_available() returned False.
This means that no GPU has been detected.
Falling back to CPU mode.

Traceback (most recent call last):
  File "C:\AI\oobabooga_windows\text-generation-webui\server.py", line 914, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\AI\oobabooga_windows\text-generation-webui\modules\models.py", line 209, in load_model
    model = LoaderClass.from_pretrained(checkpoint, **params)
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2405, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory models\mayaeary_pygmalion-6b_dev-4bit-128g.

Done!
Press any key to continue . . .
```

### System Info

```shell
RTX 3070
```

**Comment by Brawlence** [comment]
A full clean reinstall (deleting all the `installer_files` & `textgen-webui` dirs beforehand) fixed that for me.

Don't forget to move out your models & other stuff you need so you won't have to re-download it.

**Comment by coilpaint** [comment]
I'm getting the same error. Does using this installer mean you don't have to download visual studio, python, cuda-tools? Does it do that for you? I'm wondering if there's a conflict between my installations of the requirements and the ones provided by the oogabooga installation
