### ISSUE TITLE
Error when using LLaVA with the custom stopping string as mentioned in the read me

### ISSUE THREAD

**Issue by xuuyz** [oobabooga/text-generation-webui#1522]
### Describe the bug

I get a Syntax Error when uploading an image

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Use LLaVA
use the custom stopping string 
```
\n###
``` 
attach image
get error

### Logs

```shell
Traceback (most recent call last):
  File "H:\ooba-webui\installer_files\env\lib\site-packages\gradio\routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\ooba-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "H:\ooba-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 930, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\ooba-webui\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\ooba-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "H:\ooba-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "H:\ooba-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 491, in async_iteration
    return next(iterator)
  File "H:\ooba-webui\text-generation-webui\modules\chat.py", line 227, in cai_chatbot_wrapper
    for history in chatbot_wrapper(text, state):
  File "H:\ooba-webui\text-generation-webui\modules\chat.py", line 130, in chatbot_wrapper
    stopping_strings = get_stopping_strings(state)
  File "H:\ooba-webui\text-generation-webui\modules\chat.py", line 83, in get_stopping_strings
    stopping_strings += ast.literal_eval(f"[{state['custom_stopping_strings']}]")
  File "H:\ooba-webui\installer_files\env\lib\ast.py", line 64, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
  File "H:\ooba-webui\installer_files\env\lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    [\n###]
      ^
SyntaxError: unexpected character after line continuation character
```

### System Info

```shell
Windows 11, miniconda, RTX 4090
```

**Comment by LaaZa** [comment]
Did you put it in quotes? "\n###"

**Comment by xuuyz** [comment]
No, I did not. Thank you.
