### ISSUE TITLE
Can't use RWKV-4

### ISSUE THREAD

**Issue by Slug-Cat** [oobabooga/text-generation-webui#153]
Windows, RTX 3060, latest pull
I'm trying to run the ui with "RWKV-4-Pile-3B-20221110-ctx4096" and it's giving me an OS error:
Input: call python server.py --gpu-memory 8 --no-stream --bf16 --cai-chat --extensions gallery
```Traceback (most recent call last):
  File "E:\oobabooga\text-generation-webui\server.py", line 185, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "E:\oobabooga\text-generation-webui\modules\models.py", line 84, in load_model
    model = RWKVModel.from_pretrained(Path(f'models/{model_name}'), dtype="fp32" if shared.args.cpu else "bf16" if shared.args.bf16 else "fp16", device="cpu" if shared.args.cpu else "cuda")
  File "E:\oobabooga\text-generation-webui\modules\RWKV.py", line 29, in from_pretrained
    pipeline = PIPELINE(model, tokenizer_path.as_posix())
  File "E:\oobabooga\installer_files\env\lib\site-packages\rwkv\utils.py", line 23, in __init__
    self.tokenizer = Tokenizer.from_file(WORD_NAME)
Exception: The system cannot find the file specified. (os error 2)
Press any key to continue . . .```

**Comment by oobabooga** [comment]
This may fix it, can you update and try again? https://github.com/oobabooga/text-generation-webui/commit/449116a5101c32617a497d3c79210bb7255505be

**Comment by Slug-Cat** [comment]
updated and tried again, slightly different error this time:
```Traceback (most recent call last):
  File "E:\oobabooga\text-generation-webui\server.py", line 185, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "E:\oobabooga\text-generation-webui\modules\models.py", line 84, in load_model
    model = RWKVModel.from_pretrained(Path(f'models/{model_name}'), dtype="fp32" if shared.args.cpu else "bf16" if shared.args.bf16 else "fp16", device="cpu" if shared.args.cpu else "cuda")
  File "E:\oobabooga\text-generation-webui\modules\RWKV.py", line 29, in from_pretrained
    pipeline = PIPELINE(model, os.path.abspath(tokenizer_path))
  File "E:\oobabooga\installer_files\env\lib\site-packages\rwkv\utils.py", line 23, in __init__
    self.tokenizer = Tokenizer.from_file(WORD_NAME)
Exception: The system cannot find the file specified. (os error 2)```

**Comment by oobabooga** [comment]
Do you have `20B_tokenizer.json` inside the models folder?

**Comment by Slug-Cat** [comment]
I don't. Is that a necessary file for RWKV?

**Comment by Slug-Cat** [comment]
Alright, will try again after doing that.

**Comment by Slug-Cat** [comment]
Alright, seems to work fine. Thanks.

**Comment by oobabooga** [comment]
If you find any other problems let me know. You are probably the first person other than me to try this.

**Comment by Slug-Cat** [comment]
I have noticed it takes quite a bit of VRAM, contrary to the claims of VRAM savings by the RWKV github. Not sure what that's about.
