### ISSUE TITLE
 CUDA out of memory. Tried to allocate 34.00 MiB

### ISSUE THREAD

**Issue by 3badi114** [oobabooga/text-generation-webui#1536]
### Describe the bug

does anyone have a solution for this error ?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

not enough gpu Memory 

### Logs

```shell
Gradio HTTP request redirected to localhost :)
bin F:\Ai_bot\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
Loading anon8231489123_gpt4-x-alpaca-13b-native-4bit-128g...
Warning: more than one .pt model has been found. The last one will be selected. It could be wrong.
Found the following quantized model: models\anon8231489123_gpt4-x-alpaca-13b-native-4bit-128g\gpt-x-alpaca-13b-native-4bit-128g.pt
Loading model ...
Done.
Traceback (most recent call last):
  File "F:\Ai_bot\oobabooga_windows\text-generation-webui\server.py", line 914, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "F:\Ai_bot\oobabooga_windows\text-generation-webui\modules\models.py", line 150, in load_model
    model = load_quantized(model_name)
  File "F:\Ai_bot\oobabooga_windows\text-generation-webui\modules\GPTQ_loader.py", line 197, in load_quantized
    model = model.to(torch.device('cuda:0'))
  File "F:\Ai_bot\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 1896, in to
    return super().to(*args, **kwargs)
  File "F:\Ai_bot\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "F:\Ai_bot\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "F:\Ai_bot\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "F:\Ai_bot\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "F:\Ai_bot\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 844, in _apply
    self._buffers[key] = fn(buf)
  File "F:\Ai_bot\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 34.00 MiB (GPU 0; 8.00 GiB total capacity; 6.71 GiB already allocated; 16.56 MiB free; 6.95 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Done!
Press any key to continue . . .
```

### System Info

```shell
Rtx 3070 8gb
rayzen 5 5600x 
32 gb ram
```

**Comment by elcotek** [comment]
Additional memory of the GPU is required for text generation buffer in Vram, which must be kept free, otherwise the error mentioned above occurs. Use this in your command line will reduce the usage. For example.  --gpu-memory 2844MiB

**Comment by elcotek** [comment]
Oobabooga could possibly dynamically adapt the Vram usage to the text length to be transmitted, but I don't know if the Vram can be dynamized as required.

**Comment by 3badi114** [comment]
> Additional memory of the GPU is required for text generation buffer in Vram, which must be kept free, otherwise the error mentioned above occurs. Use this in your command line will reduce the usage. For example. --gpu-memory 2844MiB

do i need to edit the start web ui for it to work?

**Comment by BarfingLemurs** [comment]
>do i need to edit the start web ui for it to work?
adding settings in the start_linux.sh script seems to prevent me from starting the program alltogether. 
It might be working for on windows though, try.

**Comment by elcotek** [comment]
You can also set this on the interface under the Model settings.
![grafik](https://user-images.githubusercontent.com/18084281/234309334-191193d6-3774-4755-9394-b540ede8cfc8.png)

**Comment by elcotek** [comment]
Then use the command line like i say before.
