### ISSUE TITLE
GPT2-XL model failing via API

### ISSUE THREAD

**Issue by raziel2001au** [oobabooga/text-generation-webui#1543]
### Describe the bug

All models that load for me generally work via API, but I'm finding that GPT2-XL crashes oobabooga when called via API using SillyTavern. It works fine via the UI.

I've attempted to load the model with 8bit encoding just to make sure it isn't something VRAM related, but same result. It works fine in the UI, hit it via API, and it just crashed OOBA with this stack trace.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

download the 'gpt2-xl' model, open up SillyTavern and start any conversation. Testing GPT2 XL via the UI works fine.

### Logs

```shell
Stacktrace as below:

Traceback (most recent call last):
  File "D:\Development\text-generation-webui\text-generation-webui\modules\callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "D:\Development\text-generation-webui\text-generation-webui\modules\text_generation.py", line 257, in generate_with_callback
    shared.model.generate(**kwargs)
  File "D:\Development\text-generation-webui\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Development\text-generation-webui\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1485, in generate
    return self.sample(
  File "D:\Development\text-generation-webui\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 2524, in sample
    outputs = self(
  File "D:\Development\text-generation-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Development\text-generation-webui\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "D:\Development\text-generation-webui\installer_files\env\lib\site-packages\transformers\models\gpt2\modeling_gpt2.py", line 1075, in forward
    transformer_outputs = self.transformer(
  File "D:\Development\text-generation-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Development\text-generation-webui\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "D:\Development\text-generation-webui\installer_files\env\lib\site-packages\transformers\models\gpt2\modeling_gpt2.py", line 899, in forward
    outputs = block(
  File "D:\Development\text-generation-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Development\text-generation-webui\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "D:\Development\text-generation-webui\installer_files\env\lib\site-packages\transformers\models\gpt2\modeling_gpt2.py", line 389, in forward
    attn_outputs = self.attn(
  File "D:\Development\text-generation-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Development\text-generation-webui\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "D:\Development\text-generation-webui\installer_files\env\lib\site-packages\transformers\models\gpt2\modeling_gpt2.py", line 330, in forward
    attn_output, attn_weights = self._attn(query, key, value, attention_mask, head_mask)
  File "D:\Development\text-generation-webui\installer_files\env\lib\site-packages\transformers\models\gpt2\modeling_gpt2.py", line 200, in _attn
    mask_value = torch.full([], mask_value, dtype=attn_weights.dtype).to(attn_weights.device)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception in thread Thread-12 (gentask):
Traceback (most recent call last):
  File "D:\Development\text-generation-webui\installer_files\env\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\Development\text-generation-webui\installer_files\env\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Development\text-generation-webui\text-generation-webui\modules\callbacks.py", line 73, in gentask
    clear_torch_cache()
  File "D:\Development\text-generation-webui\text-generation-webui\modules\callbacks.py", line 105, in clear_torch_cache
    torch.cuda.empty_cache()
  File "D:\Development\text-generation-webui\installer_files\env\lib\site-packages\torch\cuda\memory.py", line 133, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### System Info

```shell
RTX4080
```

**Comment by Jeduh** [comment]
Same here

**Comment by Jeduh** [comment]
Did the same thing but added the CUDA_LAUNCH_BLOCKING environment to 1 this time, hope it helps :)

` Traceback (most recent call last):
   File "/app/modules/text_generation.py", line 272, in generate_reply
     output = shared.model.generate(**generate_params)[0]
   File "/app/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
     return func(*args, **kwargs)
   File "/app/venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 1485, in generate
     return self.sample(
   File "/app/venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 2524, in sample
     outputs = self(
   File "/app/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
     return forward_call(*args, **kwargs)
   File "/app/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 687, in forward
     outputs = self.model(
   File "/app/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
     return forward_call(*args, **kwargs)
   File "/app/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 577, in forward
     layer_outputs = decoder_layer(
   File "/app/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
     return forward_call(*args, **kwargs)
   File "/app/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 292, in forward
     hidden_states, self_attn_weights, present_key_value = self.self_attn(
   File "/app/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
     return forward_call(*args, **kwargs)
   File "/app/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 196, in forward
     query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
   File "/app/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
     return forward_call(*args, **kwargs)
   File "/app/repositories/GPTQ-for-LLaMa/quant.py", line 431, in forward
     y = y.to(output_dtype)
 RuntimeError: CUDA error: no kernel image is available for execution on the device
 Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
`

**Comment by Jeduh** [comment]
Did the same thing but added the CUDA_LAUNCH_BLOCKING environment to 1 this time, hope it helps :)


```Traceback (most recent call last): File "/app/modules/text_generation.py", line 272, in generate_reply output = shared.model.generate(**generate_params)[0] File "/app/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/app/venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 1485, in generate return self.sample( File "/app/venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 2524, in sample outputs = self( File "/app/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/app/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 687, in forward outputs = self.model( File "/app/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/app/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 577, in forward layer_outputs = decoder_layer( File "/app/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/app/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 292, in forward hidden_states, self_attn_weights, present_key_value = self.self_attn( File "/app/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/app/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 196, in forward query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2) File "/app/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/app/repositories/GPTQ-for-LLaMa/quant.py", line 431, in forward y = y.to(output_dtype) RuntimeError: CUDA error: no kernel image is available for execution on the device Compile withTORCH_USE_CUDA_DSAto enable device-side assertions.```

**Comment by Jeduh** [comment]
Have you checked if TORCH_CUDA_ARCH_LIST=8.9 in your .env file?

**Comment by raziel2001au** [comment]
I don't think I have a .env file, is this on Windows? I checked if it was set as an environment variable, which it wasn't, so I set it, but it made no difference. Still stack traces the moment you try and access GPT2 via API...

**Comment by raziel2001au** [comment]
This is still an issue. Commenting to unclose this.

**Comment by p1x33l** [comment]
Same issue
