### ISSUE TITLE
Commit 92cdb4f breaks loading of models whose names contain capital letters

### ISSUE THREAD

**Issue by logiconcepts819** [oobabooga/text-generation-webui#1552]
### Describe the bug

It seems commit 92cdb4f broke the loading of models in directories whose names contain capital letters.  The model loads fine if I go to the models directory and create a symlink as follows:
`ln -s MetaIX_GPT4-X-Alpaca-30B-Int4 metaix_gpt4-x-alpaca-30b-int4`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Pull the latest upstream version.
2. Download a model containing capital letters (e.g., "MetaIX/GPT4-X-Alpaca-30B-Int4").
3. Load the model (e.g., `python server.py --listen --model MetaIX_GPT4-X-Alpaca-30B-Int4 --wbits 4 --model_type LLaMA --groupsize 128`)

### Logs

```shell
$ python server.py --listen --model MetaIX_GPT4-X-Alpaca-30B-Int4 --wbits 4 --model_type LLaMA --groupsize 128
Gradio HTTP request redirected to localhost :)
bin /home/ron/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
Loading MetaIX_GPT4-X-Alpaca-30B-Int4...
Traceback (most recent call last):
  File "/home/ron/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/configuration_utils.py", line 628, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/ron/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/home/ron/anaconda3/envs/textgen/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/ron/anaconda3/envs/textgen/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'models//metaix_gpt4-x-alpaca-30b-int4'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ron/Code/text-generation-webui/server.py", line 914, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/ron/Code/text-generation-webui/modules/models.py", line 71, in load_model
    shared.model_type = find_model_type(model_name)
  File "/home/ron/Code/text-generation-webui/modules/models.py", line 59, in find_model_type
    config = AutoConfig.from_pretrained(f"{shared.args.model_dir}/{model_name}")
  File "/home/ron/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 916, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/ron/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/configuration_utils.py", line 573, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/ron/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/configuration_utils.py", line 649, in _get_config_dict
    raise EnvironmentError(
OSError: Can't load the configuration of 'models//metaix_gpt4-x-alpaca-30b-int4'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'models//metaix_gpt4-x-alpaca-30b-int4' is the correct path to a directory containing a config.json file
```

### System Info

```shell
Operating system:  Ubuntu 22.04.2 LTS
GPU brand:  Nvidia
GPU model:  Gigabyte GeForce RTX 4090
```

**Comment by aaroncoffey** [comment]
This same change also broke install. I've added a comment to the line here.
https://github.com/oobabooga/text-generation-webui/pull/1535/files#r1177307102

logs:
```
$ bash start_linux.sh
Gradio HTTP request redirected to localhost :)
bin /home/aaron/llms/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
Loading EleutherAI_pythia-6.9b-deduped...
Traceback (most recent call last):
  File "/home/aaron/llms/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/transformers/configuration_utils.py", line 628, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/aaron/llms/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/home/aaron/llms/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/aaron/llms/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'models//eleutherai_pythia-6.9b-deduped'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aaron/llms/oobabooga_linux/text-generation-webui/server.py", line 914, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/aaron/llms/oobabooga_linux/text-generation-webui/modules/models.py", line 71, in load_model
    shared.model_type = find_model_type(model_name)
  File "/home/aaron/llms/oobabooga_linux/text-generation-webui/modules/models.py", line 59, in find_model_type
    config = AutoConfig.from_pretrained(f"{shared.args.model_dir}/{model_name}")
  File "/home/aaron/llms/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 916, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/aaron/llms/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/transformers/configuration_utils.py", line 573, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/aaron/llms/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/transformers/configuration_utils.py", line 649, in _get_config_dict
    raise EnvironmentError(
OSError: Can't load the configuration of 'models//eleutherai_pythia-6.9b-deduped'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name
. Otherwise, make sure 'models//eleutherai_pythia-6.9b-deduped' is the correct path to a directory containing a config.json file
```

Note the double forward slash in the model path.

**Comment by oobabooga** [comment]
Already fixed

**Comment by logiconcepts819** [comment]
Yep, the issue is indeed fixed with the latest pull.  Thanks!
