### ISSUE TITLE
Train ,when chose the Copy parameters from the select menu the page get error

### ISSUE THREAD

**Issue by elven2016** [oobabooga/text-generation-webui#1563]
### Describe the bug

Training tab,  select the lora from the menu in order to copy parameters ,the page get error, the terminal  find this error
Traceback (most recent call last):
  File "/home/elven/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/elven/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "/home/elven/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 916, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/elven/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/elven/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/elven/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/data01/text-generation-webui/modules/training.py", line 106, in do_copy_params
    with open(f"{shared.args.lora_dir}/{clean_path(None, lora_name)}/training_parameters.json", 'r', encoding='utf-8') as formatFile:
FileNotFoundError: [Errno 2] No such file or directory: 'loras//tloen_alpaca-lora-7b/training_parameters.json'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Traceback (most recent call last):
  File "/home/elven/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/elven/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "/home/elven/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 916, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/elven/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/elven/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/elven/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/data01/text-generation-webui/modules/training.py", line 106, in do_copy_params
    with open(f"{shared.args.lora_dir}/{clean_path(None, lora_name)}/training_parameters.json", 'r', encoding='utf-8') as formatFile:
FileNotFoundError: [Errno 2] No such file or directory: 'loras//tloen_alpaca-lora-7b/training_parameters.json'

### Screenshot

![image](https://user-images.githubusercontent.com/16677082/234522287-ea12e4a4-2d3e-4a09-b4ea-5e8f9cf1a997.png)

### Logs

```shell
Traceback (most recent call last):
  File "/home/elven/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/elven/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "/home/elven/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 916, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/elven/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/elven/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/elven/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/data01/text-generation-webui/modules/training.py", line 106, in do_copy_params
    with open(f"{shared.args.lora_dir}/{clean_path(None, lora_name)}/training_parameters.json", 'r', encoding='utf-8') as formatFile:
FileNotFoundError: [Errno 2] No such file or directory: 'loras//tloen_alpaca-lora-7b/training_parameters.json'
```

### System Info

```shell
OS:ubuntu22.04 
GPU:V100 32G
pip list:
Package                  Version
------------------------ ----------
accelerate               0.18.0
aiofiles                 23.1.0
aiohttp                  3.8.4
aiosignal                1.3.1
altair                   4.2.2
anyio                    3.6.2
appdirs                  1.4.4
asttokens                2.2.1
async-timeout            4.0.2
attrs                    23.1.0
backcall                 0.2.0
bitsandbytes             0.38.1
black                    23.3.0
certifi                  2022.12.7
charset-normalizer       3.1.0
click                    8.1.3
cmake                    3.26.3
contourpy                1.0.7
cycler                   0.11.0
datasets                 2.11.0
decorator                5.1.1
dill                     0.3.6
entrypoints              0.4
executing                1.2.0
fastapi                  0.95.1
ffmpy                    0.3.0
filelock                 3.12.0
fire                     0.5.0
fonttools                4.39.3
frozenlist               1.3.3
fsspec                   2023.4.0
gradio                   3.27.0
gradio_client            0.1.3
h11                      0.14.0
httpcore                 0.17.0
httpx                    0.24.0
huggingface-hub          0.13.4
idna                     3.4
ipython                  8.12.0
jedi                     0.18.2
Jinja2                   3.1.2
jsonschema               4.17.3
kiwisolver               1.4.4
linkify-it-py            2.0.0
lit                      16.0.1
loralib                  0.1.1
markdown-it-py           2.2.0
MarkupSafe               2.1.2
matplotlib               3.7.1
matplotlib-inline        0.1.6
mdit-py-plugins          0.3.3
mdurl                    0.1.2
mpmath                   1.3.0
multidict                6.0.4
multiprocess             0.70.14
mypy-extensions          1.0.0
networkx                 3.1
numpy                    1.24.3
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
orjson                   3.8.10
packaging                23.1
pandas                   2.0.0
parso                    0.8.3
pathspec                 0.11.1
peft                     0.3.0.dev0
pexpect                  4.8.0
pickleshare              0.7.5
Pillow                   9.5.0
pip                      23.1.1
platformdirs             3.2.0
prompt-toolkit           3.0.38
psutil                   5.9.5
ptyprocess               0.7.0
pure-eval                0.2.2
pyarrow                  11.0.0
pydantic                 1.10.7
pydub                    0.25.1
Pygments                 2.15.1
pyparsing                3.0.9
pyrsistent               0.19.3
python-dateutil          2.8.2
python-multipart         0.0.6
pytz                     2023.3
PyYAML                   6.0
regex                    2023.3.23
requests                 2.28.2
responses                0.18.0
semantic-version         2.10.0
sentencepiece            0.1.98
setuptools               67.7.1
six                      1.16.0
sniffio                  1.3.0
stack-data               0.6.2
starlette                0.26.1
sympy                    1.11.1
termcolor                2.2.0
tokenize-rt              5.0.0
tokenizers               0.13.3
tomli                    2.0.1
toolz                    0.12.0
torch                    2.0.0
tqdm                     4.65.0
traitlets                5.9.0
transformers             4.28.1
triton                   2.0.0
typing_extensions        4.5.0
tzdata                   2023.3
uc-micro-py              1.0.1
urllib3                  1.26.15
uvicorn                  0.21.1
wcwidth                  0.2.6
websockets               11.0.2
wheel                    0.40.0
xxhash                   3.2.0
yarl                     1.9.1
```

**Comment by elven2016** [comment]
git pull update the latest version，the training.py has changed，the old version is
![image](https://user-images.githubusercontent.com/16677082/234802982-ac3e65fb-05e6-425e-9aef-5424028b4906.png)
and now  the latest version is
![image](https://user-images.githubusercontent.com/16677082/234803177-19016ac4-ee16-45ae-8779-1181f0bdc046.png)
