### ISSUE TITLE
Gradio Public Link Not Operating as Expected

### ISSUE THREAD

**Issue by bubbabug** [oobabooga/text-generation-webui#1588]
### Describe the bug

I have attempted using the Gradio public links on both my PC and my mobile device and as of today 4/26, the links are not working as expected. I am able to load the page, and select a character, I can even activate extensions, but when I try to send messages, they never send. I have attempted using standard Enter key entry and using the Generate link, but neither method will submit my response. I am able to regenerate bot responses, I just cannot send new responses. I have updated and even tried a clean install and the issue persists.

As late as yesterday, this function was working as intended, but it ceased working before applying any updates. I am not sure if this is a gradio issue or a webui issue, but I wanted to report it in the hopes that someone can help me find a solution.

I am not positive that the included log is relevant as I have seen this log prior to this occurrence and it never impacted my ability to send messages.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Click public share link. Load character. Enter text in input field. Press enter or Generate. Input field does not send to chat.

### Logs

```shell
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\oobabooga_windows\installer_files\env\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\oobabooga_windows\installer_files\env\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

### System Info

```shell
i7-9750H CPU @ 2.60GHz
GTX 1660Ti Mobile GPU
16GB DDR4 RAM
Windows 11
```

**Comment by bubbabug** [comment]
I believe this was a partial service outage, or at least that's all that I can think of it being. After not working all day, the gradio links are now suddenly working with no changes to configuration.
