### ISSUE TITLE
"CUDA out of memory" Only When Using API

### ISSUE THREAD

**Issue by techgo** [oobabooga/text-generation-webui#1595]
### Describe the bug

When I use the API on port 5000, I run out of memory. When using the same parameters without the --api flag and using the regular web interface, I do not run out of memory.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Use this flags: `python server.py --model vicuna-13B-1.1-GPTQ-4bit-128g --wbits 4 --groupsize 128 --model_type Llama --gpu-memory 7500MiB --cpu-memory 25000MiB --chat --threads 12 --pre_layer 32`
2. Make an API request.
3. Obverse error ```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 672.00 MiB (GPU 0; 8.00 GiB total capacity; 6.23 GiB already allocated; 0 bytes free; 6.92 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Output generated in 2.48 seconds (0.00 tokens/s, 0 tokens, context 2096, seed 165012704)
```


### Screenshot

_No response_

### Logs

```shell
======================================================================
It works perfectly fine with the regular web ui interface, see below.
======================================================================

(textgen) ubuntu@ubuntu:~/text-generation-webui$ python server.py --model vicuna-13B-1.1-GPTQ-4bit-128g --wbits 4 --groupsize 128 --model_type Llama --gpu-memory 7500MiB --cpu-memory 25000MiB --chat --threads 12 --pre_layer 32
Gradio HTTP request redirected to localhost :)
bin /home/ubuntu/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
Loading vicuna-13B-1.1-GPTQ-4bit-128g...
Found the following quantized model: models/vicuna-13B-1.1-GPTQ-4bit-128g/vicuna-13B-1.1-GPTQ-4bit-128g.no-act-order.pt
Loading model ...
Found 4 unique KN values.
Warming up autotune cache ...
100%|███████████████████████████████████████████| 12/12 [00:31<00:00,  2.59s/it]
Done.
Loaded the model in 48.45 seconds.
Loading the extension "gallery"... Ok.
Running on local URL:  http://127.0.0.1:7860
 
To create a public link, set `share=True` in `launch()`.
Output generated in 151.14 seconds (1.93 tokens/s, 292 tokens, context 40, seed 1911569689)

======================================================================
When using --api & --listen and making an API call it runs out of memory, see below.
======================================================================

(textgen) ubuntu@ubuntu:~/text-generation-webui$ python server.py --model vicuna-13B-1.1-GPTQ-4bit-128g --wbits 4 --groupsize 128 --model_type Llama --gpu-memory 7500MiB --cpu-memory 25000MiB --chat --threads 12 --pre_layer 32 --api --listen
Gradio HTTP request redirected to localhost :)
bin /home/ubuntu/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
Loading vicuna-13B-1.1-GPTQ-4bit-128g...
Found the following quantized model: models/vicuna-13B-1.1-GPTQ-4bit-128g/vicuna-13B-1.1-GPTQ-4bit-128g.no-act-order.pt
Loading model ...
Found 4 unique KN values.
Warming up autotune cache ...
100%|███████████████████████████████████████████| 12/12 [00:31<00:00,  2.62s/it]
Done.
Loaded the model in 37.19 seconds.
Starting streaming server at ws://0.0.0.0:5005/api/v1/stream
Loading the extension "gallery"... Starting API at http://0.0.0.0:5000/api
Ok.
Running on local URL:  http://0.0.0.0:7860
 
To create a public link, set `share=True` in `launch()`.
127.0.0.1 - - [27/Apr/2023 01:10:42] code 404, message Not Found
127.0.0.1 - - [27/Apr/2023 01:10:42] "GET /api HTTP/1.1" 404 -
127.0.0.1 - - [27/Apr/2023 01:10:42] code 404, message Not Found
127.0.0.1 - - [27/Apr/2023 01:10:42] "GET /api HTTP/1.1" 404 -
127.0.0.1 - - [27/Apr/2023 01:10:42] code 404, message Not Found
127.0.0.1 - - [27/Apr/2023 01:10:42] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [27/Apr/2023 01:10:42] code 404, message Not Found
127.0.0.1 - - [27/Apr/2023 01:10:42] "GET /favicon.ico HTTP/1.1" 404 -
172.18.0.2 - - [27/Apr/2023 01:11:59] "POST /api/v1/generate HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/ubuntu/text-generation-webui/modules/callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/home/ubuntu/text-generation-webui/modules/text_generation.py", line 280, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/ubuntu/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1485, in generate
    return self.sample(
  File "/home/ubuntu/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2524, in sample
    outputs = self(
  File "/home/ubuntu/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "/home/ubuntu/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/text-generation-webui/repositories/GPTQ-for-LLaMa/llama_inference_offload.py", line 164, in forward
    layer_outputs = decoder_layer(
  File "/home/ubuntu/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/ubuntu/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/text-generation-webui/repositories/GPTQ-for-LLaMa/quant.py", line 600, in forward
    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query_states.dtype)
  File "/home/ubuntu/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/functional.py", line 1845, in softmax
    ret = input.softmax(dim, dtype=dtype)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 672.00 MiB (GPU 0; 8.00 GiB total capacity; 6.23 GiB already allocated; 0 bytes free; 6.92 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Output generated in 2.48 seconds (0.00 tokens/s, 0 tokens, context 2096, seed 165012704)
```

### System Info

```shell
OS: Ubuntu
GPU: Nvidia 3070 TI
CPU: AMD 5600
```

**Comment by askmyteapot** [comment]
> 3\. context 2096

At a first glance, thats why. Llama models only accept 2048 for context.  Reduce your context size in the frontend you are using and it will work.... but i last time i tried to use Tavern or aganaistic i found it was a bit hit and miss anyway. But that was a few weeks ago.

**Comment by techgo** [comment]
> > 3. context 2096
> 
> At a first glance, thats why. Llama models only accept 2048 for context. Reduce your context size in the frontend you are using and it will work.... but i last time i tried to use Tavern or aganaistic i found it was a bit hit and miss anyway. But that was a few weeks ago.

I think this is the issue. I am going to close this for now and I will revisit should I experience crashing with context under 2000. I appreciate your help!

**Comment by FieldMarshallVague** [comment]
I used some of the params from the OP and it's running for me now.  This is the first 13b model I've used, so I missed these flags.

```
call python server.py --model stable-vicuna-13b --chat --listen-port 7864 --model_type Llama --gpu-memory 23000MiB --cpu-memory 48000MiB --threads 16 --pre_layer 32
```
