### ISSUE TITLE
WEBUI server never starts

### ISSUE THREAD

**Issue by Rubiooo04** [oobabooga/text-generation-webui#1598]
### Describe the bug

When I try to run server.py my web browser doesn't open and I get an error followed by ILLEGAL INSTRUCTION.

I have tried with different versions of VICUNA and ALPACA but the same thing happens with all of them and I can never access the webui

### Is there an existing issue for this?

- [X] I have searched the existing issues

**There are similar errors but there is no solution and none is on a raspberry,**
**I have reopened a ticket because I have increased the information I gave in the last one =)**

### **_1º Normal installation_**
      Step 1 -> I download the text-generation-webui
      Step 2 -> I run `pip3 install -r requirements`
      Step 3 -> I download the ia and add it to the models folder
      Step 4 -> I start the server with `python3 server.py --chat`

### **_2º Using the one click installer_**
      Step 1 -> I download the one-click-installers
      Step 2 -> I run `pip3 install -r requirements`
      Step 3 -> I download the ia and add it to the models folder
      Step 4 -> I start the server with `python3 server.py --chat`

### Screenshot
<details>
 <summary>(click to see the Screenshot)</summary>

![suuu](https://user-images.githubusercontent.com/77902247/234818439-bf32c300-c440-42b1-a054-d182b7dead73.png)
![suuuu](https://user-images.githubusercontent.com/77902247/234818453-415c3362-beae-4bf2-b464-8456a0cf36f3.png)

</details> 

### LOGS
<details>
 <summary>(click to see the logs)</summary>

```shell
Gradio HTTP request redirected to localhost :)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/Pitata/.local/lib/python3.9/site-packages/gradio/strings.py", line 38, in get_updated_messaging
    updated_messaging = requests.get(MESSAGING_API_ENDPOINT, timeout=3).json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Illegal instruction
```
</details> 

### System Info
<details>
 <summary>(click to see the System Info)</summary>

```shell
Hardware: Raspberry pi 4 (4gb ram)
OS: raspberrian 6.1.21-v8 aarch64


Package             Version
------------------- --------------
accelerate          0.18.0
aiofiles            23.1.0
aiohttp             3.8.4
aiosignal           1.3.1
altair              4.2.2
anyio               3.6.2
arandr              0.1.10
astroid             2.5.1
asttokens           2.0.4
async-timeout       4.0.2
attrs               23.1.0
automationhat       0.2.0
beautifulsoup4      4.9.3
blinker             1.4
blinkt              0.1.2
buttonshim          0.0.2
Cap1xxx             0.1.3
certifi             2020.6.20
chardet             4.0.0
charset-normalizer  3.1.0
click               7.1.2
colorama            0.4.4
colorzero           1.1
contourpy           1.0.7
cryptography        3.3.2
cupshelpers         1.0
cycler              0.11.0
datasets            2.11.0
dbus-python         1.2.16
dill                0.3.6
distro              1.5.0
dnspython           2.0.0
docutils            0.16
drumhat             0.1.0
entrypoints         0.4
envirophat          1.0.0
ExplorerHAT         0.4.2
fastapi             0.95.1
ffmpy               0.3.0
filelock            3.12.0
Flask               1.1.2
flexgen             0.1.7
fonttools           4.39.3
fourletterphat      0.1.0
frozenlist          1.3.3
fsspec              2023.4.0
gpg                 1.14.0-unknown
gpiozero            1.6.2
gradio              3.25.0
gradio-client       0.1.3
h11                 0.14.0
html5lib            1.1
httpcore            0.17.0
httpx               0.24.0
huggingface-hub     0.14.1
idna                2.10
importlib-resources 5.12.0
isort               5.6.4
itsdangerous        1.1.0
jedi                0.18.0
Jinja2              2.11.3
jsonschema          4.17.3
kiwisolver          1.4.4
lazy-object-proxy   0.0.0
linkify-it-py       2.0.0
logilab-common      1.8.1
lxml                4.6.3
Markdown            3.3.4
markdown-it-py      2.2.0
MarkupSafe          1.1.1
matplotlib          3.7.1
mccabe              0.6.1
mdit-py-plugins     0.3.3
mdurl               0.1.2
microdotphat        0.2.1
mote                0.0.4
motephat            0.0.3
mpmath              1.3.0
multidict           6.0.4
multiprocess        0.70.14
mypy                0.812
mypy-extensions     0.4.3
networkx            3.1
numpy               1.24.3
oauthlib            3.1.0
orjson              3.8.10
packaging           23.1
pandas              2.0.1
pantilthat          0.0.7
parso               0.8.1
peft                0.3.0.dev0
pexpect             4.8.0
pgzero              1.2
phatbeat            0.1.1
pianohat            0.1.0
picamera2           0.3.9
pidng               4.0.9
piexif              1.1.3
piglow              1.2.5
pigpio              1.78
Pillow              9.5.0
pip                 20.3.4
psutil              5.8.0
PuLP                2.7.0
pyarrow             11.0.0
pycairo             1.16.2
pycups              2.0.1
pydantic            1.10.7
pydub               0.25.1
pygame              1.9.6
Pygments            2.7.1
PyGObject           3.38.0
pyinotify           0.9.6
PyJWT               1.7.1
pylint              2.7.2
PyOpenGL            3.1.5
pyOpenSSL           20.0.1
pyparsing           3.0.9
PyQt5               5.15.2
PyQt5-sip           12.8.1
pyrsistent          0.19.3
pyserial            3.5b0
pysmbc              1.0.23
python-apt          2.2.1
python-dateutil     2.8.2
python-multipart    0.0.6
python-prctl        1.7
pytz                2023.3
PyYAML              5.3.1
rainbowhat          0.1.0
regex               2023.3.23
reportlab           3.5.59
requests            2.25.1
requests-oauthlib   1.0.0
requests-toolbelt   0.9.1
responses           0.12.1
roman               2.0.0
RPi.GPIO            0.7.0
RTIMULib            7.2.1
rwkv                0.7.3
safetensors         0.3.0
scrollphat          0.0.7
scrollphathd        1.2.1
semantic-version    2.10.0
Send2Trash          1.6.0b1
sense-hat           2.4.0
sentencepiece       0.1.98
setuptools          52.0.0
simplejpeg          1.6.4
simplejson          3.17.2
six                 1.16.0
skywriter           0.0.7
sn3218              1.2.7
sniffio             1.3.0
soupsieve           2.2.1
spidev              3.5
ssh-import-id       5.10
starlette           0.26.1
sympy               1.11.1
thonny              4.0.1
tokenizers          0.13.3
toml                0.10.1
toolz               0.12.0
torch               2.0.0
touchphat           0.0.1
tqdm                4.65.0
transformers        4.28.1
twython             3.8.2
typed-ast           1.4.2
typing-extensions   4.5.0
tzdata              2023.3
uc-micro-py         1.0.1
unicornhathd        0.0.4
urllib3             1.26.5
uvicorn             0.21.1
v4l2-python3        0.3.2
webencodings        0.5.1
websockets          11.0.2
Werkzeug            1.0.1
wheel               0.34.2
wrapt               1.12.1
xxhash              3.2.0
yarl                1.9.2
zipp                3.15.0
```
</details>

**Comment by xNul** [comment]
run `start_linux.sh` to run the webui. `bash start_linux.sh`

**Comment by Rubiooo04** [comment]
> run `start_linux.sh` to run the webui. `bash start_linux.sh`

It doesn't work for me I get this
![AI ERROR](https://user-images.githubusercontent.com/77902247/234828817-78fc5ee8-02ce-451c-8c9b-c842aff6f4cd.png)

```
Pitata@Pitata:/media/Pitata/Patataneta/oobabooga_linux $ bash start_linux.sh
Gradio HTTP request redirected to localhost :)
Illegal instruction

Done!
```

**Comment by xNul** [comment]
oh wow that's weird. Could you narrow down what line of code causes that Illegal Instruction?

**Comment by xNul** [comment]
looks like it has something to do with running an executable with the wrong architecture
https://www.google.com/search?q=%22illegal+instruction%22+python

**Comment by Rubiooo04** [comment]
> oh wow that's weird. Could you narrow down what line of code causes that Illegal Instruction?

I don't know how to tell you in which line that happens,

But if I run the server.py directly as I said above, the same thing happens to me, only if it tells me where the error is

**Comment by Rubiooo04** [comment]
> So an initial question.
> 
> 1. did you `git clone https://github.com/oobabooga/text-generation-webui.git` or download a .zip on a windows PC and copy it across?
>    1a) If you didn't git clone, then you will need to completely delete the folder and re-download it using git clone, then get the requirements again. (Unix text encoding is different to windows which is why you cant just copy it across from a windows machine or filesystem)
> 
> Outside of that, i haven't used this ui on an ARM device, so i cant really help further.

I'm going to try this because it didn't work for me to add `OPENBLAS_CORETYPE=ARMV8` before executing the python

**Comment by Rubiooo04** [comment]
> So an initial question.
> 
> 1. did you `git clone https://github.com/oobabooga/text-generation-webui.git` or download a .zip on a windows PC and copy it across?
>    1a) If you didn't git clone, then you will need to completely delete the folder and re-download it using git clone, then get the requirements again. (Unix text encoding is different to windows which is why you cant just copy it across from a windows machine or filesystem)
> 
> Outside of that, i haven't used this ui on an ARM device, so i cant really help further.

I have done as you told me but this is still the same
![image](https://user-images.githubusercontent.com/77902247/234852343-69bc0f2f-8f03-4bb9-b48f-2c8dfd96e430.png)

Although in theory when you run start_linux.sh it redirects you to the webui.py file and that file makes a git clone to the repository so I think the problem could never be that xD

![image](https://user-images.githubusercontent.com/77902247/234854238-69c21086-b93a-4f39-a031-48284fdc0337.png)


> looks like it has something to do with running an executable with the wrong architecture
https://www.google.com/search?q=%22illegal+instruction%22+python

I tried this so that Illegal instruction does not appear

`OPENBLAS_CORETYPE=ARMV8 python server.py --chat`

but i recive 

![image](https://user-images.githubusercontent.com/77902247/234854371-dafd5970-51c7-4f2e-bb91-9469d3053a34.png)

**Comment by Rubiooo04** [comment]
Hey, I managed to advance a bit and I no longer get the `Illegal instruction`, although now I get this other error

```
(textgen) Pitata@Pitata:~/text-generation-webui $ python3 server.py --chat 
Traceback (most recent call last):
  File "/home/Pitata/text-generation-webui/server.py", line 17, in <module>
    import gradio as gr
  File "/home/Pitata/miniforge3/envs/textgen/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/home/Pitata/miniforge3/envs/textgen/lib/python3.10/site-packages/gradio/components.py", line 25, in <module>
    import altair as alt
  File "/home/Pitata/miniforge3/envs/textgen/lib/python3.10/site-packages/altair/__init__.py", line 4, in <module>
    from .vegalite import *
  File "/home/Pitata/miniforge3/envs/textgen/lib/python3.10/site-packages/altair/vegalite/__init__.py", line 2, in <module>
    from .v4 import *
  File "/home/Pitata/miniforge3/envs/textgen/lib/python3.10/site-packages/altair/vegalite/v4/__init__.py", line 2, in <module>
    from .schema import *
  File "/home/Pitata/miniforge3/envs/textgen/lib/python3.10/site-packages/altair/vegalite/v4/schema/__init__.py", line 2, in <module>
    from .core import *
  File "/home/Pitata/miniforge3/envs/textgen/lib/python3.10/site-packages/altair/vegalite/v4/schema/core.py", line 4, in <module>
    from altair.utils.schemapi import SchemaBase, Undefined, _subclasses
  File "/home/Pitata/miniforge3/envs/textgen/lib/python3.10/site-packages/altair/utils/__init__.py", line 13, in <module>
    from .html import spec_to_html
  File "/home/Pitata/miniforge3/envs/textgen/lib/python3.10/site-packages/altair/utils/html.py", line 2, in <module>
    import jinja2
  File "/home/Pitata/miniforge3/envs/textgen/lib/python3.10/site-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/home/Pitata/miniforge3/envs/textgen/lib/python3.10/site-packages/jinja2/environment.py", line 14, in <module>
    from jinja2.defaults import BLOCK_START_STRING, \
  File "/home/Pitata/miniforge3/envs/textgen/lib/python3.10/site-packages/jinja2/defaults.py", line 32, in <module>
    from jinja2.tests import TESTS as DEFAULT_TESTS
  File "/home/Pitata/miniforge3/envs/textgen/lib/python3.10/site-packages/jinja2/tests.py", line 12, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/home/Pitata/miniforge3/envs/textgen/lib/python3.10/collections/__init__.py)
```

**Comment by Rubiooo04** [comment]
Hey, I managed to advance a bit and I no longer get the `Illegal instruction`, although now I get this other error

<details><summary>Error</summary>

```python

(textgen) Pitata@Pitata:~/text-generation-webui $ python3 server.py --chat 
Traceback (most recent call last):
  File "/home/Pitata/text-generation-webui/server.py", line 17, in <module>
    import gradio as gr
  File "/home/Pitata/miniforge3/envs/textgen/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/home/Pitata/miniforge3/envs/textgen/lib/python3.10/site-packages/gradio/components.py", line 25, in <module>
    import altair as alt
  File "/home/Pitata/miniforge3/envs/textgen/lib/python3.10/site-packages/altair/__init__.py", line 4, in <module>
    from .vegalite import *
  File "/home/Pitata/miniforge3/envs/textgen/lib/python3.10/site-packages/altair/vegalite/__init__.py", line 2, in <module>
    from .v4 import *
  File "/home/Pitata/miniforge3/envs/textgen/lib/python3.10/site-packages/altair/vegalite/v4/__init__.py", line 2, in <module>
    from .schema import *
  File "/home/Pitata/miniforge3/envs/textgen/lib/python3.10/site-packages/altair/vegalite/v4/schema/__init__.py", line 2, in <module>
    from .core import *
  File "/home/Pitata/miniforge3/envs/textgen/lib/python3.10/site-packages/altair/vegalite/v4/schema/core.py", line 4, in <module>
    from altair.utils.schemapi import SchemaBase, Undefined, _subclasses
  File "/home/Pitata/miniforge3/envs/textgen/lib/python3.10/site-packages/altair/utils/__init__.py", line 13, in <module>
    from .html import spec_to_html
  File "/home/Pitata/miniforge3/envs/textgen/lib/python3.10/site-packages/altair/utils/html.py", line 2, in <module>
    import jinja2
  File "/home/Pitata/miniforge3/envs/textgen/lib/python3.10/site-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/home/Pitata/miniforge3/envs/textgen/lib/python3.10/site-packages/jinja2/environment.py", line 14, in <module>
    from jinja2.defaults import BLOCK_START_STRING, \
  File "/home/Pitata/miniforge3/envs/textgen/lib/python3.10/site-packages/jinja2/defaults.py", line 32, in <module>
    from jinja2.tests import TESTS as DEFAULT_TESTS
  File "/home/Pitata/miniforge3/envs/textgen/lib/python3.10/site-packages/jinja2/tests.py", line 12, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/home/Pitata/miniforge3/envs/textgen/lib/python3.10/collections/__init__.py)

```

</details> 
<details><summary>Pip freeze</summary>

```
accelerate==0.18.0
aiofiles==23.1.0
aiohttp==3.8.4
aiosignal==1.3.1
altair==4.2.2
anyio==3.6.2
async-timeout==4.0.2
attrs==23.1.0
bitsandbytes==0.38.1
certifi==2022.12.7
charset-normalizer==3.1.0
click==8.1.3
colorama==0.4.6
contourpy==1.0.7
cycler==0.11.0
datasets==2.11.0
dill==0.3.6
entrypoints==0.4
fastapi==0.95.1
ffmpy==0.3.0
filelock==3.12.0
flexgen==0.1.7
fonttools==4.39.3
frozenlist==1.3.3
fsspec==2023.4.0
gradio==3.25.0
gradio_client==0.1.3
h11==0.14.0
httpcore==0.17.0
httpx==0.24.0
huggingface-hub==0.14.1
idna==3.4
Jinja2==2.8.1
jsonschema==4.17.3
kiwisolver==1.4.4
linkify-it-py==2.0.0
llama-cpp-python==0.1.36
Markdown==3.4.3
markdown-it-py==2.2.0
MarkupSafe==0.11
matplotlib==3.7.1
mdit-py-plugins==0.3.3
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
multiprocess==0.70.14
networkx==3.1
numpy==1.24.3
orjson==3.8.10
packaging==23.1
pandas==2.0.1
peft @ git+https://github.com/huggingface/peft@e8f66b8a425eced6c592089d40b8d33d82c2b2f0
Pillow==9.5.0
psutil==5.9.5
PuLP==2.7.0
pyarrow==11.0.0
pydantic==1.10.7
pydub==0.25.1
pyparsing==3.0.9
pyrsistent==0.19.3
python-dateutil==2.8.2
python-multipart==0.0.6
pytz==2023.3
PyYAML==6.0
regex==2023.3.23
requests==2.29.0
responses==0.18.0
rwkv==0.7.3
safetensors==0.3.0
semantic-version==2.10.0
sentencepiece==0.1.98
six==1.16.0
sniffio==1.3.0
starlette==0.26.1
sympy==1.11.1
tokenizers==0.13.3
toolz==0.12.0
torch==2.0.0
torchaudio==2.0.1
torchvision==0.1.6
tqdm==4.65.0
transformers==4.28.1
typing_extensions==4.5.0
tzdata==2023.3
uc-micro-py==1.0.1
urllib3==1.26.15
uvicorn==0.21.1
websockets==11.0.2
xxhash==3.2.0
yarl==1.9.2
```

</details>

**Comment by xNul** [comment]
@Rubiooo04 it looks like things went backwards actually because the code doesn't even reach the `Gradio HTTP request redirected to localhost :)` part of the log. I've never used miniforge before so I don't know how to resolve dependency issues with it
