### ISSUE TITLE
Model Crashes upon interaction with KeyError:'model.layers... , Cuda kernel compilation failed during single click installer 

### ISSUE THREAD

**Issue by HB-Stratos** [oobabooga/text-generation-webui#1602]
### Describe the bug

I can load the Ui successfully, Model loads successfully, but any attempt to generate things fails with a key error. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run the single click installer on windows, observe 
`C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] Das System kann die angegebene Datei nicht finden
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
error: [WinError 2] Das System kann die angegebene Datei nicht finden
CUDA kernel compilation failed.
Attempting installation with wheel.
Collecting quant-cuda==0.0.0`
(ignore the folder name, this was not installed or launched with seait, just lives in the same folder)

Load the model (model used: gpt-x-alpaca-13b-native-4bit-128g-cuda.pt), but upon any interaction it will fail with either a memory error, or a KeyError with flag --gpu-memory 6.

#### Debugging steps taken
Tried manual install on windows with the reddit post. Same compilation error. 
Tried upgrading the seait installed version (which uses venv instead of conda).
Installed cuda, first 12.1.1, then downgrade to 11.7.
Installed Visual Studio Build Tools C++, first 2022, then downgrade to 2019. Made sure C++ is actually installed. cl.exe works within the environment, no PATH variable is set, as is default.
Installed cuDNN
No success anywhere. Resolved other errors but always got stuck on {compiler}: {error}

possibly related issue could be #1273 , though I am seeing a different error.

### Logs

```shell
--- INSTALL EXCERPT ---
Successfully uninstalled datasets-2.11.0
Successfully installed datasets-2.10.1 transformers-4.28.0
running install
C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
creating quant_cuda.egg-info
writing quant_cuda.egg-info\PKG-INFO
writing dependency_links to quant_cuda.egg-info\dependency_links.txt
writing top-level names to quant_cuda.egg-info\top_level.txt
writing manifest file 'quant_cuda.egg-info\SOURCES.txt'
reading manifest file 'quant_cuda.egg-info\SOURCES.txt'
writing manifest file 'quant_cuda.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] Das System kann die angegebene Datei nicht finden
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
error: [WinError 2] Das System kann die angegebene Datei nicht finden
CUDA kernel compilation failed.
Attempting installation with wheel.
Collecting quant-cuda==0.0.0
  Using cached https://github.com/jllllll/GPTQ-for-LLaMa-Wheels/raw/main/quant_cuda-0.0.0-cp310-cp310-win_amd64.whl (398 kB)
Installing collected packages: quant-cuda
Successfully installed quant-cuda-0.0.0
Select the model that you want to download:

A) OPT 6.7B
B) OPT 2.7B


--- FULL LOG OF MODEL LOAD AND CRASH ON INTERACTION ---

Gradio HTTP request redirected to localhost :)
bin C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
Loading gpt4-x-alpaca-13b-native-4bit-128g...
Found the following quantized model: models\gpt4-x-alpaca-13b-native-4bit-128g\gpt-x-alpaca-13b-native-4bit-128g-cuda.pt
Loading model ...
Done.
Using the following device map for the quantized model: {'model.embed_tokens': 0, 'model.layers.0': 0, 'model.layers.1': 0, 'model.layers.2': 0, 'model.layers.3': 0, 'model.layers.4': 0, 'model.layers.5': 0, 'model.layers.6': 0, 'model.layers.7': 0, 'model.layers.8': 0, 'model.layers.9': 0, 'model.layers.10': 0, 'model.layers.11': 0, 'model.layers.12': 0, 'model.layers.13': 0, 'model.layers.14': 0, 'model.layers.15': 0, 'model.layers.16': 0, 'model.layers.17': 0, 'model.layers.18': 0, 'model.layers.19': 0, 'model.layers.20': 0, 'model.layers.21': 0, 'model.layers.22': 0, 'model.layers.23': 0, 'model.layers.24': 0, 'model.layers.25': 0, 'model.layers.26': 0, 'model.layers.27': 0, 'model.layers.28': 0, 'model.layers.29': 0, 'model.layers.30': 0, 'model.layers.31': 0, 'model.layers.32': 0, 'model.layers.33': 'cpu', 'model.layers.34': 'cpu', 'model.layers.35': 'cpu', 'model.layers.36': 'cpu', 'model.layers.37': 'cpu', 'model.layers.38': 'cpu', 'model.layers.39': 'cpu', 'model.norm': 'cpu', 'lm_head': 'cpu'}
Loaded the model in 37.73 seconds.
Loading the extension "gallery"... Ok.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set share=True in launch().
Traceback (most recent call last):
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\text-generation-webui\modules\callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\text-generation-webui\modules\text_generation.py", line 290, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1485, in generate
    return self.sample(
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 2524, in sample
    outputs = self(
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 577, in forward
    layer_outputs = decoder_layer(
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 292, in forward
```

### System Info

```shell
Windows 10 Pro
Ryzen 5 3600
16 GB RAM, 3200 MHZ DDR4
Nvidia GeForce RTX 2060 Super (8 GB)

Logs created with start_windows.bat and model launch parameters: --chat --model-menu  --auto-devices --wbits 4 --groupsize 128 --gpu-memory 6
```

**Comment by xNul** [comment]
Can you verify that a folder starting with "quant_cuda" exists in your `installer_files/env/libs/site-packages` folder? If it doesn't, some fixes I've made to the installer might help https://github.com/xNul/one-click-installers

**Comment by HB-Stratos** [comment]
@xNul I have had a chance to have a look now
Under `text-generation-webui/installer_files/env/libs/` there is no folder called `site-packages`, in fact there is no folder within libs at all.
However, under `env/Lib` there is a site-packages folder, within which I could find `quant_cuda-0.0.0.dist-info` but no `quant-cuda`.
I will attempt to use your fixed installer.

**Comment by HB-Stratos** [comment]
I have tested your installer. It gave me a different looking error, but it still failed to compile quant-cuda

```
Successfully installed datasets-2.10.1 transformers-4.28.0
Processing c:\seait_supereasyaiinstallertool\text-generation-webui\text-generation-webui\repositories\gptq-for-llama
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: quant-cuda
  Building wheel for quant-cuda (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      running bdist_wheel
      running build
      running build_ext
      C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] Das System kann die angegebene Datei nicht finden
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      error: [WinError 2] Das System kann die angegebene Datei nicht finden
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for quant-cuda
  Running setup.py clean for quant-cuda
Failed to build quant-cuda
Installing collected packages: quant-cuda
  Running setup.py install for quant-cuda ... error
  error: subprocess-exited-with-error

  × Running setup.py install for quant-cuda did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running install
      C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] Das System kann die angegebene Datei nicht finden
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      error: [WinError 2] Das System kann die angegebene Datei nicht finden
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> quant-cuda

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
ERROR: GPTQ CUDA kernel compilation failed.
Attempting installation with wheel.
Collecting quant-cuda==0.0.0
  Using cached https://github.com/jllllll/GPTQ-for-LLaMa-Wheels/raw/main/quant_cuda-0.0.0-cp310-cp310-win_amd64.whl (398 kB)
Installing collected packages: quant-cuda
Successfully installed quant-cuda-0.0.0
Wheel installation success!
Continuing with install..
Select the model that you want to download:

A) OPT 6.7B
B) OPT 2.7B
``` 
looking in `env/Lib` again, there is no more `quant-cuda-0.0.0.dist-info` and also no `quant-cuda` folder. Overall, there appear to be less folders total in `Lib` than there used to be.
I used your installer by downloading the repository as a zip, grabbing the contents into my folder, and running `start_windows.bat`

**Comment by xNul** [comment]
@HB-Stratos this is exactly what we're looking for. Cool, now let's see if it runs a model. Get to the download model menu via the install or you can open `cmd_windows.bat`, use the command `cd text-generation-webui`, and then use the command `python download-model.py`. Once there, use the L option and enter this model "wcde/llama-7b-4bit-gr128". Once it finishes downloading, you can try running the model with webui. If it works, you're all set!

It's unfortunate the compilation method didn't work though. There's probably something wrong with the installer.

**Comment by HB-Stratos** [comment]
The llama 7b model works. My model still fails with a key error, or an out of ram if the flags aren't set right. Used the same flags as in the initial post this time, seems to have the same issues. What could cause this?

log: 
```
Gradio HTTP request redirected to localhost :)
bin C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
The following models are available:

1. gpt4-x-alpaca-13b-native-4bit-128g
2. wcde_llama-7b-4bit-gr128

Which one do you want to load? 1-2

1

Loading gpt4-x-alpaca-13b-native-4bit-128g...
Found the following quantized model: models\gpt4-x-alpaca-13b-native-4bit-128g\gpt-x-alpaca-13b-native-4bit-128g-cuda.pt
Loading model ...
Done.
Using the following device map for the quantized model: {'model.embed_tokens': 0, 'model.layers.0': 0, 'model.layers.1': 0, 'model.layers.2': 0, 'model.layers.3': 0, 'model.layers.4': 0, 'model.layers.5': 0, 'model.layers.6': 0, 'model.layers.7': 0, 'model.layers.8': 0, 'model.layers.9': 0, 'model.layers.10': 0, 'model.layers.11': 0, 'model.layers.12': 0, 'model.layers.13': 0, 'model.layers.14': 0, 'model.layers.15': 0, 'model.layers.16': 0, 'model.layers.17': 0, 'model.layers.18': 0, 'model.layers.19': 0, 'model.layers.20': 0, 'model.layers.21': 0, 'model.layers.22': 0, 'model.layers.23': 0, 'model.layers.24': 0, 'model.layers.25': 0, 'model.layers.26': 0, 'model.layers.27': 0, 'model.layers.28': 0, 'model.layers.29': 0, 'model.layers.30': 0, 'model.layers.31': 0, 'model.layers.32': 0, 'model.layers.33': 'cpu', 'model.layers.34': 'cpu', 'model.layers.35': 'cpu', 'model.layers.36': 'cpu', 'model.layers.37': 'cpu', 'model.layers.38': 'cpu', 'model.layers.39': 'cpu', 'model.norm': 'cpu', 'lm_head': 'cpu'}
Loaded the model in 44.35 seconds.
Loading the extension "gallery"... Ok.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\text-generation-webui\modules\callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\text-generation-webui\modules\text_generation.py", line 290, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1485, in generate
    return self.sample(
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 2524, in sample
    outputs = self(
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 577, in forward
    layer_outputs = decoder_layer(
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 196, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\accelerate\hooks.py", line 160, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\accelerate\hooks.py", line 280, in pre_forward
    set_module_tensor_to_device(module, name, self.execution_device, value=self.weights_map[name])
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\accelerate\utils\offload.py", line 123, in __getitem__
    return self.dataset[f"{self.prefix}{key}"]
  File "C:\seait_SuperEasyAIInstallerTool\text-generation-webui\installer_files\env\lib\site-packages\accelerate\utils\offload.py", line 170, in __getitem__
    weight_info = self.index[key]
KeyError: 'model.layers.33.self_attn.q_proj.wf1'
Output generated in 2.76 seconds (0.00 tokens/s, 0 tokens, context 37, seed 2043276947)
``` 

... if I am reading this right it is loading the model on the cpu, but taskmanager is telling me it is loading into vram. What is going on here?

**Comment by xNul** [comment]
@HB-Stratos I've seen a lot of problems with this model. It looks like there's an incompatibility between how the model was built and how it's being used by the transformers library. My guess is that the model was made for a different version of transformers

**Comment by HB-Stratos** [comment]
I'm guessing there's no way for me, the end user, to fix this?

**Comment by xNul** [comment]
@HB-Stratos As far as I know, I'm afraid not
