### ISSUE TITLE
NameError: name 'xformers' is not defined

### ISSUE THREAD

**Issue by SansQuartier** [oobabooga/text-generation-webui#1624]
### Describe the bug

I've tried using `--xformers`, the UI launches fine but trying to type in a prompt nothing happens

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Launch the WebUI with the `--xformers` argument and type in a prompt

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\qherm\Documents\4Chan\AI\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 272, in generate_reply
    output = shared.model.generate(**generate_params)[0]
  File "C:\Users\qherm\Documents\4Chan\AI\oobabooga-windows\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\qherm\Documents\4Chan\AI\oobabooga-windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1485, in generate
    return self.sample(
  File "C:\Users\qherm\Documents\4Chan\AI\oobabooga-windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 2524, in sample
    outputs = self(
  File "C:\Users\qherm\Documents\4Chan\AI\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\qherm\Documents\4Chan\AI\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "C:\Users\qherm\Documents\4Chan\AI\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\qherm\Documents\4Chan\AI\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 577, in forward
    layer_outputs = decoder_layer(
  File "C:\Users\qherm\Documents\4Chan\AI\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\qherm\Documents\4Chan\AI\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "C:\Users\qherm\Documents\4Chan\AI\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\qherm\Documents\4Chan\AI\oobabooga-windows\text-generation-webui\modules\llama_attn_hijack.py", line 73, in xformers_forward
    attn_output = xformers.ops.memory_efficient_attention(query_states, key_states, value_states, attn_bias=xformers.ops.LowerTriangularMask())
NameError: name 'xformers' is not defined
```

### System Info

```shell
Windows 10 Intel(R) Core(TM) i7-8750H 16GB RAM, RTX2070-Max-Q
```

**Comment by askmyteapot** [comment]
Xformers isnt installed by default with the one-click installer. 

You will need to run the cmd_windows.bat then `pip install xformers`

In theory that should get it installed, then you can close it and run your launch script again.

**Comment by SansQuartier** [comment]
Thanks, i thought xformers was included like it is with automatic1111.

( i don't have a cmd_windows.bat file but i used micromamba-cmd.bat instead and it works, i'm assuming any command prompt in the right folder would have worked.)
