### ISSUE TITLE
vicuna safetensors loads but doesnt generate responses

### ISSUE THREAD

**Issue by Garen69** [oobabooga/text-generation-webui#1628]
### Describe the bug

installed the oneclick installer, updated gptq for llama to the cuda version, start the model, type "hi", model types for a bit but then stops.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

 run_cmd("python server.py --wbits 4 --groupsize 128 --model_type Llama --chat --model-menu")

### Logs

```shell
`Loading vicuna-13B-1.1-GPTQ-4bit-128g...
Found the following quantized model: models\vicuna-13B-1.1-GPTQ-4bit-128g\vicuna-13B-1.1-GPTQ-4bit-128g.safetensors
Loading model ...
Done.
Loading the universal LLaMA tokenizer from models\oobabooga_llama-tokenizer...
Loaded the model in 15.27 seconds.
Loading the extension "gallery"... Ok.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\Users\User\Downloads\oobabooga_windows\text-generation-webui\modules\callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "C:\Users\User\Downloads\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 290, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Users\User\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\User\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1563, in generate
    return self.sample(
  File "C:\Users\User\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 2610, in sample
    outputs = self(
  File "C:\Users\User\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\User\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 688, in forward
    outputs = self.model(
  File "C:\Users\User\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\User\Downloads\oobabooga_windows\text-generation-webui\repositories\GPTQ-for-LLaMa\llama_inference_offload.py", line 162, in forward
    layer_outputs = decoder_layer(
  File "C:\Users\User\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\User\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 293, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "C:\Users\User\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\User\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 197, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "C:\Users\User\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\User\Downloads\oobabooga_windows\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 279, in forward
    quant_cuda.vecquant4matmul(x.float(), self.qweight, out, self.scales.float(), self.qzeros, self.g_idx)
TypeError: vecquant4matmul(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch.Tensor, arg1: torch.Tensor, arg2: torch.Tensor, arg3: torch.Tensor, arg4: torch.Tensor, arg5: int) -> None

Invoked with: tensor([[ 0.0097, -0.0423,  0.2747,  ..., -0.0144,  0.0021,  0.0083],
        [ 0.0172,  0.0039, -0.0247,  ..., -0.0062, -0.0020, -0.0056],
        [ 0.0144,  0.0142, -0.0514,  ...,  0.0037,  0.0072,  0.0195],
        ...,
        [ 0.0117, -0.0166,  0.0213,  ...,  0.0200,  0.0124,  0.0093],
        [ 0.0219, -0.0053,  0.0230,  ..., -0.0189,  0.0629,  0.0051],
        [-0.0053, -0.0219, -0.0596,  ...,  0.0373, -0.0200,  0.0070]],
       device='cuda:0'), tensor([[ 1818725976,   138849433, -1535478587,  ..., -1789286762,
          2075669608,  1987818610],
        [ 2053732233, -1672951194, -2035853562,  ..., -1133934939,
           901286473, -1369270681],
        [-1234789703,  1448792681, -1977252477,  ...,  -110598569,
           564566347, -1382511956],
        ...,
        [ 1461565612,   696546725, -1785359048,  ..., -1767143063,
           875526984,  -375875459],
        [-1297377942, -1419229274,  1521908069,  ..., -1665447735,
         -2127055527, -1432790902],
        [  141912649, -1888199995, -1181763453,  ...,  1097831093,
          2058911093, -1488278902]], device='cuda:0', dtype=torch.int32), tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0'), tensor([[0.0319, 0.0154, 0.0293,  ..., 0.0321, 0.0178, 0.0309],
        [0.0106, 0.0081, 0.0083,  ..., 0.0220, 0.0143, 0.0172],
        [0.0074, 0.0074, 0.0071,  ..., 0.0160, 0.0173, 0.0110],
        ...,
        [0.0053, 0.0058, 0.0036,  ..., 0.0119, 0.0083, 0.0072],
        [0.0055, 0.0047, 0.0044,  ..., 0.0125, 0.0083, 0.0078],
        [0.0043, 0.0049, 0.0042,  ..., 0.0097, 0.0085, 0.0066]],
       device='cuda:0'), tensor([[ 1719170664,  1484158581,  2004248422,  ...,  1720083575,
          1987601783,  1986492247],
        [-2006485145,  2004309623,  1987467092,  ...,  1182168967,
          1466398328,  1466402407],
        [ 1717921624,  1987475030,  1987475302,  ..., -2022156713,
          1466328694,  2003003511],
        ...,
        [ 1734834023,  2020051061,  1985443159,  ...,  2002090086,
          1182103143,  2003203703],
        [ 1449682551,  1751611254,  2004182903,  ...,  1970759015,
          1716947079,  1718974310],
        [ 1720145766, -2040043401,  2021950838,  ...,  1988523894,
          2004248166,  1733785702]], device='cuda:0', dtype=torch.int32), tensor([38,  6,  1,  ..., 23,  9, 17], device='cuda:0', dtype=torch.int32)
Output generated in 0.39 seconds (0.00 tokens/s, 0 tokens, context 23, seed 351120562)`
```

### System Info

```shell
Operating System: Windows 10 Pro 64-bit (10.0, Build 19044) (19041.vb_release.191206-1406)
                     BIOS: 2803 (type: UEFI)
                Processor: AMD Ryzen 5 5600X 6-Core Processor              (12 CPUs), ~3.7GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16296MB RAM
                Page File: 8338MB used, 25750MB available
  Chip type: NVIDIA GeForce RTX 3060
      Display Memory: 20276 MB
    Dedicated Memory: 12129 MB
       Shared Memory: 8147 MB
```

**Comment by bubbabug** [comment]
I'm having the same error with ethzanalytics/RedPajama-INCITE-Chat-3B-v1-GPTQ-4bit-128g

**Comment by kaiserdan** [comment]
Same issue here. 

```python server.py --model camelids_llama-33b-int4-gptq-groupsize128-safetensors --listen --model_type Llama --lora supercot  --extensions openai  --monkey-patch --chat```
