### ISSUE TITLE
On interface restart, conn. refused then port is in use

### ISSUE THREAD

**Issue by dblacknc** [oobabooga/text-generation-webui#1632]
### Describe the bug

Git pull as of this morning.  When I change interface options in the UI and click restart, it seems the web browser immediately does a refresh (?) and gets a connection refused.    That's not necessarily a problem - I can click reload when I know the UI is again running.  It'd be cleaner for it to cause the browser to wait for some period of time, even 10 sec or so, then retry.

However, when it then attempts to restart, I see the error shown in the log.

If I then wait for a moment and manually start server.py again, it comes up normally.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Under the Interface tab, change a setting and click the large restart bar.

### Logs

```shell
Traceback (most recent call last):
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/networking.py", line 119, in start_server
    s.bind((LOCALHOST_NAME, server_port))
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/text-generation-webui/server.py", line 933, in <module>
    create_interface()
  File "/root/text-generation-webui/server.py", line 850, in create_interface
    shared.gradio['interface'].launch(prevent_thread_lock=True, share=shared.args.share, server_name=shared.args.listen_host or '0.0.0.0', server_port=shared.args.listen_port, inbrowser=shared.args.auto_launch, auth=auth)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1512, in launch
    server_name, server_port, local_url, app, server = networking.start_server(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/networking.py", line 122, in start_server
    raise OSError(
OSError: Port 80 is in use. If a gradio.Blocks is running on the port, you can close() it or gradio.close_all().
```

### System Info

```shell
Ubuntu 22.04
```

**Comment by dblacknc** [comment]
If I run "netstat -an | fgrep :80" and watch for the TIME_WAIT connections to go away (no output), it'll then start.

It has been a very long time since I did network programming and recall there's some switch or other thing one can do to either cleanly close a socket, or force open one.  I.e. I've seen this behavior before, but it was in C.
