### ISSUE TITLE
Issues instaling 

### ISSUE THREAD

**Issue by talvasconcelos** [oobabooga/text-generation-webui#1634]
### Describe the bug

I'm following the installation and I'm getting this errors when installing dependencies.

```ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pinecone-client 2.2.1 requires dnspython>=2.0.0, which is not installed.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.3 which is incompatible.
```
and 

```ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pinecone-client 2.2.1 requires dnspython>=2.0.0, which is not installed.
```

which then results in the webui not starting, when "loading" the model (even if I had no model, it happened):
``` File "~/Work/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/OpenSSL/crypto.py", line 3253, in <module>
    utils.deprecated(
TypeError: deprecated() got an unexpected keyword argument 'name'

Done!
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Install using the 1 click install on arch

### Logs

```shell
[talvasconcelos@talvasconcelos oobabooga_linux]$ ./start_linux.sh 
Gradio HTTP request redirected to localhost :)
Traceback (most recent call last):
  File "/home/talvasconcelos/Work/oobabooga_linux/text-generation-webui/server.py", line 44, in <module>
    from modules import chat, shared, training, ui
  File "/home/talvasconcelos/Work/oobabooga_linux/text-generation-webui/modules/chat.py", line 16, in <module>
    from modules.text_generation import (encode, generate_reply,
  File "/home/talvasconcelos/Work/oobabooga_linux/text-generation-webui/modules/text_generation.py", line 16, in <module>
    from modules.models import clear_torch_cache, local_rank
  File "/home/talvasconcelos/Work/oobabooga_linux/text-generation-webui/modules/models.py", line 12, in <module>
    from accelerate import infer_auto_device_map, init_empty_weights
  File "/home/talvasconcelos/Work/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/home/talvasconcelos/Work/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/accelerate/accelerator.py", line 31, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/home/talvasconcelos/Work/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/home/talvasconcelos/Work/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/accelerate/utils/__init__.py", line 106, in <module>
    from .launch import (
  File "/home/talvasconcelos/Work/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/accelerate/utils/launch.py", line 24, in <module>
    from ..commands.config.config_args import SageMakerConfig
  File "/home/talvasconcelos/Work/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/accelerate/commands/config/__init__.py", line 19, in <module>
    from .config import config_command_parser
  File "/home/talvasconcelos/Work/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/accelerate/commands/config/config.py", line 25, in <module>
    from .sagemaker import get_sagemaker_input
  File "/home/talvasconcelos/Work/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/accelerate/commands/config/sagemaker.py", line 35, in <module>
    import boto3  # noqa: F401
  File "/home/talvasconcelos/.local/lib/python3.10/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/home/talvasconcelos/.local/lib/python3.10/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/home/talvasconcelos/.local/lib/python3.10/site-packages/botocore/session.py", line 29, in <module>
    import botocore.credentials
  File "/home/talvasconcelos/.local/lib/python3.10/site-packages/botocore/credentials.py", line 35, in <module>
    from botocore.config import Config
  File "/home/talvasconcelos/.local/lib/python3.10/site-packages/botocore/config.py", line 16, in <module>
    from botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS
  File "/home/talvasconcelos/.local/lib/python3.10/site-packages/botocore/endpoint.py", line 24, in <module>
    from botocore.awsrequest import create_request_object
  File "/home/talvasconcelos/.local/lib/python3.10/site-packages/botocore/awsrequest.py", line 24, in <module>
    import botocore.utils
  File "/home/talvasconcelos/.local/lib/python3.10/site-packages/botocore/utils.py", line 32, in <module>
    import botocore.httpsession
  File "/home/talvasconcelos/.local/lib/python3.10/site-packages/botocore/httpsession.py", line 28, in <module>
    from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
  File "/home/talvasconcelos/Work/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
    import OpenSSL.crypto
  File "/home/talvasconcelos/Work/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/home/talvasconcelos/Work/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/home/talvasconcelos/Work/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/OpenSSL/crypto.py", line 3253, in <module>
    utils.deprecated(
TypeError: deprecated() got an unexpected keyword argument 'name'

Done!
```

### System Info

```shell
Linux Arch
HP laptop - I'm just testing...
```

**Comment by xNul** [comment]
@talvasconcelos you could try using the latest version of the one-click installer that I have here which fixes some bugs, but this is the first time I'm seeing this error and it indicates there is something different or wrong with your Arch install, affecting SSL. Maybe an outdated SSL library.

I'm able to install webui perfectly on WSL Arch and have talked with others who have been able to install successfully on normal Arch and Manjaro so this definitely seems to be specific to your system.
