### ISSUE TITLE
Windows - cannot import name 'LlamaTokenizer' from 'transformers'

### ISSUE THREAD

**Issue by benninkcorien** [oobabooga/text-generation-webui#1650]
### Describe the bug

Installed with start_windows today.
Downloaded a few models with download-model.py (galactica, Pythia, WizardLM)
So far so good.

But when I run

    > python server.py  --model-menu

I get an error about LlamaTokenizer.

I can't figure out the correct lowercase/uppercase spelling to get this to work.
When I open the text-generation-webui\modules\models.py file in VSCode, nothing that starts with 'Ll' will autocomplete for that import.

Everything is spelled "LlamaTokenizer" in all the other files. (Nothing says "LLaMa")

│ F:\OobaWeb\text-generation-webui\modules\models.py:13 in <module>                    │
│                                                                                                  │
│    10 import torch                                                                               │
│    11 import transformers                                                                        │
│    12 from accelerate import infer_auto_device_map, init_empty_weights                           │
│ ❱  13 from transformers import (AutoConfig, AutoModel, AutoModelForCausalLM,                     │
│    14 │   │   │   │   │   │     AutoModelForSeq2SeqLM, AutoTokenizer,                            │
│    15 │   │   │   │   │   │     BitsAndBytesConfig, LlamaTokenizer)                              │
│    16                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'LlamaTokenizer' from 'transformers'

 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Install and try to run on windows.

### Logs

```shell
$ py server.py --chat --model-menu
Gradio HTTP request redirected to localhost :)
Exception in thread Thread-1 (get_updated_messaging):
Traceback (most recent call last):
  File "C:\Users\Corien\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Corien\AppData\Local\Programs\Python\Python310\lib\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Corien\AppData\Local\Programs\Python\Python310\lib\site-packages\simplejson\decoder.py", line 372, in decode
    obj, end = self.raw_decode(s)
  File "C:\Users\Corien\AppData\Local\Programs\Python\Python310\lib\site-packages\simplejson\decoder.py", line 402, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Corien\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Corien\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Corien\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\strings.py", line 38, in get_updated_messaging
    updated_messaging = requests.get(MESSAGING_API_ENDPOINT, timeout=3).json()
  File "C:\Users\Corien\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ F:\OobaWebUiTextModels\text-generation-webui\server.py:44 in <module>                            │
│                                                                                                  │
│    41 from PIL import Image                                                                      │
│    42                                                                                            │
│    43 import modules.extensions as extensions_module                                             │
│ ❱  44 from modules import chat, shared, training, ui                                             │
│    45 from modules.html_generator import chat_html_wrapper                                       │
│    46 from modules.LoRA import add_lora_to_model                                                 │
│    47 from modules.models import load_model, load_soft_prompt, unload_model                      │
│                                                                                                  │
│ F:\OobaWebUiTextModels\text-generation-webui\modules\chat.py:16 in <module>                      │
│                                                                                                  │
│    13 import modules.shared as shared                                                            │
│    14 from modules.extensions import apply_extensions                                            │
│    15 from modules.html_generator import chat_html_wrapper, make_thumbnail                       │
│ ❱  16 from modules.text_generation import (encode, generate_reply,                               │
│    17 │   │   │   │   │   │   │   │   │    get_max_prompt_length)                                │
│    18                                                                                            │
│    19                                                                                            │
│                                                                                                  │
│ F:\OobaWebUiTextModels\text-generation-webui\modules\text_generation.py:16 in <module>           │
│                                                                                                  │
│    13 │   │   │   │   │   │   │      _SentinelTokenStoppingCriteria)                             │
│    14 from modules.extensions import apply_extensions                                            │
│    15 from modules.html_generator import generate_4chan_html, generate_basic_html                │
│ ❱  16 from modules.models import clear_torch_cache, local_rank                                   │
│    17                                                                                            │
│    18                                                                                            │
│    19 def get_max_prompt_length(state):                                                          │
│                                                                                                  │
│ F:\OobaWebUiTextModels\text-generation-webui\modules\models.py:13 in <module>                    │
│                                                                                                  │
│    10 import torch                                                                               │
│    11 import transformers                                                                        │
│    12 from accelerate import infer_auto_device_map, init_empty_weights                           │
│ ❱  13 from transformers import (AutoConfig, AutoModel, AutoModelForCausalLM,                     │
│    14 │   │   │   │   │   │     AutoModelForSeq2SeqLM, AutoTokenizer,                            │
│    15 │   │   │   │   │   │     BitsAndBytesConfig, LlamaTokenizer)                              │
│    16                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'LlamaTokenizer' from 'transformers'
(C:\Users\Corien\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\__init__.py)
```

### System Info

```shell
localhost on Win11.

Nvidia RTX 3070, CUDA 11.7, torch installed.
```

**Comment by askmyteapot** [comment]
My first guess would be that you are running an ancient version of Transformers. 
Alternatively, you could be using a model that still has the old llama tokenizer_config.json. The Tokenizer_class needs to be "LlamaTokenizer"

Also, model-menu is no longer needed, as model loading can be done easily from the ui now.

**Comment by benninkcorien** [comment]
Thanks! 
pip install -U transformers worked.
(I was running 4.27, now running transformers 4.28).
I'm getting the webui now.

**Comment by 2018211801** [comment]
my transformer ==4.29.2,and I still have the error ,why?

**Comment by AllanOricil** [comment]
Im using the latest release of transformers and Im still with this error

transformers @ git+https://github.com/huggingface/transformers@9fe3f585bb4ea29f209dc705d269fbe292e1128f

```txt
annotated-types==0.6.0
certifi==2024.2.2
charset-normalizer==3.3.2
deepspeed==0.14.2
filelock==3.13.4
fsspec==2024.3.1
hf_transfer==0.1.6
hjson==3.1.0
huggingface-hub==0.22.2
idna==3.7
Jinja2==3.1.3
MarkupSafe==2.1.5
mpmath==1.3.0
networkx==3.3
ninja==1.11.1.1
numpy==1.26.4
packaging==24.0
psutil==5.9.8
py-cpuinfo==9.0.0
pydantic==2.7.1
pydantic_core==2.18.2
pynvml==11.5.0
PyYAML==6.0.1
regex==2024.4.28
requests==2.31.0
safetensors==0.4.3
sympy==1.12
tokenizers==0.19.1
torch==2.3.0
tqdm==4.66.2
transformers @ git+https://github.com/huggingface/transformers@9fe3f585bb4ea29f209dc705d269fbe292e1128f
typing_extensions==4.11.0
urllib3==2.2.1
```
