### ISSUE TITLE
NameError: name 'matmul_248_kernel' is not defined

### ISSUE THREAD

**Issue by IndrasMirror** [oobabooga/text-generation-webui#1681]
### Describe the bug

I can load up the model successfully but when I give any input it fails and returns this error. I couldn't get the packages triton or trioton to install for the life of me, they are being met with a (Could not find a version that satisfies requirement). Not sure if that's what is causing it.

'''To create a public link, set `share=True` in `launch()`.
Loading GPT4xAlpaca-13b-4bit-128g CUDA...
trioton not installed.
triton not installed.
Found the following quantized model: models\GPT4xAlpaca-13b-4bit-128g CUDA\gpt-x-alpaca-13b-native-4bit-128g-cuda.pt
Loading model ...
Done.
Loading the universal LLaMA tokenizer from models\oobabooga_llama-tokenizer...
Loaded the model in 20.22 seconds.
Traceback (most recent call last):
  File "E:\AI\Oobagooba\text-generation-webui\modules\callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\Oobagooba\text-generation-webui\modules\text_generation.py", line 290, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Users\excid\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\excid\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\generation\utils.py", line 1485, in generate
    return self.sample(
           ^^^^^^^^^^^^
  File "C:\Users\excid\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\generation\utils.py", line 2524, in sample
    outputs = self(
              ^^^^^
  File "C:\Users\excid\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\excid\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\models\llama\modeling_llama.py", line 687, in forward
    outputs = self.model(
              ^^^^^^^^^^^
  File "C:\Users\excid\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\excid\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\models\llama\modeling_llama.py", line 577, in forward
    layer_outputs = decoder_layer(
                    ^^^^^^^^^^^^^^
  File "C:\Users\excid\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\excid\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\models\llama\modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
                                                          ^^^^^^^^^^^^^^^
  File "C:\Users\excid\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\excid\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\models\llama\modeling_llama.py", line 196, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\excid\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\Oobagooba\text-generation-webui\repositories\GPTQ-for-LLaMa\quant\quant_linear.py", line 375, in forward
    out = QuantLinearFunction.apply(x.reshape(-1, x.shape[-1]), self.qweight, self.scales, self.qzeros, self.g_idx, self.bits, self.maxq)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\excid\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\excid\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\cuda\amp\autocast_mode.py", line 106, in decorate_fwd
    return fwd(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\Oobagooba\text-generation-webui\repositories\GPTQ-for-LLaMa\quant\quant_linear.py", line 287, in forward
    output = matmul248(input, qweight, scales, qzeros, g_idx, bits, maxq)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\Oobagooba\text-generation-webui\repositories\GPTQ-for-LLaMa\quant\quant_linear.py", line 267, in matmul248
    matmul_248_kernel[grid](input, qweight, output, scales, qzeros, g_idx, input.shape[0], qweight.shape[1], input.shape[1], bits, maxq, input.stride(0), input.stride(1), qweight.stride(0),
    ^^^^^^^^^^^^^^^^^
NameError: name 'matmul_248_kernel' is not defined
Output generated in 0.28 seconds (0.00 tokens/s, 0 tokens, context 37, seed 881328569)'''

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Install Oobagooba WebUI - a) Nvidia

### Logs

```shell
n/a
```

### System Info

```shell
CPU - Ryzen 5700X
GPU - Nvidia RTX 3060 Eagle

Running locally
```

**Comment by askmyteapot** [comment]
It's trying to load the Triton version of GPTQ. 
You will need to follow https://github.com/oobabooga/text-generation-webui/blob/main/docs/GPTQ-models-(4-bit-mode).md

**Comment by IndrasMirror** [comment]
All good got it working by doing a fresh install using this One-click installer script 

https://hub.tcno.co/ai/text-ai/vicuna/

https://www.youtube.com/watch?v=ByV5w1ES38A
