### ISSUE TITLE
LLaMa Fails to run in 8 bit mode

### ISSUE THREAD

**Issue by mwbryant** [oobabooga/text-generation-webui#170]
I have followed all the instructions in the main issue and have the model working on my 3070.  However when I attempt to get better performance with --load-in-8-bit the model fails to load with the following message: 
```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
Traceback (most recent call last):
  File "/media/matthew/Disk 1/llama/text-generation-webui/server.py", line 188, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/media/matthew/Disk 1/llama/text-generation-webui/modules/models.py", line 122, in load_model
    model = eval(command)
  File "<string>", line 1, in <module>
  File "/home/matthew/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "/home/matthew/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2578, in from_pretrained
    raise ValueError(
ValueError: 
                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you have set a value for `max_memory` you should increase that. To have
                        an idea of the modules that are set on the CPU or RAM you can print model.hf_device_map.
```

Others in that thread seemed to run into the same issue and I could not see any solution mentioned beyond giving up on the flag.  

The full command I am running is `python server.py --listen --no-stream  --gpu-memory 5 --auto-devices --load-in-8bit` but any permutation I've tried gives the same result

**Comment by oobabooga** [comment]
Try removing `--gpu-memory`. If that fails, try increasing the number after `--gpu-memory` 1 at a time. This error happens when bitsandbytes doesn't have enough memory to load the model.

**Comment by mwbryant** [comment]
Hmm with `python server.py --listen --no-stream --auto-devices --load-in-8bit` gpu memory increases until it crashes with the normal OOM error.  With `python server.py --listen --no-stream  --gpu-memory 1 --auto-devices --load-in-8bit` I get the same error message I got above

**Comment by oobabooga** [comment]
No, not `--gpu-memory 1`. 

Try `--gpu-memory 4`, then `--gpu-memory 3`if it fails, etc

**Comment by mwbryant** [comment]
Sorry I was unclear, I tried every single number and all fail the same way, even 1 which should have the easiest time working if I'm understanding correctly.

**Comment by Titaniumtown** [comment]
I can also reproduce this error. But I only get this error on models that would require more ram than my gpu can provide. LLaMA-7B and LLaMA-13B work, but LLaMA-30B fails with this error.

**Comment by sashasubbbb** [comment]
For 8gb VRAM i was able to run LLaMA-7B in 8bit mode with --gpu-memory 7 (but it did not really help with anything when generating gets me OOM 20MB). Anything below --gpu-memory 7 gives the same error. 32gb RAM.
