### ISSUE TITLE
Unable to open any language models. 

### ISSUE THREAD

**Issue by DuckersMcQuack** [oobabooga/text-generation-webui#1715]
### Describe the bug

1. Aitrepreneur_wizardLM-7B-GPTQ-4bit-128g
2. facebook_opt-350m
3. TheBloke_stable-vicuna-13B-GPTQ

Which one do you want to load? 1-3

3

Loading TheBloke_stable-vicuna-13B-GPTQ...
Loading checkpoint shards:   0%|                                                                 | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "G:\Stablechat\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 442, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "G:\Stablechat\oobabooga_windows\installer_files\env\lib\site-packages\torch\serialization.py", line 791, in load    with _open_file_like(f, 'rb') as opened_file:
  File "G:\Stablechat\oobabooga_windows\installer_files\env\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "G:\Stablechat\oobabooga_windows\installer_files\env\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models\\TheBloke_stable-vicuna-13B-GPTQ\\pytorch_model-00001-of-00003.bin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\Stablechat\oobabooga_windows\text-generation-webui\server.py", line 914, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "G:\Stablechat\oobabooga_windows\text-generation-webui\modules\models.py", line 217, in load_model
    model = LoaderClass.from_pretrained(checkpoint, **params)
  File "G:\Stablechat\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "G:\Stablechat\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2795, in from_pretrained
    ) = cls._load_pretrained_model(
  File "G:\Stablechat\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 3109, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "G:\Stablechat\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 445, in load_state_dict
    with open(checkpoint_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models\\TheBloke_stable-vicuna-13B-GPTQ\\pytorch_model-00001-of-00003.bin'

Done!
Press any key to continue . . .

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Clean install oobabooga one click, download TheBloke_stable-vicuna-13B-GPTQ, quit the cmd, then start it again, and select vicuna and it errors out.

### Screenshot

![image](https://user-images.githubusercontent.com/9039370/235515037-0922d322-249e-4f3a-ba7a-d19a369054e2.png)

### Logs

```shell
Loading TheBloke_stable-vicuna-13B-GPTQ...
Loading checkpoint shards:   0%|                                                                 | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "G:\Stablechat\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 442, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "G:\Stablechat\oobabooga_windows\installer_files\env\lib\site-packages\torch\serialization.py", line 791, in load    with _open_file_like(f, 'rb') as opened_file:
  File "G:\Stablechat\oobabooga_windows\installer_files\env\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "G:\Stablechat\oobabooga_windows\installer_files\env\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models\\TheBloke_stable-vicuna-13B-GPTQ\\pytorch_model-00001-of-00003.bin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\Stablechat\oobabooga_windows\text-generation-webui\server.py", line 914, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "G:\Stablechat\oobabooga_windows\text-generation-webui\modules\models.py", line 217, in load_model
    model = LoaderClass.from_pretrained(checkpoint, **params)
  File "G:\Stablechat\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "G:\Stablechat\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2795, in from_pretrained
    ) = cls._load_pretrained_model(
  File "G:\Stablechat\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 3109, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "G:\Stablechat\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 445, in load_state_dict
    with open(checkpoint_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models\\TheBloke_stable-vicuna-13B-GPTQ\\pytorch_model-00001-of-00003.bin'
```

### System Info

```shell
Windows 11 home 22h2

R9 5900x
trident Z neo 64GB 3600mhz
MSI 3090 suprim X
```

**Comment by DuckersMcQuack** [comment]
Went through the error now, and the vicuna doesn't have the "pytorch_model-00001-of-00003.bin", just "stable-vicuna-13B-GPTQ-4bit.compat.no-act-order.safetensors", is there some conversion needed?

**Comment by LaaZa** [comment]
It is a GPTQ model, set wbits, groupsize and model_type to match the model. In this case wbits=4 and groupsize=128 and model_type llama. (some models are detected automatically)
When the model is not loading(errors out) set the GPTQ settings to these and save the config, then reload the model.

**Comment by DuckersMcQuack** [comment]
Got it working as well by wiping all of it, download first a random small model of the OPT was it, then in webGUI, then download vicuna, and it loaded fine with all up to date.

And don't know if i can have a follow up comment regarding another issue:

How can i make the word generator use more cuda performance? when i had quite little loaded into the memory, it used little performance as well. Had to pretty much max out the 24GB memory to see near 100% cuda performance. Is it only set to use X amount of cuda per token?

**Comment by JayDark1** [comment]
> It is a GPTQ model, set wbits, groupsize and model_type to match the model. In this case wbits=4 and groupsize=128 and model_type llama. (some models are detected automatically) When the model is not loading(errors out) set the GPTQ settings to these and save the config, then reload the model.

When I set those parameters the error only changes. More pressing, I can load no model - how is one supposed to know which parameters a model needs?
