### ISSUE TITLE
API doesn't load in docker version

### ISSUE THREAD

**Issue by Reezlaw** [oobabooga/text-generation-webui#1729]
### Describe the bug

If I try to load the extension with the CLI argument "--extensions api" in the .env file I get this:

Loading the extension "api"... Fail.
Traceback (most recent call last):
  File "/app/modules/extensions.py", line 23, in load_extensions
    extension.setup()
  File "/app/extensions/api/script.py", line 9, in setup
    blocking_api.start_server(BLOCKING_PORT, share=shared.args.public_api)
AttributeError: 'Namespace' object has no attribute 'public_api'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

In .env:
CLI_ARGS=--model xyz --no-stream --wbits 4 --groupsize 128 --listen --auto-devices --extensions api

docker-compose up

### Logs

```shell
Loading the extension "api"... Fail.
Traceback (most recent call last):
  File "/app/modules/extensions.py", line 23, in load_extensions
    extension.setup()
  File "/app/extensions/api/script.py", line 9, in setup
    blocking_api.start_server(BLOCKING_PORT, share=shared.args.public_api)
AttributeError: 'Namespace' object has no attribute 'public_api'
```

### System Info

```shell
OS: Manjaro
```

**Comment by narayanmiani** [comment]
![image](https://user-images.githubusercontent.com/7037630/235580006-6846bccd-33df-42bb-84f8-de1e336aa410.png)
This is how chatGPT fixed it for me. Idk if this is ideal way to do it though. But it works, I can now connect to silly tavern.
