### ISSUE TITLE
bitsandbytes error on 13B model (working on 7B) - Linux/3090

### ISSUE THREAD

**Issue by HappyCatKitten** [oobabooga/text-generation-webui#173]
**This works on Linux with 3090** 

python server.py --load-in-8bit --model LLaMa-7B
python server.py  --model LLaMa-7B

**However this doesnt work.**

python server.py --load-in-8bit --model LLaMa-13B
python server.py  --model LLaMa-13B

I have attempted to update the bitsandbytes library but hasnt resolved it

**Error produced.**

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/home/monster/.local/lib/python3.10/site-packages/bitsandbytes/cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading checkpoint shards:   0%|                                                                                                                            | 0/41 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/monster/Desktop/LLama/text-generation-webui/server.py", line 188, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/monster/Desktop/LLama/text-generation-webui/modules/models.py", line 122, in load_model

**Comment by oobabooga** [comment]
See here https://github.com/oobabooga/text-generation-webui/issues/147#issuecomment-1456040134

**Comment by HappyCatKitten** [comment]
> 

This looks like Windows. im running Linux
