### ISSUE TITLE
one click install- 2nd gen or so (I will just do a simple error dump) cmd shell after installation is done.

### ISSUE THREAD

**Issue by haindmade** [oobabooga/text-generation-webui#1732]
### Describe the bug

I have tried several one-click and the LLM models. (3) vicuna and bloke and..............
[OOGA_FAILED.txt](https://github.com/oobabooga/text-generation-webui/files/11369423/OOGA_FAILED.txt)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

one click install: start_windows.bat

### Logs

```shell
Input> TheBloke/vicuna-13B-1.1-GPTQ-4bit-128g
Downloading the model to models\TheBloke_vicuna-13B-1.1-GPTQ-4bit-128g
100%|██████████████████████████████████████████████████████████████████████████████████████████| 7.67k /7.67k  268kiB/s
100%|██████████████████████████████████████████████████████████████████████████████████████████| 576   /576    576kiB/s
100%|██████████████████████████████████████████████████████████████████████████████████████████| 131   /131    131kiB/s
100%|██████████████████████████████████████████████████████████████████████████████████████████| 411   /411    411kiB/s
100%|██████████████████████████████████████████████████████████████████████████████████████████| 500k  /500k   477kiB/s
100%|██████████████████████████████████████████████████████████████████████████████████████████| 699   /699    699kiB/s
100%|█████████████████████████████████████████████████████████████████████████████████████████| 7.26G /7.26G  39.4MiB/s
Gradio HTTP request redirected to localhost :)
bin C:\Users\333mo\AI_CHAT\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
Loading TheBloke_vicuna-13B-1.1-GPTQ-4bit-128g...
Found the following quantized model: models\TheBloke_vicuna-13B-1.1-GPTQ-4bit-128g\vicuna-13B-1.1-GPTQ-4bit-128g.latest.safetensors
Traceback (most recent call last):
  File "C:\Users\333mo\AI_CHAT\oobabooga_windows\text-generation-webui\server.py", line 914, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\333mo\AI_CHAT\oobabooga_windows\text-generation-webui\modules\models.py", line 158, in load_model
    model = load_quantized(model_name)
  File "C:\Users\333mo\AI_CHAT\oobabooga_windows\text-generation-webui\modules\GPTQ_loader.py", line 176, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.wbits, shared.args.groupsize, kernel_switch_threshold=threshold)
  File "C:\Users\333mo\AI_CHAT\oobabooga_windows\text-generation-webui\modules\GPTQ_loader.py", line 44, in _load_quant
    model = AutoModelForCausalLM.from_config(config)
  File "C:\Users\333mo\AI_CHAT\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 411, in from_config
    return model_class._from_config(config, **kwargs)
  File "C:\Users\333mo\AI_CHAT\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 1146, in _from_config
    model = cls(config, **kwargs)
  File "C:\Users\333mo\AI_CHAT\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 614, in __init__
    self.model = LlamaModel(config)
  File "C:\Users\333mo\AI_CHAT\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 445, in __init__
    self.layers = nn.ModuleList([LlamaDecoderLayer(config) for _ in range(config.num_hidden_layers)])
  File "C:\Users\333mo\AI_CHAT\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 445, in <listcomp>
    self.layers = nn.ModuleList([LlamaDecoderLayer(config) for _ in range(config.num_hidden_layers)])
  File "C:\Users\333mo\AI_CHAT\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 255, in __init__
    self.self_attn = LlamaAttention(config=config)
  File "C:\Users\333mo\AI_CHAT\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 179, in __init__
    self.o_proj = nn.Linear(self.num_heads * self.head_dim, self.hidden_size, bias=False)
  File "C:\Users\333mo\AI_CHAT\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\linear.py", line 96, in __init__
    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 52428800 bytes.

Done!
Press any key to continue . . .
```

### System Info

```shell
Win10>Nvidia3070
```

**Comment by hypersniper05** [comment]
Can you get into the ui? If so make sure 4bit, 128, llama model are selected in the models page then reload the model. It should work

**Comment by Primary-Ad2848** [comment]
i have same issue!

![Screenshot_80](https://user-images.githubusercontent.com/132370329/235699613-bd40544f-cf24-4965-8d50-61b22c513aa4.png)

my gpu is : nvidia 940mx 4gb

**Comment by xNul** [comment]
Anyone who is getting this error does not have enough memory to load the model and needs to choose a smaller model. This model https://huggingface.co/wcde/llama-7b-4bit-gr128 works on most GPUs. If you selected the CPU option on install, this model https://huggingface.co/Drararara/llama-7b-ggml should work for you

**Comment by Primary-Ad2848** [comment]
> Anyone who is getting this error does not have enough memory to load the model and needs to choose a smaller model. This model https://huggingface.co/wcde/llama-7b-4bit-gr128 works on most GPUs. If you selected the CPU option on install, this model https://huggingface.co/Drararara/llama-7b-ggml should work for you

I am getting this error while installing the application, should I select cpu instead of gpu? 
my gpu is: nvidia 940mx

**Comment by xNul** [comment]
@Primary-Ad2848 oh your error is different. Windows has a limit to how long you can make a path (i.e. how many folders deep you can have) and it looks like the install is failing because it reached that limit. Try installing to C:\Users\hayra\Desktop instead

**Comment by xNul** [comment]
What version of Windows do you have and is it 64bit or 32bit?

**Comment by jllllll** [comment]
@Primary-Ad2848 If you absolutely need to have the webui installed in that path, you can enable long file path support in Windows. The easiest way of doing this that I know of is this:
1. Open CMD command prompt as admin
2. Enter this command:
```
Reg add "HKLM\SYSTEM\CurrentControlSet\Control\FileSystem" /v "LongPathsEnabled" /t REG_DWORD /d "1" /f
```
You may need to restart your computer after that command, not sure.
This may or may not work with Windows 11 as long file path support on that os is buggy and may refuse to enable.

**Comment by haindmade** [comment]
Hey.yes. 16 and vram.But. Another wrote it was a long string error.I have a Nvda 3070 and chose GPU. After choosing GPU…that was where it all just spit out strings of errors.New laptop/specs are what everyone has now….for the gaming laptops.I will try to do both with yours and maybe up the vram.Thanks. Tried the one click 7 times. Actually at the top level C/user and the other person said to go to C: user/desktop.My SD is on a desktop where all of this would work. But. Those models/sizes are getting massive.Don’t know. Thanks for your help.   Sent from a Samsung Note 5 From: bkutasiSent: Tuesday, May 2, 2023 9:01 PMTo: oobabooga/text-generation-webuiCc: haindmade; AuthorSubject: Re: [oobabooga/text-generation-webui] one click install- 2nd gen or so (I will just do a simple error dump) cmd shell after installation is done. (Issue #1732) Looks like a memory error. I’ve seen this when i tried to load large models and didn't have virtual memory turned on. I had enough memory and enough vram but a large amount of virt mem was needed to fix this problem.What GPU do you have? Does it have enough VRAM? Do you have a large enough page file/virtual memory?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by haindmade** [comment]
Hey.Win10/64. It is a newer laptop that I wanted to use specifically for LLM’s/text. I have a 3070 and chose GPU. And have vram setup.    Sent from a Samsung Note 5 From: Blake WyattSent: Wednesday, May 3, 2023 2:23 AMTo: oobabooga/text-generation-webuiCc: haindmade; AuthorSubject: Re: [oobabooga/text-generation-webui] one click install- 2nd gen or so (I will just do a simple error dump) cmd shell after installation is done. (Issue #1732) What version of Windows do you have and is it 64bit or 32bit?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by haindmade** [comment]
Hey.Let me try both solutions.DesktopIt is at the C: user level.So maybe trying the CMD/Admin might work.Thank you.    Sent from a Samsung Note 5 From: jllllllSent: Wednesday, May 3, 2023 4:51 AMTo: oobabooga/text-generation-webuiCc: haindmade; AuthorSubject: Re: [oobabooga/text-generation-webui] one click install- 2nd gen or so (I will just do a simple error dump) cmd shell after installation is done. (Issue ***@***.*** If you absolutely need to have the webui installed in that path, you can enable long file path support in Windows. The easiest way of doing this that I know of is this:Open CMD command prompt as adminEnter this command:Reg add "HKLM\SYSTEM\CurrentControlSet\Control\FileSystem" /v "LongPathsEnabled" /t REG_DWORD /d "1" /fYou may need to restart your computer after that command, not sure.This may or may not work with Windows 11 as long file path support on that os is buggy and may refuse to enable.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by xNul** [comment]
@haindmade I don't think you have the path issue. That was a response to @Primary-Ad2848. In your case with 16gb of VRAM, you should definitely be able to run the model. How much normal RAM do you have? If you have 16gb or more then maybe pytorch isn't being used efficiently enough by webui

**Comment by haindmade** [comment]
Input> L

Then type the name of your desired Hugging Face model in the format organization/name.

Examples:
facebook/opt-1.3b
EleutherAI/pythia-1.4b-deduped

Input> TheBloke/stable-vicuna-13B-GPTQ
Downloading the model to models\TheBloke_stable-vicuna-13B-GPTQ
100%|██████████████████████████████████████████████████████████████████████████████████████████| 13.2k /13.2k  264kiB/s
100%|█████████████████████████████████████████████████████████████████████████████████████████| 21.0  /21.0   21.0kiB/s
100%|██████████████████████████████████████████████████████████████████████████████████████████| 587   /587    588kiB/s
100%|██████████████████████████████████████████████████████████████████████████████████████████| 137   /137    137kiB/s
100%|██████████████████████████████████████████████████████████████████████████████████████████| 33.4k /33.4k  172kiB/s
100%|█████████████████████████████████████████████████████████████████████████████████████████| 96.0  /96.0   94.8kiB/s
100%|█████████████████████████████████████████████████████████████████████████████████████████| 7.26G /7.26G  48.3MiB/s
100%|█████████████████████████████████████████████████████████████████████████████████████████| 1.84M /1.84M  1.41MiB/s
100%|██████████████████████████████████████████████████████████████████████████████████████████| 500k  /500k   504kiB/s
100%|██████████████████████████████████████████████████████████████████████████████████████████| 715   /715    358kiB/s
Gradio HTTP request redirected to localhost :)
bin C:\Users\333mo\Desktop\AI\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
Loading TheBloke_stable-vicuna-13B-GPTQ...
Loading checkpoint shards:   0%|                                                                 | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\333mo\Desktop\AI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 442, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "C:\Users\333mo\Desktop\AI\oobabooga_windows\installer_files\env\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\333mo\Desktop\AI\oobabooga_windows\installer_files\env\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\333mo\Desktop\AI\oobabooga_windows\installer_files\env\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models\\TheBloke_stable-vicuna-13B-GPTQ\\pytorch_model-00001-of-00003.bin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\333mo\Desktop\AI\oobabooga_windows\text-generation-webui\server.py", line 914, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\333mo\Desktop\AI\oobabooga_windows\text-generation-webui\modules\models.py", line 84, in load_model
    model = LoaderClass.from_pretrained(Path(f"{shared.args.model_dir}/{model_name}"), low_cpu_mem_usage=True, torch_dtype=torch.bfloat16 if shared.args.bf16 else torch.float16, trust_remote_code=trust_remote_code)
  File "C:\Users\333mo\Desktop\AI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\333mo\Desktop\AI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2795, in from_pretrained
    ) = cls._load_pretrained_model(
  File "C:\Users\333mo\Desktop\AI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 3109, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "C:\Users\333mo\Desktop\AI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 445, in load_state_dict
    with open(checkpoint_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models\\TheBloke_stable-vicuna-13B-GPTQ\\pytorch_model-00001-of-00003.bin'

Done!
