### ISSUE TITLE
Getting TypeError: '>' not supported between instances of 'str' and 'int' when trying to load any model

### ISSUE THREAD

**Issue by samsal** [oobabooga/text-generation-webui#1736]
### Describe the bug

I'm using docker and just ran a git pull and then a docker compose up --build.
when trying to load any model from the web interface i get the following error:

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

git pull
docker compose up --build

### Logs

```shell
==========
== CUDA ==
==========

CUDA Version 11.8.0

Container image Copyright (c) 2016-2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

Gradio HTTP request redirected to localhost :)
bin /app/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
Starting streaming server at ws://0.0.0.0:5005/api/v1/stream
Starting API at http://0.0.0.0:5000/api
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/app/venv/lib/python3.10/site-packages/gradio/routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "/app/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "/app/venv/lib/python3.10/site-packages/gradio/blocks.py", line 916, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/app/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/app/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/app/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/app/server.py", line 243, in update_model_parameters
    if i > 0:
TypeError: '>' not supported between instances of 'str' and 'int'
Traceback (most recent call last):
  File "/app/venv/lib/python3.10/site-packages/gradio/routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "/app/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "/app/venv/lib/python3.10/site-packages/gradio/blocks.py", line 916, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/app/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/app/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/app/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/app/server.py", line 243, in update_model_parameters
    if i > 0:
TypeError: '>' not supported between instances of 'str' and 'int'
```

### System Info

```shell
Ubuntu 22.04 + docker (portainer) + RTX 3090
```

**Comment by samsal** [comment]
My bad. The error seems to happen only when trying to load the `gozfarb_pygmalion-7b-4bit-128g-cuda` model. But after that error happens, the container needs to be restarted to be able to load any other model. So I guess the pygmalion model is the probem. Not sure why though.

**Comment by FrancescoSaverioZuppichini** [comment]
same issue here

**Comment by FrancescoSaverioZuppichini** [comment]
I can see this from the loading ui

```
Traceback (most recent call last):
File “/home/zuppif/Documents/text-generation-webui/server.py”, line 67, in load_model_wrapper
shared.model, shared.tokenizer = load_model(shared.model_name)
File “/home/zuppif/Documents/text-generation-webui/modules/models.py”, line 85, in load_model
model = LoaderClass.from_pretrained(Path(f"{shared.args.model_dir}/{model_name}"), low_cpu_mem_usage=True, torch_dtype=torch.bfloat16 if shared.args.bf16 else torch.float16, trust_remote_code=trust_remote_code)
File “/home/zuppif/Documents/text-generation-webui/.venv/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py”, line 471, in from_pretrained
return model_class.from_pretrained(
File “/home/zuppif/Documents/text-generation-webui/.venv/lib/python3.9/site-packages/transformers/modeling_utils.py”, line 2405, in from_pretrained
raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory models/mayaeary_pygmalion-6b_dev-4bit-128g.
```
