### ISSUE TITLE
[Issue]: running on colab, downloading other models besides preset not working

### ISSUE THREAD

**Issue by roseyyy2022ai** [oobabooga/text-generation-webui#1752]
### Describe the bug

I tried to run the webui on colab, everything works until the last step, where the download happens.
I tried it with Vicuna 13B and Pygmalion 7B (these weren't preprogrammed, so I added them...... and the notebook clearly didn't like that!
[Here's the notebook](https://colab.research.google.com/drive/16X8YI2u-AqzcFddhs6E_4CGv2-duMoF0?usp=share_link)

[UPDATE: [the official notebook](https://colab.research.google.com/github/oobabooga/AI-Notebooks/blob/main/Colab-TextGen-GPU.ipynb#scrollTo=hKuocueuXnm5) doesn't work either, none of the models load....

![image](https://user-images.githubusercontent.com/122406301/235835067-243e83c5-9534-4369-a398-01f6eaa0b0b3.png)

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

I added two new strings to the model set: Vicuna 13B and Pygmalion 7B
I launched (tried to) the webui
It gives an error like this:

Loading pyg7b-4bit-128g...
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py:259 │
│ in hf_raise_for_status                                                       │
│                                                                              │
│   256 │   </Tip>                                                             │
│   257 │   """                                                                │
│   258 │   try:                                                               │
│ ❱ 259 │   │   response.raise_for_status()                                    │
│   260 │   except HTTPError as e:                                             │
│   261 │   │   error_code = response.headers.get("X-Error-Code")              │
│   262                                                                        │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/requests/models.py:960 in            │
│ raise_for_status                                                             │
│                                                                              │
│   957 │   │   │   http_error_msg = u'%s Server Error: %s for url: %s' % (sel │
│   958 │   │                                                                  │
│   959 │   │   if http_error_msg:                                             │
│ ❱ 960 │   │   │   raise HTTPError(http_error_msg, response=self)             │
│   961 │                                                                      │
│   962 │   def close(self):                                                   │
│   963 │   │   """Releases the connection back to the pool. Once this method  │
╰──────────────────────────────────────────────────────────────────────────────╯
HTTPError: 401 Client Error: Unauthorized for url: 
https://huggingface.co/models/pyg7b-4bit-128g/resolve/main/config.json

The above exception was the direct cause of the following exception:

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py:409 in     │
│ cached_file                                                                  │
│                                                                              │
│    406 │   user_agent = http_user_agent(user_agent)                          │
│    407 │   try:                                                              │
│    408 │   │   # Load from URL or cache if already cached                    │
│ ❱  409 │   │   resolved_file = hf_hub_download(                              │
│    410 │   │   │   path_or_repo_id,                                          │
│    411 │   │   │   filename,                                                 │
│    412 │   │   │   subfolder=None if len(subfolder) == 0 else subfolder,     │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py │
│ :120 in _inner_fn                                                            │
│                                                                              │
│   117 │   │   if check_use_auth_token:                                       │
│   118 │   │   │   kwargs = smoothly_deprecate_use_auth_token(fn_name=fn.__na │
│   119 │   │                                                                  │
│ ❱ 120 │   │   return fn(*args, **kwargs)                                     │
│   121 │                                                                      │
│   122 │   return _inner_fn  # type: ignore                                   │
│   123                                                                        │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:119 │
│ 5 in hf_hub_download                                                         │
│                                                                              │
│   1192 │   if not local_files_only:                                          │
│   1193 │   │   try:                                                          │
│   1194 │   │   │   try:                                                      │
│ ❱ 1195 │   │   │   │   metadata = get_hf_file_metadata(                      │
│   1196 │   │   │   │   │   url=url,                                          │
│   1197 │   │   │   │   │   token=token,                                      │
│   1198 │   │   │   │   │   proxies=proxies,                                  │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py │
│ :120 in _inner_fn                                                            │
│                                                                              │
│   117 │   │   if check_use_auth_token:                                       │
│   118 │   │   │   kwargs = smoothly_deprecate_use_auth_token(fn_name=fn.__na │
│   119 │   │                                                                  │
│ ❱ 120 │   │   return fn(*args, **kwargs)                                     │
│   121 │                                                                      │
│   122 │   return _inner_fn  # type: ignore                                   │
│   123                                                                        │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:154 │
│ 1 in get_hf_file_metadata                                                    │
│                                                                              │
│   1538 │   │   proxies=proxies,                                              │
│   1539 │   │   timeout=timeout,                                              │
│   1540 │   )                                                                 │
│ ❱ 1541 │   hf_raise_for_status(r)                                            │
│   1542 │                                                                     │
│   1543 │   # Return                                                          │
│   1544 │   return HfFileMetadata(                                            │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py:291 │
│ in hf_raise_for_status                                                       │
│                                                                              │
│   288 │   │   │   │   " `repo_type`.\nIf you are trying to access a private  │
│   289 │   │   │   │   " make sure you are authenticated."                    │
│   290 │   │   │   )                                                          │
│ ❱ 291 │   │   │   raise RepositoryNotFoundError(message, response) from e    │
│   292 │   │                                                                  │
│   293 │   │   elif response.status_code == 400:                              │
│   294 │   │   │   message = (                                                │
╰──────────────────────────────────────────────────────────────────────────────╯
RepositoryNotFoundError: 401 Client Error. (Request ID: 
Root=1-6451e78c-160895574ea35692118cf3a1)

Repository Not Found for url: 
https://huggingface.co/models/pyg7b-4bit-128g/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are 
authenticated.
Invalid username or password.

During handling of the above exception, another exception occurred:

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /content/text-generation-webui/server.py:234 in <module>                     │
│                                                                              │
│   231 │   │   i = int(input())-1                                             │
│   232 │   │   print()                                                        │
│   233 │   shared.model_name = available_models[i]                            │
│ ❱ 234 shared.model, shared.tokenizer = load_model(shared.model_name)         │
│   235 if shared.args.lora:                                                   │
│   236 │   add_lora_to_model(shared.args.lora)                                │
│   237                                                                        │
│                                                                              │
│ /content/text-generation-webui/modules/models.py:51 in load_model            │
│                                                                              │
│    48 │   │   if any(size in shared.model_name.lower() for size in ('13b', ' │
│    49 │   │   │   model = AutoModelForCausalLM.from_pretrained(Path(f"models │
│    50 │   │   else:                                                          │
│ ❱  51 │   │   │   model = AutoModelForCausalLM.from_pretrained(Path(f"models │
│    52 │   │   │   if torch.has_mps:                                          │
│    53 │   │   │   │   device = torch.device('mps')                           │
│    54 │   │   │   │   model = model.to(device)                               │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factor │
│ y.py:445 in from_pretrained                                                  │
│                                                                              │
│   442 │   │   │   if kwargs_copy.get("torch_dtype", None) == "auto":         │
│   443 │   │   │   │   _ = kwargs_copy.pop("torch_dtype")                     │
│   444 │   │   │                                                              │
│ ❱ 445 │   │   │   config, kwargs = AutoConfig.from_pretrained(               │
│   446 │   │   │   │   pretrained_model_name_or_path,                         │
│   447 │   │   │   │   return_unused_kwargs=True,                             │
│   448 │   │   │   │   trust_remote_code=trust_remote_code,                   │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/transformers/models/auto/configurati │
│ on_auto.py:925 in from_pretrained                                            │
│                                                                              │
│   922 │   │   kwargs["_from_auto"] = True                                    │
│   923 │   │   kwargs["name_or_path"] = pretrained_model_name_or_path         │
│   924 │   │   trust_remote_code = kwargs.pop("trust_remote_code", False)     │
│ ❱ 925 │   │   config_dict, unused_kwargs = PretrainedConfig.get_config_dict( │
│   926 │   │   if "auto_map" in config_dict and "AutoConfig" in config_dict[" │
│   927 │   │   │   if not trust_remote_code:                                  │
│   928 │   │   │   │   raise ValueError(                                      │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py: │
│ 574 in get_config_dict                                                       │
│                                                                              │
│   571 │   │   """                                                            │
│   572 │   │   original_kwargs = copy.deepcopy(kwargs)                        │
│   573 │   │   # Get config dict associated with the base config file         │
│ ❱ 574 │   │   config_dict, kwargs = cls._get_config_dict(pretrained_model_na │
│   575 │   │   if "_commit_hash" in config_dict:                              │
│   576 │   │   │   original_kwargs["_commit_hash"] = config_dict["_commit_has │
│   577                                                                        │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py: │
│ 629 in _get_config_dict                                                      │
│                                                                              │
│   626 │   │   │                                                              │
│   627 │   │   │   try:                                                       │
│   628 │   │   │   │   # Load from local folder or from cache or download fro │
│ ❱ 629 │   │   │   │   resolved_config_file = cached_file(                    │
│   630 │   │   │   │   │   pretrained_model_name_or_path,                     │
│   631 │   │   │   │   │   configuration_file,                                │
│   632 │   │   │   │   │   cache_dir=cache_dir,                               │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py:424 in     │
│ cached_file                                                                  │
│                                                                              │
│    421 │   │   )                                                             │
│    422 │                                                                     │
│    423 │   except RepositoryNotFoundError:                                   │
│ ❱  424 │   │   raise EnvironmentError(                                       │
│    425 │   │   │   f"{path_or_repo_id} is not a local folder and is not a va │
│    426 │   │   │   "listed on 'https://huggingface.co/models'\nIf this is a  │
│    427 │   │   │   "pass a token having permission to this repo with `use_au │
╰──────────────────────────────────────────────────────────────────────────────╯
OSError: models/pyg7b-4bit-128g is not a local folder and is not a valid model 
identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to 
this repo with `use_auth_token` or log in with `huggingface-cli login` and pass 
`use_auth_token=True`.

### Logs

```shell
Loading pyg7b-4bit-128g...
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py:259 │
│ in hf_raise_for_status                                                       │
│                                                                              │
│   256 │   </Tip>                                                             │
│   257 │   """                                                                │
│   258 │   try:                                                               │
│ ❱ 259 │   │   response.raise_for_status()                                    │
│   260 │   except HTTPError as e:                                             │
│   261 │   │   error_code = response.headers.get("X-Error-Code")              │
│   262                                                                        │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/requests/models.py:960 in            │
│ raise_for_status                                                             │
│                                                                              │
│   957 │   │   │   http_error_msg = u'%s Server Error: %s for url: %s' % (sel │
│   958 │   │                                                                  │
│   959 │   │   if http_error_msg:                                             │
│ ❱ 960 │   │   │   raise HTTPError(http_error_msg, response=self)             │
│   961 │                                                                      │
│   962 │   def close(self):                                                   │
│   963 │   │   """Releases the connection back to the pool. Once this method  │
╰──────────────────────────────────────────────────────────────────────────────╯
HTTPError: 401 Client Error: Unauthorized for url: 
https://huggingface.co/models/pyg7b-4bit-128g/resolve/main/config.json

The above exception was the direct cause of the following exception:

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py:409 in     │
│ cached_file                                                                  │
│                                                                              │
│    406 │   user_agent = http_user_agent(user_agent)                          │
│    407 │   try:                                                              │
│    408 │   │   # Load from URL or cache if already cached                    │
│ ❱  409 │   │   resolved_file = hf_hub_download(                              │
│    410 │   │   │   path_or_repo_id,                                          │
│    411 │   │   │   filename,                                                 │
│    412 │   │   │   subfolder=None if len(subfolder) == 0 else subfolder,     │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py │
│ :120 in _inner_fn                                                            │
│                                                                              │
│   117 │   │   if check_use_auth_token:                                       │
│   118 │   │   │   kwargs = smoothly_deprecate_use_auth_token(fn_name=fn.__na │
│   119 │   │                                                                  │
│ ❱ 120 │   │   return fn(*args, **kwargs)                                     │
│   121 │                                                                      │
│   122 │   return _inner_fn  # type: ignore                                   │
│   123                                                                        │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:119 │
│ 5 in hf_hub_download                                                         │
│                                                                              │
│   1192 │   if not local_files_only:                                          │
│   1193 │   │   try:                                                          │
│   1194 │   │   │   try:                                                      │
│ ❱ 1195 │   │   │   │   metadata = get_hf_file_metadata(                      │
│   1196 │   │   │   │   │   url=url,                                          │
│   1197 │   │   │   │   │   token=token,                                      │
│   1198 │   │   │   │   │   proxies=proxies,                                  │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py │
│ :120 in _inner_fn                                                            │
│                                                                              │
│   117 │   │   if check_use_auth_token:                                       │
│   118 │   │   │   kwargs = smoothly_deprecate_use_auth_token(fn_name=fn.__na │
│   119 │   │                                                                  │
│ ❱ 120 │   │   return fn(*args, **kwargs)                                     │
│   121 │                                                                      │
│   122 │   return _inner_fn  # type: ignore                                   │
│   123                                                                        │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:154 │
│ 1 in get_hf_file_metadata                                                    │
│                                                                              │
│   1538 │   │   proxies=proxies,                                              │
│   1539 │   │   timeout=timeout,                                              │
│   1540 │   )                                                                 │
│ ❱ 1541 │   hf_raise_for_status(r)                                            │
│   1542 │                                                                     │
│   1543 │   # Return                                                          │
│   1544 │   return HfFileMetadata(                                            │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py:291 │
│ in hf_raise_for_status                                                       │
│                                                                              │
│   288 │   │   │   │   " `repo_type`.\nIf you are trying to access a private  │
│   289 │   │   │   │   " make sure you are authenticated."                    │
│   290 │   │   │   )                                                          │
│ ❱ 291 │   │   │   raise RepositoryNotFoundError(message, response) from e    │
│   292 │   │                                                                  │
│   293 │   │   elif response.status_code == 400:                              │
│   294 │   │   │   message = (                                                │
╰──────────────────────────────────────────────────────────────────────────────╯
RepositoryNotFoundError: 401 Client Error. (Request ID: 
Root=1-6451e78c-160895574ea35692118cf3a1)

Repository Not Found for url: 
https://huggingface.co/models/pyg7b-4bit-128g/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are 
authenticated.
Invalid username or password.

During handling of the above exception, another exception occurred:

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /content/text-generation-webui/server.py:234 in <module>                     │
│                                                                              │
│   231 │   │   i = int(input())-1                                             │
│   232 │   │   print()                                                        │
│   233 │   shared.model_name = available_models[i]                            │
│ ❱ 234 shared.model, shared.tokenizer = load_model(shared.model_name)         │
│   235 if shared.args.lora:                                                   │
│   236 │   add_lora_to_model(shared.args.lora)                                │
│   237                                                                        │
│                                                                              │
│ /content/text-generation-webui/modules/models.py:51 in load_model            │
│                                                                              │
│    48 │   │   if any(size in shared.model_name.lower() for size in ('13b', ' │
│    49 │   │   │   model = AutoModelForCausalLM.from_pretrained(Path(f"models │
│    50 │   │   else:                                                          │
│ ❱  51 │   │   │   model = AutoModelForCausalLM.from_pretrained(Path(f"models │
│    52 │   │   │   if torch.has_mps:                                          │
│    53 │   │   │   │   device = torch.device('mps')                           │
│    54 │   │   │   │   model = model.to(device)                               │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factor │
│ y.py:445 in from_pretrained                                                  │
│                                                                              │
│   442 │   │   │   if kwargs_copy.get("torch_dtype", None) == "auto":         │
│   443 │   │   │   │   _ = kwargs_copy.pop("torch_dtype")                     │
│   444 │   │   │                                                              │
│ ❱ 445 │   │   │   config, kwargs = AutoConfig.from_pretrained(               │
│   446 │   │   │   │   pretrained_model_name_or_path,                         │
│   447 │   │   │   │   return_unused_kwargs=True,                             │
│   448 │   │   │   │   trust_remote_code=trust_remote_code,                   │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/transformers/models/auto/configurati │
│ on_auto.py:925 in from_pretrained                                            │
│                                                                              │
│   922 │   │   kwargs["_from_auto"] = True                                    │
│   923 │   │   kwargs["name_or_path"] = pretrained_model_name_or_path         │
│   924 │   │   trust_remote_code = kwargs.pop("trust_remote_code", False)     │
│ ❱ 925 │   │   config_dict, unused_kwargs = PretrainedConfig.get_config_dict( │
│   926 │   │   if "auto_map" in config_dict and "AutoConfig" in config_dict[" │
│   927 │   │   │   if not trust_remote_code:                                  │
│   928 │   │   │   │   raise ValueError(                                      │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py: │
│ 574 in get_config_dict                                                       │
│                                                                              │
│   571 │   │   """                                                            │
│   572 │   │   original_kwargs = copy.deepcopy(kwargs)                        │
│   573 │   │   # Get config dict associated with the base config file         │
│ ❱ 574 │   │   config_dict, kwargs = cls._get_config_dict(pretrained_model_na │
│   575 │   │   if "_commit_hash" in config_dict:                              │
│   576 │   │   │   original_kwargs["_commit_hash"] = config_dict["_commit_has │
│   577                                                                        │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py: │
│ 629 in _get_config_dict                                                      │
│                                                                              │
│   626 │   │   │                                                              │
│   627 │   │   │   try:                                                       │
│   628 │   │   │   │   # Load from local folder or from cache or download fro │
│ ❱ 629 │   │   │   │   resolved_config_file = cached_file(                    │
│   630 │   │   │   │   │   pretrained_model_name_or_path,                     │
│   631 │   │   │   │   │   configuration_file,                                │
│   632 │   │   │   │   │   cache_dir=cache_dir,                               │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py:424 in     │
│ cached_file                                                                  │
│                                                                              │
│    421 │   │   )                                                             │
│    422 │                                                                     │
│    423 │   except RepositoryNotFoundError:                                   │
│ ❱  424 │   │   raise EnvironmentError(                                       │
│    425 │   │   │   f"{path_or_repo_id} is not a local folder and is not a va │
│    426 │   │   │   "listed on 'https://huggingface.co/models'\nIf this is a  │
│    427 │   │   │   "pass a token having permission to this repo with `use_au │
╰──────────────────────────────────────────────────────────────────────────────╯
OSError: models/pyg7b-4bit-128g is not a local folder and is not a valid model 
identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to 
this repo with `use_auth_token` or log in with `huggingface-cli login` and pass 
`use_auth_token=True`.
```

### System Info

```shell
Tesla T4, running remotely on Google Colab
```

**Comment by rklasen** [comment]
Same issue in the Docker version, all steps except the last work:

```
 ✔ Container text-generation-webui-text-generation-webui-1  Recreated                                                0.1s 
Attaching to text-generation-webui-text-generation-webui-1
text-generation-webui-text-generation-webui-1  | 
text-generation-webui-text-generation-webui-1  | ==========
text-generation-webui-text-generation-webui-1  | == CUDA ==
text-generation-webui-text-generation-webui-1  | ==========
text-generation-webui-text-generation-webui-1  | 
text-generation-webui-text-generation-webui-1  | CUDA Version 11.8.0
text-generation-webui-text-generation-webui-1  | 
text-generation-webui-text-generation-webui-1  | Container image Copyright (c) 2016-2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
text-generation-webui-text-generation-webui-1  | 
text-generation-webui-text-generation-webui-1  | This container image and its contents are governed by the NVIDIA Deep Learning Container License.
text-generation-webui-text-generation-webui-1  | By pulling and using the container, you accept the terms and conditions of this license:
text-generation-webui-text-generation-webui-1  | https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
text-generation-webui-text-generation-webui-1  | 
text-generation-webui-text-generation-webui-1  | A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.
text-generation-webui-text-generation-webui-1  | 
text-generation-webui-text-generation-webui-1  | INFO:generated new fontManager
text-generation-webui-text-generation-webui-1  | INFO:Gradio HTTP request redirected to localhost :)
text-generation-webui-text-generation-webui-1  | bin /app/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
text-generation-webui-text-generation-webui-1  | INFO:Loading llama-7b-4bit...
text-generation-webui-text-generation-webui-1  | Traceback (most recent call last):
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 259, in hf_raise_for_status
text-generation-webui-text-generation-webui-1  |     response.raise_for_status()
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
text-generation-webui-text-generation-webui-1  |     raise HTTPError(http_error_msg, response=self)
text-generation-webui-text-generation-webui-1  | requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/models/llama-7b-4bit/resolve/main/config.json
text-generation-webui-text-generation-webui-1  | 
text-generation-webui-text-generation-webui-1  | The above exception was the direct cause of the following exception:
text-generation-webui-text-generation-webui-1  | 
text-generation-webui-text-generation-webui-1  | Traceback (most recent call last):
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/transformers/utils/hub.py", line 409, in cached_file
text-generation-webui-text-generation-webui-1  |     resolved_file = hf_hub_download(
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
text-generation-webui-text-generation-webui-1  |     return fn(*args, **kwargs)
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1195, in hf_hub_download
text-generation-webui-text-generation-webui-1  |     metadata = get_hf_file_metadata(
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
text-generation-webui-text-generation-webui-1  |     return fn(*args, **kwargs)
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1541, in get_hf_file_metadata
text-generation-webui-text-generation-webui-1  |     hf_raise_for_status(r)
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 291, in hf_raise_for_status
text-generation-webui-text-generation-webui-1  |     raise RepositoryNotFoundError(message, response) from e
text-generation-webui-text-generation-webui-1  | huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-6458dd37-6cdae0474803d95e1928f718)
text-generation-webui-text-generation-webui-1  | 
text-generation-webui-text-generation-webui-1  | Repository Not Found for url: https://huggingface.co/models/llama-7b-4bit/resolve/main/config.json.
text-generation-webui-text-generation-webui-1  | Please make sure you specified the correct `repo_id` and `repo_type`.
text-generation-webui-text-generation-webui-1  | If you are trying to access a private or gated repo, make sure you are authenticated.
text-generation-webui-text-generation-webui-1  | Invalid username or password.
text-generation-webui-text-generation-webui-1  | 
text-generation-webui-text-generation-webui-1  | During handling of the above exception, another exception occurred:
text-generation-webui-text-generation-webui-1  | 
text-generation-webui-text-generation-webui-1  | Traceback (most recent call last):
text-generation-webui-text-generation-webui-1  |   File "/app/server.py", line 872, in <module>
text-generation-webui-text-generation-webui-1  |     shared.model, shared.tokenizer = load_model(shared.model_name)
text-generation-webui-text-generation-webui-1  |   File "/app/modules/models.py", line 74, in load_model
text-generation-webui-text-generation-webui-1  |     shared.model_type = find_model_type(model_name)
text-generation-webui-text-generation-webui-1  |   File "/app/modules/models.py", line 62, in find_model_type
text-generation-webui-text-generation-webui-1  |     config = AutoConfig.from_pretrained(Path(f'{shared.args.model_dir}/{model_name}'), trust_remote_code=shared.args.trust_remote_code)
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 916, in from_pretrained
text-generation-webui-text-generation-webui-1  |     config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 573, in get_config_dict
text-generation-webui-text-generation-webui-1  |     config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 628, in _get_config_dict
text-generation-webui-text-generation-webui-1  |     resolved_config_file = cached_file(
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/transformers/utils/hub.py", line 424, in cached_file
text-generation-webui-text-generation-webui-1  |     raise EnvironmentError(
text-generation-webui-text-generation-webui-1  | OSError: models/llama-7b-4bit is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
text-generation-webui-text-generation-webui-1  | If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.
text-generation-webui-text-generation-webui-1 exited with code 1
```
