### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '6GB'

### ISSUE THREAD

**Issue by Bennett-Fourr** [oobabooga/text-generation-webui#1774]
### Describe the bug

Error when opening any model 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

IDK

### Screenshot

![Screenshot 2023-05-03 190512](https://user-images.githubusercontent.com/94060774/236069458-f81c1b62-1e0b-4d97-b805-b00b8207da97.png)

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\Other_side\Desktop\AI_things\text-generation-webui\server.py", line 914, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\Other_side\Desktop\AI_things\text-generation-webui\modules\models.py", line 217, in load_model
    model = LoaderClass.from_pretrained(checkpoint, **params)
  File "C:\Users\Other_side\anaconda3\envs\textgen\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\Other_side\anaconda3\envs\textgen\lib\site-packages\transformers\modeling_utils.py", line 2722, in from_pretrained
    max_memory = get_balanced_memory(
  File "C:\Users\Other_side\anaconda3\envs\textgen\lib\site-packages\accelerate\utils\modeling.py", line 465, in get_balanced_memory
    max_memory = get_max_memory(max_memory)
  File "C:\Users\Other_side\anaconda3\envs\textgen\lib\site-packages\accelerate\utils\modeling.py", line 380, in get_max_memory
    max_memory[key] = convert_file_size_to_int(max_memory[key])
  File "C:\Users\Other_side\anaconda3\envs\textgen\lib\site-packages\accelerate\utils\modeling.py", line 59, in convert_file_size_to_int
    return int(size[:-3]) * (2**30)
ValueError: invalid literal for int() with base 10: '6GB'
```

### System Info

```shell
RTX 3060 TI
i711700
32 GB of ram
```

**Comment by LaaZa** [comment]
You need to set it like `6GiB`. Or just the number `6`.

**Comment by Bennett-Fourr** [comment]
Where do I do this?

**Comment by LaaZa** [comment]
I mean the --gpu-memory and --cpu-memory if you have them as launch parameters

**Comment by Bennett-Fourr** [comment]
Thank you
