### ISSUE TITLE
How do I install the suggested custom models?

### ISSUE THREAD

**Issue by ARandomUserFromGithub** [oobabooga/text-generation-webui#180]
I tried installing Galactica1.3B, it makes an error when loading it.
https://huggingface.co/facebook/galactica-1.3b/tree/main
I git cloned it with all the files that comes alongside with it.
Here is my error message:
`Loading galactica-1.3b...
Auto-assiging --gpu-memory 23 for your GPU to try to prevent out-of-memory errors.
You can manually set other values.
Traceback (most recent call last):
  File "A:\TextGenWebUI\text-generation-webui\server.py", line 188, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "A:\TextGenWebUI\text-generation-webui\modules\models.py", line 122, in load_model
    model = eval(command)
  File "<string>", line 1, in <module>
  File "A:\TextGenWebUI\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "A:\TextGenWebUI\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2273, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory models\galactica-1.3b.
Press any key to continue . . .`

b.t.w., is there a good model for multi-lingual translation like chatGPT do?

**Comment by oobabooga** [comment]
Try

```
python download.py facebook/galactica-1.3b
```

Your `models/galactica-1.3b` folder is either incomplete or the model files are inside another subfolder like `galactica-1.3b/galactica-1.3b`.

**Comment by ARandomUserFromGithub** [comment]
I'm not sure where the file download.py is available at. I did the first thing that seemed coherent and used download-model.py instead but it makes an error at line 15 so it mustn't be the right download.py.
