### ISSUE TITLE
ModuleNotFoundError: No module named 'google.protobuf'

### ISSUE THREAD

**Issue by CreeperNinjaYT** [oobabooga/text-generation-webui#1806]
### Describe the bug

Error "ModuleNotFoundError: No module named 'google.protobuf'" after running start_windows.bat from the one click installer after installation completed

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Running start_windows.bat from the one click installer after installation completed

### Screenshot

![image](https://user-images.githubusercontent.com/53459761/236395165-ff17aa0f-6557-473e-97d2-a1e99adeb5e8.png)

### Logs

```shell
INFO:Gradio HTTP request redirected to localhost :)
Traceback (most recent call last):
  File "D:\Documents\Oobgabooga\oobabooga_windows\installer_files\env\lib\site-packages\accelerate\tracking.py", line 42, in <module>
    from torch.utils import tensorboard
  File "D:\Documents\Oobgabooga\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\tensorboard\__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "D:\Documents\Oobgabooga\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\tensorboard\writer.py", line 9, in <module>
    from tensorboard.compat.proto.event_pb2 import SessionLog
  File "C:\Users\happy\AppData\Roaming\Python\Python310\site-packages\tensorboard\compat\proto\event_pb2.py", line 7, in <module>
    from google.protobuf.internal import enum_type_wrapper
ModuleNotFoundError: No module named 'google.protobuf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Documents\Oobgabooga\oobabooga_windows\text-generation-webui\server.py", line 45, in <module>
    from modules import chat, shared, training, ui
  File "D:\Documents\Oobgabooga\oobabooga_windows\text-generation-webui\modules\chat.py", line 17, in <module>
    from modules.text_generation import (encode, generate_reply,
  File "D:\Documents\Oobgabooga\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 17, in <module>
    from modules.models import clear_torch_cache, local_rank
  File "D:\Documents\Oobgabooga\oobabooga_windows\text-generation-webui\modules\models.py", line 13, in <module>
    from accelerate import infer_auto_device_map, init_empty_weights
  File "D:\Documents\Oobgabooga\oobabooga_windows\installer_files\env\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "D:\Documents\Oobgabooga\oobabooga_windows\installer_files\env\lib\site-packages\accelerate\accelerator.py", line 37, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "D:\Documents\Oobgabooga\oobabooga_windows\installer_files\env\lib\site-packages\accelerate\tracking.py", line 44, in <module>
    import tensorboardX as tensorboard
  File "C:\Users\happy\AppData\Roaming\Python\Python310\site-packages\tensorboardX\__init__.py", line 5, in <module>
    from .torchvis import TorchVis
  File "C:\Users\happy\AppData\Roaming\Python\Python310\site-packages\tensorboardX\torchvis.py", line 10, in <module>
    from .writer import SummaryWriter
  File "C:\Users\happy\AppData\Roaming\Python\Python310\site-packages\tensorboardX\writer.py", line 16, in <module>
    from .comet_utils import CometLogger
  File "C:\Users\happy\AppData\Roaming\Python\Python310\site-packages\tensorboardX\comet_utils.py", line 5, in <module>
    from google.protobuf.json_format import MessageToJson
ModuleNotFoundError: No module named 'google.protobuf'

Done!
Press any key to continue . . .
```

### System Info

```shell
Operating System: Windows 10
GPU Brand: Nvidia
GPU Model: GTX 1660 Ti, GTX 1080
```

**Comment by dannyp777** [comment]
I am getting a similar thing on Ubuntu Lunar.
Log:

`Traceback (most recent call last):
  File "/home/danny/Downloads/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/accelerate/tracking.py", line 42, in <module>
    from torch.utils import tensorboard
  File "/home/danny/Downloads/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/utils/tensorboard/__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/home/danny/Downloads/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py", line 9, in <module>
    from tensorboard.compat.proto.event_pb2 import SessionLog
  File "/home/danny/.local/lib/python3.10/site-packages/tensorboard/compat/proto/event_pb2.py", line 7, in <module>
    from google.protobuf.internal import enum_type_wrapper
ModuleNotFoundError: No module named 'google.protobuf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/danny/Downloads/oobabooga_linux/text-generation-webui/server.py", line 47, in <module>
    from modules import chat, shared, training, ui, utils
  File "/home/danny/Downloads/oobabooga_linux/text-generation-webui/modules/chat.py", line 17, in <module>
    from modules.text_generation import (generate_reply, get_encoded_length,
  File "/home/danny/Downloads/oobabooga_linux/text-generation-webui/modules/text_generation.py", line 17, in <module>
    from modules.models import clear_torch_cache, local_rank
  File "/home/danny/Downloads/oobabooga_linux/text-generation-webui/modules/models.py", line 13, in <module>
    from accelerate import infer_auto_device_map, init_empty_weights
  File "/home/danny/Downloads/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/home/danny/Downloads/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/accelerate/accelerator.py", line 39, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "/home/danny/Downloads/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/accelerate/tracking.py", line 44, in <module>
    import tensorboardX as tensorboard
ModuleNotFoundError: No module named 'tensorboardX'`

**Comment by dannyp777** [comment]
I 

> I am getting a similar thing on Ubuntu Lunar. Hardware: https://linux-hardware.org/?probe=f90de81324 Python/Conda Environment:
> 
> [conda-env.log](https://github.com/oobabooga/text-generation-webui/files/11473189/conda-env.log) [pip-freeze.log](https://github.com/oobabooga/text-generation-webui/files/11473190/pip-freeze.log)
> 
> Log:
> 
> ```
>   File "/home/danny/Downloads/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/accelerate/tracking.py", line 42, in <module>
>     from torch.utils import tensorboard
>   File "/home/danny/Downloads/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/utils/tensorboard/__init__.py", line 12, in <module>
>     from .writer import FileWriter, SummaryWriter  # noqa: F401
>   File "/home/danny/Downloads/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py", line 9, in <module>
>     from tensorboard.compat.proto.event_pb2 import SessionLog
>   File "/home/danny/.local/lib/python3.10/site-packages/tensorboard/compat/proto/event_pb2.py", line 7, in <module>
>     from google.protobuf.internal import enum_type_wrapper
> ModuleNotFoundError: No module named 'google.protobuf'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/danny/Downloads/oobabooga_linux/text-generation-webui/server.py", line 47, in <module>
>     from modules import chat, shared, training, ui, utils
>   File "/home/danny/Downloads/oobabooga_linux/text-generation-webui/modules/chat.py", line 17, in <module>
>     from modules.text_generation import (generate_reply, get_encoded_length,
>   File "/home/danny/Downloads/oobabooga_linux/text-generation-webui/modules/text_generation.py", line 17, in <module>
>     from modules.models import clear_torch_cache, local_rank
>   File "/home/danny/Downloads/oobabooga_linux/text-generation-webui/modules/models.py", line 13, in <module>
>     from accelerate import infer_auto_device_map, init_empty_weights
>   File "/home/danny/Downloads/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/accelerate/__init__.py", line 3, in <module>
>     from .accelerator import Accelerator
>   File "/home/danny/Downloads/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/accelerate/accelerator.py", line 39, in <module>
>     from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
>   File "/home/danny/Downloads/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/accelerate/tracking.py", line 44, in <module>
>     import tensorboardX as tensorboard
> ModuleNotFoundError: No module named 'tensorboardX'
> ```

I resolved this by using the cmd_linux.sh script to enter the conda env and issuing `conda install tensorbaordx` after which in proceeded to download and install libprotobuf-3.20.3, protobuf-3.20.3 and tensorboardx-2.2. After rerunning the start_linux.sh script the prior errors are resolved but I am getting some other errors which I'm still looking at. I will open a different issue for this if needed.

Maybe tensorboardx needs to be added to requirements.txt?

**Comment by novadiem** [comment]
for those on windows encountering this:
`pip install tensorboardx`

Thanks to @dannyp777
