### ISSUE TITLE
Recommended RWKV test model on generation: UnboundLocalError: local variable 'output' referenced before assignment

### ISSUE THREAD

**Issue by dblacknc** [oobabooga/text-generation-webui#1812]
### Describe the bug

I exactly followed the instructions here: https://github.com/oobabooga/text-generation-webui/blob/main/docs/RWKV-model.md, to try out RWKV, and specifically have RWKV-4b-Pile-3B-20230228-7963.pth

The model appears to load OK.  Tried in chat and instruct mode (None template) both, I get a crash maybe 10 seconds after generation of a reply is requested:  UnboundLocalError: local variable 'output' referenced before assignment

FYI I see nothing loaded on my second GPU (cuda:1) and don't know if it should.  No bother though as it's only using about 1/3 of available VRAM anyway on cuda:0.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load the above model, type a prompt such as seen in the log, and hit enter.

### Logs

```shell
python server.py --chat --model-dir /z820/ds2/models --verbose --listen --listen-port 80 --model-dir /z820/ds2/models --model RWKV-4b-Pile-3B-20230228-7963.pth
INFO:Gradio HTTP request redirected to localhost :)
INFO:Loading RWKV-4b-Pile-3B-20230228-7963.pth...
RWKV_JIT_ON 1 RWKV_CUDA_ON 0 RESCALE_LAYER 6

Loading /z820/ds2/models/RWKV-4b-Pile-3B-20230228-7963.pth ...
Strategy: (total 32+1=33 layers)
* cuda [float16, float16], store 33 layers
0-cuda-float16-float16 1-cuda-float16-float16 2-cuda-float16-float16 3-cuda-float16-float16 4-cuda-float16-float16 5-cuda-float16-float16 6-cuda-float16-float16 7-cuda-float16-float16 8-cuda-float16-float16 9-cuda-float16-float16 10-cuda-float16-float16 11-cuda-float16-float16 12-cuda-float16-float16 13-cuda-float16-float16 14-cuda-float16-float16 15-cuda-float16-float16 16-cuda-float16-float16 17-cuda-float16-float16 18-cuda-float16-float16 19-cuda-float16-float16 20-cuda-float16-float16 21-cuda-float16-float16 22-cuda-float16-float16 23-cuda-float16-float16 24-cuda-float16-float16 25-cuda-float16-float16 26-cuda-float16-float16 27-cuda-float16-float16 28-cuda-float16-float16 29-cuda-float16-float16 30-cuda-float16-float16 31-cuda-float16-float16 32-cuda-float16-float16 
emb.weight                        f16      cpu  50277  2560 
blocks.0.ln1.weight               f16   cuda:0   2560       
blocks.0.ln1.bias                 f16   cuda:0   2560       
blocks.0.ln2.weight               f16   cuda:0   2560       
blocks.0.ln2.bias                 f16   cuda:0   2560       
blocks.0.att.time_decay           f32   cuda:0   2560       
blocks.0.att.time_first           f32   cuda:0   2560       
blocks.0.att.time_mix_k           f16   cuda:0   2560       
blocks.0.att.time_mix_v           f16   cuda:0   2560       
blocks.0.att.time_mix_r           f16   cuda:0   2560       
blocks.0.att.time_mix_qq          f16   cuda:0   2560       
blocks.0.att.time_mix_kk          f16   cuda:0   2560       
blocks.0.att.time_mix_vv          f16   cuda:0   2560       
blocks.0.att.att_mask             f16   cuda:0   1024  1024 
blocks.0.att.key.weight           f16   cuda:0   2560  2560 
blocks.0.att.value.weight         f16   cuda:0   2560  2560 
blocks.0.att.receptance.weight    f16   cuda:0   2560  2560 
blocks.0.att.output.weight        f16   cuda:0   2560  2560 
blocks.0.att.qq.weight            f16   cuda:0    160  2560 
blocks.0.att.kk.weight            f16   cuda:0    160  2560 
blocks.0.att.vv.weight            f16   cuda:0    160  2560 
blocks.0.att.oo.weight            f16   cuda:0   2560   160 
blocks.0.ffn.time_mix_k           f16   cuda:0   2560       
blocks.0.ffn.time_mix_r           f16   cuda:0   2560       
blocks.0.ffn.key.weight           f16   cuda:0   2560 10240 
blocks.0.ffn.receptance.weight    f16   cuda:0   2560  2560 
blocks.0.ffn.value.weight         f16   cuda:0  10240  2560 
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
blocks.31.ln1.weight              f16   cuda:0   2560       
blocks.31.ln1.bias                f16   cuda:0   2560       
blocks.31.ln2.weight              f16   cuda:0   2560       
blocks.31.ln2.bias                f16   cuda:0   2560       
blocks.31.att.time_decay          f32   cuda:0   2560       
blocks.31.att.time_first          f32   cuda:0   2560       
blocks.31.att.time_mix_k          f16   cuda:0   2560       
blocks.31.att.time_mix_v          f16   cuda:0   2560       
blocks.31.att.time_mix_r          f16   cuda:0   2560       
blocks.31.att.time_mix_qq         f16   cuda:0   2560       
blocks.31.att.time_mix_kk         f16   cuda:0   2560       
blocks.31.att.time_mix_vv         f16   cuda:0   2560       
blocks.31.att.att_mask            f16   cuda:0   1024  1024 
blocks.31.att.key.weight          f16   cuda:0   2560  2560 
blocks.31.att.value.weight        f16   cuda:0   2560  2560 
blocks.31.att.receptance.weight   f16   cuda:0   2560  2560 
blocks.31.att.output.weight       f16   cuda:0   2560  2560 
blocks.31.att.qq.weight           f16   cuda:0    160  2560 
blocks.31.att.kk.weight           f16   cuda:0    160  2560 
blocks.31.att.vv.weight           f16   cuda:0    160  2560 
blocks.31.att.oo.weight           f16   cuda:0   2560   160 
blocks.31.ffn.time_mix_k          f16   cuda:0   2560       
blocks.31.ffn.time_mix_r          f16   cuda:0   2560       
blocks.31.ffn.key.weight          f16   cuda:0   2560 10240 
blocks.31.ffn.receptance.weight   f16   cuda:0   2560  2560 
blocks.31.ffn.value.weight        f16   cuda:0  10240  2560 
ln_out.weight                     f16   cuda:0   2560       
ln_out.bias                       f16   cuda:0   2560       
head.weight                       f16   cuda:0   2560 50277 
INFO:Loading the extension "gallery"...
Running on local URL:  http://0.0.0.0:80

To create a public link, set `share=True` in `launch()`.


This is a conversation with your Assistant. The Assistant is very helpful and is eager to chat with you and answer your questions.
You: What's the airspeed velocity of an unladen swallow?
Assistant:
--------------------

Traceback (most recent call last):
  File "/root/text-generation-webui/modules/callbacks.py", line 73, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/root/text-generation-webui/modules/RWKV.py", line 48, in generate
    return self.pipeline.generate(context, token_count=token_count, args=args, callback=callback)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/rwkv/utils.py", line 100, in generate
    token = self.sample_logits(out, temperature=args.temperature, top_p=args.top_p, top_k=args.top_k)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/rwkv/utils.py", line 78, in sample_logits
    out = torch.multinomial(probs, num_samples=1)[0]
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
Traceback (most recent call last):
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/utils.py", line 490, in async_iteration
    return next(iterator)
  File "/root/text-generation-webui/modules/chat.py", line 248, in cai_chatbot_wrapper
    for history in chatbot_wrapper(text, state):
  File "/root/text-generation-webui/modules/chat.py", line 182, in chatbot_wrapper
    for reply in generate_reply(f"{prompt}{' ' if len(cumulative_reply) > 0 else ''}{cumulative_reply}", state, eos_token=eos_token, stopping_strings=stopping_strings):
  File "/root/text-generation-webui/modules/text_generation.py", line 225, in generate_reply
    new_tokens = len(encode(output)[0]) - original_tokens
UnboundLocalError: local variable 'output' referenced before assignment

ls -l /z820/ds2/models/RWKV-4b-Pile-3B-20230228-7963.pth /z820/ds2/models/20B_tokenizer.json 
-rw-r--r-- 1 root root    2467981 May  5 13:51 /z820/ds2/models/20B_tokenizer.json
-rw-r--r-- 1 root root 6141846662 Mar  1 09:40 /z820/ds2/models/RWKV-4b-Pile-3B-20230228-7963.pth
```

### System Info

```shell
Ubuntu 22.04
RTX 3060 x 2
git pull as of today
```

**Comment by dblacknc** [comment]
I see I grabbed the latest "4b" model and the model card warns against this.  Trying instead these and will update this issue after doing so:

RWKV-4-Pile-3B-20221008-8023.pth
RWKV-4-Pile-3B-Instruct-test2-20230209.pth

**Comment by dblacknc** [comment]
The Raven model - RWKV-4-Raven-3B-v8-Eng-20230408-ctx4096
...is working well too.  I hope it can span two GPUs - going to try a larger model.  Closing this as it's not a bug... note to self, stay away from the 4a/4b models for now.

Nice performance on Raven!
Output generated in 15.53 seconds (**12.87 tokens/s**, 200 tokens, context 63, seed 1928606931)
