### ISSUE TITLE
 CUDA out of memory

### ISSUE THREAD

**Issue by lolgame123445** [oobabooga/text-generation-webui#1816]
### Describe the bug

I try to start my cmd thingy but it say it doesnt have enough memory and that it tried to allocate some bytes. Am not sure what the reserved GiB means but am guessing its how much i still need to have free space of memory for it to work. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. download 1 step downloader
2. download everything necessary and put it in its place
3. start to load it 

I i've tried to download the oobabooga-windows many times cuz the other times I didn't fully understand what to do so I don't know if it affected the starting process in some way.

### Screenshot

![image](https://user-images.githubusercontent.com/62266366/236527501-21c75dee-2fd5-4975-b7b0-1417c3c2ae4a.png)

### Logs

```shell
INFO:Gradio HTTP request redirected to localhost :)
bin C:\Users\Owner\Desktop\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117_nocublaslt.dll
INFO:Loading gpt4-x-alpaca-13b-native-4bit-128g...
INFO:Found the following quantized model: models\gpt4-x-alpaca-13b-native-4bit-128g\gpt-x-alpaca-13b-native-4bit-128g-cuda.pt
Traceback (most recent call last):
  File "C:\Users\Owner\Desktop\oobabooga_windows\text-generation-webui\server.py", line 915, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\Owner\Desktop\oobabooga_windows\text-generation-webui\modules\models.py", line 159, in load_model
    model = load_quantized(model_name)
  File "C:\Users\Owner\Desktop\oobabooga_windows\text-generation-webui\modules\GPTQ_loader.py", line 200, in load_quantized
    model = model.to(torch.device('cuda:0'))
  File "C:\Users\Owner\Desktop\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 1896, in to
    return super().to(*args, **kwargs)
  File "C:\Users\Owner\Desktop\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "C:\Users\Owner\Desktop\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\Owner\Desktop\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\Owner\Desktop\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "C:\Users\Owner\Desktop\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 844, in _apply
    self._buffers[key] = fn(buf)
  File "C:\Users\Owner\Desktop\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 34.00 MiB (GPU 0; 3.00 GiB total capacity; 2.53 GiB already allocated; 0 bytes free; 2.62 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Done!
Press any key to continue . . .
```

### System Info

```shell
Windows 10, gpu NVIDIA GEFORCE GTX 1050, 24 GB ram,
```

**Comment by jepjoo** [comment]
Looks like your GPU doesn't have enough VRAM. It has 4GB and you need 10GB VRAM to run that model.
