### ISSUE TITLE
cannot change mode in deploy on docker 

### ISSUE THREAD

**Issue by biaggii** [oobabooga/text-generation-webui#1821]
### Describe the bug

OSError: Port 8000 is in use. If a gradio.Blocks is running on the port, you can close() it or gradio.close_all().
exited with code 1

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

on me change chat to default cannot restart , docker stop

### Logs

```shell
text-generation-webui-text-generation-webui-1  | INFO:Profile picture saved to "cache/pfp_me.png"
text-generation-webui-text-generation-webui-1  | Closing server running on port: 8000
text-generation-webui-text-generation-webui-1  | INFO:Loading the extension "gallery"...
text-generation-webui-text-generation-webui-1  | Traceback (most recent call last):
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/gradio/networking.py", line 119, in start_server
text-generation-webui-text-generation-webui-1  |     s.bind((LOCALHOST_NAME, server_port))
text-generation-webui-text-generation-webui-1  | OSError: [Errno 98] Address already in use
text-generation-webui-text-generation-webui-1  |
text-generation-webui-text-generation-webui-1  | During handling of the above exception, another exception occurred:
text-generation-webui-text-generation-webui-1  |
text-generation-webui-text-generation-webui-1  | Traceback (most recent call last):
text-generation-webui-text-generation-webui-1  |   File "/app/server.py", line 934, in <module>
text-generation-webui-text-generation-webui-1  |     create_interface()
text-generation-webui-text-generation-webui-1  |   File "/app/server.py", line 851, in create_interface
text-generation-webui-text-generation-webui-1  |     shared.gradio['interface'].launch(prevent_thread_lock=True, share=shared.args.share, server_name=shared.args.listen_host or '0.0.0.0', server_port=shared.args.listen_port, inbrowser=shared.args.auto_launch, auth=auth)
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1596, in launch
text-generation-webui-text-generation-webui-1  |     server_name, server_port, local_url, app, server = networking.start_server(
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/gradio/networking.py", line 122, in start_server
text-generation-webui-text-generation-webui-1  |     raise OSError(
text-generation-webui-text-generation-webui-1  | OSError: Port 8000 is in use. If a gradio.Blocks is running on the port, you can close() it or gradio.close_all().
```

### System Info

```shell
operating system: windows 10, docker desktop with wsl2
GPU model: rtx 3090 x 2
```

**Comment by jamesbiederbeck** [comment]
I've been able to reproduce this. Sometimes I can get it to work if I do a docker restart shortly after. I suspect we just need to change something on the file system then restart container.
