### ISSUE TITLE
Can't load mosaicml/mpt-7b-instruct model

### ISSUE THREAD

**Issue by almagest21** [oobabooga/text-generation-webui#1828]
Hi, thank you for this great ui.
Today I tried to use mosaicml/mpt-7b-instruct model. downloading from webui is successufully finished but it can't be loaded. Here is error message:
> Traceback (most recent call last):
>   File "D:\dl\webui\text-generation-webui\server.py", line 917, in <module>
>     shared.model, shared.tokenizer = load_model(shared.model_name)
>   File "D:\dl\webui\text-generation-webui\modules\models.py", line 74, in load_model
>     shared.model_type = find_model_type(model_name)
>   File "D:\dl\webui\text-generation-webui\modules\models.py", line 62, in find_model_type
>     config = AutoConfig.from_pretrained(Path(f'{shared.args.model_dir}/{model_name}'), trust_remote_code=shared.args.trust_remote_code)
>   File "D:\dl\webui\installer_files\env\lib\site-packages\transformers\models\auto\configuration_auto.py", line 919, in from_pretrained
>     raise ValueError(
> ValueError: Loading models\mosaicml_mpt-7b-instruct requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.

Could you please give me the file and location to add this `trust_remote_code=True` option?

**Comment by oobabooga** [comment]
Try --trust-remote-code

**Comment by almagest21** [comment]
@oobabooga Thanks. Could you teach me where to add this argument on start_windows.bat or other file?

**Comment by jepjoo** [comment]
INSTRUCTIONS.TXT tells you how to do this:

# Adding flags like --chat, --notebook, etc

Edit the "webui.py" script using a text editor and add the desired flags
to the line that says

run_cmd("python server.py --chat --model-menu")

For instance, to add the --notebook flag, change it to

run_cmd("python server.py --notebook --model-menu")

**Comment by hwamil** [comment]
There's no such flag named `--trust-remote-code`

**Comment by SrVill** [comment]
> There's no such flag named `--trust-remote-code`
> 
> edit: I was wrong. But even when enabled I get the same message still.

Same problem. After setting the flag (which can be enabled directly from the interface), an error will appear related to the lack of support for this model. Asked a question here: https://github.com/oobabooga/text-generation-webui/issues/1856

**Comment by SharkWipf** [comment]
Works fine for me (Fedora), just needed to `pip install einops` and launch with `--trust-remote-code`.

**Comment by Slug-Cat** [comment]
I've tried launching with --trust-remote-code and pip install einops and it still gives the same error:
Traceback (most recent call last):
File “E:\oobabooga\text-generation-webui\[server.py](http://server.py/)”, line 103, in load_model_wrapper
shared.model, shared.tokenizer = load_model(shared.model_name)
File “E:\oobabooga\text-generation-webui\modules\[models.py](http://models.py/)”, line 207, in load_model
config = AutoConfig.from_pretrained(checkpoint)
File “E:\oobabooga\installer_files\env\lib\site-packages\transformers\models\auto\configuration_auto.py”, line 919, in from_pretrained
raise ValueError(
ValueError: Loading models\mosaicml_mpt-7b-storywriter requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option trust_remote_code=True to remove this error.

**Comment by SharkWipf** [comment]
You might need to manually download/clone (make sure you have git-lfs enabled if you clone) the huggingface model repo to the models folder instead of auto-downloading it, that's what I did.

**Comment by NickWithBotronics** [comment]
I've been running into the same issues. I tried the --trust_remote_code and pip install einops, and i get the same error as shown at the top of this thread.

**Comment by oobabooga** [comment]
Try updating the web ui, if trust-remote-code doesn't work then you are probably using an older version of the UI

**Comment by almagest21** [comment]
Sorry to confusing you, but when I wrote the --trust-remote-code argument on webui.py as jepjoo taught me, it was successfully proceeded.
But I got another error about the missing einops module. Therefore, I installed it by adding "call pip install einops" before "call python webui.py" line. 
And tried again and got the following error:

> C:\Users\alma/.cache\huggingface\modules\transformers_modules\mosaicml_mpt-7b-instruct\attention.py:148: UserWarning: Using `attn_impl: torch`. If your model does not use `alibi` or `prefix_lm` we recommend using `attn_impl: flash` otherwise we recommend using `attn_impl: triton`.
>   warnings.warn('Using `attn_impl: torch`. If your model does not use `alibi` or ' + '`prefix_lm` we recommend using `attn_impl: flash` otherwise ' + 'we recommend using `attn_impl: triton`.')
> Traceback (most recent call last):
>   File "D:\dl\webui\text-generation-webui\server.py", line 872, in <module>
>     shared.model, shared.tokenizer = load_model(shared.model_name)
>   File "D:\dl\webui\text-generation-webui\modules\models.py", line 219, in load_model
>     model = LoaderClass.from_pretrained(checkpoint, **params)
>   File "D:\dl\webui\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 466, in from_pretrained
>     return model_class.from_pretrained(
>   File "D:\dl\webui\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2703, in from_pretrained
>     raise ValueError(f"{model.__class__.__name__} does not support `device_map='{device_map}'` yet.")
> ValueError: MPTForCausalLM does not support `device_map='auto'` yet.

If anyone knows of this problem, I would appreciate any help.

**Comment by Slug-Cat** [comment]
> 

I get this error when trying to run the model with --trust-remote-code at 16bit precision, and get the other error when trying to run the model at 8bit precision. I'm on the latest version of the UI on windows and have confirmed that the model folder matches the huggingface page of the model.

**Comment by CarlKenner** [comment]
Once those errors are solved, you will also need instruction-following characters and prompts for gpt-instruct and gpt-chat, and for them to be automatically recognised, which I added to my pull request #1596.

In the meantime, for the `mpt-7b-instruct` model, you should scroll down in the chat window and set it to `instruct` then choose Alpaca from the dropdown menu.

But for the `mpt-7b-chat` model, it uses a variant of ChatML, so it won't work with the Alpaca option.

**Comment by Lesani** [comment]
WHERE is that webui.py? I can't find it. I got the remote code flag in the bat file, I can see trust_remote_code enabled in the "interface mode" tab, but still get the ", then set the option trust_remote_code=True to remove this error." error.
I cannot find a "webui.py" file anywhere in the repo ?!?

**Comment by jepjoo** [comment]
> WHERE is that webui.py? I can't find it. I got the remote code flag in the bat file, I can see trust_remote_code enabled in the "interface mode" tab, but still get the ", then set the option trust_remote_code=True to remove this error." error. I cannot find a "webui.py" file anywhere in the repo ?!?

It's included in the 1-click installers.

https://github.com/oobabooga/text-generation-webui/releases/tag/installers

**Comment by camenduru** [comment]
https://github.com/oobabooga/text-generation-webui/pull/1891

**Comment by Anonym0us33** [comment]
> Try --trust-remote-code

Hi, I just did a `git pull` but when using this code I get 
`server.py: error: unrecognized arguments: --trust-remote-code`

**Comment by DocShotgun** [comment]
It looks like people have managed to get the full versions of the model running, but has anyone had any luck with the 4bit quantized version?
https://huggingface.co/OccamRazor/mpt-7b-storywriter-4bit-128g

It looks like occam made some edits to GPTQ to support mpt in his repo:
https://github.com/0cc4m/GPTQ-for-LLaMa

Not a coder myself, but wondering if it would be possible to adapt those changes to a webui-compatible version of GPTQ-for-LLaMa?

**Comment by SrVill** [comment]
> It looks like people have managed to get the full versions of the model running...

How did they do it? So far I'm stuck on a bug:

Traceback (most recent call last):
File “E:\oobabooga_windows\text-generation-webui\[server.py](http://server.py/)”, line 60, in load_model_wrapper
shared.model, shared.tokenizer = load_model(shared.model_name)
File “E:\oobabooga_windows\text-generation-webui\modules\[models.py](http://models.py/)”, line 219, in load_model
model = LoaderClass.from_pretrained(checkpoint, **params)
File “E:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py”, line 466, in from_pretrained
return model_class.from_pretrained(
File “E:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py”, line 2703, in from_pretrained
raise ValueError(f"{model.class.name} does not support device_map='{device_map}' yet.")
ValueError: MPTForCausalLM does not support device_map='auto' yet.

**Comment by Lesani** [comment]
Uncheck the ‚auto devices‘ checkbox in the model areaSent by my iPhoneOn 08.05.2023, at 12:51, SrVill ***@***.***> wrote:﻿

It looks like people have managed to get the full versions of the model running...

How did they do it? So far I'm stuck on a bug:
Traceback (most recent call last):
File “E:\oobabooga_windows\text-generation-webui[server.py](http://server.py/)”, line 60, in load_model_wrapper
shared.model, shared.tokenizer = load_model(shared.model_name)
File “E:\oobabooga_windows\text-generation-webui\modules[models.py](http://models.py/)”, line 219, in load_model
model = LoaderClass.from_pretrained(checkpoint, **params)
File “E:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py”, line 466, in from_pretrained
return model_class.from_pretrained(
File “E:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py”, line 2703, in from_pretrained
raise ValueError(f"{model.class.name} does not support device_map='{device_map}' yet.")
ValueError: MPTForCausalLM does not support device_map='auto' yet.

**Comment by ajallooeian** [comment]
I think I found the issue:

This line should be copied before if/else:
https://github.com/oobabooga/text-generation-webui/blob/main/modules/models.py#LL172C43-L172C60

**Comment by YoussefMP** [comment]
I added the flag "--trust-remote-code" under webui.py l.164, it fixed it for me.

**Comment by anuragupadhyaya** [comment]
```
base_model = AutoModelForCausalLM.from_pretrained("mosaicml/mpt-7b-instruct",
                                                        offload_folder="model/",
                                                        trust_remote_code=True,
                                                        device_map="auto")
```

**Comment by PrimalOutshoot** [comment]
- I have einops installed, 
- I have --trust-remote-code
- I have updated my Oobabooga webui 

And still have not managed to get any version of mpt running.

Error Messages:
1. call python server.py --notebook --api --model occamrazor_mpt-7b-storywriter-4bit-128g --trust-remote-code --wbits 4 --groupsize 128 --model_type mpt  => ERROR:Unknown pre-quantized model type specified. Only 'llama', 'opt' and 'gptj' are supported
2. call python server.py --notebook --api --model occamrazor_mpt-7b-storywriter-4bit-128g --trust-remote-code --wbits 4 --groupsize 128 => INFO:Loading occamrazor_mpt-7b-storywriter-4bit-128g...
ERROR:The model could not be loaded because its type could not be inferred from its name.
ERROR:Please specify the type manually using the --model_type argument.

And this is the same process for everything. In addition I have to create a separate .bat file because there is no dropdown menu in the webui to select these options.

I hear as someone mentioned: occam made offers mpt support: https://github.com/0cc4m/GPTQ-for-LLaMa
But I have no idea how to get that to work in Oobabooga. 

And while others have gotten mpt to run I am not sure how they are doing that since none of their instructions are detailed, and it just doesn't seem to work for me. 

The main page says oobabooga/text-generation-webui supports MPT here:
Instruct mode compatible with various formats, including Alpaca, Vicuna, Open Assistant, Dolly, Koala, ChatGLM, MOSS, RWKV-Raven, Galactica, StableLM, WizardLM, Baize, Ziya, Chinese-Vicuna, MPT, INCITE, Wizard Mega, KoAlpaca, Vigogne, Bactrian, h2o, and OpenBuddy

But I have not had any luck with it out of the box so not sure how it supports MPT out of the box if it is causing this much of a headache to run. 

Having Oobabooga support MPT out of the box, with trust-remote-code selectable within the WebUI without a custom .bat file, and without tweaking or playing around/breaking code would be ideal. Also having proper versioning would be nice, to know if this is Oobabooga/text-generation 1.4 vs. 2.8 and be able to compare the changes between them, without overriding and breaking everything that used to work -- but then doesn't.

**Comment by Rilwan-Adewoyin** [comment]
Another solution to this problem is just to change the default value for _no_split_modules during initialization. This can be done by changing the _no_split_modules to an empty list instead of None in the PreTrainedModel Class in the transformers.modelling_utils.py file.

```
class PreTrainedModel(nn.Module, ModuleUtilsMixin, GenerationMixin, PushToHubMixin):
...
    config_class = None
    base_model_prefix = ""
    main_input_name = "input_ids"
    _auto_class = None
    # Patch here
    # _no_split_modules = None
    _no_split_modules = []
    _keep_in_fp32_modules = None
```

**Comment by franciscolemos** [comment]
> --trust-remote-code

![image](https://github.com/oobabooga/text-generation-webui/assets/28149891/ad3f6fd1-417f-4a33-af68-42d218f80959)

**Comment by ChrisNonyminus** [comment]
> > --trust-remote-code
> 
> ![image](https://user-images.githubusercontent.com/28149891/243125831-ad3f6fd1-417f-4a33-af68-42d218f80959.png)

Not working.
![image](https://github.com/oobabooga/text-generation-webui/assets/50080567/7090a154-e49a-4348-b104-a24e88d89179)

**Comment by eizoxx** [comment]
I can't start the web ui for some reason. I always get in the cmd_windows.bat this error:

(D:\AI\LLM\oobabooga_windows\installer_files\env) D:\AI\LLM\oobabooga_windows\text-generation-webui>python server.py --model mosaicml_mpt-7b-storywriter --listen --trust-remote-code --bf16
2023-08-23 00:24:58 WARNING:trust_remote_code is enabled. This is dangerous.
Traceback (most recent call last):
  File "D:\AI\LLM\oobabooga_windows\text-generation-webui\server.py", line 28, in <module>
    from modules import (
  File "D:\AI\LLM\oobabooga_windows\text-generation-webui\modules\chat.py", line 17, in <module>
    from modules.text_generation import (
  File "D:\AI\LLM\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 23, in <module>
    from modules.models import clear_torch_cache, local_rank
  File "D:\AI\LLM\oobabooga_windows\text-generation-webui\modules\models.py", line 148
    +    config = `transformers.AutoConfig.from_pretrained(`
                                                          ^
IndentationError: unindent does not match any outer indentation level

I followed every step from:
https://youtu.be/EvM0A6d_KSA
https://youtu.be/QVVb6Md6huA

But I can't get it to run.
Can anyone help?

**Comment by Eddcapone** [comment]
This is still relevant. Please reopen.

**Comment by EvgeneKuklin** [comment]
Use CMD_FLAGS.TXT
