### ISSUE TITLE
Docker builds successfully but does not work 

### ISSUE THREAD

**Issue by CRCODE22** [oobabooga/text-generation-webui#1833]
### Describe the bug here is the first part check the attached .txt file for the full error log.

[Dockernotwork.txt](https://github.com/oobabooga/text-generation-webui/files/11411536/Dockernotwork.txt)

text-generation-webui-text-generation-webui-1  | Traceback (most recent call last):
text-generation-webui-text-generation-webui-1  |   File "/app/server.py", line 885, in <module>
text-generation-webui-text-generation-webui-1  |     create_interface()
text-generation-webui-text-generation-webui-1  |   File "/app/server.py", line 472, in create_interface
text-generation-webui-text-generation-webui-1  |     with gr.Blocks(css=ui.css if not shared.is_chat() else ui.css + ui.chat_css, analytics_enabled=False, title=title, theme=ui.theme) as shared.gradio['interface']:
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1285, in __exit__
text-generation-webui-text-generation-webui-1  |     self.config = self.get_config_file()
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1261, in get_config_file
text-generation-webui-text-generation-webui-1  |     "input": list(block.input_api_info()),  # type: ignore
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/gradio_client/serializing.py", line 40, in input_api_info
text-generation-webui-text-generation-webui-1  |     return (api_info["serialized_input"][0], api_info["serialized_input"][1])
text-generation-webui-text-generation-webui-1  | KeyError: 'serialized_input'
text-generation-webui-text-generation-webui-1 exited with code 1

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Follow the docker install instructions on the github.

### Logs

```shell
[Dockernotwork.txt](https://github.com/oobabooga/text-generation-webui/files/11411297/Dockernotwork.txt)
```

### System Info

```shell
Windows 11
Nvidia Geforce 3060 12 GB Gaming OC 2.0
Processor: AMD Ryzen 7 3700X 8-Core Processor (16 CPUs), ~3.6GHz
Memory: 57344MB RAM
Available OS Memory: 57250MB RAM
Docker Desktop 4.19.0 (106363) is currently the newest version available.
```

**Comment by CRCODE22** [comment]
I solved the model load problem but now there is another problem

[456456345354.txt](https://github.com/oobabooga/text-generation-webui/files/11411409/456456345354.txt)

**Comment by gardner** [comment]
The Dockerfile was [moved](https://github.com/oobabooga/text-generation-webui/commit/753cd2d30324aba37faf898a94c02287193bcdbc) a few weeks ago but it was not updated to use different paths. 

An immediate workaround for this would be to simply copy the files from the `docker/` directory into the root directory of the repo (usually named `text-generation-webui/`)

From the root of the repo run: `cp docker/{*,.env,.dockerignore} ./`

This would mean you should see the following four files in the root directory of your git repository:
```
text-generation-webui/Dockerfile
text-generation-webui/docker-compose.yml
text-generation-webui/.env
text-generation-webui/.dockerignore
```
