### ISSUE TITLE
why i can not download chatglm-6b?

### ISSUE THREAD

**Issue by zaccheus** [oobabooga/text-generation-webui#1839]
### Describe the bug

python download-model.py THUDM/chatglm-6b

log:
Traceback (most recent call last):
  File "/home/apps/text-generation-webui/download-model.py", line 196, in <module>
    links, sha256, is_lora = get_download_links_from_huggingface(model, branch)
  File "/home/apps/text-generation-webui/download-model.py", line 130, in get_download_links_from_huggingface
    fname = dict[i]['path']
KeyError: 0

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

python download-model.py THUDM/chatglm-6b

log:
Traceback (most recent call last):
  File "/home/apps/text-generation-webui/download-model.py", line 196, in <module>
    links, sha256, is_lora = get_download_links_from_huggingface(model, branch)
  File "/home/apps/text-generation-webui/download-model.py", line 130, in get_download_links_from_huggingface
    fname = dict[i]['path']
KeyError: 0

### Logs

```shell
python download-model.py THUDM/chatglm-6b

log:
Traceback (most recent call last):
  File "/home/apps/text-generation-webui/download-model.py", line 196, in <module>
    links, sha256, is_lora = get_download_links_from_huggingface(model, branch)
  File "/home/apps/text-generation-webui/download-model.py", line 130, in get_download_links_from_huggingface
    fname = dict[i]['path']
KeyError: 0
```

### System Info

```shell
python download-model.py THUDM/chatglm-6b

log:
Traceback (most recent call last):
  File "/home/apps/text-generation-webui/download-model.py", line 196, in <module>
    links, sha256, is_lora = get_download_links_from_huggingface(model, branch)
  File "/home/apps/text-generation-webui/download-model.py", line 130, in get_download_links_from_huggingface
    fname = dict[i]['path']
KeyError: 0
```

**Comment by Max-Headspace** [comment]
> try downloading it manually or using jdownlader

no offense but don't you think more specific instructions like do this->then this->then that would be more helpful to users that don't already know what you know?  If they download it manually, they probably won't know where to place the file. by they i mean me... i apologize I am coming off strange. having a hard time. "on the spectrum"
