### ISSUE TITLE
Gradio serializing error

### ISSUE THREAD

**Issue by ssenthilanand** [oobabooga/text-generation-webui#1843]
### Describe the bug

On starting the server.py in a WSL Ubuntu 22.04 installation, the program errors out with gradio error.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

On a WSL Ubuntu 22.04 system follow the Manual installation using Conda and try to launch the server.

### Screenshot

![otg_error](https://user-images.githubusercontent.com/1107823/236625976-650c5110-7bdc-41fd-9676-6c97cb23ab97.png)

### Logs

```shell
(textgen) senthil@IdeaCentreG5:~/text-generation-webui$ python server.py
INFO:Gradio HTTP request redirected to localhost :)
bin /home/senthil/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/senthil/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Traceback (most recent call last):
  File "/home/senthil/text-generation-webui/server.py", line 885, in <module>
    create_interface()
  File "/home/senthil/text-generation-webui/server.py", line 472, in create_interface
    with gr.Blocks(css=ui.css if not shared.is_chat() else ui.css + ui.chat_css, analytics_enabled=False, title=title, theme=ui.theme) as shared.gradio['interface']:
  File "/home/senthil/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1285, in __exit__
    self.config = self.get_config_file()
  File "/home/senthil/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1261, in get_config_file
    "input": list(block.input_api_info()),  # type: ignore
  File "/home/senthil/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio_client/serializing.py", line 40, in input_api_info
    return (api_info["serialized_input"][0], api_info["serialized_input"][1])
KeyError: 'serialized_input'
(textgen) senthil@IdeaCentreG5:~/text-generation-webui$
```

### System Info

```shell
Lenovo Ideacenter 5 Prebuilt.
Windows 11.
WSL Ubuntu 22.04.
Nvidia RTX 3060 13GB.
```

**Comment by ssenthilanand** [comment]
Duplicate of #1825
