### ISSUE TITLE
pytorch cuda Out of memory rtx 4090

### ISSUE THREAD

**Issue by lol1greg1lol** [oobabooga/text-generation-webui#1860]
### Describe the bug

can't run this model nor any other 20b models as i run out of memory
somehow i can run KoboldAI_OPT-6.7B-Erebus model. but i can't run the 20b model.
i imagine with 24gb vram and 96gb ram i could run a 20b model locally.
so i must be doing something wrong or the one click installer failed me somehow.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

use windows 1 click installer
install KoboldAI_GPT-NeoX-20B-Erebus
attempt to run

### Logs

```shell
INFO:Loading KoboldAI_GPT-NeoX-20B-Erebus...
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████| 23/23 [00:11<00:00,  2.08it/s]
Traceback (most recent call last):
  File "C:\Users\PC\Desktop\AI\text-generation-webui\server.py", line 872, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\PC\Desktop\AI\text-generation-webui\modules\models.py", line 90, in load_model
    model = model.cuda()
  File "C:\Users\PC\Desktop\AI\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\PC\Desktop\AI\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\PC\Desktop\AI\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\PC\Desktop\AI\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "C:\Users\PC\Desktop\AI\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Users\PC\Desktop\AI\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 288.00 MiB (GPU 0; 23.99 GiB total capacity; 22.91 GiB already allocated; 0 bytes free; 22.92 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Done!
Press any key to continue . . .
```

### System Info

```shell
OS Name	Microsoft Windows 11 Pro
Processor	13th Gen Intel(R) Core(TM) i9-13900KF, 3000 Mhz, 24 Core(s), 32 Logical Processor(s)

Installed Physical Memory (RAM)	96.0 GB
Total Virtual Memory	110 GB
```

**Comment by ClayShoaf** [comment]
If you're talking about this: https://huggingface.co/KoboldAI/GPT-NeoX-20B-Erebus/tree/main
It will have to be quantized to 4-bits if you want to run it in 24GB vram. You could run it in CPU mode (if you use [this model](https://huggingface.co/KoboldAI/GPT-NeoX-20B-Erebus-GGML), but it will go a lot slower.
