### ISSUE TITLE
ValueError: Invalid extension type state

### ISSUE THREAD

**Issue by cosmiclantern** [oobabooga/text-generation-webui#1864]
### Describe the bug

Hi, I'm running the 4bit_TextGen_Gdrive.ipynb notebook in colab.

I can't do inference, as when I type a prompt and click the 'generate' button, the "assistant" says it's typing a reponse but it just hangs in that state. 

Was working with all the exact same settings/model etc. last night.

It was giving me the "serialized input" error earlier, but it stopped doing that after I forced it to upgrade gradio to 3.28.3 by putting gradio==3.28.3 in the requirements.txt.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run the notebook found here: https://github.com/eucdee/AI

!pip install --upgrade gradio

or just put it in the requirements.txt
gradio==3.28.3

to get away from the dreaded serialized input error.

Choose a model. Run either with 8bit or not, any of the startup settings it doesn't matter.

Type a prompt and try to generate a reply - it will hang.

### Logs

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1035, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 491, in async_iteration
    return next(iterator)
  File "/content/drive/MyDrive/text-generation-webui/modules/chat.py", line 248, in cai_chatbot_wrapper
    for history in chatbot_wrapper(text, state):
  File "/content/drive/MyDrive/text-generation-webui/modules/chat.py", line 182, in chatbot_wrapper
    for reply in generate_reply(f"{prompt}{' ' if len(cumulative_reply) > 0 else ''}{cumulative_reply}", state, eos_token=eos_token, stopping_strings=stopping_strings):
  File "/content/drive/MyDrive/text-generation-webui/modules/text_generation.py", line 146, in generate_reply
    state = apply_extensions('state', state)
  File "/content/drive/MyDrive/text-generation-webui/modules/extensions.py", line 110, in apply_extensions
    raise ValueError(f"Invalid extension type {typ}")
ValueError: Invalid extension type state
```

### System Info

```shell
Google colab, any GPU: t4, v100, a100, high ram state.
```

**Comment by cosmiclantern** [comment]
I fixed it.

I replaced the modules/extensions.py file with the extensions.py from the current repository.
