### ISSUE TITLE
Silero_tts: TypeError: save_history() missing 1 required positional argument: 'mode'

### ISSUE THREAD

**Issue by chigkim** [oobabooga/text-generation-webui#1869]
### Describe the bug

silero_tts throws an error first time generating output.
`extensions/silero_tts/script.py", line 177: TypeError: save_history() missing 1 required positional argument: 'mode'`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Run the server with silero_tts
2. Activate tts and check automatic playback
3. Send an input to get a response.

It generates speech and plays the audio, but it throws an error below.

### Screenshot

N/A

### Logs

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1021, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/GPTQ-for-LLaMa/extensions/silero_tts/script.py", line 177, in <lambda>
    show_text.change(lambda: chat.save_history(timestamp=False), [], [], show_progress=False)
TypeError: save_history() missing 1 required positional argument: 'mode'
Using Silero TTS cached checkpoint found at /root/.cache/torch/hub
Output generated in 18.21 seconds (2.14 tokens/s, 39 tokens, context 1108, seed 448506474)
```

### System Info

```shell
Colab
```

**Comment by lpohl** [comment]
Same error for me, but it's happening immediately when I check the "Show message text under audio player", before generating an answer.
But it didn't seem to impact the interface from working.
