### ISSUE TITLE
ModuleNotFoundError: No module named 'jmespath'

### ISSUE THREAD

**Issue by athenawisdoms** [oobabooga/text-generation-webui#1874]
### Describe the bug

Got the ModuleNotFoundError when trying to start the web ui on a newly created conda env. 

Had to fix it by also running

```
pip install jmespath
```

Did I miss a step? Thanks!

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
conda create -n textgen python=3.10.9
conda activate textgen
git clone https://github.com/oobabooga/text-generation-webui
cd text-generation-webui
pip3 install torch torchvision torchaudio
pip install -r requirements.txt
python server.py
```

### Logs

```shell
$ python server.py
INFO:Gradio HTTP request redirected to localhost :)
Traceback (most recent call last):
  File "/home/athenawisdoms/test/text-generation-webui/server.py", line 46, in <module>
    from modules import chat, shared, training, ui, utils
  File "/home/athenawisdoms/test/text-generation-webui/modules/chat.py", line 17, in <module>
    from modules.text_generation import (encode, generate_reply,
  File "/home/athenawisdoms/test/text-generation-webui/modules/text_generation.py", line 17, in <module>
    from modules.models import clear_torch_cache, local_rank
  File "/home/athenawisdoms/test/text-generation-webui/modules/models.py", line 13, in <module>
    from accelerate import infer_auto_device_map, init_empty_weights
  File "/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/accelerator.py", line 31, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/utils/__init__.py", line 106, in <module>
    from .launch import (
  File "/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/utils/launch.py", line 24, in <module>
    from ..commands.config.config_args import SageMakerConfig
  File "/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/commands/config/__init__.py", line 19, in <module>
    from .config import config_command_parser
  File "/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/commands/config/config.py", line 25, in <module>
    from .sagemaker import get_sagemaker_input
  File "/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/commands/config/sagemaker.py", line 35, in <module>
    import boto3  # noqa: F401
  File "/home/athenawisdoms/.local/lib/python3.10/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/home/athenawisdoms/.local/lib/python3.10/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/home/athenawisdoms/.local/lib/python3.10/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/home/athenawisdoms/.local/lib/python3.10/site-packages/botocore/client.py", line 15, in <module>
    from botocore import waiter, xform_name
  File "/home/athenawisdoms/.local/lib/python3.10/site-packages/botocore/waiter.py", line 16, in <module>
    import jmespath
ModuleNotFoundError: No module named 'jmespath'
```

### System Info

```shell
Nvidia RTX 3090 Founder Edition #1
Nvidia RTX 3090 Founder Edition #2
Ubuntu 22.04.2 LTS
```

**Comment by cibernicola** [comment]
Exatrly same error but in current version (pulled a few moments ago) 
Nvidia RTX 3090
Windows 10
