### ISSUE TITLE
Seeing "Operation not permitted" when installing on Mac OS 12.3.1

### ISSUE THREAD

**Issue by programmingkidx** [oobabooga/text-generation-webui#1888]
### Describe the bug

After downloading the installer for Mac OS I tried to run the start script in the terminal and saw the error "Permission denied". After running "chmod +x start_macos.sh" I was able to make it execute. It did not complete successfully. Here is the error I saw:

Miniconda version:
Traceback (most recent call last):
  File "/Users/user/Downloads/oobabooga_macos/installer_files/conda/bin/conda", line 12, in <module>
    from conda.cli import main
  File "/Users/user/Downloads/oobabooga_macos/installer_files/conda/lib/python3.10/site-packages/conda/cli/__init__.py", line 3, in <module>
    from .main import main  # NOQA
  File "/Users/user/Downloads/oobabooga_macos/installer_files/conda/lib/python3.10/site-packages/conda/cli/main.py", line 34, in <module>
    from .conda_argparse import generate_parser
  File "/Users/user/Downloads/oobabooga_macos/installer_files/conda/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 27, in <module>
    from ..base.context import context
  File "/Users/user/Downloads/oobabooga_macos/installer_files/conda/lib/python3.10/site-packages/conda/base/context.py", line 63, in <module>
    os.getcwd()
PermissionError: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/Users/user/Downloads/oobabooga_macos/installer_files/conda/bin/conda", line 12, in <module>
    from conda.cli import main
  File "/Users/user/Downloads/oobabooga_macos/installer_files/conda/lib/python3.10/site-packages/conda/cli/__init__.py", line 3, in <module>
    from .main import main  # NOQA
  File "/Users/user/Downloads/oobabooga_macos/installer_files/conda/lib/python3.10/site-packages/conda/cli/main.py", line 34, in <module>
    from .conda_argparse import generate_parser
  File "/Users/user/Downloads/oobabooga_macos/installer_files/conda/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 27, in <module>
    from ..base.context import context
  File "/Users/user/Downloads/oobabooga_macos/installer_files/conda/lib/python3.10/site-packages/conda/base/context.py", line 63, in <module>
    os.getcwd()
PermissionError: [Errno 1] Operation not permitted
Conda environment is empty.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Try to run the start_macos.sh script.

### Logs

```shell
See description.
```

### System Info

```shell
Mac OS 12.3.1
M1 CPU
Python 3.10.9
```

**Comment by xNul** [comment]
@programmingkidx delete all files and try to run again with `bash start_macos.sh`. Do you still have the problem?

**Comment by programmingkidx** [comment]
@xNul Yes.

**Comment by xNul** [comment]
@programmingkidx have you tried this? https://stackoverflow.com/questions/58479686/permissionerror-errno-1-operation-not-permitted-after-macos-catalina-update

**Comment by programmingkidx** [comment]
This fixed the problem. Thank you very much for the help.

**Comment by xNul** [comment]
@programmingkidx no problem! Please close the issue if everything is resolved
