### ISSUE TITLE
TypeError: install() got an unexpected keyword argument 'show_locals'

### ISSUE THREAD

**Issue by Snimm** [oobabooga/text-generation-webui#1916]
### Describe the bug

I tried to download and run Pygmalion 7B (gozfarb/pygmalion-7b-4bit-128g-cuda). on this UI.  I got this error TypeError: install() got an unexpected keyword argument 'show_locals'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Used one-click installed on Linux installer
install is successful
Select Nvidia 
download this model gozfarb/pygmalion-7b-4bit-128g-cuda.
get error

### Logs

```shell
Traceback (most recent call last):
  File "/home/sonnet/AI/oobabooga_linux/text-generation-webui/server.py", line 47, in <module>
    from modules import chat, shared, training, ui, utils
  File "/home/sonnet/AI/oobabooga_linux/text-generation-webui/modules/chat.py", line 17, in <module>
    from modules.text_generation import (encode, generate_reply,
  File "/home/sonnet/AI/oobabooga_linux/text-generation-webui/modules/text_generation.py", line 17, in <module>
    from modules.models import clear_torch_cache, local_rank
  File "/home/sonnet/AI/oobabooga_linux/text-generation-webui/modules/models.py", line 13, in <module>
    from accelerate import infer_auto_device_map, init_empty_weights
  File "/home/sonnet/AI/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/accelerate/__init__.py", line 32, in <module>
    from .utils import rich
  File "/home/sonnet/AI/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/accelerate/utils/rich.py", line 21, in <module>
    install(show_locals=False)
TypeError: install() got an unexpected keyword argument 'show_locals'
```

### System Info

```shell
Operating system: Linux Ubuntu
GPU: Nvidia RTX 3060 12 GB
RAM: 8 GB
```

**Comment by joker01-01** [comment]
> ### Describe the bug
> I tried to download and run Pygmalion 7B (gozfarb/pygmalion-7b-4bit-128g-cuda). on this UI. I got this error TypeError: install() got an unexpected keyword argument 'show_locals'
> 
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Reproduction
> Used one-click installed on Linux installer install is successful Select Nvidia download this model gozfarb/pygmalion-7b-4bit-128g-cuda. get error
> 
> ### Screenshot
> _No response_
> 
> ### Logs
> ```shell
> Traceback (most recent call last):
>   File "/home/sonnet/AI/oobabooga_linux/text-generation-webui/server.py", line 47, in <module>
>     from modules import chat, shared, training, ui, utils
>   File "/home/sonnet/AI/oobabooga_linux/text-generation-webui/modules/chat.py", line 17, in <module>
>     from modules.text_generation import (encode, generate_reply,
>   File "/home/sonnet/AI/oobabooga_linux/text-generation-webui/modules/text_generation.py", line 17, in <module>
>     from modules.models import clear_torch_cache, local_rank
>   File "/home/sonnet/AI/oobabooga_linux/text-generation-webui/modules/models.py", line 13, in <module>
>     from accelerate import infer_auto_device_map, init_empty_weights
>   File "/home/sonnet/AI/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/accelerate/__init__.py", line 32, in <module>
>     from .utils import rich
>   File "/home/sonnet/AI/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/accelerate/utils/rich.py", line 21, in <module>
>     install(show_locals=False)
> TypeError: install() got an unexpected keyword argument 'show_locals'
> ```
> 
> ### System Info
> ```shell
> Operating system: Linux Ubuntu
> GPU: Nvidia RTX 3060 12 GB
> RAM: 8 GB
> ```

I reslove this problem's way is 
`install(show_locals=False)`
from it to
`# install(show_locals=False)`
It solve my problem
