### ISSUE TITLE
Superbooga: ValueError: You must provide either query embeddings or query texts, but not both

### ISSUE THREAD

**Issue by dcbishop** [oobabooga/text-generation-webui#1919]
### Describe the bug

I get this error whenever I try and generate text with superbooga.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Use superbooga.

### Logs

```shell
Traceback (most recent call last):
  File "/home/dcbishop/.local/lib/python3.11/site-packages/gradio/routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dcbishop/.local/lib/python3.11/site-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dcbishop/.local/lib/python3.11/site-packages/gradio/blocks.py", line 1035, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dcbishop/.local/lib/python3.11/site-packages/gradio/utils.py", line 491, in async_iteration
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/home/dcbishop/src/text-generation-webui/modules/text_generation.py", line 164, in generate_reply
    question = apply_extensions('input', question)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dcbishop/src/text-generation-webui/modules/extensions.py", line 132, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dcbishop/src/text-generation-webui/modules/extensions.py", line 58, in _apply_string_extensions
    text = getattr(extension, function_name)(text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dcbishop/src/text-generation-webui/extensions/superbooga/script.py", line 150, in input_modifier
    results = collector.get(user_input, n_results=chunk_count)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dcbishop/src/text-generation-webui/extensions/superbooga/script.py", line 55, in get
    result = self.collection.query(query_texts=search_strings, n_results=n_results, include=['documents'])['documents'][0]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dcbishop/.local/lib/python3.11/site-packages/chromadb/api/models/Collection.py", line 185, in query
    raise ValueError(
ValueError: You must provide either query embeddings or query texts, but not both
```

### System Info

```shell
Arch Linux, nVidia 2080TI
```

**Comment by Pakobbix** [comment]
You have to include the tags into the text field.

https://github.com/oobabooga/text-generation-webui/pull/1548#issuecomment-1537335635
> The user input should be written between <|begin-user-input|> and <|end-user-input|> tags
> The injection point should be specified with <|injection-point|> in the prompt
> The data should be entered in a textbox created by the extension

For me, something like:
```
Common sense questions and answers
<|injection-point|>
<|begin-user-input|>

Question: ?
<|end-user-input|>

Factual answer: ​
```
