### ISSUE TITLE
Loading big models 4bit

### ISSUE THREAD

**Issue by scavru** [oobabooga/text-generation-webui#1938]
### Describe the bug

As I understand it, the model is loaded through the cpu. and not directly into the GPU. This makes it impossible to load a large model with little system memory. The same [koboldAI ](https://github.com/0cc4m/KoboldAI)build for 4bit models loads normally, directly into the GPU.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

run start_windows.bat with python server.py --bf16 --gpu-memory 23 --chat --model-menu --wbits 4 --groupsize 128

### Logs

```shell
INFO:Loading MetaIX_GPT4-X-Alpaca-30B-4bit...
INFO:Found the following quantized model: models\MetaIX_GPT4-X-Alpaca-30B-4bit\4bit.safetensors
Traceback (most recent call last):
  File "D:\oobabooga_windows\text-generation-webui\server.py", line 885, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\oobabooga_windows\text-generation-webui\modules\models.py", line 159, in load_model
    model = load_quantized(model_name)
  File "D:\oobabooga_windows\text-generation-webui\modules\GPTQ_loader.py", line 186, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.wbits, shared.args.groupsize, kernel_switch_threshold=threshold)
  File "D:\oobabooga_windows\text-generation-webui\modules\GPTQ_loader.py", line 76, in _load_quant
    make_quant(**make_quant_kwargs)
  File "D:\oobabooga_windows\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 446, in make_quant
    make_quant(child, names, bits, groupsize, faster, name + '.' + name1 if name != '' else name1, kernel_switch_threshold=kernel_switch_threshold)
  File "D:\oobabooga_windows\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 446, in make_quant
    make_quant(child, names, bits, groupsize, faster, name + '.' + name1 if name != '' else name1, kernel_switch_threshold=kernel_switch_threshold)
  File "D:\oobabooga_windows\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 446, in make_quant
    make_quant(child, names, bits, groupsize, faster, name + '.' + name1 if name != '' else name1, kernel_switch_threshold=kernel_switch_threshold)
  [Previous line repeated 1 more time]
  File "D:\oobabooga_windows\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 443, in make_quant
    module, attr, QuantLinear(bits, groupsize, tmp.in_features, tmp.out_features, faster=faster, kernel_switch_threshold=kernel_switch_threshold)
  File "D:\oobabooga_windows\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 154, in __init__
    'qweight', torch.zeros((infeatures // 32 * bits, outfeatures), dtype=torch.int)
RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 22151168 bytes.

Done!
```

### System Info

```shell
win11 32Gb and 3090 24Gb
```

**Comment by scavru** [comment]
try --no-cache, didn't help.

**Comment by 2BlackChicken** [comment]
Try increasing window's swap file to a fix 64GB on an SSD instead of using system managed (Doesn't have to be the system drive). I had the same issue when I tried loading the 30B model on my 3090 and my system also have 32GB of RAM. Basically, your system runs out of RAM before finishing to load the model on the GPU. The other option is to upgrade your system to 64GB of RAM.
