### ISSUE TITLE
Can't launch after setting RAM amount

### ISSUE THREAD

**Issue by RaymondTracer** [oobabooga/text-generation-webui#1940]
### Describe the bug

It basically breaks everything if you set the RAM in the web UI.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Launch
2. Set RAM amount
3. Relaunch

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/6290310/a8dc0c17-257b-4619-bf04-dbd584e5424c)

### Logs

```shell
INFO:Gradio HTTP request redirected to localhost :)
INFO:Loading Imablank_P1GM4L10N-7B-MERGED_WEIGHTS...
WARNING:Auto-assiging --gpu-memory 7 for your GPU to try to prevent out-of-memory errors.
You can manually set other values.
Traceback (most recent call last):
  File "C:\Users\user\Documents\oobabooga-text-gen\text-generation-webui\server.py", line 885, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\user\Documents\oobabooga-text-gen\text-generation-webui\modules\models.py", line 212, in load_model
    params['device_map'] = infer_auto_device_map(
  File "C:\Users\user\Documents\oobabooga-text-gen\installer_files\env\lib\site-packages\accelerate\utils\modeling.py", line 567, in infer_auto_device_map
    max_memory = get_max_memory(max_memory)
  File "C:\Users\user\Documents\oobabooga-text-gen\installer_files\env\lib\site-packages\accelerate\utils\modeling.py", line 380, in get_max_memory
    max_memory[key] = convert_file_size_to_int(max_memory[key])
  File "C:\Users\user\Documents\oobabooga-text-gen\installer_files\env\lib\site-packages\accelerate\utils\modeling.py", line 59, in convert_file_size_to_int
    return int(size[:-3]) * (2**30)
ValueError: invalid literal for int() with base 10: '32700MiB'

Done!
Press any key to continue . . .
```

### System Info

```shell
Windows 10 22H2
Nvidia RTX 3070 Ti
```

**Comment by RaymondTracer** [comment]
I fixed it by deleting "config-user.yaml", but it might be a good idea to fix it in the code.

**Comment by kilroy1492** [comment]
I have the same issue since the last update. Unable to use a model with any custom RAM settings. Model loads and server quits.


Sys info:
Windows 10
Nvidia 3060 x2
