### ISSUE TITLE
How to install specific compiled deepspeed whl file in the conda environment under Windows without WSL?

### ISSUE THREAD

**Issue by AngelTs** [oobabooga/text-generation-webui#1966]
Under WIndows and without WSL I have successfully compiled deepspeed (deepspeed-0.9.3+unknown-cp310-cp310-win_amd64.whl).
So how to install this specific file it in the current conda environment to be able to use the command "deepspeed --num_gpus=1 server.py --deepspeed --chat --model gpt-j-6B" in "webui.py"?

**Comment by jllllll** [comment]
Open `cmd_windows.bat` and enter this command:
```
python -m pip install deepspeed-0.9.3+unknown-cp310-cp310-win_amd64.whl
```
Keep in mind that, while you can install deepspeed on Windows, it is unlikely to work due to Pytorch lacking support for the backend that Windows uses: https://github.com/oobabooga/text-generation-webui/issues/1225

**Comment by AngelTs** [comment]
> Open `cmd_windows.bat` and enter this command:
> 
> ```
> python -m pip install deepspeed-0.9.3+unknown-cp310-cp310-win_amd64.whl
> ```
> 
> Keep in mind that, while you can install deepspeed on Windows, it is unlikely to work due to Pytorch lacking support for the backend that Windows uses: #1225

Thanks, I success to install deepspeed with your command in this miniconda environment, but can't start it:
in "webui.py" i put the line "run_cmd("deepspeed --num_gpus=1 server.py --deepspeed --chat --model gpt-j-6B", environment=True)  # put your flags here!" and after start the command "start_windows.bat" the following error occurred:
"'deepspeed' is not recognized as an internal or external command"

**Comment by AngelTs** [comment]
FInally i managed to start the deep speed via the following command in the "webui.py" file:
run_cmd("python ..\installer_files\env\scripts\ds --num_gpus=1 server.py --deepspeed --model-menu --chat", environment=True)  # put your flags here!
but end up with the NCCL error:

[2023-05-11 09:41:20,913] [INFO] [launch.py:229:main] WORLD INFO DICT: {'localhost': [0]}
[2023-05-11 09:41:20,913] [INFO] [launch.py:235:main] nnodes=1, num_local_procs=1, node_rank=0
[2023-05-11 09:41:20,913] [INFO] [launch.py:246:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2023-05-11 09:41:20,913] [INFO] [launch.py:247:main] dist_world_size=1
[2023-05-11 09:41:20,913] [INFO] [launch.py:249:main] Setting CUDA_VISIBLE_DEVICES=0
INFO:Gradio HTTP request redirected to localhost :)
[2023-05-11 09:41:31,023] [INFO] [comm.py:622:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [AngelT]:29500 (system error: 10049 - unknown error).
[W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [AngelT]:29500 (system error: 10049 - unknown error).
Traceback (most recent call last):
  File "C:\oobabooga_windows\text-generation-webui\server.py", line 45, in <module>
    from modules import chat, shared, training, ui
  File "C:\oobabooga_windows\text-generation-webui\modules\chat.py", line 17, in <module>
    from modules.text_generation import (encode, generate_reply,
  File "C:\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 17, in <module>
    from modules.models import clear_torch_cache, local_rank
  File "C:\oobabooga_windows\text-generation-webui\modules\models.py", line 38, in <module>
    deepspeed.init_distributed()
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\deepspeed\comm\comm.py", line 624, in init_distributed
    cdb = TorchBackend(dist_backend, timeout, init_method, rank, world_size)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\deepspeed\comm\torch.py", line 60, in __init__
    self.init_process_group(backend, timeout, init_method, rank, world_size)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\deepspeed\comm\torch.py", line 86, in init_process_group
    torch.distributed.init_process_group(backend,
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\torch\distributed\distributed_c10d.py", line 895, in init_process_group
    default_pg = _new_process_group_helper(
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\torch\distributed\distributed_c10d.py", line 998, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
[2023-05-11 09:41:33,038] [INFO] [launch.py:428:sigkill_handler] Killing subprocess 6920
[2023-05-11 09:41:33,038] [ERROR] [launch.py:434:sigkill_handler] ['C:\\oobabooga_windows\\installer_files\\env\\python.exe', '-u', 'server.py', '--local_rank=0', '--deepspeed', '--model-menu', '--chat'] exits with return code = 1

Done!

**Comment by AngelTs** [comment]
The above error is resolved after changed dist_backend=None to dist_backend='gloo' on line 562 in "C:\oobabooga_windows\installer_files\env\Lib\site-packages\deepspeed\comm\comm.py"
But it is not enough because of the next raised error:
"RuntimeError: a leaf Variable that requires grad is being used in an in-place operation."
Game over ...
