### ISSUE TITLE
Yet another MPT issue

### ISSUE THREAD

**Issue by elfgoose** [oobabooga/text-generation-webui#1972]
### Describe the bug

Getting an error when I try to load to 4-bit MPT model. I tried searching, but I can't figure out how to apply some of th eother issues to mine. 

CMD text:

Requirement already satisfied: einops in c:\ai\oobabooga_windows\installer_files\env\lib\site-packages (0.6.1)
Gradio HTTP request redirected to localhost :)
Warning: trust_remote_code is enabled. This is dangerous.

bin C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
Loading settings from settings.json...
Loading mosaicml_mpt-7b-storywriter...
Traceback (most recent call last):
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 628, in _get_config_dict
    resolved_config_file = cached_file(
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\huggingface_hub\utils\_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\huggingface_hub\utils\_validators.py", line 166, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'models\mosaicml_mpt-7b-storywriter'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\AI\oobabooga_windows\text-generation-webui\server.py", line 917, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\AI\oobabooga_windows\text-generation-webui\modules\models.py", line 56, in load_model
    model = LoaderClass.from_pretrained(Path(f"{shared.args.model_dir}/{shared.model_name}"), low_cpu_mem_usage=True, torch_dtype=torch.bfloat16 if shared.args.bf16 else torch.float16, trust_remote_code=trust_remote_code)
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 441, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\configuration_auto.py", line 916, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 573, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 649, in _get_config_dict
    raise EnvironmentError(
OSError: Can't load the configuration of 'models\mosaicml_mpt-7b-storywriter'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'models\mosaicml_mpt-7b-storywriter' is the correct path to a directory containing a config.json file

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Happens every time

### Logs

```shell
Requirement already satisfied: einops in c:\ai\oobabooga_windows\installer_files\env\lib\site-packages (0.6.1)
Gradio HTTP request redirected to localhost :)
Warning: trust_remote_code is enabled. This is dangerous.

bin C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
Loading settings from settings.json...
Loading mosaicml_mpt-7b-storywriter...
Traceback (most recent call last):
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 628, in _get_config_dict
    resolved_config_file = cached_file(
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\huggingface_hub\utils\_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\huggingface_hub\utils\_validators.py", line 166, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'models\mosaicml_mpt-7b-storywriter'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\AI\oobabooga_windows\text-generation-webui\server.py", line 917, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\AI\oobabooga_windows\text-generation-webui\modules\models.py", line 56, in load_model
    model = LoaderClass.from_pretrained(Path(f"{shared.args.model_dir}/{shared.model_name}"), low_cpu_mem_usage=True, torch_dtype=torch.bfloat16 if shared.args.bf16 else torch.float16, trust_remote_code=trust_remote_code)
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 441, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\configuration_auto.py", line 916, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 573, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 649, in _get_config_dict
    raise EnvironmentError(
OSError: Can't load the configuration of 'models\mosaicml_mpt-7b-storywriter'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'models\mosaicml_mpt-7b-storywriter' is the correct path to a directory containing a config.json file
```

### System Info

```shell
NVIDIA RTX3080 TI 12GB, Windows 10
```

**Comment by yhyu13** [comment]
> huggingface_hub.utils.validators.HFValidationError: Repo id must use alphanumeric chars or '-', '', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'models\mosaicml_mpt-7b-storywriter'.

ehh, "models\mosaicml_mpt-7b-storywrite" is not a standardized folder name, you should use mosaicml-mpt-7b-storywrite instead? I have not tried mpt before

**Comment by elfgoose** [comment]
Thanks for th ereply.  It's weird because the folder is actually called "OccamRazor_mpt-7b-storywriter-4bit-128g"  and I d/l it from within the ooba interface, so it is the one that named it
