### ISSUE TITLE
KeyError: 'CONDA_DEFAULT_ENV'

### ISSUE THREAD

**Issue by luphoria** [oobabooga/text-generation-webui#1989]
### Describe the bug

Just tried to run oobabooga from the Linux setup script, using Arch Linux, ran into this error on `python webui.py`. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

- Download oobabooga_linux.zip
- run ./start_linux.sh
- specify no GPU
- run webui.py

### Logs

```shell
~/llama/oobabooga_linux via  v3.11.3 took 10s  python webui.py
Traceback (most recent call last):
  File "/home/trent/llama/oobabooga_linux/webui.py", line 176, in <module>
    check_env()
  File "/home/trent/llama/oobabooga_linux/webui.py", line 45, in check_env
    if os.environ["CONDA_DEFAULT_ENV"] == "base":
       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'CONDA_DEFAULT_ENV'
```

### System Info

```shell
#####           trent@bread
       #######          -----------
       ##O#O##          OS: instantOS x86_64
       #######          Host: Jupiter 1
     ###########        Kernel: 6.1.27-1-lts
    #############       Uptime: 2 days, 19 hours, 49 mins
   ###############      Packages: 1238 (pacman)
   ################     Shell: zsh 5.9
  #################     Resolution: 1920x1080
#####################   DE: instantwm
#####################   WM: dwm
  #################     Theme: Qogir [GTK2/3]
                        Icons: Papirus [GTK2/3]
                        Terminal: tmux
                        CPU: AMD Custom APU 0405 (8) @ 2.800GHz
                        GPU: AMD ATI AMD Custom GPU 0405
                        Memory: 2575MiB / 14830MiB
```

**Comment by cornpo** [comment]
Install anaconda or monoconda. Create and activate a conda environment. Install the python requirements.

But, you don't have enough RAM probably.

**Comment by luphoria** [comment]
> But, you don't have enough RAM probably.

I can run llama.cpp with no problems
