### ISSUE TITLE
"CUDA out of memory"

### ISSUE THREAD

**Issue by txmzyz** [oobabooga/text-generation-webui#1999]
### Describe the bug

"CUDA out of memory"

I cannot access the webui to change the "pre_layer" setting, because I am unable to get pass the cmd stage. 

I tried the "--pre_layer" (edited infront of "call python webui.py") technique but It is not recognised and shows an error when I try to execute. Not sure what to do. I also included a number infront of --pre_layer with a space e.g., (--pre_layer 12). I expiremented with many numbers, including ones calculated using the 0.222 formula thing. 

maybe related idk:
- I have a very basic understanding of computers 
- Stable diffusion works great on my pc

### Reproduction

 1. try to open webui 
 - "CUDA out of memory" 
 2. edit "start_windows" file to include "--pre_layer 12" infront of "call python webui.py"
 - [error ](error: unrecognized arguments: --pre_layer 12)

### Logs

```shell
(((FIRST LOGS/BEFORE EDIT)))

INFO:Gradio HTTP request redirected to localhost :)
bin C:\GPT-4\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
INFO:Loading anon8231489123_gpt4-x-alpaca-13b-native-4bit-128g...
WARNING:More than one .pt model has been found. The last one will be selected. It could be wrong.
INFO:Found the following quantized model: models\anon8231489123_gpt4-x-alpaca-13b-native-4bit-128g\gpt-x-alpaca-13b-native-4bit-128g.pt
Traceback (most recent call last):
  File "C:\GPT-4\oobabooga_windows\oobabooga_windows\text-generation-webui\server.py", line 919, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\GPT-4\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\models.py", line 159, in load_model
    model = load_quantized(model_name)
  File "C:\GPT-4\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\GPTQ_loader.py", line 199, in load_quantized
    model = model.to(torch.device('cuda:0'))
  File "C:\GPT-4\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 1896, in to
    return super().to(*args, **kwargs)
  File "C:\GPT-4\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "C:\GPT-4\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\GPT-4\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\GPT-4\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "C:\GPT-4\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 844, in _apply
    self._buffers[key] = fn(buf)
  File "C:\GPT-4\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 14.00 MiB (GPU 0; 6.00 GiB total capacity; 5.15 GiB already allocated; 0 bytes free; 5.32 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Done!
Press any key to continue . . .

(((SECOND LOGS/AFTER EDIT)))
usage: webui.py [-h] [--update]
webui.py: error: unrecognized arguments: --pre_layer 12

Done!
Press any key to continue . . .
```

### System Info

```shell
- My pc has 7.9GB of GPU memory (NVIDIA)
```

**Comment by FlyingFathead** [comment]
LLM's are extremely heavy and 8GB of VRAM is extremely little when it comes to running them. You might want to look for a model that's small as possible and run it in i.e. 4bit quantized mode.

**Comment by Ph0rk0z** [comment]
Yea.. a 13b isn't going to happen, try the 7b.
