### ISSUE TITLE
8-bit loading of OPT 13B fails (tensor contains inf/nan error)

### ISSUE THREAD

**Issue by LoopControl** [oobabooga/text-generation-webui#200]
When using any OPT model smaller than 13B, 8 bit mode works fine.

However, when using OPT-13B and larger, I'm getting the following error:

```
Traceback (most recent call last):
  File "/home/loop/.local/lib/python3.10/site-packages/gradio/routes.py", line 374, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/loop/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1017, in process_api
    result = await self.call_function(
  File "/home/loop/.local/lib/python3.10/site-packages/gradio/blocks.py", line 849, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/loop/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/loop/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/loop/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/loop/.local/lib/python3.10/site-packages/gradio/utils.py", line 453, in async_iteration
    return next(iterator)
  File "/media/loop/BigThree/sd-2/text-generation-webui/modules/text_generation.py", line 170, in generate_reply
    output = eval(f"shared.model.generate({', '.join(generate_params)}){cuda}")[0]
  File "<string>", line 1, in <module>
  File "/home/loop/.local/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/loop/apps/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1452, in generate
    return self.sample(
  File "/home/loop/apps/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2504, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

I'm using latest transformers, CUDA 11.7, Ubuntu Linux and using a Nvidia Tesla P40 (24GB VRAM). I've tried both the pip installed bitsandbytes and the compiled-from-source versions and getting same error.

Any suggestions for resolving this?

**Comment by oobabooga** [comment]
> Hardware requirements:
> 
> LLM.int8(): NVIDIA Turing (RTX 20xx; T4) or Ampere GPU (RTX 30xx; A4-A100); (a GPU from 2018 or older).
> 8-bit optimizers and quantization: NVIDIA Kepler GPU or newer (>=GTX 78X).

https://github.com/TimDettmers/bitsandbytes

You can start a new issue on bitsandbytes, as this is an upstream issue with their library not supporting older GPUs.
