### ISSUE TITLE
Impossible to generate if whole model isn't on device 0. CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by HideLord** [oobabooga/text-generation-webui#2004]
### Describe the bug

Impossible to generate if the whole model isn't on device 0. It does not matter if the whole model is loaded on device 1 or is split between 0 and 1.

The issue is not reproducible for unquantized models.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Requires two GPUs to be reproducible.

**Scenario 1:**

1. Set `run_cmd` string to `python server.py --model_type LLaMA --notebook --model-menu --auto-devices --wbits 4 --groupsize 128 --xformers --quant_attn`
2. Load a 30B **4bit** model (e.g. **LLaMA-HF-4bit-128g** or **GPT4-x-AlpacaDente2-30b**) 
3. Hit Generate in the Webui. 

Expected device map:
{'model.embed_tokens': 0, 'model.layers.0': 0, 'model.layers.1': 0, 'model.layers.2': 0, 'model.layers.3': 0, 'model.layers.4': 0, 'model.layers.5': 0, 'model.layers.6': 0, 'model.layers.7': 0, 'model.layers.8': 0, 'model.layers.9': 0, 'model.layers.10': 0, 'model.layers.11': 0, 'model.layers.12': 0, 'model.layers.13': 0, 'model.layers.14': 0, 'model.layers.15': 0, 'model.layers.16': 0, 'model.layers.17': 0, 'model.layers.18': 0, 'model.layers.19': 0, 'model.layers.20': 0, 'model.layers.21': 0, 'model.layers.22': 0, 'model.layers.23': 0, 'model.layers.24': 0, 'model.layers.25': 0, 'model.layers.26': 0, 'model.layers.27': 0, 'model.layers.28': 1, 'model.layers.29': 1, 'model.layers.30': 1, 'model.layers.31': 1, 'model.layers.32': 1, 'model.layers.33': 1, 'model.layers.34': 1, 'model.layers.35': 1, 'model.layers.36': 1, 'model.layers.37': 1, 'model.layers.38': 1, 'model.layers.39': 1, 'model.layers.40': 1, 'model.layers.41': 1, 'model.layers.42': 1, 'model.layers.43': 1, 'model.layers.44': 1, 'model.layers.45': 1, 'model.layers.46': 1, 'model.layers.47': 1, 'model.layers.48': 1, 'model.layers.49': 1, 'model.layers.50': 1, 'model.layers.51': 1, 'model.layers.52': 1, 'model.layers.53': 1, 'model.layers.54': 1, 'model.layers.55': 1, 'model.layers.56': 1, 'model.layers.57': 1, 'model.layers.58': 1, 'model.layers.59': 1, 'model.norm': 1, 'lm_head': 1}

---
**Scenario 2:**

1. Set `run_cmd` string to `python server.py --model_type LLaMA --notebook --model-menu --gpu-memory 0 22 --wbits 4 --groupsize 128 --xformers --quant_attn` OR modify line 190 in GPTQ_loader to `accelerate.utils.get_balanced_memory(model, low_zero=True)` to force the model to be loaded entirely on the second GPU.
2. Load a 30B **4bit** model (e.g. **LLaMA-HF-4bit-128g** or **GPT4-x-AlpacaDente2-30b**) 
3. Hit Generate in the Webui. 

Expected device map:
{'': 1}

### Logs

```shell
Traceback (most recent call last):
  File "/home/hidelord/Desktop/LLM/Oobabooga/text-generation-webui/modules/callbacks.py", line 73, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/text-generation-webui/modules/text_generation.py", line 259, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/transformers/generation/utils.py", line 1565, in generate
    return self.sample(
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/transformers/generation/utils.py", line 2612, in sample
    outputs = self(
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 688, in forward
    outputs = self.model(
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 578, in forward
    layer_outputs = decoder_layer(
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/accelerate/hooks.py", line 160, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/accelerate/hooks.py", line 275, in pre_forward
    return send_to_device(args, self.execution_device), send_to_device(kwargs, self.execution_device)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/accelerate/utils/operations.py", line 133, in send_to_device
    return recursively_apply(_send_to_device, tensor, device, non_blocking, test_type=_has_to_method)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/accelerate/utils/operations.py", line 93, in recursively_apply
    {
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/accelerate/utils/operations.py", line 94, in <dictcomp>
    k: recursively_apply(
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/accelerate/utils/operations.py", line 101, in recursively_apply
    return func(data, *args, **kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/accelerate/utils/operations.py", line 126, in _send_to_device
    return t.to(device, non_blocking=non_blocking)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception in thread Thread-3 (gentask):
Traceback (most recent call last):
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hidelord/Desktop/LLM/Oobabooga/text-generation-webui/modules/callbacks.py", line 80, in gentask
    clear_torch_cache()
  File "/home/hidelord/Desktop/LLM/Oobabooga/text-generation-webui/modules/callbacks.py", line 112, in clear_torch_cache
    torch.cuda.empty_cache()
  File "/home/hidelord/Desktop/LLM/Oobabooga/installer_files/env/lib/python3.10/site-packages/torch/cuda/memory.py", line 133, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### System Info

```shell
Linux Mint

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.41.03              Driver Version: 530.41.03    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090         On | 00000000:04:00.0  On |                  N/A |
| 58%   52C    P2              127W / 265W|   1132MiB / 24576MiB |      3%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 3090         On | 00000000:08:00.0 Off |                  N/A |
|  0%   57C    P8               27W / 265W|  18076MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1266      G   /usr/lib/xorg/Xorg                          221MiB |
|    0   N/A  N/A      1867      G   ...ures=SpareRendererForSitePerProcess       34MiB |
|    0   N/A  N/A      2117      G   ...9465242,11150620367205049605,262144       67MiB |
|    0   N/A  N/A     18156      G   ...sion,SpareRendererForSitePerProcess       54MiB |
|    0   N/A  N/A     24894      C   python                                      750MiB |
|    1   N/A  N/A      1266      G   /usr/lib/xorg/Xorg                            4MiB |
|    1   N/A  N/A     24894      C   python                                    18068MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by HideLord** [comment]
Also, just to be safe, I tested without any overclocking/undervolting. It's still reproducible.

**Comment by HideLord** [comment]
Hm, it seems that --quant_attn was breaking it somehow. Without it, the error does not appear.
