### ISSUE TITLE
KeyError: 'HOME' on windows 11 using triton

### ISSUE THREAD

**Issue by Midaychi** [oobabooga/text-generation-webui#2015]
### Describe the bug

in \lib\site-packages\triton\compiler.py
When trying to actually run the inference, it tries to run os.environ.get('TRITON_CACHE_DIR', default_cache_dir())
 return os.path.join(os.environ["HOME"], ".triton", "cache")

 line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

get mildly old but working triton prebuilt from 
https://huggingface.co/r4ziel/xformers_pre_built
Install within a functional conda environment

Install ooba req with 2.0 torch+ cuda 117 on windows in that env

Quickest way to trigger the issue is to just run ooba server.py with the normal switches as well as --warmup_autotune

### Screenshot

![homeerror](https://github.com/oobabooga/text-generation-webui/assets/1968809/be9c7fad-cd64-4969-b512-3eb62a906225)

### Logs

```shell
Traceback (most recent call last):
  File "<myoobadir>\text-generation-webui\modules\callbacks.py", line 73, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "<myoobadir>\text-generation-webui\modules\text_generation.py", line 263, in generate_with_callback
    shared.model.generate(**kwargs)
  File "<mycondaenv>\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "<mycondaenv>\lib\site-packages\transformers\generation\utils.py", line 1565, in generate
    return self.sample(
  File "<mycondaenv>\lib\site-packages\transformers\generation\utils.py", line 2612, in sample
    outputs = self(
  File "<mycondaenv>\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "<mycondaenv>\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "<mycondaenv>\lib\site-packages\transformers\models\llama\modeling_llama.py", line 688, in forward
    outputs = self.model(
  File "<mycondaenv>\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "<mycondaenv>\lib\site-packages\transformers\models\llama\modeling_llama.py", line 578, in forward
    layer_outputs = decoder_layer(
  File "<mycondaenv>\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "<mycondaenv>\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "<mycondaenv>\lib\site-packages\transformers\models\llama\modeling_llama.py", line 293, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "<mycondaenv>\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "<mycondaenv>\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "<myoobadir>\text-generation-webui\repositories\GPTQ-for-LLaMa\quant\fused_attn.py", line 121, in forward
    qkv_states = self.qkv_proj(hidden_states)
  File "<mycondaenv>\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "<mycondaenv>\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "<myoobadir>\text-generation-webui\repositories\GPTQ-for-LLaMa\quant\quant_linear.py", line 375, in forward
    out = QuantLinearFunction.apply(x.reshape(-1, x.shape[-1]), self.qweight, self.scales, self.qzeros, self.g_idx, self.bits, self.maxq)
  File "<mycondaenv>\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "<mycondaenv>\lib\site-packages\torch\cuda\amp\autocast_mode.py", line 106, in decorate_fwd
    return fwd(*args, **kwargs)
  File "<myoobadir>\text-generation-webui\repositories\GPTQ-for-LLaMa\quant\quant_linear.py", line 287, in forward
    output = matmul248(input, qweight, scales, qzeros, g_idx, bits, maxq)
  File "<myoobadir>\text-generation-webui\repositories\GPTQ-for-LLaMa\quant\quant_linear.py", line 267, in matmul248
    matmul_248_kernel[grid](input, qweight, output, scales, qzeros, g_idx, input.shape[0], qweight.shape[1], input.shape[1], bits, maxq, input.stride(0), input.stride(1), qweight.stride(0),
  File "<mycondaenv>\lib\site-packages\triton\runtime\jit.py", line 106, in launcher
    return self.run(*args, grid=grid, **kwargs)
  File "<myoobadir>\text-generation-webui\repositories\GPTQ-for-LLaMa\quant\custom_autotune.py", line 90, in run
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
  File "<myoobadir>\text-generation-webui\repositories\GPTQ-for-LLaMa\quant\custom_autotune.py", line 90, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
  File "<myoobadir>\text-generation-webui\repositories\GPTQ-for-LLaMa\quant\custom_autotune.py", line 72, in _bench
    return triton.testing.do_bench(kernel_call, percentiles=(0.5, 0.2, 0.8), rep=40)
  File "<mycondaenv>\lib\site-packages\triton\testing.py", line 136, in do_bench
    fn()
  File "<myoobadir>\text-generation-webui\repositories\GPTQ-for-LLaMa\quant\custom_autotune.py", line 67, in kernel_call
    self.fn.run(*args, num_warps=config.num_warps, num_stages=config.num_stages, **current)
  File "<string>", line 41, in matmul_248_kernel
  File "<mycondaenv>\lib\site-packages\triton\compiler.py", line 1230, in compile
    so_cache_manager = CacheManager(so_cache_key)
  File "<mycondaenv>\lib\site-packages\triton\compiler.py", line 1102, in __init__
    self.cache_dir = os.environ.get('TRITON_CACHE_DIR', default_cache_dir())
  File "<mycondaenv>\lib\site-packages\triton\compiler.py", line 1093, in default_cache_dir
    return os.path.join(os.environ["HOME"], ".triton", "cache")
  File "<mycondaenv>\lib\os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'
Output generated in 0.28 seconds (0.00 tokens/s, 0 tokens, context 16, seed 1196075087)
```

### System Info

```shell
win 11 (*-12ish)
gtx 3070 mobile 8gb
i7 12650H
not using WSL/WSL2
```

Edit: was trying to load stable vicuna from https://huggingface.co/TheBloke/stable-vicuna-13B-GPTQ
and I was using the triton gptq branch from oob's.

**Comment by Midaychi** [comment]
after a bit of poking, the precompiled version of triton is older than this commit https://github.com/openai/triton/pull/1364

So it could be related. Oobaboob's is the only program using triton that gives me this error though.
