### ISSUE TITLE
CPU mode shows Torch AssertionError: Torch not compiled with CUDA enabled (Ubuntu)

### ISSUE THREAD

**Issue by MbBrainz** [oobabooga/text-generation-webui#2038]
### Describe the bug

After trying GPU mode and finding out that my gpu is way too old, I tried reinstalling the repo from scratch but using cpu mode. I ran the start_linux.sh downloaded the opt2.7b model but then it showed: `AssertionError: Torch not compiled with CUDA enabled`. I did not see this error when using the GPU, but I got a out of memory error.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. download linux installer using `wget https://github.com/oobabooga/text-generation-webui/releases/download/installers/oobabooga_linux.zip`
2. cd into it
3. run `chmod -v +x start_linux.sh`
4. run `./start_linux.sh`

### Logs

```shell
100%|█████████████████████████████████████████████████████████████████████████| 899k  /899k   3.16MiB/s
INFO:Gradio HTTP request redirected to localhost :)
bin /home/user/code/text-gn-webui/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/user/code/text-gn-webui/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
INFO:Loading facebook_opt-2.7b...
Traceback (most recent call last):
  File "/home/user/code/text-gn-webui/oobabooga_linux/text-generation-webui/server.py", line 948, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/user/code/text-gn-webui/oobabooga_linux/text-generation-webui/modules/models.py", line 90, in load_model
    model = model.cuda()
  File "/home/user/code/text-gn-webui/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/user/code/text-gn-webui/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/user/code/text-gn-webui/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/user/code/text-gn-webui/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/user/code/text-gn-webui/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/user/code/text-gn-webui/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/user/code/text-gn-webui/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

Done!
```

### System Info

```shell
## system specs: 

### OS 
Operating System: Ubuntu 22.04.2 LTS
          Kernel: Linux 5.19.0-41-generic
    Architecture: x86-64

### CPU
CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  8
  On-line CPU(s) list:   0-7
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz

### GPU
nvidia quadro M1000M
NVIDIA-SMI 530.41.03 
Driver Version: 530.41.03    
CUDA Version: 12.1
```

**Comment by feoh** [comment]
Seeing this as well on AMD GPU/Linux.
