### ISSUE TITLE
is this really a GGML file? llama_init_from_file: failed to load model

### ISSUE THREAD

**Issue by 2tYfX8sgnrx** [oobabooga/text-generation-webui#2046]
Error

**Comment by KingofMidnight** [comment]
i got the same error on my windows vm

llama.cpp: loading model from models\TheBloke_Wizard-Vicuna-13B-Uncensored-GGML\Wizard-Vicuna-13B-Uncensored.ggml.q4_0.bin
error loading model: unknown (magic, version) combination: 67676a74, 00000002; is this really a GGML file?
llama_init_from_file: failed to load model
Traceback (most recent call last):
  File "D:\oobabooga_windows\text-generation-webui\server.py", line 948, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\oobabooga_windows\text-generation-webui\modules\models.py", line 142, in load_model
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
  File "D:\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 32, in from_pretrained
    self.model = Llama(**params)
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 159, in __init__
    assert self.ctx is not None
AssertionError

**Comment by m-spangenberg** [comment]
Not a bug. Your model isn't compatible with the version of llama.cpp being used by the web-ui.

See: https://github.com/oobabooga/text-generation-webui/issues/2020#issuecomment-1546656696

**Comment by asif-ansari** [comment]
You can try updating llama.cpp
1. goto conda environment by running the `cmd_windows.bat` (assuming you're on windows because, the path in the error looks like windows one)
2. uninstall existing llama.cpp `pip uninstall -y llama-cpp-python`
3. re-install the latest llama.cpp `pip install llama-cpp-python --no-cache-dir`

You can optionally enable llama.cpp cmake flags like LLAMA_NATIVE, LLAMA_LTO or thirdparty libraries like CUBLAS

`CMAKE_ARGS="-DLLAMA_CUBLAS=ON -DCUDAToolkit_ROOT=/opt/cuda -DCMAKE_CUDA_ARCHITECTURES=86 -DCMAKE_CUDA_COMPILER=/opt/cuda/bin/nvcc -DLLAMA_NATIVE=ON -DLLAMA_LTO=ON" FORCE_CMAKE=1 pip install llama-cpp-python --no-cache-dir`

**Comment by amaze28** [comment]
@asif-ansari Thank you!  Your suggestion worked to fix theabove error.  Quick question - I installed the llama_cpp...whl from the link you gave but is this the new llama.cpp released on 5/13/2023 that does the GPU offloading?  In the text-generation-webui I tried to enable the GPU but based on the token generation and what I was seeing in Windows Task Manager my 8GB Nvidia GTX1070 card was still not activated

**Comment by asif-ansari** [comment]
@amaze28 The link I gave was to release page and the latest one at the moment being v0.1.50
I am not sure about whether this version supports GPU offloading or not.
But, for the GPU to work you'll need to build llama.cpp with GPU flags enabled. I am on Linux with RTX3070 and I built llama.cpp with GPU flags ON and it IS using the GPU.

To build with GPU flags you can pass flags to CMake

For example, with -march=native and Link Time Optimisation ON
`CMAKE_ARGS="-DLLAMA_CUBLAS=ON -DLLAMA_NATIVE=ON -DLLAMA_LTO=ON" FORCE_CMAKE=1 pip install llama-cpp-python --no-cache-dir`


If CUDA toolkit is installed and all the environment variables are set, this should do the work. In my case I had to manually specify other flags also, leaving the command here for your reference (you may need to change the architecture for GTX1070 it should be 60):

`CMAKE_ARGS="-DLLAMA_CUBLAS=ON -DCUDAToolkit_ROOT=/opt/cuda -DCMAKE_CUDA_ARCHITECTURES=86 -DCMAKE_CUDA_COMPILER=/opt/cuda/bin/nvcc -DLLAMA_NATIVE=ON -DLLAMA_LTO=ON" FORCE_CMAKE=1 pip install llama-cpp-python --no-cache-dir`

**Comment by Zhengquan** [comment]
It works for me with the following steps on Apple M1:

- download the latest `GGMLv3` models from [here](https://huggingface.co/TheBloke/Wizard-Vicuna-7B-Uncensored-GGML/tree/main) 
- upgrade llama-cpp-python to `0.1.53`

      pip install llama-cpp-python==0.1.53

- Run with the new model
```bash
 python server.py --model Wizard-Vicuna-7B-Uncensored.ggmlv3.q4_0.bin
```

**Comment by NeoAnthropocene** [comment]
I had the same problem and installing with the below code solved it.
Unfortunately everytime I run the "start_windows.bat" file, it breaks sth and I'm trying to fix it.

```
pip uninstall -y llama-cpp-python
set CMAKE_ARGS="-DLLAMA_CUBLAS=on"
set FORCE_CMAKE=1
pip install llama-cpp-python==0.1.53 --no-cache-dir
```

**Comment by SunixLiu** [comment]
> You can try updating llama.cpp
> 
> 1. goto conda environment by running the `cmd_windows.bat` (assuming you're on windows because, the path in the error looks like windows one)
> 2. uninstall existing llama.cpp `pip uninstall -y llama-cpp-python`
> 3. re-install the latest llama.cpp from [here](https://github.com/abetlen/llama-cpp-python/releases)

I got same issue, it's working after upgrade the llama-cpp-python
