### ISSUE TITLE
× Encountered error while trying to install package. ╰─> quant-cuda

### ISSUE THREAD

**Issue by nb-ai-23** [oobabooga/text-generation-webui#2047]
### Describe the bug

Getting this when using new one click installer.  This UI used to work around a week ago. I feel like I've tried everything. The copy/paste below is from update_windows.bat but I get the same error when using the one click installer.

Any help would be appreciated, I feel like I've tried everything and I've been looking this up for days.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Getting this when using on click installer. 

oobabooga webui used to work but stopped a couple of days ago (I _was_ using the micromamba version)
- I deleted the folder 
- tried new one click installer 
- get this error
- uninstalled/reinstalled python/cuda/visual studio
- still getting error

### Logs

```shell
running build_ext
      C:\Users\<username>\AppData\Roaming\Python\Python310\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\ai\oobabooga_windows\text-generation-webui\repositories\GPTQ-for-LLaMa\setup.py", line 4, in <module>
          setup(
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\<username>\AppData\Roaming\Python\Python310\site-packages\wheel\bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
          self.build_extensions()
        File "C:\Users\<username>\AppData\Roaming\Python\Python310\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "C:\Users\<username>\AppData\Roaming\Python\Python310\site-packages\torch\utils\cpp_extension.py", line 383, in _check_cuda_version
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 49, in parse
          return Version(version)
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 264, in __init__
          match = self._regex.search(version)
      TypeError: expected string or bytes-like object
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for quant-cuda
  Running setup.py clean for quant-cuda
Failed to build quant-cuda
Installing collected packages: quant-cuda
  Attempting uninstall: quant-cuda
    Found existing installation: quant-cuda 0.0.0
    Uninstalling quant-cuda-0.0.0:
      Successfully uninstalled quant-cuda-0.0.0
  Running setup.py install for quant-cuda ... error
  error: subprocess-exited-with-error

  × Running setup.py install for quant-cuda did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7'
      running install
      D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      C:\Users\<username>\AppData\Roaming\Python\Python310\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\ai\oobabooga_windows\text-generation-webui\repositories\GPTQ-for-LLaMa\setup.py", line 4, in <module>
          setup(
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\command\install.py", line 68, in run
          return orig.install.run(self)
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\_distutils\command\install.py", line 698, in run
          self.run_command('build')
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
          self.build_extensions()
        File "C:\Users\<username>\AppData\Roaming\Python\Python310\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "C:\Users\<username>\AppData\Roaming\Python\Python310\site-packages\torch\utils\cpp_extension.py", line 383, in _check_cuda_version
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 49, in parse
          return Version(version)
        File "D:\ai\oobabooga_windows\installer_files\env\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 264, in __init__
          match = self._regex.search(version)
      TypeError: expected string or bytes-like object
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of quant-cuda
  Moving to d:\ai\oobabooga_windows\installer_files\env\lib\site-packages\quant_cuda-0.0.0.dist-info\
   from D:\ai\oobabooga_windows\installer_files\env\Lib\site-packages\~uant_cuda-0.0.0.dist-info
  Moving to d:\ai\oobabooga_windows\installer_files\env\lib\site-packages\quant_cuda.cp310-win_amd64.pyd
   from D:\ai\oobabooga_windows\installer_files\pip-uninstall-2huz6xwt\quant_cuda.cp310-win_amd64.pyd
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> quant-cuda

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

### System Info

```shell
win11
16 ram
i7 11th gen
3090 24gb vram
```

**Comment by nb-ai-23** [comment]
Issue resolved.

I had cpu version of pytorch installed.

Uninstalled pytoch and reinstalled correct version and it works perfectly

**Comment by nikolaiusa** [comment]
can you write what version and how to install?
