### ISSUE TITLE
Groupsize error with TheBloke/OpenAssistant-SFT-7-Llama-30B-GPTQ when character context is added

### ISSUE THREAD

**Issue by poisenbery** [oobabooga/text-generation-webui#2054]
### Describe the bug

The GPTQ 4bit model from TheBloke/OpenAssistant-SFT-7-Llama-30B-GPTQ works fine without the --chat arguement.
But as soon as --chat is enabled, and character context is introduced, it gives an error:

 weight = weight.reshape(-1, self.groupsize, weight.shape[2])
RuntimeError: shape '[-1, 1024, 6656]' is invalid for input of size 44302336

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1.) Manual install (linux)
2.) Manual install GPTQ
3.) run server.py --chat
4.) Use the chat function a few times so context is added, or load the example character
5.) It will error right away if character has context. If there is no context, it can generate 1-2 responses before giving the error

### Logs

```shell
(textgen) poisenbery@pop-os:~/AI_Stuff/text-generation-webui$ python server.py
INFO:Gradio HTTP request redirected to localhost :)
bin /home/poisenbery/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
INFO:Loading TheBloke_OpenAssistant-SFT-7-Llama-30B-GPTQ...
INFO:Found the following quantized model: models/TheBloke_OpenAssistant-SFT-7-Llama-30B-GPTQ/OpenAssistant-30B-epoch7-GPTQ-4bit-1024g.compat.no-act-order.safetensors
INFO:Loaded the model in 6.30 seconds.

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Output generated in 11.61 seconds (15.94 tokens/s, 185 tokens, context 16, seed 1531221872)
^C^CTraceback (most recent call last):
  File "/home/poisenbery/AI_Stuff/text-generation-webui/server.py", line 963, in <module>
    time.sleep(0.5)
KeyboardInterrupt

(textgen) poisenbery@pop-os:~/AI_Stuff/text-generation-webui$ python server.py --chat
INFO:Gradio HTTP request redirected to localhost :)
bin /home/poisenbery/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
INFO:Loading TheBloke_OpenAssistant-SFT-7-Llama-30B-GPTQ...
INFO:Found the following quantized model: models/TheBloke_OpenAssistant-SFT-7-Llama-30B-GPTQ/OpenAssistant-30B-epoch7-GPTQ-4bit-1024g.compat.no-act-order.safetensors
INFO:Loaded the model in 6.32 seconds.

INFO:Loading the extension "gallery"...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/home/poisenbery/AI_Stuff/text-generation-webui/modules/callbacks.py", line 73, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/home/poisenbery/AI_Stuff/text-generation-webui/modules/text_generation.py", line 263, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/poisenbery/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/poisenbery/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1485, in generate
    return self.sample(
  File "/home/poisenbery/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2524, in sample
    outputs = self(
  File "/home/poisenbery/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/poisenbery/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "/home/poisenbery/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/poisenbery/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 577, in forward
    layer_outputs = decoder_layer(
  File "/home/poisenbery/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/poisenbery/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/poisenbery/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/poisenbery/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 196, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "/home/poisenbery/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/poisenbery/AI_Stuff/text-generation-webui/repositories/GPTQ-for-LLaMa/quant.py", line 362, in forward
    weight = weight.reshape(-1, self.groupsize, weight.shape[2])
RuntimeError: shape '[-1, 1024, 6656]' is invalid for input of size 44302336
Output generated in 0.30 seconds (0.00 tokens/s, 0 tokens, context 146, seed 713051755)
```

### System Info

```shell
Linux: PopOS! 22.04 LTS
GPU: RTX 3090ti Nvidia
Browser: Firefox


I installed everything manually.
```

**Comment by Ph0rk0z** [comment]
I've not tried group size of 1024 yet and can't tell you if it works with classic forked GPTQ. You can try the triton one or the newer ones and report back. I will probably quantize something today and see what happens as well.
