### ISSUE TITLE
Failed to load silero_tts extension [ModuleNotFoundError]

### ISSUE THREAD

**Issue by retromoustache** [oobabooga/text-generation-webui#2063]
### Describe the bug

When attempting to load the Silero TTS extension module after modfying the webui.py launch parameter (by adding `--extension silero_tts`), the following error occurs: "**ModuleNotFoundError: No module named 'src.silero'**". 

Whilst the interface loads along with any other extensions such as Whisper (which loads successfully), this error prevents the loading of the Silero TTS extension.

**What I've tried:**
- `pip install -r requirements.txt` in the silero_tts extension folder
- doing a separate `pip install silero` (not through `cmd_windows.bat`)
- removing any cached copy of the silero package in `cache not found at C:\Users\Admin/.cache\torch\hub` to force a re-download

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

- Currently running this commit: ab08cf646543c72e35096094390a4a676fd5af72
- Add `--extension silero_tts` to `webui.py` (my full launch parameters is: `python server.py --chat --extension whisper_stt silero_tts` -- tried with and without --listen)
- PyTorch version: 2.0.0+cu117
- Python version: 3.10.11

### Logs

```shell
INFO:Loading the extension "silero_tts"...

Silero TTS cache not found at C:\Users\Admin/.cache\torch\hub. Attempting to download...
D:\Programs\oobaboogaAI\installer_files\env\lib\site-packages\torch\hub.py:286: UserWarning: You are about to download and run code from an untrusted repository. In a future release, this won't be allowed. To add the repository to your trusted list, change the command to {calling_fn}(..., trust_repo=False) and a command prompt will appear asking for an explicit confirmation of trust, or load(..., trust_repo=True), which will assume that the prompt is to be answered with 'yes'. You can also use load(..., trust_repo='check') which will only prompt for confirmation if the repo is not already trusted. This will eventually be the default behaviour
  warnings.warn(
Downloading: "https://github.com/snakers4/silero-models/zipball/master" to C:\Users\Admin/.cache\torch\hub\master.zip
ERROR:Failed to load the extension "silero_tts".
Traceback (most recent call last):
  File "D:\Programs\oobaboogaAI\text-generation-webui\modules\extensions.py", line 39, in load_extensions
    extension.setup()
  File "D:\Programs\oobaboogaAI\text-generation-webui\extensions\silero_tts\script.py", line 142, in setup
    model = load_model()
  File "D:\Programs\oobaboogaAI\text-generation-webui\extensions\silero_tts\script.py", line 54, in load_model
    model, example_text = torch.hub.load(repo_or_dir='snakers4/silero-models', model='silero_tts', language=params['language'], speaker=params['model_id'])
  File "D:\Programs\oobaboogaAI\installer_files\env\lib\site-packages\torch\hub.py", line 558, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "D:\Programs\oobaboogaAI\installer_files\env\lib\site-packages\torch\hub.py", line 584, in _load_local
    hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
  File "D:\Programs\oobaboogaAI\installer_files\env\lib\site-packages\torch\hub.py", line 98, in _import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Admin/.cache\torch\hub\snakers4_silero-models_master\hubconf.py", line 4, in <module>
    from src.silero import (
ModuleNotFoundError: No module named 'src.silero'
```

### System Info

```shell
Windows 10
Ryzen 5 5600X
NVIDIA GeForce RTX 3070 FE
32 GB RAM
```

**Comment by gitihobo** [comment]
same issue, any soluction?

**Comment by retromoustache** [comment]
Yes, I was tinkering around and found a working solution. 

1. Navigate to the `.cache\torch\hub\snakers4_silero-models_master` folder (see your error output for full path)
2. Move the `silero` folder out of the `src` directory and placed them in the root directory of the project (so it's like **.\snakers4_silero-models_master\silero**)
3. Open and edit the `hubconf.py` file to the following: 
```
import os
import sys

from silero import (
    silero_stt,
    silero_tts,
    silero_te,
)

__all__ = [
    "silero_stt",
    "silero_tts",
    "silero_te",
]

sys.path.append(os.path.dirname(__file__))
```
This dynamically changes the path. I removed it out of src since I get issues no matter how much I reconfigure the script.

5. Relaunch the web interface

This works, only thing is that the output whenever generating text using Silero enabled, has this printed in the logs which isn't a problem:
```
Silero TTS cache not found at C:\Users\Admin/.cache\torch\hub. Attempting to download...
Using cache found in C:\Users\Admin/.cache\torch\hub\snakers4_silero-models_master
```

**Comment by harlyh** [comment]
These errors appear in the lock because in reality the English language model download from seller fails with 403 Forbidden error.

Those who still have the model cached from earlier can use it. This is also everything by looking at your log snippet above.

Since I didn't have the model cashed, I had to do some trickery to download the model from silero and put it to the extension folder, after which I made some changes to go straight to loading it from local disc instead of trying to download it from torch hub all the time.

The en_v3 mother works absolutely fast on you, and gives me 117 different voices. 

At one point I Even generated samples with one on the same sentence using all voices and created per voice configs for those voices that didn't sound good with default speech settings. I haven't had a chance to look into whether this kind of usage is actually permissible or whether I could Make this modified silero-tts extension available for all

**Comment by gitihobo** [comment]
this is still relevant

**Comment by 1joshw** [comment]
this is still relevant


2023-10-01 11:23:00 ERROR:Failed to load the extension "silero_tts".
Traceback (most recent call last):
  File "F:\A1111\Chat\text-generation-webui-main\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "F:\A1111\Chat\text-generation-webui-main\extensions\silero_tts\script.py", line 9, in <module>
    from extensions.silero_tts import tts_preprocessor
  File "F:\A1111\Chat\text-generation-webui-main\extensions\silero_tts\tts_preprocessor.py", line 3, in <module>
    from num2words import num2words
ModuleNotFoundError: No module named 'num2words'

**Comment by HolgerBr65** [comment]
I have the same Error: 
2023-11-07 00:21:11 ERROR:Failed to load the extension "silero_tts".
Traceback (most recent call last):
  File "C:\Users\Brunken\Documents\Oobabooga\text-generation-webui-main\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "C:\Users\Brunken\Documents\Oobabooga\text-generation-webui-main\extensions\silero_tts\script.py", line 10, in <module>
    from extensions.silero_tts import tts_preprocessor
  File "C:\Users\Brunken\Documents\Oobabooga\text-generation-webui-main\extensions\silero_tts\tts_preprocessor.py", line 3, in <module>
    from num2words import num2words
ModuleNotFoundError: No module named 'num2words'

Elevenlabs extension works fine but Silero does not load. Thanks for help.

**Comment by Yametepower** [comment]
01:32:03-113955 INFO     Loading the extension "gallery"
01:32:03-118592 INFO     Loading the extension "silero_tts"
01:32:03-123607 ERROR    Could not import the requirements for 'silero_tts'. Make sure to install the requirements for
                         the extension.

                         Linux / Mac:

                         pip install -r extensions/silero_tts/requirements.txt --upgrade

                         Windows:

                         pip install -r extensions\silero_tts\requirements.txt --upgrade

                         If you used the one-click installer, paste the command above in the terminal window opened
                         after launching the cmd script for your OS.
01:32:03-130614 ERROR    Failed to load the extension "silero_tts".
Traceback (most recent call last):
  File "D:\Tools\AI-oobabooga\text-generation-webui\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "D:\Tools\AI-oobabooga\text-generation-webui\extensions\silero_tts\script.py", line 10, in <module>
    from extensions.silero_tts import tts_preprocessor
  File "D:\Tools\AI-oobabooga\text-generation-webui\extensions\silero_tts\tts_preprocessor.py", line 3, in <module>
    from num2words import num2words
ModuleNotFoundError: No module named 'num2words'


ive treid  pip install -r extensions\silero_tts\requirements.txt --upgrade in the main folder and it downloaded all the stuff but it still dose not work...

**Comment by armelvil** [comment]
Still broken here, also.

**Comment by andrianavony** [comment]
> 01:32:03-113955 INFO Loading the extension "gallery" 01:32:03-118592 INFO Loading the extension "silero_tts" 01:32:03-123607 ERROR Could not import the requirements for 'silero_tts'. Make sure to install the requirements for the extension.
> 
> ```
>                      Linux / Mac:
> 
>                      pip install -r extensions/silero_tts/requirements.txt --upgrade
> 
>                      Windows:
> 
>                      pip install -r extensions\silero_tts\requirements.txt --upgrade
> 
>                      If you used the one-click installer, paste the command above in the terminal window opened
>                      after launching the cmd script for your OS.
> ```
> 
> 01:32:03-130614 ERROR Failed to load the extension "silero_tts". Traceback (most recent call last): File "D:\Tools\AI-oobabooga\text-generation-webui\modules\extensions.py", line 36, in load_extensions exec(f"import extensions.{name}.script") File "", line 1, in File "D:\Tools\AI-oobabooga\text-generation-webui\extensions\silero_tts\script.py", line 10, in from extensions.silero_tts import tts_preprocessor File "D:\Tools\AI-oobabooga\text-generation-webui\extensions\silero_tts\tts_preprocessor.py", line 3, in from num2words import num2words ModuleNotFoundError: No module named 'num2words'
> 
> I've tried pip install -r extensions\silero_tts\requirements.txt --upgrade in the main folder and it downloaded all the stuff but it still dose not work...

I have the same issue

**Comment by AddzModz** [comment]
same here someone please help and fix this

**Comment by smileymerx** [comment]
Hi, I just wanted to activate silero_tts and get the same error. I manually installed the requirements.txt after the first error, but it didn't help.

My system is Linux Mint, AMD Ryzen 7 5800x3d, 64GB RAM, AMD Radeon 6900 XT 16GB.

<img width="2626" height="1232" alt="Image" src="https://github.com/user-attachments/assets/32769f9a-42be-40bd-970d-f9a0e38ab6fe" />
