### ISSUE TITLE
whisper_stt extension runs into `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

### ISSUE THREAD

**Issue by Yeecy-sketch** [oobabooga/text-generation-webui#2065]
### Describe the bug

The whisper_stt extension runs into a error when trying to use the microphone inside the browser. 
Tried Firefox and Ungoogled chromium. Error message seems to be similar to #1114.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Launch webui with `--chat --extension whisper_stt`
Navigate to the browser and use "Record from microphone" under whisper_stt
Error should occur

### Screenshot

![Screenshot_20230515_015049](https://github.com/oobabooga/text-generation-webui/assets/78103725/b0fe8e73-1ebc-4006-ae6e-ce2d4e56cfe6)

### Logs

```shell
(base) yeecy@debianpc:~/oobabooga_linux$ bash start_linux.sh 
INFO:Gradio HTTP request redirected to localhost :)
bin /home/yeecy/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
The following models are available:

1. Aitrepreneur_stable-vicuna-13B-GPTQ-4bit-128g
2. ausboss_WizardLM-13B-Uncensored-4bit-128g
3. CPU_anon8231489123_gpt4-x-alpaca-13b-native-4bit-128g
4. CUDA_anon8231489123_gpt4-x-alpaca-13b-native-4bit-128g
5. EleutherAI_pythia-1b-deduped
6. EleutherAI_pythia-2.8b-deduped
7. elinas_vicuna-13b-4bit
8. ggml-model-q4_2.bin
9. llama-7b
10. mayaeary_pygmalion-6b_dev-4bit-128g
11. mosaicml_mpt-7b-chat
12. mosaicml_mpt-7b-instruct
13. notstoic_OPT-13B-Erebus-4bit-128g
14. TheBloke_koala-7B-GPTQ-4bit-128g
15. TheBloke_wizardLM-7B-GPTQ
16. TheBloke_WizardLM-7B-uncensored-GPTQ
17. THUDM_chatglm-6b-int8
18. Vicuna_cpu
19. zicara_OPT-30B-Erebus-4bit-128g

Which one do you want to load? 1-19

10

INFO:Loading mayaeary_pygmalion-6b_dev-4bit-128g...
INFO:Found the following quantized model: models/mayaeary_pygmalion-6b_dev-4bit-128g/pygmalion-6b_dev-4bit-128g.safetensors
INFO:Loaded the model in 3.40 seconds.

INFO:Loading the extension "whisper_stt"...
INFO:Loading the extension "gallery"...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/home/yeecy/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/yeecy/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1191, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/home/yeecy/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1039, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/home/yeecy/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/components.py", line 2279, in preprocess
    sample_rate, data = processing_utils.audio_from_file(
  File "/home/yeecy/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/processing_utils.py", line 138, in audio_from_file
    audio = AudioSegment.from_file(filename)
  File "/home/yeecy/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/pydub/audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "/home/yeecy/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/pydub/utils.py", line 279, in mediainfo_json
    info = json.loads(output)
  File "/home/yeecy/oobabooga_linux/installer_files/env/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/yeecy/oobabooga_linux/installer_files/env/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/yeecy/oobabooga_linux/installer_files/env/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
```


### System Info

```shell
OS: Debian 11 Linux
GPU: Gigabyte Geforce RTX 3060 12G
RAM: 32GB DDR4
```

**Comment by robbie-cahill** [comment]
This appears to be an issue with the "Chat Style" selected. It went away for me when I switched to the `messenger` chat style/theme.

Also, be sure you have `ffmpeg` installed on your system or you'll get a different error.
