### ISSUE TITLE
Can't load Moss 4-bit model 

### ISSUE THREAD

**Issue by 631068264** [oobabooga/text-generation-webui#2070]
### Describe the bug

python server.py --trust-remote-code --listen --auto-devices --model moss-moon-003-sft-plugin-int4

```
INFO:Gradio HTTP request redirected to localhost :)
WARNING:trust_remote_code is enabled. This is dangerous.
bin /data/home/yaokj5/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
INFO:Loading moss-moon-003-sft-plugin-int4...
ERROR:The model could not be loaded because its type could not be inferred from its name.
ERROR:Please specify the type manually using the --model_type argument.
INFO:Loaded the model in 0.79 seconds.

Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
^CTraceback (most recent call last):
  File "/data/home/yaokj5/dl/apps/text-generation-webui/server.py", line 948, in <module>
    time.sleep(0.5)
KeyboardInterrupt


```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

-  I have install [https://github.com/oobabooga/text-generation-webui/blob/main/docs/GPTQ-models-(4-bit-mode).md]
-  put model to dir `models`
- run `python server.py --trust-remote-code --listen --auto-devices --model moss-moon-003-sft-plugin-int4`

### Logs

```shell
1
```

### System Info

```shell
1
```

**Comment by Ph0rk0z** [comment]
You tried with correct argument? 

ERROR:Please specify the type manually using the --model_type argument.

**Comment by Ph0rk0z** [comment]
Ok.. but model isn't llama.. it is moss. And rename pytorch_model.bin to something like moss-4bit.pt and see what happens.

**Comment by 631068264** [comment]
rename pytorch_model.bin to  moss-4bit.pt  and I don't know what is the model_type of moss

```
python server.py --trust-remote-code --listen --auto-devices --model moss-moon-003-sft-plugin-int4 --model_type opt
INFO:Gradio HTTP request redirected to localhost :)
WARNING:trust_remote_code is enabled. This is dangerous.
bin /data/home/yaokj5/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
INFO:Loading moss-moon-003-sft-plugin-int4...
INFO:Found the following quantized model: models/moss-moon-003-sft-plugin-int4/moss-4bit.pt
Traceback (most recent call last):
  File "/data/home/yaokj5/dl/apps/text-generation-webui/server.py", line 933, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/data/home/yaokj5/dl/apps/text-generation-webui/modules/models.py", line 159, in load_model
    model = load_quantized(model_name)
  File "/data/home/yaokj5/dl/apps/text-generation-webui/modules/GPTQ_loader.py", line 178, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.wbits, shared.args.groupsize, kernel_switch_threshold=threshold)
  File "/data/home/yaokj5/dl/apps/text-generation-webui/modules/GPTQ_loader.py", line 52, in _load_quant
    model = AutoModelForCausalLM.from_config(config, trust_remote_code=shared.args.trust_remote_code)
  File "/data/home/yaokj5/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 408, in from_config
    return model_class._from_config(config, **kwargs)
  File "/data/home/yaokj5/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1146, in _from_config
    model = cls(config, **kwargs)
  File "/data/home/yaokj5/.cache/huggingface/modules/transformers_modules/moss-moon-003-sft-plugin-int4/modeling_moss.py", line 608, in __init__
    self.quantize(config.wbits, config.groupsize)
  File "/data/home/yaokj5/.cache/huggingface/modules/transformers_modules/moss-moon-003-sft-plugin-int4/modeling_moss.py", line 732, in quantize
    from .quantization import quantize_with_gptq
  File "/data/home/yaokj5/.cache/huggingface/modules/transformers_modules/moss-moon-003-sft-plugin-int4/quantization.py", line 8, in <module>
    from .custom_autotune import *
ModuleNotFoundError: No module named 'transformers_modules.moss-moon-003-sft-plugin-int4.custom_autotune'
```

**Comment by Ph0rk0z** [comment]
So their script requires some import and it fails. It feels like they wrote their own little GPTQ there.. calling it autotune smells of triton.

I know autoGPTQ supports this model but not sure if that means you have to re-quantize with it and use it to load it too.

**Comment by d4n1elchen** [comment]
The AutoGPTQ support was dropped for some random reasons... https://github.com/oobabooga/text-generation-webui/pull/1668
