### ISSUE TITLE
load_in_8bit has more requirements than "half()"?

### ISSUE THREAD

**Issue by monsieurpooh** [oobabooga/text-generation-webui#2073]
### Describe the bug

I am trying to load a model in half precision and it seems the way to do it in oobabooga is to set load_in_8bit to true. This results in a lot of errors from the requirements needed such as bitsandbytes. In a barebones huggingface implementation, all that's needed is to simply say `modal.cuda().half()`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Call server.py with load_in_8bit set to true

### Logs

```shell
(C:\Max\oobabooga_windows_copy\installer_files\env) C:\Max\oobabooga_windows_copy\text-generation-webui>C:\Max\oobabooga_windows_copy\start_windows.bat
eloworld sys path debug1: server.py
eloworld sys path debug2: C:\Max\oobabooga_windows_copy\text-generation-webui
eloworld _utils debug1
eloworld _utils debug2
<function path at 0x00000265BF886EF0>
INFO:Gradio HTTP request redirected to localhost :)
bin C:\Max\oobabooga_windows_copy\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so
C:\Max\oobabooga_windows_copy\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
INFO:Loading EleutherAI_pythia-125m-deduped...
Traceback (most recent call last):
  File "C:\Max\oobabooga_windows_copy\text-generation-webui\server.py", line 956, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Max\oobabooga_windows_copy\text-generation-webui\modules\models.py", line 90, in load_model
    model = model.cuda()
  File "C:\Max\oobabooga_windows_copy\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\Max\oobabooga_windows_copy\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Max\oobabooga_windows_copy\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Max\oobabooga_windows_copy\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Max\oobabooga_windows_copy\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "C:\Max\oobabooga_windows_copy\installer_files\env\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

### System Info

```shell
Windows 10, NVIDIA RTX 2060S
```

**Comment by Ph0rk0z** [comment]
You got the wrong torch.
