### ISSUE TITLE
pip install llama-cpp-python

### ISSUE THREAD

**Issue by wilac-pv** [oobabooga/text-generation-webui#2075]
### Describe the bug

      llama.cpp:2686:36: warning: cast from type ‘const uint8_t* {aka const unsigned char*}’ to type ‘void*’ casts away qualifiers [-Wcast-qual]
                   kin3d->data = (void *) inp;
                                          ^
      llama.cpp:2690:36: warning: cast from type ‘const uint8_t* {aka const unsigned char*}’ to type ‘void*’ casts away qualifiers [-Wcast-qual]
                   vin3d->data = (void *) inp;
                                          ^
      make: *** [llama.o] Error 1
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/tmp/pip-build-env-2p95i1em/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 674, in setup
          cmkr.make(make_args, install_target=cmake_install_target, env=env)
        File "/tmp/pip-build-env-2p95i1em/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 696, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
        File "/tmp/pip-build-env-2p95i1em/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 741, in make_impl
          raise SKBuildError(msg)

      An error occurred while building with CMake.
        Command:
          /tmp/pip-build-env-2p95i1em/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake --build . --target install --config Release --
        Install target:
          install
        Source directory:
          /tmp/pip-install-d27waoub/llama-cpp-python_e7a11e15c3fc4de9b16a856b09061189
        Working directory:
          /tmp/pip-install-d27waoub/llama-cpp-python_e7a11e15c3fc4de9b16a856b09061189/_skbuild/linux-x86_64-3.10/cmake-build
      Please check the install target is valid and see CMake's output for more information.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

这个是什么问题导致的？

### Logs

```shell
pip install llama-cpp-python
```

### System Info

```shell
pip install llama-cpp-python
```

**Comment by ELind77** [comment]
I had the same issue.  Fixed by updating my gcc version to gcc-8.  
https://askubuntu.com/questions/466651/how-do-i-use-the-latest-gcc-on-ubuntu

**Comment by spaceman4717** [comment]
Referencing here(https://www.reddit.com/r/LocalLLaMA/comments/12yzldp/failed_building_wheel_for_llamacpppython/)

for me on arch do:
to install build essentials
```
sudo pacman -Sy base-devel 
```

then rerun

'''
pip install llama-cpp-python 
'''

**Comment by itsmeherefolks** [comment]
> ```
> sudo pacman -Sy base-devel 
> ```

Thank's works for me on Manjaro
