### ISSUE TITLE
Evaluation perplexity doesn't work with loaded 4-bit Lora

### ISSUE THREAD

**Issue by janvarev** [oobabooga/text-generation-webui#2077]
### Describe the bug

Evaluation perplexity doesn't work with loaded 4-bit Lora

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Load 4 bit Lora
2. Run Evaluate loaded model on some text fail

Fail.

Evalution on clean model (without Lora) works ok.

### Logs

```shell
0%|                                                                                          | 0/120 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\gradio\routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 930, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 491, in async_iteration
    return next(iterator)
  File "C:\Software\text-gen-webui\text-generation-webui\modules\evaluate.py", line 95, in calculate_perplexity
    outputs = shared.model(input_ids, labels=target_ids)
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\peft\peft_model.py", line 678, in forward
    return self.base_model(
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 577, in forward
    layer_outputs = decoder_layer(
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 196, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Software\text-gen-webui\text-generation-webui\repositories\alpaca_lora_4bit\monkeypatch\peft_tuners_lora_monkey_patch.py", line 66, in forward
    self.lora_A[self.active_adapter](self.lora_dropout[self.active_adapter](x))
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Float but found Half
```

### System Info

```shell
Windows 11
GPU: 3070 Ti Mobile, 8 Gb VRAM
```

**Comment by Ph0rk0z** [comment]
Disable model.half. I get no other difference when I did this on my own fork.


```
def load_model_llama(model_name):
    config_path = str(Path(f'{shared.args.model_dir}/{model_name}'))
    model_path = str(find_quantized_model_file(model_name))
    model, tokenizer = load_llama_model_4bit_low_ram(config_path, model_path, groupsize=shared.args.groupsize, is_v1_model=False)
    for n, m in model.named_modules():
        if isinstance(m, Autograd4bitQuantLinear) or isinstance(m, Linear4bitLt):
            if m.is_v1_model:
                m.zeros = m.zeros.half()
            m.scales = m.scales.half()
            m.bias = m.bias.half()

    autograd_4bit.use_new = True
    autograd_4bit.auto_switch = True

    #model.half()
    wrapper = AMPWrapper(model)
    wrapper.apply_generate()

    return model, tokenizer
```

**Comment by janvarev** [comment]
@Ph0rk0z 
Doesn't work for me :( seems to be the same error.

```
  0%|                                                                                          | 0/240 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\gradio\routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 930, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 491, in async_iteration
    return next(iterator)
  File "C:\Software\text-gen-webui\text-generation-webui\modules\evaluate.py", line 95, in calculate_perplexity
    outputs = shared.model(input_ids, labels=target_ids)
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\peft\peft_model.py", line 678, in forward
    return self.base_model(
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 577, in forward
    layer_outputs = decoder_layer(
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 196, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Software\text-gen-webui\text-generation-webui\repositories\alpaca_lora_4bit\monkeypatch\peft_tuners_lora_monkey_patch.py", line 66, in forward
    self.lora_A[self.active_adapter](self.lora_dropout[self.active_adapter](x))
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Software\text-gen-webui\installer_files\env\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Float but found Half
```

**Comment by Ph0rk0z** [comment]
Something else is setting model.half() perhaps in load_llama_model_4bit_low_ram

Did you try the PIP based PR? https://github.com/oobabooga/text-generation-webui/pull/1333

On my fork it was enough to disable model.half for it to do perplexity properly. Now the code/kernel for 4bit_lora has changed. You can also try disabling the amp wrapper completely.

**Comment by janvarev** [comment]
Seems you are correct about model.half(), but sorry, now have a no time to dig into it. 
This bug doesn't affect me seriously, but it'll be good to fix it.

**Comment by Simplegram** [comment]
Hello, I have the same issue. Is there a fix?
