### ISSUE TITLE
llama.cpp int4 model generate error

### ISSUE THREAD

**Issue by big-thousand** [oobabooga/text-generation-webui#2079]
### Describe the bug

use llama.cpp int4 model generate text error.
after first error, it wll only generate one or two token

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

on main brach
use llama.cpp int4 model

### Screenshot

<img width="1263" alt="截屏2023-05-15 23 25 59" src="https://github.com/oobabooga/text-generation-webui/assets/114633619/dbabe813-4d7e-4876-a0e1-107e967f8bd7">
<img width="637" alt="截屏2023-05-15 23 35 24" src="https://github.com/oobabooga/text-generation-webui/assets/114633619/f6a1f782-2eb9-49e0-b8ba-67a90c8d07dd">

### Logs

```shell
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/gradio/routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/gradio/blocks.py", line 1193, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/gradio/blocks.py", line 930, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gitpod/.pyenv/versions/3.11.1/lib/python3.11/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gitpod/.pyenv/versions/3.11.1/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/gitpod/.pyenv/versions/3.11.1/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/gradio/utils.py", line 491, in async_iteration
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/workspace/text-generation-webui/modules/text_generation.py", line 150, in generate_reply_wrapper
    for reply in generate_reply(question, state, eos_token, stopping_strings, is_chat=False):
  File "/workspace/text-generation-webui/modules/text_generation.py", line 184, in generate_reply
    for reply in generate_func(question, original_question, seed, state, eos_token, stopping_strings, is_chat=is_chat):
  File "/workspace/text-generation-webui/modules/text_generation.py", line 316, in generate_reply_custom
    new_tokens = len(encode(original_question + reply)[0]) - original_tokens
                                                ^^^^^
UnboundLocalError: cannot access local variable 'reply' where it is not associated with a value

```

### System Info

```shell
gitpod
```

**Comment by atanida** [comment]
Same here, in all cpp models so far, only happens when generating Chinese text though. 

> text-generation-webui\modules\text_generation.py", line 316, in
>  generate_reply_custom
>     new_tokens = len(encode(original_question + reply)[0]) - original_tokens
> UnboundLocalError: local variable 'reply' referenced before assignment

**Comment by stignarnia** [comment]
Thank you so much for the idea of lowering max new tokens, I always used this on one PC and I just moved to another so I thought something went wrong there. Turns out this new PC (AMD 5000 instead of Intel 10) can handle less new tokens but is also 3 times faster than what I had so I guess fine
