### ISSUE TITLE
The AI is looking for the txt2img script in the wrong directory

### ISSUE THREAD

**Issue by Elia1995-Official** [oobabooga/text-generation-webui#2084]
### Describe the bug

Hello, I've enabled the sd_api_pictures extension so I could have my chat bot generate and send me pictures through Automatic1111's stable diffusion, which I am running on a separate Windows terminal.

However, when it tries to generate a picture, the console returns a 404 error because it looks for the txt2img script in the wrong directory (I don't have any "sdapi" directory in my automatic1111 webui folder)

I get the following error in the cmd:

raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:7860/sdapi/v1/txt2img

I couldn't find anything related to this issue online, so here I am opening this issue, hoping that I've described the problem correctly.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run Automtic1111's webui and oobabooga AI, enable sd_api_pictures from the "Interface mode" tab, after properly configuring the parameters on the bottom of the page, ask the AI to "send a picture".

### Logs

```shell
Traceback (most recent call last):
  File "F:\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "F:\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 930, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\AI\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\AI\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\AI\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 491, in async_iteration
    return next(iterator)
  File "F:\AI\oobabooga_windows\text-generation-webui\modules\chat.py", line 307, in generate_chat_reply_wrapper
    for history in generate_chat_reply(text, state, regenerate, _continue):
  File "F:\AI\oobabooga_windows\text-generation-webui\modules\chat.py", line 301, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue):
  File "F:\AI\oobabooga_windows\text-generation-webui\modules\chat.py", line 230, in chatbot_wrapper
    visible_reply = apply_extensions("output", visible_reply)
  File "F:\AI\oobabooga_windows\text-generation-webui\modules\extensions.py", line 139, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "F:\AI\oobabooga_windows\text-generation-webui\modules\extensions.py", line 58, in _apply_string_extensions
    text = getattr(extension, function_name)(text)
  File "F:\AI\oobabooga_windows\text-generation-webui\extensions\sd_api_pictures\script.py", line 212, in output_modifier
    string = get_SD_pictures(string) + "\n" + text
  File "F:\AI\oobabooga_windows\text-generation-webui\extensions\sd_api_pictures\script.py", line 151, in get_SD_pictures
    response.raise_for_status()
  File "F:\AI\oobabooga_windows\installer_files\env\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:7860/sdapi/v1/txt2img
```

### System Info

```shell
Microsoft Windows 11 Enterprise Insider Preview, PNY NVIDIA RTX 4090 24GB, 128 GB of DDR4 RAM, Intel i9-12900KS
```

**Comment by dmeleedy** [comment]
I am getting the same issue.

Prompting the image generator via the API on http://127.0.0.1:7860...
Output generated in 5.52 seconds (2.54 tokens/s, 14 tokens, context 1255, seed 2091659181)
Traceback (most recent call last):
  File "/Users/dmeleedy/Library/Python/3.9/lib/python/site-packages/gradio/routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/dmeleedy/Library/Python/3.9/lib/python/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/Users/dmeleedy/Library/Python/3.9/lib/python/site-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/Users/dmeleedy/Library/Python/3.9/lib/python/site-packages/gradio/utils.py", line 339, in async_iteration
    return await iterator.__anext__()
  File "/Users/dmeleedy/Library/Python/3.9/lib/python/site-packages/gradio/utils.py", line 332, in __anext__
    return await anyio.to_thread.run_sync(
  File "/Users/dmeleedy/Library/Python/3.9/lib/python/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/dmeleedy/Library/Python/3.9/lib/python/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/dmeleedy/Library/Python/3.9/lib/python/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/dmeleedy/Library/Python/3.9/lib/python/site-packages/gradio/utils.py", line 315, in run_sync_iterator_async
    return next(iterator)
  File "/Users/dmeleedy/text-generation-webui/modules/chat.py", line 307, in generate_chat_reply_wrapper
    for history in generate_chat_reply(text, state, regenerate, _continue):
  File "/Users/dmeleedy/text-generation-webui/modules/chat.py", line 301, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue):
  File "/Users/dmeleedy/text-generation-webui/modules/chat.py", line 230, in chatbot_wrapper
    visible_reply = apply_extensions("output", visible_reply)
  File "/Users/dmeleedy/text-generation-webui/modules/extensions.py", line 183, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "/Users/dmeleedy/text-generation-webui/modules/extensions.py", line 58, in _apply_string_extensions
    text = getattr(extension, function_name)(text)
  File "/Users/dmeleedy/text-generation-webui/extensions/sd_api_pictures/script.py", line 212, in output_modifier
    string = get_SD_pictures(string) + "\n" + text
  File "/Users/dmeleedy/text-generation-webui/extensions/sd_api_pictures/script.py", line 151, in get_SD_pictures
    response.raise_for_status()
  File "/Users/dmeleedy/Library/Python/3.9/lib/python/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:7860/sdapi/v1/txt2img

**Comment by carlosgalveias** [comment]
I had the same issue but then I realized that I wasn't starting stable diffusion with the --api option. Once I did that it solved it.

**Comment by dan4in** [comment]
i just returned to this webui after some time and after i installed everything i found out the sdapi doesn't work anymore it used to work before now i get this error `Requesting Auto1111 to re-load last checkpoint used...
Traceback (most recent call last):
  File "X:\Auto-TEXT-WEBUI\assnotworking\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "X:\Auto-TEXT-WEBUI\assnotworking\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "X:\Auto-TEXT-WEBUI\assnotworking\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "X:\Auto-TEXT-WEBUI\assnotworking\installer_files\env\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "X:\Auto-TEXT-WEBUI\assnotworking\installer_files\env\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "X:\Auto-TEXT-WEBUI\assnotworking\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "X:\Auto-TEXT-WEBUI\assnotworking\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "X:\Auto-TEXT-WEBUI\assnotworking\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "X:\Auto-TEXT-WEBUI\assnotworking\installer_files\env\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "X:\Auto-TEXT-WEBUI\assnotworking\text-generation-webui\modules\chat.py", line 299, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, shared.history, state, regenerate, _continue, loading_message=True)):
  File "X:\Auto-TEXT-WEBUI\assnotworking\text-generation-webui\modules\chat.py", line 284, in generate_chat_reply
    for history in chatbot_wrapper(text, history, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "X:\Auto-TEXT-WEBUI\assnotworking\text-generation-webui\modules\chat.py", line 244, in chatbot_wrapper
    output['visible'][-1][1] = apply_extensions("output", output['visible'][-1][1])
  File "X:\Auto-TEXT-WEBUI\assnotworking\text-generation-webui\modules\extensions.py", line 193, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "X:\Auto-TEXT-WEBUI\assnotworking\text-generation-webui\modules\extensions.py", line 58, in _apply_string_extensions
    text = getattr(extension, function_name)(text)
  File "X:\Auto-TEXT-WEBUI\assnotworking\text-generation-webui\extensions\sd_api_pictures\script.py", line 216, in output_modifier
    string = get_SD_pictures(string) + "\n" + text
  File "X:\Auto-TEXT-WEBUI\assnotworking\text-generation-webui\extensions\sd_api_pictures\script.py", line 134, in get_SD_pictures
    give_VRAM_priority('SD')
  File "X:\Auto-TEXT-WEBUI\assnotworking\text-generation-webui\extensions\sd_api_pictures\script.py", line 52, in give_VRAM_priority
    response.raise_for_status()
  File "X:\Auto-TEXT-WEBUI\assnotworking\installer_files\env\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:7860/sdapi/v1/reload-checkpoint`

and sometimes it says like this `    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:7860/sdapi/v1/unload-checkpoint`

and when this error appears it will ask me to load a model even tho i had loaded it and was talking to the ai ! this is the error

`2023-07-02 13:59:21 ERROR:No model is loaded! Select one in the Model tab.`

after i load it and try to get an image with the sdapi same thing happens forced to reload a model everytime

`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:7860/sdapi/v1/reload-checkpoint
2023-07-02 14:01:23 ERROR:No model is loaded! Select one in the Model tab.`

no idea what to do looks like either the stable diffusion or the text generation is not playing nice

**Comment by RiversKosmos** [comment]
I am still having this issue as text2image isn't showing up 

![image](https://github.com/oobabooga/text-generation-webui/assets/143301596/ff97a30c-d293-45ca-b0d7-2d29dec7b28f)

I am also getting this error as well. 

 File "C:\Users\natha\anaconda3\envs\textgen\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:7861/sdapi/v1/reload-checkpoint

**Comment by jianmomo** [comment]
我也碰到了这样的错误，请问有什么解决办法吗？

**Comment by inventwithdean** [comment]
In the Generation parameters of sd_api_pictures, try replacing Sampling method "DPM++ 2M Karras" with "DPM++ 2M" only, as now, there is another option of Schedule type. Doing this got rid of Client 404 error on my side and my AI can generate images now :)
![image](https://github.com/oobabooga/text-generation-webui/assets/106145602/a1113639-280e-476d-8d42-4255f7a169a9)

**Comment by christopherquenneville** [comment]
> In the Generation parameters of sd_api_pictures, try replacing Sampling method "DPM++ 2M Karras" with "DPM++ 2M" only, because as of now, there is another option to set Schedule type. Defining it all in Sampling Method name won't work. Doing this got rid of Client 404 error on my side and my AI can generate images now :) ![image](https://private-user-images.githubusercontent.com/106145602/324266477-a1113639-280e-476d-8d42-4255f7a169a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwOTY2MzEsIm5iZiI6MTcxNjA5NjMzMSwicGF0aCI6Ii8xMDYxNDU2MDIvMzI0MjY2NDc3LWExMTEzNjM5LTI4MGUtNDc2ZC04ZDQyLTQyNTVmN2ExNjlhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQwNTI1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmM3OThiNzMyNWIzYTk3MjRhMGNjOTg3MGM3MmVkZTQ5MzdiNzg4NjJmNzAxNDYyNzM2ODJjYmUzYmQyNjA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a7U4UzMrGI1yU_zS3QzHzk-7bm_Ky7F4lbMziCUHf2s)

This resolved my issue
