### ISSUE TITLE
Is there a wiki for superbooga?

### ISSUE THREAD

**Issue by bbecausereasonss** [oobabooga/text-generation-webui#2085]
### Describe the bug

Can't seem to get it to work.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Use superbooga

### Logs

```shell
Traceback (most recent call last):
  File "/home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "/home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 930, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/utils.py", line 491, in async_iteration
    return next(iterator)
  File "/home/perplexity/text-generation-webui/modules/chat.py", line 307, in generate_chat_reply_wrapper
    for history in generate_chat_reply(text, state, regenerate, _continue):
  File "/home/perplexity/text-generation-webui/modules/chat.py", line 301, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue):
  File "/home/perplexity/text-generation-webui/modules/chat.py", line 193, in chatbot_wrapper
    stopping_strings = get_stopping_strings(state)
  File "/home/perplexity/text-generation-webui/modules/chat.py", line 128, in get_stopping_strings
    state['turn_template'].split('<|user-message|>')[1].split('<|bot|>')[0] + '<|bot|>',
IndexError: list index out of range
```

### System Info

```shell
Chrome, Latest Win11, Latest Commit
```

**Comment by n00mkrad** [comment]
You need to load an instruct template (Alpaca should be fine for most models) to fix this.

Chat Settings -> Instruction template

I think there's a bug right now where this isn't saved/loaded by default, causing an error because the code tries to insert something into an empty template.

**Comment by truedat101** [comment]
This was extremely insightful in understanding how to use this feature: (the original concept pull request) https://github.com/oobabooga/text-generation-webui/pull/1548
