### ISSUE TITLE
windows one click installation error

### ISSUE THREAD

**Issue by profsher** [oobabooga/text-generation-webui#2104]
i followed one click installation in my windows 10. it shows error: Traceback (most recent call last):
  File "C:\Users\dell\Downloads\oobabooga_windows\text-generation-webui\download-model.py", line 19, in <module>
    import tqdm
ModuleNotFoundError: No module named 'tqdm'
Traceback (most recent call last):
  File "C:\Users\dell\Downloads\oobabooga_windows\text-generation-webui\server.py", line 21, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

i search issue section, can't find proper solution. i didn't find any micromamba-command.bat file. please help.

**Comment by ramzeez88** [comment]
do you run through cmd_windows.bat ?

**Comment by profsher** [comment]
> 

No, i double click start_windows.bat file. please tell me details about how to run through cmd_windows.bat

**Comment by mvergaraq** [comment]
same issue on mac intel

**Comment by B34STW4RS** [comment]
Yup just tried installing it on windows and it just doesn't do anything after attempting to load the model, says done, any key to continue...

**Comment by ramzeez88** [comment]
> > 
> 
> No, i double click start_windows.bat file. please tell me details about how to run through cmd_windows.bat

Do a full uninstall first. Keep your models safe. Install ooba again. Open cmd_windows.bat then in the new like after it's has loaded type start_windows.bat

**Comment by B34STW4RS** [comment]
Figured out my issue, was trying to load an incompatible model thus causing the launcher to silently fail.

**Comment by profsher** [comment]
> > > 
> > 
> > 
> > No, i double click start_windows.bat file. please tell me details about how to run through cmd_windows.bat
> 
> Do a full uninstall first. Keep your models safe. Install ooba again. Open cmd_windows.bat then in the new line after it's has loaded type start_windows.bat

same error

**Comment by karehto** [comment]
> Figured out my issue, was trying to load an incompatible model thus causing the launcher to silently fail.

How did you fix it? I am new at all this and i am getting the same error.

**Comment by aicoder2048** [comment]
I have the same error, and I am trying to install the missing modules/packages using pip mannually. But which venv to activate before pip install missing packages? Pls help! thanks
