### ISSUE TITLE
Elevenlabs TTS extension throwing TypeError on new install

### ISSUE THREAD

**Issue by PixelDJ** [oobabooga/text-generation-webui#2105]
### Describe the bug

I have tried installing in Windows and in Linux. No errors during the install.

When I enable the elevenlabs_tts extension, I get the following error and the webui quits:
```
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Closing server running on port: 7860
INFO:Loading the extension "gallery"...
INFO:Loading the extension "whisper_stt"...
INFO:Loading the extension "elevenlabs_tts"...
Traceback (most recent call last):
  File "/home/pixel/oobabooga_linux/text-generation-webui/server.py", line 984, in <module>
    create_interface()
  File "/home/pixel/oobabooga_linux/text-generation-webui/server.py", line 882, in create_interface
    extensions_module.create_extensions_block()
  File "/home/pixel/oobabooga_linux/text-generation-webui/modules/extensions.py", line 157, in create_extensions_block
    extension.ui()
  File "/home/pixel/oobabooga_linux/text-generation-webui/extensions/elevenlabs_tts/script.py", line 126, in ui
    voices = refresh_voices()
  File "/home/pixel/oobabooga_linux/text-generation-webui/extensions/elevenlabs_tts/script.py", line 22, in refresh_voices
    your_voices = elevenlabs.voices(api_key=params['api_key'])
TypeError: voices() got an unexpected keyword argument 'api_key'

Done!
```

I do not see a place to enter the api key, as the program exits as soon as I enable the extension.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Install webui fresh using any method (I tried Windows, Linux one click installers as well as the linux manual install).
2. Enable elevenlabs_tts extension
3. Click button to apply settings and restart webui

### Logs

```shell
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Closing server running on port: 7860
INFO:Loading the extension "gallery"...
INFO:Loading the extension "whisper_stt"...
INFO:Loading the extension "elevenlabs_tts"...
Traceback (most recent call last):
  File "/home/pixel/oobabooga_linux/text-generation-webui/server.py", line 984, in <module>
    create_interface()
  File "/home/pixel/oobabooga_linux/text-generation-webui/server.py", line 882, in create_interface
    extensions_module.create_extensions_block()
  File "/home/pixel/oobabooga_linux/text-generation-webui/modules/extensions.py", line 157, in create_extensions_block
    extension.ui()
  File "/home/pixel/oobabooga_linux/text-generation-webui/extensions/elevenlabs_tts/script.py", line 126, in ui
    voices = refresh_voices()
  File "/home/pixel/oobabooga_linux/text-generation-webui/extensions/elevenlabs_tts/script.py", line 22, in refresh_voices
    your_voices = elevenlabs.voices(api_key=params['api_key'])
TypeError: voices() got an unexpected keyword argument 'api_key'

Done!
```

### System Info

```shell
Windows 11 22H2 / WSL with Debian
RTX 3090
```

**Comment by PixelDJ** [comment]
Looks like this was an issue here #2097 and has just been merged. Closing this.
