### ISSUE TITLE
Key Error: 'no-mmap'

### ISSUE THREAD

**Issue by Prinnny** [oobabooga/text-generation-webui#2106]
Error code: 

Traceback (most recent call last):
  File "C:\Users\Yayat\OneDrive\Desktop\oobabooga_windows\text-generation-webui\server.py", line 962, in <module>
    update_model_parameters(model_settings, initial=True)  # hijacking the command-line arguments
  File "C:\Users\Yayat\OneDrive\Desktop\oobabooga_windows\text-generation-webui\server.py", line 206, in update_model_parameters
    if initial and vars(shared.args)[element] != vars(shared.args_defaults)[element]:
KeyError: 'no-mmap'

Every time I fresh install oobabooga (with Windows once click installation) and run it 3x, the 4th onwards start-up has this issue and requires another fresh install.

**Comment by oobabooga** [comment]
Fixed here

https://github.com/oobabooga/text-generation-webui/commit/5cd6dd4287edd2e22a6175e1263b78b2345e2e09

Make sure to delete the file models/config-user.yaml after updating. Then this error shouldn't happen again
