### ISSUE TITLE
ImportError: cannot import name 'themes' from partially initialized module 'gradio'

### ISSUE THREAD

**Issue by BlacKnightZer0** [oobabooga/text-generation-webui#2111]
### Describe the bug

I've been trying to get Oobabooga Text Generation WebUI working, but I encountered this problem at the end of the process. I have already tried to update gradio to the latest version using "pip install -U gradio" , but the problem is unchanged. Below is the traceback code that is generated when I try to run the start_windows.bat file in the Oobabooga folder.

INFO:Gradio HTTP request redirected to localhost :)
Traceback (most recent call last):
File "C:\Users\danie\Downloads\oobabooga_windows\text-generation-webui\server.py", line 21, in
import gradio as gr
File "C:\Users\danie\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\gradio_init_.py", line 3, in
import gradio.components as components
File "C:\Users\danie\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\gradio\components.py", line 53, in
from gradio.blocks import Block, BlockContext
File "C:\Users\danie\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 25, in
from gradio import (
ImportError: cannot import name 'themes' from partially initialized module 'gradio' (most likely due to a circular import) (C:\Users\danie\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\gradio_init_.py)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

After completing installation of oobabooga (using the file start_windows.bat) and installing a model, whenever I try to run start_windows.bat now, it just gives me the traceback code in the above description.

### Screenshot

![Screenshot 2023-05-14 223452](https://github.com/oobabooga/text-generation-webui/assets/133618052/6ddfd9a2-9988-4592-88b5-a64cfa455bf1)

### Logs

```shell
INFO:Gradio HTTP request redirected to localhost :)
Traceback (most recent call last):
File "C:\Users\danie\Downloads\oobabooga_windows\text-generation-webui\server.py", line 21, in
import gradio as gr
File "C:\Users\danie\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\gradio_init_.py", line 3, in
import gradio.components as components
File "C:\Users\danie\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\gradio\components.py", line 53, in
from gradio.blocks import Block, BlockContext
File "C:\Users\danie\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 25, in
from gradio import (
ImportError: cannot import name 'themes' from partially initialized module 'gradio' (most likely due to a circular import) (C:\Users\danie\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\gradio_init_.py)
```

### System Info

```shell
Microsoft Surface Pro 8 (Intel Iris Xe Graphics)
Windows 11
```

**Comment by BlacKnightZer0** [comment]
I've decided that this issue is most likely impossible to fix with my current computer. I presume that it is because I am trying to run in CPU mode a model that definitely needs a GPU to run. After reinstalling oobabooga, I got a different error, where it said I ran out of RAM, among other things. At any rate, I'll try running a smaller model with lower requirements.
