### ISSUE TITLE
one click install mac error "Preparing metadata (pyproject.toml) did not run successfully."

### ISSUE THREAD

**Issue by mvergaraq** [oobabooga/text-generation-webui#2117]
### Describe the bug

On Mac Intel (OS: Mojave), I'm getting this error log at the end of the installation (See Logs)

Then, when I try executing the "start" file again I get these errors "No module named 'tqdm'" and "No module named 'gradio'". After installing both modules via pip, it still throws the same errors.

### Is there an existing issue for this?

- [X] I have searched the existing issues
- There is someone having the same issue on Windows but thought I might post it for Mac in case there are different solutions

### Reproduction

Just execute "start" on MacOS Intel with Mojave

### Logs

```shell
After first installation:

Collecting orjson
  Downloading orjson-3.8.12.tar.gz (669 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 669.2/669.2 kB 1.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
      
      Checking for Rust toolchain....
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Command '. "/Downloads/oobabooga_macos/installer_files/conda/etc/profile.d/conda.sh" && conda activate "/Downloads/oobabooga_macos/installer_files/env" && python -m pip install -r requirements.txt --upgrade' failed with exit status code '1'. Exiting...


And when running start again:

Traceback (most recent call last):
  File "/Downloads/oobabooga_macos/text-generation-webui/download-model.py", line 19, in <module>
    import tqdm
ModuleNotFoundError: No module named 'tqdm'
Traceback (most recent call last):
  File "/Downloads/oobabooga_macos/text-generation-webui/server.py", line 21, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
```

### System Info

```shell
Intel Macbook MacOS Mojave
```

**Comment by Kolesar** [comment]
Same error!
