### ISSUE TITLE
RuntimeError: expected scalar type Half but found Float when training llama in 8 bit mode

### ISSUE THREAD

**Issue by guyman624** [oobabooga/text-generation-webui#2119]
### Describe the bug

RuntimeError: expected scalar type Half but found Float error when trying to train LoRa on llama

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

- Create new Docker Compose instance
- Load llama-7b-hf model and check load-in-8bit
- Go to training tab
- set raw data source and name and click generate

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/82007920/64498962-d568-40c5-8b73-ce64c780c1b4)

### Logs

```shell
INFO:Loading Neko-Institute-of-Science_LLaMA-7B-HF...
Loading checkpoint shards: 100% 2/2 [00:06<00:00,  3.30s/it]
INFO:Loaded the model in 7.13 seconds.

INFO:Loading raw text file dataset...
INFO:Getting model ready...
INFO:Prepping for training...
INFO:Creating LoRA model...
INFO:Starting training...
/app/venv/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py:318: UserWarning: MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
Exception in thread Thread-4 (threaded_run):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/modules/training.py", line 413, in threaded_run
    trainer.train()
  File "/app/venv/lib/python3.10/site-packages/transformers/trainer.py", line 1664, in train
    return inner_training_loop(
  File "/app/venv/lib/python3.10/site-packages/transformers/trainer.py", line 1940, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/app/venv/lib/python3.10/site-packages/transformers/trainer.py", line 2745, in training_step
    self.scaler.scale(loss).backward()
  File "/app/venv/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/app/venv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/app/venv/lib/python3.10/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/app/venv/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 157, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/app/venv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/app/venv/lib/python3.10/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/app/venv/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 476, in backward
    grad_A = torch.matmul(grad_output, CB).view(ctx.grad_shape).to(ctx.dtype_A)
RuntimeError: expected scalar type Half but found Float
INFO:Training complete, saving...
INFO:Training complete!
```

### System Info

```shell
Debian Stable 11.7.0
NVidia Tesla P40 24GB
Intel Core i7-6700
8GB DDR4
```

**Comment by Ph0rk0z** [comment]
On this card consider training in 4-bit. In 8bit you need to patch bnb to not NAN on pascal https://github.com/TimDettmers/bitsandbytes/pull/335

It still runs sort of half speed in 8-bit. You may also want to try the newest BnB from source because TD made some big changes and closed all PRs.

**Comment by Ph0rk0z** [comment]
I ran tests and I don't get this error.. just training is slow. Hence I say do it in 4bits.

**Comment by guyman624** [comment]
> I ran tests and I don't get this error.. just training is slow. Hence I say do it in 4bits.

Yeah, I ended up picking a smaller model and its working fine in 4bit mode. Even llama 7b is too big to train in 4 bit mode on 24gb vram

**Comment by Ph0rk0z** [comment]
What? I am training 13b right now on 3090.

**Comment by jasperan** [comment]
> > I ran tests and I don't get this error.. just training is slow. Hence I say do it in 4bits.
> 
> Yeah, I ended up picking a smaller model and its working fine in 4bit mode. Even llama 7b is too big to train in 4 bit mode on 24gb vram

Thanks, this looked like it worked for the base model I'm using (a 7B param model).
