### ISSUE TITLE
Install fails when using GCC 13

### ISSUE THREAD

**Issue by seeseemelk** [oobabooga/text-generation-webui#2131]
### Describe the bug

When installing with GCC 13, the installation will fail as `quant-cuda` requires a version of GCC no newer than 11.

The check in `webui.py` check for the output of `gcc --version`, and installs the correct one if it fails or returns `g++ (GCC) 12`. This fails on version 13, or on any version that has a different name that `g++` (for instance, gcc 12 on my system reports itself as `g++-12 (GCC) 12`.

Making this check more robust should make sure that quant-cuda can install.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run `update_linux.sh` on a system that has GCC 13 installed.

### Logs

```shell
jinja2->torch>=1.4.0->accelerate==0.18.0->-r requirements.txt (line 5)) (2.1.1)
Requirement already satisfied: mpmath>=0.19 in /home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/mpmath-1.2.1-py3.10.egg (from sympy->torch>=1.4.0->accelerate==0.18.0->-r requirements.txt (line 5)) (1.2.1)
Installing collected packages: safetensors, transformers, accelerate, datasets
  Attempting uninstall: safetensors
    Found existing installation: safetensors 0.3.1
    Uninstalling safetensors-0.3.1:
      Successfully uninstalled safetensors-0.3.1
  Attempting uninstall: transformers
    Found existing installation: transformers 4.29.1
    Uninstalling transformers-4.29.1:
      Successfully uninstalled transformers-4.29.1
  Attempting uninstall: accelerate
    Found existing installation: accelerate 0.19.0
    Uninstalling accelerate-0.19.0:
      Successfully uninstalled accelerate-0.19.0
  Attempting uninstall: datasets
    Found existing installation: datasets 2.12.0
    Uninstalling datasets-2.12.0:
      Successfully uninstalled datasets-2.12.0
Successfully installed accelerate-0.18.0 datasets-2.10.1 safetensors-0.3.0 transformers-4.28.0
Processing /home/seeseemelk/tmp/oobabooga_linux/text-generation-webui/repositories/GPTQ-for-LLaMa
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: quant-cuda
  Building wheel for quant-cuda (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [45 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
    if sys.platform.startswith("win"):
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/seeseemelk/tmp/oobabooga_linux/text-generation-webui/repositories/GPTQ-for-LLaMa/setup.py", line 4, in <module>
          setup(
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 416, in _check_cuda_version
          raise RuntimeError(
      RuntimeError: The current installed version of g++ (13.1.1) is greater than the maximum required version by CUDA 11.7. Please make sure to use an adequate version of g++ (>=6.0.0, <12.0).
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for quant-cuda
  Running setup.py clean for quant-cuda
Failed to build quant-cuda
Installing collected packages: quant-cuda
  Running setup.py install for quant-cuda ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for quant-cuda did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      running install
      /home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/seeseemelk/tmp/oobabooga_linux/text-generation-webui/repositories/GPTQ-for-LLaMa/setup.py", line 4, in <module>
          setup(
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "/home/seeseemelk/tmp/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 416, in _check_cuda_version
          raise RuntimeError(
      RuntimeError: The current installed version of g++ (13.1.1) is greater than the maximum required version by CUDA 11.7. Please make sure to use an adequate version of g++ (>=6.0.0, <12.0).
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> quant-cuda

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
ERROR: GPTQ CUDA kernel compilation failed.
You will not be able to use GPTQ-based models.
Continuing with install..
```

### System Info

```shell
Arch Linux with GCC 13, Nvidia RTX 3080
```

**Comment by brokeboiflex** [comment]
Maximum supported version of GCC by CUDA is 12 [See this gist](https://gist.github.com/ax3l/9489132). So it seems that bleeding edge distros users are in the bad position (myself included, however im planning on testing out Rocky Linux 9 which should work fine according to posts I've read on Nvidia forums)

**Comment by seeseemelk** [comment]
Thing is, the install script will automatically install an older version of GCC if needed. This check however only does it if it cannot find GCC or if the installed GCC version reports itself as version 12. It breaks on version 13 and thus does not automatically download the older version.

**Comment by seeseemelk** [comment]
If you change line 135 of `webui.py` to check for `g++ (GCC) 13` it installs perfectly fine on my machine.

**Comment by samfundev** [comment]
@seeseemelk Is this fixed now that oobabooga/one-click-installers#72 is merged?
