### ISSUE TITLE
During the lora training I loaded the gpt4all- model to fine tune after filling the parameter when I click lora it pass AttributeError: 'list' object has no attribute 'strip'

### ISSUE THREAD

**Issue by Tejaswi-kashyap-006** [oobabooga/text-generation-webui#2138]
### Describe the bug

During the lora training I loaded the gpt4all- model to fine tune after filling the parameter when I click lora it pass AttributeError: 'list' object has no attribute 'strip'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

run the conda textgen python server.py The gui starts and when I start lora training it give AttributeError: 'list' object has no attribute 'strip', The model I loaded is gpt4all -j model in 8 bit model

### Logs

```shell
Traceback (most recent call last):
  File "/home/haive/.local/lib/python3.10/site-packages/gradio/routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/haive/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "/home/haive/.local/lib/python3.10/site-packages/gradio/blocks.py", line 930, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/haive/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/haive/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/haive/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/haive/.local/lib/python3.10/site-packages/gradio/utils.py", line 491, in async_iteration
    return next(iterator)
  File "/home/haive/web_ui/text-generation-webui/modules/training.py", line 301, in do_train
    train_data = data['train'].map(generate_and_tokenize_prompt)
  File "/home/haive/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 578, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/haive/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 543, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/haive/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3073, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "/home/haive/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3427, in _map_single
    example = apply_function_on_filtered_inputs(example, i, offset=offset)
  File "/home/haive/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3330, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/home/haive/web_ui/text-generation-webui/modules/training.py", line 296, in generate_and_tokenize_prompt
    prompt = generate_prompt(data_point)
  File "/home/haive/web_ui/text-generation-webui/modules/training.py", line 288, in generate_prompt
    if set(options.split(',')) == set(x[0] for x in data_point.items() if (x[1] is not None and len(x[1].strip()) > 0)):
  File "/home/haive/web_ui/text-generation-webui/modules/training.py", line 288, in <genexpr>
    if set(options.split(',')) == set(x[0] for x in data_point.items() if (x[1] is not None and len(x[1].strip()) > 0)):
AttributeError: 'list' object has no attribute 'strip'
```

### System Info

```shell
single 40gb A100 gpu
```

**Comment by Rajhin** [comment]
Same for my attempts to make any LoRAs for Vicuna

**Comment by svenkevs** [comment]
I have a similar problem training Llama2.
