### ISSUE TITLE
Chat errors at quotes and colons

### ISSUE THREAD

**Issue by mykeehu** [oobabooga/text-generation-webui#2146]
### Describe the bug

When I use a colon, asterisk or quotation marks in chat, I repeatedly get the following errors:
```
Traceback (most recent call last):
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 339, in async_iteration
    return await iterator.__anext__()
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 332, in __anext__
    return await anyio.to_thread.run_sync(
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 315, in run_sync_iterator_async
    return next(iterator)
  File "J:\oobabooga_windows\text-generation-webui\modules\chat.py", line 307, in generate_chat_reply_wrapper
    for history in generate_chat_reply(text, state, regenerate, _continue):
  File "J:\oobabooga_windows\text-generation-webui\modules\chat.py", line 301, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue):
  File "J:\oobabooga_windows\text-generation-webui\modules\chat.py", line 247, in chatbot_wrapper
    elif not (j == 0 and visible_reply.strip() == ''):
AttributeError: 'NoneType' object has no attribute 'strip'
```

Or sometimes this:
```
Traceback (most recent call last):
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 339, in async_iteration
    return await iterator.__anext__()
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 332, in __anext__
    return await anyio.to_thread.run_sync(
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 315, in run_sync_iterator_async
    return next(iterator)
  File "J:\oobabooga_windows\text-generation-webui\modules\chat.py", line 308, in generate_chat_reply_wrapper
    yield chat_html_wrapper(history, state['name1'], state['name2'], state['mode'], state['chat_style'])
  File "J:\oobabooga_windows\text-generation-webui\modules\html_generator.py", line 279, in chat_html_wrapper
    return generate_cai_chat_html(history, name1, name2, style, reset_cache)
  File "J:\oobabooga_windows\text-generation-webui\modules\html_generator.py", line 199, in generate_cai_chat_html
    row = [convert_to_markdown(entry) for entry in _row]
  File "J:\oobabooga_windows\text-generation-webui\modules\html_generator.py", line 199, in <listcomp>
    row = [convert_to_markdown(entry) for entry in _row]
  File "J:\oobabooga_windows\text-generation-webui\modules\html_generator.py", line 48, in convert_to_markdown
    string = pattern.sub(replace_blockquote, string)
TypeError: expected string or bytes-like object
Traceback (most recent call last):
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "J:\oobabooga_windows\text-generation-webui\modules\chat.py", line 361, in redraw_html
    return chat_html_wrapper(shared.history['visible'], name1, name2, mode, style, reset_cache=reset_cache)
  File "J:\oobabooga_windows\text-generation-webui\modules\html_generator.py", line 279, in chat_html_wrapper
    return generate_cai_chat_html(history, name1, name2, style, reset_cache)
  File "J:\oobabooga_windows\text-generation-webui\modules\html_generator.py", line 199, in generate_cai_chat_html
    row = [convert_to_markdown(entry) for entry in _row]
  File "J:\oobabooga_windows\text-generation-webui\modules\html_generator.py", line 199, in <listcomp>
    row = [convert_to_markdown(entry) for entry in _row]
  File "J:\oobabooga_windows\text-generation-webui\modules\html_generator.py", line 48, in convert_to_markdown
    string = pattern.sub(replace_blockquote, string)
TypeError: expected string or bytes-like object
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. use Chat mode.
2. I use Pygmalion 7b 4bit cuda model. 
3. if I use quotes or colons in the text at the beginning or end of a chat or new line, these errors may occur.

### Logs

```shell
See above
```

### System Info

```shell
RTX 3060 12 GB
Windows 10 64 bit
```

**Comment by mykeehu** [comment]
The bug is very annoying, because I can't format text in chat mode, because I can get an error at any time. It might have something to do with Google Translate (translate from Hungarian), but it's getting annoying that it keeps getting stuck, sometimes I can't even start a new chat because of it.

**Comment by mykeehu** [comment]
Ok, it looks like the error is in the Google translate add-on. When I unchecked line 230 of the chat.py file, the English text appeared without any problem.
So Google Translate returns a text or character that the chat can't handle (like an initial or special character?)

**Comment by mykeehu** [comment]
I just got one of those, so either Google Translate is screwing me and returning an empty string or I don't know:
```
Traceback (most recent call last):
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 339, in async_iteration
    return await iterator.__anext__()
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 332, in __anext__
    return await anyio.to_thread.run_sync(
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 315, in run_sync_iterator_async
    return next(iterator)
  File "J:\oobabooga_windows\text-generation-webui\modules\chat.py", line 316, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, shared.history, state, regenerate, _continue, loading_message=True)):
  File "J:\oobabooga_windows\text-generation-webui\modules\chat.py", line 310, in generate_chat_reply
    for history in chatbot_wrapper(text, history, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "J:\oobabooga_windows\text-generation-webui\modules\chat.py", line 258, in chatbot_wrapper
    output['visible'][-1] = [visible_text, visible_reply.lstrip(' ')]
AttributeError: 'NoneType' object has no attribute 'lstrip'
```

**Comment by mykeehu** [comment]
I downloaded some models from this site, they don't work well, even though I use the pygmalion model:
https://booru.plus/+pygmalion

I also loaded the downloaded image into the [Character Editor](https://zoltanai.github.io/character-editor/), saved it as JSON and loaded it that way, that didn't work either. So it's getting frustrating that you can't chat with external characters in other languages.

**Comment by mykeehu** [comment]
Another twist to the story: if I turn off the _Activate text streaming_ option, the error does not occur. It's fine as a workaround, but I prefer to see what it generates so I can stop it on the fly.
