### ISSUE TITLE
Failed to load the extension "whisper_stt" and "silero_tts" in kaggle or collab

### ISSUE THREAD

**Issue by Asmedeus998** [oobabooga/text-generation-webui#2161]
### Describe the bug

failed to install whisper and silero tts (already try it at google collab too)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

!python server.py --public-api --share --chat --wbits 4 --groupsize 128 --extension whisper_stt silero_tts

### Logs

```shell
/kaggle/text-generation-webui
WARNING:The gradio "share link" feature downloads a proprietary and unaudited blob to create a reverse tunnel. This is potentially dangerous.
bin /opt/conda/envs/newCondaEnvironment/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
INFO:Loading vicuna-13b-GPTQ-4bit-128g...
INFO:Found the following quantized model: models/vicuna-13b-GPTQ-4bit-128g/vicuna-13b-4bit-128g.safetensors
INFO:Using the following device map for the quantized model:
INFO:Loaded the model in 48.20 seconds.

INFO:Loading the extension "whisper_stt"...
ERROR:Failed to load the extension "whisper_stt".
Traceback (most recent call last):
  File "/kaggle/text-generation-webui/modules/extensions.py", line 34, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "/kaggle/text-generation-webui/extensions/whisper_stt/script.py", line 2, in <module>
    import speech_recognition as sr
ModuleNotFoundError: No module named 'speech_recognition'
INFO:Loading the extension "silero_tts"...
ERROR:Failed to load the extension "silero_tts".
Traceback (most recent call last):
  File "/kaggle/text-generation-webui/modules/extensions.py", line 34, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "/kaggle/text-generation-webui/extensions/silero_tts/script.py", line 8, in <module>
    from extensions.silero_tts import tts_preprocessor
  File "/kaggle/text-generation-webui/extensions/silero_tts/tts_preprocessor.py", line 3, in <module>
    from num2words import num2words
ModuleNotFoundError: No module named 'num2words'
INFO:Loading the extension "gallery"...
INFO:server listening on 127.0.0.1:5005
You should install flask_cloudflared manually
Exception in thread Thread-3 (_start_cloudflared):
Traceback (most recent call last):
  File "/kaggle/text-generation-webui/extensions/api/util.py", line 53, in _start_cloudflared
    from flask_cloudflared import _run_cloudflared
ModuleNotFoundError: No module named 'flask_cloudflared'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/newCondaEnvironment/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/newCondaEnvironment/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/kaggle/text-generation-webui/extensions/api/util.py", line 56, in _start_cloudflared
    raise Exception(
Exception: flask_cloudflared not installed. Make sure you installed the requirements.txt for this extension.
You should install flask_cloudflared manually
Exception in thread Thread-4 (_start_cloudflared):
Traceback (most recent call last):
  File "/kaggle/text-generation-webui/extensions/api/util.py", line 53, in _start_cloudflared
    from flask_cloudflared import _run_cloudflared
ModuleNotFoundError: No module named 'flask_cloudflared'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/newCondaEnvironment/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/newCondaEnvironment/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/kaggle/text-generation-webui/extensions/api/util.py", line 56, in _start_cloudflared
    raise Exception(
Exception: flask_cloudflared not installed. Make sure you installed the requirements.txt for this extension.
Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://d0038612312381b6e3ab247.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
```

### System Info

```shell
- kaggle 
- google collab
```

**Comment by krigeta** [comment]
how are you able to run the notebook on kaggle? In my case, everything is running fine and within seconds I got 

```
This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
^C
17:03:03-622468 INFO     Received Ctrl+C. Shutting down Text generation web UI  
                         gracefully.                                            
Killing tunnel 127.0.0.1:7860 <> https://01f5117d933793e02f.gradio.live/
```
