### ISSUE TITLE
RuntimeError: [enforce fail at alloc_cpu.cpp:75] err == 0. DefaultCPUAllocator: can't allocate memory: you tried to allocate 28296376320 bytes. Error code 12 (Cannot allocate memory)

### ISSUE THREAD

**Issue by jimi202008** [oobabooga/text-generation-webui#2168]
### Describe the bug

I run RWKV-Raven with text-generation-webui in wsl-Ubuntu showing not enough memory. But my graphics card is 3090 and I have 32GB of memory, I shouldn't be out of memory.
By the way, my running parameters are:
python server.py --model RWKV-4-Raven-14B-v6-EngChnJpn-20230401-ctx4096.pth --chat --rwkv-strategy "cuda fp16i8" --rwkv-cuda-on
I tried multiple --rwkv-strategy at the same time but the effect is the same.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Using any --rwkv-strategy will report out of memory errors

### Logs

```shell
INFO:Gradio HTTP request redirected to localhost :)
bin /root/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
INFO:Loading RWKV-4-Raven-14B-v6-EngChnJpn-20230401-ctx4096.pth...
Using /root/.cache/torch_extensions/py310_cu117 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py310_cu117/wkv_cuda/build.ninja...
Building extension module wkv_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module wkv_cuda...
RWKV_JIT_ON 1 RWKV_CUDA_ON 1 RESCALE_LAYER 6

Loading models/RWKV-4-Raven-14B-v6-EngChnJpn-20230401-ctx4096.pth ...
Traceback (most recent call last):
  File "/mnt/d/text-generation-webui/server.py", line 984, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/mnt/d/text-generation-webui/modules/models.py", line 95, in load_model
    output = load_func(model_name)
  File "/mnt/d/text-generation-webui/modules/models.py", line 240, in RWKV_loader
    model = RWKVModel.from_pretrained(Path(f'{shared.args.model_dir}/{model_name}'), dtype="fp32" if shared.args.cpu else "bf16" if shared.args.bf16 else "fp16", device="cpu" if shared.args.cpu else "cuda")
  File "/mnt/d/text-generation-webui/modules/RWKV.py", line 30, in from_pretrained
    model = RWKV(model=str(path), strategy=shared.args.rwkv_strategy)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/jit/_script.py", line 292, in init_then_script
    original_init(self, *args, **kwargs)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/rwkv/model.py", line 101, in __init__
    self.w = torch.load(args.MODEL_NAME, map_location='cpu') # load model to CPU first
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/serialization.py", line 1112, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage)._typed_storage()._untyped_storage
RuntimeError: [enforce fail at alloc_cpu.cpp:75] err == 0. DefaultCPUAllocator: can't allocate memory: you tried to allocate 28296376320 bytes. Error code 12 (Cannot allocate memory)
```

### System Info

```shell
GPU:3090
CPU:I5-13600KF
wsl-Ubuntu
```

**Comment by SuperBruceJia** [comment]
+1
