### ISSUE TITLE
Messenger CSS for chat mode here

### ISSUE THREAD

**Issue by mykeehu** [oobabooga/text-generation-webui#2173]
I created a Messenger-like look for the chat mode. I'll share it with you in case you use it.
Put it in the css folder, delete the TXT extension and restart the webui!

[chat_style-messenger.css.txt](https://github.com/oobabooga/text-generation-webui/files/11513756/chat_style-messenger.css.txt)

![image](https://github.com/oobabooga/text-generation-webui/assets/6390413/e9f27254-f37f-4f7d-a871-0fe83f82adf9)

Dark mode:
![image](https://github.com/oobabooga/text-generation-webui/assets/6390413/b313749e-4b91-4007-b23d-7978a6a3dba0)

**Comment by oobabooga** [comment]
That's nice, could you make it also work in dark mode (by making `.dark ...` selectors) and submit the .css in a PR?

**Comment by mykeehu** [comment]
Ok, I added the dark mode text color, mainly for the bot. It's good in principle, so if you need any more formatting, let me know.

**Comment by mykeehu** [comment]
@oobabooga 
In principle it shouldn't, but is it possible that css affects the use of chat? Because I get this error repeatedly when I click on the Regenerate button, and it links to html here:
```
Traceback (most recent call last):
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 339, in async_iteration
    return await iterator.__anext__()
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 332, in __anext__
    return await anyio.to_thread.run_sync(
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 315, in run_sync_iterator_async
    return next(iterator)
  File "J:\oobabooga_windows\text-generation-webui\modules\chat.py", line 308, in generate_chat_reply_wrapper
    yield chat_html_wrapper(history, state['name1'], state['name2'], state['mode'], state['chat_style'])
  File "J:\oobabooga_windows\text-generation-webui\modules\html_generator.py", line 279, in chat_html_wrapper
    return generate_cai_chat_html(history, name1, name2, style, reset_cache)
  File "J:\oobabooga_windows\text-generation-webui\modules\html_generator.py", line 199, in generate_cai_chat_html
    row = [convert_to_markdown(entry) for entry in _row]
  File "J:\oobabooga_windows\text-generation-webui\modules\html_generator.py", line 199, in <listcomp>
    row = [convert_to_markdown(entry) for entry in _row]
  File "J:\oobabooga_windows\text-generation-webui\modules\html_generator.py", line 48, in convert_to_markdown
    string = pattern.sub(replace_blockquote, string)
TypeError: expected string or bytes-like object
Traceback (most recent call last):
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "J:\oobabooga_windows\text-generation-webui\modules\chat.py", line 361, in redraw_html
    return chat_html_wrapper(shared.history['visible'], name1, name2, mode, style, reset_cache=reset_cache)
  File "J:\oobabooga_windows\text-generation-webui\modules\html_generator.py", line 279, in chat_html_wrapper
    return generate_cai_chat_html(history, name1, name2, style, reset_cache)
  File "J:\oobabooga_windows\text-generation-webui\modules\html_generator.py", line 199, in generate_cai_chat_html
    row = [convert_to_markdown(entry) for entry in _row]
  File "J:\oobabooga_windows\text-generation-webui\modules\html_generator.py", line 199, in <listcomp>
    row = [convert_to_markdown(entry) for entry in _row]
  File "J:\oobabooga_windows\text-generation-webui\modules\html_generator.py", line 48, in convert_to_markdown
    string = pattern.sub(replace_blockquote, string)
TypeError: expected string or bytes-like object
```
