### ISSUE TITLE
CPU mode is not working anymore for quantized models

### ISSUE THREAD

**Issue by Ookami123** [oobabooga/text-generation-webui#2175]
### Describe the bug

Loading the model "Stable Vicuna" gives the error:
"INFO:Loading stable-vicuna-13B-GPTQ-4bit...
ERROR:Failed to load GPTQ-for-LLaMa
ERROR:See https://github.com/oobabooga/text-generation-webui/blob/main/docs/GPTQ-models-(4-bit-mode).md"
This worked in a previous version.
I'm also getting the same error with the wizard-mega-13B.ggml.q4_0.bin model.
Also 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Download the current version of the linux package, unzip, run start_linux.sh, select CPU mode, don't download any model at this time, download the mentioned models to the model folder, run again and try out the models

### Logs

```shell
No stack trace, just the Error mentioned in the bug description
```

### System Info

```shell
OS: Kali linux, kernel "Linux kali 6.0.0-kali6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1kali1 (2022-12-19) x86_64 GNU/Linux", GPU not applicable
```

**Comment by mrcashcash** [comment]
got same issue running on cpu
used to work in previous versions:

INFO:Loading wizard-vicuna-13B.ggml.q4_2.bin...
INFO:llama.cpp weights detected: models\wizard-vicuna-13B.ggml.q4_2.bin

INFO:Cache capacity is 0 bytes
Exception ignored in: <function Llama.__del__ at 0x000001DE127CBBE0>
Traceback (most recent call last):
  File "C:\Users\USER\Documents\GitHub\text-generation-webui\env\lib\site-packages\llama_cpp\llama.py", line 905, in __del__
    if self.ctx is not None:
AttributeError: 'Llama' object has no attribute 'ctx'
Exception ignored in: <function LlamaCppModel.__del__ at 0x000001DE127C9CF0>
Traceback (most recent call last):
  File "C:\Users\USER\Documents\GitHub\text-generation-webui\modules\llamacpp_model.py", line 23, in __del__
    self.model.__del__()
AttributeError: 'LlamaCppModel' object has no attribute 'model'

**Comment by githubuser1987** [comment]
Got the same issue when trying to load ggml models, after updating OobaBooga.
Only my message reads "ERROR:Could not find the quantized model in .pt or .safetensors format, exiting...".
It's a .bin file. It worked fine before the update.

**Comment by Recruiter2** [comment]
the .cpp has been updated u need newer models or roll back to previous version

**Comment by Ookami123** [comment]
Nope, that isn't it in my case but for the old stanford alpaca model. The precise reason I updated is also because I was testing a new model. This model runs under the newest version of llama.cpp. Now please stop guessing @ Recruiter2 and also please stop posting other, unrelated bug reports with different error messages and causes under mine, mrcashcash & githubuser1987.

**Comment by thusinh1969** [comment]
> the .cpp has been updated u need newer requantized models or roll back to previous version of the web-ui

Which old version should I roll back ? Can NOT use any .bin any more :( ..!!!!

**Comment by BlazzingSaddles** [comment]
where can i find and older version of the web ui to roll back to?

**Comment by Cebtenzzre** [comment]
> Got the same issue when trying to load ggml models, after updating OobaBooga. Only my message reads "ERROR:Could not find the quantized model in .pt or .safetensors format, exiting...". It's a .bin file. It worked fine before the update.

I did a little digging, and in my case this seems to be caused by wbits getting set to 4 by the UI when I try to load a model, even though the dropdown says 'None'. When wbits is nonzero, it tries the use the GPTQ loader even if shared.model_type is llamacpp.

**Comment by elyakim** [comment]
> 

Yep, this is exactly it.
I decided to remove the GPTQ parameters and some GGML models started working again. The others are probably not supported by the new llama.cpp version.
