### ISSUE TITLE
AI is forever "Is typing..." (AttributeError: module 'torch' has no attribute 'has_mps')

### ISSUE THREAD

**Issue by Bleeplo** [oobabooga/text-generation-webui#2176]
### Describe the bug

(Running on Linux)

I have gotten the UI to run, everything seems responsive - except for the AI! I am using the [mayaeary/pygmalion-6b_dev-4bit-128g](https://huggingface.co/mayaeary/pygmalion-6b_dev-4bit-128g) model. When I go to say something, and then I tell it to generate, it stays in a forever "Is typing..." loop. I think the issue is related to pytorch, due to the response (in the terminal) I get when I go to run the AI.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Open terminal
2. Run in Bash
3. ./start_linux.sh
4. Go to model tab
5. Set GPTQ parameters
     1. wbits: 4
     2. model_type: gptj
     3. groupsize: 128
6. Reload model
7. Go to "Text Generation" tab
8. Select Example character
9. Type "Hello" into prompt
10. Click Generate
11. AI forever is typing (also when log appears in the terminal)

### Screenshot

![Screenshot_20230518_141200](https://github.com/oobabooga/text-generation-webui/assets/81447023/4c6b20cf-490f-44cc-ad4e-83f1aaff4b32)
![Screenshot_20230518_141218](https://github.com/oobabooga/text-generation-webui/assets/81447023/1ff4a6a6-0129-4df4-95eb-5ed5d9733924)

### Logs

```shell
INFO:Loading mayaeary_pygmalion-6b_dev-4bit-128g...
CUDA extension not installed.
INFO:Found the following quantized model: models/mayaeary_pygmalion-6b_dev-4bit-128g/pygmalion-6b_dev-4bit-128g.safetensors
INFO:Using the following device map for the quantized model:
INFO:Loaded the model in 4.77 seconds.

INFO:Loading the extension "gallery"...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
INFO:Loading mayaeary_pygmalion-6b_dev-4bit-128g...
INFO:Found the following quantized model: models/mayaeary_pygmalion-6b_dev-4bit-128g/pygmalion-6b_dev-4bit-128g.safetensors
INFO:Using the following device map for the quantized model:
INFO:Loaded the model in 2.39 seconds.

Traceback (most recent call last):
  File "/home/phil/text-generation-webui-oobabooga/installer_files/env/lib/python3.10/site-packages/gradio/routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/phil/text-generation-webui-oobabooga/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/phil/text-generation-webui-oobabooga/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/phil/text-generation-webui-oobabooga/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 339, in async_iteration
    return await iterator.__anext__()
  File "/home/phil/text-generation-webui-oobabooga/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 332, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/phil/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/phil/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/phil/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/phil/text-generation-webui-oobabooga/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 315, in run_sync_iterator_async
    return next(iterator)
  File "/home/phil/text-generation-webui-oobabooga/text-generation-webui/modules/chat.py", line 307, in generate_chat_reply_wrapper
    for history in generate_chat_reply(text, state, regenerate, _continue):
  File "/home/phil/text-generation-webui-oobabooga/text-generation-webui/modules/chat.py", line 301, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue):
  File "/home/phil/text-generation-webui-oobabooga/text-generation-webui/modules/chat.py", line 219, in chatbot_wrapper
    prompt = generate_chat_prompt(text, state, **kwargs)
  File "/home/phil/text-generation-webui-oobabooga/text-generation-webui/modules/chat.py", line 87, in generate_chat_prompt
    while i >= 0 and get_encoded_length(wrapper.replace('<|prompt|>', ''.join(rows))) < max_length:
  File "/home/phil/text-generation-webui-oobabooga/text-generation-webui/modules/text_generation.py", line 67, in get_encoded_length
    return len(encode(prompt)[0])
  File "/home/phil/text-generation-webui-oobabooga/text-generation-webui/modules/text_generation.py", line 55, in encode
    elif torch.has_mps:
AttributeError: module 'torch' has no attribute 'has_mps'
```

### System Info

```shell
OS: Linux (Majaro KDE)
GPU: Nvidia GeForce RTX 2060
```

**Comment by Bleeplo** [comment]
I suppose the install process didn't fully install correctly. So, I reinstalled via deleting the folder and rerunning the start_linux.sh. After doing the same thing as the first time, the AI seems to work now. I guess the ol'uninstall, reinstall works.
