### ISSUE TITLE
Issue with prebuilt wheels

### ISSUE THREAD

**Issue by tangelov** [oobabooga/text-generation-webui#2194]
### Describe the bug

I get "KeyError: 'model.layers.17.self_attn.q_proj.wf'"

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction
I installed the 832e220 wheels(with the corresponding repo). I try loading the Wizard-Vicuna-13B-Uncensored-GPTQ:

- With no memory limitation flags - the whole model gets loaded in VRAM but OOMs at some point in inference.

- With --gpu-memory it loads but can't infer any length, it errors with KeyError: 'model.layers.17.self_attn.q_proj.wf'

- With --pre-layers it fails on load with: torch\nn\modules[module.py]([http://module.py/)”](http://module.py/)%E2%80%9D), line 2041, in load_state_dict raise RuntimeError(‘Error(s) in loading state_dict for {}:\n\t{}’.format( RuntimeError: Error(s) in loading state_dict for LlamaForCausalLM: Missing key(s) in state_dict: “model.layers.0.self_attn.k_proj.g_idx”,

- With CPU only I get some error.(As explained in the comments, this model does not support CPU).

### Logs

```shell
INFO:Loading Wizard-Vicuna-13B-Uncensored-GPTQ...
INFO:Found the following quantized model: models\Wizard-Vicuna-13B-Uncensored-GPTQ\Wizard-Vicuna-13B-Uncensored-GPTQ-4bit-128g.compat.no-act-order.safetensors
INFO:Using the following device map for the quantized model:
INFO:Loaded the model in 14.68 seconds.

Traceback (most recent call last):
  File "E:\ai-playground\LLM\text-generation-webui\modules\callbacks.py", line 73, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "E:\ai-playground\LLM\text-generation-webui\modules\text_generation.py", line 263, in generate_with_callback
    shared.model.generate(**kwargs)
  File "D:\conda-envs\textgen\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\conda-envs\textgen\lib\site-packages\transformers\generation\utils.py", line 1565, in generate
    return self.sample(
  File "D:\conda-envs\textgen\lib\site-packages\transformers\generation\utils.py", line 2612, in sample
    outputs = self(
  File "D:\conda-envs\textgen\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\conda-envs\textgen\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "D:\conda-envs\textgen\lib\site-packages\transformers\models\llama\modeling_llama.py", line 688, in forward
    outputs = self.model(
  File "D:\conda-envs\textgen\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\conda-envs\textgen\lib\site-packages\transformers\models\llama\modeling_llama.py", line 578, in forward
    layer_outputs = decoder_layer(
  File "D:\conda-envs\textgen\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\conda-envs\textgen\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "D:\conda-envs\textgen\lib\site-packages\transformers\models\llama\modeling_llama.py", line 293, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "D:\conda-envs\textgen\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\conda-envs\textgen\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "D:\conda-envs\textgen\lib\site-packages\transformers\models\llama\modeling_llama.py", line 197, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "D:\conda-envs\textgen\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\conda-envs\textgen\lib\site-packages\accelerate\hooks.py", line 160, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "D:\conda-envs\textgen\lib\site-packages\accelerate\hooks.py", line 280, in pre_forward
    set_module_tensor_to_device(module, name, self.execution_device, value=self.weights_map[name])
  File "D:\conda-envs\textgen\lib\site-packages\accelerate\utils\offload.py", line 123, in __getitem__
    return self.dataset[f"{self.prefix}{key}"]
  File "D:\conda-envs\textgen\lib\site-packages\accelerate\utils\offload.py", line 170, in __getitem__
    weight_info = self.index[key]
KeyError: 'model.layers.17.self_attn.q_proj.wf'
Output generated in 16.70 seconds (0.00 tokens/s, 0 tokens, context 16, seed 810248490)
```

### System Info

```shell
GPU is 1070ti
Windows 11
32 RAM(system managed page)
```

**Comment by BarfingLemurs** [comment]
the model for gptq is for gpu, not cpu (won't work.)
https://github.com/oobabooga/text-generation-webui/issues/936 others with older cards 10XX also fail to use 4bit gptq repo. you might want to check if someone has complied for these older cards.

**Comment by tangelov** [comment]
Environment was not clean(wrong torch, etc).

**Comment by tangelov** [comment]
It sometimes work, sometimes doesn't. Maybe it's memory related. My page file is set to system managed.

**Comment by tangelov** [comment]
> the model for gptq is for gpu, not cpu (won't work.) #936 others with older cards 10XX also fail to use 4bit gptq repo. you might want to check if someone has complied for these older cards.

On first look, #936 doesn't match the stack trace

**Comment by tangelov** [comment]
Do all the errors stem from the fact this model doesn't support CPU?
