### ISSUE TITLE
Webui doesn't support older gpu without CUDA.

### ISSUE THREAD

**Issue by mlgbenhur** [oobabooga/text-generation-webui#2203]
### Describe the bug

i choose cpu mode but this always happens

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

old gpu without CUDA.

### Logs

```shell
INFO:Loading EleutherAI_pythia-410m-deduped...
Traceback (most recent call last):
  File "C:\Users\ben1123\Documents\oobabooga_windows\text-generation-webui\server.py", line 984, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\ben1123\Documents\oobabooga_windows\text-generation-webui\modules\models.py", line 95, in load_model
    output = load_func(model_name)
  File "C:\Users\ben1123\Documents\oobabooga_windows\text-generation-webui\modules\models.py", line 158, in huggingface_loader
    model = model.cuda()
  File "C:\Users\ben1123\Documents\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\ben1123\Documents\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\ben1123\Documents\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\ben1123\Documents\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Users\ben1123\Documents\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\ben1123\Documents\oobabooga_windows\installer_files\env\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

### System Info

```shell
GT420 (2GB VRAM) NVIDIA

I5 3470
DDR3 1600 MHZ
```

**Comment by oobabooga** [comment]
Try adding --cpu flag

**Comment by mlgbenhur** [comment]
ok

**Comment by mlgbenhur** [comment]
but how to do it

**Comment by mlgbenhur** [comment]
> Try adding --cpu flag

how to add flag and i cannot see webui-user.bat

**Comment by mlgbenhur** [comment]
> Try adding --cpu flag

Now is OSError: Unable to load weights from pytorch checkpoint file for 'models\PygmalionAI_pygmalion-6b\pytorch_model-00001-of-00002.bin' at 'models\PygmalionAI_pygmalion-6b\pytorch_model-00001-of-00002.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**Comment by oobabooga** [comment]
It looks like your model file may be corrupt, try re-downloading it

**Comment by mlgbenhur** [comment]
ok

**Comment by mlgbenhur** [comment]
THANKS YOU!!!!!!!!!!!!!
