### ISSUE TITLE
DefaultCPUAllocator: not enough memory: you tried to allocate 268435456 bytes.

### ISSUE THREAD

**Issue by mlgbenhur** [oobabooga/text-generation-webui#2207]
### Describe the bug

i dont have enough memory?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

install pygmalionai 6b on a bad pc?

### Screenshot

![Screenshot (3)](https://github.com/oobabooga/text-generation-webui/assets/91999796/5bed6183-10e5-45c9-8d07-9345f64351c7)

### Logs

```shell
INFO:Loading PygmalionAI_pygmalion-6b...
Loading checkpoint shards:   0%|                                                                 | 0/2 [06:37<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\ben1123\Documents\oobabooga_windows\text-generation-webui\server.py", line 998, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\ben1123\Documents\oobabooga_windows\text-generation-webui\modules\models.py", line 95, in load_model
    output = load_func(model_name)
  File "C:\Users\ben1123\Documents\oobabooga_windows\text-generation-webui\modules\models.py", line 209, in huggingface_loader
    model = LoaderClass.from_pretrained(checkpoint, **params)
  File "C:\Users\ben1123\Documents\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 467, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\ben1123\Documents\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2777, in from_pretrained
    ) = cls._load_pretrained_model(
  File "C:\Users\ben1123\Documents\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 3118, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "C:\Users\ben1123\Documents\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 668, in _load_state_dict_into_meta_model
    param = param.to(dtype)
RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 268435456 bytes.
```

### System Info

```shell
I5 3470
NVIDIA GT 420
16GB DDR3 1600MHZ RAM
```

**Comment by mlgbenhur** [comment]
I accidentally close it
