### ISSUE TITLE
--no-stream argument raises a ValueError

### ISSUE THREAD

**Issue by VraethrDalkr** [oobabooga/text-generation-webui#2209]
### Describe the bug

When launching server.py, using --no-stream argument returns ValueError: Queue needs to be enabled!

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

conda activate textgen
cd /home/user/text-generation-webui/
python server.py --no-stream

### Logs

```shell
bin /home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
INFO:Loading settings from settings.json...
Traceback (most recent call last):
  File "/home/user/text-generation-webui/server.py", line 1011, in <module>
    create_interface()
  File "/home/user/text-generation-webui/server.py", line 922, in create_interface
    shared.gradio['interface'].launch(prevent_thread_lock=True, share=shared.args.share, server_port=shared.args.listen_port, inbrowser=shared.args.auto_launch, auth=auth)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1727, in launch
    self.validate_queue_settings()
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1575, in validate_queue_settings
    raise ValueError(
ValueError: Queue needs to be enabled! You may get this error by either 1) passing a function that uses the yield keyword into an interface without enabling the queue or 2) defining an event that cancels another event without enabling the queue. Both can be solved by calling .queue() before .launch()
```

### System Info

```shell
Windows 11 Home (WSL2 Ubuntu), NVIDIA 3070 Ti Laptop GPU
```

**Comment by chigkim** [comment]
Have the same problem.

**Comment by Kaiten10** [comment]
Getting the same problem. I have to enable --no-stream to use Bark TTS extension, or else Bark generates a sound file on every stream token generated.

**Comment by Infexis95** [comment]
Getting the same error.

**Comment by Erthar** [comment]
Same issue here on Google Colab.

```
INFO:Loaded the model in 44.69 seconds.

INFO:server listening on 127.0.0.1:5005
Traceback (most recent call last):
  File "/content/Colab-TextGen/extensions/api/util.py", line 61, in _start_cloudflared
    public_url = _run_cloudflared(port, port + 1)
  File "/usr/local/lib/python3.10/dist-packages/flask_cloudflared.py", line 69, in _run_cloudflared
    _download_cloudflared(cloudflared_path, command)
  File "/usr/local/lib/python3.10/dist-packages/flask_cloudflared.py", line 101, in _download_cloudflared
    update_cloudflared = subprocess.Popen([(cloudflared_path+'/'+command), 'update'], stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/tmp/cloudflared-linux-amd64'
Traceback (most recent call last):
  File "/content/Colab-TextGen/extensions/api/util.py", line 61, in _start_cloudflared
    public_url = _run_cloudflared(port, port + 1)
  File "/usr/local/lib/python3.10/dist-packages/flask_cloudflared.py", line 69, in _run_cloudflared
    _download_cloudflared(cloudflared_path, command)
  File "/usr/local/lib/python3.10/dist-packages/flask_cloudflared.py", line 101, in _download_cloudflared
    update_cloudflared = subprocess.Popen([(cloudflared_path+'/'+command), 'update'], stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/tmp/cloudflared-linux-amd64'
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /content/Colab-TextGen/server.py:1011 in <module>                            │
│                                                                              │
│   1008 │   │   })                                                            │
│   1009 │                                                                     │
│   1010 │   # Launch the web UI                                               │
│ ❱ 1011 │   create_interface()                                                │
│   1012 │   while True:                                                       │
│   1013 │   │   time.sleep(0.5)                                               │
│   1014 │   │   if shared.need_restart:                                       │
│                                                                              │
│ /content/Colab-TextGen/server.py:922 in create_interface                     │
│                                                                              │
│    919 │   if shared.args.listen:                                            │
│    920 │   │   shared.gradio['interface'].launch(prevent_thread_lock=True, s │
│    921 │   else:                                                             │
│ ❱  922 │   │   shared.gradio['interface'].launch(prevent_thread_lock=True, s │
│    923                                                                       │
│    924                                                                       │
│    925 if __name__ == "__main__":                                            │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/gradio/blocks.py:1727 in launch      │
│                                                                              │
│   1724 │   │   if not isinstance(self.blocked_paths, list):                  │
│   1725 │   │   │   raise ValueError("`blocked_paths` must be a list of direc │
│   1726 │   │                                                                 │
│ ❱ 1727 │   │   self.validate_queue_settings()                                │
│   1728 │   │                                                                 │
│   1729 │   │   self.config = self.get_config_file()                          │
│   1730 │   │   self.max_threads = max(                                       │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/gradio/blocks.py:1575 in             │
│ validate_queue_settings                                                      │
│                                                                              │
│   1572 │   │   │   │   )                                                     │
│   1573 │   │   │   for i in dep["cancels"]:                                  │
│   1574 │   │   │   │   if not self.queue_enabled_for_fn(i):                  │
│ ❱ 1575 │   │   │   │   │   raise ValueError(                                 │
│   1576 │   │   │   │   │   │   "Queue needs to be enabled! "                 │
│   1577 │   │   │   │   │   │   "You may get this error by either 1) passing  │
│   1578 │   │   │   │   │   │   "into an interface without enabling the queue │
╰──────────────────────────────────────────────────────────────────────────────╯
ValueError: Queue needs to be enabled! You may get this error by either 1) 
passing a function that uses the yield keyword into an interface without 
enabling the queue or 2) defining an event that cancels another event without 
enabling the queue. Both can be solved by calling .queue() before .launch()

**Comment by ksylvan** [comment]
I'm getting this without using `--no-stream` just trying to load bark_tts

```
CMD_FLAGS = '--api --chat --model-menu --trust-remote-code --extension bark_tts'
```

Using the latest text-generation-webui:

```
INFO:Loading the extension "bark_tts"...
[nltk_data] Downloading package punkt to /home/kayvan/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

== Loading Bark TTS extension ==
+ This may take a while on first run don't worry!
+ Creating directories (if they don't exist)...
+ Done!
+ Loading model...
INFO:model loaded: 312.3M params, 1.269 loss
INFO:model loaded: 314.4M params, 2.901 loss
INFO:model loaded: 302.1M params, 2.079 loss
+ Done!
== Bark TTS extension loaded ==


Starting streaming server at ws://127.0.0.1:5005/api/v1/stream
INFO:Loading the extension "gallery"...
Starting API at http://127.0.0.1:5000/api
INFO:server listening on 127.0.0.1:5005
Traceback (most recent call last):
  File "/home/kayvan/oobabooga_linux/text-generation-webui/server.py", line 1046, in <module>
    create_interface()
  File "/home/kayvan/oobabooga_linux/text-generation-webui/server.py", line 957, in create_interface
    shared.gradio['interface'].launch(prevent_thread_lock=True, share=shared.args.share, server_port=shared.args.listen_port, inbrowser=shared.args.auto_launch, auth=auth)
  File "/home/kayvan/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1727, in launch
    self.validate_queue_settings()
  File "/home/kayvan/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1575, in validate_queue_settings
    raise ValueError(
ValueError: Queue needs to be enabled! You may get this error by either 1) passing a function that uses the yield keyword into an interface without enabling the queue or 2) defining an event that cancels another event without enabling the queue. Both can be solved by calling .queue() before .launch()
```

**Comment by RagingJacob** [comment]
Yeahp same issue here when using `--no-stream` argument even though `.queue()` is already being called in `server.py`

**Comment by perkel666** [comment]
Same issue here.

**Comment by Rurounin** [comment]
Same here.

**Comment by Erthar** [comment]
Rolling back to the f052ab9 May 17 commit worked for me.

`git checkout f052ab9c8fed3dedc446c3847f10ab22e42bfb3A`

Whatever they added on the 19th or 20th broke something.

**Comment by ksylvan** [comment]
@Erthar Do you think you can narrow it down via `git bisect`? Does the next commit break it?

**Comment by Erthar** [comment]
@ksylvan Checked through each commit. It finally broke on a3e9769.

https://github.com/oobabooga/text-generation-webui/commit/a3e9769e31c9c813ee4068f9de40bc8116fef82a

But this shouldn't be an issue anymore. At least with the latest 78dbec4 commit.

https://github.com/oobabooga/text-generation-webui/commit/78dbec4c4e00c9e862ede67a3e04b31bd27896c3

I think this can be closed now.
