### ISSUE TITLE
OSERROR when model loading wizard-vicuna 13B where it says "no files named.."

### ISSUE THREAD

**Issue by oreocaty22** [oobabooga/text-generation-webui#2211]
### Describe the bug

I was just downloading normally a model for Oobabooga using the one-click install version, it is directly after oobabooga was done and it needed a model to download, so I chose the L option which is specifying the model, and copied then pasted TheBloke/Wizard-Vicuna-13B-Uncensored-GPTQ, and then got the OSError of "no files named..."

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Unsure how to reproduce it, I simply just did the one-click install, then chose my gpu nvidia, and copy pasted TheBloke/Wizard-Vicuna-13B-Uncensored-GPTQ and after it was done downloading and attempted loading the model, gave me the error. I even tried with TheBloke/wizard-mega-13B-GPTQ and gave the same error (the one in logs is wizard-mega)

### Screenshot

![OSERROR](https://github.com/oobabooga/text-generation-webui/assets/79416368/261c4d54-9ae9-48ae-a8fc-b1c88fc546bf)

### Logs

```shell
Traceback (most recent call last):
  File "D:\AI\webUI\oobabooga_windows\text-generation-webui\server.py", line 998, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\AI\webUI\oobabooga_windows\text-generation-webui\modules\models.py", line 95, in load_model
    output = load_func(model_name)
  File "D:\AI\webUI\oobabooga_windows\text-generation-webui\modules\models.py", line 153, in huggingface_loader
    model = LoaderClass.from_pretrained(Path(f"{shared.args.model_dir}/{model_name}"), low_cpu_mem_usage=True, torch_dtype=torch.bfloat16 if shared.args.bf16 else torch.float16, trust_remote_code=shared.args.trust_remote_code)
  File "D:\AI\webUI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 467, in from_pretrained
    return model_class.from_pretrained(
  File "D:\AI\webUI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2387, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory models\TheBloke_wizard-mega-13B-GPTQ.
```

### System Info

```shell
My gpu is an rtx 3060 12gb VRAM, 16gb RAM, and an i5 10400F.
```

**Comment by jllllll** [comment]
The webui uses the model's folder name to auto-detect gptq parameters. Either use the appropriate command-line arguments for that model, or add `-4bit-128g` to the end of the folder name.

**Comment by dchawisher** [comment]
> The webui uses the model's folder name to auto-detect gptq parameters. Either use the appropriate command-line arguments for that model, or add `-4bit-128g` to the end of the folder name.

I came here with the same problem. That fixes it, but now I get a new error:
`Traceback (most recent call last): File “C:\mypath\oobabooga_windows\text-generation-webui\server.py”, line 68, in load_model_wrapper shared.model, shared.tokenizer = load_model(shared.model_name) File “C:\mypath\oobabooga_windows\text-generation-webui\modules\models.py”, line 95, in load_model output = load_func(model_name) File “C:\mypath\oobabooga_windows\text-generation-webui\modules\models.py”, line 275, in GPTQ_loader model = modules.GPTQ_loader.load_quantized(model_name) File “C:\mypath\oobabooga_windows\text-generation-webui\modules\GPTQ_loader.py”, line 177, in load_quantized model = load_quant(str(path_to_model), str(pt_path), shared.args.wbits, shared.args.groupsize, kernel_switch_threshold=threshold) File “C:\mypath\oobabooga_windows\text-generation-webui\modules\GPTQ_loader.py”, line 84, in _load_quant model.load_state_dict(safe_load(checkpoint), strict=False) File “C:\mypath\oobabooga_windows\installer_files\env\lib\site-packages\safetensors\torch.py”, line 259, in load_file with safe_open(filename, framework=“pt”, device=device) as f: safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer`

**Comment by dchawisher** [comment]
Redownloading the model fixed that new error. I think it must have been unrelated.

**Comment by nathanleclaire** [comment]
I had some confusion over `OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory` trying to use Wizard installing from the UI. What I noticed in the Wizard instructions is that apparently you are supposed to just ignore this message, set wbits to 4, click "Save Settings", then "Reload Model", and you should be on your way. I also found that the CLI I have to run is `python server.py --wbits 4 --groupsize 128` (no idea why group size is set to None in UI, and 128 on CLI, I might be missing something)

**Comment by jllllll** [comment]
> I had some confusion over `OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory` trying to use Wizard installing from the UI. What I noticed in the Wizard instructions is that apparently you are supposed to just ignore this message, set wbits to 4, click "Save Settings", then "Reload Model", and you should be on your way. I also found that the CLI I have to run is `python server.py --wbits 4 --groupsize 128` (no idea why group size is set to None in UI, and 128 on CLI, I might be missing something)

https://github.com/oobabooga/text-generation-webui/issues/2211#issuecomment-1556052379

**Comment by amazingnerd** [comment]
Does anyone know how much VRAM is needed to set up this 13B model?

**Comment by jllllll** [comment]
> Does anyone know how much VRAM is needed to set up this 13B model?

If I remember correctly, ~9 GB.
