### ISSUE TITLE
TypeError: info() missing 1 required positional argument: 'msg' when trying to load in a soft-prompt

### ISSUE THREAD

**Issue by uyopi** [oobabooga/text-generation-webui#2215]
### Describe the bug

Whenever I try to load in a soft-prompt on the TextGen UI, I get an error "TypeError: info() missing 1 required positional argument: 'msg'" in the cmd window. The softprompt keeps trying to load in indefinitely in the UI.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Try to load in a softprompt on TextGen WebUI

### Logs

```shell
Traceback (most recent call last):
  File "C:\Nexus\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Nexus\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Nexus\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Nexus\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Nexus\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Nexus\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Nexus\oobabooga_windows\text-generation-webui\modules\models.py", line 344, in load_soft_prompt
    logging.info()
TypeError: info() missing 1 required positional argument: 'msg'
```

### System Info

```shell
System: Windows 10
GPU: NVIDIA GeForce RTX 3060
```

**Comment by oobabooga** [comment]
Fixed here https://github.com/oobabooga/text-generation-webui/commit/05593a783492bdcd526492a3231481cf68172509
