### ISSUE TITLE
failed to install GPTQ-for-LLaMa

### ISSUE THREAD

**Issue by phoenix8875** [oobabooga/text-generation-webui#2218]
### Describe the bug

I tried instlling gptq for llama using this 
pip install git+https://github.com/sterlind/GPTQ-for-LLaMa.git@lora_4bit
and getting error
  ERROR: Failed building wheel for gptq-llama
  Running setup.py clean for gptq-llama
Failed to build gptq-llama
Installing collected packages: gptq-llama
  Running setup.py install for gptq-llama ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for gptq-llama did not run successfully.
  │ exit code: 1
  ╰─> [127 lines of output]
      running install
      /home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/gptq_llama
      copying src/gptq_llama/test_performance.py -> build/lib.linux-x86_64-cpython-311/gptq_llama
      copying src/gptq_llama/gptq.py -> build/lib.linux-x86_64-cpython-311/gptq_llama
      copying src/gptq_llama/modelutils.py -> build/lib.linux-x86_64-cpython-311/gptq_llama
      copying src/gptq_llama/llama_inference_offload.py -> build/lib.linux-x86_64-cpython-311/gptq_llama
      copying src/gptq_llama/opt.py -> build/lib.linux-x86_64-cpython-311/gptq_llama
      copying src/gptq_llama/datautils.py -> build/lib.linux-x86_64-cpython-311/gptq_llama
      copying src/gptq_llama/quant.py -> build/lib.linux-x86_64-cpython-311/gptq_llama
      copying src/gptq_llama/llama.py -> build/lib.linux-x86_64-cpython-311/gptq_llama
      copying src/gptq_llama/convert_llama_weights_to_hf.py -> build/lib.linux-x86_64-cpython-311/gptq_llama
      copying src/gptq_llama/llama_inference.py -> build/lib.linux-x86_64-cpython-311/gptq_llama
      copying src/gptq_llama/__init__.py -> build/lib.linux-x86_64-cpython-311/gptq_llama
      running build_ext
      building 'gptq_llama.quant_cuda' extension
      creating /tmp/pip-req-build-riz5rkil/build/temp.linux-x86_64-cpython-311
      creating /tmp/pip-req-build-riz5rkil/build/temp.linux-x86_64-cpython-311/src
      creating /tmp/pip-req-build-riz5rkil/build/temp.linux-x86_64-cpython-311/src/gptq_llama
      creating /tmp/pip-req-build-riz5rkil/build/temp.linux-x86_64-cpython-311/src/gptq_llama/quant_cuda
      Emitting ninja build file /tmp/pip-req-build-riz5rkil/build/temp.linux-x86_64-cpython-311/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/2] /home/tensax/anaconda3/envs/wizard/bin/nvcc  -I/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include -I/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -I/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include/TH -I/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include/THC -I/home/tensax/anaconda3/envs/wizard/include -I/home/tensax/anaconda3/envs/wizard/include/python3.11 -c -c /tmp/pip-req-build-riz5rkil/src/gptq_llama/quant_cuda/quant_cuda_kernel.cu -o /tmp/pip-req-build-riz5rkil/build/temp.linux-x86_64-cpython-311/src/gptq_llama/quant_cuda/quant_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=quant_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++17
      FAILED: /tmp/pip-req-build-riz5rkil/build/temp.linux-x86_64-cpython-311/src/gptq_llama/quant_cuda/quant_cuda_kernel.o
      /home/tensax/anaconda3/envs/wizard/bin/nvcc  -I/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include -I/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -I/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include/TH -I/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include/THC -I/home/tensax/anaconda3/envs/wizard/include -I/home/tensax/anaconda3/envs/wizard/include/python3.11 -c -c /tmp/pip-req-build-riz5rkil/src/gptq_llama/quant_cuda/quant_cuda_kernel.cu -o /tmp/pip-req-build-riz5rkil/build/temp.linux-x86_64-cpython-311/src/gptq_llama/quant_cuda/quant_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=quant_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++17
      /home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
                detected during:
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
      (61): here
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
      /home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include/c10/core/TensorImpl.h(77): here
      
      /home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
                detected during:
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
      (61): here
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
      /home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include/ATen/core/qualified_name.h(73): here
      
      /tmp/pip-req-build-riz5rkil/src/gptq_llama/quant_cuda/quant_cuda_kernel.cu(958): error: no instance of overloaded function "atomicAdd" matches the argument list
                  argument types are: (__half *, c10::Half)
                detected during instantiation of "void VecQuant4MatMulKernelFaster(const half2 *, const int *, scalar_t *, const scalar_t *, const int *, const int *, int, int, int, int, int) [with scalar_t=c10::Half]"
      (879): here
      
      /tmp/pip-req-build-riz5rkil/src/gptq_llama/quant_cuda/quant_cuda_kernel.cu(1128): error: no instance of overloaded function "atomicAdd" matches the argument list
                  argument types are: (__half *, c10::Half)
                detected during instantiation of "void VecQuant4MatMulV1KernelFaster(const half2 *, const int *, scalar_t *, const scalar_t *, const scalar_t *, int, int, int, int) [with scalar_t=c10::Half]"
      (1150): here
      
      2 errors detected in the compilation of "/tmp/pip-req-build-riz5rkil/src/gptq_llama/quant_cuda/quant_cuda_kernel.cu".
      [2/2] c++ -MMD -MF /tmp/pip-req-build-riz5rkil/build/temp.linux-x86_64-cpython-311/src/gptq_llama/quant_cuda/quant_cuda.o.d -pthread -B /home/tensax/anaconda3/envs/wizard/compiler_compat -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/tensax/anaconda3/envs/wizard/include -fPIC -O2 -isystem /home/tensax/anaconda3/envs/wizard/include -fPIC -I/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include -I/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -I/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include/TH -I/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include/THC -I/home/tensax/anaconda3/envs/wizard/include -I/home/tensax/anaconda3/envs/wizard/include/python3.11 -c -c /tmp/pip-req-build-riz5rkil/src/gptq_llama/quant_cuda/quant_cuda.cpp -o /tmp/pip-req-build-riz5rkil/build/temp.linux-x86_64-cpython-311/src/gptq_llama/quant_cuda/quant_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=quant_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
          subprocess.run(
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-riz5rkil/setup.py", line 4, in <module>
          setup(
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
          build_ext.build_extensions(self)
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
          self._build_extensions_serial()
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 549, in build_extension
          objects = self.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> gptq-llama

general inference is working fine but in --monkey-patch getting "no module named gptq for llama"
tried clean install of  nvcc then running "python setup_cuda install" from text-generation-webui/repositories/GPTQ-for-LLaMa
installed quan cuda but while trying to install
pip install git+https://github.com/sterlind/GPTQ-for-LLaMa.git@lora_4bit
still same error its working in colab but not on my device

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

pip install git+https://github.com/sterlind/GPTQ-for-LLaMa.git@lora_4bit

### Logs

```shell
ERROR: Failed building wheel for gptq-llama
  Running setup.py clean for gptq-llama
Failed to build gptq-llama
Installing collected packages: gptq-llama
  Running setup.py install for gptq-llama ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for gptq-llama did not run successfully.
  │ exit code: 1
  ╰─> [127 lines of output]
      running install
      /home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/gptq_llama
      copying src/gptq_llama/test_performance.py -> build/lib.linux-x86_64-cpython-311/gptq_llama
      copying src/gptq_llama/gptq.py -> build/lib.linux-x86_64-cpython-311/gptq_llama
      copying src/gptq_llama/modelutils.py -> build/lib.linux-x86_64-cpython-311/gptq_llama
      copying src/gptq_llama/llama_inference_offload.py -> build/lib.linux-x86_64-cpython-311/gptq_llama
      copying src/gptq_llama/opt.py -> build/lib.linux-x86_64-cpython-311/gptq_llama
      copying src/gptq_llama/datautils.py -> build/lib.linux-x86_64-cpython-311/gptq_llama
      copying src/gptq_llama/quant.py -> build/lib.linux-x86_64-cpython-311/gptq_llama
      copying src/gptq_llama/llama.py -> build/lib.linux-x86_64-cpython-311/gptq_llama
      copying src/gptq_llama/convert_llama_weights_to_hf.py -> build/lib.linux-x86_64-cpython-311/gptq_llama
      copying src/gptq_llama/llama_inference.py -> build/lib.linux-x86_64-cpython-311/gptq_llama
      copying src/gptq_llama/__init__.py -> build/lib.linux-x86_64-cpython-311/gptq_llama
      running build_ext
      building 'gptq_llama.quant_cuda' extension
      creating /tmp/pip-req-build-riz5rkil/build/temp.linux-x86_64-cpython-311
      creating /tmp/pip-req-build-riz5rkil/build/temp.linux-x86_64-cpython-311/src
      creating /tmp/pip-req-build-riz5rkil/build/temp.linux-x86_64-cpython-311/src/gptq_llama
      creating /tmp/pip-req-build-riz5rkil/build/temp.linux-x86_64-cpython-311/src/gptq_llama/quant_cuda
      Emitting ninja build file /tmp/pip-req-build-riz5rkil/build/temp.linux-x86_64-cpython-311/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/2] /home/tensax/anaconda3/envs/wizard/bin/nvcc  -I/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include -I/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -I/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include/TH -I/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include/THC -I/home/tensax/anaconda3/envs/wizard/include -I/home/tensax/anaconda3/envs/wizard/include/python3.11 -c -c /tmp/pip-req-build-riz5rkil/src/gptq_llama/quant_cuda/quant_cuda_kernel.cu -o /tmp/pip-req-build-riz5rkil/build/temp.linux-x86_64-cpython-311/src/gptq_llama/quant_cuda/quant_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=quant_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++17
      FAILED: /tmp/pip-req-build-riz5rkil/build/temp.linux-x86_64-cpython-311/src/gptq_llama/quant_cuda/quant_cuda_kernel.o
      /home/tensax/anaconda3/envs/wizard/bin/nvcc  -I/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include -I/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -I/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include/TH -I/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include/THC -I/home/tensax/anaconda3/envs/wizard/include -I/home/tensax/anaconda3/envs/wizard/include/python3.11 -c -c /tmp/pip-req-build-riz5rkil/src/gptq_llama/quant_cuda/quant_cuda_kernel.cu -o /tmp/pip-req-build-riz5rkil/build/temp.linux-x86_64-cpython-311/src/gptq_llama/quant_cuda/quant_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=quant_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++17
      /home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
                detected during:
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
      (61): here
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
      /home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include/c10/core/TensorImpl.h(77): here
      
      /home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
                detected during:
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
      (61): here
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
      /home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include/ATen/core/qualified_name.h(73): here
      
      /tmp/pip-req-build-riz5rkil/src/gptq_llama/quant_cuda/quant_cuda_kernel.cu(958): error: no instance of overloaded function "atomicAdd" matches the argument list
                  argument types are: (__half *, c10::Half)
                detected during instantiation of "void VecQuant4MatMulKernelFaster(const half2 *, const int *, scalar_t *, const scalar_t *, const int *, const int *, int, int, int, int, int) [with scalar_t=c10::Half]"
      (879): here
      
      /tmp/pip-req-build-riz5rkil/src/gptq_llama/quant_cuda/quant_cuda_kernel.cu(1128): error: no instance of overloaded function "atomicAdd" matches the argument list
                  argument types are: (__half *, c10::Half)
                detected during instantiation of "void VecQuant4MatMulV1KernelFaster(const half2 *, const int *, scalar_t *, const scalar_t *, const scalar_t *, int, int, int, int) [with scalar_t=c10::Half]"
      (1150): here
      
      2 errors detected in the compilation of "/tmp/pip-req-build-riz5rkil/src/gptq_llama/quant_cuda/quant_cuda_kernel.cu".
      [2/2] c++ -MMD -MF /tmp/pip-req-build-riz5rkil/build/temp.linux-x86_64-cpython-311/src/gptq_llama/quant_cuda/quant_cuda.o.d -pthread -B /home/tensax/anaconda3/envs/wizard/compiler_compat -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/tensax/anaconda3/envs/wizard/include -fPIC -O2 -isystem /home/tensax/anaconda3/envs/wizard/include -fPIC -I/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include -I/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -I/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include/TH -I/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/include/THC -I/home/tensax/anaconda3/envs/wizard/include -I/home/tensax/anaconda3/envs/wizard/include/python3.11 -c -c /tmp/pip-req-build-riz5rkil/src/gptq_llama/quant_cuda/quant_cuda.cpp -o /tmp/pip-req-build-riz5rkil/build/temp.linux-x86_64-cpython-311/src/gptq_llama/quant_cuda/quant_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=quant_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
          subprocess.run(
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-riz5rkil/setup.py", line 4, in <module>
          setup(
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
          build_ext.build_extensions(self)
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
          self._build_extensions_serial()
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 549, in build_extension
          objects = self.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/home/tensax/anaconda3/envs/wizard/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> gptq-llama
```

### System Info

```shell
DELL G7
Ubuntu 20.04
Nvidia 1060 M
VRAM 6 GB
RAM 20 GB
```

**Comment by jllllll** [comment]
The error you got is indicative of an unsupported gpu. The code it is trying to compile requires a minimum compute of 7.0. Your gpu uses 6.1.

**Comment by phoenix8875** [comment]
> The error you got is indicative of an unsupported gpu. The code it is trying to compile requires a minimum compute of 7.0. Your gpu uses 6.1.

oh! Thanks ,I'll give it a try using a different device

**Comment by jllllll** [comment]
> > The error you got is indicative of an unsupported gpu. The code it is trying to compile requires a minimum compute of 7.0. Your gpu uses 6.1.
> 
> oh! Thanks ,I'll give it a try using a different device

You can choose which gpus to compile for using the `TORCH_CUDA_ARCH_LIST` environment variable. For instance, setting it to
`7.0 7.5 8.0 8.6+PTX` will compile for every architecture that this code supports under cuda 11.7. If you use a newer cuda toolkit, you can compile for `8.9 9.0` as well.

Keep in mind that, while you can compile for any architecture irrespective of the gpu that is installed, the resulting program will only run on a gpu that is supported. The `+PTX` part means that gpus newer than that arch will be able to compile it's own code on the fly.

**Comment by Ph0rk0z** [comment]
Yep..that new repo is not compatible. You have to roll back to https://github.com/sterlind/GPTQ-for-LLaMa/commit/eaa9955d8700dc8566f0c443054233e9c4503f66

Also because of FP16 it works more slowly on that card. I was able to fix it in my GPTQ version and fork.
