### ISSUE TITLE
AttributeError: module 'bitsandbytes.nn' has no attribute 'Linear4bit'. Did you mean: 'Linear8bitLt'?

### ISSUE THREAD

**Issue by ikt100** [oobabooga/text-generation-webui#2225]
### Describe the bug

After installing the webui on Windows and trying to start it with the only model installed (gpt4-x-alpaca-13b-native-4bit-128g) it gives an error:

AttributeError: module 'bitsandbytes.nn' has no attribute 'Linear4bit'. Did you mean: 'Linear8bitLt'?

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Reproduction

Trying to start the webui always returns the same error.

### Screenshot

![Näyttökuva 2023-05-20 211851](https://github.com/oobabooga/text-generation-webui/assets/60978445/1a96535f-7d48-4250-8d14-ee84dcad5adc)

### Logs

```shell
bin D:\oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
Traceback (most recent call last):
  File "D:\oobabooga\oobabooga_windows\text-generation-webui\server.py", line 47, in <module>
    from modules import chat, shared, training, ui, utils
  File "D:\oobabooga\oobabooga_windows\text-generation-webui\modules\training.py", line 14, in <module>
    from peft import (LoraConfig, get_peft_model, prepare_model_for_int8_training,
  File "D:\oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "D:\oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\peft\mapping.py", line 16, in <module>
    from .peft_model import (
  File "D:\oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\peft\peft_model.py", line 31, in <module>
    from .tuners import (
  File "D:\oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\peft\tuners\__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel
  File "D:\oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\peft\tuners\lora.py", line 735, in <module>
    class Linear4bit(bnb.nn.Linear4bit, LoraLayer):
AttributeError: module 'bitsandbytes.nn' has no attribute 'Linear4bit'. Did you mean: 'Linear8bitLt'?

Done!
Press any key to continue . . .
```

### System Info

```shell
Windows 11, NVIDIA GeForce RTX 2070 (8 Gb)
```

**Comment by ikt100** [comment]
Ok, going to the lora.py file and deleting everything that includes the Linear4bit seems to work.
