### ISSUE TITLE
[ BUG ] Incompatible with M1 Mac

### ISSUE THREAD

**Issue by ibehnam** [oobabooga/text-generation-webui#2240]
### Describe the bug

I followed the instructions and made sure to pay attention to [this](https://github.com/oobabooga/text-generation-webui/pull/393) as well.

However, upon running the server `python server.py`, I get:

```
Traceback (most recent call last):
  File "/Users/behnam/Downloads/text-generation-webui/server.py", line 21, in <module>
    import gradio as gr
  File "/Users/behnam/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/Users/behnam/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/gradio/components.py", line 56, in <module>
    from gradio.blocks import Block, BlockContext
  File "/Users/behnam/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 26, in <module>
    from gradio import (
  File "/Users/behnam/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/gradio/networking.py", line 17, in <module>
    from gradio.routes import App
  File "/Users/behnam/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/gradio/routes.py", line 24, in <module>
    import orjson
  File "/Users/behnam/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/orjson/__init__.py", line 3, in <module>
    from .orjson import *
ImportError: dlopen(/Users/behnam/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/orjson/orjson.cpython-310-darwin.so, 0x0002): tried: '/Users/behnam/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/orjson/orjson.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/behnam/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/orjson/orjson.cpython-310-darwin.so' (no such file), '/Users/behnam/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/orjson/orjson.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
```

I tried running the terminal in Rosetta mode but still got the same error.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Follow the instructions and pay attention to [this](https://github.com/oobabooga/text-generation-webui/pull/393) as well.

Then run the server `python server.py`.

### Logs

```shell
Traceback (most recent call last):
  File "/Users/behnam/Downloads/text-generation-webui/server.py", line 21, in <module>
    import gradio as gr
  File "/Users/behnam/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/Users/behnam/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/gradio/components.py", line 56, in <module>
    from gradio.blocks import Block, BlockContext
  File "/Users/behnam/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 26, in <module>
    from gradio import (
  File "/Users/behnam/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/gradio/networking.py", line 17, in <module>
    from gradio.routes import App
  File "/Users/behnam/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/gradio/routes.py", line 24, in <module>
    import orjson
  File "/Users/behnam/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/orjson/__init__.py", line 3, in <module>
    from .orjson import *
ImportError: dlopen(/Users/behnam/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/orjson/orjson.cpython-310-darwin.so, 0x0002): tried: '/Users/behnam/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/orjson/orjson.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/behnam/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/orjson/orjson.cpython-310-darwin.so' (no such file), '/Users/behnam/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/orjson/orjson.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
```
```


### System Info

```shell
M1 Mac, Ventura 13.3.1 (22E261)
```

**Comment by bpben** [comment]
Downgrading orjson worked for me on M1 mac:

`pip install orjson==3.8.1`

**Comment by ibehnam** [comment]
> Downgrading orjson worked for me on M1 mac:
> 
> `pip install orjson==3.8.1`

Do you use MPS or CPU?
