### ISSUE TITLE
webui.py and not server.py

### ISSUE THREAD

**Issue by opnoobkiller** [oobabooga/text-generation-webui#2275]
### Describe the bug

who else is watching 20 videos where they all somehow have start-webui.bat meanwhile I have start-windows.bat and because of that I can't run parameters like --gpu-memory 5 to fix my issue with ram, alpaca tries to reserve more ram then you have on your system

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

start up "start-windows.bat" file and launch gpt alpaca.

### Logs

```shell
INFO:Loading gpt4-x-alpaca-13b-native-4bit-128g...
INFO:Found the following quantized model: models\gpt4-x-alpaca-13b-native-4bit-128g\gpt-x-alpaca-13b-native-4bit-128g-cuda.pt
Traceback (most recent call last):
  File "C:\Users\rainb\Downloads\ai\b\text-generation-webui\server.py", line 1045, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\rainb\Downloads\ai\b\text-generation-webui\modules\models.py", line 95, in load_model
    output = load_func(model_name)
  File "C:\Users\rainb\Downloads\ai\b\text-generation-webui\modules\models.py", line 275, in GPTQ_loader
    model = modules.GPTQ_loader.load_quantized(model_name)
  File "C:\Users\rainb\Downloads\ai\b\text-generation-webui\modules\GPTQ_loader.py", line 177, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.wbits, shared.args.groupsize, kernel_switch_threshold=threshold)
  File "C:\Users\rainb\Downloads\ai\b\text-generation-webui\modules\GPTQ_loader.py", line 86, in _load_quant
    model.load_state_dict(torch.load(checkpoint), strict=False)
  File "C:\Users\rainb\Downloads\ai\b\installer_files\env\lib\site-packages\torch\serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\rainb\Downloads\ai\b\installer_files\env\lib\site-packages\torch\serialization.py", line 1172, in _load
    result = unpickler.load()
  File "C:\Users\rainb\Downloads\ai\b\installer_files\env\lib\site-packages\torch\serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "C:\Users\rainb\Downloads\ai\b\installer_files\env\lib\site-packages\torch\serialization.py", line 1112, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage)._typed_storage()._untyped_storage
RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 35389440 bytes.
```

### System Info

```shell
RTX 3070 TI, Windows 10, ATX motherboard
```

**Comment by rebelangel13** [comment]
You have to code it into the webui.py file now...if you open it up in a text or code editor you will see at the top where to add the tags
