### ISSUE TITLE
ModuleNotFoundError: No module named 'pyparsing'

### ISSUE THREAD

**Issue by Ege-P** [oobabooga/text-generation-webui#2276]
### Describe the bug

When I try to open the webUI from "start-webui.bat", I'm getting this error: ModuleNotFoundError: No module named 'pyparsing'

But when I try to manually download the module, it says already satisfied. I tried to add to python path as well but its already there as well.

The last thing I did was installing privateGPT, which I believe did something.

When I try to open server.py instead, I'm getting error related to CUDA I think. I'll include that error in log as well.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

execute start-webui.bat file

### Logs

```shell
Traceback (most recent call last):
  File "D:\ALLAI\AIChatUI\text-generation-webui\server.py", line 22, in <module>
    import gradio as gr
  File "D:\ALLAI\AIChatUI\installer_files\env\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "D:\ALLAI\AIChatUI\installer_files\env\lib\site-packages\gradio\components.py", line 26, in <module>
    import matplotlib.figure
  File "C:\Users\ege\AppData\Roaming\Python\Python310\site-packages\matplotlib\__init__.py", line 148, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "C:\Users\ege\AppData\Roaming\Python\Python310\site-packages\matplotlib\rcsetup.py", line 28, in <module>
    from matplotlib._fontconfig_pattern import parse_fontconfig_pattern
  File "C:\Users\ege\AppData\Roaming\Python\Python310\site-packages\matplotlib\_fontconfig_pattern.py", line 15, in <module>
    from pyparsing import (
ModuleNotFoundError: No module named 'pyparsing'
Press any key to continue . . .




CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
C:\Users\ege\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cuda_setup\paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA SETUP: Loading binary C:\Users\ege\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\ALLAI\AIChatUI\text-generation-webui\server.py:48 in <module>                                 │
│                                                                                                  │
│     45 from PIL import Image                                                                     │
│     46                                                                                           │
│     47 import modules.extensions as extensions_module                                            │
│ ❱   48 from modules import chat, shared, training, ui, utils                                     │
│     49 from modules.extensions import apply_extensions                                           │
│     50 from modules.html_generator import chat_html_wrapper                                      │
│     51 from modules.LoRA import add_lora_to_model                                                │
│                                                                                                  │
│ D:\ALLAI\AIChatUI\text-generation-webui\modules\training.py:13 in <module>                       │
│                                                                                                  │
│    10 import torch                                                                               │
│    11 import transformers                                                                        │
│    12 from datasets import Dataset, load_dataset                                                 │
│ ❱  13 from peft import (LoraConfig, get_peft_model, prepare_model_for_int8_training,             │
│    14 │   │   │   │     set_peft_model_state_dict)                                               │
│    15                                                                                            │
│    16 from modules import shared, ui, utils                                                      │
│                                                                                                  │
│ C:\Users\ege\AppData\Local\Programs\Python\Python310\lib\site-packages\peft\__init__.py:22 in    │
│ <module>                                                                                         │
│                                                                                                  │
│   19                                                                                             │
│   20 __version__ = "0.4.0.dev0"                                                                  │
│   21                                                                                             │
│ ❱ 22 from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_    │
│   23 from .peft_model import (                                                                   │
│   24 │   PeftModel,                                                                              │
│   25 │   PeftModelForCausalLM,                                                                   │
│                                                                                                  │
│ C:\Users\ege\AppData\Local\Programs\Python\Python310\lib\site-packages\peft\mapping.py:16 in     │
│ <module>                                                                                         │
│                                                                                                  │
│    13 # See the License for the specific language governing permissions and                      │
│    14 # limitations under the License.                                                           │
│    15                                                                                            │
│ ❱  16 from .peft_model import (                                                                  │
│    17 │   PeftModel,                                                                             │
│    18 │   PeftModelForCausalLM,                                                                  │
│    19 │   PeftModelForSeq2SeqLM,                                                                 │
│                                                                                                  │
│ C:\Users\ege\AppData\Local\Programs\Python\Python310\lib\site-packages\peft\peft_model.py:31 in  │
│ <module>                                                                                         │
│                                                                                                  │
│     28 from transformers.modeling_outputs import SequenceClassifierOutput, TokenClassifierOutpu  │
│     29 from transformers.utils import PushToHubMixin                                             │
│     30                                                                                           │
│ ❱   31 from .tuners import (                                                                     │
│     32 │   AdaLoraModel,                                                                         │
│     33 │   AdaptionPromptModel,                                                                  │
│     34 │   LoraModel,                                                                            │
│                                                                                                  │
│ C:\Users\ege\AppData\Local\Programs\Python\Python310\lib\site-packages\peft\tuners\__init__.py:2 │
│ 1 in <module>                                                                                    │
│                                                                                                  │
│   18 # limitations under the License.                                                            │
│   19                                                                                             │
│   20 from .adaption_prompt import AdaptionPromptConfig, AdaptionPromptModel                      │
│ ❱ 21 from .lora import LoraConfig, LoraModel                                                     │
│   22 from .adalora import AdaLoraConfig, AdaLoraModel                                            │
│   23 from .p_tuning import PromptEncoder, PromptEncoderConfig, PromptEncoderReparameterizatio    │
│   24 from .prefix_tuning import PrefixEncoder, PrefixTuningConfig                                │
│                                                                                                  │
│ C:\Users\ege\AppData\Local\Programs\Python\Python310\lib\site-packages\peft\tuners\lora.py:40 in │
│ <module>                                                                                         │
│                                                                                                  │
│    37                                                                                            │
│    38                                                                                            │
│    39 if is_bnb_available():                                                                     │
│ ❱  40 │   import bitsandbytes as bnb                                                             │
│    41                                                                                            │
│    42                                                                                            │
│    43 @dataclass                                                                                 │
│                                                                                                  │
│ C:\Users\ege\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\__init__.py: │
│ 6 in <module>                                                                                    │
│                                                                                                  │
│    3 # This source code is licensed under the MIT license found in the                           │
│    4 # LICENSE file in the root directory of this source tree.                                   │
│    5                                                                                             │
│ ❱  6 from .autograd._functions import (                                                          │
│    7 │   MatmulLtState,                                                                          │
│    8 │   bmm_cublas,                                                                             │
│    9 │   matmul,                                                                                 │
│                                                                                                  │
│ C:\Users\ege\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\autograd\_fu │
│ nctions.py:5 in <module>                                                                         │
│                                                                                                  │
│     2 import warnings                                                                            │
│     3                                                                                            │
│     4 import torch                                                                               │
│ ❱   5 import bitsandbytes.functional as F                                                        │
│     6                                                                                            │
│     7 from dataclasses import dataclass                                                          │
│     8 from functools import reduce  # Required in Python 3                                       │
│                                                                                                  │
│ C:\Users\ege\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\functional.p │
│ y:13 in <module>                                                                                 │
│                                                                                                  │
│     10 from typing import Tuple                                                                  │
│     11 from torch import Tensor                                                                  │
│     12                                                                                           │
│ ❱   13 from .cextension import COMPILED_WITH_CUDA, lib                                           │
│     14 from functools import reduce  # Required in Python 3                                      │
│     15                                                                                           │
│     16 # math.prod not compatible with python < 3.8                                              │
│                                                                                                  │
│ C:\Users\ege\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cextension.p │
│ y:41 in <module>                                                                                 │
│                                                                                                  │
│   38 │   │   return cls._instance                                                                │
│   39                                                                                             │
│   40                                                                                             │
│ ❱ 41 lib = CUDALibrary_Singleton.get_instance().lib                                              │
│   42 try:                                                                                        │
│   43 │   lib.cadam32bit_g32                                                                      │
│   44 │   lib.get_context.restype = ct.c_void_p                                                   │
│                                                                                                  │
│ C:\Users\ege\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cextension.p │
│ y:37 in get_instance                                                                             │
│                                                                                                  │
│   34 │   def get_instance(cls):                                                                  │
│   35 │   │   if cls._instance is None:                                                           │
│   36 │   │   │   cls._instance = cls.__new__(cls)                                                │
│ ❱ 37 │   │   │   cls._instance.initialize()                                                      │
│   38 │   │   return cls._instance                                                                │
│   39                                                                                             │
│   40                                                                                             │
│                                                                                                  │
│ C:\Users\ege\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cextension.p │
│ y:31 in initialize                                                                               │
│                                                                                                  │
│   28 │   │   │   self.lib = ct.cdll.LoadLibrary(binary_path)                                     │
│   29 │   │   else:                                                                               │
│   30 │   │   │   print(f"CUDA SETUP: Loading binary {binary_path}...")                           │
│ ❱ 31 │   │   │   self.lib = ct.cdll.LoadLibrary(binary_path)                                     │
│   32 │                                                                                           │
│   33 │   @classmethod                                                                            │
│   34 │   def get_instance(cls):                                                                  │
│                                                                                                  │
│ C:\Users\ege\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py:452 in LoadLibrary   │
│                                                                                                  │
│   449 │   │   return getattr(self, name)                                                         │
│   450 │                                                                                          │
│   451 │   def LoadLibrary(self, name):                                                           │
│ ❱ 452 │   │   return self._dlltype(name)                                                         │
│   453 │                                                                                          │
│   454 │   __class_getitem__ = classmethod(_types.GenericAlias)                                   │
│   455                                                                                            │
│                                                                                                  │
│ C:\Users\ege\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py:364 in __init__      │
│                                                                                                  │
│   361 │   │   │   else:                                                                          │
│   362 │   │   │   │   import nt                                                                  │
│   363 │   │   │   │   mode = nt._LOAD_LIBRARY_SEARCH_DEFAULT_DIRS                                │
│ ❱ 364 │   │   │   │   if '/' in name or '\\' in name:                                            │
│   365 │   │   │   │   │   self._name = nt._getfullpathname(self._name)                           │
│   366 │   │   │   │   │   mode |= nt._LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR                           │
│   367                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: argument of type 'WindowsPath' is not iterable
```

### System Info

```shell
Windows 10
GeForce RTX 4090 GIGABYTE
AMD Ryzen 9 7950x
```

**Comment by Ege-P** [comment]
Requirement already satisfied: pyparsing in c:\users\ege\appdata\local\programs\python\python310\lib\site-packages (2.4.7)
