### ISSUE TITLE
NameError: name 'quant_cuda' is not defined

### ISSUE THREAD

**Issue by ShadowStorm0** [oobabooga/text-generation-webui#228]
I get this error after running these two commands for load-in-4bit, `NameError: name 'quant_cuda' is not defined` after running `conda activate textgen` and `python3.9 server.py --model llama-7b --load-in-4bit`than clicking *generate*

**Comment by Ether90** [comment]
I have the same problem. Followed this Tutorial: https://www.reddit.com/r/LocalLLaMA/comments/11o6o3f/how_to_install_llama_8bit_and_4bit/

**Comment by Ether90** [comment]
> 

I fixed it. 
This step gave me an error before and I did not saw it : python setup_cuda.py install
**UserWarning: It seems that the VC environment is activated but DISTUTILS_USE_SDK is not set.This may lead to multiple activations of the VC env.Please set `DISTUTILS_USE_SDK=1` and try again.**

I just created a new User System-Variable DISTUTILS_USE_SDK and set the value to 1. After that, the install prompt worked and the UI generated with no errors.

**Comment by ShadowStorm0** [comment]
on my Linux system, I entered `export DISTUTILS_USE_SDK=1` and restarted and ran `python3.9 server.py --load-in-4bit --model llama-7b` I still get the same error

**Comment by mastoca** [comment]
I was able to go into the `repositories/GPTQ-for-LLaMa]` directory and run `python setup_cuda.py`

**Comment by kdubey22** [comment]
> I am experiencing this issue as well with `python server.py --model llama-7b-4bit --wbits 4`
> 
> The following did not resolve the issue for me.
> 
> > I was able to go into the `repositories/GPTQ-for-LLaMa` directory and run `python setup_cuda.py`
> > PS: you must be in your pyenv etc already before doing the setup above...etc.
> 
> **Logs** on Startup issues:
> 
> 1. `CUDA SETUP: Detected CUDA version 117` however later `CUDA extension not installed.`
> 2. Warnings regarding TypedStorage : `UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()   storage = cls(wrap_storage=untyped_storage)`
> 
> ```
> Starting the web UI...
> 
> ===================================BUG REPORT===================================
> Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
> ================================================================================
> CUDA SETUP: CUDA runtime path found: F:\AI\oobabooga\installer_files\env\bin\cudart64_110.dll
> CUDA SETUP: Highest compute capability among GPUs detected: 7.5
> CUDA SETUP: Detected CUDA version 117
> CUDA SETUP: Loading binary F:\AI\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
> Loading llama-7b-4bit...
> CUDA extension not installed.
> Found the following quantized model: models\llama-7b-4bit\llama-7b-4bit.safetensors
> Loading model ...
> F:\AI\oobabooga\installer_files\env\lib\site-packages\safetensors\torch.py:99: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
>   with safe_open(filename, framework="pt", device=device) as f:
> F:\AI\oobabooga\installer_files\env\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
>   return self.fget.__get__(instance, owner)()
> F:\AI\oobabooga\installer_files\env\lib\site-packages\torch\storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
>   storage = cls(wrap_storage=untyped_storage)
> Done.
> Loaded the model in 1.95 seconds.
> Running on local URL:  http://127.0.0.1:7860
> 
> To create a public link, set `share=True` in `launch()`.
> ```
> 
> Error on executing a prompt
> 
> 1. Error `NameError: name 'quant_cuda' is not defined`
> 
> ```
> Traceback (most recent call last):
>   File "F:\AI\oobabooga\text-generation-webui\modules\callbacks.py", line 66, in gentask
>     ret = self.mfunc(callback=_callback, **self.kwargs)
>   File "F:\AI\oobabooga\text-generation-webui\modules\text_generation.py", line 234, in generate_with_callback
>     shared.model.generate(**kwargs)
>   File "F:\AI\oobabooga\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "F:\AI\oobabooga\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1485, in generate
>     return self.sample(
>   File "F:\AI\oobabooga\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 2524, in sample
>     outputs = self(
>   File "F:\AI\oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "F:\AI\oobabooga\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 687, in forward
>     outputs = self.model(
>   File "F:\AI\oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "F:\AI\oobabooga\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 577, in forward
>     layer_outputs = decoder_layer(
>   File "F:\AI\oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "F:\AI\oobabooga\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 292, in forward
>     hidden_states, self_attn_weights, present_key_value = self.self_attn(
>   File "F:\AI\oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "F:\AI\oobabooga\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 196, in forward
>     query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
>   File "F:\AI\oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "F:\AI\oobabooga\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 426, in forward
>     quant_cuda.vecquant4matmul(x, self.qweight, y, self.scales, self.qzeros, self.groupsize)
> NameError: name 'quant_cuda' is not defined
> Output generated in 0.34 seconds (0.00 tokens/s, 0 tokens, context 16, seed 1163117151)
> ```
> 
> The things I've tried:
> 
> * A completely fresh install as of the date of this post utilizing the latest installer.
> * Manually installing GPTQ for LLaMa and experimenting with different versions
> * A fresh download of LLaMa models
> * experimented with different versions CUDA 117 and 118 with reinstalls for each test
> 
> I adapted the following bat to automate the install GPTQ for LLaMa.
> 
> 1. `conda install -c conda-forge cudatoolkit-dev`
> 2. Run this bat
> 
> ```batchfile
> @echo off
> 
> @echo Starting the web UI...
> 
> cd /D "%~dp0"
> 
> set MAMBA_ROOT_PREFIX=%cd%\installer_files\mamba
> set INSTALL_ENV_DIR=%cd%\installer_files\env
> 
> if not exist "%MAMBA_ROOT_PREFIX%\condabin\micromamba.bat" (
>   call "%MAMBA_ROOT_PREFIX%\micromamba.exe" shell hook >nul 2>&1
> )
> call "%MAMBA_ROOT_PREFIX%\condabin\micromamba.bat" activate "%INSTALL_ENV_DIR%" || ( echo MicroMamba hook not found. && goto end )
> cd text-generation-webui
> 
> mkdir repositories
> cd repositories
> rm -rf GPTQ-for-LLaMa
> git clone https://github.com/oobabooga/GPTQ-for-LLaMa.git -b cuda
> cd GPTQ-for-LLaMa
> python setup_cuda.py install
> 
> pause
> ```

I am facing the exact same issue, I have tried every solution suggested here: https://www.reddit.com/r/LocalLLaMA/comments/11o6o3f/how_to_install_llama_8bit_and_4bit/ but couldn't able to figure out the reason behind it. Can somebody please look into this issue?
