### ISSUE TITLE
AttributeError: 'LlamaCppModel' object has no attribute 'model'

### ISSUE THREAD

**Issue by mr-september** [oobabooga/text-generation-webui#2295]
### Describe the bug

Hi, I just downloaded and used the `start_windows.bat`, and am trying to run this "Wizard-Vicuna-7B-Uncensored" model. It errors out and closes. I have tried both manually downloading the file and putting it in the `models\` folder, and using the built-in downloader.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run start_windows.bat. 
Select either 1 or 2. 
Error and close.

### Logs

```shell
The following models are available:

1. TheBloke_Wizard-Vicuna-7B-Uncensored-GGML
2. Wizard-Vicuna-7B-Uncensored.ggmlv3.q5_1.bin

Which one do you want to load? 1-2

2

INFO:Loading Wizard-Vicuna-7B-Uncensored.ggmlv3.q5_1.bin...
INFO:llama.cpp weights detected: models\Wizard-Vicuna-7B-Uncensored.ggmlv3.q5_1.bin

INFO:Cache capacity is 0 bytes
llama.cpp: loading model from models\Wizard-Vicuna-7B-Uncensored.ggmlv3.q5_1.bin
error loading model: unknown (magic, version) combination: 67676a74, 00000003; is this really a GGML file?
llama_init_from_file: failed to load model
Traceback (most recent call last):
  File "E:\oobabooga_windows\text-generation-webui\server.py", line 1063, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "E:\oobabooga_windows\text-generation-webui\modules\models.py", line 95, in load_model
    output = load_func(model_name)
  File "E:\oobabooga_windows\text-generation-webui\modules\models.py", line 258, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
  File "E:\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 50, in from_pretrained
    self.model = Llama(**params)
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 161, in __init__
    assert self.ctx is not None
AssertionError
Exception ignored in: <function LlamaCppModel.__del__ at 0x000001C5A09377F0>
Traceback (most recent call last):
  File "E:\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 23, in __del__
    self.model.__del__()
AttributeError: 'LlamaCppModel' object has no attribute 'model'

```

### System Info

```shell
Windows 11, 32GB ram, Nvidia 2070 Super (8GB)
```

**Comment by mr-september** [comment]
Sorry, just found this [PR](https://github.com/oobabooga/text-generation-webui/pull/2264) from a reddit thread. Didn't come up searching on github itself...

Is my issue the very same one this PR is meant to address?

**Comment by mr-september** [comment]
I am so sorry, it turned out to be exactly that. I just implemented the PR locally and it's working flawlessly now. 

Hope this thread surfaces on Google/Github searches in case anyone else first attempts this within these unfortunate hours.
