### ISSUE TITLE
Oobabooga error after loading a soft prompt

### ISSUE THREAD

**Issue by sukhysall** [oobabooga/text-generation-webui#2305]
### Describe the bug

A soft prompt loaded and trained using the local-softtuner does not work in Oobabooga. Text generation works fine but once the softprompt is selected from the drop down list, oobabooga console presents an error

The model I'm using is KoboldAI_OPT-6.7B-Erebus

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Load Oobabooga
2. Generate Text (No soft prompt loaded)
3. Load softprompt
4. Generate Text - Console error presented and no text generation occurs

### Logs

```shell
INFO:Loaded the model in 8.39 seconds.

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Output generated in 7.36 seconds (27.03 tokens/s, 199 tokens, context 8, seed 285011319)
INFO:
Loading the softprompt "my_softprompt".
INFO:author: You
INFO:supported: models/KoboldAI_OPT-6.7B-Erebus
INFO:description: softprompt test
Traceback (most recent call last):
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\gradio\utils.py", line 339, in async_iteration
    return await iterator.__anext__()
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\gradio\utils.py", line 332, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\gradio\utils.py", line 315, in run_sync_iterator_async
    return next(iterator)
  File "C:\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 150, in generate_reply_wrapper
    for reply in generate_reply(question, state, eos_token, stopping_strings, is_chat=False):
  File "C:\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 184, in generate_reply
    for reply in generate_func(question, original_question, seed, state, eos_token, stopping_strings, is_chat=is_chat):
  File "C:\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 218, in generate_reply_HF
    inputs_embeds, filler_input_ids = generate_softprompt_input_tensors(input_ids)
  File "C:\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 75, in generate_softprompt_input_tensors
    inputs_embeds = shared.model.transformer.wte(input_ids)
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'OPTForCausalLM' object has no attribute 'transformer'
```

### System Info

```shell
Locally Hosted
Nvidia RTX 4090
```

**Comment by sukhysall** [comment]
It seems loras have succeeded soft prompts. Closing this issue as it does seem like soft prompt rate any form of priority.

**Comment by Pevernow** [comment]
I have the same problem.
Could you please help me?
![image](https://github.com/oobabooga/text-generation-webui/assets/29888010/41d4430b-7920-45e0-bee5-87fc7ae909c3)

**Comment by sukhysall** [comment]
Sorry bud. I've decided not to progress chasing for fixes to soft prompt tuning. There doesn't appear to be any development that I can see or any progression with soft prompts.  The focus appears to be on Lora so I'm focusing on Lora (even if that isn't going well either).
