### ISSUE TITLE
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory models\TheBloke_Wizard-Vicuna-7B-Uncensored-GPTQ.

### ISSUE THREAD

**Issue by agonzalezm** [oobabooga/text-generation-webui#2306]
### Describe the bug

Downloading any model and doing start_windows gives this error and exist.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

run start_windows use NVIDIA and download model

### Logs

```shell
PS C:\x\oobabooga_windows> .\start_windows.bat
bin C:\x\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
INFO:Loading TheBloke_Wizard-Vicuna-7B-Uncensored-GPTQ...
Traceback (most recent call last):
  File "C:\x\oobabooga_windows\text-generation-webui\server.py", line 1063, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\x\oobabooga_windows\text-generation-webui\modules\models.py", line 95, in load_model
    output = load_func(model_name)
  File "C:\x\oobabooga_windows\text-generation-webui\modules\models.py", line 153, in huggingface_loader
    model = LoaderClass.from_pretrained(Path(f"{shared.args.model_dir}/{model_name}"), low_cpu_mem_usage=True, torch_dtype=torch.bfloat16 if shared.args.bf16 else torch.float16, trust_remote_code=shared.args.trust_remote_code)
  File "C:\x\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 467, in from_pretrained
    return model_class.from_pretrained(
  File "C:\x\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2387, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory models\TheBloke_Wizard-Vicuna-7B-Uncensored-GPTQ.
```

### System Info

```shell
nvida rtx 3060 12GB vram
```

**Comment by Ph0rk0z** [comment]
Specify -wbits 4 in the UI or on the commandline

**Comment by bavcol** [comment]
Duplicate of #2211
