### ISSUE TITLE
ERROR:Task exception was never retrieved

### ISSUE THREAD

**Issue by GiusTex** [oobabooga/text-generation-webui#2307]
### Describe the bug

When I start the webui I get this red error log:
#### Error log:
```shell
ERROR:Task exception was never retrieved
future: <Task finished name='whwi9m3v1h_58' coro=<Queue.process_events() done, defined at C:\Users\wgius\Desktop\TextGenerationWebui\installer_files\env\lib\site-packages\gradio\queueing.py:343> exception=ValidationError(model='PredictBody', errors=[{'loc': ('data',), 'msg': 'field required', 'type': 'value_error.missing'}])>
Traceback (most recent call last):
  File "C:\Users\wgius\Desktop\TextGenerationWebui\installer_files\env\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "C:\Users\wgius\Desktop\TextGenerationWebui\installer_files\env\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "C:\Users\wgius\Desktop\TextGenerationWebui\installer_files\env\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for PredictBody
data
  field required (type=value_error.missing)
```
And with this error sometimes I can't use either other internet extensions, like EdgeGPT (that was working some minutes before).

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Start the webui. It shows up both with extensions and without them. I'm using the last update.

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/112352961/f46a46af-59df-409a-ad81-40046331f722)

### System Info

```shell
Windows 11, nvidia rtx 3060, local computer.
```

**Comment by bbecausereasonss** [comment]
Having the same issue, as well as bitsandbytes all of a sudden not compiled with GPU support (even though it is...)

To create a public link, set `share=True` in `launch()`.
ERROR:Task exception was never retrieved
future: <Task finished name='q39bo56ntma_120' coro=<Queue.process_events() done, defined at /home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/queueing.py:343> exception=ValidationError(model='PredictBody', errors=[{'loc': ('data',), 'msg': 'field required', 'type': 'value_error.missing'}])>
Traceback (most recent call last):
  File "/home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for PredictBody
data
  field required (type=value_error.missing)

**Comment by baobabKoodaa** [comment]
I'm also having the same issue.

**Comment by baobabKoodaa** [comment]
Thanks. Resolved by reinstalling.

**Comment by GiusTex** [comment]
Same, thanks
