### ISSUE TITLE
Unable to load any GGML

### ISSUE THREAD

**Issue by Eric-Hsieh97** [oobabooga/text-generation-webui#2312]
### Discussed in https://github.com/oobabooga/text-generation-webui/discussions/2242

<div type='discussions-op-text'>

<sup>Originally posted by **watcher60** May 21, 2023</sup>
I'm having issues loading any GGML file --are the new format files supported?
. I've tried:
https://huggingface.co/TheBloke/Wizard-Vicuna-13B-Uncensored-GGML
https://huggingface.co/TheBloke/wizard-mega-13B-GGML/

I have llama-cpp-python-0.1.52 installed.

**Both in the terminal give:**
llama.cpp: loading model from models/Wizard-Vicuna-13B-Uncensored.ggmlv3.q4_0.bin
error loading model: unknown (magic, version) combination: 67676a74, 00000003; is this really a GGML file?
llama_init_from_file: failed to load model
Exception ignored in: <function LlamaCppModel.__del__ at 0x7fc7ac9fa680>
Traceback (most recent call last):
  File "/home/watc/oobabooga_linux/text-generation-webui/modules/llamacpp_model.py", line 23, in __del__
    self.model.__del__()
AttributeError: 'LlamaCppModel' object has no attribute 'model

**In the webgui it gives:**
Traceback (most recent call last): File “/home/watc/oobabooga_linux/text-generation-webui/server.py”, line 68, in load_model_wrapper shared.model, shared.tokenizer = load_model(shared.model_name) File “/home/watc/oobabooga_linux/text-generation-webui/modules/models.py”, line 95, in load_model output = load_func(model_name) File “/home/watc/oobabooga_linux/text-generation-webui/modules/models.py”, line 258, in llamacpp_loader model, tokenizer = LlamaCppModel.from_pretrained(model_file) File “/home/watc/oobabooga_linux/text-generation-webui/modules/llamacpp_model.py”, line 50, in from_pretrained self.model = Llama(**params) File “/home/watcminiconda3/lib/python3.10/site-packages/llama_cpp/llama.py”, line 159, in init assert self.ctx is not None AssertionError

Thanks in advance to any pointers</div>

**Comment by gabriead** [comment]
I have the exact same error

**Comment by m-spangenberg** [comment]
This was just merged: https://github.com/oobabooga/text-generation-webui/issues/2245

**Comment by Vadimluck** [comment]
Last night I decided to reinstall and got the exact same error. Reinstalled about 5 times from scratch and nothing helped. (Everything was working before that!)

**Comment by m-spangenberg** [comment]
> Last night I decided to reinstall and got the exact same error.

Did you remember to download the newest supported GGML model? I don't believe older models are backwards compatible.

Here is a newly quantized [WizardLM-7B-uncensored.ggmlv3.q5_1](https://huggingface.co/TheBloke/WizardLM-7B-uncensored-GGML/resolve/main/WizardLM-7B-uncensored.ggmlv3.q5_1.bin.) model to test. Hope this helps. Also, see the uploaders note about quantized models:

> Note: at this time text-generation-webui may not support the new May 19th llama.cpp quantisation methods for q4_0, q4_1 and q8_0 files.

**Comment by Vadimluck** [comment]
> > I decided to reinstall last night and got the exact same error. > > Did you remember to download the latest supported GGML model? I don't believe older models are backwards compatible. > > Here is a newly quantized [model WizardLM-7B-uncensored.ggmlv3.q5_1](https://huggingface.co/TheBloke/WizardLM-7B-uncensored-GGML/resolve/main/WizardLM-7B-uncensored.ggmlv3.q5_1.bin.) for testing. I hope this helps. Also see Loaders Note about quantized models: > > > Note: currently text-generation-webui might not support the new version of May 19th llama.cpp quantization methods for q4_0, q4_1 and q8_0 files.

Thank you very much! My problem was solved as soon as I loaded q5, before that I was using q8.

**Comment by bbecausereasonss** [comment]
Getting this error. AttributeError: 'LlamaCppModel' object has no attribute 'model'

2023-06-14 14:12:37 INFO:Cache capacity is 0 bytes
llama.cpp: loading model from models\30b-Lazarus.ggmlv3.q4_K_M.bin
error loading model: unrecognized tensor type 12

llama_init_from_file: failed to load model
Exception ignored in: <function LlamaCppModel.__del__ at 0x0000017D899F8160>
Traceback (most recent call last):
  File "C:\xxxx\vdrut\Deep\TextGen\text-generation-webui\modules\llamacpp_model.py", line 23, in __del__
    self.model.__del__()
AttributeError: 'LlamaCppModel' object has no attribute 'model'
