### ISSUE TITLE
'quant_cuda' is not defined (Linux)

### ISSUE THREAD

**Issue by PostalVoid** [oobabooga/text-generation-webui#2324]
### Describe the bug

After installing the webui, while the actual webui shows up correctly, any text sent results in an error, with the focal point being that 'quant_cuda' is not defined. I've also has this issue with the "one-click installer".

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Install the manual version of oobabooga's text-generation-webui
conda activate textgen (base gives same result)
run start_linux.sh

### Logs

```shell
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/home/user/Programs/oobabooga_linux/text-generation-webui/modules/callbacks.py", line 73, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/home/user/Programs/oobabooga_linux/text-generation-webui/modules/text_generation.py", line 277, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/user/Programs/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/Programs/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/transformers/generation/utils.py", line 1565, in generate
    return self.sample(
  File "/home/user/Programs/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/transformers/generation/utils.py", line 2612, in sample
    outputs = self(
  File "/home/user/Programs/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/Programs/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 688, in forward
    outputs = self.model(
  File "/home/user/Programs/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/Programs/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 578, in forward
    layer_outputs = decoder_layer(
  File "/home/user/Programs/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/Programs/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 293, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/user/Programs/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/Programs/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 197, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "/home/user/Programs/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/Programs/oobabooga_linux/text-generation-webui/repositories/GPTQ-for-LLaMa/quant.py", line 426, in forward
    quant_cuda.vecquant4matmul(x, self.qweight, y, self.scales, self.qzeros, self.groupsize)
NameError: name 'quant_cuda' is not defined
Output generated in 0.30 seconds (0.00 tokens/s, 0 tokens, context 81, seed 1172637845)
```

### System Info

```shell
OS: EndeavorOS (Arch-based linux)
GPU: RTX 3080
Torch: 2.0.1+cu117
```

**Comment by gabriead** [comment]
same here

**Comment by Ph0rk0z** [comment]
Yea. You have to compile and install the kernels for it to work.

**Comment by FutanariPogging** [comment]
Ok so I compiled gcc-11, reset GPTQ for llama, and loaded the 7B model, which worked the first time around, but now it's having trouble loading again.

```
/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/cuda/__init__.py:107: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
bin /home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
INFO:Loading llama-7b-4bit-128g...
INFO:Found the following quantized model: models/llama-7b-4bit-128g/llama-7b-4bit-128g.safetensors
Traceback (most recent call last):
  File "/home/user/Programs/oobabooga_linux/text-generation-webui/server.py", line 1072, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/user/Programs/oobabooga_linux/text-generation-webui/modules/models.py", line 95, in load_model
    output = load_func(model_name)
  File "/home/user/Programs/oobabooga_linux/text-generation-webui/modules/models.py", line 275, in GPTQ_loader
    model = modules.GPTQ_loader.load_quantized(model_name)
  File "/home/user/Programs/oobabooga_linux/text-generation-webui/modules/GPTQ_loader.py", line 199, in load_quantized
    model = model.to(torch.device('cuda:0'))
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1878, in to
    return super().to(*args, **kwargs)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.
```


I looked into it, and this is what I got:

> `sudo rmmod nvidia_uvm`
> `sudo rmmod nvidia`
> `sudo modprobe nvidia`
> `sudo modprobe nvidia_uvm`
> Then test
> `>>> import torch`
> `>>> torch.cuda.is_available()`
> `True`

I tried testing if CUDA was available, but got a response just like before:
```
/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/cuda/__init__.py:107: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
False
```
So as I understand it, CUDA is still being used by the original instance of the program, but doesn't recognize that it's actually no longer in use?

**Comment by Ph0rk0z** [comment]
Yea, seems like your env is messed up.

**Comment by michael-imbeault** [comment]
I had this problem, for me I was using an 'old' 1 click installer - reinstalled everything using the latest 1 click installer from https://github.com/oobabooga/one-click-installers and that fixed it

**Comment by michael-imbeault** [comment]
Now on updating:

Building wheels for collected packages: quant-cuda
  Building wheel for quant-cuda (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      running bdist_wheel
      running build
      running build_ext
      D:\Oobabooga\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      building 'quant_cuda' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for quant-cuda
  Running setup.py clean for quant-cuda
Failed to build quant-cuda
Installing collected packages: quant-cuda
  Attempting uninstall: quant-cuda
    Found existing installation: quant-cuda 0.0.0
    Uninstalling quant-cuda-0.0.0:
      Successfully uninstalled quant-cuda-0.0.0
  Running setup.py install for quant-cuda ... error
  error: subprocess-exited-with-error

  × Running setup.py install for quant-cuda did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      running install
      D:\Oobabooga\installer_files\env\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      D:\Oobabooga\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      building 'quant_cuda' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of quant-cuda
  Moving to d:\oobabooga\installer_files\env\lib\site-packages\quant_cuda-0.0.0.dist-info\
   from D:\Oobabooga\installer_files\env\Lib\site-packages\~uant_cuda-0.0.0.dist-info
  Moving to d:\oobabooga\installer_files\env\lib\site-packages\quant_cuda.cp310-win_amd64.pyd
   from D:\Oobabooga\installer_files\pip-uninstall-q9mznc9v\quant_cuda.cp310-win_amd64.pyd
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> quant-cuda

note: This is an issue with the package mentioned above, not pip.

**Comment by pluberd** [comment]
I have the same Problem. I am using Linux. The Link from the solution above is death:  https://github.com/oobabooga/text-generation-webui/blob/main/docs/GPTQ-models-(4-bit-mode).md
