### ISSUE TITLE
extensions/openai KeyError: 'assistant'

### ISSUE THREAD

**Issue by mongolu** [oobabooga/text-generation-webui#2326]
### Describe the bug

Starting after [https://github.com/oobabooga/text-generation-webui/pull/2291]

Which I think it's a great improvement.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Start server with extension --openai --model openaccess-ai-collective_manticore-13b.
Starting [DGdev91 Auto-GPT](https://github.com/DGdev91/Auto-GPT), runs 1 cycle, give 'y' for the second, the error appears.

### Logs

```shell
openaccess-ai-collectiveException occurred during processing of request from ('127.0.0.1', 42032)
Traceback (most recent call last):
  File "/home/mihai/miniconda3/envs/textgen/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/mihai/miniconda3/envs/textgen/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/mihai/miniconda3/envs/textgen/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/home/mihai/miniconda3/envs/textgen/lib/python3.10/http/server.py", line 433, in handle
    self.handle_one_request()
  File "/home/mihai/miniconda3/envs/textgen/lib/python3.10/http/server.py", line 421, in handle_one_request
    method()
  File "/home/mihai/text-generation-webui/extensions/openai/script.py", line 310, in do_POST
    msg = role_formats[role].format(message=content)
KeyError: 'assistant'
----------------------------------------
```

### System Info

```shell
Win11 WSL2 Ubuntu 20.04
Python 3.10
```

**Comment by matatonic** [comment]
This looks like 2 problems: 
1) you need to update your models/config.yaml (to include manticore) and/or your characters/instruction-following/Manticore Chat.yaml is missing.
2) There is a bug in the default template (says 'bot') should be 'assistant'

I will fix 2), for better results you should also fix 1).

**Comment by mongolu** [comment]
Thank you for 2.
For 1, now, after a morning git pull, ./models/config.yaml contains at the end
.*manticore:
  mode: 'instruct'
  instruction_template: 'Manticore Chat'
