### ISSUE TITLE
extension/openai chat/completion endpoint IndexError: string index out of range

### ISSUE THREAD

**Issue by fakezeta** [oobabooga/text-generation-webui#2331]
### Describe the bug

openai extension /completion endpoint works correctly whilst /chat/completion returns IndexError: string index out of range in the logs and obviously no result in the API.

The issue seems at line 318 when checking if the string end with newline:
`if system_msg[-1] != '\n':` 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
curl http://192.168.178.35:5001/v1/chat/completions -H "Content-Type: application/json" -d '{
     "model": "gpt-3.5-turbo",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "temperature": 0.7
   }'
```

### Logs

```shell
25/May/2023 14:03:09] "POST /v1/chat/completions HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('192.168.196.154', 54388)
Traceback (most recent call last):
  File "D:\Apps\oobabooga-windows\installer_files\env\lib\socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "D:\Apps\oobabooga-windows\installer_files\env\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\Apps\oobabooga-windows\installer_files\env\lib\socketserver.py", line 747, in init
    self.handle()
  File "D:\Apps\oobabooga-windows\installer_files\env\lib\http\server.py", line 433, in handle
    self.handle_one_request()
  File "D:\Apps\oobabooga-windows\installer_files\env\lib\http\server.py", line 421, in handle_one_request
    method()
  File "D:\Apps\oobabooga-windows\text-generation-webui\extensions\openai\script.py", line 318, in do_POST
    if system_msg[-1] != '\n':
IndexError: string index out of range
```

### System Info

```shell
Windows 11
Nvidia Geforce 3060Ti
Python 3.10.11
```

**Comment by matatonic** [comment]
Thanks for the report! The fix should be merged soon.

**Comment by fakezeta** [comment]
Thank you @matatonic !

I've tried the fix and can confirm it's working.
