### ISSUE TITLE
Newest build broke something - scipy missing

### ISSUE THREAD

**Issue by michael-imbeault** [oobabooga/text-generation-webui#2335]
### Describe the bug

Updated using install.bat - Ooba doesn't run anymore. Tried to delete the installer_files folder and reinstall from scratch, same result.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Update / reinstall

### Logs

```shell
Traceback (most recent call last):
  File "D:\Oobabooga\text-generation-webui\server.py", line 49, in <module>
    from modules import chat, shared, training, ui, utils
  File "D:\Oobabooga\text-generation-webui\modules\training.py", line 14, in <module>
    from peft import (LoraConfig, get_peft_model, prepare_model_for_int8_training,
  File "D:\Oobabooga\installer_files\env\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "D:\Oobabooga\installer_files\env\lib\site-packages\peft\mapping.py", line 16, in <module>
    from .peft_model import (
  File "D:\Oobabooga\installer_files\env\lib\site-packages\peft\peft_model.py", line 31, in <module>
    from .tuners import (
  File "D:\Oobabooga\installer_files\env\lib\site-packages\peft\tuners\__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel
  File "D:\Oobabooga\installer_files\env\lib\site-packages\peft\tuners\lora.py", line 40, in <module>
    import bitsandbytes as bnb
  File "D:\Oobabooga\installer_files\env\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "D:\Oobabooga\installer_files\env\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "D:\Oobabooga\installer_files\env\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "D:\Oobabooga\installer_files\env\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "D:\Oobabooga\installer_files\env\lib\site-packages\bitsandbytes\optim\__init__.py", line 8, in <module>
    from .adagrad import Adagrad, Adagrad8bit, Adagrad32bit
  File "D:\Oobabooga\installer_files\env\lib\site-packages\bitsandbytes\optim\adagrad.py", line 5, in <module>
    from bitsandbytes.optim.optimizer import Optimizer1State
  File "D:\Oobabooga\installer_files\env\lib\site-packages\bitsandbytes\optim\optimizer.py", line 12, in <module>
    import bitsandbytes.functional as F
  File "D:\Oobabooga\installer_files\env\lib\site-packages\bitsandbytes\functional.py", line 12, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
```

### System Info

```shell
Windows 11
```

**Comment by Undone** [comment]
Installing scipy manually with "pip install scipy" fixes it. Missing from the requirements.txt?

**Comment by TheStagnation** [comment]
Windows 10, same error here. Attempted "pip install scipy"; it installed, but same error even after that.

**Comment by jllllll** [comment]
Seems to be an issue with bitsandbytes not properly listing scipy as a requirement.

**Comment by jllllll** [comment]
bitsandbytes Windows wheel has been updated to include scipy as a dependency. This will make it so that scipy is installed automatically if it is missing.

**Comment by michael-imbeault** [comment]
It now loads, but loading a model and using it results in:

Traceback (most recent call last):
  File "D:\Oobabooga\text-generation-webui\modules\callbacks.py", line 73, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "D:\Oobabooga\text-generation-webui\modules\text_generation.py", line 274, in generate_with_callback
    shared.model.generate(**kwargs)
  File "D:\Oobabooga\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Oobabooga\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1568, in generate
    return self.sample(
  File "D:\Oobabooga\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 2615, in sample
    outputs = self(
  File "D:\Oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Oobabooga\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "D:\Oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Oobabooga\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 577, in forward
    layer_outputs = decoder_layer(
  File "D:\Oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Oobabooga\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "D:\Oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Oobabooga\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 194, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "D:\Oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Oobabooga\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 426, in forward
    quant_cuda.vecquant4matmul(x, self.qweight, y, self.scales, self.qzeros, self.groupsize)
NameError: name 'quant_cuda' is not defined
Output generated in 0.40 seconds (0.00 tokens/s, 0 tokens, context 8, seed 867273690)

Not sure if related or not. Reinstalled from scratch after your latest commit.

**Comment by jllllll** [comment]
@michael-imbeault Which model? Are you on CPU only?

**Comment by TheStagnation** [comment]
> bitsandbytes Windows wheel has been updated to include scipy as a dependency. This will make it so that scipy is installed automatically if it is missing.

Issue resolved after updating, thanks for the prompt responses!

**Comment by michael-imbeault** [comment]
It is models I used before (llama-30b-4bit-128g, stable-vicuna-13B-GPTQ-4bit, many others, all quantized, all of which were working as before yesterday) - did something change with GPTQ? Issue on reddit that might be related https://www.reddit.com/r/Oobabooga/comments/13rscbm/fix_i_found_for_problems_with_quantized_models/ ?

**Comment by michael-imbeault** [comment]
Fixed, found out I was using an 'old' version of the 1 click installer, reinstalled everything with the new one, works now, thanks!
