### ISSUE TITLE
stuck at python setup_cuda.py install

### ISSUE THREAD

**Issue by HolzerDavid** [oobabooga/text-generation-webui#239]
i am not sure where to go from here, i tried downgrading torch, installing Visual Studio 2019.
I don't have any experience in terms of C++ compilers, especially on windows. so i might have borked it there, but i don't know how to check for errors.

```
D:\Conda\envs\LLM\lib\site-packages\torch\utils\cpp_extension.py:346: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
Traceback (most recent call last):
  File "P:\Privat\text-generation-webui\respositories\GPTQ-for-LLaMa\setup_cuda.py", line 4, in <module>
    setup(
  File "D:\Conda\envs\LLM\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "D:\Conda\envs\LLM\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "D:\Conda\envs\LLM\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "D:\Conda\envs\LLM\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "D:\Conda\envs\LLM\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "D:\Conda\envs\LLM\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\Conda\envs\LLM\lib\site-packages\setuptools\command\install.py", line 74, in run
    self.do_egg_install()
  File "D:\Conda\envs\LLM\lib\site-packages\setuptools\command\install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "D:\Conda\envs\LLM\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "D:\Conda\envs\LLM\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "D:\Conda\envs\LLM\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\Conda\envs\LLM\lib\site-packages\setuptools\command\bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "D:\Conda\envs\LLM\lib\site-packages\setuptools\command\bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "D:\Conda\envs\LLM\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "D:\Conda\envs\LLM\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "D:\Conda\envs\LLM\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\Conda\envs\LLM\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "D:\Conda\envs\LLM\lib\site-packages\setuptools\_distutils\command\install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "D:\Conda\envs\LLM\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "D:\Conda\envs\LLM\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "D:\Conda\envs\LLM\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\Conda\envs\LLM\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "D:\Conda\envs\LLM\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
    self.build_extensions()
  File "D:\Conda\envs\LLM\lib\site-packages\torch\utils\cpp_extension.py", line 434, in build_extensions
    self._check_cuda_version(compiler_name, compiler_version)
  File "D:\Conda\envs\LLM\lib\site-packages\torch\utils\cpp_extension.py", line 812, in _check_cuda_version
    raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
RuntimeError:
The detected CUDA version (12.1) mismatches the version that was used to compile
PyTorch (11.3). Please make sure to use the same CUDA versions.
```

CUDA:
```
(LLM) P:\Privat\text-generation-webui\respositories\GPTQ-for-LLaMa>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:59:34_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0
```

PyTorch:
```
>>> print(torch. __version__)
1.12.0+cu113

```

**Comment by oobabooga** [comment]
See here #222, people are trying to do the same thing.

**Comment by HolzerDavid** [comment]
downgraded to CUDA 11.8

now it works

**Comment by appvoid** [comment]
Try with: `python setup_cuda.py install --user`

**Comment by GeorvityLabs** [comment]
@HolzerDavid @oobabooga i'm on cuda 11.6 and am getting RuntimeError: 
The detected CUDA version (12.1) mismatches the version that was used to compile
PyTorch (11.7). Please make sure to use the same CUDA versions. how do i fix this?
