### ISSUE TITLE
QUERY: Screen display goes black when attempting train Lora

### ISSUE THREAD

**Issue by sukhysall** [oobabooga/text-generation-webui#2394]
### Describe the bug

Hi

I have a 1.5mb raw dataset file of stories which I'm trying to perform Lora training on. 

As far as I can tell, I have everything set up correctly and when I click start training I can see the little timer which states how long the training will take. I see that only briefly before my windows instance goes dark. I lose the display. No amount of keyboard tapping brings it back. I have a black monitor and no idea if the training is happening.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Choose dataset
2. Begin training

### Screenshot

No screenshot available. 

### Logs

```shell
No logs to provide in the command line as the display has gone dark. 

Due to having to soft reset the PC, I automatically lose whatever was in the command line.
```

### System Info

```shell
Running:
core-9-13900k
RTX4090
```

**Comment by sukhysall** [comment]
okay so I managed to get something by using teamview to get into the PC after I lost the screen. Turns out if I try to move up to anything over Batch Size 4, the issue occurs. But I had it running with no issues for 2 minutes at Batch Size 4.

Console log I managed to grab for when it did go dark:

Exception in thread Thread-6 (threaded_run):
Traceback (most recent call last):
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\torch\random.py", line 133, in fork_rng
    yield
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\torch\utils\checkpoint.py", line 141, in backward
    outputs = ctx.run_function(*detached_inputs)
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\opt\modeling_opt.py", line 692, in custom_forward
    return module(*inputs, output_attentions, None)
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\opt\modeling_opt.py", line 329, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\opt\modeling_opt.py", line 174, in forward
    query_states = self.q_proj(hidden_states) * self.scaling
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\peft\tuners\lora.py", line 698, in forward
    result = super().forward(x)
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\nn\modules.py", line 242, in forward
    out = bnb.matmul(x, self.weight, bias=self.bias, state=self.state)
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\autograd\_functions.py", line 488, in matmul
    return MatMul8bitLt.apply(A, B, out, bias, state)
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\autograd\_functions.py", line 303, in forward
    CA, CAt, SCA, SCAt, coo_tensorA = F.double_quant(A.to(torch.float16), threshold=state.threshold)
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\functional.py", line 1640, in double_quant
    nnz = nnz_row_ptr[-1].item()
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\oobabooga-windows\installer_files\env\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\oobabooga-windows\installer_files\env\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\oobabooga-windows\text-generation-webui\modules\training.py", line 461, in threaded_run
    trainer.train()
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\transformers\trainer.py", line 1662, in train
    return inner_training_loop(
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\transformers\trainer.py", line 1929, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\transformers\trainer.py", line 2709, in training_step
    self.scaler.scale(loss).backward()
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\torch\_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\torch\autograd\__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\torch\autograd\function.py", line 274, in apply
    return user_fn(self, *args)
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\torch\utils\checkpoint.py", line 132, in backward
    with torch.random.fork_rng(devices=rng_devices, enabled=ctx.preserve_rng_state):
  File "C:\oobabooga-windows\installer_files\env\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\torch\random.py", line 137, in fork_rng
    torch.cuda.set_rng_state(gpu_rng_state, device)
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\torch\cuda\random.py", line 64, in set_rng_state
    _lazy_call(cb)
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\torch\cuda\__init__.py", line 183, in _lazy_call
    callable()
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\torch\cuda\random.py", line 62, in cb
    default_generator.set_state(new_state_copy)
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

INFO:Training complete, saving...
Traceback (most recent call last):
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\gradio\utils.py", line 339, in async_iteration
    return await iterator.__anext__()
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\gradio\utils.py", line 332, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\gradio\utils.py", line 315, in run_sync_iterator_async
    return next(iterator)
  File "C:\oobabooga-windows\text-generation-webui\modules\training.py", line 497, in do_train
    lora_model.save_pretrained(lora_file_path)
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\peft\peft_model.py", line 130, in save_pretrained
    torch.save(output_state_dict, os.path.join(output_dir, WEIGHTS_NAME))
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 441, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 665, in _save
    storage = storage.cpu()
  File "C:\oobabooga-windows\installer_files\env\lib\site-packages\torch\storage.py", line 121, in cpu
    return torch.UntypedStorage(self.size()).copy_(self, False)
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by sukhysall** [comment]
okay so tried several times and looks like lora training is just crashing and taking my display with it.

**Comment by sukhysall** [comment]
I reinstalled oobabooga and one of the commits must have fixed this.Now I get the dam pfet error when I try to open a lora.

This issue no longer valid. Closing.
