### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Ether90** [oobabooga/text-generation-webui#241]
I get this error if the answer is too long I think:

```
Traceback (most recent call last):
  File "C:\Users\still\miniconda3\envs\textgen\lib\site-packages\gradio\routes.py", line 374, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\still\miniconda3\envs\textgen\lib\site-packages\gradio\blocks.py", line 1017, in process_api
    result = await self.call_function(
  File "C:\Users\still\miniconda3\envs\textgen\lib\site-packages\gradio\blocks.py", line 849, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\still\miniconda3\envs\textgen\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\still\miniconda3\envs\textgen\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\still\miniconda3\envs\textgen\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\still\miniconda3\envs\textgen\lib\site-packages\gradio\utils.py", line 453, in async_iteration
    return next(iterator)
  File "Q:\OogaBooga\text-generation-webui\modules\chat.py", line 172, in cai_chatbot_wrapper
    for _history in chatbot_wrapper(text, max_new_tokens, do_sample, temperature, top_p, typical_p, repetition_penalty, top_k, min_length, no_repeat_ngram_size, num_beams, penalty_alpha, length_penalty, early_stopping, name1, name2, context, check, chat_prompt_size, chat_generation_attempts):
  File "Q:\OogaBooga\text-generation-webui\modules\chat.py", line 129, in chatbot_wrapper
    reply, next_character_found, substring_found = extract_message_from_reply(prompt, reply, name1, name2, check)
  File "Q:\OogaBooga\text-generation-webui\modules\chat.py", line 63, in extract_message_from_reply
    idx = idx[max(len(previous_idx)-1, 0)]
IndexError: list index out of range
```

Settings:
Chat-Mode
max_new_tokens: 1587
Gen attempts: 3

Edit: I just saw that the answer is generated, the answer is shown if I ask another question.

**Comment by oobabooga** [comment]
With max_new_tokens set to 1587, your prompt as a whole is likely being truncated, causing the chat to have trouble locating where the bot's response begins. The solution is to reduce this value, as hardly you will get a response this long.

But let's leave this issue open. There is a probably a way of making sure that it will never happen

**Comment by FranticFoxGarage** [comment]
I'm also getting this exact issue when using Character file with 3354 lines of example dialogue. I'm running an i5-12600kf, 32gb of ram, and a RTX 3050 with 8gb of vram. I've got a 3090 ti on the way so will test again to see if its a gpu issue 
![Screenshot 2023-03-24 164705](https://user-images.githubusercontent.com/13055021/227647369-2cb7c577-d766-4224-841b-6fae27ed6f20.png)
Server start command used "server.py --cai-chat --settings settings-template.json --auto-devices --gpu-memory 6 --disk --gptq-bits 4 --listen --listen-port=8888"

**Comment by oobabooga** [comment]
Make sure to `git pull`, you are running an older version of the web UI.

**Comment by FranticFoxGarage** [comment]
Moved from TheTerrasque's pre made docker and reinstalled everything into ubuntu manually and was able to get it working!
