### ISSUE TITLE
mac python server.py error on MAC M2 chip

### ISSUE THREAD

**Issue by C0deXG** [oobabooga/text-generation-webui#2421]
### Describe the bug

error:
`Traceback (most recent call last):
  File "/Users/khederyusuf/Desktop/text-generation-webui/server.py", line 1090, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/Users/khederyusuf/Desktop/text-generation-webui/modules/models.py", line 95, in load_model
    output = load_func(model_name)
  File "/Users/khederyusuf/Desktop/text-generation-webui/modules/models.py", line 156, in huggingface_loader
    model = model.to(device)
  File "/Users/khederyusuf/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1891, in to
    return super().to(*args, **kwargs)
  File "/Users/khederyusuf/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1149, in to
    return self._apply(convert)
  File "/Users/khederyusuf/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 801, in _apply
    module._apply(fn)
  File "/Users/khederyusuf/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 801, in _apply
    module._apply(fn)
  File "/Users/khederyusuf/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 801, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/Users/khederyusuf/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 824, in _apply
    param_applied = fn(param)
  File "/Users/khederyusuf/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1147, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: MPS backend out of memory (MPS allocated: 9.02 GB, other allocations: 15.80 MB, max allowed: 9.07 GB). Tried to allocate 32.00 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

when i run python server.py i get that error

### Screenshot

none

### Logs

```shell
`Traceback (most recent call last):
  File "/Users/khederyusuf/Desktop/text-generation-webui/server.py", line 1090, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/Users/khederyusuf/Desktop/text-generation-webui/modules/models.py", line 95, in load_model
    output = load_func(model_name)
  File "/Users/khederyusuf/Desktop/text-generation-webui/modules/models.py", line 156, in huggingface_loader
    model = model.to(device)
  File "/Users/khederyusuf/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1891, in to
    return super().to(*args, **kwargs)
  File "/Users/khederyusuf/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1149, in to
    return self._apply(convert)
  File "/Users/khederyusuf/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 801, in _apply
    module._apply(fn)
  File "/Users/khederyusuf/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 801, in _apply
    module._apply(fn)
  File "/Users/khederyusuf/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 801, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/Users/khederyusuf/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 824, in _apply
    param_applied = fn(param)
  File "/Users/khederyusuf/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1147, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: MPS backend out of memory (MPS allocated: 9.02 GB, other allocations: 15.80 MB, max allowed: 9.07 GB). Tried to allocate 32.00 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).`
```

### System Info

```shell
`Traceback (most recent call last):
  File "/Users/khederyusuf/Desktop/text-generation-webui/server.py", line 1090, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/Users/khederyusuf/Desktop/text-generation-webui/modules/models.py", line 95, in load_model
    output = load_func(model_name)
  File "/Users/khederyusuf/Desktop/text-generation-webui/modules/models.py", line 156, in huggingface_loader
    model = model.to(device)
  File "/Users/khederyusuf/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1891, in to
    return super().to(*args, **kwargs)
  File "/Users/khederyusuf/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1149, in to
    return self._apply(convert)
  File "/Users/khederyusuf/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 801, in _apply
    module._apply(fn)
  File "/Users/khederyusuf/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 801, in _apply
    module._apply(fn)
  File "/Users/khederyusuf/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 801, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/Users/khederyusuf/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 824, in _apply
    param_applied = fn(param)
  File "/Users/khederyusuf/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1147, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: MPS backend out of memory (MPS allocated: 9.02 GB, other allocations: 15.80 MB, max allowed: 9.07 GB). Tried to allocate 32.00 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).`
```

**Comment by TanishqGoyal02** [comment]
need help with similar problem
