### ISSUE TITLE
Falcon-40b-instruct loaded as 8 bit - error at inference

### ISSUE THREAD

**Issue by dblacknc** [oobabooga/text-generation-webui#2437]
### Describe the bug

**This should read falcon-40b-instruct or -7b-instruct, any of 16, 8 and 4 bit modes. **

I'm loading tiiuae/falcon-40b-instruct with --auto-devices --load-in-8bit --trust-remote-code --gpu-memory 10 10, and there's plenty of CPU RAM.   About 20 GB is in my two GPUs and the rest is CPU offload.    Several seconds after entering the first prompt, I see the error as per the logs.

FYI also tried the experimental AutoGPTQ 4-bit quant by TheBloke  and saw a different error, and thought I saw someone else had already opened an issue for that.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load tilluae/falcon-40b-instruct as above, enter any prompt.

### Logs

```shell
Traceback (most recent call last):
  File "/root/text-generation-webui/modules/callbacks.py", line 73, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/root/text-generation-webui/modules/text_generation.py", line 274, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1485, in generate
    return self.sample(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2524, in sample
    outputs = self(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/tiiuae_falcon-40b-instruct/modelling_RW.py", line 759, in forward
    transformer_outputs = self.transformer(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/tiiuae_falcon-40b-instruct/modelling_RW.py", line 654, in forward
    outputs = block(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/tiiuae_falcon-40b-instruct/modelling_RW.py", line 396, in forward
    attn_outputs = self.self_attention(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/tiiuae_falcon-40b-instruct/modelling_RW.py", line 289, in forward
    attn_output = F.scaled_dot_product_attention(
RuntimeError: Expected query, key, and value to have the same dtype, but got query.dtype: float key.dtype: float and value.dtype: c10::Half instead.
```

### System Info

```shell
ubuntu 22.04
git pull as of 5/29, all pkgs upgraded with pip -U
2 x RTX3060 12 GB
96 GB RAM
```

**Comment by dblacknc** [comment]
I get the same exact error loading tiiuae-falcon-7b in HF 16-bit splitting between the GPUs and 8 bit on just one, so stopping there.

**Comment by knewter** [comment]
I ran into the same issue

**Comment by aibarito-ua** [comment]
Maybe you should pull the latest commit with falcon support (204731952ae59d79ea3805a425c73dd171d943c3). I could run the falcon40b with --load-in-8bit

**Comment by dblacknc** [comment]
I have pulled it since then.  I also found this one works:  **TheBloke/falcon-7b-instruct-GPTQ**

Loading tiiuae_falcon-7b-instruct...
in default 16-bit mode, across my two GPUs, as well as load-in-8bit on just one, same error.

I just did another git pull + pip -U -r requirements.txt and will update if that changes anything.

**Comment by dblacknc** [comment]
TheBloke/falcon-40b-instruct-GPTQ using AutoGPTQ also works fine, albeit slow - but speed is a known issue with that quantization

**Comment by aljungberg** [comment]
There's a bug in their rotary embedding code in the 7B version.

**Comment by aljungberg** [comment]
Okay since we can't easily change these various HuggingFace repos with Falcon models, I pushed a kind of 'auto-fixer' for textgen in #2548. Give it a go if you like.
