### ISSUE TITLE
ModuleNotFoundError: No module named 'jmespath' {v2}

### ISSUE THREAD

**Issue by cibernicola** [oobabooga/text-generation-webui#2439]
### Describe the bug

ModuleNotFoundError: No module named 'jmespath'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

After update a local installation I'm seeing this error

git pull

It's also here: https://github.com/oobabooga/text-generation-webui/issues/1874 but its 3 weeks ago and not exactly the same.

### Logs

```shell
Starting the web UI... Traceback (most recent call last): File "J:\gpt\text-generation-webui\text-generation-webui\server.py", line 49, in <module> from modules import chat, shared, training, ui, utils File "J:\gpt\text-generation-webui\text-generation-webui\modules\chat.py", line 18, in <module> from modules.text_generation import (generate_reply, get_encoded_length, File "J:\gpt\text-generation-webui\text-generation-webui\modules\text_generation.py", line 18, in <module> from modules.models import clear_torch_cache, local_rank File "J:\gpt\text-generation-webui\text-generation-webui\modules\models.py", line 12, in <module> from accelerate import infer_auto_device_map, init_empty_weights File "J:\gpt\text-generation-webui\installer_files\env\lib\site-packages\accelerate\__init__.py", line 3, in <module> from .accelerator import Accelerator File "J:\gpt\text-generation-webui\installer_files\env\lib\site-packages\accelerate\accelerator.py", line 33, in <module> from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state File "J:\gpt\text-generation-webui\installer_files\env\lib\site-packages\accelerate\checkpointing.py", line 24, in <module> from .utils import ( File "J:\gpt\text-generation-webui\installer_files\env\lib\site-packages\accelerate\utils\__init__.py", line 111, in <module> from .launch import ( File "J:\gpt\text-generation-webui\installer_files\env\lib\site-packages\accelerate\utils\launch.py", line 23, in <module> from ..commands.config.config_args import SageMakerConfig File "J:\gpt\text-generation-webui\installer_files\env\lib\site-packages\accelerate\commands\config\__init__.py", line 19, in <module> from .config import config_command_parser File "J:\gpt\text-generation-webui\installer_files\env\lib\site-packages\accelerate\commands\config\config.py", line 25, in <module> from .sagemaker import get_sagemaker_input File "J:\gpt\text-generation-webui\installer_files\env\lib\site-packages\accelerate\commands\config\sagemaker.py", line 35, in <module> import boto3  # noqa: F401 File "C:\Users\*****\AppData\Roaming\Python\Python310\site-packages\boto3\__init__.py", line 17, in <module> from boto3.session import Session File "C:\Users\*****\AppData\Roaming\Python\Python310\site-packages\boto3\session.py", line 17, in <module> import botocore.session File "C:\Users\*****\AppData\Roaming\Python\Python310\site-packages\botocore\session.py", line 26, in <module> import botocore.client File "C:\Users\*****\AppData\Roaming\Python\Python310\site-packages\botocore\client.py", line 15, in <module> from botocore import waiter, xform_name File "C:\Users\*****\AppData\Roaming\Python\Python310\site-packages\botocore\waiter.py", line 16, in <module> import jmespath ModuleNotFoundError: No module named 'jmespath'
```

### System Info

```shell
Windows 10
48GB RAM
RTX 3090
AMD 3600 XT
```

**Comment by jllllll** [comment]
This seems to be due to Python importing `boto3` from outside of the Conda environment.

`set PYTHONNOUSERSITE=1` is supposed to prevent this, but I guess Python doesn't care much about isolation. I've tried many things to isolate the Conda environment from system packages, but there doesn't seem to be much else to do.

`boto3` is an optional dependency of `accelerate`. However, the way that `accelerate` checks if it is installed is by trying to import it. Since Python is happy to import packages from pretty much anywhere, it finds `boto3` in your system Python installation.

Only real solution I see is adding `boto3` and `jmespath` to the webui's requirements.txt.
