### ISSUE TITLE
Cannot load llama-30b-hf = ValueError: weight is on the meta device, we need a `value` to put in on 0.

### ISSUE THREAD

**Issue by GenTxt** [oobabooga/text-generation-webui#244]
Thanks for the hard work on this repo. Tested first with llama-7b-hf and works great. 

Looking forward to testing llama-30b-hf but keep running into this error after what appears to be successful loading:

ValueError: weight is on the meta device, we need a `value` to put in on 0.

Running on ubuntu 22.04 in conda and have installed all requirements as per instructions. 

Attempting to run modified commands from 'api-example.py' inside (textgen) conda environment.

python server.py --model llama-30b-hf --no-stream --gpu-memory 20 20 --cpu-memory 30

Gpu memory is balanced on 2 RTX 24 gig cards @ 18+ to 21+ per card with approximately 33+ gigs ram used of 64 available.

Loading llama-30b-hf...

Loading checkpoint shards: 100%|████████████████| 61/61 [10:39<00:00, 10.49s/it]

Traceback (most recent call last):
  File "/home/ubuntubox/Desktop/oobabooga/text-generation-webui-main/server.py", line 194, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/ubuntubox/Desktop/oobabooga/text-generation-webui-main/modules/models.py", line 171, in load_model
    model = eval(command)
  File "<string>", line 1, in <module>
  File "/home/ubuntubox/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "/home/ubuntubox/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2681, in from_pretrained
    dispatch_model(model, device_map=device_map, offload_dir=offload_folder, offload_index=offload_index)
  File "/home/ubuntubox/.local/lib/python3.10/site-packages/accelerate/big_modeling.py", line 290, in dispatch_model
    attach_align_device_hook_on_blocks(
  File "/home/ubuntubox/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 486, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/home/ubuntubox/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 486, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/home/ubuntubox/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 486, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/home/ubuntubox/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 462, in attach_align_device_hook_on_blocks
    add_hook_to_module(module, hook)
  File "/home/ubuntubox/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 146, in add_hook_to_module
    module = hook.init_hook(module)
  File "/home/ubuntubox/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 235, in init_hook
    set_module_tensor_to_device(module, name, self.execution_device)
  File "/home/ubuntubox/.local/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 117, in set_module_tensor_to_device
    raise ValueError(f"{tensor_name} is on the meta device, we need a `value` to put in on {device}.")

ValueError: weight is on the meta device, we need a `value` to put in on 0.

Perhaps the model was corrupted during download from https://huggingface.co/decapoda-research/llama-30b-hf ???

Any help is appreciated.

**Comment by ImpossibleExchange** [comment]
@GenTxt  Having the same issue with the 13b-hf model. It was working for me, then after getting the 4bit to work, it stopped. Similar setup of a 2x ampere card setup. Was using the model and weights from the magnets, but then used the Decapoda Research ones trying to get it to work again. Going to waste some time on it again, and I will let you know if I make any progress.

**Comment by ImpossibleExchange** [comment]
@GenTxt , 

Okay, so here's what I ended up doing, and I have everything working back as normal, or as close to it as I can say. This first bit isn't probably relevant to you, but I will include everything I did. 

(I was running on manjaro, had gobs of kernel panics and other cuda issues etc, so I switched over to ubuntu this morning. I kept my old folder on the nvme and the like.) 

What seemed to fix my issue was using the 

python download-model.py organization/model 

for the affected models. I suppose I also did a clean install of the webui as well. Anyways this got me sorted. I suppose it was some sort of issue with the mapping, and maybe downloading the models directly rather than dumping them solved this, why I couldn't say, but I am up and running. 

Give this a try and let me know if it helps you out. 

Peace and best to you!

**Comment by GenTxt** [comment]
@ImpossibleExchange 

Thanks for looking into this. Was about to test 4bit until I saw your post. Will run recommendation. Currently downloading 7b and 30b 4bit

Cheers

**Comment by GenTxt** [comment]
Having success with current 30b 4bit and looking forward to testing 66b 4bit. Will wait on downloading and testing 30b in fp16 as all versions can be updated at any time.

Needed to add this to 'server.py'

import os

os.environ ["CUDA_VISIBLE_DEVICES"] = "0,1"

and in repositories/GPTQ-for-LLaMa/llama.py

# change the line from checkpoint.endswith('.safetensors') to checkpoint.as_posix().endswith('.safetensors')

    print('Loading model ...')
    if checkpoint.as_posix().endswith('.safetensors'):

Closing for now
