### ISSUE TITLE
Chat interface - IndexError: list index out of range

### ISSUE THREAD

**Issue by gbajson-area22** [oobabooga/text-generation-webui#2451]
### Describe the bug

After switching interface to "chat" I am no longer able to use UI.
Any try to talk application produces the following exception:

```
Traceback (most recent call last):
  File "/home/skyhook-user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/skyhook-user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/skyhook-user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/skyhook-user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 339, in async_iteration
    return await iterator.__anext__()
  File "/home/skyhook-user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 332, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/skyhook-user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/skyhook-user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/skyhook-user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/skyhook-user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 315, in run_sync_iterator_async
    return next(iterator)
  File "/home/skyhook-user/oobabooga_linux/text-generation-webui/modules/chat.py", line 327, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, shared.history, state, regenerate, _continue, loading_message=True)):
  File "/home/skyhook-user/oobabooga_linux/text-generation-webui/modules/chat.py", line 321, in generate_chat_reply
    for history in chatbot_wrapper(text, history, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "/home/skyhook-user/oobabooga_linux/text-generation-webui/modules/chat.py", line 199, in chatbot_wrapper
    stopping_strings = get_stopping_strings(state)
  File "/home/skyhook-user/oobabooga_linux/text-generation-webui/modules/chat.py", line 133, in get_stopping_strings
    state['turn_template'].split('<|user-message|>')[1].split('<|bot|>')[0] + '<|bot|>',
IndexError: list index out of range
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Change interface to chat
2. Try to chat
3. Observe logs

### Logs

```shell
To create a public link, set `share=True` in `launch()`.
Closing server running on port: 7860
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/home/skyhook-user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/skyhook-user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/skyhook-user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/skyhook-user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 339, in async_iteration
    return await iterator.__anext__()
  File "/home/skyhook-user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 332, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/skyhook-user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/skyhook-user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/skyhook-user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/skyhook-user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 315, in run_sync_iterator_async
    return next(iterator)
  File "/home/skyhook-user/oobabooga_linux/text-generation-webui/modules/chat.py", line 327, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, shared.history, state, regenerate, _continue, loading_message=True)):
  File "/home/skyhook-user/oobabooga_linux/text-generation-webui/modules/chat.py", line 321, in generate_chat_reply
    for history in chatbot_wrapper(text, history, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "/home/skyhook-user/oobabooga_linux/text-generation-webui/modules/chat.py", line 199, in chatbot_wrapper
    stopping_strings = get_stopping_strings(state)
  File "/home/skyhook-user/oobabooga_linux/text-generation-webui/modules/chat.py", line 133, in get_stopping_strings
    state['turn_template'].split('<|user-message|>')[1].split('<|bot|>')[0] + '<|bot|>',
IndexError: list index out of range
Closing server running on port: 7860
```
```


### System Info

```shell
GCP G2 VM with Debian 11.
```

**Comment by gbajson-area22** [comment]
This only happens when Instruction template is set to None (default behaviour).
When I set up instruction template to Alpaca it started to work.

**Comment by JediMaster25** [comment]
I encountered a similar error, but I was unable to resolve it by choosing the instruction template "Alpaca" from the `Chat settings`.

# Reproduction:
1. Install and download [4bit/pyg-7b-4bit-128g-cuda](https://huggingface.co/4bit/pyg-7b-4bit-128g-cuda).
2. Refresh the list and select the model.
3. In the GPTQ parameters, choose wbit 4, groupsize 128, and model_type "llama."
4. Save the settings and click "reload."
5. Proceed to the text generation section, enter some text, and click "generate."
6. The error mentioned in the logs is displayed. Despite attempting to resolve the issue by selecting the instruction template "Alpaca" from the `Chat settings`, the error persists.

# Logs
```
❯ ./start_linux.sh


*******************************************************************
* WARNING: You haven't downloaded any model yet.
* Once the web UI launches, head over to the bottom of the "Model" tab and download one.
*******************************************************************


bin /mnt/storage/Software/Linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/mnt/storage/Software/Linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/mnt/storage/Software/Linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
2023-06-13 23:11:23 INFO:Loading the extension "gallery"...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/mnt/storage/Software/Linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/mnt/storage/Software/Linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/mnt/storage/Software/Linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/mnt/storage/Software/Linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/mnt/storage/Software/Linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/mnt/storage/Software/Linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/mnt/storage/Software/Linux/oobabooga_linux/text-generation-webui/server.py", line 255, in load_model_specific_settings
    model_settings = get_model_specific_settings(model)
  File "/mnt/storage/Software/Linux/oobabooga_linux/text-generation-webui/server.py", line 247, in get_model_specific_settings
    if re.match(pat.lower(), model.lower()):
AttributeError: 'NoneType' object has no attribute 'lower'
2023-06-13 23:34:40 INFO:Loading None...
2023-06-13 23:34:40 ERROR:The path to the model does not exist. Exiting.
Downloading the model to models/4bit_pyg-7b-4bit-128g-cuda
100%|███████████████████████████████████████████████████████████████████████████████████████████| 76.0  /76.0   913kiB/s
100%|██████████████████████████████████████████████████████████████████████████████████████████| 598   /598    8.65MiB/s
100%|██████████████████████████████████████████████████████████████████████████████████████████| 137   /137    1.19MiB/s
100%|██████████████████████████████████████████████████████████████████████████████████████████| 4.00G /4.00G  11.5MiB/s
100%|██████████████████████████████████████████████████████████████████████████████████████████| 26.8k /26.8k  15.9MiB/s
100%|██████████████████████████████████████████████████████████████████████████████████████████| 411   /411    3.98MiB/s
100%|██████████████████████████████████████████████████████████████████████████████████████████| 1.84M /1.84M  3.35MiB/s
100%|██████████████████████████████████████████████████████████████████████████████████████████| 500k  /500k   11.7MiB/s
100%|██████████████████████████████████████████████████████████████████████████████████████████| 783   /783    7.57MiB/s
Traceback (most recent call last):
  File "/mnt/storage/Software/Linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/mnt/storage/Software/Linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/mnt/storage/Software/Linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/mnt/storage/Software/Linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "/mnt/storage/Software/Linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "/mnt/storage/Software/Linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/mnt/storage/Software/Linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/mnt/storage/Software/Linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/mnt/storage/Software/Linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "/mnt/storage/Software/Linux/oobabooga_linux/text-generation-webui/server.py", line 274, in save_model_settings
    model_regex = model + '$'  # For exact matches
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
2023-06-13 23:46:38 INFO:Loading 4bit_pyg-7b-4bit-128g-cuda...
2023-06-13 23:46:38 INFO:The AutoGPTQ params are: {'model_basename': 'pyg7b-4bit-128g', 'device': 'cpu', 'use_triton': False, 'use_safetensors': True, 'trust_remote_code': False, 'max_memory': None, 'quantize_config': BaseQuantizeConfig(bits=4, group_size=128, damp_percent=0.01, desc_act=False, sym=True, true_sequential=True, model_name_or_path=None, model_file_base_name=None)}
2023-06-13 23:46:39 WARNING:CUDA extension not installed.
2023-06-13 23:46:40 WARNING:The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
2023-06-13 23:46:40 WARNING:The safetensors archive passed at models/4bit_pyg-7b-4bit-128g-cuda/pyg7b-4bit-128g.safetensors does not contain metadata. Make sure to save your model with the `save_pretrained` method. Defaulting to 'pt' metadata.
2023-06-13 23:47:39 WARNING:skip module injection for FusedLlamaMLPForQuantizedModel not support integrate without triton yet.
2023-06-13 23:47:39 INFO:Loaded the model in 61.10 seconds.

2023-06-13 23:47:41 INFO:Loading 4bit_pyg-7b-4bit-128g-cuda...
2023-06-13 23:47:41 INFO:The AutoGPTQ params are: {'model_basename': 'pyg7b-4bit-128g', 'device': 'cpu', 'use_triton': False, 'use_safetensors': True, 'trust_remote_code': False, 'max_memory': None, 'quantize_config': BaseQuantizeConfig(bits=4, group_size=128, damp_percent=0.01, desc_act=False, sym=True, true_sequential=True, model_name_or_path=None, model_file_base_name=None)}
2023-06-13 23:47:42 WARNING:The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
2023-06-13 23:47:42 WARNING:The safetensors archive passed at models/4bit_pyg-7b-4bit-128g-cuda/pyg7b-4bit-128g.safetensors does not contain metadata. Make sure to save your model with the `save_pretrained` method. Defaulting to 'pt' metadata.
2023-06-13 23:48:42 WARNING:skip module injection for FusedLlamaMLPForQuantizedModel not support integrate without triton yet.
2023-06-13 23:48:42 INFO:Loaded the model in 61.17 seconds.

Traceback (most recent call last):
  File "/mnt/storage/Software/Linux/oobabooga_linux/text-generation-webui/modules/callbacks.py", line 73, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/mnt/storage/Software/Linux/oobabooga_linux/text-generation-webui/modules/text_generation.py", line 263, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/mnt/storage/Software/Linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/auto_gptq/modeling/_base.py", line 422, in generate
    with torch.inference_mode(), torch.amp.autocast(device_type=self.device.type):
  File "/mnt/storage/Software/Linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/auto_gptq/modeling/_base.py", line 411, in device
    device = [d for d in self.hf_device_map.values() if d not in {'cpu', 'disk'}][0]
IndexError: list index out of range
```

# System Info

## Kernel Version
```
❯uname -a
Linux arch 6.1.31-2-MANJARO #1 SMP PREEMPT_DYNAMIC Sun Jun  4 12:31:46 UTC 2023 x86_64 GNU/Linux
```

## Distribution Information
```
❯cat /etc/*-release
Manjaro Linux
DISTRIB_ID="ManjaroLinux"
DISTRIB_RELEASE="23.0.0"
DISTRIB_CODENAME="Ultima Thule"
DISTRIB_DESCRIPTION="Manjaro Linux"
Manjaro Linux
NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux

## Graphics Driver
```
❯mhwd -li
[1m[31m> [mInstalled PCI configs:
--------------------------------------------------------------------------------
                  NAME               VERSION          FREEDRIVER           TYPE
--------------------------------------------------------------------------------
           video-linux            2018.05.04                true            PCI


[1m[31mWarning: [mNo installed USB configs!
```

## Hardware Information
```
❯inxi -Fxz
System:
  Kernel: 6.1.31-2-MANJARO arch: x86_64 bits: 64 compiler: gcc v: 13.1.1
    Desktop: Cinnamon v: 5.6.8 Distro: Manjaro Linux base: Arch Linux
Machine:
  Type: Desktop System: Gigabyte product: B450M DS3H v: N/A
    serial: <superuser required>
  Mobo: Gigabyte model: B450M DS3H-CF v: x.x serial: <superuser required>
    UEFI: American Megatrends LLC. v: F61c date: 05/10/2021
CPU:
  Info: 8-core model: AMD Ryzen 7 5700G with Radeon Graphics bits: 64
    type: MT MCP arch: Zen 3 rev: 0 cache: L1: 512 KiB L2: 4 MiB L3: 16 MiB
  Speed (MHz): avg: 1550 high: 3800 min/max: 1400/4672 boost: enabled cores:
    1: 1400 2: 1400 3: 1400 4: 1400 5: 1400 6: 1400 7: 1400 8: 1400 9: 3800
    10: 1400 11: 1400 12: 1400 13: 1400 14: 1400 15: 1400 16: 1400
    bogomips: 121419
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD Cezanne [Radeon Vega Series / Radeon Mobile Series]
    vendor: Gigabyte driver: amdgpu v: kernel arch: GCN-5 bus-ID: 07:00.0
    temp: 32.0 C
  Display: x11 server: X.Org v: 21.1.8 with: Xwayland v: 23.1.1 driver: X:
    loaded: amdgpu unloaded: modesetting dri: radeonsi gpu: amdgpu
    resolution: 1920x1080~60Hz
  API: OpenGL v: 4.6 Mesa 23.0.4 renderer: AMD Radeon Graphics (renoir LLVM
    15.0.7 DRM 3.49 6.1.31-2-MANJARO) direct-render: Yes
Audio:
  Device-1: AMD Renoir Radeon High Definition Audio driver: snd_hda_intel
    v: kernel bus-ID: 07:00.1
  Device-2: AMD Family 17h/19h HD Audio vendor: Gigabyte
    driver: snd_hda_intel v: kernel bus-ID: 07:00.6
  API: ALSA v: k6.1.31-2-MANJARO status: kernel-api
  Server-1: JACK v: 1.9.22 status: off
  Server-2: PipeWire v: 0.3.70 status: off
  Server-3: PulseAudio v: 16.1 status: active
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    vendor: Gigabyte driver: r8169 v: kernel port: f000 bus-ID: 04:00.0
  IF: enp4s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
  IF-ID-1: docker0 state: down mac: <filter>
Drives:
  Local Storage: total: 10.01 TiB used: 5.12 TiB (51.2%)
  ID-1: /dev/nvme0n1 vendor: Western Digital model: WDS100T2B0C-00PXH0
    size: 931.51 GiB temp: 39.9 C
  ID-2: /dev/sda vendor: Seagate model: Expansion size: 4.55 TiB type: USB
  ID-3: /dev/sdb vendor: Seagate model: Portable size: 4.55 TiB type: USB
Partition:
  ID-1: / size: 882.24 GiB used: 321.53 GiB (36.4%) fs: ext4
    dev: /dev/nvme0n1p2
  ID-2: /boot/efi size: 299.4 MiB used: 312 KiB (0.1%) fs: vfat
    dev: /dev/nvme0n1p1
Swap:
  ID-1: swap-1 type: partition size: 33.82 GiB used: 2.5 MiB (0.0%)
    dev: /dev/nvme0n1p3
Sensors:
  System Temperatures: cpu: 44.0 C mobo: 36.0 C gpu: amdgpu temp: 33.0 C
  Fan Speeds (RPM): N/A
Info:
  Processes: 456 Uptime: 15h 37m Memory: available: 30.74 GiB
  used: 13.2 GiB (43.0%) Init: systemd Compilers: gcc: 13.1.1 clang: 15.0.7
  Packages: 2168 Shell: Zsh v: 5.9 inxi: 3.3.27
```

**Comment by vmelog** [comment]
same here

**Comment by LitenBuzzTh** [comment]
same here, I don't know why, but it happened this morning. yesterday it was fine.
Any solution for this?

**Comment by DeBuGWoLf** [comment]
same problem
