### ISSUE TITLE
ModuleNotFoundError: No module named 'peft'

### ISSUE THREAD

**Issue by 4m1r4h** [oobabooga/text-generation-webui#2453]
I'm facing an issue with the 'peft' module in my project, and I could use some assistance. Even though I have installed the 'peft' module, I keep getting a "ModuleNotFoundError: No module named 'peft'" error when running start_windows.

`Traceback (most recent call last):
  File "C:\Users\Downloads\windows\oobabooga_windows\text-generation-webui\server.py", line 49, in <module>
    from modules import chat, shared, training, ui, utils
  File "C:\Users\Downloads\windows\oobabooga_windows\text-generation-webui\modules\training.py", line 14, in <module>
    from peft import (LoraConfig, get_peft_model, prepare_model_for_int8_training,
ModuleNotFoundError: No module named 'peft'

Done!
Press any key to continue . . .`

I've followed the installation instructions and confirmed that 'peft' is installed in my project's environment.
I'm not sure why the 'peft' module is not being recognized even after installation. Has anyone else encountered a similar issue or have any suggestions on how to resolve this?

**Comment by 4m1r4h** [comment]
> You probably installed it ouside of the venv.
> 
> 1. Run `cmd_windows.bat` (which will activate the venv)
> 2. Run `pip install peft`
> 3. Close the window (or not, doesn't matter) and start the GUI

I have installed it in the cmd_windows.bat. When I run pip install peft it says requirement already satisfied. Should I try deleting peft and install it again?
