### ISSUE TITLE
Streaming api deadlock

### ISSUE THREAD

**Issue by xzqxnet0990** [oobabooga/text-generation-webui#2475]
### Describe the bug

When I am using mutiple threads to pressure measurement the streaming api.
I think it will cause a deadlock.
The code is here /extension/api/streaming_api.py line(51).

async def _handle_connection(self, websocket, path):

        self.send_response(200)
        self.send_header('Content-type', 'text/plain')
        self.send_header('Transfer-Encoding', 'chunked')
        self.end_headers()
        if self.path == '/api/v1/stream':
            async for message in websocket:
                message = json.loads(message)

                prompt = message['prompt']
                generate_params = build_parameters(message)
                stopping_strings = generate_params.pop('stopping_strings')
                generate_params['stream'] = True

                generator = generate_reply(
                    prompt, generate_params, stopping_strings=stopping_strings, is_chat=False)

```
def generate_reply(*args, **kwargs):
    shared.generation_lock.acquire()
    try:
        for result in _generate_reply(*args, **kwargs):
            yield result
    finally:
        shared.generation_lock.release()
```

and It will always cause websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received problem.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Use WebSocket request-response Sampler and thread group with 2 threads to pressure measurement the port 5005/api/v1/stream.

### Logs

```shell
Traceback (most recent call last):
  File "/data/ketadb/llm/venv/lib/python3.8/site-packages/websockets/legacy/server.py", line 240, in handler
    await self.ws_handler(self)
  File "/data/ketadb/llm/venv/lib/python3.8/site-packages/websockets/legacy/server.py", line 1186, in _ws_handler
    return await cast(
  File "/home/ubuntu/llm/text-generation-webui/extensions/api/streaming_api.py", line 18, in _handle_connection
    async for message in websocket:
  File "/data/ketadb/llm/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 497, in __aiter__
    yield await self.recv()
  File "/data/ketadb/llm/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/data/ketadb/llm/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 935, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
```

### System Info

```shell
GPU:T4
System:Ubuntu 20.0.4
CPU:2.8Ghz
Just Use CPU with llama.cpp
```

**Comment by meditans** [comment]
I'm hitting this problem too. Here's another way of reproducing this: when the streaming server is up, use this command twice (in two different terminals):
```
[nix-shell:~]$ websocat ws://<HOST>:5005/api/v1/stream
{"top_k":40,"mirostat_tau":5,"epsilon_cutoff":0,"tfs":1,"penalty_alpha":0,"top_p":0.5,"max_new_tokens":2000,"mirostat_mode":0,"num_beams":1,"no_repeat_ngram_size":0,"mirostat_eta":0.1,"typical_p":1,"stopping_strings":[],"seed":-1,"skip_special_tokens":true,"add_bos_token":true,"prompt":"generate a poem\n","eta_cutoff":0,"do_sample":true,"ban_eos_token":false,"early_stopping":false,"repetition_penalty":1.18,"min_length":0,"length_penalty":1,"top_a":0,"temperature":0.7,"truncation_length":2048}    
```
A couple moments after you issue the second command, you can see the generation stopping, and you will see the error message in the server:
```
ERROR:connection handler failed
Traceback (most recent call last):
  File "/app/venv/lib/python3.10/site-packages/websockets/legacy/server.py", line 240, in handler
    await self.ws_handler(self)
  File "/app/venv/lib/python3.10/site-packages/websockets/legacy/server.py", line 1186, in _ws_handler
    return await cast(
  File "/app/extensions/api/streaming_api.py", line 38, in _handle_connection
    await websocket.send(json.dumps({
  File "/app/venv/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 647, in send
    await self.write_frame(True, opcode, data)
  File "/app/venv/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1205, in write_frame
    await self.drain()
  File "/app/venv/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1194, in drain
    await self.ensure_open()
  File "/app/venv/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 935, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received

```

**Comment by meditans** [comment]
I'm not familiar with this codebase, but I think the crash is due to the way locking is done:

Here we're operating asyncronously over the messages we receive, ultimately calling `generate_reply`:
https://github.com/oobabooga/text-generation-webui/blob/c05edfcdfcfb61c9151ad94e0edc4ed682d22f19/extensions/api/streaming_api.py#L18-L27

But `generate-reply` is protected by the `shared.generation_lock`:
https://github.com/oobabooga/text-generation-webui/blob/c05edfcdfcfb61c9151ad94e0edc4ed682d22f19/modules/text_generation.py#L20-L26

Which is a simple lock:
https://github.com/oobabooga/text-generation-webui/blob/c05edfcdfcfb61c9151ad94e0edc4ed682d22f19/server.py#L1091

I think this could bring to a deadlock for reasons similar to the ones [in this article](https://superfastpython.com/asyncio-use-threading-lock/), In fact I patched the crash by using an `asyncio.Lock` around the websocket response. But then I stopped, because what I would really want here is the ability of having parallel inference (so that, for example, I can use Tree of Thoughts in a parallel way) and all the code seems structured around the idea of that lock.

Am I right, @oobabooga? Is there any llm inference framework that allows this kind of parallelism?

**Comment by meditans** [comment]
After researching the topic myself, I understand now why concurrent inference is no easy task. I suggest https://le.qun.ch/en/blog/2023/05/13/transformer-batching/ as a starting point to explore the issue.

**Comment by chrisrude** [comment]
This is a pretty big issue for folks who are using `oobabot`.  A lot of them have been running multiple chatbots against a single Oobabooga backend for months, in order to support chat rooms with multiple characters talking to each other.  It's pretty awesome, and appreciation for all the hard work here, but unfortunately it's broken at the moment.

Some people are setting up multiple different instances of Oobabooga to work around it (https://github.com/chrisrude/oobabot-plugin/issues/18), which is a pretty resource-intensive proposition.

I can confirm the assessment that @meditans provided is correct.  The regression appeared as a result of the changes landed in this commit d37a28730dc208ca5fbff50b32818a93a305b5ef.

As a temporary workaround, running from the commit just before does face this issue: 7dc87984a2347794beed957a1923203b70a597b9.

I'm happy to help with a fix here, the question is what approach folks want to take.

**Comment by oobabooga** [comment]
> This is a pretty big issue for folks who are using `oobabot`. A lot of them have been running multiple chatbots against a single Oobabooga backend for months, in order to support chat rooms with multiple characters talking to each other. It's pretty awesome, and appreciation for all the hard work here, but unfortunately it's broken at the moment.
> 
> Some people are setting up multiple different instances of Oobabooga to work around it ([chrisrude/oobabot-plugin#18](https://github.com/chrisrude/oobabot-plugin/issues/18)), which is a pretty resource-intensive proposition.
> 
> I can confirm the assessment that @meditans provided is correct. The regression appeared as a result of the changes landed in this commit [d37a287](https://github.com/oobabooga/text-generation-webui/commit/d37a28730dc208ca5fbff50b32818a93a305b5ef).
> 
> As a temporary workaround, one can run from the prior commit ([7dc8798](https://github.com/oobabooga/text-generation-webui/commit/7dc87984a2347794beed957a1923203b70a597b9)) which doesn't face this issue.
> 
> I'm happy to help with a fix here, the question is what approach folks want to take.

If you can find a solution, please feel free to submit a PR.

**Comment by chrisrude** [comment]
Posted my approach here: https://github.com/oobabooga/text-generation-webui/pull/3048.

I tested it, and it appears to work.  Let me know what you think!

**Comment by oobabooga** [comment]
v4.0 now supports parallel API requests for llama.cpp, ExLlamaV3, and TensorRT-LLM. This should resolve the deadlock when multiple clients connect simultaneously. See the [docs](https://github.com/oobabooga/text-generation-webui/wiki/12-%E2%80%90-OpenAI-API#python-parallel-requests-example) and [release notes](https://github.com/oobabooga/text-generation-webui/releases/tag/v4.0).
