### ISSUE TITLE
Does not work with OpenCALM 7B

### ISSUE THREAD

**Issue by decolygs** [oobabooga/text-generation-webui#2484]
I need to solve a problem that does not work with OpenCALM 7B (cyberagent/open-calm-7b). 

Please advise me!!

<Situation>
In the Model tab, specify the above and download is possible.
In the Model tab, select the downloaded model (OpenCALM 7B) in Model, and Loading checkpoint shards: is completed = INFO: Loaded the model.
When attempting to generate the model in the Text generation tab, the following error occurs.

<Output error message>
Traceback (most recent call last):
  File “text-generation-webui/modules/callbacks.py", line 73, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  
File "text-generation-webui/modules/text_generation.py", line 286, in generate_with_callback
    shared.model.generate(**kwargs)

  File "installer_files/env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  
File "installer_files/env/lib/python3.10/site-packages/transformers/generation/utils.py", line 1568, in generate
    return self.sample(
  
File "/installer_files/env/lib/python3.10/site-packages/transformers/generation/utils.py", line 2612, in sample
    model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
  
File "installer_files/env/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 722, in prepare_inputs_for_generation
    position_ids = attention_mask.long().cumsum(-1) - 1

RuntimeError: MPS does not support cumsum op with int64 input

Output generated in 0.22 seconds (0.00 tokens/s, 0 tokens, context 100, seed 1821443272)

**Comment by yachty66** [comment]
are you on mac?

**Comment by decolygs** [comment]
Thank you.
Yes, MAC.

During setup GPU selection,
I selected Apple(M) and an error occurred,
I selected CPU Use,
The above error is still occurring.
