### ISSUE TITLE
Error on Launching third and second notebook in Colab

### ISSUE THREAD

**Issue by ghost** [oobabooga/text-generation-webui#2487]
Hey, yesterday it worked all fine, but now, after starting each notebook correctly, I first get this error in the second notebook:

ERROR: Cannot install -r requirements.txt (line 13) and safetensors==0.3.0 because these package versions have conflicting dependencies.

I think this is the reason why, after I start the third Notebook only get this Error:

Traceback (most recent call last): File "/content/text-generation-webui/download-model.py", line 169, in <module> links, is_lora = get_download_links_from_huggingface(model, branch) File "/content/text-generation-webui/download-model.py", line 113, in get_download_links_from_huggingface fname = dict[i]['path'] KeyError: 0 python server.py --share --model pygmalion-6b_original-sharded --settings settings-colab.json --no-stream --load-in-8bit --extensions gallery --chat Traceback (most recent call last): File "/content/text-generation-webui/server.py", line 9, in <module> import gradio as gr ModuleNotFoundError: No module named 'gradio'

I hope I didn't miss understand something. And yes, I tried to modify the requirements.txt myself, but the Colab-Backend just don't respond on download. I used this Colab: https://colab.research.google.com/github/oobabooga/AI-Notebooks/blob/main/Colab-TextGen-GPU.ipynb

If there is a newer one, that works, I would really like it.

**Comment by Amritanshu312** [comment]
hey can I ask you a question it's not about your issue but how can you connect your Oobabooga chat model which is in google colab and connect it in Python which is on my PC using API
