### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by grigio** [oobabooga/text-generation-webui#2489]
### Describe the bug

I've issues running on Linux

pip install -r requirements.txt

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

pip install -r requirements.txt

### Logs

```shell
Ignoring bitsandbytes: markers 'platform_system == "Windows"' don't match your environment
Ignoring llama-cpp-python: markers 'platform_system == "Windows"' don't match your environment
Ignoring auto-gptq: markers 'platform_system == "Windows"' don't match your environment
ERROR: auto_gptq-0.2.0+cu117-cp310-cp310-linux_x86_64.whl is not a supported wheel on this platform.

Linux hua 6.3.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 30 May 2023 13:44:01 +0000 x86_64 GNU/Linux

```
```


### System Info

```shell
Linux hua 6.3.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 30 May 2023 13:44:01 +0000 x86_64 GNU/Linux
```

**Comment by grigio** [comment]
it seems the conda installed via Linux Distro works diffently

```
TypeError: 'NoneType' object is not subscriptable
```

**Comment by ethdig** [comment]
I did the installation but it gives the model not found error. don't tire yourself, check it out when the update comes.

**Comment by jllllll** [comment]
Open a Python terminal and enter these commands to show how Python interprets your system:
```python
import platform
platform.system()
platform.machine()
```
I can add filters to the requirements.txt based on the output.

**Comment by grigio** [comment]
```
python
Python 3.10.10 (main, Mar 21 2023, 18:45:11) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.system()
'Linux'
>>> platform.machine()
'x86_64'
>>> 

```

**Comment by jllllll** [comment]
> ```
> python
> Python 3.10.10 (main, Mar 21 2023, 18:45:11) [GCC 11.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import platform
> >>> platform.system()
> 'Linux'
> >>> platform.machine()
> 'x86_64'
> >>> 
> ```

Well... That is the exact platform that wheel was made for. Does it install if you do it manually?
```
python -m pip install https://github.com/PanQiWei/AutoGPTQ/releases/download/v0.2.0/auto_gptq-0.2.0+cu117-cp310-cp310-linux_x86_64.whl
```
I'm pretty confused what it means by `not a supported wheel on this platform` when the only identification it has matches your platform. See what this command says:
```python
import os
os.uname()
```

**Comment by grigio** [comment]
now I get

```
ModuleNotFoundError: No module named '_cffi_backend'

```

**Comment by grigio** [comment]
this is the full log

```
(textgen) ➜  text-generation-webui git:(main) ✗ python server.py               









bin /home/grigio/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/grigio/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/grigio/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/grigio/Code/text-generation-webui/server.py:49 in <module>                                 │
│                                                                                                  │
│     46 from PIL import Image                                                                     │
│     47                                                                                           │
│     48 import modules.extensions as extensions_module                                            │
│ ❱   49 from modules import chat, shared, training, ui, utils                                     │
│     50 from modules.extensions import apply_extensions                                           │
│     51 from modules.html_generator import chat_html_wrapper                                      │
│     52 from modules.LoRA import add_lora_to_model                                                │
│                                                                                                  │
│ /home/grigio/Code/text-generation-webui/modules/training.py:14 in <module>                       │
│                                                                                                  │
│    11 import torch                                                                               │
│    12 import transformers                                                                        │
│    13 from datasets import Dataset, load_dataset                                                 │
│ ❱  14 from peft import (LoraConfig, get_peft_model, prepare_model_for_int8_training,             │
│    15 │   │   │   │     set_peft_model_state_dict)                                               │
│    16                                                                                            │
│    17 from modules import shared, ui, utils                                                      │
│                                                                                                  │
│ /home/grigio/miniconda3/envs/textgen/lib/python3.10/site-packages/peft/__init__.py:22 in         │
│ <module>                                                                                         │
│                                                                                                  │
│   19                                                                                             │
│   20 __version__ = "0.4.0.dev0"                                                                  │
│   21                                                                                             │
│ ❱ 22 from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_    │
│   23 from .peft_model import (                                                                   │
│   24 │   PeftModel,                                                                              │
│   25 │   PeftModelForCausalLM,                                                                   │
│                                                                                                  │
│ /home/grigio/miniconda3/envs/textgen/lib/python3.10/site-packages/peft/mapping.py:16 in <module> │
│                                                                                                  │
│    13 # See the License for the specific language governing permissions and                      │
│    14 # limitations under the License.                                                           │
│    15                                                                                            │
│ ❱  16 from .peft_model import (                                                                  │
│    17 │   PeftModel,                                                                             │
│    18 │   PeftModelForCausalLM,                                                                  │
│    19 │   PeftModelForSeq2SeqLM,                                                                 │
│                                                                                                  │
│ /home/grigio/miniconda3/envs/textgen/lib/python3.10/site-packages/peft/peft_model.py:31 in       │
│ <module>                                                                                         │
│                                                                                                  │
│     28 from transformers.modeling_outputs import SequenceClassifierOutput, TokenClassifierOutpu  │
│     29 from transformers.utils import PushToHubMixin                                             │
│     30                                                                                           │
│ ❱   31 from .tuners import (                                                                     │
│     32 │   AdaLoraModel,                                                                         │
│     33 │   AdaptionPromptModel,                                                                  │
│     34 │   LoraModel,                                                                            │
│                                                                                                  │
│ /home/grigio/miniconda3/envs/textgen/lib/python3.10/site-packages/peft/tuners/__init__.py:21 in  │
│ <module>                                                                                         │
│                                                                                                  │
│   18 # limitations under the License.                                                            │
│   19                                                                                             │
│   20 from .adaption_prompt import AdaptionPromptConfig, AdaptionPromptModel                      │
│ ❱ 21 from .lora import LoraConfig, LoraModel                                                     │
│   22 from .adalora import AdaLoraConfig, AdaLoraModel                                            │
│   23 from .p_tuning import PromptEncoder, PromptEncoderConfig, PromptEncoderReparameterizatio    │
│   24 from .prefix_tuning import PrefixEncoder, PrefixTuningConfig                                │
│                                                                                                  │
│ /home/grigio/miniconda3/envs/textgen/lib/python3.10/site-packages/peft/tuners/lora.py:40 in      │
│ <module>                                                                                         │
│                                                                                                  │
│    37                                                                                            │
│    38                                                                                            │
│    39 if is_bnb_available():                                                                     │
│ ❱  40 │   import bitsandbytes as bnb                                                             │
│    41                                                                                            │
│    42                                                                                            │
│    43 @dataclass                                                                                 │
│                                                                                                  │
│ /home/grigio/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/__init__.py:16 in │
│ <module>                                                                                         │
│                                                                                                  │
│   13 │   matmul_4bit                                                                             │
│   14 )                                                                                           │
│   15 from .cextension import COMPILED_WITH_CUDA                                                  │
│ ❱ 16 from .nn import modules                                                                     │
│   17                                                                                             │
│   18 if COMPILED_WITH_CUDA:                                                                      │
│   19 │   from .optim import adam                                                                 │
│                                                                                                  │
│ /home/grigio/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/nn/__init__.py:6  │
│ in <module>                                                                                      │
│                                                                                                  │
│   3 # This source code is licensed under the MIT license found in the                            │
│   4 # LICENSE file in the root directory of this source tree.                                    │
│   5 from .modules import Int8Params, Linear8bitLt, StableEmbedding, Linear4bit, LinearNF4, L     │
│ ❱ 6 from .triton_based_modules import SwitchBackLinear, SwitchBackLinearGlobal, SwitchBackLi     │
│   7                                                                                              │
│                                                                                                  │
│ /home/grigio/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/nn/triton_based_m │
│ odules.py:8 in <module>                                                                          │
│                                                                                                  │
│     5                                                                                            │
│     6 from bitsandbytes.triton.triton_utils import is_triton_available                           │
│     7                                                                                            │
│ ❱   8 from bitsandbytes.triton.dequantize_rowwise import dequantize_rowwise                      │
│     9 from bitsandbytes.triton.quantize_rowwise import quantize_rowwise                          │
│    10 from bitsandbytes.triton.quantize_columnwise_and_transpose import quantize_columnwise_an   │
│    11 from bitsandbytes.triton.int8_matmul_rowwise_dequantize import int8_matmul_rowwise_dequa   │
│                                                                                                  │
│ /home/grigio/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/triton/dequantize │
│ _rowwise.py:10 in <module>                                                                       │
│                                                                                                  │
│    7 │   def dequantize_rowwise(x: torch.Tensor, state_x: torch.Tensor): return None             │
│    8 else:                                                                                       │
│    9 │                                                                                           │
│ ❱ 10 │   import triton                                                                           │
│   11 │   import triton.language as tl                                                            │
│   12 │   from triton.ops.matmul_perf_model import early_config_prune, estimate_matmul_time       │
│   13                                                                                             │
│                                                                                                  │
│ /home/grigio/.local/lib/python3.10/site-packages/triton/__init__.py:20 in <module>               │
│                                                                                                  │
│   17 │   reinterpret,                                                                            │
│   18 │   TensorWrapper,                                                                          │
│   19 )                                                                                           │
│ ❱ 20 from .runtime import (                                                                      │
│   21 │   autotune,                                                                               │
│   22 │   Config,                                                                                 │
│   23 │   heuristics,                                                                             │
│                                                                                                  │
│ /home/grigio/.local/lib/python3.10/site-packages/triton/runtime/__init__.py:1 in <module>        │
│                                                                                                  │
│ ❱  1 from .autotuner import Config, Heuristics, autotune, heuristics                             │
│    2 from .jit import JITFunction, KernelInterface, version_key                                  │
│    3                                                                                             │
│    4 __all__ = [                                                                                 │
│                                                                                                  │
│ /home/grigio/.local/lib/python3.10/site-packages/triton/runtime/autotuner.py:7 in <module>       │
│                                                                                                  │
│     4 import time                                                                                │
│     5 from typing import Dict                                                                    │
│     6                                                                                            │
│ ❱   7 from ..compiler import OutOfResources                                                      │
│     8 from ..testing import do_bench                                                             │
│     9 from .jit import KernelInterface                                                           │
│    10                                                                                            │
│                                                                                                  │
│ /home/grigio/.local/lib/python3.10/site-packages/triton/compiler.py:1888 in <module>             │
│                                                                                                  │
│   1885   else:                                                                                   │
│   1886 │     return {}                                                                           │
│   1887                                                                                           │
│ ❱ 1888 @static_vars(amdgcn_bitcode_paths = _get_amdgcn_bitcode_paths())                          │
│   1889 def get_amdgcn_bitcode_paths():                                                           │
│   1890   return get_amdgcn_bitcode_paths.amdgcn_bitcode_paths                                    │
│   1891                                                                                           │
│                                                                                                  │
│ /home/grigio/.local/lib/python3.10/site-packages/triton/compiler.py:1867 in                      │
│ _get_amdgcn_bitcode_paths                                                                        │
│                                                                                                  │
│   1864 │   │   │   │   │   │   │   │   │   │   │    "oclc_unsafe_math_off.bc",                   │
│   1865 │   │   │   │   │   │   │   │   │   │   │    "oclc_wavefrontsize64_on.bc"]                │
│   1866 │                                                                                         │
│ ❱ 1867 │     gfx_arch = _get_amdgcn_bitcode_paths.discovered_gfx_arch_fulldetails[1]             │
│   1868 │     gfx_arch_id = re.search('gfx(\\w+)', gfx_arch).group(1).strip()                     │
│   1869 │                                                                                         │
│   1870 │     gpu_arch_specific_bitcode_library = 'oclc_isa_version_' + gfx_arch_id + ".bc"       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: 'NoneType' object is not subscriptable

```

**Comment by Omegastick** [comment]
In my case, it's because I was trying to install the Python 3.10 binary in a 3.9 environment.

The full binary list is here: https://github.com/PanQiWei/AutoGPTQ/releases/

**Comment by grigio** [comment]
> In my case, it's because I was trying to install the Python 3.10 binary in a 3.9 environment.

Isn't `conda` supposed to deal with that ?

```
(base) ➜  text-generation-webui git:(main) ✗ python --version
Python 3.10.10
(base) ➜  text-generation-webui git:(main) ✗ conda activate textgen       
(textgen) ➜  text-generation-webui git:(main) ✗ python --version 
Python 3.10.9
```

**Comment by yumemio** [comment]
@grigio `pip` invokes the default Python's `pip`, i.e. the one installed in your host OS, even in the conda environment (see [this SO answer](https://stackoverflow.com/a/56889729/13301046)).

How about using `python3 -m pip` instead?

```console
$ # 🙅 this does not work
$ pip install -r requirements.txt

$ # ✅ this works
$ python3 -m pip install -r requirements.txt
```

**Comment by grigio** [comment]
@yumemio 

I get the same error, it seems GPU support is required but i can run `llama.cpp` without it. I also tried to downgrade bitsandbytes as written in the docs

```
python3 server.py
bin /home/grigio/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/grigio/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
╭────────────────────── Traceback (most recent call last) ───────────────────────╮
│ /home/grigio/Code/text-generation-webui/server.py:49 in <module>               │
│                                                                                │
│     46 from PIL import Image                                                   │
│     47                                                                         │
│     48 import modules.extensions as extensions_module                          │
│ ❱   49 from modules import chat, shared, training, ui, utils 
```

**Comment by jllllll** [comment]
> @yumemio
> 
> I get the same error, it seems GPU support is required but i can run `llama.cpp` without it. I also tried to downgrade bitsandbytes as written in the docs
> 
> ```
> python3 server.py
> bin /home/grigio/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
> /home/grigio/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
>   warn("The installed version of bitsandbytes was compiled without GPU support. "
> ╭────────────────────── Traceback (most recent call last) ───────────────────────╮
> │ /home/grigio/Code/text-generation-webui/server.py:49 in <module>               │
> │                                                                                │
> │     46 from PIL import Image                                                   │
> │     47                                                                         │
> │     48 import modules.extensions as extensions_module                          │
> │ ❱   49 from modules import chat, shared, training, ui, utils 
> ```

I recently compiled a custom version of bitsandbytes for Linux with expanded CUDA search paths. Would you mind trying it to see if it fixes your issue? It can be installed with this command:
```
python -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/Wheels-Release/bitsandbytes-0.39.0-py3-none-linux_x86_64.whl --force-reinstall --no-deps
```
Source code: https://github.com/jllllll/bitsandbytes/tree/linux_0.39.0
It is based on the recent update to the main bitsandbytes source where compatibility with older GPUs was improved. Only 8bit works with older GPUs, the improvement was simply to allow those GPUs to install the latest version.

**Comment by grigio** [comment]
> 
> Keep in mind that what bitsandbytes is looking for is a library called `libcudart.so`. To obtain a compatible version, you may need to install the CUDA Toolkit version that Pytorch is using and set the `CUDA_HOME` environment variable to it's installation path.

But is it also for non-NVIDIA gpus ? because I've an AMD gpu and it has no CUDA support

**Comment by jllllll** [comment]
> > Keep in mind that what bitsandbytes is looking for is a library called `libcudart.so`. To obtain a compatible version, you may need to install the CUDA Toolkit version that Pytorch is using and set the `CUDA_HOME` environment variable to it's installation path.
> 
> But is it also for non-NVIDIA gpus ? because I've an AMD gpu and it has no CUDA support

No. It doesn't support ROCm to my knowledge. However, you should be able to use it with CPU only, which it will default to without CUDA. Another thing to try is installing the CPU-only/Triton-only build of AutoGPTQ:
```
python -m pip install https://github.com/PanQiWei/AutoGPTQ/releases/download/v0.2.1/auto_gptq-0.2.1-py3-none-any.whl --force-reinstall --no-deps
```

**Comment by grigio** [comment]
I've tried that with `python3 server.py --cpu` but I always get the error `TypeError: 'NoneType' object is not subscriptable`

> ```
> python -m pip install https://github.com/PanQiWei/AutoGPTQ/releases/download/v0.2.1/auto_gptq-0.2.1-py3-none-any.whl --force-reinstall --no-deps
> ```
> 
> If you do want to go the CPU only route, make sure that you run the webui with the `--cpu` flag.

**Comment by juliocesarfs** [comment]
I could only run it using the CPU following these instructions in issue #1396 :

in /modules/training.py I commented out line 14
#from peft import LoraConfig, get_peft_model, set_peft_model_state_dict, prepare_model_for_int8_training

I also needed to comment out line line 4 in /modules/LoRa.py
#from peft import PeftModel

I had the same problem as yours, so it worked to run with the CPU

**Comment by grigio** [comment]
Thanks @juliocesarfs it worked!

**Comment by tekinosman** [comment]
The error seems to be caused by Triton failing to locate the ROCm directory (/opt/rocm) and then trying to access the resulting "null" (NoneType) object in `gfx_arch = _get_amdgcn_bitcode_paths.discovered_gfx_arch_fulldetails[1]`. If you want to use only the CPU a simple fix might be passing `https://download.pytorch.org/whl/cpu` as the `--index-url` argument, like this:
```sh
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
```
instead of:
```sh
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.4.2
```

**Comment by aisk** [comment]
Got the same error, and found that it's caused the rocm sdk is not installed, install it via your distrubution's package  manager will solve it.

**Comment by 748391** [comment]
Hello,
I've been trying to run the textgen-ui on my linux vm with AMD gpus and I still get the ''NoneType' object is not subscriptable' error like @grigio :
`
/anaconda/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/anaconda/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
Traceback (most recent call last):
  File "/home/localadmin/text-generation-webui/server.py", line 28, in <module>
    from modules import (
  File "/home/localadmin/text-generation-webui/modules/chat.py", line 16, in <module>
    from modules.text_generation import (
  File "/home/localadmin/text-generation-webui/modules/text_generation.py", line 22, in <module>
    from modules.models import clear_torch_cache, local_rank
  File "/home/localadmin/text-generation-webui/modules/models.py", line 10, in <module>
    from accelerate import infer_auto_device_map, init_empty_weights
  File "/anaconda/envs/textgen/lib/python3.10/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/anaconda/envs/textgen/lib/python3.10/site-packages/accelerate/accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/anaconda/envs/textgen/lib/python3.10/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/anaconda/envs/textgen/lib/python3.10/site-packages/accelerate/utils/__init__.py", line 131, in <module>
    from .bnb import has_4bit_bnb_layers, load_and_quantize_model
  File "/anaconda/envs/textgen/lib/python3.10/site-packages/accelerate/utils/bnb.py", line 42, in <module>
    import bitsandbytes as bnb
  File "/anaconda/envs/textgen/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 16, in <module>
    from .nn import modules
  File "/anaconda/envs/textgen/lib/python3.10/site-packages/bitsandbytes/nn/__init__.py", line 6, in <module>
    from .triton_based_modules import SwitchBackLinear, SwitchBackLinearGlobal, SwitchBackLinearVectorwise, StandardLinear
  File "/anaconda/envs/textgen/lib/python3.10/site-packages/bitsandbytes/nn/triton_based_modules.py", line 8, in <module>
    from bitsandbytes.triton.dequantize_rowwise import dequantize_rowwise
  File "/anaconda/envs/textgen/lib/python3.10/site-packages/bitsandbytes/triton/dequantize_rowwise.py", line 10, in <module>
    import triton
  File "/anaconda/envs/textgen/lib/python3.10/site-packages/triton/__init__.py", line 20, in <module>
    from .runtime import (
  File "/anaconda/envs/textgen/lib/python3.10/site-packages/triton/runtime/__init__.py", line 1, in <module>
    from .autotuner import Config, Heuristics, autotune, heuristics
  File "/anaconda/envs/textgen/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 7, in <module>
    from ..compiler import OutOfResources
  File "/anaconda/envs/textgen/lib/python3.10/site-packages/triton/compiler.py", line 1888, in <module>
    @static_vars(amdgcn_bitcode_paths = _get_amdgcn_bitcode_paths())
  File "/anaconda/envs/textgen/lib/python3.10/site-packages/triton/compiler.py", line 1867, in _get_amdgcn_bitcode_paths
    gfx_arch = _get_amdgcn_bitcode_paths.discovered_gfx_arch_fulldetails[1]`

The solution @juliocesarfs provided, doesn't work for me.
Doese anyone have an idea how I can fix this?
