### ISSUE TITLE
LLaMA-7B in 8bits  CUDA Setup failed despite GPU being available.

### ISSUE THREAD

**Issue by KamiAso** [oobabooga/text-generation-webui#249]
Anyone can help with this error? I am trying to deploy a leaked LLaMA-7B in 8bits following this guide: https://rentry.org/llama-tard-v2#so-you-got-the-right-weights-now-what

And the below error happened, I have no experience in computer programming but its something to do with the conda not recognizing my cuda location?

I tried to google it a bit and reinstalling the cuda kit with conda command but didnt work. 

Greatly appreciated if someone has the patient to reply to this noob.

```
(textgen) PS D:\miniconda3\text-generation-webui> python server.py --model LLaMA-7B --load-in-8bit --no-stream
Loading LLaMA-7B...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
D:\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('D')}
  warn(msg)
D:\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: D:\miniconda3\envs\textgen did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
D:\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(msg)
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
D:\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
D:\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Loading binary D:\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: Loading binary D:\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Traceback (most recent call last):
  File "D:\miniconda3\text-generation-webui\server.py", line 194, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\miniconda3\text-generation-webui\modules\models.py", line 171, in load_model
    model = eval(command)
  File "<string>", line 1, in <module>
  File "D:\miniconda3\envs\textgen\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "D:\miniconda3\envs\textgen\lib\site-packages\transformers\modeling_utils.py", line 2503, in from_pretrained
    from .utils.bitsandbytes import get_keys_to_not_convert, replace_8bit_linear
  File "D:\miniconda3\envs\textgen\lib\site-packages\transformers\utils\bitsandbytes.py", line 7, in <module>
    import bitsandbytes as bnb
  File "D:\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\__init__.py", line 7, in <module>
    from .autograd._functions import (
  File "D:\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\autograd\__init__.py", line 1, in <module>
    from ._functions import undo_layout, get_inverse_transform_indices
  File "D:\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\autograd\_functions.py", line 9, in <module>
    import bitsandbytes.functional as F
  File "D:\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "D:\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\cextension.py", line 22, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues
```

**Comment by fret-t** [comment]
I am getting a similar error when I try to use 8-bit, though I am not using LLaMA - I'm actually trying to follow what the user did here, running Pygmalion -6b on a 2070 Super #85 

```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('C')}
  warn(msg)
C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: C:\Users\terfy\Desktop\oobabooga\installer_files\env did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(msg)
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Loading binary C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: Loading binary C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Traceback (most recent call last):
  File "C:\Users\terfy\Desktop\oobabooga\text-generation-webui\server.py", line 194, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\terfy\Desktop\oobabooga\text-generation-webui\modules\models.py", line 171, in load_model
    model = eval(command)
  File "<string>", line 1, in <module>
  File "C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2503, in from_pretrained
    from .utils.bitsandbytes import get_keys_to_not_convert, replace_8bit_linear
  File "C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\transformers\utils\bitsandbytes.py", line 7, in <module>
    import bitsandbytes as bnb
  File "C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\__init__.py", line 7, in <module>
    from .autograd._functions import (
  File "C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\autograd\__init__.py", line 1, in <module>
    from ._functions import undo_layout, get_inverse_transform_indices
  File "C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\autograd\_functions.py", line 9, in <module>
    import bitsandbytes.functional as F
  File "C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\cextension.py", line 22, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues
        ```
        
        I have a very vague understanding of what is wrong here but I definitely don't know how to fix it. It seems that the file paths being referenced are for linux rather than windows - is this an issue? Any help would be appreciated.

**Comment by KamiAso** [comment]
> I am getting a similar error when I try to use 8-bit, though I am not using LLaMA - I'm actually trying to follow what the user did here, running Pygmalion -6b on a 2070 Super #85
> 
> I have a very vague understanding of what is wrong here but I definitely don't know how to fix it. It seems that the file paths being referenced are for linux rather than windows - is this an issue? Any help would be appreciated.
> 
> ```
> ===================================BUG REPORT===================================
> Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
> ================================================================================
> C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('C')}
>   warn(msg)
> C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: C:\Users\terfy\Desktop\oobabooga\installer_files\env did not contain libcudart.so as expected! Searching further paths...
>   warn(msg)
> CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
> C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
>   warn(msg)
> CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
> C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
>   warn(msg)
> C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
>   warn(msg)
> CUDA SETUP: Loading binary C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
> argument of type 'WindowsPath' is not iterable
> CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
> CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
> CUDA SETUP: Loading binary C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
> argument of type 'WindowsPath' is not iterable
> CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
> CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
> CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
> CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
> CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
> CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
> Traceback (most recent call last):
>   File "C:\Users\terfy\Desktop\oobabooga\text-generation-webui\server.py", line 194, in <module>
>     shared.model, shared.tokenizer = load_model(shared.model_name)
>   File "C:\Users\terfy\Desktop\oobabooga\text-generation-webui\modules\models.py", line 171, in load_model
>     model = eval(command)
>   File "<string>", line 1, in <module>
>   File "C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
>     return model_class.from_pretrained(
>   File "C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2503, in from_pretrained
>     from .utils.bitsandbytes import get_keys_to_not_convert, replace_8bit_linear
>   File "C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\transformers\utils\bitsandbytes.py", line 7, in <module>
>     import bitsandbytes as bnb
>   File "C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\__init__.py", line 7, in <module>
>     from .autograd._functions import (
>   File "C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\autograd\__init__.py", line 1, in <module>
>     from ._functions import undo_layout, get_inverse_transform_indices
>   File "C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\autograd\_functions.py", line 9, in <module>
>     import bitsandbytes.functional as F
>   File "C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\functional.py", line 17, in <module>
>     from .cextension import COMPILED_WITH_CUDA, lib
>   File "C:\Users\terfy\Desktop\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\cextension.py", line 22, in <module>
>     raise RuntimeError('''
> RuntimeError:
>         CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!
>         If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
>         https://github.com/TimDettmers/bitsandbytes/issues
>         ```
>         
> ```

Yes, the file paths being referenced in the console are all for linux rather than windows. The problem for me currently is even I follow the instructions provided by the error report above, and translate all the path and command from linux specific to windows, it still didnt work.

The webui just cannot recognize the cuda library path for some reason (Or maybe I am just stupid)

I just installed cuda tool kit manually downloaded from nvidia and used the nvcc --version to check, comfirmed that the cuda library path is being set, but still no luck.

**Comment by marianbastiUNRN** [comment]
Bitsadbytes isn't officialy supported on Windows as specified [here](https://github.com/TimDettmers/bitsandbytes#requirements--installation)

**Comment by Ph0rk0z** [comment]
Someone compiled this DLL for windows in the wrong way I think.

**Comment by madmads11** [comment]
I was following the same guide as KamiAso, but I got the same error at the same point on Windows 11. Hopefully a solution to this will come as the one-click installer also had issues and did not work for me.

**Comment by oobabooga** [comment]
See if this helps: https://www.reddit.com/r/LocalLLaMA/comments/11o6o3f/how_to_install_llama_8bit_and_4bit/

**Comment by madmads11** [comment]
> See if this helps: https://www.reddit.com/r/LocalLLaMA/comments/11o6o3f/how_to_install_llama_8bit_and_4bit/

Yes! This works, specifically resuming the tutorial from step 6.

> 6. Download [libbitsandbytes_cuda116.dll](https://github.com/DeXtmL/bitsandbytes-win-prebuilt) and put it in C:\Users\xxx\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\
> 7. In \bitsandbytes\cuda_setup\main.py search for: if not torch.cuda.is_available(): return 'libsbitsandbytes_cpu.so', None, None, None, None and replace with: if torch.cuda.is_available(): return 'libbitsandbytes_cuda116.dll', None, None, None, None
> 8. In \bitsandbytes\cuda_setup\main.py search for this twice: self.lib = ct.cdll.LoadLibrary(binary_path) and replace with: self.lib = ct.cdll.LoadLibrary(str(binary_path))
> 9. Run the following command in your conda environment: python server.py --model llama-13b-hf --load-in-8bit

Thank you for sharing this solution! So if you follow the guide on rentry and receive the error, resume from step 6. and it should work.

**Comment by franzkruhm** [comment]
didn't work here

**Comment by gruevy** [comment]
@oobabooga any chance you could implement this fix into the install script somehow?

**Comment by jiluojiluo** [comment]
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
