### ISSUE TITLE
AttributeError: 'LlamaForCausalLM' object has no attribute 'disable_adapter'

### ISSUE THREAD

**Issue by batuhan3526** [oobabooga/text-generation-webui#2494]
### Describe the bug

I am training a LoRa for my research. Train has finished and ı wanted to try. Then I got the error and cant use my own LoRa.

AttributeError: 'LlamaForCausalLM' object has no attribute 'disable_adapter'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I gathered raw txt file for data. Started LoRa and finished succesfully. Then I wanted to use the LoRa. Thats it.

### Logs

```shell
Traceback (most recent call last):
  File "F:\LLM\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\LLM\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "F:\LLM\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 930, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\LLM\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\LLM\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\LLM\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\LLM\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 491, in async_iteration
    return next(iterator)
  File "F:\LLM\oobabooga_windows\oobabooga_windows\text-generation-webui\server.py", line 80, in load_lora_wrapper
    add_lora_to_model(selected_loras)
  File "F:\LLM\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\LoRA.py", line 30, in add_lora_to_model    shared.model.disable_adapter()
  File "F:\LLM\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LlamaForCausalLM' object has no attribute 'disable_adapter'
```

### System Info

```shell
2x3090
128gb Ram
5950x
```

**Comment by bsord** [comment]
I'm also experiencing this when trying to 'apply' a LORA.
Model used is TheBloke_Wizard-Vicuna-13B-Uncensored-GPTQ, loaded via gptq-for-llama. Had to enable monkey patch in order to get training of the LORA to proceed. Training succeeded, but now getting the AttributeError: 'LlamaForCausalLM' object has no attribute 'disable_adapter' when trying to 'apply' the LORA on the model page.

**Comment by howardslee** [comment]
I am also getting this error when trying to apply any LoRa "AttributeError: 'LlamaForCausalLM' object has no attribute 'disable_adapter'"

**Comment by mihnin** [comment]
i have the same error/. i have RTX4090 + 64GB RAM + CPU AMD7900.

Traceback (most recent call last):
  File "/home/mih50/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/mih50/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/mih50/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/mih50/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "/home/mih50/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/mih50/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/mih50/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/mih50/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/mih50/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "/home/mih50/text-generation-webui/server.py", line 79, in load_lora_wrapper
    add_lora_to_model(selected_loras)
  File "/home/mih50/text-generation-webui/modules/LoRA.py", line 67, in add_lora_to_model
    shared.model.disable_adapter()
  File "/home/mih50/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LlamaForCausalLM' object has no attribute 'disable_adapter'

**Comment by hadnet** [comment]
Hey Guys, did you resolve that issue?

**Comment by GilgameshofUT** [comment]
Having same issue. On a Runpod with TheBloke_Wizard-Vicuna-13B-Uncensored. Loaded in 8 bit with transformers. first time training a Lora and thought I might be doing something wrong. Fails with this error on runpod and my home system.

**Comment by GilgameshofUT** [comment]
Well. Good news these loras do work correctly on Kobold ccp. I did need to first run the convery to GGML python script that comes with kobold, but then they loaded without error and had the appropriate effect. To be clear I trained them with load-in-8bit and using transformers. I could not get them to load either in the rodpod that created them (which seems the most odd) or on Ooba on my local system running the GGML version of the same model. However I was able to load them fine into Kobold ccp. So maybe it is a version of llama.ccp? But that doesn't explain why I couldn't run them on the version that created them. I should note that Kobold insisted I run only on CPU to load the lora. Tried adjusting that on Ooba but no change.

**Comment by fanconic** [comment]
I might be late to the party, but this error in a similar setting was solved for me, when removing the `model_init` argument from the HF `trainer`, and passing the `model` directly. I would have to further investigate what exactly is the cause.
