### ISSUE TITLE
Training LoRA gives Failed to read file... JSON parse error

### ISSUE THREAD

**Issue by rafa-9** [oobabooga/text-generation-webui#2500]
### Describe the bug

I tried running the default dataset(https://github.com/gururise/AlpacaDataCleaned/blob/main/alpaca_data_cleaned.json) and my own small 200 line dataset but it gave me error that it failed to read file. It is the default file so it doesn't make sense that it should have wrong format.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Download TheBloke/WizardLM-30B-Uncensored-GPTQ model from huggingface on runpod

2. Download the dataset:
wget https://github.com/gururise/AlpacaDataCleaned/blob/main/alpaca_data_cleaned.json

3. Set params: 
// set gpu-memory in MiB for device : 5500
//cpu-memory in MiB: 8000
//load-in-4bit checked
//wbits: 4
//model_type: llama

4. cd into text-generation-webui and run the monkey-patch
python server.py --listen --listen-host 0.0.0.0 --listen-port 7861 --model TheBloke_WizardLM-30B-Uncensored-GPTQ --chat --wbits 4 --auto-devices --pre_layer 40 --cache-capacity 2GiB --quant_attn --warmup_autotune --fused_mlp --model_type llama --monkey-patch

5. Go to train tab in webui and use start training on the downloaded dataset

### Logs

```shell
Generating train split: 0 examples [00:00, ? examples/s]ERROR:Failed to read file '/root/text-generation-webui/training/datasets/train.json' with error <class 'pyarrow.lib.ArrowInvalid'>: JSON parse error: Invalid value. in row 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/datasets/packaged_modules/json/json.py", line 152, in _generate_tables
    dataset = json.load(f)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/datasets/builder.py", line 1860, in _prepare_split_single
    for _, table in generator:
  File "/usr/local/lib/python3.10/dist-packages/datasets/packaged_modules/json/json.py", line 155, in _generate_tables
    raise e
  File "/usr/local/lib/python3.10/dist-packages/datasets/packaged_modules/json/json.py", line 131, in _generate_tables
    pa_table = paj.read_json(
  File "pyarrow/_json.pyx", line 258, in pyarrow._json.read_json
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: JSON parse error: Invalid value. in row 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 339, in async_iteration
    return await iterator.__anext__()
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 332, in __anext__
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 315, in run_sync_iterator_async
    return next(iterator)
  File "/root/text-generation-webui/modules/training.py", line 348, in do_train
    data = load_dataset("json", data_files=clean_path('training/datasets', f'{dataset}.json'))
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1782, in load_dataset
    builder_instance.download_and_prepare(
  File "/usr/local/lib/python3.10/dist-packages/datasets/builder.py", line 872, in download_and_prepare
    self._download_and_prepare(
  File "/usr/local/lib/python3.10/dist-packages/datasets/builder.py", line 967, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/datasets/builder.py", line 1749, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "/usr/local/lib/python3.10/dist-packages/datasets/builder.py", line 1892, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.builder.DatasetGenerationError: An error occurred while generating the dataset
```
```


### System Info

```shell
Using runpod RTX 4090 16vCPU 83 GB RAM
```

**Comment by Ph0rk0z** [comment]
This repo's monkeypatch doesn't support quant_attn or fused_mlp, nor does it support offloading through pipelining so no pre-layer.

But more importantly, something is wrong with your dataset, open it up and makes sure there is nothing weird at the begining and that the formatting is right.. it keeps mentioning `Invalid value. in row 0`

**Comment by rafa-9** [comment]
> This repo's monkeypatch doesn't support quant_attn or fused_mlp, nor does it support offloading through pipelining so no pre-layer.
> 
> But more importantly, something is wrong with your dataset, open it up and makes sure there is nothing weird at the begining and that the formatting is right.. it keeps mentioning `Invalid value. in row 0`

@Ph0rk0z I'm using the default dataset to try this out that is mentioned here: https://github.com/gururise/AlpacaDataCleaned/blob/main/alpaca_data_cleaned.json

Do you have a bit of time to come on discord and help debug? I can pay for your time

**Comment by Ph0rk0z** [comment]
I can't use discord. It requires a phone #. Open the dataset up, it says the first line has something wrong with it.
`
Expecting value: line 1 column 1 (char 0)`

Are you sure you selected the right format? https://github.com/oobabooga/text-generation-webui/blob/main/training/formats/alpaca-format.json

And of course --load-in-4bit also doesn't work with monkeypatch, you need to pick one or the other.

**Comment by rafa-9** [comment]
@Ph0rk0z Ok I disabled --load-in-4bit, removed quant_attn or fused_mlp and pre layer. Still getting the same error.

Any other tool you prefer to chat about this? zoom, slack?

**Comment by Ph0rk0z** [comment]
Github I think will help others. Literally it says invalid value in row 0. So the first character of your dataset has something invalid. Either missing [ or you have to delete the [ and the corresponding ] on the bottom.

**Comment by rafa-9** [comment]
@Ph0rk0z I just wget https://raw.githubusercontent.com/gururise/AlpacaDataCleaned/main/alpaca_data_cleaned.json and tried to run the LoRA with the all default settings in webui.

here is the link to my pod: https://9cbbdbe5ab9c05c1fc.gradio.live/

**Comment by Ph0rk0z** [comment]
says: No interface is running right now

**Comment by rafa-9** [comment]
My bad. It is working now. After retrying with your settings it works. Thanks for your help!

**Comment by Ph0rk0z** [comment]
Yup.. no problem. I had to do this with a fresh dataset and write the "format" part for it too so it happened to me a lot.

**Comment by JomSpoons** [comment]
How exactly was this resolved? Having the same issue.
