### ISSUE TITLE
OSError: exception: access violation writing 0x0000000001400000

### ISSUE THREAD

**Issue by kelheor** [oobabooga/text-generation-webui#2501]
### Describe the bug

I followed this guide:
https://github.com/oobabooga/text-generation-webui/blob/main/docs/llama.cpp-models.md

No errors and when I run textgen, I can see in logs:

```
llama_model_load_internal: [cublas] offloading 40 layers to GPU
llama_model_load_internal: [cublas] total VRAM used: 9076 MB
...................................................................................................
llama_init_from_file: kv self size  = 1600.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
```

However, when I try to write anything to chatbot, I'm getting this error:

```
Traceback (most recent call last):
  File "C:\text-generation-webui\text-generation-webui\modules\callbacks.py", line 73, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "C:\text-generation-webui\text-generation-webui\modules\llamacpp_model.py", line 77, in generate
    for completion_chunk in completion_chunks:
  File "C:\Users\kelhe\anaconda3\envs\textgen\lib\site-packages\llama_cpp\llama.py", line 756, in _create_completion
    for token in self.generate(
  File "C:\Users\kelhe\anaconda3\envs\textgen\lib\site-packages\llama_cpp\llama.py", line 591, in generate
    self.eval(tokens)
  File "C:\Users\kelhe\anaconda3\envs\textgen\lib\site-packages\llama_cpp\llama.py", line 320, in eval
    return_code = llama_cpp.llama_eval(
  File "C:\Users\kelhe\anaconda3\envs\textgen\lib\site-packages\llama_cpp\llama_cpp.py", line 439, in llama_eval
    return _lib.llama_eval(ctx, tokens, n_tokens, n_past, n_threads)
OSError: exception: access violation writing 0x0000000001400000
```
I'm not getting such error with pre-compiled llama-cpp-python from requirements.txt (https://github.com/abetlen/llama-cpp-python/releases/download/v0.1.56/llama_cpp_python-0.1.56-cp310-cp310-win_amd64.whl), but it doesn't have BLAS = 1

I got this error on two different PC (notebook with 3080 and PC with 4090, both have AMD CPU).

Any ideas on how to fix such error?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Follow this guide:
https://github.com/oobabooga/text-generation-webui/blob/main/docs/llama.cpp-models.md
Start textgen and try to write something to textbot.

### Logs

```shell
Traceback (most recent call last):
  File "C:\text-generation-webui\text-generation-webui\modules\callbacks.py", line 73, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "C:\text-generation-webui\text-generation-webui\modules\llamacpp_model.py", line 77, in generate
    for completion_chunk in completion_chunks:
  File "C:\Users\kelhe\anaconda3\envs\textgen\lib\site-packages\llama_cpp\llama.py", line 756, in _create_completion
    for token in self.generate(
  File "C:\Users\kelhe\anaconda3\envs\textgen\lib\site-packages\llama_cpp\llama.py", line 591, in generate
    self.eval(tokens)
  File "C:\Users\kelhe\anaconda3\envs\textgen\lib\site-packages\llama_cpp\llama.py", line 320, in eval
    return_code = llama_cpp.llama_eval(
  File "C:\Users\kelhe\anaconda3\envs\textgen\lib\site-packages\llama_cpp\llama_cpp.py", line 439, in llama_eval
    return _lib.llama_eval(ctx, tokens, n_tokens, n_past, n_threads)
OSError: exception: access violation writing 0x0000000001400000
```

### System Info

```shell
4090, Windows 11
```

**Comment by IkariDevGIT** [comment]
hey, i have the same problem, did you get it fixed?

**Comment by quarkpapel** [comment]
same problem
