### ISSUE TITLE
Wrong concept: loading model during webUI startup

### ISSUE THREAD

**Issue by cibernicola** [oobabooga/text-generation-webui#2502]
### Describe the bug

It is a mistake to force the loading of the model, especially considering that it is more than possible that it has specific configurations and that, in addition, it is required to open the webUI to, for example, just download some model or test something else.
In addition, if the model you are trying to load does not have the settings saved, the error is not handled and the webUI loading is broken.

I think it is much more logical to allow the model to load once the webUI has already loaded, if it is required to load the model during the webUI load, do it by parameters.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load a model that does not have the configuration, force model loading during webUI loading

### Screenshot

N/A

### Logs

```shell
INFO:Loading tiiuae_falcon-7b...
Traceback (most recent call last):
  File "J:\gpt\oobabooga_windows\text-generation-webui\server.py", line 1102, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "J:\gpt\oobabooga_windows\text-generation-webui\modules\models.py", line 79, in load_model
    shared.model_type = find_model_type(model_name)
  File "J:\gpt\oobabooga_windows\text-generation-webui\modules\models.py", line 67, in find_model_type
    config = AutoConfig.from_pretrained(path_to_model, trust_remote_code=shared.args.trust_remote_code)
  File "J:\gpt\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\configuration_auto.py", line 934, in from_pretrained
    raise ValueError(
ValueError: Loading models\tiiuae_falcon-7b requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.
```

### System Info

```shell
N/A
```

**Comment by jllllll** [comment]
When launching the webui, I have to go to the model tab and select one. Models aren't being forced to load for me.
What launch args are you using?

**Comment by Ph0rk0z** [comment]
Turn off auto load in the user config.

**Comment by cibernicola** [comment]
Both answers may be correct, but they are not: with Windows installer, first launch, its on, and the problem begins. So, it should be off by default, then each user can decide.

**Comment by Ph0rk0z** [comment]
For my own version it is off by default.

**Comment by cibernicola** [comment]
oobabooga-windows.zip:

webui.py

line 13:  

`CMD_FLAGS = '--chat --model-menu'`
![image](https://github.com/oobabooga/text-generation-webui/assets/4579387/e4551a53-92bd-4167-a561-9008a18258b0)

**Comment by jllllll** [comment]
> oobabooga-windows.zip:
> 
> webui.py
> 
> line 13:
> 
> `CMD_FLAGS = '--chat --model-menu'` ![image](https://user-images.githubusercontent.com/4579387/244029862-e4551a53-92bd-4167-a561-9008a18258b0.png)

I just downloaded the Windows zip file linked in the README.md and it does not show that. Only flag included is `--chat`.
`--model-menu` was already removed in response to your previous issue on the matter: https://github.com/oobabooga/one-click-installers/commit/290a3374e491e6a5609ecc4ed115d5ef8caa1d12

https://github.com/oobabooga/text-generation-webui/releases/download/installers/oobabooga_windows.zip
