### ISSUE TITLE
Program crashes due to not enough VRAM when loading.

### ISSUE THREAD

**Issue by Deejay85** [oobabooga/text-generation-webui#2510]
### Describe the bug

Whenever I try to run this program, it attempts to load a model at start up, and then immediately crashes with the following message:

```
bin S:\Oobabooga\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
INFO:Loading ehartford_WizardLM-13B-Uncensored...
Traceback (most recent call last):
  File "S:\Oobabooga\text-generation-webui\server.py", line 1102, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "S:\Oobabooga\text-generation-webui\modules\models.py", line 97, in load_model
    output = load_func(model_name)
  File "S:\Oobabooga\text-generation-webui\modules\models.py", line 160, in huggingface_loader
    model = model.cuda()
  File "S:\Oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "S:\Oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "S:\Oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "S:\Oobabooga\installer_files\env\lib\site-packa your ges\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "S:\Oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "S:\Oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 11.99 GiB total capacity; 11.17 GiB already allocated; 0 bytes free; 11.18 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

I tried to fix the problem by removing the model, running the program, and then going to models to make some changes, but since the model isn't loaded due to being moved, I can't say any of the changes that I made to it ended up fixing the problem. That said, since I have to have the model in the directory to make changes to it, and the program crashes whenever I try to run the program if the model is present, I am kind of at a loss as to what I can do here.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Run the program
2. There is no step 2.

### Logs

```shell
bin S:\Oobabooga\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
INFO:Loading ehartford_WizardLM-13B-Uncensored...
Traceback (most recent call last):
  File "S:\Oobabooga\text-generation-webui\server.py", line 1102, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "S:\Oobabooga\text-generation-webui\modules\models.py", line 97, in load_model
    output = load_func(model_name)
  File "S:\Oobabooga\text-generation-webui\modules\models.py", line 160, in huggingface_loader
    model = model.cuda()
  File "S:\Oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "S:\Oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "S:\Oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "S:\Oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "S:\Oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "S:\Oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 11.99 GiB total capacity; 11.17 GiB already allocated; 0 bytes free; 11.18 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### System Info

```shell
Windows 10

Nvidia RTX 4080
```

**Comment by NEFlame** [comment]
There is no bug. You're trying to run an [8-bit 13B model which requires 16.3GB VRAM](https://www.reddit.com/r/LocalLLaMA/wiki/models) despite only having 12GB VRAM. Switch to a 4-bit 13B model like [this](https://huggingface.co/TheBloke/Wizard-Vicuna-13B-Uncensored-GPTQ) or an 8-bit 7B model, since that's the most your GPU can handle.

**Comment by Deejay85** [comment]
In other words there is no way to offload the remaining onto RAM?

**Comment by minipasila** [comment]
> In other words there is no way to offload the remaining onto RAM?

you can add "--gpu-memory" with the amount of VRAM you want to allocate to your GPU but it's probably better to just use a 4 bit version of the model. You could also just load it in 4-bit using bitsandbytes by adding --load-in-4bit. Though I personally prefer using pre-quantized models like GGML or GPTQ. (you can run GPTQ models using --autogptq and with GGML you don't need to add anything extra unless you need to offload the model to your gpu which actually requires an additional step explained [here](https://github.com/oobabooga/text-generation-webui/blob/main/docs/llama.cpp-models.md#gpu-acceleration))

**Comment by Deejay85** [comment]
Thanks. Silly as it sounds what do I add these arguments to? The .bat file, or somewhere else?
