### ISSUE TITLE
ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by St33lMouse** [oobabooga/text-generation-webui#2513]
### Describe the bug

Trying a clean install of Ooba.  Can't seem to get past this error on load:

(textgen) mouse@mousehole:~/text-generation-webui$ python server.py
Traceback (most recent call last):
  File "/home/mouse/text-generation-webui/server.py", line 44, in <module>
    import torch
  File "/home/mouse/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Did a git pull and install requirements -r requirements.txt --upgrade and started getting this error on load. Did a clean reinstall, but that didn't fix the problem.

### Logs

```shell
(textgen) mouse@mousehole:~/text-generation-webui$ python server.py
Traceback (most recent call last):
  File "/home/mouse/text-generation-webui/server.py", line 44, in <module>
    import torch
  File "/home/mouse/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory
```

### System Info

```shell
Ubuntu KDE
```

**Comment by St33lMouse** [comment]
Found the solution:  downgraded to Pytorch 2.0. I have no idea why this affected me but nobody else. It's also quite possible that I could now upgrade to pytorch 2.01, but I am too tired to try. Round and round trying to fix this for 2 hours. Sigh.
