### ISSUE TITLE
Consistent "RuntimeError: probability tensor contains either `inf`, `nan` or element < 0" during text generation

### ISSUE THREAD

**Issue by novellus** [oobabooga/text-generation-webui#2540]
# Problem Description
I am consistently getting the same error when attempting to generate text: ```RuntimeError: probability tensor contains either `inf`, `nan` or element < 0```. This occurs when using any model (tested ```timdettmers/guanaco-33b-merged```, ```timdettmers/guanaco-65b-merged```, and ```eachadea/vicuna-7b-1.1```). Tested this with a clean install, all default settings, and full reproduction steps below. After removing my environment, and reproducing from scratch a couple times, occasionally one of the models will work and then later fail with the same error, so there may be some stochastic weirdness. 

# Troubleshooting Steps which I have taken
* ```python download-model.py timdettmers/guanaco-33b-merged --check``` - This returns inconsistent checksums from run to run
* Wrote this small script to check checksum stability

```
for n in $(seq 1 10)
do
    echo "sha256sum" >> tmp.txt
    sha256sum models/timdettmers_guanaco-33b-merged/pytorch_model-00001-of-00007.bin >> tmp.txt
    sha256sum models/timdettmers_guanaco-33b-merged/pytorch_model-00002-of-00007.bin >> tmp.txt
    sha256sum models/timdettmers_guanaco-33b-merged/pytorch_model-00003-of-00007.bin >> tmp.txt
    sha256sum models/timdettmers_guanaco-33b-merged/pytorch_model-00004-of-00007.bin >> tmp.txt
    sha256sum models/timdettmers_guanaco-33b-merged/pytorch_model-00005-of-00007.bin >> tmp.txt
    sha256sum models/timdettmers_guanaco-33b-merged/pytorch_model-00006-of-00007.bin >> tmp.txt
    sha256sum models/timdettmers_guanaco-33b-merged/pytorch_model-00007-of-00007.bin >> tmp.txt
    echo "download-model.py" >> tmp.txt
    conda run -n textgen python download-model.py timdettmers/guanaco-33b-merged --check >> tmp.txt
done
```

* with a minor change to ```download-model.py``` to print the file hash on failure:

```
- print(f'Checksum failed: {sha256[i][0]}  {sha256[i][1]}')
+ print(f'Checksum failed: {sha256[i][0]}  {file_hash} vs {sha256[i][1]}')
```

* each of the ```sha256sum``` executions returned consistent results, and match the checksums posted on huggingface.
* each of the ```download-model.py``` checks returned unique checksums
* full results from the script are attached as [tmp.txt](https://github.com/oobabooga/text-generation-webui/files/11658731/tmp.txt)
* Tried the troubleshooting steps from a similar issue [issue-199](https://github.com/oobabooga/text-generation-webui/issues/199), but none of these helped
    * The mentioned code refactor is a month old, so does not seem relevant
    * ```top_p``` is set to default value (0.1)
    * have not tried disabling ```do_sample```, but that shouldn't stop the invalid distribution values from existing anyway
    * not sure what is meant by ```turn off the low_resource: in eval_configs/minigpt4_eval.yaml, line 8. low_resource: False```, since ```low_resource``` does not show up in any recursive content search of the ```text-generation-webui``` folder. It might be model specific.
* I removed and redownloaded the models. I also tried manually downloading the files which failed the ```download-model.py``` checksum verification, but since the failed files changed which each execution, this wasn't very helpful.
* I removed my environment and clone folder recursively, and followed from scratch the reproduction steps above. This did not help, so the problem is consistent.

# My thoughts
* Possibly there is a bug in model loading that sometimes corrupts a file?
* Possibly I have a broken environment setup, but I am not sure how to troubleshoot any further. Advice would be welcomed, and I will try to provide prompt responses for additional information.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

* ```git clone https://github.com/oobabooga/text-generation-webui``` (I retrieved at commit ```60bfd0b7223ea5c150fec075464e2a689d6b29c6```, Jun 5 2023)
* ```cd text-generation-webui```
* ```conda create -n textgen python=3.10.9```
* ```conda activate textgen```
* ```pip install torch torchvision torchaudio```
* ```pip install -r requirements.txt```
* ```conda install -c conda-forge mpi4py mpich```
* ```pip install -U deepspeed```
* ```python download-model.py timdettmers/guanaco-33b-merged```
* ```python server.py --model timdettmers_guanaco-33b-merged --auto-devices --gpu-memory 23 --cpu-memory 250```
* open webui
    * type in any prompt (eg ```banana```)
    * error shows on console ```RuntimeError: probability tensor contains either `inf`, `nan` or element < 0```
    * no generated characters are printed to the output box, after the prompt

### Logs

```shell
(textgen) user@system:~/text-generation-webui$ python server.py --model timdettmers_guanaco-33b-merged --auto-devices --gpu-memory 23 --cpu-memory 250
Setting ds_accelerator to cuda (auto detect)
bin /home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
INFO:Loading timdettmers_guanaco-33b-merged...
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:40<00:00,  5.75s/it]
INFO:Loaded the model in 41.17 seconds.

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/home/user/text-generation-webui/modules/callbacks.py", line 73, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/home/user/text-generation-webui/modules/text_generation.py", line 286, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1568, in generate
    return self.sample(
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2651, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
Output generated in 4.80 seconds (0.00 tokens/s, 0 tokens, context 3, seed 765114828)
```

### System Info

```shell
OS: Linux Mint 21.1 (Ubuntu 22.04)
CPU: AMD Ryzen Threadripper 3970X
GPU 1: NVIDIA GeForce RTX 2080 SUPER (exclusively used for video output)
GPU 2: NVIDIA GeForce RTX 4090 (exclusively allocated to this program)
GPU Driver: 520.61.05
CUDA: 11.8
RAM: 256 GB
```
See attached [pip_list.txt](https://github.com/oobabooga/text-generation-webui/files/11658733/pip_list.txt) and [conda_list.txt](https://github.com/oobabooga/text-generation-webui/files/11658735/conda_list.txt) for retrieved package versions.

**Comment by pandego** [comment]
Same here, and my system is very similar to yours (2x Nvidia GPUs, CUDA 11.8, and AMD Ryzen), except I'm running Windows 11 instead of Linux.

**Comment by M4TH1EU** [comment]
Same problems here with a RX 6800XT (Linux/Fedora 38 ROCM 5.4.2) tried multiples models (currently using TheBloke_Wizard-Vicuna-13B-Uncensored-GPTQ (4bit)).

**Comment by novellus** [comment]
This issue is still occurring, for around 50-80% of server starts.

**Comment by ReasonDuan** [comment]
I have encountered the same issue.
`Traceback (most recent call last):
  File "/data/home/buyabs.corp/reason/workspace/text-webui/text-generation-webui/modules/callbacks.py", line 57, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "/data/home/buyabs.corp/reason/workspace/text-webui/text-generation-webui/modules/text_generation.py", line 352, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/data/home/buyabs.corp/reason/workspace/text-webui/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/home/buyabs.corp/reason/workspace/text-webui/venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 1652, in generate
    return self.sample(
  File "/data/home/buyabs.corp/reason/workspace/text-webui/venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 2770, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
Output generated in 1.54 seconds (0.00 tokens/s, 0 tokens, context 68, seed 1915926732)
`
