### ISSUE TITLE
integer divide by zero

### ISSUE THREAD

**Issue by Priestru** [oobabooga/text-generation-webui#2576]
### Describe the bug

When using SillyTavern if you stop generation and then swipe too soon webui crashes with error

It's easy to avoid crash, you just have to wait few seconds before sending another prompt. But i somehow incapable of waiting for the right amont of time. Is there any possibility this could be handled anyhow else to at least reject to generate instead of crashing or smth.

 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Cancel generation in Sillytavern, swipe using Sillytavern without waiting for llama.cpp to report statistics about previous generation. Receive a crash.

### Logs

```shell
INFO:Loading Wizard-Vicuna-30B-Uncensored.ggmlv3.q5_1.bin...
INFO:llama.cpp weights detected: D:\Models\Wizard-Vicuna-30B-Uncensored.ggmlv3.q5_1.bin

INFO:Cache capacity is 0 bytes
llama.cpp: loading model from D:\Models\Wizard-Vicuna-30B-Uncensored.ggmlv3.q5_1.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2400
llama_model_load_internal: n_embd     = 6656
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 52
llama_model_load_internal: n_layer    = 60
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 9 (mostly Q5_1)
llama_model_load_internal: n_ff       = 17920
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 30B
llama_model_load_internal: ggml ctx size =    0.13 MB
llama_model_load_internal: mem required  = 25573.14 MB (+ 3124.00 MB per state)
llama_model_load_internal: [cublas] offloading 0 layers to GPU
llama_model_load_internal: [cublas] total VRAM used: 0 MB
.
llama_init_from_file: kv self size  = 3656.25 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
INFO:Loaded the model in 3.16 seconds.

Starting streaming server at ws://0.0.0.0:5005/api/v1/stream
INFO:Loading the extension "gallery"...
Starting API at http://0.0.0.0:5000/api
127.0.0.1 - - [08/Jun/2023 08:41:52] "GET /api/v1/model HTTP/1.1" 200 -
Running on local URL:  http://0.0.0.0:7860

Traceback (most recent call last):
  File "D:\LLM\oobabooga_windows\text-generation-webui\modules\callbacks.py", line 73, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "D:\LLM\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 78, in generate
    for completion_chunk in completion_chunks:
  File "D:\LLM\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 756, in _create_completion
    for token in self.generate(
  File "D:\LLM\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 591, in generate
    self.eval(tokens)
  File "D:\LLM\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 320, in eval
    return_code = llama_cpp.llama_eval(
  File "D:\LLM\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp\llama_cpp.py", line 439, in llama_eval
    return _lib.llama_eval(ctx, tokens, n_tokens, n_past, n_threads)
OSError: exception: integer divide by zero
```
```


### System Info

```shell
Up to date webui.
SillyTavern 1.6.6
```

**Comment by Ph0rk0z** [comment]
This looks like an error in the llama cpp python bindings.
