### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'pad_token_id'

### ISSUE THREAD

**Issue by wd5dw** [oobabooga/text-generation-webui#2579]
### Describe the bug

When I try to train on cpu, I get the following error.

llama.cpp: loading model from models\keldenl_Dante_1.3B3-GGML\ggml-model-q5_1.bin
error loading model: missing tok_embeddings.weight
llama_init_from_file: failed to load model
Exception ignored in: <function LlamaCppModel.__del__ at 0x000002414B1B5120>
Traceback (most recent call last):
  File "C:\Users\User\Downloads\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 23, in __del__
    self.model.__del__()
AttributeError: 'LlamaCppModel' object has no attribute 'model'
WARNING:LoRA training has only currently been validated for LLaMA, OPT, GPT-J, and GPT-NeoX models. (Found model type: NoneType)
WARNING:It is highly recommended you use `--load-in-8bit` for LoRA training.
Traceback (most recent call last):
  File "C:\Users\User\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\User\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\User\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\User\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\User\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\User\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\User\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\User\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\User\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\User\Downloads\oobabooga_windows\text-generation-webui\modules\training.py", line 250, in do_train
    shared.tokenizer.pad_token_id = 0
AttributeError: 'NoneType' object has no attribute 'pad_token_id'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

see description above

### Logs

```shell
see description above
```

### System Info

```shell
cpu(intel core i7)
```

**Comment by ChrisCates** [comment]
Same issue... Except my stack trace is way harder to debug...

```console
Traceback (most recent call last):
  File "/home/fortytwo/miniconda3/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/fortytwo/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/fortytwo/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/fortytwo/miniconda3/lib/python3.10/site-packages/gradio/utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "/home/fortytwo/miniconda3/lib/python3.10/site-packages/gradio/utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/fortytwo/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/fortytwo/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/fortytwo/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/fortytwo/miniconda3/lib/python3.10/site-packages/gradio/utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "/home/fortytwo/Projects/other/ChatBotApp/trainer/modules/training.py", line 312, in do_train
    shared.tokenizer.pad_token_id = 0
AttributeError: 'NoneType' object has no attribute 'pad_token_id'
```

**Comment by syaoran68** [comment]
Yes. I am also getting this issue but with wizardLM-7B-GGML version. I have done a git fetch and pull so i believe i'm on the latest. this happens if i used the JSON formatted or the raw formatted training.

**Comment by Benstime** [comment]
**loading model meta-llama/Llama-2-13b-chat-hf raise KeyError: 'pad_token_id'**

```
2023-08-07 16:29:05 INFO:Loading Llama-2-13b-chat-hf...
Traceback (most recent call last):
  File "/data2/u2/nas/code/aigc/LLaMA-Efficient-Tuning/lib/text-generation-webui/server.py", line 230, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/data2/u2/nas/code/aigc/LLaMA-Efficient-Tuning/lib/text-generation-webui/modules/models.py", line 78, in load_model
    output = load_func_map[loader](model_name)
  File "/data2/u2/nas/code/aigc/LLaMA-Efficient-Tuning/lib/text-generation-webui/modules/models.py", line 300, in ExLlama_HF_loader
    return ExllamaHF.from_pretrained(model_name)
  File "/data2/u2/nas/code/aigc/LLaMA-Efficient-Tuning/lib/text-generation-webui/modules/exllama_hf.py", line 92, in from_pretrained
    config = ExLlamaConfig(pretrained_model_name_or_path / 'config.json')
  File "/data2/u2/anaconda3/envs/textgen/lib/python3.10/site-packages/exllama/model.py", line 52, in __init__
    self.pad_token_id = read_config["pad_token_id"]
KeyError: 'pad_token_id'
```

**Comment by zyugyzarc** [comment]
Seems to also make the same error in the raw text format.

```
2023-08-15 11:59:30 WARNING:LoRA training has only currently been validated for LLaMA, OPT, GPT-J, and GPT-NeoX models. (Found model type: NoneType)
Traceback (most recent call last):
  File "/home/zyugyzarc/programs/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/zyugyzarc/programs/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/zyugyzarc/programs/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/zyugyzarc/programs/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "/home/zyugyzarc/programs/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/zyugyzarc/programs/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/zyugyzarc/programs/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/zyugyzarc/programs/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/zyugyzarc/programs/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "/home/zyugyzarc/programs/oobabooga_linux/text-generation-webui/modules/training.py", line 325, in do_train
    shared.tokenizer.pad_token_id = 0
AttributeError: 'NoneType' object has no attribute 'pad_token_id'
```

**Comment by Sigura** [comment]
Few minutes in code... And it works for me.

Follow:
1. Navigate to the [Model] tab
2. Click on the [reload] button to reload the model
3. Return to the [Training] tab
4. Click on the [Start LoRA Training] and to going!
