### ISSUE TITLE
rwkv stop words, token_stop not implemented

### ISSUE THREAD

**Issue by determo13** [oobabooga/text-generation-webui#2598]
### Describe the bug

my RWKV model never stopped and continue generating until token will run out regardless of specified stop words or now.  
I looked into text_generation.py and it lead me to RWKV.py.  token_stop variable not passed at all so I altered code a bit in case anyone needs it.

RWKV.py alteration

    def generate(

        tokenizer_path = Path(f"./models/20B_tokenizer.json")
        tokenizer = Tokenizer.from_file(str(tokenizer_path))
        additional_stop_words = token_stop
        st = tokenizer.encode(additional_stop_words).ids

        args = PIPELINE_ARGS(
            temperature=temperature,
            top_p=top_p,
            top_k=top_k,
            alpha_frequency=alpha_frequency,  # Frequency Penalty (as in GPT-3)
            alpha_presence=alpha_presence,  # Presence Penalty (as in GPT-3)
            token_ban=token_ban or [0],  # ban the generation of some tokens
            token_stop=st or []
        )
        
        
       
To pass custom words needs to alter text_generation.py

 text_generation.py alteration

def generate_reply_custom(question, original_question, seed, state, eos_token=None, stopping_strings=None, is_chat=False):
    seed = set_manual_seed(state['seed'])
    generate_params = {'token_count': state['max_new_tokens'],'token_stop': stopping_strings}

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

-

### Logs

```shell
-
```

### System Info

```shell
-
```

**Comment by luthis1124** [comment]
Which RWKV model are you using? I just downloaded Raven 14B and can't get it to work:
```

Traceback (most recent call last):
  File "/home/st/GIT/oobabooga_linux_2/text-generation-webui/modules/text_generation.py", line 249, in generate_reply_HF
    output = shared.model.generate(**generate_params)[0]
  File "/home/st/GIT/oobabooga_linux_2/installer_files/env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/st/GIT/oobabooga_linux_2/installer_files/env/lib/python3.10/site-packages/transformers/generation/utils.py", line 1568, in generate
    return self.sample(
  File "/home/st/GIT/oobabooga_linux_2/installer_files/env/lib/python3.10/site-packages/transformers/generation/utils.py", line 2615, in sample
    outputs = self(
  File "/home/st/GIT/oobabooga_linux_2/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/st/GIT/oobabooga_linux_2/installer_files/env/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/st/GIT/oobabooga_linux_2/installer_files/env/lib/python3.10/site-packages/transformers/models/rwkv/modeling_rwkv.py", line 785, in forward
    rwkv_outputs = self.rwkv(
  File "/home/st/GIT/oobabooga_linux_2/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/st/GIT/oobabooga_linux_2/installer_files/env/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/st/GIT/oobabooga_linux_2/installer_files/env/lib/python3.10/site-packages/transformers/models/rwkv/modeling_rwkv.py", line 645, in forward
    self._rescale_layers()
  File "/home/st/GIT/oobabooga_linux_2/installer_files/env/lib/python3.10/site-packages/transformers/models/rwkv/modeling_rwkv.py", line 717, in _rescale_layers
    block.attention.output.weight.div_(2 ** int(block_id // self.config.rescale_every))
RuntimeError: result type Float can't be cast to the desired output type Byte
Output generated in 0.01 seconds (0.00 tokens/s, 0 tokens, context 8, seed 1160682024)
```

**Comment by DifferentialityDevelopment** [comment]
I wonder if this is related to what I just fixed in exlama.py
Basically stopping_strings never gets passed through and it never checks that the decoded output ends with something in the stopping_strings array, I just passed it to the state dict so that it can be picked up and made it check after each iteration.
Anyways I just wanted to get the API up and running my side correctly so I can actually work on my project I'm building.
Not gonna bother with a pull request but here is the changes I made.

![exllama_py](https://github.com/oobabooga/text-generation-webui/assets/9594229/2c60569f-55bc-4c4e-9e69-dc108955bae4)
![text_generation_py](https://github.com/oobabooga/text-generation-webui/assets/9594229/c0438cad-6a4e-44d9-a800-bf1d2ebef7f0)

**Comment by chaddwick25** [comment]
> I used RWKV-4-Raven-7B-v12-Eng98%-Other2%-20230521-ctx8192.pth with cuda fp16i8 -> cuda fp16 and tested
> 
> RWKV-4-Raven-3B-v12-Eng98%-Other2%-20230520-ctx4096.pth with cuda fp16 all seemed to work fine with Tesla K80

Hello,

I have also  K80 but I am struggling to get it to work. Would you mind sharing any insights on your setup, specifically what version of cuda that your running ?

**Comment by determo13** [comment]
cuda_11.7.0_515.43.04_linux.run
NVIDIA-Linux-x86_64-470.182.03.run
