### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by ghost** [oobabooga/text-generation-webui#2599]
### Describe the bug

When I run `./start_linux.sh` I get an error.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I don't know what I've done. I installed it with the one click installer and have been running it with `./start_linux.sh`. It was working fine and then I run it again and it's not starting. I don't remember changing anything manually except `CMD_FLAGS = '--cpu --chat --model-menu'` in `webui.py`.

### Logs

```shell
bin /mnt/storage/Software/Linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/mnt/storage/Software/Linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/mnt/storage/Software/Linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
Traceback (most recent call last):
  File "/mnt/storage/Software/Linux/oobabooga_linux/text-generation-webui/server.py", line 1091, in <module>
    update_model_parameters(model_settings, initial=True)  # hijacking the command-line arguments
  File "/mnt/storage/Software/Linux/oobabooga_linux/text-generation-webui/server.py", line 238, in update_model_parameters
    value = int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

### System Info

```shell
❯ uname -a
Linux arch 6.1.31-2-MANJARO #1 SMP PREEMPT_DYNAMIC Sun Jun  4 12:31:46 UTC 2023 x86_64 GNU/Linux
❯ lspci -k | grep -A 2 -i "VGA"
07:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] (rev c8)
        Subsystem: Gigabyte Technology Co., Ltd Cezanne [Radeon Vega Series / Radeon Vega Mobile Series]
        Kernel driver in use: amdgpu
```

**Comment by LastStardaughter** [comment]
This happens whenever I try to load a model.
