### ISSUE TITLE
I successfully installed but i get this error for running

### ISSUE THREAD

**Issue by shamio** [oobabooga/text-generation-webui#2644]
### Describe the bug

I successfully installed the application using one-click installer for Windows, and the installer downloaded mroe than 6 GB of data, but after finishing the installation, when i run start_windows.bat , i get this error and when i press the key, the windows closes and nothing happens.

`bin C:\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll
C:\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
function 'cadam32bit_grad_fp32' not found
INFO:Loading ggml-model.bin...
INFO:llama.cpp weights detected: models\ggml-model.bin

INFO:Cache capacity is 0 bytes
llama.cpp: loading model from models\ggml-model.bin
error loading model: missing tok_embeddings.weight
llama_init_from_file: failed to load model
Traceback (most recent call last):
  File "C:\oobabooga_windows\text-generation-webui\server.py", line 1079, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\oobabooga_windows\text-generation-webui\modules\models.py", line 94, in load_model
    output = load_func(model_name)
  File "C:\oobabooga_windows\text-generation-webui\modules\models.py", line 271, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
  File "C:\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 49, in from_pretrained
    self.model = Llama(**params)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 197, in __init__
    assert self.ctx is not None
AssertionError
Exception ignored in: <function LlamaCppModel.__del__ at 0x000001C9E86180D0>
Traceback (most recent call last):
  File "C:\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 23, in __del__
    self.model.__del__()
AttributeError: 'LlamaCppModel' object has no attribute 'model'
Press any key to continue . . .`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I even installed twice on different folders and the problem persists.

### Logs

```shell
bin C:\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll
C:\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
function 'cadam32bit_grad_fp32' not found
INFO:Loading ggml-model.bin...
INFO:llama.cpp weights detected: models\ggml-model.bin

INFO:Cache capacity is 0 bytes
llama.cpp: loading model from models\ggml-model.bin
error loading model: missing tok_embeddings.weight
llama_init_from_file: failed to load model
Traceback (most recent call last):
  File "C:\oobabooga_windows\text-generation-webui\server.py", line 1079, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\oobabooga_windows\text-generation-webui\modules\models.py", line 94, in load_model
    output = load_func(model_name)
  File "C:\oobabooga_windows\text-generation-webui\modules\models.py", line 271, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
  File "C:\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 49, in from_pretrained
    self.model = Llama(**params)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 197, in __init__
    assert self.ctx is not None
AssertionError
Exception ignored in: <function LlamaCppModel.__del__ at 0x000001C9E86180D0>
Traceback (most recent call last):
  File "C:\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 23, in __del__
    self.model.__del__()
AttributeError: 'LlamaCppModel' object has no attribute 'model'
Press any key to continue . . .
```

### System Info

```shell
CPU, Intel 11300 without additional GPU, Windows 11 Pro, RAM 16 GB
```

**Comment by shamio** [comment]
I have downloaded another model and i got the following errors:
`Traceback (most recent call last): File “C:\oobabooga_windows\text-generation-webui\server.py”, line 70, in load_model_wrapper shared.model, shared.tokenizer = load_model(shared.model_name) File “C:\oobabooga_windows\text-generation-webui\modules\models.py”, line 102, in load_model tokenizer = load_tokenizer(model_name, model) File “C:\oobabooga_windows\text-generation-webui\modules\models.py”, line 137, in load_tokenizer tokenizer = AutoTokenizer.from_pretrained(path_to_model, trust_remote_code=shared.args.trust_remote_code) File “C:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\tokenization_auto.py”, line 709, in from_pretrained return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs) File “C:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py”, line 1825, in from_pretrained return cls._from_pretrained( File “C:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py”, line 1857, in _from_pretrained slow_tokenizer = (cls.slow_tokenizer_class)._from_pretrained( File “C:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py”, line 1988, in _from_pretrained tokenizer = cls(*init_inputs, **init_kwargs) File “C:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\gpt2\tokenization_gpt2.py”, line 188, in init with open(vocab_file, encoding=“utf-8”) as vocab_handle: TypeError: expected str, bytes or os.PathLike object, not NoneType`
