### ISSUE TITLE
No output from any model that is being loaded 

### ISSUE THREAD

**Issue by litlstereo** [oobabooga/text-generation-webui#2649]
### Describe the bug

Hello there, I hope anyone can point me in the right direction here as I'm struggling to find a solution for this. I successfully load the models without any visible errors however when I try to generate the output I cannot see any response from the models. Is there anything I'm missing here? Thanks! 

![image](https://github.com/oobabooga/text-generation-webui/assets/68483319/d17fb1cb-2ede-4f41-b829-c2aa1f228715)
![image](https://github.com/oobabooga/text-generation-webui/assets/68483319/de5733ef-1e11-4c73-88f5-e91e85344105)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

bin D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
2023-06-12 15:09:33 INFO:Loading the extension "gallery"...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
2023-06-12 15:09:41 INFO:Loading anon8231489123_gpt4-x-alpaca-13b-native-4bit-128g...
2023-06-12 15:09:41 WARNING:More than one .pt model has been found. The last one will be selected. It could be wrong.
2023-06-12 15:09:41 INFO:The AutoGPTQ params are: {'model_basename': 'gpt-x-alpaca-13b-native-4bit-128g', 'device': 'cpu', 'use_triton': False, 'use_safetensors': False, 'trust_remote_code': False, 'max_memory': {0: '10000MiB', 'cpu': '5000MiB'}, 'quantize_config': BaseQuantizeConfig(bits=4, group_size=128, damp_percent=0.01, desc_act=False, sym=True, true_sequential=True, model_name_or_path=None, model_file_base_name=None)}
2023-06-12 15:11:12 WARNING:skip module injection for FusedLlamaMLPForQuantizedModel not support integrate without triton yet.
2023-06-12 15:11:12 INFO:Loaded the model in 90.60 seconds.

D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\transformers\generation\utils.py:1405: UserWarning: You are calling .generate() with the `input_ids` being on a device type different than your model's device. `input_ids` is on cpu, whereas the model is on cuda. You may experience unexpected behaviors or slower generation. Please make sure that you have put `input_ids` to the correct device by calling for example input_ids = input_ids.to('cuda') before running `.generate()`.
  warnings.warn(
Traceback (most recent call last):
  File "D:\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\callbacks.py", line 73, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "D:\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 263, in generate_with_callback
    shared.model.generate(**kwargs)
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\modeling\_base.py", line 423, in generate
    return self.model.generate(**kwargs)
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1485, in generate
    return self.sample(
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 2524, in sample
    outputs = self(
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 530, in forward
    inputs_embeds = self.embed_tokens(input_ids)
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\sparse.py", line 162, in forward
    return F.embedding(
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)
Output generated in 1.43 seconds (0.00 tokens/s, 0 tokens, context 122, seed 1279844447)
Traceback (most recent call last):
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\oobabooga_windows\oobabooga_windows\text-generation-webui\server.py", line 107, in load_preset_values
    with open(Path(f'presets/{preset_menu}.yaml'), 'r') as infile:
FileNotFoundError: [Errno 2] No such file or directory: 'presets\\None.yaml'
Traceback (most recent call last):
  File "D:\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\callbacks.py", line 73, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "D:\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 263, in generate_with_callback
    shared.model.generate(**kwargs)
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\modeling\_base.py", line 423, in generate
    return self.model.generate(**kwargs)
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1437, in generate
    return self.greedy_search(
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 2248, in greedy_search
    outputs = self(
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 530, in forward
    inputs_embeds = self.embed_tokens(input_ids)
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\sparse.py", line 162, in forward
    return F.embedding(
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)
Output generated in 0.35 seconds (0.00 tokens/s, 0 tokens, context 127, seed 1860414487)

### Logs

```shell
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)
Output generated in 0.35 seconds (0.00 tokens/s, 0 tokens, context 127, seed 1860414487)
```

### System Info

```shell
AMD Ryzen 5 3600 4.2GHz RTX 3060 12GB Desktop PC • 16GB 3200MHz • 240GB SSD • 1TB Hard Drive • Windows 11
```

**Comment by Deathproof76** [comment]
Same here, running on Ubuntu using latest docker image from https://github.com/Atinoda/text-generation-webui-docker 
Will add more info later.

**Comment by ndparissos** [comment]
Same error to me.

**Comment by litlstereo** [comment]
I've managed to get a response  though not really a response haha it was just a string of numbers and symbols but when I removed --auto-devices and specified --gpu-memory 10 however it was hella slow... now I'm back searching for alternative ways out

**Comment by DamascusGit** [comment]
error still exists. please re-open

**Comment by nikhund** [comment]
I am also having this issue via AutoGPTQ, but only with models larger than my GPU memory limit (5G). For example, TheBloke_WizardLM-7B-V1.0-Uncensored-GPTQ (3.8G) & TheBloke_llama2_7b_chat_uncensored-GPTQ (3.7G) work fine, but TheBloke_WizardLM-13B-V1.0-Uncensored-GPTQ (7G) & TheBloke_WizardLM-30B-uncensored-GPTQ (16G) do not. 

```
2023-07-23 09:35:55 INFO:Loading TheBloke_WizardLM-13B-V1.0-Uncensored-GPTQ...
2023-07-23 09:35:55 INFO:The AutoGPTQ params are: {'model_basename': 'wizardlm-13b-v1.0-uncensored-GPTQ-4bit-128g.no-act.order', 'device': 'cuda:0', 'use_triton': False, 'inject_fused_attention': True, 'inject_fused_mlp': True, 'use_safetensors': True, 'trust_remote_code': False, 'max_memory': {0: '5000MiB', 'cpu': '24500MiB'}, 'quantize_config': None, 'use_cuda_fp16': False}
2023-07-23 09:35:59 WARNING:The safetensors archive passed at models/TheBloke_WizardLM-13B-V1.0-Uncensored-GPTQ/wizardlm-13b-v1.0-uncensored-GPTQ-4bit-128g.no-act.order.safetensors does not contain metadata. Make sure to save your model with the `save_pretrained` method. Defaulting to 'pt' metadata.
2023-07-23 09:37:52 WARNING:skip module injection for FusedLlamaMLPForQuantizedModel not support integrate without triton yet.
2023-07-23 09:37:52 WARNING:models/TheBloke_WizardLM-13B-V1.0-Uncensored-GPTQ/tokenizer_config.json is different from the original LlamaTokenizer file. It is either customized or outdated.
2023-07-23 09:37:52 WARNING:models/TheBloke_WizardLM-13B-V1.0-Uncensored-GPTQ/special_tokens_map.json is different from the original LlamaTokenizer file. It is either customized or outdated.
2023-07-23 09:37:52 INFO:Loaded the model in 117.20 seconds.

Traceback (most recent call last):
tornado==6.3.2
  File "/home/nikdog/Development/text-generation-webui/modules/callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "/home/nikdog/Development/text-generation-webui/modules/text_generation.py", line 297, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/nikdog/.local/lib/python3.10/site-packages/auto_gptq/modeling/_base.py", line 438, in generate
    return self.model.generate(**kwargs)
  File "/home/nikdog/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/nikdog/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "/home/nikdog/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 2642, in sample
    outputs = self(
  File "/home/nikdog/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nikdog/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 806, in forward
    outputs = self.model(
  File "/home/nikdog/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nikdog/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 693, in forward
    layer_outputs = decoder_layer(
  File "/home/nikdog/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nikdog/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/nikdog/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 408, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/nikdog/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nikdog/.local/lib/python3.10/site-packages/auto_gptq/nn_modules/fused_llama_attn.py", line 53, in forward
    qkv_states = self.qkv_proj(hidden_states)
  File "/home/nikdog/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nikdog/.local/lib/python3.10/site-packages/auto_gptq/nn_modules/qlinear/qlinear_cuda_old.py", line 264, in forward
    out = out + self.bias if self.bias is not None else out
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
Output generated in 9.32 seconds (0.00 tokens/s, 0 tokens, context 21, seed 1276542501)
```

It seems as though device should be set to 'cuda:0' and 'cpu!' instead of just 'cuda:0'. I'm using the auto-devices flag. Not sure how else to set that.

**Comment by lecykx** [comment]
RuntimeError: Placeholder storage has not been allocated on MPS device!

**Comment by Delcos** [comment]
Same issue when loading 22b Llama 2 models and assigning part of the model to the gpu and cpu.
