### ISSUE TITLE
AttributeError: 'GPTJForCausalLM' object has no attribute 'model'

### ISSUE THREAD

**Issue by jetunaware** [oobabooga/text-generation-webui#2655]
### Describe the bug

I have a couple of times installed oogabooga, and the launch of the webUI at the end of the initial installation has worked several times, but for some reason I am unable to launch it again subsequently. The text in the title seemed the most relevant from the command prompt of the subsequent failed launches. 

Any help would be much appreciated. I realize I am a total amateur. Very excited to play around with the tool once I can get it working!

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Install latest oogabooga for windows with start_windows.bat
keep the command prompt from installation open and go to the webUI. download the pygmalion 6b model from hugging face
close the webUI and the command prompt
relaunch start_windows.bat

### Screenshot

bin C:\Users\paull\Documents\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117_nocublaslt.dll
2023-06-13 00:02:10 INFO:Loading mayaeary_pygmalion-6b_dev-4bit-128g...
2023-06-13 00:02:10 INFO:The AutoGPTQ params are: {'model_basename': 'pygmalion-6b_dev-4bit-128g', 'device': 'cuda:0', 'use_triton': False, 'use_safetensors': True, 'trust_remote_code': False, 'max_memory': None, 'quantize_config': BaseQuantizeConfig(bits=4, group_size=128, damp_percent=0.01, desc_act=False, sym=True, true_sequential=True, model_name_or_path=None, model_file_base_name=None)}
2023-06-13 00:02:11 WARNING:The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
2023-06-13 00:02:11 WARNING:The safetensors archive passed at models\mayaeary_pygmalion-6b_dev-4bit-128g\pygmalion-6b_dev-4bit-128g.safetensors does not contain metadata. Make sure to save your model with the `save_pretrained` method. Defaulting to 'pt' metadata.
2023-06-13 00:02:21 WARNING:GPTJGPTQForCausalLM hasn't fused mlp module yet, will skip inject fused mlp.
Traceback (most recent call last):
  File "C:\Users\paull\Documents\oobabooga_windows\text-generation-webui\server.py", line 1154, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\paull\Documents\oobabooga_windows\text-generation-webui\modules\models.py", line 94, in load_model
    output = load_func(model_name)
  File "C:\Users\paull\Documents\oobabooga_windows\text-generation-webui\modules\models.py", line 296, in AutoGPTQ_loader
    return modules.AutoGPTQ_loader.load_quantized(model_name)
  File "C:\Users\paull\Documents\oobabooga_windows\text-generation-webui\modules\AutoGPTQ_loader.py", line 60, in load_quantized
    model.embed_tokens = model.model.model.embed_tokens
  File "C:\Users\paull\Documents\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GPTJForCausalLM' object has no attribute 'model'
Press any key to continue . . .

### Logs

```shell
bin C:\Users\paull\Documents\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117_nocublaslt.dll
2023-06-13 00:02:10 INFO:Loading mayaeary_pygmalion-6b_dev-4bit-128g...
2023-06-13 00:02:10 INFO:The AutoGPTQ params are: {'model_basename': 'pygmalion-6b_dev-4bit-128g', 'device': 'cuda:0', 'use_triton': False, 'use_safetensors': True, 'trust_remote_code': False, 'max_memory': None, 'quantize_config': BaseQuantizeConfig(bits=4, group_size=128, damp_percent=0.01, desc_act=False, sym=True, true_sequential=True, model_name_or_path=None, model_file_base_name=None)}
2023-06-13 00:02:11 WARNING:The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
2023-06-13 00:02:11 WARNING:The safetensors archive passed at models\mayaeary_pygmalion-6b_dev-4bit-128g\pygmalion-6b_dev-4bit-128g.safetensors does not contain metadata. Make sure to save your model with the `save_pretrained` method. Defaulting to 'pt' metadata.
2023-06-13 00:02:21 WARNING:GPTJGPTQForCausalLM hasn't fused mlp module yet, will skip inject fused mlp.
Traceback (most recent call last):
  File "C:\Users\paull\Documents\oobabooga_windows\text-generation-webui\server.py", line 1154, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\paull\Documents\oobabooga_windows\text-generation-webui\modules\models.py", line 94, in load_model
    output = load_func(model_name)
  File "C:\Users\paull\Documents\oobabooga_windows\text-generation-webui\modules\models.py", line 296, in AutoGPTQ_loader
    return modules.AutoGPTQ_loader.load_quantized(model_name)
  File "C:\Users\paull\Documents\oobabooga_windows\text-generation-webui\modules\AutoGPTQ_loader.py", line 60, in load_quantized
    model.embed_tokens = model.model.model.embed_tokens
  File "C:\Users\paull\Documents\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GPTJForCausalLM' object has no attribute 'model'
Press any key to continue . . .
```

### System Info

```shell
Windows 10
GPU: NVIDIA GeForce GTX 1070 8GB
```

**Comment by BenjiKCF** [comment]
I got the similar attribute error.
`AttributeError: 'RWForCausalLM' object has no attribute 'model'`

**Comment by mikila85** [comment]
2023-06-13 10:39:06 ERROR:No model is loaded! Select one in the Model tab.

Traceback (most recent call last): File “C:\Users\mike\Downloads\oobabooga_windows\oobabooga_windows\text-generation-webui\[server.py](http://server.py/)”, line 176, in download_model_wrapper model, branch = downloader.sanitize_model_and_branch_names(model, branch) File “C:\Users\mike\Downloads\oobabooga_windows\oobabooga_windows\text-generation-webui\[download-model.py](http://download-model.py/)”, line 82, in sanitize_model_and_branch_names if model[-1] == ‘/’: IndexError: string index out of range

**Comment by lVx2l** [comment]
I have exactly the same error with the same pygmalion model :c

**Comment by zhangmaosen** [comment]
> I got the similar attribute error. `AttributeError: 'RWForCausalLM' object has no attribute 'model'`
comment the lines of  code modules\AutoGPTQ_loader.py below, will work:

    # These lines fix the multimodal extension when used with AutoGPTQ
    if not hasattr(model, 'dtype'):
        model.dtype = model.model.dtype

    if not hasattr(model, 'embed_tokens'):
        model.embed_tokens = model.model.model.embed_tokens

    if not hasattr(model.model, 'embed_tokens'):
        model.model.embed_tokens = model.model.model.embed_tokens

**Comment by Iory1998** [comment]
Same here! I got the same exact error as @jetunaware. Many of the models I have don't work anymore. I spent the entire day trying to fix it thinking I messed up the update or something. Any fix so far?

**Comment by xlavs** [comment]
Having the same problem with 6B pygmalion model.

Commenting out these lines at the end of AutoGPTQloader.py works as a temporary workaraound for me.

~~~
    # # These lines fix the multimodal extension when used with AutoGPTQ
    # if not hasattr(model, 'dtype'):
    #     model.dtype = model.model.dtype

    # if not hasattr(model, 'embed_tokens'):
    #     model.embed_tokens = model.model.model.embed_tokens

    # if not hasattr(model.model, 'embed_tokens'):
    #     model.model.embed_tokens = model.model.model.embed_tokens
~~~

**Comment by oobabooga** [comment]
I think that this fixes this issue https://github.com/oobabooga/text-generation-webui/commit/4d508cbe586823d360e2bcaec4cde16f134331e1

**Comment by jwb1969** [comment]
I can't load any models either, mya error message is pretty much the same as everyone else!
![Model error](https://github.com/oobabooga/text-generation-webui/assets/122735317/c303def2-1301-4e5b-b493-b037163171d9)

**Comment by jwb1969** [comment]
FYI, for me this fix: I think that this fixes this issue https://github.com/oobabooga/text-generation-webui/commit/4d508cbe586823d360e2bcaec4cde16f134331e1

Did stop the yellow warning messages. But it is stuck on loading the  model, it's been trying to load for 30 min. Usually it only took maybe 3-4 minutes.

Close, but no cigar!
