### ISSUE TITLE
llama_tokenize: too many tokens - superbooga bug

### ISSUE THREAD

**Issue by mykeehu** [oobabooga/text-generation-webui#2665]
### Describe the bug

When I turn on superbooga and want to continue an existing conversation on **TheBloke_chronos-wizardlm-uc-scot-st-13B-GGML\chronos-wizardlm-uc-scot-st-13B.ggmlv3.q6_K.bin**, I get the `llama_tokenize: too many tokens` error. If superbooga is not enabled, no problem, it generates the text.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Chat with a character under TheBloke_chronos-wizardlm-uc-scot-st-13B-GGML\chronos-wizardlm-uc-scot-st-13B.ggmlv3.q6_K.bin model, then restart webui with superbooga. Chat again, and get error.

### Logs

```shell
*******************************************************************
* WARNING: You haven't downloaded any model yet.
* Once the web UI launches, head over to the bottom of the "Model" tab and download one.
*******************************************************************


bin J:\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
2023-06-13 18:14:15 INFO:Loading settings from J:\oobabooga_windows\mysettings.yaml...
2023-06-13 18:14:15 INFO:Loading TheBloke_chronos-wizardlm-uc-scot-st-13B-GGML...
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3060
2023-06-13 18:14:16 INFO:llama.cpp weights detected: I:\Textmodels\TheBloke_chronos-wizardlm-uc-scot-st-13B-GGML\chronos-wizardlm-uc-scot-st-13B.ggmlv3.q6_K.bin

2023-06-13 18:14:16 INFO:Cache capacity is 0 bytes
llama.cpp: loading model from I:\Textmodels\TheBloke_chronos-wizardlm-uc-scot-st-13B-GGML\chronos-wizardlm-uc-scot-st-13B.ggmlv3.q6_K.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32001
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 18 (mostly Q6_K)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.09 MB
llama_model_load_internal: using CUDA for GPU acceleration
llama_model_load_internal: mem required  = 2304.46 MB (+ 1608.00 MB per state)
llama_model_load_internal: allocating batch_size x 1 MB = 512 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 40 layers to GPU
llama_model_load_internal: total VRAM used: 10440 MB
...................................................................................................
llama_init_from_file: kv self size  = 1600.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
2023-06-13 18:14:20 INFO:Replaced attention with sdp_attention
2023-06-13 18:14:20 INFO:Loaded the model in 4.97 seconds.

2023-06-13 18:14:20 INFO:Loading the extension "google_translate"...
2023-06-13 18:14:20 INFO:Loading the extension "superbooga"...
2023-06-13 18:14:21 INFO:Intercepting all calls to posthog :)
2023-06-13 18:14:21 WARNING:Using embedded DuckDB without persistence: data will be transient
2023-06-13 18:14:21 WARNING:Using embedded DuckDB without persistence: data will be transient
2023-06-13 18:14:21 INFO:Loading the extension "FPreloader"...
2023-06-13 18:14:21 INFO:Loading the extension "gallery"...

FPreloader ready - Python 3.10.11
Extension "google_translate"...
Extension "superbooga"...
Extension "FPreloader"...
Extension "gallery"...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

llama_tokenize: too many tokens
Traceback (most recent call last):
  File "J:\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 301, in generate_reply_custom
    reply = shared.model.generate(context=question, **generate_params)
  File "J:\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 78, in generate
    for completion_chunk in completion_chunks:
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 815, in _create_completion
    raise ValueError(f"Requested tokens exceed context window of {self._n_ctx}")
ValueError: Requested tokens exceed context window of 2048
llama_tokenize: too many tokens
llama_tokenize: too many tokens
Output generated in 0.02 seconds (0.00 tokens/s, 0 tokens, context 2087, seed 1284973751)
```

**Temporary solution:**
- restart webui
- change n_ctx value to 8192
- save parameters
- reload model
- go chat!

### System Info

```shell
RTX 3060 12 GB
i9-13900K
64 GB RAM
Windows 10 64-bit
```

**Comment by randoentity** [comment]
I see `WARNING:Using embedded DuckDB without persistence: data will be transient` in your logs. I don't know if that's a problem. Can you check if upgrading chromadb helps? When I upgraded to 0.3.26 that warning went away for me, but I resolved the warning before reproducing this.
