### ISSUE TITLE
Error occurred when generating text with Deepspeed

### ISSUE THREAD

**Issue by guijuzhejiang** [oobabooga/text-generation-webui#2675]
### Describe the bug

The chat content can be generated normally without using deepspeed to start the server. After using deepspeed to start the server, the following error occurs when generating a dialog：
  File "/home/miniconda3/envs/py310_DL_cu118/lib/python3.10/site-packages/peft/tuners/lora.py", line 577, in forward
    result = F.linear(x, transpose(self.weight, self.fan_in_fan_out), bias=self.bias)
  File "/home/miniconda3/envs/py310_DL_cu118/lib/python3.10/site-packages/deepspeed/runtime/zero/linear.py", line 108, in zero3_linear_wrap
    return LinearFunctionForZeroStage3.apply(input, weight, bias)
  File "/home/miniconda3/envs/py310_DL_cu118/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/miniconda3/envs/py310_DL_cu118/lib/python3.10/site-packages/torch/cuda/amp/autocast_mode.py", line 98, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/miniconda3/envs/py310_DL_cu118/lib/python3.10/site-packages/deepspeed/runtime/zero/linear.py", line 57, in forward
    output = input.matmul(weight.t())
RuntimeError: size mismatch, got 412, 412x4096,0
Output generated in 0.59 seconds (0.00 tokens/s, 0 tokens, context 412, seed 982033271)

The lora is trained using the qlora strategy, so the following parameters are used for model loading during inference:
load_in_4bit: true
compute_dtype: bfloat16
quant_type: nf4
use_double_quant: true

How to fix this error, thanks in advance

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

deepspeed --num_gpus=1 server.py --deepspeed --bf16 --xformers --chat --model-menu --model xxx_7b --lora xxx_7b _lorar64_loraalpha32

### Logs

```shell
Traceback (most recent call last):
  File "/home/workspace/pycharm/oobabooga_linux/text-generation-webui/modules/callbacks.py", line 73, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/home/workspace/pycharm/oobabooga_linux/text-generation-webui/modules/text_generation.py", line 263, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/miniconda3/envs/py310_DL_cu118/lib/python3.10/site-packages/peft/peft_model.py", line 743, in generate
    outputs = self.base_model.generate(**kwargs)
  File "/home/miniconda3/envs/py310_DL_cu118/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/miniconda3/envs/py310_DL_cu118/lib/python3.10/site-packages/transformers/generation/utils.py", line 1568, in generate
    return self.sample(
  File "/home/miniconda3/envs/py310_DL_cu118/lib/python3.10/site-packages/transformers/generation/utils.py", line 2615, in sample
    outputs = self(
  File "/home/miniconda3/envs/py310_DL_cu118/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/miniconda3/envs/py310_DL_cu118/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 672, in forward
    outputs = self.gpt_neox(
  File "/home/miniconda3/envs/py310_DL_cu118/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/miniconda3/envs/py310_DL_cu118/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 563, in forward
    outputs = layer(
  File "/home/miniconda3/envs/py310_DL_cu118/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/miniconda3/envs/py310_DL_cu118/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 330, in forward
    attention_layer_outputs = self.attention(
  File "/home/miniconda3/envs/py310_DL_cu118/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/miniconda3/envs/py310_DL_cu118/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 126, in forward
    qkv = self.query_key_value(hidden_states)
  File "/home/miniconda3/envs/py310_DL_cu118/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/miniconda3/envs/py310_DL_cu118/lib/python3.10/site-packages/peft/tuners/lora.py", line 577, in forward
    result = F.linear(x, transpose(self.weight, self.fan_in_fan_out), bias=self.bias)
  File "/home/miniconda3/envs/py310_DL_cu118/lib/python3.10/site-packages/deepspeed/runtime/zero/linear.py", line 108, in zero3_linear_wrap
    return LinearFunctionForZeroStage3.apply(input, weight, bias)
  File "/home/miniconda3/envs/py310_DL_cu118/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/miniconda3/envs/py310_DL_cu118/lib/python3.10/site-packages/torch/cuda/amp/autocast_mode.py", line 98, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/miniconda3/envs/py310_DL_cu118/lib/python3.10/site-packages/deepspeed/runtime/zero/linear.py", line 57, in forward
    output = input.matmul(weight.t())
RuntimeError: size mismatch, got 412, 412x4096,0
Output generated in 0.59 seconds (0.00 tokens/s, 0 tokens, context 412, seed 982033271)
```

### System Info

```shell
ubuntu:22
GPU:3090
```

**Comment by hanxiaotian** [comment]
Did you solve this problem?

**Comment by hanxiaotian** [comment]
I think you need to make sure generate function are included in deepspeed forward function, then parameters can be gathered.
