### ISSUE TITLE
Getting AttributeError: 'LlamaCppModel' object has no attribute 'decode'

### ISSUE THREAD

**Issue by jaldaadithya** [oobabooga/text-generation-webui#2682]
### Describe the bug

When I hit the button **Start Lora training** after few seconds I'm getting below error

2023-06-14 17:46:33 INFO:Loading raw text file dataset...
Traceback (most recent call last):
  File "/home/adithya/ai_work/app/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/adithya/ai_work/app/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/adithya/ai_work/app/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/adithya/ai_work/app/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "/home/adithya/ai_work/app/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/adithya/ai_work/app/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/adithya/ai_work/app/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/adithya/ai_work/app/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/adithya/ai_work/app/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "/home/adithya/ai_work/app/oobabooga_linux/text-generation-webui/modules/training.py", line 313, in do_train
    text_chunks = [shared.tokenizer.decode(x) for x in out_tokens]
  File "/home/adithya/ai_work/app/oobabooga_linux/text-generation-webui/modules/training.py", line 313, in <listcomp>
    text_chunks = [shared.tokenizer.decode(x) for x in out_tokens]
AttributeError: 'LlamaCppModel' object has no attribute 'decode'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1) Go to UI http://localhost:7860/
2) Go to Training
3) Under the Train LoRA tab default all settings and go to the Raw text file tab
4) select the raw text file from the dropdown
5) Click on Start LoRA training button

### Screenshot

<img width="1277" alt="image" src="https://github.com/oobabooga/text-generation-webui/assets/19626378/80dab5dc-d23f-4f1b-a33f-877156db8f55">

### Logs

```shell
2023-06-14 17:46:33 INFO:Loading raw text file dataset...
Traceback (most recent call last):
  File "/home/adithya/ai_work/app/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/adithya/ai_work/app/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/adithya/ai_work/app/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/adithya/ai_work/app/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "/home/adithya/ai_work/app/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/adithya/ai_work/app/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/adithya/ai_work/app/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/adithya/ai_work/app/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/adithya/ai_work/app/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "/home/adithya/ai_work/app/oobabooga_linux/text-generation-webui/modules/training.py", line 313, in do_train
    text_chunks = [shared.tokenizer.decode(x) for x in out_tokens]
  File "/home/adithya/ai_work/app/oobabooga_linux/text-generation-webui/modules/training.py", line 313, in <listcomp>
    text_chunks = [shared.tokenizer.decode(x) for x in out_tokens]
AttributeError: 'LlamaCppModel' object has no attribute 'decode'
```

### System Info

```shell
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

CPU 8core 
GPU : NA
```

**Comment by kallebysantos** [comment]
Same error for me when I'd try to train an ``openlm-research/open_llama_7b`` with a small raw text file.

**Comment by end-me-please** [comment]
i think you cant train with GGML models
