### ISSUE TITLE
AttributeError: 'LlamaCppModel' object has no attribute 'decode'

### ISSUE THREAD

**Issue by kiteflo** [oobabooga/text-generation-webui#2700]
### Describe the bug

Hi...

I have installed the latest version of obbabooga on My Macbook Pro and downloaded the following model via Web UI:
TheBloke_Wizard-Vicuna-7B-Uncensored-GGML/Wizard-Vicuna-7B-Uncensored.ggmlv3.q4_K_S.bin

When starting to train the model by adding a simple txt file I receive the error below:

2023-06-15 07:13:09 WARNING:LoRA training has only currently been validated for LLaMA, OPT, GPT-J, and GPT-NeoX models. (Found model type: LlamaCppModel)
2023-06-15 07:13:14 WARNING:It is highly recommended you use `--load-in-8bit` for LoRA training.
2023-06-15 07:13:16 INFO:Loading raw text file dataset...
Traceback (most recent call last):
  File "/Users/fairy_mercury/Downloads/oobabooga_macos/installer_files/env/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/fairy_mercury/Downloads/oobabooga_macos/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/Users/fairy_mercury/Downloads/oobabooga_macos/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/Users/fairy_mercury/Downloads/oobabooga_macos/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "/Users/fairy_mercury/Downloads/oobabooga_macos/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "/Users/fairy_mercury/Downloads/oobabooga_macos/installer_files/env/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/fairy_mercury/Downloads/oobabooga_macos/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/Users/fairy_mercury/Downloads/oobabooga_macos/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/Users/fairy_mercury/Downloads/oobabooga_macos/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "/Users/fairy_mercury/Downloads/oobabooga_macos/text-generation-webui/modules/training.py", line 313, in do_train
    text_chunks = [shared.tokenizer.decode(x) for x in out_tokens]
  File "/Users/fairy_mercury/Downloads/oobabooga_macos/text-generation-webui/modules/training.py", line 313, in <listcomp>
    text_chunks = [shared.tokenizer.decode(x) for x in out_tokens]
AttributeError: 'LlamaCppModel' object has no attribute 'decode'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

<img width="1387" alt="Screenshot 2023-06-15 at 07 21 40" src="https://github.com/oobabooga/text-generation-webui/assets/1423422/fa66729e-ad70-4258-b2f0-7f02fd431e2b">

### Logs

```shell
2023-06-15 07:13:09 WARNING:LoRA training has only currently been validated for LLaMA, OPT, GPT-J, and GPT-NeoX models. (Found model type: LlamaCppModel)
2023-06-15 07:13:14 WARNING:It is highly recommended you use `--load-in-8bit` for LoRA training.
2023-06-15 07:13:16 INFO:Loading raw text file dataset...
Traceback (most recent call last):
  File "/Users/fairy_mercury/Downloads/oobabooga_macos/installer_files/env/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/fairy_mercury/Downloads/oobabooga_macos/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/Users/fairy_mercury/Downloads/oobabooga_macos/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/Users/fairy_mercury/Downloads/oobabooga_macos/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "/Users/fairy_mercury/Downloads/oobabooga_macos/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "/Users/fairy_mercury/Downloads/oobabooga_macos/installer_files/env/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/fairy_mercury/Downloads/oobabooga_macos/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/Users/fairy_mercury/Downloads/oobabooga_macos/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/Users/fairy_mercury/Downloads/oobabooga_macos/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "/Users/fairy_mercury/Downloads/oobabooga_macos/text-generation-webui/modules/training.py", line 313, in do_train
    text_chunks = [shared.tokenizer.decode(x) for x in out_tokens]
  File "/Users/fairy_mercury/Downloads/oobabooga_macos/text-generation-webui/modules/training.py", line 313, in <listcomp>
    text_chunks = [shared.tokenizer.decode(x) for x in out_tokens]
AttributeError: 'LlamaCppModel' object has no attribute 'decode'
```

### System Info

```shell
Macbook Pro Apple M2 Max
```

**Comment by end-me-please** [comment]
i think you cant train with ggml models

**Comment by paulyu12** [comment]
Have you solved this problem ?
