### ISSUE TITLE
no matching keyset

### ISSUE THREAD

**Issue by Locutusque** [oobabooga/text-generation-webui#2710]
### Describe the bug

I'm getting an error saying that there are no matching columns in the train lora tab, but looking at the dataset I'm using and the alpaca chatbot format and they have the same columns.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Use the alpaca dataset format json that came with the source code, and use the vicgalle/alpaca-gpt4 from hugging face dataset turned into json format as the train dataset

### Screenshot

![Screenshot from 2023-06-15 18-02-33](https://github.com/oobabooga/text-generation-webui/assets/122424773/04ed4d5d-92fa-4e51-893f-dc7f1546de63)

### Logs

```shell
Traceback (most recent call last):                                              
  File "/home/locutusque/Desktop/oobabooga_linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/locutusque/Desktop/oobabooga_linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/locutusque/Desktop/oobabooga_linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/locutusque/Desktop/oobabooga_linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "/home/locutusque/Desktop/oobabooga_linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/locutusque/Desktop/oobabooga_linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/locutusque/Desktop/oobabooga_linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/locutusque/Desktop/oobabooga_linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/locutusque/Desktop/oobabooga_linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "/home/locutusque/Desktop/oobabooga_linux/oobabooga_linux/text-generation-webui/modules/training.py", line 349, in do_train
    train_data = data['train'].map(generate_and_tokenize_prompt, new_fingerprint='%030x' % random.randrange(16**30))
  File "/home/locutusque/Desktop/oobabooga_linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 580, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/locutusque/Desktop/oobabooga_linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 545, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/locutusque/Desktop/oobabooga_linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3087, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "/home/locutusque/Desktop/oobabooga_linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3441, in _map_single
    example = apply_function_on_filtered_inputs(example, i, offset=offset)
  File "/home/locutusque/Desktop/oobabooga_linux/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3344, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/home/locutusque/Desktop/oobabooga_linux/oobabooga_linux/text-generation-webui/modules/training.py", line 344, in generate_and_tokenize_prompt
    prompt = generate_prompt(data_point)
  File "/home/locutusque/Desktop/oobabooga_linux/oobabooga_linux/text-generation-webui/modules/training.py", line 341, in generate_prompt
    raise RuntimeError(f'Data-point "{data_point}" has no keyset match within format "{list(format_data.keys())}"')
RuntimeError: Data-point "{'instruction': 'Give three tips for staying healthy.', 'text': 'Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\nGive three tips for staying healthy.\n\n### Response:\n1. Eat a balanced and nutritious diet: Make sure your meals are inclusive of a variety of fruits and vegetables, lean protein, whole grains, and healthy fats. This helps to provide your body with the essential nutrients to function at its best and can help prevent chronic diseases.\n\n2. Engage in regular physical activity: Exercise is crucial for maintaining strong bones, muscles, and cardiovascular health. Aim for at least 150 minutes of moderate aerobic exercise or 75 minutes of vigorous exercise each week.\n\n3. Get enough sleep: Getting enough quality sleep is crucial for physical and mental well-being. It helps to regulate mood, improve cognitive function, and supports healthy growth and immune function. Aim for 7-9 hours of sleep each night.', 'output': '1. Eat a balanced and nutritious diet: Make sure your meals are inclusive of a variety of fruits and vegetables, lean protein, whole grains, and healthy fats. This helps to provide your body with the essential nutrients to function at its best and can help prevent chronic diseases.\n\n2. Engage in regular physical activity: Exercise is crucial for maintaining strong bones, muscles, and cardiovascular health. Aim for at least 150 minutes of moderate aerobic exercise or 75 minutes of vigorous exercise each week.\n\n3. Get enough sleep: Getting enough quality sleep is crucial for physical and mental well-being. It helps to regulate mood, improve cognitive function, and supports healthy growth and immune function. Aim for 7-9 hours of sleep each night.', 'input': ''}" has no keyset match within format "['instruction,output', 'instruction,input,output']"
```

### System Info

```shell
ubuntu latest version, NVIDIA Titan V GPU, 32 gb ram, intel i5-13600kf, 1tb nvme ssd, 2tb external ssd
```

**Comment by Ph0rk0z** [comment]
Edit the format to your format. make a copy and add the missing keys.

**Comment by Locutusque** [comment]
> Edit the format to your format. make a copy and add the missing keys.

that's the thing I did that but I'm still getting this error

**Comment by syaoran68** [comment]
i have also noticed this. not sure if they expect a specific key?

**Comment by yukinotenshi** [comment]
just for anyone who's wondering, there are a couple of possibility why you get this error:
1. Wrong format, your data must be in either
```
{'output': '...', 'instruction': '...'}
```
or
```
{'output: '...', 'instruction': '...', 'input': '...'}
```

2. the format is correct, but the value is empty, which will still throw error. For example, turns out in my dataset, I got some output empty. Simply remove the problematic data point and proceed.

**Comment by marianbastiUNRN** [comment]
I have the same problem. My dataset is formatted as
```json
[
    {
        "instruction,output": "User: A question by the user\nAssistant: The answer by the assistant."
    },
    {
        "instruction,output": "User: A question by the user\nAssistant: The answer by the assistant."
    },
    //...
]
```
and the format json as
```json
{
    "instruction,output": "User: %instruction%\nAssistant: %output%"
}

```
I'm clearly missing something? The error arises with the first item in the dataset.

**Comment by yukinotenshi** [comment]
> I'm clearly missing something? The error arises with the first item in the dataset.

@marianbastiUNRN you can read the format I pasted in my comment above. All keys are separated into their own fields with nothing added (no "User:" or "Assistant"), that would be handled by the program later. "input" is optional, but everything else must be there with non-empty value.

**Comment by marianbastiUNRN** [comment]
Thanks for the reply!
It's weird because the example formats come like that (in this case 'alpaca-chatbot-format.json' )
```json
{
    "instruction,output": "User: %instruction%\nAssistant: %output%",
    "instruction,input,output": "User: %instruction%: %input%\nAssistant: %output%"
}
```

**Comment by Ph0rk0z** [comment]
>the format is correct, but the value is empty, which will still throw error.

That shouldn't be. It used to work with blank output.

**Comment by net-flow** [comment]
I'm also having this issue and I'm confident I have my data formatted correctly. @marianbastiUNRN were you able to get yours working?

**Comment by marianbastiUNRN** [comment]
> I'm also having this issue and I'm confident I have my data formatted correctly. @marianbastiUNRN were you able to get yours working?

I ended up using a variation of an Alpaca dataset I found, and using the existing 'alpaca-chatbot-format.json'

**Comment by jubisa** [comment]
Hi guys, first of all this is an awesome script and I truly hope I get it to work. I am also getting the "no matching keyset" error. My dataset is a JSON file that looks like this. What should be the format file to not get that error?

`{
	"threads": [{
		"topic-url": "https://www.example.org/discussion-forum/viewtopic.php?t=80",
		"topic-subject": "What do men think?",
		"topic-post": [{
			"post": "What do men think of ...",
			"poster": "past member"
		}],
		"replies": [{
			"reply": "Hello Taisie...my goodness girl ...",
			"poster": "tarababys",
			"weight": 1
		}, {
			"reply": "Tarababy, You're quite awesome ...",
			"poster": "past member",
			"weight": 0.3
		}]
	}]
}`

Thank you.

**Comment by talhaanwarch** [comment]
getting this error after around 20% of record,which mean format is correct

**Comment by talhaanwarch** [comment]
https://github.com/oobabooga/text-generation-webui/blob/3ae2cee446b075a20937a60d4e49d42bebf4a744/modules/training.py#L445

I modified this to following
```
def generate_prompt(data_point: dict[str, str]):
    for options, data in format_data.items():
        if set(options.split(',')) == set(x[0] for x in data_point.items() if (type(x[1]) is str and len(x[1].strip()) > 0)):
            for key, val in data_point.items():
                if type(val) is str:
                    data = data.replace(f'%{key}%', val)
            return data
    print(f'Data-point "{data_point}" has no keyset match within format "{list(format_data.keys())}"')
    return None 


def generate_and_tokenize_prompt(data_point):
    prompt = generate_prompt(data_point)
    if prompt is not None:
        return tokenize(prompt, add_eos_token)
    return {'input_ids':[],'labels':[],'attention_mask':[]}

logger.info("Loading JSON datasets...")
data = load_dataset("json", data_files=clean_path('training/datasets', f'{dataset}.json'))
train_data = data['train'].map(generate_and_tokenize_prompt, new_fingerprint='%030x' % random.randrange(16**30))
train_data = train_data.filter(lambda example: not isinstance(example['input_ids'], list))


```

**Comment by jubisa** [comment]
Thank you very much! I will test it and let you know if it works well.

Regards,
Julian
________________________________

**Comment by jubisa** [comment]
Hi Talha,

Ones again, thank you for looking into this. I still get error messages: Here is the complete log, the error is at the end. Let me know if you need any other information from me. You can se my initial post here: https://github.com/oobabooga/text-generation-webui/issues/3549



2023-08-16 04:01:19 WARNING:It is highly recommended you use `--load-in-8bit` for LoRA training. 2023-08-16 04:01:21 INFO:Loading JSON datasets... Map:   0% 0/1 [00:00<?, ? examples/s] Traceback (most recent call last):   File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 427, in run_predict     output = await app.get_blocks().process_api(   File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1323, in process_api     result = await self.call_function(   File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1067, in call_function     prediction = await utils.async_iteration(iterator)   File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 336, in async_iteration     return await iterator.__anext__()   File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 329, in __anext__     return await anyio.to_thread.run_sync(   File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync     return await get_asynclib().run_sync_in_worker_thread(   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread     return await future   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run     result = context.run(func, *args)   File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 312, in run_sync_iterator_async     return next(iterator)   File "/content/text-generation-webui/modules/training.py", line 461, in do_train   File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 592, in wrapper     out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)   File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 557, in wrapper     out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)   File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 3097, in map     for rank, done, content in Dataset._map_single(**dataset_kwargs):   File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 3450, in _map_single     example = apply_function_on_filtered_inputs(example, i, offset=offset)   File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 3353, in apply_function_on_filtered_inputs     processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)   File "/content/text-generation-webui/modules/training.py", line 456, in generate_and_tokenize_prompt     return tokenize(prompt, add_eos_token)   File "/content/text-generation-webui/modules/training.py", line 448, in generate_prompt     for key, val in data_point.items():   File "/content/text-generation-webui/modules/training.py", line 448, in <genexpr>     for key, val in data_point.items(): AttributeError: 'list' object has no attribute 'strip'
________________________________

**Comment by jubisa** [comment]
Hi Talha,

I need your help modifying the code for a custom dataset. I am willing to pay for that.

I tried with all LLAMA models from here - https://github.com/camenduru/text-generation-webui-colab and I couldn't make it work. I run a small website for people with a medical condition and I want to train my own model based on the forum posts done by the members of the website. I really like that your project has a nice interface and it seems easy to work with and understand. I am a PHP programmer and have no understanding of python and all the AI stuff. So, I would need your help.

I don't work for a company and I don't have much of a budget. Let me know if you are willing to do this work for me and how much it will cost. Thank you.

Here is a sample dataset that has the same structure of my dataset.


{
    "threads": [
      {
        "topic-url": "https://www.example.org/discussion-forum/viewtopic.php?t=80",
        "topic-subject": "What do men think?",
        "topic-post": [
          {
            "post": "What do men think of ...",
            "poster": "past member"
          }
        ],
        "replies": [
          {
            "reply": "Hello Taisie...my goodness girl ...",
            "poster": "tarababys",
            "weight": 1
          },
          {
            "reply": "Tarababy, You're quite awesome ...",
            "poster": "past member",
            "weight": 0.3
          }
        ]
      },
      {
        "topic-url": "https://www.example.org/discussion-forum/viewtopic.php?t=90",
        "topic-subject": "What do women think?",
        "topic-post": [
          {
            "post": "What do women think of ...",
            "poster": "past member"
          }
        ],
        "replies": [
          {
            "reply": "Hello Jimmi...my how are you?",
            "poster": "tarababys",
            "weight": 1
          },
          {
            "reply": "Jimmi, You're quite awesome ...",
            "poster": "past member",
            "weight": 0.3
          }
        ]
      }
    ]
}




________________________________

**Comment by marianbastiUNRN** [comment]
The following modification in `modules/training.py` fixed it for me:
```python
from typing import Dict

def generate_prompt(data_point: Dict[str, str]):
    for options, data in format_data.items():
        if set(options.split(',')) == set(x[0] for x in data_point.items() if (x[1] is not None and len(x[1].strip()) > 0)):
            for key, val in data_point.items():
                if val is not None:
                    data = data.replace(f'%{key}%', val)
            return data  # Returning the modified data
    raise RuntimeError(f'Data-point "{data_point}" has no keyset match within format "{list(format_data.keys())}"')

```

**Comment by noobmaster29** [comment]
I have the same issue, did anyone find a solution?

**Comment by VegaStarlake** [comment]
**I'm not proficient in Python so there could be conceptual or other errors in this post, but these steps did solve the problem for me**

For me, this issue was caused by problems with my dataset. I fixed it by:

**1. Removing/Altering the start of the dataset.** I was trying to use vicuna. (I didn't get it to work yet so vicuna might be incompatible with webui, but these instructions should be applicable to other models). Vicuna's format file begins with:

`{
  "instruction,output": "...`

So I began my Dataset incorrectly. I had:

`{"instruction,output": [{"instruction": "`

The fixed version looks like:

`[
    {
        "instruction": "`

The new lines are just formatting changes to make it easier to read. I removed `{"instruction,output":` from the beginning of the file and a `}` from the end.

**2. Ensure the dataset was encoded properly.** This can be automated with a python script. This step may not be necessary. I manually sorted files and then used a script to read them and format them, but iirc some of the files were had encoding problems that carried over.

**3. Use a python script to check the dataset for errors.**

This is what I used:

`import json

def identify_issues(data): # Modify this section to match your format. For example, instruction output may not match your format. The training\formats\ folder has default formats for various models. You can create your own or find creative ways to make your dataset fit in the format, but iirc new formats could have performance issues. 
    problem_entries = []
    for idx, entry in enumerate(data):
        if not isinstance(entry, dict):
            print(f"Unexpected entry at index {idx}: {entry}")
            problem_entries.append((idx, entry))
            continue  # Skip to the next entry
            
        instruction = entry.get('instruction', '').strip() 
        output = entry.get('output', '').strip()

        if not instruction or not output:
            problem_entries.append((idx, entry))

    return problem_entries

with open('path_to_dataset.json', 'r', encoding='utf-8') as f:
    original_data = json.load(f)

problem_entries = identify_issues(original_data)

if problem_entries:
    print(f"Found {len(problem_entries)} problematic entries in the dataset:")
    for idx, entry in problem_entries:
        print(f"Index {idx}: {entry}")
else:
    print("No problematic entries found in the dataset.")`
    
**4.  Locate the problems and fix them.** 

If your IDE is working properly or your dataset is readable (not one long line of text) you may be able to find the problem areas easily, but if you are struggling you can use this to add indexes to the dataset, then ctrl+f to find them and delete or edit them. In my case, somehow through the process of re-encoding or fixing the dataset, some of the entries were blank so I just deleted them. If the error entries are important you'll need to figure out something else. You might consider checking the encoding or characters of the problem files and then finding ways to retain that data or alter it.

I added index numbers to the dataset so I could find the problem areas with this:

`import json

with open('path_to_file.json', 'r', encoding='utf-8') as f:
    dataset = json.load(f)

# Add index numbers as new keys
for i, entry in enumerate(dataset):
    entry['index'] = i

with open('indexed_file.json', 'w', encoding='utf-8') as f:
    json.dump(dataset, f, ensure_ascii=False, indent=4)`
    
Then I removed the indexes:

`import json

# Load the formatted dataset
with open('formatted_file.json', 'r', encoding='utf-8') as f:
    dataset = json.load(f)

# Remove 'index' keys
for entry in dataset:
    entry.pop('index', None)  # The 'None' is a default value if 'index' is not found, meaning no action will be taken.

# Save the dataset back without the 'index' keys
with open('cleaned_file.json', 'w', encoding='utf-8') as f:
    json.dump(dataset, f, ensure_ascii=False, indent=4)`

**Comment by b8kings0ga** [comment]
does anyone know how to resolve the issue?
