### ISSUE TITLE
i cant get the program to start, i had it started successfully once,but after restarting the ui it no longer starts...

### ISSUE THREAD

**Issue by F-16Aircraft** [oobabooga/text-generation-webui#2732]
### Describe the bug

unable to get the program to start. log below....

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

i closed the webui, after starting the webui again with 'start_windows.bat' i recieve the error.

### Logs

```shell
bin F:\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
2023-06-16 23:45:11 INFO:Loading TheBloke_Wizard-Vicuna-30B-Uncensored-GPTQ...
2023-06-16 23:45:11 INFO:Found the following quantized model: models\TheBloke_Wizard-Vicuna-30B-Uncensored-GPTQ\Wizard-Vicuna-30B-Uncensored-GPTQ-4bit.act.order.safetensors
Traceback (most recent call last):
  File "F:\oobabooga_windows\text-generation-webui\server.py", line 1006, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "F:\oobabooga_windows\text-generation-webui\modules\models.py", line 65, in load_model
    output = load_func_map[loader](model_name)
  File "F:\oobabooga_windows\text-generation-webui\modules\models.py", line 263, in GPTQ_loader
    model = modules.GPTQ_loader.load_quantized(model_name)
  File "F:\oobabooga_windows\text-generation-webui\modules\GPTQ_loader.py", line 177, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.wbits, shared.args.groupsize, kernel_switch_threshold=threshold)
  File "F:\oobabooga_windows\text-generation-webui\modules\GPTQ_loader.py", line 52, in _load_quant
    model = AutoModelForCausalLM.from_config(config, trust_remote_code=shared.args.trust_remote_code)
  File "F:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 425, in from_config
    return model_class._from_config(config, **kwargs)
  File "F:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 1143, in _from_config
    model = cls(config, **kwargs)
  File "F:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 615, in __init__
    self.model = LlamaModel(config)
  File "F:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 446, in __init__
    self.layers = nn.ModuleList([LlamaDecoderLayer(config) for _ in range(config.num_hidden_layers)])
  File "F:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 446, in <listcomp>
    self.layers = nn.ModuleList([LlamaDecoderLayer(config) for _ in range(config.num_hidden_layers)])
  File "F:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 256, in __init__
    self.mlp = LlamaMLP(
  File "F:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 149, in __init__
    self.gate_proj = nn.Linear(hidden_size, intermediate_size, bias=False)
  File "F:\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\linear.py", line 96, in __init__
    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 238551040 bytes.
Press any key to continue . . .
```

### System Info

```shell
windows 11, NVIDA RTX 2060 gupu, the ai model is: TheBloke/Wizard-Vicuna-30B-Uncensored-GPTQ
```

**Comment by n00mkrad** [comment]
You can't load a 30B model into a 2060

**Comment by F-16Aircraft** [comment]
> You can't load a 30B model into a 2060
yeah but i cant even get the webui to start anymore, it was starting originally, but now it wont, and i cant seem to change the model before using the 'start_windows.bat' file.

**Comment by F-16Aircraft** [comment]
i figured out how to get it to run again by deleting the model in the models folder, not sure what model i will be able to use with my 2060 going to try the 13b model,

**Comment by F-16Aircraft** [comment]
i got the model working and loaded properly, however the console outputs this when i try to ask it something and it does not generate a reply, only replies with the assistant name: Output generated in 0.37 seconds (0.00 tokens/s, 0 tokens, context 396, seed 1640811788)
