### ISSUE TITLE
How do I enable Apple Silicon Metal support with the macos one-click installer?

### ISSUE THREAD

**Issue by CyborgArmy83** [oobabooga/text-generation-webui#2736]
Like the title says, how can I enable Metal (GPU) acceleration on Apple Silicon (M1 / M2) devices or is this not entirely supported yet?

**Comment by jllllll** [comment]
Pytorch installation instructions on their webpage indicate that this should enable Metal acceleration:
```
conda remove cpuonly
conda install pytorch::pytorch torchvision torchaudio -c pytorch
```
If that works, I'll write up a pull request to update the installer.

**Comment by CyborgArmy83** [comment]
> Run `cmd_macos.sh` and enter these commands:
> 
> ```
> conda remove cpuonly
> conda install pytorch::pytorch torchvision torchaudio -c pytorch
> ```
> 
> Pytorch installation instructions on their webpage indicate that this should enable Metal acceleration.
> 
> > # MPS acceleration is available on MacOS 12.3+
> > conda install pytorch::pytorch torchvision torchaudio -c pytorch
> 
> If that works, I'll write up a pull request to update the installer. If that doesn't work, try this:
> 
> ```
> conda remove pytorch torchvision torchaudio
> python -m pip install torch torchvision torchaudio
> python -m pip install -r ./text-generation-webui/requirements.txt --upgrade
> ```
> 
> I don't have a Mac, so I can only rely on what the Pytorch instructions say.

Thanks, I will try it out

**Comment by CyborgArmy83** [comment]
I had no luck so far, it will not even let me launch the cmd_macos.sh 

I am getting this erorr: 

cmd_macos.sh: line 19: syntax error near unexpected token `('
cmd_macos.sh: line 19: `bash --init-file <(echo "source \"$CONDA_ROOT_PREFIX/etc/profile.d/conda.sh\" && conda activate \"$INSTALL_ENV_DIR\"")' 

Can anyone tell me if Apple Silicon and Metal support is already possible in this software? I am willing to delete all and run the one-click installer script again, but I guess I'll have to edit the script to enable GPU acceleration.

**Comment by jllllll** [comment]
The MacOS installer was updated to fix that issue. Re-download the zip and extract the cmd_macos.sh script to replace the broken one.

**Comment by CyborgArmy83** [comment]
> The MacOS installer was updated to fix that issue. Re-download the zip and extract the cmd_macos.sh script to replace the broken one.

I am still not able to install Oobabooga with Metal GPU support on my M1 Max 64GB system. The one click installer does not install the required modules when choosing the M1/M2 Apple Silicon option.

Using your first suggested commands, I got a whole slew of errors, after also trying the alternative command I get:

james@apple oobabooga_macos % sh start_macos.sh 
Traceback (most recent call last):
  File "/Users/james/Downloads/oobabooga_macos/text-generation-webui/server.py", line 5, in <module>
    from modules.block_requests import RequestBlocker
  File "/Users/james/Downloads/oobabooga_macos/text-generation-webui/modules/block_requests.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

What is the best way to get this working? I've been having issues for it for weeks. There was also bugs in the one-click installer before but it still does not work as one should expect.

I would really like to give Oobabooga a try but I really want Metal support :)

**Comment by jllllll** [comment]
The `requests` package was meant to be installed along side Pytorch immediately after choosing an installation option.

The Mac option in the installer operates the same as choosing the CPU-only option. Delete, move or rename the `text-generation-webui` folder such that it isn't in the same folder as the installer, then run the start script again. That should get it to restart the installation process from the beginning. If you see any errors, be sure to post them here.

Worst case scenario, I can give you instructions for manually installing everything.

**Comment by CyborgArmy83** [comment]
> The `requests` package was meant to be installed alongside Pytorch immediately after choosing an installation option.
> 
> The Mac option in the installer operates the same as choosing the CPU-only option. Delete, move or rename the `text-generation-webui` folder such that it isn't in the same folder as the installer, then run the start script again. That should get it to restart the installation process from the beginning. If you see any errors, be sure to post them here.
> 
> Worst case scenario, I can give you instructions for manually installing everything.

I just tried that and reinstalled everything, it seems that it still using my CPU cores, I do see some light GPU activity, but compared to other LLM apps that use Metal acceleration (which spikes my GPU activity to 100% but does not consume CPU, this looks very different on my activity graphs)

It seems it uses all my CPU cores and a little bit of GPU at the same time, which is kinda weird. It is also slower than other LLM apps with metal support.

I use llama.cpp as loader. I've tried several supported models with the Q4-K_M and Q5-K_M file format.

Can you check these settings and see if I am missing something? 

---
llama_init_from_file: kv self size  = 3120.00 MB
AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | VSX = 0 | 
2023-06-28 18:40:30 INFO:Loaded the model in 0.38 seconds.
---

I do see ARM_FMA = 1 but not sure if others should be "1" as well. 

I also noticed this warning every time I start:

/oobabooga_macos/installer_files/env/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'

But from reading, this is probably because it does not support Apple Silicon? 

Thanks for the help so far, it is appreciated!

**Comment by Ciel-MC** [comment]
What is the state of this issue right now? I tried setting it up on my M1 macbook with no luck, if I install manually, it looks lie it only uses the CPU, I am using Transformer and getting 0.02 token/s, I do believe that the M1 is capable of more than this, I could be wrong though. If I use the one-click installer, it tries(?) to use the GPU but gets the error `RuntimeError: MPS does not support cumsum op with int64 input` on line `position_ids = attention_mask.long().cumsum(-1) - 1`, running neither
```bash
conda remove cpuonly
conda install pytorch::pytorch torchvision torchaudio -c pytorch
```(I should note that this says cpuonly isn't something that can be removed)
nor
```bash
conda remove pytorch torchvision torchaudio
python -m pip install torch torchvision torchaudio
python -m pip install -r ./text-generation-webui/requirements.txt --upgrade
```
fixed the problem.
The former ended somehow screwed with the env to the point that imports stopped working.
I ran the second script separately just to be safe:
First line will uninstall the pkgs if you ran the first command set, but it *does not* fix the prompt of not being able to import anything
Second line doesn't fix the prompt, or as I see, do anything really.
Third line seems to say that everything is satisfied, and prints an error about tiktoken, and numpy's version being too high for openai-whispe and numba respectively. But otherwise it doesn't do anything, the error persists.

**Comment by jllllll** [comment]
@Ciel-MC It seems to be an older bug in Pytorch that wasn't fixed in 2.0 release. Devs say that the fix is currently in the nightly builds:
```
python -m pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu
```

**Comment by Ciel-MC** [comment]
@jllllll 
First of all, nightly shows this warning
```
UserWarning: 'has_mps' is deprecated, please use 'torch.backends.mps.is_built()'
```
So that's a thing.

Second, running this (I did it with --force just to be sure) still uses the CPU, and (I think) gpu parameters aren't showing up in the model tab.
<img width="359" alt="image" src="https://github.com/oobabooga/text-generation-webui/assets/47144701/ff2ebe4f-613d-40b3-8e7d-2d865f598d1a">

**Comment by AndrewTriesToCode** [comment]
I have had success getting this to work with my M1 Max 32GB.

1. Install with one click installer. Run `start_macos.sh` and select the Apple option. Exit application.
2. Run `cmd_macos.sh` and run this command from [here](https://github.com/oobabooga/text-generation-webui/blob/main/docs/llama.cpp.md) then exit the shell:
```sh
pip uninstall -y llama-cpp-python
CMAKE_ARGS="-DLLAMA_METAL=on" FORCE_CMAKE=1 pip install llama-cpp-python --no-cache-dir
```
3. Run `start_macos.sh' again and load a model. Then set the `-n-gpu-layers` option to 1 and **reload** the model

At this point I see some terminal messages in the load output that indicate metal is being used:
```
ggml_metal_add_buffer: allocated 'data            ' buffer, size = 16384.00 MB, offs =            0
ggml_metal_add_buffer: allocated 'data            ' buffer, size =  1288.00 MB, offs =  17005117440, (17674.31 / 21845.34)
ggml_metal_add_buffer: allocated 'eval            ' buffer, size =    16.00 MB, (17690.31 / 21845.34)
ggml_metal_add_buffer: allocated 'kv              ' buffer, size =  3122.00 MB, (20812.31 / 21845.34)
ggml_metal_add_buffer: allocated 'scr0            ' buffer, size =   387.00 MB, (21199.31 / 21845.34)
ggml_metal_add_buffer: allocated 'scr1            ' buffer, size =   256.00 MB, (21455.31 / 21845.34)
```

Speed of generation and activity manager confirms this is working. I'm getting about ~11/12 tokens per second on a 33b 4bit model.

**Comment by jllllll** [comment]
To be clear, the installer's `Apple M Series` option is pretty much the same as the CPU option. It is just there to clarify that MacOS GPU is technically supported. Another thing to note, is that only HF (unquantized) models use MacOS GPU by default as part of Pytorch's Metal support. llama-cpp-python has nothing to do with Pytorch and needs to be built manually for Metal support on GGML models. Metal support for both applies to both Intel CPU with an AMD graphics card and M1/2.

**Comment by Ciel-MC** [comment]
> I have had success getting this to work with my M1 Max 32GB.
> 
>     1. Install with one click installer. Run `start_macos.sh` and select the Apple option. Exit application.
> 
>     2. Run `cmd_macos.sh` and run this command from [here](https://github.com/oobabooga/text-generation-webui/blob/main/docs/llama.cpp.md) then exit the shell:
> 
> 
> ```shell
> pip uninstall -y llama-cpp-python
> CMAKE_ARGS="-DLLAMA_METAL=on" FORCE_CMAKE=1 pip install llama-cpp-python --no-cache-dir
> ```
> 
> I think the `--no-cache-dir` is critical.
> 
>     3. Run `start_macos.sh` again and **select** a model to load in the model tab of the ui. **Before you load the model**, set the `-n-gpu-layers` option to 1 and then load the model.
> 
> 
> At this point I see some terminal messages in the load output that indicate metal is being used:
> 
> ```
> ggml_metal_add_buffer: allocated 'data            ' buffer, size = 16384.00 MB, offs =            0
> ggml_metal_add_buffer: allocated 'data            ' buffer, size =  1288.00 MB, offs =  17005117440, (17674.31 / 21845.34)
> ggml_metal_add_buffer: allocated 'eval            ' buffer, size =    16.00 MB, (17690.31 / 21845.34)
> ggml_metal_add_buffer: allocated 'kv              ' buffer, size =  3122.00 MB, (20812.31 / 21845.34)
> ggml_metal_add_buffer: allocated 'scr0            ' buffer, size =   387.00 MB, (21199.31 / 21845.34)
> ggml_metal_add_buffer: allocated 'scr1            ' buffer, size =   256.00 MB, (21455.31 / 21845.34)
> ```
> 
> Speed of generation and activity manager confirms this is working. I'm getting about about 12-13 tokens per second on a 33b 4bit model.
> 
> I didn't have to reinstall PyTorch or use nightlies or anything.

This is for llama right? I'm using transformer and this didn't help, I was hopeful that this would somehow help, but as expected, it did nothing for the HF model.

**Comment by jllllll** [comment]
```
python -m pip install torch torchvision torchaudio
```
This is what the official Pytorch instructions for MacOS 12.3+ says to get MPS (Metal) GPU acceleration working. You may need to add `--force-reinstall --no-deps` to replace what you have currently. It's worth noting that this is what the latest version of the one-click-installer uses to install Pytorch on Macs. If it isn't working, then I don't know what else to do.

**Comment by Ciel-MC** [comment]
> 

If I do this in the one-click installer version, it just completely kills the installation lol, if I go into the python env, I couldn't import anything

If I do this on a regular manual installation, this happens when I click generate after loading it in:
```

/opt/homebrew/Caskroom/miniconda/base/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py:725: UserWarning: MPS: no support for int64 repeats mask, casting it to int32 (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/Repeat.mm:236.)
  input_ids = input_ids.repeat_interleave(expand_size, dim=0)
Traceback (most recent call last):
  File "/Users/ciel/text-generation-webui/modules/callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "/Users/ciel/text-generation-webui/modules/text_generation.py", line 293, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2639, in sample
    model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 861, in prepare_inputs_for_generation
    position_ids = attention_mask.long().cumsum(-1) - 1
RuntimeError: MPS does not support cumsum op with int64 input
Output generated in 0.55 seconds (0.00 tokens/s, 0 tokens, context 16, seed 1423188738)
```

**Comment by jllllll** [comment]
The one-click-installer uses a Conda env, not a Python venv. A `cmd_*` script is included to easily enter the environment.

That particular error is due to a bug in Pytorch 2.0.x that wasn't fixed. It is fixed in the nightly builds, I just forgot about that:
```
python -m install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu
```
This version isn't included in the installer due to the constant changes being made to it and older versions not being kept.
If a breaking change is made, then the webui would just be uninstallable for MacOS users.

**Comment by Ciel-MC** [comment]
> 



> The one-click-installer uses a Conda env, not a Python venv. A `cmd_*` script is included to easily enter the environment.
> 
> That particular error is due to a bug in Pytorch 2.0.x that wasn't fixed. It is fixed in the nightly builds, I just forgot about that:
> 
> ```
> python -m install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu
> ```
> 
> This version isn't included in the installer due to the constant changes being made to it and older versions not being kept. If a breaking change is made, then the webui would just be uninstallable for MacOS users.

Uh, the manual instruction also uses conda? I always did conda smth and not python -m venv.

I'm tried that already and it doesn't throw the error anymore, but it doesn't use the GPU either, it's doing like, 1 token/30s on a 14 inch MacBook Pro 2021

**Comment by jllllll** [comment]
Metal requires MacOS 12.3+. If you are on that, then it may simply be broken. Not much that can be done about it except for hoping that the Pytorch devs eventually fix it.

**Comment by Ciel-MC** [comment]
> Metal requires MacOS 12.3+. If you are on that, then it may simply be broken. Not much that can be done about it except for hoping that the Pytorch devs eventually fix it.

Yeah I'm on Ventura 13.4.1, so that's not the problem. Weird how nobody else has complained about this to the PyTorch dev to get it fixed yet, since not being able to use GPU on Apple Silicon is quite a big deal, you'd think.

**Comment by PierreEscargot** [comment]
are you using q4_0? it only works with that

**Comment by AndrewTriesToCode** [comment]
To clarify my post, yeah using llama.cpp ggml models. Specifically the q4_k_s variant.

**Comment by Majestic81** [comment]
> I have had success getting this to work with my M1 Max 32GB.
> 
> 1. Install with one click installer. Run `start_macos.sh` and select the Apple option. Exit application.
> 2. Run `cmd_macos.sh` and run this command from [here](https://github.com/oobabooga/text-generation-webui/blob/main/docs/llama.cpp.md) then exit the shell:
> 
> ```shell
> pip uninstall -y llama-cpp-python
> CMAKE_ARGS="-DLLAMA_METAL=on" FORCE_CMAKE=1 pip install llama-cpp-python --no-cache-dir
> ```
> 
> I think the `--no-cache-dir` is critical.
> 
> 3. Run `start_macos.sh` again and **select** a model to load in the model tab of the ui. **Before you load the model**, set the `-n-gpu-layers` option to 1 and then load the model.
> 
> At this point I see some terminal messages in the load output that indicate metal is being used:
> 
> ```
> ggml_metal_add_buffer: allocated 'data            ' buffer, size = 16384.00 MB, offs =            0
> ggml_metal_add_buffer: allocated 'data            ' buffer, size =  1288.00 MB, offs =  17005117440, (17674.31 / 21845.34)
> ggml_metal_add_buffer: allocated 'eval            ' buffer, size =    16.00 MB, (17690.31 / 21845.34)
> ggml_metal_add_buffer: allocated 'kv              ' buffer, size =  3122.00 MB, (20812.31 / 21845.34)
> ggml_metal_add_buffer: allocated 'scr0            ' buffer, size =   387.00 MB, (21199.31 / 21845.34)
> ggml_metal_add_buffer: allocated 'scr1            ' buffer, size =   256.00 MB, (21455.31 / 21845.34)
> ```
> 
> Speed of generation and activity manager confirms this is working. I'm getting about about 12-13 tokens per second on a 33b 4bit model.
> 
> I am using a llama.cpp ggml model so I didn't have to reinstall PyTorch or use nightlies or anything.

This worked for me, thanks!
Working great on my M1 MAX 64gb
I am now checking how I turn on the Whisper Neural engine acceleration!

**Comment by cfmbrand** [comment]
> > Metal requires MacOS 12.3+. If you are on that, then it may simply be broken. Not much that can be done about it except for hoping that the Pytorch devs eventually fix it.
> 
> 
> 
> Yeah I'm on Ventura 13.4.1, so that's not the problem. Weird how nobody else has complained about this to the PyTorch dev to get it fixed yet, since not being able to use GPU on Apple Silicon is quite a big deal, you'd think.

@Ciel-MC this is where I'm at right now - super slow, clearly not using the GPU.

**Comment by scott-mackenzie** [comment]
**Hardware Overview:**

      Model Name: MacBook Pro
      Model Identifier: Mac14,6
      Model Number: Z179000H4LL/A
      Chip: Apple M2 Max
      Total Number of Cores: 12 (8 performance and 4 efficiency)
      Memory: 96 GB
      System Firmware Version: 8422.141.2
      OS Loader Version: 8422.141.2
  
Using the latest source `https://github.com/oobabooga/text-generation-webui.git` and performing the standard setup it seems that the GPU offloading works if one follows the suggestion by @AndrewTriesToCode above where he states, make sure to change "n-gpu-layers" option in the models tab to your desired threshold and then reload the model.

![Screenshot 2023-09-24 at 12 25 58 PM](https://github.com/oobabooga/text-generation-webui/assets/1774915/51bb881a-7145-4d3c-8d45-e826027dee01)

**See above example.** 

I still see the error in the command console when starting using the start script but by making the suggested change to the "n-gpu-layers" option in webui models tab the load moves from CPU to GPU so it does seem to work:

`text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
2023-09-24 11:38:39 INFO:Loading the extension "gallery"...
Running on local URL:  http://127.0.0.1:7860`

After making the change and reloading the model, and this is using Llama 2 70B Chat - GGUF, it can be seen through Activity Monitor that the offloading is working, see below:

![image](https://github.com/oobabooga/text-generation-webui/assets/1774915/6ee276c9-c58e-4e1e-85b7-44d1c67aa3e6)

`Output generated in 78.83 seconds (6.98 tokens/s, 550 tokens, context 130, seed 1134034710)`

Please keep in mind the tokens per second is on a laptop using Llama 2 70B Chat.  Providing one follows the suggestion by @AndrewTriesToCode above where he states, make sure to change "n-gpu-layers" option in the models tab to your desired threshold and then reload the model it does seem to work.  Can someone else please confirm?

**Comment by jllllll** [comment]
Glad my llama-cpp-python Metal builds work. Had trouble finding people to test it for a while as I don't have a Mac to test with myself.

That warning on startup is from bitsandbytes showing that it is running in CPU-only mode, which is needed on Mac since it's CUDA code isn't compatible.

---
For additional performance on Mac, you can try building NumPy from source with Accelerate support.

On MacOS 13.3+:
```
python -m pip install  numpy --force-reinstall --no-deps --no-cache --no-binary :all: -Csetup-args=-Dblas=accelerate -Csetup-args=-Dlapack=accelerate -Csetup-args=-Duse-ilp64=true
```
On MacOS older than 13.3:
```
python -m pip install  numpy --force-reinstall --no-deps --no-cache --no-binary :all: -Csetup-args=-Dblas=accelerate -Csetup-args=-Dlapack=accelerate
```

**Comment by scott-mackenzie** [comment]
On mac the above suggestion ends up with below error:

`❯ python -m pip install numpy --force-reinstall --no-deps --no-cache --no-binary :all: -Csetup-args=-Dblas=accelerate -Csetup-args=-Dlapack=accelerate -Csetup-args=-Duse-ilp64=true

Usage:
  /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install [options] <requirement specifier> [package-index-options] ...
  /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install [options] -r <requirements file> [package-index-options] ...
  /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install [options] [-e] <vcs project url> ...
  /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install [options] [-e] <local project path> ...
  /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install [options] <archive url/path> ...

no such option: -C`

**Comment by jllllll** [comment]
Why is your `python` command using a completely different Python installation to your `pip` command?

Make sure you are using `cmd_macos.sh` to enter these commands or else it won't effect the webui.
The one-click-installer isolates the webui's packages into a virtual environment which that script activates for easier modification.

**Comment by scott-mackenzie** [comment]
Excellent question. 

After going inside the env I corrected the pip/python version issue.

`❯ ./cmd_macos.sh pip --version

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$ pip --version
pip 23.2.1 from /Users/scott.mackenzie/WebstormProjects/text-generation-webui/installer_files/env/lib/python3.10/site-packages/pip (python 3.10)
bash-3.2$ python --version
Python 3.10.13`

And, drum roll.... now it works!

`bash-3.2$ python -m pip install numpy --force-reinstall --no-deps --no-cache --no-binary :all: -Csetup-args=-Dblas=accelerate -Csetup-args=-Dlapack=accelerate -Csetup-args=-Duse-ilp64=true
Collecting numpy
  Downloading numpy-1.26.0.tar.gz (15.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.6/15.6 MB 14.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: numpy
  Building wheel for numpy (pyproject.toml) ... done
  Created wheel for numpy: filename=numpy-1.26.0-cp310-cp310-macosx_13_0_arm64.whl size=18499110 sha256=54e245f31782aeea5ff56f85c7b81fa04e6a31e76b87fe4f27782fca3a209d3f
  Stored in directory: /private/var/folders/x7/5xlx0b113vq6t5k2hzfn23xw0000gn/T/pip-ephem-wheel-cache-eo4veu6j/wheels/e8/30/57/9dd4b6feb9e57a2ee777d9986f9d96e22ca08607d8645bcaf4
Successfully built numpy
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.24.0
    Uninstalling numpy-1.24.0:
      Successfully uninstalled numpy-1.24.0
Successfully installed numpy-1.26.0`

Thanks for pointing that out. Usually the little things that one overlooks that bites one. Appreciate the assist.
