### ISSUE TITLE
Will not load model on start or when I manually load it

### ISSUE THREAD

**Issue by TimyIsCool** [oobabooga/text-generation-webui#2749]
### Describe the bug

Im trying to start the webui with the pygmalion-13b model but i get the error (see below)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run the webui with the notstoic/pygmalion-13b-4bit-128g model

### Logs

```shell
bin F:\Ai\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117_nocublaslt.dll
2023-06-18 19:30:46 INFO:Loading notstoic_pygmalion-13b-4bit-128g...
Loading checkpoint shards:   0%|                                                                                                                                                                                      | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "F:\Ai\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 463, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "F:\Ai\oobabooga_windows\installer_files\env\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "F:\Ai\oobabooga_windows\installer_files\env\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "F:\Ai\oobabooga_windows\installer_files\env\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models\\notstoic_pygmalion-13b-4bit-128g\\pytorch_model-00001-of-00003.bin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Ai\oobabooga_windows\text-generation-webui\server.py", line 1014, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "F:\Ai\oobabooga_windows\text-generation-webui\modules\models.py", line 65, in load_model
    output = load_func_map[loader](model_name)
  File "F:\Ai\oobabooga_windows\text-generation-webui\modules\models.py", line 127, in huggingface_loader
    model = LoaderClass.from_pretrained(Path(f"{shared.args.model_dir}/{model_name}"), low_cpu_mem_usage=True, torch_dtype=torch.bfloat16 if shared.args.bf16 else torch.float16, trust_remote_code=shared.args.trust_remote_code)
  File "F:\Ai\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 484, in from_pretrained
    return model_class.from_pretrained(
  File "F:\Ai\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2881, in from_pretrained
    ) = cls._load_pretrained_model(
  File "F:\Ai\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 3214, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "F:\Ai\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 466, in load_state_dict
    with open(checkpoint_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models\\notstoic_pygmalion-13b-4bit-128g\\pytorch_model-00001-of-00003.bin'
Press any key to continue . . .
```

### System Info

```shell
Nvidia Tesla P40 24GB
```

**Comment by TimyIsCool** [comment]
![image](https://github.com/oobabooga/text-generation-webui/assets/74112751/c4c1dd81-73f1-4b21-bdbd-ef435694444b)
This is all I get when the model tries to load when I start the web UI

**Comment by missionfloyd** [comment]
Set "Model loader" to AutoGPTQ, then click "Save settings".

**Comment by Webslug** [comment]
I've been having that same error lately too.   I tried setting the model loader to AutoGPTQ and it still causes the issue.

**Comment by TimyIsCool** [comment]
Try reading through this on discord https://discord.com/channels/1089972953506123937/1120427314266783804
Invite link: https://discord.gg/u27RhJECcW
Solved my issue there
