### ISSUE TITLE
Issues getting oobabooga to work. (Traceback error)

### ISSUE THREAD

**Issue by PrinceOfIonia** [oobabooga/text-generation-webui#2754]
### Describe the bug

Hello, whenever I try to type in anything in the input chat, I get this error.

I am very very new to this with little clue what I am doing. I simply followed the tutorials to the best of my ability. Thank you for your help. I can provide additional info if need be.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Here are my launch parameters: --cpu --chat --wbits 4 --groupsize 128

### Logs

```shell
bin C:\Users\Wilkie\Desktop\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll
C:\Users\Wilkie\Desktop\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
function 'cadam32bit_grad_fp32' not found
2023-06-18 16:24:29 INFO:Loading the extension "gallery"...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
2023-06-18 16:25:14 INFO:Loading mayaeary_pygmalion-6b_dev-4bit-128g...
2023-06-18 16:25:14 INFO:The AutoGPTQ params are: {'model_basename': 'pygmalion-6b_dev-4bit-128g', 'device': 'cpu', 'use_triton': False, 'use_safetensors': True, 'trust_remote_code': False, 'max_memory': None, 'quantize_config': BaseQuantizeConfig(bits=4, group_size=128, damp_percent=0.01, desc_act=False, sym=True, true_sequential=True, model_name_or_path=None, model_file_base_name=None)}
2023-06-18 16:25:14 WARNING:CUDA extension not installed.
2023-06-18 16:25:15 WARNING:The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
2023-06-18 16:25:15 WARNING:The safetensors archive passed at models\mayaeary_pygmalion-6b_dev-4bit-128g\pygmalion-6b_dev-4bit-128g.safetensors does not contain metadata. Make sure to save your model with the `save_pretrained` method. Defaulting to 'pt' metadata.
2023-06-18 16:25:26 WARNING:GPTJGPTQForCausalLM hasn't fused mlp module yet, will skip inject fused mlp.
2023-06-18 16:25:26 INFO:Loaded the model in 12.45 seconds.

Traceback (most recent call last):
  File "C:\Users\Wilkie\Desktop\oobabooga_windows\text-generation-webui\modules\callbacks.py", line 73, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "C:\Users\Wilkie\Desktop\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 263, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Users\Wilkie\Desktop\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\modeling\_base.py", line 422, in generate
    with torch.inference_mode(), torch.amp.autocast(device_type=self.device.type):
  File "C:\Users\Wilkie\Desktop\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\modeling\_base.py", line 411, in device
    device = [d for d in self.hf_device_map.values() if d not in {'cpu', 'disk'}][0]
IndexError: list index out of range
Output generated in 0.27 seconds (0.00 tokens/s, 0 tokens, context 63, seed 324656358)
```

### System Info

```shell
My PC specs are as followed.

OS: Windows 10 Home 64-bit
CPU: AMD Ryzen 9 5900X 12-Core Processor
RAM: 32.0GB Dual-Channel DDR4 @ 1799MHz (18-22-22-42)
Motherboard: Gigabyte Technology Co. Ltd. X570S AORUS MASTER (AM4)
GPU: 12272MB ATI AMD Radeon RX 6700 XT (ASRock)
```

**Comment by PrinceOfIonia** [comment]
I also realize I am trying to use this program with an AMD GPU, users on another Discord told me I should be fine if I used the --cpu launch option.

**Comment by ashish-um** [comment]
were you able to solve it, im using the same model  and getting the same exact error. I'm using an AMD cpu and no gpu

**Comment by ashish-um** [comment]
seems like AMD doesn't work on Windows. It is written in their readme.md
