### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by AlexJJJChen** [oobabooga/text-generation-webui#276]
I don't know why it always showed this error, anyone could help me? thank you so much! 

(textgen) j@ai1:~/llama/text-generation-webui$ python server.py --model LLaMA-7B --load-in-8bit --no-stream
Loading LLaMA-7B...
Traceback (most recent call last):
  File "/home/jianc/llama/text-generation-webui/server.py", line 194, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/jianc/llama/text-generation-webui/modules/models.py", line 123, in load_model
    model = eval(command)
  File "<string>", line 1, in <module>
  File "/home/jianc/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "/home/jianc/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2405, in from_pretrained
    resolved_archive_file, sharded_metadata = get_checkpoint_shard_files(
  File "/home/jianc/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/utils/hub.py", line 902, in get_checkpoint_shard_files
    index = json.loads(f.read())
  File "/home/jianc/anaconda3/envs/textgen/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/jianc/anaconda3/envs/textgen/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/jianc/anaconda3/envs/textgen/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by racecn** [comment]
I have this issue as well!

**Comment by racecn** [comment]
> I have this issue as well!

I found that this comes from a corrupted JSON file during downloading, if you redownload from HF it works just fine.

**Comment by suntekcorps** [comment]
still error

**Comment by suntekcorps** [comment]
![222AB](https://user-images.githubusercontent.com/127466537/233577217-7e53c983-368e-4ba4-8d74-00bd7f9acc83.png)

**Comment by hjiang2020** [comment]
Still error!
![222AB](https://user-images.githubusercontent.com/57387115/233577470-834902be-e4d2-4b15-a4ed-c252cee46994.png)

**Comment by hjiang2020** [comment]
> This issue has been closed due to inactivity for 30 days. If you believe it is still relevant, please leave a comment below.

yes, still error.
