### ISSUE TITLE
oobabooga - no longer loads any model

### ISSUE THREAD

**Issue by Webslug** [oobabooga/text-generation-webui#2779]
### Describe the bug

![image](https://github.com/oobabooga/text-generation-webui/assets/7551638/2dcf30dc-44f1-489d-80fd-e97d30a1cb31)

I'm not sure what has happened but oobabooga now no longer loads any model for me what so ever.  I have set it to AutoGPT and this model has been working for me for many months now.

I think the latest version of oobabooga has broken something since others are reporting this same problem too.  I know for a fact that this model works.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Tried 3 different models.  The terminal opens and then waits a while and just says press any key

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/7551638/a02a5426-7788-44bd-8b4a-b4fd218ee63c)

### Logs

```shell
![image](https://github.com/oobabooga/text-generation-webui/assets/7551638/a02a5426-7788-44bd-8b4a-b4fd218ee63c)
```

### System Info

```shell
Intel I7 6700
16GB DDR RAM
GTX 3060 (12GB RAM)
```

**Comment by bombel28** [comment]
In my case, after updating. I had more detailled errors. For me worked this one:
change line 14 in modules/training.py: 
from peft import (LoraConfig, get_peft_model, prepare_model_for_int8_training,

why? in __init__py (installer_files/env/Lib/site-packages/peft) there is no entry for prepare_model_for_kbit_training

**Comment by FartyPants** [comment]
The issue is not with prepare_model_for_kbit_training, it's that you are running old PEFT which has also other issues

run cmd_windows.bat to start in the correct env
pip uninstall peft
pip install git+https://github.com/huggingface/peft

**Comment by KLXYinc** [comment]
> The issue is not with prepare_model_for_kbit_training, it's that you are running old PEFT which has also other issues
> 
> run cmd_windows.bat to start in the correct env pip uninstall peft pip install git+https://github.com/huggingface/peft

i have reinstalled peft but its the same. it crashes.. and all my models that worked dosent load

**Comment by ArkyonVeil** [comment]
Can confirm that this bug is occurring to me as well. Previously able to run 30B models no problem, now I no longer can. Same message as OP.
(Special note: I got a traceback once claiming not enough memory, which is untrue. However, subsequent tries hold no traceback so no screenshot) 

My machine has 48 GB of RAM, and 24 GB of VRAM. Plenty for handling these models.

**Comment by KLXYinc** [comment]
> Can confirm that this bug is occurring to me as well. Previously able to run 30B models no problem, now I no longer can. Same message as OP. (Special note: I got a traceback once claiming not enough memory (something like 40 GB of bytes I believe), which is untrue. However, subsequent tries hold no traceback so no screenshot)
> 
> My machine has 48 GB of RAM, and 24 GB of VRAM. Plenty for handling these models under 4 byte quantization.

have you changed the size of the virtual memory in windows?

**Comment by ArkyonVeil** [comment]
> > Can confirm that this bug is occurring to me as well. Previously able to run 30B models no problem, now I no longer can. Same message as OP. (Special note: I got a traceback once claiming not enough memory (something like 40 GB of bytes I believe), which is untrue. However, subsequent tries hold no traceback so no screenshot)
> > My machine has 48 GB of RAM, and 24 GB of VRAM. Plenty for handling these models under 4 byte quantization.
> 
> have you changed the size of the virtual memory in windows?

It's at 100 GB.

**Comment by KLXYinc** [comment]
> > > Can confirm that this bug is occurring to me as well. Previously able to run 30B models no problem, now I no longer can. Same message as OP. (Special note: I got a traceback once claiming not enough memory (something like 40 GB of bytes I believe), which is untrue. However, subsequent tries hold no traceback so no screenshot)
> > > My machine has 48 GB of RAM, and 24 GB of VRAM. Plenty for handling these models under 4 byte quantization.
> > 
> > 
> > have you changed the size of the virtual memory in windows?
> 
> It's at 100 GB.

try it with system controlled option for your system drive. it worked for me and all models now load.

**Comment by KLXYinc** [comment]
> > try it with system controlled option for your system drive. it worked for me and all models now load.
> 
> Nope. Going to try reinstalling, maybe the installer lost its marbles somewhere along the way.

i dont think this will help. i tried reinstalling it was the same. only chaning the settings for virtual memory helped

**Comment by ArkyonVeil** [comment]
> i dont think this will help. i tried reinstalling it was the same. only chaning the settings for virtual memory helped

You're right, it did not help. But it did get me a traceback!

```
2023-06-22 15:39:20 INFO:Loading TheBloke_WizardLM-30B-GPTQ...
2023-06-22 15:39:20 WARNING:More than one .safetensors model has been found. The last one will be selected. It could be wrong.
2023-06-22 15:39:20 INFO:The AutoGPTQ params are: {'model_basename': 'wizardlm-30b-GPTQ-4bit.act.order', 'device': 'cuda:0', 'use_triton': False, 'inject_fused_attention': True, 'inject_fused_mlp': True, 'use_safetensors': True, 'trust_remote_code': False, 'max_memory': None, 'quantize_config': None}
2023-06-22 15:39:28 WARNING:The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
2023-06-22 15:39:30 WARNING:The safetensors archive passed at models\TheBloke_WizardLM-30B-GPTQ\wizardlm-30b-GPTQ-4bit.act.order.safetensors does not contain metadata. Make sure to save your model with the `save_pretrained` method. Defaulting to 'pt' metadata.
2023-06-22 15:39:32 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "C:\Users\kendo\Documents\AITools\OobaboogaT2\text-generation-webui\server.py", line 62, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "C:\Users\kendo\Documents\AITools\OobaboogaT2\text-generation-webui\modules\models.py", line 66, in load_model
    output = load_func_map[loader](model_name)
  File "C:\Users\kendo\Documents\AITools\OobaboogaT2\text-generation-webui\modules\models.py", line 272, in AutoGPTQ_loader
    return modules.AutoGPTQ_loader.load_quantized(model_name)
  File "C:\Users\kendo\Documents\AITools\OobaboogaT2\text-generation-webui\modules\AutoGPTQ_loader.py", line 55, in load_quantized
    model = AutoGPTQForCausalLM.from_quantized(path_to_model, **params)
  File "C:\Users\kendo\Documents\AITools\OobaboogaT2\installer_files\env\lib\site-packages\auto_gptq\modeling\auto.py", line 82, in from_quantized
    return quant_func(
  File "C:\Users\kendo\Documents\AITools\OobaboogaT2\installer_files\env\lib\site-packages\auto_gptq\modeling\_base.py", line 773, in from_quantized
    accelerate.utils.modeling.load_checkpoint_in_model(
  File "C:\Users\kendo\Documents\AITools\OobaboogaT2\installer_files\env\lib\site-packages\accelerate\utils\modeling.py", line 1094, in load_checkpoint_in_model
    checkpoint = load_state_dict(checkpoint_file, device_map=device_map)
  File "C:\Users\kendo\Documents\AITools\OobaboogaT2\installer_files\env\lib\site-packages\accelerate\utils\modeling.py", line 946, in load_state_dict
    return safe_load_file(checkpoint_file, device=list(device_map.values())[0])
  File "C:\Users\kendo\Documents\AITools\OobaboogaT2\installer_files\env\lib\site-packages\safetensors\torch.py", line 261, in load_file
    result[k] = f.get_tensor(k)
RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 425997312 bytes.
```

**Comment by ArkyonVeil** [comment]
So after turning half my SSD into page file. I did get them to load.
200 GB ought to do it.

(This is ridiculous)

**Comment by LiamJSP** [comment]
This may have something to do with all of the new loaders that have been added in the last month or so - some may require more working memory during load than others. Try running with this CLI flag in webui.py:

--loader gptq-for-llama

Note that will only work for llama models.
