### ISSUE TITLE
Can't launch after latest pull

### ISSUE THREAD

**Issue by Slug-Cat** [oobabooga/text-generation-webui#2787]
### Describe the bug

Previously working install no longer starts after pulling recent changes. Gives the following error and exits:
```Starting the web UI...
bin E:\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
Traceback (most recent call last):
  File "E:\oobabooga\text-generation-webui\server.py", line 35, in <module>
    from modules import chat, loaders, presets, shared, training, ui, utils
  File "E:\oobabooga\text-generation-webui\modules\training.py", line 14, in <module>
    from peft import (LoraConfig, get_peft_model, prepare_model_for_kbit_training,
ImportError: cannot import name 'prepare_model_for_kbit_training' from 'peft' (E:\oobabooga\installer_files\env\lib\site-packages\peft\__init__.py)
Press any key to continue . . .
```
Here is my start-webui.bat, which was working previously:
```
@echo off

@echo Starting the web UI...

cd /D "%~dp0"

set MAMBA_ROOT_PREFIX=%cd%\installer_files\mamba
set INSTALL_ENV_DIR=%cd%\installer_files\env

if not exist "%MAMBA_ROOT_PREFIX%\condabin\micromamba.bat" (
  call "%MAMBA_ROOT_PREFIX%\micromamba.exe" shell hook >nul 2>&1
)
call "%MAMBA_ROOT_PREFIX%\condabin\micromamba.bat" activate "%INSTALL_ENV_DIR%" || ( echo MicroMamba hook not found. && goto end )
cd text-generation-webui

call python server.py --chat --trust-remote-code --n-gpu-layers 28 --gpu-memory 8
:end
pause
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Git pull, and attempt to start program

### Logs

```shell
Starting the web UI...
bin E:\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
Traceback (most recent call last):
  File "E:\oobabooga\text-generation-webui\server.py", line 35, in <module>
    from modules import chat, loaders, presets, shared, training, ui, utils
  File "E:\oobabooga\text-generation-webui\modules\training.py", line 14, in <module>
    from peft import (LoraConfig, get_peft_model, prepare_model_for_kbit_training,
ImportError: cannot import name 'prepare_model_for_kbit_training' from 'peft' (E:\oobabooga\installer_files\env\lib\site-packages\peft\__init__.py)
Press any key to continue . . .
```

### System Info

```shell
OS: Windows 10
CPU: i7 9700k
GPU: RTX 3060 12GB
```

**Comment by practicaldreamer** [comment]
Same error here... why did you mark as completed?

**Comment by practicaldreamer** [comment]
Found solution here. Uninstall peft and reinstall with command here: https://github.com/oobabooga/text-generation-webui/issues/2773#issuecomment-1598355327
