### ISSUE TITLE
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack

### ISSUE THREAD

**Issue by mykeehu** [oobabooga/text-generation-webui#2795]
### Describe the bug

I have updated my webui, and now I get this message for my previously working model:
```
Traceback (most recent call last):
  File "J:\oobabooga_windows\text-generation-webui\server.py", line 1007, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "J:\oobabooga_windows\text-generation-webui\modules\models.py", line 65, in load_model
    output = load_func_map[loader](model_name)
  File "J:\oobabooga_windows\text-generation-webui\modules\models.py", line 197, in huggingface_loader
    model = LoaderClass.from_pretrained(checkpoint, **params)
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 484, in from_pretrained
    return model_class.from_pretrained(
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2449, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory I:\Textmodels\TheBloke_chronos-wizardlm-uc-scot-st-13B-GPTQ.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I just updated the webu and it gives an error

### Logs

```shell
bin J:\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
2023-06-21 16:16:49 INFO:Loading settings from J:\oobabooga_windows\mysettings.yaml...
2023-06-21 16:16:49 INFO:Loading TheBloke_chronos-wizardlm-uc-scot-st-13B-GPTQ...
Traceback (most recent call last):
  File "J:\oobabooga_windows\text-generation-webui\server.py", line 1007, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "J:\oobabooga_windows\text-generation-webui\modules\models.py", line 65, in load_model
    output = load_func_map[loader](model_name)
  File "J:\oobabooga_windows\text-generation-webui\modules\models.py", line 197, in huggingface_loader
    model = LoaderClass.from_pretrained(checkpoint, **params)
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 484, in from_pretrained
    return model_class.from_pretrained(
  File "J:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2449, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory I:\Textmodels\TheBloke_chronos-wizardlm-uc-scot-st-13B-GPTQ.
Press any key to continue . . .
```

### System Info

```shell
RTX 3060 12 GB
Windows 10 64-bit
i9-13900K
64 GB RAM
```

**Comment by mykeehu** [comment]
It seems the old config-user.yaml files should be improved for compatibility. Because the old parameters are on the left and the new ones on the right. The old one did not load the model giving the above error. After renaming the config-user.yaml file, it started up interestingly. 
Here are the differences:

![image](https://github.com/oobabooga/text-generation-webui/assets/6390413/243a8978-3c9e-4d8a-a0ef-747fcff513b9)
