### ISSUE TITLE
tokenizers>=0.13.3 is required for a normal functioning of this module, but found tokenizers==0.13.2.

### ISSUE THREAD

**Issue by YakuzaSuske** [oobabooga/text-generation-webui#2805]
### Describe the bug

When loading a model in the newest commit and generating, i get a `tokenizers>=0.13.3 is required for a normal functioning of this module, but found tokenizers==0.13.2.` 
![image](https://github.com/oobabooga/text-generation-webui/assets/63294141/42712a31-8d00-4c8b-aac3-0879a8435bbe)
How do i update it?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Open Web-UI
2. Load Model
3. Press Generate
4. Error

### Logs

```shell
Starting the web UI...
bin D:\OOBABOOGA\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
2023-06-21 19:19:45 INFO:Loading the extension "gallery"...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
2023-06-21 19:19:54 INFO:Loading TheBloke_vicuna-13b-v1.3-GPTQ...
2023-06-21 19:19:54 INFO:Found the following quantized model: models\TheBloke_vicuna-13b-v1.3-GPTQ\vicuna-13b-v1.3-GPTQ-4bit-128g.no-act.order.safetensors
2023-06-21 19:20:04 INFO:Loaded the model in 10.00 seconds.

Traceback (most recent call last):
  File "D:\OOBABOOGA\installer_files\env\lib\site-packages\transformers\utils\import_utils.py", line 1086, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "D:\OOBABOOGA\installer_files\env\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\OOBABOOGA\installer_files\env\lib\site-packages\transformers\models\llama\tokenization_llama_fast.py", line 26, in <module>
    require_version("tokenizers>=0.13.3")
  File "D:\OOBABOOGA\installer_files\env\lib\site-packages\transformers\utils\versions.py", line 117, in require_version    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "D:\OOBABOOGA\installer_files\env\lib\site-packages\transformers\utils\versions.py", line 50, in _compare_versions
    raise ImportError(
ImportError: tokenizers>=0.13.3 is required for a normal functioning of this module, but found tokenizers==0.13.2.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\OOBABOOGA\text-generation-webui\modules\text_generation.py", line 269, in generate_reply_HF
    yield get_reply_from_output_ids(output, input_ids, original_question, state, is_chat=is_chat)
  File "D:\OOBABOOGA\text-generation-webui\modules\text_generation.py", line 108, in get_reply_from_output_ids
    if type(shared.tokenizer) in [transformers.LlamaTokenizer, transformers.LlamaTokenizerFast] and len(output_ids) > 0:  File "D:\OOBABOOGA\installer_files\env\lib\site-packages\transformers\utils\import_utils.py", line 1077, in __getattr__
    value = getattr(module, name)
  File "D:\OOBABOOGA\installer_files\env\lib\site-packages\transformers\utils\import_utils.py", line 1076, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\OOBABOOGA\installer_files\env\lib\site-packages\transformers\utils\import_utils.py", line 1088, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.llama.tokenization_llama_fast because of the following error (look up to see its traceback):
tokenizers>=0.13.3 is required for a normal functioning of this module, but found tokenizers==0.13.2.
Output generated in 2.81 seconds (0.36 tokens/s, 1 tokens, context 43, seed 469366423)
```

### System Info

```shell
Windows 10
RTX 3080Ti
```

**Comment by FartyPants** [comment]
were transformers version bumped up? then the tokenizers would need to be bumped too...

**Comment by mcmonkey4eva** [comment]
Pip was really unwilling to install the update for me.
I had to:
`pip uninstall tokenizers` multiple times, then
`pip cache remove \*`
_then_ `pip install tokenizers==0.13.3`
and _then_ it was willing to work
