### ISSUE TITLE
Tensors must have same number of dimensions: got 3 and 4

### ISSUE THREAD

**Issue by s1530129650** [oobabooga/text-generation-webui#282]
Following the [wiki](https://github.com/oobabooga/text-generation-webui/wiki/LLaMA-model) to config the env and run the code 
```
CUDA_VISIBLE_DEVICES=1 python server.py --share --listen --model llama-7b
```
![image](https://user-images.githubusercontent.com/34572118/224661070-d688fe98-d929-49d1-8189-10b0d7e5f3ca.png)

**Comment by janmaltel** [comment]
Just ran into the exact same issue using the same setup that did work yesterday.

**Comment by janmaltel** [comment]
Seems to be an issue with a new commit on zphang's transformers PR: https://github.com/huggingface/transformers/pull/21955#issuecomment-1465821265

**Comment by minlik** [comment]
> I have temp fixed it by updating my `requirements.txt` with zphang's transformers branch up to this commit: `68d640f7c368bcaaaecfc678f11908ebbd3d6176`. So do the following:
> 
> 1. `pip uninstall transformers`
> 2. Update the last line of `requirements.txt` so it looks as follows: `git+https://github.com/zphang/transformers.git@68d640f7c368bcaaaecfc678f11908ebbd3d6176`
> 3. `pip install -r requirements.txt`
> 
> Works fine now.

After updating transformers, i got the following log and the model generated nothing. Is it related to this issue?
`Output generated in 0.25 seconds (0.00 tokens/s, 0 tokens)`

**Comment by s1530129650** [comment]
> > I have temp fixed it by updating my `requirements.txt` with zphang's transformers branch up to this commit: `68d640f7c368bcaaaecfc678f11908ebbd3d6176`. So do the following:
> > 
> > 1. `pip uninstall transformers`
> > 2. Update the last line of `requirements.txt` so it looks as follows: `git+https://github.com/zphang/transformers.git@68d640f7c368bcaaaecfc678f11908ebbd3d6176`
> > 3. `pip install -r requirements.txt`
> > 
> > Works fine now.
> 
> After updating transformers, i got the following log and the model generated nothing. Is it related to this issue? `Output generated in 0.25 seconds (0.00 tokens/s, 0 tokens)`

I ask it to "generate a quick sort code in python"
The terminal outputs:
```
Output generated in 19.47 seconds (10.22 tokens/s, 199 tokens)
Output generated in 18.69 seconds (10.65 tokens/s, 199 tokens)
Output generated in 14.55 seconds (6.25 tokens/s, 91 tokens)
Output generated in 2.09 seconds (9.11 tokens/s, 19 tokens)
Output generated in 12.20 seconds (10.73 tokens/s, 131 tokens)

```

![image](https://user-images.githubusercontent.com/34572118/224677958-6b652740-9341-4405-8bf2-8eb69bf3e5cd.png)

**Comment by minlik** [comment]
> > > I have temp fixed it by updating my `requirements.txt` with zphang's transformers branch up to this commit: `68d640f7c368bcaaaecfc678f11908ebbd3d6176`. So do the following:
> > > 
> > > 1. `pip uninstall transformers`
> > > 2. Update the last line of `requirements.txt` so it looks as follows: `git+https://github.com/zphang/transformers.git@68d640f7c368bcaaaecfc678f11908ebbd3d6176`
> > > 3. `pip install -r requirements.txt`
> > > 
> > > Works fine now.
> > 
> > 
> > After updating transformers, i got the following log and the model generated nothing. Is it related to this issue? `Output generated in 0.25 seconds (0.00 tokens/s, 0 tokens)`
> 
> I ask it to "generate a quick sort code in python" The terminal outputs:
> 
> ```
> Output generated in 19.47 seconds (10.22 tokens/s, 199 tokens)
> Output generated in 18.69 seconds (10.65 tokens/s, 199 tokens)
> Output generated in 14.55 seconds (6.25 tokens/s, 91 tokens)
> Output generated in 2.09 seconds (9.11 tokens/s, 19 tokens)
> Output generated in 12.20 seconds (10.73 tokens/s, 131 tokens)
> ```
> 
> ![image](https://user-images.githubusercontent.com/34572118/224677958-6b652740-9341-4405-8bf2-8eb69bf3e5cd.png)

 I re-install transformers and everything goes right. Thanks.

**Comment by enn-nafnlaus** [comment]
Sadly not fixed for me.  :(

user@host text-generation-webui]$ git pull https://github.com/oobabooga/text-generation-webui.git
remote: Enumerating objects: 85, done.
remote: Counting objects: 100% (85/85), done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 85 (delta 39), reused 5 (delta 1), pack-reused 0
Unpacking objects: 100% (85/85), 16.08 KiB | 28.00 KiB/s, done.
From https://github.com/oobabooga/text-generation-webui
 * branch            HEAD       -> FETCH_HEAD
Updating 7ab45fb..79e519c
Fast-forward
 .github/ISSUE_TEMPLATE/bug_report_template.yml | 53 +++++++++++++++++++++++++++++++++++++++++++++++++++++
 .github/ISSUE_TEMPLATE/feature_request.md      | 16 ++++++++++++++++
 .github/workflows/stale.yml                    | 22 ++++++++++++++++++++++
 3 files changed, 91 insertions(+)
 create mode 100644 .github/ISSUE_TEMPLATE/bug_report_template.yml
 create mode 100644 .github/ISSUE_TEMPLATE/feature_request.md
 create mode 100644 .github/workflows/stale.yml
[user@host text-generation-webui]$ python server.py --verbose --gpu-memory 5 5 --model llama-7b-hf --listen --load-in-4bit --cai-chat
Loading settings from settings.json...
Loading the extension "gallery"... Ok.
Loading llama-7b-hf...
Loading model ...
Done.
Loaded the model in 5.66 seconds.
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.


AI is a digital personal assistant. It is always helpful, honest, patient, nuanced, scientific, introspective, verbose, and writes responses to all inquiries thoroughly and in great detail.
AI: Hello! How many I assist you today?
Karen: Hi!
AI:
--------------------

Exception in thread Thread-3 (gentask):
Traceback (most recent call last):
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/path/to/my/text-generation-webui/modules/callbacks.py", line 64, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/path/to/my/text-generation-webui/modules/text_generation.py", line 191, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/usr/local/lib64/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/my/homedir/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 1452, in generate
    return self.sample(
  File "/my/homedir/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 2468, in sample
    outputs = self(
  File "/usr/local/lib64/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/my/homedir/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/my/homedir/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 772, in forward
    outputs = self.model(
  File "/usr/local/lib64/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/my/homedir/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/my/homedir/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 621, in forward
    layer_outputs = decoder_layer(
  File "/usr/local/lib64/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/my/homedir/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/my/homedir/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 318, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/usr/local/lib64/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/my/homedir/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/my/homedir/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 228, in forward
    query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin, offset=offset)
  File "/my/homedir/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 142, in apply_rotary_pos_emb
    q_embed = (q * cos) + (rotate_half(q) * sin)
  File "/my/homedir/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 136, in rotate_half
    return torch.cat((-x2, x1), dim=-1)
**RuntimeError: Tensors must have same number of dimensions: got 3 and 4**

Same result with:

[user@host text-generation-webui]$ CUDA_VISIBLE_DEVICES=0 python server.py --verbose --model llama-7b-hf --listen --load-in-4bit --cai-chat
