### ISSUE TITLE
GPU not working!

### ISSUE THREAD

**Issue by RickyWang111** [oobabooga/text-generation-webui#2825]
### Describe the bug

I install by One-click installers.   then I run it, just CPU work.GPU no working. how to set? use my GPU to work. thank you!

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Install by One-click installers
2. Open "cmd_windows.bat" ,and cd "text-generation-webui"
3. python server.py
4. Just CPU working, GPU not working.

### Screenshot

(1)
![image](https://github.com/oobabooga/text-generation-webui/assets/96077395/3da04902-ee29-4523-8a9c-d4e9042e452c)

when I Generate my text,Just CPU is working.

(2)
![image](https://github.com/oobabooga/text-generation-webui/assets/96077395/febc95c2-deb1-4697-abe8-62286afcc58b)

### Logs

```shell
NO wrong. just my startup code.

'''
bin F:\__4__code\gc_python\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
2023-06-23 06:23:54 INFO:Loading ggml-model-q4_0.bin...
2023-06-23 06:23:54 INFO:llama.cpp weights detected: models\ggml-model-q4_0.bin

2023-06-23 06:23:54 INFO:Cache capacity is 0 bytes
llama.cpp: loading model from models\ggml-model-q4_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 49954
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.09 MB
llama_model_load_internal: mem required  = 9130.33 MB (+ 1608.00 MB per state)
...................................................................................................
llama_init_from_file: kv self size  = 1600.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
2023-06-23 06:23:54 INFO:Loaded the model in 0.52 seconds.

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

llama_print_timings:        load time =   981.98 ms
llama_print_timings:      sample time =     5.25 ms /   200 runs   (    0.03 ms per token)
llama_print_timings: prompt eval time =   981.86 ms /     4 tokens (  245.47 ms per token)
llama_print_timings:        eval time = 44070.68 ms /   199 runs   (  221.46 ms per token)
llama_print_timings:       total time = 46565.68 ms
Output generated in 46.87 seconds (4.27 tokens/s, 200 tokens, context 3, seed 193566160)
'''
```

### System Info

```shell
window11,
RTX 3060 Laptop 6G,
RTX 3090 24G.
```

**Comment by RickyWang111** [comment]
I can run other Code by my RTX3090 (ChatGLM..) .CPU can work,but it's slow,100% resource utilization.The computer has become sluggish.

**Comment by berkut1** [comment]
https://github.com/oobabooga/text-generation-webui/blob/main/docs/llama.cpp-models.md#gpu-acceleration
And you have to do it every time it stops working, especially after update of llama-cpp-python

**Comment by Rivaidan** [comment]
> https://github.com/oobabooga/text-generation-webui/blob/main/docs/llama.cpp-models.md#gpu-acceleration And you have to do it every time it stops working, especially after update of llama-cpp-python

Everything worked a few days but after updating today llama-cpp just wont use the gpu. when i try to update using the link you gave i get this fun error. any idea where i could go from here? been trying for a few hours with no success.






`(G:\ChatGPT\oobabooga_windows\installer_files\env) G:\ChatGPT\oobabooga_windows>pip uninstall -y llama-cpp-python
Found existing installation: llama-cpp-python 0.1.65
Uninstalling llama-cpp-python-0.1.65:
  Successfully uninstalled llama-cpp-python-0.1.65

(G:\ChatGPT\oobabooga_windows\installer_files\env) G:\ChatGPT\oobabooga_windows>set CMAKE_ARGS="-DLLAMA_CUBLAS=on"

(G:\ChatGPT\oobabooga_windows\installer_files\env) G:\ChatGPT\oobabooga_windows>set FORCE_CMAKE=1

(G:\ChatGPT\oobabooga_windows\installer_files\env) G:\ChatGPT\oobabooga_windows>pip install llama-cpp-python --no-cache-dir
Collecting llama-cpp-python
  Downloading llama_cpp_python-0.1.65.tar.gz (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 24.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.20.0 in g:\chatgpt\oobabooga_windows\installer_files\env\lib\site-packages (from llama-cpp-python) (1.25.0)
Requirement already satisfied: typing-extensions>=4.5.0 in g:\chatgpt\oobabooga_windows\installer_files\env\lib\site-packages (from llama-cpp-python) (4.6.3)
Requirement already satisfied: diskcache>=5.6.1 in g:\chatgpt\oobabooga_windows\installer_files\env\lib\site-packages (from llama-cpp-python) (5.6.1)
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [144 lines of output]


      --------------------------------------------------------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is MSVC 19.35.32217.1
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.35.32215/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is MSVC 19.35.32217.1
      CMake Warning (dev) at G:/ChatGPT/oobabooga_windows/installer_files/pip-build-env-2afdbr9d/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:168 (if):
        Policy CMP0054 is not set: Only interpret if() arguments as variables or
        keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
        details.  Use the cmake_policy command to set the policy and suppress this
        warning.

        Quoted variables like "MSVC" will no longer be dereferenced when the policy
        is set to NEW.  Since the policy is not set the OLD behavior will be used.
      Call Stack (most recent call first):
        CMakeLists.txt:4 (ENABLE_LANGUAGE)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      CMake Warning (dev) at G:/ChatGPT/oobabooga_windows/installer_files/pip-build-env-2afdbr9d/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:189 (elseif):
        Policy CMP0054 is not set: Only interpret if() arguments as variables or
        keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
        details.  Use the cmake_policy command to set the policy and suppress this
        warning.

        Quoted variables like "MSVC" will no longer be dereferenced when the policy
        is set to NEW.  Since the policy is not set the OLD behavior will be used.
      Call Stack (most recent call first):
        CMakeLists.txt:4 (ENABLE_LANGUAGE)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.35.32215/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (1.4s)
      -- Generating done (0.0s)
      -- Build files have been written to: G:/ChatGPT/oobabooga_windows/installer_files/pip-install-jyeoclty/llama-cpp-python_4c89d5b0ffd548f68a515f1c1965c5c0/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          G:\ChatGPT\oobabooga_windows\installer_files\pip-install-jyeoclty\llama-cpp-python_4c89d5b0ffd548f68a515f1c1965c5c0\_skbuild\win-amd64-3.10\cmake-build
        Command:
          'G:\ChatGPT\oobabooga_windows\installer_files\pip-build-env-2afdbr9d\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' 'G:\ChatGPT\oobabooga_windows\installer_files\pip-install-jyeoclty\llama-cpp-python_4c89d5b0ffd548f68a515f1c1965c5c0' -G Ninja '-DCMAKE_MAKE_PROGRAM:FILEPATH=G:\ChatGPT\oobabooga_windows\installer_files\pip-build-env-2afdbr9d\overlay\Lib\site-packages\ninja\data\bin\ninja' -D_SKBUILD_FORCE_MSVC=1930 --no-warn-unused-cli '-DCMAKE_INSTALL_PREFIX:PATH=G:\ChatGPT\oobabooga_windows\installer_files\pip-install-jyeoclty\llama-cpp-python_4c89d5b0ffd548f68a515f1c1965c5c0\_skbuild\win-amd64-3.10\cmake-install' -DPYTHON_VERSION_STRING:STRING=3.10.11 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=G:\ChatGPT\oobabooga_windows\installer_files\pip-build-env-2afdbr9d\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=G:\ChatGPT\oobabooga_windows\installer_files\env\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=G:\ChatGPT\oobabooga_windows\installer_files\env\Include' '-DPYTHON_LIBRARY:PATH=G:\ChatGPT\oobabooga_windows\installer_files\env\libs\python310.lib' '-DPython_EXECUTABLE:PATH=G:\ChatGPT\oobabooga_windows\installer_files\env\python.exe' '-DPython_ROOT_DIR:PATH=G:\ChatGPT\oobabooga_windows\installer_files\env' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_INCLUDE_DIR:PATH=G:\ChatGPT\oobabooga_windows\installer_files\env\Include' '-DPython_LIBRARY:PATH=G:\ChatGPT\oobabooga_windows\installer_files\env\libs\python310.lib' '-DPython3_EXECUTABLE:PATH=G:\ChatGPT\oobabooga_windows\installer_files\env\python.exe' '-DPython3_ROOT_DIR:PATH=G:\ChatGPT\oobabooga_windows\installer_files\env' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_INCLUDE_DIR:PATH=G:\ChatGPT\oobabooga_windows\installer_files\env\Include' '-DPython3_LIBRARY:PATH=G:\ChatGPT\oobabooga_windows\installer_files\env\libs\python310.lib' '-DCMAKE_MAKE_PROGRAM:FILEPATH=G:\ChatGPT\oobabooga_windows\installer_files\pip-build-env-2afdbr9d\overlay\Lib\site-packages\ninja\data\bin\ninja' '"-DLLAMA_CUBLAS=on"' -DCMAKE_BUILD_TYPE:STRING=Release -DLLAMA_CUBLAS=on

      Not searching for unused variables given on the command line.
      CMake Warning:
        Ignoring extra path from command line:

         ""-DLLAMA_CUBLAS=on""


      -- The C compiler identification is MSVC 19.35.32217.1
      -- The CXX compiler identification is MSVC 19.35.32217.1
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.35.32215/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.35.32215/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found Git: G:/ChatGPT/oobabooga_windows/installer_files/env/Library/bin/git.exe (found version "2.34.1.windows.1")
      fatal: not a git repository (or any of the parent directories): .git
      fatal: not a git repository (or any of the parent directories): .git
      CMake Warning at vendor/llama.cpp/CMakeLists.txt:113 (message):
        Git repository not found; to enable automatic generation of build info,
        make sure Git is installed and the project is a Git repository.


      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Looking for pthread_create in pthreads
      -- Looking for pthread_create in pthreads - not found
      -- Looking for pthread_create in pthread
      -- Looking for pthread_create in pthread - not found
      -- Found Threads: TRUE
      -- Found CUDAToolkit: G:/ChatGPT/oobabooga_windows/installer_files/env/include (found version "11.7.64")
      -- cuBLAS found
      -- The CUDA compiler identification is NVIDIA 11.7.64
      -- Detecting CUDA compiler ABI info
      -- Detecting CUDA compiler ABI info - done
      -- Check for working CUDA compiler: G:/ChatGPT/oobabooga_windows/installer_files/env/bin/nvcc.exe - skipped
      -- Detecting CUDA compile features
      -- Detecting CUDA compile features - done
      -- CMAKE_SYSTEM_PROCESSOR: AMD64
      -- x86 detected
      -- GGML CUDA sources found, configuring CUDA architecture
      -- Configuring done (8.3s)
      -- Generating done (0.0s)
      -- Build files have been written to: G:/ChatGPT/oobabooga_windows/installer_files/pip-install-jyeoclty/llama-cpp-python_4c89d5b0ffd548f68a515f1c1965c5c0/_skbuild/win-amd64-3.10/cmake-build
      [1/8] Building CUDA object vendor\llama.cpp\CMakeFiles\ggml.dir\ggml-cuda.cu.obj
      FAILED: vendor/llama.cpp/CMakeFiles/ggml.dir/ggml-cuda.cu.obj
      G:\ChatGPT\oobabooga_windows\installer_files\env\bin\nvcc.exe -forward-unknown-to-host-compiler -DGGML_CUDA_DMMV_X=32 -DGGML_CUDA_DMMV_Y=1 -DGGML_USE_CUBLAS -DGGML_USE_K_QUANTS -DK_QUANTS_PER_ITERATION=2 -D_CRT_SECURE_NO_WARNINGS -IG:\ChatGPT\oobabooga_windows\installer_files\pip-install-jyeoclty\llama-cpp-python_4c89d5b0ffd548f68a515f1c1965c5c0\vendor\llama.cpp\. -isystem G:\ChatGPT\oobabooga_windows\installer_files\env\include -D_WINDOWS -Xcompiler=" /EHsc" -Xcompiler="-O2 -Ob2" -DNDEBUG -arch=native -Xcompiler=-MD -MD -MT vendor\llama.cpp\CMakeFiles\ggml.dir\ggml-cuda.cu.obj -MF vendor\llama.cpp\CMakeFiles\ggml.dir\ggml-cuda.cu.obj.d -x cu -c G:\ChatGPT\oobabooga_windows\installer_files\pip-install-jyeoclty\llama-cpp-python_4c89d5b0ffd548f68a515f1c1965c5c0\vendor\llama.cpp\ggml-cuda.cu -o vendor\llama.cpp\CMakeFiles\ggml.dir\ggml-cuda.cu.obj -Xcompiler=-Fdvendor\llama.cpp\CMakeFiles\ggml.dir\,-FS
      nvcc fatal   : Unsupported gpu architecture 'compute_89'

      [2/8] Building C object vendor\llama.cpp\CMakeFiles\ggml.dir\k_quants.c.obj
      [3/8] Building C object vendor\llama.cpp\CMakeFiles\ggml.dir\ggml.c.obj
      C:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um\winbase.h(9531): warning C5105: macro expansion producing 'defined' has undefined behavior
      [4/8] Building CXX object vendor\llama.cpp\CMakeFiles\llama.dir\llama.cpp.obj
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "G:\ChatGPT\oobabooga_windows\installer_files\pip-build-env-2afdbr9d\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 674, in setup
          cmkr.make(make_args, install_target=cmake_install_target, env=env)
        File "G:\ChatGPT\oobabooga_windows\installer_files\pip-build-env-2afdbr9d\overlay\Lib\site-packages\skbuild\cmaker.py", line 697, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
        File "G:\ChatGPT\oobabooga_windows\installer_files\pip-build-env-2afdbr9d\overlay\Lib\site-packages\skbuild\cmaker.py", line 742, in make_impl
          raise SKBuildError(msg)

      An error occurred while building with CMake.
        Command:
          'G:\ChatGPT\oobabooga_windows\installer_files\pip-build-env-2afdbr9d\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' --build . --target install --config Release --
        Install target:
          install
        Source directory:
          G:\ChatGPT\oobabooga_windows\installer_files\pip-install-jyeoclty\llama-cpp-python_4c89d5b0ffd548f68a515f1c1965c5c0
        Working directory:
          G:\ChatGPT\oobabooga_windows\installer_files\pip-install-jyeoclty\llama-cpp-python_4c89d5b0ffd548f68a515f1c1965c5c0\_skbuild\win-amd64-3.10\cmake-build
      Please check the install target is valid and see CMake's output for more information.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

(G:\ChatGPT\oobabooga_windows\installer_files\env) G:\ChatGPT\oobabooga_windows>`

**Comment by berkut1** [comment]
@Rivaidan that build parameters only for CUDA GPUs, Your GPU doesn't support that.

**Comment by RickyWang111** [comment]
@Rivaidan  use this code to install:`pip install llama-cpp-python==0.1.63 --force-reinstall --upgrade --no-cache-dir --verbose`

**Comment by RickyWang111** [comment]
I still have this problem....  GPU not working.

I generate the text now,just CPU  working.

![image](https://github.com/oobabooga/text-generation-webui/assets/96077395/7579a9a2-9c9f-4c6b-b311-6e1def9007d0)


> https://github.com/oobabooga/text-generation-webui/blob/main/docs/llama.cpp-models.md#gpu-acceleration And you have to do it every time it stops working, especially after update of llama-cpp-python

**Comment by RickyWang111** [comment]
> @Rivaidan that build parameters only for CUDA GPUs, Your GPU doesn't support that.
> 
> UPD: You should read https://pypi.org/project/llama-cpp-python/ and find parameters for your GPU (I guess you have AMD)

Thank you ! I can run it by my GPU now! I forget set --n-gpu-layers 200000 . sorry.

![image](https://github.com/oobabooga/text-generation-webui/assets/96077395/883167eb-d698-4519-9579-9e3e437f66d1)

**Comment by Rivaidan** [comment]
> @Rivaidan that build parameters only for CUDA GPUs, Your GPU doesn't support that.
> 
> UPD: You should read https://pypi.org/project/llama-cpp-python/ and find parameters for your GPU (I guess you have AMD)

Thank you for the help, but i run an RTX 4090 so i assure you my gpu is compatible. I ended up solving my issue so again, thank you for your time and help.

**Comment by Rivaidan** [comment]
> @Rivaidan use this code to install:`pip install llama-cpp-python==0.1.63 --force-reinstall --upgrade --no-cache-dir --verbose`

Thank you so much for your help. that command started me down a rabbit hole that ended up solving my problem so now all is well again, Again, thank you so much for taking the time to help me.

**Comment by berkut1** [comment]
>hank you for the help, but i run an RTX 4090 

@Rivaidan that is weird, cause your log said that it incompatible with your software. I recommend to create an issue in the llama-cpp-python repo.

**Comment by RickyWang111** [comment]
@Rivaidan 

您能看看这个BUG么，无法进行lora训练，我查询了issue，和他们有同样的问题
[#2682 ](https://github.com/oobabooga/text-generation-webui/issues/2682l)
[#2700 ](https://github.com/oobabooga/text-generation-webui/issues/2700)
`AttributeError: 'LlamaCppModel' object has no attribute 'decode'`

**Comment by sumersm7** [comment]
> https://github.com/oobabooga/text-generation-webui/blob/main/docs/llama.cpp-models.md#gpu-acceleration And you have to do it every time it stops working, especially after update of llama-cpp-python



> @Rivaidan use this code to install:`pip install llama-cpp-python==0.1.63 --force-reinstall --upgrade --no-cache-dir --verbose`


and as conda create its private env

what should i use.

iam with AI and Python

**Comment by Pinkmoth419** [comment]
I'm having the same issue :( I'm not sure what to do, I've got a 4090 and 64gb installed ram (16gb vram, it's a gigabyte laptop) so I don't think the hardware is the problem but idk. I'm very technologically illiterate in this regard.
