### ISSUE TITLE
when i updated today, i can't get in the web-ui

### ISSUE THREAD

**Issue by one-pip** [oobabooga/text-generation-webui#2833]
### Describe the bug

when i updated today, i can't get in the web-ui

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Traceback (most recent call last):
  File "D:\NEW_OOBA\oobabooga\oobabooga_windows\text-generation-webui\server.py", line 35, in <module>
    from modules import chat, loaders, presets, shared, training, ui, utils
  File "D:\NEW_OOBA\oobabooga\oobabooga_windows\text-generation-webui\modules\training.py", line 14, in <module>
    from peft import (LoraConfig, get_peft_model, prepare_model_for_kbit_training,
ImportError: cannot import name 'prepare_model_for_kbit_training' from 'peft' (D:\NEW_OOBA\oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\peft\__init__.py)

### Logs

```shell
Traceback (most recent call last):
  File "D:\NEW_OOBA\oobabooga\oobabooga_windows\text-generation-webui\server.py", line 35, in <module>
    from modules import chat, loaders, presets, shared, training, ui, utils
  File "D:\NEW_OOBA\oobabooga\oobabooga_windows\text-generation-webui\modules\training.py", line 14, in <module>
    from peft import (LoraConfig, get_peft_model, prepare_model_for_kbit_training,
ImportError: cannot import name 'prepare_model_for_kbit_training' from 'peft' (D:\NEW_OOBA\oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\peft\__init__.py)
```

### System Info

```shell
windows 11
NVIDIA 3060 12G
```

**Comment by kelheor** [comment]
Same here.

bin C:\Users\kelhe\anaconda3\envs\textgen\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\text-generation-webui\text-generation-webui\server.py:35 in <module>                          │
│                                                                                                  │
│     32 from PIL import Image                                                                     │
│     33                                                                                           │
│     34 import modules.extensions as extensions_module                                            │
│ ❱   35 from modules import chat, loaders, presets, shared, training, ui, utils                   │
│     36 from modules.extensions import apply_extensions                                           │
│     37 from modules.github import clone_or_pull_repository                                       │
│     38 from modules.html_generator import chat_html_wrapper                                      │
│                                                                                                  │
│ C:\text-generation-webui\text-generation-webui\modules\training.py:14 in <module>                │
│                                                                                                  │
│    11 import torch                                                                               │
│    12 import transformers                                                                        │
│    13 from datasets import Dataset, load_dataset                                                 │
│ ❱  14 from peft import (LoraConfig, get_peft_model, prepare_model_for_kbit_training,             │
│    15 │   │   │   │     set_peft_model_state_dict)                                               │
│    16                                                                                            │
│    17 from modules import shared, ui, utils                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'prepare_model_for_kbit_training' from 'peft'

**Comment by ThatCoffeeGuy** [comment]
Same here. 

ImportError: cannot import name 'prepare_model_for_kbit_training' from 'peft'

**Comment by somenewaccountthen** [comment]
MeToo 
(I had not update in a week or 3)

**Comment by burgerlawful** [comment]
i think uninstalling and reinstalling peft fixes it

**Comment by berkut1** [comment]
Just need to use searching. The problem was resolved, follow the link below, or just redownload the new version of updater.
https://github.com/oobabooga/text-generation-webui/issues/2773

**Comment by somenewaccountthen** [comment]
> You just need to use the search. The problem has been resolved, follow the link below or simply download the new version of the updater (*.bat scripts). #2773
I live in Linux. But i will check out your link it probably has info i can use.
Thank you.

**Comment by berkut1** [comment]
@somenewaccountthen that doesn't fix the problem, it just delays it. You must update the updater script.

**Comment by somenewaccountthen** [comment]
> @somenewaccountthen that doesn't fix the problem, it just delays it. You must update the updater script.

I run of a git clone, in linux. I don't have install scripts i don't think. 
I will remember your remark if it goes wrong. Until then i am not worried :)

**Comment by FartyPants** [comment]
Wherever you are linux, windows or whatnot, peft doesn't update version numbers so pip will not reinstall it. If you are having troubles, find out where peft is installed (venv, conda, etc...) and delete it manually, then just install the latest.,

**Comment by superswan** [comment]
> 

Entering the conda environment on WIndows and reinstall peft also works for me. hopefully it will be fixed in next update

**Comment by marinhero** [comment]
> i think uninstalling and reinstalling peft fixes it

This worked for me.

```
pip uninstall peft
pip install -q -U git+https://github.com/huggingface/peft.git
```

**Comment by zeway-prog** [comment]
Traceback (most recent call last):
  File "C:\oobabooga_windows\text-generation-webui\server.py", line 4, in <module>
    from modules import shared
  File "C:\oobabooga_windows\text-generation-webui\modules\shared.py", line 8, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

I try to install text generation webui but i don't understand how to make it works. I am not a programer. 
Thank you

**Comment by randomtask2000** [comment]
same issue still persists even after reinstalling perf
```
text-generation-webui$ bash start_linux.sh
Traceback (most recent call last):
  File "text-generation-webui/server.py", line 4, in <module>
    from modules import shared
  File "text-generation-webui/modules/shared.py", line 8, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
text-generation-webui$ pip uninstall peft
Found existing installation: peft 0.7.1
Uninstalling peft-0.7.1:
  Would remove:
    /home/.local/lib/python3.10/site-packages/peft-0.7.1.dist-info/*
    /home/.local/lib/python3.10/site-packages/peft/*
Proceed (Y/n)? y
  Successfully uninstalled peft-0.7.1
text-generation-webui$ bash start_linux.sh
Traceback (most recent call last):
  File "text-generation-webui/server.py", line 4, in <module>
    from modules import shared
  File "text-generation-webui/modules/shared.py", line 8, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
text-generation-webui$ pip install -q -U git+https://github.com/huggingface/peft.git
text-generation-webui$ bash start_linux.sh
Traceback (most recent call last):
  File "text-generation-webui/server.py", line 4, in <module>
    from modules import shared
  File "text-generation-webui/modules/shared.py", line 8, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```
