### ISSUE TITLE
Galactica not working after c7aa51f

### ISSUE THREAD

**Issue by CreativeFriday** [oobabooga/text-generation-webui#285]
Hi,
Galactica was working just fine yesterday. After upgrading today I get the error below when submitting a prompt. 

It seems to be caused by: https://github.com/oobabooga/text-generation-webui/commit/c7aa51faa6488f019447c7f2eba26013105281e7   Works fine on the commit just before (17210ff).

I tried a few other models but only had problems with Galactica. 

(I'm running Pop OS and a 3090 card)

```
Loading galactica-6.7b...
Loading checkpoint shards: 100%|██████████████████| 2/2 [00:05<00:00,  2.74s/it]
Loaded the model in 8.61 seconds.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Exception in thread Thread-4 (gentask):
Traceback (most recent call last):
  File "/home/svend/anaconda3/envs/textgen/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/svend/anaconda3/envs/textgen/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/svend/github/text-generation-webui/modules/callbacks.py", line 64, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/home/svend/github/text-generation-webui/modules/text_generation.py", line 187, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/svend/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/svend/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1452, in generate
    return self.sample(
  File "/home/svend/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2421, in sample
    eos_token_id_tensor = torch.tensor(eos_token_id).to(input_ids.device) if eos_token_id is not None else None
RuntimeError: Could not infer dtype of NoneType
```

**Comment by oobabooga** [comment]
Should be fixed now, thanks!

**Comment by CreativeFriday** [comment]
It's me who is thanking!!  Galactica is working again

**Comment by DartPower** [comment]
I think same problem have again but after e18a0460d446f72f015f2fdc6b8b5962574dde98

```
2023-11-05 00:10:21 INFO:Loading facebook_galactica-1.3b...
2023-11-05 00:10:24 INFO:Loaded the model in 2.94 seconds.
Traceback (most recent call last):
  File "C:\Tools\_Neuro\text-generation-webui-main\modules\callbacks.py", line 57, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Tools\_Neuro\text-generation-webui-main\modules\text_generation.py", line 352, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Tools\_Neuro\text-generation-webui-main\installer_files\env\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Tools\_Neuro\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\generation\utils.py", line 1673, in generate
    return self.greedy_search(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Tools\_Neuro\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\generation\utils.py", line 2534, in greedy_search
    next_tokens_scores = logits_processor(input_ids, next_token_logits)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Tools\_Neuro\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\generation\logits_process.py", line 97, in __call__
    scores = processor(input_ids, scores)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Tools\_Neuro\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\generation\logits_process.py", line 1436, in __call__
    scores[:, self.suppress_tokens] = -float("inf")
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Could not infer dtype of NoneType
Output generated in 0.77 seconds (0.00 tokens/s, 0 tokens, context 145, seed 1018175378)
```
