### ISSUE TITLE
OSError: exception: integer divide by zero

### ISSUE THREAD

**Issue by IkariDevGIT** [oobabooga/text-generation-webui#2850]
### Describe the bug

I dont really know how to describe it, i just chat a bit then that error pops up and it crashes.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

i would like to know that too, just chat a bit, then that pops up

### Logs

```shell
Traceback (most recent call last):
  File "D:\oobabooga-windows\new\text-generation-webui\modules\callbacks.py", line 74, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "D:\oobabooga-windows\new\text-generation-webui\modules\llamacpp_model.py", line 88, in generate
    for completion_chunk in completion_chunks:
  File "D:\oobabooga-windows\new\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 855, in _create_completion
    for token in self.generate(
  File "D:\oobabooga-windows\new\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 683, in generate
    self.eval(tokens)
  File "D:\oobabooga-windows\new\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 412, in eval
    return_code = llama_cpp.llama_eval(
  File "D:\oobabooga-windows\new\installer_files\env\lib\site-packages\llama_cpp\llama_cpp.py", line 497, in llama_eval
    return _lib.llama_eval(ctx, tokens, n_tokens, n_past, n_threads)
OSError: exception: integer divide by zero
```

### System Info

```shell
msi geforce rtx 3070
windows 10
```

**Comment by IkariDevGIT** [comment]
i use this btw: https://github.com/oobabooga/text-generation-webui/blob/main/docs/llama.cpp-models.md#windows

**Comment by IkariDevGIT** [comment]
ik, not really related, but i get another error just by chatting:

Traceback (most recent call last):
  File "D:\oobabooga-windows\new\text-generation-webui\modules\callbacks.py", line 74, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "D:\oobabooga-windows\new\text-generation-webui\modules\llamacpp_model.py", line 88, in generate
    for completion_chunk in completion_chunks:
  File "D:\oobabooga-windows\new\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 855, in _create_completion
    for token in self.generate(
  File "D:\oobabooga-windows\new\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 683, in generate
    self.eval(tokens)
  File "D:\oobabooga-windows\new\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 412, in eval
    return_code = llama_cpp.llama_eval(
  File "D:\oobabooga-windows\new\installer_files\env\lib\site-packages\llama_cpp\llama_cpp.py", line 497, in llama_eval
    return _lib.llama_eval(ctx, tokens, n_tokens, n_past, n_threads)
OSError: exception: access violation reading 0x000000000000000C

**Comment by GauravB159** [comment]
Probably a llama.cpp error rather than something to do with the webui. Can you post your chat transcript and which model you're using with which parameters?

**Comment by IkariDevGIT** [comment]
@GauravB159 thanks for the help. You dont wanna see my chatlogs xd, i figured(probably) bot errors out, everytime my ssd hit 0gb free that error came up
