### ISSUE TITLE
No module named ‘auto_gptq’

### ISSUE THREAD

**Issue by UserHIJ** [oobabooga/text-generation-webui#2855]
### Describe the bug

Used the MacOS , M chip install, install went okay. 
Went to download TheBloke/robin-7B-v2-GPTQ, and I'm getting 
Traceback (most recent call last):
  File "/Users/xx/Downloads/oobabooga_macos/text-generation-webui/server.py", line 62, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/Users/xxx/Downloads/oobabooga_macos/text-generation-webui/modules/models.py", line 66, in load_model
    output = load_func_map[loader](model_name)
  File "/Users/xx/Downloads/oobabooga_macos/text-generation-webui/modules/models.py", line 270, in AutoGPTQ_loader
    import modules.AutoGPTQ_loader
  File "/Users/xx/Downloads/oobabooga_macos/text-generation-webui/modules/AutoGPTQ_loader.py", line 3, in <module>
    from auto_gptq import AutoGPTQForCausalLM, BaseQuantizeConfig
ModuleNotFoundError: No module named 'auto_gptq

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I had tried the manual way and have the same problem (same exact message) 

### Screenshot

Stack included 

### Logs

```shell
Stack included
```

### System Info

```shell
MacBook Pro M2 , Ventura .. the rest of the install when okay, but the startup of any of these models just crashes with that module error
```

**Comment by BadisG** [comment]
Did you upgrade the packages on your conda environnement?
```
conda activate textgen 
pip install --upgrade -r requirements.txt
```

**Comment by UserHIJ** [comment]
I ran the start script ...

***@***.***

**Comment by UserHIJ** [comment]
ok  , no change .. looks like same message. 

(base) yyy@de-MacBook-Pro-2 text-generation-webui % conda info --envs                                               
# conda environments:
#
                         /Users/yyy/Downloads/oobabooga_macos/installer_files/conda
                         /Users/yyy/Downloads/oobabooga_macos/installer_files/env
base                  *  /opt/homebrew/Caskroom/miniforge/base
pt122                    /opt/homebrew/Caskroom/miniforge/base/envs/pt122

Running this worked fine 
(base) yyy@Davids-MacBook-Pro-2 text-generation-webui % pip3 install --upgrade -r requirements.txt
Collecting git+https://github.com/huggingface/peft@03eb378eb914fbee709ff7c86ba5b1d033b89524 (from -r requirements.txt (line 19))
  Cloning https://github.com/huggingface/peft (to revision 03eb378eb914fbee709ff7c86ba5b1d033b89524) to /private/var/folders/0j/227lrybj63j5q_p56qb5_28r0000gn/T/pip-req-build-03prh9of
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/peft /private/var/folders/0j/227lrybj63j5q_p56qb5_28r0000gn/T/pip-req-build-03prh9of .....

and help modules did not show auto_gptq 
OpenSSL             argparse            html                resource
PIL                 array               http                rlcompleter
__future__          ast                 httpcore            runpy
_abc                async_timeout       httpx               safetensors
_aix_support        asynchat            huggingface_hub     sched
_ast                asyncio             idlelib             scipy
_asyncio            asyncore            idna                secrets
_bisect             atexit              imaplib             select
_blake2             attr                imghdr              selectors
_bootsubprocess     attrs               imp                 semantic_version
_bz2                audioop             importlib           sentencepiece
_cffi_backend       base64              inspect             server

**Comment by ykandrashou** [comment]
I also have the same problem. Macbook Pro M1.
I also tried building 'auto_gptq' from repo but got the same result at the end.

**Comment by UserHIJ** [comment]
https://www.youtube.com/watch?v=btmVhRuoLkc

**Comment by ipeychev** [comment]
> I also have the same problem. Macbook Pro M1. I also tried building 'auto_gptq' from repo but got the same result at the end.

I have the same configuration, same issue, same attempt to resolve it, and got the same result.

**Comment by mcaubrey** [comment]
Same problem.

**Comment by ykandrashou** [comment]
I tried to check conda env content. It looks like `auto_gptq` is there:
```shell
ls /Users/ykandrashou/miniconda3/envs/textgen/lib/python3.10/site-packages/auto_gptq

__init__.py  __pycache__  eval_tasks   modeling     nn_modules   quantization utils
```

I also googled the way to check if module is installed and it also shows `auto_gptq`:
```shell
python -c 'help("modules")' | grep auto_gptq

_codecs_hk          auto_gptq           itertools           shutil
```

Unfortunately I'm not familiar with python development and I have no idea where to look farther. Any suggestions?

**Comment by bryanburress** [comment]
No doubt! same issue

**Comment by khirasaki** [comment]
I saw a comment from The-Bloke that GPTQ models can't be run on Mac, but only on Windows and Linux. Instead, you have to use a GGML model. https://www.reddit.com/r/LocalLLaMA/comments/13op1sd/comment/jl5ys2s/?utm_source=share&utm_medium=web2x&context=3

Examples:
https://huggingface.co/TheBloke/WizardLM-30B-Uncensored-GGML
https://huggingface.co/TheBloke/WizardLM-30B-Uncensored-GPTQ

**Comment by Patronics** [comment]
> Instead, you have to use a GGML model.

For anyone in the future's reference, as of a few weeks later, it seems that GGML is obsolete and in the process of being replaced by the GGUF model format, which is also likewise supported on MacOS.

**Comment by iakar** [comment]
I read somewhere that you have to run GGUF model on a Mac

**Comment by yoponchik** [comment]
Did everyone manage to get it to work? I am trying to use a GGUF model on my Mac M1 Pro but it's giving me
```ModuleNotFoundError: No module named 'auto_gptq'```
