### ISSUE TITLE
ERROR:Failed to load the model.

### ISSUE THREAD

**Issue by GudBagel** [oobabooga/text-generation-webui#2862]
### Describe the bug

I just installed the webui, got a modell but its refusing to load, idk hhat to do.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I just followed the instructions

### Logs

```shell
Traceback (most recent call last):
  File "A:\Chatbot\oobabooga_windows\text-generation-webui\server.py", line 67, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "A:\Chatbot\oobabooga_windows\text-generation-webui\modules\models.py", line 74, in load_model
    output = load_func_map[loader](model_name)
  File "A:\Chatbot\oobabooga_windows\text-generation-webui\modules\models.py", line 280, in AutoGPTQ_loader
    return modules.AutoGPTQ_loader.load_quantized(model_name)
  File "A:\Chatbot\oobabooga_windows\text-generation-webui\modules\AutoGPTQ_loader.py", line 56, in load_quantized
    model = AutoGPTQForCausalLM.from_quantized(path_to_model, **params)
  File "A:\Chatbot\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\modeling\auto.py", line 82, in from_quantized
    return quant_func(
  File "A:\Chatbot\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\modeling\_base.py", line 717, in from_quantized
    model = AutoModelForCausalLM.from_config(
  File "A:\Chatbot\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 425, in from_config
    return model_class._from_config(config, **kwargs)
  File "A:\Chatbot\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 1143, in _from_config
    model = cls(config, **kwargs)
  File "A:\Chatbot\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 615, in __init__
    self.model = LlamaModel(config)
  File "A:\Chatbot\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 446, in __init__
    self.layers = nn.ModuleList([LlamaDecoderLayer(config) for _ in range(config.num_hidden_layers)])
  File "A:\Chatbot\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 446, in <listcomp>
    self.layers = nn.ModuleList([LlamaDecoderLayer(config) for _ in range(config.num_hidden_layers)])
  File "A:\Chatbot\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 256, in __init__
    self.mlp = LlamaMLP(
  File "A:\Chatbot\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 149, in __init__
    self.gate_proj = nn.Linear(hidden_size, intermediate_size, bias=False)
  File "A:\Chatbot\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\linear.py", line 96, in __init__
    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 141557760 bytes.
```

### System Info

```shell
Windows 11
Gigabyte RTX 3060 12Gb Vram
```

**Comment by jamesbiederbeck** [comment]
Try limiting your gpu memory usage. Did you read the error?

**Comment by EliEron** [comment]
Actually given that the error comes from `DefaultCPUAllocator`, the issue is actually System Memory / RAM, not GPU VRAM.

AutoGPTQ does consume a bit of RAM (especially during the loading of the model) though it's not a large amount. Were you running a ton of other software at the time? If so try closing most other programs before you load the model. Alternatively you can enable / increase the size of your pagefile, which acts as virtual memory. Though that will be far slower than relying on real RAM. 

Also you didn't list the model you were trying to load, if it was a 7b or 13b model then it should load fine on your card, but anything bigger won't fit, even if you resolve the RAM situation.

**Comment by 8skull** [comment]
Increasing the size of pagefile.. `--pre_layer` command?

I'm trying the GPT4 x Alpaca 128 model. With the same error. I'm trying --pre_layer now.-
