### ISSUE TITLE
Can't download chat history after update

### ISSUE THREAD

**Issue by Victoralm** [oobabooga/text-generation-webui#2863]
### Describe the bug

Can't download chat history after update (update_windows.bat)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Update, run model, generate some inputs, try to download the chat history

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/5475429/595c3d05-1d5b-41c0-930d-904b36463c07)

### Logs

```shell
Output generated in 35.13 seconds (0.88 tokens/s, 31 tokens, context 81, seed 162664964)
Traceback (most recent call last):
  File "D:\Projects\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Projects\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\Projects\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Projects\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Projects\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Projects\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\Projects\oobabooga_windows\text-generation-webui\server.py", line 844, in <lambda>
    shared.gradio['download_button'].click(lambda x: chat.save_history(x, timestamp=True, user_request=True), shared.gradio['mode'], shared.gradio['download'])
TypeError: save_history() got an unexpected keyword argument 'user_request'
```

### System Info

```shell
Windows 11
i9 11900k
32Gb ram
Nvidia 1060
```

**Comment by 0-N-3** [comment]
Found the same one earlier today, can't continue my work without it. Thank you for posting. I'm new to Git Hub, a bit scared of posting something.
