### ISSUE TITLE
IndexError: list index out of range, can't work for chatglm2-6b, but work well with chatglm-6b

### ISSUE THREAD

**Issue by whmc76** [oobabooga/text-generation-webui#2866]
### Describe the bug

i have run update_windows.bat before and it is 2023/6/26, already up to date

2023-06-26 00:31:11 INFO:Loading THUDM_chatglm2-6b...
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 7/7 [00:10<00:00,  1.50s/it]
2023-06-26 00:31:25 INFO:Loaded the model in 13.21 seconds.

Traceback (most recent call last):
  File "E:\oobabooga_windows\text-generation-webui\modules\callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "E:\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 289, in generate_with_callback
    shared.model.generate(**kwargs)
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1285, in generate
    eos_token_id = eos_token_id[0]
IndexError: list index out of range
Output generated in 0.24 seconds (0.00 tokens/s, 0 tokens, context 15, seed 2071097085)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

trust-remote-code check,
chatglm2 loaded and start chat something

### Logs

```shell
Traceback (most recent call last):
  File "E:\oobabooga_windows\text-generation-webui\modules\callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "E:\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 289, in generate_with_callback
    shared.model.generate(**kwargs)
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1285, in generate
    eos_token_id = eos_token_id[0]
IndexError: list index out of range
Output generated in 0.24 seconds (0.00 tokens/s, 0 tokens, context 15, seed 2071097085)
```

### System Info

```shell
windows
4090
chatglm2-6b
```

**Comment by coyude** [comment]
I also encountered this problem.🤔

**Comment by Pb-207** [comment]
same problem.

**Comment by elven2016** [comment]
the same too，did you find any solutions？

**Comment by almagest21** [comment]
I have same problem. Could you check this issue?
I'm using this model.
https://huggingface.co/matsuo-lab/weblab-10b-instruction-sft

`Traceback (most recent call last):
  File "D:\llama\webui\text-generation-webui\modules\callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "D:\llama\webui\text-generation-webui\modules\text_generation.py", line 307, in generate_with_callback
    shared.model.generate(**kwargs)
  File "D:\llama\webui\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\llama\webui\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1391, in generate
    eos_token_id = eos_token_id[0]
IndexError: list index out of range
Output generated in 0.47 seconds (0.00 tokens/s, 0 tokens, context 67, seed 736166909)`

**Comment by nneri** [comment]
> I have same problem. Could you check this issue?
> I'm using this model.
> https://huggingface.co/matsuo-lab/weblab-10b-instruction-sft


I ran into the same problem, it seems that for some reason the eos_token_id is not being retrieved.
It is not the correct fix, but I added 0 to the array from line 277 of modules/text_generation.py and it worked.


Original Line:
`eos_token_ids = [shared.tokenizer.eos_token_id] if shared.tokenizer.eos_token_id is not None else []`

Modified Line:
`eos_token_ids = [shared.tokenizer.eos_token_id] if shared.tokenizer.eos_token_id is not None else [0]`

Alternatively, it should work if the eos_token setting is properly added to the _tokenizer_config.json_ or _special_tokens_map.json_.
