### ISSUE TITLE
Support THUDM/chatglm2-6b-int4,THUDM/chatglm2-6b loading?

### ISSUE THREAD

**Issue by win10ogod** [oobabooga/text-generation-webui#2874]
Support THUDM/chatglm2-6b-int4,THUDM/chatglm2-6b loading?

**Comment by elven2016** [comment]
Traceback (most recent call last):
  File "/ssd_data01/text-generation-webui/modules/callbacks.py", line 73, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/ssd_data01/text-generation-webui/modules/text_generation.py", line 263, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/elven/miniconda3/envs/tgweb/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/elven/miniconda3/envs/tgweb/lib/python3.10/site-packages/transformers/generation/utils.py", line 1285, in generate
    eos_token_id = eos_token_id[0]
IndexError: list index out of range 能加载，但是问问题报错

**Comment by elulis** [comment]
I was trying to load THUDM/chatglm2-6b-int4 with Model Loader: Transformers, and got the following Error:
RuntimeError: Only Tensors of floating point and complex dtype can require gradients
but the call stack said requires_grad=False:
[quantization.py] line 314, in init self.weight = Parameter([self.weight.to](device), requires_grad=False)

---Full stack trace---
Traceback (most recent call last): File “C:\data\oobabooga_windows\text-generation-webui\[server.py](http://server.py/)”, line 67, in load_model_wrapper shared.model, shared.tokenizer = load_model(shared.model_name, loader) File “C:\data\oobabooga_windows\text-generation-webui\modules\[models.py](http://models.py/)”, line 74, in load_model output = load_func_map[loader](http://127.0.0.1:7860/model_name) File “C:\data\oobabooga_windows\text-generation-webui\modules\[models.py](http://models.py/)”, line 206, in huggingface_loader model = LoaderClass.from_pretrained(checkpoint, **params) File “C:\data\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py”, line 479, in from_pretrained return model_class.from_pretrained( File “C:\data\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py”, line 2675, in from_pretrained model = cls(config, *model_args, **model_kwargs) File “C:\Users\Eluli/.cache\huggingface\modules\transformers_modules\THUDM_chatglm2-6b-int4\modeling_chatglm.py”, line 775, in init self.quantize(self.config.quantization_bit, empty_init=True) File “C:\Users\Eluli/.cache\huggingface\modules\transformers_modules\THUDM_chatglm2-6b-int4\modeling_chatglm.py”, line 1109, in quantize self.transformer.encoder = quantize(self.transformer.encoder, bits, empty_init=empty_init, device=device, File “C:\Users\Eluli/.cache\huggingface\modules\transformers_modules\THUDM_chatglm2-6b-int4\[quantization.py](http://quantization.py/)”, line 331, in quantize layer.self_attention.query_key_value = QuantizedLinear( File “C:\Users\Eluli/.cache\huggingface\modules\transformers_modules\THUDM_chatglm2-6b-int4\[quantization.py](http://quantization.py/)”, line 314, in init self.weight = Parameter([self.weight.to](http://self.weight.to/)(device), requires_grad=False) File “C:\data\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\[module.py](http://module.py/)”, line 1632, in setattr self.register_parameter(name, value) File “C:\data\oobabooga_windows\installer_files\env\lib\site-packages\accelerate\big_modeling.py”, line 108, in register_empty_parameter module._parameters[name] = param_cls(module._parameters[name].to(device), **kwargs) File “C:\data\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\[parameter.py](http://parameter.py/)”, line 36, in new return torch.Tensor._make_subclass(cls, data, requires_grad) RuntimeError: Only Tensors of floating point and complex dtype can require gradients

**Comment by zark119** [comment]
2023-06-29 20:31:36 INFO:Loading chatglm2-6b-int4...
2023-06-29 20:31:36 INFO:The AutoGPTQ params are: {'model_basename': 'pytorch_model', 'device': 'cuda:0', 'use_triton': False, 'inject_fused_attention': True, 'inject_fused_mlp': True, 'use_safetensors': False, 'trust_remote_code': True, 'max_memory': None, 'quantize_config': BaseQuantizeConfig(bits=4, group_size=-1, damp_percent=0.01, desc_act=False, sym=True, true_sequential=True, model_name_or_path=None, model_file_base_name=None), 'use_cuda_fp16': True}
Traceback (most recent call last):
  File "E:\oobabooga_windows\text-generation-webui\server.py", line 1018, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "E:\oobabooga_windows\text-generation-webui\modules\models.py", line 74, in load_model
    output = load_func_map[loader](model_name)
  File "E:\oobabooga_windows\text-generation-webui\modules\models.py", line 280, in AutoGPTQ_loader
    return modules.AutoGPTQ_loader.load_quantized(model_name)
  File "E:\oobabooga_windows\text-generation-webui\modules\AutoGPTQ_loader.py", line 56, in load_quantized
    model = AutoGPTQForCausalLM.from_quantized(path_to_model, **params)
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\modeling\auto.py", line 79, in from_quantized
    model_type = check_and_get_model_type(save_dir or model_name_or_path, trust_remote_code)
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\modeling\_utils.py", line 125, in check_and_get_model_type
    raise TypeError(f"{config.model_type} isn't supported yet.")
TypeError: chatglm isn't supported yet.
