### ISSUE TITLE
Failed building wheel for llama-cpp-python

### ISSUE THREAD

**Issue by mongolu** [oobabooga/text-generation-webui#2879]
### Describe the bug

Done a `git pull` on `text-generation-webui`
Run `pip install -r requirements --upgrade`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

`git pull` on `text-generation-webui`
Run `pip install -r requirements --upgrade`

### Logs

```shell
error at building wheel for llama-cpp-python
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [101 lines of output]


      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 11.1.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 11.1.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (1.2s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-7qmpqs5u/llama-cpp-python_29a61aeb054f4ccfbecb1ae24b8cc1ce/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          /tmp/pip-install-7qmpqs5u/llama-cpp-python_29a61aeb054f4ccfbecb1ae24b8cc1ce/_skbuild/linux-x86_64-3.10/cmake-build
        Command:
          /tmp/pip-build-env-jy8ni6aq/overlay/local/lib/python3.10/dist-packages/cmake/data/bin/cmake /tmp/pip-install-7qmpqs5u/llama-cpp-python_29a61aeb054f4ccfbecb1ae24b8cc1ce -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-jy8ni6aq/overlay/local/lib/python3.10/dist-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-7qmpqs5u/llama-cpp-python_29a61aeb054f4ccfbecb1ae24b8cc1ce/_skbuild/linux-x86_64-3.10/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.11 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-jy8ni6aq/overlay/local/lib/python3.10/dist-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/usr/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPYTHON_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.10.so -DPython_EXECUTABLE:PATH=/usr/bin/python3 -DPython_ROOT_DIR:PATH=/usr -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython3_EXECUTABLE:PATH=/usr/bin/python3 -DPython3_ROOT_DIR:PATH=/usr -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.10 -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-jy8ni6aq/overlay/local/lib/python3.10/dist-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release

      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 11.1.0
      -- The CXX compiler identification is GNU 11.1.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (1.0s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-7qmpqs5u/llama-cpp-python_29a61aeb054f4ccfbecb1ae24b8cc1ce/_skbuild/linux-x86_64-3.10/cmake-build
      [1/2] Generating /tmp/pip-install-7qmpqs5u/llama-cpp-python_29a61aeb054f4ccfbecb1ae24b8cc1ce/vendor/llama.cpp/libllama.so
      FAILED: /tmp/pip-install-7qmpqs5u/llama-cpp-python_29a61aeb054f4ccfbecb1ae24b8cc1ce/vendor/llama.cpp/libllama.so
      cd /tmp/pip-install-7qmpqs5u/llama-cpp-python_29a61aeb054f4ccfbecb1ae24b8cc1ce/vendor/llama.cpp && make libllama.so
      I llama.cpp build info:
      I UNAME_S:  Linux
      I UNAME_P:  x86_64
      I UNAME_M:  x86_64
      I CFLAGS:   -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS
      I CXXFLAGS: -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS
      I LDFLAGS:
      I CC:       cc (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0
      I CXX:      g++ (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0

      g++ -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS -c llama.cpp -o llama.o
      cc  -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS   -c ggml.c -o ggml.o
      /tmp/ccHGC2j7.s: Assembler messages:
      /tmp/ccHGC2j7.s:1680: Error: unsupported instruction `vpdpbusd'
      /tmp/ccHGC2j7.s:1741: Error: unsupported instruction `vpdpbusd'
      /tmp/ccHGC2j7.s:1805: Error: unsupported instruction `vpdpbusd'
      /tmp/ccHGC2j7.s:1875: Error: unsupported instruction `vpdpbusd'
      /tmp/ccHGC2j7.s:1945: Error: unsupported instruction `vpdpbusd'
      make: *** [Makefile:253: ggml.o] Error 1
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/tmp/pip-build-env-jy8ni6aq/overlay/local/lib/python3.10/dist-packages/skbuild/setuptools_wrap.py", line 674, in setup
          cmkr.make(make_args, install_target=cmake_install_target, env=env)
        File "/tmp/pip-build-env-jy8ni6aq/overlay/local/lib/python3.10/dist-packages/skbuild/cmaker.py", line 697, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
        File "/tmp/pip-build-env-jy8ni6aq/overlay/local/lib/python3.10/dist-packages/skbuild/cmaker.py", line 742, in make_impl
          raise SKBuildError(msg)

      An error occurred while building with CMake.
        Command:
          /tmp/pip-build-env-jy8ni6aq/overlay/local/lib/python3.10/dist-packages/cmake/data/bin/cmake --build . --target install --config Release --
        Install target:
          install
        Source directory:
          /tmp/pip-install-7qmpqs5u/llama-cpp-python_29a61aeb054f4ccfbecb1ae24b8cc1ce
        Working directory:
          /tmp/pip-install-7qmpqs5u/llama-cpp-python_29a61aeb054f4ccfbecb1ae24b8cc1ce/_skbuild/linux-x86_64-3.10/cmake-build
      Please check the install target is valid and see CMake's output for more information.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
```

### System Info

```shell
mihai@MihaiPC:~/text-generation-webui$ python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.31

Python version: 3.10.12 (main, Jun  7 2023, 12:45:35) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY

Nvidia driver version: 535.98

Versions of relevant libraries:
[pip3] mypy==1.3.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.25.0
[pip3] pytorch-triton==2.1.0+7d1a95b046
[pip3] torch==2.0.1
[pip3] torchaudio==2.1.0.dev20230523+cu117
[pip3] torchvision==0.16.0.dev20230523+cu117
[conda] Could not collect
```

**Comment by mongolu** [comment]
I've deleted these 2 lines in requirements.txt

llama-cpp-python==0.1.64; platform_system != "Windows"
https://github.com/abetlen/llama-cpp-python/releases/download/v0.1.64/llama_cpp_python-0.1.64-cp310-cp310-win_amd64.whl; platform_system == "Windows"

run `pip install -r requirements.txt --upgrade`

and after this run:
`CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python --no-cache-dir`

now it's ok

**Comment by MelvinIdema** [comment]
On Ubuntu you have to install the `build-essential` like this: `sudo apt install build-essential`.

**Comment by mongolu** [comment]
I have it, this is not the case.

mihai@MihaiPC:~/AGiXT$ sudo apt install build-essential
[sudo] password for mihai:
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.8ubuntu1.1).
0 upgraded, 0 newly installed, 0 to remove and 69 not upgraded.
mihai@MihaiPC:~/AGiXT$
