### ISSUE TITLE
llama-cpp-python Installation Issue with gcc 12 for GPU Accelleration

### ISSUE THREAD

**Issue by qazpllp** [oobabooga/text-generation-webui#2881]
### Describe the bug

llama-cpp-python with GPU accelleration has issues building with a system that has gcc that is too recent (gcc 12). The command
```
pip uninstall -y llama-cpp-python
CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python --no-cache-dir
```
fails to build (due to gcc being too recent for CUDA), on a one-click installation.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

- Have a linux system using gcc 12
- Install using the one-click installer
- Run llama.cpp in the web UI instructions (``CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python --no-cache-dir``)

Unable to build. (See logs[1])

An attempted solution is to symlink gcc 11 by:
- ``mount --bind /usr/bin/gcc-11 /opt/cuda/bin/gcc`` and ``mount --bind /usr/bin/g++-11 /opt/cuda/bin/g++``
But this still has issues (provided in the second set of logs, logs[2])
Does this have something to do with [removing libpthread](https://developers.redhat.com/articles/2021/12/17/why-glibc-234-removed-libpthread)?

### Logs

```shell
Logs [1]:

Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [189 lines of output]
      
      
      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 11.2.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /home/user/Programs/oobabooga_linux/installer_files/env/bin/x86_64-conda-linux-gnu-cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 11.2.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /home/user/Programs/oobabooga_linux/installer_files/env/bin/x86_64-conda-linux-gnu-c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (0.3s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-f70n2j6_/llama-cpp-python_74e4ae8fbccc4bb086e69fb964af6d80/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - success
      --------------------------------------------------------------------------------
      
      Configuring Project
        Working directory:
          /tmp/pip-install-f70n2j6_/llama-cpp-python_74e4ae8fbccc4bb086e69fb964af6d80/_skbuild/linux-x86_64-3.10/cmake-build
        Command:
          /tmp/pip-build-env-mfp3h6v7/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake /tmp/pip-install-f70n2j6_/llama-cpp-python_74e4ae8fbccc4bb086e69fb964af6d80 -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-mfp3h6v7/overlay/lib/python3.10/site-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-f70n2j6_/llama-cpp-python_74e4ae8fbccc4bb086e69fb964af6d80/_skbuild/linux-x86_64-3.10/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.11 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-mfp3h6v7/overlay/lib/python3.10/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/home/user/Programs/oobabooga_linux/installer_files/env/bin/python -DPYTHON_INCLUDE_DIR:PATH=/home/user/Programs/oobabooga_linux/installer_files/env/include/python3.10 -DPYTHON_LIBRARY:PATH=/home/user/Programs/oobabooga_linux/installer_files/env/lib/libpython3.10.so -DPython_EXECUTABLE:PATH=/home/user/Programs/oobabooga_linux/installer_files/env/bin/python -DPython_ROOT_DIR:PATH=/home/user/Programs/oobabooga_linux/installer_files/env -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/home/user/Programs/oobabooga_linux/installer_files/env/include/python3.10 -DPython3_EXECUTABLE:PATH=/home/user/Programs/oobabooga_linux/installer_files/env/bin/python -DPython3_ROOT_DIR:PATH=/home/user/Programs/oobabooga_linux/installer_files/env -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/home/user/Programs/oobabooga_linux/installer_files/env/include/python3.10 -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-mfp3h6v7/overlay/lib/python3.10/site-packages/ninja/data/bin/ninja -DLLAMA_CUBLAS=on -DCMAKE_BUILD_TYPE:STRING=Release -DLLAMA_CUBLAS=on
      
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 11.2.0
      -- The CXX compiler identification is GNU 11.2.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /home/user/Programs/oobabooga_linux/installer_files/env/bin/x86_64-conda-linux-gnu-cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /home/user/Programs/oobabooga_linux/installer_files/env/bin/x86_64-conda-linux-gnu-c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found Git: /home/user/Programs/oobabooga_linux/installer_files/env/bin/git (found version "2.34.1")
      fatal: not a git repository (or any parent up to mount point /)
      Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
      fatal: not a git repository (or any parent up to mount point /)
      Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
      CMake Warning at vendor/llama.cpp/CMakeLists.txt:113 (message):
        Git repository not found; to enable automatic generation of build info,
        make sure Git is installed and the project is a Git repository.
      
      
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Check if compiler accepts -pthread
      -- Check if compiler accepts -pthread - yes
      -- Found Threads: TRUE
      -- Found CUDAToolkit: /home/user/Programs/oobabooga_linux/installer_files/env/include (found version "11.7.64")
      -- cuBLAS found
      CMake Error at /tmp/pip-build-env-mfp3h6v7/overlay/lib/python3.10/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:751 (message):
        Compiling the CUDA compiler identification source file
        "CMakeCUDACompilerId.cu" failed.
      
        Compiler:
        /home/user/Programs/oobabooga_linux/installer_files/env/bin/nvcc
      
        Build flags:
      
        Id flags: --keep;--keep-dir;tmp -v
      
      
      
        The output was:
      
        1
      
        #$ _NVVM_BRANCH_=nvvm
      
        #$ _SPACE_=
      
        #$ _CUDART_=cudart
      
        #$ _HERE_=/home/user/Programs/oobabooga_linux/installer_files/env/bin
      
        #$ _THERE_=/home/user/Programs/oobabooga_linux/installer_files/env/bin
      
        #$ _TARGET_SIZE_=
      
        #$ _TARGET_DIR_=
      
        #$ _TARGET_SIZE_=64
      
        #$ TOP=/home/user/Programs/oobabooga_linux/installer_files/env/bin/..
      
        #$
        NVVMIR_LIBRARY_DIR=/home/user/Programs/oobabooga_linux/installer_files/env/bin/../nvvm/libdevice
      
      
        #$
        LD_LIBRARY_PATH=/home/user/Programs/oobabooga_linux/installer_files/env/bin/../lib:
      
      
        #$
        PATH=/home/user/Programs/oobabooga_linux/installer_files/env/bin/../nvvm/bin:/home/user/Programs/oobabooga_linux/installer_files/env/bin:/tmp/pip-build-env-mfp3h6v7/overlay/bin:/tmp/pip-build-env-mfp3h6v7/normal/bin:/home/user/Programs/oobabooga_linux/installer_files/env/bin:/opt/cuda/bin:/opt/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/home/user/.dotnet/tools:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
      
      
        #$
        INCLUDES="-I/home/user/Programs/oobabooga_linux/installer_files/env/bin/../include"
      
      
        #$ LIBRARIES=
        "-L/home/user/Programs/oobabooga_linux/installer_files/env/bin/../lib/stubs"
        "-L/home/user/Programs/oobabooga_linux/installer_files/env/bin/../lib"
      
        #$ CUDAFE_FLAGS=
      
        #$ PTXAS_FLAGS=
      
        #$ rm tmp/a_dlink.reg.c
      
        #$ gcc -D__CUDA_ARCH__=520 -D__CUDA_ARCH_LIST__=520 -E -x c++
        -DCUDA_DOUBLE_MATH_FUNCTIONS -D__CUDACC__ -D__NVCC__
        "-I/home/user/Programs/oobabooga_linux/installer_files/env/bin/../include"
        -D__CUDACC_VER_MAJOR__=11 -D__CUDACC_VER_MINOR__=7
        -D__CUDACC_VER_BUILD__=64 -D__CUDA_API_VER_MAJOR__=11
        -D__CUDA_API_VER_MINOR__=7 -D__NVCC_DIAG_PRAGMA_SUPPORT__=1 -include
        "cuda_runtime.h" -m64 "CMakeCUDACompilerId.cu" -o
        "tmp/CMakeCUDACompilerId.cpp1.ii"
      
        In file included from
        /home/user/Programs/oobabooga_linux/installer_files/env/bin/../include/cuda_runtime.h:83,
      
      
                         from <command-line>:
      
      
        /home/user/Programs/oobabooga_linux/installer_files/env/bin/../include/crt/host_config.h:132:2:
        error: #error -- unsupported GNU version! gcc versions later than 11 are
        not supported! The nvcc flag '-allow-unsupported-compiler' can be used to
        override this version check; however, using an unsupported host compiler
        may cause compilation failure or incorrect run time execution.  Use at your
        own risk.
      
          132 | #error -- unsupported GNU version! gcc versions later than 11 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
              |  ^~~~~
      
        # --error 0x1 --
      
      
      
      
      
      Call Stack (most recent call first):
        /tmp/pip-build-env-mfp3h6v7/overlay/lib/python3.10/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
        /tmp/pip-build-env-mfp3h6v7/overlay/lib/python3.10/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:53 (__determine_compiler_id_test)
        /tmp/pip-build-env-mfp3h6v7/overlay/lib/python3.10/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:307 (CMAKE_DETERMINE_COMPILER_ID)
        vendor/llama.cpp/CMakeLists.txt:235 (enable_language)
      
      
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "/tmp/pip-build-env-mfp3h6v7/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 666, in setup
          env = cmkr.configure(
        File "/tmp/pip-build-env-mfp3h6v7/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 357, in configure
          raise SKBuildError(msg)
      
      An error occurred while configuring with CMake.
        Command:
          /tmp/pip-build-env-mfp3h6v7/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake /tmp/pip-install-f70n2j6_/llama-cpp-python_74e4ae8fbccc4bb086e69fb964af6d80 -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-mfp3h6v7/overlay/lib/python3.10/site-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-f70n2j6_/llama-cpp-python_74e4ae8fbccc4bb086e69fb964af6d80/_skbuild/linux-x86_64-3.10/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.11 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-mfp3h6v7/overlay/lib/python3.10/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/home/user/Programs/oobabooga_linux/installer_files/env/bin/python -DPYTHON_INCLUDE_DIR:PATH=/home/user/Programs/oobabooga_linux/installer_files/env/include/python3.10 -DPYTHON_LIBRARY:PATH=/home/user/Programs/oobabooga_linux/installer_files/env/lib/libpython3.10.so -DPython_EXECUTABLE:PATH=/home/user/Programs/oobabooga_linux/installer_files/env/bin/python -DPython_ROOT_DIR:PATH=/home/user/Programs/oobabooga_linux/installer_files/env -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/home/user/Programs/oobabooga_linux/installer_files/env/include/python3.10 -DPython3_EXECUTABLE:PATH=/home/user/Programs/oobabooga_linux/installer_files/env/bin/python -DPython3_ROOT_DIR:PATH=/home/user/Programs/oobabooga_linux/installer_files/env -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/home/user/Programs/oobabooga_linux/installer_files/env/include/python3.10 -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-mfp3h6v7/overlay/lib/python3.10/site-packages/ninja/data/bin/ninja -DLLAMA_CUBLAS=on -DCMAKE_BUILD_TYPE:STRING=Release -DLLAMA_CUBLAS=on
        Source directory:
          /tmp/pip-install-f70n2j6_/llama-cpp-python_74e4ae8fbccc4bb086e69fb964af6d80
        Working directory:
          /tmp/pip-install-f70n2j6_/llama-cpp-python_74e4ae8fbccc4bb086e69fb964af6d80/_skbuild/linux-x86_64-3.10/cmake-build
      Please see CMake's output for more information.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
```

The logs when attempting to install after linking to gcc 11. Logs [2]:
```
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [116 lines of output]
      
      
      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 11.2.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /home/user/Programs/oobabooga_linux/installer_files/env/bin/x86_64-conda-linux-gnu-cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 11.2.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /home/user/Programs/oobabooga_linux/installer_files/env/bin/x86_64-conda-linux-gnu-c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (0.3s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-xa_1_uk9/llama-cpp-python_359eca3abd1b4f1c998324a9d54b90fa/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - success
      --------------------------------------------------------------------------------
      
      Configuring Project
        Working directory:
          /tmp/pip-install-xa_1_uk9/llama-cpp-python_359eca3abd1b4f1c998324a9d54b90fa/_skbuild/linux-x86_64-3.10/cmake-build
        Command:
          /tmp/pip-build-env-1udh_slt/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake /tmp/pip-install-xa_1_uk9/llama-cpp-python_359eca3abd1b4f1c998324a9d54b90fa -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-1udh_slt/overlay/lib/python3.10/site-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-xa_1_uk9/llama-cpp-python_359eca3abd1b4f1c998324a9d54b90fa/_skbuild/linux-x86_64-3.10/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.11 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-1udh_slt/overlay/lib/python3.10/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/home/user/Programs/oobabooga_linux/installer_files/env/bin/python -DPYTHON_INCLUDE_DIR:PATH=/home/user/Programs/oobabooga_linux/installer_files/env/include/python3.10 -DPYTHON_LIBRARY:PATH=/home/user/Programs/oobabooga_linux/installer_files/env/lib/libpython3.10.so -DPython_EXECUTABLE:PATH=/home/user/Programs/oobabooga_linux/installer_files/env/bin/python -DPython_ROOT_DIR:PATH=/home/user/Programs/oobabooga_linux/installer_files/env -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/home/user/Programs/oobabooga_linux/installer_files/env/include/python3.10 -DPython3_EXECUTABLE:PATH=/home/user/Programs/oobabooga_linux/installer_files/env/bin/python -DPython3_ROOT_DIR:PATH=/home/user/Programs/oobabooga_linux/installer_files/env -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/home/user/Programs/oobabooga_linux/installer_files/env/include/python3.10 -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-1udh_slt/overlay/lib/python3.10/site-packages/ninja/data/bin/ninja -DLLAMA_CUBLAS=on -DCMAKE_BUILD_TYPE:STRING=Release -DLLAMA_CUBLAS=on
      
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 11.2.0
      -- The CXX compiler identification is GNU 11.2.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /home/user/Programs/oobabooga_linux/installer_files/env/bin/x86_64-conda-linux-gnu-cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /home/user/Programs/oobabooga_linux/installer_files/env/bin/x86_64-conda-linux-gnu-c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found Git: /home/user/Programs/oobabooga_linux/installer_files/env/bin/git (found version "2.34.1")
      fatal: not a git repository (or any parent up to mount point /)
      Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
      fatal: not a git repository (or any parent up to mount point /)
      Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
      CMake Warning at vendor/llama.cpp/CMakeLists.txt:113 (message):
        Git repository not found; to enable automatic generation of build info,
        make sure Git is installed and the project is a Git repository.
      
      
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Check if compiler accepts -pthread
      -- Check if compiler accepts -pthread - yes
      -- Found Threads: TRUE
      -- Found CUDAToolkit: /home/user/Programs/oobabooga_linux/installer_files/env/include (found version "11.7.64")
      -- cuBLAS found
      -- The CUDA compiler identification is NVIDIA 11.7.64
      -- Detecting CUDA compiler ABI info
      -- Detecting CUDA compiler ABI info - done
      -- Check for working CUDA compiler: /home/user/Programs/oobabooga_linux/installer_files/env/bin/nvcc - skipped
      -- Detecting CUDA compile features
      -- Detecting CUDA compile features - done
      -- CMAKE_SYSTEM_PROCESSOR: x86_64
      -- x86 detected
      -- GGML CUDA sources found, configuring CUDA architecture
      -- Configuring done (2.4s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-xa_1_uk9/llama-cpp-python_359eca3abd1b4f1c998324a9d54b90fa/_skbuild/linux-x86_64-3.10/cmake-build
      [1/8] Building C object vendor/llama.cpp/CMakeFiles/ggml.dir/k_quants.c.o
      [2/8] Building CUDA object vendor/llama.cpp/CMakeFiles/ggml.dir/ggml-cuda.cu.o
      [3/8] Building CXX object vendor/llama.cpp/CMakeFiles/llama.dir/llama.cpp.o
      [4/8] Building C object vendor/llama.cpp/CMakeFiles/ggml.dir/ggml.c.o
      [5/8] Linking CUDA shared library vendor/llama.cpp/libggml_shared.so
      FAILED: vendor/llama.cpp/libggml_shared.so
      : && /opt/cuda/bin/g++ -fPIC -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/user/Programs/oobabooga_linux/installer_files/env/lib -Wl,-rpath-link,/home/user/Programs/oobabooga_linux/installer_files/env/lib -L/home/user/Programs/oobabooga_linux/installer_files/env/lib -shared -Wl,-soname,libggml_shared.so -o vendor/llama.cpp/libggml_shared.so vendor/llama.cpp/CMakeFiles/ggml.dir/ggml.c.o vendor/llama.cpp/CMakeFiles/ggml.dir/ggml-cuda.cu.o vendor/llama.cpp/CMakeFiles/ggml.dir/k_quants.c.o -L/home/user/Large/user/Programs/oobabooga_linux/installer_files/env/lib/gcc/x86_64-conda-linux-gnu/11.2.0   -L/home/user/Large/user/Programs/oobabooga_linux/installer_files/env/lib/gcc   -L/home/user/Large/user/Programs/oobabooga_linux/installer_files/env/x86_64-conda-linux-gnu/lib64   -L/home/user/Large/user/Programs/oobabooga_linux/installer_files/env/x86_64-conda-linux-gnu/sysroot/lib64   -L/home/user/Large/user/Programs/oobabooga_linux/installer_files/env/x86_64-conda-linux-gnu/sysroot/usr/lib64   -L/home/user/Large/user/Programs/oobabooga_linux/installer_files/env/x86_64-conda-linux-gnu/lib   -L/home/user/Large/user/Programs/oobabooga_linux/installer_files/env/x86_64-conda-linux-gnu/sysroot/lib   -L/home/user/Large/user/Programs/oobabooga_linux/installer_files/env/x86_64-conda-linux-gnu/sysroot/usr/lib /home/user/Programs/oobabooga_linux/installer_files/env/lib/libcudart.so  /home/user/Programs/oobabooga_linux/installer_files/env/lib/libcublas.so  /home/user/Programs/oobabooga_linux/installer_files/env/lib/libcublasLt.so  -pthread  /home/user/Programs/oobabooga_linux/installer_files/env/lib/libculibos.a  -lcudadevrt  -lcudart_static  -lrt  -lpthread  -ldl -L"/home/user/Programs/oobabooga_linux/installer_files/env/lib/stubs" -L"/home/user/Programs/oobabooga_linux/installer_files/env/lib" && :
      /usr/bin/ld: cannot find /usr/lib64/libpthread_nonshared.a: No such file or directory
      collect2: error: ld returned 1 exit status
      [6/8] Linking CUDA static library vendor/llama.cpp/libggml_static.a
      [7/8] Linking CXX shared library vendor/llama.cpp/libllama.so
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/tmp/pip-build-env-1udh_slt/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 674, in setup
          cmkr.make(make_args, install_target=cmake_install_target, env=env)
        File "/tmp/pip-build-env-1udh_slt/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 697, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
        File "/tmp/pip-build-env-1udh_slt/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 742, in make_impl
          raise SKBuildError(msg)
      
      An error occurred while building with CMake.
        Command:
          /tmp/pip-build-env-1udh_slt/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake --build . --target install --config Release --
        Install target:
          install
        Source directory:
          /tmp/pip-install-xa_1_uk9/llama-cpp-python_359eca3abd1b4f1c998324a9d54b90fa
        Working directory:
          /tmp/pip-install-xa_1_uk9/llama-cpp-python_359eca3abd1b4f1c998324a9d54b90fa/_skbuild/linux-x86_64-3.10/cmake-build
      Please check the install target is valid and see CMake's output for more information.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
```

### System Info

```shell
OS: Arch Linux x86_64 
Kernel: 6.3.9-arch1-1 
GPU: NVIDIA TITAN Xp
```

**Comment by berkut1** [comment]
You should create this issue in the llama-cpp-python repo.

**Comment by valden80** [comment]
I was experienced similar issue on Manjaro Linux, and got help at the llama-cpp-python repo. This is thread with solution that is works for me:
https://github.com/abetlen/llama-cpp-python/issues/500
