### ISSUE TITLE
module 'gradio.components' has no attribute 'FormComponent'

### ISSUE THREAD

**Issue by Kas1o** [oobabooga/text-generation-webui#2888]
### Describe the bug

gradio version 3.35.2;
python version 3.10;

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

install:
conda create -n TGW python=3.10;
pip install -r req***.txt;

try to run server.py 
and install everything cause ModuleNotFoundError.
pytorch install:pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117 

run:
log below

### Logs

```shell
run:
(tgw) PS Z:\Tools\TGW\text-generation-webui> python .\server.py
Traceback (most recent call last):
  File "Z:\Tools\TGW\text-generation-webui\server.py", line 35, in <module>
    from modules import chat, loaders, presets, shared, training, ui, utils
  File "Z:\Tools\TGW\text-generation-webui\modules\chat.py", line 17, in <module>
    from modules.text_generation import (
  File "Z:\Tools\TGW\text-generation-webui\modules\text_generation.py", line 21, in <module>
    from modules.models import clear_torch_cache, local_rank
  File "Z:\Tools\TGW\text-generation-webui\modules\models.py", line 23, in <module>
    from modules.models_settings import infer_loader
  File "Z:\Tools\TGW\text-generation-webui\modules\models_settings.py", line 6, in <module>
    from modules import shared, ui
  File "Z:\Tools\TGW\text-generation-webui\modules\ui.py", line 69, in <module>
    class ToolButton(gr.Button, gr.components.FormComponent):
AttributeError: module 'gradio.components' has no attribute 'FormComponent'. Did you mean: 'IOComponent'?
```

### System Info

```shell
windows10 22h2;
2666v3;
3060 12G & Tesla M40 24G;
driver: 531.41;
cuda installed:
    v10.1
    v11.3
    v11.7
```

**Comment by Kas1o** [comment]
the problem is when I pip install -r req***.txt , thing  went wrong, so I download mannully, that cause I download wrong version of many module

**Comment by TissueC** [comment]
same here.

**Comment by Kas1o** [comment]
> same here.

Have you noticed my last comment? 
the version should be gradio==3.33.1

**Comment by 24mlight** [comment]
> 

it works!

**Comment by 24mlight** [comment]
> > same here.
> 
> Have you noticed my last comment? the version should be gradio==3.33.1

it works!
