### ISSUE TITLE
Error when trying to use >5k context on SuperHOT 8k models on exllama_hf

### ISSUE THREAD

**Issue by Panchovix** [oobabooga/text-generation-webui#2891]
### Describe the bug

Hi there, thanks for all the work.

Was trying some SuperHOT 8k merged models (like https://huggingface.co/Panchovix/tulu-30b-SuperHOT-8K-4bit-32g), and then, when trying to generate while context was larger than 5000, I get issues and it doesn't generate any output.

The only seems to happen only on exllama_hf, since on exllama itself, it works without issues.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Get any SuperHOT 8k merged model.
2. Load into the webui with max_seq_len 8192 and compress_pos_emb 4.
3. Try to generate or continue a chat with more than 5000 tokens.

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/19153797/a13c245e-5842-432f-9500-de3bc8e949a3)

### Logs

```shell
To create a public link, set `share=True` in `launch()`.
2023-06-27 02:06:37 INFO:Loading h2ogpt-research-oig-oasst1-512-30b-SuperHOT-8k-4bit-32g...
2023-06-27 02:06:37 WARNING:Exllama module failed to load. Will attempt to load from repositories.
2023-06-27 02:06:45 INFO:Replaced attention with xformers_attention
2023-06-27 02:06:45 INFO:Loaded the model in 8.47 seconds.

Output generated in 9.92 seconds (20.06 tokens/s, 199 tokens, context 1848, seed 356899934)
Traceback (most recent call last):
  File "F:\ChatIAs\oobabooga\text-generation-webui\modules\callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "F:\ChatIAs\oobabooga\text-generation-webui\modules\text_generation.py", line 289, in generate_with_callback
    shared.model.generate(**kwargs)
  File "F:\ChatIAs\oobabooga\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\ChatIAs\oobabooga\venv\lib\site-packages\transformers\generation\utils.py", line 1572, in generate
    return self.sample(
  File "F:\ChatIAs\oobabooga\venv\lib\site-packages\transformers\generation\utils.py", line 2619, in sample
    outputs = self(
  File "F:\ChatIAs\oobabooga\text-generation-webui\modules\exllama_hf.py", line 57, in __call__
    self.ex_model.forward(torch.tensor([seq[:-1]], dtype=torch.long), cache, preprocess_only=True, lora=self.lora)
  File "F:\ChatIAs\oobabooga\text-generation-webui\repositories\exllama\model.py", line 860, in forward
    hidden_states = decoder_layer.forward(hidden_states, cache, buffers[device], lora)
  File "F:\ChatIAs\oobabooga\text-generation-webui\repositories\exllama\model.py", line 466, in forward
    hidden_states = self.self_attn.forward(hidden_states, cache, buffer, lora)
  File "F:\ChatIAs\oobabooga\text-generation-webui\repositories\exllama\model.py", line 385, in forward
    value_states = self.v_proj.forward(hidden_states, lora).view(bsz, q_len, self.config.num_attention_heads, self.config.head_dim).transpose(1, 2)
  File "F:\ChatIAs\oobabooga\text-generation-webui\repositories\exllama\model.py", line 195, in forward
    out = cuda_ext.ext_q4_matmul(x, self.q4, self.width)
  File "F:\ChatIAs\oobabooga\text-generation-webui\repositories\exllama\cuda_ext.py", line 102, in ext_q4_matmul
    output = torch.empty((x.shape[0], q4_width), dtype = torch.float16, device = x.device)
RuntimeError: CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Output generated in 0.98 seconds (0.00 tokens/s, 0 tokens, context 7680, seed 1735502537)
```

### System Info

```shell
Windows 10/Ubuntu 22.04
RTX 4090x2
AMD Ryzen 7 7800X3D
64GB DDR5
```

**Comment by tensiondriven** [comment]
What command are you using to invoke server?  

I'm using

```
python server.py --listen --listen-port $port \
        --loader exllama \
        --gpu-split 16,24 \
        --model \
          33-8k/WizardLM-33B-V1.0-Uncensored-SuperHOT-8K-GPTQ \
        --chat \
        --api \
        --extensions api \
        --verbose \
        --max_seq_len 8192 \
        --compress_pos_emb 4
```

And upon loading, I'm seeing:

```
(textgen) j@textgen-working:~/text-generation-webui$ ~/run/wizard33buncensored8k 
bin /home/j/miniconda3/envs/textgen/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
2023-06-27 12:08:01 INFO:Loading 33-8k/WizardLM-33B-V1.0-Uncensored-SuperHOT-8K-GPTQ...
2023-06-27 12:08:01 WARNING:Exllama module failed to load. Will attempt to load from repositories.
loaded exllama
Traceback (most recent call last):
  File "/home/j/text-generation-webui/server.py", line 1017, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/j/text-generation-webui/modules/models.py", line 74, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/j/text-generation-webui/modules/models.py", line 286, in ExLlama_loader
    model, tokenizer = ExllamaModel.from_pretrained(model_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/j/text-generation-webui/modules/exllama.py", line 57, in from_pretrained
    cache = ExLlamaCache(model)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/j/text-generation-webui/repositories/exllama/model.py", line 419, in __init__
    p_key_states = torch.zeros(self.batch_size, self.config.num_attention_heads, self.max_seq_len, self.config.head_dim, dtype = torch.float16, device = self.model.config.device_map.layers[i])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 104.00 MiB (GPU 0; 23.69 GiB total capacity; 22.77 GiB already allocated; 72.06 MiB free; 22.98 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
Could this be related?  (Sounds like you're getting father than me anyway.)

**Comment by MildPanda** [comment]
> CUDA out of memory. Tried to allocate 104.00 MiB (GPU 0; 23.69 GiB total

Your issue is ram. these 8k token models (30b) will take more than 24GB VRAM. This is also noted on thebloke's readmes for these 8k token models.

**Comment by treplogle** [comment]
The larger context takes up a lot of VRAM. I got 8k context working by using --gpu-split 8,24. This gives more room for the context to load on the first GPU I think.

**Comment by Panchovix** [comment]
> The larger context takes up a lot of VRAM. I got 8k context working by using --gpu-split 8,24. This gives more room for the context to load on the first GPU I think.

It does work fine on exllama itself, but when using exllama_hf I get the issue mentioned on the first post.

**Comment by tensiondriven** [comment]
That did the job:
```
--gpu_split 8,24
```
thank you @treplogle @Panchovix
