### ISSUE TITLE
OSError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by ytpk** [oobabooga/text-generation-webui#29]
python3 server.py --cpu --cpu-memory 11 --disk --disk-cache-dir /home/ytpk/test/cach/ --cai-chat --listen --model pygmalion-2.7b --no-stream
2023-01-27 07:13:48.400788: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Loading pygmalion-2.7b...
Loaded the model in 83.87 seconds.
Traceback (most recent call last):
  File "/mnt/sdb3/games/text-generation-webui/server.py", line 513, in <module>
    with gr.Blocks(css=css+".h-\[40vh\] {height: 66.67vh} .gradio-container {max-width: 800px; margin-left: auto; margin-right: auto}", analytics_enabled=False) as interface:
  File "/home/ytpk/.local/lib/python3.10/site-packages/gradio/blocks.py", line 473, in __init__
    if css is not None and Path(css).exists():
  File "/usr/lib/python3.10/pathlib.py", line 1290, in exists
    self.stat()
  File "/usr/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
OSError: [Errno 36] File name too long: '.my-4 {margin-top: 0} .py-6 {padding-top: 2.5rem} #refresh-button {flex: none; margin: 0; padding: 0; min-width: 50px; border: none; box-shadow: none; border-radius: 0} #download-label, #upload-label {min-height: 0}.h-\\[40vh\\] {height: 66.67vh} .gradio-container {max-width: 800px; margin-left: auto; margin-right: auto}'

**Comment by oobabooga** [comment]
Can you try `pip install -r requirements.txt` to make sure that you have the right versions of everything?

**Comment by ytpk** [comment]
ERROR: Could not find a version that satisfies the requirement mkl-fft==1.3.1 (from versions: none)
ERROR: No matching distribution found for mkl-fft==1.3.1
this is the only package that I don't have installed for some reason.os Arch linux

**Comment by ytpk** [comment]
could it be that the project is launched only from under conda?

**Comment by oobabooga** [comment]
It could be, it's best to create a conda environment as in the README.
