### ISSUE TITLE
Context over 2k in ExLLaMa doesn't truncate

### ISSUE THREAD

**Issue by just-someguy** [oobabooga/text-generation-webui#2905]
### Describe the bug

When context goes over the max size in other GPTQ loaders, the prompt will be truncated to keep it within the size limit, but in ExLLaMa, I get an error that start+length exceeds dimensions. My system doesn't have enough VRAM to run 13B models above standard 2k context and there is no 7B SUPERHOT to test with to see if that affects it.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Have a conversation reach over 2048 Tokens with context

### Logs

```shell
Output generated in 27.58 seconds (1.52 tokens/s, 42 tokens, context 1986, seed 1079392374)
Traceback (most recent call last):
  File "C:\Users\user\Documents\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 323, in generate_reply_custom
    for reply in shared.model.generate_with_streaming(question, state):
  File "C:\Users\user\Documents\oobabooga_windows\text-generation-webui\modules\exllama.py", line 81, in generate_with_streaming
    self.generator.gen_begin_reuse(ids)
  File "C:\Users\user\Documents\oobabooga_windows\installer_files\env\lib\site-packages\exllama\generator.py", line 213, in gen_begin_reuse
    if reuse < in_tokens.shape[-1]: self.gen_feed_tokens(in_tokens[:, reuse:])
  File "C:\Users\user\Documents\oobabooga_windows\installer_files\env\lib\site-packages\exllama\generator.py", line 235, in gen_feed_tokens
    self.model.forward(self.sequence[:, a:b], self.cache, preprocess_only = True, lora = self.lora)
  File "C:\Users\user\Documents\oobabooga_windows\installer_files\env\lib\site-packages\exllama\model.py", line 860, in forward
    hidden_states = decoder_layer.forward(hidden_states, cache, buffers[device], lora)
  File "C:\Users\user\Documents\oobabooga_windows\installer_files\env\lib\site-packages\exllama\model.py", line 466, in forward
    hidden_states = self.self_attn.forward(hidden_states, cache, buffer, lora)
  File "C:\Users\user\Documents\oobabooga_windows\installer_files\env\lib\site-packages\exllama\model.py", line 389, in forward
    new_keys = cache.key_states[self.index].narrow(2, past_len, q_len)
RuntimeError: start (1973) + length (103) exceeds dimension size (2048).
Output generated in 0.05 seconds (0.00 tokens/s, 0 tokens, context 2077, seed 394522683)
```

### System Info

```shell
Windows 11
16GB RAM
Intel Core i9-12900H
Nvidia RTX 3050Ti Mobile 4GB
```

**Comment by official-elinas** [comment]
Same issue. It's not using the latest exllama implementation which should fix this.

**Comment by fgdfgfthgr-fox** [comment]
Same issue, although I was using the latest exllama implementation (git clone exllama into repositories).

**Comment by fgdfgfthgr-fox** [comment]
https://github.com/oobabooga/text-generation-webui/commit/1ba2e88551f968cd74478fd02218a62869336ac5 this commint seems to fix the issue.
