### ISSUE TITLE
chatglm2 support 

### ISSUE THREAD

**Issue by elven2016** [oobabooga/text-generation-webui#2906]
### Describe the bug

chatglm2-6b load successfully but canot chat，input message response nothing，and the terminal  show the following errors

Traceback (most recent call last):
  File "/ssd_data01/text-generation-webui/modules/callbacks.py", line 73, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/ssd_data01/text-generation-webui/modules/text_generation.py", line 263, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/elven/miniconda3/envs/tgweb/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/elven/miniconda3/envs/tgweb/lib/python3.10/site-packages/transformers/generation/utils.py", line 1285, in generate
    eos_token_id = eos_token_id[0]
IndexError: list index out of range

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

load the model and  in chat message mode ，input the message  in the chabox，response nothing

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/16677082/8297ae47-0b1c-4fda-82e6-e023f8a54cb6)
![image](https://github.com/oobabooga/text-generation-webui/assets/16677082/da9ed075-ac15-44c8-b096-dbf382bbf61c)

### Logs

```shell
Traceback (most recent call last):
  File "/ssd_data01/text-generation-webui/modules/callbacks.py", line 73, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/ssd_data01/text-generation-webui/modules/text_generation.py", line 263, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/elven/miniconda3/envs/tgweb/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/elven/miniconda3/envs/tgweb/lib/python3.10/site-packages/transformers/generation/utils.py", line 1285, in generate
    eos_token_id = eos_token_id[0]
IndexError: list index out of range
```

### System Info

```shell
ubuntu22.04 LTS
python3.10.10
```

**Comment by junphine** [comment]
on tokenization_chatglm.py


line：78   add    self._eos_token='<eos>'

**Comment by junphine** [comment]
line：78 add self._eos_token='&lt;eos&gt;'

**Comment by elven2016** [comment]
> line：78 add self._eos_token='<eos>'
![image](https://github.com/oobabooga/text-generation-webui/assets/16677082/e2c08569-a1d0-4096-8d79-3aa8d8bd3fdd)

感谢回复。添加这个之后能回复了，但是回复内容会胡言乱语，并且会不终止，一直发个不停，而且还是没有问的问题，
![image](https://github.com/oobabooga/text-generation-webui/assets/16677082/349ea0f4-0401-4bbb-9533-adf2961d37cb)

**Comment by upbit** [comment]
> > line：78 add self._eos_token=''
> > ![image](https://user-images.githubusercontent.com/16677082/249734164-e2c08569-a1d0-4096-8d79-3aa8d8bd3fdd.png)
> 
> 感谢回复。添加这个之后能回复了，但是回复内容会胡言乱语，并且会不终止，一直发个不停，而且还是没有问的问题， ![image](https://user-images.githubusercontent.com/16677082/249734680-349ea0f4-0401-4bbb-9533-adf2961d37cb.png)

The same problem. Comparing [the demo of ChatGLM2](https://github.com/THUDM/ChatGLM2-6B/blob/main/web_demo.py#L7), WebUI will output "// another topic" after the answer.

What is the reason for this? Did ChatGLM2 use special ending marks?

**Comment by upbit** [comment]
Found the reason(thanks [lejunzhu](https://huggingface.co/THUDM/chatglm2-6b/discussions/29#64a409781664581878a36ede)): Similar to LLaM's quick fix, it needs to be manually set the `eos/bos/pad` token id:

```diff
diff --git a/modules/models.py b/modules/models.py
index 4b47e64..dea9e73 100644
--- a/modules/models.py
+++ b/modules/models.py
@@ -116,6 +116,17 @@ def load_tokenizer(model_name, model):
         if path_to_model.exists():
             tokenizer = AutoTokenizer.from_pretrained(path_to_model, trust_remote_code=shared.args.trust_remote_code)

+        if 'chatglm' in model_name.lower():
+            try:
+                tokenizer.eos_token_id = 2
+            except:
+                pass
+            try:
+                tokenizer.bos_token_id = 1
+                tokenizer.pad_token_id = 0
+            except:
+                pass
+
     return tokenizer
```

But I don't know why my `tokenizer.eos_token_id` has a value here, setting it directly will cause error, so I divided it into 2 `try..catch`

**Comment by elven2016** [comment]
> 
thanks your reply， but I set it according to your code change，the same error again，no response in chat windows
Traceback (most recent call last):
  File "/ssd_data01/text-generation-webui/modules/callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "/ssd_data01/text-generation-webui/modules/text_generation.py", line 289, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/elven/miniconda3/envs/tgweb/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/elven/miniconda3/envs/tgweb/lib/python3.10/site-packages/transformers/generation/utils.py", line 1285, in generate
    eos_token_id = eos_token_id[0]
IndexError: list index out of range
![image](https://github.com/oobabooga/text-generation-webui/assets/16677082/0f629a3b-647d-4cae-a755-6c0cd7ec1942)
