### ISSUE TITLE
auto_gptq-0.2.2+cu117-cp310-cp310-linux_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by jpentland** [oobabooga/text-generation-webui#2910]
### Describe the bug

Webui no longer starts after updating to latest main

Platform: archlinux
GPU: Nvidia 3060
Python version: 3.9.7 (inside virtualenv)
Commit: 63770c0

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

pyenv activate my_project
pip install --upgrade -r requirements.txt
python server.py --chat --sdp-attention --model wizard-mega-13B.ggml.q5_0.bin --api

### Logs

```shell
Collecting git+https://github.com/huggingface/peft@03eb378eb914fbee709ff7c86ba5b1d033b89524 (from -r requirements.txt (line 19))
  Cloning https://github.com/huggingface/peft (to revision 03eb378eb914fbee709ff7c86ba5b1d033b89524) to /tmp/pip-req-build-sbhuozkg
  Running command git clone -q https://github.com/huggingface/peft /tmp/pip-req-build-sbhuozkg
  Running command git rev-parse -q --verify 'sha^03eb378eb914fbee709ff7c86ba5b1d033b89524'
  Running command git fetch -q https://github.com/huggingface/peft 03eb378eb914fbee709ff7c86ba5b1d033b89524
  Running command git checkout -q 03eb378eb914fbee709ff7c86ba5b1d033b89524
  Resolved https://github.com/huggingface/peft to commit 03eb378eb914fbee709ff7c86ba5b1d033b89524
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Ignoring bitsandbytes: markers 'platform_system == "Windows"' don't match your environment
Ignoring llama-cpp-python: markers 'platform_system == "Windows"' don't match your environment
Ignoring auto-gptq: markers 'platform_system == "Windows"' don't match your environment
ERROR: auto_gptq-0.2.2+cu117-cp310-cp310-linux_x86_64.whl is not a supported wheel on this platform.
WARNING: You are using pip version 21.2.3; however, version 23.1.2 is available.
You should consider upgrading via the '/home/user/.pyenv/versions/3.9.7/envs/my_project/bin/python3.9 -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/home/user/text-generation-webui/server.py", line 5, in <module>
    from modules.block_requests import RequestBlocker
  File "/home/user/text-generation-webui/modules/block_requests.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

```
```


### System Info

```shell
Platform: archlinux
GPU: Nvidia 3060
Python version: 3.9.7 (inside virtualenv)
Commit: 63770c0
```

**Comment by jpentland** [comment]
looks like i

**Comment by jpentland** [comment]
looks like i just needed to upgrade to 3.10. Was on 3.9 because 3.10 wasn't supported a month or so ago but i guess that changed
