### ISSUE TITLE
Every Model that i download from the webui ist not usable?

### ISSUE THREAD

**Issue by ollybrain** [oobabooga/text-generation-webui#2914]
### Describe the bug

I want to use a Model, with a german language. 

I testes so many diffrent medels that i dont know whitch one ist a god one, cause i never get one to run. 

I get so diffrent errors like:

for example:
T-Systems-onsite/cross-en-de-roberta-sentence-transformer:
Traceback (most recent call last): File “C:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py”, line 1988, in from_pretrained tokenizer = cls(*init_inputs, **init_kwargs) File “C:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\xlm_roberta\tokenization_xlm_roberta.py”, line 168, in init self.sp_model.Load(str(vocab_file)) File "C:\oobabooga_windows\installer_files\env\lib\site-packages\sentencepiece_init.py", line 905, in Load return self.LoadFromFile(model_file) File “C:\oobabooga_windows\installer_files\env\lib\site-packages\sentencepiece_init_.py”, line 310, in LoadFromFile return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg) OSError: Not found: “None”: No such file or directory Error #2

During handling of the above exception, another exception occurred:

Traceback (most recent call last): File “C:\oobabooga_windows\text-generation-webui\[server.py](http://server.py/)”, line 67, in load_model_wrapper shared.model, shared.tokenizer = load_model(shared.model_name, loader) File “C:\oobabooga_windows\text-generation-webui\modules\[models.py](http://models.py/)”, line 82, in load_model tokenizer = load_tokenizer(model_name, model) File “C:\oobabooga_windows\text-generation-webui\modules\[models.py](http://models.py/)”, line 117, in load_tokenizer tokenizer = AutoTokenizer.from_pretrained(path_to_model, trust_remote_code=shared.args.trust_remote_code) File “C:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\tokenization_auto.py”, line 709, in from_pretrained return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs) File “C:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py”, line 1825, in from_pretrained return cls._from_pretrained( File “C:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py”, line 1857, in _from_pretrained slow_tokenizer = (cls.slow_tokenizer_class)._from_pretrained( File “C:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py”, line 1990, in _from_pretrained raise OSError( OSError: Unable to load vocabulary from file. Please check that the provided vocabulary is accessible and not corrupted.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Download the zip for Windows extrakt it to c:\

make an intall

go to the model webui an enter T-Systems-onsite/cross-en-de-roberta-sentence-transformer to download

after downloading and initialice the model i geet the errorcode like
T-Systems-onsite/cross-en-de-roberta-sentence-transformer:
Traceback (most recent call last): File “C:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py”, line 1988, in from_pretrained tokenizer = cls(*init_inputs, **init_kwargs) File “C:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\xlm_roberta\tokenization_xlm_roberta.py”, line 168, in init self.sp_model.Load(str(vocab_file)) File "C:\oobabooga_windows\installer_files\env\lib\site-packages\sentencepiece_init.py", line 905, in Load return self.LoadFromFile(model_file) File “C:\oobabooga_windows\installer_files\env\lib\site-packages\sentencepiece_init_.py”, line 310, in LoadFromFile return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg) OSError: Not found: “None”: No such file or directory Error #2

During handling of the above exception, another exception occurred:

Traceback (most recent call last): File “C:\oobabooga_windows\text-generation-webui\[server.py](http://server.py/)”, line 67, in load_model_wrapper shared.model, shared.tokenizer = load_model(shared.model_name, loader) File “C:\oobabooga_windows\text-generation-webui\modules\[models.py](http://models.py/)”, line 82, in load_model tokenizer = load_tokenizer(model_name, model) File “C:\oobabooga_windows\text-generation-webui\modules\[models.py](http://models.py/)”, line 117, in load_tokenizer tokenizer = AutoTokenizer.from_pretrained(path_to_model, trust_remote_code=shared.args.trust_remote_code) File “C:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\tokenization_auto.py”, line 709, in from_pretrained return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs) File “C:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py”, line 1825, in from_pretrained return cls._from_pretrained( File “C:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py”, line 1857, in _from_pretrained slow_tokenizer = (cls.slow_tokenizer_class)._from_pretrained( File “C:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py”, line 1990, in _from_pretrained raise OSError( OSError: Unable to load vocabulary from file. Please check that the provided vocabulary is accessible and not corrupted.

### Logs

```shell
T-Systems-onsite/cross-en-de-roberta-sentence-transformer:
Traceback (most recent call last): File “C:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py”, line 1988, in from_pretrained tokenizer = cls(*init_inputs, **init_kwargs) File “C:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\xlm_roberta\tokenization_xlm_roberta.py”, line 168, in init self.sp_model.Load(str(vocab_file)) File "C:\oobabooga_windows\installer_files\env\lib\site-packages\sentencepiece_init.py", line 905, in Load return self.LoadFromFile(model_file) File “C:\oobabooga_windows\installer_files\env\lib\site-packages\sentencepiece_init_.py”, line 310, in LoadFromFile return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg) OSError: Not found: “None”: No such file or directory Error #2

During handling of the above exception, another exception occurred:

Traceback (most recent call last): File “C:\oobabooga_windows\text-generation-webui\[server.py](http://server.py/)”, line 67, in load_model_wrapper shared.model, shared.tokenizer = load_model(shared.model_name, loader) File “C:\oobabooga_windows\text-generation-webui\modules\[models.py](http://models.py/)”, line 82, in load_model tokenizer = load_tokenizer(model_name, model) File “C:\oobabooga_windows\text-generation-webui\modules\[models.py](http://models.py/)”, line 117, in load_tokenizer tokenizer = AutoTokenizer.from_pretrained(path_to_model, trust_remote_code=shared.args.trust_remote_code) File “C:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\tokenization_auto.py”, line 709, in from_pretrained return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs) File “C:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py”, line 1825, in from_pretrained return cls._from_pretrained( File “C:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py”, line 1857, in _from_pretrained slow_tokenizer = (cls.slow_tokenizer_class)._from_pretrained( File “C:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py”, line 1990, in _from_pretrained raise OSError( OSError: Unable to load vocabulary from file. Please check that the provided vocabulary is accessible and not corrupted.
```

### System Info

```shell
WIN11
i5 11300H
16 GB RAM
GPU 0 Intel iris Xe
GPU 1 Nvidia GeForce RTX 3050 Ti
480 GB SSD
```

**Comment by ollybrain** [comment]
when i test xlm-roberta-large-finetuned-conll03-german i get:

You
guten Tag

Assistant
fredag fleksibelvere samochody piłki realizowane populiariausi Tarptautini cztery Olav vtedy lördag Svo gniazd....and so on

(i use OpenAI to fix the some of Errors, but i don´t get a model to run?)

**Comment by Urammar** [comment]
Your error message suggests that C:\oobabooga_windows\installer_files\env\lib\site-packages\sentencepiece_init_.py does not exist, I think?

If you ran the one click installer, make sure you have also run the update windows .bat file to get the latest version.

Additionally, if you are downloading from HF, pasting the link in the webui will probably download incorrect models, you are better off going to the files page at HF and downloading the correct model versions manually.

**Comment by ollybrain** [comment]
Thx, and yes ist looks like the file is not there:

28.06.2023  14:08    <DIR>          sentencepiece
28.06.2023  14:08    <DIR>          sentencepiece-0.1.99.dist-info
28.06.2023  14:09    <DIR>          sentence_transformers
28.06.2023  14:09    <DIR>          sentence_transformers-2.2.2.dist-info

ok, so it is better to download directly from the HF site the module with "all" files. 

Yes, I have also noticed that sometimes not all files are downloaded. 

I will test it. Thanks a lot for now. I will report if it finally worked.

**Comment by ollybrain** [comment]
Yes it looks like it changed somethin in xlm-roberta-large-finetuned-conll03-german.... what a lovley german :)

You
guten Tag

Assistant
沒有 mặt Aus沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有


What i did for this change:

1. I delete the old xlm-roberta-large-finetuned-conll03-german direktory
2. create anew xlm-roberta-large-finetuned-conll03-german direktory
3. download all the fils of https://huggingface.co/xlm-roberta-large-finetuned-conll03-german/tree/main to the new direktory
4. start update_windows.bat (i think this time without any error)
5. start start_windows.bat
6. insert the https://huggingface.co/xlm-roberta-large-finetuned-conll03-german/tree/main module over the webui
7. got to tab chat an write Guten Tag..
8. look at the tasc manager and see that the GPU is working fine, but

Assistant
沒有 mặt Aus沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有沒有

;_)))
