### ISSUE TITLE
Error loading model with ExLlama

### ISSUE THREAD

**Issue by campio97** [oobabooga/text-generation-webui#2918]
### Describe the bug

when I try to load a model with the ExLlama loader the system returns error.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
2023-06-29 00:21:50 INFO:Loading llama-13b...
2023-06-29 00:21:52 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "C:\Users\pietr\OneDrive\Documenti\SoftwareAI\oobabooga_windows\text-generation-webui\server.py", line 67, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "C:\Users\pietr\OneDrive\Documenti\SoftwareAI\oobabooga_windows\text-generation-webui\modules\models.py", line 74, in load_model
    output = load_func_map[loader](model_name)
  File "C:\Users\pietr\OneDrive\Documenti\SoftwareAI\oobabooga_windows\text-generation-webui\modules\models.py", line 293, in ExLlama_HF_loader
    return ExllamaHF.from_pretrained(model_name)
  File "C:\Users\pietr\OneDrive\Documenti\SoftwareAI\oobabooga_windows\text-generation-webui\modules\exllama_hf.py", line 106, in from_pretrained
    return ExllamaHF(config)
  File "C:\Users\pietr\OneDrive\Documenti\SoftwareAI\oobabooga_windows\text-generation-webui\modules\exllama_hf.py", line 31, in __init__
    self.ex_model = ExLlama(self.ex_config)
  File "C:\Users\pietr\OneDrive\Documenti\SoftwareAI\oobabooga_windows\installer_files\env\lib\site-packages\exllama\model.py", line 735, in __init__
    self.embed_tokens.weight = nn.Parameter(tensors["model.embed_tokens.weight"])
KeyError: 'model.embed_tokens.weight'
----------------------------------------------------------------------------------------
2023-06-29 00:32:43 INFO:Loading llama-13b...
2023-06-29 00:32:43 WARNING:More than one .safetensors model has been found. The last one will be selected. It could be wrong.
2023-06-29 00:32:45 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "C:\Users\pietr\OneDrive\Documenti\SoftwareAI\oobabooga_windows\text-generation-webui\server.py", line 67, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "C:\Users\pietr\OneDrive\Documenti\SoftwareAI\oobabooga_windows\text-generation-webui\modules\models.py", line 74, in load_model
    output = load_func_map[loader](model_name)
  File "C:\Users\pietr\OneDrive\Documenti\SoftwareAI\oobabooga_windows\text-generation-webui\modules\models.py", line 286, in ExLlama_loader
    model, tokenizer = ExllamaModel.from_pretrained(model_name)
  File "C:\Users\pietr\OneDrive\Documenti\SoftwareAI\oobabooga_windows\text-generation-webui\modules\exllama.py", line 55, in from_pretrained
    model = ExLlama(config)
  File "C:\Users\pietr\OneDrive\Documenti\SoftwareAI\oobabooga_windows\installer_files\env\lib\site-packages\exllama\model.py", line 735, in __init__
    self.embed_tokens.weight = nn.Parameter(tensors["model.embed_tokens.weight"])
KeyError: 'model.embed_tokens.weight'
``` 

### Logs

```shell
2023-06-29 00:21:50 INFO:Loading llama-13b...
2023-06-29 00:21:52 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "C:\Users\pietr\OneDrive\Documenti\SoftwareAI\oobabooga_windows\text-generation-webui\server.py", line 67, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "C:\Users\pietr\OneDrive\Documenti\SoftwareAI\oobabooga_windows\text-generation-webui\modules\models.py", line 74, in load_model
    output = load_func_map[loader](model_name)
  File "C:\Users\pietr\OneDrive\Documenti\SoftwareAI\oobabooga_windows\text-generation-webui\modules\models.py", line 293, in ExLlama_HF_loader
    return ExllamaHF.from_pretrained(model_name)
  File "C:\Users\pietr\OneDrive\Documenti\SoftwareAI\oobabooga_windows\text-generation-webui\modules\exllama_hf.py", line 106, in from_pretrained
    return ExllamaHF(config)
  File "C:\Users\pietr\OneDrive\Documenti\SoftwareAI\oobabooga_windows\text-generation-webui\modules\exllama_hf.py", line 31, in __init__
    self.ex_model = ExLlama(self.ex_config)
  File "C:\Users\pietr\OneDrive\Documenti\SoftwareAI\oobabooga_windows\installer_files\env\lib\site-packages\exllama\model.py", line 735, in __init__
    self.embed_tokens.weight = nn.Parameter(tensors["model.embed_tokens.weight"])
KeyError: 'model.embed_tokens.weight'
-------------------------------------------------------------------------------------------------------
2023-06-29 00:32:43 INFO:Loading llama-13b...
2023-06-29 00:32:43 WARNING:More than one .safetensors model has been found. The last one will be selected. It could be wrong.
2023-06-29 00:32:45 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "C:\Users\pietr\OneDrive\Documenti\SoftwareAI\oobabooga_windows\text-generation-webui\server.py", line 67, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "C:\Users\pietr\OneDrive\Documenti\SoftwareAI\oobabooga_windows\text-generation-webui\modules\models.py", line 74, in load_model
    output = load_func_map[loader](model_name)
  File "C:\Users\pietr\OneDrive\Documenti\SoftwareAI\oobabooga_windows\text-generation-webui\modules\models.py", line 286, in ExLlama_loader
    model, tokenizer = ExllamaModel.from_pretrained(model_name)
  File "C:\Users\pietr\OneDrive\Documenti\SoftwareAI\oobabooga_windows\text-generation-webui\modules\exllama.py", line 55, in from_pretrained
    model = ExLlama(config)
  File "C:\Users\pietr\OneDrive\Documenti\SoftwareAI\oobabooga_windows\installer_files\env\lib\site-packages\exllama\model.py", line 735, in __init__
    self.embed_tokens.weight = nn.Parameter(tensors["model.embed_tokens.weight"])
KeyError: 'model.embed_tokens.weight'
```

### System Info

```shell
GPU: RTX 4090
CPU: Ryzen 7950x3D
Ram: 32gb
```

**Comment by xcaliber123** [comment]
Same problem. Have you found any solution?

**Comment by campio97** [comment]
No, i didn't find any solution yet

**Comment by xcaliber123** [comment]
> No, i didn't find any solution yet

Do you have GPU?
I think this Ex llma works only on GPU and not on CPU.
Because what I observed is that people who are posting videos of exllma on YouTube,are using high end NVIDIA GPU.

**Comment by xcaliber123** [comment]
> No, i didn't find any solution yet

Have you first installed the web UI in CPU mode? Or NVIDIA GPU mode?

**Comment by CRCODE22** [comment]
Same problem.

**Comment by viktor-ferenczi** [comment]
Same error with the recently released `meta-llama/Llama-2-13b-chat-hf` model.

Latest ooba 87926d03, cleanly installed today.

**Comment by campio97** [comment]
> > No, i didn't find any solution yet
> 
> Have you first installed the web UI in CPU mode? Or NVIDIA GPU mode?

I installed in NVIDIA GPU mode

**Comment by xms991** [comment]
@campio97 - Is the model you're trying to load quantized? 

I just found this thread because I was experiencing the same issue, but I realized that I was trying to load an fp16 .safetensors model using exllama, but exllama is designed for 4 bit GPTQ weights. 

Try loading the model using the Transformers loader instead and see if it works.

**Comment by Benstime** [comment]
Same error with the recently released meta-llama/Llama-2-13b-chat-hf model.

**Comment by Elwakeel-ah** [comment]
The same error but it has been solved with Transformers Model Loader
