### ISSUE TITLE
RuntimeError: expected scalar type Half but found Char

### ISSUE THREAD

**Issue by gameveloster** [oobabooga/text-generation-webui#2919]
### Describe the bug

Tried to train a LoRA using a raw text file, but training fails at the start with the error

> RuntimeError: expected scalar type Half but found Char

Is there something wrong with my settings?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Start Ooba and load the model `TheBloke_wizardLM-13B-1.0-fp16` with 8-bits quantization.
   `python server.py --listen --monkey-patch`
   ![image](https://github.com/oobabooga/text-generation-webui/assets/103383490/c40a6bc5-b38c-40f4-9ca9-a1f786463617)
2. Setup Training parameters as shown in image. Text data is from [here](https://github.com/bublint/ue5-llama-lora/blob/main/unreal_docs.txt).
   ![image](https://github.com/oobabooga/text-generation-webui/assets/103383490/c7f2842c-e18a-4266-9dd1-ab3246b86d13)
3. Press the button `Start LoRA Training`
4. Error appears in the terminal

### Logs

```shell
Exception in thread Thread-4 (threaded_run):
Traceback (most recent call last):
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/md0/text-generation-webui/modules/training.py", line 461, in threaded_run
    trainer.train()
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/trainer.py", line 1938, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/trainer.py", line 2759, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/trainer.py", line 2784, in compute_loss
    outputs = model(**inputs)
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 553, in forward
    return model_forward(*args, **kwargs)
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 541, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/peft/peft_model.py", line 707, in forward
    return self.base_model(
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 688, in forward
    outputs = self.model(
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 570, in forward
    layer_outputs = torch.utils.checkpoint.checkpoint(
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 566, in custom_forward
    return module(*inputs, output_attentions, None)
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 194, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/peft/tuners/lora.py", line 630, in forward
    result = F.linear(x, transpose(self.weight, self.fan_in_fan_out), bias=self.bias)
RuntimeError: expected scalar type Half but found Char
```

### System Info

```shell
Ubuntu 22.04
Two Nvidia RTX 3090 FE

accelerate==0.20.3
peft @ git+https://github.com/huggingface/peft@e45529b149c7f91ec1d4d82a5a152ef56c56cb94
transformers==4.30.2
```

**Comment by Nicolas99-9** [comment]
Same issue here, could you solve it?

**Comment by yclicc** [comment]
There's a workaround here https://github.com/huggingface/transformers/issues/25144 which worked for me. You need to edit the config.json of the downloaded model though.
