### ISSUE TITLE
Can't get ExLlama to work with multiple GPUs

### ISSUE THREAD

**Issue by thomasbidou** [oobabooga/text-generation-webui#2923]
### Describe the bug

Hi,

When loading a model (TheBloke/WizardLM-33B-V1.0-Uncensored-SuperHOT-8K-GPTQ) with ExLlama, the system only uses 1 GPU.
I got 3.
1x RTX 4000 8Gb
2x RTX A4000 16Gb

I can't get gpu-split to take effect.

The split work when loading a model via AUTO-GPT (TheBloke/WizardLM-33B-V1.0-Uncensored-GPTQ).

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Have 3 GPU's with a total of 40Gb and load a model via ExLlama

### Logs

```shell
2023-06-29 10:55:43 INFO:Loading TheBloke_WizardLM-33B-V1.0-Uncensored-SuperHOT-8K-GPTQ...
2023-06-29 10:55:51 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "K:\text-generation-webui\text-generation-webui\server.py", line 67, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "K:\text-generation-webui\text-generation-webui\modules\models.py", line 74, in load_model
    output = load_func_map[loader](model_name)
  File "K:\text-generation-webui\text-generation-webui\modules\models.py", line 286, in ExLlama_loader
    model, tokenizer = ExllamaModel.from_pretrained(model_name)
  File "K:\text-generation-webui\text-generation-webui\modules\exllama.py", line 55, in from_pretrained
    model = ExLlama(config)
  File "K:\text-generation-webui\installer_files\env\lib\site-packages\exllama\model.py", line 720, in __init__
    tensor = tensor.to(device, non_blocking = True)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 15.99 GiB total capacity; 15.06 GiB already allocated; 0 bytes free; 15.27 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### System Info

```shell
Epyc 7262
64Gb DDR4 3200Mhz
GPU0 RTX A4000 16GB
GPU1 RTX A4000 16GB
GPU2 RTX 4000 8GB
OS: Windows 11
```

**Comment by epolewski** [comment]
I had the same issue with 2x 3090's. I set my memory split to 8,20 and that balanced it between the two cards. Maybe play with setting the first memory allocation lower than you'd expect to workaround the bug? It still loads 16GB on each card with the 8,20 setting.

**Comment by thomasbidou** [comment]
You are right. When lowering the first GPU I can make it work.
Thanks a lot.

**Comment by BenJackGill** [comment]
+1.

I'm also seeing this bug.

I am renting 2 x RTX A6000 (each is 48GB VRAM / 31GB RAM / 8vCPU) and the only way I can get the other GPU to run is to use a 8,20 split.

**Comment by bootlegyaga** [comment]
Any update on this? I am also not able to use the function
Running 2 RTX3060 with 12GB VRAM each.

**Comment by RuntimeRacer** [comment]
I just figured out the actual command is `--gpu-split` of you're using ExLama: https://github.com/oobabooga/text-generation-webui#exllama
After I changed to this param everything worked again.

**Comment by nktice** [comment]
I have 2 GPUs - 
- AMD Radeon 7900XTX (24GB) and 
- AMD Radeon 6900XT (16GB)

The only loader I have working is exllama 
There's no problems using one GPU or the other on the own.  
[ and I can run SD on the 2nd card with Oobabooga on the 1st... ] 
When I try to use both (various splits), I get gibberish; 
Here's an example : 
```
beствуiatil hal Hal white--pher Ga-yyyerdtds clubsa " wh %% {-t-
```

And there's an error on the console that looks like this : 

```
Traceback (most recent call last):
  File "/home/n/text-generation-webui/modules/text_generation.py", line 344, in generate_reply_custom
    for reply in shared.model.generate_with_streaming(question, state):
  File "/home/n/text-generation-webui/modules/exllama.py", line 126, in generate_with_streaming
    token = self.generator.gen_single_token()
  File "/home/n/text-generation-webui/repositories/exllama/generator.py", line 362, in gen_single_token
    token, _ = self.batched_sample(logits,
  File "/home/n/text-generation-webui/repositories/exllama/generator.py", line 65, in batched_sample
    if logits.shape[0] == 1: return self.sample(logits, temperature, top_k, top_p, min_p, typical, num)
  File "/home/n/text-generation-webui/repositories/exllama/generator.py", line 162, in sample
    sampled_ind = torch.multinomial(top_probs, top_probs.shape[-1] if num == -1 else min(num, top_probs.shape[-1]))
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```
