### ISSUE TITLE
TypeError: PeftConfig.__init__() got an unexpected keyword argument 'dtype'

### ISSUE THREAD

**Issue by gameveloster** [oobabooga/text-generation-webui#2936]
### Describe the bug

I get the following error when trying to apply [a LoRA I created with Oobabooga](https://huggingface.co/gameveloster/ue5-llama-lora) to the model `TheBloke_wizardLM-13B-1.0-fp16`

```
TypeError: PeftConfig.__init__() got an unexpected keyword argument 'dtype'
```

What should i do? Is my LoRA bad?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Start Oobabooga
2. Load the model `TheBloke_wizardLM-13B-1.0-fp16` with `load-in-8bit` enabled.
3. Select the [LoRA](https://huggingface.co/gameveloster/ue5-llama-lora) and click on the button "Apply LoRAs"
   ![image](https://github.com/oobabooga/text-generation-webui/assets/103383490/1f2e550e-7d78-4dec-9258-e4b65d3d716a)
4. Error appears in the terminal

### Logs

```shell
2023-06-30 00:28:28 INFO:Loading TheBloke_wizardLM-13B-1.0-fp16...
2023-06-30 00:28:29 WARNING:The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:13<00:00,  4.56s/it]
2023-06-30 00:28:42 INFO:Loaded the model in 14.36 seconds.

2023-06-30 00:28:49 INFO:Applying the following LoRAs to TheBloke_wizardLM-13B-1.0-fp16: ue5-llama-lora
Traceback (most recent call last):
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "/mnt/md0/text-generation-webui/server.py", line 82, in load_lora_wrapper
    add_lora_to_model(selected_loras)
  File "/mnt/md0/text-generation-webui/modules/LoRA.py", line 17, in add_lora_to_model
    add_lora_transformers(lora_names)
  File "/mnt/md0/text-generation-webui/modules/LoRA.py", line 122, in add_lora_transformers
    shared.model = PeftModel.from_pretrained(shared.model, Path(f"{shared.args.lora_dir}/{lora_names[0]}"), adapter_name=lora_names[0], **params)
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/peft/peft_model.py", line 169, in from_pretrained
    PeftConfig.from_pretrained(model_id, subfolder=kwargs.get("subfolder", None), **kwargs).peft_type
  File "/home/gv/miniconda3/envs/textgen/lib/python3.10/site-packages/peft/utils/config.py", line 114, in from_pretrained
    config = cls(**kwargs)
TypeError: PeftConfig.__init__() got an unexpected keyword argument 'dtype'
```

### System Info

```shell
Ubuntu 22.04
2x Nvidia RTX 3090 FE

oobabooga/text-generation-webui @ 3c076c3c8096fa83440d701ba4d7d49606aaf61f

accelerate==0.20.3
bitsandbytes==0.39.1
peft @ git+https://github.com/huggingface/peft@e45529b149c7f91ec1d4d82a5a152ef56c56cb94
torch==2.0.1
torchaudio==2.0.2
torchvision==0.15.2
transformers==4.30.2
```

**Comment by VldmrB** [comment]
I had the same error - changing the loader from `GPTQ` to `exllama_HF` fixed it.  
In your case, the loader is `Transformers`, and I'm not even sure if models using that would be compatible with exllama_HF or not, but you can at least download a GPTQ version of the model and try that instead.
