### ISSUE TITLE
Failure to Launch: Gallery Extension throwing exception when loading gallery images 7/1/2023

### ISSUE THREAD

**Issue by LupoGrigi0** [oobabooga/text-generation-webui#2963]
### Describe the bug

Windows 11, using one click installer setup. the whole thing has been running great since I first installed it a couple weeks. ago. Generally every day I shut it down, run an update, and fire it up again via the .\update_windows.bat file and then launch the via the .\start_windows.bat file
I run these in a VSCode terminal window
The Only extension I have enabled at the moment is Gallery. 
Today (7/1) I update, and start and get the following...
```
2023-07-01 20:09:26 INFO:Loading the extension "gallery"...
Traceback (most recent call last):
  File "D:\Lupo\Source\AI\one-click-installers\text-generation-webui\server.py", line 1075, in <module>
    create_interface()
  File "D:\Lupo\Source\AI\one-click-installers\text-generation-webui\server.py", line 970, in create_interface
    extensions_module.create_extensions_block()
  File "D:\Lupo\Source\AI\one-click-installers\text-generation-webui\modules\extensions.py", line 162, in create_extensions_block
    extension.ui()
  File "D:\Lupo\Source\AI\one-click-installers\text-generation-webui\extensions\gallery\script.py", line 91, in ui
    samples=generate_html(),
  File "D:\Lupo\Source\AI\one-click-installers\text-generation-webui\extensions\gallery\script.py", line 71, in generate_html
    image_html = f'<img src="file/{get_image_cache(path)}">'
  File "D:\Lupo\Source\AI\one-click-installers\text-generation-webui\modules\html_generator.py", line 144, in get_image_cache
    img = make_thumbnail(Image.open(path))
  File "D:\Lupo\Source\AI\one-click-installers\text-generation-webui\modules\html_generator.py", line 132, in make_thumbnail
    image = ImageOps.fit(image, (350, 470), Image.ANTIALIAS)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
Press any key to continue . . . 
```
I have not added or removed any characters for several days.... and definitely no changes in character images.  "it worked yesterday"... it was running just fine, I literally had stopped the .\start_windows.bat ran update_windows.bat then .\start_windows and now it won't launch. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

have a list of about a dozen characters in your gallery...

### Logs

```shell
no logs where generated.
```

### System Info

```shell
OS Name	Microsoft Windows 11 Home
Version	10.0.22621 Build 22621
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	GREYWOLF
System Manufacturer	Micro-Star International Co., Ltd.
System Model	MS-7C83
System Type	x64-based PC
System SKU	Default string
Processor	Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz, 2901 Mhz, 8 Core(s), 16 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. 1.20, 7/23/2020
SMBIOS Version	3.2
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Micro-Star International Co., Ltd.
BaseBoard Product	B460M PRO-VDH WIFI (MS-7C83)
BaseBoard Version	1.0
Platform Role	Desktop
Secure Boot State	Off
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume5
Locale	United States
Hardware Abstraction Layer	Version = "10.0.22621.1413"
User Name	GREYWOLF\Lupo
Time Zone	Pacific Daylight Time
Installed Physical Memory (RAM)	48.0 GB
Total Physical Memory	47.9 GB
Available Physical Memory	37.0 GB
Total Virtual Memory	54.9 GB
Available Virtual Memory	39.8 GB
Page File Space	7.00 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, UEFI Code Readonly, Mode Based Execution Control, APIC Virtualization
Virtualization-based security Services Configured	
Virtualization-based security Services Running	
Windows Defender Application Control policy	Enforced
Windows Defender Application Control user mode policy	Off
Device Encryption Support	Elevation Required to View
A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```

**Comment by LupoGrigi0** [comment]
Trying a few things... Rebooting the PC had no effect. Deleting everything in the cache directory did nothing. then deleting everything in the logs directory had no effect. Emptying out the characters directory DID allow the UI to load. Removing "Gallery" from     'chat_default_extensions': ['api'],
in shared.py line 64 allowed the UI to launch. (after replacing the contents of the characters and logs directories)

-----------------------AH, found it!  it appears there was a change to PILImage.. that Gallery depends on----------
the answer is right on the tin as the saying goes:
   image = ImageOps.fit(image, (350, 470), Image.ANTIALIAS)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

**Comment by jllllll** [comment]
This has been fixed: https://github.com/oobabooga/text-generation-webui/pull/2954
