### ISSUE TITLE
No module named gradio

### ISSUE THREAD

**Issue by HighSteam** [oobabooga/text-generation-webui#2964]
```
*******************************************************************
* WARNING: You haven't downloaded any model yet.
* Once the web UI launches, head over to the bottom of the "Model" tab and download one.
*******************************************************************


Traceback (most recent call last):
  File "/home/ali/Desktop/oobabooga_linux./oobabooga_linux/text-generation-webui/server.py", line 12, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

```

I then did pip install gradio and still the same error occured. Running start_linux.sh

**Comment by 877kc6** [comment]
Yes, I also encountered this problem.

**Comment by InsanityGamer** [comment]
> Same here.
> 
> Here's a workaround: Add a `requirements.txt`:
> 
> ```
> gradio
> psutil
> markdown
> transformers
> accelerate
> peft
> ```
> 
> Add `pip install -r requirements.txt` to the `start_linux.sh` here:
> 
> ```
> # activate installer env
> source "$CONDA_ROOT_PREFIX/etc/profile.d/conda.sh" # otherwise conda complains about 'shell not initialized' (needed when running in a script)
> conda activate "$INSTALL_ENV_DIR"
> 
> # install the necessary Python packages
> pip install -r requirements.txt
> 
> # setup installer env
> python webui.py
> ```

This worked Great! I found that i also needed to add datasets to requirements.txt

``` echo datasets >> requirements.txt```

**Comment by stobbsc** [comment]
I'm having the same issue but in MacOS
`(textgen) Rebeccas-iMac:text-generation-webui stobbsc$ ./start_macos.sh
Traceback (most recent call last):
  File "/Users/stobbsc/text-generation-webui/server.py", line 13, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'`

When I run "pip show gradio" I get:
`Name: gradio
Version: 3.48.0
Summary: Python library for easily interacting with trained machine learning models
Home-page: 
Author: 
Author-email: Abubakar Abid <team@gradio.app>, Ali Abid <team@gradio.app>, Ali Abdalla <team@gradio.app>, Dawood Khan <team@gradio.app>, Ahsen Khaliq <team@gradio.app>, Pete Allen <team@gradio.app>, Ömer Faruk Özdemir <team@gradio.app>
License: 
Location: /Users/stobbsc/anaconda3/envs/textgen/lib/python3.10/site-packages
Requires: aiofiles, altair, fastapi, ffmpy, gradio-client, httpx, huggingface-hub, importlib-resources, jinja2, markupsafe, matplotlib, numpy, orjson, packaging, pandas, pillow, pydantic, pydub, python-multipart, pyyaml, requests, semantic-version, typing-extensions, uvicorn, websockets
Required-by: `

When I run "pip -V" I get:
`pip 23.2.1 from /Users/stobbsc/anaconda3/envs/textgen/lib/python3.10/site-packages/pip (python 3.10)`

Any thoughts, this is killing me :-(
