### ISSUE TITLE
Exllama low context issue

### ISSUE THREAD

**Issue by Galaxia-mk** [oobabooga/text-generation-webui#2971]
### Describe the bug

Whenever i try to load a model using Exllama with a low context size.
I get the error: "RuntimeError: start (0) + length (2049) exceeds dimension size (2048)"

And sometimes it gives me another error that makes it impossible to load any models again:

"RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions."

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

For me it shows up every time I have an LLM respond with 3k, 4k or 6k. It seemingly wants to go to a number around 7921 context size. I run Linux Kubuntu if that matters.

### Screenshot

![Screenshot_20230702_172218](https://github.com/oobabooga/text-generation-webui/assets/110353717/e054c280-3307-419c-a518-6ea5ba22f72c)

### Logs

```shell
Traceback (most recent call last):
  File "/home/galaxia/text-generation-webui/modules/text_generation.py", line 323, in generate_reply_custom
    for reply in shared.model.generate_with_streaming(question, state):
  File "/home/galaxia/text-generation-webui/modules/exllama.py", line 81, in generate_with_streaming
    self.generator.gen_begin_reuse(ids)
  File "/home/galaxia/miniconda3/envs/textgen/lib/python3.10/site-packages/exllama/generator.py", line 193, in gen_begin_reuse
    self.gen_begin(in_tokens, max_chunk)
  File "/home/galaxia/miniconda3/envs/textgen/lib/python3.10/site-packages/exllama/generator.py", line 177, in gen_begin
    self.model.forward(self.sequence[:, a:b], self.cache, preprocess_only = True, lora = self.lora)
  File "/home/galaxia/miniconda3/envs/textgen/lib/python3.10/site-packages/exllama/model.py", line 860, in forward
    hidden_states = decoder_layer.forward(hidden_states, cache, buffers[device], lora)
  File "/home/galaxia/miniconda3/envs/textgen/lib/python3.10/site-packages/exllama/model.py", line 466, in forward
    hidden_states = self.self_attn.forward(hidden_states, cache, buffer, lora)
  File "/home/galaxia/miniconda3/envs/textgen/lib/python3.10/site-packages/exllama/model.py", line 389, in forward
    new_keys = cache.key_states[self.index].narrow(2, past_len, q_len)
RuntimeError: start (4096) + length (2048) exceeds dimension size (6000).
Output generated in 1.86 seconds (0.00 tokens/s, 0 tokens, context 7921, seed 488019736)
```

### System Info

```shell
Operating system: Kubuntu 22.04

GPU: Nvidia GTX A5000 GB24
```

**Comment by Galaxia-mk** [comment]
Never mind I found what the issue was. I had to change "Truncate the prompt up to this length" to the same number as the max_seq_length and then reload the model. Sorry false alarm
