### ISSUE TITLE
RuntimeError: expected scalar type Float but found Half, when trying to use trained LoRA

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [oobabooga/text-generation-webui#2980]
### Describe the bug

Hello.

I've downloaded this model [huggyllama-llama-13b](https://huggingface.co/huggyllama/llama-13b)  launched webui in 8bit mode and trained LoRa with my dataset as raw file. I've used default parameters.

When I try to generate text with my lora, I receive this error:

    Last login: Mon Jul  3 01:56:15 2023 from 91.231.66.154
    output = old_forward(*args, **kwargs)
      File "/root/one-click-installers/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 578, in forward
    layer_outputs = decoder_layer(
      File "/root/one-click-installers/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
      File "/root/one-click-installers/installer_files/env/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
      File "/root/one-click-installers/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
      File "/root/one-click-installers/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
      File "/root/one-click-installers/installer_files/env/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
      File "/root/one-click-installers/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 194, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
      File "/root/one-click-installers/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
      File "/root/one-click-installers/installer_files/env/lib/python3.10/site-packages/peft/tuners/lora.py", line 954, in forward
    self.lora_A[self.active_adapter](self.lora_dropout[self.active_adapter](x))
      File "/root/one-click-installers/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
      File "/root/one-click-installers/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
    RuntimeError: expected scalar type Float but found Half

What I did wrong? Everything in default mode. Model is loaded with `Transformers` loader.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Train Lora with raw file with model name that I provided in 8bit mode.

### Logs

```shell
Logs are provided above
```

### System Info

```shell
GPU - RTX A6000 - 49 GB VRAM
CPU - Xeon® Gold 6248R
RAM - 50 GB
```

**Comment by QHYAHFY** [comment]
please contact AUTHOR by QQ：1509770203

**Comment by harpomaxx** [comment]
I got the same error when trying to finetune the model [lmsys-vicuna-7B-v1.3](https://huggingface.co/lmsys/vicuna-7b-v1.3) loaded in 8bits. When I load the model using 4bits. It works OK.

I have a pretty old hardware:

```
GPU - Titan V - 12 GB VRAM
CPU - Ryzen 7 2700
RAM - 32 GB
```

The error message.
```
2023-07-09 21:31:37 INFO:Starting training...
/home/harpo/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py:321: UserWarning: MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
Exception in thread Thread-5 (threaded_run):
Traceback (most recent call last):
  File "/home/harpo/miniconda3/envs/textgen/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/harpo/miniconda3/envs/textgen/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/harpo/text-generation-webui/modules/training.py", line 471, in threaded_run
    trainer.train()
  File "/home/harpo/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/home/harpo/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/trainer.py", line 1938, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/harpo/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/trainer.py", line 2770, in training_step
    self.accelerator.backward(loss)
  File "/home/harpo/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/accelerator.py", line 1819, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "/home/harpo/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/harpo/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/harpo/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/home/harpo/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 157, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/home/harpo/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/harpo/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/home/harpo/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 479, in backward
    grad_A = torch.matmul(grad_output, CB).view(ctx.grad_shape).to(ctx.dtype_A)
RuntimeError: expected scalar type Half but found Float
2023-07-09 21:31:38 INFO:Training complete, saving...
2023-07-09 21:31:40 INFO:Training complete!
^CTraceback (most recent call last):
  File "/home/harpo/text-generation-webui/server.py", line 1028, in <module>
    time.sleep(0.5)
KeyboardInterrupt
```

**Comment by SuperMasterBlasterLaser** [comment]
I have ticked 8-bit mode flag, and it started to work as I expected.

**Comment by HaoYang0123** [comment]
> I have ticked 8-bit mode flag, in models settings, and it started to work as I expected.

How to ticked 8-bit model flag?

**Comment by SuperMasterBlasterLaser** [comment]
@HaoYang0123 Open model tab, load model with Transformers and there should be 8 bit mode. Tick it and reload it.
