### ISSUE TITLE
cant get output

### ISSUE THREAD

**Issue by doctaf** [oobabooga/text-generation-webui#2990]
### Describe the bug

anytime i send a prompt for inference, i get the following error in the console:

Traceback (most recent call last):
  File "C:\ai_work\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\ai_work\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\ai_work\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\ai_work\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "C:\ai_work\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\ai_work\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\ai_work\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\ai_work\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\ai_work\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "C:\ai_work\oobabooga_windows\text-generation-webui\modules\chat.py", line 299, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, shared.history, state, regenerate, _continue, loading_message=True)):
  File "C:\ai_work\oobabooga_windows\text-generation-webui\modules\chat.py", line 284, in generate_chat_reply
    for history in chatbot_wrapper(text, history, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "C:\ai_work\oobabooga_windows\text-generation-webui\modules\chat.py", line 201, in chatbot_wrapper
    prompt = apply_extensions('custom_generate_chat_prompt', text, state, **kwargs)
  File "C:\ai_work\oobabooga_windows\text-generation-webui\modules\extensions.py", line 193, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "C:\ai_work\oobabooga_windows\text-generation-webui\modules\extensions.py", line 80, in _apply_custom_generate_chat_prompt
    return extension.custom_generate_chat_prompt(text, state, **kwargs)
  File "C:\ai_work\oobabooga_windows\text-generation-webui\extensions\EdgeGPT\script.py", line 135, in custom_generate_chat_prompt
    max_length = min(get_max_prompt_length(state), state['chat_prompt_size'])
KeyError: 'chat_prompt_size'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

load model 
input prompt?

### Logs

```shell
Traceback (most recent call last):
  File "C:\ai_work\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\ai_work\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\ai_work\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\ai_work\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "C:\ai_work\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\ai_work\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\ai_work\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\ai_work\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\ai_work\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "C:\ai_work\oobabooga_windows\text-generation-webui\modules\chat.py", line 299, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, shared.history, state, regenerate, _continue, loading_message=True)):
  File "C:\ai_work\oobabooga_windows\text-generation-webui\modules\chat.py", line 284, in generate_chat_reply
    for history in chatbot_wrapper(text, history, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "C:\ai_work\oobabooga_windows\text-generation-webui\modules\chat.py", line 201, in chatbot_wrapper
    prompt = apply_extensions('custom_generate_chat_prompt', text, state, **kwargs)
  File "C:\ai_work\oobabooga_windows\text-generation-webui\modules\extensions.py", line 193, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "C:\ai_work\oobabooga_windows\text-generation-webui\modules\extensions.py", line 80, in _apply_custom_generate_chat_prompt
    return extension.custom_generate_chat_prompt(text, state, **kwargs)
  File "C:\ai_work\oobabooga_windows\text-generation-webui\extensions\EdgeGPT\script.py", line 135, in custom_generate_chat_prompt
    max_length = min(get_max_prompt_length(state), state['chat_prompt_size'])
KeyError: 'chat_prompt_size'
```

### System Info

```shell
windows, nvidia p100-16gb
```

**Comment by juangea** [comment]
I have the same problem, 3090 on windows 11

**Comment by swizzcheeze** [comment]
3090 win 11 here too
