### ISSUE TITLE
Need help with "IndexError: list index out of range" For "oobabooga"

### ISSUE THREAD

**Issue by AkumiShindo** [oobabooga/text-generation-webui#2995]
### Describe the bug

Traceback
IndexError: list index out of range

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I have tried searching for similar problems as this, but I don't really understand a lot of it for the most part. I am completely new to all of this, and a lot of search results I have found on this topic are people already know about a lot of the technical side of things. So if there's any mention of coding or anything like it, it would be nice to what I should click on and where to add it.

I do have python and I tried different settings in the Instruction template but nothing seem to work (Default is Alpaca). I don't know if I'm looking at the guides for my problem in particular or not, or if there's something I'm just missing or just a simple editing error. Any help will be appreciated, thank you.

Also, I'll be happy to provide any further info if needed to help solve this. I'm also not really sure what all else I should add here.

The only thing I ever tried was this:

my_list = [1,2,3]
print(my_list[2])

Then I ran it through the "cmd" of the folder location that it was in with python. But nothing happened, the results were still the same. 

### Screenshot

![Screenshot_4](https://github.com/oobabooga/text-generation-webui/assets/138536241/b9f882ef-6604-496a-bdc9-a616b0b79acd)

### Logs

```shell
Traceback (most recent call last):
  File "D:\shind\Desktop\oobabooga_windows\text-generation-webui\modules\callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "D:\shind\Desktop\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 289, in generate_with_callback
    shared.model.generate(**kwargs)
  File "D:\shind\Desktop\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\modeling\_base.py", line 422, in generate
    with torch.inference_mode(), torch.amp.autocast(device_type=self.device.type):
  File "D:\shind\Desktop\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\modeling\_base.py", line 411, in device
    device = [d for d in self.hf_device_map.values() if d not in {'cpu', 'disk'}][0]
IndexError: list index out of range
Output generated in 0.67 seconds (0.00 tokens/s, 0 tokens, context 37, seed 1461913445)
```

### System Info

```shell
Processor	AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx     2.30 GHz
Installed RAM	16.0 GB (15.4 GB usable)
System type	64-bit operating system, x64-based processor
NVIDIA GeForce GTX 1650
```

**Comment by noacktexas** [comment]
Also having the same error

**Comment by xiangtaowong** [comment]
same error

**Comment by xiangtaowong** [comment]
@AkumiShindo  I met the same error, did you save it?

**Comment by DuFFie88** [comment]
same error what the hell?
