### ISSUE TITLE
Oobabooga is completely broken at least on windows

### ISSUE THREAD

**Issue by goodglitch** [oobabooga/text-generation-webui#3003]
### Describe the bug

After running windows_update.bat I can not load most of the models. The rest of the model that oobabooga manages to load return 'NoneType' as output somewhere in the process that breaks the code. I tried reinstall app with oobabooga_windows.zip, but nothing changes.

Here is the sample output for ggml model with llama.cpp.

2023-07-04 16:12:36 INFO:Loading Wizard-Vicuna-13B-Uncensored.ggmlv3.q5_K_M.bin...
2023-07-04 16:12:36 INFO:llama.cpp weights detected: models\Wizard-Vicuna-13B-Uncensored.ggmlv3.q5_K_M.bin

2023-07-04 16:12:36 INFO:Cache capacity is 0 bytes
2023-07-04 16:12:36 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "C:\AI\oobabooga_windows\text-generation-webui\server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "C:\AI\oobabooga_windows\text-generation-webui\modules\models.py", line 74, in load_model
    output = load_func_map[loader](model_name)
  File "C:\AI\oobabooga_windows\text-generation-webui\modules\models.py", line 255, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
  File "C:\AI\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 47, in from_pretrained
    'seed': int(shared.args.llama_cpp_seed),
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

Exception ignored in: <function LlamaCppModel.__del__ at 0x000001A908661240>
Traceback (most recent call last):
  File "C:\AI\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 29, in __del__
    self.model.__del__()
AttributeError: 'LlamaCppModel' object has no attribute 'model'

Here is the sample of output for gptq model with exllama:

2023-07-04 16:25:35 INFO:Loading TheBloke_Wizard-Vicuna-13B-Uncensored-SuperHOT-8K-GPTQ...
2023-07-04 16:25:39 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "C:\AI\oobabooga_windows\text-generation-webui\server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "C:\AI\oobabooga_windows\text-generation-webui\modules\models.py", line 74, in load_model
    output = load_func_map[loader](model_name)
  File "C:\AI\oobabooga_windows\text-generation-webui\modules\models.py", line 286, in ExLlama_loader
    model, tokenizer = ExllamaModel.from_pretrained(model_name)
  File "C:\AI\oobabooga_windows\text-generation-webui\modules\exllama.py", line 67, in from_pretrained
    model = ExLlama(config)
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\exllama\model.py", line 751, in __init__
    t = torch.arange(self.config.max_seq_len, device = device, dtype = torch.float32)
TypeError: arange() received an invalid combination of arguments - got (NoneType, dtype=torch.dtype, device=str), but expected one of:
 * (Number end, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (Number start, Number end, *, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (Number start, Number end, Number step, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)

AutoGPTQ seems to load model but when you try to submit anything you get:

2023-07-04 16:27:38 INFO:Loading TheBloke_Wizard-Vicuna-13B-Uncensored-SuperHOT-8K-GPTQ...
2023-07-04 16:27:38 INFO:The AutoGPTQ params are: {'model_basename': 'wizard-vicuna-13b-uncensored-superhot-8k-GPTQ-4bit-128g.no-act.order', 'device': 'cuda:0', 'use_triton': None, 'inject_fused_attention': True, 'inject_fused_mlp': True, 'use_safetensors': True, 'trust_remote_code': None, 'max_memory': None, 'quantize_config': None, 'use_cuda_fp16': True}
2023-07-04 16:27:39 WARNING:The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
2023-07-04 16:27:40 WARNING:The safetensors archive passed at models\TheBloke_Wizard-Vicuna-13B-Uncensored-SuperHOT-8K-GPTQ\wizard-vicuna-13b-uncensored-superhot-8k-GPTQ-4bit-128g.no-act.order.safetensors does not contain metadata. Make sure to save your model with the `save_pretrained` method. Defaulting to 'pt' metadata.
2023-07-04 16:27:44 WARNING:skip module injection for FusedLlamaMLPForQuantizedModel not support integrate without triton yet.
2023-07-04 16:27:44 INFO:Loaded the model in 5.70 seconds.

Traceback (most recent call last):
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\AI\oobabooga_windows\text-generation-webui\modules\ui.py", line 146, in gather_interface_values
    with open(Path(f'logs/session_{shared.get_mode()}_autosave.json'), 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs\\session_chat_autosave.json'
Traceback (most recent call last):
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "C:\AI\oobabooga_windows\text-generation-webui\modules\chat.py", line 304, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True)):
  File "C:\AI\oobabooga_windows\text-generation-webui\modules\chat.py", line 289, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "C:\AI\oobabooga_windows\text-generation-webui\modules\chat.py", line 172, in chatbot_wrapper
    stopping_strings = get_stopping_strings(state)
  File "C:\AI\oobabooga_windows\text-generation-webui\modules\chat.py", line 135, in get_stopping_strings
    state['turn_template'].split('<|user-message|>')[1].split('<|bot|>')[0] + '<|bot|>',
AttributeError: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\AI\oobabooga_windows\text-generation-webui\modules\ui.py", line 146, in gather_interface_values
    with open(Path(f'logs/session_{shared.get_mode()}_autosave.json'), 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs\\session_chat_autosave.json'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Fresh oobabooga download or run windows_updatr.bat on existing app.

### Logs

```shell
See above.
```

### System Info

```shell
OS: Windows 10
CPU: Ryzen 5950x
GPU: RTX 3090
RAM: 32Gb
```

**Comment by leuchtetgruen** [comment]
Same on Linux

**Comment by Culpeo** [comment]
I'm getting another error on ExLlama / Runpod, interestingly. Maybe it is because I'm using a network volume, or maybe because I'm running on two GPUs...

2023-07-04 14:29:35 INFO:Loading TheBloke_airoboros-65B-gpt4-1.4-GPTQ...
bin /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so
Traceback (most recent call last):
  File "/workspace/text-generation-webui/server.py", line 1156, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/workspace/text-generation-webui/modules/models.py", line 74, in load_model
    output = load_func_map[loader](model_name)
  File "/workspace/text-generation-webui/modules/models.py", line 286, in ExLlama_loader
    model, tokenizer = ExllamaModel.from_pretrained(model_name)
  File "/workspace/text-generation-webui/modules/exllama.py", line 59, in from_pretrained
    config.calculate_rotary_embedding_base()
AttributeError: 'ExLlamaConfig' object has no attribute 'calculate_rotary_embedding_base'

**Comment by HazySkies** [comment]
Can confirm this is the same on Linux Mint:
```
(base) hazyskies@Hazy-LM:~/oobabooga_linux$ ./start_linux.sh
bin /home/hazyskies/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
2023-07-05 14:49:27 INFO:Loading ggml-q4_1.bin...
2023-07-05 14:49:27 INFO:llama.cpp weights detected: models/ggml-q4_1.bin

2023-07-05 14:49:27 INFO:Cache capacity is 0 bytes
llama.cpp: loading model from models/ggml-q4_1.bin
error loading model: unexpectedly reached end of file
llama_load_model_from_file: failed to load model
Traceback (most recent call last):
  File "/home/hazyskies/oobabooga_linux/text-generation-webui/server.py", line 1154, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/hazyskies/oobabooga_linux/text-generation-webui/modules/models.py", line 74, in load_model
    output = load_func_map[loader](model_name)
  File "/home/hazyskies/oobabooga_linux/text-generation-webui/modules/models.py", line 256, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
  File "/home/hazyskies/oobabooga_linux/text-generation-webui/modules/llamacpp_model.py", line 55, in from_pretrained
    result.model = Llama(**params)
  File "/home/hazyskies/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/llama_cpp/llama.py", line 290, in __init__
    assert self.model is not None
AssertionError
Exception ignored in: <function Llama.__del__ at 0x7fba81b89c60>
Traceback (most recent call last):
  File "/home/hazyskies/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/llama_cpp/llama.py", line 1440, in __del__
    if self.ctx is not None:
AttributeError: 'Llama' object has no attribute 'ctx'
Exception ignored in: <function LlamaCppModel.__del__ at 0x7fba81b157e0>
Traceback (most recent call last):
  File "/home/hazyskies/oobabooga_linux/text-generation-webui/modules/llamacpp_model.py", line 29, in __del__
    self.model.__del__()
AttributeError: 'LlamaCppModel' object has no attribute 'model'
```
Also, I know I'm using (base) rather than an activated/exclusive environment. Was feeling somewhat lazy and wasn't sure it'd interfere with the setup script.
