### ISSUE TITLE
[TEXT-GEN-WEBUI SERVICE TERMINATED]

### ISSUE THREAD

**Issue by ghost** [oobabooga/text-generation-webui#3007]
### Describe the bug

I don't know if this is a common occurrence or just me, but I can use the notebook here: https://colab.research.google.com/drive/18L3akiVE8Y6KKjd8TdPlvadTsQAqXh73#scrollTo=T6oyrr4X0wc2

to use SillyTavern (by ticking Get API), but the error in the title appears when I just want the webui (Gradio).
I leave everything else as defaults

I stand corrected. I can't even connect using SillyTavern. Below is the errors being printed.

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

Open up colab, leave everything default, then click the play button
For SillyTavern issue: Run after ticking Get API box

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/138266623/ed222403-c65d-45cc-9828-afe02d9176df)

### Logs

For the SillyTavern issue:
```shell
Running from source
SillyTavern 1.8.1 'main' (6770ccbe)
Migrating Novel key...
Writing updated settings.json...
Generating thumbnails cache. Please wait...
2023-07-04 21:01:57.397370: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
bin /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so
Done! Generated: 22 preview images
Launching...
SillyTavern is listening on: http://0.0.0.0:7860/

0.0.0.0 means SillyTavern is listening on all network interfaces (Wi-Fi, LAN, localhost). If you want to limit it only to internal localhost (127.0.0.1), change the setting in config.conf to “listen=false”

INFO:Loading settings from /content/text-generation-webui/cache/Anon-san-settings-colab.json...
INFO:Loading PygmalionCoT-7b...
Loading checkpoint shards: 100% 7/7 [01:05<00:00,  9.39s/it]
INFO:Loaded the model in 74.63 seconds.

INFO:Loading the extension "complex_memory"...
INFO:Loading the extension "gallery"...
INFO:server listening on 127.0.0.1:5005
--Unable to load complex memories for character None.  filename: extensions/complex_memory/saved_memories.json.  Using defaults.
Traceback (most recent call last):
  File "/content/text-generation-webui/extensions/api/util.py", line 61, in _start_cloudflared
    public_url = _run_cloudflared(port, port + 1)
  File "/usr/local/lib/python3.10/dist-packages/flask_cloudflared.py", line 75, in _run_cloudflared
    cloudflared = subprocess.Popen([executable, 'tunnel', '--url', 'http://127.0.0.1/:' + str(port), '--metrics', '127.0.0.1:' + str(metrics_port)], stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 26] Text file busy: '/tmp/cloudflared-linux-amd64'
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /content/text-generation-webui/server.py:997 in <module>                     │
│                                                                              │
│    994 │   │   })                                                            │
│    995 │                                                                     │
│    996 │   # Launch the web UI                                               │
│ ❱  997 │   create_interface()                                                │
│    998 │   while True:                                                       │
│    999 │   │   time.sleep(0.5)                                               │
│   1000 │   │   if shared.need_restart:                                       │
│                                                                              │
│ /content/text-generation-webui/server.py:901 in create_interface             │
│                                                                              │
│    898 │   │   extensions_module.create_extensions_tabs()                    │
│    899 │   │                                                                 │
│    900 │   │   # Extensions block                                            │
│ ❱  901 │   │   extensions_module.create_extensions_block()                   │
│    902 │                                                                     │
│    903 │   # Launch the interface                                            │
│    904 │   shared.gradio['interface'].queue()                                │
│                                                                              │
│ /content/text-generation-webui/modules/extensions.py:153 in                  │
│ create_extensions_block                                                      │
│                                                                              │
│   150 │   │   │   │   extension, name = row                                  │
│   151 │   │   │   │   display_name = getattr(extension, 'params', {}).get('d │
│   152 │   │   │   │   gr.Markdown(f"\n### {display_name}")                   │
│ ❱ 153 │   │   │   │   extension.ui()                                         │
│   154                                                                        │
│   155                                                                        │
│   156 def create_extensions_tabs():                                          │
│                                                                              │
│ /content/text-generation-webui/extensions/gallery/script.py:91 in ui         │
│                                                                              │
│   88 │   │   gr.HTML(value="<style>" + generate_css() + "</style>")          │
│   89 │   │   gallery = gr.Dataset(components=[gr.HTML(visible=False)],       │
│   90 │   │   │   │   │   │   │    label="",                                  │
│ ❱ 91 │   │   │   │   │   │   │    samples=generate_html(),                   │
│   92 │   │   │   │   │   │   │    elem_classes=["character-gallery"],        │
│   93 │   │   │   │   │   │   │    samples_per_page=50                        │
│   94 │   │   │   │   │   │   │    )                                          │
│                                                                              │
│ /content/text-generation-webui/extensions/gallery/script.py:71 in            │
│ generate_html                                                                │
│                                                                              │
│   68 │   │   │                                                               │
│   69 │   │   │   for path in [Path(f"characters/{character}.{extension}") fo │
│   70 │   │   │   │   if path.exists():                                       │
│ ❱ 71 │   │   │   │   │   image_html = f'<img src="file/{get_image_cache(path │
│   72 │   │   │   │   │   break                                               │
│   73 │   │   │                                                               │
│   74 │   │   │   container_html += f'{image_html} <span class="character-nam │
│                                                                              │
│ /content/text-generation-webui/modules/html_generator.py:150 in              │
│ get_image_cache                                                              │
│                                                                              │
│   147 │                                                                      │
│   148 │   mtime = os.stat(path).st_mtime                                     │
│   149 │   if (path in image_cache and mtime != image_cache[path][0]) or (pat │
│ ❱ 150 │   │   img = make_thumbnail(Image.open(path))                         │
│   151 │   │   output_file = Path(f'cache/{path.name}_cache.png')             │
│   152 │   │   img.convert('RGB').save(output_file, format='PNG')             │
│   153 │   │   image_cache[path] = [mtime, output_file.as_posix()]            │
│                                                                              │
│ /content/text-generation-webui/modules/html_generator.py:138 in              │
│ make_thumbnail                                                               │
│                                                                              │
│   135 def make_thumbnail(image):                                             │
│   136 │   image = image.resize((350, round(image.size[1] / image.size[0] * 3 │
│   137 │   if image.size[1] > 470:                                            │
│ ❱ 138 │   │   image = ImageOps.fit(image, (350, 470), Image.ANTIALIAS)       │
│   139 │                                                                      │
│   140 │   return image                                                       │
│   141                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```
Above this error:
###Copy Google Colab's Endpoint IP###
Endpoint IP: XXXXX

###SillyTavern LINK###
your url is: XXXXXXX

I plug the endpoint IP into the sillytavern link, and it opens a SillyTavern page (I have it listening for a connection), but it won't connect. I'm not sure why. I don't really have good output to provide.

### System Info

```shell
It's Google Colab.
```

**Comment by baiker9999** [comment]
![image](https://github.com/oobabooga/text-generation-webui/assets/138266623/a7d33559-4771-4fdf-9ea4-027a7493ceb0)

Huh. This might be the answer.

**Comment by UBCToad** [comment]
The specific error (module 'PIL.Image' has no attribute 'ANTIALIAS') has been resolved in commit, https://github.com/oobabooga/text-generation-webui/pull/2954 .
See Issues:
https://github.com/oobabooga/text-generation-webui/issues/2958#issue-1784289529  (Closed)
https://github.com/oobabooga/text-generation-webui/issues/2963#issue-1784412698  (Still Open?)

In the colab referenced I can see that the old_ooba variable forces use of an older commit which doesn't include the fix.
I expect if you update the colab to use a fix which does include this fix you will encounter a problem with the complex_memory extension as reported here: https://github.com/theubie/complex_memory/issues/17#issue-1790553488
