### ISSUE TITLE
Unable to load any model

### ISSUE THREAD

**Issue by MikeAW2010** [oobabooga/text-generation-webui#3008]
### Describe the bug

I am using a Windows 11 Desktop.

When I attempt to load any model using the GPTQ-for-LLaMa or llama.cpp Model loader, I am receiving the following errors:

`Traceback (most recent call last): File “D:\AI\Clients\oobabooga_windows\text-generation-webui\[server.py](http://server.py/)”, line 68, in load_model_wrapper shared.model, shared.tokenizer = load_model(shared.model_name, loader) File “D:\AI\Clients\oobabooga_windows\text-generation-webui\modules\[models.py](http://models.py/)”, line 74, in load_model output = load_func_map[loader](http://127.0.0.1:7860/model_name) File “D:\AI\Clients\oobabooga_windows\text-generation-webui\modules\[models.py](http://models.py/)”, line 272, in GPTQ_loader model = modules.GPTQ_loader.load_quantized(model_name) File “D:\AI\Clients\oobabooga_windows\text-generation-webui\modules\GPTQ_loader.py”, line 163, in load_quantized exit() File “D:\AI\Clients\oobabooga_windows\installer_files\env\lib_sitebuiltins.py”, line 26, in call raise SystemExit(code) SystemExit: None`

The models I am using are:
**vicuna_ggml-vicuna-13b-1.1** & **PygmalionAI_pygmalion-7b**

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Launch oobabooga for Windows via start_windows.bat
Navigate to 'Model'
Select any model
Select llama.cpp or GPTQ_for_LLaMa for the Model Loader
Reload
receive error.

### Logs

```shell
2023-07-04 16:12:39 INFO:Loading PygmalionAI_pygmalion-7b...
2023-07-04 16:12:39 ERROR:Could not find the quantized model in .pt or .safetensors format, exiting...
2023-07-04 16:12:39 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "D:\AI\Clients\oobabooga_windows\text-generation-webui\server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "D:\AI\Clients\oobabooga_windows\text-generation-webui\modules\models.py", line 74, in load_model
    output = load_func_map[loader](model_name)
  File "D:\AI\Clients\oobabooga_windows\text-generation-webui\modules\models.py", line 272, in GPTQ_loader
    model = modules.GPTQ_loader.load_quantized(model_name)
  File "D:\AI\Clients\oobabooga_windows\text-generation-webui\modules\GPTQ_loader.py", line 163, in load_quantized
    exit()
  File "D:\AI\Clients\oobabooga_windows\installer_files\env\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

2023-07-04 16:13:02 INFO:Loading vicuna_ggml-vicuna-13b-1.1...
2023-07-04 16:13:02 INFO:llama.cpp weights detected: models\vicuna_ggml-vicuna-13b-1.1\ggml-old-vic13b-q4_0.bin

2023-07-04 16:13:02 INFO:Cache capacity is 0 bytes
llama.cpp: loading model from models\vicuna_ggml-vicuna-13b-1.1\ggml-old-vic13b-q4_0.bin
error loading model: unexpectedly reached end of file
llama_load_model_from_file: failed to load model
2023-07-04 16:13:06 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "D:\AI\Clients\oobabooga_windows\text-generation-webui\server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "D:\AI\Clients\oobabooga_windows\text-generation-webui\modules\models.py", line 74, in load_model
    output = load_func_map[loader](model_name)
  File "D:\AI\Clients\oobabooga_windows\text-generation-webui\modules\models.py", line 255, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
  File "D:\AI\Clients\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 55, in from_pretrained
    result.model = Llama(**params)
  File "D:\AI\Clients\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 290, in __init__
    assert self.model is not None
AssertionError

Exception ignored in: <function Llama.__del__ at 0x000001AC2A775E10>
Traceback (most recent call last):
  File "D:\AI\Clients\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 1440, in __del__
    if self.ctx is not None:
AttributeError: 'Llama' object has no attribute 'ctx'
Exception ignored in: <function LlamaCppModel.__del__ at 0x000001AC2A814EE0>
Traceback (most recent call last):
  File "D:\AI\Clients\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 29, in __del__
    self.model.__del__()
AttributeError: 'LlamaCppModel' object has no attribute 'model'
```

### System Info

```shell
Windows 11 Desktop PC
NVidia GeForce RTX 3090 Ti
```

**Comment by bkniffler** [comment]
Similar issue here, on mac m1 with model TheBloke/orca_mini_v2_7B-GPTQ

```
Traceback (most recent call last):
  File "/Users/bkniffler/oobabooga_macos/text-generation-webui/server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/Users/bkniffler/oobabooga_macos/text-generation-webui/modules/models.py", line 74, in load_model
    output = load_func_map[loader](model_name)
  File "/Users/bkniffler/oobabooga_macos/text-generation-webui/modules/models.py", line 279, in AutoGPTQ_loader
    import modules.AutoGPTQ_loader
  File "/Users/bkniffler/oobabooga_macos/text-generation-webui/modules/AutoGPTQ_loader.py", line 3, in <module>
    from auto_gptq import AutoGPTQForCausalLM, BaseQuantizeConfig
ModuleNotFoundError: No module named 'auto_gptq'
```

**Comment by T3chRomanc3r** [comment]
Same issue with falcon 40b instruct ggmlv3 q5_k_s from 🤗 TheBloke/falcon-40b-instruct-GGML 

```
Traceback (most recent call last):
  File "E:\oobabooga_windows\text-generation-webui\server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "E:\oobabooga_windows\text-generation-webui\modules\models.py", line 74, in load_model
    output = load_func_map[loader](model_name)
  File "E:\oobabooga_windows\text-generation-webui\modules\models.py", line 263, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
  File "E:\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 55, in from_pretrained
    result.model = Llama(**params)
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 286, in __init__
    assert self.model is not None
AssertionError

Exception ignored in: <function Llama.__del__ at 0x000002702721FD00>
Traceback (most recent call last):
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 1445, in __del__
    if self.ctx is not None:
AttributeError: 'Llama' object has no attribute 'ctx'
Exception ignored in: <function LlamaCppModel.__del__ at 0x00000270271E2E60>
Traceback (most recent call last):
  File "E:\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 29, in __del__
    self.model.__del__()
AttributeError: 'LlamaCppModel' object has no attribute 'model
```

**Comment by Alpagaffeur** [comment]
Same while using CPU.
Specs : 
CPU 13th Gen Intel(R) Core(TM) i9-13900KF   3.00 GHz
RAM 64,0 Go  
GPU AMD RX 7900 XTX (24Go VRAM)


```
2023-07-19 11:25:13 INFO:Loading eachadea_ggml-vicuna-13b-1.1...
2023-07-19 11:25:13 INFO:llama.cpp weights detected: models\eachadea_ggml-vicuna-13b-1.1\ggml-old-vic13b-q4_0.bin

2023-07-19 11:25:13 INFO:Cache capacity is 0 bytes
llama.cpp: loading model from models\eachadea_ggml-vicuna-13b-1.1\ggml-old-vic13b-q4_0.bin
error loading model: unexpectedly reached end of file
llama_load_model_from_file: failed to load model
2023-07-19 11:25:49 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "F:\Bureau\oobabooga_windows\text-generation-webui\server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "F:\Bureau\oobabooga_windows\text-generation-webui\modules\models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "F:\Bureau\oobabooga_windows\text-generation-webui\modules\models.py", line 268, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
  File "F:\Bureau\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 58, in from_pretrained
    result.model = Llama(**params)
  File "F:\Bureau\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 305, in __init__
    assert self.model is not None
AssertionError

Exception ignored in: <function Llama.__del__ at 0x000001E0CFE579A0>
Traceback (most recent call last):
  File "F:\Bureau\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 1502, in __del__
    if self.ctx is not None:
AttributeError: 'Llama' object has no attribute 'ctx'
Exception ignored in: <function LlamaCppModel.__del__ at 0x000001E0CFDB77F0>
Traceback (most recent call last):
  File "F:\Bureau\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 29, in __del__
    self.model.__del__()
AttributeError: 'LlamaCppModel' object has no attribute 'model'
```
