### ISSUE TITLE
API chat Example does not work

### ISSUE THREAD

**Issue by mangywizard** [oobabooga/text-generation-webui#3024]
### Describe the bug

Fresh install. Regular model use works just fine but the REST api does not.

api-example-chat.py does NOT work. I just tried running it, on server I get a

TypeError: generate_chat_reply() got multiple values for argument 'regenerate'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Download current latest oobabooga, go to oobabooga_windows\text-generation-webui\api-examples\api-example-chat.py

Open in whatever python editor rand just run it. Server raises exception.

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/122325604/f4aec3f1-9660-47a7-9ed3-583dcb08bd39)

### Logs

```shell
Exception occurred during processing of request from ('127.0.0.1', 57773)
Traceback (most recent call last):
  File "C:\Users\Master-Donut\Documents\neat\oobabooga_windows\installer_files\env\lib\socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\Master-Donut\Documents\neat\oobabooga_windows\installer_files\env\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Master-Donut\Documents\neat\oobabooga_windows\installer_files\env\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\Users\Master-Donut\Documents\neat\oobabooga_windows\installer_files\env\lib\http\server.py", line 433, in handle
    self.handle_one_request()
  File "C:\Users\Master-Donut\Documents\neat\oobabooga_windows\installer_files\env\lib\http\server.py", line 421, in handle_one_request
    method()
  File "C:\Users\Master-Donut\Documents\neat\oobabooga_windows\text-generation-webui\extensions\api\blocking_api.py", line 82, in do_POST
    generator = generate_chat_reply(
TypeError: generate_chat_reply() got multiple values for argument 'regenerate'
```

### System Info

```shell
Windows
```

**Comment by mangywizard** [comment]
Seems it was just resolved with a pending PR.

https://github.com/oobabooga/text-generation-webui/issues/3006
