### ISSUE TITLE
exllama_hf throws error when num_beams > 1

### ISSUE THREAD

**Issue by tensiondriven** [oobabooga/text-generation-webui#3028]
### Describe the bug

When running exllama w/ llama-65b, it seems that the `no_repeat_ngram_size` parameter is ignored when using the API.  Has anyone else run into this, or am I doing something wrong?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run text-generation-webui, latest from main, with:

```
python server.py --listen --listen-port $port \
	--loader exllama \
	--model 33/hippogriff-30b-chat-GPTQ \
	--verbose \
	--chat \
	--api \
	--verbose
        #  --alpha_value 2 --gpu-split 10,23 --max_seq_len 4900
```
and the following params over API:
```
chat_params: %{
  do_sample: true,
  encoder_repetition_penalty: 1.0,
  no_repeat_ngram_size: 5,
  prompt: "...",
  repetition_penalty: 1.16,
  repetition_penalty_range: 512,
  seed: 81295,
  stopping_strings: [...],
  temperature: 0.4,
  top_k: 0,
  top_p: 0.5,
  truncation_length: 5300
}


### Screenshot

_No response_

### Logs

```shell
n/a
```

### System Info

```shell
Ubuntu 22.04, text-generation-webui at `ff453170329ad9f5414aa1e396130e82472f0b1b`
```

**Comment by tensiondriven** [comment]
If anyone *does* have no_repeat_engram_size working with exllama via the API, please post!

**Comment by tensiondriven** [comment]
Related: https://github.com/oobabooga/text-generation-webui/issues/2746

**Comment by tensiondriven** [comment]
From what @oobabooga mentioned in the thread linked above, a number of parameters, including `no_repeat_ngram_size`, are provided by huggingface Transformers, not by exllama.  So, it's necessary to run `--loader exllama_hf`.  However, when I attempt to load exllama_hf and perform inference, I get an error.

Started with: (Ubuntu 22.04, 3090)

```
python server.py --listen --listen-port $port \
	--loader exllama_hf \
	--gpu-split 16,24 \
	--model VicUnlocked-alpaca-65b-4bit \
	--api \
        --verbose
```

Note: `VicUnlocked-alpaca-65b-4bit` is a symlink.

Error:

```
Traceback (most recent call last):
  File "/home/j/text-generation-webui/modules/callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "/home/j/text-generation-webui/modules/text_generation.py", line 289, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/j/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/j/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1665, in generate
    return self.beam_sample(
  File "/home/j/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 3278, in beam_sample
    next_token_scores_processed = logits_processor(input_ids, next_token_scores)
  File "/home/j/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 92, in __call__
    scores = processor(input_ids, scores)
  File "/home/j/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 203, in __call__
    score = torch.gather(scores, 1, input_ids)
RuntimeError: Size does not match at dimension 0 expected index [4, 1835] to be smaller tTraceback (most recent call last):
  File "/home/j/text-generation-webui/modules/callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "/home/j/text-generation-webui/modules/text_generation.py", line 289, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/j/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/j/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1665, in generate
    return self.beam_sample(
  File "/home/j/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 3278, in beam_sample
    next_token_scores_processed = logits_processor(input_ids, next_token_scores)
  File "/home/j/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 92, in __call__
    scores = processor(input_ids, scores)
  File "/home/j/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 203, in __call__
    score = torch.gather(scores, 1, input_ids)
RuntimeError: Size does not match at dimension 0 expected index [4, 1835] to be smaller than self [1, 32000] apart from dimension 1
Output generated in 3.07 seconds (0.00 tokens/s, 0 tokens, context 1835, seed 81295)
han self [1, 32000] apart from dimension 1
Output generated in 3.07 seconds (0.00 tokens/s, 0 tokens, context 1835, seed 81295)
```

Does this error, `Size does not match at dimension 0 expected index [4, 1835] to be smaller than self [1, 32000] apart from dimension 1`, look familiar to anyone?

Perhaps i'm missing some parameter that is necessary when loading `exllama_hf`?


If I switch from `exllama_hf` to `exllama`, I'm able to perform inference just fine, but `no_repeat_ngram_size` is ignored.

text-generation-webui at `5ac4e4da8b6c4e6ad046248ae24c6633c0987a54`
exllama at `617fd2a849fe3d6f94b5ce0c153c7d76f2cf4438`
transformers at recent head of main

**Comment by tensiondriven** [comment]
Ok, I've traced it down to the following:

```
    %{
      num_beams: 4
    }
```

Attempting to perform inference with `exllama_hf` when using num_beams > 1 causes the exception.  There is no error when `num_beams = 1`

This occurs on both API and through the UI.

If `num_beams` is not supported by exllama_hf, perhaps we'd do well to raise a more friendly exception?

**Comment by tensiondriven** [comment]
Additional notes:

- num_beams > 1 works with `--loader exllama`
- num_beams > 1 breaks with `--loader exllama_hf`
- no_repeat_ngram_size works with `--loader exllama_hf`
- no_repeat_ngram_size is ignored with `--loader exllama`

I'll close this in favor of a new issue.
