### ISSUE TITLE
fatal error: 'android_lf.h' file not found

### ISSUE THREAD

**Issue by adaaaaaa** [oobabooga/text-generation-webui#3030]
### Describe the bug

[ 38%] Building C object Utilities/cmlibarchive/libarchive/CMakeFiles/cmlibarchive.dir/archive_acl.c.o
            In file included from /data/data/com.termux/files/usr/tmp/pip-install-w4jol5q0/cmake_3353084776f94fd585ca86f2dde4cf73/CMake-src/Utilities/cmlibarchive/libarchive/archive_acl.c:40:
            In file included from /data/data/com.termux/files/usr/tmp/pip-install-w4jol5q0/cmake_3353084776f94fd585ca86f2dde4cf73/CMake-src/Utilities/cmlibarchive/libarchive/archive_acl_private.h:35:
            In file included from /data/data/com.termux/files/usr/tmp/pip-install-w4jol5q0/cmake_3353084776f94fd585ca86f2dde4cf73/CMake-src/Utilities/cmlibarchive/libarchive/archive_string.h:49:
            /data/data/com.termux/files/usr/tmp/pip-install-w4jol5q0/cmake_3353084776f94fd585ca86f2dde4cf73/CMake-src/Utilities/cmlibarchive/libarchive/archive.h:101:10: fatal error: 'android_lf.h' file not found
            #include "android_lf.h"
                     ^~~~~~~~~~~~~~
            1 error generated.
            make[5]: *** [Utilities/cmlibarchive/libarchive/CMakeFiles/cmlibarchive.dir/build.make:76: Utilities/cmlibarchive/libarchive/CMakeFiles/cmlibarchive.dir/archive_acl.c.o] Error 1
            make[4]: *** [CMakeFiles/Makefile2:1990: Utilities/cmlibarchive/libarchive/CMakeFiles/cmlibarchive.dir/all] Error 2
            make[3]: *** [Makefile:166: all] Error 2
            make[2]: *** [CMakeFiles/CMakeProject-build.dir/build.make:88: CMakeProject-build-prefix/src/CMakeProject-build-stamp/CMakeProject-build-build] Error 2
            make[1]: *** [CMakeFiles/Makefile2:113: CMakeFiles/CMakeProject-build.dir/all] Error 2
            make: *** [Makefile:136: all] Error 2
            Traceback (most recent call last):
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-6fevv2u_/overlay/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 674, in setup
                cmkr.make(make_args, install_target=cmake_install_target, env=env)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-6fevv2u_/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 697, in make
                self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-6fevv2u_/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 742, in make_impl
                raise SKBuildError(msg)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

pip install -r requirement.txt

### Logs

```shell
see upon
```

### System Info

```shell
os:Android 13
cpu:snapdrogan 8+gen1
terminal:termux
```

**Comment by Ree1352** [comment]
The issue is relevant. I have same problem: android_lf.h' file not found
