### ISSUE TITLE
Failed to load the model.

### ISSUE THREAD

**Issue by jojohahahi87** [oobabooga/text-generation-webui#3040]
### Describe the bug

When I start generate it said failed to load the model and I reload the model it error,how can i fix it

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

1.Start the webui
2.Load model

### Logs

```shell
ERROR:Failed to load the model.
Traceback (most recent call last):
  File "E:\chat_ai\oobabooga_windows\oobabooga_windows\text-generation-webui\server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "E:\chat_ai\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\models.py", line 74, in load_model
    output = load_func_map[loader](model_name)
  File "E:\chat_ai\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\models.py", line 288, in AutoGPTQ_loader
    return modules.AutoGPTQ_loader.load_quantized(model_name)
  File "E:\chat_ai\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\AutoGPTQ_loader.py", line 56, in load_quantized
    model = AutoGPTQForCausalLM.from_quantized(path_to_model, **params)
  File "E:\chat_ai\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\modeling\auto.py", line 82, in from_quantized
    return quant_func(
  File "E:\chat_ai\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\modeling\_base.py", line 730, in from_quantized
    make_quant(
  File "E:\chat_ai\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\modeling\_utils.py", line 80, in make_quant
    make_quant(child, names, bits, group_size, name + '.' + name1 if name != '' else name1, use_triton=use_triton, use_cuda_fp16=use_cuda_fp16,desc_act=desc_act)
  File "E:\chat_ai\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\modeling\_utils.py", line 80, in make_quant
    make_quant(child, names, bits, group_size, name + '.' + name1 if name != '' else name1, use_triton=use_triton, use_cuda_fp16=use_cuda_fp16,desc_act=desc_act)
  File "E:\chat_ai\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\modeling\_utils.py", line 80, in make_quant
    make_quant(child, names, bits, group_size, name + '.' + name1 if name != '' else name1, use_triton=use_triton, use_cuda_fp16=use_cuda_fp16,desc_act=desc_act)
  [Previous line repeated 1 more time]
  File "E:\chat_ai\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\modeling\_utils.py", line 74, in make_quant
    new_layer = QuantLinear(bits, group_size, in_features, out_features, True, use_cuda_fp16=use_cuda_fp16)
  File "E:\chat_ai\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\nn_modules\qlinear_old.py", line 42, in __init__
    torch.zeros((infeatures // 32 * self.bits, outfeatures), dtype=torch.int32)
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 35389440 bytes.
```

### System Info

```shell
win11
Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz   2.90 GHz
Ram 16.0 GB
```

**Comment by jasperan** [comment]
What model is it?

**Comment by bschleter** [comment]
im getting similar error. Im trying to load: sahil2801/replit-code-instruct-glaive

3B parameter, I have the capabilities to run. 

Traceback (most recent call last):
File “/Users/username/text-generation-webui/server.py”, line 60, in load_model_wrapper
shared.model, shared.tokenizer = load_model(shared.model_name)
File “/Users/username/text-generation-webui/modules/models.py”, line 219, in load_model
model = LoaderClass.from_pretrained(checkpoint, **params)
File “/Users/username/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py”, line 462, in from_pretrained
model_class = get_class_from_dynamic_module(
File “/Users/username/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/dynamic_module_utils.py”, line 388, in get_class_from_dynamic_module
return get_class_in_module(class_name, final_module.replace(“.py”, “”))
File “/Users/username/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/dynamic_module_utils.py”, line 157, in get_class_in_module
module = importlib.import_module(module_path)
File “/Users/username/opt/anaconda3/envs/textgen/lib/python3.10/importlib/init.py”, line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File “”, line 1050, in _gcd_import
File “”, line 1027, in _find_and_load
File “”, line 1006, in _find_and_load_unlocked
File “”, line 688, in _load_unlocked
File “”, line 883, in exec_module
File “”, line 241, in _call_with_frames_removed
File “/Users/username/.cache/huggingface/modules/transformers_modules/sahil2801_replit-code-instruct-glaive/modeling_mpt.py”, line 13, in
from .attention import attn_bias_shape, build_attn_bias
File “/Users/username.cache/huggingface/modules/transformers_modules/sahil2801_replit-code-instruct-glaive/attention.py”, line 7, in
from einops import rearrange
ModuleNotFoundError: No module named ‘einops’


I thought it was just simply the model being newer and the type, but came to Issues and saw this.

**Comment by jasperan** [comment]
> im getting similar error. Im trying to load: sahil2801/replit-code-instruct-glaive
> 
> 3B parameter, I have the capabilities to run.
> 
> Traceback (most recent call last): File “/Users/username/text-generation-webui/server.py”, line 60, in load_model_wrapper shared.model, shared.tokenizer = load_model(shared.model_name) File “/Users/username/text-generation-webui/modules/models.py”, line 219, in load_model model = LoaderClass.from_pretrained(checkpoint, **params) File “/Users/username/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py”, line 462, in from_pretrained model_class = get_class_from_dynamic_module( File “/Users/username/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/dynamic_module_utils.py”, line 388, in get_class_from_dynamic_module return get_class_in_module(class_name, final_module.replace(“.py”, “”)) File “/Users/username/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/dynamic_module_utils.py”, line 157, in get_class_in_module module = importlib.import_module(module_path) File “/Users/username/opt/anaconda3/envs/textgen/lib/python3.10/importlib/init.py”, line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File “”, line 1050, in _gcd_import File “”, line 1027, in _find_and_load File “”, line 1006, in _find_and_load_unlocked File “”, line 688, in _load_unlocked File “”, line 883, in exec_module File “”, line 241, in _call_with_frames_removed File “/Users/username/.cache/huggingface/modules/transformers_modules/sahil2801_replit-code-instruct-glaive/modeling_mpt.py”, line 13, in from .attention import attn_bias_shape, build_attn_bias File “/Users/username.cache/huggingface/modules/transformers_modules/sahil2801_replit-code-instruct-glaive/attention.py”, line 7, in from einops import rearrange ModuleNotFoundError: No module named ‘einops’
> 
> I thought it was just simply the model being newer and the type, but came to Issues and saw this.

If you used the integrated downloader you might be missing a .model file that you need to download manually

**Comment by strifedeeno** [comment]
> im getting similar error. Im trying to load: sahil2801/replit-code-instruct-glaive
> 
> 3B parameter, I have the capabilities to run.
> 
> Traceback (most recent call last): File “/Users/username/text-generation-webui/server.py”, line 60, in load_model_wrapper shared.model, shared.tokenizer = load_model(shared.model_name) File “/Users/username/text-generation-webui/modules/models.py”, line 219, in load_model model = LoaderClass.from_pretrained(checkpoint, **params) File “/Users/username/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py”, line 462, in from_pretrained model_class = get_class_from_dynamic_module( File “/Users/username/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/dynamic_module_utils.py”, line 388, in get_class_from_dynamic_module return get_class_in_module(class_name, final_module.replace(“.py”, “”)) File “/Users/username/opt/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/dynamic_module_utils.py”, line 157, in get_class_in_module module = importlib.import_module(module_path) File “/Users/username/opt/anaconda3/envs/textgen/lib/python3.10/importlib/init.py”, line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File “”, line 1050, in _gcd_import File “”, line 1027, in _find_and_load File “”, line 1006, in _find_and_load_unlocked File “”, line 688, in _load_unlocked File “”, line 883, in exec_module File “”, line 241, in _call_with_frames_removed File “/Users/username/.cache/huggingface/modules/transformers_modules/sahil2801_replit-code-instruct-glaive/modeling_mpt.py”, line 13, in from .attention import attn_bias_shape, build_attn_bias File “/Users/username.cache/huggingface/modules/transformers_modules/sahil2801_replit-code-instruct-glaive/attention.py”, line 7, in from einops import rearrange ModuleNotFoundError: No module named ‘einops’
> 
> I thought it was just simply the model being newer and the type, but came to Issues and saw this.

Maybe try doing pip install einops

**Comment by ionizn** [comment]
As written above, download 'spiece.model' from the repository.
