### ISSUE TITLE
An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by hdslol** [oobabooga/text-generation-webui#3050]
### Describe the bug

Whenever i run start_windows.bat with the API flag, I get this error.
Things i have tried:

manually installing with conda instead of the one click installer

updating

adding inbound and outbound exceptions to windows firewall for port 7860

disabling firewall entirely

killing any processes that may be using port 7860

disabling anti virus

uninstalling and reinstalling

changing port from 7860 to other numbers

running windows troubleshooter

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run start_windows.bat once to install, add api flag, and then run start_windows.bat a second time

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/47882534/0fadeffe-ce63-4961-b13c-a16f22e503ed)

### Logs

```shell
bin C:\Use\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
Exception in thread Thread-1 (_run_server):
Traceback (most recent call last):
Starting streaming server at ws://127.0.0.1:5005/api/v1/stream
  File "C:\Use\oobabooga_windows\oobabooga_windows\installer_files\env\lib\threading.py", line 1016, in _bootstrap_inner
2023-07-08 19:25:49 INFO:Loading the extension "gallery"...
    self.run()
  File "C:\Use\oobabooga_windows\oobabooga_windows\installer_files\env\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Use\oobabooga_windows\oobabooga_windows\text-generation-webui\extensions\api\blocking_api.py", line 201, in _run_server
    server = ThreadingHTTPServer((address, port), Handler)
  File "C:\Use\oobabooga_windows\oobabooga_windows\installer_files\env\lib\socketserver.py", line 452, in __init__
    self.server_bind()
  File "C:\Use\oobabooga_windows\oobabooga_windows\installer_files\env\lib\http\server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "C:\Use\oobabooga_windows\oobabooga_windows\installer_files\env\lib\socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

### System Info

```shell
Windows 10 home
Nvidia RTX 3070ti
```

**Comment by powercore2000** [comment]
I'm having the same issue, on Windows 10, RTX 3070. 
![Screenshot 2023-07-14 003152](https://github.com/oobabooga/text-generation-webui/assets/42394999/d7c94323-f4f1-4084-807a-23eac23b9053)

**Comment by powercore2000** [comment]
So I did some digging and found my problem was that I had another application using the 5000 port the API server would normally run on, and that's why I got that error. As a result, the API server on port 5000 was never activated. Either change the API server's port or prevent the competing application from using that port
