### ISSUE TITLE
IndexError: index -1 is out of bounds for dimension 1 with size 0

### ISSUE THREAD

**Issue by matatonic** [oobabooga/text-generation-webui#3054]
### Describe the bug

Getting this error when I try to use Transformers loader in 8bit or 4bit, very recent behavior, perhaps only since Thursday or Friday. (Jul 7)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load a model like chavinlo/alpaca-13b-hf-safetensors in 8bit, I'm testing with the following prompt:
```
Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
Translate this into French

### Input:
Our mission is to ensure that artificial general intelligence benefits all of humanity.

### Response:
```

### Logs

```shell
Traceback (most recent call last):
  File "/app/modules/callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "/app/modules/text_generation.py", line 296, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 1319, in generate
    and torch.sum(inputs_tensor[:, -1] == generation_config.pad_token_id) > 0
IndexError: index -1 is out of bounds for dimension 1 with size 0
Output generated in 0.37 seconds (0.00 tokens/s, 0 tokens, context 0, seed 1156438958)
```

### System Info

```shell
Docker, ubuntu 22, Nivida, AMD CPU.
```

**Comment by TetsujinXLIV** [comment]
Hello, I am getting the same error. Can you explain the fix? I am trying to run: TheBloke_WizardCoder-Python-34B-V1.0-GPTQ and I loaded it using ExLlama_HF.

**Comment by thijsi123** [comment]
I have a problem with Llamacoder 7b

2023-08-30 21:37:00 INFO:Loading TheBloke_CodeLlama-7B-GPTQ...
2023-08-30 21:37:00 INFO:The AutoGPTQ params are: {'model_basename': 'model', 'device': 'cuda:0', 'use_triton': False, 'inject_fused_attention': True, 'inject_fused_mlp': True, 'use_safetensors': True, 'trust_remote_code': False, 'max_memory': None, 'quantize_config': None, 'use_cuda_fp16': True, 'disable_exllama': False}
2023-08-30 21:37:07 WARNING:skip module injection for FusedLlamaMLPForQuantizedModel not support integrate without triton yet.
2023-08-30 21:37:07 WARNING:C:\Users\jonge\AppData\Local\nomic.ai\GPT4All\TheBloke_CodeLlama-7B-GPTQ\tokenizer_config.json is different from the original LlamaTokenizer file. It is either customized or outdated.
2023-08-30 21:37:07 INFO:Loaded the model in 6.52 seconds.

Traceback (most recent call last):
  File "H:\AI\oobabooga_windows\text-generation-webui\modules\callbacks.py", line 56, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "H:\AI\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 311, in generate_with_callback
    shared.model.generate(**kwargs)
  File "H:\AI\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\modeling\_base.py", line 443, in generate
    return self.model.generate(**kwargs)
  File "H:\AI\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "H:\AI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1476, in generate
    and torch.sum(inputs_tensor[:, -1] == generation_config.pad_token_id) > 0
IndexError: index -1 is out of bounds for dimension 1 with size 0
Output generated in 0.36 seconds (0.00 tokens/s, 0 tokens, context 0, seed 1974241523)

**Comment by KaraRyougi** [comment]
My issue is that I set `max_new_tokens` in parameter too large.

**Comment by simong99** [comment]
> My issue is that I set `max_new_tokens` in parameter too large.

Many thanks for the pointer, yes I had this too. (I'd been experimenting with a different model which was fine with many new tokens)

**Comment by DiffusionAllusion** [comment]
For me, the "Truncate the prompt up to this length" setting had gotten set to 0 when restarting the software
