### ISSUE TITLE
ERROR:Failed to load the model. TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by matatonic** [oobabooga/text-generation-webui#3056]
### Describe the bug

AutoGPTQ model fails to load TheBloke/minotaur-15B-GPTQ, this worked on Thursday (Jul 6).
Something wrong after the tokenizer changes?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

as above.

### Logs

```shell
2023-07-08 15:46:50 INFO:Loading TheBloke_minotaur-15B-GPTQ...
2023-07-08 15:46:50 INFO:The AutoGPTQ params are: {'model_basename': 'gptq_model-4bit-128g', 'device': 'cuda:0', 'use_triton': False, 'inject_fused_attention': True, 'inject_fused_mlp': True, 'use_safetensors': True, 'trust_remote_code': True, 'max_memory': None, 'quantize_config': None, 'use_cuda_fp16': True}
2023-07-08 15:46:51 WARNING:The safetensors archive passed at models/TheBloke_minotaur-15B-GPTQ/gptq_model-4bit-128g.safetensors does not contain metadata. Make sure to save your model with the `save_pretrained` method. Defaulting to 'pt' metadata.
2023-07-08 15:47:00 WARNING:GPTBigCodeGPTQForCausalLM hasn't fused attention module yet, will skip inject fused attention.
2023-07-08 15:47:00 WARNING:GPTBigCodeGPTQForCausalLM hasn't fused mlp module yet, will skip inject fused mlp.
2023-07-08 15:47:00 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/app/server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/app/modules/models.py", line 82, in load_model
    tokenizer = load_tokenizer(model_name, model)
  File "/app/modules/models.py", line 99, in load_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/tokenization_auto.py", line 691, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1825, in from_pretrained
    return cls._from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1988, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/gpt2/tokenization_gpt2.py", line 194, in __init__
    with open(merges_file, encoding="utf-8") as merges_handle:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

### System Info

```shell
Also including the tokenizer_config.json for the model:
{
  "add_prefix_space": false,
  "additional_special_tokens": [
    "<|endoftext|>",
    "<fim_prefix>",
    "<fim_middle>",
    "<fim_suffix>",
    "<fim_pad>",
    "<filename>",
    "<gh_stars>",
    "<issue_start>",
    "<issue_comment>",
    "<issue_closed>",
    "<jupyter_start>",
    "<jupyter_text>",
    "<jupyter_code>",
    "<jupyter_output>",
    "<empty_output>",
    "<commit_before>",
    "<commit_msg>",
    "<commit_after>",
    "<reponame>"
  ],
  "bos_token": "<|endoftext|>",
  "eos_token": "<|endoftext|>",
  "model_max_length": 1000000000000000019884624838656,
  "tokenizer_class": "GPT2Tokenizer",
  "unk_token": "<|endoftext|>",
  "vocab_size": 49152
}
```

**Comment by websiteduck** [comment]
I got this same error with `TheBloke/starcoderplus-GPTQ`

It looks like it was missing `merges.txt` which was uploaded later. After I downloaded that file to my model directory the model loaded.

**Comment by matatonic** [comment]
@websiteduck Indeed, the TheBloke/minotaur-15B-GPTQ/merges.txt was updated and now fixed. Thanks!
