### ISSUE TITLE
Unable to load exllama from repositories

### ISSUE THREAD

**Issue by noblespade** [oobabooga/text-generation-webui#3060]
### Describe the bug

I had the issue mentioned here: https://github.com/oobabooga/text-generation-webui/issues/2949

Generation with exllama was extremely slow and the fix resolved my issue. (pip uninstall exllama and modified q4_matmul.cu according to https://github.com/turboderp/exllama/issues/111

After starting oobabooga again, it did not work anymore. The command line is stuck on "INFO:Loading Manticore-13B-Chat-Pyg-Guanaco-SuperHOT-8K-GPTQ... WARNING:Exllama module failed to load. Will attempt to load from repositories."

But nothing happens at all.

I am sorry, i am very new to all this and can't understand why it worked one time and then exllama seemingly can't be loaded from repositories anymore. No changes, no error messages.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. install oobabooga + prerequisites (one click installer)
2. pip uninstall exllama so exllama is loaded from repositories
3. start webui and load model / start with arguments --loader exllama --max_seq_len 2048 ----compress_pos_emb 1

### Screenshot

![screenshot](https://github.com/oobabooga/text-generation-webui/assets/139001734/0186004d-0d5d-4bb9-99a6-2335421376fa)

### Logs

```shell
-no errors
```

### System Info

```shell
Windows 10
Nvidia GeForce GTX 1080 Ti
```

**Comment by tensiondriven** [comment]
I was running into something similar recently - Perhaps check your dependencies:
- Correct python version loaded?
- conda environment activated?
- pip install requirements --upgrade?
- pulled latest text-generation-webui?

In my case, the python version in my conda env was slightly mismatched.

**Comment by noblespade** [comment]
Thank you! I tried all of your suggestions but no luck. There actually was a mismatch of python versions but matching it unfortunately did not change anything.

**Comment by Ph0rk0z** [comment]
This is weird because I never installed the pip version and load exllama all the time from where I cloned it to repositories. But I notice you are on windows so you have to be sure that you can compile it there. 

Run it on it's own from the scripts it has and see if you get an error.

**Comment by MrOiseau** [comment]
Hi did you managed to solve this issue? I'm using macbook m1 and getting similar issue:
"""
2023-09-20 00:25:32 WARNING:exllama module failed to import. Will attempt to import from repositories/.
2023-09-20 00:25:32 ERROR:Could not find repositories/exllama. Please ensure that exllama (https://github.com/turboderp/exllama) is cloned inside repositories/ and is up to date.
2023-09-20 00:25:32 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/Users/.../text-generation-webui/modules/exllama.py", line 13, in <module>
    from exllama.generator import ExLlamaGenerator
ModuleNotFoundError: No module named 'exllama'
"""

**Comment by dayaaary** [comment]
> Hi did you managed to solve this issue? I'm getting similar issue related to exllama when trying to load a model on Text gneration web UI on Macbook M1: """ 2023-09-20 00:55:59 WARNING:exllama module failed to import. Will attempt to import from repositories/. 2023-09-20 00:55:59 ERROR:Could not find repositories/exllama. Please ensure that exllama (https://github.com/turboderp/exllama) is cloned inside repositories/ and is up to date. 2023-09-20 00:55:59 ERROR:Failed to load the model. Traceback (most recent call last): File "/Users/.../text-generation-webui/modules/exllama.py", line 13, in from exllama.generator import ExLlamaGenerator ModuleNotFoundError: No module named 'exllama'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/Users/.../text-generation-webui/modules/ui_model_menu.py", line 194, in load_model_wrapper shared.model, shared.tokenizer = load_model(shared.model_name, [loader](https://github.com/turboderp/exllama/issues/model_name)) File "/Users/.../text-generation-webui/modules/models.py", line 77, in load_model output = load_func_maploader File "/Users/.../text-generation-webui/modules/models.py", line 307, in ExLlama_loader from modules.exllama import ExllamaModel File "/Users/.../text-generation-webui/modules/exllama.py", line 22, in from generator import ExLlamaGenerator ModuleNotFoundError: No module named 'generator' """ Anyone know how to solve this one?

i'm facing this issue .  is it resolved for you ?
