### ISSUE TITLE
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group on 13B models

### ISSUE THREAD

**Issue by weeblebeeb** [oobabooga/text-generation-webui#3071]
### Describe the bug

Whenever I try to generate an output using a 13B model, it gives me an error saying that I need to call init_process group. It does this with every model loader type, and only seems to affect 13B models.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load a 13B model and attempt to generate a response.

### Screenshot

![WindowsTerminal_W04BNsLSB6](https://github.com/oobabooga/text-generation-webui/assets/139071275/9f3db0e4-1ba9-4c21-816f-e455ce44dbe8)

### Logs

```shell
Traceback (most recent call last):
  File "C:\one-click-installers-main\text-generation-webui\modules\callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "C:\one-click-installers-main\text-generation-webui\modules\text_generation.py", line 289, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\one-click-installers-main\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\one-click-installers-main\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1572, in generate
    return self.sample(
  File "C:\one-click-installers-main\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 2610, in sample
    dist.all_reduce(this_peer_finished_flag, op=dist.ReduceOp.SUM)
  File "C:\one-click-installers-main\installer_files\env\lib\site-packages\torch\distributed\distributed_c10d.py", line 1451, in wrapper
    return func(*args, **kwargs)
  File "C:\one-click-installers-main\installer_files\env\lib\site-packages\torch\distributed\distributed_c10d.py", line 1699, in all_reduce
    default_pg = _get_default_group()
  File "C:\one-click-installers-main\installer_files\env\lib\site-packages\torch\distributed\distributed_c10d.py", line 707, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
```

### System Info

```shell
OS: Windows 11
GPU: Nvidia RTX 3070
```

**Comment by TheLustriVA** [comment]
This is still a problem.

```shell
Traceback (most recent call last):
  File "/home/websinthe/content/textgen/text-generation-webui/modules/callbacks.py", line 56, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "/home/websinthe/content/textgen/text-generation-webui/modules/text_generation.py", line 351, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/websinthe/content/textgen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/awq/models/base.py", line 36, in generate
    return self.model.generate(*args, **kwargs)
  File "/home/websinthe/content/textgen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/websinthe/content/textgen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/generation/utils.py", line 1652, in generate
    return self.sample(
  File "/home/websinthe/content/textgen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/generation/utils.py", line 2725, in sample
    dist.all_reduce(this_peer_finished_flag, op=dist.ReduceOp.SUM)
  File "/home/websinthe/content/textgen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/websinthe/content/textgen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2039, in all_reduce
    group = _get_default_group()
  File "/home/websinthe/content/textgen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 940, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
Output generated in 0.51 seconds (0.00 tokens/s, 0 tokens, context 1340, seed 1935717995)
``` 
It's happening when I try to use AWQ models that had previously worked. (Amethyst-20B is the only one I can remember that I haven't deleted for being dead-on-arrival for TGW.

OS: Ubuntu 22.04
Card: Nvidia RTX 3090

**Comment by Urammar** [comment]
Im also getting this on 3090
