### ISSUE TITLE
KeyError: 'repetition_penalty_range' when using API

### ISSUE THREAD

**Issue by jonfairbanks** [oobabooga/text-generation-webui#3086]
### Describe the bug

When using [api-example.py](https://github.com/oobabooga/text-generation-webui/blob/main/api-examples/api-example.py), errors are returned when processing the response:
```
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Digging deeper, this is because no valid response is returned upon making an API call although an HTTP 200 is returned.
<img width="900" alt="Screenshot 2023-07-10 at 12 26 31 PM" src="https://github.com/oobabooga/text-generation-webui/assets/1957806/89a29719-ef62-45bc-99f7-aed98f45bea6">

If you take a look at Ooba logs after running, it gives a KeyError.
```
KeyError: 'repetition_penalty_range'
```

This key is in-fact passed during the request however and I am unfortunately not yet able to get past this error.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

This can be confirmed by using api-example.py, in Postman or via curl:

```
curl --location 'http://localhost:5000/api/v1/generate' \
--header 'Content-Type: application/json' \
--data '{
    "prompt": "In order to make homemade bread, follow these steps:\n1)",
    "max_new_tokens": 1800,
    "preset": "None",
    "do_sample": true,
    "temperature": 0.7,
    "top_p": 0.1,
    "typical_p": 1,
    "epsilon_cutoff": 0,
    "eta_cutoff": 0,
    "tfs": 1,
    "top_a": 0,
    "repetition_penalty": 1.21,
    "repetition_penalty_range": 0,
    "top_k": 40,
    "min_length": 0,
    "no_repeat_ngram_size": 0,
    "num_beams": 1,
    "penalty_alpha": 0,
    "length_penalty": 1,
    "early_stopping": false,
    "mirostat_mode": 0,
    "mirostat_tau": 5,
    "mirostat_eta": 0.1,
    "seed": -1,
    "add_bos_token": true,
    "truncation_length": 2048,
    "ban_eos_token": false,
    "skip_special_tokens": true
}'
```

### Screenshot

<img width="779" alt="Screenshot 2023-07-10 at 12 21 49 PM" src="https://github.com/oobabooga/text-generation-webui/assets/1957806/7d349345-f0fe-4219-a8af-e7d7c25158f8">

### Logs

```shell
In order to make homemade bread, follow these steps:
1)
--------------------

----------------------------------------
Exception occurred during processing of request from ('192.168.4.115', 62905)
Traceback (most recent call last):
  File "/usr/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.10/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/usr/lib/python3.10/http/server.py", line 420, in handle_one_request
    method()
  File "/app/extensions/api/blocking_api.py", line 58, in do_POST
    for a in generator:
  File "/app/modules/text_generation.py", line 27, in generate_reply
    for result in _generate_reply(*args, **kwargs):
  File "/app/modules/text_generation.py", line 214, in _generate_reply
    for reply in generate_func(question, original_question, seed, state, stopping_strings, is_chat=is_chat):
  File "/app/modules/text_generation.py", line 234, in generate_reply_HF
    generate_params[k] = state[k]
KeyError: 'repetition_penalty_range'
----------------------------------------
```

### System Info

```shell
Ubuntu 22.x
Nvidia RTX 3090 Founders
```

**Comment by jonfairbanks** [comment]
Looks like some recent changes related to this may have taken place in this PR: https://github.com/oobabooga/text-generation-webui/pull/2916
