### ISSUE TITLE
No GPU Detected on 4080

### ISSUE THREAD

**Issue by awiggins12** [oobabooga/text-generation-webui#310]
### Describe the bug

I followed the instructions on https://www.reddit.com/r/LocalLLaMA/comments/11o6o3f/how_to_install_llama_8bit_and_4bit/ for installing 8-bit llama, but when I run the command to start the app it tells me no gpu has been detected and falls back to CPU mode.

F:\text-generation-webui>python server.py --model llama-7b-hf --load-in-8bit
Loading llama-7b-hf...
Warning: no GPU has been detected.
Falling back to CPU mode.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

python server.py --model llama-7b-hf --load-in-8bit

### Logs

```shell
F:\text-generation-webui>python server.py --model llama-7b-hf --load-in-8bit
Loading llama-7b-hf...
Warning: no GPU has been detected.
Falling back to CPU mode.
```

### System Info

```shell
Windows 10
Gigabyte RTX 4080
```

**Comment by DxBang** [comment]
Getting same error message on RTX 3090 on Windows 11 using the one-click-installer choosing the A: Nvidia option at installation. 

```
PS D:\ai\oobabooga> .\start-webui.bat
Starting the web UI...
Loading the extension "gallery"... Ok.
The following models are available:

1. opt-350m
2. pygmalion-2.7b
3. pygmalion-6b_b8344bb4eb76a437797ad3b19420a13922aaabe1

Which one do you want to load? 1-3

1

Loading opt-350m...
Warning: no GPU has been detected.
Falling back to CPU mode.

Loaded the model in 1.05 seconds.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```



start-webui.bat

**Comment by tristanhanks** [comment]
Same issue on a 3070 10GB

**Comment by yi** [comment]
looks more like a driver problem. try [run `nvidia-smi`](https://stackoverflow.com/questions/68533863/running-nvidia-smi-from-windows-powershell) to see if the gpu correctly recogized by the system.

**Comment by RandomName321** [comment]
I have a problem on rtx2060. Appeared after git pull

**Comment by deadeye12** [comment]
Same issue - agree appeared after latest git pull.  Was working fine before that; GPU still working fine in other envs. RTX 4090

**Comment by BingoGreen** [comment]
Same issue on a 3090 24GB

**Comment by Alleykatz** [comment]
Also having this issue - RTX 4090

**Comment by franzkruhm** [comment]
Same, win10 with one click install latest nvidia drivers on 3060 12gigs

**Comment by franzkruhm** [comment]
> Same issue - agree appeared after latest git pull. Was working fine before that; GPU still working fine in other envs. RTX 4090. Update: Captured the Following
> 
> ```
> > 
> > > Loading pygmalion-6b...
> > > Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.94s/it]
> > > Traceback (most recent call last):
> > >   File "F:\oobabooga\text-generation-webui\server.py", line 191, in <module>
> > >     shared.model, shared.tokenizer = load_model(shared.model_name)
> > >   File "F:\oobabooga\text-generation-webui\modules\models.py", line 49, in load_model
> > >     model = AutoModelForCausalLM.from_pretrained(Path(f"models/{shared.model_name}"), low_cpu_mem_usage=True, torch_dtype=torch.bfloat16 if shared.args.bf16 else torch.float16).cuda()
> > >   File "F:\miniconda3\envs\textgen\lib\site-packages\torch\nn\modules\module.py", line 749, in cuda
> > >     return self._apply(lambda t: t.cuda(device))
> > >   File "F:\miniconda3\envs\textgen\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
> > >     module._apply(fn)
> > >   File "F:\miniconda3\envs\textgen\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
> > >     module._apply(fn)
> > >   File "F:\miniconda3\envs\textgen\lib\site-packages\torch\nn\modules\module.py", line 664, in _apply
> > >     param_applied = fn(param)
> > >   File "F:\miniconda3\envs\textgen\lib\site-packages\torch\nn\modules\module.py", line 749, in <lambda>
> > >     return self._apply(lambda t: t.cuda(device))
> > >   File "F:\miniconda3\envs\textgen\lib\site-packages\torch\cuda\__init__.py", line 221, in _lazy_init
> > >     raise AssertionError("Torch not compiled with CUDA enabled")
> > > AssertionError: Torch not compiled with CUDA enabled
> > 
> > 
> ```
> 
> **When I try llama:**
> 
> ```
> 
> Loading llama-13b-hf...
> Warning: no GPU has been detected.
> Falling back to CPU mode.
> 
> Loading checkpoint shards: 100%|███████████████████████████████████████████████████████| 41/41 [00:27<00:00,  1.51it/s]
> Loaded the model in 27.27 seconds.
> Running on local URL:  http://127.0.0.1:7860
> ```

would that mean a version of torch without CUDA gets installed? madness!

**Comment by borge12** [comment]
> looks more like a driver problem. try [run `nvidia-smi`](https://stackoverflow.com/questions/68533863/running-nvidia-smi-from-windows-powershell) to see if the gpu correctly recogized by the system.

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 528.02       Driver Version: 528.02       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:0A:00.0  On |                  N/A |
|  0%   24C    P8    16W / 340W |   2579MiB / 16376MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|

I'm not sure how to get that formatting right, but a GPU is appearing in there.

**Comment by deadeye12** [comment]
Interestingly, I ran outside of the conda environment setup in he option 1 install, and it worked fine (probably have the requirements from other non-conda envs.  This just seems to be a conda environment setup/install/requirements issue

**Comment by innightwolfsleep** [comment]
During pip install -r requirements.txt cought this:

```
Installing collected packages: torch
  Attempting uninstall: torch
    Found existing installation: torch 2.0.0
    Uninstalling torch-2.0.0:
      Successfully uninstalled torch-2.0.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.15.0 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
torchaudio 2.0.0 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
```
First we uninstall torch-2.0.0, then we require  torch==2.0.0.
Seems like a bug in requirements of some installed module.

**Comment by franzkruhm** [comment]
the above reddit's instruction do not work here.
and yes I noticed this torch version issue, dont know how to solve it

**Comment by borge12** [comment]
> > Same issue - agree appeared after latest git pull. Was working fine before that; GPU still working fine in other envs. RTX 4090. Update: Captured the Following

Do you know what commit you were at when this was working?

**Comment by franzkruhm** [comment]
> > the above reddit's instruction do not work here. and yes I noticed this torch version issue, dont know how to solve it
> 
> did you try the alternate instructions posted on the reddit guide? worked for me

yep... same result as using the one clock install.
torch doesn't seem to be compiled with cuda

**Comment by franzkruhm** [comment]
alright works! thanks I think my mistake was when editing the files... if not to if...
now only problem is ... I dont have enough VRAM...

**Comment by deadeye12** [comment]
Line 11. above is what I messed up.  Seems to have solved the issue.
`pip install torch==1.12+cu113 -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by Alleykatz** [comment]
Changes have been made to the one-click-installer. Using the new install.bat has resolved the issue for me.

**Comment by oobabooga** [comment]
This issue is probably related to https://github.com/oobabooga/text-generation-webui/issues/347, as @Alleykatz pointed out.

The solution was to change 

```
conda install torchvision torchaudio pytorch-cuda=11.7 git -c pytorch -c nvidia

```

to

```
conda install torchvision=0.14.1 torchaudio=0.13.1 pytorch-cuda=11.7 git -c pytorch -c nvidia
```
