### ISSUE TITLE
Better error message when trying to load GPTQ models on macOS.

### ISSUE THREAD

**Issue by briandw** [oobabooga/text-generation-webui#3107]
### Describe the bug

Since GPTQ won't work on macOS, there should be a better error message when opening a GPTQ model. 
I downloaded TheBloke_WizardCoder-15B-1.0-GPTQ model and the error was:

> ModuleNotFoundError: No module named 'auto_gptq'

How about a check for the platform and an appropriate error message?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

On a Mac run pip install -r requirements.txt

### Logs

```shell
(textgen) ➜  text-generation-webui git:(main) python server.py --threads 16
bin /opt/homebrew/Caskroom/miniforge/base/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/opt/homebrew/Caskroom/miniforge/base/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
2023-07-11 21:07:45 INFO:Loading TheBloke_WizardCoder-15B-1.0-GPTQ...
Traceback (most recent call last):
  File "/Users/brian/text-generation-webui/server.py", line 1155, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/Users/brian/text-generation-webui/modules/models.py", line 78, in load_model
    output = load_func_map[loader](model_name)
  File "/Users/brian/text-generation-webui/modules/models.py", line 290, in AutoGPTQ_loader
    import modules.AutoGPTQ_loader
  File "/Users/brian/text-generation-webui/modules/AutoGPTQ_loader.py", line 3, in <module>
    from auto_gptq import AutoGPTQForCausalLM, BaseQuantizeConfig
ModuleNotFoundError: No module named 'auto_gptq'
```

### System Info

```shell
Mac Studio M1 Ultra
```

**Comment by Ph0rk0z** [comment]
Does autogptq even work on metal?

**Comment by Foxtr0t1337** [comment]
You can use llama.cpp with ggml models. I don't think you can solve this easily if you insist to use gptq on macos. However if you come across a way to use gptq model on macos you should give it a try. I mean, what if it works?

**Comment by Foxtr0t1337** [comment]
I am so confused. There is no info I can find  about AutoGPTQ and MacOS. It only mentioned CUDA but it didn't mention Nvidia. I will try to find out whether it is possible to use GPTQ on Apple silicon.

**Comment by kshitijyad** [comment]
Same error -

line 411, in device
    device = [d for d in self.hf_device_map.values() if d not in {'cpu', 'disk'}][0]

**Comment by unixwzrd** [comment]
> text-generation has worked on the Mac in the past, so I guess the question is, do you want to continue to support it going forward. It's currently not working and this is one of the problems.

auto_gpotq and a number of other modules are now only supported fro Linus and Windows as specified in the requirements.txt and are coming from custom build locations other than PyPi. Many of the loaders in the "modules" directory are now Windows or Linux specific and for x86_64, though some Linux arm64. ExLlama and GPTQ are this way as well

I've already identified some issues with the llama-cpp-python and now have a reliable build/install. located here: https://github.com/unixwzrd/oobabooga-macOS  Manual for now, but I am working my way through the modules and dependencies. The instructions work, but there are still huge performance issues I am looking into. I decided to focus first on llama-cpp since it will run most models and there are plenty of other things which use stand-alone llama-cpp.

There are still performance problems well before the GPU is accessed and I suspect there is some sort of way the 'mps' device is being replaced in the code somewhere by 'cuda', and later falls back to 'cpu' when the Cuda device isn't found,  but haven't tracked it down.  The issue, I think, is due to different interfaces for PyTorch devices torch.cuda and torch.mps, then there's torch.backends.cuda and torch.device.mps, and just so no one is confused, torch.device([cuda|mps|cpu] [, index]).  Looks like the device is possibly overlaid and building a /torch device calls of *any* device to a ComputeDevice class I'm working on in a separate fork. In the text-generation-webui code, the three types of calls are mixed and matched in various ways.
