### ISSUE TITLE
Windows one-click install gives errors

### ISSUE THREAD

**Issue by mockinbirdy** [oobabooga/text-generation-webui#3123]
### Describe the bug

This repo was installed and reinstalled dozens of times and each way of installation creates different errors. And after going through all the repo issues with similar errors, it leaves you nowhere. For the record, automatic1111 and similar repos installed just fine on my system. Here is what it shows when you try to use it after one-click windows:

1. running start-windows.bat after `conda activate` gives this

```
bin D:\0\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda110.dll
False
D:\0\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:156: UserWarning: D:\0\oobabooga_windows\oobabooga_windows\installer_files\env did not contain ['cudart64_110.dll', 'cudart64_120.dll', 'cudart64_12.dll'] as expected! Searching further paths...
  warn(msg)
D:\0\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:156: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('D:/0/oobabooga_windows/oobabooga_windows/installer_files/env/Library/mingw-w64/bin')}
  warn(msg)
D:\0\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:156: UserWarning: Found duplicate ['cudart64_110.dll', 'cudart64_120.dll', 'cudart64_12.dll'] files: {WindowsPath('C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.0/bin/cudart64_110.dll'), WindowsPath('C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7/bin/cudart64_110.dll'), WindowsPath('C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/bin/cudart64_110.dll'), WindowsPath('C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.0/bin/cudart64_12.dll')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['cudart64_110.dll', 'cudart64_120.dll', 'cudart64_12.dll'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 110
CUDA SETUP: Required library version not found: libbitsandbytes_cuda110.dll. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.dll...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=110 make cuda110
python setup.py install
CUDA SETUP: Setup Failed!
Traceback (most recent call last):
File "D:\0\oobabooga_windows\oobabooga_windows\text-generation-webui\server.py", line 35, in <module>
    from modules import chat, loaders, presets, shared, training, ui, utils
File "D:\0\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\training.py", line 23, in <module>
    from peft import (
File "D:\0\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
File "D:\0\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\peft\mapping.py", line 16, in <module>
    from .peft_model import (
File "D:\0\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\peft\peft_model.py", line 34, in <module>
    from .tuners import (
File "D:\0\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\peft\tuners\__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel
File "D:\0\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\peft\tuners\lora.py", line 41, in <module>
    import bitsandbytes as bnb
File "D:\0\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
File "D:\0\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
File "D:\0\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
File "D:\0\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
File "D:\0\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
File "D:\0\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```

I ran the command `python -m bitsandbytes` and finally got that. But it changed nothing and all errors remained the same.

```
++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = True
COMPUTE_CAPABILITIES_PER_GPU = ['8.6']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
+ library is importable
+ CUDA function is callable

WARNING: Please be sure to sanitize sensible info from any such env vars!

SUCCESS!
Installation was successful!
```

2. what i get if i run [server.py](http://server.py/) with arguments
```
D:\0\oobabooga_windows\oobabooga_windows\text-generation-webui>python [[server.py](http://server.py/)](http://server.py/) --model-dir "E:\models" --notebook --loader exllama --max_seq_len 2048 --compress_pos_emb 1
bin C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll
C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\[[cextension.py:34](http://cextension.py:34/)](http://cextension.py:34/): UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
function 'cadam32bit_grad_fp32' not found
2023-07-13 06:39:48 INFO:Loading airoboros-13B-gpt4-1.4-GPTQ...
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7'
2023-07-13 06:39:48 WARNING:Exllama module failed to load. Will attempt to load from repositories.
2023-07-13 06:39:48 ERROR:Could not find repositories/exllama/. Make sure that exllama is cloned inside repositories/ and is up to date.
Traceback (most recent call last):
  
File "D:\0\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\[[exllama.py](http://exllama.py/)](http://exllama.py/)", line 10, in <module>
    from exllama.generator import ExLlamaGenerator
  
File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\exllama\__init__.py", line 1, in <module>
    from . import cuda_ext, generator, model, tokenizer
  
File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\exllama\cuda_[[ext.py](http://ext.py/)](http://ext.py/)", line 9, in <module>
    import exllama_ext
ImportError: DLL load failed while importing exllama_ext: 
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  
File "D:\0\oobabooga_windows\oobabooga_windows\text-generation-webui\[[server.py](http://server.py/)](http://server.py/)", line 1157, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  
File "D:\0\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\[[models.py](http://models.py/)](http://models.py/)", line 78, in load_model
    output = load_func_map[loader](model_name)
  
File "D:\0\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\[[models.py](http://models.py/)](http://models.py/)", line 296, in ExLlama_loader
    from modules.exllama import ExllamaModel
  
File "D:\0\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\[[exllama.py](http://exllama.py/)](http://exllama.py/)", line 19, in <module>
    from generator import ExLlamaGenerator
  
File "D:\0\oobabooga_windows\oobabooga_windows\text-generation-webui\repositories\exllama\[[generator.py](http://generator.py/)](http://generator.py/)", line 1, in <module>
    import cuda_ext
  
File "D:\0\oobabooga_windows\oobabooga_windows\text-generation-webui\repositories\exllama\cuda_[[ext.py](http://ext.py/)](http://ext.py/)", line 43, in <module>
    exllama_ext = load(
  
File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_[[extension.py](http://extension.py/)](http://extension.py/)", line 1284, in load
    return jitcompile(
  
File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_[[extension.py](http://extension.py/)](http://extension.py/)", line 1509, in jitcompile
    writeninja_file_and_build_library(
  
File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_[[extension.py](http://extension.py/)](http://extension.py/)", line 1611, in writeninja_file_and_build_library
    writeninja_file_to_build_library(
  
File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_[[extension.py](http://extension.py/)](http://extension.py/)", line 2007, in writeninja_file_to_build_library
    cuda_flags = common_cflags + COMMON_NVCC_FLAGS + getcuda_arch_flags()
  
File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_[[extension.py](http://extension.py/)](http://extension.py/)", line 1773, in getcuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range
```
3. what i get if i run [server.py](http://server.py/) with arguments without --loader exllama
```
D:\0\oobabooga_windows\oobabooga_windows\text-generation-webui>python [[server.py](http://server.py/)](http://server.py/) --model-dir "E:\models" --notebook --max_seq_len 2048 --compress_pos_emb 1
bin C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll
C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\[[cextension.py:34](http://cextension.py:34/)](http://cextension.py:34/): UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
function 'cadam32bit_grad_fp32' not found
2023-07-13 06:47:09 INFO:Loading airoboros-13B-gpt4-1.4-GPTQ...
2023-07-13 06:47:09 INFO:The AutoGPTQ params are: {'model_basename': '[[airoboros-13b-gpt4-1.4-GPTQ-4bit-128g.no](http://airoboros-13b-gpt4-1.4-gptq-4bit-128g.no/)](http://airoboros-13b-gpt4-1.4-gptq-4bit-128g.no/)-act.order', 'device': 'cuda:0', 'use_triton': False, 'inject_fused_attention': True, 'inject_fused_mlp': True, 'use_safetensors': True, 'trust_remote_code': False, 'max_memory': None, 'quantize_config': None, 'use_cuda_fp16': True}
2023-07-13 06:47:09 WARNING:The model weights are not tied. Please use the tie_weights method before using the infer_auto_device function.
2023-07-13 06:47:09 WARNING:The safetensors archive passed at E:\models\airoboros-13B-gpt4-1.4-GPTQ\[[airoboros-13b-gpt4-1.4-GPTQ-4bit-128g.no](http://airoboros-13b-gpt4-1.4-gptq-4bit-128g.no/)](http://airoboros-13b-gpt4-1.4-gptq-4bit-128g.no/)-act.order.safetensors does not contain metadata. Make sure to save your model with the save_pretrained method. Defaulting to 'pt' metadata.
Traceback (most recent call last):
  
File "D:\0\oobabooga_windows\oobabooga_windows\text-generation-webui\[[server.py](http://server.py/)](http://server.py/)", line 1157, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  
File "D:\0\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\[[models.py](http://models.py/)](http://models.py/)", line 78, in load_model
    output = load_func_map[loader](model_name)
  
File "D:\0\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\[[models.py](http://models.py/)](http://models.py/)", line 292, in AutoGPTQ_loader
    return modules.AutoGPTQ_loader.load_quantized(model_name)
  
File "D:\0\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\AutoGPTQ_[[loader.py](http://loader.py/)](http://loader.py/)", line 56, in load_quantized
    model = AutoGPTQForCausalLM.from_quantized(path_to_model, **params)
  
File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\auto_gptq\modeling\[[auto.py](http://auto.py/)](http://auto.py/)", line 82, in from_quantized
    return quant_func(
  
File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\auto_gptq\modeling\_[[base.py](http://base.py/)](http://base.py/)", line 773, in from_quantized
    accelerate.utils.modeling.load_checkpoint_in_model(
  
File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\utils\[[modeling.py](http://modeling.py/)](http://modeling.py/)", line 1094, in load_checkpoint_in_model
    checkpoint = load_state_dict(checkpoint_file, device_map=device_map)
  
File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\utils\[[modeling.py](http://modeling.py/)](http://modeling.py/)", line 946, in load_state_dict
    return safe_load_file(checkpoint_file, device=list(device_map.values())[0])
  
File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\safetensors\[[torch.py](http://torch.py/)](http://torch.py/)", line 261, in load_file
    result[k] = f.get_tensor(k)
  
File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda\__init__.py", line 239, in lazyinit
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```
Also yes, tried different torch versions, cuda versions.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Install it and try to use it

### Logs

```shell
included above
```

### System Info

```shell
win 10, nvidia
```

**Comment by jllllll** [comment]
> running start-windows.bat after `conda activate` gives this

Don't run `start_windows.bat` after `conda activate`. `start_windows.bat` activates the Conda env on it's own.

Your logs are indicative of installing the webui with the CPU-only option as the CUDA runtime dll was not found in the Conda env, where it would be if selecting the NVIDIA option in the installer.

**Comment by mockinbirdy** [comment]
Running `start_windows.bat` right off the bat activates the webui with no models, no arguments, no nothing. So I can open the localhost but it's completely useless. 

And as stated above and in my previously opened issue, I selected NVIDIA with each installation and even manually reinstalled cuda for NVIDIA after it showed me the error about CPU. It does not fix the issue.

**Comment by bbecausereasonss** [comment]
I've been getting this very same error recently. 

model weights are not tied.
