### ISSUE TITLE
Falcon40B 4bit is slower than 8 bit

### ISSUE THREAD

**Issue by amanbirs** [oobabooga/text-generation-webui#3127]
### Describe the bug

I'm using the API options of text-generation-webui on a runpod machine. I downloaded the tiiuae/falcon-40b-instruct model to run some tests.

My problem is when I run the model in 4 bit it is extremely slow. Much slower than 8 bit as well. Inference times for the same prompt are below:

4 bit:   Output generated in 17.11 seconds (3.27 tokens/s, 56 tokens, context 21, seed 1642262622)
8 bit:   Output generated in 13.11 seconds (4.50 tokens/s, 59 tokens, context 21, seed 1585467573)

It seems to be correctly loading the model in 4 bits since the memory consumption is half of the 8-bit memory consumption (~23GB vs ~44GB). 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

`python3 ./download-model.py  tiiuae/falcon-40b-instruct

python3 ./server.py --model  tiiuae_falcon-40b-instruct --api --listen --public-api --trust-remote-code --chat --share --load-in-4bit`

### Logs

```shell
api --trust-remote-code --chat --share --load-in-4bit 
2023-07-13 12:24:16 WARNING:trust_remote_code is enabled. This is dangerous.
2023-07-13 12:24:16 WARNING:The gradio "share link" feature uses a proprietary executable to create a reverse tunnel. Use it with care.
bin /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so
2023-07-13 12:24:17 INFO:Loading tiiuae_falcon-40b-instruct...
2023-07-13 12:24:17 WARNING:Using the following 4-bit params: {'load_in_4bit': True, 'bnb_4bit_compute_dtype': torch.float16, 'bnb_4bit_quant_type': 'nf4', 'bnb_4bit_use_double_quant': False}
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████| 9/9 [01:26<00:00,  9.66s/it]
2023-07-13 12:25:47 INFO:Loaded the model in 89.33 seconds.

2023-07-13 12:25:47 INFO:Loading the extension "gallery"...
Traceback (most recent call last):
  File "/workspace/text-generation-webui/extensions/api/util.py", line 102, in _start_cloudflared
    public_url = _run_cloudflared(port, port + 1)
  File "/usr/local/lib/python3.10/dist-packages/flask_cloudflared.py", line 69, in _run_cloudflared
    _download_cloudflared(cloudflared_path, command)
  File "/usr/local/lib/python3.10/dist-packages/flask_cloudflared.py", line 101, in _download_cloudflared
    update_cloudflared = subprocess.Popen([(cloudflared_path+'/'+command), 'update'], stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/tmp/cloudflared-linux-amd64'
Traceback (most recent call last):
  File "/workspace/text-generation-webui/extensions/api/util.py", line 102, in _start_cloudflared
    public_url = _run_cloudflared(port, port + 1)
  File "/usr/local/lib/python3.10/dist-packages/flask_cloudflared.py", line 69, in _run_cloudflared
    _download_cloudflared(cloudflared_path, command)
  File "/usr/local/lib/python3.10/dist-packages/flask_cloudflared.py", line 101, in _download_cloudflared
    update_cloudflared = subprocess.Popen([(cloudflared_path+'/'+command), 'update'], stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/tmp/cloudflared-linux-amd64'
Running on local URL:  http://0.0.0.0:7860
Exception in thread Thread-4 (_start_cloudflared):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/text-generation-webui/extensions/api/util.py", line 112, in _start_cloudflared
    raise Exception('Could not start cloudflared.')
Exception: Could not start cloudflared.
Exception in thread Thread-5 (_start_cloudflared):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/text-generation-webui/extensions/api/util.py", line 112, in _start_cloudflared
    raise Exception('Could not start cloudflared.')
Exception: Could not start cloudflared.
Running on public URL: https://be9b23763e4272906a.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
100.64.0.22 - - [13/Jul/2023 12:25:58] "POST /api/v1/generate HTTP/1.1" 200 -
Output generated in 17.11 seconds (3.27 tokens/s, 56 tokens, context 21, seed 1642262622)
```

### System Info

```shell
runpod.io machine
A100 80GB GPU
Ubuntu 22.04.2 LTS
```

**Comment by amanbirs** [comment]
ahh understood. Thanks for pointing that out. Will close the issue.
