### ISSUE TITLE
Trojan detected in one-click installer

### ISSUE THREAD

**Issue by ScarredRazor** [oobabooga/text-generation-webui#3133]
### Describe the bug

Encountered a Trojan that triggered windows defender while trying to install Oobabooga.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run the one-click installer.

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/139471699/0d61e565-8c66-4c36-8ae0-e66d13ae3d45)

### Logs

```shell
*******************************************************************
* WARNING: You haven't downloaded any model yet.
* Once the web UI launches, head over to the bottom of the "Model" tab and download one.
*******************************************************************


Traceback (most recent call last):
  File "C:\Ooba\text-generation-webui\server.py", line 12, in <module>
    import gradio as gr
  File "C:\Ooba\installer_files\env\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\Ooba\installer_files\env\lib\site-packages\gradio\components.py", line 56, in <module>
    from gradio.blocks import Block, BlockContext
  File "C:\Ooba\installer_files\env\lib\site-packages\gradio\blocks.py", line 26, in <module>
    from gradio import (
  File "C:\Ooba\installer_files\env\lib\site-packages\gradio\networking.py", line 17, in <module>
    from gradio.routes import App
  File "C:\Ooba\installer_files\env\lib\site-packages\gradio\routes.py", line 49, in <module>
    from gradio.helpers import EventData
  File "C:\Ooba\installer_files\env\lib\site-packages\gradio\helpers.py", line 17, in <module>
    import matplotlib.pyplot as plt
  File "C:\Ooba\installer_files\env\lib\site-packages\matplotlib\pyplot.py", line 53, in <module>
    import matplotlib.image
  File "C:\Ooba\installer_files\env\lib\site-packages\matplotlib\image.py", line 18, in <module>
    from matplotlib import _image
ImportError: DLL load failed while importing _image: Operation did not complete successfully because the file contains a virus or potentially unwanted software.
Press any key to continue . . .
```

### System Info

```shell
Operating System: Windows 11
Processor: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
GPU: NVIDIA EVGA GEFORCE GTX 1080 FTW
Ram: 16GB DDR 4
Storage: SSD
```

**Comment by FranciscoFornell** [comment]
Hi! I opened [this](https://github.com/oobabooga/text-generation-webui/security/advisories/GHSA-mjm9-44r5-9g39), not sure if was the correct way or if it should be a bug like this one. But it's the exact same issue.
I even run the installer a second time to check it downloaded an infected file, and not that it got infected some other way, but as soon as the file was downloaded, the trojan was detected.

**Comment by pturri83** [comment]
I am not using Oobabooga, but I get the same problem ("_image" being quarantined as a "Trojan:Win32/Randet.A!plock") whenever I try to import some modules from matplotlib. Yesterday it was working fine, not so much today. It is likely a problem with the latest Windows Defender update

**Comment by jllllll** [comment]
Nothing to do with the one-click-installer. matplotlib is a dependency of Gradio.
matplotlib 3.7.2 was released on July 5. I would think if there was a trojan in that version that people would have mentioned it before given how widely used matplotlib is. Very likely a false positive.

**Comment by pturri83** [comment]
> Nothing to do with the one-click-installer. matplotlib is a dependency of Gradio. matplotlib 3.7.2 was released on July 5. I would think if there was a trojan in that version that people would have mentioned it before given how widely used matplotlib is. Very likely a false positive.

Yes, the problem is likely with the latest virus definitions update of Windows Defender. I have solved it by adding the folder with all my Python environments (including the matplotlib modules) to the list of folders excluded by Windows Security
