### ISSUE TITLE
(Linux) submitting non 512x512 cards errors, cannot be used

### ISSUE THREAD

**Issue by BarfingLemurs** [oobabooga/text-generation-webui#3140]
### Describe the bug

tried this: https://chub.ai/characters/ClausOfTheNewMoon/r63-father-penguin-super-mario-64

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

submit non-512x512 card, and it will not register in the gallery nor text-generation tab.
all metadata is read. uploaded card is transformed into a json and png in the `characters` folder.
If you replace the picture in the character folder with a 512x512 image, it will work.

If you resize the image to a square manually with the gradio image editor, it will work. 

### Screenshot

![main_r63-father-penguin-super-mario-64_tavern](https://github.com/oobabooga/text-generation-webui/assets/128182951/202ff5bd-073f-4722-85f0-fed9aece95c1)

### Logs

```shell
2023-07-14 01:00:14 INFO:New character saved to "characters/TavernAI-R63 Father Penguin - Super Mario 64.json".
Traceback (most recent call last):
  File "/home/user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/user/oobabooga_linux/text-generation-webui/modules/chat.py", line 482, in load_character
    picture = generate_pfp_cache(character)
  File "/home/user/oobabooga_linux/text-generation-webui/modules/chat.py", line 463, in generate_pfp_cache
    img = make_thumbnail(Image.open(path))
  File "/home/user/oobabooga_linux/text-generation-webui/modules/html_generator.py", line 132, in make_thumbnail
    image = ImageOps.fit(image, (350, 470), Image.ANTIALIAS)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```
```


### System Info

```shell
Ubuntu 22.04
```

**Comment by missionfloyd** [comment]
That error has been [fixed](https://github.com/oobabooga/text-generation-webui/pull/2954). Try updating.
