### ISSUE TITLE
CUDA OOM while there are still plenty of free VRAM

### ISSUE THREAD

**Issue by viktor-ferenczi** [oobabooga/text-generation-webui#3161]
### Describe the bug

Trying to load [https://huggingface.co/Salesforce/codegen-16B-mono](https://huggingface.co/Salesforce/codegen-16B-mono) at 9-bit, bfloat16, auto-devices and trust-remote-code enabled. All other settings are at their defaults. GPU is 4090 with 24GB RAM. Windows is using only ~1.4GB of VRAM.

Tried to allocate **144.00 MiB** (GPU 0; 23.99 GiB total capacity; 14.22 GiB already allocated; **7.57 GiB free**; 14.43 GiB reserved in total by PyTorch)

Tried to set gpu-memory to 21GB, lower than free VRAM, but larger than 16GB. It did not help.

Regular RAM is 64GB, it seems to be enough as well.

Why does a relatively small allocation fail if there is plenty of VRAM left?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load [https://huggingface.co/Salesforce/codegen-16B-mono](https://huggingface.co/Salesforce/codegen-16B-mono) at 9-bit, bfloat16, auto-devices and trust-remote-code enabled.

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/1848514/c6f3a780-48f9-4a72-8a0f-d2fb8fe9dae4)

### Logs

```shell
2023-07-16 04:24:56 INFO:Loading Salesforce_codegen-16B-mono...
2023-07-16 04:24:56 WARNING:The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
2023-07-16 04:25:31 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "D:\oobabooga_windows\text-generation-webui\server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "D:\oobabooga_windows\text-generation-webui\modules\models.py", line 74, in load_model
    output = load_func_map[loader](model_name)
  File "D:\oobabooga_windows\text-generation-webui\modules\models.py", line 206, in huggingface_loader
    model = LoaderClass.from_pretrained(checkpoint, **params)
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 484, in from_pretrained
    return model_class.from_pretrained(
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2881, in from_pretrained
    ) = cls._load_pretrained_model(
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 3228, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 728, in _load_state_dict_into_meta_model
    set_module_quantized_tensor_to_device(
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\utils\bitsandbytes.py", line 89, in set_module_quantized_tensor_to_device
    new_value = bnb.nn.Int8Params(new_value, requires_grad=False, **kwargs).to(device)
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\nn\modules.py", line 294, in to
    return self.cuda(device)
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\nn\modules.py", line 258, in cuda
    CB, CBt, SCB, SCBt, coo_tensorB = bnb.functional.double_quant(B)
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\functional.py", line 1998, in double_quant
    out_col = torch.zeros(A.shape, device=device, dtype=torch.int8)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 144.00 MiB (GPU 0; 23.99 GiB total capacity; 14.22 GiB already allocated; 7.57 GiB free; 14.43 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
```


### System Info

```shell
Ryzen 3800X, 64GB RAM, RTX 4090 24GB VRAM, Windows 11
```

**Comment by RandomInternetPreson** [comment]
I'm having the same issue, I can't load models I used to to load with previous versions :C

**Comment by viktor-ferenczi** [comment]
So we "just" need to roll back a few version(s). It may bring back another (already fixed) issues, however, so this is only a workaround at best.

Which one is the last working for your model? 

Also, which model have your tried to load (if not a secret)?

**Comment by RandomInternetPreson** [comment]
So I don't know if this will help you, but the problem has cleared up for me.  I did the following:

1. I ran the update_window.bat file, this still did not resolve the issue. But maybe this needs to be done still, idk.
2. I deleted all the files from my temp directory C:\Users\"insert your name here"\AppData\Local\Temp
3. I turned off my computer, flipped the power button off on my power supply and pressed the power button.  I don't know if this does anything, but in my mind it makes sure all the ram is all cleared everywhere.
4. Loaded the modes that once loaded but wouldn't, and now they do.

The version that was not giving me any issues was from July 8, https://github.com/oobabooga/text-generation-webui/commit/acf24ebb49d0077796508ab05630d8d5ae3df14d

**Comment by RandomInternetPreson** [comment]
I don't know if you ever got this working, but I ran into the problem again...and it was because I had turned off paging files.  I have 128GB of cpu ram, but sometimes models need A LOT of cpu ram to load up.  If it's possible for you, if you jack up your paging files so you have 300GB in total (cpu ram + paging files) you should have enough to load up all your models if that is the issue.

**Comment by bbecausereasonss** [comment]
Getting this issue as well model weights are not tied.
