### ISSUE TITLE
Multiple GPUs use '--gpu-memory'

### ISSUE THREAD

**Issue by JeffFong172** [oobabooga/text-generation-webui#3170]
### Describe the bug

Hello,  I've got the 13B_alpaca model loaded onto a node with 2x RTX4090 24GB. 
try `python server.py --model 13B_alpaca --chat --listen --listen-port 7861 --gpu-memory 20 20`
It loads into memory OK, but crashes out when I try to generate with a CUDA error:

lots of:

/opt/conda/conda-bld/pytorch_1682343995026/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [123,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.

and finally:

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.

It seems that`--gpu-memory` have mistake. I use 7B_alpaca with `--gpu-memory`, doing this is the same mistake, and it is ok that I use it without `--gpu-memory`.

I am unsure what to do.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

start webui
load model
generate it
then shows error

### Logs

```shell
/opt/conda/conda-bld/pytorch_1682343995026/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [6,0,0], thread: [115,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343995026/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [6,0,0], thread: [116,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343995026/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [6,0,0], thread: [117,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343995026/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [6,0,0], thread: [118,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343995026/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [6,0,0], thread: [119,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343995026/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [6,0,0], thread: [120,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343995026/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [6,0,0], thread: [121,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343995026/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [6,0,0], thread: [122,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343995026/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [6,0,0], thread: [123,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343995026/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [6,0,0], thread: [124,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343995026/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [6,0,0], thread: [125,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343995026/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [6,0,0], thread: [126,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343995026/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [6,0,0], thread: [127,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "/opt/text-generation-webui/modules/callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "/opt/text-generation-webui/modules/text_generation.py", line 297, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/work/ai/conda/envs/llama/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/work/ai/conda/envs/llama/lib/python3.10/site-packages/transformers/generation/utils.py", line 1572, in generate
    return self.sample(
  File "/work/ai/conda/envs/llama/lib/python3.10/site-packages/transformers/generation/utils.py", line 2619, in sample
    outputs = self(
  File "/work/ai/conda/envs/llama/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/work/ai/conda/envs/llama/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/work/ai/conda/envs/llama/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 688, in forward
    outputs = self.model(
  File "/work/ai/conda/envs/llama/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/work/ai/conda/envs/llama/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 578, in forward
    layer_outputs = decoder_layer(
  File "/work/ai/conda/envs/llama/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/work/ai/conda/envs/llama/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/work/ai/conda/envs/llama/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/work/ai/conda/envs/llama/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/work/ai/conda/envs/llama/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/work/ai/conda/envs/llama/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 227, in forward
    attn_weights, torch.tensor(torch.finfo(attn_weights.dtype).min, device=attn_weights.device)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception in thread Thread-3 (gentask):
Traceback (most recent call last):
  File "/work/ai/conda/envs/llama/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/work/ai/conda/envs/llama/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/text-generation-webui/modules/callbacks.py", line 62, in gentask
    clear_torch_cache()
  File "/opt/text-generation-webui/modules/callbacks.py", line 94, in clear_torch_cache
    torch.cuda.empty_cache()
  File "/work/ai/conda/envs/llama/lib/python3.10/site-packages/torch/cuda/memory.py", line 133, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### System Info

```shell
gpu: Nvidia RTX 4090*2 24gb
Driver Version: 525.78.01
cuda version:11.8
conda version:22.9.0
system: ubuntu 22.04
```

**Comment by JeffFong172** [comment]
> Does it actually load into both GPU? As in you're loading it in FP16? I don't remember if the HF loader automatically knows to not split certain layers like `no_split_module_classes=["LlamaDecoderLayer"]` which is done in gptq/autogptq
> 
> Try to update transformers and accelerate and see if it goes away.

it will load into both GPU, and I loading it in FP16. I can load 7B model, but when I try to load 13B model, it wills `CUDA out of memory` without `--gpu-memory`. Add `--gpu-memory 20 20` can load  but crashes out when I try to generate with a CUDA error. I don't know what problem.

**Comment by Ph0rk0z** [comment]
How does it split? Evenly? Maybe use different memory limits and with luck the decoder layer doesn't get split. I can try this with a fp16 llama later and see what it does on my system.

**Comment by JeffFong172** [comment]
> How does it split? Evenly? Maybe use different memory limits and with luck the decoder layer doesn't get split. I can try this with a fp16 llama later and see what it does on my system.

Yes，evenly. Only one WARNING 
WARNING:The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function. 
it  load successful, but didn't generate.

**Comment by wz0424** [comment]
I had this problem too, have you solved it yet?

**Comment by kyleboddy** [comment]
Wait, seriously? Can you not use gpu-split from the command line by using gpu-memory and multiple arguments? I am having this issue as well.
