### ISSUE TITLE
Error when trying to limit GPU memory

### ISSUE THREAD

**Issue by ANimeisbestu** [oobabooga/text-generation-webui#32]
C:\text-generation-webui>python server.py --model PygmalionAI_pygmalion-2.7b --gpu-memory 5 --cai-chat --no-stream --listen &
Loading PygmalionAI_pygmalion-2.7b...
Traceback (most recent call last):
  File "C:\text-generation-webui\server.py", line 284, in <module>
    model, tokenizer = load_model(model_name)
  File "C:\text-generation-webui\server.py", line 113, in load_model
    model = eval(command)
  File "<string>", line 1, in <module>
  File "C:\Users\(name)\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 446, in from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, config=config, **kwargs)
  File "C:\Users\(name)\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 2024, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
TypeError: GPTNeoForCausalLM.__init__() got an unexpected keyword argument 'device_map'

**Comment by oobabooga** [comment]
I cannot reproduce

```
$ python server.py --model pygmalion-2.7b --gpu-memory 5 --cai-chat --no-stream --listen
Loading pygmalion-2.7b...
Loaded the model in 6.77 seconds.
```

Did you create the conda environment and install the requirements as described in the README?

**Comment by ANimeisbestu** [comment]
the require
