### ISSUE TITLE
Exllama loader work on itself but not when with webui

### ISSUE THREAD

**Issue by fgdfgfthgr-fox** [oobabooga/text-generation-webui#3204]
### Describe the bug

I was trying to load a llama 2 13b 4bit gptq model. I can load and complete Perplexity calculation using the test_benchmark_inference.py as shown in the log below. **(part 1)**
However, when I use the webui to try to load the model, it errors out as failed to build exllama_ext, despite the building has already been done when running the test_benchmark_inference.py, as shown in the log below. **(part 2)**
Note it's showing missing hipcc, however hipcc is present on this computer and the build can be finished if not using the webui.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Don't install the jllllll's exllama release, as that one won't work neither on my system.
2. Use git clone to get exllama under repositories/exllama
3. Run test_benchmark_inference.py, see it finish building the extension and evaluate the Perplexity
4. Launch webui with server.py
5. Try to load the same model again using ExLlama model loader

### Logs

```shell
**Part 1:**
(textgen) fgdfgfthgr@fgdfgfthgr-MS-7C95:/mnt/7018F20D48B6C548/text-generation-webui/repositories/exllama$ python test_benchmark_inference.py -d /mnt/7018F20D48B6C548/text-generation-webui/models/gptq-llama2-13b-128g -p -ppl
Successfully preprocessed all matching files.
 -- Perplexity:
 -- - Dataset: datasets/wikitext2_val_sample.jsonl
 -- - Chunks: 100
 -- - Chunk size: 2048 -> 2048
 -- - Chunk overlap: 0
 -- - Min. chunk size: 50
 -- - Key: text
 -- Tokenizer: /mnt/7018F20D48B6C548/text-generation-webui/models/gptq-llama2-13b-128g/tokenizer.model
 -- Model config: /mnt/7018F20D48B6C548/text-generation-webui/models/gptq-llama2-13b-128g/config.json
 -- Model: /mnt/7018F20D48B6C548/text-generation-webui/models/gptq-llama2-13b-128g/gptq_model-4bit-128g.safetensors
 -- Sequence length: 2048
 -- Tuning:
 -- --matmul_recons_thd: 8
 -- --fused_mlp_thd: 2
 -- --sdp_thd: 8
 -- --rmsnorm_no_half2
 -- --rope_no_half2
 -- --matmul_no_half2
 -- --silu_no_half2
 -- Options: ['perf', 'perplexity']
 ** Time, Load model: 66.45 seconds
 ** Time, Load tokenizer: 0.01 seconds
 -- Groupsize (inferred): 128
 -- Act-order (inferred): yes
 ** VRAM, Model: [cuda:0] 6,873.52 MB
 -- Warmup pass 1...
 ** Time, Warmup: 11.29 seconds
 -- Warmup pass 2...
 ** Time, Warmup: 6.39 seconds
 -- Inference, first pass.
 ** Time, Inference: 6.49 seconds
 ** Speed: 295.98 tokens/second
 -- Generating 128 tokens, 1920 token prompt...
 ** Speed: 7.68 tokens/second
 -- Generating 128 tokens, 4 token prompt...
 ** Speed: 16.43 tokens/second
 ** VRAM, Inference: [cuda:0] 2,253.20 MB
 ** VRAM, Total: [cuda:0] 9,126.72 MB
 -- Loading dataset...
 -- Testing 100 chunks..........
 ** Perplexity: 5.3531



**Part 2:**
/home/fgdfgfthgr/anaconda3/envs/textgen/bin/python /mnt/7018F20D48B6C548/text-generation-webui/server.py 
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
2023-07-20 01:08:08 INFO:Loading gptq-llama2-13b-128g...
2023-07-20 01:08:08 WARNING:Exllama module failed to load. Will attempt to load from repositories.
Successfully preprocessed all matching files.
2023-07-20 01:08:09 ERROR:Could not find repositories/exllama/. Make sure that exllama is cloned inside repositories/ and is up to date.
2023-07-20 01:08:09 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/mnt/7018F20D48B6C548/text-generation-webui/modules/exllama.py", line 10, in <module>
    from exllama.generator import ExLlamaGenerator
ModuleNotFoundError: No module named 'exllama'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/7018F20D48B6C548/text-generation-webui/server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/mnt/7018F20D48B6C548/text-generation-webui/modules/models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "/mnt/7018F20D48B6C548/text-generation-webui/modules/models.py", line 318, in ExLlama_loader
    from modules.exllama import ExllamaModel
  File "/mnt/7018F20D48B6C548/text-generation-webui/modules/exllama.py", line 19, in <module>
    from generator import ExLlamaGenerator
  File "/mnt/7018F20D48B6C548/text-generation-webui/repositories/exllama/generator.py", line 1, in <module>
    import cuda_ext
  File "/mnt/7018F20D48B6C548/text-generation-webui/repositories/exllama/cuda_ext.py", line 43, in <module>
    exllama_ext = load(
  File "/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'exllama_ext': [1/11] bin/hipcc  -DWITH_HIP -DTORCH_EXTENSION_NAME=exllama_ext -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/mnt/7018F20D48B6C548/text-generation-webui/repositories/exllama/exllama_ext -isystem /home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/include -isystem /home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/include/TH -isystem /home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/include/THC -isystem /home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/include/THH -isystem include -isystem /home/fgdfgfthgr/anaconda3/envs/textgen/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -fPIC -D__HIP_PLATFORM_HCC__=1 -DUSE_ROCM=1 -DCUDA_HAS_FP16=1 -D__HIP_NO_HALF_OPERATORS__=1 -D__HIP_NO_HALF_CONVERSIONS__=1 -lineinfo -U__HIP_NO_HALF_CONVERSIONS__ -O3 --amdgpu-target=gfx900 --amdgpu-target=gfx906 --amdgpu-target=gfx908 --amdgpu-target=gfx90a --amdgpu-target=gfx1030 -fno-gpu-rdc -c /mnt/7018F20D48B6C548/text-generation-webui/repositories/exllama/exllama_ext/hip_func/q4_matrix.hip -o q4_matrix.cuda.o 
FAILED: q4_matrix.cuda.o
```

### System Info

```shell
CPU: Ryzen 5500
GPU: Radeon VII
OS: Linux Mint 21.1
RAM: 64GB of DDR4 running at 3000MHz
```

**Comment by jllllll** [comment]
I have a ROCm 5.4.2/3 version of the exllama module here if you want to try it:
https://github.com/jllllll/exllama/releases/download/0.0.7/exllama-0.0.7+rocm5.4.2-cp310-cp310-linux_x86_64.whl

No clue if it actually works or not as I don't have an AMD GPU to test with. It does build successfully at least.

**Comment by fgdfgfthgr-fox** [comment]
> I have a ROCm 5.4.2/3 version of the exllama module here if you want to try it:
It works now, thanks!

**Comment by fgdfgfthgr-fox** [comment]
> I run it using python's venv instead of conda, Could this be the cause?

Unlikely, because I am running conda and have same issue.

**Comment by jllllll** [comment]
I use GitHub Actions to build the exllama wheels. This is the workflow for building the ROCm wheels with the most relevant part highlighted:
https://github.com/jllllll/exllama/blob/master/.github/workflows/build-wheels-release-rocm.yml#L39-L49

The part that may be different to your setup is the environment variables:
- `/opt/rocm/bin` (ROCm `bin` directory) is added to `PATH`
- `ROCM_PATH` is set to `/opt/rocm` (ROCm root directory)
- `ROCM_VERSION` is set to `5.4.2`
  - Don't think that one is relevant as I was just using it for the workflow's scripting.

**Comment by alangwell** [comment]
Unsure whether this will be helpful, _but_ it seems when I had the same issue that simply running from virtualenv rather than (Mini)conda seems to have sorted this for me, but I'm still troubleshooting some other issues elsewhere, but simply changing the Environment seems to have helped me
