### ISSUE TITLE
sentence_transformers missing for openai extension

### ISSUE THREAD

**Issue by TheMasterFX** [oobabooga/text-generation-webui#3207]
### Describe the bug

When activating the openai extension I get the following error:
```
2023-07-19 19:29:31 ERROR:Failed to load the extension "openai".
Traceback (most recent call last):
  File "F:\text-gen-webui\text-generation-webui\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "F:\text-gen-webui\text-generation-webui\extensions\openai\script.py", line 10, in <module>
    import extensions.openai.models as OAImodels
  File "F:\text-gen-webui\text-generation-webui\extensions\openai\models.py", line 7, in <module>
    from extensions.openai.embeddings import get_embeddings_model_name
  File "F:\text-gen-webui\text-generation-webui\extensions\openai\embeddings.py", line 2, in <module>
    from sentence_transformers import SentenceTransformer
ModuleNotFoundError: No module named 'sentence_transformers'
```
After installing sentence_transformers in the venv everythin works fine. So requirements.txt should be include sentence_transformers 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Install/update text-generation-webui to 3c076c3..0d7f432
2. Activate openai extension (eg in start-webui.bat via --extension openai)
3. Start webui

### Logs

```shell
Starting the web UI...
bin F:\text-gen-webui\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
2023-07-19 20:44:20 INFO:Loading the extension "openai"...
2023-07-19 20:44:20 ERROR:Failed to load the extension "openai".
Traceback (most recent call last):
  File "F:\text-gen-webui\text-generation-webui\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "F:\text-gen-webui\text-generation-webui\extensions\openai\script.py", line 10, in <module>
    import extensions.openai.models as OAImodels
  File "F:\text-gen-webui\text-generation-webui\extensions\openai\models.py", line 7, in <module>
    from extensions.openai.embeddings import get_embeddings_model_name
  File "F:\text-gen-webui\text-generation-webui\extensions\openai\embeddings.py", line 2, in <module>
    from sentence_transformers import SentenceTransformer
ModuleNotFoundError: No module named 'sentence_transformers'
Starting streaming server at ws://0.0.0.0:5005/api/v1/stream
2023-07-19 20:44:20 INFO:Loading the extension "gallery"...
Starting API at http://0.0.0.0:5000/api
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
```

### System Info

```shell
Intel Xeon E5-1650 v3
64 GB DDR ECC RAM
Geforce 3080 (10 GB)
```

**Comment by xydreen** [comment]
Did you install the additional requirements (the pip ones - requirements.txt) from the extensions\openai folder (while inside the relevant environment)?

**Comment by TheMasterFX** [comment]
Yes I first activate the env with micromamba-cmd.bat and then install the sentence_transformers

**Comment by matatonic** [comment]
My own update procedure is like this:
```bash
for i in extensions/*/requirements.txt ; do pip3 install -r $i --upgrade ; done
```

**Comment by TheMasterFX** [comment]
Ok that might be, but since it is a build-in plugin it might be reasonable to put it in the superior requirements.txt so that the section of the text-gen-ui README is true

> Updating the requirements
> From time to time, the requirements.txt changes. To update, use this command:
> 
> conda activate textgen
> cd text-generation-webui
> pip install -r requirements.txt --upgrade

**Comment by sumersm7** [comment]
facing same issue even after install the additional requirements and pip install -r requirements.txt --upgrade

**Comment by matatonic** [comment]
> facing same issue even after install the additional requirements and pip install -r requirements.txt --upgrade

That's strange, so you say you installed sentence_transformers but it's still saying "ModuleNotFoundError: No module named 'sentence_transformers'" ?
