### ISSUE TITLE
4bit LLaMA-65B: DefaultCPUAllocator:not enough memory, on 64GB RAM and 48GB total VRAM

### ISSUE THREAD

**Issue by Panchvzluck** [oobabooga/text-generation-webui#321]
### Describe the bug

Hi there, wondering if it's there a way to load the LLaMA-65B model with 64GB of RAM and 48GB of VRAM total (2x4090), since I'm trying with:

`python server.py  --cai-chat --listen --load-in-4bit --listen-port 7990 --gpu-memory 19 21 --no-stream`

But I get DefaultCPUAllocator:not enough memory issue.

I've tried with more pagefile size (ATM with 78GB of swap) and no luck sadly.

The interesting thing, is that when I had 32GB of RAM and I loaded the 30B model, it worked using pagefile itself (It seem to have worked since it loaded more memory than what I had)

Is there a way to load the model with this system configuration?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load 65B LLaMA model, wait some minutes and then the error appears.

### Screenshot

![cmd_W5jH6rxIYs](https://user-images.githubusercontent.com/19153797/225029809-a18584d6-829c-48de-939d-10b5cd62fd20.png)

### Logs

```shell
Loading llama-65b-hf...
Loading model ...
Traceback (most recent call last):
  File "F:\ChatIAs\oobabooga\text-generation-webui\server.py", line 191, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "F:\ChatIAs\oobabooga\text-generation-webui\modules\models.py", line 94, in load_model
    model = load_quantized_LLaMA(model_name)
  File "F:\ChatIAs\oobabooga\text-generation-webui\modules\quantized_LLaMA.py", line 43, in load_quantized_LLaMA
    model = load_quant(str(path_to_model), str(pt_path), bits)
  File "F:\ChatIAs\oobabooga\text-generation-webui\repositories\GPTQ-for-LLaMa\llama.py", line 245, in load_quant
    model.load_state_dict(torch.load(checkpoint))
  File "F:\ChatIAs\oobabooga\textgen\lib\site-packages\torch\serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "F:\ChatIAs\oobabooga\textgen\lib\site-packages\torch\serialization.py", line 1131, in _load
    result = unpickler.load()
  File "F:\ChatIAs\oobabooga\textgen\lib\site-packages\torch\serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "F:\ChatIAs\oobabooga\textgen\lib\site-packages\torch\serialization.py", line 1079, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage).storage().untyped()
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 90177536 bytes.
```

### System Info

CPU: Ryzen 7 5800X
RAM: 64GB DDR4 3800Mhz
GPU: RTX 4090 x x2
```

**Comment by ortegaalfredo** [comment]
Try adding --auto-devices

**Comment by Panchvzluck** [comment]
@ortegaalfredo tried and got the same issue

```
(F:\ChatIAs\oobabooga\textgen) F:\ChatIAs\oobabooga\text-generation-webui>python server.py  --cai-chat --listen --load-in-4bit --listen-port 7990 --gpu-memory 19 21 --no-stream --auto-devices
Loading the extension "gallery"... Ok.
The following models are available:

1. ChanMalion
2. GPT-J-Pyg_PPO-6B
3. gpt-neox-20b
4. KoboldAI_GPT-NeoX-20B-Erebus
5. llama-13b-hf
6. llama-30b-hf
7. llama-65b-hf
8. llama-7b-hf
9. opt-13b
10. OPT-13B-Erebus
11. OPT-13B-Nerybus-Mix
12. opt-6.7b
13. OPT-6.7B-Erebus
14. OPT-6.7B-Nerybus-Mix
15. ppohh-4chan-pygmalion-25-25-50-GPT-J
16. pygmalion-6b
17. pygmalion-6b_b8344bb4eb76a437797ad3b19420a13922aaabe1
18. pygmalion-6b_dev

Which one do you want to load? 1-18

7

Loading llama-65b-hf...
Loading model ...
Traceback (most recent call last):
  File "F:\ChatIAs\oobabooga\text-generation-webui\server.py", line 191, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "F:\ChatIAs\oobabooga\text-generation-webui\modules\models.py", line 94, in load_model
    model = load_quantized_LLaMA(model_name)
  File "F:\ChatIAs\oobabooga\text-generation-webui\modules\quantized_LLaMA.py", line 43, in load_quantized_LLaMA
    model = load_quant(str(path_to_model), str(pt_path), bits)
  File "F:\ChatIAs\oobabooga\text-generation-webui\repositories\GPTQ-for-LLaMa\llama.py", line 245, in load_quant
    model.load_state_dict(torch.load(checkpoint))
  File "F:\ChatIAs\oobabooga\textgen\lib\site-packages\torch\serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "F:\ChatIAs\oobabooga\textgen\lib\site-packages\torch\serialization.py", line 1131, in _load
    result = unpickler.load()
  File "F:\ChatIAs\oobabooga\textgen\lib\site-packages\torch\serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "F:\ChatIAs\oobabooga\textgen\lib\site-packages\torch\serialization.py", line 1079, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage).storage().untyped()
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 33554432 bytes.

(F:\ChatIAs\oobabooga\textgen) F:\ChatIAs\oobabooga\text-generation-webui>pause
```

**Comment by ortegaalfredo** [comment]
Maybe increase swap file? I have same setup but 96 GB RAM and it uses swap.

**Comment by Panchvzluck** [comment]
@ortegaalfredo I have ~80GB of swap and same issue. (Windows resizing automatically)

When setting a manual swap size (let's say, 100GB) it fails instantly instead after some minutes.

**Comment by Panchvzluck** [comment]
@awatuna you were right! Changed it to 140-150GB and it loaded!

Many thanks!

```
Which one do you want to load? 1-18

7

Loading llama-65b-hf...
Loading model ...
Done.
Loaded the model in 109.81 seconds.
```

**Comment by RandomInternetPreson** [comment]
How well does it run on 2x4090s?!?! I'm super curious, compared to the 30b on a single card is it a lot slower or a little bit slower.  

I got the 65B to run on a single card with about 100gb of cpu ram taken up, but eventually got oom errors after a few sentences.

**Comment by ye7iaserag** [comment]
how did you get `--gpu-memory 19` to work with 4bit?

**Comment by Panchvzluck** [comment]
@RandomInternetPreson It's not the fastest, 30b is faster, 65b on the 2x4090s give me about 0.8 tokens/s, and I think 30b is like 4x-5x times faster. The good thing is I don't get OOM even with 512-1024 new tokens, so pretty good.

@ye7iaserag I just tried it and worked without issues, even now I'm using --gpu_memory 16 22 and it works, on GPU 0 it loads actually about 19GB of VRAM, and the rest on GPU 1. I guess from inference and such.

**Comment by RandomInternetPreson** [comment]
Thank you so much for the information, it is greatly appreciated <3

**Comment by ye7iaserag** [comment]
@Panchvzluck very weird, in my case with a single gpu defining a limit for it for the rest to be offloaded to cpu always ends with an OOM

**Comment by Panchvzluck** [comment]
@ye7iaserag maybe something related to cpu layers instead of GPU layers?

Here how my 65b loads looks like

```
(F:\ChatIAs\oobabooga\textgen) F:\ChatIAs\oobabooga\text-generation-webui>python server.py  --extensions api --listen --gptq-bits 4 --listen-port 7990 --gpu-memory 16 22  --auto-devices
The following models are available:

1. ChanMalion
2. GPT-J-Pyg_PPO-6B
3. gpt-neox-20b
4. KoboldAI_GPT-NeoX-20B-Erebus
5. llama-13b-hf
6. llama-30b-hf
7. llama-65b-hf
8. llama-7b-hf
9. opt-13b
10. OPT-13B-Erebus
11. OPT-13B-Nerybus-Mix
12. opt-6.7b
13. OPT-6.7B-Erebus
14. OPT-6.7B-Nerybus-Mix
15. ppo_hh_gpt-j
16. ppohh-4chan-pygmalion-25-25-50-GPT-J
17. pygmalion-6b
18. pygmalion-6b_b8344bb4eb76a437797ad3b19420a13922aaabe1
19. pygmalion-6b_dev

Which one do you want to load? 1-19

7

Loading llama-65b-hf...
Loading model ...
Done.
Loaded the model in 170.07 seconds.
Loading the extension "api"... Ok.
Starting KoboldAI compatible api at http://0.0.0.0:5000/api
Running on local URL:  http://0.0.0.0:7990

To create a public link, set `share=True` in `launch()`.
```

**Comment by ye7iaserag** [comment]
I'm using 
```
python server.py --auto-devices --gpu-memory 8 --gptq-bits=4 --model llama-30b-hf --cai-chat --listen --listen-port=8888
```
but it still tries to load more then 8bg on vram and crashes

**Comment by thot-experiment** [comment]
> @ortegaalfredo tried and got the same issue

I've been running into the same issue trying to run 65B on a heterogeneous system w/ a 1080Ti 11Gb + GV100 32Gb and increasing my swap to 160Gb seems to have solved *that* issue but unfortunately now i'm running into CUDA OOM, just using `--auto-devices`, but will try messing with `--gpu_memory` tomorrow, i'll update here if i make any progress, however I believe the solution to the OP is just adding more swap, and what i have is a separate issue.
