### ISSUE TITLE
LogitsProcessorList import error on model load

### ISSUE THREAD

**Issue by housec84** [oobabooga/text-generation-webui#3210]
### Describe the bug

Apologies if this is just me being dumb... I'm getting the following when trying to load a model using llama_cpp:

`Traceback (most recent call last):
  File "C:\oobabooga\text-generation-webui\server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "C:\oobabooga\text-generation-webui\modules\models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "C:\oobabooga\text-generation-webui\modules\models.py", line 259, in llamacpp_loader
    from modules.llamacpp_model import LlamaCppModel
  File "C:\oobabooga\text-generation-webui\modules\llamacpp_model.py", line 12, in <module>
    from llama_cpp import Llama, LlamaCache, LogitsProcessorList
ImportError: cannot import name 'LogitsProcessorList' from 'llama_cpp' (C:\oobabooga\installer_files\env\lib\site-packages\llama_cpp\__init__.py)`

What am I doing wrong?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Try to load a model with the llama.cpp loader.

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/61622583/833a3681-01aa-4cb7-a6aa-bd50a11e94b6)

### Logs

```shell
To create a public link, set `share=True` in `launch()`.
2023-07-19 22:56:22 INFO:Loading llama-2-7b-chat...
2023-07-19 22:56:22 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "C:\oobabooga\text-generation-webui\server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "C:\oobabooga\text-generation-webui\modules\models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "C:\oobabooga\text-generation-webui\modules\models.py", line 259, in llamacpp_loader
    from modules.llamacpp_model import LlamaCppModel
  File "C:\oobabooga\text-generation-webui\modules\llamacpp_model.py", line 12, in <module>
    from llama_cpp import Llama, LlamaCache, LogitsProcessorList
ImportError: cannot import name 'LogitsProcessorList' from 'llama_cpp' (C:\oobabooga\installer_files\env\lib\site-packages\llama_cpp\__init__.py)
```

### System Info

```shell
nvidia 3080, win 11
```

**Comment by redpanda3** [comment]
I have the same issue
