### ISSUE TITLE
RuntimeError: start (0) + length (2049) exceeds dimension size (2048).

### ISSUE THREAD

**Issue by chigkim** [oobabooga/text-generation-webui#3214]
### Describe the bug

If I load a Llama 2 model with exllama_hf and chat for a while, I get the error: `RuntimeError: start (0) + length (2049) exceeds dimension size (2048).`
Isn't supposed to automatically remove old messages to fit the max context length?
Also I thought Llama 2 increased the context length from 2048 to 4096?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

!python download-model.py localmodels/Llama-2-13B-GPTQ --output models
!python server.py --verbose --share --chat --model-dir models --model localmodels_Llama-2-13B-GPTQ --model_type llama --wbits 4 --groupsize 128 --loader exllama_hf --xformers --no-stream

### Logs

```shell
Traceback (most recent call last):
  File "/content/text-generation-webui/modules/callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "/content/text-generation-webui/modules/text_generation.py", line 297, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 2642, in sample
    outputs = self(
  File "/content/text-generation-webui/modules/exllama_hf.py", line 63, in __call__
    logits = self.ex_model.forward(torch.tensor([seq[-1:]], dtype=torch.long), cache, lora=self.lora).to(kwargs['input_ids'].device)
  File "/usr/local/lib/python3.10/dist-packages/exllama/model.py", line 887, in forward
    r = self._forward(input_ids[:, chunk_begin : chunk_end],
  File "/usr/local/lib/python3.10/dist-packages/exllama/model.py", line 968, in _forward
    hidden_states = decoder_layer.forward(hidden_states, cache, buffers[device], lora)
  File "/usr/local/lib/python3.10/dist-packages/exllama/model.py", line 465, in forward
    self.self_attn.fused(hidden_states, cache, buffer, self.input_layernorm, lora)
  File "/usr/local/lib/python3.10/dist-packages/exllama/model.py", line 349, in fused
    key_states = cache.key_states[self.index].narrow(2, 0, past_len + q_len)
RuntimeError: start (0) + length (2049) exceeds dimension size (2048).
Exception in thread Thread-8 (gentask):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/content/text-generation-webui/modules/callbacks.py", line 62, in gentask
    clear_torch_cache()
  File "/content/text-generation-webui/modules/callbacks.py", line 94, in clear_torch_cache
    torch.cuda.empty_cache()
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/memory.py", line 133, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### System Info

```shell
Colab
```

**Comment by oobabooga** [comment]
The cache in exllama is preallocated. You need to set `max_seq_len` to 4096 in the UI before loading the model, or use the `--max_seq_len 4096` flag.

**Comment by chigkim** [comment]
That worked! Thanks!

**Comment by Charan587** [comment]
> The cache in exllama is preallocated. You need to set `max_seq_len` to 4096 in the UI before loading the model, or use the `--max_seq_len 4096` flag.

Is there any way i can increase further??

**Comment by Vincent-Stragier** [comment]
Hi @Charan587,

Yes, you can double it to 8192 tokens, but be aware the attention mechanism of the LLM will be affected (see the abstract of [Lost in the Middle:  How Language Models Use Long Contexts](https://arxiv.org/pdf/2307.03172.pdf)).
