### ISSUE TITLE
Llama-2-70B-GPTQ model throwing shape '[1, 5, 64, 128]' is invalid for input of size 5120 error 

### ISSUE THREAD

**Issue by RageshAntony** [oobabooga/text-generation-webui#3215]
### Describe the bug

I am using latest pull of text-generation-webui in runpod

I downloaded Llama-2-70B-GPTQ and used ExLLama 

When I click generate , nothing happened 

So I checked the logs, and found this stacktrace 

```
Traceback (most recent call last):
  File "/workspace/text-generation-webui/modules/text_generation.py", line 331, in generate_reply_custom
    for reply in shared.model.generate_with_streaming(question, state):
  File "/workspace/text-generation-webui/modules/exllama.py", line 98, in generate_with_streaming
    self.generator.gen_begin_reuse(ids)
  File "/usr/local/lib/python3.10/dist-packages/exllama/generator.py", line 186, in gen_begin_reuse
    self.gen_begin(in_tokens)
  File "/usr/local/lib/python3.10/dist-packages/exllama/generator.py", line 171, in gen_begin
    self.model.forward(self.sequence[:, :-1], self.cache, preprocess_only = True, lora = self.lora)
  File "/usr/local/lib/python3.10/dist-packages/exllama/model.py", line 849, in forward
    r = self._forward(input_ids[:, chunk_begin : chunk_end],
  File "/usr/local/lib/python3.10/dist-packages/exllama/model.py", line 930, in _forward
    hidden_states = decoder_layer.forward(hidden_states, cache, buffers[device], lora)
  File "/usr/local/lib/python3.10/dist-packages/exllama/model.py", line 470, in forward
    hidden_states = self.self_attn.forward(hidden_states, cache, buffer, lora)
  File "/usr/local/lib/python3.10/dist-packages/exllama/model.py", line 388, in forward
    key_states = key_states.view(bsz, q_len, self.config.num_attention_heads, self.config.head_dim).transpose(1, 2)

RuntimeError: shape '[1, 5, 64, 128]' is invalid for input of size 5120
```

Why this error happening ? the readme files ExLlama and TheBloke mentions 70b inference problems are fixed but still I am getting error

I also tried Exllama_HF, AutoGPTQ . All them throwing error 

Also checked Panchovix/LLaMA-2-70B-GPTQ-transformers4.32.0.dev0

Nothing works

Please help me 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Start runpod instance with A6000 and use 'thebloke/cuda11.8.0-ubuntu22.04-oneclick:latest' template

Download 'TheBloke/Llama-2-70B-GPTQ' and select ExLlama and load model

Click Generate with some question

### Logs

```shell
Traceback (most recent call last):
  File "/workspace/text-generation-webui/modules/text_generation.py", line 331, in generate_reply_custom
    for reply in shared.model.generate_with_streaming(question, state):
  File "/workspace/text-generation-webui/modules/exllama.py", line 98, in generate_with_streaming
    self.generator.gen_begin_reuse(ids)
  File "/usr/local/lib/python3.10/dist-packages/exllama/generator.py", line 186, in gen_begin_reuse
    self.gen_begin(in_tokens)
  File "/usr/local/lib/python3.10/dist-packages/exllama/generator.py", line 171, in gen_begin
    self.model.forward(self.sequence[:, :-1], self.cache, preprocess_only = True, lora = self.lora)
  File "/usr/local/lib/python3.10/dist-packages/exllama/model.py", line 849, in forward
    r = self._forward(input_ids[:, chunk_begin : chunk_end],
  File "/usr/local/lib/python3.10/dist-packages/exllama/model.py", line 930, in _forward
    hidden_states = decoder_layer.forward(hidden_states, cache, buffers[device], lora)
  File "/usr/local/lib/python3.10/dist-packages/exllama/model.py", line 470, in forward
    hidden_states = self.self_attn.forward(hidden_states, cache, buffer, lora)
  File "/usr/local/lib/python3.10/dist-packages/exllama/model.py", line 388, in forward
    key_states = key_states.view(bsz, q_len, self.config.num_attention_heads, self.config.head_dim).transpose(1, 2)
RuntimeError: shape '[1, 5, 64, 128]' is invalid for input of size 5120
```

### System Info

```shell
RTX A6000 
16 vCPU 58 GB RAM
Runpod thebloke/cuda11.8.0-ubuntu22.04-oneclick:latest template
```

**Comment by RageshAntony** [comment]
Working if I create a empty pod and cloned manually

But not working when using the runpod template : thebloke/cuda11.8.0-ubuntu22.04-oneclick
:latest

Maybe some issue in the Docker

**Comment by iibw** [comment]
Make sure you have the latest version of transformers and Exllama

**Comment by TikkunCreation** [comment]
@RageshAntony try this fix: https://gpus.llm-utils.org/running-llama-2-on-runpod-with-oobaboogas-text-generation-webui/

**Comment by RageshAntony** [comment]
@TikkunCreation 

Thanks. But not working for me directly . If I restart the pod, changes reverting !

The Readme of Docker states the last update as 28 June 2023.

I think @oobabooga need to do update the docker to latest release

**Comment by TikkunCreation** [comment]
> @TikkunCreation
> 
> Thanks. But not working for me directly . If I restart the pod, changes reverting !
> 
> The Readme of Docker states the last update as 28 June 2023.
> 
> I think @oobabooga need to do update the docker to latest release

Yes, that is the expected behavior of my 'fix' sadly - it'll work while you keep the terminal open, and then when you close the terminal or restart the pod, you'll need to do the steps again.

The proper fix will be that @TheBloke will update this repo: https://github.com/TheBlokeAI/dockerLLM/tree/main

**Comment by TheBloke** [comment]
Yes sorry, I have done it I just haven't had time to test it yet.  The new container is `thebloke/cuda11.8.0-ubuntu22.04-oneclick:21072023`

If anyone could test that and let me know it works, I will push it to `:latest`.  Otherwise I will try and test it myself in a couple of hours

**Comment by RageshAntony** [comment]
@TheBloke 

I checked the image now

Showing same issue 

Traceback (most recent call last):
  File "/workspace/text-generation-webui/modules/text_generation.py", line 331, in generate_reply_custom
    for reply in shared.model.generate_with_streaming(question, state):
  File "/workspace/text-generation-webui/modules/exllama.py", line 98, in generate_with_streaming
    self.generator.gen_begin_reuse(ids)
  File "/usr/local/lib/python3.10/dist-packages/exllama/generator.py", line 186, in gen_begin_reuse
    self.gen_begin(in_tokens)
  File "/usr/local/lib/python3.10/dist-packages/exllama/generator.py", line 171, in gen_begin
    self.model.forward(self.sequence[:, :-1], self.cache, preprocess_only = True, lora = self.lora)
  File "/usr/local/lib/python3.10/dist-packages/exllama/model.py", line 849, in forward
    r = self._forward(input_ids[:, chunk_begin : chunk_end],
  File "/usr/local/lib/python3.10/dist-packages/exllama/model.py", line 930, in _forward
    hidden_states = decoder_layer.forward(hidden_states, cache, buffers[device], lora)
  File "/usr/local/lib/python3.10/dist-packages/exllama/model.py", line 470, in forward
    hidden_states = self.self_attn.forward(hidden_states, cache, buffer, lora)
  File "/usr/local/lib/python3.10/dist-packages/exllama/model.py", line 388, in forward
    key_states = key_states.view(bsz, q_len, self.config.num_attention_heads, self.config.head_dim).transpose(1, 2)
RuntimeError: shape '[1, 20, 64, 128]' is invalid for input of size 20480

<img width="968" alt="image" src="https://github.com/oobabooga/text-generation-webui/assets/36100215/18b39f11-449d-4540-8e38-73d2c95ae53c">

**Comment by RageshAntony** [comment]
@TheBloke  

I am new to these things. Please check yourself

**Comment by TheBloke** [comment]
OK yes my template was still broken.  I have now fixed it and tested it.

`thebloke/cuda11.8.0-ubuntu22.04-oneclick:latest` is now up-to-date, so the standard Runpod template URLs will work as normal with 70B.

I've updated the template so it uninstalls the exllama pip package, allowing exllama to build its own.  Therefore exllama should always be up-to-date with new updates in future, without requiring a docker rebuild.

I'll update my dockerLLM Github repo shortly.

**Comment by RageshAntony** [comment]
@TheBloke 

Thanks. Let me check

**Comment by TheBloke** [comment]
Yeah a few people have asked for Jupyter. I will take a look and add it if I can.

**Comment by RageshAntony** [comment]
@TheBloke 

Thanks

**Comment by TikkunCreation** [comment]
I'm confirming that the updated docker images work for Llama 2 GPTQ. Successful load and text generation with AutoGPTQ for 13B-base-gptq and ExLlama (didn't try ExLlama_HF) for 70B-base-gptq. I didn't try other loaders, only the 2 pairs listed.

https://github.com/TheBlokeAI/dockerLLM/tree/main

Note that the template on runpod shows the old readme prior to the July 23 update, but the version still seems to be the new one.

**Comment by TikkunCreation** [comment]
Actually - I'm able to get one text generation to complete, and then the model seems to run into an error and then I can no longer load either model. 

Traceback (most recent call last): File “/workspace/text-generation-webui/server.py”, line 66, in load_model_wrapper unload_model() File “/workspace/text-generation-webui/modules/models.py”, line 338, in unload_model clear_torch_cache() File “/workspace/text-generation-webui/modules/models.py”, line 331, in clear_torch_cache torch.cuda.empty_cache() File “/usr/local/lib/python3.10/dist-packages/torch/cuda/memory.py”, line 133, in empty_cache torch._C._cuda_emptyCache() RuntimeError: CUDA error: an illegal memory access was encountered CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.

Getting this on 1x A100, including on older models, with both ExLlama and AutoGPTQ. It'll work for a first text generation, then give errors on future generations or model loads. Model unloading succeeds but loading doesn't.

Anyone else seen this issue with @TheBloke dockerLLM and text-generation-webui?

**Comment by RageshAntony** [comment]
@TikkunCreation 

yes. This error sometime occurs for me also. I will restart the pod and use again. So, I think this needs to be fixed
