### ISSUE TITLE
Unable to load LLaMATokenizer configs in loading 4bit 

### ISSUE THREAD

**Issue by chy-chiu** [oobabooga/text-generation-webui#322]
### Describe the bug

When running `(textgen) PS C:\Users\{user}\repos\text-generation-webui> python server.py  --gptq-bits 4 --gptq-model-type LLaMa --model llama30b`, I run into an error where model.py does not recognise the tokenizer files in the model folder. This is not an issue when I loaded llama13b 8-bit.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I downloaded the llama30b model from [here](https://mega.nz/file/KpsVkJQa#op4lhX9hiRl5FHSyQeq-wg1LpvNzBv5gm4MkelWEJJk) and the rest of the config files from `[here](https://huggingface.co/decapoda-research/llama-30b-hf/tree/main)`. Then I just loaded the script. I am using the correct version of transformer and most up to date PR 

### Screenshot

![image](https://user-images.githubusercontent.com/32184626/225035429-232bf071-9b4c-4f02-b0ba-4731eff5bc84.png)

### Logs

```shell
`(textgen) PS C:\Users\{user}\repos\text-generation-webui> python server.py  --gptq-bits 4 --gptq-model-type LLaMa --model llama30b

Loading llama30b...

Loading model ...

Done.

Traceback (most recent call last):
  File "C:\Users\{user}\repos\text-generation-webui\server.py", line 191, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\{user}\repos\text-generation-webui\modules\models.py", line 136, in load_model
    tokenizer = AutoTokenizer.from_pretrained(Path(f"models/{shared.model_name}/"))
  File "C:\Users\{user}\Anaconda3\envs\textgen\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 676, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.`
```

### System Info

```shell
Windows 11
4090 GPU 
128GB RAM
```

**Comment by oobabooga** [comment]
It seems like you are not using the right transformers version. Try this:

```
pip uninstall transformers
pip install git+https://github.com/zphang/transformers.git@68d640f7c368bcaaaecfc678f11908ebbd3d6176
```

**Comment by dnhkng** [comment]
I hit the same issue, and helped a few people with this issue. 

It coming from the people following the old instructions on [LLaMA-model](https://github.com/oobabooga/text-generation-webui/wiki/LLaMA-model) at Step 1.

**Comment by oobabooga** [comment]
Well noted, I have updated the guide.

**Comment by chy-chiu** [comment]
Thanks a lot for the help. However, with the newest version of transformer `transformers-4.27.0.dev0` I am still encountering the same problem

**Comment by chy-chiu** [comment]
To clarify, I am using the converted 4-bit 30b model from here:
https://huggingface.co/maderix/llama-65b-4bit/blob/main/llama30b-4bit.pt

And I am using the tokenizer.model and tokenizer_config from https://huggingface.co/decapoda-research/llama-30b-hf

**Comment by chy-chiu** [comment]
Upon further investigation, it appears that the version of transformer is not loading llama submodule. 

Relevant section of code:

`def tokenizer_class_from_name(class_name: str):
    if class_name == "PreTrainedTokenizerFast":
        return PreTrainedTokenizerFast

    for module_name, tokenizers in TOKENIZER_MAPPING_NAMES.items():
        if class_name in tokenizers:
            module_name = model_type_to_module_name(module_name)

            module = importlib.import_module(f".{module_name}", "transformers.models")
            try:
                return getattr(module, class_name)
            except AttributeError:
                continue`
                
where module_name = llama

**Comment by kagevazquez** [comment]
Move your .pt from models/llama30b to
/models. Just take it out of the folder

**Comment by sudoyang** [comment]
I've got the same issue but I use the method in this link 

https://github.com/oobabooga/text-generation-webui/wiki/LLaMA-model#convert_llama_weights_to_hfpy 

After the convert in step 2, I never got any .pt file in my case.

**Comment by kagevazquez** [comment]
> I've got the same issue but I use the method in this link 
> 
> 
> 
> https://github.com/oobabooga/text-generation-webui/wiki/LLaMA-model#convert_llama_weights_to_hfpy 
> 
> 
> 
> After the convert in step 2, I never got any .pt file in my case.

https://huggingface.co/maderix/llama-65b-4bit/tree/main

Save yourself some time by getting it here

**Comment by LexiconCode** [comment]
No matter which method I use there seems to be an issue with the transformers.
```
pip uninstall transformers
pip install git+https://github.com/zphang/transformers.git@68d640f7c368bcaaaecfc678f11908ebbd3d6176
```
```
Found existing installation: transformers 4.28.0.dev0
Uninstalling transformers-4.28.0.dev0:
  Would remove:
    f:\ai\oobabooga\installer_files\env\lib\site-packages\transformers-4.28.0.dev0.dist-info\*
    f:\ai\oobabooga\installer_files\env\lib\site-packages\transformers\*
    f:\ai\oobabooga\installer_files\env\scripts\transformers-cli.exe
Proceed (Y/n)? y
  Successfully uninstalled transformers-4.28.0.dev0
Collecting git+https://github.com/zphang/transformers.git@68d640f7c368bcaaaecfc678f11908ebbd3d6176
  Cloning https://github.com/zphang/transformers.git (to revision 68d640f7c368bcaaaecfc678f11908ebbd3d6176) to c:\users\main\appdata\local\temp\pip-req-build-5jepls9m
  Running command git clone --filter=blob:none --quiet https://github.com/zphang/transformers.git 'C:\Users\Main\AppData\Local\Temp\pip-req-build-5jepls9m'
  Running command git rev-parse -q --verify 'sha^68d640f7c368bcaaaecfc678f11908ebbd3d6176'
  Running command git fetch -q https://github.com/zphang/transformers.git 68d640f7c368bcaaaecfc678f11908ebbd3d6176
  Running command git checkout -q 68d640f7c368bcaaaecfc678f11908ebbd3d6176
  Resolved https://github.com/zphang/transformers.git to commit 68d640f7c368bcaaaecfc678f11908ebbd3d6176
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: filelock in c:\users\main\appdata\roaming\python\python310\site-packages (from transformers==4.27.0.dev0) (3.9.0)
Requirement already satisfied: requests in f:\ai\oobabooga\installer_files\env\lib\site-packages (from transformers==4.27.0.dev0) (2.28.2)
Requirement already satisfied: packaging>=20.0 in f:\ai\oobabooga\installer_files\env\lib\site-packages (from transformers==4.27.0.dev0) (23.0)
Requirement already satisfied: pyyaml>=5.1 in f:\ai\oobabooga\installer_files\env\lib\site-packages (from transformers==4.27.0.dev0) (6.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in f:\ai\oobabooga\installer_files\env\lib\site-packages (from transformers==4.27.0.dev0) (0.13.2)
Requirement already satisfied: tqdm>=4.27 in f:\ai\oobabooga\installer_files\env\lib\site-packages (from transformers==4.27.0.dev0) (4.65.0)
Requirement already satisfied: numpy>=1.17 in f:\ai\oobabooga\installer_files\env\lib\site-packages (from transformers==4.27.0.dev0) (1.24.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.11.0 in f:\ai\oobabooga\installer_files\env\lib\site-packages (from transformers==4.27.0.dev0) (0.13.2)
Requirement already satisfied: regex!=2019.12.17 in f:\ai\oobabooga\installer_files\env\lib\site-packages (from transformers==4.27.0.dev0) (2022.10.31)
Requirement already satisfied: typing-extensions>=3.7.4.3 in f:\ai\oobabooga\installer_files\env\lib\site-packages (from huggingface-hub<1.0,>=0.11.0->transformers==4.27.0.dev0) (4.5.0)
Requirement already satisfied: colorama in f:\ai\oobabooga\installer_files\env\lib\site-packages (from tqdm>=4.27->transformers==4.27.0.dev0) (0.4.6)
Requirement already satisfied: idna<4,>=2.5 in f:\ai\oobabooga\installer_files\env\lib\site-packages (from requests->transformers==4.27.0.dev0) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in f:\ai\oobabooga\installer_files\env\lib\site-packages (from requests->transformers==4.27.0.dev0) (2022.12.7)
Requirement already satisfied: charset-normalizer<4,>=2 in f:\ai\oobabooga\installer_files\env\lib\site-packages (from requests->transformers==4.27.0.dev0) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in f:\ai\oobabooga\installer_files\env\lib\site-packages (from requests->transformers==4.27.0.dev0) (1.26.15)
Building wheels for collected packages: transformers
  Building wheel for transformers (pyproject.toml) ... done
  Created wheel for transformers: filename=transformers-4.27.0.dev0-py3-none-any.whl size=6688243 sha256=3f466c3bf41f11bd36d57b5bdc15878055b3b8dafaaf4c0494cc12007049348c
  Stored in directory: c:\users\main\appdata\local\pip\cache\wheels\ff\b3\ff\ea09da57e5bda47ec3934a3dadb7c1219e5034092c91db5a08
Successfully built transformers
Installing collected packages: transformers
Successfully installed transformers-4.27.0.dev0
Press any key to continue . . .
```
```
Starting the web UI...
Loading llama-7b-hf...
Traceback (most recent call last):
  File "F:\AI\oobabooga\text-generation-webui\server.py", line 215, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "F:\AI\oobabooga\text-generation-webui\modules\models.py", line 93, in load_model
    model = load_quantized(model_name)
  File "F:\AI\oobabooga\text-generation-webui\modules\GPTQ_loader.py", line 55, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.gptq_bits)
  File "F:\AI\oobabooga\text-generation-webui\repositories\GPTQ-for-LLaMa\llama.py", line 220, in load_quant
    from transformers import LlamaConfig, LlamaForCausalLM
ImportError: cannot import name 'LlamaConfig' from 'transformers' (F:\AI\oobabooga\installer_files\env\lib\site-packages\transformers\__init__.py)
Press any key to continue . . .
```

pip uninstall transformers
pip install git+https://github.com/huggingface/transformers

```
Found existing installation: transformers 4.27.0.dev0
Uninstalling transformers-4.27.0.dev0:
  Would remove:
    f:\ai\oobabooga\installer_files\env\lib\site-packages\transformers-4.27.0.dev0.dist-info\*
    f:\ai\oobabooga\installer_files\env\lib\site-packages\transformers\*
    f:\ai\oobabooga\installer_files\env\scripts\transformers-cli.exe
Proceed (Y/n)? y
  Successfully uninstalled transformers-4.27.0.dev0
Collecting git+https://github.com/huggingface/transformers
  Cloning https://github.com/huggingface/transformers to c:\users\main\appdata\local\temp\pip-req-build-rji27xh2
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers 'C:\Users\Main\AppData\Local\Temp\pip-req-build-rji27xh2'
  Resolved https://github.com/huggingface/transformers to commit fb366b9a2a94b38171896f6ba9fb9ae8bffd77af
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: huggingface-hub<1.0,>=0.11.0 in f:\ai\oobabooga\installer_files\env\lib\site-packages (from transformers==4.28.0.dev0) (0.13.2)
Requirement already satisfied: pyyaml>=5.1 in f:\ai\oobabooga\installer_files\env\lib\site-packages (from transformers==4.28.0.dev0) (6.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in f:\ai\oobabooga\installer_files\env\lib\site-packages (from transformers==4.28.0.dev0) (0.13.2)
Requirement already satisfied: requests in f:\ai\oobabooga\installer_files\env\lib\site-packages (from transformers==4.28.0.dev0) (2.28.2)
Requirement already satisfied: packaging>=20.0 in f:\ai\oobabooga\installer_files\env\lib\site-packages (from transformers==4.28.0.dev0) (23.0)
Requirement already satisfied: regex!=2019.12.17 in f:\ai\oobabooga\installer_files\env\lib\site-packages (from transformers==4.28.0.dev0) (2022.10.31)
Requirement already satisfied: tqdm>=4.27 in f:\ai\oobabooga\installer_files\env\lib\site-packages (from transformers==4.28.0.dev0) (4.65.0)
Requirement already satisfied: numpy>=1.17 in f:\ai\oobabooga\installer_files\env\lib\site-packages (from transformers==4.28.0.dev0) (1.24.2)
Requirement already satisfied: filelock in c:\users\main\appdata\roaming\python\python310\site-packages (from transformers==4.28.0.dev0) (3.9.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in f:\ai\oobabooga\installer_files\env\lib\site-packages (from huggingface-hub<1.0,>=0.11.0->transformers==4.28.0.dev0) (4.5.0)
Requirement already satisfied: colorama in f:\ai\oobabooga\installer_files\env\lib\site-packages (from tqdm>=4.27->transformers==4.28.0.dev0) (0.4.6)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in f:\ai\oobabooga\installer_files\env\lib\site-packages (from requests->transformers==4.28.0.dev0) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in f:\ai\oobabooga\installer_files\env\lib\site-packages (from requests->transformers==4.28.0.dev0) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in f:\ai\oobabooga\installer_files\env\lib\site-packages (from requests->transformers==4.28.0.dev0) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in f:\ai\oobabooga\installer_files\env\lib\site-packages (from requests->transformers==4.28.0.dev0) (2.1.1)
Building wheels for collected packages: transformers
  Building wheel for transformers (pyproject.toml) ... done
  Created wheel for transformers: filename=transformers-4.28.0.dev0-py3-none-any.whl size=6756510 sha256=78a402912430c9b4094f6ce5b1dd7c506eae8b818622040c8c1530296dd0d09a
  Stored in directory: C:\Users\Main\AppData\Local\Temp\pip-ephem-wheel-cache-9h13vn0b\wheels\c0\14\d6\6c9a5582d2ac191ec0a483be151a4495fe1eb2a6706ca49f1b
Successfully built transformers
Installing collected packages: transformers
Successfully installed transformers-4.28.0.dev0
```
```
Starting the web UI...
Loading llama-7b-hf...
Loading model ...
Done.
Traceback (most recent call last):
  File "F:\AI\oobabooga\text-generation-webui\server.py", line 215, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "F:\AI\oobabooga\text-generation-webui\modules\models.py", line 135, in load_model
    tokenizer = AutoTokenizer.from_pretrained(Path(f"models/{shared.model_name}/"))
  File "F:\AI\oobabooga\installer_files\env\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 677, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.
Press any key to continue . . .
```

**Comment by LexiconCode** [comment]
Changing `LLaMATokenizer`  to `LlamaTokenizer` works  `tokenizer_config.json`
Thank you
