### ISSUE TITLE
Reinstalled using one_click_installers and now LLama 2 doesn't work

### ISSUE THREAD

**Issue by FartyPants** [oobabooga/text-generation-webui#3227]
### Describe the bug

During generation throws error.
Worked before I updated.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

other works, a;; llama 2 throws error

### Logs

```shell
Traceback (most recent call last):
  File "H:\oobabooga_windows\text-generation-webui\modules\callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "H:\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 297, in generate_with_callback
    shared.model.generate(**kwargs)
  File "H:\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "H:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1588, in generate
    return self.sample(
  File "H:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 2642, in sample
    outputs = self(
  File "H:\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl    return forward_call(*args, **kwargs)
  File "H:\oobabooga_windows\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "H:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 806, in forward
    outputs = self.model(
  File "H:\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl    return forward_call(*args, **kwargs)
  File "H:\oobabooga_windows\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "H:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 693, in forward
    layer_outputs = decoder_layer(
  File "H:\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl    return forward_call(*args, **kwargs)
  File "H:\oobabooga_windows\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "H:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 408, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "H:\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl    return forward_call(*args, **kwargs)
  File "H:\oobabooga_windows\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "H:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 295, in forward
    query_states = [F.linear(hidden_states, query_slices[i]) for i in range(self.pretraining_tp)]
  File "H:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 295, in <listcomp>
    query_states = [F.linear(hidden_states, query_slices[i]) for i in range(self.pretraining_tp)]
RuntimeError: mat1 and mat2 shapes cannot be multiplied (66x5120 and 1x2560)
Output generated in 0.37 seconds (0.00 tokens/s, 0 tokens, context 66, seed 1317782351)
```

### System Info

```shell
Windows
transformers-4.31.0
```

**Comment by FartyPants** [comment]
Ok, I put transformers to 4.30.2 and llama-cpp-python to 0.1.70 and all works now.
