### ISSUE TITLE
No matter how small of a model I try to load, this error always shows.

### ISSUE THREAD

**Issue by Desusaur** [oobabooga/text-generation-webui#3229]
### Describe the bug

Just as the title says. No matter what model I use, or how big or small it is, my Oobabooga will always come back with the same error as the screenshot. I have very little (if any) knowledge for coding, so, truthfully, I have no idea what it means or how to fix the issue.

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

I've used the one click installer. I can boot up the start_windows.bat file fine, Oobabooga loads up fine, I can download models, but cannot run models.

### Screenshot

![Screenshot 2023-07-20 215641](https://github.com/oobabooga/text-generation-webui/assets/68882096/36969907-db67-409f-87f3-30303fbd9f04)

### Logs

```shell
2023-07-20 21:55:57 ERROR:No model is loaded! Select one in the Model tab.
2023-07-20 21:56:06 INFO:Loading PygmalionAI_pygmalion-7b...
2023-07-20 21:56:06 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "D:\Users\shamr\OneDrive\Documents\AI_Chatbot\oobabooga_windows\text-generation-webui\server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "D:\Users\shamr\OneDrive\Documents\AI_Chatbot\oobabooga_windows\text-generation-webui\modules\models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "D:\Users\shamr\OneDrive\Documents\AI_Chatbot\oobabooga_windows\text-generation-webui\modules\models.py", line 320, in ExLlama_loader
    model, tokenizer = ExllamaModel.from_pretrained(model_name)
  File "D:\Users\shamr\OneDrive\Documents\AI_Chatbot\oobabooga_windows\text-generation-webui\modules\exllama.py", line 49, in from_pretrained
    config = ExLlamaConfig(str(model_config_path))
  File "D:\Users\shamr\OneDrive\Documents\AI_Chatbot\oobabooga_windows\installer_files\env\lib\site-packages\exllama\model.py", line 40, in __init__
    with open(model_config_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models\\PygmalionAI_pygmalion-7b\\config.json'
```

### System Info

```shell
Windows 11
NVIDIA 
GeForce RTX 3060 Ti
32 GB Ram
8GB VRAM
```

**Comment by missionfloyd** [comment]
[`PygmalionAI/pygmalion-7b`](https://huggingface.co/PygmalionAI/pygmalion-7b) can't be used as-is. Try this instead.
https://huggingface.co/TheBloke/Pygmalion-7B-SuperHOT-8K-GPTQ

**Comment by Desusaur** [comment]
> [`PygmalionAI/pygmalion-7b`](https://huggingface.co/PygmalionAI/pygmalion-7b) can't be used as-is. 

Oh, I had no idea. Is there a special way to run Pygmalion then?
I'm guessing that's above anything I would know how to do, if that's the case.

Either way, thank you! I'm gonna try the model you suggested, and have my fingers crossed, haha! :)

**Comment by missionfloyd** [comment]
> Is there a special way to run Pygmalion then?

Pygmalion [7B](https://huggingface.co/PygmalionAI/pygmalion-7b)/[13B](https://huggingface.co/PygmalionAI/pygmalion-13b) is distributed as a patch that has to be applied to the original llama model from facebook. The one I posted above has that already done, and then quantized so it needs less VRAM.

**Comment by Flanua** [comment]
Make sure your model located in the models folder with the same folder name as your model.
Example: I have a folder in the models folder named Wizard-Vicuna-30B-Uncensored.ggmlv3.q8_0 and inside that folder I have my GGML model: Wizard-Vicuna-30B-Uncensored.ggmlv3.q8_0.bin
