### ISSUE TITLE
New commits make model fail to load

### ISSUE THREAD

**Issue by official-elinas** [oobabooga/text-generation-webui#323]
### Describe the bug

I pulled the latest changes and I am unable to load models I previously could. I know the path is correct and it has worked in the past.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Pull the latest commit and run the following command `python server.py --listen --model llama-13b --auto-devices --gpu-memory 21 13`

### Logs

```shell
$ python server.py --listen --model llama-13b --auto-devices --gpu-memory 21 13
Loading llama-13b...
Traceback (most recent call last):
  File "G:\llm-webui\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 628, in _get_config_dict
    resolved_config_file = cached_file(
  File "G:\llm-webui\installer_files\env\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "G:\llm-webui\installer_files\env\lib\site-packages\huggingface_hub\utils\_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "G:\llm-webui\installer_files\env\lib\site-packages\huggingface_hub\utils\_validators.py", line 166, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'models\llama-13b'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\llm-webui\text-generation-webui\server.py", line 191, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "G:\llm-webui\text-generation-webui\modules\models.py", line 130, in load_model
    model = eval(command)
  File "<string>", line 1, in <module>
  File "G:\llm-webui\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 441, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "G:\llm-webui\installer_files\env\lib\site-packages\transformers\models\auto\configuration_auto.py", line 890, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "G:\llm-webui\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 573, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "G:\llm-webui\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 649, in _get_config_dict
    raise EnvironmentError(
OSError: Can't load the configuration of 'models\llama-13b'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'models\llama-13b' is the correct path to a directory containing a config.json file
```

### System Info
```
Win 10
RTX 3090
A4000
64 GB RAM
```

**Comment by official-elinas** [comment]
Never mind, issue on my end.
