### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'int' and 'str'

### ISSUE THREAD

**Issue by ZhenyaPav** [oobabooga/text-generation-webui#3236]
### Describe the bug

When trying to generate text in the gradio webui, I get an error, and no text is generated.
I have managed to replicate the bug on several models using ExLlama and GPTQ-for-Llama.
The issue seems to only affect the web ui, as SillyTavern still works.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Launch text-generation-webui
2. Load any model
3. Try to generate text

### Logs

```shell
Traceback (most recent call last):
  File "/root/text-generation-webui/modules/text_generation.py", line 328, in generate_reply_custom
    reply = shared.model.generate(question, state)
  File "/root/text-generation-webui/modules/exllama.py", line 116, in generate
    for output in self.generate_with_streaming(prompt, state):
  File "/root/text-generation-webui/modules/exllama.py", line 96, in generate_with_streaming
    ids = ids[:, -get_max_prompt_length(state):]
  File "/root/text-generation-webui/modules/text_generation.py", line 35, in get_max_prompt_length
    return state['truncation_length'] - state['max_new_tokens']
TypeError: unsupported operand type(s) for -: 'int' and 'str'
```
```


### System Info

```shell
OS: Arch Linux, using Docker image
GPU: 7900XT
```

**Comment by ZhenyaPav** [comment]
That's weird, after a restart the issue went away.
