### ISSUE TITLE
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by dnhkng** [oobabooga/text-generation-webui#324]
### Describe the bug

Clean install following the instructions from the tutorial.

I can run 7B and 13b Int4 weight nicely, but from the same torrent the 30B and 65B weight always generate an error, either instantly or after the generation of a garbled output:
`RuntimeError: probability tensor contains either `inf`, `nan` or element < 0`

This was after the generation of this garbled output:
```
Common sense questions and answers

Question: 
Factual answer:gment ValueInternal部 aquestpandas devilպael대編ino
```

I have tried using the tokenizer files etc from HF from Decapoda, and the HFv2 torrent files (not the weights though, just the setting files..this works fine for 7B, 13B).

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

`python server.py --gptq-bits 4 --listen --model llama-65b-hf  --gpu-memory 20 20`
Note. is this correct?

### Logs

```shell
To create a public link, set `share=True` in `launch()`.
Exception in thread Thread-3 (gentask):
Traceback (most recent call last):
  File "/home/x/miniconda3/envs/textgen/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/x/miniconda3/envs/textgen/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x/Projects/text-generation-webui/modules/callbacks.py", line 64, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/home/x/Projects/text-generation-webui/modules/text_generation.py", line 191, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/x/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/x/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1452, in generate
    return self.sample(
  File "/home/x/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2504, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

### System Info

```shell
I'm on Ubuntu 22.04.2


Hardware:
5900x, 2x 4090, 64Gb ram.
```

**Comment by Spencer-Dawson** [comment]
I see this error using pygmalion-6b in 8 bit mode with amd hw. Obviously that's a totally different environment, but I have a hunch that the root cause is some kind of casting floor or ceiling issue with (in my case) bitsandbytes-rocm or (in your case) gptq. Hopefully someone with a better understanding of these libs and tf can provide a solution or workaround.

**Comment by Ph0rk0z** [comment]
Hey so as much as I agree with there being casting errors in bits and bytes.. to me this looks like something is wrong with your weights. I have successfully self converted the leaked models twice now to match the HF transformers updates. I then downloaded the 30b from https://huggingface.co/maderix/llama-65b-4bit/tree/main and the 7/13 from decapoda. My 30b does not exhibit this issue on a 1700x and quadro P6000.

**Comment by dnhkng** [comment]
@Ph0rk0z Did you see this error from the maderix and decapoda weights? It's not clear from your comment if those weights were good or bad.

**Comment by Ph0rk0z** [comment]
I see this error on 8bit all the time in bitsandbytes and it's surely a casting error here too. On maderix it works fine for me on a single GPU. I only used the decapoda weights he put in their own repos and not the ones he uploaded together. Supposedly those were not converted right and I didn't want to spend the bandwidth to download them.

Maderix are working fine, at least the 30b.

**Comment by mcmonkey4eva** [comment]
Had the same error, redownloaded from decapoda, it's fine now. Note that decapoda pushed an update ~15 days ago so if you downloaded before then, you have outdated weights and need to redownload.
