### ISSUE TITLE
Finetune Llama-2 error on encode call

### ISSUE THREAD

**Issue by LAXnACE** [oobabooga/text-generation-webui#3249]
### Describe the bug

I'm trying to finetune llama2, but an error occurs when calling the encoder

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Try to finetune llama2 model loaded via llama.cpp

### Logs

```shell
Traceback (most recent call last):
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "C:\oobabooga_windows\text-generation-webui\modules\training.py", line 461, in do_train
    train_data = data['train'].map(generate_and_tokenize_prompt, new_fingerprint='%030x' % random.randrange(16**30))
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\datasets\arrow_dataset.py", line 580, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\datasets\arrow_dataset.py", line 545, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\datasets\arrow_dataset.py", line 3087, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\datasets\arrow_dataset.py", line 3441, in _map_single
    example = apply_function_on_filtered_inputs(example, i, offset=offset)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\datasets\arrow_dataset.py", line 3344, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "C:\oobabooga_windows\text-generation-webui\modules\training.py", line 457, in generate_and_tokenize_prompt
    return tokenize(prompt, add_eos_token)
  File "C:\oobabooga_windows\text-generation-webui\modules\training.py", line 341, in tokenize
    input_ids = encode(prompt, True)
  File "C:\oobabooga_windows\text-generation-webui\modules\training.py", line 329, in encode
    result = shared.tokenizer.encode(text, truncation=True, max_length=cutoff_len)
TypeError: LlamaCppModel.encode() got an unexpected keyword argument 'truncation'
```

### System Info

```shell
CPU: AMD R9 5900X
RAM: 32GB
GPU: 3070Ti
```

**Comment by Ph0rk0z** [comment]
llama.cpp can't make lora unless something has changed recently.

**Comment by LeoFitz87** [comment]
Having the same problem.

**Comment by arthurwolf** [comment]
Not the *exact* same error message, but a very similar one at nearly the same line.

**Comment by arthurwolf** [comment]
> llama.cpp can't make lora unless something has changed recently.

so what should I use ??

**Comment by steven4547466** [comment]
> > llama.cpp can't make lora unless something has changed recently.
> 
> so what should I use ??

Figure anything out?

**Comment by kallebysantos** [comment]
# I almost made it 😢!!!!

> >  llama.cpp can't make lora unless something has changed recently.
> 
> 
>  so what should I use ??

Try switch to `LlamacppHF`  model loader, also was necessary download `oobabooga/llama-tokenizer` (described here #3499)

## logs:
- From my console:
```
2023-09-21 11:05:45 WARNING:LoRA training has only currently been validated for LLaMA, OPT, GPT-J, and GPT-NeoX models. (Found model type: LlamacppHF)
2023-09-21 11:05:50 INFO:Loading JSON datasets...
Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 87.15 examples/s]
2023-09-21 11:05:51 INFO:Getting model ready...
2023-09-21 11:05:51 INFO:Preparing for training...
2023-09-21 11:05:51 INFO:Creating LoRA model...
```

- But in interface I got the following:
```
Traceback (most recent call last):

File “/home/kallebysantos/projects/machine-learning/oobabooga_linux/text-generation-webui/modules/training.py”, line 505, in do_train

lora_model = get_peft_model(shared.model, config)
File “/home/kallebysantos/projects/machine-learning/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/peft/mapping.py”, line 106, in get_peft_model

return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)
File “/home/kallebysantos/projects/machine-learning/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/peft/peft_model.py”, line 889, in init

super().__init__(model, peft_config, adapter_name)
File “/home/kallebysantos/projects/machine-learning/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/peft/peft_model.py”, line 111, in init

self.base_model = PEFT_TYPE_TO_MODEL_MAPPING[peft_config.peft_type](
File “/home/kallebysantos/projects/machine-learning/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/peft/tuners/lora.py”, line 274, in init

super().__init__(model, config, adapter_name)
File “/home/kallebysantos/projects/machine-learning/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/peft/tuners/tuners_utils.py”, line 88, in init

self.inject_adapter(self.model, adapter_name)
File “/home/kallebysantos/projects/machine-learning/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/peft/tuners/tuners_utils.py”, line 222, in inject_adapter

raise ValueError(
ValueError: Target modules [‘q_proj’, ‘v_proj’] not found in the base model. Please check the target modules and try again.
```

**Comment by jellohouse** [comment]
Any updates on this?

I'm trying to do the same also with [TheBloke/Llama-2-7b-Chat-GGUF](https://huggingface.co/TheBloke/Llama-2-7b-Chat-GGUF/blob/main/llama-2-7b-chat.Q5_K_M.gguf)

**Comment by BartAgterbosch** [comment]
On normal training I'm getting TypeError: LlamaCppModel.encode() got an expected keyword argument 'truncation', regardless of the loader, then I read that someone had success with using Training_PRO, unfortunately that also throws me an error, which is TypeError: LlamaCppModel.decode() got an unexpected keyword argument 'skip_special_tokens'.
If I switch to the llamacpp_HF loader and download the llama_tokenizer however (successfully) training will fail with the following error: AttributeError: 'NoneType' object has no attribute 'pad_token_id'

Anybody got any ideas?

**Comment by nephi-dev** [comment]
Same errors here, i don't think that it's possible to train a lora of a gguf model

**Comment by Ph0rk0z** [comment]
You can train a HF format (bnb int8, int4,etc) model or gptq. Or train with llama.cpp itself.

**Comment by HasaanIjaz** [comment]
Training LoRAs atm is only supported for Model Loader is:
1. Transformer
2. GPTQ-for-LLaMa
To find the most recent information on this, visit the following official wiki page of the text-generation-webui repo: https://github.com/oobabooga/text-generation-webui/wiki .
