### ISSUE TITLE
qweight and qzeros have incompatible shapes

### ISSUE THREAD

**Issue by extesy** [oobabooga/text-generation-webui#3255]
### Describe the bug

Using the model `TheBloke/FreeWilly2-GPTQ:gptq-3bit--1g-actorder_True` and loader `ExLlama_HF`, an attempt to load the model results in "qweight and qzeros have incompatible shapes" error.__

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Download model `TheBloke/FreeWilly2-GPTQ:gptq-3bit--1g-actorder_True`
2. Use loader ExLlama or ExLlama_HF.
3. Load the model.

### Logs

```shell
2023-07-22 15:07:37 INFO:Loading TheBloke_FreeWilly2-GPTQ_gptq-3bit--1g-actorder_True...
2023-07-22 15:07:51 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "C:\Users\olega\Documents\anaconda3\envs\textgen\text-generation-webui\server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "C:\Users\olega\Documents\anaconda3\envs\textgen\text-generation-webui\modules\models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "C:\Users\olega\Documents\anaconda3\envs\textgen\text-generation-webui\modules\models.py", line 320, in ExLlama_loader
    model, tokenizer = ExllamaModel.from_pretrained(model_name)
  File "C:\Users\olega\Documents\anaconda3\envs\textgen\text-generation-webui\modules\exllama.py", line 67, in from_pretrained
    model = ExLlama(config)
  File "C:\Users\olega\anaconda3\envs\textgen\lib\site-packages\exllama\model.py", line 847, in __init__
    layer = ExLlamaDecoderLayer(self.config, tensors, f"model.layers.{i}", i, sin, cos)
  File "C:\Users\olega\anaconda3\envs\textgen\lib\site-packages\exllama\model.py", line 482, in __init__
    self.self_attn = ExLlamaAttention(self.config, tensors, key + ".self_attn", sin, cos, self.index)
  File "C:\Users\olega\anaconda3\envs\textgen\lib\site-packages\exllama\model.py", line 297, in __init__
    self.q_proj = Ex4bitLinear(config, self.config.hidden_size, self.config.num_attention_heads * self.config.head_dim, False, tensors, key + ".q_proj")
  File "C:\Users\olega\anaconda3\envs\textgen\lib\site-packages\exllama\model.py", line 147, in __init__
    self.q4 = cuda_ext.ext_make_q4(self.qweight,
  File "C:\Users\olega\anaconda3\envs\textgen\lib\site-packages\exllama\cuda_ext.py", line 33, in ext_make_q4
    return make_q4(qweight,
RuntimeError: qweight and qzeros have incompatible shapes
```

### System Info

```shell
Microsoft Windows 11 Pro
128gb RAM
GeForce RTX 3080 10gb
```

**Comment by musicurgy** [comment]
Did you figure out what the problem was? I have the same issue.

**Comment by extesy** [comment]
No, but the reason I closed this bug is because I realized it's not a text-generation-webui's problem. The bug is in ExLlama so it should be opened there.

**Comment by cochese9000** [comment]
Exllama doesn't support 8bit GPTQ models

Source: The Bloke.
https://huggingface.co/TheBloke/Nethena-MLewd-Xwin-23B-GPTQ/discussions/1?not-for-all-audiences=true
