### ISSUE TITLE
Issue starting new instance in Arch

### ISSUE THREAD

**Issue by weirdbeardgame** [oobabooga/text-generation-webui#3259]
### Describe the bug

Trying to follow the ROCM instructions. Got everything installed and all dependencies met. I have split installed in pacman and in pip if that helps.

```
Traceback (most recent call last):
  File "/home/musungo/text-generation-webui/server.py", line 35, in <module>
    from modules import chat, loaders, presets, shared, training, ui, utils
  File "/home/musungo/text-generation-webui/modules/chat.py", line 17, in <module>
    from modules.text_generation import (
  File "/home/musungo/text-generation-webui/modules/text_generation.py", line 22, in <module>
    from modules.models import clear_torch_cache, local_rank
  File "/home/musungo/text-generation-webui/modules/models.py", line 10, in <module>
    from accelerate import infer_auto_device_map, init_empty_weights
  File "/home/musungo/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/home/musungo/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/home/musungo/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/home/musungo/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/utils/__init__.py", line 131, in <module>
    from .bnb import has_4bit_bnb_layers, load_and_quantize_model
  File "/home/musungo/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/utils/bnb.py", line 42, in <module>
    import bitsandbytes as bnb
  File "/home/musungo/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/musungo/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/musungo/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/musungo/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/musungo/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/musungo/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 13, in <module>
    setup.run_cuda_setup()
  File "/home/musungo/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 120, in run_cuda_setup
    binary_name, cudart_path, cc, cuda_version_string = evaluate_cuda_setup()
  File "/home/musungo/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 341, in evaluate_cuda_setup
    cuda_version_string = get_cuda_version()
  File "/home/musungo/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 311, in get_cuda_version
    major, minor = map(int, torch.version.cuda.split("."))
AttributeError: 'NoneType' object has no attribute 'split'

```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Just run the server.py command. I

### Logs

```shell
N/A
```

### System Info

```shell
AMD Ryzen 7 3700x
AMD ATI Radeon RX 6950 XT
Arch linux
```

**Comment by lufixSch** [comment]
I had the same issue on Aarch with an AMD GPU

In the docs it states, that for some NVIDIA you may need `bitsandbytes==0.38.1`.
I installed It (`pip install bitsandbytes==0.38.1`) and now it works for me even though I am on AMD.

**Comment by weirdbeardgame** [comment]
Wow! That seems to have been the magic fix here

**Comment by Milor123** [comment]
> 

 UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "

are you sure? It says that dont have GPU ?
