### ISSUE TITLE
I cannot see the text generated

### ISSUE THREAD

**Issue by Suppexion** [oobabooga/text-generation-webui#3263]
### Describe the bug

New user here, after getting everything in order, when I typed a prompt, for a split second I saw  the words 'typing...' as an indication that the ai was generating a response before a blank page with nothing on it. No words, i checked inspect already. Does anyone have a solution to this seemingly simple issue? More info below but i listed everything i could because i'm new and don't exactly know what happened

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I used CPU instead of GPU, and faced a few other issues before such as 'torch not compiled with cuda enabled' which I resolved by reinstalling torch, and turning off the 'auto devices' setting to prevent the error the Nvidia gpu wasn't found since I use AMD. Also, I was using anon8231489123_gpt4-x-alpaca-13b-native-4bit-128g.
My settings:
![Text generation web UI - Google Chrome 7_23_2023 10_05_38 PM](https://github.com/oobabooga/text-generation-webui/assets/93919386/e419c0b6-d5da-40dc-afc2-3f6e4d3089ac)
![Text generation web UI - Google Chrome 7_23_2023 10_05_44 PM](https://github.com/oobabooga/text-generation-webui/assets/93919386/46cba771-47fe-47ac-bc85-dd829580349c)
![New Issue · oobabooga_text-generation-webui - Google Chrome 7_23_2023 10_12_53 PM](https://github.com/oobabooga/text-generation-webui/assets/93919386/4ac6b7b2-be60-49d8-8b6b-bb42bfb3556a)
![New Issue · oobabooga_text-generation-webui - Google Chrome 7_23_2023 10_13_11 PM](https://github.com/oobabooga/text-generation-webui/assets/93919386/29926c6a-b7a0-4e04-8114-21db9669f915)
![Screenshot 2023-07-23 221337](https://github.com/oobabooga/text-generation-webui/assets/93919386/4a18c933-1656-4801-b3d5-8c26f2fa160f)

### Screenshot

![Text generation web UI - Google Chrome 7_23_2023 7_00_23 PM](https://github.com/oobabooga/text-generation-webui/assets/93919386/55a58290-2e2e-4f2e-aaa5-ac8b89ab3642)
![Text generation web UI - Google Chrome 7_23_2023 10_00_34 PM](https://github.com/oobabooga/text-generation-webui/assets/93919386/092d9531-cf0b-44b7-a605-7f479f222031)

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\user\Desktop\aitextgen\oobabooga_windows\text-generation-webui\modules\callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "C:\Users\user\Desktop\aitextgen\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 297, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Users\user\Desktop\aitextgen\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\modeling\_base.py", line 437, in generate
    with torch.inference_mode(), torch.amp.autocast(device_type=self.device.type):
  File "C:\Users\user\Desktop\aitextgen\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\modeling\_base.py", line 426, in device
    device = [d for d in self.hf_device_map.values() if d not in {'cpu', 'disk'}][0]
IndexError: list index out of range
Output generated in 0.40 seconds (0.00 tokens/s, 0 tokens, context 38, seed 2038868305)
Traceback (most recent call last):
  File "C:\Users\user\Desktop\aitextgen\oobabooga_windows\text-generation-webui\modules\callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "C:\Users\user\Desktop\aitextgen\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 297, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Users\user\Desktop\aitextgen\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\modeling\_base.py", line 437, in generate
    with torch.inference_mode(), torch.amp.autocast(device_type=self.device.type):
  File "C:\Users\user\Desktop\aitextgen\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\modeling\_base.py", line 426, in device
    device = [d for d in self.hf_device_map.values() if d not in {'cpu', 'disk'}][0]
IndexError: list index out of range
Output generated in 0.37 seconds (0.00 tokens/s, 0 tokens, context 67, seed 890229865)
Traceback (most recent call last):
  File "C:\Users\user\Desktop\aitextgen\oobabooga_windows\text-generation-webui\modules\callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "C:\Users\user\Desktop\aitextgen\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 297, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Users\user\Desktop\aitextgen\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\modeling\_base.py", line 437, in generate
    with torch.inference_mode(), torch.amp.autocast(device_type=self.device.type):
  File "C:\Users\user\Desktop\aitextgen\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\modeling\_base.py", line 426, in device
    device = [d for d in self.hf_device_map.values() if d not in {'cpu', 'disk'}][0]
IndexError: list index out of range
Output generated in 0.38 seconds (0.00 tokens/s, 0 tokens, context 71, seed 842588845)
```

### System Info

```shell
Windows 11 Home
Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz, 1801 Mhz, 4 Core(s), 8 Logical Processor(s)
19.9 GB Total RAM
```

**Comment by DefKahn** [comment]
same here

**Comment by teamplayer3** [comment]
Same here. Any solution?

**Comment by qrtise** [comment]
same thing

**Comment by sam2332** [comment]
same issue, anyone had any luck?

**Comment by theosissomeday** [comment]
Same problem
