### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str' - trainer.py

### ISSUE THREAD

**Issue by blueberrysnapple** [oobabooga/text-generation-webui#3273]
### Describe the bug

I'm attempting to train a LoRA with a raw text file and when I do I get an error: TypeError: a bytes-like object is required. I tried playing with some of the code and the raw text file as the dataset but nothing I did or changed improved the situation. 

Thanks for you help. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

 I have loaded the model, llama-2-13b-chat.ggmlv3.q4_1.bin, filled in the needed info on the training page, and hit the "Start LoRA Training" button at the bottom and on m screen I get an error. More details are in the console log. 

### Logs

```shell
2023-07-23 23:26:14 INFO:Loading llama-2-13b-chat.ggmlv3.q4_1.bin...
2023-07-23 23:26:14 INFO:llama.cpp weights detected: models/llama-2-13b-chat.ggmlv3.q4_1.bin

2023-07-23 23:26:14 INFO:Cache capacity is 0 bytes
llama.cpp: loading model from models/llama-2-13b-chat.ggmlv3.q4_1.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 3 (mostly Q4_1)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.09 MB
llama_model_load_internal: mem required  = 9729.49 MB (+ 1608.00 MB per state)
llama_new_context_with_model: kv self size  = 1600.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 
2023-07-23 23:26:24 INFO:Loaded the model in 9.76 seconds.

2023-07-23 23:26:58 WARNING:LoRA training has only currently been validated for LLaMA, OPT, GPT-J, and GPT-NeoX models. (Found model type: LlamaCppModel)
2023-07-23 23:27:03 WARNING:It is highly recommended you use `--load-in-8bit` for LoRA training.
2023-07-23 23:27:05 INFO:Loading raw text file dataset...
Traceback (most recent call last):
  File "/home/user/ai/oobabooga/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/ai/oobabooga/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/user/ai/oobabooga/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/user/ai/oobabooga/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "/home/user/ai/oobabooga/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/user/ai/oobabooga/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/ai/oobabooga/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/user/ai/oobabooga/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/user/ai/oobabooga/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "/home/user/ai/oobabooga/oobabooga_linux/text-generation-webui/modules/training.py", line 422, in do_train
    text_chunks = [cut_chunk_for_newline(x, newline_favor_len) for x in text_chunks]
  File "/home/user/ai/oobabooga/oobabooga_linux/text-generation-webui/modules/training.py", line 422, in <listcomp>
    text_chunks = [cut_chunk_for_newline(x, newline_favor_len) for x in text_chunks]
  File "/home/user/ai/oobabooga/oobabooga_linux/text-generation-webui/modules/training.py", line 719, in cut_chunk_for_newline
    if '\n' not in chunk:
TypeError: a bytes-like object is required, not 'str'
```

### System Info

```shell
This here may be relevant:

 warn("The installed version of bitsandbytes was compiled without GPU support. "

I'm on a debian VM. I do not have GPU support on my current machine so I set very low values for thing like LoRa Rank, Overlap Length etc...

$ uname -a
Linux coding 6.1.35-1.qubes.fc32.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Jun 25 16:39:03 CEST 2023 x86_64 GNU/Linux
```

**Comment by blueberrysnapple** [comment]
Apologies it looks like someone else reported this 4 days ago here:

https://github.com/oobabooga/text-generation-webui/issues/3217
