### ISSUE TITLE
model cant load

### ISSUE THREAD

**Issue by kingyoolee** [oobabooga/text-generation-webui#3276]
### Describe the bug

Traceback (most recent call last): File “D:\oobabooga_windows\oobabooga_windows\text-generation-webui\[server.py](http://server.py/)”, line 68, in load_model_wrapper shared.model, shared.tokenizer = load_model(shared.model_name, loader) File “D:\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\[models.py](http://models.py/)”, line 79, in load_model output = load_func_map[loader](http://127.0.0.1:7860/model_name) File “D:\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\[models.py](http://models.py/)”, line 268, in llamacpp_loader model, tokenizer = LlamaCppModel.from_pretrained(model_file) File “D:\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py”, line 63, in from_pretrained result.model = Llama(**params) File “D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp_cuda\[llama.py](http://llama.py/)”, line 302, in init self.model = llama_cpp.llama_load_model_from_file( File “D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp_cuda\llama_cpp.py”, line 360, in llama_load_model_from_file return _lib.llama_load_model_from_file(path_model, params) OSError: [WinError -1073741795] Windows Error 0xc000001d

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

load model

### Screenshot

![屏幕截图 2023-07-24 135916](https://github.com/oobabooga/text-generation-webui/assets/140373588/698c7109-267c-4812-826a-563e07aa66b5)
![屏幕截图 2023-07-24 135938](https://github.com/oobabooga/text-generation-webui/assets/140373588/76ed9a3d-9a12-4012-95f8-4d26ecc9b059)

### Logs

```shell
2023-07-24 13:59:22 INFO:Loading open-llama-7B-open-instruct.ggmlv3.q4_0.bin...
2023-07-24 13:59:22 INFO:llama.cpp weights detected: models\open-llama-7B-open-instruct.ggmlv3.q4_0.bin

2023-07-24 13:59:22 INFO:Cache capacity is 0 bytes
llama.cpp: loading model from models\open-llama-7B-open-instruct.ggmlv3.q4_0.bin
2023-07-24 13:59:22 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "D:\oobabooga_windows\oobabooga_windows\text-generation-webui\server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "D:\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "D:\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\models.py", line 268, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
  File "D:\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 63, in from_pretrained
    result.model = Llama(**params)
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp_cuda\llama.py", line 302, in __init__
    self.model = llama_cpp.llama_load_model_from_file(
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp_cuda\llama_cpp.py", line 360, in llama_load_model_from_file
    return _lib.llama_load_model_from_file(path_model, params)
OSError: [WinError -1073741795] Windows Error 0xc000001d

Exception ignored in: <function Llama.__del__ at 0x000001CD1A661870>
Traceback (most recent call last):
  File "D:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp_cuda\llama.py", line 1499, in __del__
    if self.model is not None:
AttributeError: 'Llama' object has no attribute 'model'
Exception ignored in: <function LlamaCppModel.__del__ at 0x000001CD191C1C60>
Traceback (most recent call last):
  File "D:\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 34, in __del__
    self.model.__del__()
AttributeError: 'LlamaCppModel' object has no attribute 'model'
```

### System Info

```shell
win11 3060(12g) ram32
```

**Comment by Flanua** [comment]
Make sure your model located in the folder with the same name as your model.
Example: I have a folder named Wizard-Vicuna-30B-Uncensored.ggmlv3.q8_0 and inside that folder I have my GGML model: Wizard-Vicuna-30B-Uncensored.ggmlv3.q8_0.bin

**Comment by jllllll** [comment]
`Windows Error 0xc000001d` when loading a GGML model indicates that your CPU does not have AVX2 support.
I have also seen at least one instance of this error occurring with a CPU that does have AVX2, but does not use it for some reason.
Regardless, the solution is the same. This command will install a version without AVX2:
```
python -m pip install llama-cpp-python-cuda --force-reinstall --no-deps --index-url=https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/textgen/AVX/cu117
```
That command will install the latest available version that I have added to the package index. 0.1.77 is currently the latest version out, but it has not been added to the index yet due to rapid successive updates to llama-cpp-python causing delays.

This command will install the 0.1.77 version in the mean time:
```
python -m pip install https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/releases/download/textgen-webui/llama_cpp_python_cuda-0.1.77+cu117avx-cp310-cp310-win_amd64.whl --force-reinstall --no-deps

**Comment by yhyu13** [comment]
@jllllll 

Just appreciate your efforts in making llamacpp-python for different cuda version! https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/releases/tag/wheels

**Comment by kenwud** [comment]
> `Windows Error 0xc000001d` when loading a GGML model indicates that your CPU does not have AVX2 support. I have also seen at least one instance of this error occurring with a CPU that does have AVX2, but does not use it for some reason. Regardless, the solution is the same. This command will install the latest version without AVX2:
> 
> ```
> python -m pip install llama-cpp-python-cuda --force-reinstall --no-deps --index-url=https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/textgen/AVX/cu117
> ```

with a fresh install of the text-gen ui, i get the error 
attribute found no model, when i try to load a model,

`Traceback (most recent call last):

File "E:\text-generation-webui-snapshot-2023-10-15\modules\ui_model_menu.py", line 201, in load_model_wrapper

shared.model, shared.tokenizer = load_model(shared.model_name, loader)
File "E:\text-generation-webui-snapshot-2023-10-15\modules\models.py", line 79, in load_model

output = load_func_map[loader](model_name)
File "E:\text-generation-webui-snapshot-2023-10-15\modules\models.py", line 225, in llamacpp_loader

model, tokenizer = LlamaCppModel.from_pretrained(model_file)
File "E:\text-generation-webui-snapshot-2023-10-15\modules\llamacpp_model.py", line 91, in from_pretrained

result.model = Llama(**params)
File "E:\text-generation-webui-snapshot-2023-10-15\installer_files\env\lib\site-packages\llama_cpp_cuda\llama.py", line 357, in init

self.model = llama_cpp.llama_load_model_from_file(
File "E:\text-generation-webui-snapshot-2023-10-15\installer_files\env\lib\site-packages\llama_cpp_cuda\llama_cpp.py", line 498, in llama_load_model_from_file

return _lib.llama_load_model_from_file(path_model, params)
OSError: [WinError -1073741795] Windows Error 0xc000001d`

your comment seems to be the solution, i dont really understand what the problem is but i seem to assume that it means my cpu doesnt have avx2 support

**Comment by jllllll** [comment]
Technically, the error just means that your CPU doesn't support whatever instruction set is being used.
The webui uses wheels that utilize `AVX2 FMA FP16C` instruction sets.
Typically, getting that error indicates a lack of `AVX2` support since the other instruction sets are included in CPUs that have `AVX2`.

The latest one-click-installer, which is now part of the main webui repo, includes detection for a lack of `AVX2` and will install compatible packages as needed. If you also don't have `AVX` support, then you may need to use this command:
```
python -m pip install llama-cpp-python llama-cpp-python-cuda --force-reinstall --no-deps --index-url=https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/basic/cpu --extra-index-url=https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/textgen/basic/cu118
```
