### ISSUE TITLE
Using llama2, how to use two GPUs, in fact, it only uses one

### ISSUE THREAD

**Issue by mozeqiu123** [oobabooga/text-generation-webui#3278]
### Describe the bug

When I load llama2, I actually have two GPUs and the other one is not used，anyone can help?

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 448.00 MiB (GPU 0; 23.65 GiB total capacity; 19.91 GiB already allocated; 265.81 MiB free; 19.91 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

just -->python server.py --chat  
i load llama v2 

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/139750690/495260f0-5303-426b-882a-275e8d5c39b9)

### Logs

```shell
2023-07-24 16:30:54 INFO:Loading the extension "gallery"...
Running on local URL:  http://0.0.0.0:7865

To create a public link, set `share=True` in `launch()`.
2023-07-24 16:31:05 INFO:Loading llama-70B-bin...
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████| 81/81 [20:14<00:00, 14.99s/it]
2023-07-24 16:51:48 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/data/lilin/text-generation-webui-main/server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/data/lilin/text-generation-webui-main/modules/models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "/data/lilin/text-generation-webui-main/modules/models.py", line 154, in huggingface_loader
    model = model.cuda()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 448.00 MiB (GPU 0; 23.65 GiB total capacity; 19.91 GiB already allocated; 265.81 MiB free; 19.91 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

^CTraceback (most recent call last):
  File "/data/lilin/text-generation-webui-main/server.py", line 1175, in <module>
    time.sleep(0.5)
KeyboardInterrupt
```

### System Info

```shell
ubuntu
nvidia 4090 24g*2
```

**Comment by Ph0rk0z** [comment]
for 70b set 15.5, 24 in the exllama loader to split it.

**Comment by smith-co** [comment]
@Ph0rk0z can you please show an example?

**Comment by Ph0rk0z** [comment]
select the exllama or exllama_hf loader and put `15.5, 24` in the text box, the only one that's there.
