### ISSUE TITLE
CUDA error: unspecified launch failure

### ISSUE THREAD

**Issue by goodglitch** [oobabooga/text-generation-webui#3291]
### Describe the bug

After sometime of using text-generation-webui I get the following error: RuntimeError: CUDA error: unspecified launch failure. No other programs are using GPU.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

It is difficult to say how to reproduce the issue. I hope call stack will help to understand what may go wrong.

### Logs

```shell
127.0.0.1 - - [24/Jul/2023 23:05:48] "POST /v1/chat/completions HTTP/1.1" 200 -
Exception: When loading characters/instruction-following/None.yaml: FileNotFoundError(2, 'No such file or directory')
Warning: Loaded default instruction-following template for model.
Warning: $This model maximum context length is 2048 tokens. However, your messages resulted in over 2029 tokens and max_tokens is 1024.
Output generated in 6.27 seconds (16.58 tokens/s, 104 tokens, context 2029, seed 845657357)
127.0.0.1 - - [24/Jul/2023 23:05:55] "POST /v1/chat/completions HTTP/1.1" 200 -
Exception: When loading characters/instruction-following/None.yaml: FileNotFoundError(2, 'No such file or directory')
Warning: Loaded default instruction-following template for model.
Warning: $This model maximum context length is 2048 tokens. However, your messages resulted in over 1030 tokens and max_tokens is 1024.
Traceback (most recent call last):
  File "C:\AI\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 331, in generate_reply_custom
    for reply in shared.model.generate_with_streaming(question, state):
  File "C:\AI\oobabooga_windows\text-generation-webui\modules\exllama.py", line 102, in generate_with_streaming
    token = self.generator.gen_single_token()
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\exllama\generator.py", line 326, in gen_single_token
    logits = self.model.forward(self.sequence[:, -1:], self.cache, lora = self.lora)
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\exllama\model.py", line 924, in forward
    r = self._forward(input_ids[:, chunk_begin : chunk_end],
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\exllama\model.py", line 1003, in _forward
    hidden_states = _move_tensor(hidden_states, device, "hidden_states", self.config)
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\exllama\model.py", line 673, in _move_tensor
    return tensor.to(new_device)
RuntimeError: CUDA error: unspecified launch failure
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

When I tried to reload model:

```shell
2023-07-24 23:26:31 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "C:\AI\oobabooga_windows\text-generation-webui\server.py", line 66, in load_model_wrapper
    unload_model()
  File "C:\AI\oobabooga_windows\text-generation-webui\modules\models.py", line 365, in unload_model
    clear_torch_cache()
  File "C:\AI\oobabooga_windows\text-generation-webui\modules\models.py", line 358, in clear_torch_cache
    torch.cuda.empty_cache()
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\torch\cuda\memory.py", line 133, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: unspecified launch failure
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### System Info

```shell
Windows 10, CPU 5950x, RAM 98Gb, RTX 3090
```

**Comment by ekg** [comment]
I've had the same issue. I can't seem to reproduce it, but large memory allocations seem to proceed it.
