### ISSUE TITLE
Error running in windows with user not admin

### ISSUE THREAD

**Issue by alkampfergit** [oobabooga/text-generation-webui#3304]
### Describe the bug

In my system I'm using a non adminstrator user, my user is called alkam and I have another user called **root** that is the administrator (different user, different password)

I've configured conda environment and then tried to start server.py but I got this error.

As you can see the script is trying to access the profile directory of the root user, even if I'm logged with user alkam. Is this supposed to work only running with administrator user? Why is it trying to access another user profile directory?

```
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\root\\AppData\\Local\\Microsoft\\WindowsApps'

(textgen) R:\tools\oobabooga\manual\text-generation-webui>whoami
shismatrix\alkam

```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Use a Windows box with a non adminstrator user and then try to run the system.

### Logs

```shell
(textgen) R:\tools\oobabooga\manual\text-generation-webui>python server.py
Traceback (most recent call last):
  File "R:\tools\oobabooga\manual\text-generation-webui\server.py", line 35, in <module>
    from modules import chat, loaders, presets, shared, training, ui, utils
  File "R:\tools\oobabooga\manual\text-generation-webui\modules\chat.py", line 17, in <module>
    from modules.text_generation import (
  File "R:\tools\oobabooga\manual\text-generation-webui\modules\text_generation.py", line 22, in <module>
    from modules.models import clear_torch_cache, local_rank
  File "R:\tools\oobabooga\manual\text-generation-webui\modules\models.py", line 10, in <module>
    from accelerate import infer_auto_device_map, init_empty_weights
  File "C:\Users\alkam\anaconda3\envs\textgen\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\Users\alkam\anaconda3\envs\textgen\lib\site-packages\accelerate\accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "C:\Users\alkam\anaconda3\envs\textgen\lib\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "C:\Users\alkam\anaconda3\envs\textgen\lib\site-packages\accelerate\utils\__init__.py", line 131, in <module>
    from .bnb import has_4bit_bnb_layers, load_and_quantize_model
  File "C:\Users\alkam\anaconda3\envs\textgen\lib\site-packages\accelerate\utils\bnb.py", line 42, in <module>
    import bitsandbytes as bnb
  File "C:\Users\alkam\anaconda3\envs\textgen\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\alkam\anaconda3\envs\textgen\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\alkam\anaconda3\envs\textgen\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\alkam\anaconda3\envs\textgen\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\alkam\anaconda3\envs\textgen\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\alkam\anaconda3\envs\textgen\lib\site-packages\bitsandbytes\cextension.py", line 13, in <module>
    setup.run_cuda_setup()
  File "C:\Users\alkam\anaconda3\envs\textgen\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 126, in run_cuda_setup
    binary_name, cudart_path, cc, cuda_version_string = evaluate_cuda_setup()
  File "C:\Users\alkam\anaconda3\envs\textgen\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 419, in evaluate_cuda_setup
    cudart_path = determine_cuda_runtime_lib_path()
  File "C:\Users\alkam\anaconda3\envs\textgen\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 361, in determine_cuda_runtime_lib_path
    lib_path_cuda_libs = find_cuda_lib_in(candidate_env_vars["PATH"])
  File "C:\Users\alkam\anaconda3\envs\textgen\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 239, in find_cuda_lib_in
    resolve_paths_list(paths_list_candidate)
  File "C:\Users\alkam\anaconda3\envs\textgen\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 234, in resolve_paths_list
    return remove_non_existent_dirs(extract_candidate_paths(paths_list_candidate))
  File "C:\Users\alkam\anaconda3\envs\textgen\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 208, in remove_non_existent_dirs
    raise exc
  File "C:\Users\alkam\anaconda3\envs\textgen\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 204, in remove_non_existent_dirs
    if path.exists():
  File "C:\Users\alkam\anaconda3\envs\textgen\lib\pathlib.py", line 1290, in exists
    self.stat()
  File "C:\Users\alkam\anaconda3\envs\textgen\lib\pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\root\\AppData\\Local\\Microsoft\\WindowsApps'
```

### System Info

```shell
Windows 11 updated to the latest version (22H2)
```

**Comment by alkampfergit** [comment]
Clearly if I use the root user to give access to that directory everything runs just fine.
