### ISSUE TITLE
Missing Argument on model_info using openai extension (v1/models/gpt-3.5-turbo etc.)

### ISSUE THREAD

**Issue by TheMasterFX** [oobabooga/text-generation-webui#3305]
When calling the openai API with a specific model you got an error since the needed string parameter is missing
```127.0.0.1 - - [25/Jul/2023 19:42:20] "GET /v1/models/gpt-3.5-turbo HTTP/1.1" 500 -
OpenAIError TypeError("model_info() missing 1 required positional argument: 'model_name'")
Traceback (most recent call last):
  File "F:\text-gen-webui\text-generation-webui\extensions\openai\script.py", line 98, in wrapper
    func(self)
  File "F:\text-gen-webui\text-generation-webui\extensions\openai\script.py", line 123, in do_GET
    resp = OAImodels.model_info()
TypeError: model_info() missing 1 required positional argument: 'model_name'

127.0.0.1 - - [25/Jul/2023 19:43:22] "GET /v1/models/gpt-3.5-turbo HTTP/1.1" 500 -
```
Model name should be used as parameter
```
diff --git a/extensions/openai/script.py b/extensions/openai/script.py
index 86f2deb..f95205a 100644
--- a/extensions/openai/script.py
+++ b/extensions/openai/script.py
@@ -120,7 +120,7 @@ class Handler(BaseHTTPRequestHandler):
                 resp = OAImodels.list_models(is_legacy)
             else:
                 model_name = self.path[len('/v1/models/'):]
-                resp = OAImodels.model_info()
+                resp = OAImodels.model_info(model_name)

             self.return_json(resp)

```
https://github.com/oobabooga/text-generation-webui/blob/08c622df2e26811440f6b3311dff3553ba20dc86/extensions/openai/script.py#L123C24-L123C24

**Comment by matatonic** [comment]
Good catch, thanks, I will fix asap.
