### ISSUE TITLE
Model is not loading , few lib missing - UI is not working in MAC M2 

### ISSUE THREAD

**Issue by Karthiofficialpage** [oobabooga/text-generation-webui#3328]
### Describe the bug

I tried manual as well as one click install version both resulting same and leading to one or other issue in Mac. UI is loading but when i try to load any of the model , it ends up in error saying some of lib is missing or not able to import the function.

Please fix the mac released installation issues or try to share us pre installed files that can be ran with just required software.  

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

just install the webui and load the model , it gives auto_gtpq is not able tp import , when i fixed by installing it then it says other error related to the same. 

1- ModuleNotFoundError: No module named 'auto_gptq'
2- ModuleNotFoundError: No module named 'exllama'
3 - ModuleNotFoundError: No module named 'generator'
4-line 258, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
5 - text-llm/text-generation-webui/modules/GPTQ_loader.py", line 21, in <module>
    sys.exit(-1)
SystemExit: -1

6 -ModuleNotFoundError: No module named 'llama_inference_offload'

7 -  line 238, in llamacpp_loader
    model_file = list(Path(f'{shared.args.model_dir}/{model_name}').glob('*ggml*.bin'))[0]
IndexError: list index out of range

### Logs

```shell
warn("The installed version of bitsandbytes was compiled without GPU support. "
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Closing server running on port: 7860
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
2023-07-27 01:26:39 INFO:Loading vicuna-13b-GPTQ-4bit-128g...
2023-07-27 01:26:39 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/Users/karthi/playground/text-llm/text-generation-webui/server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/models.py", line 78, in load_model
    output = load_func_map[loader](model_name)
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/models.py", line 285, in AutoGPTQ_loader
    import modules.AutoGPTQ_loader
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/AutoGPTQ_loader.py", line 3, in <module>
    from auto_gptq import AutoGPTQForCausalLM, BaseQuantizeConfig
ModuleNotFoundError: No module named 'auto_gptq'

2023-07-27 01:31:07 INFO:Loading gpt4-x-alpaca-13b-native-4bit-128g...
2023-07-27 01:31:08 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/Users/karthi/playground/text-llm/text-generation-webui/server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/models.py", line 78, in load_model
    output = load_func_map[loader](model_name)
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/models.py", line 238, in llamacpp_loader
    model_file = list(Path(f'{shared.args.model_dir}/{model_name}').glob('*ggml*.bin'))[0]
IndexError: list index out of range

2023-07-27 01:40:04 INFO:Loading gpt4-x-alpaca-13b-native-4bit-128g...
2023-07-27 01:40:04 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/Users/karthi/playground/text-llm/text-generation-webui/server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/models.py", line 78, in load_model
    output = load_func_map[loader](model_name)
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/models.py", line 238, in llamacpp_loader
    model_file = list(Path(f'{shared.args.model_dir}/{model_name}').glob('*ggml*.bin'))[0]
IndexError: list index out of range

2023-07-27 01:40:08 INFO:Loading gpt4-x-alpaca-13b-native-4bit-128g...
2023-07-27 01:40:08 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/Users/karthi/playground/text-llm/text-generation-webui/server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/models.py", line 78, in load_model
    output = load_func_map[loader](model_name)
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/models.py", line 238, in llamacpp_loader
    model_file = list(Path(f'{shared.args.model_dir}/{model_name}').glob('*ggml*.bin'))[0]
IndexError: list index out of range

2023-07-27 01:40:25 INFO:Loading gpt4-x-alpaca-13b-native-4bit-128g...
2023-07-27 01:40:25 ERROR:Failed to load GPTQ-for-LLaMa
2023-07-27 01:40:25 ERROR:See https://github.com/oobabooga/text-generation-webui/blob/main/docs/GPTQ-models-(4-bit-mode).md
2023-07-27 01:40:25 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/GPTQ_loader.py", line 17, in <module>
    import llama_inference_offload
ModuleNotFoundError: No module named 'llama_inference_offload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/karthi/playground/text-llm/text-generation-webui/server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/models.py", line 78, in load_model
    output = load_func_map[loader](model_name)
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/models.py", line 277, in GPTQ_loader
    import modules.GPTQ_loader
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/GPTQ_loader.py", line 21, in <module>
    sys.exit(-1)
SystemExit: -1

2023-07-27 01:40:50 INFO:Loading gpt4-x-alpaca-13b-native-4bit-128g...
2023-07-27 01:40:51 ERROR:Failed to load GPTQ-for-LLaMa
2023-07-27 01:40:51 ERROR:See https://github.com/oobabooga/text-generation-webui/blob/main/docs/GPTQ-models-(4-bit-mode).md
2023-07-27 01:40:51 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/GPTQ_loader.py", line 17, in <module>
    import llama_inference_offload
ModuleNotFoundError: No module named 'llama_inference_offload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/karthi/playground/text-llm/text-generation-webui/server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/models.py", line 78, in load_model
    output = load_func_map[loader](model_name)
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/models.py", line 277, in GPTQ_loader
    import modules.GPTQ_loader
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/GPTQ_loader.py", line 21, in <module>
    sys.exit(-1)
SystemExit: -1

2023-07-27 01:40:55 INFO:Loading gpt4-x-alpaca-13b-native-4bit-128g...
2023-07-27 01:40:55 ERROR:Failed to load GPTQ-for-LLaMa
2023-07-27 01:40:55 ERROR:See https://github.com/oobabooga/text-generation-webui/blob/main/docs/GPTQ-models-(4-bit-mode).md
2023-07-27 01:40:55 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/GPTQ_loader.py", line 17, in <module>
    import llama_inference_offload
ModuleNotFoundError: No module named 'llama_inference_offload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/karthi/playground/text-llm/text-generation-webui/server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/models.py", line 78, in load_model
    output = load_func_map[loader](model_name)
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/models.py", line 277, in GPTQ_loader
    import modules.GPTQ_loader
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/GPTQ_loader.py", line 21, in <module>
    sys.exit(-1)
SystemExit: -1

2023-07-27 01:40:58 INFO:Loading gpt4-x-alpaca-13b-native-4bit-128g...
2023-07-27 01:40:58 ERROR:Failed to load GPTQ-for-LLaMa
2023-07-27 01:40:58 ERROR:See https://github.com/oobabooga/text-generation-webui/blob/main/docs/GPTQ-models-(4-bit-mode).md
2023-07-27 01:40:58 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/GPTQ_loader.py", line 17, in <module>
    import llama_inference_offload
ModuleNotFoundError: No module named 'llama_inference_offload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/karthi/playground/text-llm/text-generation-webui/server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/models.py", line 78, in load_model
    output = load_func_map[loader](model_name)
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/models.py", line 277, in GPTQ_loader
    import modules.GPTQ_loader
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/GPTQ_loader.py", line 21, in <module>
    sys.exit(-1)
SystemExit: -1

2023-07-27 01:41:22 INFO:Loading gpt4-x-alpaca-13b-native-4bit-128g...
2023-07-27 01:41:22 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/Users/karthi/playground/text-llm/text-generation-webui/server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/models.py", line 78, in load_model
    output = load_func_map[loader](model_name)
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/models.py", line 285, in AutoGPTQ_loader
    import modules.AutoGPTQ_loader
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/AutoGPTQ_loader.py", line 3, in <module>
    from auto_gptq import AutoGPTQForCausalLM, BaseQuantizeConfig
ModuleNotFoundError: No module named 'auto_gptq'

2023-07-27 01:41:27 INFO:Loading vicuna-13b-GPTQ-4bit-128g...
2023-07-27 01:41:27 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/Users/karthi/playground/text-llm/text-generation-webui/server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/models.py", line 78, in load_model
    output = load_func_map[loader](model_name)
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/models.py", line 285, in AutoGPTQ_loader
    import modules.AutoGPTQ_loader
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/AutoGPTQ_loader.py", line 3, in <module>
    from auto_gptq import AutoGPTQForCausalLM, BaseQuantizeConfig
ModuleNotFoundError: No module named 'auto_gptq'

2023-07-27 01:41:37 INFO:Loading gpt4-x-alpaca-13b-native-4bit-128g...
2023-07-27 01:41:37 WARNING:Exllama module failed to load. Will attempt to load from repositories.
2023-07-27 01:41:37 ERROR:Could not find repositories/exllama/. Make sure that exllama is cloned inside repositories/ and is up to date.
2023-07-27 01:41:37 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/exllama.py", line 10, in <module>
    from exllama.generator import ExLlamaGenerator
ModuleNotFoundError: No module named 'exllama'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/karthi/playground/text-llm/text-generation-webui/server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/models.py", line 78, in load_model
    output = load_func_map[loader](model_name)
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/models.py", line 291, in ExLlama_loader
    from modules.exllama import ExllamaModel
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/exllama.py", line 19, in <module>
    from generator import ExLlamaGenerator
ModuleNotFoundError: No module named 'generator'

2023-07-27 01:41:45 INFO:Loading gpt4-x-alpaca-13b-native-4bit-128g...
2023-07-27 01:41:45 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/Users/karthi/playground/text-llm/text-generation-webui/server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/models.py", line 78, in load_model
    output = load_func_map[loader](model_name)
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/models.py", line 200, in huggingface_loader
    params['max_memory'] = get_max_memory_dict()
  File "/Users/karthi/playground/text-llm/text-generation-webui/modules/models.py", line 316, in get_max_memory_dict
    total_mem = (torch.cuda.get_device_properties(0).total_memory / (1024 * 1024))
  File "/Users/karthi/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/cuda/__init__.py", line 414, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "/Users/karthi/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/cuda/__init__.py", line 258, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

### System Info

```shell
Apple M2 ,8 GB , 13.5 (22G74)
```

**Comment by jllllll** [comment]
Use a GGML or HF model. GPTQ models are made for NVIDIA GPUs.

**Comment by Karthiofficialpage** [comment]
> Use a GGML or HF model. GPTQ models are made for NVIDIA GPUs.

i tried  Wizard-Vicuna-13B-Uncensored-HF. but yet the below error is popping up.. 
1)
2023-07-27 18:27:59 ERROR:Could not load the model because a tokenizer in transformers format was not found. Please download oobabooga/llama-tokenizer.

2)

Traceback (most recent call last): File “/Users/karthi/playground/text-llm/oobabooga_macos/text-generation-webui/modules/exllama_hf.py”, line 14, in from exllama.model import ExLlama, ExLlamaCache, ExLlamaConfig ModuleNotFoundError: No module named ‘exllama’

During handling of the above exception, another exception occurred:

Traceback (most recent call last): File “/Users/karthi/playground/text-llm/oobabooga_macos/text-generation-webui/server.py”, line 68, in load_model_wrapper shared.model, shared.tokenizer = load_model(shared.model_name, loader) File “/Users/karthi/playground/text-llm/oobabooga_macos/text-generation-webui/modules/models.py”, line 78, in load_model output = load_func_map[loader](http://127.0.0.1:7860/model_name) File “/Users/karthi/playground/text-llm/oobabooga_macos/text-generation-webui/modules/models.py”, line 298, in ExLlama_HF_loader from modules.exllama_hf import ExllamaHF File “/Users/karthi/playground/text-llm/oobabooga_macos/text-generation-webui/modules/exllama_hf.py”, line 21, in from model import ExLlama, ExLlamaCache, ExLlamaConfig ModuleNotFoundError: No module named ‘model’

**Comment by jllllll** [comment]
exllama can't load HF models. Use the Transformers loader to load them. Use the llama.cpp loader to load GGML models.

**Comment by Karthiofficialpage** [comment]
I was able to load the model

**Comment by LateButSteady** [comment]
What made you be able to load the model?
I'm also facing the same issue. Thx in advance :)

**Comment by felipeavilis** [comment]
> I was able to load the model

Great! What have you done? Im faccing the same issue here.

**Comment by Karthiofficialpage** [comment]
Change the model , use GGML or HF models and use low parameter at first , still it is giving slow response though 

> > I was able to load the model
> 
> Great! What have you done? Im faccing the same issue here.
