### ISSUE TITLE
[Llama-2-7b-Chat-GPTQ] RuntimeError: self and mat2 must have the same dtype

### ISSUE THREAD

**Issue by Bec-k** [oobabooga/text-generation-webui#3333]
### Describe the bug

**Using latest main branch** with commit `d6314fd5394bbfe2edd9030d953892dcfc4de105` and this model from here:
https://huggingface.co/TheBloke/Llama-2-7b-Chat-GPTQ

**Using raw text dataset.** With default 3 new lines separation `\n\n\n` (Hard Cut String).

Getting this error when performing training:
```
2023-07-27 16:08:08 WARNING:It is highly recommended you use `--load-in-8bit` for LoRA training.
2023-07-27 16:08:10 INFO:Loading raw text file dataset...
2023-07-27 16:08:17 INFO:Getting model ready...
/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/peft/utils/other.py:102: FutureWarning: prepare_model_for_int8_training is deprecated and will be removed in a future version. Use prepare_model_for_kbit_training instead.
  warnings.warn(
2023-07-27 16:08:17 INFO:Prepping for training...
2023-07-27 16:08:17 INFO:Creating LoRA model...
2023-07-27 16:08:18 INFO:Starting training...
Training 'llama' model using (q, v) projections
Trainable params: 16,777,216 (1.5391 %), All params: 1,090,048,000 (Model: 1,073,270,784)
2023-07-27 16:08:18 INFO:Log file 'train_dataset_sample.json' created in the 'logs' directory.
wandb: Tracking run with wandb version 0.15.7
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
Exception in thread Thread-2 (threaded_run):
Traceback (most recent call last):
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/var/local/acp/oobabooga/text-generation-webui/modules/training.py", line 665, in threaded_run
    trainer.train()
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/trainer.py", line 1809, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/trainer.py", line 2654, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/trainer.py", line 2679, in compute_loss
    outputs = model(**inputs)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 581, in forward
    return model_forward(*args, **kwargs)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 569, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/peft/peft_model.py", line 947, in forward
    return self.base_model(
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/auto_gptq/modeling/_base.py", line 433, in forward
    return self.model(*args, **kwargs)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 806, in forward
    outputs = self.model(
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 693, in forward
    layer_outputs = decoder_layer(
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 408, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/auto_gptq/nn_modules/fused_llama_attn.py", line 53, in forward
    qkv_states = self.qkv_proj(hidden_states)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/peft/tuners/lora.py", line 840, in forward
    result = F.linear(x, transpose(self.weight, self.fan_in_fan_out), bias=self.bias)
RuntimeError: self and mat2 must have the same dtype
2023-07-27 16:08:21 INFO:Training complete, saving...
2023-07-27 16:08:21 INFO:Training complete!
```

Some strange `<unk>` in the `train_dataset_sample.json` that's a placeholder to match required input size? Just a filler?
```
    {
        "value": "<unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><s>Version\\Winlogon"
    },
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Use any raw text dataset and described model and perform training with default settings for 1 epoch.

### Logs

```shell
2023-07-27 16:08:08 WARNING:It is highly recommended you use `--load-in-8bit` for LoRA training.
2023-07-27 16:08:10 INFO:Loading raw text file dataset...
2023-07-27 16:08:17 INFO:Getting model ready...
/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/peft/utils/other.py:102: FutureWarning: prepare_model_for_int8_training is deprecated and will be removed in a future version. Use prepare_model_for_kbit_training instead.
  warnings.warn(
2023-07-27 16:08:17 INFO:Prepping for training...
2023-07-27 16:08:17 INFO:Creating LoRA model...
2023-07-27 16:08:18 INFO:Starting training...
Training 'llama' model using (q, v) projections
Trainable params: 16,777,216 (1.5391 %), All params: 1,090,048,000 (Model: 1,073,270,784)
2023-07-27 16:08:18 INFO:Log file 'train_dataset_sample.json' created in the 'logs' directory.
wandb: Tracking run with wandb version 0.15.7
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
Exception in thread Thread-2 (threaded_run):
Traceback (most recent call last):
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/var/local/acp/oobabooga/text-generation-webui/modules/training.py", line 665, in threaded_run
    trainer.train()
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/trainer.py", line 1809, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/trainer.py", line 2654, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/trainer.py", line 2679, in compute_loss
    outputs = model(**inputs)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 581, in forward
    return model_forward(*args, **kwargs)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 569, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/peft/peft_model.py", line 947, in forward
    return self.base_model(
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/auto_gptq/modeling/_base.py", line 433, in forward
    return self.model(*args, **kwargs)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 806, in forward
    outputs = self.model(
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 693, in forward
    layer_outputs = decoder_layer(
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 408, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/auto_gptq/nn_modules/fused_llama_attn.py", line 53, in forward
    qkv_states = self.qkv_proj(hidden_states)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/peft/tuners/lora.py", line 840, in forward
    result = F.linear(x, transpose(self.weight, self.fan_in_fan_out), bias=self.bias)
RuntimeError: self and mat2 must have the same dtype
2023-07-27 16:08:21 INFO:Training complete, saving...
2023-07-27 16:08:21 INFO:Training complete!
```

### System Info

```shell
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"


+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   52C    P8    19W / 115W |    795MiB /  8192MiB |     18%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1614      G   /usr/lib/xorg/Xorg                458MiB |
|    0   N/A  N/A      2044      G   /usr/bin/gnome-shell               92MiB |
|    0   N/A  N/A      5053      G   ...909798386149046327,262144      179MiB |
|    0   N/A  N/A     29834      G   .../usr/bin/telegram-desktop        3MiB |
|    0   N/A  N/A     31325      G   ...RendererForSitePerProcess       55MiB |
+-----------------------------------------------------------------------------+
```
```

**Comment by Bec-k** [comment]
I suspect that it is related to dtype and bit mode of the loaded model.

**Comment by Bec-k** [comment]
its 4bit quantized model [ptq_model-4bit-128g.safetensors](https://huggingface.co/TheBloke/Llama-2-7b-Chat-GPTQ/blob/main/gptq_model-4bit-128g.safetensors)

**Comment by Bec-k** [comment]
It seems that it is ignoring `quantize_config.json` file settings. I might be wrong thou, but GUI doesn't reflect those settings from that file. Values in the form doesn't change, shouldn't they be the same as in that config file from downloaded model?
```
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
2023-07-27 16:35:19 INFO:Loading TheBloke_Llama-2-7b-Chat-GPTQ...
2023-07-27 16:35:19 INFO:The AutoGPTQ params are: {'model_basename': 'gptq_model-4bit-128g', 'device': 'cuda:0', 'use_triton': False, 'inject_fused_attention': True, 'inject_fused_mlp': True, 'use_safetensors': True, 'trust_remote_code': False, 'max_memory': None, 'quantize_config': None, 'use_cuda_fp16': True}
2023-07-27 16:35:19 WARNING:The safetensors archive passed at models/TheBloke_Llama-2-7b-Chat-GPTQ/gptq_model-4bit-128g.safetensors does not contain metadata. Make sure to save your model with the `save_pretrained` method. Defaulting to 'pt' metadata.
2023-07-27 16:35:21 WARNING:skip module injection for FusedLlamaMLPForQuantizedModel not support integrate without triton yet.
2023-07-27 16:35:21 INFO:Loaded the model in 2.47 seconds.
```

**Comment by Bec-k** [comment]
ok, it seems its outdated and complicated due to complex quantization method

**Comment by clearsitedesigns** [comment]
I've been having the same issue all day.

**Comment by twmoveon** [comment]
Did you solve it? I have the same problem.

**Comment by 13631368** [comment]
> ### Describe the bug
> 
> **Using latest main branch** with commit `d6314fd5394bbfe2edd9030d953892dcfc4de105` and this model from here:
> https://huggingface.co/TheBloke/Llama-2-7b-Chat-GPTQ
> 
> **Using raw text dataset.** With default 3 new lines separation `\n\n\n` (Hard Cut String).
> 
> Getting this error when performing training:
> ```
> 2023-07-27 16:08:08 WARNING:It is highly recommended you use `--load-in-8bit` for LoRA training.
> 2023-07-27 16:08:10 INFO:Loading raw text file dataset...
> 2023-07-27 16:08:17 INFO:Getting model ready...
> /home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/peft/utils/other.py:102: FutureWarning: prepare_model_for_int8_training is deprecated and will be removed in a future version. Use prepare_model_for_kbit_training instead.
>   warnings.warn(
> 2023-07-27 16:08:17 INFO:Prepping for training...
> 2023-07-27 16:08:17 INFO:Creating LoRA model...
> 2023-07-27 16:08:18 INFO:Starting training...
> Training 'llama' model using (q, v) projections
> Trainable params: 16,777,216 (1.5391 %), All params: 1,090,048,000 (Model: 1,073,270,784)
> 2023-07-27 16:08:18 INFO:Log file 'train_dataset_sample.json' created in the 'logs' directory.
> wandb: Tracking run with wandb version 0.15.7
> wandb: W&B syncing is set to `offline` in this directory.  
> wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
> Exception in thread Thread-2 (threaded_run):
> Traceback (most recent call last):
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/threading.py", line 953, in run
>     self._target(*self._args, **self._kwargs)
>   File "/var/local/acp/oobabooga/text-generation-webui/modules/training.py", line 665, in threaded_run
>     trainer.train()
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
>     return inner_training_loop(
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/trainer.py", line 1809, in _inner_training_loop
>     tr_loss_step = self.training_step(model, inputs)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/trainer.py", line 2654, in training_step
>     loss = self.compute_loss(model, inputs)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/trainer.py", line 2679, in compute_loss
>     outputs = model(**inputs)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 581, in forward
>     return model_forward(*args, **kwargs)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 569, in __call__
>     return convert_to_fp32(self.model_forward(*args, **kwargs))
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
>     return func(*args, **kwargs)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/peft/peft_model.py", line 947, in forward
>     return self.base_model(
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/auto_gptq/modeling/_base.py", line 433, in forward
>     return self.model(*args, **kwargs)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 806, in forward
>     outputs = self.model(
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 693, in forward
>     layer_outputs = decoder_layer(
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 408, in forward
>     hidden_states, self_attn_weights, present_key_value = self.self_attn(
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/auto_gptq/nn_modules/fused_llama_attn.py", line 53, in forward
>     qkv_states = self.qkv_proj(hidden_states)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/peft/tuners/lora.py", line 840, in forward
>     result = F.linear(x, transpose(self.weight, self.fan_in_fan_out), bias=self.bias)
> RuntimeError: self and mat2 must have the same dtype
> 2023-07-27 16:08:21 INFO:Training complete, saving...
> 2023-07-27 16:08:21 INFO:Training complete!
> ```
> 
> Some strange `<unk>` in the `train_dataset_sample.json` that's a placeholder to match required input size? Just a filler?
> ```
>     {
>         "value": "<unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><s>Version\\Winlogon"
>     },
> ```
> 
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### Reproduction
> 
> Use any raw text dataset and described model and perform training with default settings for 1 epoch.
> 
> ### Screenshot
> 
> _No response_
> 
> ### Logs
> 
> ```shell
> 2023-07-27 16:08:08 WARNING:It is highly recommended you use `--load-in-8bit` for LoRA training.
> 2023-07-27 16:08:10 INFO:Loading raw text file dataset...
> 2023-07-27 16:08:17 INFO:Getting model ready...
> /home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/peft/utils/other.py:102: FutureWarning: prepare_model_for_int8_training is deprecated and will be removed in a future version. Use prepare_model_for_kbit_training instead.
>   warnings.warn(
> 2023-07-27 16:08:17 INFO:Prepping for training...
> 2023-07-27 16:08:17 INFO:Creating LoRA model...
> 2023-07-27 16:08:18 INFO:Starting training...
> Training 'llama' model using (q, v) projections
> Trainable params: 16,777,216 (1.5391 %), All params: 1,090,048,000 (Model: 1,073,270,784)
> 2023-07-27 16:08:18 INFO:Log file 'train_dataset_sample.json' created in the 'logs' directory.
> wandb: Tracking run with wandb version 0.15.7
> wandb: W&B syncing is set to `offline` in this directory.  
> wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
> Exception in thread Thread-2 (threaded_run):
> Traceback (most recent call last):
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/threading.py", line 953, in run
>     self._target(*self._args, **self._kwargs)
>   File "/var/local/acp/oobabooga/text-generation-webui/modules/training.py", line 665, in threaded_run
>     trainer.train()
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
>     return inner_training_loop(
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/trainer.py", line 1809, in _inner_training_loop
>     tr_loss_step = self.training_step(model, inputs)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/trainer.py", line 2654, in training_step
>     loss = self.compute_loss(model, inputs)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/trainer.py", line 2679, in compute_loss
>     outputs = model(**inputs)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 581, in forward
>     return model_forward(*args, **kwargs)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 569, in __call__
>     return convert_to_fp32(self.model_forward(*args, **kwargs))
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
>     return func(*args, **kwargs)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/peft/peft_model.py", line 947, in forward
>     return self.base_model(
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/auto_gptq/modeling/_base.py", line 433, in forward
>     return self.model(*args, **kwargs)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 806, in forward
>     outputs = self.model(
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 693, in forward
>     layer_outputs = decoder_layer(
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 408, in forward
>     hidden_states, self_attn_weights, present_key_value = self.self_attn(
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/auto_gptq/nn_modules/fused_llama_attn.py", line 53, in forward
>     qkv_states = self.qkv_proj(hidden_states)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/beck/anaconda3/envs/oobabooga-text-gen/lib/python3.10/site-packages/peft/tuners/lora.py", line 840, in forward
>     result = F.linear(x, transpose(self.weight, self.fan_in_fan_out), bias=self.bias)
> RuntimeError: self and mat2 must have the same dtype
> 2023-07-27 16:08:21 INFO:Training complete, saving...
> 2023-07-27 16:08:21 INFO:Training complete!
> ```
> 
> 
> ### System Info
> 
> ```shell
> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=22.04
> DISTRIB_CODENAME=jammy
> DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
> 
> 
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
> | N/A   52C    P8    19W / 115W |    795MiB /  8192MiB |     18%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                                  |
> |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> |        ID   ID                                                   Usage      |
> |=============================================================================|
> |    0   N/A  N/A      1614      G   /usr/lib/xorg/Xorg                458MiB |
> |    0   N/A  N/A      2044      G   /usr/bin/gnome-shell               92MiB |
> |    0   N/A  N/A      5053      G   ...909798386149046327,262144      179MiB |
> |    0   N/A  N/A     29834      G   .../usr/bin/telegram-desktop        3MiB |
> |    0   N/A  N/A     31325      G   ...RendererForSitePerProcess       55MiB |
> +-----------------------------------------------------------------------------+
> ```
> ```
>
