### ISSUE TITLE
Linux torch rocm bitsandbytes cuda None

### ISSUE THREAD

**Issue by adeliktas** [oobabooga/text-generation-webui#3339]
### Describe the bug

just with cpu i'm only getting ~1 tokens/s.
(I haven't specified any arguments like possible core/threads, but wanted to first test base performance with gpu as well.)
I installed torch-2.0.1+rocm5.4.2 and webui errors at launch with:
>major, minor = map(int, torch.version.cuda.split("."))
>AttributeError: 'NoneType' object has no attribute 'split'

running other versions of bitsandbytes==0.38.1 up to current 0.41.0 did not help.
Only pip uninstall of torch (rocm version) and reinstall torch (cpu version torch-2.0.1-cp310-cp310-manylinux1_x86_64.whl) makes it "useable" again.

>>> import torch
>>> print(torch.__version__)    2.0.1+rocm5.4.2
>>> print("GPU available:", torch.cuda.is_available())    GPU available: True
>>> print(torch.version.cuda)    None

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

python3.10 -m venv .
. bin/activate.fish
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.4.2
pip install -r requirements.txt
python3.10 server.py

### Logs

```shell
from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/foo/text-generation-webui/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 13, in <module>
    setup.run_cuda_setup()
  File "/home/foo/text-generation-webui/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 120, in run_cuda_setup
    binary_name, cudart_path, cc, cuda_version_string = evaluate_cuda_setup()
  File "/home/foo/text-generation-webui/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 341, in evaluate_cuda_setup
    cuda_version_string = get_cuda_version()
  File "/home/foo/text-generation-webui/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 311, in get_cuda_version
    major, minor = map(int, torch.version.cuda.split("."))
AttributeError: 'NoneType' object has no attribute 'split'
```

### System Info

```shell
Cpu: AMD Ryzen 9 3950X
Gpu: AMD Radeon™ RX 6900 XT
Gentoo Linux 6.2
Python 3.10.12
```

**Comment by ianwal** [comment]
I'm experiencing the same thing on Arch Linux 6.4.7 with an AMD RX 6600XT, even with manually installing https://github.com/agrocylo/bitsandbytes-rocm.

**Comment by Orionnss** [comment]
I'm experiencing the same issue with an AMD RX 7900XT

**Comment by rabume** [comment]
I'm experiencing the same issue with an AMD RX 6800 on Arch Linux. Using the one click installer.

**Comment by JillianTo** [comment]
After doing installing requirements.txt, do "pip uninstall bitsandbytes" and manually install the agrocylo one

**Comment by rabume** [comment]
@JillianTo Ye this worked. Thanks a lot.

**Comment by adeliktas** [comment]
> After installing requirements.txt, do "pip uninstall bitsandbytes" and manually install the agrocylo one (for good measure, comment out the bitsandbytes lines from requirements.txt so it doesn't overwrite the rocm version when you update)



> @JillianTo Ye this worked. Thanks a lot.
> ## Reproduction
> 
>     1. git clone https://github.com/oobabooga/text-generation-webui
> 
>     2. cd text-generation-webui
> 
>     3. vim requirements.txt -> _remove all lines related to bitsandbytes_
> 
>     4. python3.10 -m venv .
> 
>     5. . bin/activate.fish
> 
>     6. pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.4.2
> 
>     7. pip install -r requirements.txt
> 
>     8. python3.10 server.py
(python3.10 server.py --auto-devices --gpu-memory 12 --n-gpu-layers 1000000000)
Didn't solve anything for me, still runs on cpu. @rabume Are you sure it is utilizing your gpu, so how high is your GPU usage?

**Comment by John23Anthony** [comment]
I managed to get the WebUI working following the instructions here. However, once the model (TheBloke/Wizard-Vicuna-13B-Uncensored-GPTQ) has loaded and I try and generate some text, I get this error:

```
Traceback (most recent call last):
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/text-generation-webui/modules/callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/text-generation-webui/modules/text_generation.py", line 294, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/transformers/generation/utils.py", line 2642, in sample
    outputs = self(
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 806, in forward
    outputs = self.model(
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/text-generation-webui/repositories/GPTQ-for-LLaMa/llama_inference_offload.py", line 162, in forward
    layer_outputs = decoder_layer(
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 408, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 305, in forward
    query_states = self.q_proj(hidden_states)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/text-generation-webui/repositories/GPTQ-for-LLaMa/quant.py", line 426, in forward
    quant_cuda.vecquant4matmul(x, self.qweight, y, self.scales, self.qzeros, self.groupsize)
RuntimeError: Unrecognized tensor type ID: AutocastCUDA
```

No text is generated.

I've tried replacing the GPTQ-for-Llama with the one described in https://rentry.org/eq3hg, but I'm unable to install it due to this error:

```
88 warnings generated when compiling for host.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1917, in _run_ninja_build
    subprocess.run(
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/text-generation-webui/repositories/GPTQ-for-LLaMa/setup_rocm.py", line 4, in <module>
    setup(
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/command/install.py", line 80, in run
    self.do_egg_install()
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/command/install.py", line 129, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 865, in build_extensions
    build_ext.build_extensions(self)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 678, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1590, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/tony/AI/text_gen/oobabooga_linux_gpu/installer_files/env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1933, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

I do have a CPU version with GPU offloading running without issue. However, I would like to get the GPTQ-for-LLaMa working if possible. Am i just an idiot who's missing something with the install process? I'm only commenting here since I've been stuck with it a few days now, and the issue is similar to mine (identical until I followed the steps given here). Am I just an idiot who's missing something with the install process?

**System Info:**
```
CPU: AMD Ryzen 7 5800x3D
GPU: AMD Radeon RX 6700 XT
OS: Garuda Linux (Arch)
```

**Comment by rabume** [comment]
@adeliktas Yes, it is utilizing my GPU. Spikes after loading of a model from 10% to around 30%.(facebook_opt-1.3b)
![image](https://github.com/oobabooga/text-generation-webui/assets/19410629/0304c51b-f5c6-42f0-8eee-5638e1496211)

@John23Anthony Had exactly the same issue. Tried this guide, but had no luck: https://github.com/WapaMario63/GPTQ-for-LLaMa-ROCm/wiki/Install-with-Text-Generation

**Comment by Orionnss** [comment]
> @JillianTo Ye this worked. Thanks a lot.
> ## Reproduction
> 
>     1. git clone https://github.com/oobabooga/text-generation-webui
> 
>     2. cd text-generation-webui
> 
>     3. vim requirements.txt -> _remove all lines related to bitsandbytes_
> 
>     4. python3.10 -m venv .
> 
>     5. . bin/activate.fish
> 
>     6. pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.4.2
> 
>     7. pip install -r requirements.txt
> 
>     8. python3.10 server.py

It worked for me, It's my GPU that is used, everything's good. Thank you very much

**Comment by adeliktas** [comment]
solved it with
```
export HSA_OVERRIDE_GFX_VERSION=10.3.0
export HIP_VISIBLE_DEVICES=0
export CUDA_VERSION=gfx1030 #likely irrelevant      
source .venv/bin/activate
./start_linux.sh
```
