### ISSUE TITLE
state isn't clearly understood how to incorporate for script.py

### ISSUE THREAD

**Issue by thistleknot** [oobabooga/text-generation-webui#3341]
### Describe the bug

I see that output_modifier and a few other functions require state object, which is not defined in script.py nor are any of the existing plugins (that I looked at) use a state object.

As a result, I am unable to use the functions.  I get a message about needing to pass state

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

try to use this snippet

https://github.com/ChobPT/oobaboogas-webui-langchain_agent/blob/main/script.py#L185-L190

```
def input_modifier(string):
    if string[:3] == "/do Story":
       print('hi')
       string += ' Tell me a story.'
    else:
        output_modifier(string.split("###")[0].split("Human:")[0])
    return string.replace('/do ', '')

```

### Logs

```shell
File "/home/user/oobabooga_linux/text-generation-webui/extensions/helloworld/script.py", line 144, in input_modifier
    output_modifier(string.split("###")[0].split("Human:")[0],state_dict)
NameError: name 'state_dict' is not defined

```
```
  File "/home/user/oobabooga_linux/text-generation-webui/extensions/helloworld/script.py", line 144, in input_modifier
    output_modifier(string.split("###")[0].split("Human:")[0],state)
NameError: name 'state' is not defined

```

```
    output_modifier(string.split("###")[0].split("Human:")[0])
TypeError: output_modifier() missing 1 required positional argument: 'state'

```

and if I removed state from output_modifier (as you see in my snippet above w print) I get no modified output nor print statement at console
Output generated in 1.99 seconds (9.06 tokens/s, 18 tokens, context 66, seed 123523724)
Traceback (most recent call last):
  File "/home/user/oobabooga_linux/text-generation-webui/server.py", line 1181, in <module>
    time.sleep(0.5)
```


### System Info

```shell
python 3.9 oracle linux 8.5
```

**Comment by thistleknot** [comment]
this worked
```
def output_modifier(string, state):
    """
    Modifies the LLM output before it gets presented.

    In chat mode, the modified version goes into history['visible'],
    and the original version goes into history['internal'].
    """
    return string+'test'

```
