### ISSUE TITLE
CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by krypterro** [oobabooga/text-generation-webui#3342]
### Describe the bug

My Oobabooga setup works very well, and I'm getting over 15 Tokens Per Second replies from my 33b LLM. However, when using the API and sending back-to-back posts, after 70 to 80, it crashes with the below error.

I've read the Low VRAM Tutorial and every post mentioning CUDA I could find, and tried dozens of combinations of settings. Without deepspeed it crashes between 50 and 60 API calls, with deepspeed I get a little further.

Hardware Specs
`
Nvidia A40 w/ 48GB VRAM
(the model is only 16GB)

Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 48 bits 
  
CPU(s):                  72
Intel(R) Xeon(R) CPU E5-2697 v4 @2.30GHz
    CPU family:          6
    Model:               79
    Thread(s) per core:  2
    Core(s) per socket:  18
    Socket(s):           2
    Stepping:            1
    CPU max MHz:         3600.0000
    CPU min MHz:         1200.0000
    
RAM
256GB DDR4
`

Here's my launch script for what gets me the furthest before a crash. Please note, the model is stored on a 1TB NVME, and the nvme offload is another 1TB NVME.
```
#!/bin/bash
export PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.8,max_split_size_mb:128M
cd text-generation-webui
deepspeed --num_gpus=1 server.py \
--deepspeed \
--chat --model-dir "/Data1/models/" \
--threads 72 \
--listen  \
--listen-port 80 \
--model "TheBloke_Vicuna-33b-1-3-SuperHOT-8K-GPTQ" \
--api \
--auto-devices \
--gpu-memory 46 \
--nvme-offload-dir "/Data2/cache/" \
--loader "ExLlama" \
--trust-remote-code \
--no-cache
```

And here's the error:
```
Traceback (most recent call last):
  File "/home/zino/oobabooga/text-generation-webui/modules/text_generation.py", line 331, in generate_reply_custom
    for reply in shared.model.generate_with_streaming(question, state):
  File "/home/zino/oobabooga/text-generation-webui/modules/exllama.py", line 102, in generate_with_streaming
    token = self.generator.gen_single_token()
  File "/home/zino/oobabooga/installer_files/env/lib/python3.10/site-packages/exllama/generator.py", line 326, in gen_single_token
    logits = self.model.forward(self.sequence[:, -1:], self.cache, lora = self.lora)
  File "/home/zino/oobabooga/installer_files/env/lib/python3.10/site-packages/exllama/model.py", line 887, in forward
    r = self._forward(input_ids[:, chunk_begin : chunk_end],
  File "/home/zino/oobabooga/installer_files/env/lib/python3.10/site-packages/exllama/model.py", line 968, in _forward
    hidden_states = decoder_layer.forward(hidden_states, cache, buffers[device], lora)
  File "/home/zino/oobabooga/installer_files/env/lib/python3.10/site-packages/exllama/model.py", line 465, in forward
    self.self_attn.fused(hidden_states, cache, buffer, self.input_layernorm, lora)
  File "/home/zino/oobabooga/installer_files/env/lib/python3.10/site-packages/exllama/model.py", line 349, in fused
    key_states = cache.key_states[self.index].narrow(2, 0, past_len + q_len)
RuntimeError: start (0) + length (8193) exceeds dimension size (8192).
Output generated in 134.41 seconds (14.48 tokens/s, 1946 tokens, context 7299, seed 1525600403)
149.28.86.6 - - [28/Jul/2023 00:11:03] "POST /api/v1/chat HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('149.28.86.6', 32836)
Traceback (most recent call last):
  File "/home/zino/oobabooga/installer_files/env/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/zino/oobabooga/installer_files/env/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/zino/oobabooga/installer_files/env/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/home/zino/oobabooga/installer_files/env/lib/python3.10/http/server.py", line 433, in handle
    self.handle_one_request()
  File "/home/zino/oobabooga/installer_files/env/lib/python3.10/http/server.py", line 421, in handle_one_request
    method()
  File "/home/zino/oobabooga/text-generation-webui/extensions/api/blocking_api.py", line 85, in do_POST
    for a in generator:
  File "/home/zino/oobabooga/text-generation-webui/modules/chat.py", line 290, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "/home/zino/oobabooga/text-generation-webui/modules/chat.py", line 214, in chatbot_wrapper
    for j, reply in enumerate(generate_reply(prompt + cumulative_reply, state, stopping_strings=stopping_strings, is_chat=True)):
  File "/home/zino/oobabooga/text-generation-webui/modules/text_generation.py", line 28, in generate_reply
    for result in _generate_reply(*args, **kwargs):
  File "/home/zino/oobabooga/text-generation-webui/modules/text_generation.py", line 206, in _generate_reply
    clear_torch_cache()
  File "/home/zino/oobabooga/text-generation-webui/modules/models.py", line 358, in clear_torch_cache
    torch.cuda.empty_cache()
  File "/home/zino/oobabooga/installer_files/env/lib/python3.10/site-packages/torch/cuda/memory.py", line 133, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

I would greatly appreciate it if anyone can point me in the right direction. I'm running out of things to try.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Clean install on Ubuntu 22.04 LTS
apt update
apt upgrade
install Oobabooga with start_linux.sh
install microconda
activate the venv
download the listed model
run the start script above 

### Logs

```shell
see above
```

### System Info

```shell
Ubuntu 22.04 LTS
72 CPU Cores
256GB DDR4 RAM
```

**Comment by ImpossibleExchange** [comment]
Think I had a similar issue to this and what I did to correct this was turning off optimizations (GPU accelerations). I was using firefox, had switched over to a Deb based distro as ARCH was giving me constant headaches. Let me know if this helps or not.

**Comment by krypterro** [comment]
I'm not sure which optimizations you're referring to, all I have enabled is what you see above.

**Comment by ImpossibleExchange** [comment]
> I'm not sure which optimizations you're referring to, all I have enabled is what you see above.

I can't guess your web browser, but when I was running FF, and had optimizations turned on(GPU acceleration or something to that effect) I believe I had the same error until I turned them off.

**Comment by krypterro** [comment]
There isn't a web browser involved. I'm using a Python application from a server, to post API calls to the API interface.

**Comment by ImpossibleExchange** [comment]
> There isn't a web browser involved. I'm using a Python application from a server, to post API calls to the API interface.

Welp dunno what to tell you then, I had browser optimizations accessing  the gpu and cause a similar issue, so if no browser running, guess I'm no help. Best of luck.

**Comment by epolewski** [comment]
> RuntimeError: start (0) + length (8193) exceeds dimension size (8192).

I'm not seeing a deepspeed option to truncate the tokens. Are you running over the max length?

**Comment by krypterro** [comment]
I wiped the install, removed CUDA, reinstalled CUDA, reinstalled the latest Oobabooga, and switched to a new 70b GPTQ version of Llama-2, and it's working great. I suspect I had a mismatched driver version.
