### ISSUE TITLE
Failed building wheel for llama-cpp-python

### ISSUE THREAD

**Issue by saikumar1182** [oobabooga/text-generation-webui#3346]
### Describe the bug

ERROR: Failed building wheel for llama-cpp-python

even i tried updating these 
CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python --no-cache-dir

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Have a linux system using gcc 11

### Logs

```shell
Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [126 lines of output]
      
      
      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      Not searching for unused variables given on the command line.
      
      -- The C compiler identification is GNU 7.3.1
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 7.3.1
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (0.4s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-3qrks36b/llama-cpp-python_bc42199e531a4b35b4b9296532c95eca/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - success
      --------------------------------------------------------------------------------
      
      Configuring Project
        Working directory:
          /tmp/pip-install-3qrks36b/llama-cpp-python_bc42199e531a4b35b4b9296532c95eca/_skbuild/linux-x86_64-3.10/cmake-build
        Command:
          /tmp/pip-build-env-avkr2q3b/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake /tmp/pip-install-3qrks36b/llama-cpp-python_bc42199e531a4b35b4b9296532c95eca -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-avkr2q3b/overlay/lib/python3.10/site-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-3qrks36b/llama-cpp-python_bc42199e531a4b35b4b9296532c95eca/_skbuild/linux-x86_64-3.10/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.9 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-avkr2q3b/overlay/lib/python3.10/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/opt/conda/envs/tg/bin/python3.10 -DPYTHON_INCLUDE_DIR:PATH=/opt/conda/envs/tg/include/python3.10 -DPYTHON_LIBRARY:PATH=/opt/conda/envs/tg/lib/libpython3.10.so -DPython_EXECUTABLE:PATH=/opt/conda/envs/tg/bin/python3.10 -DPython_ROOT_DIR:PATH=/opt/conda/envs/tg -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/opt/conda/envs/tg/include/python3.10 -DPython3_EXECUTABLE:PATH=/opt/conda/envs/tg/bin/python3.10 -DPython3_ROOT_DIR:PATH=/opt/conda/envs/tg -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/opt/conda/envs/tg/include/python3.10 -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-avkr2q3b/overlay/lib/python3.10/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release
      
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 7.3.1
      -- The CXX compiler identification is GNU 7.3.1
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (0.4s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-3qrks36b/llama-cpp-python_bc42199e531a4b35b4b9296532c95eca/_skbuild/linux-x86_64-3.10/cmake-build
      [1/2] Generating /tmp/pip-install-3qrks36b/llama-cpp-python_bc42199e531a4b35b4b9296532c95eca/vendor/llama.cpp/libllama.so
      FAILED: /tmp/pip-install-3qrks36b/llama-cpp-python_bc42199e531a4b35b4b9296532c95eca/vendor/llama.cpp/libllama.so
      cd /tmp/pip-install-3qrks36b/llama-cpp-python_bc42199e531a4b35b4b9296532c95eca/vendor/llama.cpp && make libllama.so
      I llama.cpp build info:
      I UNAME_S:  Linux
      I UNAME_P:  x86_64
      I UNAME_M:  x86_64
      I CFLAGS:   -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS
      I CXXFLAGS: -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS
      I LDFLAGS:
      I CC:       cc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-15)
      I CXX:      g++ (GCC) 11.1.0
      
      g++ -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS -c llama.cpp -o llama.o
      cc  -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS   -c ggml.c -o ggml.o
      cc -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS   -c -o k_quants.o k_quants.c
      k_quants.c: In function ‘ggml_vec_dot_q2_K_q8_K’:
      k_quants.c:1356:36: warning: implicit declaration of function ‘_mm256_set_m128i’; did you mean ‘_mm256_set_epi8’? [-Wimplicit-function-declaration]
               const __m256i scales[2] = {_mm256_set_m128i(l_scales, l_scales), _mm256_set_m128i(h_scales, h_scales)};
                                          ^~~~~~~~~~~~~~~~
                                          _mm256_set_epi8
      k_quants.c:1356:35: warning: missing braces around initializer [-Wmissing-braces]
               const __m256i scales[2] = {_mm256_set_m128i(l_scales, l_scales), _mm256_set_m128i(h_scales, h_scales)};
                                         ^
                                          {                                                                         }
      k_quants.c: In function ‘ggml_vec_dot_q3_K_q8_K’:
      k_quants.c:1864:35: warning: missing braces around initializer [-Wmissing-braces]
               const __m256i scales[2] = {_mm256_set_m128i(l_scales, l_scales), _mm256_set_m128i(h_scales, h_scales)};
                                         ^
                                          {                                                                         }
      k_quants.c: In function ‘ggml_vec_dot_q4_K_q8_K’:
      k_quants.c:2480:32: error: incompatible types when initializing type ‘__m256i {aka const __vector(4) long long int}’ using type ‘int’
               const __m256i scales = _mm256_set_m128i(sc128, sc128);
                                      ^~~~~~~~~~~~~~~~
      k_quants.c: In function ‘ggml_vec_dot_q5_K_q8_K’:
      k_quants.c:2966:32: error: incompatible types when initializing type ‘__m256i {aka const __vector(4) long long int}’ using type ‘int’
               const __m256i scales = _mm256_set_m128i(sc128, sc128);
                                      ^~~~~~~~~~~~~~~~
      make: *** [k_quants.o] Error 1
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/tmp/pip-build-env-avkr2q3b/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 674, in setup
          cmkr.make(make_args, install_target=cmake_install_target, env=env)
        File "/tmp/pip-build-env-avkr2q3b/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 697, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
        File "/tmp/pip-build-env-avkr2q3b/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 742, in make_impl
          raise SKBuildError(msg)
      
      An error occurred while building with CMake.
        Command:
          /tmp/pip-build-env-avkr2q3b/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake --build . --target install --config Release --
        Install target:
          install
        Source directory:
          /tmp/pip-install-3qrks36b/llama-cpp-python_bc42199e531a4b35b4b9296532c95eca
        Working directory:
          /tmp/pip-install-3qrks36b/llama-cpp-python_bc42199e531a4b35b4b9296532c95eca/_skbuild/linux-x86_64-3.10/cmake-build
      Please check the install target is valid and see CMake's output for more information.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
  Building wheel for peft (pyproject.toml) ... done
  Created wheel for peft: filename=peft-0.5.0.dev0-py3-none-any.whl size=73132 sha256=3f415fced3d758aed78bff5a2808182567acd1178bab54828d243ca2dab9f57e
  Stored in directory: /home/ec2-user/.cache/pip/wheels/ff/57/c1/a023c490307cd8ffa3b61c86c48d9767f0bb850053af18674b
Successfully built peft
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
```

### System Info

```shell
OS: amzn2.x86_64
GPU: NVIDIA-SMI 525.85.12
```

**Comment by ClockLoop** [comment]
https://github.com/oobabooga/text-generation-webui/issues/1534#issuecomment-1590614539

Debian just updated (today) something related to c in apt i think and then an hour later I noticed this same error.
I ran 
~/conda install -c conda-forge cxx-compiler , and then ran the upgrader again.
~/pip install -r requirements.txt --upgrade
then run your server..
~/python server.py

**Comment by ClockLoop** [comment]
I just deleted all miniconda, conda, anaconda3 folders, removed all conda/variant entries from .bashrc, cleared cache using bleachbit, restarted, installed the oobabooga all in one installer from the download again, it did everything, installed conda and it all works now.
The installer apparently doesn't even need a local install of conda, its all in the oobabooga folder.  :D  But I don't use conda for anything so...

**Comment by jllllll** [comment]
llama-cpp-python with cuBLAS is included in the webui's requirements.txt as a separate package and will be used by default when CUDA is detected.

As for the error, I would guess that your GCC version is not fully at the right version. Log shows `g++` at 11.1.0 and `cc` at 7.3.1.
`cc` needs to be at least 8 to my understanding.

**Comment by calculuscalculus** [comment]
I have the same error. did you manage to solve it?

**Comment by RobViren** [comment]
Had same issue come up on mine. Had to install g++ specifically to make it work on my Ubuntu based distro. So apt install g++ or use whatever package manager you use to install g++-11 tools and it should work.

**Comment by afoland** [comment]
I had exactly the same problem with building llama on a fresh install of Linux Mint 21.2

Installed cuda, still didn't build

Did RobViren's apt install g++ and then everything builds without error

**Comment by dancingmadkefka** [comment]
can confirm that installing G++ fixes this, thank you to the commenters.
