### ISSUE TITLE
Add support for ggllm.cpp

### ISSUE THREAD

**Issue by djmaze** [oobabooga/text-generation-webui#3357]
Falcon is one of the very few good multilingual models. Support for the Falcon family models (7b / 40b) in text-generation-webui is currently very limited (4 bit only, bad performance) through AutoGPTQ. Also it needs [at least 35 GB of VRAM](https://huggingface.co/TheBloke/falcon-40b-instruct-GPTQ). 

[ggllm.cpp](https://github.com/cmp-nct/ggllm.cpp) is optimized for running quantized versions of those models and runs much faster. Also, it supports [down to 2 bit quantized versions](https://huggingface.co/TheBloke/falcon-40b-sft-mix-1226-GGML), which allows using the 40b model on a single 24 GB GPU.

**Comment by Flanua** [comment]
Just my two cents: I personally don't recommend to down anything to 2 bits lower than 8 bits. The AI model degrades significantly.

**Comment by jllllll** [comment]
Not technically a duplicate, but close enough to: https://github.com/oobabooga/text-generation-webui/issues/3351

CTransformers is what would be used if ggllm.cpp were to be integrated.

**Comment by djmaze** [comment]
> Just my two cents: I personally don't recommend to down anything to 2 bits lower than 8 bits. The AI model degrades significantly.

Not sure I understood you correctly. I am using the 3-bit quantized version (`GGML_TYPE_Q3_K`) of the linked model with ggllm.cpp and AFAICS it works really good. Especially when using German, I did not find a better a better model yet.

**Comment by jllllll** [comment]
3bit is worth using only on the larger model sizes where it makes less of a difference. 30B+. It does lower output quality significantly, but is still worth using if it allows you to use a larger model. 2bit is pretty much useless though.

**Comment by goodglitch** [comment]
> > Just my two cents: I personally don't recommend to down anything to 2 bits lower than 8 bits. The AI model degrades significantly.
> 
> Not sure I understood you correctly. I am using the 3-bit quantized version (`GGML_TYPE_Q3_K`) of the linked model with ggllm.cpp and AFAICS it works really well. Especially when using German, I did not find a better a better model yet.

Try 2bit model with moderate difficulty coding task and you will see what he is talking about. Anything that requires precision is out of question. It is good that for your use case a lower quantization still produces output that makes sense.

**Comment by oobabooga** [comment]
ctransformers is on my radar, I'll merge one of the open PRs adding support soon. It's always a challenge to add new backends because they usually don't come with precompiled wheels.

**Comment by jllllll** [comment]
> ctransformers is on my radar, I'll merge one of the open PRs adding support soon. It's always a challenge to add new backends because they usually don't come with precompiled wheels.

I'm currently in the process of building pre-compiled wheels for CUDA 11.7.
ctransformers has a wheel for CUDA 12.1, but that isn't particularly useful for us as we use CUDA 11.7.

**Comment by oobabooga** [comment]
That's very nice to hear @jllllll.

**Comment by jllllll** [comment]
> That's very nice to hear @jllllll.
```
https://github.com/jllllll/ctransformers-cuBLAS-wheels/releases/download/AVX2/ctransformers-0.2.16+cu117-py3-none-any.whl
```
This wheel includes CUDA binaries for both Windows and Linux. MacOS is also supported through non-CUDA binaries.

**Comment by jllllll** [comment]
`ctransformers` has been implemented, which includes `ggllm.cpp`.

It should work.

**Comment by augchan42** [comment]
Still doesn't work for me, I'm on Macbook Pro M2 Max (Apple Silicon):
pip3 install -r requirements.txt output:

Installing collected packages: ctransformers
  Attempting uninstall: ctransformers
    Found existing installation: ctransformers 0.2.27
    Uninstalling ctransformers-0.2.27:
      Successfully uninstalled ctransformers-0.2.27
Successfully installed ctransformers-0.2.27+cu121
(venv) auchan@Augustins-MBP text-generation-webui % 

Then when trying to load the model after restarting the server:
2023-12-05 09:43:16 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/Users/auchan/projects/text-generation-webui/modules/ui_model_menu.py", line 209, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/auchan/projects/text-generation-webui/modules/models.py", line 85, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/auchan/projects/text-generation-webui/modules/models.py", line 280, in ctransformers_loader
    from modules.ctransformers_model import CtransformersModel
  File "/Users/auchan/projects/text-generation-webui/modules/ctransformers_model.py", line 1, in <module>
    from ctransformers import AutoConfig, AutoModelForCausalLM
ModuleNotFoundError: No module named 'ctransformers'

**Comment by augchan42** [comment]
Might be because it's tied to AVX2
Collecting ctransformers==0.2.27+cu121 (from -r requirements.txt (line 88))
  Downloading https://github.com/jllllll/ctransformers-cuBLAS-wheels/releases/download/**AVX2**/ctransformers-0.2.27+cu121-py3-none-any.whl (15.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.5/15.5 MB 12.2 MB/s eta 0:00:00
