### ISSUE TITLE
Any way to disable fused attention when loading via exllama?

### ISSUE THREAD

**Issue by practicaldreamer** [oobabooga/text-generation-webui#3359]
### Describe the bug

Trying to apply QLoRA that was trained with fused attention disabled.

I see "no_inject_fused_attention" and can verify it works with AUTOGPTQ but it's not as fast or VRAM efficient as exllama. 

Is there any way to disable fused attention when using the exllama loader?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

N/A

### Logs

```shell
Traceback (most recent call last):
  File "/home/user/Documents/practicaldreamer/text-generation-webui/server.py", line 66, in load_model_wrapper
    unload_model()
  File "/home/user/Documents/practicaldreamer/text-generation-webui/modules/models.py", line 338, in unload_model
    clear_torch_cache()
  File "/home/user/Documents/practicaldreamer/text-generation-webui/modules/models.py", line 331, in clear_torch_cache
    torch.cuda.empty_cache()
  File "/home/user/.local/lib/python3.10/site-packages/torch/cuda/memory.py", line 133, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### System Info

```shell
5600X
2x3090
```

**Comment by Ph0rk0z** [comment]
It is off in exllama_hf. Also you can just edit the file.

**Comment by practicaldreamer** [comment]
Thanks I found a commented out line at the bottom of exllama_hf.py that says “config.fuse_attn=False” and I UN-commented it out
