### ISSUE TITLE
Windows Oobabooga WebUI, torch.cuda.OutOfMemoryError: CUDA out of memory

### ISSUE THREAD

**Issue by u431535** [oobabooga/text-generation-webui#3379]
### Describe the bug

Load "Llama-2-7b-chat-hf" show the error:   File "D:\Install\Oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 6.00 GiB total capacity; 5.28 GiB already allocated; 0 bytes free; 5.29 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Installed : okay
2. run start_windows.bat: okay
3. Chrome browser connect to http://127.0.0.1:7860. the WebUI screen okay
4. Load Model: Llama-2-7b-chat-hf, the system show errors.

### Logs

```shell
(D:\Install\Oobabooga\oobabooga_windows\installer_files\env) D:\Install\Oobabooga\oobabooga_windows>start_windows --gpu-memory 6
bin D:\Install\Oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
2023-07-31 14:51:25 INFO:Loading the extension "gallery"...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
2023-07-31 14:51:58 INFO:Loading Llama-2-7b-chat-hf...
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.69it/s]
2023-07-31 14:52:08 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "D:\Install\Oobabooga\oobabooga_windows\text-generation-webui\server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "D:\Install\Oobabooga\oobabooga_windows\text-generation-webui\modules\models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "D:\Install\Oobabooga\oobabooga_windows\text-generation-webui\modules\models.py", line 163, in huggingface_loader
    model = model.cuda()
  File "D:\Install\Oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "D:\Install\Oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "D:\Install\Oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "D:\Install\Oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "D:\Install\Oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "D:\Install\Oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 6.00 GiB total capacity; 5.28 GiB already allocated; 0 bytes free; 5.29 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### System Info

```shell
1. OS: Windows 11 Pro (21H2)
2. CPU: 12th Gen Intel(R) Core(TM) i9-12900H   2.50 GHz
3. RAM: 16GB
4. GPU: RTX 3060 Laptop
```

**Comment by ImpossibleExchange** [comment]
Doesn't look like a bug. It looks like you are running out of Vram.  Windows or something else running in the background  is likely taking up some of your vram.  I guess you could try running off the CPU on that system but it is going to be slow relative to running off a GPU.

**Comment by Flanua** [comment]
Easy fix is to lower pre layers numbers. Put this: (--pre_layer 18) into your webui.py file. And feel free to increase the pre layer according to your GPU vram.

![Screenshot 2023-07-27 005327](https://github.com/oobabooga/text-generation-webui/assets/140022879/9b57f64d-143f-4bb2-8be4-5b3663120ca1)

**Comment by jllllll** [comment]
You are attempting to load an unquantized HF model with 6gb of VRAM. This simply isn't going to work. You can enable `auto-devices` to try to offload most of the model to RAM, but you are far better off using a 4bit GGML version of the model:
https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML/resolve/main/llama-2-7b-chat.ggmlv3.q4_K_S.bin
