### ISSUE TITLE
Failed to load the model

### ISSUE THREAD

**Issue by Antwa-sensei253** [oobabooga/text-generation-webui#3399]
### Describe the bug

Traceback (most recent call last): File “C:\Users\king\Documents\oobabooga_windows\text-generation-webui\[server.py](http://server.py/)”, line 68, in load_model_wrapper shared.model, shared.tokenizer = load_model(shared.model_name, loader) File “C:\Users\king\Documents\oobabooga_windows\text-generation-webui\modules\[models.py](http://models.py/)”, line 78, in load_model output = load_func_map[loader](http://127.0.0.1:7860/model_name) File “C:\Users\king\Documents\oobabooga_windows\text-generation-webui\modules\[models.py](http://models.py/)”, line 241, in llamacpp_loader model, tokenizer = LlamaCppModel.from_pretrained(model_file) File “C:\Users\king\Documents\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py”, line 60, in from_pretrained result.model = Llama(**params) File “C:\Users\king\Documents\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp\[llama.py](http://llama.py/)”, line 314, in init assert self.model is not None AssertionError

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1-have windows 10
2-get an Rx 750 GPU
1-download the one-click install for windows
2-download the model
3-put the model inside the models folder
4-launch the start_windows script
5-open  the local host webUI in browser
6-load the model
7-get the error

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/101470839/0b956c16-d33a-4218-aa16-cdbcc9cb19d7)
![image](https://github.com/oobabooga/text-generation-webui/assets/101470839/ae6e51c0-29ce-4e72-8f27-8ec0a05a74cb)

### Logs

```shell
2023-08-01 22:15:45 INFO:Loading TheBloke_Wizard-Vicuna-13B-Uncensored-GGML...
2023-08-01 22:15:45 INFO:llama.cpp weights detected: models\TheBloke_Wizard-Vicuna-13B-Uncensored-GGML\Wizard-Vicuna-13B-Uncensored.ggmlv3.q2_K.bin

2023-08-01 22:15:45 INFO:Cache capacity is 0 bytes
Model Path: models\TheBloke_Wizard-Vicuna-13B-Uncensored-GGML\Wizard-Vicuna-13B-Uncensored.ggmlv3.q2_K.bin
llama.cpp: loading model from models\TheBloke_Wizard-Vicuna-13B-Uncensored-GGML\Wizard-Vicuna-13B-Uncensored.ggmlv3.q2_K.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_head_kv  = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: n_gqa      = 1
llama_model_load_internal: rnorm_eps  = 1.0e-06
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 10 (mostly Q2_K)
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.06 MB
error loading model: llama.cpp: tensor 'layers.21.ffn_norm.weight' is missing from model
llama_load_model_from_file: failed to load model
2023-08-01 22:15:45 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "C:\Users\king\Documents\oobabooga_windows\text-generation-webui\server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "C:\Users\king\Documents\oobabooga_windows\text-generation-webui\modules\models.py", line 78, in load_model
    output = load_func_map[loader](model_name)
  File "C:\Users\king\Documents\oobabooga_windows\text-generation-webui\modules\models.py", line 241, in llamacpp_loader    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
  File "C:\Users\king\Documents\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 60, in from_pretrained
    result.model = Llama(**params)
  File "C:\Users\king\Documents\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 314, in __init__
    assert self.model is not None
AssertionError

Exception ignored in: <function Llama.__del__ at 0x000002148FDF70A0>
Traceback (most recent call last):
  File "C:\Users\king\Documents\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 1511, in __del__
    if self.ctx is not None:
AttributeError: 'Llama' object has no attribute 'ctx'
Exception ignored in: <function LlamaCppModel.__del__ at 0x000002148FA360E0>
Traceback (most recent call last):
  File "C:\Users\king\Documents\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 29, in __del__
    self.model.__del__()
AttributeError: 'LlamaCppModel' object has no attribute 'model'
```

### System Info

```shell
windows 10
Ryzen 5 5600g CPU
Rx 750 SAPPHIRE GPU
16 gb of ram 
600 wat power supply
```

**Comment by Fusseldieb** [comment]
> "put the model inside the models folder"

Instead, try to download it using the tab Model > "Download custom model or lora"

![image](https://github.com/oobabooga/text-generation-webui/assets/4715129/424c4c26-2bdb-4714-ae2f-599a87eaf6bd)

![image](https://github.com/oobabooga/text-generation-webui/assets/4715129/2cf5ead1-18fd-43cf-8bd1-88a3db20f753)

Do not include the complete URL, as shown.

**Comment by Antwa-sensei253** [comment]
I redownload it again, and the problem is solved
