### ISSUE TITLE
Error when trying to start with multimodel extension

### ISSUE THREAD

**Issue by AvisP** [oobabooga/text-generation-webui#3401]
### Describe the bug

Everything is working properly when I am working with the normal interface without the `multimodal` extension. But when I go to session and check the multimodal and do a `Apply and restart` then it gives an error regarding shared.model

I tried to debug and I found that the shared.args.model is empty which is why this is happening. I have confirmed I have models folder in the model_dir.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Start the ui with `python server.py` and then go to Sessions tab and select `multimodal` and do a `Apply and Restart` and the error message will show up in the terminal.

### Logs

```shell
Exception has occurred: AttributeError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
'NoneType' object has no attribute 'lower'
  File "/Users/paula/Desktop/Projects/text-generation-webui/extensions/multimodal/pipeline_loader.py", line 34, in load_pipeline
    model_name = shared.args.model.lower()
  File "/Users/paula/Desktop/Projects/text-generation-webui/extensions/multimodal/multimodal_embedder.py", line 27, in __init__
    pipeline, source = load_pipeline(params)
  File "/Users/paula/Desktop/Projects/text-generation-webui/extensions/multimodal/script.py", line 98, in ui
    multimodal_embedder = MultimodalEmbedder(params)
  File "/Users/paula/Desktop/Projects/text-generation-webui/modules/extensions.py", line 175, in create_extensions_block
    extension.ui()
  File "/Users/paula/Desktop/Projects/text-generation-webui/server.py", line 1086, in create_interface
    extensions_module.create_extensions_block()
  File "/Users/paula/Desktop/Projects/text-generation-webui/server.py", line 1187, in <module>
    create_interface()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main (Current frame)
    return _run_code(code, main_globals, None,
AttributeError: 'NoneType' object has no attribute 'lower'
```
```


### System Info

```shell
Operating system : Mac OS X
GPU Brand : M1
No google colab notebook
```

**Comment by AvisP** [comment]
I realized that I was supposed to start by specifying commands as mentioned in the multimodal extensions page git repo https://github.com/oobabooga/text-generation-webui/tree/main/extensions/multimodal I noted that `auto_gptq` doesn't work on Mac M1 yet so I couldn't manage to run in the end and had this error message

```
Traceback (most recent call last):
  File "/Users/paula/Desktop/Projects/text-generation-webui/server.py", line 1172, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/Users/paula/Desktop/Projects/text-generation-webui/modules/models.py", line 78, in load_model
    output = load_func_map[loader](model_name)
  File "/Users/paula/Desktop/Projects/text-generation-webui/modules/models.py", line 285, in AutoGPTQ_loader
    import modules.AutoGPTQ_loader
  File "/Users/paula/Desktop/Projects/text-generation-webui/modules/AutoGPTQ_loader.py", line 3, in <module>
    from auto_gptq import AutoGPTQForCausalLM, BaseQuantizeConfig
ModuleNotFoundError: No module named 'auto_gptq'
```

The issue can be deleted/closed.
