### ISSUE TITLE
Can't run llama2-13b-chat anymore

### ISSUE THREAD

**Issue by BadisG** [oobabooga/text-generation-webui#3420]
### Describe the bug

Hey,

I can't do generations on llama2-13b-chat anymore, I got an error now. I think that's the only model that has this, the other llama1 and llama2 finetunes work fine tho.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run llama2-13b-chat with exllama_hf loader

### Logs

```shell
2023-08-02 19:57:38 INFO:Loading Llama-2-13B-chat-GPTQ...
2023-08-02 19:57:43 WARNING:models\Llama-2-13B-chat-GPTQ\tokenizer_config.json is different from the original LlamaTokenizer file. It is either customized or outdated.
2023-08-02 19:57:43 WARNING:models\Llama-2-13B-chat-GPTQ\special_tokens_map.json is different from the original LlamaTokenizer file. It is either customized or outdated.
2023-08-02 19:57:43 INFO:Loaded the model in 5.63 seconds.

Traceback (most recent call last):
  File "D:\Large-Language-Models\text-generation-webui\modules\callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "D:\Large-Language-Models\text-generation-webui\modules\text_generation.py", line 295, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Users\Utilisateur\anaconda3\envs\textgen\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Utilisateur\anaconda3\envs\textgen\lib\site-packages\transformers\generation\utils.py", line 1335, in generate
    and torch.sum(inputs_tensor[:, -1] == generation_config.pad_token_id) > 0
IndexError: index -1 is out of bounds for dimension 1 with size 0
Output generated in 0.37 seconds (0.00 tokens/s, 0 tokens, context 0, seed 412999398)
```

### System Info

```shell
Windows 10
exllama_hf
```

**Comment by BadisG** [comment]
All right, I seem to have got it working again by simply creating a new folder and putting the files on it...
