### ISSUE TITLE
Gradio issues on WSL2 & Windows

### ISSUE THREAD

**Issue by ghost** [oobabooga/text-generation-webui#3421]
### Describe the bug

Elements of the UI load either painfully slow, or don't load at all producing errors.

Tested over multiple reinstallations, on both WSL2 manual conda install and Windows one-click.

These are the kind of errors I got on Windows:

![image](https://github.com/oobabooga/text-generation-webui/assets/101902000/340d04c2-0b1c-4dcd-8263-cc8881433b39)

This is how it looks in the UI:

![image](https://github.com/oobabooga/text-generation-webui/assets/101902000/ba037325-83dd-4006-839c-235902cda709)

Don't have issues with any other software or UI, including Stable Diffusion WebUI

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I run the server and the issue happens almost immediately as soon as I open the web page.
In some cases the issue doesn't present immediately, but can be reliably triggered by going to "models" and changing model loader.

### Logs

```shell
2023-08-02 20:24:29 ERROR:Task exception was never retrieved
future: <Task finished name='6afpo3bjrvl_169' coro=<Queue.process_events() done, defined at C:\ProgramData\Text-Generation-WebUI\installer_files\env\lib\site-packages\gradio\queueing.py:343> exception=WebSocketDisconnect(1006)>
Traceback (most recent call last):
  File "C:\ProgramData\Text-Generation-WebUI\installer_files\env\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "C:\ProgramData\Text-Generation-WebUI\installer_files\env\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "C:\ProgramData\Text-Generation-WebUI\installer_files\env\lib\site-packages\gradio\queueing.py", line 453, in get_message
    data = await asyncio.wait_for(
  File "C:\ProgramData\Text-Generation-WebUI\installer_files\env\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\ProgramData\Text-Generation-WebUI\installer_files\env\lib\site-packages\starlette\websockets.py", line 133, in receive_json
    self._raise_on_disconnect(message)
  File "C:\ProgramData\Text-Generation-WebUI\installer_files\env\lib\site-packages\starlette\websockets.py", line 105, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1006
```

### System Info

```shell
Ryzen 5900X, RTX 3060, 64GB RAM
```

**Comment by enterplasma** [comment]
Errors persist after full Windows reinstall
