### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by mzubairumt** [oobabooga/text-generation-webui#3429]
### Describe the bug

AssertionError: Torch not compiled with CUDA enabled

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

AssertionError: Torch not compiled with CUDA enabled

### Screenshot

AssertionError: Torch not compiled with CUDA enabled

### Logs

```shell
2023-08-03 14:35:12 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "C:\llama\text-generation-webui\server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "C:\llama\text-generation-webui\modules\models.py", line 78, in load_model
    output = load_func_map[loader](model_name)
  File "C:\llama\text-generation-webui\modules\models.py", line 153, in huggingface_loader
    model = model.cuda()
  File "C:\Users\muhammad.zubair\AppData\Local\miniconda3\envs\textgen\lib\site-packages\torch\nn\modules\module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\muhammad.zubair\AppData\Local\miniconda3\envs\textgen\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\muhammad.zubair\AppData\Local\miniconda3\envs\textgen\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\muhammad.zubair\AppData\Local\miniconda3\envs\textgen\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Users\muhammad.zubair\AppData\Local\miniconda3\envs\textgen\lib\site-packages\torch\nn\modules\module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\muhammad.zubair\AppData\Local\miniconda3\envs\textgen\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
```

### System Info

```shell
11th gen intal core i7 with 32GB RAM
```

**Comment by Davidlazer18** [comment]
i also have a same problem, which only happens to me whenever i tried to load my own trained chat model but when i load the default model it works..

**Comment by CircuitGuy** [comment]
Duplicate of #1394

**Comment by sammcj** [comment]
This bug report requires more information.

- What model and model format are you trying to load?
- What kind of nvidia GPU are you trying to use with it?
- What settings are you trying to load it with?

etc...

For general support I'd suggest either:

- Subreddit: https://www.reddit.com/r/oobabooga/
- Discord: https://discord.gg/jwZCF2dPQN
