### ISSUE TITLE
ModuleNotFoundError: No module named 'markdown'

### ISSUE THREAD

**Issue by jurandfantom** [oobabooga/text-generation-webui#343]
### Describe the bug

It start appearing right after update gui. Reinstall requirements not help or "pip install markdown".

Only mentioned topic about markdown, not bring idea about solution.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Update with cmd "git pull"

### Screenshot

![23,03,15 - 17,49,58 - 7415 a](https://user-images.githubusercontent.com/30580568/225452544-01bd2af9-b29d-4a98-871b-10fa7e36a933.png)

### Logs

```shell
huh?
```

### System Info

```shell
Windows 10
RTX 4090
```

**Comment by DamonianoStudios** [comment]
I have the same issue, RTX 3090 and just git pulled about 3 minutes ago.

Here is the log

`Traceback (most recent call last):
  File "D:\AI\text-generation-webui\server.py", line 13, in <module>
    import modules.chat as chat
  File "D:\AI\text-generation-webui\modules\chat.py", line 14, in <module>
    from modules.html_generator import generate_chat_html
  File "D:\AI\text-generation-webui\modules\html_generator.py", line 11, in <module>
    import markdown
ModuleNotFoundError: No module named 'markdown'`

**Comment by oobabooga** [comment]
Chat mode now uses markdown. Try this

```
conda activate textgen
pip install -r requirements.txt  --upgrade
```

**Comment by DamonianoStudios** [comment]
That fixed the issue for me, apparently bits and bytes also needed an update (unrelated though), so thank you!
