### ISSUE TITLE
The chat doesn't seem to keep all the previous tokens in memory when a new generation is being made

### ISSUE THREAD

**Issue by BadisG** [oobabooga/text-generation-webui#3458]
### Describe the bug

Hey,

I think the whole text is truncatured when chatting with a bot
![h7lzmf1](https://github.com/oobabooga/text-generation-webui/assets/110173477/d36e1114-f1ff-4c75-8eb7-be467224cbd4)
The context should be increasing, or else the bot quickly forgets what we were talking about

Here's my settings:
![image](https://github.com/oobabooga/text-generation-webui/assets/110173477/9621df2c-fd8b-4cb6-a1d8-5da6668fdb4a)

By the way, when I put another value than 16384 on the truncation length I got this error

```
Traceback (most recent call last):
  File "D:\Large-Language-Models\text-generation-webui\modules\callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "D:\Large-Language-Models\text-generation-webui\modules\text_generation.py", line 294, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Users\Utilisateur\anaconda3\envs\textgen\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Utilisateur\anaconda3\envs\textgen\lib\site-packages\transformers\generation\utils.py", line 1335, in generate
    and torch.sum(inputs_tensor[:, -1] == generation_config.pad_token_id) > 0
IndexError: index -1 is out of bounds for dimension 1 with size 0
Output generated in 0.39 seconds (0.00 tokens/s, 0 tokens, context 0, seed 1870652743)
C:\Users\Utilisateur\anaconda3\envs\textgen\lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\Utilisateur\anaconda3\envs\textgen\lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Use chat
Look at the context for ea

### Logs

```shell
No logs
```

### System Info

```shell
Windows 10
loader: exllama_hf
```

**Comment by BadisG** [comment]
Ok I guess I fixed it by not using custom values on the setings.yaml...
