### ISSUE TITLE
shared.py creating conflicts

### ISSUE THREAD

**Issue by Maverous** [oobabooga/text-generation-webui#3483]
### Describe the bug

After following all the installation directions, I am getting an error with the shared.py file not finding something and its constantly crashing my program. I can't open and use the UI or even get it to work.

I am using my CPU, on Windows 10.

I'm new at using and working with python, and I have no idea what is causing this or how to fix it. I cannot find anything on Git, YouTube, reddit or the internet to help me understand the issue or how to fix it.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Open start_windows.bat

Wait for program to load

### Screenshot

![Screenshot (1013)](https://github.com/oobabooga/text-generation-webui/assets/141048791/a416c0c5-ee50-409c-8a32-7cdd0de00785)

### Logs

```shell
Traceback (most recent call last):
  File "F:\Oobabooga\text-generation-webui\server.py", line 27, in <module>
    import modules.extensions as extensions_module
  File "F:\Oobabooga\text-generation-webui\modules\extensions.py", line 8, in <module>
    import modules.shared as shared
  File "F:\Oobabooga\text-generation-webui\modules\shared.py", line 239, in <module>
    args.loader = fix_loader_name(args.loader)
  File "F:\Oobabooga\text-generation-webui\modules\shared.py", line 202, in fix_loader_name
    name = name.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

### System Info

```shell
AMD Radeon RX 6600 XT GPU
Windows 10 
16GB RAM
8GB VRAM
```

**Comment by staticawesome** [comment]
For now, edit line 205 in the shared.py from:
name = name.lower()

to:
#name = name.lower()

I have no idea what this breaks, if anything, but I'm able to use text generation in my models for now, including API.
