### ISSUE TITLE
How to infer llama2 model in multi-gpu?

### ISSUE THREAD

**Issue by microbenh** [oobabooga/text-generation-webui#3486]
### Describe the bug

I try to load meta-llama/Llama-2-13b-chat-hf model using transformers loader in multi-gpu for inference, loading is success, but inference fails? 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
export CUDA_VISIBLE_DEVICES=0,1
python server.py \
    --model-dir $root/resource/model/meta-llama/ \
    --model Llama-2-13b-chat-hf \
    --auto-devices \
    --model_type LLaMA \
    --loader transformers \
    --gpu-memory 23 23 \
    --listen --listen-host 10.11.0.13 --listen-port 9100
```

### Logs

```shell
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [5,0,0], thread: [61,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [5,0,0], thread: [62,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [5,0,0], thread: [63,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "/data2/u2/nas/code/aigc/LLaMA-Efficient-Tuning/lib/text-generation-webui/modules/callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "/data2/u2/nas/code/aigc/LLaMA-Efficient-Tuning/lib/text-generation-webui/modules/text_generation.py", line 307, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/data2/u2/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data2/u2/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "/data2/u2/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2642, in sample
    outputs = self(
  File "/data2/u2/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/u2/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/data2/u2/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 806, in forward
    outputs = self.model(
  File "/data2/u2/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/u2/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 693, in forward
    layer_outputs = decoder_layer(
  File "/data2/u2/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/u2/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/data2/u2/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 408, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/data2/u2/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/u2/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/data2/u2/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 317, in forward
    query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin, position_ids)
  File "/data2/u2/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 184, in apply_rotary_pos_emb
    cos = cos[position_ids].unsqueeze(1)  # [bs, 1, seq_len, dim]
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### System Info

```shell
ubuntu18.04
4*4090 gpu
```

**Comment by evannorstrand-mp** [comment]
Bumping this as it blocks the ability to do lora training on multiple GPU

**Comment by HuHuanfa1** [comment]
Maximum GPU memory in GiB to be allocated per GPU. Example: --gpu-memory 10 for a single GPU, --gpu-memory 10 5 for two GPUs.

**Comment by vampirismtrueblood** [comment]
I have the same exact issue when loading LLama2 70B in 4-bit across 2 4090s

python  server.py --listen --auto-devices --load-in-4bit --gpu-split 20,20 --gpu-memory 20 20 --verbose --use_fast


`./aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [14,0,0], thread: [91,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [14,0,0], thread: [92,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [14,0,0], thread: [93,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [14,0,0], thread: [94,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [14,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "/nvme_ugreen_usb/QLoRa/text-generation-webui/modules/callbacks.py", line 56, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "/nvme_ugreen_usb/QLoRa/text-generation-webui/modules/text_generation.py", line 347, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/peter/anaconda3/envs/oc12-1/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/peter/anaconda3/envs/oc12-1/lib/python3.10/site-packages/transformers/generation/utils.py", line 1652, in generate
    return self.sample(
  File "/home/peter/anaconda3/envs/oc12-1/lib/python3.10/site-packages/transformers/generation/utils.py", line 2734, in sample
    outputs = self(
  File "/home/peter/anaconda3/envs/oc12-1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/peter/anaconda3/envs/oc12-1/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/peter/anaconda3/envs/oc12-1/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1034, in forward
    outputs = self.model(
  File "/home/peter/anaconda3/envs/oc12-1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/peter/anaconda3/envs/oc12-1/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 921, in forward
    layer_outputs = decoder_layer(
  File "/home/peter/anaconda3/envs/oc12-1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/peter/anaconda3/envs/oc12-1/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/peter/anaconda3/envs/oc12-1/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 631, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/peter/anaconda3/envs/oc12-1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/peter/anaconda3/envs/oc12-1/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/peter/anaconda3/envs/oc12-1/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 361, in forward
    query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin, position_ids)
  File "/home/peter/anaconda3/envs/oc12-1/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 211, in apply_rotary_pos_emb
    cos = cos[position_ids].unsqueeze(1)  # [bs, 1, seq_len, dim]
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception in thread Thread-6 (gentask):
Traceback (most recent call last):
  File "/home/peter/anaconda3/envs/oc12-1/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/peter/anaconda3/envs/oc12-1/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/nvme_ugreen_usb/QLoRa/text-generation-webui/modules/callbacks.py", line 63, in gentask
    clear_torch_cache()
  File "/nvme_ugreen_usb/QLoRa/text-generation-webui/modules/callbacks.py", line 95, in clear_torch_cache
    torch.cuda.empty_cache()
  File "/home/peter/anaconda3/envs/oc12-1/lib/python3.10/site-packages/torch/cuda/memory.py", line 133, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
`
