### ISSUE TITLE
during conversation oom

### ISSUE THREAD

**Issue by elven2016** [oobabooga/text-generation-webui#3493]
### Describe the bug

when i  git  pull to update to the newest version、 every models turns to this issue:  after about serveral conversions it ends with oom

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1、 load the model
2、give a subjet  and make a coversion with the model
3、continue  to  conversation with it
4、after 3_5 times conversions, it is erminated before completed.

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/16677082/7e8ce906-8b89-4a6d-97c2-14ad118aee5c)
![image](https://github.com/oobabooga/text-generation-webui/assets/16677082/49afe783-1951-451f-8828-578c4b685886)

### Logs

```shell
Traceback (most recent call last):
  File "/ssd_data01/text-generation-webui/modules/callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "/ssd_data01/text-generation-webui/modules/text_generation.py", line 307, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/elven/miniconda3/envs/tgweb/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/elven/miniconda3/envs/tgweb/lib/python3.10/site-packages/transformers/generation/utils.py", line 1633, in generate
    return self.sample(
  File "/home/elven/miniconda3/envs/tgweb/lib/python3.10/site-packages/transformers/generation/utils.py", line 2755, in sample
    outputs = self(
  File "/home/elven/miniconda3/envs/tgweb/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/elven/miniconda3/envs/tgweb/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/elven/miniconda3/envs/tgweb/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 810, in forward
    outputs = self.model(
  File "/home/elven/miniconda3/envs/tgweb/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/elven/miniconda3/envs/tgweb/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 698, in forward
    layer_outputs = decoder_layer(
  File "/home/elven/miniconda3/envs/tgweb/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/elven/miniconda3/envs/tgweb/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/elven/miniconda3/envs/tgweb/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 413, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/elven/miniconda3/envs/tgweb/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/elven/miniconda3/envs/tgweb/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/elven/miniconda3/envs/tgweb/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 327, in forward
    value_states = torch.cat([past_key_value[1], value_states], dim=2)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 23.65 GiB total capacity; 12.81 GiB already allocated; 15.19 MiB free; 12.96 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### System Info

```shell
ubunut 22.04
pytorch 2.0.1
python 3.10.10
GPU: 2*4090 24G
```

**Comment by Ph0rk0z** [comment]
Check how you have split the model.

**Comment by elven2016** [comment]
> 
I  used the default newest code of this repo, not make any change ,is there  any advice?
