### ISSUE TITLE
ooba generates suddenly no output anymore

### ISSUE THREAD

**Issue by Woisek** [oobabooga/text-generation-webui#3502]
### Describe the bug

Repo is at the latest, but since a few hours now, ooba produces no response anymore. Many models I have and that worked previously don't work anymore. And those few that work give no output. My message doesn't even show up, it disappears right away.

I have absolutely no clue what happened and why no output is given.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load a functional model and start chat

### Screenshot

![Zwischenablagebild](https://github.com/oobabooga/text-generation-webui/assets/122026301/ae41324c-8e0e-4af5-8594-6bc99fe27361)

### Logs

```shell
2023-08-08 20:09:56 INFO:Loading the extension "long_term_memory"...
2023-08-08 20:09:56 INFO:Loading the extension "gallery"...
Running on local URL:  http://127.0.0.1:7862

To create a public link, set `share=True` in `launch()`.
Output generated in 0.34 seconds (0.00 tokens/s, 0 tokens, context 16, seed 1719872565)
Output generated in 0.31 seconds (0.00 tokens/s, 0 tokens, context 56, seed 835567304)
Closing server running on port: 7862
2023-08-08 20:11:30 INFO:Loading the extension "long_term_memory"...
2023-08-08 20:11:30 INFO:Loading the extension "gallery"...
Running on local URL:  http://127.0.0.1:7862

To create a public link, set `share=True` in `launch()`.
Closing server running on port: 7862
2023-08-08 20:11:52 INFO:Loading the extension "long_term_memory"...
2023-08-08 20:11:52 INFO:Loading the extension "gallery"...
Running on local URL:  http://127.0.0.1:7862

To create a public link, set `share=True` in `launch()`.
============================================================
loading character ella_hurtsome
-----------------------
NEW MEMORY SAVED to LTM
-----------------------
name: Ella Hurtsome
message: Well, we can always talk about it later *she turns her back to you and starts cooking something* Oh look! I made pizza! *She smiles at herself while looking in the kitchen.* Do you want a piece?
-----------------------
Output generated in 0.30 seconds (0.00 tokens/s, 0 tokens, context 1483, seed 1142576874)
============================================================
loading character lily_sinclair
Output generated in 0.30 seconds (0.00 tokens/s, 0 tokens, context 1084, seed 689145657)
```

### System Info

```shell
Windows 10, Nvidia RTX 2070 SUPER 8GB VRAM
```

**Comment by dchatel** [comment]
same here

**Comment by dchatel** [comment]
I fully reinstalled the ui, with a manual conda install, like the first time. Now it works properly.

**Comment by Woisek** [comment]
Update:
I started the install.bat and let it do it's magic. I saw, that a few things where updated. After this process, ooba worked like before. I previously only did an git pull in the text-generation-webui folder but obviously that is not enough to update the whole thing at once. So I guess this is now solved.

**Comment by ErfolgreichCharismatisch** [comment]
> Update: I started the install.bat and let it do it's magic. I saw, that a few things where updated. After this process, ooba worked like before. I previously only did an git pull in the text-generation-webui folder but obviously that is not enough to update the whole thing at once. So I guess this is now solved.

I used update_windows.bat with great success.

**Comment by Woisek** [comment]
> I used update_windows.bat with great success.

Well, I have here only the install.bat and start-webui.bat. But probably it's doing the same. 🙂

**Comment by estilodevida** [comment]
same here:
windows 10 gtx3060 16gb

bin C:\Users\xplus-win\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
Starting streaming server at ws://127.0.0.1:5005/api/v1/stream
2023-08-09 22:05:57 INFO:Loading the extension "gallery"...
Starting API at http://127.0.0.1:7788/api
Running on local URL:  http://127.0.0.1:7777

To create a public link, set `share=True` in `launch()`.
2023-08-09 22:06:49 INFO:Loading conceptofmind_LLongMA-2-13b-16k...
2023-08-09 22:06:49 WARNING:Using the following 4-bit params: {'load_in_4bit': True, 'bnb_4bit_compute_dtype': torch.float16, 'bnb_4bit_quant_type': 'nf4', 'bnb_4bit_use_double_quant': False}
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████| 3/3 [06:58<00:00, 139.61s/it]
2023-08-09 22:13:52 WARNING:models\conceptofmind_LLongMA-2-13b-16k\tokenizer_config.json is different from the original LlamaTokenizer file. It is either customized or outdated.
2023-08-09 22:13:52 WARNING:models\conceptofmind_LLongMA-2-13b-16k\special_tokens_map.json is different from the original LlamaTokenizer file. It is either customized or outdated.
2023-08-09 22:13:52 INFO:Loaded the model in 422.12 seconds.

C:\Users\xplus-win\oobabooga_windows\installer_files\env\lib\site-packages\transformers\generation\utils.py:1365: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation )
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\xplus-win\oobabooga_windows\text-generation-webui\modules\callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "C:\Users\xplus-win\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 307, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Users\xplus-win\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\xplus-win\oobabooga_windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1633, in generate
    return self.sample(
  File "C:\Users\xplus-win\oobabooga_windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 2755, in sample
    outputs = self(
  File "C:\Users\xplus-win\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\xplus-win\oobabooga_windows\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\Users\xplus-win\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 810, in forward
    outputs = self.model(
  File "C:\Users\xplus-win\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\xplus-win\oobabooga_windows\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\Users\xplus-win\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 698, in forward
    layer_outputs = decoder_layer(
  File "C:\Users\xplus-win\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\xplus-win\oobabooga_windows\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\Users\xplus-win\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 413, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "C:\Users\xplus-win\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\xplus-win\oobabooga_windows\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\Users\xplus-win\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 300, in forward
    query_states = [F.linear(hidden_states, query_slices[i]) for i in range(self.config.pretraining_tp)]
  File "C:\Users\xplus-win\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 300, in <listcomp>
    query_states = [F.linear(hidden_states, query_slices[i]) for i in range(self.config.pretraining_tp)]
RuntimeError: mat1 and mat2 shapes cannot be multiplied (67x5120 and 1x2560)
Output generated in 1.32 seconds (0.00 tokens/s, 0 tokens, context 67, seed 828065784)

**Comment by SynthpX** [comment]
I get the same issue, but im on linux. Any idea why its fixed with Update_windows.bat file ?

**Comment by LordVeitor** [comment]
I'm having the same issue, with the exception I'm not running locally, I'm using colab to run ooba, any idea on how to solve the problem in that case?

**Comment by geronimi73** [comment]
> I get the same issue, but im on linux. Any idea why its fixed with Update_windows.bat file ?

same, ubuntu here. solved it by downgrading to a version from a month ago (commit 9ae0eab)

btw: reinstalling the requirements did not work
