### ISSUE TITLE
AttributeError: module 'os' has no attribute 'statvfs'

### ISSUE THREAD

**Issue by VitaleyUsa** [oobabooga/text-generation-webui#3515]
### Describe the bug

Hello everyone,

I've just downloaded text-generation-webui, installed all the required dependencies. However, when I try to start the web UI, I encounter the following error:
`AttributeError: module 'os' has no attribute 'statvfs'`

I've searched online, but all the Google results seem to be pointing to old Python 2.7 threads. What steps can I take to fix this issue? Your help would be greatly appreciated.

Thank you!

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

I'm encountering the same error whether I install it normally or by using the Windows installer.

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/36405102/6009552d-d112-4c38-8306-483599627408)

### Logs

```shell
Traceback (most recent call last):
  File "C:\text-generation-webui\text-generation-webui\server.py", line 12, in <module>
    import gradio as gr
  File "C:\text-generation-webui\installer_files\env\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\text-generation-webui\installer_files\env\lib\site-packages\gradio\components.py", line 56, in <module>
    from gradio.blocks import Block, BlockContext
  File "C:\text-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 26, in <module>
    from gradio import (
  File "C:\text-generation-webui\installer_files\env\lib\site-packages\gradio\networking.py", line 17, in <module>
    from gradio.routes import App
  File "C:\text-generation-webui\installer_files\env\lib\site-packages\gradio\routes.py", line 44, in <module>
    import gradio.ranged_response as ranged_response
  File "C:\text-generation-webui\installer_files\env\lib\site-packages\gradio\ranged_response.py", line 12, in <module>
    from aiofiles.os import stat as aio_stat
  File "C:\text-generation-webui\installer_files\env\lib\site-packages\aiofiles\os.py", line 32, in <module>
    statvfs = wrap(os.statvfs)
AttributeError: module 'os' has no attribute 'statvfs'
```

### System Info

```shell
> Windows 10 Pro x64
> 32 GB DDR4
> i7 - 12700kf
> Geforce GTX 3070TI
```

**Comment by CODPUD** [comment]
I get the exactly same error `AttributeError: module 'os' has no attribute 'statvfs'`
System Info

> Windows 11 x64
> 32 GB DDR4
> i5-12600KF
> Geforce GTX 3060Ti

**Comment by tweetyleaf2** [comment]
Same problem:

> System Info
> Windows 11 x64
> 32GB DDR4
> i5  - 10600KF
> Geforce RTX 3070 8GB

```

*******************************************************************
* WARNING: You haven't downloaded any model yet.
* Once the web UI launches, head over to the "Model" tab and download one.
*******************************************************************

Traceback (most recent call last):
  File "E:\Oobabooga\text-generation-webui\server.py", line 12, in <module>
    import gradio as gr
  File "E:\Oobabooga\installer_files\env\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "E:\Oobabooga\installer_files\env\lib\site-packages\gradio\components.py", line 56, in <module>
    from gradio.blocks import Block, BlockContext
  File "E:\Oobabooga\installer_files\env\lib\site-packages\gradio\blocks.py", line 26, in <module>
    from gradio import (
  File "E:\Oobabooga\installer_files\env\lib\site-packages\gradio\networking.py", line 17, in <module>
    from gradio.routes import App
  File "E:\Oobabooga\installer_files\env\lib\site-packages\gradio\routes.py", line 44, in <module>
    import gradio.ranged_response as ranged_response
  File "E:\Oobabooga\installer_files\env\lib\site-packages\gradio\ranged_response.py", line 12, in <module>
    from aiofiles.os import stat as aio_stat
  File "E:\Oobabooga\installer_files\env\lib\site-packages\aiofiles\os.py", line 32, in <module>
    statvfs = wrap(os.statvfs)
AttributeError: module 'os' has no attribute 'statvfs'
Press any key to continue . . .
```

**Comment by CODPUD** [comment]
Issue caused in [aiofiles](https://github.com/Tinche/aiofiles) library. Issue was reported here already https://github.com/Tinche/aiofiles/issues/171


cc: @VitaleyUsa @tweetyleaf2

**Comment by iXab3r** [comment]
Encountered same issue, installed via WSL in the end. Worked like a charm, the whole configuration took about 10 extra minutes, thanks to great instructions

**Comment by oobabooga** [comment]
I think that this should have fixed it https://github.com/oobabooga/text-generation-webui/commit/7c1300fab55e39f80c1d6fa8f547b9a7c41fcbcd

Can someone try running the update script to see if it worked?

**Comment by CODPUD** [comment]
@oobabooga I reverted aiofiles version manually to the version you applied, it worked fine on my end

**Comment by VitaleyUsa** [comment]
> Can someone try running the update script to see if it worked?
Just tested it, works like a charm, thank you for your support!
