### ISSUE TITLE
Character- [WinError 183] Cannot create a file when that file already exists

### ISSUE THREAD

**Issue by angrysky56** [oobabooga/text-generation-webui#3541]
### Describe the bug

Loading a character, get error message and no history is loaded.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load character from gallery and error.

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/113643118/bd652935-e169-49b6-9722-2398301d5a60)

### Logs

```shell
2023-08-11 14:22:28 WARNING:Renaming logs\Zen Koan Enigma Mode_persistent.json to logs\persistent_Zen Koan Enigma Mode.json
Traceback (most recent call last):
  File "D:\oobabooga\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\oobabooga\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\oobabooga\installer_files\env\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\oobabooga\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\oobabooga\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\oobabooga\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\oobabooga\text-generation-webui\modules\chat.py", line 441, in load_persistent_history
    old_p.rename(p)
  File "D:\oobabooga\installer_files\env\lib\pathlib.py", line 1234, in rename
    self._accessor.rename(self, target)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'logs\\Zen Koan Enigma Mode_persistent.json' -> 'logs\\persistent_Zen Koan Enigma Mode.json'
```

### System Info

```shell
Windows, Nvidia 3060 12gb.
```

**Comment by jllllll** [comment]
While this technically can be fixed, I'm not sure it should be as the intention behind the code is to facilitate renaming of old histories to a new filename format. It isn't expected to already have a chat history stored under the new file name while still having the old one.

You should check both logs under `\text-generation-webui\logs\` to see if either has a history that you want to keep and manually delete the other. So long as only one of them exists, the error should go away.

If a fix is truly warranted, the simplest approach would be to change:
https://github.com/oobabooga/text-generation-webui/blob/main/modules/chat.py#L441
To:
```py
        old_p.replace(p)
```

**Comment by angrysky56** [comment]
I am not sure what happened but it did several fine, just left the old one of the one. I will mention if it continues to happen. Glad it wasn't one with a lot of history.
