### ISSUE TITLE
LLaMA model does not work after migrating to the main transformers

### ISSUE THREAD

**Issue by kristaller486** [oobabooga/text-generation-webui#357]
### Describe the bug

The LLaMA model does not work after the webui update.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Update webui via install.bat and run the script with args "--gptq-bits 4 --extension llama_prompts --model llama-7b-hf"

### Logs

```shell
Starting the web UI...
Loading llama-7b-hf...
NOTE: Redirects are currently not supported in Windows or MacOs.
Traceback (most recent call last):
    File "F:\oobabooga-windows\oobabooga\text-generation-webui\server.py", line 197, in <module>
        shared.model, shared.tokenizer = load_model(shared.model_name)
    File "F:\oobabooga-windows\oobabooga\text-generation-webui\modules\models.py", line 93, in load_model
        model = load_quantized(model_name)
    File "F:\oobabooga-windows\oobabooga\text-generation-webui\modules\GPTQ_loader.py", line 55, in load_quantized
        model = load_quant(str(path_to_model), str(pt_path), shared.args.gptq_bits)
    File "F:\oobabooga-windows\oobabooga\text-generation-webui\repositories\GPTQ-for-LLaMa\llama.py", line 220, in load_quant
        from transformers import LLaMAConfig, LLaMAForCausalLM
ImportError: cannot import name 'LLaMAConfig' from 'transformers' (F:\oobabooga-windows\oobabooga\installer_files\env\lib\site-packages\transformers\__init__.py)
```

### System Info

```shell
Windows 10
Nvidia RTX 3060 12GB
```

**Comment by USBhost** [comment]
See the comment on this https://github.com/oobabooga/text-generation-webui/commit/23a5e886e1aa6849e0819256c3bb4b2bf7d8358e

**Comment by kristaller486** [comment]
> See the comment on this [23a5e88](https://github.com/oobabooga/text-generation-webui/commit/23a5e886e1aa6849e0819256c3bb4b2bf7d8358e)

Thanks, updating the GPTQ solved the problem, but I think it would be a good idea to document the solution so that other users don't have to deal with this

**Comment by kristaller486** [comment]
> > > See the comment on this [23a5e88](https://github.com/oobabooga/text-generation-webui/commit/23a5e886e1aa6849e0819256c3bb4b2bf7d8358e)
> > 
> > 
> > Thanks, updating the GPTQ solved the problem, but I think it would be a good idea to document the solution so that other users don't have to deal with this
> 
> Can you please tell me the exact steps to solve this? I did a `git pull` in the root directory and also did `pip install -r requirements.txt` in both the root directory and in ./repositories/GPTQ-for-LLaMA, I still get the same error like you!

1) git pull in repositories/gptq-for-llama
2) rename LLaMATokenizer to LlamaTokenizer in models/llama-7b-hf/tokenizer_config.json

**Comment by RandomName321** [comment]
```
E:\oobabooga\installer_files\env\lib\site-packages\transformers\generation\utils.py:1201: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
  warnings.warn(
Output generated in 0.70 seconds (0.00 tokens/s, 0 tokens)
```
Now I have a new problem

**Comment by RandomName321** [comment]
If you do not use the option

> --no-stream

 then

> CUDA error: an illegal memory access was encountered

**Comment by BugReporterZ** [comment]
I also had the 0 tokens problem; after reconverting my weights (from the original torrent) with the latest `convert_llama_weights_to_hf.py`, now it seems to work correctly.

**Comment by athu16** [comment]
> If you do not use the option
> 
> > --no-stream
> 
> then
> 
> > CUDA error: an illegal memory access was encountered

I have the exact same issue. Also, it doesn't seem to be specific to the llama model, as I had the same issue with GPT-J 6B.

**Comment by askmyteapot** [comment]
If you are still getting issues with multi-gpu you need to update the file **modules\GPTQ_Loader.py**

line 64. update `no_split_module_classes=["LLaMADecoderLayer"]` to `no_split_module_classes=["LlamaDecoderLayer"]`

Now im able to generate tokens for replies again. 

This is on top of re-doing the weight tokenizer_config.json

**Comment by oobabooga** [comment]
To fix the `0.00 tokens/s, 0 tokens` issue, this is what I did on my laptop:

1. Update to the latest transformers version:

```
conda activate textgen
pip uninstall transformers
pip install git+https://github.com/huggingface/transformers
```

2. Make sure that you have the decapoda weights:

```
python download-model.py decapoda-research/llama-7b-hf
```

3. Edit the file `models/llama-7b-hf/tokenizer_config.json` and replace `LLaMATokenizer` with `LlamaTokenizer`.

After that I started getting outputs again.
