### ISSUE TITLE
Problem when using the --public-api flag.

### ISSUE THREAD

**Issue by akaikite** [oobabooga/text-generation-webui#3570]
### Describe the bug

I used the --api --public-api flag as usual, but got an error.
So I fixed it by opening text-generation-webui\extensions\api\util.py and modifying public_url = _run_cloudflared(port, port + 1, tunnel_id=tunnel_id) to public_url = _run_cloudflared(port, port + 1).

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

--api --public-api flag

### Logs

```shell
2023-08-14 17:30:05 INFO:Loading the extension "gallery"...
Traceback (most recent call last):
  File "D:\AIchat\oobabooga-windows\text-generation-webui\extensions\api\util.py", line 102, in _start_cloudflared
    public_url = _run_cloudflared(port, port + 1, tunnel_id=tunnel_id)
TypeError: _run_cloudflared() got an unexpected keyword argument 'tunnel_id'
Traceback (most recent call last):
  File "D:\AIchat\oobabooga-windows\text-generation-webui\extensions\api\util.py", line 102, in _start_cloudflared
    public_url = _run_cloudflared(port, port + 1, tunnel_id=tunnel_id)
TypeError: _run_cloudflared() got an unexpected keyword argument 'tunnel_id'
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Exception in thread Thread-7 (_start_cloudflared):
Exception in thread Thread-8 (_start_cloudflared):
Traceback (most recent call last):
Traceback (most recent call last):
  File "D:\AIchat\oobabooga-windows\installer_files\env\lib\threading.py", line 1016, in _bootstrap_inner
  File "D:\AIchat\oobabooga-windows\installer_files\env\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    self.run()
  File "D:\AIchat\oobabooga-windows\installer_files\env\lib\threading.py", line 953, in run
  File "D:\AIchat\oobabooga-windows\installer_files\env\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "D:\AIchat\oobabooga-windows\text-generation-webui\extensions\api\util.py", line 112, in _start_cloudflared
  File "D:\AIchat\oobabooga-windows\text-generation-webui\extensions\api\util.py", line 112, in _start_cloudflared
    raise Exception('Could not start cloudflared.')
Exception: Could not start cloudflared.
    raise Exception('Could not start cloudflared.')
Exception: Could not start cloudflared.
```

### System Info

```shell
Windows 11 pro, text-generation-webui one-click mode
```

**Comment by 15899885850** [comment]
Me too, have you solved this problem?

**Comment by akaikite** [comment]
> Me too, have you solved this problem?

So I fixed it by opening text-generation-webui\extensions\api\util.py and modifying public_url = _run_cloudflared(port, port + 1, tunnel_id=tunnel_id) to public_url = _run_cloudflared(port, port + 1). <<<<<< you can read it.

**Comment by 15899885850** [comment]
> public_url

thx!!!!

**Comment by 15899885850** [comment]
> > Me too, have you solved this problem?
> 
> So I fixed it by opening text-generation-webui\extensions\api\util.py and modifying public_url = _run_cloudflared(port, port + 1, tunnel_id=tunnel_id) to public_url = _run_cloudflared(port, port + 1). <<<<<< you can read it. and yes, I fixed that shitty bug.

Thx!!!!

**Comment by ausboss** [comment]
I just did a pr that should fix this so you don't have to manually edit the file.

**Comment by mattscott** [comment]
After pulling the latest, I have this updated code in utils.py:

            if tunnel_id is not None:
                public_url = _run_cloudflared(port, port + 1, tunnel_id=tunnel_id)
            else:
                public_url = _run_cloudflared(port, port + 1)

However, attempting to run with the --public-api switch still produces an error and the public api never starts.

Traceback (most recent call last):
  File "/home/user/oobabooga_linux/text-generation-webui/extensions/api/util.py", line 105, in _start_cloudflared
    public_url = _run_cloudflared(port, port + 1)
  File "/home/user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/flask_cloudflared.py", line 75, in _run_cloudflared
    cloudflared = subprocess.Popen([executable, 'tunnel', '--url', 'http://127.0.0.1:' + str(port), '--metrics', '127.0.0.1:' + str(metrics_port)], stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
  File "/home/user/oobabooga_linux/installer_files/env/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/user/oobabooga_linux/installer_files/env/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 26] Text file busy: '/tmp/cloudflared-linux-amd64'
Exception in thread Thread-4 (_start_cloudflared):
Traceback (most recent call last):
  File "/home/user/oobabooga_linux/installer_files/env/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/user/oobabooga_linux/installer_files/env/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/oobabooga_linux/text-generation-webui/extensions/api/util.py", line 115, in _start_cloudflared
    raise Exception('Could not start cloudflared.')
Exception: Could not start cloudflared.

**Comment by alicat22** [comment]
This is still an issue, so I'm reopening.

**Comment by alicat22** [comment]
This is still an issue. Same error as above.

**Comment by marijnbent** [comment]
Can confirm, still an issue.
