### ISSUE TITLE
Some wrong about public api

### ISSUE THREAD

**Issue by 15899885850** [oobabooga/text-generation-webui#3593]
### Describe the bug

When I use the following command:
!python server.py --share --chat --load-in-8bit --model /root/autodl-tmp/text-generation-webui/models/Llama-2-13b-chat-hf --public-api

An error was reported, and the error message is as follows:
/root/autodl-tmp/text-generation-webui
2023-08-16 16:00:01 WARNING:The --chat flag has been deprecated and will be removed soon. Please remove that flag.
2023-08-16 16:00:01 WARNING:The gradio "share link" feature uses a proprietary executable to create a reverse tunnel. Use it with care.
2023-08-16 16:00:04 INFO:Loading /root/autodl-tmp/text-generation-webui/models/Llama-2-13b-chat-hf...
Loading checkpoint shards: 100%|██████████████████| 3/3 [00:08<00:00,  2.91s/it]
2023-08-16 16:00:14 WARNING:models/Llama-2-13b-chat-hf/tokenizer_config.json is different from the original LlamaTokenizer file. It is either customized or outdated.
2023-08-16 16:00:14 WARNING:models/Llama-2-13b-chat-hf/special_tokens_map.json is different from the original LlamaTokenizer file. It is either customized or outdated.
2023-08-16 16:00:14 INFO:Loaded the model in 10.31 seconds.

2023-08-16 16:00:14 INFO:Loading the extension "gallery"...
Running on local URL:  http://127.0.0.1:6006/
Running on public URL: https://d950a6178f57d659c7.gradio.live/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
Traceback (most recent call last):
  File "/root/autodl-tmp/text-generation-webui/extensions/api/util.py", line 102, in _start_cloudflared
    public_url = _run_cloudflared(port, port + 1, tunnel_id=tunnel_id)
  File "/root/.local/lib/python3.10/site-packages/flask_cloudflared.py", line 137, in _run_cloudflared
    raise Exception(f"! Can't connect to Cloudflare Edge")
Exception: ! Can't connect to Cloudflare Edge
Traceback (most recent call last):
  File "/root/autodl-tmp/text-generation-webui/extensions/api/util.py", line 102, in _start_cloudflared
    public_url = _run_cloudflared(port, port + 1, tunnel_id=tunnel_id)
  File "/root/.local/lib/python3.10/site-packages/flask_cloudflared.py", line 137, in _run_cloudflared
    raise Exception(f"! Can't connect to Cloudflare Edge")
Exception: ! Can't connect to Cloudflare Edge
Exception in thread Thread-5 (_start_cloudflared):
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/autodl-tmp/text-generation-webui/extensions/api/util.py", line 113, in _start_cloudflared
    raise Exception('Could not start cloudflared.')
Exception: Could not start cloudflared.
Exception in thread Thread-4 (_start_cloudflared):
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/autodl-tmp/text-generation-webui/extensions/api/util.py", line 113, in _start_cloudflared
    raise Exception('Could not start cloudflared.')
Exception: Could not start cloudflared.

I don't know where the problem occurred, it seems to be a connection error. I used curl-I https://www.cloudflare.com You can get a good response.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

When I use the following command:
!python server.py --share --chat --load-in-8bit --model /root/autodl-tmp/text-generation-webui/models/Llama-2-13b-chat-hf --public-api

### Logs

```shell
This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
Traceback (most recent call last):
  File "/root/autodl-tmp/text-generation-webui/extensions/api/util.py", line 102, in _start_cloudflared
    public_url = _run_cloudflared(port, port + 1, tunnel_id=tunnel_id)
  File "/root/.local/lib/python3.10/site-packages/flask_cloudflared.py", line 137, in _run_cloudflared
    raise Exception(f"! Can't connect to Cloudflare Edge")
Exception: ! Can't connect to Cloudflare Edge
Traceback (most recent call last):
  File "/root/autodl-tmp/text-generation-webui/extensions/api/util.py", line 102, in _start_cloudflared
    public_url = _run_cloudflared(port, port + 1, tunnel_id=tunnel_id)
  File "/root/.local/lib/python3.10/site-packages/flask_cloudflared.py", line 137, in _run_cloudflared
    raise Exception(f"! Can't connect to Cloudflare Edge")
Exception: ! Can't connect to Cloudflare Edge
Exception in thread Thread-5 (_start_cloudflared):
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/autodl-tmp/text-generation-webui/extensions/api/util.py", line 113, in _start_cloudflared
    raise Exception('Could not start cloudflared.')
Exception: Could not start cloudflared.
Exception in thread Thread-4 (_start_cloudflared):
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/autodl-tmp/text-generation-webui/extensions/api/util.py", line 113, in _start_cloudflared
    raise Exception('Could not start cloudflared.')
Exception: Could not start cloudflared.
```

### System Info

```shell
Thumbnail:Thumbnail
Python  3.10(ubuntu22.04)
Cuda  11.8
GPU:RTX A5000(24GB) * 1
CPU:15 vCPU AMD EPYC 7302 16-Core Processor
Memory:28GB

And I use this cloud server AUTODL just like Colab.
```

**Comment by Sousheyyy** [comment]
Just use --share argument it will give you a gradio link and you can access the api over there

**Comment by 15899885850** [comment]
> Just use --share argument it will give you a gradio link and you can access the api over there
