### ISSUE TITLE
Incompatibility with the installed version of numpy when running the update_windows batch script.

### ISSUE THREAD

**Issue by tkbit** [oobabooga/text-generation-webui#3599]
### Describe the bug

Description:
When I execute the update_windows batch script for automatic windows installation, it installs a version of numpy that is incompatible with the requirements of the whisper extension. This leads to a crash when attempting to use the extension.

Temporary Solution:
I've created a temporary batch script that downgrades numpy to version 1.24, which resolves the issue.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

run update_windows.bat when outdated. Then use the whisper extension.

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\tkbits\Desktop\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\tkbits\Desktop\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\tkbits\Desktop\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\tkbits\Desktop\AI\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\tkbits\Desktop\AI\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\tkbits\Desktop\AI\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\tkbits\Desktop\AI\oobabooga_windows\text-generation-webui\extensions\whisper_stt\script.py", line 48, in auto_transcribe
    transcription = do_stt(audio, whipser_model, whipser_language)
  File "C:\Users\tkbits\Desktop\AI\oobabooga_windows\text-generation-webui\extensions\whisper_stt\script.py", line 36, in do_stt
    transcription = r.recognize_whisper(audio_data, language=whipser_language, model=whipser_model)
  File "C:\Users\tkbits\Desktop\AI\oobabooga_windows\installer_files\env\lib\site-packages\speech_recognition\__init__.py", line 1479, in recognize_whisper
    import whisper
  File "C:\Users\tkbits\Desktop\AI\oobabooga_windows\installer_files\env\lib\site-packages\whisper\__init__.py", line 13, in <module>
    from .model import ModelDimensions, Whisper
  File "C:\Users\tkbits\Desktop\AI\oobabooga_windows\installer_files\env\lib\site-packages\whisper\model.py", line 13, in <module>
    from .transcribe import transcribe as transcribe_function
  File "C:\Users\tkbits\Desktop\AI\oobabooga_windows\installer_files\env\lib\site-packages\whisper\transcribe.py", line 20, in <module>
    from .timing import add_word_timestamps
  File "C:\Users\tkbits\Desktop\AI\oobabooga_windows\installer_files\env\lib\site-packages\whisper\timing.py", line 7, in <module>
    import numba
  File "C:\Users\tkbits\Desktop\AI\oobabooga_windows\installer_files\env\lib\site-packages\numba\__init__.py", line 55, in <module>
    _ensure_critical_deps()
  File "C:\Users\tkbits\Desktop\AI\oobabooga_windows\installer_files\env\lib\site-packages\numba\__init__.py", line 42, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.24 or less")
ImportError: Numba needs NumPy 1.24 or less
```

### System Info

```shell
Windows 10
NVIDIA Geforce RTX 3090
32GB Ram
AMD Ryzen 5 3600
```

**Comment by tkbit** [comment]
Created a pull request to address this: #3651
