### ISSUE TITLE
LoRA training error "Using pad_token, but it is not set yet."

### ISSUE THREAD

**Issue by ciro-01** [oobabooga/text-generation-webui#3603]
### Describe the bug

Model: llama-2-13b-hf

Error from console:

2023-08-17 14:00:55 INFO:Getting model ready...
2023-08-17 14:00:55 INFO:Prepping for training...
2023-08-17 14:00:55 INFO:Creating LoRA model...
2023-08-17 14:01:57 INFO:Starting training...
2023-08-17 14:01:57 INFO:Log file 'train_dataset_sample.json' created in the 'logs' directory.
Using pad_token, but it is not set yet.
Exception in thread Thread-14 (threaded_run):
Traceback (most recent call last):
  File "C:\SAPDevelop\oobabooga_windows\installer_files\env\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\SAPDevelop\oobabooga_windows\installer_files\env\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\SAPDevelop\oobabooga_windows\text-generation-webui\modules\training.py", line 664, in threaded_run
    trainer.train()
  File "C:\SAPDevelop\oobabooga_windows\installer_files\env\lib\site-packages\transformers\trainer.py", line 1544, in train
    return inner_training_loop(
  File "C:\SAPDevelop\oobabooga_windows\installer_files\env\lib\site-packages\transformers\trainer.py", line 1795, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "C:\SAPDevelop\oobabooga_windows\installer_files\env\lib\site-packages\accelerate\data_loader.py", line 384, in __iter__
    current_batch = next(dataloader_iter)
  File "C:\SAPDevelop\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\data\dataloader.py", line 633, in __next__
    data = self._next_data()
  File "C:\SAPDevelop\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\data\dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\SAPDevelop\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "C:\SAPDevelop\oobabooga_windows\installer_files\env\lib\site-packages\transformers\data\data_collator.py", line 45, in __call__
    return self.torch_call(features)
  File "C:\SAPDevelop\oobabooga_windows\installer_files\env\lib\site-packages\transformers\data\data_collator.py", line 732, in torch_call
    batch = self.tokenizer.pad(examples, return_tensors="pt", pad_to_multiple_of=self.pad_to_multiple_of)
  File "C:\SAPDevelop\oobabooga_windows\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py", line 3051, in pad
    padding_strategy, _, max_length, _ = self._get_padding_truncation_strategies(
  File "C:\SAPDevelop\oobabooga_windows\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py", line 2499, in _get_padding_truncation_strategies
    raise ValueError(
ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.
2023-08-17 14:01:58 INFO:Training complete, saving...
2023-08-17 14:01:58 INFO:Training complete!

The error says pad token has not been set but in training.py pad_token_id has been set to 0 which is <unk> in llama

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

- load model llama-2-13b-hf
- train lora with data

### Logs

```shell
2023-08-17 14:00:55 INFO:Getting model ready...
2023-08-17 14:00:55 INFO:Prepping for training...
2023-08-17 14:00:55 INFO:Creating LoRA model...
2023-08-17 14:01:57 INFO:Starting training...
2023-08-17 14:01:57 INFO:Log file 'train_dataset_sample.json' created in the 'logs' directory.
Using pad_token, but it is not set yet.
Exception in thread Thread-14 (threaded_run):
Traceback (most recent call last):
  File "C:\SAPDevelop\oobabooga_windows\installer_files\env\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\SAPDevelop\oobabooga_windows\installer_files\env\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\SAPDevelop\oobabooga_windows\text-generation-webui\modules\training.py", line 664, in threaded_run
    trainer.train()
  File "C:\SAPDevelop\oobabooga_windows\installer_files\env\lib\site-packages\transformers\trainer.py", line 1544, in train
    return inner_training_loop(
  File "C:\SAPDevelop\oobabooga_windows\installer_files\env\lib\site-packages\transformers\trainer.py", line 1795, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "C:\SAPDevelop\oobabooga_windows\installer_files\env\lib\site-packages\accelerate\data_loader.py", line 384, in __iter__
    current_batch = next(dataloader_iter)
  File "C:\SAPDevelop\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\data\dataloader.py", line 633, in __next__
    data = self._next_data()
  File "C:\SAPDevelop\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\data\dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\SAPDevelop\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "C:\SAPDevelop\oobabooga_windows\installer_files\env\lib\site-packages\transformers\data\data_collator.py", line 45, in __call__
    return self.torch_call(features)
  File "C:\SAPDevelop\oobabooga_windows\installer_files\env\lib\site-packages\transformers\data\data_collator.py", line 732, in torch_call
    batch = self.tokenizer.pad(examples, return_tensors="pt", pad_to_multiple_of=self.pad_to_multiple_of)
  File "C:\SAPDevelop\oobabooga_windows\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py", line 3051, in pad
    padding_strategy, _, max_length, _ = self._get_padding_truncation_strategies(
  File "C:\SAPDevelop\oobabooga_windows\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py", line 2499, in _get_padding_truncation_strategies
    raise ValueError(
ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.
2023-08-17 14:01:58 INFO:Training complete, saving...
2023-08-17 14:01:58 INFO:Training complete!
```

### System Info

```shell
os: windows 11
gpu: 3090
```

**Comment by guyman624** [comment]
Same issue, same os, same gpu.

**Comment by phelixzhen** [comment]
I have this problem too. Does anyone have a solution?

**Comment by moritzschaefer** [comment]
Same error here with Mistral 7B. Please reopen the issue

**Comment by lamkhatinh** [comment]
me too, help pleases!
