### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by HolzerDavid** [oobabooga/text-generation-webui#3607]
### Describe the bug

When loading a GGML model manually, using the cmd_windows.bat, I get this error.
The files are in the corresponding model directories, so i am not sure how this occurs.

```
cmdr@DESKTOP-9UKDAN9:/mnt/a/oobabooga_windows/text-generation-webui/models/TheBloke_Llama-2-70B-Chat-GGML$ ls -all
total 423331140
drwxrwxrwx 1 cmdr cmdr         512 Aug 17 19:54 .
drwxrwxrwx 1 cmdr cmdr         512 Aug 18 00:50 ..
-rwxrwxrwx 1 cmdr cmdr        7020 Aug 17 18:11 LICENSE.txt
-rwxrwxrwx 1 cmdr cmdr       20114 Aug 17 18:11 README.md
-rwxrwxrwx 1 cmdr cmdr        4766 Aug 17 18:11 USE_POLICY.md
-rwxrwxrwx 1 cmdr cmdr          29 Aug 17 18:11 config.json
-rwxrwxrwx 1 cmdr cmdr        1269 Aug 18 00:41 huggingface-metadata.txt
-rwxrwxrwx 1 cmdr cmdr 28586905216 Aug 17 18:19 llama-2-70b-chat.ggmlv3.q2_K.bin
-rwxrwxrwx 1 cmdr cmdr 36147547776 Aug 17 18:29 llama-2-70b-chat.ggmlv3.q3_K_L.bin
-rwxrwxrwx 1 cmdr cmdr 33043762816 Aug 17 18:37 llama-2-70b-chat.ggmlv3.q3_K_M.bin
-rwxrwxrwx 1 cmdr cmdr 29745991296 Aug 17 18:45 llama-2-70b-chat.ggmlv3.q3_K_S.bin
-rwxrwxrwx 1 cmdr cmdr 38871961216 Aug 17 18:56 llama-2-70b-chat.ggmlv3.q4_0.bin
-rwxrwxrwx 1 cmdr cmdr 43166535296 Aug 17 19:07 llama-2-70b-chat.ggmlv3.q4_1.bin
-rwxrwxrwx 1 cmdr cmdr 41380679296 Aug 17 19:18 llama-2-70b-chat.ggmlv3.q4_K_M.bin
-rwxrwxrwx 1 cmdr cmdr 38871961216 Aug 17 19:28 llama-2-70b-chat.ggmlv3.q4_K_S.bin
-rwxrwxrwx 1 cmdr cmdr 47461109376 Aug 17 19:41 llama-2-70b-chat.ggmlv3.q5_0.bin
-rwxrwxrwx 1 cmdr cmdr 48753479296 Aug 17 19:54 llama-2-70b-chat.ggmlv3.q5_K_M.bin
-rwxrwxrwx 1 cmdr cmdr 47461109376 Aug 17 20:06 llama-2-70b-chat.ggmlv3.q5_K_S.bin
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

launch cmd_windows.bat
> cd text-generation-webui
> python server.py --model models/llama-2-70b-chat.ggmlv3.q4_K_M.bin --n-gpu-layers 35 --loader llamacpp_hf

### Logs

```shell
(A:\oobabooga_windows\installer_files\env) A:\oobabooga_windows\text-generation-webui>python server.py --model models/llama-2-70b-chat.ggmlv3.q4_K_M.bin --n-gpu-layers 35 --loader llamacpp_hf
bin A:\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
2023-08-18 00:53:16 INFO:Loading models/llama-2-70b-chat.ggmlv3.q4_K_M.bin...
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090, compute capability 8.6
Traceback (most recent call last):
  File "A:\oobabooga_windows\text-generation-webui\server.py", line 223, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "A:\oobabooga_windows\text-generation-webui\modules\models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "A:\oobabooga_windows\text-generation-webui\modules\models.py", line 268, in llamacpp_HF_loader
    model = LlamacppHF.from_pretrained(model_name)
  File "A:\oobabooga_windows\text-generation-webui\modules\llamacpp_hf.py", line 102, in from_pretrained
    model_file = list(path.glob('*ggml*.bin'))[0]
IndexError: list index out of range
````
```


### System Info

```shell
RTX3090, 8700k, RAM 64GB
```

**Comment by jllllll** [comment]
Use `--model llama-2-70b-chat.ggmlv3.q4_K_M.bin`

Alternatively, place the `.bin` in it's own folder like `llama-2-70b-chat-GGML` and use this to load it:
`--model llama-2-70b-chat-GGML`
