### ISSUE TITLE
screwed up install

### ISSUE THREAD

**Issue by mcblockserrilla** [oobabooga/text-generation-webui#3635]
### Describe the bug

i had the program running fine and i thought everything was self contained for the most part.
i moved the files to a different drive and it didn't want to work.
i decided to make a fresh install on the drive and i copied the modified config.jason file and the modded server file.

2023-08-20 12:52:23 WARNING:The --chat flag has been deprecated and will be removed soon. Please remove that flag.
bin F:\one-click-installers-main\one-click-installers-main\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
Traceback (most recent call last):
  File "F:\one-click-installers-main\one-click-installers-main\text-generation-webui\server.py", line 194, in <module>
    for extension in shared.settings['chat_default_extensions']:
KeyError: 'chat_default_extensions'
Press any key to continue . . .

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

use auto installer. move files to new drive.

### Logs

```shell
2023-08-20 12:52:23 WARNING:The --chat flag has been deprecated and will be removed soon. Please remove that flag.
bin F:\one-click-installers-main\one-click-installers-main\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
Traceback (most recent call last):
  File "F:\one-click-installers-main\one-click-installers-main\text-generation-webui\server.py", line 194, in <module>
    for extension in shared.settings['chat_default_extensions']:
KeyError: 'chat_default_extensions'
Press any key to continue . . .
```

### System Info

```shell
windows 10
ryzen 7 5800x3d
64gb ddr4 3200mhz
rtx 4090
1tb nvme
500gb nvme
8tb hdd
4tb hdd
```

**Comment by Fusseldieb** [comment]
`i copied the modified config.jason file and the modded server file`

Yea don't modify files randomly or else you cannot update it properly anymore.

I would suggest to redownload it and reinstall, and then, if you want, re-add your stuff manually (open and paste).
