### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by MackDing** [oobabooga/text-generation-webui#3647]
### Describe the bug

![WXWorkCapture_16926956394166](https://github.com/oobabooga/text-generation-webui/assets/19878893/e63fb592-6a50-452d-a6d3-2a2048e0caea)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

use UI download TheBloke_Llama-2-70B-Chat-GGML 

select TheBloke_Llama-2-70B-Chat-GGML 
load  TheBloke_Llama-2-70B-Chat-GGML 

### Logs

```shell
llama.cpp: loading model from models/TheBloke_Llama-2-70B-Chat-GGML/llama-2-70b-chat.ggmlv3.q5_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 8192
llama_model_load_internal: n_mult     = 4096
llama_model_load_internal: n_head     = 64
llama_model_load_internal: n_head_kv  = 64
llama_model_load_internal: n_layer    = 80
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: n_gqa      = 1
llama_model_load_internal: rnorm_eps  = 5.0e-06
llama_model_load_internal: n_ff       = 24576
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 8 (mostly Q5_0)
llama_model_load_internal: model size = 65B
llama_model_load_internal: ggml ctx size =    0.21 MB
error loading model: llama.cpp: tensor 'layers.0.attention.wk.weight' has wrong shape; expected  8192 x  8192, got  8192 x  1024
llama_load_model_from_file: failed to load model
2023-08-22 18:49:58 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/data/oobabooga_wsl/text-generation-webui/modules/ui_model_menu.py", line 185, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/data/oobabooga_wsl/text-generation-webui/modules/models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "/data/oobabooga_wsl/text-generation-webui/modules/models.py", line 247, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
  File "/data/oobabooga_wsl/text-generation-webui/modules/llamacpp_model.py", line 82, in from_pretrained
    result.model = Llama(**params)
  File "/home/mack/anaconda3/envs/textgen/lib/python3.10/site-packages/llama_cpp/llama.py", line 328, in __init__
    assert self.model is not None
AssertionError

Exception ignored in: <function LlamaCppModel.__del__ at 0x7f3eea6bb7f0>
Traceback (most recent call last):
  File "/data/oobabooga_wsl/text-generation-webui/modules/llamacpp_model.py", line 39, in __del__
    self.model.__del__()
AttributeError: 'LlamaCppModel' object has no attribute 'model'
```

### System Info

```shell
windows10_WSL_Ubuntu

(base) [root@PS2021WWURSRXY ~]# neofetch
            .-/+oossssoo+/-.               root@PS2021WWURSRXY 
        `:+ssssssssssssssssss+:`           ------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 18.04.2 LTS on Windows 10 x86_64 
    .ossssssssssssssssssdMMMNysssso.       Kernel: 5.15.90.1-microsoft-standard-WSL2 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Uptime: 1 day, 28 mins 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Packages: 1029 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Shell: bash 4.4.20 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Adwaita [GTK3] 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Icons: Adwaita [GTK3] 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Terminal: /dev/pts/7 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: Intel i5-10400F (12) @ 2.903GHz 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   GPU: Microsoft Corporation Device 008e 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Memory: 1123MiB / 15961MiB
```

**Comment by Ph0rk0z** [comment]
You forgot to set GQA.
