### ISSUE TITLE
Rehman

### ISSUE THREAD

**Issue by MaimonaSehar** [oobabooga/text-generation-webui#3648]
can some one help me out i m getting this error every time i try to run oobabooga webui
Traceback (most recent call last):
  File "C:\Users\htc\Downloads\Compressed\oobabooga_windows\oobabooga_windows\text-generation-webui\server.py", line 12, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

**Comment by 13631368** [comment]
> can some one help me out i m getting this error every time i try to run oobabooga webui
> Traceback (most recent call last):
>   File "C:\Users\htc\Downloads\Compressed\oobabooga_windows\oobabooga_windows\text-generation-webui\server.py", line 12, in <module>
>     import gradio as gr
> ModuleNotFoundError: No module named 'gradio'

**Comment by jllllll** [comment]
Looks to be a failed install. Very likely due to the file path being too long.

**Comment by MaimonaSehar** [comment]
how to solve this problem?

**Comment by jllllll** [comment]
Place the installer in `C:\oobabooga_windows\`

**Comment by MaimonaSehar** [comment]
installed on c:\....
still got this error
no module  name 'gradio'
can u tell me what is the minimum requirement of RAM to run this ?

**Comment by risedangel** [comment]
can you try to run update_windows.bat ?

**Comment by MaimonaSehar** [comment]
yes i did a couple of times still not work :(

**Comment by jllllll** [comment]
Were there no errors shown during the update process?
`ModuleNotFoundError: No module named 'gradio'` indicates that the pip requirements failed to install.
This should have shown an error message that could explain why.

**Comment by MaimonaSehar** [comment]
Thanks for help
i got installed through pinokio AI :)
