### ISSUE TITLE
ImportError: cannot import name 'is_npu_available' from 'accelerate.utils'

### ISSUE THREAD

**Issue by GamingDaveUk** [oobabooga/text-generation-webui#3654]
### Describe the bug

Will not load.
See log for more details as i know "Will not load is not exactly descriptive...just apt"

Loaded fine yesterday, updated today and viola...not working.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Update using "update_windows.bat"
Then try to load using "start_windows.bat"

### Logs

```shell
2023-08-23 01:34:41 WARNING:The --chat flag has been deprecated and will be removed soon. Please remove that flag.
Traceback (most recent call last):
  File "C:\AI\oobabooga_windows\text-generation-webui\server.py", line 28, in <module>
    from modules import (
  File "C:\AI\oobabooga_windows\text-generation-webui\modules\training.py", line 21, in <module>
    from peft import (
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .auto import (
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\peft\auto.py", line 30, in <module>
    from .config import PeftConfig
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\peft\config.py", line 24, in <module>
    from .utils import CONFIG_NAME, PeftType, TaskType
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\peft\utils\__init__.py", line 22, in <module>
    from .other import (
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\peft\utils\other.py", line 24, in <module>
    from accelerate.utils import is_npu_available, is_xpu_available
ImportError: cannot import name 'is_npu_available' from 'accelerate.utils' (C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\accelerate\utils\__init__.py)

Done!
Press any key to continue . .
```

### System Info

```shell
windows 11
nvidia rtx 3090 gpu
```

**Comment by GamingDaveUk** [comment]
Updated again just now and same error when I try to run the start_windows.bat

**Comment by Terristen** [comment]
Same issue with update. WIndows 11, nvidia rtx 4090, 192 gb ram

**Comment by VRArt1** [comment]
Also having this error since updating. Also tried removing the GPTQ folder like mentioned in the instructions txt but no dice. Windows 11, NVIDIA GeForce RTX 3080, 26 gb vram

**Comment by FreeApophis** [comment]
Same Problem: after the update it will start up with the exact same error:

Windows 11, RTX 3080, 64GB Ram

**Comment by verysuperkev** [comment]
Hey, after falling over the same problem, I realised you need to re-download the one click installer for windows. Once I extracted and copied it over the exisiting files and re-ran the update_windows.bat it fixed the accelerate library issue and installed the correct 0.22 version.

Maybe this works for you guys too ?

**Comment by o0oradaro0o** [comment]
> 

This fixed the issue for me with ease. Thank you for commenting.

**Comment by Sqrlly** [comment]
Just updated after a few weeks (because it takes a long time and usually a hassle to get working afterwards) and now getting this bug too.  Reinstalling from one-click isn't a fix for this update bug.  Updates take me a hour.  Full installs are over six hours.  And I don't want to install it over my existing one and wipe out my logs and stuff.

**Comment by Sqrlly** [comment]
Actual fix from https://www.reddit.com/r/Oobabooga/comments/15yzfgl/error_running_ooba/ :

pip install accelerate==0.21.0

I ran this right from the oobabooga_windows folder I was sitting in after getting the error.
