### ISSUE TITLE
Models won't download/run

### ISSUE THREAD

**Issue by Atoli** [oobabooga/text-generation-webui#3656]
### Describe the bug

Newer version of oogabooga fails to download models every time, immediately skips the file and goes to the next, so when you are "done" you will have an incomplete model that won't load. 
Downloading manually won't work either. 
GGML models won't run.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Try to download a large model via oogabooga.
It will fail to connect and skip it, leading to an incomplete model download that won't work.

### Screenshot

Models skipped:

![3](https://github.com/oobabooga/text-generation-webui/assets/43733214/fa3c10c5-6ba7-4d90-906f-9060bc1b85f9)

Incomplete models failing to load (obviously):

![2](https://github.com/oobabooga/text-generation-webui/assets/43733214/fd35a64f-3f3c-4925-96a6-7b21468571d9)

Error if try to run a manual download model:

![1](https://github.com/oobabooga/text-generation-webui/assets/43733214/26621c63-502c-4266-ac1a-8c1b2361b1fc)

Will even run into an out of memory problem, 12GB VRAM is more than enough for 13B checkpoints:

![Capture](https://github.com/oobabooga/text-generation-webui/assets/43733214/822fc7cd-ae8e-44f0-b98d-7551ce32220e)

### Logs

GPTQ models give this error:

```shell
`File “F:\oobabooga_windows\text-generation-webui\modules\ui_model_menu.py”, line 185, in load_model_wrapper

shared.model, shared.tokenizer = load_model(shared.model_name, loader)

File “F:\oobabooga_windows\text-generation-webui\modules\models.py”, line 79, in load_model

output = load_func_map[loader](model_name)

File “F:\oobabooga_windows\text-generation-webui\modules\models.py”, line 154, in huggingface_loader

model = model.cuda()

File “F:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py”, line 2003, in cuda

return super().cuda(*args, **kwargs)
`
```

GGML models will give this error:

````shell
Traceback (most recent call last):
  File "C:\oobabooga_windows\text-generation-webui\modules\callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "C:\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 127, in generate
    for completion_chunk in completion_chunks:
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp_cuda\llama.py", line 944, in _create_completion
    for token in self.generate(
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp_cuda\llama.py", line 764, in generate
    self.eval(tokens)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp_cuda\llama.py", line 483, in eval
    return_code = llama_cpp.llama_eval(
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp_cuda\llama_cpp.py", line 712, in llama_eval
    return _lib.llama_eval(ctx, tokens, n_tokens, n_past, n_threads)
OSError: exception: access violation writing 0x00000000000008C0`
```


### System Info

```shell
Windows 10.
16GB RAM.
Nvidia RTX 3060 12GB VRAM.
Offline local Oogabooga.
```

**Comment by alam234** [comment]
I have the same problem as well for all of the model i tried loading. Model that i've manage to download are : 
- fangloveskari_ORCA_LLaMA_70B_QLoRA
- TheBloke_CodeLlama-13B-oasst-sft-v10-GPTQ
- TheBloke_WizardCoder-Python-34B-V1.0-GPTQ

### System Info

```shell
Windows 11.
16GB RAM.
Nvidia RTX 3050 12GB VRAM.
Offline local Oogabooga.
```

**Comment by sammcj** [comment]
Have you tried cloning the model repo into your models directory and loading it that way?

If so - and it still doesn't work - perhaps the model is broken.

I'd suggest seeking general help on either:

- Subreddit: https://www.reddit.com/r/oobabooga/
- Discord: https://discord.gg/jwZCF2dPQN
