### ISSUE TITLE
PAD Error on training CodeLlama-13B-Instruct using Transformers

### ISSUE THREAD

**Issue by hypersniper05** [oobabooga/text-generation-webui#3690]
### Describe the bug

I am using [https://huggingface.co/TheBloke/CodeLlama-13B-Instruct-fp16](https://huggingface.co/TheBloke/CodeLlama-13B-Instruct-fp16) and Transformers loader to fine-tune. **After** the first run, I the following error "See Log"

The only walk around is to redownload the model from Huggingface. 

Is anyone else experiencing this?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1.Load the Model in Transformers
-load-in-4bit
-use_double_quant
-trust-remote-code

2. Train and when training starts interrupt.

3. Try to continue training. `Error occurs Here`

### Logs

```shell
`2023-08-25 18:02:23 WARNING:Using the following 4-bit params: {'load_in_4bit': True, 'bnb_4bit_compute_dtype': torch.float16, 'bnb_4bit_quant_type': 'nf4', 'bnb_4bit_use_double_quant': True}
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 3/3 [01:02<00:00, 20.81s/it]
2023-08-25 18:03:27 WARNING:models\CodeLlama-13B-Instruct-fp16-ALT\tokenizer_config.json is different from the original LlamaTokenizer file. It is either customized or outdated.
2023-08-25 18:03:27 WARNING:models\CodeLlama-13B-Instruct-fp16-ALT\special_tokens_map.json is different from the original LlamaTokenizer file. It is either customized or outdated.
2023-08-25 18:03:27 INFO:Loaded the model in 63.66 seconds.

Model reloaded OK, continue with training.
2023-08-25 18:03:27 INFO:Getting model ready...
2023-08-25 18:03:27 INFO:Preparing for training...
2023-08-25 18:03:27 INFO:Creating LoRA model...
2023-08-25 18:03:36 INFO:Starting training...
Training 'llama' model using (v, o) projections
Trainable params: 26,214,400 (0.3914 %), All params: 6,698,357,760 (Model: 6,672,143,360)
2023-08-25 18:03:37 INFO:Log file 'train_dataset_sample.json' created in the 'logs' directory.
Using pad_token, but it is not set yet.
Exception in thread Thread-20 (threaded_run):
Traceback (most recent call last):
  File "D:\AI\oobabooga_windows\installer_files\env\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\AI\oobabooga_windows\installer_files\env\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\AI\oobabooga_windows\text-generation-webui\modules\training.py", line 655, in threaded_run
    trainer.train()
  File "D:\AI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\trainer.py", line 1555, in train
    return inner_training_loop(
  File "D:\AI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\trainer.py", line 1815, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "D:\AI\oobabooga_windows\installer_files\env\lib\site-packages\accelerate\data_loader.py", line 384, in __iter__
    current_batch = next(dataloader_iter)
  File "D:\AI\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\data\dataloader.py", line 633, in __next__
    data = self._next_data()
  File "D:\AI\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\data\dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\AI\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "D:\AI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\data\data_collator.py", line 45, in __call__
    return self.torch_call(features)
  File "D:\AI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\data\data_collator.py", line 732, in torch_call
    batch = self.tokenizer.pad(examples, return_tensors="pt", pad_to_multiple_of=self.pad_to_multiple_of)
  File "D:\AI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py", line 3059, in pad
    padding_strategy, _, max_length, _ = self._get_padding_truncation_strategies(
  File "D:\AI\oobabooga_windows\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py", line 2507, in _get_padding_truncation_strategies
    raise ValueError(
ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.
2023-08-25 18:03:37 INFO:Training complete, saving...
2023-08-25 18:03:37 INFO:Training complete!`
```

### System Info

```shell
2 GPU's
3080ti/12GB
2070/8GB
```

**Comment by hypersniper05** [comment]
#3603
