### ISSUE TITLE
extension openai api langchain integration error：openai.error.APIError: UnboundLocalError("local variable 'tokens' referenced before assignment")

### ISSUE THREAD

**Issue by elven2016** [oobabooga/text-generation-webui#3723]
### Describe the bug

openai.error.APIError: UnboundLocalError("local variable 'tokens' referenced before assignment") {"error": {"message": "UnboundLocalError(\"local variable 'tokens' referenced before assignment\")", "code": 500, "type": "OpenAIError", "param": ""}} 500 {'error': {'message': 'UnboundLocalError("local variable \'tokens\' referenced before assignment")', 'code': 500, 'type': 'OpenAIError', 'param': ''}} {'Connection': 'close', 'Content-Length': '150', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Origin, Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, Authorization', 'Access-Control-Allow-Methods': 'GET,HEAD,OPTIONS,POST,PUT', 'Access-Control-Allow-Origin': '*', 'Content-Type': 'application/json', 'Date': 'Mon, 28 Aug 2023 08:14:40 GMT', 'Server': 'BaseHTTP/0.6 Python/3.10.10'}

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

develop an simple app through langchain and webui exten openai api，from the chatbox input the question and the api returns this error
openai.error.APIError: UnboundLocalError("local variable 'tokens' referenced before assignment") {"error": {"message": "UnboundLocalError(\"local variable 'tokens' referenced before assignment\")", "code": 500, "type": "OpenAIError", "param": ""}} 500 {'error': {'message': 'UnboundLocalError("local variable \'tokens\' referenced before assignment")', 'code': 500, 'type': 'OpenAIError', 'param': ''}} {'Connection': 'close', 'Content-Length': '150', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Origin, Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, Authorization', 'Access-Control-Allow-Methods': 'GET,HEAD,OPTIONS,POST,PUT', 'Access-Control-Allow-Origin': '*', 'Content-Type': 'application/json', 'Date': 'Mon, 28 Aug 2023 08:14:40 GMT', 'Server': 'BaseHTTP/0.6 Python/3.10.10'}

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/16677082/a7d84831-1298-4192-b2d3-b388c75d6d31)

### Logs

```shell
Traceback (most recent call last):
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/home/elven/finreport/finapp/app.py", line 182, in <module>
    main()
  File "/home/elven/finreport/finapp/app.py", line 120, in main
    handle_userinput(user_question)
  File "/home/elven/finreport/finapp/app.py", line 82, in handle_userinput
    response = st.session_state.conversation({'question': user_question})
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/langchain/chains/base.py", line 282, in __call__
    raise e
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/langchain/chains/base.py", line 276, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/langchain/chains/conversational_retrieval/base.py", line 141, in _call
    answer = self.combine_docs_chain.run(
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/langchain/chains/base.py", line 480, in run
    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/langchain/chains/base.py", line 282, in __call__
    raise e
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/langchain/chains/base.py", line 276, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/langchain/chains/combine_documents/base.py", line 105, in _call
    output, extra_return_dict = self.combine_docs(
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/langchain/chains/combine_documents/stuff.py", line 171, in combine_docs
    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/langchain/chains/llm.py", line 255, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/langchain/chains/base.py", line 282, in __call__
    raise e
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/langchain/chains/base.py", line 276, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/langchain/chains/llm.py", line 91, in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/langchain/chains/llm.py", line 101, in generate
    return self.llm.generate_prompt(
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/langchain/chat_models/base.py", line 414, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/langchain/chat_models/base.py", line 309, in generate
    raise e
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/langchain/chat_models/base.py", line 299, in generate
    self._generate_with_cache(
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/langchain/chat_models/base.py", line 446, in _generate_with_cache
    return self._generate(
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 345, in _generate
    response = self.completion_with_retry(
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 278, in completion_with_retry
    return _completion_with_retry(**kwargs)
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 276, in _completion_with_retry
    return self.client.create(**kwargs)
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/home/elven/miniconda3/envs/finreport/lib/python3.10/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.APIError: UnboundLocalError("local variable 'tokens' referenced before assignment") {"error": {"message": "UnboundLocalError(\"local variable 'tokens' referenced before assignment\")", "code": 500, "type": "OpenAIError", "param": ""}} 500 {'error': {'message': 'UnboundLocalError("local variable \'tokens\' referenced before assignment")', 'code': 500, 'type': 'OpenAIError', 'param': ''}} {'Connection': 'close', 'Content-Length': '150', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Origin, Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, Authorization', 'Access-Control-Allow-Methods': 'GET,HEAD,OPTIONS,POST,PUT', 'Access-Control-Allow-Origin': '*', 'Content-Type': 'application/json', 'Date': 'Mon, 28 Aug 2023 08:14:40 GMT', 'Server': 'BaseHTTP/0.6 Python/3.10.10'}
```

### System Info

```shell
ubuntu22.04
python 3.10.6
torch 2.0.1
lagnchain-0.0.274
```

**Comment by matatonic** [comment]
Can you enable the OPENEDAI_DEBUG=1 environment variable and restart the server and share the logs after reproducing this? pastebin is also fine if the logs are very long. Thanks for the report!
