### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by iamtheelfqueen** [oobabooga/text-generation-webui#374]
### Describe the bug

I'm trying to load the CPU-only version through conda. Everything went fine, but when I tried to run python server.py I got the 'AssertionError: Torch not compiled with CUDA enabled' message. Traceback says it has something to do with line 221 in __init__.py of cuda, but when I checked the line is just a comment... any potential fixes? 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Install through python following CPU-only version steps
Install pygmalion model
Run python server.py
Receive error 

### Screenshot

![pythonservererror](https://user-images.githubusercontent.com/128113237/225809311-1427a653-e0ea-49c5-802f-6945399e5c89.PNG)

### Logs

```shell
(textgen) C:\Users\[username]\text-generation-webui\text-generation-webui>python server.py
Loading pygmalion-6b...
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:49<00:00, 24.55s/it]
Traceback (most recent call last):
  File "C:\Users\[username]\text-generation-webui\text-generation-webui\server.py", line 215, in <module>
	shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\[username]\text-generation-webui\text-generation-webui\modules\models.py", line 50, in load_model
	model = AutoModelForCausalLM.from_pretrained(Path(f"models/{shared.model_name}"), low_cpu_mem_usage=True, torch_dtype=torch.bfloat16 if shared.args.bf16 else torch.float16).cuda()
  File "C:\Users\[username]\.conda\envs\textgen\lib\site-packages\torch\nn\modules\module.py", line 749, in cuda
	return self._apply(lambda t: t.cuda(device))
  File "C:\Users\[username]\.conda\envs\textgen\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
	module._apply(fn)
  File "C:\Users\[username]\.conda\envs\textgen\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
	module._apply(fn)
  File "C:\Users\[username]\.conda\envs\textgen\lib\site-packages\torch\nn\modules\module.py", line 664, in _apply
	param_applied = fn(param)
  File "C:\Users\[username]\.conda\envs\textgen\lib\site-packages\torch\nn\modules\module.py", line 749, in <lambda>
	return self._apply(lambda t: t.cuda(device))
  File "C:\Users\[username]\.conda\envs\textgen\lib\site-packages\torch\cuda\__init__.py", line 221, in _lazy_init
	raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

(textgen) C:\Users\[username]\text-generation-webui\text-generation-webui>python server.py
```

### System Info

```shell
Windows 10, AMD Gpu (Radeon RX 5700 XT)
```

**Comment by oobabooga** [comment]
Try python server.py --cpu

**Comment by iamtheelfqueen** [comment]
That works, thank you so much!

**Comment by Toby1364** [comment]
this didn't work for me does anyone know a different solution?
