### ISSUE TITLE
4-bit inference on Google Colab

### ISSUE THREAD

**Issue by YongeBai** [oobabooga/text-generation-webui#375]
### Describe the bug

follow the instruction listed here
https://github.com/oobabooga/text-generation-webui/wiki/LLaMA-model#4-bit-mode

for 4-bit inference, however when running
`!python server.py --model llama-13b-hf --gptq-bits 4 --no-stream`

results in 

```
/content/text-generation-webui
Loading llama-13b-hf...
Loading model ...
Traceback (most recent call last):
  File "/content/text-generation-webui/server.py", line 215, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/content/text-generation-webui/modules/models.py", line 93, in load_model
    model = load_quantized(model_name)
  File "/content/text-generation-webui/modules/GPTQ_loader.py", line 55, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.gptq_bits)
  File "/content/text-generation-webui/repositories/GPTQ-for-LLaMa/llama.py", line 245, in load_quant
    model.load_state_dict(torch.load(checkpoint))
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
```

Has anyone had this issue or know what the problem is?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://colab.research.google.com/drive/1G8dmKAZDzJftTTxhpy3EIMANkIR9PcU9#scrollTo=rb4DHYYubn49

run the notebook

### Logs

```shell
/content/text-generation-webui
Loading llama-13b-hf...
Loading model ...
Traceback (most recent call last):
  File "/content/text-generation-webui/server.py", line 215, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/content/text-generation-webui/modules/models.py", line 93, in load_model
    model = load_quantized(model_name)
  File "/content/text-generation-webui/modules/GPTQ_loader.py", line 55, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.gptq_bits)
  File "/content/text-generation-webui/repositories/GPTQ-for-LLaMa/llama.py", line 245, in load_quant
    model.load_state_dict(torch.load(checkpoint))
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
```

### System Info

```shell
Google Colab notebook
```

**Comment by mouchourider** [comment]
If you're still looking for a fix (or anyone else), you just need to download again the quantized version of the model.

**Comment by Enferlain** [comment]
Dunno why but it doesn't work for me even when I download quantized models. 

```
Loading llama-13b-hf-int4...
Could not find the quantized model in .pt or .safetensors format, exiting...
```

Tried 2 other ones and says the same.
