### ISSUE TITLE
Issue with own data

### ISSUE THREAD

**Issue by tripurarisingh1** [oobabooga/text-generation-webui#3751]
### Describe the bug

trying to trained own model with plan text and getting below error:

To create a public link, set `share=True` in `launch()`.
2023-08-30 13:27:41 WARNING:LoRA training has only currently been validated for LLaMA, OPT, GPT-J, and GPT-NeoX models. (Found model type: NoneType)
Traceback (most recent call last):
  File "C:\Users\Tripurari.Singh\AppData\Roaming\Python\Python311\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tripurari.Singh\AppData\Roaming\Python\Python311\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tripurari.Singh\AppData\Roaming\Python\Python311\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tripurari.Singh\AppData\Roaming\Python\Python311\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tripurari.Singh\AppData\Roaming\Python\Python311\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\anyio\to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\anyio\_backends\_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\anyio\_backends\_asyncio.py", line 754, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tripurari.Singh\AppData\Roaming\Python\Python311\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "D:\LLaMA-2\text-generation-webui\modules\training.py", line 317, in do_train
    shared.tokenizer.pad_token_id = 0
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'pad_token_id'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

[txt.txt](https://github.com/oobabooga/text-generation-webui/files/12473196/txt.txt)

This is the data sample file.

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/132330976/2eabb6ea-9bb6-4450-a437-074e91a80c22)

### Logs

```shell
No.
```

### System Info

```shell
Processor	12th Gen Intel(R) Core(TM) i5-1235U, 1300 Mhz, 10 Core(s), 12 Logical Processor(s)
```

**Comment by tripurarisingh1** [comment]
Can you please provide me sample txt file as well so that we can modify according.

**Comment by tripurarisingh1** [comment]
Trying to trained model from text file and getting this error:

To create a public link, set `share=True` in `launch()`.
2023-08-31 11:30:22 WARNING:LoRA training has only currently been validated for LLaMA, OPT, GPT-J, and GPT-NeoX models. (Found model type: NoneType)

AttributeError: 'NoneType' object has no attribute 'pad_token_id'
