### ISSUE TITLE
superbooga failed to start

### ISSUE THREAD

**Issue by kikoferrer** [oobabooga/text-generation-webui#3762]
### Describe the bug

I reinstalled textgen and got this error for superbooga. It used to work for me. Please check log to see what's wrong. I tried pip install with the missing module but it could not be found.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Start textgen with superbooga

### Logs

```shell
2023-08-31 08:46:32 ERROR:Failed to load the extension "superbooga".
Traceback (most recent call last):
  File "/home/chupz22/text-generation-webui/modules/extensions.py", line 35, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "/home/chupz22/text-generation-webui/extensions/superbooga/script.py", line 23, in <module>
    collector = make_collector()
  File "/home/chupz22/text-generation-webui/extensions/superbooga/chromadb.py", line 117, in make_collector
    return ChromaCollector(embedder)
  File "/home/chupz22/text-generation-webui/extensions/superbooga/chromadb.py", line 40, in __init__
    self.collection = self.chroma_client.create_collection(name="context", embedding_function=embedder.embed)
  File "/home/chupz22/venv/textgen/lib/python3.10/site-packages/chromadb/api/local.py", line 69, in create_collection
    res = self._db.create_collection(name, metadata, get_or_create)
  File "/home/chupz22/venv/textgen/lib/python3.10/site-packages/chromadb/db/duckdb.py", line 86, in create_collection
    dupe_check = self.get_collection(name)
  File "/home/chupz22/venv/textgen/lib/python3.10/site-packages/chromadb/db/duckdb.py", line 104, in get_collection
    res = self._conn.execute(f"""SELECT * FROM collections WHERE name = ?""", [name]).fetchall()
duckdb.InvalidInputException: Invalid Input Error: Required module 'pandas.core.arrays.arrow.dtype' failed to import, due to the following Python exception:
ModuleNotFoundError: No module named 'pandas.core.arrays.arrow.dtype'
```

### System Info

```shell
Linux Mint 21
NVIDIA 3060 12gb VRAM
```

**Comment by dominiczy** [comment]
Same, maybe a pandas update that no longer includes this type by default?

**Comment by dominiczy** [comment]
Pretty sure it's the Pandas Array change listed here: https://pandas.pydata.org/docs/whatsnew/v2.1.0.html#backwards-incompatible-api-changes
Probably need to pin a previous version of Pandas?

**Comment by SmoothBrainApe** [comment]
Which version of pandas should I install? Sorry I am not that experienced yet.

**Comment by RandomInternetPreson** [comment]
I had this issue too :c

**Comment by RandomInternetPreson** [comment]
This is how I fixed it after doing the windows one click install:

Changed line 222-224 of the webui.py script and ran the start_windows.bat to this to uninstall pandas:

def launch_webui():
    os.chdir('text-generation-webui')
    run_cmd(f"pip uninstall pandas", environment=True)
    
then changed line 222-224 to this to install a version that worked with superbooga (ran the start_windows.bat file again):
def launch_webui():
    os.chdir('text-generation-webui')
    run_cmd(f"pip install pandas==2.0.3", environment=True)
    
then changed the lines in webui.py back to their original lines and can load up supberbooga just fine

**Comment by KewkLW** [comment]
Just change requirements.txt and run cmd_windows/cmd_linux or whatever os you're on. Also, make sure you're installing the requirements.txt in the extensions/superbooga dir and make sure you're in the env already.

pandas

to

pandas==2.0.3

**Comment by ZeusLT** [comment]
> Just change requirements.txt and run update_windows/update_linux or whatever os you're on. Also, make sure you're installing the requirements.txt in the extensions/superbooga dir and make sure you're in the env already.
> 
> pandas
> 
> to
> 
> pandas==2.0.3

how do you properly enter the venv? It never seems to work for me (windows)

**Comment by funkyman228** [comment]
> > Just change requirements.txt and run update_windows/update_linux or whatever os you're on. Also, make sure you're installing the requirements.txt in the extensions/superbooga dir and make sure you're in the env already.
> > pandas
> > to
> > pandas==2.0.3
> 
> how do you properly enter the venv? It never seems to work for me (windows)
open the cmd_windows.bat

**Comment by truedat101** [comment]
@ZeusLT  you can run the appropriate cmd_PLATFORM.sh script to get into your conda environment/venv.  For example, I ran ./cmd_linux.sh to get into my environment.  Then I did pip uninstall pandas, and pip install pandas==2.0.3.

**Comment by truedat101** [comment]
Also worth mentioning, the chromadb version should be 0.3.18

Reference: https://github.com/oobabooga/text-generation-webui/blob/main/extensions/superbooga/requirements.txt

Simply changing the Pandas version to 2.0.3 won't necessarily fix the error.

I still don't understand the point of having an extension installer that doesn't seem to install the requirements.

**Comment by revolvedai** [comment]
> Also worth mentioning, the chromadb version should be 0.3.18
> 
> Reference: https://github.com/oobabooga/text-generation-webui/blob/main/extensions/superbooga/requirements.txt
> 
> Simply changing the Pandas version to 2.0.3 won't necessarily fix the error.
> 
> I still don't understand the point of having an extension installer that doesn't seem to install the requirements.

Have to agree with this, it makes no sense. Everytime I reinstall, update, or change something around I have to deal with this chromadb superbooger.
