### ISSUE TITLE
Not generating text

### ISSUE THREAD

**Issue by Lost-Saint** [oobabooga/text-generation-webui#3776]
### Describe the bug

when i type in hello in the prompt it doesnt do anything

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

i Downloaded miniconda create a env whit this command `conda create -n textgen python=3.10.8` follow the quide
[guide](https://github.com/oobabooga/text-generation-webui#manual-installation-using-conda) with only cpu with this `pip install -r requirements.txt` cause cpu AVCX2 and finally `python server.py`.

then install a model it loaded and then type hello

### Screenshot

![screenshot1](https://github.com/oobabooga/text-generation-webui/assets/85581209/da5365db-7c3c-4e9a-aee5-f8eeb39f4ead)
![screenshot2](https://github.com/oobabooga/text-generation-webui/assets/85581209/143b0b13-edd1-449e-bc08-c4d68332d669)

### Logs

```shell
2023-08-31 19:06:42 INFO:Loading Nous-Hermes-13B-GPTQ...
2023-08-31 19:06:42 INFO:The AutoGPTQ params are: {'model_basename': 'model', 'device': 'cpu', 'use_triton': False, 'inject_fused_attention': True, 'inject_fused_mlp': True, 'use_safetensors': True, 'trust_remote_code': False, 'max_memory': None, 'quantize_config': None, 'use_cuda_fp16': True, 'disable_exllama': False}
2023-08-31 19:06:42 WARNING:Exllama kernel is not installed, reset disable_exllama to True. This may because you installed auto_gptq using a pre-build wheel on Windows, in which exllama_kernels are not compiled. To use exllama_kernels to further speedup inference, you can re-install auto_gptq from source.
2023-08-31 19:06:42 WARNING:CUDA kernels for auto_gptq are not installed, this will result in very slow inference speed. This may because:
1. You disabled CUDA extensions compilation by setting BUILD_CUDA_EXT=0 when install auto_gptq from source.
2. You are using pytorch without CUDA support.
3. CUDA and nvcc are not installed in your device.
2023-08-31 19:06:42 WARNING:CUDA extension not installed.
2023-08-31 19:06:50 WARNING:skip module injection for FusedLlamaMLPForQuantizedModel not support integrate without triton yet.
2023-08-31 19:06:50 WARNING:models/Nous-Hermes-13B-GPTQ/tokenizer_config.json is different from the original LlamaTokenizer file. It is either customized or outdated.
2023-08-31 19:06:50 WARNING:models/Nous-Hermes-13B-GPTQ/special_tokens_map.json is different from the original LlamaTokenizer file. It is either customized or outdated.
2023-08-31 19:06:50 INFO:Loaded the model in 7.50 seconds.

Traceback (most recent call last):
  File "/home/user/Downloads/text-generation-webui/modules/callbacks.py", line 56, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "/home/user/Downloads/text-generation-webui/modules/text_generation.py", line 321, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/auto_gptq/modeling/_base.py", line 442, in generate
    with torch.inference_mode(), torch.amp.autocast(device_type=self.device.type):
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/auto_gptq/modeling/_base.py", line 431, in device
    device = [d for d in self.hf_device_map.values() if d not in {'cpu', 'disk'}][0]
IndexError: list index out of range
Output generated in 0.23 seconds (0.00 tokens/s, 0 tokens, context 37, seed 1152805250)
```

### System Info

```shell
os: fedora linux 38
gpu: no 
cpu:Intel i9-10850K
ram: 32gb
```

**Comment by FALKONPS** [comment]
I face the same problem on both my Windows machine and Linux server. I believe this is a bug or there may be something missing.
![image](https://github.com/oobabooga/text-generation-webui/assets/36137098/f29cb7dd-2244-4212-b278-883209813dcc)

**Comment by sammcj** [comment]
Hey I see you're not using a GPU but are trying to load a GPTQ model which are made for GPUs.

Try downloading and using a GGUF model which can be used by CPUs instead.
