### ISSUE TITLE
Tokenizer class CodeLlamaTokenizer does not exist or is not currently imported.

### ISSUE THREAD

**Issue by lighteternal** [oobabooga/text-generation-webui#3781]
### Describe the bug

I downloaded the [CodeLlama-34b-instruct ](https://huggingface.co/codellama/CodeLlama-34b-Instruct-hf)model and was about to finetune it. 
I get a `ValueError: Tokenizer class CodeLlamaTokenizer does not exist or is not currently imported.` error after the checkpoint shards are loaded. 

I have the latest version of the repo. 

Is it possible that `[text-generation-webui](https://github.com/oobabooga/text-generation-webui/tree/main)/[modules](https://github.com/oobabooga/text-generation-webui/tree/main/modules)
/models.py` needs updating?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Download  [CodeLlama-34b-instruct ](https://huggingface.co/codellama/CodeLlama-34b-Instruct-hf)
2. Try loading it.
3. The error will appear on the terminal (see screenshot).

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/22905968/be8f0c1e-e677-477d-8109-7c913703c7e5)

### Logs

```shell
2023-09-01 15:35:57 INFO:Loading codellama_CodeLlama-34b-Instruct-hf...
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 7/7 [04:18<00:00, 36.97s/it]
2023-09-01 15:40:17 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/home/d.papadopoulos/text-generation-webui/one-click-installers/text-generation-webui/modules/models.py", line 104, in load_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
  File "/home/d.papadopoulos/text-generation-webui/one-click-installers/installer_files/env/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 724, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class CodeLlamaTokenizer does not exist or is not currently imported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/d.papadopoulos/text-generation-webui/one-click-installers/text-generation-webui/modules/ui_model_menu.py", line 195, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/home/d.papadopoulos/text-generation-webui/one-click-installers/text-generation-webui/modules/models.py", line 87, in load_model
    tokenizer = load_tokenizer(model_name, model)
  File "/home/d.papadopoulos/text-generation-webui/one-click-installers/text-generation-webui/modules/models.py", line 110, in load_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
  File "/home/d.papadopoulos/text-generation-webui/one-click-installers/installer_files/env/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 724, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class CodeLlamaTokenizer does not exist or is not currently imported.
```

### System Info

```shell
AWS instance
```

**Comment by lighteternal** [comment]
Solving my own issue, after reading the model card:

```
Model Use
To use this model, please make sure to install transformers from main until the next version is released:

pip install git+https://github.com/huggingface/transformers.git@main accelerate
```

So essentially, either wait for next HF version or install manually from the above.
