### ISSUE TITLE
CAnnot open open Keeps failing after numerous tries and github fixes

### ISSUE THREAD

**Issue by timastras** [oobabooga/text-generation-webui#3793]
Here is what command prompt outputs:

Traceback (most recent call last):
  File "C:\dev\oobabooga_windows\text-generation-webui\modules\ui_model_menu.py", line 196, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "C:\dev\oobabooga_windows\text-generation-webui\modules\models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "C:\dev\oobabooga_windows\text-generation-webui\modules\models.py", line 140, in huggingface_loader
    config = AutoConfig.from_pretrained(path_to_model, trust_remote_code=shared.args.trust_remote_code)
  File "C:\dev\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\configuration_auto.py", line 1007, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\dev\oobabooga_windows\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 620, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\dev\oobabooga_windows\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 675, in _get_config_dict
    resolved_config_file = cached_file(
  File "C:\dev\oobabooga_windows\installer_files\env\lib\site-packages\transformers\utils\hub.py", line 399, in cached_file
    raise EnvironmentError(
OSError: models\Llama-2-7b does not appear to have a file named config.json. Checkout 'https://huggingface.co/models\Llama-2-7b/None' for available files.

**Comment by sammcj** [comment]
For general support I'd suggest either:

- Subreddit: [reddit.com/r/oobabooga](https://www.reddit.com/r/oobabooga/) 
- Discord: [discord.gg/jwZCF2dPQN](https://discord.gg/jwZCF2dPQN)

**Comment by seyfer** [comment]
I have the same issue right now

**Comment by seyfer** [comment]
@timastras this is the answer https://github.com/oobabooga/text-generation-webui/issues/3246#issuecomment-1646623974
