### ISSUE TITLE
Can't load GGUF model

### ISSUE THREAD

**Issue by Ege-P** [oobabooga/text-generation-webui#3803]
### Describe the bug

When try to load the model in the UI, getting error: AttributeError: 'LlamaCppModel' object has no attribute 'model'

(Also for more knowledge, what are these stands for: Q#_K_S_L etc. )

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Download "llama-2-70b-chat.Q5_K_S.gguf" into ***\text-generation-webui\models folder.
Start the web UI, select the model, and try to load.

### Screenshot

![Text generation web UI - Google Chrome 5 09 2023 12_22_21](https://github.com/oobabooga/text-generation-webui/assets/64746057/c5d25636-c36f-4cfb-9992-0937e429ab83)
![image](https://github.com/oobabooga/text-generation-webui/assets/64746057/ffaec6ce-7800-45ea-8ab1-3060fe543330)

### Logs

```shell
2023-09-05 12:19:13 INFO:Loading llama-2-70b-chat.Q5_K_S.gguf...
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4090, compute capability 8.9
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4090, compute capability 8.9
2023-09-05 12:19:14 INFO:llama.cpp weights detected: models\llama-2-70b-chat.Q5_K_S.gguf
2023-09-05 12:19:14 INFO:Cache capacity is 0 bytes
llama.cpp: loading model from models\llama-2-70b-chat.Q5_K_S.gguf
error loading model: unknown (magic, version) combination: 00000000, 00000000; is this really a GGML file?
llama_load_model_from_file: failed to load model
2023-09-05 12:19:14 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "D:\ALLAI\AIChatUI\text-generation-webui\modules\ui_model_menu.py", line 196, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "D:\ALLAI\AIChatUI\text-generation-webui\modules\models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "D:\ALLAI\AIChatUI\text-generation-webui\modules\models.py", line 247, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
  File "D:\ALLAI\AIChatUI\text-generation-webui\modules\llamacpp_model.py", line 105, in from_pretrained
    result.model = Llama(**params)
  File "D:\ALLAI\AIChatUI\installer_files\env\lib\site-packages\llama_cpp_ggml_cuda\llama.py", line 328, in __init__
    assert self.model is not None
AssertionError

Exception ignored in: <function LlamaCppModel.__del__ at 0x000001C2A3F2A290>
Traceback (most recent call last):
  File "D:\ALLAI\AIChatUI\text-generation-webui\modules\llamacpp_model.py", line 57, in __del__
    self.model.__del__()
AttributeError: 'LlamaCppModel' object has no attribute 'model'
```

### System Info

```shell
Windows 10
NVIDIA GeForce RTX 4090
amd ryzen 9 7950x
```

**Comment by Ph0rk0z** [comment]
U got the wrong llama.cpp probably

**Comment by Ege-P** [comment]
I freshly installed the UI with a one-click installer. What do I need to do to update the llama.cpp? (In modules there are llama_attn_hijack, llamacpp_hf and llamacpp_model .py files there)

**Comment by Ph0rk0z** [comment]
```
# llama-cpp-python without GPU support
llama-cpp-python==0.1.83; platform_system != "Windows"
https://github.com/abetlen/llama-cpp-python/releases/download/v0.1.83/llama_cpp_python-0.1.83-cp310-cp310-win_amd64.whl; platform_system == "Windows"

# llama-cpp-python with CUDA support
https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/releases/download/textgen-webui/llama_cpp_python_cuda-0.1.83+cu117-cp310-cp310-win_amd64.whl; platform_system == "Windows"
https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/releases/download/textgen-webui/llama_cpp_python_cuda-0.1.83+cu117-cp310-cp310-linux_x86_64.whl; platform_system == "Linux" and platform_machine == "x86_64"
```

**Comment by Ege-P** [comment]
I'm not sure what to do with this. I assume the one I'm looking for is
"https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/releases/download/textgen-webui/llama_cpp_python_cuda-0.1.83+cu117-cp310-cp310-win_amd64.whl; platform_system == "Windows""

but it doesnt open a site. also I checked the jllll's github page and try to dwonload webui wheels but requirements already satisfied.

**Comment by Ph0rk0z** [comment]
Uninstall the GGML one.

**Comment by Ege-P** [comment]
I removed the:
llama_cpp_ggml
llama_cpp_ggml_cuda
llama_cpp_python_ggml_cuda-0.1.78+cu117.dist-info
llama_cpp_python_ggml-0.1.78+cpuavx2.dist-info

Files from installer_files\env\Lib\site-packages. Still getting the same error

**Comment by Ph0rk0z** [comment]
Hmm.. I think you have to uninstall the actual packages inside the VENV and install only the GGUF one. 

I also can't use GGML + GGUF installed at the same time or I get similar errors.

on linux its `source venv/bin/activate` to load the environment and then pip install/pip uninstall to work that.

**Comment by Ege-P** [comment]
I looked at it but it kinda destroyed everything. Ended up re-installing everything freshly and did the same things above. Can you write it step by step to what to do (including commands if possible)? Or should I wait the one-click installer to be updated for gguf to work?

**Comment by Ph0rk0z** [comment]
It's supposed to work now. Just go into the venv as above and do pip install https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/releases/download/textgen-webui/llama_cpp_python_cuda-0.1.83+cu117-cp310-cp310-win_amd64.whl

**Comment by Ege-P** [comment]
Nope. Requirement already satisfied, and getting same error.

**Comment by Flanua** [comment]
> Hmm.. I think you have to uninstall the actual packages inside the VENV and install only the GGUF one.
> 
> I also can't use GGML + GGUF installed at the same time or I get similar errors.
> 
> on linux its `source venv/bin/activate` to load the environment and then pip install/pip uninstall to work that.

I can run GGML and GGUF models in Obaboga WEB UI (Latest current build) just fine and no errors. Just make sure GGUF model placed straight to the models root folder no need to create a folder for GGUF model or it won't load.

**Comment by Ege-P** [comment]
It is. 1 big file with .gguf extension right under models folder

**Comment by Flanua** [comment]
> It is. 1 big file with .gguf extension right under models folder

Maybe try to update Obaboga WEB UI update usually fix alot of problems though.

**Comment by Ege-P** [comment]
Re-installed and tried to use it in cpu mode but still same error

**Comment by Flanua** [comment]
> Re-installed and tried to use it in cpu mode but still same error

If you give me the link to your AI model I can download it and try to run it myself to see if your model can work on my end.

**Comment by Ege-P** [comment]
llama-2-70b-chat.Q5_K_S.gguf

**Comment by Flanua** [comment]
> [llama-2-70b-chat.Q5_K_S.gguf](https://huggingface.co/TheBloke/Llama-2-70B-chat-GGUF/tree/main)

Ok will download it and try after 40min need to finish downloading my falcon 180B model first. In hour or two I will let you know if your model is working on my end.

**Comment by Ph0rk0z** [comment]
>mbination: 00000000, 00000000; is this really a GGML file?

The model is fine, it's clearly loading with the old version and expecting GGML. For me too, I cannot use GGUF + GGML at the same time. I have to install one or the other. I thought it could be because I don't use the pre-compiled wheels. But for some reason you're having issues with those.

You have to go pip list inside your venv and then pip uninstall the llama_cpp_python that has GGML in it. Then restart textgen and it will load only GGUFs. As long as you don't remove normal llama_cpp or llama_cpp_cuda


pip uninstall llama_cpp_ggml
pip uninstall llama_cpp_ggml_cuda

**Comment by Flanua** [comment]
Ok I tested your model and I have same error as you on Obaboga WEB UI and in native Llama.cpp:

![888](https://github.com/oobabooga/text-generation-webui/assets/140022879/fa174191-f6eb-422a-9c6b-7754c09ff7a7)

![99999](https://github.com/oobabooga/text-generation-webui/assets/140022879/819ff866-3fcc-455d-9356-9174b054c566)

As far as I remember Magic number error not hard to fix and have something to do with incompatibility if my memory serves me well I was able to fix such error by updating my Obaboga WEB UI a a long time ago though and it was fixed for me. Also a bit older version of Llama.cpp might be able to run it though. I hope someone else helps you.

**Comment by Flanua** [comment]
> > mbination: 00000000, 00000000; is this really a GGML file?
> 
> The model is fine, it's clearly loading with the old version and expecting GGML. For me too, I cannot use GGUF + GGML at the same time. I have to install one or the other. I thought it could be because I don't use the pre-compiled wheels. But for some reason you're having issues with those.
> 
> You have to go pip list inside your venv and then pip uninstall the llama_cpp_python that has GGML in it. Then restart textgen and it will load only GGUFs. As long as you don't remove normal llama_cpp or llama_cpp_cuda
> 
> pip uninstall llama_cpp_ggml pip uninstall llama_cpp_ggml_cuda

But I can use GGML: Wizard-Vicuna-30B-Uncensored.ggmlv3.q8_0.bin + GGUF: synthia-70b-v1.1.Q8_0.gguf just fine. I have them both in my models folder in my Obaboga WEB UI (Latest build). though.

**Comment by Ph0rk0z** [comment]
It didn't work for me even though I renamed both versions to be the same as the wheels. I have both ggml_cuda and a cuda but it picks the wrong one and then I get an error same as the op. Could be linux or how I compiled them. I also use folders for GGUFs and I have no issues with that.

In ops screenshot it also errors inside llama_cpp_**ggml**_cuda

Really surprised bloke would mess up a quant, especially of one of the most common models.

**Comment by Flanua** [comment]
> mess up a quant

Could be a coolprint here though.

**Comment by Ege-P** [comment]
I get this error when I try to uninstall llama_cpp_ggml and other one. "WARNING: Skipping llama_cpp_ggml_cuda as it is not installed".
I download another gguf model and it successfully load. So I guess the problem was the model not the UI.

**Comment by Ph0rk0z** [comment]
GGUF models are only faster for me with nvlink patch and fully offloaded. Q5 going to need some CPU unless you have 3 cards and that's gonna be slow.

**Comment by Flanua** [comment]
To make it faster you need a lot of CPU cores with decent frequency. I'm using i9900KS 5Ghz CPU my responses like 20-30 tokens per sec on average.

**Comment by Ph0rk0z** [comment]
70b doesn't fit on 1 4090 so half (or more) of it is on CPU.

**Comment by Flanua** [comment]
> I'm using AMD Ryzen 9 7950X 16-Core Processor 4.50 GHz. But I dont understand why would I need to use CPU to make it faster. I'm using a 4090.

You can run 70B model on your 4090 70B model requires 75+GB of ram to run it. So your only option is to run it in CPU mode (you can also try to offload some layers to GPU for faster inference) if you have enough ddr ram available or you can use and increase windows swap file to run it which is even more slow.

**Comment by AG-w** [comment]
has anyone figure out what's wrong or it's in an eternal limbo that some of unlucky people just won't make it work?

**Comment by timothyallan** [comment]
I had to recompile llama-cpp-python with flags for my GPU on for it to be able to use my M2 GPU, not sure if it's the same issue with windows, but the error message was the same, as was the CPU loading working, but GPU not...
`CMAKE_ARGS="-DLLAMA_METAL=on"`
`pip install llama-cpp-python`

**Comment by AG-w** [comment]
I think I found a funny thing
in repo https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/

llama_cpp_python_cuda-0.2.6+cu117avx-cp310-cp310-win_amd64.whl
is for AVX
llama_cpp_python_cuda-0.2.6+cu117basic-cp310-cp310-win_amd64.whl
is for non AVX

Buuuuuuut
llama_cpp_python_cuda-0.2.6+cu117-cp310-cp310-win_amd64.whl
is actually for AVX2

**Comment by AG-w** [comment]
I think I found interesting thing
in repo https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/
in `textgen_webui`

`llama_cpp_python_cuda-0.2.6+cu117avx-cp310-cp310-win_amd64.whl`
is for AVX
`llama_cpp_python_cuda-0.2.6+cu117basic-cp310-cp310-win_amd64.whl`
is for non AVX
But
`llama_cpp_python_cuda-0.2.6+cu117-cp310-cp310-win_amd64.whl`
is actually for AVX2

I can manage to load model without CPU flag now
but I don't know why it still using CPU most of time and my CUDA usage remains low

**Comment by AG-w** [comment]
I'm not sure if it's related but in
`https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/blob/main/workflows.md`

it said `the wheels in the main repo are only built to support the default configuration of AVX2.`
that means beside CPU-only wheel, all the other wheel with AVX2 support don't have avx2 in file name

so I changed file name 
`llama_cpp_python_cuda-0.2.6+cu117-cp310-cp310-win_amd64.whl `
to 
`llama_cpp_python_cuda-0.2.6+cu117avx-cp310-cp310-win_amd64.whl`
and now model can load normally

that being said, I still don't know why cuda usage is low when not using cpu flag

also I think
`https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/releases/download/cpu/llama_cpp_python-0.2.6+cpuavx-cp310-cp310-win_amd64.whl`
is the actual CPU-only wheel?
the link in `requirements_noavx2.txt` actually point to a CUDA wheel with no avx support ?

**Comment by kenwud** [comment]
was this ever solved ?
im having a similar, but i think different error when trying to load a .gguf model
`
2023-09-27 08:23:58 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "E:\text-generation-webui-1.6.1\modules\ui_model_menu.py", line 198, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "E:\text-generation-webui-1.6.1\modules\models.py", line 78, in load_model
    output = load_func_map[loader](model_name)
  File "E:\text-generation-webui-1.6.1\modules\models.py", line 232, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
  File "E:\text-generation-webui-1.6.1\modules\llamacpp_model.py", line 90, in from_pretrained
    result.model = Llama(**params)
  File "E:\text-generation-webui-1.6.1\installer_files\env\lib\site-packages\llama_cpp_cuda\llama.py", line 332, in __init__
    self.model = llama_cpp.llama_load_model_from_file(
  File "E:\text-generation-webui-1.6.1\installer_files\env\lib\site-packages\llama_cpp_cuda\llama_cpp.py", line 434, in llama_load_model_from_file
    return _lib.llama_load_model_from_file(path_model, params)
OSError: [WinError -1073741795] Windows Error 0xc000001d

Exception ignored in: <function LlamaCppModel.__del__ at 0x000002780FA7CA60>
Traceback (most recent call last):
  File "E:\text-generation-webui-1.6.1\modules\llamacpp_model.py", line 49, in __del__
    self.model.__del__()
AttributeError: 'LlamaCppModel' object has no attribute 'model'
`
everything seems find it does quite a fine lines after 
`
2023-09-27 08:23:56 INFO:Loading MLewd-Chat-v2-13B.q5_k_m.gguf...
2023-09-27 08:23:56 INFO:llama.cpp weights detected: models\MLewd-Chat-v2-13B.q5_k_m.gguf
2023-09-27 08:23:56 INFO:Cache capacity is 0 bytes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce GTX 1060 6GB, compute capability 6.1
llama_model_loader: loaded meta data with 19 key-value pairs and 363 tensors from models\MLewd-Chat-v2-13B.q5_k_m.gguf (version GGUF V2 (latest))
llama_model_loader: - tensor    0:                token_embd.weight q5_K     [  5120, 32000,     1,     1 ]`

before it hits the problem mentioned at the beginning of my comment

**Comment by Malumen** [comment]
> has anyone figure out what's wrong or it's in an eternal limbo that some of unlucky people just won't make it work?
> 
> edit: if I force it on CPU then it manage to load, but same error when trying to use cuda

Same here, cannot get this to run.
