### ISSUE TITLE
error when training vicuna-v1.5

### ISSUE THREAD

**Issue by caterpillarpants** [oobabooga/text-generation-webui#3812]
### Describe the bug

Trying to train vicuna-7b-1.5, but get an error.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

bash update_linux.sh
bash start_linux.sh
choose lmsys-vicuna-7b-v1.5
under model loader I choose "transformers"
gpu vram 4000(really it's 8gb)
cpu ram 64000
check load-in-4bit, use_double_quant, trust-remote-code
load model
choose a small text file for the dataset and use default parameters.
hit "start LoRA training" button

### Logs

```shell
`2023-09-05 20:51:26 INFO:Loading raw text file dataset...
Traceback (most recent call last):
  File "/home/ana/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/ana/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/ana/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/ana/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "/home/ana/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/ana/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/ana/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/ana/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/ana/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "/home/ana/oobabooga_linux/text-generation-webui/modules/training.py", line 415, in do_train
    train_data = Dataset.from_list([tokenize(x) for x in text_chunks])
  File "/home/ana/oobabooga_linux/text-generation-webui/modules/training.py", line 415, in <listcomp>
    train_data = Dataset.from_list([tokenize(x) for x in text_chunks])
  File "/home/ana/oobabooga_linux/text-generation-webui/modules/training.py", line 333, in tokenize
    input_ids = encode(prompt, True)
  File "/home/ana/oobabooga_linux/text-generation-webui/modules/training.py", line 321, in encode
    result = shared.tokenizer.encode(text, truncation=True, max_length=cutoff_len)
  File "/home/ana/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2373, in encode
    encoded_inputs = self.encode_plus(
  File "/home/ana/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2781, in encode_plus
    return self._encode_plus(
  File "/home/ana/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 656, in _encode_plus
    first_ids = get_input_ids(text)
  File "/home/ana/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 623, in get_input_ids
    tokens = self.tokenize(text, **kwargs)
  File "/home/ana/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 208, in tokenize
    if tokens[0] == SPIECE_UNDERLINE and tokens[1] in self.all_special_tokens:
UnboundLocalError: local variable 'tokens' referenced before assignment
`
```

### System Info

```shell
running linux mint on i7, gtx 2070(8gb), 64ram.
```

**Comment by caterpillarpants** [comment]
this has been magically fixed! I think it was a dataset issue and not an issue with oobabooga, but I don't really know because I changed the dataset at the same time I updated ooba.
