### ISSUE TITLE
Unable to train LoRA on GPTQ Models

### ISSUE THREAD

**Issue by tqman** [oobabooga/text-generation-webui#3818]
### Describe the bug

While I was excited to see that with recent changes to Transformers, training LoRAs on GTPQ Models should now work, I've been unable to do so. I followed the instructions here:

https://github.com/oobabooga/text-generation-webui/issues/3655#issuecomment-1701264352

Even using the same model (TheBloke_Llama-2-7b-Chat-GPTQ), though I have tried others with the same result. I use --auto-devices, and the Transformers loader.

The training kicks off fine. I'm using a ~2MB raw text file as the input, and it estimates ~3100 steps to complete with the default settings. However, after 32 steps, I consistently get this error:

```
Traceback (most recent call last):
  File "/home/quark/miniconda3/envs/textgen-20230831/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/quark/miniconda3/envs/textgen-20230831/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/d/bitbot/text-generation-webui-20230831/modules/training.py", line 658, in threaded_run
    trainer.train()
  File "/home/quark/miniconda3/envs/textgen-20230831/lib/python3.10/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/home/quark/miniconda3/envs/textgen-20230831/lib/python3.10/site-packages/transformers/trainer.py", line 1916, in _inner_training_loop
    self.optimizer.step()
  File "/home/quark/miniconda3/envs/textgen-20230831/lib/python3.10/site-packages/accelerate/optimizer.py", line 132, in step
    self.scaler.step(self.optimizer, closure)
  File "/home/quark/miniconda3/envs/textgen-20230831/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 372, in step
    assert len(optimizer_state["found_inf_per_device"]) > 0, "No inf checks were recorded for this optimizer."
AssertionError: No inf checks were recorded for this optimizer.

```
Oobabooga then declares that the training is complete (probably some error handling to add there too I guess), but the resultant file is tiny and isn't loadable.

Searching on this error on Google gives me a lot of hits from Stable Diffusion LoRA training, and poking at it a little, I suspect this is sort of a generic error that pops out when the parameters to Torch are inconsistent. But I don't have any real experience with this toolchain, so I'm not really sure where to start with debugging it.

Would love any suggestions on what else to try or where to poke. I'm using the latest code on main on GH, and updated to all the latest requirements packages within the last 24 hours.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Using --auto-devices, us Transformers to load a GPTQ model and attempt to train a raw text file LoRA with it.

### Logs

```shell
Traceback (most recent call last):
  File "/home/quark/miniconda3/envs/textgen-20230831/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/quark/miniconda3/envs/textgen-20230831/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/d/bitbot/text-generation-webui-20230831/modules/training.py", line 658, in threaded_run
    trainer.train()
  File "/home/quark/miniconda3/envs/textgen-20230831/lib/python3.10/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/home/quark/miniconda3/envs/textgen-20230831/lib/python3.10/site-packages/transformers/trainer.py", line 1916, in _inner_training_loop
    self.optimizer.step()
  File "/home/quark/miniconda3/envs/textgen-20230831/lib/python3.10/site-packages/accelerate/optimizer.py", line 132, in step
    self.scaler.step(self.optimizer, closure)
  File "/home/quark/miniconda3/envs/textgen-20230831/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 372, in step
    assert len(optimizer_state["found_inf_per_device"]) > 0, "No inf checks were recorded for this optimizer."
AssertionError: No inf checks were recorded for this optimizer.
```

### System Info

```shell
WSL 2 under Windows 11 running Ubuntu 22.04 on an NVidia 3090-RTX.
```

**Comment by oobabooga** [comment]
Try updating and loading the model using the Transformers loader with both `auto-devices` and `disable_exllama` checked. https://github.com/oobabooga/text-generation-webui/commit/36c38d756137ee335b37430c4a14eada1e7ece2e
