### ISSUE TITLE
Allow for windows shortcut/links

### ISSUE THREAD

**Issue by Dariusz1989** [oobabooga/text-generation-webui#3819]
**Description**

Can we update the model browser logic so it can handle links/shortcuts in windows? I'd like to use folder shortcut and have it follow its path to the directory/load model from that location.
Would make managing models a lot easier than having to copy them all to 1 place.

**Comment by Flanua** [comment]
It would be nice to have web links visible in the chat because as soon as AI type them they are disappear and I can't copy them.

**Comment by missionfloyd** [comment]
You can use symlinks.
https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/mklink

E.g., 
```
mklink /d D:\text-generation-webui\models\TheBloke_Kimiko-v2-13B-GPTQ D:\TheBloke_Kimiko-v2-13B-GPTQ
```
![image](https://github.com/oobabooga/text-generation-webui/assets/4073789/b10686a7-c46d-4ed5-88f2-dbd8081f26b4)

`mklink` only works in cmd, not powershell.

**Comment by Dariusz1989** [comment]
@missionfloyd not sure, I don't think it works when I tried to use it via chat >
```
Traceback (most recent call last):
  File "K:\\AI\Meta\LLama2\Venv_text-generation-webui\lib\site-packages\transformers\configuration_utils.py", line 705, in _get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "K:\\AI\Meta\LLama2\Venv_text-generation-webui\lib\site-packages\transformers\configuration_utils.py", line 800, in _dict_from_json_file
    text = reader.read()
  File "C:\Program Files\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 12: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\\AI\Meta\LLama2\text-generation-webui_v2\modules\ui_model_menu.py", line 196, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "K:\\AI\Meta\LLama2\text-generation-webui_v2\modules\models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "K:\\AI\Meta\LLama2\text-generation-webui_v2\modules\models.py", line 140, in huggingface_loader
    config = AutoConfig.from_pretrained(path_to_model, trust_remote_code=shared.args.trust_remote_code)
  File "K:\\AI\Meta\LLama2\Venv_text-generation-webui\lib\site-packages\transformers\models\auto\configuration_auto.py", line 1007, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "K:\\AI\Meta\LLama2\Venv_text-generation-webui\lib\site-packages\transformers\configuration_utils.py", line 620, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "K:\\AI\Meta\LLama2\Venv_text-generation-webui\lib\site-packages\transformers\configuration_utils.py", line 708, in _get_config_dict
    raise EnvironmentError(
OSError: It looks like the config file at 'models\CodeLlama-13b - Shortcut.lnk' is not a valid JSON file.
```

**Comment by missionfloyd** [comment]
Symlinks, not shortcuts.
```
mklink /d [DESTINATION] [SOURCE]
```
