### ISSUE TITLE
llama-2-7b-hf local variable 'tokens' referenced before assignment

### ISSUE THREAD

**Issue by zwqjoy** [oobabooga/text-generation-webui#3840]
### Describe the bug

Exception occurred during processing of request from ('10.72.73.60', 61163)
10.72.73.60 - - [08/Sep/2023 06:10:39] "POST /api/v1/token-count HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/opt/conda/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/conda/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/opt/conda/lib/python3.10/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/opt/conda/lib/python3.10/http/server.py", line 420, in handle_one_request
    method()
  File "/home/work/text-generation-webui-main/extensions/api/blocking_api.py", line 180, in do_POST
    tokens = encode(body['prompt'])[0]
  File "/home/work/text-generation-webui-main/modules/text_generation.py", line 113, in encode
    input_ids = shared.tokenizer.encode(str(prompt), return_tensors='pt', add_special_tokens=add_special_tokens)
  File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2373, in encode
    encoded_inputs = self.encode_plus(
  File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2781, in encode_plus
    return self._encode_plus(
  File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 656, in _encode_plus
    first_ids = get_input_ids(text)
  File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 623, in get_input_ids
    tokens = self.tokenize(text, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 208, in tokenize
    if tokens[0] == SPIECE_UNDERLINE and tokens[1] in self.all_special_tokens:
UnboundLocalError: local variable 'tokens' referenced before assignment

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

llama-v2 is   hf-7b

python server.py --api --listen --model /home/work/text-generation-webui-main/models/llama-v2/

### Logs

```shell
To create a public link, set `share=True` in `launch()`.
10.72.73.60 - - [08/Sep/2023 06:10:39] "GET /api/v1/model HTTP/1.1" 200 -
10.72.73.60 - - [08/Sep/2023 06:10:39] "POST /api/v1/token-count HTTP/1.1" 200 -
10.72.73.60 - - [08/Sep/2023 06:10:39] "POST /api/v1/token-count HTTP/1.1" 200 -
10.72.73.60 - - [08/Sep/2023 06:10:39] "POST /api/v1/token-count HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('10.72.73.60', 61163)
10.72.73.60 - - [08/Sep/2023 06:10:39] "POST /api/v1/token-count HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/opt/conda/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/conda/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/opt/conda/lib/python3.10/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/opt/conda/lib/python3.10/http/server.py", line 420, in handle_one_request
    method()
  File "/home/work/text-generation-webui-main/extensions/api/blocking_api.py", line 180, in do_POST
    tokens = encode(body['prompt'])[0]
  File "/home/work/text-generation-webui-main/modules/text_generation.py", line 113, in encode
    input_ids = shared.tokenizer.encode(str(prompt), return_tensors='pt', add_special_tokens=add_special_tokens)
  File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2373, in encode
    encoded_inputs = self.encode_plus(
  File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2781, in encode_plus
    return self._encode_plus(
  File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 656, in _encode_plus
    first_ids = get_input_ids(text)
  File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 623, in get_input_ids
    tokens = self.tokenize(text, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 208, in tokenize
    if tokens[0] == SPIECE_UNDERLINE and tokens[1] in self.all_special_tokens:
UnboundLocalError: local variable 'tokens' referenced before assignment
----------------------------------------
```

### System Info

```shell
To create a public link, set `share=True` in `launch()`.
10.72.73.60 - - [08/Sep/2023 06:10:39] "GET /api/v1/model HTTP/1.1" 200 -
10.72.73.60 - - [08/Sep/2023 06:10:39] "POST /api/v1/token-count HTTP/1.1" 200 -
10.72.73.60 - - [08/Sep/2023 06:10:39] "POST /api/v1/token-count HTTP/1.1" 200 -
10.72.73.60 - - [08/Sep/2023 06:10:39] "POST /api/v1/token-count HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('10.72.73.60', 61163)
10.72.73.60 - - [08/Sep/2023 06:10:39] "POST /api/v1/token-count HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/opt/conda/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/conda/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/opt/conda/lib/python3.10/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/opt/conda/lib/python3.10/http/server.py", line 420, in handle_one_request
    method()
  File "/home/work/text-generation-webui-main/extensions/api/blocking_api.py", line 180, in do_POST
    tokens = encode(body['prompt'])[0]
  File "/home/work/text-generation-webui-main/modules/text_generation.py", line 113, in encode
    input_ids = shared.tokenizer.encode(str(prompt), return_tensors='pt', add_special_tokens=add_special_tokens)
  File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2373, in encode
    encoded_inputs = self.encode_plus(
  File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2781, in encode_plus
    return self._encode_plus(
  File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 656, in _encode_plus
    first_ids = get_input_ids(text)
  File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 623, in get_input_ids
    tokens = self.tokenize(text, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 208, in tokenize
    if tokens[0] == SPIECE_UNDERLINE and tokens[1] in self.all_special_tokens:
UnboundLocalError: local variable 'tokens' referenced before assignment
----------------------------------------
```

**Comment by TianYaDY** [comment]
同样的问题。

**Comment by TianYaDY** [comment]
2023-09-08 15:39:09 INFO:Loading raw text file dataset...
Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\textgen\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\ProgramData\anaconda3\envs\textgen\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\ProgramData\anaconda3\envs\textgen\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "D:\ProgramData\anaconda3\envs\textgen\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "D:\ProgramData\anaconda3\envs\textgen\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "D:\ProgramData\anaconda3\envs\textgen\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\ProgramData\anaconda3\envs\textgen\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\ProgramData\anaconda3\envs\textgen\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\ProgramData\anaconda3\envs\textgen\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "D:\Projects\text-generation-webui\modules\training.py", line 415, in do_train
    train_data = Dataset.from_list([tokenize(x) for x in text_chunks])
  File "D:\Projects\text-generation-webui\modules\training.py", line 415, in <listcomp>
    train_data = Dataset.from_list([tokenize(x) for x in text_chunks])
  File "D:\Projects\text-generation-webui\modules\training.py", line 333, in tokenize
    input_ids = encode(prompt, True)
  File "D:\Projects\text-generation-webui\modules\training.py", line 321, in encode
    result = shared.tokenizer.encode(text, truncation=True, max_length=cutoff_len)
  File "D:\ProgramData\anaconda3\envs\textgen\lib\site-packages\transformers\tokenization_utils_base.py", line 2373, in encode
    encoded_inputs = self.encode_plus(
  File "D:\ProgramData\anaconda3\envs\textgen\lib\site-packages\transformers\tokenization_utils_base.py", line 2781, in encode_plus
    return self._encode_plus(
  File "D:\ProgramData\anaconda3\envs\textgen\lib\site-packages\transformers\tokenization_utils.py", line 656, in _encode_plus
    first_ids = get_input_ids(text)
  File "D:\ProgramData\anaconda3\envs\textgen\lib\site-packages\transformers\tokenization_utils.py", line 623, in get_input_ids
    tokens = self.tokenize(text, **kwargs)
  File "D:\ProgramData\anaconda3\envs\textgen\lib\site-packages\transformers\models\llama\tokenization_llama.py", line 208, in tokenize
    if tokens[0] == SPIECE_UNDERLINE and tokens[1] in self.all_special_tokens:
UnboundLocalError: local variable 'tokens' referenced before assignment
