### ISSUE TITLE
Installation broken

### ISSUE THREAD

**Issue by Ionaut** [oobabooga/text-generation-webui#3846]
### Describe the bug

installation breaks because fastapi and elevenlabs require incompatible versions of pydantic.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

running install.bat

### Screenshot

![OogaBoogaInstallIssue](https://github.com/oobabooga/text-generation-webui/assets/8879570/f5a12e62-5ef2-4049-ba6e-41bb3c1140fb)

### Logs

```shell
Microsoft Windows [Version 10.0.22621.2215]
(c) Microsoft Corporation. All rights reserved.

D:\oobabooga-windows\installer_files>conda activate D:\oobabooga-windows\installer_files\env

(D:\oobabooga-windows\installer_files\env) D:\oobabooga-windows\installer_files>conda list
# packages in environment at D:\oobabooga-windows\installer_files\env:
#
# Name                    Version                   Build  Channel
absl-py                   1.4.0                    pypi_0    pypi
accelerate                0.21.0                   pypi_0    pypi
aiofiles                  23.1.0                   pypi_0    pypi
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
altair                    4.2.2                    pypi_0    pypi
annotated-types           0.5.0                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
asciitree                 0.3.3                    pypi_0    pypi
asttokens                 2.2.1                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     22.2.0                   pypi_0    pypi
auto-gptq                 0.4.1+cu117              pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
backoff                   2.2.1                    pypi_0    pypi
beautifulsoup4            4.12.2                   pypi_0    pypi
bitsandbytes              0.41.1                   pypi_0    pypi
blas                      2.116                       mkl    conda-forge
blas-devel                3.9.0              16_win64_mkl    conda-forge
brotlipy                  0.7.0                    pypi_0    pypi
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.12.7            h5b45459_0    conda-forge
cachetools                5.3.1                    pypi_0    pypi
certifi                   2022.12.7                pypi_0    pypi
cffi                      1.15.1                   pypi_0    pypi
charset-normalizer        3.1.0                    pypi_0    pypi
chromadb                  0.3.18                   pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
clickhouse-connect        0.6.6                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
cryptography              40.0.1                   pypi_0    pypi
ctransformers             0.2.22+cu117             pypi_0    pypi
cuda-cccl                 11.7.58                       0    nvidia/label/cuda-11.7.0
cuda-command-line-tools   11.7.0                        0    nvidia/label/cuda-11.7.0
cuda-compiler             11.7.0                        0    nvidia/label/cuda-11.7.0
cuda-cudart               11.7.60                       0    nvidia/label/cuda-11.7.0
cuda-cudart-dev           11.7.60                       0    nvidia/label/cuda-11.7.0
cuda-cuobjdump            11.7.50                       0    nvidia/label/cuda-11.7.0
cuda-cupti                11.7.50                       0    nvidia/label/cuda-11.7.0
cuda-cuxxfilt             11.7.50                       0    nvidia/label/cuda-11.7.0
cuda-documentation        11.7.50                       0    nvidia/label/cuda-11.7.0
cuda-libraries            11.7.0                        0    nvidia/label/cuda-11.7.0
cuda-libraries-dev        11.7.0                        0    nvidia/label/cuda-11.7.0
cuda-memcheck             11.7.50                       0    nvidia/label/cuda-11.7.0
cuda-nsight-compute       11.7.0                        0    nvidia/label/cuda-11.7.0
cuda-nvcc                 11.7.64                       0    nvidia/label/cuda-11.7.0
cuda-nvdisasm             11.7.50                       0    nvidia/label/cuda-11.7.0
cuda-nvml-dev             11.7.50                       0    nvidia/label/cuda-11.7.0
cuda-nvprof               11.7.50                       0    nvidia/label/cuda-11.7.0
cuda-nvprune              11.7.50                       0    nvidia/label/cuda-11.7.0
cuda-nvrtc                11.7.50                       0    nvidia/label/cuda-11.7.0
cuda-nvrtc-dev            11.7.50                       0    nvidia/label/cuda-11.7.0
cuda-nvtx                 11.7.50                       0    nvidia/label/cuda-11.7.0
cuda-nvvp                 11.7.50                       0    nvidia/label/cuda-11.7.0
cuda-runtime              11.7.0                        0    nvidia/label/cuda-11.7.0
cuda-sanitizer-api        11.7.50                       0    nvidia/label/cuda-11.7.0
cuda-toolkit              11.7.0                        0    nvidia/label/cuda-11.7.0
cuda-tools                11.7.0                        0    nvidia/label/cuda-11.7.0
cuda-visual-tools         11.7.0                        0    nvidia/label/cuda-11.7.0
cycler                    0.11.0                   pypi_0    pypi
datasets                  2.14.5                   pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
deep-translator           1.9.2                    pypi_0    pypi
dill                      0.3.6                    pypi_0    pypi
diskcache                 5.6.1                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
docopt                    0.6.2                    pypi_0    pypi
duckdb                    0.8.1                    pypi_0    pypi
einops                    0.6.1                    pypi_0    pypi
elevenlabs                0.2.25                   pypi_0    pypi
elevenlabslib             0.6.0                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
exceptiongroup            1.1.2                    pypi_0    pypi
executing                 1.2.0                    pypi_0    pypi
exllama                   0.0.10+cu117             pypi_0    pypi
fastapi                   0.95.2                   pypi_0    pypi
fasteners                 0.18                     pypi_0    pypi
ffmpeg                    1.4                      pypi_0    pypi
ffmpeg-python             0.2.0                    pypi_0    pypi
ffmpy                     0.3.0                    pypi_0    pypi
filelock                  3.11.0                   pypi_0    pypi
flask                     2.2.3                    pypi_0    pypi
flask-cloudflared         0.0.14                   pypi_0    pypi
flexgen                   0.1.7                    pypi_0    pypi
fonttools                 4.39.3                   pypi_0    pypi
freetype                  2.12.1               h546665d_1    conda-forge
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.4.0                 pypi_0    pypi
future                    0.18.3                   pypi_0    pypi
git                       2.40.0               h57928b3_1    conda-forge
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.32                   pypi_0    pypi
google-auth               2.22.0                   pypi_0    pypi
google-auth-oauthlib      1.0.0                    pypi_0    pypi
gptq-for-llama            0.1.0+cu117              pypi_0    pypi
gradio                    3.33.1                   pypi_0    pypi
gradio-client             0.2.5                    pypi_0    pypi
grpcio                    1.56.2                   pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
hnswlib                   0.7.0                    pypi_0    pypi
httpcore                  0.17.0                   pypi_0    pypi
httptools                 0.6.0                    pypi_0    pypi
httpx                     0.24.0                   pypi_0    pypi
huggingface-hub           0.16.4                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
importlib-metadata        6.8.0                    pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
intel-openmp              2023.0.0         h57928b3_25922    conda-forge
ipython                   8.15.0                   pypi_0    pypi
itsdangerous              2.1.2                    pypi_0    pypi
jedi                      0.18.2                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.3.1                    pypi_0    pypi
jpeg                      9e                   hcfcfb64_3    conda-forge
jsonschema                4.17.3                   pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
lcms2                     2.15                 ha5c8aab_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libblas                   3.9.0              16_win64_mkl    conda-forge
libcblas                  3.9.0              16_win64_mkl    conda-forge
libcublas                 11.10.1.25                    0    nvidia/label/cuda-11.7.0
libcublas-dev             11.10.1.25                    0    nvidia/label/cuda-11.7.0
libcufft                  10.7.2.50                     0    nvidia/label/cuda-11.7.0
libcufft-dev              10.7.2.50                     0    nvidia/label/cuda-11.7.0
libcurand                 10.2.10.50                    0    nvidia/label/cuda-11.7.0
libcurand-dev             10.2.10.50                    0    nvidia/label/cuda-11.7.0
libcusolver               11.3.5.50                     0    nvidia/label/cuda-11.7.0
libcusolver-dev           11.3.5.50                     0    nvidia/label/cuda-11.7.0
libcusparse               11.7.3.50                     0    nvidia/label/cuda-11.7.0
libcusparse-dev           11.7.3.50                     0    nvidia/label/cuda-11.7.0
libdeflate                1.17                 hcfcfb64_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libhwloc                  2.9.0                h51c2c0f_0    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
liblapack                 3.9.0              16_win64_mkl    conda-forge
liblapacke                3.9.0              16_win64_mkl    conda-forge
libnpp                    11.7.3.21                     0    nvidia/label/cuda-11.7.0
libnpp-dev                11.7.3.21                     0    nvidia/label/cuda-11.7.0
libnvjpeg                 11.7.2.34                     0    nvidia/label/cuda-11.7.0
libnvjpeg-dev             11.7.2.34                     0    nvidia/label/cuda-11.7.0
libpng                    1.6.39               h19919ed_0    conda-forge
libsqlite                 3.40.0               hcfcfb64_0    conda-forge
libtiff                   4.5.0                hf8721a0_2    conda-forge
libuv                     1.44.2               h8ffe710_0    conda-forge
libwebp-base              1.3.0                hcfcfb64_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.10.4               hc3477c8_0    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
linkify-it-py             2.0.0                    pypi_0    pypi
llama-cpp-python          0.1.77                   pypi_0    pypi
llama-cpp-python-cuda     0.1.77+cu117             pypi_0    pypi
llvmlite                  0.39.1                   pypi_0    pypi
lz4                       4.3.2                    pypi_0    pypi
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markdown                  3.4.4                    pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mdit-py-plugins           0.3.3                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2022.1.0           h6a75c08_874    conda-forge
mkl-devel                 2022.1.0           h57928b3_875    conda-forge
mkl-include               2022.1.0           h6a75c08_874    conda-forge
monotonic                 1.6                      pypi_0    pypi
more-itertools            9.1.0                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
msys2-conda-epoch         20160418                      1    conda-forge
multidict                 6.0.4                    pypi_0    pypi
multiprocess              0.70.14                  pypi_0    pypi
networkx                  3.1                      pypi_0    pypi
ninja                     1.11.1               h91493d7_0    conda-forge
nltk                      3.8.1                    pypi_0    pypi
nsight-compute            2022.2.0.13                   0    nvidia/label/cuda-11.7.0
num2words                 0.5.12                   pypi_0    pypi
numba                     0.56.4                   pypi_0    pypi
numcodecs                 0.11.0                   pypi_0    pypi
numpy                     1.23.5                   pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
openai-whisper            20230314                 pypi_0    pypi
openjpeg                  2.5.0                ha2aaf27_2    conda-forge
openssl                   3.1.0                hcfcfb64_0    conda-forge
orjson                    3.8.10                   pypi_0    pypi
packaging                 23.0                     pypi_0    pypi
pandas                    2.1.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pathtools                 0.1.2                    pypi_0    pypi
peft                      0.5.0.dev0               pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    10.0.0                   pypi_0    pypi
pip                       23.0.1                   pypi_0    pypi
pluggy                    1.2.0                    pypi_0    pypi
posthog                   2.4.2                    pypi_0    pypi
prompt-toolkit            3.0.38                   pypi_0    pypi
protobuf                  4.23.4                   pypi_0    pypi
psutil                    5.9.4                    pypi_0    pypi
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pulp                      2.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
py-cpuinfo                9.0.0                    pypi_0    pypi
pyarrow                   11.0.0                   pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pydantic                  2.3.0                    pypi_0    pypi
pydantic-core             2.6.3                    pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.15.0                   pypi_0    pypi
pyopenssl                 23.1.1                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
pysocks                   1.7.1                    pypi_0    pypi
pytest                    7.2.2                    pypi_0    pypi
python                    3.10.9          h4de0772_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python-dotenv             1.0.0                    pypi_0    pypi
python-multipart          0.0.6                    pypi_0    pypi
python_abi                3.10                    3_cp310    conda-forge
pytorch                   2.0.0           py3.10_cuda11.7_cudnn8_0    pytorch
pytorch-cuda              11.7                 h16d0643_3    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.3                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
quant-cuda                0.0.0                    pypi_0    pypi
regex                     2023.3.23                pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
responses                 0.18.0                   pypi_0    pypi
rouge                     1.0.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
rwkv                      0.7.3                    pypi_0    pypi
safetensors               0.3.1                    pypi_0    pypi
scikit-learn              1.2.2                    pypi_0    pypi
scipy                     1.11.2                   pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
sentence-transformers     2.2.2                    pypi_0    pypi
sentencepiece             0.1.99                   pypi_0    pypi
sentry-sdk                1.29.2                   pypi_0    pypi
setproctitle              1.3.2                    pypi_0    pypi
setuptools                67.6.1                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.0                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
sounddevice               0.4.6                    pypi_0    pypi
soundfile                 0.12.1                   pypi_0    pypi
soupsieve                 2.4                      pypi_0    pypi
speechrecognition         3.10.0                   pypi_0    pypi
stack-data                0.6.2                    pypi_0    pypi
starlette                 0.27.0                   pypi_0    pypi
sympy                     1.11.1                   pypi_0    pypi
tbb                       2021.8.0             h91493d7_0    conda-forge
tensorboard               2.14.0                   pypi_0    pypi
tensorboard-data-server   0.7.1                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tiktoken                  0.3.1                    pypi_0    pypi
tk                        8.6.12               h8ffe710_0    conda-forge
tokenizers                0.13.3                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
torch                     2.0.0                    pypi_0    pypi
torchaudio                2.0.0                    pypi_0    pypi
torchvision               0.15.0                   pypi_0    pypi
tqdm                      4.66.1                   pypi_0    pypi
traitlets                 5.9.0                    pypi_0    pypi
transformers              4.32.0.dev0              pypi_0    pypi
typing                    3.7.4.3                  pypi_0    pypi
typing-extensions         4.7.1                    pypi_0    pypi
typing_extensions         4.5.0              pyha770c72_0    conda-forge
tzdata                    2023.3                   pypi_0    pypi
uc-micro-py               1.0.1                    pypi_0    pypi
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urllib3                   1.26.15                  pypi_0    pypi
uvicorn                   0.21.1                   pypi_0    pypi
vc                        14.3                hb6edc58_10    conda-forge
vs2015_runtime            14.34.31931         h4c5c07a_10    conda-forge
wandb                     0.15.10                  pypi_0    pypi
watchfiles                0.19.0                   pypi_0    pypi
wcwidth                   0.2.6                    pypi_0    pypi
websockets                11.0.2                   pypi_0    pypi
werkzeug                  2.2.3                    pypi_0    pypi
wheel                     0.40.0                   pypi_0    pypi
win-inet-pton             1.1.0                    pypi_0    pypi
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xxhash                    3.2.0                    pypi_0    pypi
xz                        5.2.6                h8d14728_0    conda-forge
yarl                      1.8.2                    pypi_0    pypi
zarr                      2.14.2                   pypi_0    pypi
zipp                      3.16.0                   pypi_0    pypi
zstandard                 0.21.0                   pypi_0    pypi
zstd                      1.5.2                h12be248_6    conda-forge

(D:\oobabooga-windows\installer_files\env) D:\oobabooga-windows\installer_files>D:\oobabooga-windows\installer_files\envpip install pydantic==1.7
'D:\oobabooga-windows\installer_files\envpip' is not recognized as an internal or external command,
operable program or batch file.

(D:\oobabooga-windows\installer_files\env) D:\oobabooga-windows\installer_files>pip install pydantic==1.7
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting pydantic==1.7
  Downloading pydantic-1.7-py3-none-any.whl (106 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.5/106.5 kB 1.2 MB/s eta 0:00:00
Installing collected packages: pydantic
  Attempting uninstall: pydantic
    Found existing installation: pydantic 2.3.0
    Uninstalling pydantic-2.3.0:
      Successfully uninstalled pydantic-2.3.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastapi 0.95.2 requires pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2, but you have pydantic 1.7 which is incompatible.
elevenlabs 0.2.25 requires pydantic>=2.0, but you have pydantic 1.7 which is incompatible.
chromadb 0.3.18 requires pydantic>=1.9, but you have pydantic 1.7 which is incompatible.
Successfully installed pydantic-1.7

(D:\oobabooga-windows\installer_files\env) D:\oobabooga-windows\installer_files>pip install pydantic==1.9
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting pydantic==1.9
  Downloading pydantic-1.9.0-cp310-cp310-win_amd64.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 11.3 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=3.7.4.3 in d:\oobabooga-windows\installer_files\env\lib\site-packages (from pydantic==1.9) (4.7.1)
Installing collected packages: pydantic
  Attempting uninstall: pydantic
    Found existing installation: pydantic 1.7
    Uninstalling pydantic-1.7:
      Successfully uninstalled pydantic-1.7
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
elevenlabs 0.2.25 requires pydantic>=2.0, but you have pydantic 1.9.0 which is incompatible.
Successfully installed pydantic-1.9.0

(D:\oobabooga-windows\installer_files\env) D:\oobabooga-windows\installer_files>pip install pydantic==2.0
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting pydantic==2.0
  Downloading pydantic-2.0-py3-none-any.whl (355 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 355.6/355.6 kB 2.5 MB/s eta 0:00:00
Requirement already satisfied: annotated-types>=0.4.0 in d:\oobabooga-windows\installer_files\env\lib\site-packages (from pydantic==2.0) (0.5.0)
Requirement already satisfied: typing-extensions>=4.6.1 in d:\oobabooga-windows\installer_files\env\lib\site-packages (from pydantic==2.0) (4.7.1)
Collecting pydantic-core==2.0.1
  Downloading pydantic_core-2.0.1-cp310-none-win_amd64.whl (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 24.0 MB/s eta 0:00:00
Installing collected packages: pydantic-core, pydantic
  Attempting uninstall: pydantic-core
    Found existing installation: pydantic_core 2.6.3
    Uninstalling pydantic_core-2.6.3:
      Successfully uninstalled pydantic_core-2.6.3
  Attempting uninstall: pydantic
    Found existing installation: pydantic 1.9.0
    Uninstalling pydantic-1.9.0:
      Successfully uninstalled pydantic-1.9.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastapi 0.95.2 requires pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2, but you have pydantic 2.0 which is incompatible.
Successfully installed pydantic-2.0 pydantic-core-2.0.1
```

### System Info

```shell
AMD Ryzen 5 5600X 6-Core Processor 3.70 GHz
RAM 16.0 GB
Nvidia RTX3060 12GB VRAM
```

**Comment by redtier100x** [comment]
I just updated and I'm now getting errors about pydantic as well.

**Comment by karljoaquin** [comment]
Same here. Updated and now ImportError: cannot import name "Undefined" from "pydantic.fields"

**Comment by DFXLuna** [comment]
> Same here. Updated and now ImportError: cannot import name "Undefined" from "pydantic.fields"

Same. Here's my log output upon running after updating:
```
Traceback (most recent call last):
  File "/home/egrant/text-gen/oobabooga_linux/text-generation-webui/server.py", line 12, in <module>
    import gradio as gr
  File "/home/egrant/text-gen/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/home/egrant/text-gen/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/components.py", line 32, in <module>
    from fastapi import UploadFile
  File "/home/egrant/text-gen/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/home/egrant/text-gen/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/fastapi/applications.py", line 16, in <module>
    from fastapi import routing
  File "/home/egrant/text-gen/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/fastapi/routing.py", line 22, in <module>
    from fastapi import params
  File "/home/egrant/text-gen/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/fastapi/params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (/home/egrant/text-gen/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/pydantic/fields.py)
```

**Comment by ukrolelo** [comment]
+1

**Comment by Bahamut-ru** [comment]
`ImportError: cannot import name 'Undefined' from 'pydantic.fields'`
+2
PC and notebook. =)

**Comment by DFXLuna** [comment]
Did a little more digging, elevenlabs tts 0.2.25 updated to pydantic 2.0, which is incompatible with fastapi, that requires pydantic < 2.0

You should be able to workaround this by changing the contents of `extensions/elevenlabs/requirements.txt` to
```
elevenlabs==0.2.24
```

or just removing the elevenlabs folder all together and then re-run the update script.

**Comment by Ionaut** [comment]
Changing the requirement didn't work I suspect because that still requires pydantic <2.0. Got OogaBooga back up by removing the elevenlabs tts extension folder a running update.

**Comment by oobabooga** [comment]
See https://github.com/oobabooga/text-generation-webui/issues/3874 for the solution.
