### ISSUE TITLE
Installation failed due to incompatible versions of pydantic.

### ISSUE THREAD

**Issue by Habutiii** [oobabooga/text-generation-webui#3850]
### Describe the bug

Installation failed due to incompatible versions of pydantic.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Install text-generation-webui in pinokio which runs the [json installation script](https://github.com/cocktailpeanut/text-generation-webui.pinokio/blob/main/install.json) . However will fail at the end

### Logs

```shell
Traceback (most recent call last):
  File "/home/egrant/text-gen/oobabooga_linux/text-generation-webui/server.py", line 12, in <module>
    import gradio as gr
  File "/home/egrant/text-gen/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/home/egrant/text-gen/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/gradio/components.py", line 32, in <module>
    from fastapi import UploadFile
  File "/home/egrant/text-gen/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/home/egrant/text-gen/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/fastapi/applications.py", line 16, in <module>
    from fastapi import routing
  File "/home/egrant/text-gen/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/fastapi/routing.py", line 22, in <module>
    from fastapi import params
  File "/home/egrant/text-gen/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/fastapi/params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (/home/egrant/text-gen/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/pydantic/fields.py)
```

### System Info

```shell
GPU: NVIDIA RTX 4060
OS: Win11 Home
```

**Comment by 0Tick** [comment]
#3799 Seems to fix this

**Comment by xpgx1** [comment]
It does indeed. For all more _**rookie users**_ who happen to have been affected: You need to manually edit the "requirements.txt", line 2 - change it to "fastapi==0.103.1".

**Comment by alicat22** [comment]
I updated fastapi:
![image](https://github.com/oobabooga/text-generation-webui/assets/86847834/8fd6c503-ceac-4f7f-ba0a-85bab8328280)
But now I'm receiving the following error after attempting to load a model (see below). When selecting a model, it will infinitely load and then "Something went wrong. Connection errored out."
```py
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
127.0.0.1 - - [09/Sep/2023 12:06:59] code 404, message Not Found
127.0.0.1 - - [09/Sep/2023 12:06:59] "GET /api HTTP/1.1" 404 -
2023-09-09 12:07:02 ERROR:Task exception was never retrieved
future: <Task finished name='gi7envw1pb8_254' coro=<Queue.process_events() done, defined at H:\AI\ooba\installer_files\env\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [], 'event_data'...on_hash': 'gi7envw1pb8'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing>
Traceback (most recent call last):
  File "H:\AI\ooba\installer_files\env\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "H:\AI\ooba\installer_files\env\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "H:\AI\ooba\installer_files\env\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "H:\AI\ooba\installer_files\env\lib\site-packages\pydantic\main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [], 'event_data'...on_hash': 'gi7envw1pb8'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
2023-09-09 12:07:02 ERROR:Task exception was never retrieved
future: <Task finished name='gi7envw1pb8_252' coro=<Queue.process_events() done, defined at H:\AI\ooba\installer_files\env\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [], 'event_data'...on_hash': 'gi7envw1pb8'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing>
Traceback (most recent call last):
  File "H:\AI\ooba\installer_files\env\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "H:\AI\ooba\installer_files\env\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "H:\AI\ooba\installer_files\env\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "H:\AI\ooba\installer_files\env\lib\site-packages\pydantic\main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [], 'event_data'...on_hash': 'gi7envw1pb8'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
2023-09-09 12:07:02 ERROR:Task exception was never retrieved
future: <Task finished name='gi7envw1pb8_251' coro=<Queue.process_events() done, defined at H:\AI\ooba\installer_files\env\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [], 'event_data'...on_hash': 'gi7envw1pb8'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing>
Traceback (most recent call last):
  File "H:\AI\ooba\installer_files\env\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "H:\AI\ooba\installer_files\env\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "H:\AI\ooba\installer_files\env\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "H:\AI\ooba\installer_files\env\lib\site-packages\pydantic\main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [], 'event_data'...on_hash': 'gi7envw1pb8'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
2023-09-09 12:07:03 ERROR:Task exception was never retrieved
future: <Task finished name='gi7envw1pb8_255' coro=<Queue.process_events() done, defined at H:\AI\ooba\installer_files\env\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [None, 'You', 'A...on_hash': 'gi7envw1pb8'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing>
Traceback (most recent call last):
  File "H:\AI\ooba\installer_files\env\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "H:\AI\ooba\installer_files\env\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "H:\AI\ooba\installer_files\env\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "H:\AI\ooba\installer_files\env\lib\site-packages\pydantic\main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [None, 'You', 'A...on_hash': 'gi7envw1pb8'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
2023-09-09 12:07:18 ERROR:Task exception was never retrieved
future: <Task finished name='dp2hxmqvf76_228' coro=<Queue.process_events() done, defined at H:\AI\ooba\installer_files\env\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [200, False, 0, ...on_hash': 'dp2hxmqvf76'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing>
Traceback (most recent call last):
  File "H:\AI\ooba\installer_files\env\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "H:\AI\ooba\installer_files\env\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "H:\AI\ooba\installer_files\env\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "H:\AI\ooba\installer_files\env\lib\site-packages\pydantic\main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [200, False, 0, ...on_hash': 'dp2hxmqvf76'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
```

OS: Windows 10
Browser: Chrome
ooba commit: 4affa088214b59a8bbefbd0f956523a396486bd7
pip list: https://gist.github.com/alicat22/9f46262baeae5c1ee458c99c8822047e

**Comment by 0Tick** [comment]
changing gradio_client==0.5.0 should fixe this (atleast it did in my install)

**Comment by alicat22** [comment]
> changing gradio_client==0.5.0 should fixe this (atleast it did in my install)

After changing the requirements.txt to include `gradio_client==0.5.0`, I received the following error:
```py
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "H:\AI\ooba\installer_files\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "H:\AI\ooba\installer_files\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "H:\AI\ooba\installer_files\env\lib\site-packages\fastapi\applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "H:\AI\ooba\installer_files\env\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "H:\AI\ooba\installer_files\env\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "H:\AI\ooba\installer_files\env\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "H:\AI\ooba\installer_files\env\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "H:\AI\ooba\installer_files\env\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "H:\AI\ooba\installer_files\env\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "H:\AI\ooba\installer_files\env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "H:\AI\ooba\installer_files\env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "H:\AI\ooba\installer_files\env\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "H:\AI\ooba\installer_files\env\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "H:\AI\ooba\installer_files\env\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "H:\AI\ooba\installer_files\env\lib\site-packages\fastapi\routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "H:\AI\ooba\installer_files\env\lib\site-packages\fastapi\routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "H:\AI\ooba\installer_files\env\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "H:\AI\ooba\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\AI\ooba\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "H:\AI\ooba\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "H:\AI\ooba\installer_files\env\lib\site-packages\gradio\routes.py", line 282, in api_info
    return gradio.blocks.get_api_info(config, serialize)  # type: ignore
  File "H:\AI\ooba\installer_files\env\lib\site-packages\gradio\blocks.py", line 555, in get_api_info
    serializer = serializing.COMPONENT_MAPPING[type]()
KeyError: 'dataset'
```
I then ran a `pip install --upgrade gradio` and this resolved my issue!

Thank you!

**Comment by oobabooga** [comment]
See https://github.com/oobabooga/text-generation-webui/issues/3874 for the solution.
