### ISSUE TITLE
pip3 install-r. \requirements.txt

### ISSUE THREAD

**Issue by joseph16388** [oobabooga/text-generation-webui#3856]
### Describe the bug

Every time you reinstall a failed installation using pip3 install-r. \requirements.txt, the previously installed contents are not cached and you need to install from start again

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

pip3 install-r. \requirements.txt to install dependencies

### Logs

```shell
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\win11\anaconda3\envs\llama2\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\win11\anaconda3\envs\llama2\lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "C:\Users\win11\anaconda3\envs\llama2\lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\Users\win11\anaconda3\envs\llama2\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "C:\Users\win11\anaconda3\envs\llama2\lib\http\client.py", line 465, in read
    s = self.fp.read(amt)
  File "C:\Users\win11\anaconda3\envs\llama2\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\win11\anaconda3\envs\llama2\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\win11\anaconda3\envs\llama2\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\win11\anaconda3\envs\llama2\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\win11\anaconda3\envs\llama2\lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "C:\Users\win11\anaconda3\envs\llama2\lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "C:\Users\win11\anaconda3\envs\llama2\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "C:\Users\win11\anaconda3\envs\llama2\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 491, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "C:\Users\win11\anaconda3\envs\llama2\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 453, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "C:\Users\win11\anaconda3\envs\llama2\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Users\win11\anaconda3\envs\llama2\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 293, in __init__
    super().__init__(
  File "C:\Users\win11\anaconda3\envs\llama2\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "C:\Users\win11\anaconda3\envs\llama2\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\win11\anaconda3\envs\llama2\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\Users\win11\anaconda3\envs\llama2\lib\site-packages\pip\_internal\operations\prepare.py", line 538, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Users\win11\anaconda3\envs\llama2\lib\site-packages\pip\_internal\operations\prepare.py", line 609, in _prepare_linked_requirement
    local_file = unpack_url(
  File "C:\Users\win11\anaconda3\envs\llama2\lib\site-packages\pip\_internal\operations\prepare.py", line 166, in unpack_url
    file = get_http_url(
  File "C:\Users\win11\anaconda3\envs\llama2\lib\site-packages\pip\_internal\operations\prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "C:\Users\win11\anaconda3\envs\llama2\lib\site-packages\pip\_internal\network\download.py", line 147, in __call__
    for chunk in chunks:
  File "C:\Users\win11\anaconda3\envs\llama2\lib\site-packages\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "C:\Users\win11\anaconda3\envs\llama2\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "C:\Users\win11\anaconda3\envs\llama2\lib\site-packages\pip\_vendor\urllib3\response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\win11\anaconda3\envs\llama2\lib\site-packages\pip\_vendor\urllib3\response.py", line 560, in read
    with self._error_catcher():
  File "C:\Users\win11\anaconda3\envs\llama2\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\win11\anaconda3\envs\llama2\lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='objects.githubusercontent.com', port=443): Read timed out.
```

### System Info

```shell
GPU:nvidia 3080Ti
```

**Comment by bet0x** [comment]
This is not related to the project but more like an timeout issue as listed on your last line. Add --default-timeout=100 to your pip command.

**Comment by absint93** [comment]
> This is not related to the project but more like an timeout issue as listed on your last line. Add --default-timeout=100 to your pip command.

How add this command?
