### ISSUE TITLE
transformers error loading Llama

### ISSUE THREAD

**Issue by Fenfel** [oobabooga/text-generation-webui#387]
### Describe the bug

After installing the new transformers webui does not load models 
changing the tokenizer did not help

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

python server.py --auto-devices --model LLaMA-13B --gptq-bits 4 --notebook

### Logs

```shell
(textgen) C:\Users\anton\Desktop\SD\text-generation-webui>python server.py --auto-devices --model LLaMA-13B --gptq-bits 4 --notebook
Loading LLaMA-13B...
CUDA extension not installed.
Traceback (most recent call last):
  File "C:\Users\anton\Desktop\SD\text-generation-webui\server.py", line 215, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\anton\Desktop\SD\text-generation-webui\modules\models.py", line 95, in load_model
    model = load_quantized(model_name)
  File "C:\Users\anton\Desktop\SD\text-generation-webui\modules\GPTQ_loader.py", line 55, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.gptq_bits)
  File "C:\Users\anton\Desktop\SD\text-generation-webui\repositories\GPTQ-for-LLaMa\llama.py", line 220, in load_quant
    from transformers import LLaMAConfig, LLaMAForCausalLM
ImportError: cannot import name 'LLaMAConfig' from 'transformers' (C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\transformers\__init__.py)
```

### System Info

```shell
RTX 3070ti
Windows 10 home (not activated)
32GB Ram
```

**Comment by RandomInternetPreson** [comment]
https://github.com/oobabooga/text-generation-webui/issues/322#issuecomment-1472624995

I had the same problem, you need to change the capitalization of the phrase "LLaMAConfig"

**Comment by Fenfel** [comment]
> [#322 (comment)](https://github.com/oobabooga/text-generation-webui/issues/322#issuecomment-1472624995)
> 
> I had the same problem, you need to change the capitalization of the phrase "LLaMAConfig"

You mean replace "LLaMAConfig" in C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\transformers\__init__.py   to "llamaConfig"?

**Comment by RandomInternetPreson** [comment]
Nope, it's easier than that, go to your model folder where you have your llama model.  Find tokenizer_config.json and change LLaMATokenizer to LlamaTokenizer

**Comment by kinfolk0117** [comment]
Had the same problem. I solved it by pulling down the latest version of the GPTQ-for-LLaMa repo
```
cd repositories/GPTQ-for-LLaMa/
git pull
```

**Comment by Fenfel** [comment]
> Had the same problem. I solved it by pulling down the latest version of the GPTQ-for-LLaMa repo
> 
> ```
> cd repositories/GPTQ-for-LLaMa/
> git pull
> ```

tank you It's working but partially
As you can easily guess, I think it is related to the inscription "CUDA extension not installed."

(textgen) C:\Users\anton\Desktop\SD\text-generation-webui>python server.py --auto-devices --model LLaMA-13B --gptq-bits 4 --cai-chat
Loading LLaMA-13B...
CUDA extension not installed.
Loading model ...
Traceback (most recent call last):
  File "C:\Users\anton\Desktop\SD\text-generation-webui\server.py", line 215, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\anton\Desktop\SD\text-generation-webui\modules\models.py", line 95, in load_model
    model = load_quantized(model_name)
  File "C:\Users\anton\Desktop\SD\text-generation-webui\modules\GPTQ_loader.py", line 55, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.gptq_bits)
  File "C:\Users\anton\Desktop\SD\text-generation-webui\repositories\GPTQ-for-LLaMa\llama.py", line 245, in load_quant
    model.load_state_dict(torch.load(checkpoint))
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\torch\serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\torch\serialization.py", line 1131, in _load
    result = unpickler.load()
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\torch\serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\torch\serialization.py", line 1083, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\torch\serialization.py", line 215, in default_restore_location
    result = fn(storage, location)
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\torch\serialization.py", line 182, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\torch\serialization.py", line 166, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

I don't know what the problem is because conda tells me that everything is installed.

(textgen) C:\Users\anton\Desktop\SD\text-generation-webui>conda install cuda -c nvidia/label/cuda-11.3.0 -c nvidia/label/cuda-11.3.1
Collecting package metadata (current_repodata.json): done
Solving environment: done

 All requested packages already installed.

**Comment by Fenfel** [comment]
> Nope, it's easier than that, go to your model folder where you have your llama model. Find tokenizer_config.json and change LLaMATokenizer to LlamaTokenizer

In the beginning I wrote that I had already done it and that was not the problem.

**Comment by VldmrB** [comment]
Do you have multiple models? I'd double check that you did it in the right place, etc. It's unlikely there's another root cause for the issue. Worst case scenario, search the entire repo for the string with the wrong capitalization from
```
ImportError: cannot import name 'LLaMAConfig' from 'transformers' (C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\transformers\__init__.py)
```
to see where it's coming from.

**Comment by Fenfel** [comment]
> Do you have multiple models? I'd double check that you did it in the right place, etc. It's unlikely there's another root cause for the issue. Worst case scenario, search the entire repo (using VS Code, Notepad++, w/e) for the string with the wrong capitalization from
> 
> ```
> ImportError: cannot import name 'LLaMAConfig' from 'transformers' (C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\transformers\__init__.py)
> ```
> 
> to see where it's coming from.

Fixed it by using
```
cd repositories/GPTQ-for-LLaMa/
git pull
```
 but now the problem is different

`conda install cuda -c nvidia/label/cuda-11.3.0 -c nvidia/label/cuda-11.3.1` tells me that everything is in place (look at the screenshot)

![image](https://user-images.githubusercontent.com/127771767/226064823-b8d8dfe9-b69e-4ac8-a489-4659470e373a.png)

**Comment by VldmrB** [comment]
Not sure then. I suspect it might be the cuda that you install here:
https://github.com/oobabooga/text-generation-webui/pull/206
```
mkdir repositories
git clone https://github.com/qwopqwop200/GPTQ-for-LLaMa
cd GPTQ-for-LLaMa
python setup_cuda.py install
```
But I think I was able to do `git pull` on that yesterday, and not have it break anything... ¯\_(ツ)_/¯

**Comment by Fenfel** [comment]
now it`s

(textgen) C:\Users\anton\Desktop\SD\text-generation-webui\repositories\GPTQ-for-LLaMa>python setup_cuda.py install

No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3'
running install
C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing quant_cuda.egg-info\PKG-INFO
writing dependency_links to quant_cuda.egg-info\dependency_links.txt
writing top-level names to quant_cuda.egg-info\top_level.txt
C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'quant_cuda.egg-info\SOURCES.txt'
writing manifest file 'quant_cuda.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl: [WinError 2] Не удается найти указанный файл
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
Traceback (most recent call last):
  File "C:\Users\anton\Desktop\SD\text-generation-webui\repositories\GPTQ-for-LLaMa\setup_cuda.py", line 4, in <module>
    setup(
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\setuptools\command\install.py", line 74, in run
    self.do_egg_install()
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\setuptools\command\install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\setuptools\command\bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\setuptools\command\bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\setuptools\_distutils\command\install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
    self.build_extensions()
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
    _check_cuda_version(compiler_name, compiler_version)
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\torch\utils\cpp_extension.py", line 382, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 49, in parse
    return Version(version)
  File "C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 264, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object

**Comment by xNul** [comment]
@Fenfel I'd delete your environment, files, and start over. I've been able to get everything working correctly on Windows. I put some instructions [here](https://github.com/xNul/chat-llama-discord-bot#llama-setup-normal8bit4bit-for-text-generation-webui) which may help.

**Comment by Fenfel** [comment]
> @Fenfel I'd delete your environment, files, and start over. I've been able to get everything working correctly on Windows. I put some instructions [here](https://github.com/xNul/chat-llama-discord-bot#llama-setup-normal8bit4bit-for-text-generation-webui) which may help.

Thanks, everything works but an error appears at startup that does not affect the model, so okay

**Comment by xNul** [comment]
> > @Fenfel I'd delete your environment, files, and start over. I've been able to get everything working correctly on Windows. I put some instructions [here](https://github.com/xNul/chat-llama-discord-bot#llama-setup-normal8bit4bit-for-text-generation-webui) which may help.
> 
> Thanks, everything works but an error appears at startup that does not affect the model, so okay

Oh, this error?

> UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)

I get it too. I guess it will be fixed in a future update of the transformers library.
