### ISSUE TITLE
metadata_gguf.py MemoryError for certain models

### ISSUE THREAD

**Issue by JohanAR** [oobabooga/text-generation-webui#3880]
### Describe the bug

After the GGUF metadata change, selecting Marx-3B-V2-Q4_1-GGUF.gguf in WebUI causes a MemoryError exception. Other GGUF files that I have still work, though it's possible that all those models don't run the metadata extractor since they have settings saved to config-user.yaml

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Manually download model from https://huggingface.co/NikolayKozloff/Marx-3B-V2-GGUF/tree/main and place in models/ folder. (i.e. I haven't tried downloading it again using the webui)
2. Try to select it in webui tab.

### Logs

```shell
text-generation-webui-text-generation-webui-1  | Traceback (most recent call last):
text-generation-webui-text-generation-webui-1  |   File "/venv/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
text-generation-webui-text-generation-webui-1  |     output = await app.get_blocks().process_api(
text-generation-webui-text-generation-webui-1  |   File "/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
text-generation-webui-text-generation-webui-1  |     result = await self.call_function(
text-generation-webui-text-generation-webui-1  |   File "/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1051, in call_function
text-generation-webui-text-generation-webui-1  |     prediction = await anyio.to_thread.run_sync(
text-generation-webui-text-generation-webui-1  |   File "/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
text-generation-webui-text-generation-webui-1  |     return await get_asynclib().run_sync_in_worker_thread(
text-generation-webui-text-generation-webui-1  |   File "/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
text-generation-webui-text-generation-webui-1  |     return await future
text-generation-webui-text-generation-webui-1  |   File "/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
text-generation-webui-text-generation-webui-1  |     result = context.run(func, *args)
text-generation-webui-text-generation-webui-1  |   File "/app/modules/models_settings.py", line 122, in apply_model_settings_to_state
text-generation-webui-text-generation-webui-1  |     model_settings = get_model_metadata(model)
text-generation-webui-text-generation-webui-1  |   File "/app/modules/models_settings.py", line 48, in get_model_metadata
text-generation-webui-text-generation-webui-1  |     metadata = metadata_gguf.load_metadata(model_file)
text-generation-webui-text-generation-webui-1  |   File "/app/modules/metadata_gguf.py", line 76, in load_metadata
text-generation-webui-text-generation-webui-1  |     key_length = struct.unpack("<Q", file.read(8))[0]
text-generation-webui-text-generation-webui-1  | MemoryError
```

### System Info

```shell
Running in docker image nvidia/cuda:11.8.0-runtime-ubuntu22.04
32GB RAM
RTX 3080 12GB VRAM
```

**Comment by berkut1** [comment]
I have added that warning in this pull https://github.com/oobabooga/text-generation-webui/pull/3877

**Comment by JohanAR** [comment]
Closing this since the PR has been merged.
