### ISSUE TITLE
Webui is broken by the latest update (maybe because of torch 2.0.1)

### ISSUE THREAD

**Issue by SrVill** [oobabooga/text-generation-webui#3884]
### Describe the bug

Greetings! After today's update:
when starting webui:
```
bin E:\oobabooga-webui\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so
E:\oobabooga-webui\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
function 'cadam32bit_grad_fp32' not found
2023-09-12 22:28:14 INFO:Loading the extension "gallery"...
Running on local URL:  http://127.0.0.1:7860
```

loading the model in 8-bit (transformer):
```
2023-09-12 22:35:07 WARNING:torch.cuda.is_available() returned False. This means that no GPU has been detected. Falling back to CPU mode.
2023-09-12 22:35:11 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "E:\oobabooga-webui\text-generation-webui\modules\ui_model_menu.py", line 194, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "E:\oobabooga-webui\text-generation-webui\modules\models.py", line 77, in load_model
    output = load_func_map[loader](model_name)
  File "E:\oobabooga-webui\text-generation-webui\modules\models.py", line 222, in huggingface_loader
    model = LoaderClass.from_pretrained(checkpoint, **params)
  File "E:\oobabooga-webui\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
  File "E:\oobabooga-webui\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 3175, in from_pretrained
    ) = cls._load_pretrained_model(
  File "E:\oobabooga-webui\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 3563, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "E:\oobabooga-webui\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 753, in _load_state_dict_into_meta_model
    set_module_quantized_tensor_to_device(
  File "E:\oobabooga-webui\installer_files\env\lib\site-packages\transformers\integrations\bitsandbytes.py", line 58, in set_module_quantized_tensor_to_device
    if old_value.device == torch.device("meta") and device not in ["meta", torch.device("meta")] and value is None:
NameError: name 'torch' is not defined
```
Thus, the problem is probably that when updating the web ui, torch was updated to version 2.0.1, which is not compatible, which was the warning in the console when updating. Question: how do I get back to the previous version of webui or to torch 2.0.0?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

get this error:
just upgrade: update_windows.bat

### Logs

```shell
Traceback (most recent call last):

File “E:\oobabooga-webui\text-generation-webui\modules\ui_model_menu.py”, line 194, in load_model_wrapper

shared.model, shared.tokenizer = load_model(shared.model_name, loader)
File “E:\oobabooga-webui\text-generation-webui\modules\models.py”, line 77, in load_model

output = load_func_map[loader](model_name)
File “E:\oobabooga-webui\text-generation-webui\modules\models.py”, line 222, in huggingface_loader

model = LoaderClass.from_pretrained(checkpoint, **params)
File “E:\oobabooga-webui\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py”, line 563, in from_pretrained

return model_class.from_pretrained(
File “E:\oobabooga-webui\installer_files\env\lib\site-packages\transformers\modeling_utils.py”, line 3175, in from_pretrained

) = cls._load_pretrained_model(
File “E:\oobabooga-webui\installer_files\env\lib\site-packages\transformers\modeling_utils.py”, line 3563, in _load_pretrained_model

new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
File “E:\oobabooga-webui\installer_files\env\lib\site-packages\transformers\modeling_utils.py”, line 753, in _load_state_dict_into_meta_model

set_module_quantized_tensor_to_device(
File “E:\oobabooga-webui\installer_files\env\lib\site-packages\transformers\integrations\bitsandbytes.py”, line 58, in set_module_quantized_tensor_to_device

if old_value.device == torch.device("meta") and device not in ["meta", torch.device("meta")] and value is None:
NameError: name ‘torch’ is not defined
```

### System Info

```shell
Windows 10
RTX 3060
cuda 11.8.0
driver 531.68
```

**Comment by berkut1** [comment]
I have the same issue with bitsandbytes

**Comment by oobabooga** [comment]
That's weird. Maybe @jllllll will have a better idea what is going on

**Comment by jllllll** [comment]
Looking into it. Give me a bit.

**Comment by jllllll** [comment]
This appears to be a remnant issue from when the installer transitioned to installing Pytorch through pip instead of Conda.
https://github.com/oobabooga/one-click-installers/commit/9bb2fc8cd782be5930b6789f2171cb73effc9be3

Back when the installer was installing it through Conda, I had erroneously assumed that Conda would interpret `version=2` as a requirement to install 2.0.1. Instead, due to a bug, Conda was installing 2.0.0. By the time I noticed this and was able to make a PR to fix it, the issues surrounding the Pytorch Conda packages became apparent and I instead decided to make a PR for installing 2.0.1 through pip.

Due to numerous dependency updates to the webui since then, one of the dependencies must have required the installation of Torch 2.0.1. This was inevitable, given that 2.0.1 had become the standard version of Torch for quite a while. Due to this, pip decided to install the required 2.0.1 version of Torch through the only source it knew which only contained the CPU-only version that is now seemingly causing this error for you.

---
Here are some steps to fix this:
1. Ensure that you have the latest version of the installer linked in the README: https://github.com/oobabooga/text-generation-webui/releases/download/installers/oobabooga_windows.zip
2. Personally, I would prefer to fully reinstall the webui to ensure everything is set up correctly. However, if you don't want to do that, then run `cmd_windows.bat` and enter these commands:
```
conda remove pytorch torchvision torchaudio pytorch-cuda
python -m pip install torch==2.0.1+cu117 torchvision torchaudio --force-reinstall --index-url https://download.pytorch.org/whl/cu117
python -m pip install -rtext-generation-webui/requirements.txt --upgrade
```

**Comment by berkut1** [comment]
@jllllll it showed some error, in my case I should did:
`conda remove torchvision torchaudio pytorch-cuda`

It also showed some dependency errors, but anyway, bitsandbytes started without problems now.
Thanks.

**Comment by SrVill** [comment]
After reinstalling webui, the models run in 8-bit. By the way, during the installation there was one error that does not relate to this issue, but it may be useful:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
elevenlabs 0.2.26 requires pydantic>=2.0, but you have pydantic 1.10.12 which is incompatible.
```

**Comment by oobabooga** [comment]
> Due to numerous dependency updates to the webui since then, one of the dependencies must have required the installation of Torch 2.0.1.

The culprit was probably the exllama pip package that I added today:

https://github.com/turboderp/exllamav2/blob/master/setup.py

It seemed like a good idea to use this easily installable package rather than asking people to clone exllamav2 or install it manually.

**Comment by mykeehu** [comment]
After upgrading to [5e3d2f7](https://github.com/oobabooga/text-generation-webui/commit/5e3d2f7d447700076fa66fb33f991d561da0a94b), I got this with RTX 3060 GPU:

```
bin I:\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so
I:\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
function 'cadam32bit_grad_fp32' not found
2023-09-13 07:49:02 INFO:Loading settings from I:\oobabooga_windows\mysettings.yaml...
2023-09-13 07:49:02 INFO:Loading TheBloke_MLewdBoros-L2-13B-GPTQ_gptq-4bit-32g-actorder_True...
No CUDA runtime is found, using CUDA_HOME='I:\oobabooga_windows\installer_files\env'
2023-09-13 07:49:02 WARNING:Exllama module failed to load. Will attempt to load from repositories.
2023-09-13 07:49:02 ERROR:Could not find repositories/exllama/. Make sure that exllama is cloned inside repositories/ and is up to date.
Traceback (most recent call last):
  File "I:\oobabooga_windows\text-generation-webui\modules\exllama.py", line 12, in <module>
    from exllama.generator import ExLlamaGenerator
  File "I:\oobabooga_windows\installer_files\env\lib\site-packages\exllama\__init__.py", line 1, in <module>
    from . import cuda_ext, generator, model, tokenizer
  File "I:\oobabooga_windows\installer_files\env\lib\site-packages\exllama\cuda_ext.py", line 9, in <module>
    import exllama_ext
ImportError: DLL load failed while importing exllama_ext: A megadott modul nem található.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\oobabooga_windows\text-generation-webui\server.py", line 219, in <module>
    shared.model, shared.tokenizer = load_model(model_name)
  File "I:\oobabooga_windows\text-generation-webui\modules\models.py", line 77, in load_model
    output = load_func_map[loader](model_name)
  File "I:\oobabooga_windows\text-generation-webui\modules\models.py", line 322, in ExLlama_loader
    from modules.exllama import ExllamaModel
  File "I:\oobabooga_windows\text-generation-webui\modules\exllama.py", line 21, in <module>
    from generator import ExLlamaGenerator
  File "I:\oobabooga_windows\text-generation-webui\repositories\exllama\generator.py", line 1, in <module>
    import cuda_ext
  File "I:\oobabooga_windows\text-generation-webui\repositories\exllama\cuda_ext.py", line 43, in <module>
    exllama_ext = load(
  File "I:\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "I:\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "I:\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 1611, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "I:\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 2007, in _write_ninja_file_to_build_library
    cuda_flags = common_cflags + COMMON_NVCC_FLAGS + _get_cuda_arch_flags()
  File "I:\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 1773, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range
Press any key to continue . . .
```

**Comment by jllllll** [comment]
@DiamondGlassDrill
Someone else with the same error was able to fix it by updating their installer and then running the installer's update script.
https://github.com/oobabooga/text-generation-webui/releases/download/installers/oobabooga_windows.zip

**Comment by devPhases** [comment]
@DiamondGlassDrill
i had the same issue. I'm on windows. I have a "miniconda-cmd" in my ooba folder. 
Ran the miniconda, entered "conda install pydantic", then then closed it.

Ooba is back up for me and working for me now. I updated because I was having issues running micorsoft phi. It works for me now after the update.

**Comment by DiamondGlassDrill** [comment]
> @DiamondGlassDrill I'm on windows and had the same issue after updating. My install of ooba has a "miniconda-cmd" inside the main ooba folder.
> 
> Ran the miniconda, entered "conda install pydantic", then then closed it.
> 
> Ooba is back up and working for me now. I updated because I was having issues running Microsoft phi. It works for me after the update.

Thanks devPhases, but unfortunately, this didn't work for me it made more chaos in dependencies :)

**Comment by DiamondGlassDrill** [comment]
> @DiamondGlassDrill Someone else with the same error was able to fix it by updating their installer and then running the installer's update script. https://github.com/oobabooga/text-generation-webui/releases/download/installers/oobabooga_windows.zip

We can close this thread, Jillll's recommendation helped. Didn't update the "installer" part since 6 month or so :), everything up and running again !!! Now can start coding my summarizer extension, will post it on discord, as soon as ready!!!
