### ISSUE TITLE
ERROR:Failed to load the model.

### ISSUE THREAD

**Issue by thistleknot** [oobabooga/text-generation-webui#3889]
### Describe the bug

just updated to today's branch, and I can no longer load tinyllama

It was just working...

I attempted to pip install -r requirements.txt just in case those were updated (after I got the error).

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

try to load tinyllama under transformers option

### Logs

```shell
2023-09-12 18:45:39 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/data/text-generation-webui/modules/ui_model_menu.py", line 194, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/data/text-generation-webui/modules/models.py", line 77, in load_model
    output = load_func_map[loader](model_name)
  File "/data/text-generation-webui/modules/models.py", line 146, in huggingface_loader
    if not any([shared.args.cpu, shared.args.load_in_8bit, shared.args.load_in_4bit, shared.args.auto_devices, shared.args.disk, shared.args.deepspeed, shared.args.gpu_memory is not None, shared.args.cpu_memory is not None, shared.args.compress_pos_emb > 1, shared.args.alpha_value > 1]):
TypeError: '>' not supported between instances of 'str' and 'int'
```

### System Info

```shell
oracle linux 8
python 3.10
```

**Comment by thistleknot** [comment]
this appears to have been fixed with today's update
