### ISSUE TITLE
Training LoRa Error 

### ISSUE THREAD

**Issue by Maki9009** [oobabooga/text-generation-webui#3902]
### Describe the bug

I began training.. a whatapp chat i converted in Alpaca Formate, i started the training process 10 second later i got this error

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

not sure if its because of the emojis or not I'm pretty sure its not cuz the line it error on was soo was soo far down and there was many text messages with emojis in them.. so idk 

### Logs

```shell
Traceback (most recent call last):
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2106, in run_sync_in_worker_thread
    return await future
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 833, in run
    result = context.run(func, *args)
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "E:\oobabooga_windows\text-generation-webui\modules\training.py", line 452, in do_train
    train_data = data['train'].map(generate_and_tokenize_prompt, new_fingerprint='%030x' % random.randrange(16**30))
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\datasets\arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\datasets\arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\datasets\arrow_dataset.py", line 3097, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\datasets\arrow_dataset.py", line 3450, in _map_single
    example = apply_function_on_filtered_inputs(example, i, offset=offset)
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\datasets\arrow_dataset.py", line 3353, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "E:\oobabooga_windows\text-generation-webui\modules\training.py", line 447, in generate_and_tokenize_prompt
    prompt = generate_prompt(data_point)
  File "E:\oobabooga_windows\text-generation-webui\modules\training.py", line 444, in generate_prompt
    raise RuntimeError(f'Data-point "{data_point}" has no keyset match within format "{list(format_data.keys())}"')
RuntimeError: Data-point "{'output': None, 'instruction': 'I’ll show u how it works 😂😂'}" has no keyset match within format "['instruction,output', 'instruction,input,output']"
```

### System Info

```shell
i5 10th, rtx 3090, 16gb of ddr4 ram
```

**Comment by Maki9009** [comment]
tested it with a dataset from a tutorial i found for someone it worked for but I'm getting the same error :

```
Map:   0%|                                                                                | 0/3 [00:00<?, ? examples/s]
Traceback (most recent call last):
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2106, in run_sync_in_worker_thread
    return await future
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 833, in run
    result = context.run(func, *args)
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "E:\oobabooga_windows\text-generation-webui\modules\training.py", line 452, in do_train
    train_data = data['train'].map(generate_and_tokenize_prompt, new_fingerprint='%030x' % random.randrange(16**30))
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\datasets\arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\datasets\arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\datasets\arrow_dataset.py", line 3097, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\datasets\arrow_dataset.py", line 3450, in _map_single
    example = apply_function_on_filtered_inputs(example, i, offset=offset)
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\datasets\arrow_dataset.py", line 3353, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "E:\oobabooga_windows\text-generation-webui\modules\training.py", line 447, in generate_and_tokenize_prompt
    prompt = generate_prompt(data_point)
  File "E:\oobabooga_windows\text-generation-webui\modules\training.py", line 444, in generate_prompt
    raise RuntimeError(f'Data-point "{data_point}" has no keyset match within format "{list(format_data.keys())}"')
RuntimeError: Data-point "{'instruction,output': "User: Hello, I would like to speak with you about your car's extended warranty\nAssistant: What about my car's extended warranty?", 'instruction,input,output': 'User: %instruction%: %input%\nAssistant: %output%'}" has no keyset match within format "['instruction,output', 'instruction,input,output']"
```

**Comment by BelloGoo** [comment]
im having the same error. i compiled my dataset according to the alpaca and alpaca-chatbot format, but none of them work. providing the first piece of datum in my testing datasets for your references.

**alpaca-chatbot-formatted**
`[ { "instruction,output": "User: %Identify the odd one out.%\nAssistant: %The odd one out is Telegram. Twitter and Instagram are social media platforms mainly for sharing information, images and videos while Telegram is a cloud-based instant messaging and voice-over-IP service.%", "instruction,input,output": "User: %Identify the odd one out.%: %Twitter, Instagram, Telegram%\nAssistant: %The odd one out is Telegram. Twitter and Instagram are social media platforms mainly for sharing information, images and videos while Telegram is a cloud-based instant messaging and voice-over-IP service.%" }]`

**alpaca-formatted**
`[ { "instruction,output": "\n\n### Instruction:\n%Identify the odd one out.%\n\n### Response:\n%The odd one out is Telegram. Twitter and Instagram are social media platforms mainly for sharing information, images and videos while Telegram is a cloud-based instant messaging and voice-over-IP service.%", "instruction,input,output": "\n\n### Instruction:\n%Identify the odd one out.%\n\n### Input:\n%Twitter, Instagram, Telegram%\n\n### Response:\n%The odd one out is Telegram. Twitter and Instagram are social media platforms mainly for sharing information, images and videos while Telegram is a cloud-based instant messaging and voice-over-IP service.%" }]`

**Comment by KPCOFGS** [comment]
Getting same error on the latest release as well
```bash
    raise RuntimeError(f'Data-point "{data_point}" has no keyset match within format "{list(format_data.keys())}"')
RuntimeError: Data-point "{'instruction': 'You are a helpful assistant', 'input': '阿猛，如果你要cos一个角色，你会选择谁呢？', 'output': '阿猛可以cos大嫂吗 或者缸灿团队来cos个狂飙想看！！[星星眼][星星眼][星星眼]'}" has no keyset match within format "['instruction', 'input', 'output']"

```
