### ISSUE TITLE
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (E:\oobabooga_windows\installer_files\env\lib\site-packages\pydantic\fields.py)

### ISSUE THREAD

**Issue by ForwardForward** [oobabooga/text-generation-webui#3905]
### Describe the bug

Windows 10 Home. Install by start_windows.bat from zip archive for Windows from GittHub page. Say that have GPU and NVidia card.

After installation receive next message:

*******************************************************************
* WARNING: You haven't downloaded any model yet.
* Once the web UI launches, head over to the bottom of the "Model" tab and download one.
*******************************************************************

Traceback (most recent call last):
  File "E:\oobabooga_windows\text-generation-webui\server.py", line 12, in <module>
    import gradio as gr
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\components.py", line 32, in <module>
    from fastapi import UploadFile
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\fastapi\applications.py", line 16, in <module>
    from fastapi import routing
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\fastapi\routing.py", line 22, in <module>
    from fastapi import params
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\fastapi\params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (E:\oobabooga_windows\installer_files\env\lib\site-packages\pydantic\fields.py)
Для продолжения нажмите любую клавишу . . .

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Windows 10 Home. Install by start_windows.bat from zip archive for Windows from GittHub page. Say that have GPU and NVidia card.

### Logs

```shell
I don't have
```

### System Info

```shell
Intel CPU, NVidia RTX3060
```

**Comment by aetherwu** [comment]
I've encountered the same today. But it works fine on my another PC.

**Comment by Shark-Eater** [comment]
I am also experiencing this same issue

**Comment by alicat22** [comment]
I believe this is related to elevenlabs and how it downgrades pydantic.

What I've been doing is, while in the ooba environment doing:
1) pip uninstall pydantic
2) pip install pydantic==1.10.12

This fixes it for me. Just remember to make sure you're in the conda environment before you pip uninstall or install.

**Comment by newbiebunchu** [comment]
I tried uninstall and reinstall the  pydantic but the issue still persist. Can anyone help?
