### ISSUE TITLE
GPTQ's and cuda 11.4

### ISSUE THREAD

**Issue by skintflickz** [oobabooga/text-generation-webui#3923]
### Describe the bug

I'm failing to run any GPTQ models even 7b. I can run HF no problem but then I have a problem with large files for anything over 7b. I have a tesla k80 and it only supports cuda 11.4 could this be the problem ? The files loads fine then its just crashes as soon as I start the answer.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

None

### Logs

```shell
None
```

### System Info

```shell
2023-09-13 22:58:01 WARNING:skip module injection for FusedLlamaMLPForQuantizedModel not support integrate without triton yet.
2023-09-13 22:58:01 WARNING:models\TheBloke_Wizard-Vicuna-13B-Uncensored-GPTQ\tokenizer_config.json is different from the original LlamaTokenizer file. It is either customized or outdated.
2023-09-13 22:58:01 WARNING:models\TheBloke_Wizard-Vicuna-13B-Uncensored-GPTQ\special_tokens_map.json is different from the original LlamaTokenizer file. It is either customized or outdated.
2023-09-13 22:58:01 INFO:Loaded the model in 28.76 seconds.

Traceback (most recent call last):
  File "E:\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\callbacks.py", line 56, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "E:\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 322, in generate_with_callback
    shared.model.generate(**kwargs)
  File "E:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\modeling\_base.py", line 443, in generate
    return self.model.generate(**kwargs)
  File "E:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1648, in generate
    return self.sample(
  File "E:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 2766, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

**Comment by evg-tyurin** [comment]
_I have a tesla k80 and it only supports cuda 11.4 could this be the problem ?_

CUDA interacts with gpu driver not the gpu itself.
Support for k80 was removed in R495, so you can have R470 driver installed that supports your gpu.
Using cuda 11.7-11.8 with R470 driver could be allowed in compatibility mode – please read the CUDA Compatibility Guide for details.

I'd recommend to create the clean environment to avoid pip dependency problem you've mentioned above.
