### ISSUE TITLE
file markdown.py is missing

### ISSUE THREAD

**Issue by duanelawrence** [oobabooga/text-generation-webui#3930]
### Describe the bug

I downloaded TG today and when I try to launch it, I get the below error

(tg) C:\ProgramData\text-generation-webui>python server.py
Traceback (most recent call last):
  File "C:\ProgramData\text-generation-webui\server.py", line 29, in <module>
    from modules import (
  File "C:\ProgramData\text-generation-webui\modules\chat.py", line 15, in <module>
    from modules.html_generator import chat_html_wrapper, make_thumbnail
  File "C:\ProgramData\text-generation-webui\modules\html_generator.py", line 7, in <module>
    import markdown
ModuleNotFoundError: No module named 'markdown'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

try to start it.

python server.py

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/7420012/132cb2b2-b120-420b-af87-80d09f9cf89a)

### Logs

```shell
(tg) C:\ProgramData\text-generation-webui>python server.py
Traceback (most recent call last):
  File "C:\ProgramData\text-generation-webui\server.py", line 29, in <module>
    from modules import (
  File "C:\ProgramData\text-generation-webui\modules\chat.py", line 15, in <module>
    from modules.html_generator import chat_html_wrapper, make_thumbnail
  File "C:\ProgramData\text-generation-webui\modules\html_generator.py", line 7, in <module>
    import markdown
ModuleNotFoundError: No module named 'markdown'
```

### System Info

```shell
Edition	Windows 10 Enterprise
Version	22H2
Installed on	‎11/‎3/‎2022
OS build	19045.3324
Experience	Windows Feature Experience Pack 1000.19041.1000.0
```

**Comment by duanelawrence** [comment]
I found the fix.

pip install markdown
