### ISSUE TITLE
MAJOR Issue with LoRa Training for Alpaca Format

### ISSUE THREAD

**Issue by Maki9009** [oobabooga/text-generation-webui#3933]
### Describe the bug

So this could be a documentation issue or a code bug for the Alpaca Format

I have been trying to train a LoRa for a chat bot that could impersonate a person from text messages such as WhatsApp or Telegram or whatever. 

So i followed a Guide i found on Youtube who shows the process: https://www.youtube.com/watch?v=7pdEK9ckDQ8&t=283s

In the Guide, he shows the Alpaca Json Format he uses which was: 
```
[
	{
    		"instruction,output": "User: Hello, I would like to speak with you about your car's extended warranty\nAssistant: What about my car's extended warranty?",
    		"instruction,input,output": "User: %instruction%: %input%\nAssistant: %output%"
	},
	{
    		"instruction,output": "User: Your car's extended warranty has expired\nAssistant: Oh no, that's horrible",
    		"instruction,input,output": "User: %instruction%: %input%\nAssistant: %output%"
	},
	{
    		"instruction,output": "User: Can you tell me the year and make of your car?\nAssistant: Yes, it is a 2004 Honda Civic",
    		"instruction,input,output": "User: %instruction%: %input%\nAssistant: %output%"
	}
]
``` 

I made a program that converts my chat into this format. Great. I try to train and I get hit with a mismatch key error. 

But if i use this Other format it works
```
[
    {
        "instruction": "Hello, I would like to speak with you about your car's extended warranty",
        "input": "What about my car's extended warranty?",
        "output": "Sure, what would you like to know?"
    },
    {
        "instruction": "Your car's extended warranty has expired",
        "input": "Oh no, that's horrible",
        "output": "Yes, it's important to keep track of these things."
    },
    {
        "instruction": "Can you tell me the year and make of your car?",
        "input": "Yes, it is a 2004 Honda Civic",
        "output": "That's a great car! How can I assist you further?"
    }
]
``` 

It works no matter what i choose, Alpaca format or Alpaca Chatbot Format..

My issue with this Input format is how I'm i supposed to add an input for each one? or instruction? 
My plan was the instruction would be the Text messages from one person, and the output are the text messages of the person i want to train. 

the older Alpaca format that made things easier and possible with this idk... 
Plus i cant train it on raw data.. because the Model Becomes Retarded.. it talks with no understanding of any context of the conversation and the style of talking should be. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Use this Format from the same Youtube video: https://github.com/Aemon-Algiz/LoRAExamples/blob/main/FormattedTraining.json 
Train using Alpaca format or Alpaca chatbot format. Same error. Format

### Logs

```shell
Downloading data files: 100%|███████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 995.33it/s]
Extracting data files: 100%|████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 142.86it/s]
Generating train split: 3 examples [00:00, 26.68 examples/s]
Map:   0%|                                                                                | 0/3 [00:00<?, ? examples/s]
Traceback (most recent call last):
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2106, in run_sync_in_worker_thread
    return await future
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 833, in run
    result = context.run(func, *args)
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "E:\oobabooga_windows\text-generation-webui\modules\training.py", line 452, in do_train
    train_data = data['train'].map(generate_and_tokenize_prompt, new_fingerprint='%030x' % random.randrange(16**30))
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\datasets\arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\datasets\arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\datasets\arrow_dataset.py", line 3097, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\datasets\arrow_dataset.py", line 3450, in _map_single    example = apply_function_on_filtered_inputs(example, i, offset=offset)
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\datasets\arrow_dataset.py", line 3353, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "E:\oobabooga_windows\text-generation-webui\modules\training.py", line 447, in generate_and_tokenize_prompt
    prompt = generate_prompt(data_point)
  File "E:\oobabooga_windows\text-generation-webui\modules\training.py", line 444, in generate_prompt
    raise RuntimeError(f'Data-point "{data_point}" has no keyset match within format "{list(format_data.keys())}"')
RuntimeError: Data-point "{'instruction,input,output': 'User: %instruction%: %input%\nAssistant: %output%', 'instruction,output': "User: Hello, I would like to speak with you about your car's extended warranty\nAssistant: What about my car's extended warranty?"}" has no keyset match within format "['instruction,output', 'instruction,input,output']"
```

### System Info

```shell
i5 10th gen, RTX 3090, 16gb of ddr4 Ram
```

**Comment by FartyPants** [comment]
No, no, no. You changed the template (the first file you showed). You don't change the template! You don't touch it. The template is to take your JSON and format it into blocks. Also User Assistant is NOT alpaca format but Vicuna, but that's beyond the point. 
The second file you showed is correct. That's your JSON dataset.

**Comment by Maki9009** [comment]
> No, no, no. You changed the template (the first file you showed). You don't change the template! You don't touch it. The template is to take your JSON and format it into blocks. Also User Assistant is NOT alpaca format but Vicuna, but that's beyond the point. 
> 
> The second file you showed is correct. That's your JSON dataset. So revert your templates back to their original form.
> 
> 

So I'm very confused, so is the video that I watched incorrect? 

I never changed the format templates in the format folder. Never touched them. 

But if you are saying the the second format is correct. 

For my WhatsApp chat bot, how I'm I supposed to know what to put in "input"?

And do I have to do that manually? That will take a long time? 

Since I was thinking it should be instructor should be the message I sent and the output is the messages from the person I trained... unless I'm having this all wrong?

If you could provide an example that would be great. 
It's just the documentation isn't clear enough... and after watching the video for the person and it working for him but not me has confused me even further

**Comment by Maki9009** [comment]
Okay I got it to work.. but i believe the Documentation for training a LoRa needs to be updated. And the Guy in the video.. idk i think his work no longer applies to new updates

**Comment by Maki9009** [comment]
the Json i think had 225 lines.. which i know isn't a lot of data..but it doesn't seem like my model kinda learned the style or any knowledge from the conversation.. any idea what i can do to improve this? i didn't really play with the Settings since i don't know anything yet.

**Comment by FartyPants** [comment]
Well, I don't care much about anybody's video as I'm not going to watch it, but the rule is, your JSON always need to be in format

   {
        "instruction": " blah blah",
        "input": "blah blah",
        "output": "desired blah blah"
    }
    
    or
    
       {
        "input": "blah blah",
        "output": "desired blah blah"
    }

The template will then format this to the USER/ASSISTANT or whatever else. The point is, by simply choosing different template it will be automatically translated to the desired format without you needing to touch the dataset. That's the whole point of the templates. If you want to suddenly use ###input/###response or CAT: / DOG: or whatever else, you don't have to search replace your JSON, just use or write a new template and boom.

When training, keep an eye on the loss. In general around 1.8  to 1.5 loss the model should be speaking the way you trained it. If your loss is > 2.0 it's too far. If you can't bring the loss down, then you need to change the parameters. In general, don't play with LR rather adjust epochs and rank.

**Comment by Maki9009** [comment]
I have managed to figure it out and train a model with the format you just sent, thank you. Its mostly the video that got me awfully confused.. since it worked for him. But anyway... i want to train a LoRa on GPTQ model for faster inference.. but having issues with that. i tried --monkey-patch and still got an error.. I'm on windows

**Comment by FartyPants** [comment]
Moved the discussion to discord

**Comment by DrMemoryFish** [comment]
> No, no, no. You changed the template (the first file you showed). You don't change the template! You don't touch it. The template is to take your JSON and format it into blocks. Also User Assistant is NOT alpaca format but Vicuna, but that's beyond the point. The second file you showed is correct. That's your JSON dataset. So revert your templates back to their original form.

i didn't change anything and i still got the same issue, I'm literally stressing out so hard cause i literally changed nothing in the template yet its telling me the template isn't compatible:


```
2023-11-04 16:42:36 INFO:Loading JSON datasets...
Downloading data files: 100%|████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Extracting data files: 100%|████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 999.12it/s]
Generating train split: 1 examples [00:00, 26.74 examples/s]
Map:   0%|                                                                                | 0/1 [00:00<?, ? examples/s]
Traceback (most recent call last):
  File "E:\AI\text-generation-webui\installer_files\env\Lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\text-generation-webui\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\text-generation-webui\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "E:\AI\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "E:\AI\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "E:\AI\text-generation-webui\modules\training.py", line 491, in do_train
    train_data = data['train'].map(generate_and_tokenize_prompt, new_fingerprint='%030x' % random.randrange(16**30))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\text-generation-webui\installer_files\env\Lib\site-packages\datasets\arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\text-generation-webui\installer_files\env\Lib\site-packages\datasets\arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\text-generation-webui\installer_files\env\Lib\site-packages\datasets\arrow_dataset.py", line 3097, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "E:\AI\text-generation-webui\installer_files\env\Lib\site-packages\datasets\arrow_dataset.py", line 3450, in _map_single
    example = apply_function_on_filtered_inputs(example, i, offset=offset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\text-generation-webui\installer_files\env\Lib\site-packages\datasets\arrow_dataset.py", line 3353, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\text-generation-webui\modules\training.py", line 486, in generate_and_tokenize_prompt
    prompt = generate_prompt(data_point)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\text-generation-webui\modules\training.py", line 483, in generate_prompt
    raise RuntimeError(f'Data-point "{data_point}" has no keyset match within format "{list(format_data.keys())}"')
RuntimeError: Data-point "{'instruction,output': 'User: hello\nAssistant: im fine', 'instruction,input,output': 'User: hello: how are you\nAssistant: im fine'}" has no keyset match within format "['instruction,output', 'instruction,input,output']"
```

**Comment by oobabooga** [comment]
The training tab has been completely rewritten in v4.0. The Alpaca format is no longer used; chat training now takes datasets in OpenAI messages format or ShareGPT conversations format. See the [release notes](https://github.com/oobabooga/text-generation-webui/releases/tag/v4.0) and [training docs](https://github.com/oobabooga/text-generation-webui/wiki/05-%E2%80%90-Training-Tab).
