### ISSUE TITLE
exllamav2  not working within the docker container

### ISSUE THREAD

**Issue by KaruroChori** [oobabooga/text-generation-webui#3943]
### Describe the bug

Any attempt to load models with exllamav2 will fail.
Those models, as well as exllamav2 are working just fine outside the docker for oobabooga

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

Install oobabooga following the instructions to have a Docker installation.
Once the install is ready run in your browser.

Try to open any compatible model selecting exllamav2 as back-end.
Try to load it.
The same model will load if used in exllamav1 if its format is GPTQ.
The same model will load fine if used natively in exllamav2.

### Logs

```shell
Traceback (most recent call last):
text-generation-webui-text-generation-webui-1  |   File "/app/modules/ui_model_menu.py", line 194, in load_model_wrapper
text-generation-webui-text-generation-webui-1  |     shared.model, shared.tokenizer = load_model(shared.model_name, loader)
text-generation-webui-text-generation-webui-1  |   File "/app/modules/models.py", line 77, in load_model
text-generation-webui-text-generation-webui-1  |     output = load_func_map[loader](model_name)
text-generation-webui-text-generation-webui-1  |   File "/app/modules/models.py", line 336, in ExLlamav2_loader
text-generation-webui-text-generation-webui-1  |     from modules.exllamav2 import Exllamav2Model
text-generation-webui-text-generation-webui-1  |   File "/app/modules/exllamav2.py", line 5, in <module>
text-generation-webui-text-generation-webui-1  |     from exllamav2 import (
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/exllamav2/__init__.py", line 3, in <module>
text-generation-webui-text-generation-webui-1  |     from exllamav2.model import ExLlamaV2
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/exllamav2/model.py", line 12, in <module>
text-generation-webui-text-generation-webui-1  |     from exllamav2.linear import ExLlamaV2Linear
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/exllamav2/linear.py", line 4, in <module>
text-generation-webui-text-generation-webui-1  |     from exllamav2 import ext
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/exllamav2/ext.py", line 118, in <module>
text-generation-webui-text-generation-webui-1  |     exllamav2_ext = load \
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
text-generation-webui-text-generation-webui-1  |     return _jit_compile(
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1535, in _jit_compile
text-generation-webui-text-generation-webui-1  |     return _import_module_from_library(name, build_directory, is_python_module)
text-generation-webui-text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1929, in _import_module_from_library
text-generation-webui-text-generation-webui-1  |     module = importlib.util.module_from_spec(spec)
text-generation-webui-text-generation-webui-1  | ImportError: /root/.cache/torch_extensions/py310_cu117/exllamav2_ext/exllamav2_ext.so: cannot open shared object file: No such file or directory
```

### System Info

```shell
Ubuntu 22.04, RTX3090, Ryzen 5950X.
```

**Comment by Ph0rk0z** [comment]
have to pip install it in the docker when making the container

**Comment by KaruroChori** [comment]
> have to pip install it in the docker when making the container

What do you mean? In `requirements.txt` there is already a reference to the pip exllamav2==0.0.1.
That is run when constructing the container.
Albeit, it is strange as every other back-end is linking to a git repository not the pip registry.

**Comment by Ph0rk0z** [comment]
unlike the old one, it did not work straight from the repository. I had to pip install it despite cloning it. Other than that no idea.

**Comment by Callum17** [comment]
Unmodified docker didn't work for me either. Nor was it a case of a simple pip install in the build process. 
For me the initial issue boiled down to nvcc compiler not being present in the runtime container - exllamav2 tries to do a ninja build at model load:

sh
```
Traceback (most recent call last):
File “/app/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py”, line 1893, in _run_ninja_build
subprocess.run(
File “/usr/lib/python3.10/subprocess.py”, line 526, in run
raise CalledProcessError(retcode, process.args,
...
/bin/sh: 1: /usr/local/cuda/bin/nvcc: not found
...
compilation terminated.
ninja: build stopped: subcommand failed.
```

Which makes sense. I'm assuming the built libs are not included. Initial reaction was to include exllamav2 as a wheel build in the Dockerfile builder step alongside GPTQ-for-llama. However I started running into dependency conflicts and missing CUDA definitions - not entirely clear what the minimum feature set is intended to be.

I ended up taking the nuclear option and completely rewriting the Dockerfile using nvcr.io/nvidia/pytorch as a base:
https://gist.github.com/Callum17/3e55051da849802f0f68970317cdfdf8
Keep in mind this was thrown together quickly so making no claims on it not breaking other stuff (tested GGUF / original Exllama), or being an efficient use of disk space. But it will run exllamav2 models with expected performance.

The Dockerfile build on main is a bit of a mess right now. A rewrite probably needs to be done where all the requirements are built as wheels in builder image/s.

**Comment by sammcj** [comment]
I have a PR that should fix this for you - https://github.com/oobabooga/text-generation-webui/pull/3997

**Comment by city-unit** [comment]
Bumping this issue. Neither @sammcj's nor @Callum17's solutions worked for me, but I didn't have enough time to do anything but just try them.

**Comment by SynthpX** [comment]
Same, i also did the solution i find was https://github.com/mapillary/inplace_abn/issues/106 , i did applied and have bashrc included on my dockerfile. But still giving me the error, unless im doing it wrong.

`# Add CUDA environment variables to .bashrc
RUN echo 'export CUDAVER=cuda-11.8.0' >> ~/.bashrc && \
    echo 'export PATH=/usr/local/$CUDAVER/bin:$PATH' >> ~/.bashrc && \
    echo 'export LD_LIBRARY_PATH=/usr/local/$CUDAVER/lib:$LD_LIBRARY_PATH' >> ~/.bashrc && \
    echo 'export LD_LIBRARY_PATH=/usr/local/$CUDAVER/lib64:$LD_LIBRARY_PATH' >> ~/.bashrc && \
    echo 'export CUDA_PATH=/usr/local/$CUDAVER' >> ~/.bashrc && \
    echo 'export CUDA_ROOT=/usr/local/$CUDAVER' >> ~/.bashrc && \
    echo 'export CUDA_HOME=/usr/local/$CUDAVER' >> ~/.bashrc && \
    echo 'export CUDA_HOST_COMPILER=/usr/bin/gcc-11' >> ~/.bashrc`

**Comment by FryJay** [comment]
> I ended up taking the nuclear option and completely rewriting the Dockerfile using nvcr.io/nvidia/pytorch as a base: https://gist.github.com/Callum17/3e55051da849802f0f68970317cdfdf8 Keep in mind this was thrown together quickly so making no claims on it not breaking other stuff (tested GGUF / original Exllama), or being an efficient use of disk space. But it will run exllamav2 models with expected performance.

The Dockerfile you made didn't quite work for me but I managed to fix it by making this change:

```
RUN --mount=type=cache,target=/root/.cache/pip,rw \
    pip install -r requirements.txt && \
    pip install -U flash-attn nvidia-curand-cu11
```

to the line installing the main dependencies. I was running into issues with it not being able to find curand-header and then after fixing that it has issues with flash-attn and upgrading them both seemed to fix it.

Thanks for providing that dockerfile.

**Comment by Callum17** [comment]
I'll have a look at a docker rewrite this weekend if no one beats me to it. 

A summary of what I think we would like:
1. fix exllamav2 compatibility.
2. reduce the number of RUN steps.
3. get all dependencies installed / built via requirements file + wheel builder pattern. This should make the images a bit smaller.
4. drop vritualenv (is there a reason this in used?) virtualenv inside a container seems like an antipattern.

**Comment by sammcj** [comment]
If you're doing that anyway may as well update the Dockerfile to drop down to a non-root user so that it's UID doesn't map to root on the host OS (which is scary).

**Comment by Callum17** [comment]
> drop down to a non-root user

Of course. But I will assume a fixed GID with a default of root / 0.

**Comment by Callum17** [comment]
Believe this was actually fixed a few days back by: https://github.com/oobabooga/text-generation-webui/pull/4095

However I've opened a PR to improve the docker compose builder pattern a bit. Should make it easier to integrate builds of new binary dependencies from source.
