### ISSUE TITLE
Not sure what is going on here.

### ISSUE THREAD

**Issue by Herman5555** [oobabooga/text-generation-webui#3948]
### Describe the bug

Haven't had any issues with ooba before but a recent update has caused random severe repetition issues with this error that is responsible I believe. I have reinstalled with the auto installer with the same result, all settings were the same as always and were working fine. Can anyone tell me what's going on here please?.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Fresh install of ooba, here are my launch commands, connecting to Sillytavern, everything works fine until it doesn't randomly all of a sudden. I'm using Exllama HF as a loader with default settings running a 4k context llama 2 model.

--api --auto-launch

I also have api extension enabled.

### Logs

```shell
Traceback (most recent call last):
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\websockets\legacy\server.py", line 240, in handler
    await self.ws_handler(self)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\websockets\legacy\server.py", line 1186, in _ws_handler
    return await cast(
  File "C:\oobabooga_windows\text-generation-webui\extensions\api\streaming_api.py", line 89, in _handle_connection
    await _handle_stream_message(websocket, message)
  File "C:\oobabooga_windows\text-generation-webui\extensions\api\util.py", line 148, in api_wrapper
    return await func(*args, **kwargs)
  File "C:\oobabooga_windows\text-generation-webui\extensions\api\streaming_api.py", line 39, in _handle_stream_message
    await websocket.send(json.dumps({
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\websockets\legacy\protocol.py", line 635, in send
    await self.ensure_open()
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\websockets\legacy\protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1005 (no status code [internal]); then sent 1005 (no status code [internal])
```

### System Info

```shell
Windows 10 pro 64x
NVIDIA RTX 3060ti 8gb
```

**Comment by Ph0rk0z** [comment]
That is your server disconnecting.

**Comment by BadisG** [comment]
I have the same error, did someone manage to fix this?

**Comment by Gitikara** [comment]
Just adding in that I'm also still experiencing this error. Mine still works afterward and it's not preventing use, so it's probably not an urgent bug... but it was alarming to see all the red text, and I don't know enough to know if it has any performance impact in any regard.

**Comment by metamec** [comment]
Came here after seeing a post on Reddit.  I just can't get past this chronic word-for-word repetition problem with Oogabooga every time I try it.  Koboldcpp doesn't have the same problem with the same model with the same settings.
