### ISSUE TITLE
OSError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /root/miniconda3/envs/textgen/lib/python3.10/site-packages/ctransformers/lib/cuda/libctransformers.so)

### ISSUE THREAD

**Issue by thistleknot** [oobabooga/text-generation-webui#3949]
### Describe the bug

I can load a model as gguf using llama.cpp but not ctransformers

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

attempt to load a gguf models with ctransformers

### Logs

```shell
2023-09-15 20:52:29 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/data/text-generation-webui/modules/ui_model_menu.py", line 194, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/data/text-generation-webui/modules/models.py", line 77, in load_model
    output = load_func_map[loader](model_name)
  File "/data/text-generation-webui/modules/models.py", line 294, in ctransformers_loader
    model, tokenizer = ctrans.from_pretrained(model_file)
  File "/data/text-generation-webui/modules/ctransformers_model.py", line 27, in from_pretrained
    result.model = AutoModelForCausalLM.from_pretrained(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/ctransformers/hub.py", line 175, in from_pretrained
    llm = LLM(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/ctransformers/llm.py", line 246, in __init__
    self._lib = load_library(lib, gpu=config.gpu_layers > 0)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/ctransformers/llm.py", line 126, in load_library
    lib = CDLL(path)
  File "/root/miniconda3/envs/textgen/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /root/miniconda3/envs/textgen/lib/python3.10/site-packages/ctransformers/lib/cuda/libctransformers.so)
```

### System Info

```shell
rhel/centos/oracle/rocky linux 8
python 3.10 (using conda environment provided by text-generation-webui)
cuda 11.7 installed
```

I I attempt to add glibc 2.29 to the ld_library_path
```
(textgen) [root@pve0 text-generation-webui]# ./startserver.sh
Inconsistency detected by ld.so: dl-call-libc-early-init.c: 37: _dl_call_libc_early_init: Assertion `sym != NULL' failed!
(textgen) [root@pve0 text-generation-webui]# nano startserver.sh
(textgen) [root@pve0 text-generation-webui]# cat ./startserver.sh
#/bin/bash
#export LD_LIBRARY_PATH=/usr/local/glibc-2.29:$LD_LIBRARY_PATH:/usr/local/cuda-11.7/lib64 python server.py --api --extensions openai --listen
#env LD_LIBRARY_PATH=/usr/local/glibc-2.29:$LD_LIBRARY_PATH:/usr/local/cuda-11.7/lib64 python server.py --api --extensions openai --listen
#LD_LIBRARY_PATH=/usr/local/glibc-2.29:$LD_LIBRARY_PATH:/usr/local/cuda-11.7/lib64 python server.py --api --extensions openai --listen
#!/bin/bash
export LD_LIBRARY_PATH=/usr/local/glibc-2.29/lib:/usr/local/cuda-11.7/lib64$LD_LIBRARY_PATH
export PATH=/usr/local/glibc-2.29/bin:$PATH
#echo "LD_LIBRARY_PATH is set to: $LD_LIBRARY_PATH"
#ldd /root/miniconda3/envs/textgen/lib/python3.10/site-packages/ctransformers/lib/cuda/libctransformers.so
python server.py --api --extensions openai --listen

```

**Comment by evg-tyurin** [comment]
You cannot upgrade glibc version.
https://forums.rockylinux.org/t/upgrade-glibc-2-28-to-2-29/7558/4

You can recompile incompatible library from source, I guess.
