### ISSUE TITLE
I can't get start_windows.bat to work FIXED : Install Microsoft visual studios 2022 and select development for c++

### ISSUE THREAD

**Issue by Batarn** [oobabooga/text-generation-webui#3977]
### Describe the bug

Hello. Ever since I updated Oobabooga today, I'm getting an error where it refuses to start the WebUI.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Starting the Start_windows.bat file causes this.

### Logs

```shell
bin E:\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
 !! Unable to find cl.exe; compilation will probably fail
E:\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
INFO: Could not find files for the given pattern(s).
Traceback (most recent call last):
  File "E:\oobabooga_windows\text-generation-webui\server.py", line 29, in <module>
    from modules import (
  File "E:\oobabooga_windows\text-generation-webui\modules\ui_default.py", line 3, in <module>
    from modules import logits, shared, ui, utils
  File "E:\oobabooga_windows\text-generation-webui\modules\logits.py", line 5, in <module>
    from modules.exllamav2 import Exllamav2Model
  File "E:\oobabooga_windows\text-generation-webui\modules\exllamav2.py", line 5, in <module>
    from exllamav2 import (
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\exllamav2\__init__.py", line 3, in <module>
    from exllamav2.model import ExLlamaV2
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\exllamav2\model.py", line 12, in <module>
    from exllamav2.linear import ExLlamaV2Linear
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\exllamav2\linear.py", line 4, in <module>
    from exllamav2 import ext
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\exllamav2\ext.py", line 118, in <module>
    exllamav2_ext = load \
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 1611, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 2048, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 2188, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
  File "E:\oobabooga_windows\installer_files\env\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "E:\oobabooga_windows\installer_files\env\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.
Press any key to continue . . .
```

### System Info

```shell
Nvidia 3070
```

**Comment by Batarn** [comment]
I managed to fix it by downloading Microsoft visual studios 2022 and selecting development for c++. A few people suggested that in some of the other threads, thanks!

**Comment by crackerjam** [comment]
@Batarn Can you elaborate on specifically what you did to resolve this? I can't find any other issues that seem to reference cl.exe problems.
