### ISSUE TITLE
Error loading in 8bit mode on WSL

### ISSUE THREAD

**Issue by manassm** [oobabooga/text-generation-webui#398]
### Describe the bug

I recently installed WSL for the webui.
I wanted to use alpaca lora for llama model, so I tried starting it in 8bit mode, but it gave me error. 
Please let me know if you know how to fix this.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

(base) ssm05111@username:~$ conda activate textgen
(textgen) ssm05111@username:~$ cd text-generation-webui/
(textgen) ssm05111@username:~/text-generation-webui$ python server.py --load-in-8bit

### Logs

```shell
(base) ssm05111@username:~$ conda activate textgen
(textgen) ssm05111@username:~$ cd text-generation-webui/
(textgen) ssm05111@username:~/text-generation-webui$ python server.py --load-in-8bit

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/home/ssm05111/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: /home/ssm05111/miniconda3/envs/textgen did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
/home/ssm05111/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('unix')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
/home/ssm05111/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')}  warn(msg)
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
/home/ssm05111/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
/home/ssm05111/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Loading binary /home/ssm05111/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
/home/ssm05111/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
The following models are available:

1. EleutherAIpythia-1b-deduped
2. galactica-6.7b
3. gpt-j-6B
4. KoboldAIOPT-6.7B-Erebus
5. llama-7b-hf
6. opt-1.3b
7. pygmalion-6b_b8344bb4eb76a437797ad3b19420a13922aaabe1

Which one do you want to load? 1-7

5

Loading llama-7b-hf...
Loading checkpoint shards:   0%|                                                                 | 0/33 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ssm05111/text-generation-webui/server.py", line 236, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/ssm05111/text-generation-webui/modules/models.py", line 157, in load_model
    model = AutoModelForCausalLM.from_pretrained(checkpoint, **params)
  File "/home/ssm05111/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "/home/ssm05111/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2646, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/ssm05111/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2969, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/home/ssm05111/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/modeling_utils.py", line 676, in _load_state_dict_into_meta_model
    set_module_8bit_tensor_to_device(model, param_name, param_device, value=param)
  File "/home/ssm05111/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/utils/bitsandbytes.py", line 70, in set_module_8bit_tensor_to_device
    new_value = bnb.nn.Int8Params(new_value, requires_grad=False, has_fp16_weights=has_fp16_weights).to(device)
  File "/home/ssm05111/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 196, in to
    return self.cuda(device)
  File "/home/ssm05111/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 160, in cuda
    CB, CBt, SCB, SCBt, coo_tensorB = bnb.functional.double_quant(B)
  File "/home/ssm05111/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/functional.py", line 1616, in double_quant
    row_stats, col_stats, nnz_row_ptr = get_colrow_absmax(
  File "/home/ssm05111/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/functional.py", line 1505, in get_colrow_absmax
    lib.cget_col_row_stats(ptrA, ptrRowStats, ptrColStats, ptrNnzrows, ct.c_float(threshold), rows, cols)
  File "/home/ssm05111/miniconda3/envs/textgen/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/home/ssm05111/miniconda3/envs/textgen/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/ssm05111/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cget_col_row_stats
(textgen) ssm05111@username:~/text-generation-webui$
```

### System Info

```shell
Nvidia 4080
windows 11
```

**Comment by oobabooga** [comment]
See here https://github.com/oobabooga/text-generation-webui/issues/367

**Comment by manassm** [comment]
I looked for file named libbitsandbytes_cpu.so located in linux machine \wsl.localhost\Ubuntu\home\username\miniconda3\envs\textgen\lib\python3.10\site-packages\bitsandbytes, deleted it, and changed the file name of libbitsandbytes_cuda117.so into libbitsandbytes_cpu.so. It now seems to work. Thank you.
