### ISSUE TITLE
Answers and Questions in the chat disappear

### ISSUE THREAD

**Issue by Lim0n4ikS** [oobabooga/text-generation-webui#4000]
### Describe the bug

My questions and the assistant's answers disappear in the chat field. They appear for a split second and disappear. I managed to screen such a moment

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I run it according to the instructions. I tried it on YouTube videos

### Screenshot

![Безымянный](https://github.com/oobabooga/text-generation-webui/assets/145448933/199c18d8-6a5e-490f-8c2d-8d95c4eee9a1)
![Снимок](https://github.com/oobabooga/text-generation-webui/assets/145448933/5358782e-a700-459a-810e-5dfa0d0b292a)
![Снимок1](https://github.com/oobabooga/text-generation-webui/assets/145448933/18e349b4-03bc-4e81-981e-e9e9ff9f3e82)
![Снимок2](https://github.com/oobabooga/text-generation-webui/assets/145448933/cf62078e-a994-4135-8377-63c9e28ee11a)

### Logs

```shell
Traceback (most recent call last):
  File "S:\132\text-generation-webui\modules\callbacks.py", line 56, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "S:\132\text-generation-webui\modules\text_generation.py", line 347, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Users\Ad\AppData\Roaming\Python\Python310\site-packages\auto_gptq\modeling\_base.py", line 442, in generate
    with torch.inference_mode(), torch.amp.autocast(device_type=self.device.type):
  File "C:\Users\Ad\AppData\Roaming\Python\Python310\site-packages\auto_gptq\modeling\_base.py", line 431, in device
    device = [d for d in self.hf_device_map.values() if d not in {'cpu', 'disk'}][0]
IndexError: list index out of range
Output generated in 0.33 seconds (0.00 tokens/s, 0 tokens, context 27, seed 375598619)
Traceback (most recent call last):
  File "S:\132\text-generation-webui\modules\callbacks.py", line 56, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "S:\132\text-generation-webui\modules\text_generation.py", line 347, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Users\Ad\AppData\Roaming\Python\Python310\site-packages\auto_gptq\modeling\_base.py", line 442, in generate
    with torch.inference_mode(), torch.amp.autocast(device_type=self.device.type):
  File "C:\Users\Ad\AppData\Roaming\Python\Python310\site-packages\auto_gptq\modeling\_base.py", line 431, in device
    device = [d for d in self.hf_device_map.values() if d not in {'cpu', 'disk'}][0]
IndexError: list index out of range
Output generated in 0.33 seconds (0.00 tokens/s, 0 tokens, context 288, seed 1128061126)
Traceback (most recent call last):
  File "S:\132\text-generation-webui\modules\callbacks.py", line 56, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "S:\132\text-generation-webui\modules\text_generation.py", line 347, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Users\Ad\AppData\Roaming\Python\Python310\site-packages\auto_gptq\modeling\_base.py", line 442, in generate
    with torch.inference_mode(), torch.amp.autocast(device_type=self.device.type):
  File "C:\Users\Ad\AppData\Roaming\Python\Python310\site-packages\auto_gptq\modeling\_base.py", line 431, in device
    device = [d for d in self.hf_device_map.values() if d not in {'cpu', 'disk'}][0]
IndexError: list index out of range
Output generated in 0.33 seconds (0.00 tokens/s, 0 tokens, context 296, seed 1254700376)
Traceback (most recent call last):
  File "S:\132\text-generation-webui\modules\callbacks.py", line 56, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "S:\132\text-generation-webui\modules\text_generation.py", line 347, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Users\Ad\AppData\Roaming\Python\Python310\site-packages\auto_gptq\modeling\_base.py", line 442, in generate
    with torch.inference_mode(), torch.amp.autocast(device_type=self.device.type):
  File "C:\Users\Ad\AppData\Roaming\Python\Python310\site-packages\auto_gptq\modeling\_base.py", line 431, in device
    device = [d for d in self.hf_device_map.values() if d not in {'cpu', 'disk'}][0]
IndexError: list index out of range
Output generated in 0.33 seconds (0.00 tokens/s, 0 tokens, context 310, seed 1816613959)
Traceback (most recent call last):
  File "S:\132\text-generation-webui\modules\callbacks.py", line 56, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "S:\132\text-generation-webui\modules\text_generation.py", line 347, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Users\Ad\AppData\Roaming\Python\Python310\site-packages\auto_gptq\modeling\_base.py", line 442, in generate
    with torch.inference_mode(), torch.amp.autocast(device_type=self.device.type):
  File "C:\Users\Ad\AppData\Roaming\Python\Python310\site-packages\auto_gptq\modeling\_base.py", line 431, in device
    device = [d for d in self.hf_device_map.values() if d not in {'cpu', 'disk'}][0]
IndexError: list index out of range
Output generated in 0.33 seconds (0.00 tokens/s, 0 tokens, context 317, seed 1645292285)
Traceback (most recent call last):
  File "S:\132\text-generation-webui\modules\callbacks.py", line 56, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "S:\132\text-generation-webui\modules\text_generation.py", line 347, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Users\Ad\AppData\Roaming\Python\Python310\site-packages\auto_gptq\modeling\_base.py", line 442, in generate
    with torch.inference_mode(), torch.amp.autocast(device_type=self.device.type):
  File "C:\Users\Ad\AppData\Roaming\Python\Python310\site-packages\auto_gptq\modeling\_base.py", line 431, in device
    device = [d for d in self.hf_device_map.values() if d not in {'cpu', 'disk'}][0]
IndexError: list index out of range
Output generated in 0.33 seconds (0.00 tokens/s, 0 tokens, context 320, seed 2046362028)
```

### System Info

```shell
Windows 10 
Ryzen 5 5500
RAM 32gb
```

**Comment by Woisek** [comment]
Did you use the on click installer and did no update recently?

**Comment by Lim0n4ikS** [comment]
> Did you use the on click installer and did no update recently?

I tried both quick installation and manual

**Comment by Woisek** [comment]
I had this issue also once and it was because I used the on click install and the updates didn't go through complete, causing this problem later on. Only a complete update via bat file solved it (I used only git pull previously).

**Comment by Lim0n4ikS** [comment]
figured it out, didn't read the description of the models and ran it in the wrong environment)
