### ISSUE TITLE
Bump exllamav2 to fix "ValueError: invalid literal for int() with base 10: ‘post2’" with flash attention

### ISSUE THREAD

**Issue by dwraco** [oobabooga/text-generation-webui#4002]
### Describe the bug

When loading a model using exllamav2 and flash attention, the following error is produced:

```
2023-09-19 09:35:25 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/home/llm/text-generation-webui/modules/ui_model_menu.py", line 194, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/home/llm/text-generation-webui/modules/models.py", line 77, in load_model
    output = load_func_map[loader](model_name)
  File "/home/llm/text-generation-webui/modules/models.py", line 320, in ExLlamav2_loader
    from modules.exllamav2 import Exllamav2Model
  File "/home/llm/text-generation-webui/modules/exllamav2.py", line 5, in <module>
    from exllamav2 import (
  File "/home/llm/miniconda3/envs/textgen/lib/python3.10/site-packages/exllamav2/__init__.py", line 3, in <module>
    from exllamav2.model import ExLlamaV2
  File "/home/llm/miniconda3/envs/textgen/lib/python3.10/site-packages/exllamav2/model.py", line 15, in <module>
    from exllamav2.attn import ExLlamaV2Attention
  File "/home/llm/miniconda3/envs/textgen/lib/python3.10/site-packages/exllamav2/attn.py", line 19, in <module>
    flash_attn_ver = [int(t) for t in flash_attn.__version__.split(".")]
  File "/home/llm/miniconda3/envs/textgen/lib/python3.10/site-packages/exllamav2/attn.py", line 19, in <listcomp>
    flash_attn_ver = [int(t) for t in flash_attn.__version__.split(".")]
ValueError: invalid literal for int() with base 10: 'post2'
```

It looks like turboderp has fixed this issue in commit ec5164b8a8e282b91aedb2af94dfeb89887656b7 'Fix for non-numerical version number in flash-attn.' Just passing it along!

Thanks for all the work on these features!

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load a model using exllamav2 with flash attention installed.

### Logs

```shell
2023-09-19 09:35:25 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/home/llm/text-generation-webui/modules/ui_model_menu.py", line 194, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/home/llm/text-generation-webui/modules/models.py", line 77, in load_model
    output = load_func_map[loader](model_name)
  File "/home/llm/text-generation-webui/modules/models.py", line 320, in ExLlamav2_loader
    from modules.exllamav2 import Exllamav2Model
  File "/home/llm/text-generation-webui/modules/exllamav2.py", line 5, in <module>
    from exllamav2 import (
  File "/home/llm/miniconda3/envs/textgen/lib/python3.10/site-packages/exllamav2/__init__.py", line 3, in <module>
    from exllamav2.model import ExLlamaV2
  File "/home/llm/miniconda3/envs/textgen/lib/python3.10/site-packages/exllamav2/model.py", line 15, in <module>
    from exllamav2.attn import ExLlamaV2Attention
  File "/home/llm/miniconda3/envs/textgen/lib/python3.10/site-packages/exllamav2/attn.py", line 19, in <module>
    flash_attn_ver = [int(t) for t in flash_attn.__version__.split(".")]
  File "/home/llm/miniconda3/envs/textgen/lib/python3.10/site-packages/exllamav2/attn.py", line 19, in <listcomp>
    flash_attn_ver = [int(t) for t in flash_attn.__version__.split(".")]
ValueError: invalid literal for int() with base 10: 'post2'
```

### System Info

```shell
Ubuntu 22.04 running in WSL2 on Windows 10
2 x NVIDIA 3090 GPU
```

**Comment by hushaudio** [comment]
where do I find the fixed `exllamav2.py` to replace.  Can you link?

**Comment by practical-dreamer** [comment]
> thank you! For anyone else wondering how to fix this, installing from git didnt update it for me.
> 
> here is the commit with the line of code you need to change `https://github.com/turboderp/exllamav2/commit/ec5164b8a8e282b91aedb2af94dfeb89887656b7`
> 
> In the errors I found the file to fix: `File "/home/llm/miniconda3/envs/textgen/lib/python3.10/site-packages/exllamav2/attn.py"`

Can confirm this fixed it
