### ISSUE TITLE
KeyError: 'model.embed_tokens.weight' when trying to load a model using ExLlama-HF

### ISSUE THREAD

**Issue by pixol20** [oobabooga/text-generation-webui#4017]
### Describe the bug

On windows 11 I wanted to load a meta LLama 13b using ExLlama-hf but when i click load error message appears. I already loaded this model using transformers but it worked very slow. Same issue happens with every other model when loading with ExLlama-hf

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. execute start_windows.bat
2. in model tab select ExLlama as model loader

### Logs

```shell
Traceback (most recent call last):
  File "M:\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\ui_model_menu.py", line 194, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "M:\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\models.py", line 76, in load_model
    output = load_func_map[loader](model_name)
  File "M:\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\models.py", line 315, in ExLlama_HF_loader
    return ExllamaHF.from_pretrained(model_name)
  File "M:\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\exllama_hf.py", line 170, in from_pretrained
    return ExllamaHF(config)
  File "M:\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\exllama_hf.py", line 31, in __init__
    self.ex_model = ExLlama(self.ex_config)
  File "M:\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\exllama\model.py", line 852, in __init__
    self.embed_tokens.weight = nn.Parameter(tensors["model.embed_tokens.weight"])
KeyError: 'model.embed_tokens.weight'
```

### System Info

```shell
Intel core i5-13400F
32Gb RAM
RTX 3050 8gb VRAM
```

**Comment by pixol20** [comment]
My mistake i found same issue:
https://github.com/oobabooga/text-generation-webui/issues/2918
