### ISSUE TITLE
Openedai api embedding

### ISSUE THREAD

**Issue by TomiLikesToCode** [oobabooga/text-generation-webui#4050]
I cant find it anywhere but how do i run embedding models on windows. I installed via one-click installer.

**Comment by felipemeres** [comment]
just set the api url of your instance as the basepath for the tokenizer you are using (the one in langchain for example)

**Comment by TomiLikesToCode** [comment]
can you explain it please?

**Comment by TomiLikesToCode** [comment]
> just set the api url of your instance as the basepath for the tokenizer you are using (the one in langchain for example)

can you explain it please?

**Comment by yhyu13** [comment]
@TomiLikesToCode 

The embedding layer should download and load automatically by the openai api extension readme. https://github.com/oobabooga/text-generation-webui/blob/main/extensions/openai/README.md

Code that implemets embedding using setence transformer https://github.com/oobabooga/text-generation-webui/blob/main/extensions/openai/embeddings.py

Note, The openai api extension emebedding has bugs in "encode" method

```
OpenAIError TypeError('encode() takes at most 2 arguments (5 given)')
Traceback (most recent call last):
  File "/root/CodeSpace/text-generation-webui/extensions/openai/script.py", line 114, in wrapper
    func(self)
  File "/root/CodeSpace/text-generation-webui/extensions/openai/script.py", line 283, in do_POST
    response = OAIembeddings.embeddings(input, encoding_format)
  File "/root/CodeSpace/text-generation-webui/extensions/openai/embeddings.py", line 63, in embeddings
    embeddings = get_embeddings(input)
  File "/root/CodeSpace/text-generation-webui/extensions/openai/embeddings.py", line 58, in get_embeddings
    return get_embeddings_model().encode(input, convert_to_numpy=True, normalize_embeddings=True, convert_to_tensor=False, device=embeddings_device)
TypeError: encode() takes at most 2 arguments (5 given)
```
