### ISSUE TITLE
ModuleNotFoundError: No module named 'gradio'

### ISSUE THREAD

**Issue by yumianhuli1** [oobabooga/text-generation-webui#4056]
### Describe the bug

win11@win11-Vector-GP76HX-12UHS:~/githubPublic/text-generation-webui$ ./start_linux.sh
*******************************************************************
* WARNING: You haven't downloaded any model yet.
* Once the web UI launches, head over to the "Model" tab and download one.
*******************************************************************

Traceback (most recent call last):
  File "/home/win11/githubPublic/text-generation-webui/server.py", line 13, in <module>
    import gradio as gr
**ModuleNotFoundError: No module named 'gradio'**
win11@win11-Vector-GP76HX-12UHS:~/githubPublic/text-generation-webui$ pip list
Package                   Version             
------------------------- --------------------
aiofiles                  23.2.1              
altair                    5.1.1               
annotated-types           0.5.0               
anyio                     3.7.1               
apturl                    0.5.2               
attrs                     23.1.0              
bcrypt                    3.1.7               
blinker                   1.4                 
Brlapi                    0.7.0               
certifi                   2019.11.28          
chardet                   3.0.4               
Click                     7.0                 
colorama                  0.4.3               
command-not-found         0.3                 
contourpy                 1.1.1               
cryptography              2.8                 
cupshelpers               1.0                 
cycler                    0.11.0              
dbus-python               1.2.16              
defer                     1.0.6               
distro                    1.4.0               
distro-info               0.23+ubuntu1.1      
duplicity                 0.8.12.0            
entrypoints               0.3                 
exceptiongroup            1.1.3               
fastapi                   0.103.1             
fasteners                 0.14.1              
ffmpy                     0.3.1               
filelock                  3.12.4              
fonttools                 4.42.1              
fsspec                    2023.9.2            
future                    0.18.2              
**gradio                    3.44.4**              
gradio-client             0.5.1               
h11                       0.14.0  

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

/start_linux.sh

### Logs

```shell
win11@win11-Vector-GP76HX-12UHS:~/githubPublic/text-generation-webui$ ./start_linux.sh
*******************************************************************
* WARNING: You haven't downloaded any model yet.
* Once the web UI launches, head over to the "Model" tab and download one.
*******************************************************************


Traceback (most recent call last):
  File "/home/win11/githubPublic/text-generation-webui/server.py", line 13, in <module>
    import gradio as gr
**ModuleNotFoundError: No module named 'gradio'**
win11@win11-Vector-GP76HX-12UHS:~/githubPublic/text-generation-webui$ pip list
Package                   Version             
------------------------- --------------------
aiofiles                  23.2.1              
altair                    5.1.1               
annotated-types           0.5.0               
anyio                     3.7.1               
apturl                    0.5.2               
attrs                     23.1.0              
bcrypt                    3.1.7               
blinker                   1.4                 
Brlapi                    0.7.0               
certifi                   2019.11.28          
chardet                   3.0.4               
Click                     7.0                 
colorama                  0.4.3               
command-not-found         0.3                 
contourpy                 1.1.1               
cryptography              2.8                 
cupshelpers               1.0                 
cycler                    0.11.0              
dbus-python               1.2.16              
defer                     1.0.6               
distro                    1.4.0               
distro-info               0.23+ubuntu1.1      
duplicity                 0.8.12.0            
entrypoints               0.3                 
exceptiongroup            1.1.3               
fastapi                   0.103.1             
fasteners                 0.14.1              
ffmpy                     0.3.1               
filelock                  3.12.4              
fonttools                 4.42.1              
fsspec                    2023.9.2            
future                    0.18.2              
**gradio                    3.44.4**              
gradio-client             0.5.1               
h11                       0.14.0
```

### System Info

```shell
ubuntu20.04
RTX3080Ti
```

**Comment by ropebourge** [comment]
I'm having the same issue.  It can be fixed by running the update script but I think the problem is coming from an install error:

This is on a fresh install of Win11

Copy/Paste below

Using cached fsspec-2023.9.2-py3-none-any.whl (173 kB)
Building wheels for collected packages: sentence-transformers
  Building wheel for sentence-transformers (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [130 lines of output]
      D:\AI\text-generation-webui-main\text-generation-webui-main\installer_files\env\lib\site-packages\setuptools\dist.py:745: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!

              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.

              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.warn_dash_deprecation(opt, section)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib
      creating build\lib\sentence_transformers
      copying sentence_transformers\LoggingHandler.py -> build\lib\sentence_transformers
      copying sentence_transformers\model_card_templates.py -> build\lib\sentence_transformers
      copying sentence_transformers\SentenceTransformer.py -> build\lib\sentence_transformers
      copying sentence_transformers\util.py -> build\lib\sentence_transformers
      copying sentence_transformers\__init__.py -> build\lib\sentence_transformers
      creating build\lib\sentence_transformers\cross_encoder
      copying sentence_transformers\cross_encoder\CrossEncoder.py -> build\lib\sentence_transformers\cross_encoder
      copying sentence_transformers\cross_encoder\__init__.py -> build\lib\sentence_transformers\cross_encoder
      creating build\lib\sentence_transformers\datasets
      copying sentence_transformers\datasets\DenoisingAutoEncoderDataset.py -> build\lib\sentence_transformers\datasets
      copying sentence_transformers\datasets\NoDuplicatesDataLoader.py -> build\lib\sentence_transformers\datasets
      copying sentence_transformers\datasets\ParallelSentencesDataset.py -> build\lib\sentence_transformers\datasets
      copying sentence_transformers\datasets\SentenceLabelDataset.py -> build\lib\sentence_transformers\datasets
      copying sentence_transformers\datasets\SentencesDataset.py -> build\lib\sentence_transformers\datasets
      copying sentence_transformers\datasets\__init__.py -> build\lib\sentence_transformers\datasets
      creating build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\BinaryClassificationEvaluator.py -> build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\EmbeddingSimilarityEvaluator.py -> build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\InformationRetrievalEvaluator.py -> build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\LabelAccuracyEvaluator.py -> build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\MSEEvaluator.py -> build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\MSEEvaluatorFromDataFrame.py -> build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\ParaphraseMiningEvaluator.py -> build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\RerankingEvaluator.py -> build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\SentenceEvaluator.py -> build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\SequentialEvaluator.py -> build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\SimilarityFunction.py -> build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\TranslationEvaluator.py -> build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\TripletEvaluator.py -> build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\__init__.py -> build\lib\sentence_transformers\evaluation
      creating build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\BatchAllTripletLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\BatchHardSoftMarginTripletLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\BatchHardTripletLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\BatchSemiHardTripletLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\ContrastiveLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\ContrastiveTensionLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\CosineSimilarityLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\DenoisingAutoEncoderLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\MarginMSELoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\MegaBatchMarginLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\MSELoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\MultipleNegativesRankingLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\MultipleNegativesSymmetricRankingLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\OnlineContrastiveLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\SoftmaxLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\TripletLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\__init__.py -> build\lib\sentence_transformers\losses
      creating build\lib\sentence_transformers\models
      copying sentence_transformers\models\Asym.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\BoW.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\CLIPModel.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\CNN.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\Dense.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\Dropout.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\LayerNorm.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\LSTM.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\Normalize.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\Pooling.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\Transformer.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\WeightedLayerPooling.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\WordEmbeddings.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\WordWeights.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\__init__.py -> build\lib\sentence_transformers\models
      creating build\lib\sentence_transformers\readers
      copying sentence_transformers\readers\InputExample.py -> build\lib\sentence_transformers\readers
      copying sentence_transformers\readers\LabelSentenceReader.py -> build\lib\sentence_transformers\readers
      copying sentence_transformers\readers\NLIDataReader.py -> build\lib\sentence_transformers\readers
      copying sentence_transformers\readers\PairedFilesReader.py -> build\lib\sentence_transformers\readers
      copying sentence_transformers\readers\STSDataReader.py -> build\lib\sentence_transformers\readers
      copying sentence_transformers\readers\TripletReader.py -> build\lib\sentence_transformers\readers
      copying sentence_transformers\readers\__init__.py -> build\lib\sentence_transformers\readers
      creating build\lib\sentence_transformers\cross_encoder\evaluation
      copying sentence_transformers\cross_encoder\evaluation\CEBinaryAccuracyEvaluator.py -> build\lib\sentence_transformers\cross_encoder\evaluation
      copying sentence_transformers\cross_encoder\evaluation\CEBinaryClassificationEvaluator.py -> build\lib\sentence_transformers\cross_encoder\evaluation
      copying sentence_transformers\cross_encoder\evaluation\CECorrelationEvaluator.py -> build\lib\sentence_transformers\cross_encoder\evaluation
      copying sentence_transformers\cross_encoder\evaluation\CERerankingEvaluator.py -> build\lib\sentence_transformers\cross_encoder\evaluation
      copying sentence_transformers\cross_encoder\evaluation\CESoftmaxAccuracyEvaluator.py -> build\lib\sentence_transformers\cross_encoder\evaluation
      copying sentence_transformers\cross_encoder\evaluation\__init__.py -> build\lib\sentence_transformers\cross_encoder\evaluation
      creating build\lib\sentence_transformers\models\tokenizer
      copying sentence_transformers\models\tokenizer\PhraseTokenizer.py -> build\lib\sentence_transformers\models\tokenizer
      copying sentence_transformers\models\tokenizer\WhitespaceTokenizer.py -> build\lib\sentence_transformers\models\tokenizer
      copying sentence_transformers\models\tokenizer\WordTokenizer.py -> build\lib\sentence_transformers\models\tokenizer
      copying sentence_transformers\models\tokenizer\__init__.py -> build\lib\sentence_transformers\models\tokenizer
      D:\AI\text-generation-webui-main\text-generation-webui-main\installer_files\env\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        self.initialize_options()
      installing to build\bdist.win-amd64\wheel
      running install
      running install_lib
      creating build\bdist.win-amd64
      creating build\bdist.win-amd64\wheel
      creating build\bdist.win-amd64\wheel\sentence_transformers
      creating build\bdist.win-amd64\wheel\sentence_transformers\cross_encoder
      copying build\lib\sentence_transformers\cross_encoder\CrossEncoder.py -> build\bdist.win-amd64\wheel\.\sentence_transformers\cross_encoder
      creating build\bdist.win-amd64\wheel\sentence_transformers\cross_encoder\evaluation
      copying build\lib\sentence_transformers\cross_encoder\evaluation\CEBinaryAccuracyEvaluator.py -> build\bdist.win-amd64\wheel\.\sentence_transformers\cross_encoder\evaluation
      copying build\lib\sentence_transformers\cross_encoder\evaluation\CEBinaryClassificationEvaluator.py -> build\bdist.win-amd64\wheel\.\sentence_transformers\cross_encoder\evaluation
      error: could not create 'build\bdist.win-amd64\wheel\.\sentence_transformers\cross_encoder\evaluation\CEBinaryClassificationEvaluator.py': No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for sentence-transformers
  Running setup.py clean for sentence-transformers
Failed to build sentence-transformers
ERROR: Could not build wheels for sentence-transformers, which is required to install pyproject.toml-based projects
Command '"D:\AI\text-generation-webui-main\text-generation-webui-main\installer_files\conda\condabin\conda.bat" activate "D:\AI\text-generation-webui-main\text-generation-webui-main\installer_files\env" >nul && python -m pip install -r extensions\openai\requirements.txt --upgrade' failed with exit status code '1'. Exiting...
Press any key to continue . . .

**Comment by rook2pawn** [comment]
> I'm having the same issue. It can be fixed by running the update script but I think the problem is coming from an install error:
> 
> This is on a fresh install of Win11


I also am having a "No module named gradio" issue as well on fresh install. This is on Win10

**Comment by Impre-visible** [comment]
I'm having the same error, but I'm on ubuntu 22.04
