### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets'

### ISSUE THREAD

**Issue by rwmjhb** [oobabooga/text-generation-webui#4057]
### Describe the bug

I did "One-click installers" on my windows11,and at first everything is fine,then the installer reminded me I should Migrat from an old one-click install,I did it also,and nothing is wrong so far.
When I ran start_windows.bat,there was an error info"ModuleNotFoundError: No module named 'gradio'",I searched the issue and pip install markdown peft protobuf gradio,and ran the start_windows.bat again.
The error "ModuleNotFoundError: No module named 'datasets'" showed.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

same to up

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\admin\Documents\text-generation-webui\server.py", line 30, in <module>
    from modules import (
  File "C:\Users\admin\Documents\text-generation-webui\modules\training.py", line 20, in <module>
    from datasets import Dataset, load_dataset
ModuleNotFoundError: No module named 'datasets'
```

### System Info

```shell
win11
3070 8G
```

**Comment by oobabooga** [comment]
The datasets package is in the requirements.txt for the project. The fact that datasets and gradio haven't been found suggests that the install hasn't completed due to some error. Can you try deleting the `installer_files` folder and running the start script again?

**Comment by rwmjhb** [comment]
> The datasets package is in the requirements.txt for the project. The fact that datasets and gradio haven't been found suggests that the install hasn't completed due to some error. Can you try deleting the `installer_files` folder and running the start script again?

just like issue #4063 
I deleted the install_files and ran start_windows.bat,the error was
`fatal: unable to access 'https://github.com/oobabooga/text-generation-webui.git/': Recv failure: Connection was reset
Command '"C:\Users\admin\Documents\text-generation-webui\installer_files\conda\condabin\conda.bat" activate "C:\Users\admin\Documents\text-generation-webui\installer_files\env" >nul && git pull --autostash' failed with exit status code '1'. Exiting...`

and ran start_windows.bat again,the error was 
`Traceback (most recent call last):
  File "C:\Users\admin\Documents\text-generation-webui\server.py", line 13, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'`

and ran update_windows.bat,it showed
`fatal: unable to access 'https://github.com/oobabooga/text-generation-webui.git/': Recv failure: Connection was reset
Command '"C:\Users\admin\Documents\text-generation-webui\installer_files\conda\condabin\conda.bat" activate "C:\Users\admin\Documents\text-generation-webui\installer_files\env" >nul && git pull --autostash' failed with exit status code '1'. Exiting...

Done!`

now,I runing start_windows.bat,it also shows the same error.
`Traceback (most recent call last):
  File "C:\Users\admin\Documents\text-generation-webui\server.py", line 13, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'`

**Comment by rwmjhb** [comment]
I searched the some issus with key word"gradio",and got some ideas.
ran cmd_windows.bat,
and pip install markdown peft protobuf gradio,
then running start_windows.bat,and back to the top problem.
so I pip install datasets,
then running start_windwos one more time,it looks like work now.The teminal shows
`C:\Users\admin\Documents\text-generation-webui\installer_files\env\lib\site-packages\gradio\components\dropdown.py:238: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include:  or set allow_custom_value=True.
  warnings.warn(
C:\Users\admin\Documents\text-generation-webui\installer_files\env\lib\site-packages\gradio\components\dropdown.py:238: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: None or set allow_custom_value=True.
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.`

but I thought maybe I would run update_windows.bat again,so I did it.And god save me ,it worked,none of error showed.
Finnally,running start_windows.bat,it also worked well.
