### ISSUE TITLE
[BUG]: ValueError on startup

### ISSUE THREAD

**Issue by Woisek** [oobabooga/text-generation-webui#4069]
### Describe the bug

After todays update, I get a ValueError when starting ooba.
Not sure if it affects anything so far, but I wanted to report it.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Start ooba

### Screenshot

![Zwischenablagebild](https://github.com/oobabooga/text-generation-webui/assets/122026301/b42fe79b-c2c2-45b7-88c0-58c5fafb3c0f)

### Logs

```shell
Starting API at http://127.0.0.1:5000/api
Running on local URL:  http://127.0.0.1:7862

To create a public link, set `share=True` in `launch()`.
2023-09-25 10:00:46 ERROR:Could not find the character "None" inside instruction-templates/. No character has been loaded.
Traceback (most recent call last):
  File "F:\Programme\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\Programme\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "F:\Programme\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\Programme\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "F:\Programme\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2106, in run_sync_in_worker_thread
    return await future
  File "F:\Programme\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 833, in run
    result = context.run(func, *args)
  File "F:\Programme\oobabooga_windows\text-generation-webui\modules\chat.py", line 561, in load_character
    raise ValueError
ValueError
```

### System Info

```shell
Win10, Nvidia RTX 2070 SUPER 8GB VRAM
```

**Comment by skaba04** [comment]
I have a same issue loading the --share --public-api and api extension
