### ISSUE TITLE
Unable to load CodeLlama at all

### ISSUE THREAD

**Issue by alexlnkp** [oobabooga/text-generation-webui#4071]
### Describe the bug

The title speaks for itself, CodeLlama is unable to load no matter how hard i try. The version i'm using is 34b, here's a [**link**](https://huggingface.co/codellama/CodeLlama-34b-hf)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Download `codellama/CodeLlama-34b-hf` and try to load it.

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/79400603/808b6880-dfb0-48b2-b059-cec4be047b0c)
![image](https://github.com/oobabooga/text-generation-webui/assets/79400603/a845b07f-5329-4ba1-b70b-0e18bbbf29a6)
![image](https://github.com/oobabooga/text-generation-webui/assets/79400603/c7dbd2e5-3922-49ac-827c-5097c848b2be)
![image](https://github.com/oobabooga/text-generation-webui/assets/79400603/19e0a2a0-7565-4180-b25e-d28aeb5899c9)
![image](https://github.com/oobabooga/text-generation-webui/assets/79400603/17a451b9-bbc7-4df7-93f5-de7efea0c80d)
![image](https://github.com/oobabooga/text-generation-webui/assets/79400603/c0d0bfb4-8a79-46bf-b141-adb541f5f067)
![image](https://github.com/oobabooga/text-generation-webui/assets/79400603/195879e6-6375-4ac8-8082-23da9b9e20c2)
![image](https://github.com/oobabooga/text-generation-webui/assets/79400603/dc0ed046-78f0-4578-b519-6b5950cc05be)
![image](https://github.com/oobabooga/text-generation-webui/assets/79400603/1b8c844a-227b-4916-b331-11ba32a21f67)
![image](https://github.com/oobabooga/text-generation-webui/assets/79400603/a90765e7-7fa8-4e66-be23-3f540c606c3a)

### Logs

```shell
# Transformers

2023-09-25 18:59:43 INFO:Loading codellama_CodeLlama-34b-hf...
2023-09-25 18:59:43 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "D:\text-generation-webui-1.6\modules\ui_model_menu.py", line 194, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "D:\text-generation-webui-1.6\modules\models.py", line 76, in load_model
    output = load_func_map[loader](model_name)
  File "D:\text-generation-webui-1.6\modules\models.py", line 130, in huggingface_loader
    model = LoaderClass.from_pretrained(Path(f"{shared.args.model_dir}/{model_name}"), low_cpu_mem_usage=True, torch_dtype=torch.bfloat16 if shared.args.bf16 else torch.float16, trust_remote_code=shared.args.trust_remote_code)
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2982, in from_pretrained
    resolved_archive_file, sharded_metadata = get_checkpoint_shard_files(
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\transformers\utils\hub.py", line 1017, in get_checkpoint_shard_files
    index = json.loads(f.read())
  File "D:\text-generation-webui-1.6\installer_files\env\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\text-generation-webui-1.6\installer_files\env\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 298 column 2 (char 25125)
```

# ExLlama_HF
```
2023-09-25 19:00:19 INFO:Loading codellama_CodeLlama-34b-hf...
2023-09-25 19:00:19 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "D:\text-generation-webui-1.6\modules\ui_model_menu.py", line 194, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "D:\text-generation-webui-1.6\modules\models.py", line 76, in load_model
    output = load_func_map[loader](model_name)
  File "D:\text-generation-webui-1.6\modules\models.py", line 315, in ExLlama_HF_loader
    return ExllamaHF.from_pretrained(model_name)
  File "D:\text-generation-webui-1.6\modules\exllama_hf.py", line 170, in from_pretrained
    return ExllamaHF(config)
  File "D:\text-generation-webui-1.6\modules\exllama_hf.py", line 31, in __init__
    self.ex_model = ExLlama(self.ex_config)
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\exllama\model.py", line 814, in __init__
    device = self.config.device_map.map(key)
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\exllama\model.py", line 666, in map
    return self.layers[num]
IndexError: list index out of range
```

# ExLlamav2_HF
```
2023-09-25 19:00:55 INFO:Loading codellama_CodeLlama-34b-hf...
2023-09-25 19:00:55 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "D:\text-generation-webui-1.6\modules\ui_model_menu.py", line 194, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "D:\text-generation-webui-1.6\modules\models.py", line 76, in load_model
    output = load_func_map[loader](model_name)
  File "D:\text-generation-webui-1.6\modules\models.py", line 326, in ExLlamav2_HF_loader
    from modules.exllamav2_hf import Exllamav2HF
  File "D:\text-generation-webui-1.6\modules\exllamav2_hf.py", line 6, in <module>
    from exllamav2 import ExLlamaV2, ExLlamaV2Cache, ExLlamaV2Config
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\exllamav2\__init__.py", line 3, in <module>
    from exllamav2.model import ExLlamaV2
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\exllamav2\model.py", line 12, in <module>
    from exllamav2.linear import ExLlamaV2Linear
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\exllamav2\linear.py", line 5, in <module>
    from exllamav2 import ext
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\exllamav2\ext.py", line 118, in <module>
    exllamav2_ext = load \
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 1535, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 1929, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: DLL load failed while importing exllamav2_ext: Не найден указанный модуль.
```

# ExLlama
```
2023-09-25 19:01:17 INFO:Loading codellama_CodeLlama-34b-hf...
2023-09-25 19:01:17 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "D:\text-generation-webui-1.6\modules\ui_model_menu.py", line 194, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "D:\text-generation-webui-1.6\modules\models.py", line 76, in load_model
    output = load_func_map[loader](model_name)
  File "D:\text-generation-webui-1.6\modules\models.py", line 308, in ExLlama_loader
    model, tokenizer = ExllamaModel.from_pretrained(model_name)
  File "D:\text-generation-webui-1.6\modules\exllama.py", line 75, in from_pretrained
    model = ExLlama(config)
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\exllama\model.py", line 814, in __init__
    device = self.config.device_map.map(key)
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\exllama\model.py", line 666, in map
    return self.layers[num]
IndexError: list index out of range
```

# ExLlamav2
```
2023-09-25 19:01:42 INFO:Loading codellama_CodeLlama-34b-hf...
2023-09-25 19:01:42 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "D:\text-generation-webui-1.6\modules\ui_model_menu.py", line 194, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "D:\text-generation-webui-1.6\modules\models.py", line 76, in load_model
    output = load_func_map[loader](model_name)
  File "D:\text-generation-webui-1.6\modules\models.py", line 319, in ExLlamav2_loader
    from modules.exllamav2 import Exllamav2Model
  File "D:\text-generation-webui-1.6\modules\exllamav2.py", line 5, in <module>
    from exllamav2 import (
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\exllamav2\__init__.py", line 3, in <module>
    from exllamav2.model import ExLlamaV2
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\exllamav2\model.py", line 12, in <module>
    from exllamav2.linear import ExLlamaV2Linear
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\exllamav2\linear.py", line 5, in <module>
    from exllamav2 import ext
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\exllamav2\ext.py", line 118, in <module>
    exllamav2_ext = load \
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 1535, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 1929, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: DLL load failed while importing exllamav2_ext: Не найден указанный модуль.
```

# AutoGPTQ
```
2023-09-25 19:02:04 INFO:Loading codellama_CodeLlama-34b-hf...
2023-09-25 19:02:04 INFO:The AutoGPTQ params are: {'model_basename': 'model-00007-of-00007', 'device': 'cuda:0', 'use_triton': False, 'inject_fused_attention': True, 'inject_fused_mlp': True, 'use_safetensors': True, 'trust_remote_code': False, 'max_memory': None, 'quantize_config': BaseQuantizeConfig(bits=4, group_size=-1, damp_percent=0.01, desc_act=False, static_groups=False, sym=True, true_sequential=True, model_name_or_path=None, model_file_base_name=None), 'use_cuda_fp16': True, 'disable_exllama': False}
2023-09-25 19:02:09 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "D:\text-generation-webui-1.6\modules\ui_model_menu.py", line 194, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "D:\text-generation-webui-1.6\modules\models.py", line 76, in load_model
    output = load_func_map[loader](model_name)
  File "D:\text-generation-webui-1.6\modules\models.py", line 302, in AutoGPTQ_loader
    return modules.AutoGPTQ_loader.load_quantized(model_name)
  File "D:\text-generation-webui-1.6\modules\AutoGPTQ_loader.py", line 57, in load_quantized
    model = AutoGPTQForCausalLM.from_quantized(path_to_model, **params)
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\auto_gptq\modeling\auto.py", line 108, in from_quantized
    return quant_func(
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\auto_gptq\modeling\_base.py", line 875, in from_quantized
    accelerate.utils.modeling.load_checkpoint_in_model(
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\accelerate\utils\modeling.py", line 1414, in load_checkpoint_in_model
    set_module_tensor_to_device(
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\accelerate\utils\modeling.py", line 285, in set_module_tensor_to_device
    raise ValueError(
ValueError: Trying to set a tensor of shape torch.Size([32000, 8192]) in "weight" (which has shape torch.Size([32016, 4096])), this look incorrect.
```

# GPTQ-for-LLaMa
```
2023-09-25 19:02:36 INFO:Loading codellama_CodeLlama-34b-hf...
2023-09-25 19:02:36 INFO:Found the following quantized model: models\codellama_CodeLlama-34b-hf\model-00007-of-00007.safetensors
2023-09-25 19:02:36 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "D:\text-generation-webui-1.6\modules\ui_model_menu.py", line 194, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "D:\text-generation-webui-1.6\modules\models.py", line 76, in load_model
    output = load_func_map[loader](model_name)
  File "D:\text-generation-webui-1.6\modules\models.py", line 294, in GPTQ_loader
    model = modules.GPTQ_loader.load_quantized(model_name)
  File "D:\text-generation-webui-1.6\modules\GPTQ_loader.py", line 144, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.wbits, shared.args.groupsize, kernel_switch_threshold=threshold)
  File "D:\text-generation-webui-1.6\modules\GPTQ_loader.py", line 58, in _load_quant
    make_quant(**make_quant_kwargs)
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\gptq_for_llama\gptq_old\quant.py", line 446, in make_quant
    make_quant(child, names, bits, groupsize, faster, name + '.' + name1 if name != '' else name1, kernel_switch_threshold=kernel_switch_threshold)
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\gptq_for_llama\gptq_old\quant.py", line 446, in make_quant
    make_quant(child, names, bits, groupsize, faster, name + '.' + name1 if name != '' else name1, kernel_switch_threshold=kernel_switch_threshold)
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\gptq_for_llama\gptq_old\quant.py", line 446, in make_quant
    make_quant(child, names, bits, groupsize, faster, name + '.' + name1 if name != '' else name1, kernel_switch_threshold=kernel_switch_threshold)
  [Previous line repeated 1 more time]
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\gptq_for_llama\gptq_old\quant.py", line 443, in make_quant
    module, attr, QuantLinear(bits, groupsize, tmp.in_features, tmp.out_features, faster=faster, kernel_switch_threshold=kernel_switch_threshold)
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\gptq_for_llama\gptq_old\quant.py", line 142, in __init__
    raise NotImplementedError("Only 2,3,4,8 bits are supported.")
NotImplementedError: Only 2,3,4,8 bits are supported.
```
trying to set `wbits` to `2` leads to this:
```
2023-09-25 19:03:09 INFO:Loading codellama_CodeLlama-34b-hf...
2023-09-25 19:03:09 INFO:Found the following quantized model: models\codellama_CodeLlama-34b-hf\model-00007-of-00007.safetensors
2023-09-25 19:03:09 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "D:\text-generation-webui-1.6\modules\ui_model_menu.py", line 194, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "D:\text-generation-webui-1.6\modules\models.py", line 76, in load_model
    output = load_func_map[loader](model_name)
  File "D:\text-generation-webui-1.6\modules\models.py", line 294, in GPTQ_loader
    model = modules.GPTQ_loader.load_quantized(model_name)
  File "D:\text-generation-webui-1.6\modules\GPTQ_loader.py", line 144, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.wbits, shared.args.groupsize, kernel_switch_threshold=threshold)
  File "D:\text-generation-webui-1.6\modules\GPTQ_loader.py", line 63, in _load_quant
    model.load_state_dict(safe_load(checkpoint), strict=False)
  File "D:\text-generation-webui-1.6\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LlamaForCausalLM:
        size mismatch for model.norm.weight: copying a param with shape torch.Size([8192]) from checkpoint, the shape in current model is torch.Size([4096]).
        size mismatch for lm_head.weight: copying a param with shape torch.Size([32000, 8192]) from checkpoint, the shape in current model is torch.Size([32016, 4096]).
```

# llama.cpp
```
2023-09-25 19:04:13 INFO:Loading codellama_CodeLlama-34b-hf...
2023-09-25 19:04:13 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "D:\text-generation-webui-1.6\modules\ui_model_menu.py", line 194, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "D:\text-generation-webui-1.6\modules\models.py", line 76, in load_model
    output = load_func_map[loader](model_name)
  File "D:\text-generation-webui-1.6\modules\models.py", line 225, in llamacpp_loader
    model_file = list(Path(f'{shared.args.model_dir}/{model_name}').glob('*.gguf'))[0]
IndexError: list index out of range
```

# llamacpp_HF
```
2023-09-25 19:04:32 INFO:Loading codellama_CodeLlama-34b-hf...
2023-09-25 19:04:32 INFO:Using tokenizer from: models\codellama_CodeLlama-34b-hf
2023-09-25 19:04:32 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "D:\text-generation-webui-1.6\modules\ui_model_menu.py", line 194, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "D:\text-generation-webui-1.6\modules\models.py", line 76, in load_model
    output = load_func_map[loader](model_name)
  File "D:\text-generation-webui-1.6\modules\models.py", line 250, in llamacpp_HF_loader
    model = LlamacppHF.from_pretrained(model_name)
  File "D:\text-generation-webui-1.6\modules\llamacpp_hf.py", line 182, in from_pretrained
    model_file = list(path.glob('*.gguf'))[0]
IndexError: list index out of range
```

# ctransformers
```
2023-09-25 19:04:54 INFO:Loading codellama_CodeLlama-34b-hf...
2023-09-25 19:04:54 ERROR:Could not find a model for ctransformers.
2023-09-25 19:04:54 INFO:Loaded the model in 0.00 seconds.
```
```


### System Info

```shell
GPU: `Nvidia RTX 3060 12Gb`
CPU: `Intel Core i5-12400F 2.50 GHz`
RAM: `32Gb`

Local.
```

**Comment by alexlnkp** [comment]
yeah it's not actually a bug i presume, i just can't load it at all for some odd reason..
maybe i'm just a dummie, in that case i'd like if you could help me

**Comment by nixudos** [comment]
Looks like you are trying to use an unquantisized model. I have a feeling that it is not what you intended, unless you have a very very strong PC..?

Try a GGUF version from The Bloke: https://huggingface.co/TheBloke/Phind-CodeLlama-34B-v2-GGUF/tree/main

**Comment by SrVill** [comment]
This model is in transformer format, so it cannot be run on your configuration. The simplest thing to do is to run this model quantized in gguf format. You can try to run it in GPTQ format with loading part of the layers into RAM. It is impossible to run in exllama and exl2 formats due to insufficient VRAM

**Comment by alexlnkp** [comment]
> Looks like you are trying to use an unquantisized model. I have a feeling that it is not what you intended, unless you have a very very strong PC..?
> 
> Try a GGUF version from The Bloke: https://huggingface.co/TheBloke/Phind-CodeLlama-34B-v2-GGUF/tree/main

Yeah that makes sense.
Sorry, I'm new to all this stuff.

Will try it out, thanks!

**Comment by alexlnkp** [comment]
Yeah, turns out i was using the wrong model.

Sorry guys for bothering you with dumb questions, but thanks a lot for helping me :)
