### ISSUE TITLE
LoRA only training partway

### ISSUE THREAD

**Issue by sardanian** [oobabooga/text-generation-webui#4074]
### Describe the bug

Whenever I use the model **TheBloke_Llama-2-70B-chat-GPTQ** with **Transformers**, it loads up fine (I use auto-devices and put 21Gs of VRAM per device). However when I begin training it on a raw text file, it trains for just under 2 minutes (exact time varies) about 10% of the training.

An error immediately appears in the console (stack trace below). However, below the "Start LoRA Training" button, text shows that the training is complete and has been saved with no errors.

The training does not work and the LoRA that is saved does nothing.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Use the model TheBloke_Llama-2-70B-chat-GPTQ and model loader Transformers.
Load the model, choose the raw text file which you want to train on, and start the LoRA training.

The LoRA will begin training, but will stop after about 2 minutes. The console shows the error (stack trace below.) However, the following text appears below the "Start LoRA Training" button:

_Done! LoRA saved to loras/filename. Before testing your new LoRA, make sure to first reload the model, as it is currently dirty from training._

### Logs

```shell
Training 'llama' model using (q, v) projections
Trainable params: 65,536,000 (0.7159 %), All params: 9,154,240,512 (Model: 9,088,704,512)
2023-09-25 11:00:42 INFO:Log file 'train_dataset_sample.json' created in the 'logs' directory.
wandb: Tracking run with wandb version 0.15.11
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
Exception in thread Thread-3 (threaded_run):
Traceback (most recent call last):
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/llama2/text-generation-webui/modules/training.py", line 656, in threaded_run
    trainer.train()
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/trainer.py", line 1553, in train
    return inner_training_loop(
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/trainer.py", line 1835, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/trainer.py", line 2679, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/trainer.py", line 2704, in compute_loss
    outputs = model(**inputs)
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/accelerate/utils/operations.py", line 636, in forward
    return model_forward(*args, **kwargs)
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/accelerate/utils/operations.py", line 624, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/peft/peft_model.py", line 918, in forward
    return self.base_model(
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 94, in forward
    return self.model.forward(*args, **kwargs)
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/auto_gptq/modeling/_base.py", line 438, in forward
    return self.model(*args, **kwargs)
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 820, in forward
    outputs = self.model(
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 708, in forward
    layer_outputs = decoder_layer(
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 424, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 321, in forward
    query_states = self.q_proj(hidden_states)
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/peft/tuners/lora.py", line 902, in forward
    result = F.linear(x, transpose(self.weight, self.fan_in_fan_out), bias=self.bias)
RuntimeError: self and mat2 must have the same dtype
2023-09-25 11:00:45 INFO:Training complete, saving...
Traceback (most recent call last):
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2106, in run_sync_in_worker_thread
    return await future
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 833, in run
    result = context.run(func, *args)
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "/home/user/llama2/text-generation-webui/modules/training.py", line 694, in do_train
    lora_model.save_pretrained(lora_file_path)
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/peft/peft_model.py", line 162, in save_pretrained
    self.create_or_update_model_card(save_directory)
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/peft/peft_model.py", line 637, in create_or_update_model_card
    quantization_config = self.config.quantization_config.to_dict()
AttributeError: 'dict' object has no attribute 'to_dict'
2023-09-25 11:01:05 INFO:Loading TheBloke_Llama-2-70B-chat-GPTQ...
2023-09-25 11:01:21 INFO:Loaded the model in 16.30 seconds.

2023-09-25 11:01:38 INFO:Loading raw text file dataset...
2023-09-25 11:01:40 INFO:Getting model ready...
2023-09-25 11:01:40 INFO:Preparing for training...
2023-09-25 11:01:40 INFO:Creating LoRA model...
2023-09-25 11:01:40 INFO:Starting training...
Training 'llama' model using (q, v) projections
Trainable params: 65,536,000 (11.0863 %), All params: 591,142,912 (Model: 525,606,912)
2023-09-25 11:01:40 INFO:Log file 'train_dataset_sample.json' created in the 'logs' directory.
Exception in thread Thread-6 (threaded_run):
Traceback (most recent call last):
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/llama2/text-generation-webui/modules/training.py", line 656, in threaded_run
    trainer.train()
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/trainer.py", line 1553, in train
    return inner_training_loop(
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/trainer.py", line 1914, in _inner_training_loop
    self.optimizer.step()
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/accelerate/optimizer.py", line 132, in step
    self.scaler.step(self.optimizer, closure)
  File "/home/user/llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 372, in step
    assert len(optimizer_state["found_inf_per_device"]) > 0, "No inf checks were recorded for this optimizer."
AssertionError: No inf checks were recorded for this optimizer.
2023-09-25 11:03:24 INFO:Training complete, saving...
2023-09-25 11:03:24 INFO:Training complete!
```

### System Info

```shell
Operating system: Linux
GPU brand: Nvidia
GPU model: dual 3090s
```

**Comment by FartyPants** [comment]
I would check with PEFT/Transformers if you can actually split VRAM for training. IDK. I can't test/nor debug such scenario, as I only have 1 stinky GPU - so it needs to be done by someone who has hardware.

**Comment by Xabab** [comment]
Quantization config seems to have a valid config, just being a dict already
If you want a hotfix to train LoRA here and now, open your `peft_model.py` and exchange
```
quantization_config = self.config.quantization_config.to_dict()
```
for
```
if not isinstance(self.config.quantization_config, dict):
  quantization_config = self.config.quantization_config.to_dict()
else:
  quantization_config = self.config.quantization_config
```
