### ISSUE TITLE
[Bug] Error after migration to new one-click-install scripts.

### ISSUE THREAD

**Issue by valden80** [oobabooga/text-generation-webui#4078]
### Describe the bug

My original path to web ui: /home/AI/Oobaboga/text-generation-webui
After I done exactly what is migration instruction says, with only one addition - I also renamed folder "text-generation-webui" to "Oobabooga", as I prefer this name in my folder structure. Final path is /home/AI/Oobaboga
Then "start_linux.sh" don't strat UI but give this error:
```
Traceback (most recent call last):
  File "/home/AI/Oobabooga/one_click.py", line 265, in <module>
    if not is_installed():
  File "/home/AI/Oobabooga/one_click.py", line 43, in is_installed
    if site_packages_path:
UnboundLocalError: local variable 'site_packages_path' referenced before assignment
```

When I try to repeat migration with remaining folder name "text-generation-webui" I got this error on update_linux.sh step:
```
./update_linux.sh: string 22: /home/AI/text-generation-webui/installer_files/conda/etc/profile.d/conda.sh: No such file or directory

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

   $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


Conda is not installed. Exiting...

Done!
```

This is look reasonable as previous install of conda env was in ...Oobaboga/installer_files/... so it can't find it in the /home/AI/text-generation-webui/

Do I really need to do full reinstall now? This will take long time, and I'm not sure that it's will work, and don't throw error from first try again (one from one_click.py - it's seem's to not related to the folder name)...

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Described above.

### Screenshot

none, it's text log.

### Logs

```shell
Above, in description.
```

### System Info

```shell
Manjaro Linux current, Nvidia RTX3060 12Gb.
```

**Comment by Psynbiotik** [comment]
Submitted Pull Request: https://github.com/oobabooga/text-generation-webui/pull/4118
