### ISSUE TITLE
Qwen 14b chat gives error

### ISSUE THREAD

**Issue by CyberTimon** [oobabooga/text-generation-webui#4083]
### Describe the bug

Hello

When I try to load Qwen 14b chat 4bit (https://huggingface.co/Qwen/Qwen-14B-Chat-Int4) it fails with this error when I try to generate some text. Any ideas?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Download Qwen 14b (https://huggingface.co/Qwen/Qwen-14B-Chat-Int4) and load it with auto_gptq. When clicking "generate" it throws this error

### Logs

```shell
Traceback (most recent call last):
  File "/home/cybertimon/Repositories/text-generation-webui/modules/callbacks.py", line 56, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "/home/cybertimon/Repositories/text-generation-webui/modules/text_generation.py", line 347, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/cybertimon/.local/lib/python3.10/site-packages/auto_gptq/modeling/_base.py", line 443, in generate
    return self.model.generate(**kwargs)
  File "/home/cybertimon/.cache/huggingface/modules/transformers_modules/Qwen-Chat-14B/modeling_qwen.py", line 1319, in generate
    return super().generate(
  File "/home/cybertimon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/cybertimon/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 1443, in generate
    eos_token_id = eos_token_id[0]
IndexError: list index out of range
Output generated in 0.24 seconds (0.00 tokens/s, 0 tokens, context 58, seed 647093552)
```
```


### System Info

```shell
Ubuntu 22.04
RTX 3090 24GB
32GB DDR4 
I5 13600KF
```

**Comment by happyme531** [comment]
Try to load with transformers and trust_remote_code.
