### ISSUE TITLE
[Bug] Installation on linux don't work.

### ISSUE THREAD

**Issue by valden80** [oobabooga/text-generation-webui#4084]
### Describe the bug

Related to the https://github.com/oobabooga/text-generation-webui/issues/4078

I tried completely new install, but got error. Installation don't process.

```
Traceback (most recent call last):
  File "/home/AI/text-generation-webui/one_click.py", line 304, in <module>
    if not is_installed():
  File "/home/AI/text-generation-webui/one_click.py", line 75, in is_installed
    if site_packages_path:
UnboundLocalError: local variable 'site_packages_path' referenced before assignment
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

git clone ...
start_linux.sh

### Screenshot

text logs.

### Logs

```shell
git clone --depth=1 https://github.com/oobabooga/text-generation-webui.git
Cloning into "text-generation-webui"...
remote: Enumerating objects: 352, done.
remote: Counting objects: 100% (352/352), done.
remote: Compressing objects: 100% (321/321), done.
remote: Total 352 (delta 33), reused 201 (delta 14), pack-reused 0
Retrieving objects: 100% (352/352), 7.59 MiB | 3.15 MiB/s, done.
Change detection: 100% (33/33), ready.
[slant@orra AI]$ 
[slant@orra text-generation-webui]$ ./start_linux.sh
Downloading Miniconda from https://repo.anaconda.com/miniconda/Miniconda3-py310_23.3.1-0-Linux-x86_64.sh to /home/slant/AI/text-generation-webui/installer_files/miniconda_installer.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 69.7M  100 69.7M    0     0   9.8M      0  0:00:07  0:00:07 --:--:-- 10.0M
PREFIX=/home/slant/AI/text-generation-webui/installer_files/conda
Unpacking payload ...
                                                                                                                                                        
Installing base environment...


Downloading and Extracting Packages


Downloading and Extracting Packages

Preparing transaction: done
Executing transaction: done
installation finished.
Miniconda version:
conda 23.3.1
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.3.1
  latest version: 23.7.4

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.7.4



## Package Plan ##

  environment location: /home/slant/AI/text-generation-webui/installer_files/env

  added / updated specs:
    - python=3.10


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2023.08.22 |       h06a4308_0         123 KB
    libffi-3.4.4               |       h6a678d5_0         142 KB
    openssl-3.0.11             |       h7f8727e_2         5.2 MB
    pip-23.2.1                 |  py310h06a4308_0         2.6 MB
    python-3.10.13             |       h955ad1f_0        26.8 MB
    setuptools-68.0.0          |  py310h06a4308_0         936 KB
    sqlite-3.41.2              |       h5eee18b_0         1.2 MB
    xz-5.4.2                   |       h5eee18b_0         642 KB
    ------------------------------------------------------------
                                           Total:        37.6 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main 
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-5.1-1_gnu 
  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h7b6447c_0 
  ca-certificates    pkgs/main/linux-64::ca-certificates-2023.08.22-h06a4308_0 
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.38-h1181459_1 
  libffi             pkgs/main/linux-64::libffi-3.4.4-h6a678d5_0 
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-11.2.0-h1234567_1 
  libgomp            pkgs/main/linux-64::libgomp-11.2.0-h1234567_1 
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-11.2.0-h1234567_1 
  libuuid            pkgs/main/linux-64::libuuid-1.41.5-h5eee18b_0 
  ncurses            pkgs/main/linux-64::ncurses-6.4-h6a678d5_0 
  openssl            pkgs/main/linux-64::openssl-3.0.11-h7f8727e_2 
  pip                pkgs/main/linux-64::pip-23.2.1-py310h06a4308_0 
  python             pkgs/main/linux-64::python-3.10.13-h955ad1f_0 
  readline           pkgs/main/linux-64::readline-8.2-h5eee18b_0 
  setuptools         pkgs/main/linux-64::setuptools-68.0.0-py310h06a4308_0 
  sqlite             pkgs/main/linux-64::sqlite-3.41.2-h5eee18b_0 
  tk                 pkgs/main/linux-64::tk-8.6.12-h1ccaba5_0 
  tzdata             pkgs/main/noarch::tzdata-2023c-h04d1e81_0 
  wheel              pkgs/main/linux-64::wheel-0.38.4-py310h06a4308_0 
  xz                 pkgs/main/linux-64::xz-5.4.2-h5eee18b_0 
  zlib               pkgs/main/linux-64::zlib-1.2.13-h5eee18b_0 



Downloading and Extracting Packages
                                                                                                                                                        
Preparing transaction: done                                                                                                                             
Verifying transaction: done                                                                                                                             
Executing transaction: done                                                                                                                             
#                                                                                                                                                       
# To activate this environment, use                                                                                                                     
#                                                                                                                                                       
#     $ conda activate /home/slant/AI/text-generation-webui/installer_files/env                                                                         
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Traceback (most recent call last):
  File "/home/AI/text-generation-webui/one_click.py", line 304, in <module>
    if not is_installed():
  File "/home/AI/text-generation-webui/one_click.py", line 75, in is_installed
    if site_packages_path:
UnboundLocalError: local variable 'site_packages_path' referenced before assignment
```

### System Info

```shell
Manjaro Linux, current. Nvidia RTX 3060 12GB.
```

**Comment by sinful-developer** [comment]
Do you happen to be using a symbolic link?

I got the same error because there was a symbolic link in my path.
In my case the path /home/sl/Projects is a symbolic link for /mnt/Projects. 

A workaround for this is to just create a start.sh script in the text-generation-webui folder that changes the directory to the correct location.
So in my case the script would look like this:
```sh
#!/bin/bash
cd /mnt/Projects/text-generation-webui
./start_linux.sh
```
Then you just run the ./start.sh script (remember to chmod +x start.sh).

The same can be done for the update_linux.sh script.

**Comment by valden80** [comment]
@Panchovix Thanks, this is helps, install is starting now.

@sinful-developer My report above about another case, and another error. 
But your guessing is also right - I'm using symlink. And it's cause another problem, as you tell here. So, your solution also help me to avoid another problem, thank you too.
