### ISSUE TITLE
Falcon 7B-Instruct does not load correctly

### ISSUE THREAD

**Issue by fabianslife** [oobabooga/text-generation-webui#4085]
### Describe the bug

When loading in falcon 7B instruct from https://huggingface.co/tiiuae/falcon-7b-instruct I am getting the error:

```
2023-09-26 11:33:45 INFO:Loading tiiuae_falcon-7b-instruct...
Loading checkpoint shards: 100%|██████████████████| 2/2 [00:15<00:00,  7.56s/it]
2023-09-26 11:34:31 INFO:Loaded the model in 46.05 seconds.

2023-09-26 11:34:31 ERROR:Failed to load the model.
Traceback (most recent call last):

File "/Users/USER/Desktop/LLM/text-generation-webui-main/modules/ui_model_menu.py", line 203, in load_model_wrapper
    settings = get_model_metadata(selected_model)
  File "/Users/USER/Desktop/LLM/text-generation-webui-main/modules/models_settings.py", line 31, in get_model_metadata
    for k in settings[pat]:
TypeError: 'NoneType' object is not iterable
```

I followed the installation procedure, however I cannot seem to find a solution for the issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Pasted the URL: `https://huggingface.co/tiiuae/falcon-7b-instruct` into the Tab `Models`. After Downloading everything I pressed `Refresh` selected the model and pressed `load`.

### Screenshot

<img width="740" alt="Bildschirm­foto 2023-09-26 um 11 45 02" src="https://github.com/oobabooga/text-generation-webui/assets/49265757/2e84a092-86b3-4e35-9022-bbff193eb23d">

### Logs

```shell
2023-09-26 11:33:45 INFO:Loading tiiuae_falcon-7b-instruct...
Loading checkpoint shards: 100%|██████████████████| 2/2 [00:15<00:00,  7.56s/it]
2023-09-26 11:34:31 INFO:Loaded the model in 46.05 seconds.

2023-09-26 11:34:31 ERROR:Failed to load the model.
Traceback (most recent call last):

File "/Users/USER/Desktop/LLM/text-generation-webui-main/modules/ui_model_menu.py", line 203, in load_model_wrapper
    settings = get_model_metadata(selected_model)
  File "/Users/USER/Desktop/LLM/text-generation-webui-main/modules/models_settings.py", line 31, in get_model_metadata
    for k in settings[pat]:
TypeError: 'NoneType' object is not iterable
```

### System Info

```shell
Model: MacBook Pro 2021
CPU: Apple M1 Pro
Ram: 32 GB
```

**Comment by dnalbach** [comment]
I have the same issue and investigated it with the help of ChatGPT-4 (irony). I was able to fix it by changing the `for` block in the model_settings.py file line 29 from:
```
   for pat in settings:
        if re.match(pat.lower(), model.lower()):
            for k in settings[pat]:
                model_settings[k] = settings[pat][k]
```
to this:
```
    for pat in settings:
        if re.match(pat.lower(), model.lower()):
            print(f'@@@ settings[pat]:\n {settings[pat]}')
            if settings[pat] is not None:
                for k in settings[pat]:
                    model_settings[k] = settings[pat][k]
            else:
                print(f"Warning: No settings found for pattern {pat} in model config")
```
I printed `settings[pat]` to stdout while starting up before making the above change and found that one of the loops has no data:
```
@@@ settings[pat]:
 {'wbits': 'None', 'model_type': 'None', 'groupsize': 'None', 'pre_layer': 0, 'skip_special_tokens': True, 'custom_stopping_strings': '', 'truncation_length': 2048, 'n_ctx': 2048, 'rope_freq_base': 0, 'compress_pos_emb': 1}
@@@ settings[pat]:
 {'model_type': 'falcon'}
@@@ settings[pat]:
 None
 ```
 I don't know anything about where the shared.model_config data comes from but it seems like there is a bad loader for falcon that is potentially grabbing an extra reference it should not that is empty, which then breaks the blind reference in the loop.
