### ISSUE TITLE
ModuleNotFoundError: No module named 'gradio'

### ISSUE THREAD

**Issue by one-pip** [oobabooga/text-generation-webui#4101]
### Describe the bug

Traceback (most recent call last):
  File "D:\NEW_OOBA\text-generation-webui\server.py", line 13, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Traceback (most recent call last):
  File "D:\NEW_OOBA\text-generation-webui\server.py", line 13, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

### Logs

```shell
Traceback (most recent call last):
  File "D:\NEW_OOBA\text-generation-webui\server.py", line 13, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
```

### System Info

```shell
WIN11, NIDIA 3060,
```

**Comment by BrianDorado** [comment]
Same Issue, WIN10, 1080

**Comment by jurandfantom** [comment]
Decided to follow instruction https://github.com/oobabooga/text-generation-webui/wiki/Migrating-an-old-one%E2%80%90click-install   as i saw information and now I stuck with that error. I will try roll back to my "old one‐click install" that surprisingly NOT
"were much more likely to break after a simple update."

Migration and fresh install - both produce same error

**Comment by Kwisss** [comment]
same here, seems to be related to github permissions

**Comment by estebanavv** [comment]
Same issue in MacOS Monterey intel.
```
➜  text-generation-webui git:(main) ./start_macos.sh 


*******************************************************************
* WARNING: You haven't downloaded any model yet.
* Once the web UI launches, head over to the "Model" tab and download one.
*******************************************************************


Traceback (most recent call last):
  File "/Users/esteban/localDocs/text-generation-webui/server.py", line 13, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
```

**Comment by stobbsc** [comment]
Same issue on iMac Intel, being trying to solve this for 25 hrs solid now :-(

**Comment by lityrdef** [comment]
Gradio does not exist in the conda Lib folder. ( methink the problem occurs because the installation was interruptted. 


So try to pip install in such folder. 



C:\text-generation-webui-main\installer_files\conda\pkgs\python-3.10.13-he1021f5_0\Lib

**Comment by leonidaster** [comment]
> Gradio does not exist in the conda Lib folder. ( methink the problem occurs because the installation was interruptted.
> 
> So try to pip install in such folder.
> 
> C:\text-generation-webui-main\installer_files\con
![Screenshot_4](https://github.com/oobabooga/text-generation-webui/assets/42657765/e8a8c2f7-2f19-4e86-b892-bb19d487c7d0)
da\pkgs\python-3.10.13-he1021f5_0\Lib

I dont know how to code, or python so sorry if is a dumb question, how install gradio in that folder? since i dont have it please help

**Comment by Impre-visible** [comment]
Same issue on ubuntu 22.04

**Comment by DiwanshuA** [comment]
even pip install gradio doesnt work... however pip list shows it installed

gradio                    3.47.1

**Comment by dewijones92** [comment]
same here 

```
 ./start_linux.sh --extensions openai --listen --loader llama.cpp --model mistral-7b-instruct
Traceback (most recent call last):
  File "/home/dewi/code/text-generation-webui/server.py", line 14, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
```

**Comment by Impre-visible** [comment]
I found a way to patch that
i added this line "pip install -r requirements.txt" before the one_click.py call, on the start_linux.sh, you can try with start_windows hope it will help

**Comment by vmatekole** [comment]
Same bug for me macos 13.6 and gradio is installed in the virtualenv

**Comment by gzjaychen** [comment]
same issue.
Apple M1 Pro
MacOS 13.6
node v20.5.0
Python 3.10.9

**Comment by Provokingface** [comment]
hmm try "gradio server.py" instead of python server.py I guess?
