### ISSUE TITLE
Support for Mistral models

### ISSUE THREAD

**Issue by kalomaze** [oobabooga/text-generation-webui#4111]
A new set of 7b foundational models that claim to beat all 13b Llama 2 models in benchmarks.

https://huggingface.co/mistralai/Mistral-7B-v0.1
https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1

I am unsure if anything special with the tokenizer or with how the context extension is designed make this a unique challenge, as this is not a typical Llama 2 train.

**Comment by SrVill** [comment]
And add the mistral instruction-template please don't forget

**Comment by rahimnathwani** [comment]
The requirements seem to be:

- <s> at the beginning of the conversation, but not later.
- [INST] before the user message
- [/INST] before the bot message
- Bot ends each message with </s>

I'm using Mistral right now with the settings in the attached screenshot. I put the <s> part in the 'command for chat-instruct mode' box.

![image](https://github.com/oobabooga/text-generation-webui/assets/891558/984b6a55-6e72-4ba3-b2aa-b26d6b826715)

I'm not sure how to handle the </s> part, but it doesn't show up as part of the bot's responses, at least in chat-instruct mode with the cai-chat theme.

**Comment by ChristianCCastro** [comment]
every day or you’re just getting started, we’ll provide you with the skills
your organization needs to work smarter.
GitHub Actions Training

This training will enable your teams to start leveraging GitHub Actions in
their own projects across a multitude of use cases.
Learn more  <https://github.com/services/actions-training>
GitHub Admin Training (GitHub Enterprise Cloud)

Prepare your GitHub Enterprise Cloud Administrators to maintain a healthy
GitHub environment that supports the needs of your development team.
Learn more
<https://github.com/services/admin-training-github-enterprise-cloud>
GitHub Admin Training (GitHub Enterprise Server)

Prepare your GitHub Enterprise Server Administrators to maintain a healthy,
scalable GitHub environment that supports the needs of your development
team.
Learn more
<https://github.com/services/admin-training-github-enterprise-server>
GitHub API Training

GitHub’s extensive API allows you to extend the platform to accommodate
most modern workflows and easily get the data you need.
Learn more  <https://github.com/services/api-training>
GitHub Advanced Security - Getting Started

Supports you in "Getting Started" with GitHub Advanced Security (GHAS) and
helps accelerate adoption in the critical first few weeks of deployment.
Learn more  <https://github.com/services/bundle-ghas-getting-started>
CodeQL Query Customizations

Commision GitHub to customize the existing CodeQL queries to provide better
results for your organization.
Learn more  <https://github.com/services/codeql-query-customizations>
CodeQL Query Development

Commision GitHub to develop CodeQL queries based on your unique business
needs.
Learn more  <https://github.com/services/codeql-query-development>
CodeQL Query Writing Tailored Workshop

This engagement creates a tailored 2 hour training course for using CodeQL
to find a security vulnerbility or pattern of your choice.
Learn more
<https://github.com/services/codeql-query-writing-tailored-workshop>
CodeQL Query Writing Training

Learn how to write CodeQL to find new security vulnerabilities or customize
the existing rules through our extensive catalog of 2 hour training courses.
Learn more  <https://github.com/services/codeql-query-writing-training>
GitHub Copilot for Business Fundamentals Training

GitHub Copilot is the world’s first at-scale AI developer tool. Sitting
within the editor as a simple extension, GitHub Copilot draws context from
a developer’s code to suggest new lines, entire functions, tests, and even
complex algorithms.
Learn more
<https://github.com/services/copilot-for-business-fundamentals-training>
GitHub Advanced Security - Developer Training

Allows you to have a "developer-first" approach to Application Security,
recognizing that developers have a critical role to play in securing your
applications.
Learn more  <https://github.com/services/ghas-developer-training>
GitHub Advanced Security - Pilot Team Implementation

In this engagement we will work with a pilot or lighthouse team to help
them enable GitHub Advanced Security for one or more key repositories.
Learn more  <https://github.com/services/ghas-pilot-team-implementation>
GitHub Advanced Security - Rollout and Deployment Training

Provides support during the planning phases by providing best practices,
recommended rollout strategies and identifying common pitfalls and issues.
Learn more  <https://github.com/services/ghas-rollout-deployment-training>
GitHub Advanced Security - Security Advisory Services

Identify your organization’s top priorities for improving your Secure
Software Development Lifecycle with GitHub Advanced Security.
Learn more  <https://github.com/services/ghas-security-advisory-services>
GitHub Advanced Security - Results Review

Allows you to have a “developer-first” approach to Application Security,
recognizing that developers have a critical role to play in securing your
applications.
Learn more  <https://github.com/services/ghas-security-results-review>
GitHub Advanced Security - Security Team Training

Supports those who are responsible for reviewing, monitoring and driving
remediation of security results across an enterprise.
Learn more  <https://github.com/services/ghas-security-team-training>
GitHub for Developers Training

Give your developers confidence with Git and GitHub with hands-on,
practical training from GitHub Expert Services.
Learn more  <https://github.com/services/github-for-developers-training>
GitHub for Non-Developers

Opening GitHub to a broad audience in your organization, gives your
developers access to the expertise and diverse ways of thinking that
represent your entire user population.
Learn more  <https://github.com/services/github-for-non-developers-training>
Implementation (GitHub Enterprise Cloud)

Equip your team with the knowledge they need to configure and manage your
GitHub Enterprise Cloud account.
Learn more
<https://github.com/services/implementation-github-enterprise-cloud>
Implementation (GitHub Enterprise Server)

Equip your team with the knowledge they need to configure and manage your
GitHub Enterprise Server account.
Learn more
<https://github.com/services/implementation-github-enterprise-server>
Migrations to GitHub Enterprise (Standard)

Ensure your Version Control System (VCS) data is migrated to your GitHub
Enterprise platform account accurately and efficiently.
Learn more  <https://github.com/services/migrations>
Migrations to GitHub Enterprise (GitHub Enterprise Cloud to GitHub
Enterprise Cloud EMU)

Ensure your GitHub Enterprise Cloud data is migrated to your GitHub
Enterprise Cloud plus Enterprise Managed Users (EMU) platform account
accurately and efficiently.
Learn more  <https://github.com/services/migrations-emu>
GitHub Technical Advisory Services

Identify your organization's top priorities for improving software delivery
and enabling a digital transformation.
Learn more  <https://github.com/services/technical-advisory-services>
Workflow Consultation

Equip your team with the knowledge they need to evaluate, implement,
document, and design a workflow solution optimized for your branching and
release management strategy.

**Comment by travco** [comment]
This should work as a YAML for Mistral-Instruct. Also Mistral appears to work out of the box if you use a [GGUF file](https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF) and llama.cpp as a loader.
```yaml
user: '[INST] '
bot: ' [/INST]'
turn_template: <s><|user|><|user-message|><|bot|>\n<|bot-message|></s>\n
```

**Comment by fat-tire** [comment]
Just to pipe in here-- TheBloke/Mistral-7B-Instruct-v0.1-AWQ seems to work alright with ooba.  There is some occasional discontinuity between the question I asked and the answer.  Sometimes it seems to answer questions from earlier and sometimes it gets answers factually wrong...  but it works.

**Comment by DeSinc** [comment]
> Just to pipe in here-- TheBloke/Mistral-7B-Instruct-v0.1-AWQ seems to work alright with ooba. There is some occasional discontinuity between the question I asked and the answer. Sometimes it seems to answer questions from earlier and sometimes it gets answers factually wrong... but it works.

How did you get it to work? I tried TheBloke/dolphin-2.0-mistral-7B-AWQ and it gives the explicit message that it's not supported:
> TypeError: mistral isn’t supported yet.
Is the version you linked different then somehow?

**Comment by fat-tire** [comment]
Apply PR #3999 and it should work.  I use `n_batch` set to 1 and check `no_inject_fused_attention` to avoid memory errors.

**Comment by lijunle** [comment]
TheBloke just released the GPTQ version. 

https://huggingface.co/TheBloke/Mistralic-7B-1-GPTQ

**Comment by anammari** [comment]
None of the GPTQ models has loaded successfully with me. 

I've tried `mistral_7b_instruct_v0.1_gptq` and `mistralic_7b_1_gptq` and tried all available loaders. 

I've then applied PR #3999 and downloaded the `mistral_7b_instruct_v0.1_awq` model which has loaded successfully using AutoAWQ loader. However, the LLM stays unresponsive in both chat and chat-instruct modes. 

Moreover, the conda console also throws an error after submitting the prompt in chat:

```
Traceback (most recent call last):
  File "C:\Users\Ahmad\github\text-generation-webui\modules\callbacks.py", line 56, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "C:\Users\Ahmad\github\text-generation-webui\modules\text_generation.py", line 347, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Users\Ahmad\.conda\envs\textgen\lib\site-packages\awq\models\base.py", line 36, in generate
    return self.model.generate(*args, **kwargs)
  File "C:\Users\Ahmad\.conda\envs\textgen\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Ahmad\.conda\envs\textgen\lib\site-packages\transformers\generation\utils.py", line 1652, in generate
    return self.sample(
  File "C:\Users\Ahmad\.conda\envs\textgen\lib\site-packages\transformers\generation\utils.py", line 2770, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

**Comment by Pozaza** [comment]
I got it to work by modifying 2 files in packages:
- venv\Lib\site-packages\auto_gptq\modeling\_const.py
- venv\Lib\site-packages\auto_gptq\modeling\auto.py

modified files: https://gist.github.com/Pozaza/c8335bbcbbd4a73dd3bec1a9644b6865

**Comment by Thireus** [comment]
Mistral GPTQ models give me the following error when loaded with exllamav2:

```
RuntimeError: q_weight and gptq_qzeros have incompatible shapes
```

**Comment by InfernalWraith** [comment]
[TheBloke/Mistral-7B-OpenOrca-GPTQ](https://huggingface.co/TheBloke/Mistral-7B-OpenOrca-GPTQ) worked for me with the `ExLlamav2_HF` model loader out of the box. It also worked for the `Transformer` model loader, though I got the following error so I had to tick the `disable_exllama` option to get it to work
```
ValueError: Found modules on cpu/disk. Using Exllama backend requires all the modules to be on GPU.
You can deactivate exllama backend by setting `disable_exllama=True` in the quantization config object
```

Using an RTX 3070, with `ExLlamav2_HF` I get about 11.5 tokens/s, whereas with `Transformer` I get about 4.5.

**Comment by yquemener** [comment]
For those who want to try @InfernalWraith solution: if you don't have disable_exllama as an option, "auto-devices" do the trick as well

**Comment by controldev** [comment]
> Mistral GPTQ models give me the following error when loaded with exllamav2:
> 
> ```
> RuntimeError: q_weight and gptq_qzeros have incompatible shapes
> ```
> 
> Anyone facing the same issue?

This is still a problem.

**Comment by oliverban** [comment]
I'm getting this as well? :(

**Comment by bryankruman** [comment]
I'm also getting the same problem as many users above...
`RuntimeError: q_weight and gptq_qzeros have incompatible shapes`

**Comment by Ragnarok700** [comment]
Also unable to load with error:
`RuntimeError: q_weight and gptq_qzeros have incompatible shapes`

**Comment by ahmedkhlief** [comment]
also have same issue
