### ISSUE TITLE
Assistance Needed with Running a Text Generation Model Oobabooga and flowise - OPENAI API EXTENSION -on Jetson AGX Orin

### ISSUE THREAD

**Issue by MrBrabus75** [oobabooga/text-generation-webui#4116]
Hello,

I am working on a project for my studies, utilizing a Jetson AGX Xavier with 64GB memory, equipped with an aarch64 architecture, and running on Ubuntu 20.04 (5.10.120-tegra).

I have successfully installed and configured JetPack 5.1.2 along with the Docker container jetson-containers (https://github.com/dusty-nv/jetson-containers).

Through this Docker container, I am using oobabooga to execute my LLM using the following command:
`user@ubuntu:~/Desktop/workspace/ia/jetson-containers$ ./run.sh $(./autotag text-generation-webui) /bin/bash -c "cd /opt/text-generation-webui && python3 server.py --model-dir=/data/models/text-generation-webui --model=lmsys_vicuna-7b-v1.5-16k --loader=transformers --api --bf16 --listen --chat --verbose --rope_freq_base 10000 --max_seq_len 16000 --n_ctx 16000 --n_batch 16100 --extensions openai"`

I need the openai extension as I am planning to link it to Flowise on another workstation via this extension.

However, I am encountering a problem. When I execute my command, here's the error I get:
`Namespace(disable=[''], output='/tmp/autotag', packages=['text-generation-webui'], prefer=['local', 'registry', 'build'], quiet=False, user='dustynv', verbose=False)
-- L4T_VERSION=35.4.1 JETPACK_VERSION=5.1.2 CUDA_VERSION=11.4.315
-- Finding compatible container image for ['text-generation-webui']
[sudo] password for user:
dustynv/text-generation-webui:r35.3.1
localuser:root being added to access control list
+ sudo docker run --runtime nvidia -it --rm --network host --volume /tmp/argus_socket:/tmp/argus_socket --volume /etc/enctune.conf:/etc/enctune.conf --volume /etc/nv_tegra_release:/etc/nv_tegra_release --volume /tmp/nv_jetson_model:/tmp/nv_jetson_model --volume /home/user/Desktop/workspace/ia/jetson-containers/data:/data --device /dev/snd --device /dev/bus/usb -e DISPLAY=:1 -v /tmp/.X11-unix/:/tmp/.X11-unix -v /tmp/.docker.xauth:/tmp/.docker.xauth -e XAUTHORITY=/tmp/.docker.xauth dustynv/text-generation-webui:r35.3.1 /bin/bash -c 'cd /opt/text-generation-webui && python3 server.py --model-dir=/data/models/text-generation-webui --model=lmsys_vicuna-7b-v1.5-16k --loader=transformers --api --bf16 --listen --chat --verbose --rope_freq_base 10000 --max_seq_len 16000 --n_ctx 16000 --n_batch 16100 --extensions openai'
2023-09-30 08:50:06 WARNING:The --chat flag has been deprecated and will be removed soon. Please remove that flag.
bin /usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda114.so
2023-09-30 08:50:09 INFO:Loading settings from settings.json...
2023-09-30 08:50:09 INFO:Loading lmsys_vicuna-7b-v1.5-16k...
Loading checkpoint shards: 100%|███████████████████████████████████████████| 2/2 [00:11<00:00, 5.90s/it]
/usr/local/lib/python3.8/dist-packages/transformers/generation/configuration_utils.py:362: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
warnings.warn(
/usr/local/lib/python3.8/dist-packages/transformers/generation/configuration_utils.py:367: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
warnings.warn(
2023-09-30 08:50:30 INFO:Loaded the model in 21.32 seconds.

2023-09-30 08:50:30 INFO:Loading the extension "openai"...
2023-09-30 08:50:30 ERROR:Failed to load the extension "openai".
Traceback (most recent call last):
File "/opt/text-generation-webui/modules/extensions.py", line 36, in load_extensions
exec(f"import extensions.{name}.script")
File "<string>", line 1, in <module>
File "/opt/text-generation-webui/extensions/openai/script.py", line 7, in <module>
import extensions.openai.completions as OAIcompletions
File "/opt/text-generation-webui/extensions/openai/completions.py", line 3, in <module>
import tiktoken
ModuleNotFoundError: No module named 'tiktoken'`

After installing the requirements (which I have to do every time I restart Docker, quite annoying...):
`/opt/text-generation-webui/extensions/openai# pip install -r requirements.txt`

I encounter a new error:
`2023-09-30 09:03:31 INFO:Loading the extension "openai"...
2023-09-30 09:03:31 ERROR:Failed to load the extension "openai".
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sklearn/__check_build/__init__.py", line 45, in <module>
    from ._check_build import check_build  # noqa
ImportError: /usr/local/lib/python3.8/dist-packages/sklearn/__check_build/../../scikit_learn.libs/libgomp-d22c30c5.so.1.0.0: cannot allocate memory in static TLS block

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/text-generation-webui/modules/extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "/opt/text-generation-webui/extensions/openai/script.py", line 9, in <module>
    import extensions.openai.embeddings as OAIembeddings
  File "/opt/text-generation-webui/extensions/openai/embeddings.py", line 6, in <module>
    from sentence_transformers import SentenceTransformer
  File "/usr/local/lib/python3.8/dist-packages/sentence_transformers/__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "/usr/local/lib/python3.8/dist-packages/sentence_transformers/datasets/__init__.py", line 3, in <module>
    from .ParallelSentencesDataset import ParallelSentencesDataset
  File "/usr/local/lib/python3.8/dist-packages/sentence_transformers/datasets/ParallelSentencesDataset.py", line 4, in <module>
    from .. import SentenceTransformer
  File "/usr/local/lib/python3.8/dist-packages/sentence_transformers/SentenceTransformer.py", line 25, in <module>
    from .evaluation import SentenceEvaluator
  File "/usr/local/lib/python3.8/dist-packages/sentence_transformers/evaluation/__init__.py", line 3, in <module>
    from .BinaryClassificationEvaluator import BinaryClassificationEvaluator
  File "/usr/local/lib/python3.8/dist-packages/sentence_transformers/evaluation/BinaryClassificationEvaluator.py", line 5, in <module>
    from sklearn.metrics.pairwise import paired_cosine_distances, paired_euclidean_distances, paired_manhattan_distances
  File "/usr/local/lib/python3.8/dist-packages/sklearn/__init__.py", line 79, in <module>
    from . import (
  File "/usr/local/lib/python3.8/dist-packages/sklearn/__check_build/__init__.py", line 47, in <module>
    raise_build_error(e)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/__check_build/__init__.py", line 31, in raise_build_error
    raise ImportError("""%s
ImportError: /usr/local/lib/python3.8/dist-packages/sklearn/__check_build/../../scikit_learn.libs/libgomp-d22c30c5.so.1.0.0: cannot allocate memory in static TLS block
___________________________________________________________________________
Contents of /usr/local/lib/python3.8/dist-packages/sklearn/__check_build:
_check_build.cpython-38-aarch64-linux-gnu.so__pycache__               __init__.py
___________________________________________________________________________
It seems that scikit-learn has not been built correctly.

If you have installed scikit-learn from source, please do not forget
to build the package before using it: run `python setup.py install` or
`make` in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.
2023-09-30 09:03:31 INFO:Loading the extension "gallery"...
/usr/local/lib/python3.8/dist-packages/gradio/components/dropdown.py:238: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: None or set allow_custom_value=True.
  warnings.warn(
Running on local URL:  http://0.0.0.0:7861

To create a public link, set `share=True` in `launch()`.`

I have spent several days trying various manipulations and modifications without success.

I attempted to install outside Docker, but with an aarch64 architecture and limited version availability, it's quite complicated.

If anyone has a solution or can provide assistance, that would be fantastic.

Thank you in advance.

Warm regards,

(Sorry for my english)

**Comment by kryptech** [comment]
I'm also getting the error "ModuleNotFoundError: No module named 'tiktoken'", though I'm on Windows 10. Only the 'gallery' and 'openai' extensions are selected, and no other flags (for testing purposes). I've run `update_windows.bat` so I'm up-to-date. The openai extension did work on the version of text-generation-webui from a week or so ago. Here's the console output I get:

```
2023-09-30 07:59:56 INFO:Loading the extension "openai"...
2023-09-30 07:59:57 ERROR:Failed to load the extension "openai".
Traceback (most recent call last):
  File "E:\text-generation-webui\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "E:\text-generation-webui\extensions\openai\script.py", line 7, in <module>
    import extensions.openai.completions as OAIcompletions
  File "E:\text-generation-webui\extensions\openai\completions.py", line 3, in <module>
    import tiktoken
ModuleNotFoundError: No module named 'tiktoken'
```

**Comment by kryptech** [comment]
I was able to fix the tiktoken error by running `pip install -r extensions/openai/requirements.txt` while in the text-generation-webui environment.

**Comment by MrBrabus75** [comment]
Yes, but after having done the pip install as I mentioned, I'm getting this new error:


`2023-09-30 09:03:31 INFO:Loading the extension "openai"...
2023-09-30 09:03:31 ERROR:Failed to load the extension "openai".
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/sklearn/__check_build/init.py", line 45, in
from ._check_build import check_build # noqa
ImportError: /usr/local/lib/python3.8/dist-packages/sklearn/__check_build/../../scikit_learn.libs/libgomp-d22c30c5.so.1.0.0: cannot allocate memory in static TLS block

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/text-generation-webui/modules/extensions.py", line 36, in load_extensions
exec(f"import extensions.{name}.script")
File "", line 1, in
File "/opt/text-generation-webui/extensions/openai/script.py", line 9, in
import extensions.openai.embeddings as OAIembeddings
File "/opt/text-generation-webui/extensions/openai/embeddings.py", line 6, in
from sentence_transformers import SentenceTransformer
File "/usr/local/lib/python3.8/dist-packages/sentence_transformers/init.py", line 3, in
from .datasets import SentencesDataset, ParallelSentencesDataset
File "/usr/local/lib/python3.8/dist-packages/sentence_transformers/datasets/init.py", line 3, in
from .ParallelSentencesDataset import ParallelSentencesDataset
File "/usr/local/lib/python3.8/dist-packages/sentence_transformers/datasets/ParallelSentencesDataset.py", line 4, in
from .. import SentenceTransformer
File "/usr/local/lib/python3.8/dist-packages/sentence_transformers/SentenceTransformer.py", line 25, in
from .evaluation import SentenceEvaluator
File "/usr/local/lib/python3.8/dist-packages/sentence_transformers/evaluation/init.py", line 3, in
from .BinaryClassificationEvaluator import BinaryClassificationEvaluator
File "/usr/local/lib/python3.8/dist-packages/sentence_transformers/evaluation/BinaryClassificationEvaluator.py", line 5, in
from sklearn.metrics.pairwise import paired_cosine_distances, paired_euclidean_distances, paired_manhattan_distances
File "/usr/local/lib/python3.8/dist-packages/sklearn/init.py", line 79, in
from . import (
File "/usr/local/lib/python3.8/dist-packages/sklearn/__check_build/init.py", line 47, in
raise_build_error(e)
File "/usr/local/lib/python3.8/dist-packages/sklearn/__check_build/init.py", line 31, in raise_build_error
raise ImportError("""%s
ImportError: /usr/local/lib/python3.8/dist-packages/sklearn/__check_build/../../scikit_learn.libs/libgomp-d22c30c5.so.1.0.0: cannot allocate memory in static TLS block

Contents of /usr/local/lib/python3.8/dist-packages/sklearn/_check_build:
check_build.cpython-38-aarch64-linux-gnu.so__pycache init.py

It seems that scikit-learn has not been built correctly.

If you have installed scikit-learn from source, please do not forget
to build the package before using it: run python setup.py install or
make in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.
2023-09-30 09:03:31 INFO:Loading the extension "gallery"...
/usr/local/lib/python3.8/dist-packages/gradio/components/dropdown.py:238: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: None or set allow_custom_value=True.
warnings.warn(

Otherwise, does anyone know how to reinstall everything outside of Docker on a Jetson Orin TPU (arm64) running Ubuntu 20.04 AGX with this version of PyTorch?
https://developer.download.nvidia.cn/compute/redist/jp/v511/pytorch/torch-2.0.0+nv23.05-cp38-cp38-linux_aarch64.whl


I really need to solve this problem but i'm really suck on this step...

**Comment by kryptech** [comment]
It sounds like the issue I had was somewhat different than yours, and my environment is very different. Hopefully someone with greater knowledge can help you out.

**Comment by MrBrabus75** [comment]
no problem i hope :p
