### ISSUE TITLE
Update failure and webui breakdown

### ISSUE THREAD

**Issue by SrVill** [oobabooga/text-generation-webui#4123]
### Describe the bug

I try to update webui as little as possible. And now I decided to take a chance. Because every update is a risk of breakage. But it turned out it was reckless.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

run update_windows.bat
then try start_windows.bat

### Screenshot

the update ended with an error that I couldn't calculate because the console shut down
re-launch update_windows.bat
```
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
Command '"E:\text-generation-webui\installer_files\conda\condabin\conda.bat" activate "E:\text-generation-webui\installer_files\env" >nul && git pull --autostash' failed with exit status code '128'.

Exiting now.
Try running the start/update script again.
```

launching start_windows.bat

```
Traceback (most recent call last):
  File "E:\text-generation-webui\server.py", line 30, in <module>
    from modules import (
  File "E:\text-generation-webui\modules\chat.py", line 18, in <module>
    from modules.text_generation import (
  File "E:\text-generation-webui\modules\text_generation.py", line 11, in <module>
    import transformers
ModuleNotFoundError: No module named 'transformers'
```

### Logs

```shell
the update ended with an error that I couldn't calculate because the console shut down
re-launch update_windows.bat

error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
Command '"E:\text-generation-webui\installer_files\conda\condabin\conda.bat" activate "E:\text-generation-webui\installer_files\env" >nul && git pull --autostash' failed with exit status code '128'.

Exiting now.
Try running the start/update script again.
```

launching start_windows.bat

```
Traceback (most recent call last):
  File "E:\text-generation-webui\server.py", line 30, in <module>
    from modules import (
  File "E:\text-generation-webui\modules\chat.py", line 18, in <module>
    from modules.text_generation import (
  File "E:\text-generation-webui\modules\text_generation.py", line 11, in <module>
    import transformers
ModuleNotFoundError: No module named 'transformers'
```
```


### System Info

```shell
windows 10
nvidia 3060
```

**Comment by SrVill** [comment]
When installing again, it was possible to reproduce the error:

```
ERROR: Exception:
Traceback (most recent call last):
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "E:\text-generation-webui\installer_files\env\lib\http\client.py", line 466, in read
    s = self.fp.read(amt)
  File "E:\text-generation-webui\installer_files\env\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "E:\text-generation-webui\installer_files\env\lib\ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "E:\text-generation-webui\installer_files\env\lib\ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 293, in __init__
    super().__init__(
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_internal\operations\prepare.py", line 538, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_internal\operations\prepare.py", line 609, in _prepare_linked_requirement
    local_file = unpack_url(
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_internal\operations\prepare.py", line 166, in unpack_url
    file = get_http_url(
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_internal\operations\prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_internal\network\download.py", line 147, in __call__
    for chunk in chunks:
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 560, in read
    with self._error_catcher():
  File "E:\text-generation-webui\installer_files\env\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='download.pytorch.org', port=443): Read timed out.
Command '"E:\text-generation-webui\installer_files\conda\condabin\conda.bat" activate "E:\text-generation-webui\installer_files\env" >nul && conda install -y -k ninja git && python -m pip install torch==2.0.1+cu117 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117 && python -m pip install py-cpuinfo==9.0.0' failed with exit status code '2'.

Exiting now.
Try running the start/update script again.
```

Thus, at the moment it is not possible to update or reinstall webui.
