### ISSUE TITLE
[Openai API extension] Bug in embedding encode method number of argument

### ISSUE THREAD

**Issue by yhyu13** [oobabooga/text-generation-webui#4146]
### Describe the bug

Since openai api extension has not fixed sentence-transformer version https://github.com/oobabooga/text-generation-webui/blob/main/extensions/openai/requirements.txt, I guess it causes a back-ward compatibility issue on the sentence-transformer "encode" method here

my intalled versions
```
sentence-transformers     2.2.2
sentencepiece             0.1.99
```

And it raises the following error on the encode method

```
OpenAIError TypeError('encode() takes at most 2 arguments (5 given)')
Traceback (most recent call last):
  File "/root/CodeSpace/text-generation-webui/extensions/openai/script.py", line 114, in wrapper
    func(self)
  File "/root/CodeSpace/text-generation-webui/extensions/openai/script.py", line 283, in do_POST
    response = OAIembeddings.embeddings(input, encoding_format)
  File "/root/CodeSpace/text-generation-webui/extensions/openai/embeddings.py", line 63, in embeddings
    embeddings = get_embeddings(input)
  File "/root/CodeSpace/text-generation-webui/extensions/openai/embeddings.py", line 58, in get_embeddings
    return get_embeddings_model().encode(input, convert_to_numpy=True, normalize_embeddings=True, convert_to_tensor=False, device=embeddings_device)
TypeError: encode() takes at most 2 arguments (5 given)
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I am using FastGPT (https://github.com/labring/FastGPT) that call openai embedding api to my local instance of textgen with `--extensions openai` as argument. 

But I believe any call to openai embedding api would raise this exception

### Logs

```shell
OpenAI compatible API ready at: OPENAI_API_BASE=http://127.0.0.1:5051/v1
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
POST /v1/embeddings HTTP/1.1
POST /v1/embeddings HTTP/1.1
Accept: application/json, text/plain, */*
Content-Type: application/json
User-Agent: OpenAI/NodeJS/3.3.0
Authorization: Bearer sk-111111111111111111111111111111111111111111111111
auth: 
Content-Length: 697
Host: host.docker.internal:5051
Connection: keep-alive


{'model': 'text-embedding-ada-002', 'input': [' 第2步,安装 Clang 工具链,并完成配置。 在 http://releases. llvm.org/download.html #8.0.0下载clang+llvm-8.0.0-x86 64-linux-gnu-ubuntu-16.04,并将其放到 openarkcompiler/tools目录,打开 build/config 目录的 BUILDCONFIG. gn,将 GN C COMPILER、GN CXX COMPILER 和 GN AR COMPILER三个变量配置为 Clang 编译器所在路径，代码如下：\n//第2章/BUILDCONFIG. gn\nGN_C_COMPILER = "$ {MAPLE_ROOT}/tools/clang_llvm-8.0.0- x86_64-linux-gnu-ubuntu-16.04/bin/clang"\nGN_CXX_COMPILER = "${MAPLE_ROOT}/tools/clang_llvm-8.0.0 - x86_64-linux-gnu-ubuntu-16.04/bin/clang++"\nGN_AR_COMPILER = "${MAPLE_ROOT}/tools/clang_llvm-8.']}
\Try embedding model: all-MiniLM-L6-v2 on cpu
Accept: application/json, text/plain, */*
Content-Type: application/json
User-Agent: OpenAI/NodeJS/3.3.0
Authorization: Bearer sk-111111111111111111111111111111111111111111111111
auth: 
Content-Length: 1050
Host: host.docker.internal:5051
Connection: keep-alive


{'model': 'text-embedding-ada-002', 'input': ['0),将它们放到openarkcompiler/tools目录，然后使用如下命令修改它们的文件权限：\ncd openarkcompiler/tools\nchmo d 775 gn\nchmo d 775 ninja 在完成文件权限的修改之后,将 openarkcompiler/Makefile 文件中的 gn 和 Ninja 两个变量配置为 gn 和 Ninja 可执行程序的所在路径。 这里需要提醒大家注意：第一，目前方舟编译器的默认构建系统是 64 位的 Ubuntu 16.04，所以在这里推荐按照官方的默认版本选择系统，避免在更高版本的系统上出现问题；第二，根据配置文件的要求完成相关配置的时候，需要修改 gn 和 Ninja的权限。 在完成环境配置之后，可以开始进行方舟编译器源码的编译。方舟编译器源码编译需要执行以下命令：\nsource build/envsetup. sh\nmake 其中, source build/envsetup. sh 是初始化环境, make 是直接进行编译。 也可以通过 make BUILD TYPE= DEBUG 编译 Debug 版本。编译完成后的输出信息如图2.']}
OpenAIError TypeError('encode() takes at most 2 arguments (5 given)')
Traceback (most recent call last):
  File "/root/CodeSpace/text-generation-webui/extensions/openai/script.py", line 114, in wrapper
    func(self)
  File "/root/CodeSpace/text-generation-webui/extensions/openai/script.py", line 283, in do_POST
    response = OAIembeddings.embeddings(input, encoding_format)
  File "/root/CodeSpace/text-generation-webui/extensions/openai/embeddings.py", line 63, in embeddings
    embeddings = get_embeddings(input)
  File "/root/CodeSpace/text-generation-webui/extensions/openai/embeddings.py", line 58, in get_embeddings
    return get_embeddings_model().encode(input, convert_to_numpy=True, normalize_embeddings=True, convert_to_tensor=False, device=embeddings_device)
TypeError: encode() takes at most 2 arguments (5 given)

b'{"error": {"message": "TypeError(\'encode() takes at most 2 arguments (5 given)\')", "code": 500, "type": "OpenAIError", "param": ""}}'
POST /v1/embeddings HTTP/1.1
Accept: application/json, text/plain, */*
Content-Type: application/json
User-Agent: OpenAI/NodeJS/3.3.0
Authorization: Bearer sk-111111111111111111111111111111111111111111111111
auth: 
Content-Length: 832
Host: host.docker.internal:5051
Connection: keep-alive


{'model': 'text-embedding-ada-002', 'input': ['04/bin/clang"\nGN_CXX_COMPILER = "${MAPLE_ROOT}/tools/clang_llvm-8.0.0 - x86_64-linux-gnu-ubuntu-16.04/bin/clang++"\nGN_AR_COMPILER = "${MAPLE_ROOT}/tools/clang_llvm-8.0.0-x86_64-linux-gnu-ubuntu-16.04/bin/llvm-ar" 第3步,安装 gn 和 Ninja 并完成配置。 在 https://gitee.com/ xlnb/gn binary下载gn,在 https://github.com/ninja-build/ninja/\n011\n华为方舟编译器之美——基于开源代码的架构分析与实现\nreleases下载Ninja(V1.9.0),将它们放到openarkcompiler/tools目录，然后使用如下命令修改它们的文件权限：\ncd openarkcompiler/tools\nchmo d 775 gn\nchmo d 775 ninja 在完成文件权限的修改之后,将 openarkcompiler/Makefile 文件中的 gn 和 Ninja 两个变量配置为 gn 和 Ninja 可执行程序的所在路径。']}
OpenAIError TypeError('encode() takes at most 2 arguments (5 given)')
Traceback (most recent call last):
  File "/root/CodeSpace/text-generation-webui/extensions/openai/script.py", line 114, in wrapper
    func(self)
  File "/root/CodeSpace/text-generation-webui/extensions/openai/script.py", line 283, in do_POST
    response = OAIembeddings.embeddings(input, encoding_format)
  File "/root/CodeSpace/text-generation-webui/extensions/openai/embeddings.py", line 63, in embeddings
    embeddings = get_embeddings(input)
  File "/root/CodeSpace/text-generation-webui/extensions/openai/embeddings.py", line 58, in get_embeddings
    return get_embeddings_model().encode(input, convert_to_numpy=True, normalize_embeddings=True, convert_to_tensor=False, device=embeddings_device)
TypeError: encode() takes at most 2 arguments (5 given)

b'{"error": {"message": "TypeError(\'encode() takes at most 2 arguments (5 given)\')", "code": 500, "type": "OpenAIError", "param": ""}}'
```
```


### System Info

```shell
Ubuntu 20.04
RTX 3090
```

**Comment by yhyu13** [comment]
Somehow the embedding_model which suppose to be "Sentencetransformer model" has became str by this line https://github.com/oobabooga/text-generation-webui/blob/0197fdddf106270ccf77fc2757d7bc53cc9729d4/extensions/openai/embeddings.py#L29

**Comment by yhyu13** [comment]
Update:

## How to reproduce

Regard the original code https://github.com/oobabooga/text-generation-webui/blob/0197fdddf106270ccf77fc2757d7bc53cc9729d4/extensions/openai/embeddings.py#L25

If you failed to load embedding model the first time, the global variable embeddings_model is set to the str 'loading' by `embeddings_model = 'loading...'`.

So the second time you entried get_embeddings_model(), by this conditioning, this method would simply return the str embeddings_model which equals 'loading...' https://github.com/oobabooga/text-generation-webui/blob/0197fdddf106270ccf77fc2757d7bc53cc9729d4/extensions/openai/embeddings.py#L44

And python `str` has its own `encode()` method that takes `encoding` and `error` as arguments, which causes the above argument values error
