### ISSUE TITLE
StableLM GPTNeoXTokenizer Error

### ISSUE THREAD

**Issue by quartets** [oobabooga/text-generation-webui#4149]
### Describe the bug

When loading stabilityai/stablelm-3b-4e1t model, the following error was returned:

File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 748, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class GPTNeoXTokenizer does not exist or is not currently imported.

I found the following content in tokenizer_config.json:
{
  "add_prefix_space": false,
  "bos_token": "<|endoftext|>",
  "clean_up_tokenization_spaces": true,
  "eos_token": "<|endoftext|>",
  "model_max_length": 1000000000000000019884624838656,
  "tokenizer_class": "GPTNeoXTokenizer",
  "unk_token": "<|endoftext|>"
}

I can make it run from terminal with the instruction from its HF page, so I guess the repository is OK.

So is it not yet supported by text-generation-webui, or did I miss some configuration? Please advise! Thanks.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Just load the model and the error occurs.

### Logs

```shell
2023-10-02 20:09:19 INFO:Loading stablelm-3b-4e1t...
2023-10-02 20:09:22 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/home/ubuntu/text-generation-webui/modules/ui_model_menu.py", line 201, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/home/ubuntu/text-generation-webui/modules/models.py", line 86, in load_model
    tokenizer = load_tokenizer(model_name, model)
  File "/home/ubuntu/text-generation-webui/modules/models.py", line 105, in load_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 748, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class GPTNeoXTokenizer does not exist or is not currently imported.
```

### System Info

```shell
Nvidia T4 with 16GB nvram, 32GB ram. Ubuntu 2022.
```

**Comment by DeadPixhell** [comment]
I have reproduced the bug.

i made some search for this error.
i found this : https://github.com/huggingface/transformers/issues/17756
then, i tiked Use_Fast in the Model Panel, now i can load it

**Comment by quartets** [comment]
Many thanks, DeadPixhell!
I ticked use_fast box and it loaded successfully.
