### ISSUE TITLE
Unable to load Llava 13B/7B model

### ISSUE THREAD

**Issue by khoicodesthings** [oobabooga/text-generation-webui#4161]
### Describe the bug

I have downloaded the Llava models from wojtab (i.e https://huggingface.co/wojtab/llava-13b-v0-4bit-128g) and verified that it is placed in the correct directory.

Upon using `python3 server.py --model wojtab_llava-13b-v0-4bit-128g --multimodal-pipeline llava-13b` per the documentation to start the web ui, I am getting the following error (OSError) provided in the screenshot section

I am unsure how to proceed.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Download the Llava model from https://huggingface.co/wojtab/llava-13b-v0-4bit-128g
2. Start the web UI with `python3 server.py --model wojtab_llava-13b-v0-4bit-128g --multimodal-pipeline llava-13b`

### Screenshot

![error](https://github.com/oobabooga/text-generation-webui/assets/83363717/b7036535-8947-4c06-8024-a8ac185e9c49)

### Logs

```shell
N/A
```

### System Info

```shell
Intel Core i5 12600KF

Nvidia RTX 3070
```

**Comment by zuzzleberry** [comment]
same here

**Comment by BetaDoggo** [comment]
You have to also add `--loader gptq-for-llama --groupsize 128 --wbits 4`. That will get the model to load but it seems like inference is still broken.

For me it generates a single token "The" then this error message:
```
Traceback (most recent call last):
  File "E:\text\text-generation-webui\modules\callbacks.py", line 56, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "E:\text\text-generation-webui\modules\text_generation.py", line 349, in generate_with_callback
    shared.model.generate(**kwargs)
  File "E:\text\text-generation-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\text\text-generation-webui\venv\lib\site-packages\transformers\generation\utils.py", line 1652, in generate
    return self.sample(
  File "E:\text\text-generation-webui\venv\lib\site-packages\transformers\generation\utils.py", line 2734, in sample
    outputs = self(
  File "E:\text\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\text\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\text\text-generation-webui\venv\lib\site-packages\transformers\models\llama\modeling_llama.py", line 1038, in forward
    outputs = self.model(
  File "E:\text\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\text\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\text\text-generation-webui\venv\lib\site-packages\transformers\models\llama\modeling_llama.py", line 925, in forward
    layer_outputs = decoder_layer(
  File "E:\text\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\text\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\text\text-generation-webui\venv\lib\site-packages\transformers\models\llama\modeling_llama.py", line 635, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "E:\text\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\text\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\text\text-generation-webui\venv\lib\site-packages\transformers\models\llama\modeling_llama.py", line 349, in forward
    query_states = self.q_proj(hidden_states)
  File "E:\text\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\text\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\text\text-generation-webui\venv\lib\site-packages\gptq_for_llama\gptq_old\quant.py", line 426, in forward
    quant_cuda.vecquant4matmul(x, self.qweight, y, self.scales, self.qzeros, self.groupsize)
NameError: name 'quant_cuda' is not defined
```

**Comment by khoicodesthings** [comment]
> You have to also add `--loader gptq-for-llama --groupsize 128 --wbits 4`. That will get the model to load but it seems like inference is still broken.
> 
> For me it generates a single token "The" then this error message:
> 
> ```
> Traceback (most recent call last):
>   File "E:\text\text-generation-webui\modules\callbacks.py", line 56, in gentask
>     ret = self.mfunc(callback=_callback, *args, **self.kwargs)
>   File "E:\text\text-generation-webui\modules\text_generation.py", line 349, in generate_with_callback
>     shared.model.generate(**kwargs)
>   File "E:\text\text-generation-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "E:\text\text-generation-webui\venv\lib\site-packages\transformers\generation\utils.py", line 1652, in generate
>     return self.sample(
>   File "E:\text\text-generation-webui\venv\lib\site-packages\transformers\generation\utils.py", line 2734, in sample
>     outputs = self(
>   File "E:\text\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "E:\text\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "E:\text\text-generation-webui\venv\lib\site-packages\transformers\models\llama\modeling_llama.py", line 1038, in forward
>     outputs = self.model(
>   File "E:\text\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "E:\text\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "E:\text\text-generation-webui\venv\lib\site-packages\transformers\models\llama\modeling_llama.py", line 925, in forward
>     layer_outputs = decoder_layer(
>   File "E:\text\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "E:\text\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "E:\text\text-generation-webui\venv\lib\site-packages\transformers\models\llama\modeling_llama.py", line 635, in forward
>     hidden_states, self_attn_weights, present_key_value = self.self_attn(
>   File "E:\text\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "E:\text\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "E:\text\text-generation-webui\venv\lib\site-packages\transformers\models\llama\modeling_llama.py", line 349, in forward
>     query_states = self.q_proj(hidden_states)
>   File "E:\text\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "E:\text\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "E:\text\text-generation-webui\venv\lib\site-packages\gptq_for_llama\gptq_old\quant.py", line 426, in forward
>     quant_cuda.vecquant4matmul(x, self.qweight, y, self.scales, self.qzeros, self.groupsize)
> NameError: name 'quant_cuda' is not defined
> ```
> 
> Edit: Seems like there was an issue with my environment as after redoing the auto install the issue went away. I think the doc page for the extension just needs to be updated with what I mentioned above and this can be closed.

Yes! Adding these 2 extra parameters worked for me!
