### ISSUE TITLE
IndexError: Out of range durring text generation

### ISSUE THREAD

**Issue by lufixSch** [oobabooga/text-generation-webui#4163]
### Describe the bug

With some models (at the moment  I could only replicate it with TheBloke/Mistral-7B-OpenOrca-GPTQ but I think I have seen it with other models before) I get an error during text completion when loading them with ExLlama or ExLlamaV2

When using the WebUI this was never a problem as I still get an output. When using the API instead I get the same error but no output at all.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Load [TheBloke/Mistral-7B-OpenOrca-GPTQ](https://huggingface.co/TheBloke/Mistral-7B-OpenOrca-GPTQ) with exllama or exllamav2
2. Run any kind of text completion (Chat, Notebook, Default)

### Logs

Error from Notebook:
```shell
Traceback (most recent call last):
  File "/run/media/lukas/linux_data/AI/LLM/WebUI/modules/text_generation.py", line 384, in generate_reply_custom
    for reply in shared.model.generate_with_streaming(question, state):
  File "/run/media/lukas/linux_data/AI/LLM/WebUI/modules/exllamav2.py", line 119, in generate_with_streaming
    decoded_text = self.tokenizer.decode(ids[:, initial_len:])[0]
  File "/run/media/lukas/linux_data/AI/LLM/WebUI/.venvs/llm/lib/python3.10/site-packages/exllamav2/tokenizer.py", line 92, in decode
    texts.append(self.tokenizer.Decode(seq))
  File "/run/media/lukas/linux_data/AI/LLM/WebUI/.venvs/llm/lib/python3.10/site-packages/sentencepiece/__init__.py", line 780, in Decode
    return self._DecodeIds(input)
  File "/run/media/lukas/linux_data/AI/LLM/WebUI/.venvs/llm/lib/python3.10/site-packages/sentencepiece/__init__.py", line 337, in _DecodeIds
    return _sentencepiece.SentencePieceProcessor__DecodeIds(self, ids)
IndexError: Out of range: piece id is out of range.
Output generated in 3.20 seconds (31.59 tokens/s, 101 tokens, context 522, seed 2086850837)
```

Error from API:
```shell
/run/media/lukas/linux_data/AI/LLM/WebUI/repositories/exllama/model.py:493: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ../aten/src/ATen/native/transformers/hip/sdp_utils.cpp:235.)
  attn_output = F.scaled_dot_product_attention(query_states, key_states, value_states, attn_mask = None, is_causal = True)
/run/media/lukas/linux_data/AI/LLM/WebUI/repositories/exllama/model.py:493: UserWarning: 1Torch was not compiled with memory efficient attention. (Triggered internally at ../aten/src/ATen/native/transformers/hip/sdp_utils.cpp:272.)
  attn_output = F.scaled_dot_product_attention(query_states, key_states, value_states, attn_mask = None, is_causal = True)
Traceback (most recent call last):
  File "/run/media/lukas/linux_data/AI/LLM/WebUI/modules/text_generation.py", line 381, in generate_reply_custom
    reply = shared.model.generate(question, state)
  File "/run/media/lukas/linux_data/AI/LLM/WebUI/modules/exllama.py", line 215, in generate
    for output in self.generate_with_streaming(prompt, state):
  File "/run/media/lukas/linux_data/AI/LLM/WebUI/modules/exllama.py", line 162, in generate_with_streaming
    decoded_text = self.generator.tokenizer.decode(self.generator.sequence[0][initial_len:])
  File "/run/media/lukas/linux_data/AI/LLM/WebUI/repositories/exllama/tokenizer.py", line 174, in decode
    text = self.tokenizer.Decode(ids)
  File "/run/media/lukas/linux_data/AI/LLM/WebUI/.venvs/llm/lib/python3.10/site-packages/sentencepiece/__init__.py", line 780, in Decode
    return self._DecodeIds(input)
  File "/run/media/lukas/linux_data/AI/LLM/WebUI/.venvs/llm/lib/python3.10/site-packages/sentencepiece/__init__.py", line 337, in _DecodeIds
    return _sentencepiece.SentencePieceProcessor__DecodeIds(self, ids)
IndexError: Out of range: piece id is out of range.
Output generated in 1.35 seconds (0.00 tokens/s, 0 tokens, context 217, seed 1211553077)
```

### System Info

```shell
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 6.5.3-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 20 × 13th Gen Intel® Core™ i5-13500
Memory: 31.1 GiB of RAM
Graphics Processor: AMD Radeon RX 6750 XT
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7D98
System Version: 1.0
```

**Comment by gestalt73** [comment]
Same. only occurs with TheBloke_Mistral-7B-OpenOrca-GPTQ.

Also, generation through text-generation-webui will generate even though it kicks out an error.  Generation through extensions openai api errors out with 0 tokens generated.

Other variations of the Mistral model do not get the error:
- TheBloke_Mistral-7B-Instruct-v0.1-GPTQ
- TheBloke_Mistral-7B-v0.1-GPTQ

```
Traceback (most recent call last):
  File "/home/alansrobotlab/Documents/text-generation-webui/modules/text_generation.py", line 386, in generate_reply_custom
    for reply in shared.model.generate_with_streaming(question, state):
  File "/home/alansrobotlab/Documents/text-generation-webui/modules/exllamav2.py", line 119, in generate_with_streaming
    decoded_text = self.tokenizer.decode(ids[:, initial_len:])[0]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alansrobotlab/.local/lib/python3.11/site-packages/exllamav2-0.0.3-py3.11.egg/exllamav2/tokenizer.py", line 92, in decode
    texts.append(self.tokenizer.Decode(seq))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alansrobotlab/anaconda3/envs/textgen/lib/python3.11/site-packages/sentencepiece/__init__.py", line 780, in Decode
    return self._DecodeIds(input)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alansrobotlab/anaconda3/envs/textgen/lib/python3.11/site-packages/sentencepiece/__init__.py", line 337, in _DecodeIds
    return _sentencepiece.SentencePieceProcessor__DecodeIds(self, ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Out of range: piece id is out of range.
Output generated in 0.28 seconds (82.01 tokens/s, 23 tokens, context 319, seed 3399502)
```

**Comment by gestalt73** [comment]
ok,  not sure what the magic step was/is, but this resolved it for me:
1. delete the TheBloke_Mistral-7B-OpenOrca-GPTQ folder from the /models directory
2. run git pull from your text-generation-webui directory
3. pip uninstall exllamav2
4. pip install exllamav2 (installs exllamav2-0.0.5)

**Comment by lufixSch** [comment]
Updating to the latest WebUI version (and updating the dependencies according to the requirements.txt) fixed it for me too.
