### ISSUE TITLE
Unable to load GGUF models on cpu in Linux

### ISSUE THREAD

**Issue by nicholasjgraham** [oobabooga/text-generation-webui#4165]
### Describe the bug

When trying to load a GGUF model via llama.cpp on an x64 Linux server without a GPU, I receive an error.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

- Install text-generation-webui with start_linux.sh, and select "CPU Only" as the available hardware during setup.
- Try to load a GGUF model with llama.cpp

### Logs

```shell
2023-10-03 09:39:52 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/opt/chatbot/text-generation-webui/modules/ui_model_menu.py", line 201, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/opt/chatbot/text-generation-webui/modules/models.py", line 78, in load_model
    output = load_func_map[loader](model_name)
  File "/opt/chatbot/text-generation-webui/modules/models.py", line 224, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
  File "/opt/chatbot/text-generation-webui/modules/llamacpp_model.py", line 54, in from_pretrained
    Llama = llama_cpp_lib().Llama
AttributeError: 'NoneType' object has no attribute 'Llama'
```

### System Info

```shell
Rocky Linux 9.2 inside VMware, running on Xeon E5-2697 v2 CPUs
```

**Comment by AG-w** [comment]
try if this help?
https://github.com/oobabooga/text-generation-webui/pull/4189
use update script after change

**Comment by nicholasjgraham** [comment]
> try if this help? #4189 use update script after change

Nice, with that fix it works perfectly. Thanks!

**Comment by CubeTheThird** [comment]
Strangely I get this issue now, but only if I build llama-cpp to support CLBlast specifically. Others, like OpenBLAS doesn't do it.
