### ISSUE TITLE
flash-attn >= 2.0.0 breaks exllamav2, AutoGPTQ support on GPUS older than ampere

### ISSUE THREAD

**Issue by DFXLuna** [oobabooga/text-generation-webui#4172]
### Describe the bug

After updating to the commit, exllamav2 can no longer run inference on Nvidia GPUs that are older than Ampere (anything under consumer RTX 3xxx or the equivalent Axxx GPU). This is because flash-attn v2.0.0 and greater require Ampere or later, as mentioned in their [readme](https://pypi.org/project/flash-attn/).

Notably, this also includes T series GPUs like are available on google colab.

Before flash-attn was added to the requirements in f46ba12b4201cdcee7b2d0f7413dfa2a71faec26 , it was possible to install flash-attn v1.0.9 using the cmd scripts without issue; however, this seems to break something on startup now. Just to be clear, this did work before.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

- Install text-generation-webui on a machine with an Nvidia GPU older than Ampere
- Try to run a model with exllamav2
OR
- Install text-generation-webui on a machine with an Nvidia GPU older than Ampere
- Uninstall flash-attn v2 using cmd_linux
- Install flash-atten v2 using cmd_linux
- Try to start text-generation-webui

### Logs

```shell
Inference output after loading and prompting with exllamav2

2023-10-03 23:08:47 INFO:Loading QMB15_mythomax-13B-8.13bit-MAX-exl2...
2023-10-03 23:09:14 INFO:Loaded the model in 27.42 seconds.

Traceback (most recent call last):
  File "/home/SNIP/text-gen/text-generation-webui/modules/text_generation.py", line 384, in generate_reply_custom
    for reply in shared.model.generate_with_streaming(question, state):
  File "/home/SNIP/text-gen/text-generation-webui/modules/exllamav2.py", line 108, in generate_with_streaming
    self.model.forward(ids[:, :-1], self.cache, input_mask=None, preprocess_only=True)
  File "/home/SNIP/text-gen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/exllamav2/model.py", line 369, in forward
    r = self._forward(input_ids = input_ids[:, chunk_begin : chunk_end],
  File "/home/SNIP/text-gen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/exllamav2/model.py", line 421, in _forward
    x = module.forward(x, cache = cache, attn_mask = attn_mask, past_len = past_len)
  File "/home/SNIP/text-gen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/exllamav2/attn.py", line 329, in forward
    attn_output = flash_attn_func(q_states, k_states, v_states, causal = True)
  File "/home/SNIP/text-gen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 705, in flash_attn_func
    return FlashAttnFunc.apply(
  File "/home/SNIP/text-gen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/SNIP/text-gen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 434, in forward
    out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = _flash_attn_forward(
  File "/home/SNIP/text-gen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 47, in _flash_attn_forward
    out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = flash_attn_cuda.fwd(
RuntimeError: FlashAttention only supports Ampere GPUs or newer.
```

Output from uninstalling v2 and install v1.0.9
```
(/home/SNIP/text-gen/text-generation-webui/installer_files/env) SNIP@emi-ml-server:~/text-gen/text-generation-webui$ ./installer_files/env/bin/pip uninstall flash-attn
Found existing installation: flash-attn 2.3.0
Uninstalling flash-attn-2.3.0:
  Would remove:
    /home/SNIP/text-gen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/flash_attn-2.3.0.dist-info/*
    /home/SNIP/text-gen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/flash_attn/*
    /home/SNIP/text-gen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so
Proceed (Y/n)? y
  Successfully uninstalled flash-attn-2.3.0
(/home/SNIP/text-gen/text-generation-webui/installer_files/env) SNIP@emi-ml-server:~/text-gen/text-generation-webui$ ./installer_files/env/bin/pip install flash-attn==1.0.9
Collecting flash-attn==1.0.9
  Downloading flash_attn-1.0.9.tar.gz (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 30.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in ./installer_files/env/lib/python3.10/site-packages (from flash-attn==1.0.9) (2.0.1)
Requirement already satisfied: einops in ./installer_files/env/lib/python3.10/site-packages (from flash-attn==1.0.9) (0.7.0)
Requirement already satisfied: packaging in ./installer_files/env/lib/python3.10/site-packages (from flash-attn==1.0.9) (23.1)
Requirement already satisfied: ninja in ./installer_files/env/lib/python3.10/site-packages (from flash-attn==1.0.9) (1.11.1)
Requirement already satisfied: filelock in ./installer_files/env/lib/python3.10/site-packages (from torch->flash-attn==1.0.9) (3.12.4)
Requirement already satisfied: typing-extensions in ./installer_files/env/lib/python3.10/site-packages (from torch->flash-attn==1.0.9) (4.8.0)
Requirement already satisfied: sympy in ./installer_files/env/lib/python3.10/site-packages (from torch->flash-attn==1.0.9) (1.12)
Requirement already satisfied: networkx in ./installer_files/env/lib/python3.10/site-packages (from torch->flash-attn==1.0.9) (3.1)
Requirement already satisfied: jinja2 in ./installer_files/env/lib/python3.10/site-packages (from torch->flash-attn==1.0.9) (3.1.2)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in ./installer_files/env/lib/python3.10/site-packages (from torch->flash-attn==1.0.9) (11.7.99)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in ./installer_files/env/lib/python3.10/site-packages (from torch->flash-attn==1.0.9) (11.7.99)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.7.101 in ./installer_files/env/lib/python3.10/site-packages (from torch->flash-attn==1.0.9) (11.7.101)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in ./installer_files/env/lib/python3.10/site-packages (from torch->flash-attn==1.0.9) (8.5.0.96)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in ./installer_files/env/lib/python3.10/site-packages (from torch->flash-attn==1.0.9) (11.10.3.66)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in ./installer_files/env/lib/python3.10/site-packages (from torch->flash-attn==1.0.9) (10.9.0.58)
Requirement already satisfied: nvidia-curand-cu11==10.2.10.91 in ./installer_files/env/lib/python3.10/site-packages (from torch->flash-attn==1.0.9) (10.2.10.91)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.0.1 in ./installer_files/env/lib/python3.10/site-packages (from torch->flash-attn==1.0.9) (11.4.0.1)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.4.91 in ./installer_files/env/lib/python3.10/site-packages (from torch->flash-attn==1.0.9) (11.7.4.91)
Requirement already satisfied: nvidia-nccl-cu11==2.14.3 in ./installer_files/env/lib/python3.10/site-packages (from torch->flash-attn==1.0.9) (2.14.3)
Requirement already satisfied: nvidia-nvtx-cu11==11.7.91 in ./installer_files/env/lib/python3.10/site-packages (from torch->flash-attn==1.0.9) (11.7.91)
Requirement already satisfied: triton==2.0.0 in ./installer_files/env/lib/python3.10/site-packages (from torch->flash-attn==1.0.9) (2.0.0)
Requirement already satisfied: setuptools in ./installer_files/env/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch->flash-attn==1.0.9) (68.0.0)
Requirement already satisfied: wheel in ./installer_files/env/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch->flash-attn==1.0.9) (0.38.4)
Requirement already satisfied: cmake in ./installer_files/env/lib/python3.10/site-packages (from triton==2.0.0->torch->flash-attn==1.0.9) (3.27.5)
Requirement already satisfied: lit in ./installer_files/env/lib/python3.10/site-packages (from triton==2.0.0->torch->flash-attn==1.0.9) (16.0.6)
Requirement already satisfied: MarkupSafe>=2.0 in ./installer_files/env/lib/python3.10/site-packages (from jinja2->torch->flash-attn==1.0.9) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in ./installer_files/env/lib/python3.10/site-packages (from sympy->torch->flash-attn==1.0.9) (1.3.0)
Building wheels for collected packages: flash-attn
  Building wheel for flash-attn (setup.py) ... done
  Created wheel for flash-attn: filename=flash_attn-1.0.9-cp310-cp310-linux_x86_64.whl size=46778516 sha256=57de5d86bfea70cb6e870fb50fa0f8231d44abde6ba26d99dc1596fd9c1f871b
  Stored in directory: /home/SNIP/.cache/pip/wheels/39/0b/ce/636c86275ad0554779f28ed6ca514b86f01d00881968733155
Successfully built flash-attn
Installing collected packages: flash-attn
Successfully installed flash-attn-1.0.9
```

Output of starting with flash-attn v1.0.9
```
❯ ./start_linux.sh
2023-10-03 23:23:32 WARNING:
You are potentially exposing the web UI to the entire internet without any access password.
You can create one with the "--gradio-auth" flag like this:

--gradio-auth username:password

Make sure to replace username:password with your own.
Traceback (most recent call last):
  File "/home/SNIP/text-gen/text-generation-webui/server.py", line 30, in <module>
    from modules import (
  File "/home/SNIP/text-gen/text-generation-webui/modules/chat.py", line 18, in <module>
    from modules.text_generation import (
  File "/home/SNIP/text-gen/text-generation-webui/modules/text_generation.py", line 23, in <module>
    from modules.models import clear_torch_cache, local_rank
  File "/home/SNIP/text-gen/text-generation-webui/modules/models.py", line 22, in <module>
    from modules import RoPE, llama_attn_hijack, sampler_hijack
  File "/home/SNIP/text-gen/text-generation-webui/modules/llama_attn_hijack.py", line 7, in <module>
    import transformers.models.llama.modeling_llama
  File "/home/SNIP/text-gen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 45, in <module>
    from flash_attn import flash_attn_func, flash_attn_varlen_func
ImportError: cannot import name 'flash_attn_func' from 'flash_attn' (/home/SNIP/text-gen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/flash_attn/__init__.py)
7.06s user 2.08s system 140% cpu 6.508s total
```

### System Info

```shell
OS: Ubuntu Server 22.04
GPU: Nvidia RTX 8000
```

**Comment by Ph0rk0z** [comment]
So from the looks of it transformers is importing flash attention2 from the attention hijack. You would have to downgrade transformers to 4.33.x which stops you from using AWQ because that forces import of mistral.

But as long as you don't use AWQ or mistral this should work. Fingers crossed.

**Comment by iplayfast** [comment]
On startup this is what I get. (not sure if it's the same problem or not)
 import flash_attn_2_cuda as flash_attn_cuda
ImportError: /home/chris/ai/data/text-generation-webui/installer_files/env/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c106SymIntltEl

Running on a gtx960M 
inxi -Gxxx
Graphics:
  Device-1: Intel HD Graphics 530 vendor: Micro-Star MSI driver: i915
    v: kernel ports: active: eDP-1 empty: DP-1,HDMI-A-1,HDMI-A-2
    bus-ID: 00:02.0 chip-ID: 8086:191b class-ID: 0300
  Device-2: NVIDIA GM107M [GeForce GTX 960M] vendor: Micro-Star MSI
    driver: nvidia v: 535.113.01 pcie: speed: 2.5 GT/s lanes: 16
    bus-ID: 01:00.0 chip-ID: 10de:139b class-ID: 0302
  Display: x11 server: X.Org v: 1.21.1.4 driver: X:
    loaded: modesetting,nvidia unloaded: fbdev,nouveau,vesa gpu: i915
    display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1368x768 s-dpi: 96 s-size: 362x203mm (14.3x8.0")
    s-diag: 415mm (16.3")
  Monitor-1: eDP-1 model: LG res: 1368x768 hz: 60 dpi: 101
    size: 344x194mm (13.5x7.6") diag: 395mm (15.5") modes: 1920x1080
  OpenGL: renderer: Mesa Intel HD Graphics 530 (SKL GT2)
    v: 4.6 Mesa 23.0.4-0ubuntu1~22.04.1 direct render: Yes

**Comment by DFXLuna** [comment]
> > On startup this is what I get. (not sure if it's the same problem or not) import flash_attn_2_cuda as flash_attn_cuda ImportError: /home/chris/ai/data/text-generation-webui/installer_files/env/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c106SymIntltEl
> > Running on a gtx960M inxi -Gxxx Graphics: Device-1: Intel HD Graphics 530 vendor: Micro-Star MSI driver: i915 v: kernel ports: active: eDP-1 empty: DP-1,HDMI-A-1,HDMI-A-2 bus-ID: 00:02.0 chip-ID: 8086:191b class-ID: 0300 Device-2: NVIDIA GM107M [GeForce GTX 960M] vendor: Micro-Star MSI driver: nvidia v: 535.113.01 pcie: speed: 2.5 GT/s lanes: 16 bus-ID: 01:00.0 chip-ID: 10de:139b class-ID: 0302 Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: modesetting,nvidia unloaded: fbdev,nouveau,vesa gpu: i915 display-ID: :0 screens: 1 Screen-1: 0 s-res: 1368x768 s-dpi: 96 s-size: 362x203mm (14.3x8.0") s-diag: 415mm (16.3") Monitor-1: eDP-1 model: LG res: 1368x768 hz: 60 dpi: 101 size: 344x194mm (13.5x7.6") diag: 395mm (15.5") modes: 1920x1080 OpenGL: renderer: Mesa Intel HD Graphics 530 (SKL GT2) v: 4.6 Mesa 23.0.4-0ubuntu1~22.04.1 direct render: Yes
> 
> same here
> 
> Solved it by installing the wheel corresponding to my cuda version: https://github.com/Dao-AILab/flash-attention/releases/download/v2.3.1.post1/flash_attn-2.3.1.post1+cu122torch2.1cxx11abiFALSE-cp310-cp310-linux_x86_64.whl

This looks like a different issue since this one is a linker error occurring at compile time.

**Comment by DFXLuna** [comment]
Here's a workaround in case anyone stumbles on this in the meantime

- Downgrade to v1.6.1
- Make sure pip is using the conda env's pip with `which pip`
    - It should show pip coming from the `installer_files` folder rather than an OS folder
    - If it doesn't, invoke pip from the `installer_files` folder directly or install it with conda if it's not present.
- Use the command script to uninstall flash-attn with `pip uninstall flash-attn`
- Install flash-attn v1.0.9 (The last v1 version) with `pip install --no-build-isolation flash-attn==1.0.9`
- Exit the cmd script environment and restart

**Comment by fat-tire** [comment]
An alternative idea I found [here](https://github.com/Dao-AILab/flash-attention/issues/451#issuecomment-1692749712) for getting the latest `flash-attn` was to try to building it myself.  So here's what I tried:

* After installing `requirements.txt` per normal, `pip uninstall flash-attn` as suggested above.
* `pip install packaging` so you can do the next step.
* Then build flash-attn with ` FLASH_ATTENTION_FORCE_BUILD=TRUE pip install flash-attn --extra-index-url https://download.pytorch.org/whl/cu118`
* `pip uninstall packaging`

Unfortunately, it seemed to peg the CPU for me:
```
Building wheels for collected packages: flash-attn
  Building wheel for flash-attn (setup.py): started
  Building wheel for flash-attn (setup.py): still running...
  Building wheel for flash-attn (setup.py): still running...
  Building wheel for flash-attn (setup.py): still running...
  Building wheel for flash-attn (setup.py): still running...
  Building wheel for flash-attn (setup.py): still running...
  Building wheel for flash-attn (setup.py): still running...
```

Maybe it actually was doing something, but after like 15 minutes I gave up.

Weirdly I had the same issue when I just did `pip install --no-build-isolation flash-attn==1.0.9` running it in the environment.. :man_shrugging:

**Comment by Originalimoc** [comment]
Same:
```
ImportError: /home/user1/miniconda3/envs/textgen/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi
```

**Comment by Ph0rk0z** [comment]
`undefined symbol:
`
I got this same error after upgrading to torch 2.1 and re-compiling flash attention while leaving compute 6.1 GPU visible to FA.

Options were to downgrade torch or use cuda_visible_devices when compiling to hide pre-ampere gpu.

**Comment by JackCloudman** [comment]
I tested with this and it works for me 
`pip install --no-build-isolation flash-attn==2.3.0`

**Comment by fat-tire** [comment]
Not sure if there was a repo change or if targeting 2.3.0 made the difference, but it just worked for me too:

    pip3 install torch==2.0.1+cu118 torchvision==0.15.2+cu118 torchaudio==2.0.2 --extra-index-url https://download.pytorch.org/whl/cu118
    pip3 uninstall flash-attn
    pip3 install --no-build-isolation flash-attn==2.3.0 

Not sure if I needed to uninstall and then reinstall, but it worked. And AWQ worked this time without having to check `no_inject_fused_attention` either. So that's nice.

**Comment by DFXLuna** [comment]
> Not sure if there was a repo change or if targeting 2.3.0 made the difference, but it just worked for me too:
> 
> ```
> pip3 install torch==2.0.1+cu118 torchvision==0.15.2+cu118 torchaudio==2.0.2 --extra-index-url https://download.pytorch.org/whl/cu118
> pip3 uninstall flash-attn
> pip3 install --no-build-isolation flash-attn==2.3.0 
> ```
> 
> Not sure if I needed to uninstall and then reinstall, but it worked. And AWQ worked this time without having to check `no_inject_fused_attention` either. So that's nice.

This looks like a different issue since your GPU can run flash-attn v2. It would probably help the repo maintainers if you opened a separate ticket about flash-attn v2 compilation errors :)

The particular issue I'm reporting here is that flash-attn v2 is installed by default and it doesn't support GPUs older than Ampere generation (RTX 2000 and below).

**Comment by DFXLuna** [comment]
Starting the webui was fixed by #4231 but running exllamav2 on GPUs < Ampere is still broken because it's trying to use flash-attn v2. 

To be clear, the ONLY way to fix this is to check the Nvidia GPU generation at install time and choose either flash-attn v1 or v2. However, nvidia-smi will not output GPU generation, so you'll either need to correlate from GPU name to generation or ask the user.

Swapping back to v1.0.9 still works so, here's a more complete version of the workaround.
**If you're getting compiler issues, this will not fix it.** 
This will fix EXACTLY the issue where it outputs `RuntimeError: FlashAttention only supports Ampere GPUs or newer.` after trying to run inference.

```sh
# If you've already updated to the latest textgen version, do a fresh install. This will NOT work without a fresh install.
./cmd_linux.sh #Enter the conda env

which pip # Make sure pip is in [somepath]/installer_files/env/bin
which nvcc #  make sure nvcc is in [somepath]installer_files/env/bin/nvcc if this command outputs nothing OR a path other than installer_files, run the next two commands

conda install -c "nvidia/label/cuda-11.8.0" cuda-nvcc # Install nvcc because it is necessary to compile flash-attn 
which nvcc # Make sure this outputs [somepath]/installer_files/env/bin/nvcc 

pip install --no-build-isolation flash-attn==1.0.9 #Install flash-attn v1. This can take 20 or 30 minutes and will freeze up the whole time
# You can now leave the conda env with ctrl+D
```

**Comment by DFXLuna** [comment]
Just tried to run a model with AutoGPTQ and realized this issues also affects AutoGPTQ as well although it manifests in a different way (trying to import flash-attn v2 functions during model load.) Updated the issue title to reflect this.

Even if even flash-attn adds Turing support to v2, this still completely prevents Pascal GPUs (GTX 10xx & Quadro Pxx) from using AutoGPTQ. Pascal GPUs are particularly sensitive to this because exllama's performance is worse than AutoGPTQ on Pascal.

error log
```
Traceback (most recent call last):
  File "/home/SNIP/text-gen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1282, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/SNIP/text-gen/text-generation-webui/installer_files/env/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/SNIP/text-gen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 45, in <module>
    from flash_attn import flash_attn_func, flash_attn_varlen_func
ImportError: cannot import name 'flash_attn_func' from 'flash_attn' (/home/SNIP/text-gen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/flash_attn/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/SNIP/text-gen/text-generation-webui/modules/ui_model_menu.py", line 201, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/home/SNIP/text-gen/text-generation-webui/modules/models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "/home/SNIP/text-gen/text-generation-webui/modules/models.py", line 312, in GPTQ_loader
    model = modules.GPTQ_loader.load_quantized(model_name)
  File "/home/SNIP/text-gen/text-generation-webui/modules/GPTQ_loader.py", line 144, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.wbits, shared.args.groupsize, kernel_switch_threshold=threshold)
  File "/home/SNIP/text-gen/text-generation-webui/modules/GPTQ_loader.py", line 34, in _load_quant
    model = AutoModelForCausalLM.from_config(config, trust_remote_code=shared.args.trust_remote_code)
  File "/home/SNIP/text-gen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 440, in from_config
    model_class = _get_model_class(config, cls._model_mapping)
  File "/home/SNIP/text-gen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 387, in _get_model_class
    supported_models = model_mapping[type(config)]
  File "/home/SNIP/text-gen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 739, in __getitem__
    return self._load_attr_from_module(model_type, model_name)
  File "/home/SNIP/text-gen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 753, in _load_attr_from_module
    return getattribute_from_module(self._modules[module_name], attr)
  File "/home/SNIP/text-gen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 697, in getattribute_from_module
    if hasattr(module, attr):
  File "/home/SNIP/text-gen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1272, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/SNIP/text-gen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1284, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
cannot import name 'flash_attn_func' from 'flash_attn' (/home/SNIP/text-gen/text-generation-webui/installer_files/env/lib/python3.10/site-packages/flash_attn/__init__.py)
```

**Comment by Ph0rk0z** [comment]
I don't remember old flash attention supporting pascal either. For autogptq I am always adding disable exllama and disable exllamav2.

**Comment by DFXLuna** [comment]
> I don't remember old flash attention supporting pascal either. For autogptq I am always adding disable exllama and disable exllamav2.

That might be true. I have a P40 lying around here somewhere, I'll load it up and give it a try. If exllama doesn't work anyways, then maybe this is a non issue after flash-attn adds turing support.

**Comment by DFXLuna** [comment]
Alright, I ran some tests on a P40. I picked an older commit before flash-attn was baked in (72b4ab4) and ran it

- AutoGPTQ runs fine regardless of exllama kernel disabled or not
- ExLlama runs fine
    - Still seems to outperform AutoGPTQ although I didn't check super thoroughly.
- ExLlama 2 runs fine but required a manual install of nvcc
    - As expected, it outputs the no flash-attn warning

I added flash-attn v1 and redid the same tests
- AutoGPTQ still runs fine regardless of exllama kernel disabled or not
- ExLlama still runs fine
- ExLlama 2 runs fine and also doesn't output the warning about flash-attn
    - Not sure how to definitively test whether or not flash-attn is actually being used though.

Something to note is that I've only seen flash-attn v2 getting automatically installed so maybe that was your issue? Not sure.

**Comment by Ph0rk0z** [comment]
While they run, the 3t/s on a 13b you get is not the full performance of this card. I remember the v1 not working when I used it with the attention hijack. Xformers and SDP do.

**Comment by Harvester62** [comment]
Hello. I have a GTX1070 (8GB) and suddenly, after recent updates, it stopped being used for generation, which is now done with CPU. I am on Windows 10, Python 3.10.6, TexGenWebUI updated to the latest version of the main repo. I understand there is an issue, so this is just for the records.

**Comment by giaosudau** [comment]
> I tested with this and it works for me `pip install --no-build-isolation flash-attn==2.3.0`

This work for me.
