### ISSUE TITLE
Instability when performing actions during llama save state

### ISSUE THREAD

**Issue by CubeTheThird** [oobabooga/text-generation-webui#4175]
### Describe the bug

When using llama-cpp, after the prompt is generated, it enters a phase where it will save a cache of its current state. During this time, if any actions are performed in the UI (continuing the prompt, generating new text, etc.), the application behaves strangely. Some times the UI will freeze, or blank out. Some times errors are output in the console logs. The action taken may or may not actually be performed.

In my case, the save cache action can take quite long (several minutes), though it is unclear to me whether this is an issue with llama-cpp or something else.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

- Load up a gguf model using llama-cpp. In my case I have it compiled with CLBlast enabled, though I don't believe this impacts the issue. I have the model entirely offloaded onto GPU, and it defaults the n_ctx parameter to 4k.
- Using the default parameters, have the model respond to a prompt. 
- Once the text is finished generating, there is a moment afterwards where the UI will continue to show ellipsis (...) and the logs will show "saving X bytes of llama state". At this time, perform another action in the UI
- If done correctly, before the "cache saved" message appears in the logs, the UI will behave oddly

### Logs

```shell
ERROR:    Exception in ASGI application

Traceback (most recent call last):
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 247, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/starlette/middleware/cors.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/fastapi/routing.py", line 289, in app
    await dependant.call(**values)
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/gradio/routes.py", line 536, in join_queue
    session_info = await asyncio.wait_for(
  File "/home/user/.conda/envs/textgen2/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/starlette/websockets.py", line 133, in receive_json
    self._raise_on_disconnect(message)
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/starlette/websockets.py", line 105, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1006
```

### System Info

```shell
Arch Linux
AMD RX 6700XT GPU
```

**Comment by CubeTheThird** [comment]
This issue does persist. I have received a different error as a result of it:

```Traceback (most recent call last):
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/gradio/blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/gradio/utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2106, in run_sync_in_worker_thread
    return await future
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 833, in run
    result = context.run(func, *args)
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
  File "/home/user/.conda/envs/textgen2/lib/python3.10/site-packages/gradio/utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/home/user/Documents/Tmp/conda/text-generation-webui/modules/chat.py", line 342, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True)):
  File "/home/user/Documents/Tmp/conda/text-generation-webui/modules/chat.py", line 310, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "/home/user/Documents/Tmp/conda/text-generation-webui/modules/chat.py", line 257, in chatbot_wrapper
    output['visible'][-1][1] = apply_extensions('output', output['visible'][-1][1], state, is_chat=True)
IndexError: list index out of range```
