### ISSUE TITLE
[superboogav2] LlamaCppModel.decode() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by bonswouar** [oobabooga/text-generation-webui#4187]
### Describe the bug

The new superboogav2 extension crashes when generating data

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

- Load superboogav2
- Load a model (probably only for `llama.cpp` models, personally I was testing with `mistral-7b-openorca`
- Load a file or something in superboogav2
- Click on Load Data for example
- Crash

### Logs

```shell
2023-10-05 20:12:19 INFO:Successfully deleted 0 records from chromaDB.
2023-10-05 20:12:19 INFO:Adding 3 new embeddings.
Traceback (most recent call last):
  File "D:\text-generation-webui\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\text-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\text-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "D:\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "D:\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "D:\text-generation-webui\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\text-generation-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2106, in run_sync_in_worker_thread
    return await future
  File "D:\text-generation-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 833, in run
    result = context.run(func, *args)
  File "D:\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "D:\text-generation-webui\modules\chat.py", line 329, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True)):
  File "D:\text-generation-webui\modules\chat.py", line 297, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "D:\text-generation-webui\modules\chat.py", line 231, in chatbot_wrapper
    prompt = apply_extensions('custom_generate_chat_prompt', text, state, **kwargs)
  File "D:\text-generation-webui\modules\extensions.py", line 224, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "D:\text-generation-webui\modules\extensions.py", line 100, in _apply_custom_generate_chat_prompt
    return extension.custom_generate_chat_prompt(text, state, **kwargs)
  File "D:\text-generation-webui\extensions\superboogav2\script.py", line 167, in custom_generate_chat_prompt
    return custom_generate_chat_prompt_internal(user_input, state, collector, **kwargs)
  File "D:\text-generation-webui\extensions\superboogav2\chat_handler.py", line 128, in custom_generate_chat_prompt_internal
    results = collector.get_sorted_by_dist(user_input, n_results=parameters.get_chunk_count(), max_token_count=int(parameters.get_max_token_count()))
  File "D:\text-generation-webui\extensions\superboogav2\chromadb.py", line 338, in get_sorted_by_dist
    return_documents = self._get_documents_up_to_token_count(sorted_docs, max_token_count)
  File "D:\text-generation-webui\extensions\superboogav2\chromadb.py", line 312, in _get_documents_up_to_token_count
    truncated_doc = decode(doc_tokens[:remaining_tokens], skip_special_tokens=True)
  File "D:\text-generation-webui\modules\text_generation.py", line 142, in decode
    return shared.tokenizer.decode(output_ids, skip_special_tokens)
TypeError: LlamaCppModel.decode() takes 2 positional arguments but 3 were given
```

### System Info

```
Windows 10
Nvidia GTX 970
```

**Comment by bonswouar** [comment]
Fyi my dirty workaround to make it work is to replace https://github.com/oobabooga/text-generation-webui/blob/main/modules/text_generation.py#L143 with `return shared.tokenizer.decode(output_ids)`, but I'm pretty sure that's not the right way to do it (:

**Comment by AIWintermuteAI** [comment]
Can we re-open it? @oobabooga 
I can confirm the issue.

**Comment by AIWintermuteAI** [comment]
This was fixed by https://github.com/oobabooga/text-generation-webui/commit/1b69694fe9c461b901b6050d8e1c164166e39d3c - I was using an older version.
