### ISSUE TITLE
AutoAWQ Crash after generating 1 token when fused attention is enabled

### ISSUE THREAD

**Issue by latent-variable** [oobabooga/text-generation-webui#4196]
### Describe the bug

I am using TheBloke/Mistral-7B-OpenOrca-AWQ with the AutoAWQ loader  on windows with an RTX 3090
![image](https://github.com/oobabooga/text-generation-webui/assets/22504489/e95e3488-6030-4298-8496-18c243caa2a8)
After the model generates 1 token I get the following issue 
![image](https://github.com/oobabooga/text-generation-webui/assets/22504489/57b3c30d-c2e6-4f7e-83bc-fd1b9f00d40d)

I have yet to test this issue on other models. 
However, toggling no_inject_fused_attention allows the model to generate responses without an issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Steps in the description 

### Logs

```shell
Traceback (most recent call last):
  File "C:\AI\text-generation-webui\modules\callbacks.py", line 56, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "C:\AI\text-generation-webui\modules\text_generation.py", line 349, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\AI\text-generation-webui\installer_files\env\lib\site-packages\awq\models\base.py", line 36, in generate
    return self.model.generate(*args, **kwargs)
  File "C:\AI\text-generation-webui\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\AI\text-generation-webui\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1652, in generate
    return self.sample(
  File "C:\AI\text-generation-webui\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 2734, in sample
    outputs = self(
  File "C:\AI\text-generation-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\AI\text-generation-webui\installer_files\env\lib\site-packages\transformers\models\mistral\modeling_mistral.py", line 1045, in forward
    outputs = self.model(
  File "C:\AI\text-generation-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\AI\text-generation-webui\installer_files\env\lib\site-packages\transformers\models\mistral\modeling_mistral.py", line 850, in forward
    past_key_values_length = past_key_values[0][0].shape[2]
TypeError: 'NoneType' object is not subscriptable
```

### System Info

```shell
Windows
RTX 3090
Running locally
```

**Comment by YakuzaSuske** [comment]
I got the same issue.

**Comment by casper-hansen** [comment]
I'm super sorry about this. The latest version was rushed out a bit too fast to fix some issues and unfortunately, it caused new issues. You can `pip install autoawq==0.1.2` or wait until it is bumped to 0.1.4

**Comment by casper-hansen** [comment]
#4203 fixes this

**Comment by YakuzaSuske** [comment]
> #4203 fixes this

![image](https://github.com/oobabooga/text-generation-webui/assets/63294141/44beb0e4-5793-45e1-9703-d747589b2e47)
Now it generates but after i generate again it gets an error about the size of a tensor.

**Comment by latent-variable** [comment]
> > #4203 fixes this
> 
> ![image](https://user-images.githubusercontent.com/63294141/273352633-44beb0e4-5793-45e1-9703-d747589b2e47.png) Now it generates but after i generate again it gets an error about the size of a tensor.

I also am now also experiencing this

**Comment by casper-hansen** [comment]
I clearly need some unit tests for when I make releases. Notes these errors and will try to fix soon.

**Comment by casper-hansen** [comment]
@latent-variable Okay, I tried now with the same model and I cannot trigger this error on the latest version of AutoAWQ.

**Comment by casper-hansen** [comment]
I found that this is a long-standing issue on Windows as I mainly develop on Linux, so it's good to catch these types of issues to make it smooth for everyone. This has now been resolved on the main branch of AutoAWQ which you can install or wait until we bump versions to resolve this issue.

**Comment by latent-variable** [comment]
@casper-hansen the issue is still present, but now it only triggers after starting a new chat, If I load the model and continue the current chat it will work as expected. However, starting a new chat will cause the issue. Here is the stack trace:

![image](https://github.com/oobabooga/text-generation-webui/assets/22504489/6a7884b9-fe58-4119-b14e-f444b52d4a46)

I am running autoawq==0.1.4 btw

**Comment by RuntimeRacer** [comment]
I can confirm the issues happening with v0.1.4 as well. 
Downgrading to v0.1.2 solves it.
