### ISSUE TITLE
ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.

### ISSUE THREAD

**Issue by AndreyRGW** [oobabooga/text-generation-webui#420]
```
(textgen) F:\WBC\text-generation-webui>python server.py --load-in-4bit --gpu-memory 11 --cai-chat
Warning: --load-in-4bit is deprecated and will be removed. Use --gptq-bits 4 instead.

The following models are available:

1. codegen-6B-mono
2. codegen-6B-multi
3. llama-13b-hf-int4
4. llama-7b-hf
5. llama-7b-hf-int4
6. rugpt3large_based_on_gpt2
7. xglm-2.9B

Which one do you want to load? 1-7

3

Loading llama-13b-hf-int4...
Loading model ...
Done.
Traceback (most recent call last):
  File "F:\WBC\text-generation-webui\server.py", line 236, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "F:\WBC\text-generation-webui\modules\models.py", line 163, in load_model
    tokenizer = AutoTokenizer.from_pretrained(Path(f"models/{shared.model_name}/"))
  File "C:\ProgramData\Anaconda3\envs\textgen\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 677, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.
```

**Comment by Pipazoul** [comment]
Related issue here

https://github.com/oobabooga/text-generation-webui/issues/405#issuecomment-1474940628
