### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_grammar'

### ISSUE THREAD

**Issue by zhanghui-china** [oobabooga/text-generation-webui#4200]
### Describe the bug

when i  run：
python server.py --model models/chinese-alpaca-2-7b-hf --chat

it shows：
ModuleNotFoundError: No module named 'torch_grammar'

where can i find the package。

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

git clone https://github.com/oobabooga/text-generation-webui
cd text-generation-webui
pip install -r requirements.txt
python server.py --model models/chinese-alpaca-2-7b-hf --chat

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/63148804/cd495732-433b-4326-a60f-2d7496b26035)

### Logs

```shell
(textgen) zhanghui@ubuntu:/home1/zhanghui/1006/text-generation-webui$ python server.py --model models/chinese-alpaca-2-7b-hf --chat
2023-10-06 16:58:26 WARNING:The --chat flag has been deprecated and will be removed soon. Please remove that flag.
Traceback (most recent call last):
  File "server.py", line 30, in <module>
    from modules import (
  File "/home1/zhanghui/1006/text-generation-webui/modules/chat.py", line 18, in <module>
    from modules.text_generation import (
  File "/home1/zhanghui/1006/text-generation-webui/modules/text_generation.py", line 21, in <module>
    from modules.grammar import GrammarLogitsProcessor
  File "/home1/zhanghui/1006/text-generation-webui/modules/grammar.py", line 1, in <module>
    from torch_grammar import GrammarSampler
ModuleNotFoundError: No module named 'torch_grammar'
(textgen) zhanghui@ubuntu:/home1/zhanghui/1006/text-generation-webui$ ^C
```

### System Info

```shell
ubuntu 20.04 aarch64
conda 
python 3.8.13

(textgen) zhanghui@ubuntu:/home1/zhanghui/1006/text-generation-webui$ pip list
Package              Version          Editable project location
-------------------- ---------------- -------------------------------
aiofiles             23.1.0
aiohttp              3.8.4
aiosignal            1.3.1
altair               5.0.1
anyio                3.7.0
appdirs              1.4.4
async-timeout        4.0.2
attrs                23.1.0
certifi              2023.7.22
charset-normalizer   3.1.0
click                8.1.7
contourpy            1.1.1
cycler               0.12.0
docker-pycreds       0.4.0
exceptiongroup       1.1.1
fastapi              0.99.0
ffmpy                0.3.0
filelock             3.12.4
fonttools            4.43.0
frozenlist           1.3.3
fschat               0.2.16
fsspec               2023.6.0
gitdb                4.0.10
GitPython            3.1.31
gradio               3.35.2
gradio_client        0.2.7
h11                  0.14.0
httpcore             0.17.2
httpx                0.24.1
huggingface-hub      0.15.1
idna                 3.4
importlib-metadata   6.8.0
importlib-resources  5.12.0
Jinja2               3.1.2
jsonschema           4.17.3
kiwisolver           1.4.5
linkify-it-py        2.0.2
Markdown             3.4.4
markdown-it-py       2.2.0
markdown2            2.4.9
MarkupSafe           2.1.3
matplotlib           3.7.3
mdit-py-plugins      0.3.3
mdurl                0.1.2
mpmath               1.3.0
multidict            6.0.4
nanosam              0.0              /home1/zhanghui/nanosam/nanosam
networkx             3.1
nh3                  0.2.13
numpy                1.24.4
orjson               3.9.1
packaging            23.1
pandas               2.0.3
pathtools            0.1.2
Pillow               10.0.1
pip                  22.3.1
pkgutil_resolve_name 1.3.10
prompt-toolkit       3.0.38
psutil               5.9.5
pydantic             1.10.10
pydub                0.25.1
Pygments             2.15.1
pyparsing            3.1.1
pyrsistent           0.19.3
python-dateutil      2.8.2
python-multipart     0.0.6
pytz                 2023.3.post1
PyYAML               6.0.1
regex                2023.6.3
requests             2.31.0
rich                 13.4.2
semantic-version     2.10.0
sentencepiece        0.1.99
sentry-sdk           1.26.0
setproctitle         1.3.2
setuptools           65.5.1
```

**Comment by zhanghui-china** [comment]
shortuuid            1.0.11
six                  1.16.0
smmap                5.0.0
sniffio              1.3.0
starlette            0.27.0
svgwrite             1.4.3
sympy                1.12
tiktoken             0.4.0
tokenizers           0.13.3
toolz                0.12.0
torch                2.0.0+nv23.5
torchaudio           2.0.2+31de77d    /home1/zhanghui/1006/audio
torchvision          0.15.2a0+fa99a53
tqdm                 4.65.0
transformers         4.28.0
typing_extensions    4.8.0
tzdata               2023.3
uc-micro-py          1.0.2
urllib3              2.0.6
uvicorn              0.22.0
wandb                0.15.4
wavedrom             2.0.3.post3
wcwidth              0.2.6
websockets           11.0.3
wheel                0.38.4
yarl                 1.9.2
zipp                 3.15.0

**Comment by CyberTimon** [comment]
`pip install torch_grammar` does fix the issue

**Comment by Moxie1776** [comment]
> `pip install torch_grammar` does fix the issue

that isn't fixing it for me

**Comment by thelabcat** [comment]
I got this error after pulling the repo, so I deleted the whole thing (except the models) and redownloaded. Now it's working, but I think I have lost GPU acceleration for some reason?

**Comment by zhanghui-china** [comment]
my env is aarch64
cannot find torch_grammar whl
can anyone tellme where the source code is ?

**Comment by thelabcat** [comment]
> Make sure your n-gpu-layers are set higher if you're using llama.cpp

Yep. No matter what I set it for now, it always behaves as zero. the link between the control and the loader is broken I think.
