### ISSUE TITLE
⚠️ Issue with grammar argument `grammar_string` in API

### ISSUE THREAD

**Issue by ibehnam** [oobabooga/text-generation-webui#4228]
### Describe the bug

When using the API feature, the `grammar_string` argument works the first time, that is, I can give it my own grammar text and the response from the API is valid against this grammar.

If you remove the `grammar_string` arg and make a new API call, the model generates a response that obviously doesn't have to be valid against the grammar you used to give it.

BUT, if you now enable the grammar arg once again, the model ignores that and keeps generating invalid responses.

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

I'm using the following config and model:

llama-2-7b.Q4_0.gguf$:
  loader: llama.cpp
  cpu: true
  threads: 16
  threads_batch: 16
  n_batch: 1024
  no_mmap: true
  mlock: true
  mul_mat_q: true
  n_gpu_layers: 99
  tensor_split: ''
  n_ctx: 1024
  llama_cpp_seed: 0.0
  compress_pos_emb: 1
  alpha_value: 1
  rope_freq_base: 0
  numa: true

### Logs

```shell
llama_print_timings:        load time =   541.58 ms
llama_print_timings:      sample time =    15.20 ms /    20 runs   (    0.76 ms per token,  1316.22 tokens per second)
llama_print_timings: prompt eval time =     0.00 ms /     1 tokens (    0.00 ms per token,      inf tokens per second)
llama_print_timings:        eval time =  1230.88 ms /    20 runs   (   61.54 ms per token,    16.25 tokens per second)
llama_print_timings:       total time =  1275.02 ms
Output generated in 1.28 seconds (15.67 tokens/s, 20 tokens, context 113, seed 998403250)
```

### System Info

```shell
macOS, M1 Pro
```

**Comment by Legoalda** [comment]
Same issue here with SillyTavern:
```
text-generation-webui  | ### Response (2 paragraphs, engaging, natural, authentic, descriptive, creative):
text-generation-webui  | Coding Sensei:
text-generation-webui  | --------------------
text-generation-webui  |
text-generation-webui  | Traceback (most recent call last):
text-generation-webui  |   File "/app/modules/callbacks.py", line 57, in gentask
text-generation-webui  |     ret = self.mfunc(callback=_callback, *args, **self.kwargs)
text-generation-webui  |   File "/app/modules/llamacpp_model.py", line 132, in generate
text-generation-webui  |     self.load_grammar(state['grammar_string'])
text-generation-webui  | KeyError: 'grammar_string'
text-generation-webui  | Output generated in 0.48 seconds (0.00 tokens/s, 0 tokens, context 820, seed 1757455808)
