### ISSUE TITLE
Add startup parameters --xformers --sdp-attention

### ISSUE THREAD

**Issue by prog-ape** [oobabooga/text-generation-webui#4251]
### Describe the bug

**pages load very slowly and sometimes become completely unresponsive**

Traceback (most recent call last):
  File "/home/textgen/text-generation-webui/modules/callbacks.py", line 56, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "/home/textgen/text-generation-webui/modules/text_generation.py", line 349, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1652, in generate
    return self.sample(
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2734, in sample
    outputs = self(
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1038, in forward
    outputs = self.model(
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 925, in forward
    layer_outputs = decoder_layer(
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 635, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: xformers_forward() got an unexpected keyword argument 'padding_mask'
Output generated in 0.34 seconds (0.00 tokens/s, 0 tokens, context 77, seed 2052260474)

Traceback (most recent call last):
  File "/home/textgen/text-generation-webui/modules/callbacks.py", line 56, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "/home/textgen/text-generation-webui/modules/text_generation.py", line 349, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1652, in generate
    return self.sample(
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2734, in sample
    outputs = self(
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1038, in forward
    outputs = self.model(
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 925, in forward
    layer_outputs = decoder_layer(
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 635, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: sdp_attention_forward() got an unexpected keyword argument 'padding_mask'
Output generated in 0.35 seconds (0.00 tokens/s, 0 tokens, context 82, seed 2052265065)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

![image](https://github.com/oobabooga/text-generation-webui/assets/22309691/ef5f94c3-998c-466d-aec9-d22a02d32c7f)

### Logs

```shell
Traceback (most recent call last):
  File "/home/textgen/text-generation-webui/modules/callbacks.py", line 56, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "/home/textgen/text-generation-webui/modules/text_generation.py", line 349, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1652, in generate
    return self.sample(
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2734, in sample
    outputs = self(
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1038, in forward
    outputs = self.model(
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 925, in forward
    layer_outputs = decoder_layer(
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 635, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: xformers_forward() got an unexpected keyword argument 'padding_mask'
Output generated in 0.34 seconds (0.00 tokens/s, 0 tokens, context 77, seed 2052260474)






Traceback (most recent call last):
  File "/home/textgen/text-generation-webui/modules/callbacks.py", line 56, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "/home/textgen/text-generation-webui/modules/text_generation.py", line 349, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1652, in generate
    return self.sample(
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2734, in sample
    outputs = self(
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1038, in forward
    outputs = self.model(
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 925, in forward
    layer_outputs = decoder_layer(
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 635, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/textgen/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: sdp_attention_forward() got an unexpected keyword argument 'padding_mask'
Output generated in 0.35 seconds (0.00 tokens/s, 0 tokens, context 82, seed 2052265065)
```

### System Info

```shell
ubuntu22.04

torch 2.0.1

xformers 0.0.21
```

**Comment by zhzLuke96** [comment]
same issiue

I can run GPTQ model and it works fine.

But the model loaded with transformers cannot be used (can be loaded normally, but cannot be used)

my env:
```
commit: 39f16ff83d3a948c36126b43f1ba86c7f85ff015
os: windows 10 x64
python: Python 3.10.7
torch: 2.1.0+cu121
xformers: 0.0.22.post4
model: codellama_CodeLlama-13b-hf
```

full error message:
```
2023-10-17 00:01:45 INFO:Loading codellama_CodeLlama-13b-hf...
2023-10-17 00:01:45 INFO:Using the following 4-bit params: {'load_in_4bit': True, 'bnb_4bit_compute_dtype': torch.bfloat16, 'bnb_4bit_quant_type': 'nf4', 'bnb_4bit_use_double_quant': False}
Loading checkpoint shards: 100%|█████████████████████████████████████████| 3/3 [00:21<00:00,  7.31s/it]
2023-10-17 00:02:08 INFO:Replaced attention with xformers_attention
2023-10-17 00:02:08 INFO:Loaded the model in 23.21 seconds.
Traceback (most recent call last):
  File "D:\workspace\text-generation-webui\modules\callbacks.py", line 56, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "D:\workspace\text-generation-webui\modules\text_generation.py", line 349, in generate_with_callback
    shared.model.generate(**kwargs)
  File "D:\workspace\text-generation-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\workspace\text-generation-webui\venv\lib\site-packages\transformers\generation\utils.py", line 1652, in generate
    return self.sample(
  File "D:\workspace\text-generation-webui\venv\lib\site-packages\transformers\generation\utils.py", line 2734, in sample
    outputs = self(
  File "D:\workspace\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\workspace\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\workspace\text-generation-webui\venv\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "D:\workspace\text-generation-webui\venv\lib\site-packages\transformers\models\llama\modeling_llama.py", line 1038, in forward
    outputs = self.model(
  File "D:\workspace\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\workspace\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\workspace\text-generation-webui\venv\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "D:\workspace\text-generation-webui\venv\lib\site-packages\transformers\models\llama\modeling_llama.py", line 925, in forward
    layer_outputs = decoder_layer(
  File "D:\workspace\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\workspace\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\workspace\text-generation-webui\venv\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "D:\workspace\text-generation-webui\venv\lib\site-packages\transformers\models\llama\modeling_llama.py", line 635, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "D:\workspace\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\workspace\text-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\workspace\text-generation-webui\venv\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
TypeError: xformers_forward() got an unexpected keyword argument 'padding_mask'
Output generated in 0.57 seconds (0.00 tokens/s, 0 tokens, context 4725, seed 1795046401)
```

**Comment by chymian** [comment]
+1
for
> TypeError: xformers_forward() got an unexpected keyword argument 'padding_mask'

```
Python                    3.10.13
torch                     2.1.0
transformers              4.34.1
xformers                  0.0.22.post3
model                     TheBloke/Phind-CodeLlama-34B-v2-GPTQ
cuda                      11.8
```
