### ISSUE TITLE
PermissionError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by LanceLake** [oobabooga/text-generation-webui#4252]
### Describe the bug

After it loads up the OpenAI URL, it crashes.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run the program.

### Logs

```shell
OpenAI compatible API ready at: OPENAI_API_BASE=http://0.0.0.0:5001/v1
Traceback (most recent call last):
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\gradio\networking.py", line 121, in start_server
    s.bind((LOCALHOST_NAME, server_port))
PermissionError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\text-generation-webui\server.py", line 229, in <module>
    create_interface()
  File "E:\text-generation-webui\server.py", line 145, in create_interface
    shared.gradio['interface'].launch(
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1748, in launch
    server_name, server_port, local_url, app, server = networking.start_server(
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\gradio\networking.py", line 124, in start_server
    raise OSError(
OSError: Port 7860 is in use. If a gradio.Blocks is running on the port, you can close() it or gradio.close_all().
Exception ignored in: <function LlamaCppModel.__del__ at 0x0000026B623D1510>
Traceback (most recent call last):
  File "E:\text-generation-webui\modules\llamacpp_model.py", line 50, in __del__
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\llama_cpp_cuda\llama.py", line 1611, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function Llama.__del__ at 0x0000026B623D0A60>
Traceback (most recent call last):
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\llama_cpp_cuda\llama.py", line 1611, in __del__
TypeError: 'NoneType' object is not callable
```

### System Info

```shell
Windows 10, Nvidia GPU.
```

**Comment by LanceLake** [comment]
Figure it out. Installing Linux for Windows messed something up. After uninstalling, it worked fine.

**Comment by bbecausereasonss** [comment]
Sheesh... I'm not going to uninstall Linux for windows just to fix this.
