### ISSUE TITLE
cannot load autoawq Model text-generation-webui1.7 how i fix this

### ISSUE THREAD

**Issue by Mr-small-2-six** [oobabooga/text-generation-webui#4253]
### Describe the bug

cannot load autoawq Model text-generation-webui1.7 how i fix this

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

when i try load awq Model

### Logs

```shell
Traceback (most recent call last):

File “D:\oobabooga_windows\text-generation-webui-1.7\text-generation-webui\modules\ui_model_menu.py”, line 201, in load_model_wrapper

shared.model, shared.tokenizer = load_model(shared.model_name, loader)
File “D:\oobabooga_windows\text-generation-webui-1.7\text-generation-webui\modules\[models.py](http://models.py/)”, line 79, in load_model

output = load_func_map[loader](model_name)
File “D:\oobabooga_windows\text-generation-webui-1.7\text-generation-webui\modules\[models.py](http://models.py/)”, line 281, in AutoAWQ_loader

from awq import AutoAWQForCausalLM
File “D:\oobabooga_windows\text-generation-webui-1.7\text-generation-webui\installer_files\env\lib\site-packages\awq_init_.py”, line 2, in

from awq.models.auto import AutoAWQForCausalLM
File “D:\oobabooga_windows\text-generation-webui-1.7\text-generation-webui\installer_files\env\lib\site-packages\awq\models_init_.py”, line 1, in

from .mpt import MptAWQForCausalLM
File “D:\oobabooga_windows\text-generation-webui-1.7\text-generation-webui\installer_files\env\lib\site-packages\awq\models\[mpt.py](http://mpt.py/)”, line 1, in

from .base import BaseAWQForCausalLM
File “D:\oobabooga_windows\text-generation-webui-1.7\text-generation-webui\installer_files\env\lib\site-packages\awq\models\[base.py](http://base.py/)”, line 11, in

from awq.quantize.quantizer import AwqQuantizer
File “D:\oobabooga_windows\text-generation-webui-1.7\text-generation-webui\installer_files\env\lib\site-packages\awq\quantize\[quantizer.py](http://quantizer.py/)”, line 11, in

from awq.modules.linear import WQLinear_GEMM, WQLinear_GEMV
File “D:\oobabooga_windows\text-generation-webui-1.7\text-generation-webui\installer_files\env\lib\site-packages\awq\modules\[linear.py](http://linear.py/)”, line 4, in

import awq_inference_engine  # with CUDA kernels
ImportError: DLL load failed while importing awq_inference_engine: 找不到指定的程序。
```

### System Info

```shell
cpu 13600k
gpu rtx 4080
ram 32gb
win11
```

**Comment by mr-september** [comment]
Same error. Adding my log since this thread is not turning up in english search engines currently with the crucial bit in chinese:

```
2023-10-11 12:39:36 INFO:Loading Mistral-7B-OpenOrca-AWQ...
2023-10-11 12:39:36 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "E:\text-generation-webui\modules\ui_model_menu.py", line 201, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "E:\text-generation-webui\modules\models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "E:\text-generation-webui\modules\models.py", line 281, in AutoAWQ_loader
    from awq import AutoAWQForCausalLM
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\awq\__init__.py", line 2, in <module>
    from awq.models.auto import AutoAWQForCausalLM
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\awq\models\__init__.py", line 1, in <module>
    from .mpt import MptAWQForCausalLM
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\awq\models\mpt.py", line 1, in <module>
    from .base import BaseAWQForCausalLM
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\awq\models\base.py", line 11, in <module>
    from awq.quantize.quantizer import AwqQuantizer
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\awq\quantize\quantizer.py", line 11, in <module>
    from awq.modules.linear import WQLinear_GEMM, WQLinear_GEMV
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\awq\modules\linear.py", line 4, in <module>
    import awq_inference_engine  # with CUDA kernels
ImportError: DLL load failed while importing awq_inference_engine: The specified procedure could not be found.
```

**Comment by xydreen** [comment]
Same issue here. More SEO relevancy:

```
2023-10-11 15:24:59 INFO:Loading TheBloke_UndiMix-v3-13B-AWQ...██████████████████████████████▉| 7.25G /7.25G  90.3MiB/s
2023-10-11 15:24:59 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "G:\TEXTGEN\text-generation-webui-main\modules\ui_model_menu.py", line 201, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "G:\TEXTGEN\text-generation-webui-main\modules\models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "G:\TEXTGEN\text-generation-webui-main\modules\models.py", line 282, in AutoAWQ_loader
    from awq import AutoAWQForCausalLM
  File "G:\TEXTGEN\text-generation-webui-main\installer_files\env\lib\site-packages\awq\__init__.py", line 2, in <module>
    from awq.models.auto import AutoAWQForCausalLM
  File "G:\TEXTGEN\text-generation-webui-main\installer_files\env\lib\site-packages\awq\models\__init__.py", line 1, in <module>
    from .mpt import MptAWQForCausalLM
  File "G:\TEXTGEN\text-generation-webui-main\installer_files\env\lib\site-packages\awq\models\mpt.py", line 1, in <module>
    from .base import BaseAWQForCausalLM
  File "G:\TEXTGEN\text-generation-webui-main\installer_files\env\lib\site-packages\awq\models\base.py", line 11, in <module>
    from awq.quantize.quantizer import AwqQuantizer
  File "G:\TEXTGEN\text-generation-webui-main\installer_files\env\lib\site-packages\awq\quantize\quantizer.py", line 11, in <module>
    from awq.modules.linear import WQLinear_GEMM, WQLinear_GEMV
  File "G:\TEXTGEN\text-generation-webui-main\installer_files\env\lib\site-packages\awq\modules\linear.py", line 4, in <module>
    import awq_inference_engine  # with CUDA kernels
ImportError: DLL load failed while importing awq_inference_engine: The specified procedure could not be found.
```

**Comment by xydreen** [comment]
Wonder if this has something to do with "CUDA Toolkit 11.8 and later." listed on AutoAWQ's Github page as a requirement.

**Comment by rengecky** [comment]
I have the same problem. And not just AutoAWQ; exllama and AutoGPTQ also give an error. Only exllama2 works.

**Comment by rengecky** [comment]
My issues:

AutoAWQ:

`2023-10-12 09:04:54 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "E:\text-generation-webui-main\modules\ui_model_menu.py", line 201, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "E:\text-generation-webui-main\modules\models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "E:\text-generation-webui-main\modules\models.py", line 282, in AutoAWQ_loader
    from awq import AutoAWQForCausalLM
  File "E:\text-generation-webui-main\installer_files\env\lib\site-packages\awq\__init__.py", line 2, in <module>
    from awq.models.auto import AutoAWQForCausalLM
  File "E:\text-generation-webui-main\installer_files\env\lib\site-packages\awq\models\__init__.py", line 1, in <module>
    from .mpt import MptAWQForCausalLM
  File "E:\text-generation-webui-main\installer_files\env\lib\site-packages\awq\models\mpt.py", line 1, in <module>
    from .base import BaseAWQForCausalLM
  File "E:\text-generation-webui-main\installer_files\env\lib\site-packages\awq\models\base.py", line 11, in <module>
    from awq.quantize.quantizer import AwqQuantizer
  File "E:\text-generation-webui-main\installer_files\env\lib\site-packages\awq\quantize\quantizer.py", line 11, in <module>
    from awq.modules.linear import WQLinear_GEMM, WQLinear_GEMV
  File "E:\text-generation-webui-main\installer_files\env\lib\site-packages\awq\modules\linear.py", line 4, in <module>
    import awq_inference_engine  # with CUDA kernels
ImportError: DLL load failed while importing awq_inference_engine: Не найдена указанная процедура.`

exllama:

`2023-10-12 09:09:16 WARNING:exllama module failed to import. Will attempt to import from repositories/.
Unable to find cl.exe; compilation will probably fail.
2023-10-12 09:09:16 ERROR:Could not find repositories/exllama. Please ensure that exllama (https://github.com/turboderp/exllama) is cloned inside repositories/ and is up to date.
2023-10-12 09:09:16 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "E:\text-generation-webui-main\modules\exllama.py", line 13, in <module>
    from exllama.generator import ExLlamaGenerator
  File "E:\text-generation-webui-main\installer_files\env\lib\site-packages\exllama\__init__.py", line 1, in <module>
    from . import cuda_ext, generator, model, tokenizer
  File "E:\text-generation-webui-main\installer_files\env\lib\site-packages\exllama\cuda_ext.py", line 9, in <module>
    import exllama_ext
ImportError: DLL load failed while importing exllama_ext: Не найдена указанная процедура.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\text-generation-webui-main\modules\ui_model_menu.py", line 201, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "E:\text-generation-webui-main\modules\models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "E:\text-generation-webui-main\modules\models.py", line 324, in ExLlama_loader
    from modules.exllama import ExllamaModel
  File "E:\text-generation-webui-main\modules\exllama.py", line 22, in <module>
    from generator import ExLlamaGenerator
  File "E:\text-generation-webui-main\repositories\exllama\generator.py", line 1, in <module>
    import cuda_ext
  File "E:\text-generation-webui-main\repositories\exllama\cuda_ext.py", line 43, in <module>
    exllama_ext = load(
  File "E:\text-generation-webui-main\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 1308, in load
    return _jit_compile(
  File "E:\text-generation-webui-main\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 1736, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "E:\text-generation-webui-main\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 2136, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: DLL load failed while importing exllama_ext: Не найден указанный модуль.`

AutoGPTQ:

`2023-10-12 09:11:55 INFO:The AutoGPTQ params are: {'model_basename': 'model', 'device': 'cuda:0', 'use_triton': False, 'inject_fused_attention': False, 'inject_fused_mlp': True, 'use_safetensors': True, 'trust_remote_code': False, 'max_memory': None, 'quantize_config': None, 'use_cuda_fp16': True, 'disable_exllama': False}
2023-10-12 09:12:01 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "E:\text-generation-webui-main\modules\ui_model_menu.py", line 201, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "E:\text-generation-webui-main\modules\models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "E:\text-generation-webui-main\modules\models.py", line 320, in AutoGPTQ_loader
    return modules.AutoGPTQ_loader.load_quantized(model_name)
  File "E:\text-generation-webui-main\modules\AutoGPTQ_loader.py", line 57, in load_quantized
    model = AutoGPTQForCausalLM.from_quantized(path_to_model, **params)
  File "E:\text-generation-webui-main\installer_files\env\lib\site-packages\auto_gptq\modeling\auto.py", line 108, in from_quantized
    return quant_func(
  File "E:\text-generation-webui-main\installer_files\env\lib\site-packages\auto_gptq\modeling\_base.py", line 875, in from_quantized
    accelerate.utils.modeling.load_checkpoint_in_model(
  File "E:\text-generation-webui-main\installer_files\env\lib\site-packages\accelerate\utils\modeling.py", line 1357, in load_checkpoint_in_model
    checkpoint = load_state_dict(checkpoint_file, device_map=device_map)
  File "E:\text-generation-webui-main\installer_files\env\lib\site-packages\accelerate\utils\modeling.py", line 1186, in load_state_dict
    return safe_load_file(checkpoint_file, device=list(device_map.values())[0])
  File "E:\text-generation-webui-main\installer_files\env\lib\site-packages\safetensors\torch.py", line 310, in load_file
    result[k] = f.get_tensor(k)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 34.00 MiB. GPU 0 has a total capacty of 12.00 GiB of which 9.40 GiB is free. Of the allocated memory 1.58 GiB is allocated by PyTorch, and 18.35 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by Apicio** [comment]
I reverted to this https://github.com/oobabooga/text-generation-webui/tree/06fff3b2e918f37e0c7d477d111a08d042e72968 in order to fix the problem.

**Comment by rengecky** [comment]
Interim Solution:

https://github.com/oobabooga/text-generation-webui/issues/4225#issuecomment-1753490625

**Comment by Mr-small-2-six** [comment]
Traceback (most recent call last):

File "D:\oobabooga_windows\text-generation-webui-1.7\text-generation-webui\modules\ui_model_menu.py", line 201, in load_model_wrapper


shared.model, shared.tokenizer = load_model(shared.model_name, loader)
File "D:\oobabooga_windows\text-generation-webui-1.7\text-generation-webui\modules\models.py", line 79, in load_model


output = load_func_map[loader](model_name)
File "D:\oobabooga_windows\text-generation-webui-1.7\text-generation-webui\modules\models.py", line 337, in ExLlamav2_loader


from modules.exllamav2 import Exllamav2Model
File "D:\oobabooga_windows\text-generation-webui-1.7\text-generation-webui\modules\exllamav2.py", line 5, in


from exllamav2 import (
File "D:\oobabooga_windows\text-generation-webui-1.7\text-generation-webui\installer_files\env\lib\site-packages\exllamav2_init_.py", line 3, in


from exllamav2.model import ExLlamaV2
File "D:\oobabooga_windows\text-generation-webui-1.7\text-generation-webui\installer_files\env\lib\site-packages\exllamav2\model.py", line 15, in


from exllamav2.attn import ExLlamaV2Attention
File "D:\oobabooga_windows\text-generation-webui-1.7\text-generation-webui\installer_files\env\lib\site-packages\exllamav2\attn.py", line 18, in


import flash_attn
File "D:\oobabooga_windows\text-generation-webui-1.7\text-generation-webui\installer_files\env\lib\site-packages\flash_attn_init_.py", line 3, in


from flash_attn.flash_attn_interface import (
File "D:\oobabooga_windows\text-generation-webui-1.7\text-generation-webui\installer_files\env\lib\site-packages\flash_attn\flash_attn_interface.py", line 8, in


import flash_attn_2_cuda as flash_attn_cuda
ImportError: DLL load failed while importing flash_attn_2_cuda: 找不到指定的模块。

when i install flash_attn-2.3.1.post1-cp310-cp310-win_amd64.whl this also get failed load DLL on 1.7，On 1.7 easy get DLL problem

**Comment by Dehypnotic** [comment]
My problem now with a newly updated text-generation-webui is that AWQ-models run well on the first generation, but they only generate one word from the second generation. I get the second, third word etc. by clicking continue. 

I installed a new webui from scratch and then got similar problems as mentioned here with several loaders.

**Comment by mykeehu** [comment]
Same problem here with latest commit.
I downloaded two AWQ files from TheBloke site, but neither of them load, I get this error:

```
Traceback (most recent call last):
File "I:\oobabooga_windows\text-generation-webui\modules\ui_model_menu.py", line 201, in load_model_wrapper
shared.model, shared.tokenizer = load_model(shared.model_name, loader)
File "I:\oobabooga_windows\text-generation-webui\modules\models.py", line 79, in load_model
output = load_func_map[loader](model_name)
File "I:\oobabooga_windows\text-generation-webui\modules\models.py", line 291, in AutoAWQ_loader
from awq import AutoAWQForCausalLM
File "I:\oobabooga_windows\text-generation-webui\installer_files\env\lib\site-packages\awq_init_.py", line 2, in
from awq.models.auto import AutoAWQForCausalLM
File "I:\oobabooga_windows\text-generation-webui\installer_files\env\lib\site-packages\awq\models_init_.py", line 1, in
from .mpt import MptAWQForCausalLM
File "I:\oobabooga_windows\text-generation-webui\installer_files\env\lib\site-packages\awq\models\mpt.py", line 1, in
from .base import BaseAWQForCausalLM
File "I:\oobabooga_windows\text-generation-webui\installer_files\env\lib\site-packages\awq\models\base.py", line 11, in
from awq.quantize.quantizer import AwqQuantizer
File "I:\oobabooga_windows\text-generation-webui\installer_files\env\lib\site-packages\awq\quantize\quantizer.py", line 11, in
from awq.modules.linear import WQLinear_GEMM, WQLinear_GEMV
File "I:\oobabooga_windows\text-generation-webui\installer_files\env\lib\site-packages\awq\modules\linear.py", line 4, in
import awq_inference_engine  # with CUDA kernels
ImportError: DLL load failed while importing awq_inference_engine: The specified procedure cannot be found.
```
Try this model:
https://huggingface.co/TheBloke/Airoboros-L2-13B-3.1.1-AWQ
or this:
https://huggingface.co/TheBloke/MLewdBoros-L2-13B-AWQ

Why can't I use the AWQ models?

**Comment by iChristGit** [comment]
I also have an issue with the latest commit 

2023-10-21 12:20:30 INFO:Loading TheBloke_MythoMax-L2-13B-GPTQ...
2023-10-21 12:20:30 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "D:\text-generation-webui\modules\ui_model_menu.py", line 201, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "D:\text-generation-webui\modules\models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "D:\text-generation-webui\modules\models.py", line 327, in AutoGPTQ_loader
    import modules.AutoGPTQ_loader
  File "D:\text-generation-webui\modules\AutoGPTQ_loader.py", line 3, in <module>
    from auto_gptq import AutoGPTQForCausalLM, BaseQuantizeConfig
  File "D:\text-generation-webui\installer_files\env\lib\site-packages\auto_gptq\__init__.py", line 2, in <module>
    from .modeling import BaseQuantizeConfig
  File "D:\text-generation-webui\installer_files\env\lib\site-packages\auto_gptq\modeling\__init__.py", line 2, in <module>
    from .auto import *
  File "D:\text-generation-webui\installer_files\env\lib\site-packages\auto_gptq\modeling\auto.py", line 11, in <module>
    from .llama import LlamaGPTQForCausalLM
  File "D:\text-generation-webui\installer_files\env\lib\site-packages\auto_gptq\modeling\llama.py", line 7, in <module>
    from ..nn_modules.fused_llama_attn import FusedLlamaAttentionForQuantizedModel
  File "D:\text-generation-webui\installer_files\env\lib\site-packages\auto_gptq\nn_modules\fused_llama_attn.py", line 5, in <module>
    from transformers.models.llama.modeling_llama import LlamaAttention, apply_rotary_pos_emb
  File "D:\text-generation-webui\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 45, in <module>
    from flash_attn import flash_attn_func, flash_attn_varlen_func
  File "D:\text-generation-webui\installer_files\env\lib\site-packages\flash_attn\__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "D:\text-generation-webui\installer_files\env\lib\site-packages\flash_attn\flash_attn_interface.py", line 8, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: DLL load failed while importing flash_attn_2_cuda: The specified module could not be found.

**Comment by YakuzaSuske** [comment]
![image](https://github.com/oobabooga/text-generation-webui/assets/63294141/2ae19857-57fc-44fc-88ef-dfa349ddeb90)

**Comment by darkanubis0100** [comment]
Same problem here... On Windows

**Comment by YakuzaSuske** [comment]
I talked with Jllll on discord and this is what he said.
![image](https://github.com/oobabooga/text-generation-webui/assets/63294141/31555235-43e5-4bd1-a53e-566c19177639)
So hopefully when it comes to the AWQ issue in the new update with Flash Attention 2, it will be fixed soon. 
But right now AWQ only works with CUDA 11.8, but Flash Attention 2 requires CUDA 12.1

So if you are doing a fresh install, you might need to choose between installing CUDA 11.8 for AWQ support or CUDA 12.1 for Flash Attention 2 support. Hope that helps.

**Comment by Mr-small-2-six** [comment]
> I talked with Jllll on discord and this is what he said. ![image](https://user-images.githubusercontent.com/63294141/277104443-31555235-43e5-4bd1-a53e-566c19177639.png) So hopefully when it comes to the AWQ issue in the new update with Flash Attention 2, it will be fixed soon. But right now AWQ only works with CUDA 11.8, but Flash Attention 2 requires CUDA 12.1
> 
> So if you are doing a fresh install, you might need to choose between installing CUDA 11.8 for AWQ support or CUDA 12.1 for Flash Attention 2 support. Hope that helps.

new branches fresh Installation Flash Attention 2  still not working 

https://github.com/oobabooga/text-generation-webui/issues/4342

I think it's a DLL reading problem, but I don't know how to coding so I can't find the error.

i using other branches exllamaV2 can work

**Comment by CamiloMM** [comment]
> AWQ only works with CUDA 11.8, but Flash Attention 2 requires CUDA 12.1

Could someone who has been doing Python for long enough explain how can this be normal? Isn't Python a JIT thing? Isn't CUDA just a bunch of kernel crunchers? Will Mojo finally save us all?

**Comment by casper-hansen** [comment]
I see there may be an issue here - adding CUDA 12.1 to the GitHub workflows should be easy. Fingers crossed, all CUDA kernels work on CUDA 12. I just need to figure out how to correctly tag the release on PyPi, but should be easy after inspecting how [AutoGPTQ did it](https://github.com/PanQiWei/AutoGPTQ/blob/main/setup.py#L72).

**Comment by ScottSump** [comment]
it says it's been updated, but when I uninstall and reinstall, I still get the same error.  exllamav2 works fine with 12.1, so it's not the CUDA.  I'm still guessing the issue is PEBCAC though.

**Comment by casper-hansen** [comment]
I have updated my build to using CUDA 12.1 and Torch 2.1.0 and I am looking to release the wheels for next release within a week.

**Comment by carl-shen** [comment]
Thanks for the good work, any update on a release time yet?

**Comment by casper-hansen** [comment]
0.1.6 has been released with CUDA 12.1.1 and Torch 2.1.0 on PyPi. Additionally, wheels with CUDA 11.8.0 and Torch 2.0.1 are available on the GitHub release if need be.

**Comment by odragora** [comment]
AutoAWQ still doesn't work on the most recent version.

`ImportError: DLL load failed while importing flash_attn_2_cuda: The specified procedure could not be found.`

**Comment by SDSSSpai** [comment]
I have the same problem all the time:( I hope it will be fixed

**Comment by casper-hansen** [comment]
This is an environment problem. I would encourage you to reset your environment and try to install AutoAWQ from the source and to use the latest version of various libraries.

**Comment by tommasofavaron1** [comment]
pip install https://github.com/casper-hansen/AutoAWQ/releases/download/v0.1.6/autoawq-0.1.6+cu118-cp310-cp310-linux_x86_64.whl

**Comment by Bluebang** [comment]
I have the same problem.

**Comment by linhcentrio** [comment]
git clone https://github.com/casper-hansen/AutoAWQ
cd AutoAWQ
pip install -e .

**Comment by MarioPL98** [comment]
> git clone https://github.com/casper-hansen/AutoAWQ cd AutoAWQ pip install -e .

This fixed everything. I just ran "cmd_windows" and typed in these commands.

**Comment by lscheder** [comment]
> > git clone https://github.com/casper-hansen/AutoAWQ cd AutoAWQ pip install -e .
> 
> This fixed everything. I just ran "cmd_windows" and typed in these commands.

THIS WORKED FOR ME THANK YOU

**Comment by DeadGrowl** [comment]
> > > git clone https://github.com/casper-hansen/AutoAWQ cd AutoAWQ pip install -e .
> > 
> > 
> > This fixed everything. I just ran "cmd_windows" and typed in these commands.
> 
> THIS WORKED FOR ME THANK YOU

Another confirmation from me, the only thing that worked for me, thank you very much.

**Comment by morganavr** [comment]
AutoAWQ needs triton package on windows too.

Download https://github.com/woct0rdho/triton-windows/releases/download/v3.0.0-windows.post3/triton-3.0.0-cp311-cp311-win_amd64.whl 

Install triton from the downloaded wheel: 
pip install triton-3.0.0-cp311-cp311-win_amd64.whl

**Comment by morganavr** [comment]
Model (Qwen2.5-32B-Instruct-AWQ) loads but during inference it throws an exceptions:

```
Running on local URL:  http://127.0.0.1:7860

16:16:11-285741 INFO     Loading "Qwen2.5-32B-Instruct-AWQ"
16:16:11-379742 INFO     TRANSFORMERS_PARAMS=
{'low_cpu_mem_usage': True, 'torch_dtype': torch.float16}

E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\transformers\generation\configuration_utils.py:638: UserWarning: `do_sample` is set to `False`. However, `min_p` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `min_p`.
  warnings.warn(
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 5/5 [00:00<00:00,  6.44it/s]
16:16:25-013327 INFO     Loaded "Qwen2.5-32B-Instruct-AWQ" in 13.72 seconds.
16:16:25-016354 INFO     LOADER: "Transformers"
16:16:25-018339 INFO     TRUNCATION LENGTH: 32768
16:16:25-019339 INFO     INSTRUCTION TEMPLATE: "Custom (obtained from model metadata)"
Traceback (most recent call last):
  File "E:\text_gen_ai\text-generation-webui\modules\callbacks.py", line 59, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\text_gen_ai\text-generation-webui\modules\text_generation.py", line 398, in generate_with_callback
    shared.model.generate(**kwargs)
  File "E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\transformers\generation\utils.py", line 2252, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\transformers\generation\utils.py", line 3251, in _sample
    outputs = self(**model_inputs, return_dict=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\transformers\models\qwen2\modeling_qwen2.py", line 1165, in forward
    outputs = self.model(
              ^^^^^^^^^^^
  File "E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\transformers\models\qwen2\modeling_qwen2.py", line 895, in forward
    layer_outputs = decoder_layer(
                    ^^^^^^^^^^^^^^
  File "E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\transformers\models\qwen2\modeling_qwen2.py", line 623, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
                                                          ^^^^^^^^^^^^^^^
  File "E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\transformers\models\qwen2\modeling_qwen2.py", line 501, in forward
    query_states = self.q_proj(hidden_states)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\text_gen_ai\text-generation-webui\autoawq\awq\modules\linear\gemm.py", line 271, in forward
    out = WQLinearMMFunction.apply(
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\torch\autograd\function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\text_gen_ai\text-generation-webui\autoawq\awq\modules\linear\gemm.py", line 66, in forward
    out = awq_gemm_triton(
          ^^^^^^^^^^^^^^^^
  File "e:\text_gen_ai\text-generation-webui\autoawq\awq\modules\triton\gemm.py", line 337, in awq_gemm_triton
    awq_gemm_kernel[grid](
  File "E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\triton\runtime\jit.py", line 345, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\triton\runtime\jit.py", line 607, in run
    device = driver.active.get_current_device()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\triton\runtime\driver.py", line 23, in __getattr__
    self._initialize_obj()
  File "E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\triton\runtime\driver.py", line 20, in _initialize_obj
    self._obj = self._init_fn()
                ^^^^^^^^^^^^^^^
  File "E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\triton\runtime\driver.py", line 9, in _create_driver
    return actives[0]()
           ^^^^^^^^^^^^
  File "E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\triton\backends\nvidia\driver.py", line 414, in __init__
    self.utils = CudaUtils()  # TODO: make static
                 ^^^^^^^^^^^
  File "E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\triton\backends\nvidia\driver.py", line 92, in __init__
    mod = compile_module_from_src(Path(os.path.join(dirname, "driver.c")).read_text(), "cuda_utils")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\text_gen_ai\text-generation-webui\installer_files\env\Lib\site-packages\triton\backends\nvidia\driver.py", line 74, in compile_module_from_src
    mod = importlib.util.module_from_spec(spec)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 573, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1233, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing cuda_utils: The specified module could not be found.
Output generated in 0.37 seconds (0.00 tokens/s, 0 tokens, context 103, seed 1785680412)
