### ISSUE TITLE
Issue With Update | EXL2 model fails to load using Exllamav2

### ISSUE THREAD

**Issue by CraserG1** [oobabooga/text-generation-webui#4259]
### Describe the bug

EXL2 model fails to load using Exllamav2.

I just updated oogaboogawebui and now it's failing. it was working fine before and now I don't know how to un-update it.

Works perfectly fine with Exllamav2_HF but not Exllamav2

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Im just loading spicyboros-c34b-2.2-4.0bpw-h6-exl2 with Exllamav2 on windows.

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/128838863/ec7c5d61-ce0f-466e-a831-7b56bc776e16)

### Logs

```shell
bin C:\TextGenWebui\text-generation-webui\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
2023-10-10 21:43:40 INFO:Loading the extension "gallery"...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
2023-10-10 21:44:43 INFO:Loading spicyboros-c34b-2.2-4.0bpw-h6-exl2...
2023-10-10 21:44:43 WARNING:You are running ExLlamaV2 without flash-attention. This will cause the VRAM usage to be a lot higher than it could be.
Try installing flash-attention following the instructions here: https://github.com/Dao-AILab/flash-attention#installation-and-features
2023-10-10 21:45:05 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "C:\TextGenWebui\text-generation-webui\modules\ui_model_menu.py", line 201, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "C:\TextGenWebui\text-generation-webui\modules\models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "C:\TextGenWebui\text-generation-webui\modules\models.py", line 339, in ExLlamav2_loader
    model, tokenizer = Exllamav2Model.from_pretrained(model_name)
  File "C:\TextGenWebui\text-generation-webui\modules\exllamav2.py", line 54, in from_pretrained
    tokenizer = ExLlamaV2Tokenizer(config)
  File "C:\TextGenWebui\text-generation-webui\installer_files\env\lib\site-packages\exllamav2\tokenizer.py", line 57, in __init__
    self.extended_piece_to_id = json.load(f)
  File "C:\TextGenWebui\text-generation-webui\installer_files\env\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\TextGenWebui\text-generation-webui\installer_files\env\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 8: character maps to <undefined>
```

### System Info

```shell
Windows
8600K
32gb of ram
RTX 3090
RTX 2060
```

**Comment by alfredwallace7** [comment]
same error on Windows RTX 2060

**Comment by defecat0r** [comment]
In case anybody else ends up here with the same issue, I had this problem with a couple of models and ended up figuring it out. The error occurred the instant a model was selected in the "Model" dropdown in the Model tab.
The problem in the models I was using ended up being In tokenizer_config.json, there were weird underscore characters: ▁ instead of _ in a couple of the strings (what is referenced in the above example at "position 8").
