### ISSUE TITLE
AttributeError: module 'bitsandbytes.nn' has no attribute 'Linear4bit'. Did you mean: 'Linear8bitLt'?

### ISSUE THREAD

**Issue by asad-ullah321** [oobabooga/text-generation-webui#4264]
### Describe the bug

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: 
https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
binary_path: C:\Users\Asadullah Sahu\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll        
CUDA SETUP: Loading binary C:\Users\Asadullah Sahu\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
Traceback (most recent call last):
  File "c:\Users\Asadullah Sahu\Desktop\model2\fine-tune.py", line 156, in <module>
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asadullah Sahu\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\models\auto\auto_factory.py", line 493, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asadullah Sahu\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\modeling_utils.py", line 2749, in from_pretrained  
    model = replace_with_bnb_linear(
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asadullah Sahu\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\utils\bitsandbytes.py", line 212, in replace_with_be-packages\transformers\utils\bitsandbytes.py", line 173, in _replace_with_bnb_linear
    _, has_been_replaced = _replace_with_bnb_linear(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asadullah Sahu\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\utils\bitsandbytes.py", line 173, in _replace_with_bnb_linear
    _, has_been_replaced = _replace_with_bnb_linear(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asadullah Sahu\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\utils\bitsandbytes.py", line 173, in _replace_with_bnb_linear
    _, has_been_replaced = _replace_with_bnb_linear(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 1 more time]
  File "C:\Users\Asadullah Sahu\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\utils\bitsandbytes.py", line 159, in _replace_with_bnb_linear
    model._modules[name] = bnb.nn.Linear4bit(
                           ^^^^^^^^^^^^^^^^^
AttributeError: module 'bitsandbytes.nn' has no attribute 'Linear4bit'. Did you mean: 'Linear8bitLt'?

Command Used for installations:
pip install accelerate==0.21.0 peft==0.4.0 bitsandbytes==0.40.2 transformers==4.31.0 trl==0.4.7
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Command Used for installations:
pip install accelerate==0.21.0 peft==0.4.0 bitsandbytes==0.40.2 transformers==4.31.0 trl==0.4.7
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

### Logs

```shell
binary_path: C:\Users\Asadullah Sahu\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll        
CUDA SETUP: Loading binary C:\Users\Asadullah Sahu\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
Traceback (most recent call last):
  File "c:\Users\Asadullah Sahu\Desktop\model2\fine-tune.py", line 156, in <module>
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asadullah Sahu\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\models\auto\auto_factory.py", line 493, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asadullah Sahu\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\modeling_utils.py", line 2749, in from_pretrained  
    model = replace_with_bnb_linear(
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asadullah Sahu\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\utils\bitsandbytes.py", line 212, in replace_with_be-packages\transformers\utils\bitsandbytes.py", line 173, in _replace_with_bnb_linear
    _, has_been_replaced = _replace_with_bnb_linear(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asadullah Sahu\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\utils\bitsandbytes.py", line 173, in _replace_with_bnb_linear
    _, has_been_replaced = _replace_with_bnb_linear(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asadullah Sahu\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\utils\bitsandbytes.py", line 173, in _replace_with_bnb_linear
    _, has_been_replaced = _replace_with_bnb_linear(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 1 more time]
  File "C:\Users\Asadullah Sahu\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\utils\bitsandbytes.py", line 159, in _replace_with_bnb_linear
    model._modules[name] = bnb.nn.Linear4bit(
                           ^^^^^^^^^^^^^^^^^
AttributeError: module 'bitsandbytes.nn' has no attribute 'Linear4bit'. Did you mean: 'Linear8bitLt'?
```

### System Info

```shell
Python 3.11
Cuda:11.8
GPU: mx150
OS: Windows
```

**Comment by AndreaRiboni** [comment]
i am encountering the same issue
