### ISSUE TITLE
Unable to load model - AttributeError: 'NoneType' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by gbajson-area22** [oobabooga/text-generation-webui#4265]
### Describe the bug

Whenever I try to choose a model application reports the following error:

```
Traceback (most recent call last):                                                                                                                                                                     
  File "/home/gbajson/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/queueing.py", line 406, in call_prediction                                                         
    output = await route_utils.call_process_api(                                                                                                                                                       
  File "/home/gbajson/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api                                                     
    output = await app.get_blocks().process_api(                                                                                                                                                       
  File "/home/gbajson/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1554, in process_api                                                              
    result = await self.call_function(                                                                                                                                                                 
  File "/home/gbajson/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1206, in call_function                                                            
    prediction = await utils.async_iteration(iterator)                                                                                                                                                 
  File "/home/gbajson/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 517, in async_iteration                                                            
    return await iterator.__anext__()                                                                                                                                                                  
  File "/home/gbajson/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 510, in __anext__                                                                  
    return await anyio.to_thread.run_sync(                                                                                                                                                             
  File "/home/gbajson/text-generation-webui/installer_files/env/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync                                                                 
    return await get_asynclib().run_sync_in_worker_thread(                                                                                                                                             
  File "/home/gbajson/text-generation-webui/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread                                      
    return await future                                                                                                                                                                                
  File "/home/gbajson/text-generation-webui/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run                                                            
    result = context.run(func, *args)                                                                                                                                                                  
  File "/home/gbajson/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 493, in run_sync_iterator_async                                                    
    return next(iterator)                                                                                                                                                                              
  File "/home/gbajson/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 647, in gen_wrapper                                                                
    yield from f(*args, **kwargs)                                                                                                                                                                      
  File "/home/gbajson/text-generation-webui/modules/ui_model_menu.py", line 222, in load_lora_wrapper                                                                                                  
    add_lora_to_model(selected_loras)                                                                                                                                                                  
  File "/home/gbajson/text-generation-webui/modules/LoRA.py", line 17, in add_lora_to_model                                                                                                            
    add_lora_transformers(lora_names)                                                                                                                                                                  
  File "/home/gbajson/text-generation-webui/modules/LoRA.py", line 130, in add_lora_transformers                                                                                                       
    params['dtype'] = shared.model.dtype                                                                                                                                                               
AttributeError: 'NoneType' object has no attribute 'dtype'


```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Start application using:
`./start_linux.sh --listen`
2. Open app page, navigate to "Download model or LoRA" and download "kstecenko/Tinny-LLAMA2-extractor".
3. Try to choose model.

### Logs

```shell
Traceback (most recent call last):                                                                                                                                                                     
  File "/home/gbajson/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/queueing.py", line 406, in call_prediction                                                         
    output = await route_utils.call_process_api(                                                                                                                                                       
  File "/home/gbajson/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api                                                     
    output = await app.get_blocks().process_api(                                                                                                                                                       
  File "/home/gbajson/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1554, in process_api                                                              
    result = await self.call_function(                                                                                                                                                                 
  File "/home/gbajson/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1206, in call_function                                                            
    prediction = await utils.async_iteration(iterator)                                                                                                                                                 
  File "/home/gbajson/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 517, in async_iteration                                                            
    return await iterator.__anext__()                                                                                                                                                                  
  File "/home/gbajson/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 510, in __anext__                                                                  
    return await anyio.to_thread.run_sync(                                                                                                                                                             
  File "/home/gbajson/text-generation-webui/installer_files/env/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync                                                                 
    return await get_asynclib().run_sync_in_worker_thread(                                                                                                                                             
  File "/home/gbajson/text-generation-webui/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread                                      
    return await future                                                                                                                                                                                
  File "/home/gbajson/text-generation-webui/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run                                                            
    result = context.run(func, *args)                                                                                                                                                                  
  File "/home/gbajson/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 493, in run_sync_iterator_async                                                    
    return next(iterator)                                                                                                                                                                              
  File "/home/gbajson/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 647, in gen_wrapper                                                                
    yield from f(*args, **kwargs)                                                                                                                                                                      
  File "/home/gbajson/text-generation-webui/modules/ui_model_menu.py", line 222, in load_lora_wrapper                                                                                                  
    add_lora_to_model(selected_loras)                                                                                                                                                                  
  File "/home/gbajson/text-generation-webui/modules/LoRA.py", line 17, in add_lora_to_model                                                                                                            
    add_lora_transformers(lora_names)                                                                                                                                                                  
  File "/home/gbajson/text-generation-webui/modules/LoRA.py", line 130, in add_lora_transformers                                                                                                       
    params['dtype'] = shared.model.dtype                                                                                                                                                               
AttributeError: 'NoneType' object has no attribute 'dtype'
```

### System Info

```shell
$ uname -a
Linux local-llm-us-2 5.10.0-23-cloud-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux

(base) gbajson@local-llm-us-2:~/text-generation-webui$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
(base) gbajson@local-llm-us-2:~/text-generation-webui$ nvidia-smi 
Wed Oct 11 12:02:53 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA L4                       On | 00000000:00:03.0 Off |                    0 |
| N/A   45C    P8               17W /  75W|      0MiB / 23034MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA L4                       On | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8               17W /  75W|      0MiB / 23034MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

**Comment by kzorin52** [comment]
same issue
