### ISSUE TITLE
Failed to load UI with gradio==3.47.*

### ISSUE THREAD

**Issue by Starlento** [oobabooga/text-generation-webui#4277]
### Describe the bug

commit: 51c043c6bef1380e121474ad73ea2a22f2fb5737
The gradio version is 3.47.*, and I failed to switch tab in UI. Totally cannot be used.
The error is:
```
Uncaught (in promise) TypeError: Cannot destructure property 'confidences' of '_' as it is undefined.
    at a.$$.update (StaticLabel.svelte:30:8)
    at ba (scheduler.js:115:6)
    at Co (scheduler.js:79:5) 
```
If I change to older commit: 0197fdddf106270ccf77fc2757d7bc53cc9729d4 with gradio==3.33 in requirements, it works well.
And the new commit cannot fit gradio==3.33

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

`python server.py`

### Logs

```shell
Uncaught (in promise) TypeError: Cannot destructure property 'confidences' of '_' as it is undefined.
    at a.$$.update (StaticLabel.svelte:30:8)
    at ba (scheduler.js:115:6)
    at Co (scheduler.js:79:5)
```

### System Info

```shell
windows
OR
wsl2
```

**Comment by Starlento** [comment]
This is caused by my settings.yml. Seems the format or something is out of date.
``` 
default_extensions: ["code_syntax_highlight"]
chat_default_extensions:
- code_syntax_highlight
code_syntax_highlight-activate: true
code_syntax_highlight-inline_highlight: true
code_syntax_highlight-performance_mode: true
code_syntax_highlight-copy_button: true

```
