### ISSUE TITLE
AI is not responding

### ISSUE THREAD

**Issue by rtgxjzgsryksryydtyrkry** [oobabooga/text-generation-webui#4281]
### Describe the bug

5600x
cpu mode (--cpu)
No matter what i type as promt, AI will newer answer :(

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I installed everything correctly, launched, it's just not working for me.

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/79521533/c697a9af-0b10-41c1-a530-0462cd2ed8bd)
![image](https://github.com/oobabooga/text-generation-webui/assets/79521533/c5fe2593-7d52-467c-8fc7-afbf85278697)

### Logs

```shell
Starting the web UI...
bin C:\LANA1\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so
C:\LANA1\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
function 'cadam32bit_grad_fp32' not found
2023-10-14 02:08:31 INFO:Loading the extension "gallery"...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
2023-10-14 02:08:46 INFO:Loading TheBloke_Wizard-Vicuna-7B-Uncensored-GPTQ_gptq-4bit-32g-actorder_True...
2023-10-14 02:08:46 INFO:The AutoGPTQ params are: {'model_basename': 'model', 'device': 'cpu', 'use_triton': False, 'inject_fused_attention': True, 'inject_fused_mlp': True, 'use_safetensors': True, 'trust_remote_code': False, 'max_memory': None, 'quantize_config': None, 'use_cuda_fp16': True, 'disable_exllama': True}
2023-10-14 02:08:46 WARNING:CUDA kernels for auto_gptq are not installed, this will result in very slow inference speed. This may because:
1. You disabled CUDA extensions compilation by setting BUILD_CUDA_EXT=0 when install auto_gptq from source.
2. You are using pytorch without CUDA support.
3. CUDA and nvcc are not installed in your device.
2023-10-14 02:08:46 WARNING:CUDA extension not installed.
2023-10-14 02:09:14 WARNING:skip module injection for FusedLlamaMLPForQuantizedModel not support integrate without triton yet.
2023-10-14 02:09:14 INFO:Loaded the model in 27.97 seconds.
Traceback (most recent call last):
  File "C:\LANA1\one-click-installers-oobabooga-windows\text-generation-webui\modules\callbacks.py", line 56, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "C:\LANA1\one-click-installers-oobabooga-windows\text-generation-webui\modules\text_generation.py", line 349, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\LANA1\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\auto_gptq\modeling\_base.py", line 442, in generate
    with torch.inference_mode(), torch.amp.autocast(device_type=self.device.type):
  File "C:\LANA1\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\auto_gptq\modeling\_base.py", line 431, in device
    device = [d for d in self.hf_device_map.values() if d not in {'cpu', 'disk'}][0]
IndexError: list index out of range
Output generated in 0.34 seconds (0.00 tokens/s, 0 tokens, context 61, seed 417370595)
```

### System Info

```shell
windows 10 64 pro
5600x
32gb ram
6900xt
```

**Comment by nbollman** [comment]
Having a 6900xt you do not want to install the CUDA version. CUDA is for nvidia cards. I dont have much experience working with AMD cards but I think you need to select the option for:
B) AMD (Linux/MacOS only. Requires ROCm SDK 5.6 on Linux)
and I think you are on Windows... so that option probably doesnt show... you would have to install WSL [(linux on windows)](https://learn.microsoft.com/en-us/windows/wsl/install) and run it through there, you should also run it with the ./wsl command once you are running wsl - default ubuntu should be fine

**Comment by rtgxjzgsryksryydtyrkry** [comment]
The problem is I need API and good perfomance, so running secound OS is kinda bad. And I installed cpu version, so this thing should basicly work.

**Comment by maddog7667** [comment]
you seem to be using the wrong type of model try a ggml model such as:
https://huggingface.co/TheBloke/vicuna-7B-v1.5-GGML/blob/main/vicuna-7b-v1.5.ggmlv3.q5_1.bin
