### ISSUE TITLE
Setup fails at cuda

### ISSUE THREAD

**Issue by thelabcat** [oobabooga/text-generation-webui#4282]
### Describe the bug

Downloaded the repository anew, and ran start_linux.sh, only to be eventually greeted with the error shown. Apparently, it could not find the cuda library.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Download the repository and just try to start it with the NVidia proprietary drivers on Fedora 38.

### Logs

```shell
libcusparse.so.11: cannot open shared object file: No such file or directory
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
Traceback (most recent call last):
  File "/home/wilbur/Downloads/text-generation-webui-1.7/server.py", line 30, in <module>
    from modules import (
  File "/home/wilbur/Downloads/text-generation-webui-1.7/modules/training.py", line 21, in <module>
    from peft import (
  File "/home/wilbur/Downloads/text-generation-webui-1.7/installer_files/env/lib/python3.10/site-packages/peft/__init__.py", line 22, in <module>
    from .auto import (
  File "/home/wilbur/Downloads/text-generation-webui-1.7/installer_files/env/lib/python3.10/site-packages/peft/auto.py", line 31, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
  File "/home/wilbur/Downloads/text-generation-webui-1.7/installer_files/env/lib/python3.10/site-packages/peft/mapping.py", line 23, in <module>
    from .peft_model import (
  File "/home/wilbur/Downloads/text-generation-webui-1.7/installer_files/env/lib/python3.10/site-packages/peft/peft_model.py", line 38, in <module>
    from .tuners import (
  File "/home/wilbur/Downloads/text-generation-webui-1.7/installer_files/env/lib/python3.10/site-packages/peft/tuners/__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel
  File "/home/wilbur/Downloads/text-generation-webui-1.7/installer_files/env/lib/python3.10/site-packages/peft/tuners/lora.py", line 45, in <module>
    import bitsandbytes as bnb
  File "/home/wilbur/Downloads/text-generation-webui-1.7/installer_files/env/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/wilbur/Downloads/text-generation-webui-1.7/installer_files/env/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/wilbur/Downloads/text-generation-webui-1.7/installer_files/env/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/wilbur/Downloads/text-generation-webui-1.7/installer_files/env/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/wilbur/Downloads/text-generation-webui-1.7/installer_files/env/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/wilbur/Downloads/text-generation-webui-1.7/installer_files/env/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```

### System Info

```shell
Fedora 38 x64
NVidia RTX 2060 SUPER
No collab notebook in use.
```

**Comment by nbollman** [comment]
How did you try to start it exactly start_linux.sh?
Debian, 
Did you install your build tools? sudo apt-get update; sudo apt-get install make build-essential
you will need to install latest nvidia drivers, and the NVIDIA Cuda developer toolkit
If Debian 12:
wget https://developer.download.nvidia.com/compute/cuda/12.2.2/local_installers/cuda-repo-debian11-12-2-local_12.2.2-535.104.05-1_amd64.deb
sudo dpkg -i cuda-repo-debian11-12-2-local_12.2.2-535.104.05-1_amd64.deb
sudo cp /var/cuda-repo-debian11-12-2-local/cuda-*-keyring.gpg /usr/share/keyrings/
sudo add-apt-repository contrib
sudo apt-get update
sudo apt-get -y install cuda

you might try throwing in a: pip install cuda-python

hope something helped.

**Comment by kbang-egs** [comment]
Also having this issue on ArchLinux. I see the issue listed [here](https://github.com/TimDettmers/bitsandbytes/issues/817) as well without any solution so far. CUDA is installed and older version still works.

**Comment by thelabcat** [comment]
> How did you try to start it exactly 
bash start_linux.sh
Same as when I've started it successfully before.
> Did you install your build tools? sudo apt-get update; sudo apt-get install make build-essential
>
> you will need to install latest nvidia drivers, and the NVIDIA Cuda developer toolkit
Not sure if I have all of that, but... why did it stop working without me uninstalling anything?
> If Debian 12:
I'm not on Debian, I'm on Fedora 38.
> you might try throwing in a: pip install cuda-python
I'll try that.
