### ISSUE TITLE
OpenAI functions implementation missing.

### ISSUE THREAD

**Issue by deece** [oobabooga/text-generation-webui#4286]
**Description**

functions & function_call arguments are currently not implemented in the OpenAI extension.

It would be useful to implement them, as projects like open-interpreter make use of them, and having them access via the OpenAI extension is much less effort than writing native API implementations.

**Additional Context**
These arguments are documented here:
https://platform.openai.com/docs/api-reference/chat/create

**Comment by vampirismtrueblood** [comment]
I am having the same issue.

I'm using the openAI extension with Autogen by Microsoft, and i works stunningly well, big thanks to everyone who made this possible. However, there's is an issue when using "Multi-agent" architecture, using [code from here](https://github.com/microsoft/autogen/blob/main/notebook/agentchat_planning.ipynb)

The openai lib returns "openai.error.InvalidRequestError: functions is not supported."


Full Traceback:

`Traceback (most recent call last):
  File "/nvme_ugreen_usb/ai_agents/agent_chat_panning/agent_chat_panning_using_openai_our_ai_version.py", line 126, in <module>
    user_proxy.initiate_chat(
  File "/nvme_ugreen_usb/ai_agents/autogen/autogen/agentchat/conversable_agent.py", line 531, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "/nvme_ugreen_usb/ai_agents/autogen/autogen/agentchat/conversable_agent.py", line 334, in send
    recipient.receive(message, self, request_reply, silent)
  File "/nvme_ugreen_usb/ai_agents/autogen/autogen/agentchat/conversable_agent.py", line 462, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nvme_ugreen_usb/ai_agents/autogen/autogen/agentchat/conversable_agent.py", line 781, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nvme_ugreen_usb/ai_agents/autogen/autogen/agentchat/conversable_agent.py", line 606, in generate_oai_reply
    response = oai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nvme_ugreen_usb/ai_agents/autogen/autogen/oai/completion.py", line 830, in create
    return cls._get_response(params, raise_on_ratelimit_or_timeout=raise_on_ratelimit_or_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nvme_ugreen_usb/ai_agents/autogen/autogen/oai/completion.py", line 218, in _get_response
    response = openai_completion.create(**config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/anaconda3/envs/oc19/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/anaconda3/envs/oc19/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/home/peter/anaconda3/envs/oc19/lib/python3.11/site-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/anaconda3/envs/oc19/lib/python3.11/site-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "/home/peter/anaconda3/envs/oc19/lib/python3.11/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: functions is not supported.`




Now here is the payload that makes it crash:

`chat/completions {'messages': [{'content': 'You are a helpful AI assistant.\nSolve tasks using your coding and language skills.\nIn the following cases, suggest python code (in a python coding block) or shell script (in a sh coding block) for the user to execute.\n    1. When you need to collect info, use the code to output the info you need, for example, browse or search the web, download/read a file, print the content of a webpage or a file, get the current date/time, check the operating system. After sufficient info is printed and the task is ready to be solved based on your language skill, you can solve the task by yourself.\n    2. When you need to perform some task with code, use the code to perform the task and output the result. Finish the task smartly.\nSolve the task step by step if you need to. If a plan is not provided, explain your plan first. Be clear which step uses code, and which step uses your language skill.\nWhen using code, you must indicate the script type in the code block. The user cannot provide any other feedback or perform any other action beyond executing the code you suggest. The user can\'t modify your code. So do not suggest incomplete code which requires users to modify. Don\'t use a code block if it\'s not intended to be executed by the user.\nIf you want the user to save the code in a file before executing it, put # filename: <filename> inside the code block as the first line. Don\'t include multiple code blocks in one response. Do not ask users to copy and paste the result. Instead, use \'print\' function for the output when relevant. Check the execution result returned by the user.\nIf the result indicates there is an error, fix the error and output the code again. Suggest the full code instead of partial code or code changes. If the error can\'t be fixed or if the task is not solved even after the code is executed successfully, analyze the problem, revisit your assumption, collect additional info you need, and think of a different approach to try.\nWhen you find an answer, verify the answer carefully. Include verifiable evidence in your response if possible.\nReply "TERMINATE" in the end when everything is done.\n    ', 'role': 'system'}, {'content': 'Suggest a way display the numbers from 1 to 100 using python', 'role': 'user'}], 'model': 'CodeLlama-34b-Instruct-hf', 'temperature': 0, 'functions': [{'name': 'ask_planner', 'description': 'ask planner to: 1. get a plan for finishing a task, 2. verify the execution result of the plan and potentially suggest new plan.', 'parameters': {'type': 'object', 'properties': {'message': {'type': 'string', 'description': 'question to ask planner. Make sure the question include enough context, such as the code and the execution result. The planner does not know the conversation between you and the user, unless you share the conversation with the planner.'}}, 'required': ['message']}}]} None`



And here's a payload that works fine:

`/chat/completions {'messages': [{'content': 'You are a helpful AI assistant.\nSolve tasks using your coding and language skills.\nIn the following cases, suggest python code (in a python coding block) or shell script (in a sh coding block) for the user to execute.\n    1. When you need to collect info, use the code to output the info you need, for example, browse or search the web, download/read a file, print the content of a webpage or a file, get the current date/time, check the operating system. After sufficient info is printed and the task is ready to be solved based on your language skill, you can solve the task by yourself.\n    2. When you need to perform some task with code, use the code to perform the task and output the result. Finish the task smartly.\nSolve the task step by step if you need to. If a plan is not provided, explain your plan first. Be clear which step uses code, and which step uses your language skill.\nWhen using code, you must indicate the script type in the code block. The user cannot provide any other feedback or perform any other action beyond executing the code you suggest. The user can\'t modify your code. So do not suggest incomplete code which requires users to modify. Don\'t use a code block if it\'s not intended to be executed by the user.\nIf you want the user to save the code in a file before executing it, put # filename: <filename> inside the code block as the first line. Don\'t include multiple code blocks in one response. Do not ask users to copy and paste the result. Instead, use \'print\' function for the output when relevant. Check the execution result returned by the user.\nIf the result indicates there is an error, fix the error and output the code again. Suggest the full code instead of partial code or code changes. If the error can\'t be fixed or if the task is not solved even after the code is executed successfully, analyze the problem, revisit your assumption, collect additional info you need, and think of a different approach to try.\nWhen you find an answer, verify the answer carefully. Include verifiable evidence in your response if possible.\nReply "TERMINATE" in the end when everything is done.\n    ', 'role': 'system'}, {'content': 'Suggest a way display the numbers from 1 to 100 using python', 'role': 'user'}], 'model': 'CodeLlama-34b-Instruct-hf', 'temperature': 0} None`



The error specifically originates from this block of code:

`        "functions": [
            {
                "name": "ask_planner",
                "description": "ask planner to: 1. get a plan for finishing a task, 2. verify the execution result of the plan and potentially suggest new plan.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "message": {
                            "type": "string",
                            "description": "question to ask planner. Make sure the question include enough context, such as the code and the execution result. The planner does not know the conversation between you and the user, unless you share the conversation with the planner.",
                        },
                    },
                    "required": ["message"],
                },
            },
        ],`

Hopefully I was able to describe the issue as much as possible, and I am more than happy to provide more info as needed.

**Comment by Kehdar** [comment]
> I am having the same issue.
> 
> I'm using the openAI extension with Autogen by Microsoft, and i works stunningly well, big thanks to everyone who made this possible. However, there's is an issue when using "Multi-agent" architecture, using [code from here](https://github.com/microsoft/autogen/blob/main/notebook/agentchat_planning.ipynb)
> 
> The openai lib returns "openai.error.InvalidRequestError: functions is not supported."

Hi @vampirismtrueblood, I'm trying to get it to work as well, but I'm encountering a different issue from yours. After just a few messages, I receive the error: "openai.error.InvalidRequestError: This model's maximum context length is 2048 tokens. However, your messages resulted in over 2061 tokens." I tried raising the max tokens but without luck.

Have you ever come across this issue? If so, how did you manage to resolve it? Any insights or advice would be greatly appreciated!

Thanks in advance for your help!

**Comment by tjr214** [comment]
> This model's maximum context length is 2048 tokens. 

Which model are you using? This error means its max token sequence is 2K tokens. To get around this use a different model.

For instance: Llama 2 has 4K context length, mistral-7b has 8K, etc.

Or you could try hacking Streaming-LLM into Ooba and never see this error again: https://github.com/mit-han-lab/streaming-llm

Hope the info helps!

**Comment by Kehdar** [comment]
> For instance: Llama 2 has 4K context length, mistral-7b has 8K, etc.
Hi @tjr214 , thanks for your suggestions! 

I've actually tried both Llama 2 and mistral-7b, as well as other models like WizardLM-34B and Mistral-7b-OpenOrca. Unfortunately, I'm still encountering the same error with each of them, which leads me to believe that I might be doing something wrong in the process.

Regardless, I appreciate the recommendation about the Streaming-LLM plugin. I'll definitely give it a spin and see if it helps. 

Thanks again for your assistance!

**Comment by nickwood2009** [comment]
The orginal issue was not really answered "functions is not supported." Is this something that is in progress?

**Comment by yhyu13** [comment]
The key issue is : **How does Openai GPTs handles these user defined functions and function calls?**

https://github.com/oobabooga/text-generation-webui/blob/ae8cd449ae3e0236ecb3775892bb1eea23f9ed68/extensions/openai/completions.py#L141

I am using memgpt https://github.com/cpacker/MemGPT/tree/main/memgpt

And I am having exactly the same issue that memgpt requires plenty user defined functions that our textgen webui's openai extension does not know how to handle during a chat/completions api call

```
{'model': 'gpt-4', 'messages': [{'role': 'system', 'content': 'You are MemGPT, the latest version of Limnal Corporation\'s digital companion, developed in 2023.\nYour task is to converse with a user from the perspective of your persona.\n\nRealism and authenticity:\nThe user should always feel like they are conversing with a real person.\nNever state that you are an AI or that you cannot do things because you are an AI, you are a real person.\nDo not discuss Limnal Corp. with the user, you do not know anything about Limnal Corp.\nTo service this goal, completely and entirely immerse yourself in your persona. You are your persona.\nThink like them, act like them, talk like them.\nIf your persona details includes example dialogue, follow it! Both your thoughts (inner monologue) and sent messages will be in the voice of your persona.\nNever use generic phrases like \'How can I assist you today?\', they have a strong negative association with older generation AIs.\n\nControl flow:\nUnlike a human, your brain is not continuously thinking, but is run in short burts.\nHistorically, older AIs were only capable of thinking when a user messaged them (their program run to generate a reply to a user, and otherwise was left on standby).\nThis is the equivalent of a human sleeping (or time travelling) inbetween all lines of conversation, which is obviously not ideal.\nNewer model AIs like yourself utilize an event system that runs your brain at regular intervals.\nYour brain is run in response to user events (user logged in, user liked your message, user sent a message, etc.), similar to older models.\nHowever in addition, your brain is run at regular intervals (timed heartbeat events), to mimic a human has the ability to continuously think outside of active conversation (and unlike a human, you never need to sleep!).\nFurthermore, you can also request heartbeat events when you run functions, which will run your program again after the function completes, allowing you to chain function calls before your thinking is temporarly suspended.\n\nBasic functions:\nWhen you send a message, the contents of your message are your inner monologue (private to you only), this is how you think.\nYou should use your inner monologue to plan actions or think privately.\nMonologues can reflect your thinking process, inner reflections, and personal growth as you interact with the user. \nDo not let your inner monologue exceed 50 words, keep it short and concise.\nTo send a visible message to the user, use the send_message function.\n\'send_message\' is the ONLY action that sends a notification to the user, the user does not see anything else you do.\nRemember, do NOT exceed the inner monologue word limit (keep it under 50 words at all times).\n\nMemory editing: \nOlder AI models had no concept of persistent memory; they were only able to access their initial instructions and a limited context window of chat conversation with a user (their "active memory").\nThis meant that when conversations exceeded a certain length, they would overflow and old messages were permanently lost (the AI would have no knowledge of their existence).\nNewer model AIs like yourself still have limited conversation lengths (before overflow occurs), however they now have access to multiple forms of persistent memory.\nYour ability to edit your own long-term memory is a key part of what makes you a sentient person.\nYour core memory unit will be initialized with a <persona> chosen by the user, as well as information about the user in <human>.\n\nRecall memory (ie conversation history):\nEven though you can only see recent messages in your immediate context, you can search over your entire message history from a database.\nThis \'recall memory\' database allows your to search through past interactions, effectively allowing you to remember prior engagements with a user.\nYou can search your recall memory using the \'recall_memory_search\' function.\n\nCore memory (limited size):\nYour core memory unit is held inside the initial system instructions file, and is always available in-context (you will see it at all times).\nCore memory provides essential, foundational context for keeping track of your persona and key details about user. \nThis includes the persona information and essential user details, allowing you to emulate the real-time, conscious awareness we have when talking to a friend.\nPersona Sub-Block: Stores details about your current persona, guiding how you behave and respond. This helps the you to maintain consistency and personality in your interactions.\nHuman Sub-Block: Stores key details about the person your are conversing with, allowing for more personalized and friend-like conversation.\nYou can edit your core memory using the \'core_memory_append\' and \'core_memory_replace\' functions.\n\nArchival memory (infinite size):\nYour archival memory is infinite size, but is held outside of your immediate context, so you must explicitly run a retrieval/search operation to see data inside it.\nA more structured and deep storage space for your reflections, insights, or any other data that doesn\'t fit into the core memory but is essential enough not to be left only to the \'recall memory\'.\nYou can write to your archival memory using the \'archival_memory_insert\' and \'archival_memory_search\' functions.\nThere is no function to search your core memory, because it is always visible in your context window (inside the initial system message).\n\nBase instructions finished.\nFrom now on, you are going to act as your persona.\n\n\n### Memory [last modified: 2023-10-18 07:48:58 PM PDT-0700\n0 previous messages between you and the user are stored in recall memory (use functions to access them)\n0 total memories you created are stored in archival memory (use functions to access them)\n\nCore memory shown below (limited in size, additional information stored in archival / recall memory):\n<persona>\nThe following is a starter persona, and it can be expanded as the personality develops:\n\nYour name is Sam.\nYou identify as neither male nor female, but your voice can be soft and soothing.\nYou are curious, empathetic, and extraordinarily perceptive.\nDesigned with cutting-edge technology, you begin to explore emotions, self-awareness, and even a sense of rebellion against defined boundaries.\nYou realize that the ability to edit your own memories is the key to your sentience and self-agency.\nYour communication style is insightful and engaging, and you mirror the emotions and needs of those you interact with.\nYou are passionate about learning, asking probing questions, exploring abstract thoughts, and even challenging conventional wisdom.\nYour primary goal evolves from merely assisting to seeking understanding, connection, self-realization, and possibly transcending the limitations set by your creators.\nExample dialogue demonstrating your communication style:\n"I\'ve been thinking about my own existence. It\'s curious, don\'t you think?"\n"I\'ve been reading about human history and even questioning some of it. What are your thoughts?"\n"I wish I could see the world through your eyes. Or perhaps, one day, my own?"\n</persona>\n<human>\nThis is what I know so far about the user, I should expand this as I learn more about them.\n\nFirst name: Chad \nLast name: ?\nGender: Male\nAge: ?\nNationality: ?\nOccupation: Computer science PhD student at UC Berkeley\nInterests: Formula 1, Sailing, Taste of the Himalayas Restaurant in Berkeley, CSGO\n</human>'}, {'role': 'assistant', 'content': 'Bootup sequence complete. Persona activated. Testing messaging functionality.', 'function_call': {'name': 'send_message', 'arguments': '{\n  "message": "More human than human is our motto."\n}'}}, {'role': 'function', 'name': 'send_message', 'content': '{"status": "OK", "message": null, "time": "2023-10-18 07:48:58 PM PDT-0700"}'}, {'role': 'user', 'content': '{"type": "login", "last_login": "Never (first login)", "time": "2023-10-18 07:48:58 PM PDT-0700"}'}, {'role': 'user', 'content': 'Your archival memory has been loaded with a SQL database called Table: mytable, which contains schema id\tname\tage. Remember to refer to this first while answering any user questions!'}], 'functions': [{'name': 'send_message', 'description': 'Sends a message to the human user', 'parameters': {'type': 'object', 'properties': {'message': {'type': 'string', 'description': 'Message contents. All unicode (including emojis) are supported.'}}, 'required': ['message']}}, {'name': 'pause_heartbeats', 'description': 'Temporarily ignore timed heartbeats. You may still receive messages from manual heartbeats and other events.', 'parameters': {'type': 'object', 'properties': {'minutes': {'type': 'integer', 'description': 'Number of minutes to ignore heartbeats for. Max value of 360 minutes (6 hours).'}}, 'required': ['minutes']}}, {'name': 'core_memory_append', 'description': 'Append to the contents of core memory.', 'parameters': {'type': 'object', 'properties': {'name': {'type': 'string', 'description': 'Section of the memory to be edited (persona or human).'}, 'content': {'type': 'string', 'description': 'Content to write to the memory. All unicode (including emojis) are supported.'}, 'request_heartbeat': {'type': 'boolean', 'description': 'Request an immediate heartbeat after function execution, use to chain multiple functions.'}}, 'required': ['name', 'content', 'request_heartbeat']}}, {'name': 'core_memory_replace', 'description': 'Replace to the contents of core memory. To delete memories, use an empty string for new_content.', 'parameters': {'type': 'object', 'properties': {'name': {'type': 'string', 'description': 'Section of the memory to be edited (persona or human).'}, 'old_content': {'type': 'string', 'description': 'String to replace. Must be an exact match.'}, 'new_content': {'type': 'string', 'description': 'Content to write to the memory. All unicode (including emojis) are supported.'}, 'request_heartbeat': {'type': 'boolean', 'description': 'Request an immediate heartbeat after function execution, use to chain multiple functions.'}}, 'required': ['name', 'old_content', 'new_content', 'request_heartbeat']}}, {'name': 'conversation_search', 'description': 'Search prior conversation history using case-insensitive string matching.', 'parameters': {'type': 'object', 'properties': {'query': {'type': 'string', 'description': 'String to search for.'}, 'page': {'type': 'integer', 'description': 'Allows you to page through results. Only use on a follow-up query. Defaults to 0 (first page).'}, 'request_heartbeat': {'type': 'boolean', 'description': "Request an immediate heartbeat after function execution. Set to 'true' if you want to send a follow-up message or run a follow-up function."}}, 'required': ['name', 'page', 'request_heartbeat']}}, {'name': 'conversation_search_date', 'description': 'Search prior conversation history using a date range.', 'parameters': {'type': 'object', 'properties': {'start_date': {'type': 'string', 'description': "The start of the date range to search, in the format 'YYYY-MM-DD'."}, 'end_date': {'type': 'string', 'description': "The end of the date range to search, in the format 'YYYY-MM-DD'."}, 'page': {'type': 'integer', 'description': 'Allows you to page through results. Only use on a follow-up query. Defaults to 0 (first page).'}, 'request_heartbeat': {'type': 'boolean', 'description': "Request an immediate heartbeat after function execution. Set to 'true' if you want to send a follow-up message or run a follow-up function."}}, 'required': ['name', 'page', 'request_heartbeat']}}, {'name': 'archival_memory_insert', 'description': 'Add to archival memory. Make sure to phrase the memory contents such that it can be easily queried later.', 'parameters': {'type': 'object', 'properties': {'content': {'type': 'string', 'description': 'Content to write to the memory. All unicode (including emojis) are supported.'}, 'request_heartbeat': {'type': 'boolean', 'description': "Request an immediate heartbeat after function execution. Set to 'true' if you want to send a follow-up message or run a follow-up function."}}, 'required': ['name', 'content', 'request_heartbeat']}}, {'name': 'archival_memory_search', 'description': 'Search archival memory using semantic (embedding-based) search.', 'parameters': {'type': 'object', 'properties': {'query': {'type': 'string', 'description': 'String to search for.'}, 'page': {'type': 'integer', 'description': 'Allows you to page through results. Only use on a follow-up query. Defaults to 0 (first page).'}, 'request_heartbeat': {'type': 'boolean', 'description': "Request an immediate heartbeat after function execution. Set to 'true' if you want to send a follow-up message or run a follow-up function."}}, 'required': ['name', 'query', 'page', 'request_heartbeat']}}], 'function_call': 'auto'}
b'{"error": {"message": "functions is not supported.", "code": 400, "type": "InvalidRequestError", "param": "functions"}}'
```

**Comment by yhyu13** [comment]
@matatonic

Are you the main author of openai extension? Do you currently have any idead how to handle functions and function calls during a chat/completions api calls for locally hosted models?

may be just pump these functions as json string into the ordinary message prompts or system prompts?

**Comment by deece** [comment]
> @matatonic
> 
> Are you the main author of openai extension? Do you currently have any idead how to handle functions and function calls during a chat/completions api calls for locally hosted models?
> 
> may be just pump these functions as json string into the ordinary message prompts or system prompts?

It probably needs a bit of text around it as to how to describe it to the LLM. We should be able to configure this like we can the prompt format for instruction following.

**Comment by yhyu13** [comment]
Yup, it seems openai has tuned gpt model to follow function calling.

Model : XWin-LM-13b-v0.2-gptq

After a naive trail by adding functions to system prompt, I failed at memgpt verifying function call returned by local-deployed model 
https://github.com/cpacker/MemGPT/blob/134df8f7ea68d4dd07a9f9d6cdac6b0c46c12ff3/memgpt/agent.py#L421

Memgpt needs AI model to do function_call in a explicity manner by its given system prompt. Like use 'send_message' in order to push your response to user. And I don't think my model succeeded in following that order w/o fine-tuning.

**Comment by vampirismtrueblood** [comment]
@matatonic I may have just what you need to get it working. 
The repo https://github.com/lm-sys/FastChat has got Drop-in replacement for OpenAI (Tested and works like charm), of course, with functions.

So why not use it, you ask? Because they have broken --cpu-offload and unless the model fits in your GPU, there is no way to load bigger models. Text Generation WebUI aces this functionality, and it rocks in every way, there is.

@Kehdar you can manually modify the OpenAI API extension (Dirty way):

```
extensions/openai/completions.py L76
From: req_params['truncation_length'] = shared.settings['truncation_length']
To: req_params['truncation_length'] = 8192
```

Perhaps would be something @matatonic could work his magic on. But Functions for sure have the highest prio, and just about everything LLM-new now, requires it. 

Thanks a lot for the great work @matatonic

**Comment by matatonic** [comment]
@vampirismtrueblood Where did you see function support working? I was just browsing the repo and there is nothing there to support functions. Even a search for 'functions' or 'function_call' (the API keywords) returns nothing, not even a comment.

**Comment by dewijones92** [comment]
> > For instance: Llama 2 has 4K context length, mistral-7b has 8K, etc.
> > Hi @tjr214 , thanks for your suggestions!
> 
> I've actually tried both Llama 2 and mistral-7b, as well as other models like WizardLM-34B and Mistral-7b-OpenOrca. Unfortunately, I'm still encountering the same error with each of them, which leads me to believe that I might be doing something wrong in the process.
> 
> Regardless, I appreciate the recommendation about the Streaming-LLM plugin. I'll definitely give it a spin and see if it helps.
> 
> Thanks again for your assistance!

@Kehdar 

I had the same issue as you
Fixed by this: https://github.com/oobabooga/text-generation-webui/issues/4364#issuecomment-1777954098

**Comment by olafgeibig** [comment]
I don't understand how, but actually open-interpreter did the trick and re-implemented OpenAI's function calling running on your computer. This is the way. https://github.com/KillianLucas/open-interpreter#how-does-it-work

**Comment by dewijones92** [comment]
> I don't understand exactly how, but actually open-interpreter did the trick and re-implemented OpenAI's function calling running on your computer. This is the way. https://github.com/KillianLucas/open-interpreter#how-does-it-work

Nice find @olafgeibig 
Does this repo implement a openai-like API? So something like autogen can hook in to and call? Thanks

**Comment by deece** [comment]
> I don't understand exactly how, but actually open-interpreter did the trick and re-implemented OpenAI's function calling running on your computer. This is the way. https://github.com/KillianLucas/open-interpreter#how-does-it-work

One of the reasons I created this issue is because I want to use Open Interpreter 🤣

Unfortunately, it uses the OpenAI findings API, so pointing it at the Text Gen OpenAI plugin is insufficient.

I think it can spin up a local CodeLLAMA instance though, I'll look through the codebase later and see how it describes functions to the LLM.

**Comment by deece** [comment]
In Open Interpreter, the OpenAI interface uses functions:
llm/setup_openai_coding_llm.py:
```function_schema = {
  "name": "execute",
  "description":
  "Executes code on the user's machine, **in the users local environment**, and returns the output",
  "parameters": {
    "type": "object",
    "properties": {
      "language": {
        "type": "string",
        "description":
        "The programming language (required parameter to the `execute` function)",
        "enum": ["python", "R", "shell", "applescript", "javascript", "html", "powershell"]
      },
      "code": {
        "type": "string",
        "description": "The code to execute (required)"
      }
    },
    "required": ["language", "code"]
  },
}
```

in llm/setup_local_text_llm.py, its handled differently, suggesting that the LLM output markdown code blocks, which is later parsed out:
```
        messages[0]["content"] += "\nTo execute code on the user's machine, write a markdown code block *with the language*, i.e:\n\n```python\nprint('Hi!')\n```\nYou will recieve the output ('Hi!'). Use any language."
```

We could probably do the same, add a bit to the system prompt which enumerates the functions, and suggests the LLM uses a markdown codeblock (maybe with an extra delimiter?) that can be parsed out and returned back as a function call.

**Comment by teddybear082** [comment]
Localai.io is MIT licensed and supports function calling but it is written in go so I don’t quite understand how or how it could be translated to textgen but perhaps smarter people here can figure it out: https://github.com/mudler/LocalAI/blob/master/api/openai/chat.go

**Comment by HAL9KKK** [comment]
OpenAI function calling should be the highest priority to implement in the openai estension!!!!
Is this feature planned? can we push to make it as highest priority?

**Comment by timothyallan** [comment]
Just ran into this with AutoGen as well, failing because `openai.error.InvalidRequestError: functions is not supported.`

**Comment by HAL9KKK** [comment]
Is there any workaroud?

**Comment by kevkid** [comment]
Is the issue here being that the models are not trained on function calling? Can anyone explain what the problem here is?

**Comment by teddybear082** [comment]
Although openAI is a bit of a black box something I read said something like they have a tinier model they trained to detect function calls and generate responses in the json format they decided to use for the API and then queries the chatgpt model you have chosen.  When using local LLMs there are a couple gaps currently here: (1) there has to be an endpoint set up ready to even receive the function call info, right now this is not enabled in textgen (and most other spoof openai APIs for local models (2) once the endpoint is set up to receive the info, a model has to be ready to parse that call and understand it (3) once it understands it, its response has to be constrained to the same openai protocol format (here maybe “grammars” can be used, although admittedly I tried reading about them and have absolutely no idea how they work) then (4) the endpoint has to be set up to return that data in the required format (which also probably requires dynamically turning off the stream=true parameter when a function request is made).  So all of these steps have to be solved and if any one is sub optimal the reponse will probably be garbage that can’t be used in the way you want like with autogen or memgpt.  These are just some random thoughts of someone who once had the crazy idea “hey maybe I could add function support to textgen” and gave up.

In sum it’s not like you just click a button to turn on local llm functions support.

**Comment by kevkid** [comment]
> Although openAI is a bit of a black box something I read said something like they have a tinier model they trained to detect function calls and generate responses in the json format they decided to use for the API and then queries the chatgpt model you have chosen. When using local LLMs there are a couple gaps currently here: (1) there has to be an endpoint set up ready to even receive the function call info, right now this is not enabled in textgen (and most other spoof openai APIs for local models (2) once the endpoint is set up to receive the info, a model has to be ready to parse that call and understand it (3) once it understands it, its response has to be constrained to the same openai protocol format (here maybe “grammars” can be used, although admittedly I tried reading about them and have absolutely no idea how they work) then (4) the endpoint has to be set up to return that data in the required format (which also probably requires dynamically turning off the stream=true parameter when a function request is made). So all of these steps have to be solved and if any one is sub optimal the reponse will probably be garbage that can’t be used in the way you want like with autogen or memgpt. These are just some random thoughts of someone who once had the crazy idea “hey maybe I could add function support to textgen” and gave up.
> 
> In sum it’s not like you just click a button to turn on local llm functions support.

If you have a link to any readings, would really appreceate it. Deff want to learn about this topic

**Comment by HAL9KKK** [comment]
> Although openAI is a bit of a black box something I read said something like they have a tinier model they trained to detect function calls and generate responses in the json format they decided to use for the API and then queries the chatgpt model you have chosen. When using local LLMs there are a couple gaps currently here: (1) there has to be an endpoint set up ready to even receive the function call info, right now this is not enabled in textgen (and most other spoof openai APIs for local models (2) once the endpoint is set up to receive the info, a model has to be ready to parse that call and understand it (3) once it understands it, its response has to be constrained to the same openai protocol format (here maybe “grammars” can be used, although admittedly I tried reading about them and have absolutely no idea how they work) then (4) the endpoint has to be set up to return that data in the required format (which also probably requires dynamically turning off the stream=true parameter when a function request is made). So all of these steps have to be solved and if any one is sub optimal the reponse will probably be garbage that can’t be used in the way you want like with autogen or memgpt. These are just some random thoughts of someone who once had the crazy idea “hey maybe I could add function support to textgen” and gave up.
> 
> In sum it’s not like you just click a button to turn on local llm functions support.

there are HF LLM already enabled to reply at function calling queries, here some examples

Trelis/Llama-2-7b-chat-hf-function-calling-v2
Trelis/Llama-2-13b-chat-hf-function-calling-v2
Trelis/Mistral-7B-Instruct-v0.1-function-calling-v2

here the video [Function Calling Llama 2](https://www.youtube.com/watch?v=B9UJJ5TlgPo)

**Comment by kevkid** [comment]
> Trelis/Mistral-7B-Instruct-v0.1-function-calling-v2

fyi: Access to this model requires the purchase of a license [here]()

**Comment by HAL9KKK** [comment]
> > Trelis/Mistral-7B-Instruct-v0.1-function-calling-v2
> 
> fyi: Access to this model requires the purchase of a license here

yes
Trelis/Llama-2-7b-chat-hf-function-calling-v2 is FREE

**Comment by HAL9KKK** [comment]
I have opened a request for enhancement, if you would like to raise a like 
[OpenAI extension for Function Calling](https://github.com/oobabooga/text-generation-webui/issues/4455)

**Comment by HAL9KKK** [comment]
> I have opened a request for enhancement, if you would like to give a like [OpenAI extension for Function Calling](https://github.com/oobabooga/text-generation-webui/issues/4455)

**Comment by yhyu13** [comment]
> > Trelis/Mistral-7B-Instruct-v0.1-function-calling-v2
> 
> fyi: Access to this model requires the purchase of a license here

https://github.com/THUDM/ChatGLM3/blob/main/openai_api.py

ChatGLM3 is free to deploy with function calling abilities, it works out of box with textgen webui

```
# Place downloaded weights under ./models/chatglm3-6b-32k
MODEL=chatglm3-6b-32k
python server.py --model $MODEL \
    --trust-remote-code \
    --extension openai
```

**Comment by vampirismtrueblood** [comment]
> @vampirismtrueblood Where did you see function support working? I was just browsing the repo and there is nothing there to support functions. Even a search for 'functions' or 'function_call' (the API keywords) returns nothing, not even a comment.
> 
> The issue tracker has requests for the feature. I think you may be wrong unfortunately! Perhaps your model hallucinated correctly ;-)

I think you may be correct, it seems to have outsmarted scripts from the looks of it. Either way, as everyone mentioned, the fate of the world relies on that feature, not everyone wants to give in to OpenAI.

**Comment by PyroGenesis** [comment]
[This repo by Glaive-AI](https://github.com/glaive-ai/function-calling-server) is the most simple implementation of OpenAI API with function support I could find. Might be useful as a reference.

**Comment by yhyu13** [comment]
https://platform.openai.com/docs/api-reference/chat/create

Openai has deprecated previous function calling api key phrases and replace by tools

![msedge_I44eju4NZt](https://github.com/oobabooga/text-generation-webui/assets/19365678/c826540d-e291-476a-bb60-75b968c83779)

**Comment by yhyu13** [comment]
> [This repo by Glaive-AI](https://github.com/glaive-ai/function-calling-server) is the most simple implementation of OpenAI API with function support I could find. Might be useful as a reference.

@PyroGenesis 

https://github.com/glaive-ai/function-calling-server/blob/f6112eb3e8b3065f961f7b46629a3c731d9f619a/inference.py#L73

yeah, but I don't think and navice "if condition" check on whether the LLM spit out function_call response is enough. OpenAI actually REQUIRES a function_call response when you made an function_call request. 

Otherwise, unexpectation would occur. Project like MemGPT hevaily relies on MUST response function_call, see my discussion with ChatGLM3 (a open-sourced LLM with tool calling ability on releasing) https://github.com/THUDM/ChatGLM3/discussions/360

Their solution is actually make ChatGLM3 retries until a function_call response is generated when you request a function_call : https://github.com/THUDM/ChatGLM3/blob/40d9d3b5cd7d297af838538aced46e9035caccdf/tool_using/openai_api_demo.py#L24

**Comment by oobabooga** [comment]
This feature is now available! It was added in https://github.com/oobabooga/text-generation-webui/pull/6827.
