### ISSUE TITLE
Exllama Stopped Working on Colab

### ISSUE THREAD

**Issue by chigkim** [oobabooga/text-generation-webui#4293]
### Describe the bug

Loading with Exllama or exllamav2 throws an error even though pip indicates they're installed.
Logs for both cases are included below.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
!git clone https://github.com/oobabooga/text-generation-webui
%cd /content/text-generation-webui
!pip install -r requirements.txt
!python server.py --share --model-dir models --model TheBloke_Llama-2-13B-chat-GPTQ --loader exllama
```

### Logs

```shell
Exllama:

2023-10-15 13:12:32 INFO:Loading TheBloke_Llama-2-13B-chat-GPTQ...
2023-10-15 13:12:33 WARNING:exllama module failed to import. Will attempt to import from repositories/.
2023-10-15 13:12:33 ERROR:Could not find repositories/exllama. Please ensure that exllama (https://github.com/turboderp/exllama) is cloned inside repositories/ and is up to date.
Traceback (most recent call last):
  File "/content/text-generation-webui/modules/exllama.py", line 13, in <module>
    from exllama.generator import ExLlamaGenerator
  File "/usr/local/lib/python3.10/dist-packages/exllama/__init__.py", line 1, in <module>
    from . import cuda_ext, generator, model, tokenizer
  File "/usr/local/lib/python3.10/dist-packages/exllama/cuda_ext.py", line 9, in <module>
    import exllama_ext
ImportError: /usr/local/lib/python3.10/dist-packages/exllama_ext.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/text-generation-webui/server.py", line 223, in <module>
    shared.model, shared.tokenizer = load_model(model_name)
  File "/content/text-generation-webui/modules/models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "/content/text-generation-webui/modules/models.py", line 324, in ExLlama_loader
    from modules.exllama import ExllamaModel
  File "/content/text-generation-webui/modules/exllama.py", line 22, in <module>
    from generator import ExLlamaGenerator
ModuleNotFoundError: No module named 'generator'

Exllamav2:

2023-10-15 13:14:50 INFO:Loading TheBloke_Llama-2-13B-chat-GPTQ...
Traceback (most recent call last):
  File "/content/text-generation-webui/server.py", line 223, in <module>
    shared.model, shared.tokenizer = load_model(model_name)
  File "/content/text-generation-webui/modules/models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "/content/text-generation-webui/modules/models.py", line 337, in ExLlamav2_loader
    from modules.exllamav2 import Exllamav2Model
  File "/content/text-generation-webui/modules/exllamav2.py", line 5, in <module>
    from exllamav2 import (
  File "/usr/local/lib/python3.10/dist-packages/exllamav2/__init__.py", line 3, in <module>
    from exllamav2.model import ExLlamaV2
  File "/usr/local/lib/python3.10/dist-packages/exllamav2/model.py", line 11, in <module>
    from exllamav2.cache import ExLlamaV2Cache
  File "/usr/local/lib/python3.10/dist-packages/exllamav2/cache.py", line 2, in <module>
    from exllamav2.ext import exllamav2_ext as ext_c
  File "/usr/local/lib/python3.10/dist-packages/exllamav2/ext.py", line 14, in <module>
    import exllamav2_ext
ImportError: /usr/local/lib/python3.10/dist-packages/exllamav2_ext.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi
```

### System Info

```shell
Colab
```

**Comment by chigkim** [comment]
This is what I found after the fresh setup on Colab:
```
!git clone https://github.com/oobabooga/text-generation-webui
%cd /content/text-generation-webui
!pip install -r requirements.txt
```

First, downgrade flash-attn.
`!pip install flash-attn==2.3`
At this point, auto-awq works.
Then for exllama to work, upgrade exllama==0.1.0.
`!pip install exllama==0.1.0`
For exllamav2 to work, uninstall exllamav2 0.0.6+cu118 and install exllamav2-0.0.6-py3-none-any.whl.
```
!pip uninstall -y exllamav2
!pip install exllamav2
```

**Comment by Matti-Koopa** [comment]
I have this issue in a docker container based on nvidia/cuda:12.0.0-runtime-ubuntu22.04

**Comment by dariuszsekula** [comment]
same for me problem with 12.1.1-devel-ubuntu22.04, so problem still persist. 
What I did was to remove exllamav2, flash-attention with my current cudatoolkit

**Comment by rafa-9** [comment]
> same for me problem with 12.1.1-devel-ubuntu22.04, so problem still persist. What I did was to remove exllamav2, flash-attention with my current cudatoolkit

@dariuszsekula can you please share the commands you ran to solve this issue on 12.1? Thanks!
