### ISSUE TITLE
Unable to load safetensors file

### ISSUE THREAD

**Issue by Trish2201** [oobabooga/text-generation-webui#4299]
### Describe the bug

I followed the instructions for running Llava on my M1 Mac.

All dependencies had been installed and I installed `wojtab_llava-13b-v0-4bit-128g` using `python download-model.py wojtab/llava-13b-v0-4bit-128g`.

When I run this command:

`python3 server.py --model wojtab_llava-13b-v0-4bit-128g --multimodal-pipeline llava-13b --api --extensions multimodal`

I get the following error:

> 2023-10-16 08:55:12 INFO:Loading wojtab_llava-13b-v0-4bit-128g...
> Traceback (most recent call last):
>   File "/Users/user_name/oogabooga/text-generation-webui/server.py", line 223, in <module>
>     shared.model, shared.tokenizer = load_model(model_name)
>                                      ^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/trishitasingh/oogabooga/text-generation-webui/modules/models.py", line 79, in load_model
>     output = load_func_map[loader](model_name)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/trishitasingh/oogabooga/text-generation-webui/modules/models.py", line 136, in huggingface_loader
>     model = LoaderClass.from_pretrained(path_to_model, **params)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 565, in from_pretrained
>     return model_class.from_pretrained(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2866, in from_pretrained
>     raise EnvironmentError(
> OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory models/wojtab_llava-13b-v0-4bit-128g.

Is there a way to convert the safe tensors file or a possible way to load this model?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Assuming dependencies have been installed

1. `python download-model.py wojtab/llava-13b-v0-4bit-128g`
2. `python3 server.py --model wojtab_llava-13b-v0-4bit-128g --multimodal-pipeline llava-13b --api --extensions multimodal`

### Logs

```shell
> 2023-10-16 08:55:12 INFO:Loading wojtab_llava-13b-v0-4bit-128g...
> Traceback (most recent call last):
>   File "/Users/user_name/oogabooga/text-generation-webui/server.py", line 223, in <module>
>     shared.model, shared.tokenizer = load_model(model_name)
>                                      ^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/trishitasingh/oogabooga/text-generation-webui/modules/models.py", line 79, in load_model
>     output = load_func_map[loader](model_name)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/trishitasingh/oogabooga/text-generation-webui/modules/models.py", line 136, in huggingface_loader
>     model = LoaderClass.from_pretrained(path_to_model, **params)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 565, in from_pretrained
>     return model_class.from_pretrained(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2866, in from_pretrained
>     raise EnvironmentError(
> OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory models/wojtab_llava-13b-v0-4bit-128g.
```

### System Info

```shell
macOS Monterey v12.6.2
Apple M1
Memory 16GB
```

**Comment by lamkhatinh** [comment]
Me too on windows 11

**Comment by syhya** [comment]
Same issue for ubuntu 22.04

**Comment by prestonzen** [comment]
Same on Debian 12 bookworm when using the start_linux.sh

**Comment by PolicarpoBS** [comment]
Same, Ubuntu 22.04

**Comment by Sourdface** [comment]
Also ubuntu 22.04

**Comment by able2608** [comment]
Apparently the problem exists because @Wojtab did not provide the configuration file in the respository or the model file. This cause the webui to think it is a `Transformer` model and tries to load it, which will definitely cause an error. 
To load the model properly, manually set the model loader to `AutoGPTQ`, set `wbits` to `4` and `groupsize` to `128`, load it, and you're good to go. Don't forget to change the instruction template to `LLaVA` after the model is loaded though.
