### ISSUE TITLE
Attempting to load GPTQ model on Apple Silicon 

### ISSUE THREAD

**Issue by Skylerwiernik** [oobabooga/text-generation-webui#4302]
### Describe the bug

I am trying to run this model on my M1 Max Mac Studio
https://huggingface.co/TheBloke/Mistral-7B-OpenOrca-GPTQ

It defaults to the AutoGPTQ model loader. Attempting to load the model produces the following

```
Traceback (most recent call last):

File "/Users/skyler/Desktop/text-generation-webui-main/modules/ui_model_menu.py", line 201, in load_model_wrapper

shared.model, shared.tokenizer = load_model(shared.model_name, loader)

File "/Users/skyler/Desktop/text-generation-webui-main/modules/models.py", line 79, in load_model

output = load_func_map[loader](model_name)

File "/Users/skyler/Desktop/text-generation-webui-main/modules/models.py", line 320, in AutoGPTQ_loader

import modules.AutoGPTQ_loader

File "/Users/skyler/Desktop/text-generation-webui-main/modules/AutoGPTQ_loader.py", line 3, in

from auto_gptq import AutoGPTQForCausalLM, BaseQuantizeConfig

ModuleNotFoundError: No module named 'auto_gptq'
```

I get similar errors for other model loaders. Using the transformer model loader produces this error

```
Traceback (most recent call last):

File "/Users/skyler/Desktop/text-generation-webui-main/modules/ui_model_menu.py", line 201, in load_model_wrapper

shared.model, shared.tokenizer = load_model(shared.model_name, loader)

File "/Users/skyler/Desktop/text-generation-webui-main/modules/models.py", line 79, in load_model

output = load_func_map[loader](model_name)

File "/Users/skyler/Desktop/text-generation-webui-main/modules/models.py", line 136, in huggingface_loader

model = LoaderClass.from_pretrained(path_to_model, **params)

File "/Users/skyler/Desktop/text-generation-webui-main/installer_files/env/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 565, in from_pretrained

return model_class.from_pretrained(

File "/Users/skyler/Desktop/text-generation-webui-main/installer_files/env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2702, in from_pretrained

raise RuntimeError("GPU is required to quantize or run quantize model.")

RuntimeError: GPU is required to quantize or run quantize model.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Download TheBloke/Mistral-7B-OpenOrca-GPTQ through the UI and attempt to load it on Apple Silicon 

### Logs

```shell
Traceback (most recent call last):

File "/Users/skyler/Desktop/text-generation-webui-main/modules/ui_model_menu.py", line 201, in load_model_wrapper

shared.model, shared.tokenizer = load_model(shared.model_name, loader)

File "/Users/skyler/Desktop/text-generation-webui-main/modules/models.py", line 79, in load_model

output = load_func_map[loader](model_name)

File "/Users/skyler/Desktop/text-generation-webui-main/modules/models.py", line 320, in AutoGPTQ_loader

import modules.AutoGPTQ_loader

File "/Users/skyler/Desktop/text-generation-webui-main/modules/AutoGPTQ_loader.py", line 3, in

from auto_gptq import AutoGPTQForCausalLM, BaseQuantizeConfig

ModuleNotFoundError: No module named 'auto_gptq'
```

### System Info

```shell
M1 Max Mac Studio
```

**Comment by borkeszmate** [comment]
same on Intel Macbook Pro

**Comment by yanbrod** [comment]
same here with M3
