### ISSUE TITLE
AWQ: RuntimeError: The size of tensor a (4096) must match the size of tensor b (1479) at non-singleton dimension 3

### ISSUE THREAD

**Issue by amantuer** [oobabooga/text-generation-webui#4312]
### Describe the bug

Any one know how to fix this? Running model TheBloke_genz-13B-v2-AWQ, set seq length 4096. After set the seq length as tensor b (1479) it went ok again but one message later it shows similiar error again. And the offical model card said max seq length is 4096, what's wrong? And I find out if I reload the model with 4096 len every time before sending the message it will be ok. I tried other AWQ model they have similiar issues.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

max seq length 4096

### Screenshot

<img width="862" alt="Screenshot 2023-10-18 091141" src="https://github.com/oobabooga/text-generation-webui/assets/30318164/196af19e-cef4-4092-89ab-90b08275e4e0">

### Logs

```shell
2023-10-18 09:44:35 INFO:Loaded the model in 14.82 seconds.
127.0.0.1 - - [18/Oct/2023 09:44:47] "GET /api/v1/model HTTP/1.1" 200 -
Output generated in 55.75 seconds (6.82 tokens/s, 380 tokens, context 2113, seed 3707677)
Traceback (most recent call last):
  File "F:\AI-chat\oobabooga_windows\text-generation-webui\modules\callbacks.py", line 56, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "F:\AI-chat\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 351, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Users\amant\.conda\envs\textgen\lib\site-packages\awq\models\base.py", line 36, in generate
    return self.model.generate(*args, **kwargs)
  File "C:\Users\amant\.conda\envs\textgen\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\amant\.conda\envs\textgen\lib\site-packages\transformers\generation\utils.py", line 1652, in generate
    return self.sample(
  File "C:\Users\amant\.conda\envs\textgen\lib\site-packages\transformers\generation\utils.py", line 2734, in sample
    outputs = self(
  File "C:\Users\amant\.conda\envs\textgen\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\amant\.conda\envs\textgen\lib\site-packages\transformers\models\llama\modeling_llama.py", line 1038, in forward
    outputs = self.model(
  File "C:\Users\amant\.conda\envs\textgen\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\amant\.conda\envs\textgen\lib\site-packages\transformers\models\llama\modeling_llama.py", line 925, in forward
    layer_outputs = decoder_layer(
  File "C:\Users\amant\.conda\envs\textgen\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\amant\.conda\envs\textgen\lib\site-packages\transformers\models\llama\modeling_llama.py", line 635, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "C:\Users\amant\.conda\envs\textgen\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\amant\.conda\envs\textgen\lib\site-packages\awq\modules\fused\attn.py", line 180, in forward
    scores = scores + attention_mask  # (bs, n_local_heads, slen, cache_len + slen)
RuntimeError: The size of tensor a (4096) must match the size of tensor b (2780) at non-singleton dimension 3
Output generated in 28.92 seconds (0.03 tokens/s, 1 tokens, context 2779, seed 781053343)
```

### System Info

```shell
RTX 3090
```

**Comment by SrVill** [comment]
A strange mistake. In general, although this is no longer required to run falcon, but I turned on the trust-remote-code flag and the error disappeared.

**Comment by amantuer** [comment]
@SrVill I turn on this no_inject_fused_attention tag and the error disappeared.
