### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by dewijones92** [oobabooga/text-generation-webui#4313]
### Describe the bug

Chat works find when I run with the default character. Problems occur when I duplicate that character and call it "dewi character"

when I try to chat to my own created character I get:
```

Traceback (most recent call last):
  File "/home/dewi/code/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/queueing.py", line 406, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/dewi/code/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/dewi/code/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1563, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/dewi/code/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1451, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/home/dewi/code/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/components/dropdown.py", line 241, in postprocess
    self._warn_if_invalid_choice(y)
  File "/home/dewi/code/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/components/dropdown.py", line 229, in _warn_if_invalid_choice
    if self.allow_custom_value or y in [value for _, value in self.choices]:
  File "/home/dewi/code/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/components/dropdown.py", line 229, in <listcomp>
    if self.allow_custom_value or y in [value for _, value in self.choices]:
ValueError: too many values to unpack (expected 2)
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Create new character
2. Try to chat with that new character

### Logs

```shell
llm_load_tensors: ggml ctx size =    0.09 MB
llm_load_tensors: mem required  = 7338.75 MB
...................................................................................................
llama_new_context_with_model: n_ctx      = 2048
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_new_context_with_model: kv self size  =  256.00 MB
llama_new_context_with_model: compute buffer total size = 161.88 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 |
2023-10-18 06:27:54 INFO:Loaded the model in 0.15 seconds.
2023-10-18 06:27:59 ERROR:It looks like no character is loaded. Please load one under Parameters > Character.
2023-10-18 06:28:04 ERROR:It looks like no character is loaded. Please load one under Parameters > Character.
Traceback (most recent call last):
  File "/home/dewi/code/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/queueing.py", line 406, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/dewi/code/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/dewi/code/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1554, in process_api
    result = await self.call_function(
  File "/home/dewi/code/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1192, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/dewi/code/text-generation-webui/installer_files/env/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/dewi/code/text-generation-webui/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/dewi/code/text-generation-webui/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/dewi/code/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 659, in wrapper
    response = f(*args, **kwargs)
  File "/home/dewi/code/text-generation-webui/modules/chat.py", line 305, in character_is_loaded
    raise ValueError
ValueError
Traceback (most recent call last):
  File "/home/dewi/code/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/queueing.py", line 406, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/dewi/code/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/dewi/code/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1563, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/dewi/code/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1451, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/home/dewi/code/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/components/dropdown.py", line 241, in postprocess
    self._warn_if_invalid_choice(y)
  File "/home/dewi/code/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/components/dropdown.py", line 229, in _warn_if_invalid_choice
    if self.allow_custom_value or y in [value for _, value in self.choices]:
  File "/home/dewi/code/text-generation-webui/installer_files/env/lib/python3.10/site-packages/gradio/components/dropdown.py", line 229, in <listcomp>
    if self.allow_custom_value or y in [value for _, value in self.choices]:
ValueError: too many values to unpack (expected 2)
```

### System Info

```shell
commit c0ffb77fd8471c1cade593879d17d2e817a1ed0b  
I have run  ./update_linux.sh
I am running with intel cpu - no gpu
llama.cpp backend
```

**Comment by dododream** [comment]
+1

**Comment by JohanAR** [comment]
I just got this after restarting the webui, was working fine a few seconds ago. Going to check if some settings file got corrupted, but the error message from gradio isn't very helpful.

**Comment by shaktisd** [comment]
Any update on this ? I am also getting the same error

**Comment by Elsayed91** [comment]
Just got this now as well.

**Comment by TheInvisibleMage** [comment]
+1 from me.
Some additional info:

- Seems to occur for me when I've swapped back and forth between characters a few times.
- I can confirm this still occurs on Dev branch, commit: d8279dc71083a1b150bde340f95d17b2cb1d6a75.

**Comment by zeta274** [comment]
+1. Seems impossible to solve at this point, but I didn't have this problem 4 days ago. I used the same setup as now, no changes. Now, it's broken, and it seems to have to do with characters, not the model. The model loads and appears fine.

**Comment by TheLounger** [comment]
This only seems to happen with the gallery, not when changing character through Parameters > Character.
Can you confirm?

**Comment by TheInvisibleMage** [comment]
In my case, I never use the gallery, always using the Parameters > Character process, and it still occurs on occasion.

**Comment by southhy** [comment]
Happens to me very frequently, using ubuntu 22.04. Lately it has been happening even when changing/saving instruction templates.

**Comment by melroy89** [comment]
Yup same problem, see also: https://github.com/oobabooga/text-generation-webui/issues/5118

**Comment by leighklotz** [comment]
Could this be related to a conflict in state between the server and multiple web clients? I've noticed glitches like this more when I swap between browser tabs or devices.
