### ISSUE TITLE
In the API, max_new_tokens = 4096 throws exception, null response

### ISSUE THREAD

**Issue by twiffy** [oobabooga/text-generation-webui#4318]
### Describe the bug

I can run the UI with max_new_tokens = 4096, or even 8192, with no problem. However when using the API, if I set max_new_tokens = 4096, I get a null return (code 200) with the exception included below in 'logs'. (However 2048 works fine.) Replicated on both zephyr-7b-alpha (unquantized) and WizardLM-1.0-Uncensored-Llama2-13B-GPTQ. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Take api-example.py in the codebase and set max_new_tokens = 4096

### Logs

```shell
C:\Users\Tristan\text-generation-webui\installer_files\env\lib\site-packages\transformers\generation\utils.py:1421: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use and modify the model generation configuration (see https://huggingface.co/docs/transformers/generation_strategies#default-text-generation-configuration )
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\Tristan\text-generation-webui\modules\text_generation.py", line 337, in generate_reply_HF
    output = shared.model.generate(**generate_params)[0]
  File "C:\Users\Tristan\text-generation-webui\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Tristan\text-generation-webui\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1486, in generate
    and torch.sum(inputs_tensor[:, -1] == generation_config.pad_token_id) > 0
IndexError: index -1 is out of bounds for dimension 1 with size 0
Output generated in 0.02 seconds (0.00 tokens/s, 0 tokens, context 0, seed 1260835198)
127.0.0.1 - - [18/Oct/2023 13:21:33] "POST /api/v1/generate HTTP/1.1" 200 -
```

### System Info

```shell
Win 11 OS, EVGA 3090
```

**Comment by afoland** [comment]
I see this exact same error (see below) but in a variety of circumstances.  I was trying to adjust the token lengths and cutoffs in my API calls to leave the maximum space possible for new tokens.  It fails for a variety of combinations of max_new_tokens and truncation_length.  The error occurs if truncation_limit is _too low_, or if max_new_tokens is _too high_.

If I set max_new_tokens to 1024, it fails reliably with this error with truncation_limit below 875, and works reliably above 925.  It fails sporadically in between.  

If I set truncation_limit to 2048, it fails reliably with this error with max_new_tokens set above 2200, and works reliably below 2100.  It fails sporadically in between.

In all cases I've tried obvious nearby powers of 2, and plus or minus one, and those do not form the boundary regions.

I'm running dual 3090's and neither are remotely close to hitting VRAM limits (13B models, load-in-8-bit or GPTQ)

I've gotten this both in Transformers (hf model) and AutoGPTQ (GPTQ model).  

My ooba version is from 5-OCT (date of last update_linux.sh)

From the model config.json:
{
...
"max_position_embeddings": 2048,
"max_sequence_length": 2048
...
}

OS: Linux Mint 21.1 x86_64 
CPU: Intel Xeon Gold 6238R (56) @ 4.000GHz
GPU: NVIDIA GeForce RTX 3090
GPU: NVIDIA GeForce RTX 3090
Memory: 9851MiB / 128194MiB

```
127.0.0.1 - - [05/Nov/2023 18:39:56] "POST /api/v1/generate HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/andrew/ooba_llama2/text-generation-webui/modules/text_generation.py", line 335, in generate_reply_HF
    output = shared.model.generate(**generate_params)[0]
  File "/home/andrew/ooba_llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/auto_gptq/modeling/_base.py", line 443, in generate
    return self.model.generate(**kwargs)
  File "/home/andrew/ooba_llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/andrew/ooba_llama2/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/generation/utils.py", line 1486, in generate
    and torch.sum(inputs_tensor[:, -1] == generation_config.pad_token_id) > 0
IndexError: index -1 is out of bounds for dimension 1 with size 0
Output generated in 0.00 seconds (0.00 tokens/s, 0 tokens, context 0, seed 1210662708)
```

**Comment by SicariusSicariiStuff** [comment]
I still have the same issue, no matter what arg I pass when using the API, the output is cut at about 2k tokens (i've set the max to 32k)

here's what I pass:
generation:
    max_tokens: 32768
    auto_max_new_tokens: 8192
    max_new_tokens: 8192
    max_tokens_second: 0
    preset: Debug-deterministic
    instruction_template: Llama-v3
    temperature: 1
    top_p: 1
    min_p: 0
    typical_p: 1
    repetition_penalty: 1
    #repetition_penalty_range: 1024
    no_repeat_ngram_size: 0
    presence_penalty: 0
    frequency_penalty: 0
    top_k: 1
    min_length: 0
    epsilon_cutoff: 0
    eta_cutoff: 0
    tfs: 1
    top_a: 0
    num_beams: 1
    penalty_alpha: 0
    length_penalty: 1
    early_stopping: False
    mirostat_mode: 0
    mirostat_tau: 5
    mirostat_eta: 0.1
    guidance_scale: 1
    seed: 42
    auto_max_new_tokens: False
    do_sample: False
    add_bos_token: True
    truncation_length: 32768
    ban_eos_token: False
    skip_special_tokens: True
    stopping_strings: []
    temperature_last: False
    dynamic_temperature: False
    dynatemp_low: 1
    dynatemp_high: 1
    dynatemp_exponent: 1
    smoothing_factor: 0
    smoothing_curve: 1
    repetition_penalty: 1
    presence_penalty: 0
    frequency_penalty: 0
    encoder_repetition_penalty: 1
    stream: false
    user_bio: ""
