### ISSUE TITLE
Loras no longer work in exllama 1

### ISSUE THREAD

**Issue by St33lMouse** [oobabooga/text-generation-webui#4329]
### Describe the bug

A couple weeks ago I was able to get loras attached and working to 70B models in exllama HF. Did an update today, can't get them attached. 

2 weeks ago the fix was: 

Use the llama-HF model loader and uncomment the following line in modules/exllama_hf.py:
config.fused_attn = False

But this is a new error, seems unrelated to the fused attention problem. Going with straight exllama (no HF) will permit the lora to attach, but leads to an error when you try inference.

RuntimeError: CUDA error: an illegal memory access was encountered

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

load a 70B in exllama HF, then try and attach a lora.

### Logs

```shell
File "/home/mouse/anaconda3/envs/textgen/lib/python3.10/site-packages/gradio/queueing.py", line 406, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/mouse/anaconda3/envs/textgen/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/mouse/anaconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1554, in process_api
    result = await self.call_function(
  File "/home/mouse/anaconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1206, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/mouse/anaconda3/envs/textgen/lib/python3.10/site-packages/gradio/utils.py", line 517, in async_iteration
    return await iterator.__anext__()
  File "/home/mouse/anaconda3/envs/textgen/lib/python3.10/site-packages/gradio/utils.py", line 510, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/mouse/anaconda3/envs/textgen/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/mouse/anaconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/mouse/anaconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/mouse/anaconda3/envs/textgen/lib/python3.10/site-packages/gradio/utils.py", line 493, in run_sync_iterator_async
    return next(iterator)
  File "/home/mouse/anaconda3/envs/textgen/lib/python3.10/site-packages/gradio/utils.py", line 647, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/home/mouse/text-generation-webui/modules/ui_model_menu.py", line 222, in load_lora_wrapper
    add_lora_to_model(selected_loras)
  File "/home/mouse/text-generation-webui/modules/LoRA.py", line 15, in add_lora_to_model
    add_lora_exllama(lora_names)
  File "/home/mouse/text-generation-webui/modules/LoRA.py", line 62, in add_lora_exllama
    lora = ExLlamaLora(shared.model.ex_model, str(lora_config_path), str(lora_adapter_path))
  File "/home/mouse/anaconda3/envs/textgen/lib/python3.10/site-packages/exllama/lora.py", line 84, in __init__
    assert isinstance(target_module, Ex4bitLinear)
AssertionError
```

### System Info

```shell
linux, 2 3090 cards
```

**Comment by Ph0rk0z** [comment]
Nothing changed in that regard. Try to rebuild exllama if you updated cuda or torch.

**Comment by St33lMouse** [comment]
Did a clean new install. python 3.10.9, cuda 12.1, torch 2.1. I get a similar error:

Exception in thread Thread-2 (gentask):
Traceback (most recent call last):
  File "/home/mouse/test/text-generation-webui/installer_files/env/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/mouse/test/text-generation-webui/installer_files/env/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mouse/test/text-generation-webui/modules/callbacks.py", line 63, in gentask
    clear_torch_cache()
  File "/home/mouse/test/text-generation-webui/modules/callbacks.py", line 95, in clear_torch_cache
    torch.cuda.empty_cache()
  File "/home/mouse/test/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/cuda/memory.py", line 159, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Have you tried attaching a lora to a 70b recently?

HOWEVER...Just tested exllama2 with my new clean install and...it worked! for the first time ever! And I was able to attach a lora and do a successful inference. So I'm good, but my report on the exllama1 lora problem still stands. Something changed somewhere and it no longer works, as I described.

**Comment by FartyPants** [comment]
So wait, you can now attach lora in exllama? Wowzers.
