### ISSUE TITLE
Tried all installation type all failed

### ISSUE THREAD

**Issue by mgiammarco** [oobabooga/text-generation-webui#4330]
Hi,
no matter what install type I choose at the end when I start the gui server I get:

> /home/mgiammarco/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
/home/mgiammarco/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/mgiammarco/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
2023-10-20 10:38:21 INFO:Loading the extension "gallery"...
Traceback (most recent call last):
  File "/home/mgiammarco/text-generation-webui/server.py", line 230, in <module>
    create_interface()
  File "/home/mgiammarco/text-generation-webui/server.py", line 117, in create_interface
    ui_model_menu.create_ui()  # Model tab
  File "/home/mgiammarco/text-generation-webui/modules/ui_model_menu.py", line 31, in create_ui
    total_mem.append(math.floor(torch.cuda.get_device_properties(i).total_memory / (1024 * 1024)))
  File "/home/mgiammarco/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/cuda/__init__.py", line 449, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "/home/mgiammarco/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/cuda/__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.

Error improve a bit if I try bitsandbytes-cuda117.
I have also tried recompiling bitsandbytes like in #1205 
I have ubuntu 23.04 and an RTX3090.
Thanks for help,
Mario

**Comment by triakshunn** [comment]
same error on ubuntu 20.04, when trying to run the installer


`./start_linux.sh 


*******************************************************************
* WARNING: You haven't downloaded any model yet.
* Once the web UI launches, head over to the "Model" tab and download one.
*******************************************************************


15:33:03-231286 INFO     Starting Text generation web UI                                                 
15:33:03-289807 INFO     Loading the extension "gallery"                                                 
╭────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────╮
│ /home/akshunntrivedi/text-generation-webui/server.py:254 in <module>                                  │
│                                                                                                       │
│   253         # Launch the web UI                                                                     │
│ ❱ 254         create_interface()                                                                      │
│   255         while True:                                                                             │
│                                                                                                       │
│ /home/akshunntrivedi/text-generation-webui/server.py:133 in create_interface                          │
│                                                                                                       │
│   132         ui_parameters.create_ui(shared.settings['preset'])  # Parameters tab                    │
│ ❱ 133         ui_model_menu.create_ui()  # Model tab                                                  │
│   134         training.create_ui()  # Training tab                                                    │
│                                                                                                       │
│ /home/akshunntrivedi/text-generation-webui/modules/ui_model_menu.py:36 in create_ui                   │
│                                                                                                       │
│    35         for i in range(torch.cuda.device_count()):                                              │
│ ❱  36             total_mem.append(math.floor(torch.cuda.get_device_properties(i).total_memory        │
│    37                                                                                                 │
│                                                                                                       │
│ /home/akshunntrivedi/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/cud │
│ a/__init__.py:449 in get_device_properties                                                            │
│                                                                                                       │
│    448     """                                                                                        │
│ ❱  449     _lazy_init()  # will define _get_device_properties                                         │
│    450     device = _get_device_index(device, optional=True)                                          │
│                                                                                                       │
│ /home/akshunntrivedi/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/cud │
│ a/__init__.py:298 in _lazy_init                                                                       │
│                                                                                                       │
│    297             os.environ["CUDA_MODULE_LOADING"] = "LAZY"                                         │
│ ❱  298         torch._C._cuda_init()                                                                  │
│    299         # Some of the queued calls may reentrantly call _lazy_init();                          │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing 
env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.
`

**Comment by koplenov** [comment]
Same error, for now I'm staying with the previous versions
Any news?
