### ISSUE TITLE
OSError: It looks like the config file at 'models\........bin' is not a valid JSON file.

### ISSUE THREAD

**Issue by shwang1a** [oobabooga/text-generation-webui#4331]
### Describe the bug

Load model Error

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load model

### Logs

```shell
2023-10-20 17:02:41 INFO:Loading Chinese-Llama-2-7b.ggmlv3.q5_0.bin...
2023-10-20 17:02:44 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "C:\Users\Tommyw\text-generation-webui-main\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 705, in _get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "C:\Users\Tommyw\text-generation-webui-main\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 800, in _dict_from_json_file
    text = reader.read()
  File "C:\Users\Tommyw\text-generation-webui-main\installer_files\env\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 28: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tommyw\text-generation-webui-main\modules\ui_model_menu.py", line 201, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "C:\Users\Tommyw\text-generation-webui-main\modules\models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "C:\Users\Tommyw\text-generation-webui-main\modules\models.py", line 123, in huggingface_loader
    config = AutoConfig.from_pretrained(path_to_model, trust_remote_code=params['trust_remote_code'])
  File "C:\Users\Tommyw\text-generation-webui-main\installer_files\env\lib\site-packages\transformers\models\auto\configuration_auto.py", line 1034, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\Tommyw\text-generation-webui-main\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 620, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\Tommyw\text-generation-webui-main\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 708, in _get_config_dict
    raise EnvironmentError(
OSError: It looks like the config file at 'models\Chinese-Llama-2-7b.ggmlv3.q5_0.bin' is not a valid JSON file.
```

### System Info

```shell
Windows 10, NVidia
```

**Comment by strikaco** [comment]
> Chinese-Llama-2-7b.ggmlv3.q5_0.bin

See if you can find a GGUF version of this file. GGML isn't supported anymore (none of mine work on ooba), so even if you solved this problem I think you'll just encounter another.

If you can't/won't download another 5GB blob, use koboldcpp as your client instead. It's only 200MB and still supports GGML.

**Comment by skhotdotcom** [comment]
I'm having this challenge too while running a GGUF running Linux with GPUs (NVIDIA GTX 1080 Ti):

```
2023-10-27 02:33:00 INFO:Loading dolphin-2.1-mistral-7b.Q4_0.gguf...
2023-10-27 02:33:13 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/home/aiadmin/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/configuration_utils.py", line 705, in _get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aiadmin/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/configuration_utils.py", line 800, in _dict_from_json_file
    text = reader.read()
           ^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 166: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aiadmin/text-generation-webui/modules/ui_model_menu.py", line 201, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aiadmin/text-generation-webui/modules/models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aiadmin/text-generation-webui/modules/models.py", line 123, in huggingface_loader
    config = AutoConfig.from_pretrained(path_to_model, trust_remote_code=params['trust_remote_code'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aiadmin/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/models/auto/configuration_auto.py", line 1034, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aiadmin/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/configuration_utils.py", line 620, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aiadmin/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/configuration_utils.py", line 708, in _get_config_dict
    raise EnvironmentError(
OSError: It looks like the config file at 'models/dolphin-2.1-mistral-7b.Q4_0.gguf' is not a valid JSON file.
```

I'm happy to try some troubleshooting to figure this out. :)

**Comment by skhotdotcom** [comment]
#4381 mentions this same error but was closed without a solution.

**Comment by fuomag9** [comment]
This issue is not stale, I cannot load https://huggingface.co/TheBloke/Nous-Capybara-34B-GGUF/blob/main/nous-capybara-34b.Q3_K_M.gguf as well 

![image](https://github.com/oobabooga/text-generation-webui/assets/1580624/ab45556e-53b9-4605-b5d0-1bec880c5949)

**Comment by marauder37** [comment]
You need to load gguf models with the llama.cpp loader. From the traceback, it looks like oobabooa tried to use the Transformers loader. 

I think there is a problem with the "Model Loader" dropdown in the UI. Check that Model Loader is set to llama.cpp. If it already is, jiggle it a bit: change it to use some other loader, try to reload the model, let it break, then change it back to llama.cpp and reload the model. This fixed it for me.

**Comment by cooperdk** [comment]
> You need to load gguf models with the llama.cpp loader. From the traceback, it looks like oobabooa tried to use the Transformers loader.
> 
> I think there is a problem with the "Model Loader" dropdown in the UI. Check that Model Loader is set to llama.cpp. If it already is, jiggle it a bit: change it to use some other loader, try to reload the model, let it break, then change it back to llama.cpp and reload the model. This fixed it for me.

That makes ooba unusable. LM Studio will load llama.cpp files and is better at handling them. The reason for using ooba is exllama.
There is no good explanation for the lack of support for this.
