### ISSUE TITLE
Multimodal does not work

### ISSUE THREAD

**Issue by SrVill** [oobabooga/text-generation-webui#4333]
### Describe the bug

In the last commit 32984ea, the multimodal extension does not work. Webui stops working.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Enable multimodal on the session page

### Logs

```shell
Traceback (most recent call last):
  File "E:\text-generation-webui-main\server.py", line 238, in <module>
    create_interface()
  File "E:\text-generation-webui-main\server.py", line 141, in create_interface
    extensions_module.create_extensions_block()  # Extensions block
  File "E:\text-generation-webui-main\modules\extensions.py", line 192, in create_extensions_block
    extension.ui()
  File "E:\text-generation-webui-main\extensions\multimodal\script.py", line 99, in ui
    multimodal_embedder = MultimodalEmbedder(params)
  File "E:\text-generation-webui-main\extensions\multimodal\multimodal_embedder.py", line 27, in __init__
    pipeline, source = load_pipeline(params)
  File "E:\text-generation-webui-main\extensions\multimodal\pipeline_loader.py", line 34, in load_pipeline
    model_name = shared.args.model.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

### System Info

```shell
windows 10
rtx3060
```

**Comment by chielteuben** [comment]
Add the --multimodal-pipeline parameter to fix this.

e.g. server.py --multimodal-pipeline llava-v1.5-13b

**Comment by 2Chair** [comment]
@chielteuben @SrVill @luiscosio @kelvie @cyberfox still a relevant bug

**Comment by jesulo** [comment]
Hi, this error is for last transformers version? ..  ValueError: Unrecognized configuration class <class 'transformers.models.llava.configuration_llava.LlavaConfig'> for this kind of AutoModel: AutoModelForCausalLM.

Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, LlamaConfig, CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, FalconConfig, FuyuConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MistralConfig, MixtralConfig, MptConfig, MusicgenConfig, MvpConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PersimmonConfig, PhiConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, TransfoXLConfig, TrOCRConfig, WhisperConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.

**Comment by Victorivus** [comment]
Check PR https://github.com/oobabooga/text-generation-webui/pull/5038 there is a way to solving this modifying `modules/models.py`, probably will be fixed soon

**Comment by oobabooga** [comment]
Multimodal models are now supported through the llama.cpp and ExLlamaV3 loaders, both in the UI and the API. A tutorial can be found here:

https://github.com/oobabooga/text-generation-webui/wiki/Multimodal-Tutorial

<img width="600" height="884" alt="print6" src="https://github.com/user-attachments/assets/be4a8f4d-619d-49e6-86f5-012d89f8db8d" />
