### ISSUE TITLE
AutoAWQ load error

### ISSUE THREAD

**Issue by mykeehu** [oobabooga/text-generation-webui#4337]
### Describe the bug

I downloaded two AWQ files from TheBloke site, but neither of them load, I get this error:

```
Traceback (most recent call last):
File "I:\oobabooga_windows\text-generation-webui\modules\ui_model_menu.py", line 201, in load_model_wrapper
shared.model, shared.tokenizer = load_model(shared.model_name, loader)
File "I:\oobabooga_windows\text-generation-webui\modules\models.py", line 79, in load_model
output = load_func_map[loader](model_name)
File "I:\oobabooga_windows\text-generation-webui\modules\models.py", line 291, in AutoAWQ_loader
from awq import AutoAWQForCausalLM
File "I:\oobabooga_windows\text-generation-webui\installer_files\env\lib\site-packages\awq_init_.py", line 2, in
from awq.models.auto import AutoAWQForCausalLM
File "I:\oobabooga_windows\text-generation-webui\installer_files\env\lib\site-packages\awq\models_init_.py", line 1, in
from .mpt import MptAWQForCausalLM
File "I:\oobabooga_windows\text-generation-webui\installer_files\env\lib\site-packages\awq\models\mpt.py", line 1, in
from .base import BaseAWQForCausalLM
File "I:\oobabooga_windows\text-generation-webui\installer_files\env\lib\site-packages\awq\models\base.py", line 11, in
from awq.quantize.quantizer import AwqQuantizer
File "I:\oobabooga_windows\text-generation-webui\installer_files\env\lib\site-packages\awq\quantize\quantizer.py", line 11, in
from awq.modules.linear import WQLinear_GEMM, WQLinear_GEMV
File "I:\oobabooga_windows\text-generation-webui\installer_files\env\lib\site-packages\awq\modules\linear.py", line 4, in
import awq_inference_engine  # with CUDA kernels
ImportError: DLL load failed while importing awq_inference_engine: The specified procedure cannot be found.
```
Try this model:
https://huggingface.co/TheBloke/Airoboros-L2-13B-3.1.1-AWQ
or this:
https://huggingface.co/TheBloke/MLewdBoros-L2-13B-AWQ

Why can't I use the AWQ models?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I just switched to the AWQ model and loaded it.

### Logs

```shell
-
```

### System Info

```shell
i9-13900K
64 GB RAM
RTX 3060 12GB
Windows 10 64-bit
```

**Comment by mykeehu** [comment]
[Duplicated](https://github.com/oobabooga/text-generation-webui/issues/4253#issuecomment-1773448450)
