### ISSUE TITLE
branches 3345da2   flash-attention 2 for windows error 

### ISSUE THREAD

**Issue by Mr-small-2-six** [oobabooga/text-generation-webui#4342]
### Describe the bug

fail to load ExLlamav2 load model

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

using exllamav2 loading model 

### Logs

```shell
Traceback (most recent call last):

File "D:\oobabooga_windows\999\text-generation-webui\modules\ui_model_menu.py", line 201, in load_model_wrapper


shared.model, shared.tokenizer = load_model(shared.model_name, loader)

                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\oobabooga_windows\999\text-generation-webui\modules\models.py", line 79, in load_model


output = load_func_map[loader](model_name)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\oobabooga_windows\999\text-generation-webui\modules\models.py", line 346, in ExLlamav2_loader


from modules.exllamav2 import Exllamav2Model
File "D:\oobabooga_windows\999\text-generation-webui\modules\exllamav2.py", line 6, in


from exllamav2 import (
File "D:\oobabooga_windows\999\text-generation-webui\installer_files\env\Lib\site-packages\exllamav2_init_.py", line 3, in


from exllamav2.model import ExLlamaV2
File "D:\oobabooga_windows\999\text-generation-webui\installer_files\env\Lib\site-packages\exllamav2\model.py", line 15, in


from exllamav2.attn import ExLlamaV2Attention
File "D:\oobabooga_windows\999\text-generation-webui\installer_files\env\Lib\site-packages\exllamav2\attn.py", line 19, in


import flash_attn
File "D:\oobabooga_windows\999\text-generation-webui\installer_files\env\Lib\site-packages\flash_attn_init_.py", line 3, in


from flash_attn.flash_attn_interface import (
File "D:\oobabooga_windows\999\text-generation-webui\installer_files\env\Lib\site-packages\flash_attn\flash_attn_interface.py", line 8, in


import flash_attn_2_cuda as flash_attn_cuda
ImportError: DLL load failed while importing flash_attn_2_cuda: 找不到指定的模块。
```

### System Info

```shell
cpu 13600k
gpu rtx 4080
ram 32gb
win11
```

**Comment by jepjoo** [comment]
Need CUDA 12.1. Either do fresh install or this might work too (no guarantees maybe a worse solution than fresh install):

Open cmd, run cmd_windows.bat found in install directory, run

```
conda install -y -k cuda==12.1.1 -c nvidia/label/cuda-12.1.1
python -m pip install torch==2.1.0+cu121 torchvision torchaudio --upgrade --index-url https://download.pytorch.org/whl/cu121
```

BUT it might break AutoAWQ. At least for me AutoAWQ isn't working anymore even with a fresh textgen-webui install on Win11, CUDA 12.1, 4090. 

Exllama2 does work for me on both fresh install aswell as on an installation that was updated from 11.8 -> 12.1 as with the commands above.

**Comment by 3750gustavo** [comment]
After the given command mine gives a xformers warning to reinstall it, does xfomers makes a difference if i am at the moment only running GGUF with 20 layers on the GPU? besides that, it works now at least, not sure if i lost speed or memory efficiency

**Comment by Mr-small-2-six** [comment]
is same


(D:\oobabooga_windows\999\text-generation-webui\installer_files\env) D:\oobabooga_windows\999\text-generation-webui>conda install -y -k cuda==12.1.1 -c nvidia/label/cuda-12.1.1
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.3.1
  latest version: 23.9.0

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.9.0



## Package Plan ##

  environment location: D:\oobabooga_windows\999\text-generation-webui\installer_files\env

  added / updated specs:
    - cuda==12.1.1


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cuda-12.1.1                |                0           2 KB  nvidia/label/cuda-12.1.1
    cuda-cccl-12.1.109         |                0         1.2 MB  nvidia/label/cuda-12.1.1
    cuda-command-line-tools-12.1.1|                0           2 KB  nvidia/label/cuda-12.1.1
    cuda-compiler-12.1.1       |                0           2 KB  nvidia/label/cuda-12.1.1
    cuda-cudart-12.1.105       |                0         964 KB  nvidia/label/cuda-12.1.1
    cuda-cudart-dev-12.1.105   |                0         549 KB  nvidia/label/cuda-12.1.1
    cuda-cuobjdump-12.1.111    |                0         3.7 MB  nvidia/label/cuda-12.1.1
    cuda-cupti-12.1.105        |                0        11.6 MB  nvidia/label/cuda-12.1.1
    cuda-cuxxfilt-12.1.105     |                0         163 KB  nvidia/label/cuda-12.1.1
    cuda-demo-suite-12.1.105   |                0         4.7 MB  nvidia/label/cuda-12.1.1
    cuda-documentation-12.1.105|                0          89 KB  nvidia/label/cuda-12.1.1
    cuda-libraries-12.1.1      |                0           2 KB  nvidia/label/cuda-12.1.1
    cuda-libraries-dev-12.1.1  |                0           2 KB  nvidia/label/cuda-12.1.1
    cuda-nsight-compute-12.1.1 |                0           2 KB  nvidia/label/cuda-12.1.1
    cuda-nvcc-12.1.105         |                0        55.3 MB  nvidia/label/cuda-12.1.1
    cuda-nvdisasm-12.1.105     |                0        48.0 MB  nvidia/label/cuda-12.1.1
    cuda-nvml-dev-12.1.105     |                0          88 KB  nvidia/label/cuda-12.1.1
    cuda-nvprof-12.1.105       |                0         1.6 MB  nvidia/label/cuda-12.1.1
    cuda-nvprune-12.1.105      |                0         150 KB  nvidia/label/cuda-12.1.1
    cuda-nvrtc-12.1.105        |                0        73.2 MB  nvidia/label/cuda-12.1.1
    cuda-nvrtc-dev-12.1.105    |                0        16.5 MB  nvidia/label/cuda-12.1.1
    cuda-nvtx-12.1.105         |                0          41 KB  nvidia/label/cuda-12.1.1
    cuda-nvvp-12.1.105         |                0       113.6 MB  nvidia/label/cuda-12.1.1
    cuda-opencl-12.1.105       |                0          10 KB  nvidia/label/cuda-12.1.1
    cuda-opencl-dev-12.1.105   |                0          61 KB  nvidia/label/cuda-12.1.1
    cuda-profiler-api-12.1.105 |                0          18 KB  nvidia/label/cuda-12.1.1
    cuda-runtime-12.1.1        |                0           2 KB  nvidia/label/cuda-12.1.1
    cuda-sanitizer-api-12.1.105|                0        12.9 MB  nvidia/label/cuda-12.1.1
    cuda-toolkit-12.1.1        |                0           2 KB  nvidia/label/cuda-12.1.1
    cuda-tools-12.1.1          |                0           2 KB  nvidia/label/cuda-12.1.1
    cuda-visual-tools-12.1.1   |                0           2 KB  nvidia/label/cuda-12.1.1
    libcublas-12.1.3.1         |                0          35 KB  nvidia/label/cuda-12.1.1
    libcublas-dev-12.1.3.1     |                0       379.9 MB  nvidia/label/cuda-12.1.1
    libcufft-11.0.2.54         |                0           6 KB  nvidia/label/cuda-12.1.1
    libcufft-dev-11.0.2.54     |                0       102.6 MB  nvidia/label/cuda-12.1.1
    libcurand-10.3.2.106       |                0           3 KB  nvidia/label/cuda-12.1.1
    libcurand-dev-10.3.2.106   |                0        50.0 MB  nvidia/label/cuda-12.1.1
    libcusolver-11.4.5.107     |                0          30 KB  nvidia/label/cuda-12.1.1
    libcusolver-dev-11.4.5.107 |                0       108.6 MB  nvidia/label/cuda-12.1.1
    libcusparse-12.1.0.106     |                0          13 KB  nvidia/label/cuda-12.1.1
    libcusparse-dev-12.1.0.106 |                0       168.3 MB  nvidia/label/cuda-12.1.1
    libnpp-12.1.0.40           |                0         306 KB  nvidia/label/cuda-12.1.1
    libnpp-dev-12.1.0.40       |                0       135.6 MB  nvidia/label/cuda-12.1.1
    libnvjitlink-12.1.105      |                0        67.3 MB  nvidia/label/cuda-12.1.1
    libnvjitlink-dev-12.1.105  |                0        13.8 MB  nvidia/label/cuda-12.1.1
    libnvjpeg-12.2.0.2         |                0           5 KB  nvidia/label/cuda-12.1.1
    libnvjpeg-dev-12.2.0.2     |                0         2.4 MB  nvidia/label/cuda-12.1.1
    libnvvm-samples-12.1.105   |                0          32 KB  nvidia/label/cuda-12.1.1
    nsight-compute-2023.1.1.4  |                0       602.4 MB  nvidia/label/cuda-12.1.1
    ------------------------------------------------------------
                                           Total:        1.93 GB

The following NEW packages will be INSTALLED:

  cuda               nvidia/label/cuda-12.1.1/win-64::cuda-12.1.1-0
  cuda-cccl          nvidia/label/cuda-12.1.1/win-64::cuda-cccl-12.1.109-0
  cuda-command-line~ nvidia/label/cuda-12.1.1/win-64::cuda-command-line-tools-12.1.1-0
  cuda-compiler      nvidia/label/cuda-12.1.1/win-64::cuda-compiler-12.1.1-0
  cuda-cudart-dev    nvidia/label/cuda-12.1.1/win-64::cuda-cudart-dev-12.1.105-0
  cuda-cuobjdump     nvidia/label/cuda-12.1.1/win-64::cuda-cuobjdump-12.1.111-0
  cuda-cupti         nvidia/label/cuda-12.1.1/win-64::cuda-cupti-12.1.105-0
  cuda-cuxxfilt      nvidia/label/cuda-12.1.1/win-64::cuda-cuxxfilt-12.1.105-0
  cuda-demo-suite    nvidia/label/cuda-12.1.1/win-64::cuda-demo-suite-12.1.105-0
  cuda-documentation nvidia/label/cuda-12.1.1/win-64::cuda-documentation-12.1.105-0
  cuda-libraries-dev nvidia/label/cuda-12.1.1/win-64::cuda-libraries-dev-12.1.1-0
  cuda-nsight-compu~ nvidia/label/cuda-12.1.1/win-64::cuda-nsight-compute-12.1.1-0
  cuda-nvcc          nvidia/label/cuda-12.1.1/win-64::cuda-nvcc-12.1.105-0
  cuda-nvdisasm      nvidia/label/cuda-12.1.1/win-64::cuda-nvdisasm-12.1.105-0
  cuda-nvml-dev      nvidia/label/cuda-12.1.1/win-64::cuda-nvml-dev-12.1.105-0
  cuda-nvprof        nvidia/label/cuda-12.1.1/win-64::cuda-nvprof-12.1.105-0
  cuda-nvprune       nvidia/label/cuda-12.1.1/win-64::cuda-nvprune-12.1.105-0
  cuda-nvrtc-dev     nvidia/label/cuda-12.1.1/win-64::cuda-nvrtc-dev-12.1.105-0
  cuda-nvtx          nvidia/label/cuda-12.1.1/win-64::cuda-nvtx-12.1.105-0
  cuda-nvvp          nvidia/label/cuda-12.1.1/win-64::cuda-nvvp-12.1.105-0
  cuda-opencl        nvidia/label/cuda-12.1.1/win-64::cuda-opencl-12.1.105-0
  cuda-opencl-dev    nvidia/label/cuda-12.1.1/win-64::cuda-opencl-dev-12.1.105-0
  cuda-profiler-api  nvidia/label/cuda-12.1.1/win-64::cuda-profiler-api-12.1.105-0
  cuda-sanitizer-api nvidia/label/cuda-12.1.1/win-64::cuda-sanitizer-api-12.1.105-0
  cuda-toolkit       nvidia/label/cuda-12.1.1/win-64::cuda-toolkit-12.1.1-0
  cuda-tools         nvidia/label/cuda-12.1.1/win-64::cuda-tools-12.1.1-0
  cuda-visual-tools  nvidia/label/cuda-12.1.1/win-64::cuda-visual-tools-12.1.1-0
  libcublas-dev      nvidia/label/cuda-12.1.1/win-64::libcublas-dev-12.1.3.1-0
  libcufft-dev       nvidia/label/cuda-12.1.1/win-64::libcufft-dev-11.0.2.54-0
  libcurand-dev      nvidia/label/cuda-12.1.1/win-64::libcurand-dev-10.3.2.106-0
  libcusolver-dev    nvidia/label/cuda-12.1.1/win-64::libcusolver-dev-11.4.5.107-0
  libcusparse-dev    nvidia/label/cuda-12.1.1/win-64::libcusparse-dev-12.1.0.106-0
  libnpp-dev         nvidia/label/cuda-12.1.1/win-64::libnpp-dev-12.1.0.40-0
  libnvjitlink       nvidia/label/cuda-12.1.1/win-64::libnvjitlink-12.1.105-0
  libnvjitlink-dev   nvidia/label/cuda-12.1.1/win-64::libnvjitlink-dev-12.1.105-0
  libnvjpeg-dev      nvidia/label/cuda-12.1.1/win-64::libnvjpeg-dev-12.2.0.2-0
  libnvvm-samples    nvidia/label/cuda-12.1.1/win-64::libnvvm-samples-12.1.105-0
  nsight-compute     nvidia/label/cuda-12.1.1/win-64::nsight-compute-2023.1.1.4-0

The following packages will be UPDATED:

  cuda-cudart        nvidia/label/cuda-11.8.0::cuda-cudart~ --> nvidia/label/cuda-12.1.1::cuda-cudart-12.1.105-0
  cuda-libraries     nvidia/label/cuda-11.8.0::cuda-librar~ --> nvidia/label/cuda-12.1.1::cuda-libraries-12.1.1-0
  cuda-nvrtc         nvidia/label/cuda-11.8.0::cuda-nvrtc-~ --> nvidia/label/cuda-12.1.1::cuda-nvrtc-12.1.105-0
  cuda-runtime       nvidia/label/cuda-11.8.0::cuda-runtim~ --> nvidia/label/cuda-12.1.1::cuda-runtime-12.1.1-0
  libcublas          nvidia/label/cuda-11.8.0::libcublas-1~ --> nvidia/label/cuda-12.1.1::libcublas-12.1.3.1-0
  libcufft           nvidia/label/cuda-11.8.0::libcufft-10~ --> nvidia/label/cuda-12.1.1::libcufft-11.0.2.54-0
  libcurand          nvidia/label/cuda-11.8.0::libcurand-1~ --> nvidia/label/cuda-12.1.1::libcurand-10.3.2.106-0
  libcusolver        nvidia/label/cuda-11.8.0::libcusolver~ --> nvidia/label/cuda-12.1.1::libcusolver-11.4.5.107-0
  libcusparse        nvidia/label/cuda-11.8.0::libcusparse~ --> nvidia/label/cuda-12.1.1::libcusparse-12.1.0.106-0
  libnpp             nvidia/label/cuda-11.8.0::libnpp-11.8~ --> nvidia/label/cuda-12.1.1::libnpp-12.1.0.40-0
  libnvjpeg          nvidia/label/cuda-11.8.0::libnvjpeg-1~ --> nvidia/label/cuda-12.1.1::libnvjpeg-12.2.0.2-0



Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(D:\oobabooga_windows\999\text-generation-webui\installer_files\env) D:\oobabooga_windows\999\text-generation-webui>python -m pip install torch==2.1.0+cu121 torchvision torchaudio --upgrade --index-url https://download.pytorch.org/whl/cu121
Looking in indexes: https://download.pytorch.org/whl/cu121
Collecting torch==2.1.0+cu121
  Downloading https://download.pytorch.org/whl/cu121/torch-2.1.0%2Bcu121-cp311-cp311-win_amd64.whl (2473.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 GB 5.4 MB/s eta 0:00:00
Requirement already satisfied: torchvision in d:\oobabooga_windows\999\text-generation-webui\installer_files\env\lib\site-packages (0.16.0+cu118)
Collecting torchvision
  Downloading https://download.pytorch.org/whl/cu121/torchvision-0.16.0%2Bcu121-cp311-cp311-win_amd64.whl (5.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 91.2 MB/s eta 0:00:00
Requirement already satisfied: torchaudio in d:\oobabooga_windows\999\text-generation-webui\installer_files\env\lib\site-packages (2.1.0+cu118)
Collecting torchaudio
  Downloading https://download.pytorch.org/whl/cu121/torchaudio-2.1.0%2Bcu121-cp311-cp311-win_amd64.whl (4.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 129.5 MB/s eta 0:00:00
Requirement already satisfied: filelock in d:\oobabooga_windows\999\text-generation-webui\installer_files\env\lib\site-packages (from torch==2.1.0+cu121) (3.12.4)
Requirement already satisfied: typing-extensions in d:\oobabooga_windows\999\text-generation-webui\installer_files\env\lib\site-packages (from torch==2.1.0+cu121) (4.8.0)
Requirement already satisfied: sympy in d:\oobabooga_windows\999\text-generation-webui\installer_files\env\lib\site-packages (from torch==2.1.0+cu121) (1.12)
Requirement already satisfied: networkx in d:\oobabooga_windows\999\text-generation-webui\installer_files\env\lib\site-packages (from torch==2.1.0+cu121) (3.0)
Requirement already satisfied: jinja2 in d:\oobabooga_windows\999\text-generation-webui\installer_files\env\lib\site-packages (from torch==2.1.0+cu121) (3.1.2)
Requirement already satisfied: fsspec in d:\oobabooga_windows\999\text-generation-webui\installer_files\env\lib\site-packages (from torch==2.1.0+cu121) (2023.6.0)
Requirement already satisfied: numpy in d:\oobabooga_windows\999\text-generation-webui\installer_files\env\lib\site-packages (from torchvision) (1.24.4)
Requirement already satisfied: requests in d:\oobabooga_windows\999\text-generation-webui\installer_files\env\lib\site-packages (from torchvision) (2.31.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in d:\oobabooga_windows\999\text-generation-webui\installer_files\env\lib\site-packages (from torchvision) (10.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\oobabooga_windows\999\text-generation-webui\installer_files\env\lib\site-packages (from jinja2->torch==2.1.0+cu121) (2.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\oobabooga_windows\999\text-generation-webui\installer_files\env\lib\site-packages (from requests->torchvision) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in d:\oobabooga_windows\999\text-generation-webui\installer_files\env\lib\site-packages (from requests->torchvision) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\oobabooga_windows\999\text-generation-webui\installer_files\env\lib\site-packages (from requests->torchvision) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in d:\oobabooga_windows\999\text-generation-webui\installer_files\env\lib\site-packages (from requests->torchvision) (2022.12.7)
Requirement already satisfied: mpmath>=0.19 in d:\oobabooga_windows\999\text-generation-webui\installer_files\env\lib\site-packages (from sympy->torch==2.1.0+cu121) (1.3.0)
Installing collected packages: torch, torchvision, torchaudio
  Attempting uninstall: torch
    Found existing installation: torch 2.1.0+cu118
    Uninstalling torch-2.1.0+cu118:
      Successfully uninstalled torch-2.1.0+cu118
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.16.0+cu118
    Uninstalling torchvision-0.16.0+cu118:
      Successfully uninstalled torchvision-0.16.0+cu118
  Attempting uninstall: torchaudio
    Found existing installation: torchaudio 2.1.0+cu118
    Uninstalling torchaudio-2.1.0+cu118:
      Successfully uninstalled torchaudio-2.1.0+cu118
Successfully installed torch-2.1.0+cu121 torchaudio-2.1.0+cu121 torchvision-0.16.0+cu121

also get Dll error

Traceback (most recent call last):

File "D:\oobabooga_windows\999\text-generation-webui\modules\ui_model_menu.py", line 201, in load_model_wrapper


shared.model, shared.tokenizer = load_model(shared.model_name, loader)

                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\oobabooga_windows\999\text-generation-webui\modules\models.py", line 79, in load_model


output = load_func_map[loader](model_name)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\oobabooga_windows\999\text-generation-webui\modules\models.py", line 353, in ExLlamav2_HF_loader


from modules.exllamav2_hf import Exllamav2HF
File "D:\oobabooga_windows\999\text-generation-webui\modules\exllamav2_hf.py", line 6, in


from exllamav2 import ExLlamaV2, ExLlamaV2Cache, ExLlamaV2Config
File "D:\oobabooga_windows\999\text-generation-webui\installer_files\env\Lib\site-packages\exllamav2_init_.py", line 3, in


from exllamav2.model import ExLlamaV2
File "D:\oobabooga_windows\999\text-generation-webui\installer_files\env\Lib\site-packages\exllamav2\model.py", line 11, in


from exllamav2.cache import ExLlamaV2Cache
File "D:\oobabooga_windows\999\text-generation-webui\installer_files\env\Lib\site-packages\exllamav2\cache.py", line 2, in


from exllamav2.ext import exllamav2_ext as ext_c
File "D:\oobabooga_windows\999\text-generation-webui\installer_files\env\Lib\site-packages\exllamav2\ext.py", line 14, in


import exllamav2_ext
ImportError: DLL load failed while importing exllamav2_ext: 找不到指定的模块。



> Need CUDA 12.1. Either do fresh install of textgen-webui or this might work too (no guarantees maybe a worse solution than fresh install):
> 
> Open cmd, run cmd_windows.bat found in install directory, run
> 
> ```
> conda install -y -k cuda==12.1.1 -c nvidia/label/cuda-12.1.1
> python -m pip install torch==2.1.0+cu121 torchvision torchaudio --upgrade --index-url https://download.pytorch.org/whl/cu121
> ```
> 
> BUT it might break AutoAWQ. At least for me AutoAWQ isn't working anymore even with a fresh textgen-webui install on Win11, CUDA 12.1, 4090.
> 
> Exllama2 does work for me on both fresh install aswell as on an installation that was updated from 11.8 -> 12.1 with the commands above.

**Comment by Mr-small-2-six** [comment]
or my pc python need 3.1 version?cos my pc python version is 3.10?

**Comment by AStroh-edits** [comment]
I installed Cuda 12.2 through Nvidia toolkit, Visual Studio 2022, the above Pytorch line mentioned, ninja, skipped conda. Then ninja locked up my computer due to too many instances trying to install flash_attn. Did a work-a-round with doskey and flash_attn installed easily.

I had ExLlamav2_HF working before the update yesterday and then running update_windows.bat today broke it.

I don't know if there's a better route but a fresh install and 8GB download was the easiest.
ExLlamav2_HF now works and it appears to be running faster.

**Comment by Mr-small-2-six** [comment]
i try git pull and fresh install now exllamav2 can working no have flash_attn warning
