### ISSUE TITLE
RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback): DLL load failed while importing flash_attn_2_cuda: The specified module could not be found.

### ISSUE THREAD

**Issue by ayush1268** [oobabooga/text-generation-webui#4357]
File "F:\vicuna\oobabooga_windows\text-generation-webui\modules\ui_model_menu.py", line 201, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "F:\vicuna\oobabooga_windows\text-generation-webui\modules\models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "F:\vicuna\oobabooga_windows\text-generation-webui\modules\models.py", line 136, in huggingface_loader
    model = LoaderClass.from_pretrained(path_to_model, **params)
  File "F:\vicuna\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 564, in from_pretrained
    model_class = _get_model_class(config, cls._model_mapping)
  File "F:\vicuna\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 387, in _get_model_class
    supported_models = model_mapping[type(config)]
  File "F:\vicuna\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 739, in __getitem__
    return self._load_attr_from_module(model_type, model_name)
  File "F:\vicuna\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 753, in _load_attr_from_module
    return getattribute_from_module(self._modules[module_name], attr)
  File "F:\vicuna\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 697, in getattribute_from_module
    if hasattr(module, attr):
  File "F:\vicuna\oobabooga_windows\installer_files\env\lib\site-packages\transformers\utils\import_utils.py", line 1272, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "F:\vicuna\oobabooga_windows\installer_files\env\lib\site-packages\transformers\utils\import_utils.py", line 1284, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
DLL load failed while importing flash_attn_2_cuda: The specified module could not be found.

please help me with this i cant able to run the model vuicuna 

![Text generation web UI - Google Chrome 22-10-2023 20_47_02](https://github.com/oobabooga/text-generation-webui/assets/71268103/5d1f7501-426b-43a0-bcfd-54e0b877d7e5)
![Text generation web UI - Google Chrome 22-10-2023 20_47_16](https://github.com/oobabooga/text-generation-webui/assets/71268103/f788d19a-e6b4-4ec7-bfaf-b557f930c49e)
![Text generation web UI - Google Chrome 22-10-2023 20_47_24](https://github.com/oobabooga/text-generation-webui/assets/71268103/3c86f0fa-d399-4069-b328-dff2d7c9b8d0)
![Text generation web UI - Google Chrome 22-10-2023 20_47_28](https://github.com/oobabooga/text-generation-webui/assets/71268103/63c18502-9135-4d32-8122-6d769b6cd59b)

**Comment by ELEVENORANGE** [comment]
pip install transformers==4.33.0

**Comment by ayush1268** [comment]
> pip install transformers==4.33.0

still not solving the problem

**Comment by puertea-z** [comment]
having the same issue with Llama2 13B

**Comment by sharad79** [comment]
In Auto train i am getting error
  raise RuntimeError(
RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
/databricks/python/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops9_pad_enum4callERKNS_6TensorEN3c108ArrayRefINS5_6SymIntEEElNS5_8optionalIdEE


after installing the autotrain and transfermer
!pip install autotrain-advanced==0.6.51
!pip install transformers==4.38.0

not able to resolve issue 

how can resolve above issue issue

**Comment by snehalpatel-8451** [comment]
Having same issue with Llama3!
```python
RuntimeError                              Traceback (most recent call last)
File <command-1558648439763268>, line 2
      1 model_id = "meta-llama/Meta-Llama-3-8B-Instruct"
----> 2 generator = TextGenerator(model_id)
File <command-1558648439763269>, line 5, in TextGenerator.__init__(self, model_id)
      3 def __init__(self, model_id):
      4     self.tokenizer = AutoTokenizer.from_pretrained(model_id)
----> 5     self.model = AutoModelForCausalLM.from_pretrained(
      6         model_id,
      7         torch_dtype=torch.bfloat16,
      8         device_map="auto",
      9     )
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-b313828f-3701-4c58-9775-f8da5ae7b4a9/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py:562, in _BaseAutoModelClass.from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    558     return model_class.from_pretrained(
    559         pretrained_model_name_or_path, *model_args, config=config, **hub_kwargs, **kwargs
    560     )
    561 elif type(config) in cls._model_mapping.keys():
--> 562     model_class = _get_model_class(config, cls._model_mapping)
    563     return model_class.from_pretrained(
    564         pretrained_model_name_or_path, *model_args, config=config, **hub_kwargs, **kwargs
    565     )
    566 raise ValueError(
    567     f"Unrecognized configuration class {config.__class__} for this kind of AutoModel: {cls.__name__}.\n"
    568     f"Model type should be one of {', '.join(c.__name__ for c in cls._model_mapping.keys())}."
    569 )
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-b313828f-3701-4c58-9775-f8da5ae7b4a9/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py:383, in _get_model_class(config, model_mapping)
    382 def _get_model_class(config, model_mapping):
--> 383     supported_models = model_mapping[type(config)]
    384     if not isinstance(supported_models, (list, tuple)):
    385         return supported_models
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-b313828f-3701-4c58-9775-f8da5ae7b4a9/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py:734, in _LazyAutoMapping.__getitem__(self, key)
    732 if model_type in self._model_mapping:
    733     model_name = self._model_mapping[model_type]
--> 734     return self._load_attr_from_module(model_type, model_name)
    736 # Maybe there was several model types associated with this config.
    737 model_types = [k for k, v in self._config_mapping.items() if v == key.__name__]
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-b313828f-3701-4c58-9775-f8da5ae7b4a9/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py:748, in _LazyAutoMapping._load_attr_from_module(self, model_type, attr)
    746 if module_name not in self._modules:
    747     self._modules[module_name] = importlib.import_module(f".{module_name}", "transformers.models")
--> 748 return getattribute_from_module(self._modules[module_name], attr)
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-b313828f-3701-4c58-9775-f8da5ae7b4a9/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py:692, in getattribute_from_module(module, attr)
    690 if isinstance(attr, tuple):
    691     return tuple(getattribute_from_module(module, a) for a in attr)
--> 692 if hasattr(module, attr):
    693     return getattr(module, attr)
    694 # Some of the mappings have entries model_type -> object of another model type. In that case we try to grab the
    695 # object at the top level.
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-b313828f-3701-4c58-9775-f8da5ae7b4a9/lib/python3.10/site-packages/transformers/utils/import_utils.py:1500, in _LazyModule.__getattr__(self, name)
   1498     value = self._get_module(name)
   1499 elif name in self._class_to_module.keys():
-> 1500     module = self._get_module(self._class_to_module[name])
   1501     value = getattr(module, name)
   1502 else:
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-b313828f-3701-4c58-9775-f8da5ae7b4a9/lib/python3.10/site-packages/transformers/utils/import_utils.py:1512, in _LazyModule._get_module(self, module_name)
   1510     return importlib.import_module("." + module_name, self.__name__)
   1511 except Exception as e:
-> 1512     raise RuntimeError(
   1513         f"Failed to import {self.__name__}.{module_name} because of the following error (look up to see its"
   1514         f" traceback):\n{e}"
   1515     ) from e
```

**Comment by analyticsrepo01** [comment]
me too
RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):

**Comment by Khadija-Bayoud** [comment]
+1. Is there any solution for this?

**Comment by shizhediao** [comment]
> In Auto train i am getting error raise RuntimeError( RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback): /databricks/python/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops9_pad_enum4callERKNS_6TensorEN3c108ArrayRefINS5_6SymIntEEElNS5_8optionalIdEE
> 
> after installing the autotrain and transfermer !pip install autotrain-advanced==0.6.51 !pip install transformers==4.38.0
> 
> not able to resolve issue
> 
> how can resolve above issue

same question. any solutions?

**Comment by prassr** [comment]
I am also having the same issue.

Please, let us no for any solutions.

**Comment by tomsiu** [comment]
same issue :(

**Comment by priyankaiiit14** [comment]
same issue

**Comment by cuipanguo** [comment]
anybody solve it？

**Comment by tomsiu** [comment]
!pip install protobuf==3.19.00 
!pip install -U tensorflow==2.10
!pip install git+https://github.com/NVIDIA/TransformerEngine.git@stable

I have done these installations and it solve the issue in my case. See if it may help you too.

**Comment by Diya129** [comment]
same issue for LLam

> I am having the same issue with Llama2 13B

any solution?

**Comment by YuMeng2v** [comment]
same issue

**Comment by sunaarun** [comment]
same issue with llama3.1

**Comment by WangHanAiMachine** [comment]
same for me, the llava next works well 2 weeks ago, but failed because of the same error today

**Comment by AneekeshKumar** [comment]
same issue with Llama 2, Llama 3, Llama 3.1-8B-Instruct etc....

**Comment by chancharikmitra** [comment]
I don't know the reason, but there are certain versions of flash-attn that have this issue. It seems 2.5.8 works for me, and in particular this wheel: 

`pip install https://github.com/Dao-AILab/flash-attention/releases/download/v2.5.8/flash_attn-2.5.8+cu122torch2.3cxx11abiFALSE-cp310-cp310-linux_x86_64.whl`

But then again, you may need the wheel specific to your cuda, torch, gcc, and python version. I would try the above first, since my CUDA verson was slightly older but still worked.

**Comment by SiyangJ** [comment]
> I don't know the reason, but there are certain versions of flash-attn that have this issue. It seems 2.5.8 works for me, and in particular this wheel:
> 
> `pip install https://github.com/Dao-AILab/flash-attention/releases/download/v2.5.8/flash_attn-2.5.8+cu122torch2.3cxx11abiFALSE-cp310-cp310-linux_x86_64.whl`
> 
> But then again, you may need the wheel specific to your cuda, torch, gcc, and python version. I would try the above first, since my CUDA verson was slightly older but still worked.

Dude you saved my f**king life

**Comment by iftacha-nrd** [comment]
> I don't know the reason, but there are certain versions of flash-attn that have this issue. It seems 2.5.8 works for me, and in particular this wheel:
> 
> `pip install https://github.com/Dao-AILab/flash-attention/releases/download/v2.5.8/flash_attn-2.5.8+cu122torch2.3cxx11abiFALSE-cp310-cp310-linux_x86_64.whl`
> 
> But then again, you may need the wheel specific to your cuda, torch, gcc, and python version. I would try the above first, since my CUDA verson was slightly older but still worked.

Saved my life to

**Comment by JoshuaPinaca** [comment]
> > I don't know the reason, but there are certain versions of flash-attn that have this issue. It seems 2.5.8 works for me, and in particular this wheel:
> > `pip install https://github.com/Dao-AILab/flash-attention/releases/download/v2.5.8/flash_attn-2.5.8+cu122torch2.3cxx11abiFALSE-cp310-cp310-linux_x86_64.whl`
> > But then again, you may need the wheel specific to your cuda, torch, gcc, and python version. I would try the above first, since my CUDA verson was slightly older but still worked.
> 
> Dude you saved my f**king life

mine too

**Comment by prashant-dn** [comment]
Found this working for `OpenGVLab/InternVideo2_5_Chat_8B`. 

Use container `docker pull huggingface/transformers-pytorch-gpu:latest` with local CUDA 12.1+.

Inside, just install 'flash attention', if needed, using `pip install flash-attn --no-build-isolation`.

Works like a charm!

**Comment by TheCuriousCurator** [comment]
Ubuntu 22.04 
torch 2.7.0+cu126
python 3.9.19 (main, May  6 2024, 19:43:03)  [GCC 11.2.0]

This worked for me
`pip install flash_attn-2.7.4.post1+cu12torch2.6cxx11abiTRUE-cp39-cp39-linux_x86_64.whl`

I downloaded from releases. ( https://github.com/Dao-AILab/flash-attention/releases/ )
