### ISSUE TITLE
Installer fails, unable to understand why

### ISSUE THREAD

**Issue by dagbdagb** [oobabooga/text-generation-webui#4358]
### Describe the bug

start_linux.sh fails with:

Traceback (most recent call last):
  File "/home/dagb/llm/text-generation-webui/one_click.py", line 360, in <module>
    install_webui()
  File "/home/dagb/llm/text-generation-webui/one_click.py", line 210, in install_webui
    update_requirements(initial_installation=True)
  File "/home/dagb/llm/text-generation-webui/one_click.py", line 255, in update_requirements
    torver = torch_version()
  File "/home/dagb/llm/text-generation-webui/one_click.py", line 67, in torch_version
    torch_version_file = open(os.path.join(site_packages_path, 'torch', 'version.py')).read().splitlines()
FileNotFoundError: [Errno 2] No such file or directory: '/home/dagb/llm/text-generation-webui/installer_files/env/lib/python3.10/site-packages/torch/version.py'

... despite torch reportedly being installed earlier. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

git clone https://github.com/oobabooga/text-generation-webui.git
cd text-generations-webui
./start_linux.sh   <- fails
./start_linux.sh    <- for good measure, in case something got updated
./cmd_linux.sh    <- to update conda, so I can silence the warning about updated conda
./start_linux.sh   <- fails again.

I will upload a complete log

### Logs

```shell
Successfully installed PyYAML-6.0.1 antlr4-python3-runtime-4.9.3 asttokens-2.0.7 backcall-0.2.0 decorator-5.1.1 docopt-0.6.2 exceptiongroup-1.1.3 executing-2.0.0 ipython-8.16.1 jedi-0.18.1 matplotlib-inline-0.1.6 num2words-0.5.12 omegaconf-2.3.0 parso-0.8.3 pexpect-4.8.0 pickleshare-0.7.5 prompt-toolkit-3.0.39 ptyprocess-0.7.0 pure-eval-0.2.2 pydub-0.25.1 pygments-2.14.0 six-1.16.0 stack-data-0.6.3 traitlets-5.11.2 wcwidth-0.2.8
Traceback (most recent call last):
  File "/home/dagb/llm/text-generation-webui/one_click.py", line 360, in <module>
    install_webui()
  File "/home/dagb/llm/text-generation-webui/one_click.py", line 210, in install_webui
    update_requirements(initial_installation=True)
  File "/home/dagb/llm/text-generation-webui/one_click.py", line 255, in update_requirements
    torver = torch_version()
  File "/home/dagb/llm/text-generation-webui/one_click.py", line 67, in torch_version
    torch_version_file = open(os.path.join(site_packages_path, 'torch', 'version.py')).read().splitlines()
FileNotFoundError: [Errno 2] No such file or directory: '/home/dagb/llm/text-generation-webui/installer_files/env/lib/python3.10/site-packages/torch/version.py'
```

### System Info

```shell
gentoo linux, x86_64, Nvidia GeForce RTX 2070 Mobile
```

**Comment by dagbdagb** [comment]
[ooba2a.log](https://github.com/oobabooga/text-generation-webui/files/13064222/ooba2a.log)

**Comment by dagbdagb** [comment]
I am completely open to the idea that my environment is at fault here. But I fail to find any clue about what it is.

**Comment by HiroseKoichi** [comment]
I've had installs of pytorch fail because it used a cached version, and it looks like almost everything you installed was from cache. Try deleting the contents of ~/.cache/pip and see if that works.

**Comment by dagbdagb** [comment]
So, I did a `find ~ -name torch\*`  and rm -rf'ed any directory having a hint of torch* in it.
And sure enough, stuff changed. Now I get:
```
Installing collected packages: wcwidth, pydub, pure-eval, ptyprocess, docopt, antlr4-python3-runtime, traitlets, six, PyYAML, pygments, prompt-toolkit, pexpect, parso, num2words, executing, decorator, omegaconf, matplotlib-inline, jedi, asttokens, stack-data, ipython
Successfully installed PyYAML-6.0.1 antlr4-python3-runtime-4.9.3 asttokens-2.4.1 decorator-5.1.1 docopt-0.6.2 executing-2.0.1 ipython-8.17.2 jedi-0.19.1 matplotlib-inline-0.1.6 num2words-0.5.13 omegaconf-2.3.0 parso-0.8.3 pexpect-4.8.0 prompt-toolkit-3.0.39 ptyprocess-0.7.0 pure-eval-0.2.2 pydub-0.25.1 pygments-2.16.1 six-1.16.0 stack-data-0.6.3 traitlets-5.13.0 wcwidth-0.2.9
Traceback (most recent call last):
  File "/home/dagb/llm/text-generation-webui/one_click.py", line 376, in <module>
    install_webui()
  File "/home/dagb/llm/text-generation-webui/one_click.py", line 223, in install_webui
    update_requirements(initial_installation=True)
  File "/home/dagb/llm/text-generation-webui/one_click.py", line 268, in update_requirements
    torver = torch_version()
             ^^^^^^^^^^^^^^^
  File "/home/dagb/llm/text-generation-webui/one_click.py", line 80, in torch_version
    torch_version_file = open(os.path.join(site_packages_path, 'torch', 'version.py')).read().splitlines()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/dagb/llm/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/version.py'
```

Used to be 'python3.10/site-packages/torch/version.py'.

Further digging reveals that my torch package is installed to:
```
~/.local/lib/python3.11/site-packages/torch
```
and not to 

```
/home/dagb/llm/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/version.py
```

Quite a lot of them end up there, in fact. What is the correct fix here?

**Comment by aggregate1166877** [comment]
Also using `./start_linux.sh`, I'm experiencing what appears to be the same issue with a slightly different error:

```
*******************************************************************
* Updating the local copy of the repository with "git pull"
*******************************************************************


Already up to date.
Traceback (most recent call last):
  File "/tmp/ai/text-generation-webui/one_click.py", line 468, in <module>
    install_webui()
  File "/tmp/ai/text-generation-webui/one_click.py", line 318, in install_webui
    update_requirements(initial_installation=True)
  File "/tmp/ai/text-generation-webui/one_click.py", line 367, in update_requirements
    torver = torch_version()
             ^^^^^^^^^^^^^^^
  File "/tmp/ai/text-generation-webui/one_click.py", line 95, in torch_version
    torch_version_file = open(os.path.join(site_packages_path, 'torch', 'version.py')).read().splitlines()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ai/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/version.py'
```

I've tried deleting the `text-generation-webui` directory, deleting all my pip cache, doing a full-disk search and deleting everything relating to torch, and still experiencing this issue.

Running from Linux Mint. My main drive is quite small so I've changed my `$PIP_CACHE_DIR` env var to point to another drive, unsure if that's to blame.
