### ISSUE TITLE
queueing.py", line 343

### ISSUE THREAD

**Issue by SvetZitrka** [oobabooga/text-generation-webui#436]
### Describe the bug

Task exception was never retrieved
future: <Task finished name='nsgti5x386a_45' coro=<Queue.process_events() done, defined at d:\XX\oobabooga\installer_files\env\lib\site-packages\gradio\queueing.py:329> exception=AssertionError('No event data')>
Traceback (most recent call last):
  File "d:\XXX\oobabooga\installer_files\env\lib\site-packages\gradio\queueing.py", line 343, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "d:\XXX\oobabooga\installer_files\env\lib\site-packages\gradio\queueing.py", line 303, in call_prediction
    assert data is not None, "No event data"
AssertionError: No event data
Closing server running on port: 7860
Loading the extension "gallery"... Ok.
Loading the extension "character_bias"... Ok.
d:\XXX\oobabooga\installer_files\env\lib\site-packages\gradio\deprecation.py:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
  warnings.warn(value)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Make the change on the "Interface mode" tab and put Apply

### Screenshot

![image](https://user-images.githubusercontent.com/22136815/226182419-019aa5ac-d77a-490f-8070-e6b3ff9aa2ed.png)

### Logs

```shell
To create a public link, set `share=True` in `launch()`.
Output generated in 8.96 seconds (22.21 tokens/s, 199 tokens)
Task exception was never retrieved
future: <Task finished name='nsgti5x386a_45' coro=<Queue.process_events() done, defined at d:\XXX\oobabooga\installer_files\env\lib\site-packages\gradio\queueing.py:329> exception=AssertionError('No event data')>
Traceback (most recent call last):
  File "d:\XXX\oobabooga\installer_files\env\lib\site-packages\gradio\queueing.py", line 343, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "d:\XXX\oobabooga\installer_files\env\lib\site-packages\gradio\queueing.py", line 303, in call_prediction
    assert data is not None, "No event data"
AssertionError: No event data
Closing server running on port: 7860
Loading the extension "gallery"... Ok.
Loading the extension "character_bias"... Ok.
d:\XXXi\oobabooga\installer_files\env\lib\site-packages\gradio\deprecation.py:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
  warnings.warn(value)
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

### System Info

```shell
i9
```

**Comment by 4125412435** [comment]
I met the same problem, have you finished it?
