### ISSUE TITLE
Error when loading EleutherAI/Llemma_7b

### ISSUE THREAD

**Issue by mattdf** [oobabooga/text-generation-webui#4370]
### Describe the bug

When attempting to load EleutherAI/Llemma_7b via the transformers model loader, it returns the error below from the transformers lib and the model is unable to load.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Download the EleutherAI/Llemma_7b via the interface.
2. Use "Transformers" as the model loader and choose EleutherAI_llemma_7b as the model
3. Click "Load model"

### Screenshot

![Screenshot from 2023-10-23 18-07-08](https://github.com/oobabooga/text-generation-webui/assets/11067114/f3d770da-72f3-42fb-92fb-fb479b7f2ad7)

### Logs

```shell
Traceback (most recent call last):
  File "/home/serve/text-generation-webui/modules/ui_model_menu.py", line 201, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/serve/text-generation-webui/modules/models.py", line 87, in load_model
    tokenizer = load_tokenizer(model_name, model)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/serve/text-generation-webui/modules/models.py", line 106, in load_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/serve/miniconda3/envs/textgen-ui/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 751, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/serve/miniconda3/envs/textgen-ui/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2017, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/serve/miniconda3/envs/textgen-ui/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2242, in _from_pretrained
    init_kwargs[key] = added_tokens_map.get(init_kwargs[key], init_kwargs[key])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
```

### System Info

```shell
OS: Ubuntu 22.04.01 LTS, kernel 5.15.0-83-generic #92-Ubuntu SMP
GPUs: 4x Nvidia RTX A5000
transformers version: 4.34.1

Installation of text-generation-webui was done manually via conda, following the README instructions.
```

**Comment by bytesuji** [comment]
Also getting this issue with llemma-34b

**Comment by mattdf** [comment]
For anyone else having this issue in the meantime, I was able to get the model to load by checking "use_fast".

**Comment by bytesuji** [comment]
Alternatively was able to circumvent by using the [GGUF version](https://huggingface.co/TheBloke/llemma_34b-GGUF) of Llemma

**Comment by RandomInternetPreson** [comment]
Anyone have luck getting good outputs?  I'm not 100% sure how to even do inputs, I've tried LaTex and it really didn't seem to like that.

**Comment by RandomInternetPreson** [comment]
Okay after some searching and fiddling around I think I've got things to work.  The AI wants to keep talking after providing the answer but I can fix this with some stop words.

After much searching I found this screenshot of an input: https://github.com/EleutherAI/math-lm/issues/79#issue-1948701370

I copied the input and I think the model gave the intended output.  
![Untitled](https://github.com/oobabooga/text-generation-webui/assets/6488699/44796b98-4b03-4ec0-a475-e5d07addddbe)

I've given it a few other simple examples and it does the same thing, gives the right answer while rambling.  I've seen this with other models, maybe I can make it go away by changing some of the inferencing parameters.

I also have it loaded in 16f with the plain transformers loader, and "use_fast" unchecked as per mattdfs suggestion.

**Comment by DevasiaThomas** [comment]
I am getting this error with the Llama2 7B HF model. Idk what's wrong, the llama-recipes code is able to generate things fine. However, llama-recipes only works with ``transformers=4.33``

**Comment by DevasiaThomas** [comment]
> For anyone else having this issue in the meantime, I was able to get the model to load by checking "use_fast".

What else did you do? It didn't work for me :D

**Comment by lyccyl1** [comment]
> transformers=4.33

Oh, it works for me. Thx, guys.
