### ISSUE TITLE
Text files will not be loaded in Lora training

### ISSUE THREAD

**Issue by ameen-roayan** [oobabooga/text-generation-webui#4380]
### Describe the bug

I cannot find the text files despite placing them in the right folder with the right format. 
![image](https://github.com/oobabooga/text-generation-webui/assets/92278134/42302d87-d471-4dc0-a3ef-bdf54b9a05db)
![image](https://github.com/oobabooga/text-generation-webui/assets/92278134/21219990-69f0-48c5-8570-ba4a6106cdf8)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Just open, go to training tab, choose raw text 

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/92278134/c04c53b2-dbe3-4100-89f5-c36f1ac03fbe)
![image](https://github.com/oobabooga/text-generation-webui/assets/92278134/3ed3194d-0825-4b8b-a175-0a41920cc0de)

### Logs

```shell
bin F:\AI\text-generation-webui-main\installer_files\env\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll
2023-10-24 20:52:26 INFO:Loading the extension "gallery"...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Closing server running on port: 7860
2023-10-24 20:56:32 INFO:Loading the extension "gallery"...
2023-10-24 20:56:32 INFO:Loading the extension "long_replies"...
2023-10-24 20:56:32 INFO:Loading the extension "superbooga"...
2023-10-24 20:56:32 ERROR:Failed to load the extension "superbooga".
Traceback (most recent call last):
  File "F:\AI\text-generation-webui-main\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "F:\AI\text-generation-webui-main\extensions\superbooga\script.py", line 10, in <module>
    from .chromadb import add_chunks_to_collector, make_collector
  File "F:\AI\text-generation-webui-main\extensions\superbooga\chromadb.py", line 1, in <module>
    import chromadb
ModuleNotFoundError: No module named 'chromadb'
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
2023-10-24 20:56:50 INFO:Loading mistralai_Mistral-7B-v0.1...
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:25<00:00, 12.80s/it]
2023-10-24 20:57:20 INFO:Loaded the model in 30.03 seconds.
```

### System Info

```shell
windows 11
```

**Comment by FartyPants** [comment]
As a quick workaround while you wait for the fix, you can use the Training PRO extension, it will show the text files.

**Comment by bombel28** [comment]
Training Pro does list single textfiles, but not folders anymore, but training does. So another workaround: Make new folder, place textfile there. Is training of your mistral model working? I got errors before it starts:

```
  File "C:\Users\uwe\GPT\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\Users\uwe\GPT\text-generation-webui\modules\training.py", line 528, in do_train
    target_modules=list_target_modules(model_id),
  File "C:\Users\uwe\GPT\text-generation-webui\modules\training.py", line 344, in list_target_modules
    return model_to_lora_modules[model_id]
KeyError: 'mistral'
```

**Comment by ameen-roayan** [comment]
2023-10-25 09:19:44 INFO:Loading raw text file dataset...
2023-10-25 09:19:44 INFO:Training path directory textfiles
2023-10-25 09:19:44 INFO:Loaded training file: 1.txt
(Model has been modified by previous training, it needs to be reloaded...)
2023-10-25 09:19:46 INFO:Loading mistralai_Mistral-7B-v0.1...
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:19<00:00,  9.82s/it]
2023-10-25 09:20:09 INFO:Loaded the model in 22.67 seconds.
Model reloaded OK, continue with training.
2023-10-25 09:20:09 INFO:Getting model ready...
2023-10-25 09:20:09 INFO:Preparing for training...
Traceback (most recent call last):
  File "F:\AI\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "F:\AI\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "F:\AI\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "F:\AI\text-generation-webui-main\modules\training.py", line 528, in do_train
    target_modules=list_target_modules(model_id),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\text-generation-webui-main\modules\training.py", line 344, in list_target_modules
    return model_to_lora_modules[model_id]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'mistral'

Yeah i got the same error, adding the text file to a folder fixed things though !

**Comment by ameen-roayan** [comment]
Training pro seems to bypass that error though

**Comment by FartyPants** [comment]
You should not pile two things in one issue because I don't know what we are talking now - mistral or text files?

in the current Training PRO I simply disallowed the folders as a quick fix before posting PR. I believe it's simply trivial missing * and that's it. I'll probably do the PR today if nobody else did that already. 

As for mistral - the current Training PRO should be fine (don't know the main, but I assuem too). IF not, you need to update transformers - this all goes through transformers - very little done on client side. I had an error in Training PRO which I fixed in last PR (it was my silly error) in order for mistral to work. That shouldn't be in main.

**Comment by bombel28** [comment]
sorry for that. Only to clear things:
Training Pro: Mistral is working, folders for training several textfiles not (as you explained here).
Training: Mistral is not working, but training with folders instead of single raw text file.

And I am sure - things will be fixed. You all do a great job here. Thank you so much.

**Comment by Free-Radical** [comment]
Guys this is f'd up, same issue here and the final LORA produced doesnt run!

@oobabooga textgen-webui has been my go to LLM project but now I feel this project has grown too big and things are breaking every time there is an upgrade. Maybe it time to break it up in to smaller p;rjects, very let down!

**Comment by Victorivus** [comment]
I created a folder, put the file inside and I can see it now on the UI
