### ISSUE TITLE
Cant load any models

### ISSUE THREAD

**Issue by Lil-IQ** [oobabooga/text-generation-webui#4381]
### Describe the bug

I installed this today, and I cant get any model to load it downloads them but then it just pops up with an error when trying to load 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Get model from hugging face, put model in the download box, try to load it and it pops up with an error

### Screenshot

![Screenshot 2023-10-24 163418](https://github.com/oobabooga/text-generation-webui/assets/69873783/77b2602a-3197-466d-a69b-0557b93bd14e)

### Logs

```shell
KeyError: None
2023-10-24 16:27:02 INFO:Loading TheBloke_Llama-2-7b-Chat-GPTQ...
2023-10-24 16:27:02 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "D:\TextGen\text-generation-webui-main\modules\ui_model_menu.py", line 201, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TextGen\text-generation-webui-main\modules\models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TextGen\text-generation-webui-main\modules\models.py", line 123, in huggingface_loader
    config = AutoConfig.from_pretrained(path_to_model, trust_remote_code=params['trust_remote_code'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TextGen\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\models\auto\configuration_auto.py", line 1034, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TextGen\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\configuration_utils.py", line 620, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TextGen\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\configuration_utils.py", line 675, in _get_config_dict
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "D:\TextGen\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\utils\hub.py", line 400, in cached_file
    raise EnvironmentError(
OSError: models\TheBloke_Llama-2-7b-Chat-GPTQ does not appear to have a file named config.json. Checkout 'https://huggingface.co/models\TheBloke_Llama-2-7b-Chat-GPTQ/None' for available files.
```

### System Info

```shell
Windows 11
Nvidia 
RTX 3060ti
```

**Comment by Lil-IQ** [comment]
Legit no idea how I fixed it

**Comment by teto** [comment]
@Lil-IQ please share the solution when closing :*
