### ISSUE TITLE
Models failing to load in Exllama due to 'CUDA error: no kernel image is available for execution on the device'

### ISSUE THREAD

**Issue by kurukurukuru** [oobabooga/text-generation-webui#4384]
### Describe the bug

-edit- This is using Exllama. Did some more testing, and loading a model via llama.cpp and offloading to GPU works as expected.

I am trying to use 2x Tesla K80s, however when trying to load the model I get the error 'CUDA error: no kernel image is available for execution on the device'.
The model does load in VRAM, but it seems it is failing at the stage after loading.
I am currently using the repo drivers on Ubuntu 20.04 (sudo apt install nvidia-driver-470).
The most recent CUDA version this GPU can run is 11.4. 
Tried driver 450, 460, each with their respective CUDA versions. No luck, same error. 
As per NVIDIA documentation (https://docs.nvidia.com/deploy/cuda-compatibility/), things should be compatible between minor versions?

Tried in both manual installation, and one-click. No dice. I can see that for GPUs <=CC 3.5, a different Torch package is needed.  See: https://blog.nelsonliu.me/2020/10/13/newer-pytorch-binaries-for-older-gpus/
From what I've read, CC3.7 (K80) support is retained in current Torch versions. I tried the package anyways, doesn't seem like Torch 1.13 is compatible with the latest release. 

I'm kinda at a loss here. Not sure what to do next. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

-Install NVIDIA repo drivers with 'sudo apt install nvidia-driver-470'
-Install oobabooga w/ CUDA 11.8 for Keplar GPUs
-Try and launch a model

### Screenshot

N/A

### Logs

```shell

oobabooga:


2023-10-25 01:34:07 INFO:Loading TheBloke_Xwin-MLewd-13B-v0.2-GPTQ...
2023-10-25 01:34:12 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/home/h-/text-generation-webui/modules/ui_model_menu.py", line 201, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/h-/text-generation-webui/modules/models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/h-/text-generation-webui/modules/models.py", line 342, in ExLlama_HF_loader
    return ExllamaHF.from_pretrained(model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/h-/text-generation-webui/modules/exllama_hf.py", line 174, in from_pretrained
    return ExllamaHF(config)
           ^^^^^^^^^^^^^^^^^
  File "/home/h-/text-generation-webui/modules/exllama_hf.py", line 31, in __init__
    self.ex_model = ExLlama(self.ex_config)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/h-/text-generation-webui/installer_files/env/lib/python3.11/site-packages/exllama/model.py", line 903, in __init__
    temp_state = torch.zeros((config.max_input_len, config.intermediate_size), dtype = torch.float16, device = dev)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

NVIDIA-SMI:

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.199.02   Driver Version: 470.199.02   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:03:00.0 Off |                    0 |
| N/A   60C    P0    61W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 00000000:04:00.0 Off |                    0 |
| N/A   60C    P0    75W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           Off  | 00000000:0F:00.0 Off |                    0 |
| N/A   49C    P0    61W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           Off  | 00000000:10:00.0 Off |                    0 |
| N/A   53C    P0    77W / 149W |      0MiB / 11441MiB |     60%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

conda info:

h-@amanatsu:~/text-generation-webui$ ./cmd_linux.sh 
(/home/h-/text-generation-webui/installer_files/env) h-@amanatsu:~/text-generation-webui$ 
(/home/h-/text-generation-webui/installer_files/env) h-@amanatsu:~/text-generation-webui$ 
(/home/h-/text-generation-webui/installer_files/env) h-@amanatsu:~/text-generation-webui$ conda info

     active environment : /home/h-/text-generation-webui/installer_files/env
    active env location : /home/h-/text-generation-webui/installer_files/env
            shell level : 1
       user config file : /home/h-/.condarc
 populated config files : 
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=11.4=0
                          __glibc=2.31=0
                          __linux=5.4.0=0
                          __unix=0=0
       base environment : /home/h-/text-generation-webui/installer_files/conda  (writable)
      conda av data dir : /home/h-/text-generation-webui/installer_files/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/h-/text-generation-webui/installer_files/conda/pkgs
                          /home/h-/.conda/pkgs
       envs directories : /home/h-/text-generation-webui/installer_files/conda/envs
                          /home/h-/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.28.1 CPython/3.10.10 Linux/5.4.0-165-generic ubuntu/20.04.6 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

(/home/h-/text-generation-webui/installer_files/env) h-@amanatsu:~/text-generation-webui$
```

### System Info

```shell
Environment:
AMD R5 1600
DDR4 64GB
2x Tesla K80
Ubuntu 20.04.6 (also tried 22.04, no difference)

NVIDIA-SMI 470.199.02   Driver Version: 470.199.02   CUDA Version: 11.4
```

**Comment by kurukurukuru** [comment]
I didn't think to try KoboldAI, but upon a default installation it ended up working??
Maybe because it is using Torch 1.11? Here is what it installed, if it helps:

`   - colorama
   - flask=2.2.3
   - flask-socketio=5.3.2
   - flask-session=0.4.0
   - python-socketio=5.7.2
   - pytorch=1.11
   - python=3.8
   - cudatoolkit=11.1
   - eventlet=0.33.3
   - dnspython=2.2.1
   - markdown
   - bleach=4.1.0
   - pip
   - git=2.35.1
   - sentencepiece
   - protobuf
   - marshmallow[version='>=3.13']
   - apispec-webframeworks
   - loguru
   - termcolor
   - psutil


  Package                       Version  Build                        Channel           Size
──────────────────────────────────────────────────────────────────────────────────────────────
  Install:
──────────────────────────────────────────────────────────────────────────────────────────────

  + pytorch-mutex                   1.0  cuda                         pytorch         Cached
  + _libgcc_mutex                   0.1  conda_forge                  conda-forge     Cached
  + libstdcxx-ng                 13.2.0  h7e041cc_2                   conda-forge     Cached
  + python_abi                      3.8  4_cp38                       conda-forge     Cached
  + ld_impl_linux-64               2.40  h41732ed_0                   conda-forge     Cached
  + ca-certificates           2023.7.22  hbcca054_0                   conda-forge     Cached
  + libgfortran4                  7.5.0  h14aa051_20                  conda-forge     Cached
  + libgomp                      13.2.0  h807b86a_2                   conda-forge     Cached
  + libgfortran-ng                7.5.0  h14aa051_20                  conda-forge     Cached
  + _openmp_mutex                   4.5  2_gnu                        conda-forge     Cached
  + libgcc-ng                    13.2.0  h807b86a_2                   conda-forge     Cached
  + libev                          4.33  h516909a_1                   conda-forge     Cached
  + c-ares                       1.20.1  hd590300_1                   conda-forge     Cached
  + libuv                        1.46.0  hd590300_0                   conda-forge     Cached
  + yaml                          0.2.5  h7f98852_2                   conda-forge     Cached
  + libiconv                       1.17  h166bdaf_0                   conda-forge     Cached
  + gettext                      0.21.1  h27087fc_0                   conda-forge     Cached
  + libexpat                      2.5.0  hcb278e6_1                   conda-forge     Cached
  + keyutils                      1.6.1  h166bdaf_0                   conda-forge     Cached
  + ncurses                         6.4  hcb278e6_0                   conda-forge     Cached
  + xz                            5.2.6  h166bdaf_0                   conda-forge     Cached
  + libnsl                        2.0.1  hd590300_0                   conda-forge     Cached
  + libffi                        3.4.2  h7f98852_5                   conda-forge     Cached
  + bzip2                         1.0.8  h7f98852_4                   conda-forge     Cached
  + libzlib                      1.2.13  hd590300_5                   conda-forge     Cached
  + openssl                       3.1.4  hd590300_0                   conda-forge     Cached
  + libabseil                20230802.1  cxx17_h59595ed_0             conda-forge     Cached
  + cudatoolkit                  11.1.1  hb139c0e_12                  conda-forge     Cached
  + libuuid                      2.38.1  h0b41bf4_0                   conda-forge     Cached
  + expat                         2.5.0  hcb278e6_1                   conda-forge     Cached
  + libedit                3.1.20191231  he28a2e2_2                   conda-forge     Cached
  + readline                        8.2  h8228510_1                   conda-forge     Cached
  + perl                         5.32.1  4_hd590300_perl5             conda-forge     Cached
  + pcre2                         10.37  hc3806b6_1                   conda-forge     Cached
  + zstd                          1.5.5  hfc55251_0                   conda-forge     Cached
  + libsqlite                    3.43.2  h2797004_0                   conda-forge     Cached
  + zlib                         1.2.13  hd590300_5                   conda-forge     Cached
  + tk                           8.6.13  h2797004_0                   conda-forge     Cached
  + libnghttp2                   1.52.0  h61bc06f_0                   conda-forge     Cached
  + libssh2                      1.11.0  h0841786_0                   conda-forge     Cached
  + libprotobuf                  4.24.3  hf27288f_1                   conda-forge     Cached
  + krb5                         1.21.2  h659d440_0                   conda-forge     Cached
  + python                       3.8.18  hd12c33a_0_cpython           conda-forge     Cached
  + libsentencepiece             0.1.99  h1462b79_4                   conda-forge     Cached
  + libcurl                       8.4.0  hca28451_0                   conda-forge     Cached
  + sentencepiece-spm            0.1.99  h1462b79_4                   conda-forge     Cached
  + curl                          8.4.0  hca28451_0                   conda-forge     Cached
  + git                          2.35.1  pl5321h04cb727_0             conda-forge     Cached
  + intel-openmp               2023.1.0  hdb19cb5_46305               pkgs/main       Cached
  + mkl                          2020.2  256                          pkgs/main       Cached
  + wheel                        0.41.2  pyhd8ed1ab_0                 conda-forge     Cached
  + setuptools                   68.2.2  pyhd8ed1ab_0                 conda-forge     Cached
  + pip                          23.3.1  pyhd8ed1ab_0                 conda-forge     Cached
  + typing_extensions             4.8.0  pyha770c72_0                 conda-forge     Cached
  + pycparser                      2.21  pyhd8ed1ab_0                 conda-forge     Cached
  + webencodings                  0.5.1  pyhd8ed1ab_2                 conda-forge     Cached
  + idna                            3.4  pyhd8ed1ab_0                 conda-forge     Cached
  + cachelib                     0.10.2  pyhd8ed1ab_0                 conda-forge     Cached
  + bidict                       0.22.1  pyhd8ed1ab_0                 conda-forge     Cached
  + six                          1.16.0  pyh6c4a22f_0                 conda-forge     Cached
  + itsdangerous                  2.1.2  pyhd8ed1ab_0                 conda-forge     Cached
  + click                         8.1.7  unix_pyh707e725_0            conda-forge     Cached
  + zipp                         3.17.0  pyhd8ed1ab_0                 conda-forge     Cached
  + packaging                      23.2  pyhd8ed1ab_0                 conda-forge     Cached
  + termcolor                     2.3.0  pyhd8ed1ab_0                 conda-forge     Cached
  + colorama                      0.4.6  pyhd8ed1ab_0                 conda-forge     Cached
  + h11                          0.14.0  pyhd8ed1ab_0                 conda-forge     Cached
  + importlib-metadata            6.8.0  pyha770c72_0                 conda-forge     Cached
  + marshmallow                  3.20.1  pyhd8ed1ab_0                 conda-forge     Cached
  + bleach                        4.1.0  pyhd8ed1ab_0                 conda-forge     Cached
  + wsproto                       1.2.0  pyhd8ed1ab_0                 conda-forge     Cached
  + markdown                        3.5  pyhd8ed1ab_0                 conda-forge     Cached
  + simple-websocket              1.0.0  pyhd8ed1ab_1                 conda-forge     Cached
  + python-engineio               4.8.0  pyhd8ed1ab_0                 conda-forge     Cached
  + python-socketio               5.7.2  pyhd8ed1ab_0                 conda-forge     Cached
  + libblas                       3.8.0  16_mkl                       conda-forge     Cached
  + pyyaml                        6.0.1  py38h01eb140_1               conda-forge     Cached
  + markupsafe                    2.1.3  py38h01eb140_1               conda-forge     Cached
  + greenlet                      3.0.0  py38h17151c0_1               conda-forge     Cached
  + psutil                        5.9.5  py38h01eb140_1               conda-forge     Cached
  + loguru                        0.7.2  py38h578d9bd_1               conda-forge     Cached
  + protobuf                     4.24.3  py38hf14ab21_1               conda-forge     Cached
  + sentencepiece-python         0.1.99  py38h877d47d_4               conda-forge     Cached
  + cffi                         1.16.0  py38h6d47a40_0               conda-forge     Cached
  + liblapack                     3.8.0  16_mkl                       conda-forge     Cached
  + libcblas                      3.8.0  16_mkl                       conda-forge     Cached
  + sentencepiece                0.1.99  h578d9bd_4                   conda-forge     Cached
  + cryptography                 41.0.5  py38hcdda232_0               conda-forge     Cached
  + liblapacke                    3.8.0  16_mkl                       conda-forge     Cached
  + blas                           2.16  mkl                          conda-forge     Cached
  + apispec                       6.3.0  pyhd8ed1ab_0                 conda-forge     Cached
  + werkzeug                      3.0.0  pyhd8ed1ab_0                 conda-forge     Cached
  + jinja2                        3.1.2  pyhd8ed1ab_1                 conda-forge     Cached
  + pyopenssl                    23.2.0  pyhd8ed1ab_1                 conda-forge     Cached
  + dnspython                     2.2.1  pyhd8ed1ab_0                 conda-forge     Cached
  + apispec-webframeworks         0.5.2  pyhd8ed1ab_4                 conda-forge     Cached
  + flask                         2.2.3  pyhd8ed1ab_0                 conda-forge     Cached
  + eventlet                     0.33.3  pyhd8ed1ab_0                 conda-forge     Cached
  + flask-session                 0.4.0  pyhd8ed1ab_0                 conda-forge     Cached
  + flask-socketio                5.3.2  pyhd8ed1ab_0                 conda-forge     Cached
  + pytorch                      1.11.0  py3.8_cuda11.1_cudnn8.0.5_0  pytorch         Cached`

**Comment by kurukurukuru** [comment]
Any ideas?

**Comment by lugangqi** [comment]
My M40 24g runs ExLlama the same way, 4060ti 16g works fine under cuda12.4. M40 seems that the author did not update the kernel compatible with it, I also asked for help under the ExLlama2 author yesterday, I do not know whether the author to fix this compatibility problem, M40 and 980ti with the same architecture core computing power 5.2 to meet cuda12.4
