### ISSUE TITLE
QWEN 14B loader error

### ISSUE THREAD

**Issue by better-one** [oobabooga/text-generation-webui#4388]
wen i choise qwen 14b -int4 with transformers，and i open trust-remote-code，than ,there have error：

Traceback (most recent call last):
  File "E:\open\text-generation-webui-main1.9\modules\ui_model_menu.py", line 201, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\open\text-generation-webui-main1.9\modules\models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\open\text-generation-webui-main1.9\modules\models.py", line 136, in huggingface_loader
    model = LoaderClass.from_pretrained(path_to_model, **params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\open\text-generation-webui-main1.9\installer_files\env\Lib\site-packages\transformers\models\auto\auto_factory.py", line 552, in from_pretrained
    model_class = get_class_from_dynamic_module(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\open\text-generation-webui-main1.9\installer_files\env\Lib\site-packages\transformers\dynamic_module_utils.py", line 485, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\open\text-generation-webui-main1.9\installer_files\env\Lib\site-packages\transformers\dynamic_module_utils.py", line 313, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\open\text-generation-webui-main1.9\installer_files\env\Lib\site-packages\transformers\dynamic_module_utils.py", line 179, in check_imports
    raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: transformers_stream_generator. Run `pip install transformers_stream_generator`

**Comment by Husamx** [comment]
either add transformers_stream_generator to requirements.txt and run the update script, or run the command "pip install transformers_stream_generator" from inside your environment

**Comment by Trimad** [comment]
> either add transformers_stream_generator to requirements.txt and run the update script, or run the command "pip install transformers_stream_generator" from inside your environment

This didn't work for me. Neither did enabling trust-remote-code.

This is the model I'm trying to download:
https://huggingface.co/CausalLM/14B

**Comment by FartyPants** [comment]
> > either add transformers_stream_generator to requirements.txt and run the update script, or run the command "pip install transformers_stream_generator" from inside your environment
> 
> This didn't work for me. Neither did enabling trust-remote-code.
> 
> This is the model I'm trying to download: https://huggingface.co/CausalLM/14B

CasualLM doesn't need --trust-remote-code

It works on my end though. If it doesn't on yours, you may need to update transformers as it loads different tokenizer. I also quantized it to GPTQ, because thebloke quant is wrong (again wrong tokenizer) and it works with exllama_HF and exllama2_HF

**Comment by xain** [comment]
> either add transformers_stream_generator to requirements.txt and run the update script, or run the command "pip install transformers_stream_generator" from inside your environment

adding to requirements.txt and updating work.

**Comment by better-one** [comment]
> either add transformers_stream_generator to requirements.txt and run the update script, or run the command "pip install transformers_stream_generator" from inside your environment

when i do this , and run the update_windows.bat ,its not working
