### ISSUE TITLE
Error loading CausalLM-14B-GGUF

### ISSUE THREAD

**Issue by tmsingson** [oobabooga/text-generation-webui#4404]
### Describe the bug

Cannot load CausalLM-14B-GGUF. I have tried llama.cpp, llama.cpp_HF, and ctransformers but all failed to load the model. Other GGUF files can be loaded just fine.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I have tried to unload and reload the file several times. I have also re-downloaded the file from HuggingFace multiple times and also tried different quant sizes. 
I am able to load other GGUF files just fine.

### Logs

```shell
2023-10-27 16:23:30 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "E:\Apps\text-generation-webui-snapshot-2023-10-22\modules\ui_model_menu.py", line 201, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Apps\text-generation-webui-snapshot-2023-10-22\modules\models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Apps\text-generation-webui-snapshot-2023-10-22\modules\models.py", line 234, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Apps\text-generation-webui-snapshot-2023-10-22\modules\llamacpp_model.py", line 91, in from_pretrained
    result.model = Llama(**params)
                   ^^^^^^^^^^^^^^^
  File "E:\Apps\text-generation-webui-snapshot-2023-10-22\installer_files\env\Lib\site-packages\llama_cpp_cuda\llama.py", line 357, in __init__
    self.model = llama_cpp.llama_load_model_from_file(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Apps\text-generation-webui-snapshot-2023-10-22\installer_files\env\Lib\site-packages\llama_cpp_cuda\llama_cpp.py", line 498, in llama_load_model_from_file
    return _lib.llama_load_model_from_file(path_model, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: exception: access violation reading 0x0000000000000000

Exception ignored in: <function LlamaCppModel.__del__ at 0x000001BC34FE8220>
Traceback (most recent call last):
  File "E:\Apps\text-generation-webui-snapshot-2023-10-22\modules\llamacpp_model.py", line 49, in __del__
    self.model.__del__()
    ^^^^^^^^^^
AttributeError: 'LlamaCppModel' object has no attribute 'model'
```

### System Info

```shell
Windows 11, NVIDIA 3060 Ti
```

**Comment by JohanAR** [comment]
I don't think CausalLM is working with llama-cpp-python currently. You could try loading the model directly with llama.cpp, i.e. without ooba's webui, and see if it works there.
