### ISSUE TITLE
ngrok extension causing crash 

### ISSUE THREAD

**Issue by eduardm** [oobabooga/text-generation-webui#4413]
### Describe the bug

If the ngrok extension is enabled, the WebUI crashes immediately. 

The error is:

```
ERROR:Task exception was never retrieved
future: <Task finished name='Task-8' coro=<Queue.start_processing() done, defined at /home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/s
ite-packages/gradio/queueing.py:127> exception=TypeError("'NoneType' object does not support the asynchronous context manager protocol")>
Traceback (most recent call last):
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/queueing.py", line 137, in start_processing
    async with self.delete_lock:
TypeError: 'NoneType' object does not support the asynchronous context manager protocol
```

Disabling ngrok extension removes the error.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Enable ngrok extension.

Here is the content of my settings.yml

```
dark_theme: true
show_controls: true
start_with: ''
mode: chat
chat_style: cai-chat
prompt-default: QA
prompt-notebook: QA
preset: simple-1
max_new_tokens: 200
max_new_tokens_min: 1
max_new_tokens_max: 4096
seed: -1
negative_prompt: ''
truncation_length: 32768
truncation_length_min: 0
truncation_length_max: 32768
custom_stopping_strings: ''
auto_max_new_tokens: false
max_tokens_second: 0
ban_eos_token: false
custom_token_bans: ''
add_bos_token: true
skip_special_tokens: true
stream: true
name1: You
character: Assistant
instruction_template: Mistral
chat-instruct_command: |-
  Continue the chat dialogue below. Write a single reply for the character "<|character|>".

  <|prompt|>
autoload_model: false
default_extensions:
- api
- openai
- gallery
- ngrok
```

After starting the UI with ./start_linux.sh, everything boots normally, without errors

Open the UI, it will crash instantly with this error:

```
ERROR:Task exception was never retrieved
future: <Task finished name='Task-8' coro=<Queue.start_processing() done, defined at /home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/s
ite-packages/gradio/queueing.py:127> exception=TypeError("'NoneType' object does not support the asynchronous context manager protocol")>
Traceback (most recent call last):
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/queueing.py", line 137, in start_processing
    async with self.delete_lock:
TypeError: 'NoneType' object does not support the asynchronous context manager protocol
```

Remove ngrok from settings.yml, everything works just fine.

### Screenshot

<img width="1728" alt="image" src="https://github.com/oobabooga/text-generation-webui/assets/33600/ff738e0f-64eb-4055-8a8d-86b41782d82b">

### Logs

```shell
ERROR:Task exception was never retrieved
future: <Task finished name='Task-8' coro=<Queue.start_processing() done, defined at /home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/s
ite-packages/gradio/queueing.py:127> exception=TypeError("'NoneType' object does not support the asynchronous context manager protocol")>
Traceback (most recent call last):
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/queueing.py", line 137, in start_processing
    async with self.delete_lock:
TypeError: 'NoneType' object does not support the asynchronous context manager protocol
```
```


### System Info

```shell
AWS g5.2xlarge machine running Ubuntu 22.04 (A10GPU).

Fresh install, checkout from repo and run ./start_linux.sh.
```

**Comment by iongpt** [comment]
I can consistently reproduce this

**Comment by antonkulaga** [comment]
Same issue, any workarounds?

**Comment by iongpt** [comment]
@antonkulaga you should disable the ngrok extention. Use built in Cloudflare sharing option (links expire every 72 hours) via --share --public-api flags
