### ISSUE TITLE
Openbuddy falcon support?

### ISSUE THREAD

**Issue by mykeehu** [oobabooga/text-generation-webui#4439]
### Describe the bug

I tried to load the 7B and 40B GGUF models (OpenBuddy-openbuddy-falcon-40b-v9-bf16-Q3_K_M.gguf), but failed, I got the same error in llama.cpp for both.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Csak megpróbáltam betölteni bármelyik Openbuddy GGUF modellt, hibát kaptam.

### Logs

```shell
llama_model_loader: - type  f32:  242 tensors
llama_model_loader: - type q8_0:    1 tensors
llama_model_loader: - type q3_K:  151 tensors
llama_model_loader: - type q4_K:   88 tensors
llama_model_loader: - type q5_K:    2 tensors
ERROR: byte not found in vocab: '
'
2023-11-01 20:50:24 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "I:\oobabooga_windows\text-generation-webui\modules\ui_model_menu.py", line 206, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\oobabooga_windows\text-generation-webui\modules\models.py", line 84, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\oobabooga_windows\text-generation-webui\modules\models.py", line 235, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 91, in from_pretrained
    result.model = Llama(**params)
                   ^^^^^^^^^^^^^^^
  File "I:\oobabooga_windows\text-generation-webui\installer_files\env\Lib\site-packages\llama_cpp_cuda\llama.py", line 357, in __init__
    self.model = llama_cpp.llama_load_model_from_file(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\oobabooga_windows\text-generation-webui\installer_files\env\Lib\site-packages\llama_cpp_cuda\llama_cpp.py", line 498, in llama_load_model_from_file
    return _lib.llama_load_model_from_file(path_model, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: exception: access violation reading 0x0000000000000000

Exception ignored in: <function LlamaCppModel.__del__ at 0x000001F687A95260>
Traceback (most recent call last):
  File "I:\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py", line 49, in __del__
    self.model.__del__()
    ^^^^^^^^^^
AttributeError: 'LlamaCppModel' object has no attribute 'model'
```

### System Info

```shell
i9-13900K
64 GB RAM
RTX 3090 24 GB
Windows 10 64-bit
```

**Comment by Ph0rk0z** [comment]
Update and compile llama-cpp-python for the latest commits instead of using the wheels.

**Comment by ye7iaserag** [comment]
Same problem with DeepSeek even with today's commit
