### ISSUE TITLE
Extensions do not load if they contain "-" in the name

### ISSUE THREAD

**Issue by PaulCoddington** [oobabooga/text-generation-webui#4466]
### Describe the bug

Extensions that contain the "-" character as part of their name fail to load.

Workaround: manually rename cloned extensions to use "_" instead. However, this means extensions must use a different naming convention to other Git-managed projects.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Clone and attempt to load the extension:

`text-gen-webui-ui_tweaks`

Extension fails to load unless manually renamed to:

`text_gen_webui_ui_tweaks` (or similar)

### Screenshot

n.a.

### Logs

```shell
Traceback (most recent call last):
  File "C:\ProgramData\oobabooga\text-generation-webui\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1
    import extensions.text-gen-webui-ui_tweaks.script
```

### System Info

```shell
Windows 11 Pro 22H2
NVIDIA GeForce RTX 2060 Super
```

**Comment by schwarztim** [comment]
It seems like it would be easier to just rename the extension. I made your recommended changes, and then the rest of the extensions ended up failing to run.

**Comment by schwarztim** [comment]
Yeah, I did just that, and it worked swimmingly. https://github.com/schwarztim/text_gen_webui_ui_tweaks/tree/main
@xanthousm
