### ISSUE TITLE
AttributeError: 'LlamaCppModel' object has no attribute 'model'

### ISSUE THREAD

**Issue by BartAgterbosch** [oobabooga/text-generation-webui#4471]
### Describe the bug

So, essentially I'm running the Cuda version on windows, with an RTX 3060ti, 5600x, and 16 gigs of ram, now the only models I seem to be able to load are any GGUF Q5 models using either llama.cpp or llamacpp_HF, using anything even remotely else will cause an AttributeError of some sort.
To be more specific in this case, any GGUF model that is anything other than Q5 will result in "AttributeError: 'LlamaCppModel' object has no attribute 'model'".
I seem to have found a post that said it was because moving to ggmlv3 broke something that causes "older" models to no longer work? But surely that doesn't mean everything other than Q5 GGUF models? Am I maybe missing some requirements or something? It's a fairly fresh install of at most a week old, so it should be fairly up-to-date.
Is there any way to solve this? Or maybe some indication as to what I might have done wrong or might be missing here?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Just load anything other than a Q5 GGUF model

### Logs

```shell
Traceback (most recent call last):

File "C:\Users\Agterbosch\textgen\modules\ui_model_menu.py", line 206, in load_model_wrapper

shared.model, shared.tokenizer = load_model(shared.model_name, loader)

                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "C:\Users\Agterbosch\textgen\modules\models.py", line 84, in load_model

output = load_func_map[loader](model_name)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "C:\Users\Agterbosch\textgen\modules\models.py", line 235, in llamacpp_loader

model, tokenizer = LlamaCppModel.from_pretrained(model_file)

                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "C:\Users\Agterbosch\textgen\modules\llamacpp_model.py", line 91, in from_pretrained

result.model = Llama(**params)

               ^^^^^^^^^^^^^^^

File "D:\Users\Agterbosch\miniconda3\envs\textgen\Lib\site-packages\llama_cpp_cuda\llama.py", line 357, in init

self.model = llama_cpp.llama_load_model_from_file(

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "D:\Users\Agterbosch\miniconda3\envs\textgen\Lib\site-packages\llama_cpp_cuda\llama_cpp.py", line 498, in llama_load_model_from_file

return _lib.llama_load_model_from_file(path_model, params)

       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

OSError: exception: access violation reading 0x0000000000000000

Exception ignored in: <function LlamaCppModel.__del__ at 0x000001A807056E80>
Traceback (most recent call last):
File "C:\Users\Agterbosch\textgen\modules\llamacpp_model.py", line 49, in __del__
  self.model.__del__()
  ^^^^^^^^^^
AttributeError: 'LlamaCppModel' object has no attribute 'model'
```

### System Info

```shell
Windows 10 22h2
Aorus Geforce RTX 3060Ti
Ryzen 5 5600x
16gb ram 3200mhz
```

**Comment by cvinker** [comment]
Same error loading alfred-40b-1023.Q4_K_M.gguf on Win 10 22H2, RTX 3050, 32GB ram.

**Comment by Erinaceida** [comment]
Still relevant, same here on nous-hermes-llama2-13b.Q5_0.gguf

**Comment by batuco9** [comment]
Agree, still happens
