### ISSUE TITLE
No longer able to load 4bit 7B GPTQ Models on RTX 3050 8GB

### ISSUE THREAD

**Issue by coderkei** [oobabooga/text-generation-webui#4480]
### Describe the bug

In previous versions of text-generation-webui I was able to load 4bit quantized 7B GPTQ models on my 8GB RTX 3050. After updating to the latest version and migrating from the one-click installer to the new format, I am now no longer able to load these models because I get an error stating it has run out of memory.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Download Zephyr (Mistral finetune) 7B quantized 4 bit model, attempt to load model with default settings in ExLlama_HF.
Model will attempt to load and then fail with `torch.cuda.OutOfMemoryError: CUDA out of memory. `

In previous versions this model would load as expected. There have been no configuration or hardware changes.

### Logs

```shell
2023-11-04 20:28:33 INFO:Loading TheBloke_zephyr-7B-alpha-GPTQ...
2023-11-04 20:28:44 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/home/kai/Documents/TextAI/text-generation-webui/modules/ui_model_menu.py", line 209, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kai/Documents/TextAI/text-generation-webui/modules/models.py", line 84, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kai/Documents/TextAI/text-generation-webui/modules/models.py", line 348, in ExLlama_HF_loader
    return ExllamaHF.from_pretrained(model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kai/Documents/TextAI/text-generation-webui/modules/exllama_hf.py", line 174, in from_pretrained
    return ExllamaHF(config)
           ^^^^^^^^^^^^^^^^^
  File "/home/kai/Documents/TextAI/text-generation-webui/modules/exllama_hf.py", line 35, in __init__
    self.ex_cache = ExLlamaCache(self.ex_model)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kai/Documents/TextAI/text-generation-webui/installer_files/env/lib/python3.11/site-packages/exllama/model.py", line 576, in __init__
    p_key_states = torch.zeros(self.batch_size, self.config.num_key_value_heads, self.max_seq_len, self.config.head_dim, dtype = torch.float16, device = self.model.config.device_map.layers[i])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 MiB. GPU 0 has a total capacty of 7.78 GiB of which 33.00 MiB is free. Including non-PyTorch memory, this process has 7.43 GiB memory in use. Of the allocated memory 7.30 GiB is allocated by PyTorch, and 29.13 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### System Info

```shell
Operating System: Ubuntu 22.04 LTS
GPU Brand: Palit
GPU Model: Nvidia RTX 3050 8GB
```

**Comment by coderkei** [comment]
Closing the issue. It appears the max sequence length for ExLlama was erroneously set to the max. Possibly a result of the migration.
