### ISSUE TITLE
Support for Yi-6/34B

### ISSUE THREAD

**Issue by IdiotSandwichTheThird** [oobabooga/text-generation-webui#4483]
https://huggingface.co/01-ai/Yi-34B
https://huggingface.co/01-ai/Yi-6B

Model seems pretty good at benchmarks. Architecture is mostly the same as LLama2, with renamed layernorm.
exllama2 seems to have[ added support](https://github.com/turboderp/exllamav2/commit/6d24e1ad40d89f64b1bd3ae36e639c74c9f730b2) but there is an issue loading the tokenizer for now.

**Comment by Ph0rk0z** [comment]
It works just fine if you enable trust remote code.

**Comment by jepjoo** [comment]
Tried exl2 and it's not loading for me on Windows 11 (no option to trust remote code):

2023-11-06 15:44:45 INFO:Loading LoneStriker_Yi-6B-Spicyboros-3.1-6.0bpw-h6-exl2...
2023-11-06 15:44:45 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "G:\oobabooga\modules\ui_model_menu.py", line 209, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "G:\oobabooga\modules\models.py", line 84, in load_model
    output = load_func_map[loader](model_name)
  File "G:\oobabooga\modules\models.py", line 361, in ExLlamav2_HF_loader
    return Exllamav2HF.from_pretrained(model_name)
  File "G:\oobabooga\modules\exllamav2_hf.py", line 162, in from_pretrained
    config.prepare()
  File "G:\oobabooga\installer_files\env\lib\site-packages\exllamav2\config.py", line 133, in prepare
    raise ValueError(f" ## Could not find {prefix}.* in model")
ValueError:  ## Could not find model.layers.0.input_layernorm.* in model

**Comment by Ph0rk0z** [comment]
You need to compile it and not use the wheel. The wheel gets updated when he versions a new one.

**Comment by IdiotSandwichTheThird** [comment]
> It works just fine if you enable trust remote code. In plain exllamav2 it just works.

Hadn't tested that, and you're right. It would be nice to be able to use it in exllama2hf though.
