### ISSUE TITLE
I'm getting an issue when select Model Loader

### ISSUE THREAD

**Issue by alportblu** [oobabooga/text-generation-webui#4485]
### Describe the bug

Hi everyone, hope you all are doing well.

I'm getting the issue below when I try to select any Model Loader. 
![image](https://github.com/oobabooga/text-generation-webui/assets/59105422/9d45b2a0-2a04-4c09-9496-fe7f88d4081b)

Thank you,

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Just select the Model and tried to select the Model Loader.

Getting this issue.

Thank you,

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/59105422/9985cca0-3adc-47a2-8d93-6b758b9afeb8)

### Logs

```shell
2023-11-05 21:13:22 INFO:Loading TheBloke_calm2-7B-chat-GPTQ...
2023-11-05 21:13:22 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/home/alport/gepeto/text-generation-webui/modules/ui_model_menu.py", line 209, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/home/alport/gepeto/text-generation-webui/modules/models.py", line 84, in load_model
    output = load_func_map[loader](model_name)
  File "/home/alport/gepeto/text-generation-webui/modules/models.py", line 333, in AutoGPTQ_loader
    import modules.AutoGPTQ_loader
  File "/home/alport/gepeto/text-generation-webui/modules/AutoGPTQ_loader.py", line 4, in <module>
    from auto_gptq import AutoGPTQForCausalLM, BaseQuantizeConfig
ModuleNotFoundError: No module named 'auto_gptq'
```

### System Info

```shell
Kali Linux - WSL
```

**Comment by Mulakulu** [comment]
I'm getting the exact same thing. You're not the only one

**Comment by Mulakulu** [comment]
I'm getting the following error in the console when launching the program:
D:\Tools\text-generation-webui\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
function 'cadam32bit_grad_fp32' not found

Note that I tried this on an older version and it worked fine there.

**Comment by karljoaquin** [comment]
Same issue here. Following.

**Comment by JustMikess** [comment]
> I'm getting the following error in the console when launching the program: D:\Tools\text-generation-webui\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable. warn("The installed version of bitsandbytes was compiled without GPU support. " function 'cadam32bit_grad_fp32' not found
> 
> Note that I tried this on an older version and it worked fine there.

I had this issue, but installing CUDA toolkit resolved this for me.

**Comment by ergunkocak** [comment]
on M1 Max:

2023-11-29 17:22:23 INFO:Loading TheBloke_WizardCoder-15B-1.0-GPTQ...
2023-11-29 17:22:23 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/Users/tiger/projects/text-generation-webui2/modules/ui_model_menu.py", line 209, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tiger/projects/text-generation-webui2/modules/models.py", line 85, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tiger/projects/text-generation-webui2/modules/models.py", line 342, in AutoGPTQ_loader
    import modules.AutoGPTQ_loader
  File "/Users/tiger/projects/text-generation-webui2/modules/AutoGPTQ_loader.py", line 4, in <module>
    from auto_gptq import AutoGPTQForCausalLM, BaseQuantizeConfig
ModuleNotFoundError: No module named 'auto_gptq'

**Comment by Kota-11711406** [comment]
still getting the error
