### ISSUE TITLE
Need to reinstall Oogabooga every time CMD is closed

### ISSUE THREAD

**Issue by Xhavi14** [oobabooga/text-generation-webui#4490]
### Describe the bug

The  Oogabooga works properly during its initial execution. However, when the cmd is closed along with everything else  the program does not start correctly. tried to attempt to solve it with the update thing and nothing, This problem is somewhat solved by only reinstalling Oogabooga on every shutdown, resulting in an annoying experience every time i want to use the ai locally

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Reproduction

Running the /Startwindows.bat after closing the cmd after the first time

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/150063521/271640f4-3a69-4dd8-804a-488f632ebb13)

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\Xavier\Downloads\text-generation-webui-main\server.py", line 30, in <module>
    import modules.extensions as extensions_module
  File "C:\Users\Xavier\Downloads\text-generation-webui-main\modules\extensions.py", line 8, in <module>
    import modules.shared as shared
  File "C:\Users\Xavier\Downloads\text-generation-webui-main\modules\shared.py", line 266, in <module>
    model_config = yaml.safe_load(open(p, 'r').read())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xavier\Downloads\text-generation-webui-main\installer_files\env\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xavier\Downloads\text-generation-webui-main\installer_files\env\Lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xavier\Downloads\text-generation-webui-main\installer_files\env\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xavier\Downloads\text-generation-webui-main\installer_files\env\Lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xavier\Downloads\text-generation-webui-main\installer_files\env\Lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xavier\Downloads\text-generation-webui-main\installer_files\env\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xavier\Downloads\text-generation-webui-main\installer_files\env\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xavier\Downloads\text-generation-webui-main\installer_files\env\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xavier\Downloads\text-generation-webui-main\installer_files\env\Lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xavier\Downloads\text-generation-webui-main\installer_files\env\Lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "C:\Users\Xavier\Downloads\text-generation-webui-main\installer_files\env\Lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xavier\Downloads\text-generation-webui-main\installer_files\env\Lib\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xavier\Downloads\text-generation-webui-main\installer_files\env\Lib\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "C:\Users\Xavier\Downloads\text-generation-webui-main\installer_files\env\Lib\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 57, column 1:
    <<<<<<< Updated upstream
    ^
could not find expected ':'
  in "<unicode string>", line 58, column 1:
    .*galactica:
    ^
Presione una tecla para continuar . . .
```

### System Info

```shell
Windows 10 Home
Nvidia GTX 1060
intel core i7 6700 HQ
```

**Comment by sen3d** [comment]
I had a similar problem. But when I deleted the config.yaml and config-user.yaml from the models folder it worked again. I assume the error is with those files or how they are accessed.
