### ISSUE TITLE
ERROR:Failed to load the extension "superboogav2" on  Linux system

### ISSUE THREAD

**Issue by elabz** [oobabooga/text-generation-webui#4504]
### Describe the bug

On Linux system
**superboogav2 extension does not load due to** 
`ModuleNotFoundError: No module named 'chromadb'`

I have researched previous reports of the same issue and have done all the steps outlined in previous  resolutions, to no avail:

(base) boss@ubuntu2023:~/text-generation-webui$ source ./installer_files/conda/etc/profile.d/conda.sh
(base) boss@ubuntu2023:~/text-generation-webui$ conda activate ./installer_files/env
(/home/boss/text-generation-webui/installer_files/env) boss@ubuntu2023:~/text-generation-webui$ ./installer_files/env/bin/python --version
Python 3.10.13
(/home/boss/text-generation-webui/installer_files/env) boss@ubuntu2023:~/text-generation-webui$ ./installer_files/env/bin/python -m pip install -r ./extensions/superboogav2/requirements.txt

This results in 
`Requirement already satisfied: chromadb==0.3.18 in /home/boss/.local/lib/python3.10/site-packages (from -r ./extensions/superboogav2/requirements.txt (line 2)) (0.3.18)
`
among other "requirement already satisfied"

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

To reproduce: one requirements installed as in the above, restart Ooba
`
(/home/boss/text-generation-webui/installer_files/env) boss@ubuntu2023:~/text-generation-webui$ ./start_linux.sh --listen
2023-11-07 03:36:44 WARNING:
You are potentially exposing the web UI to the entire internet without any access password.
You can create one with the "--gradio-auth" flag like this:

--gradio-auth username:password

Make sure to replace username:password with your own.
2023-11-07 03:36:46 INFO:Loading settings from settings.yaml...
2023-11-07 03:36:46 WARNING:
The current API is deprecated and will be replaced with the OpenAI compatible API on November 13th.
To test the new API, use "--extensions openai" instead of "--api".
For documentation on the new API, consult:
https://github.com/oobabooga/text-generation-webui/wiki/12-%E2%80%90-OpenAI-API
2023-11-07 03:36:46 INFO:Streaming API URL:

ws://0.0.0.0:5005/api/v1/stream

2023-11-07 03:36:46 INFO:Blocking API URL:

http://0.0.0.0:5000/api

Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
`

Then go to Session  tab of Ooba UI , select superboogav2 in extensions and then "Apply flags/extensions and restart"

Error will be produced:

`
Closing server running on port: 7860
2023-11-07 03:37:03 INFO:Loading the extension "superboogav2"...
2023-11-07 03:37:03 ERROR:Failed to load the extension "superboogav2".
Traceback (most recent call last):
  File "/home/boss/text-generation-webui/modules/extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "/home/boss/text-generation-webui/extensions/superboogav2/script.py", line 20, in <module>
    from .chromadb import make_collector
  File "/home/boss/text-generation-webui/extensions/superboogav2/chromadb.py", line 2, in <module>
    import chromadb
ModuleNotFoundError: No module named 'chromadb'
`

### Logs

```shell
`Traceback (most recent call last):
  File "/home/boss/text-generation-webui/modules/extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "/home/boss/text-generation-webui/extensions/superboogav2/script.py", line 20, in <module>
    from .chromadb import make_collector
  File "/home/boss/text-generation-webui/extensions/superboogav2/chromadb.py", line 2, in <module>
    import chromadb
ModuleNotFoundError: No module named 'chromadb'
`
```

### System Info

```shell
Ubuntu 22.04
`$ uname -a
Linux ubuntu2023 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
`
```

**Comment by BarfingLemurs** [comment]
I also run Ubuntu 22.04 and can't use the extension

**Comment by Maxzurek** [comment]
I get the same error on windows 11, release: https://github.com/oobabooga/text-generation-webui/releases/tag/snapshot-2023-11-19. The superbooga (v1) extension is also not working (same error).

**Comment by Jewbby** [comment]
Same here on windows 11.

**Comment by mrtkrcm** [comment]
just run `INSTALL_EXTENSIONS=true ./update_linux.sh` which will also install the modules from the extensions.

**Comment by TheDarkTrumpet** [comment]
There's likely a bit more than that you'll need to do.

In the requirements.txt, for this extension, you have chromadb at 0.3.18.  It's a fairly old version of chromadb.  Their requirements don't pin pydantic properly, and the 2.X branch is incompatible with this version of Chromadb.  You'll likely need to also run:

```
pip uninstall pydantic
pip install pydantic==1.10.13
```

I think the requirements in the extension need to be modified to account for this.  Since it's an easy change I'll do a pull request and attach it to here.

**Comment by TheDarkTrumpet** [comment]
Apparently someone's done one already to solve this issue: https://github.com/oobabooga/text-generation-webui/pull/5091
