### ISSUE TITLE
Running Output Errors in Windows:  “ module 'gradio' has no attribute 'Box'”

### ISSUE THREAD

**Issue by alex9441** [oobabooga/text-generation-webui#4508]
I'm getting an error when running start_windows.bat: AttributeError: module 'gradio' has no attribute 'Box'

Traceback (most recent call last):
  File "C:\0_text-generation-webui\text-generation-webui-main\server.py", line 230, in <module>
    create_interface()
  File "C:\text-generation-webui-main\server.py", line 117, in create_interface
    ui_model_menu.create_ui()  # Model tab
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui-main\modules\ui_model_menu.py", line 77, in create_ui
    with gr.Box():
         ^^^^^^
  AttributeError: module 'gradio' has no attribute 'Box'

**Comment by alex9441** [comment]
This issue has been resolved by upgrading the installer.

**Comment by wortkraecker** [comment]
wdym by upgrading the installer?
I'm trying to run server.py and get the same error

**Comment by alex9441** [comment]
> wdym by upgrading the installer? I'm trying to run server.py and get the same error

What I did was to run "update_windows.bat" in a brand new blank folder, download all the files from the new download, and then run start_Windows.bat to install them, and the problem was solved.

**Comment by wortkraecker** [comment]
Thank you, now it's working

**Comment by robbe1828** [comment]
> > wdym by upgrading the installer? I'm trying to run server.py and get the same error
> 
> What I did was to run "update_windows.bat" in a brand new blank folder, download all the files from the new download, and then run start_Windows.bat to install them, and the problem was solved.

![error](https://github.com/oobabooga/text-generation-webui/assets/151371377/7a6426e1-ede3-46e2-829b-1aa3c3a68d17)

Hi guys, I get the same error but for me it's hard to understand exactly what you mean with run update in a brand new blank folder etc .. 

can you specifiy it step by step please ? 

Would be a great help !

**Comment by alex9441** [comment]
> > > wdym by upgrading the installer? I'm trying to run server.py and get the same error
> > 
> > 
> > What I did was to run "update_windows.bat" in a brand new blank folder, download all the files from the new download, and then run start_Windows.bat to install them, and the problem was solved.
> 
> ![error](https://user-images.githubusercontent.com/151371377/283996100-7a6426e1-ede3-46e2-829b-1aa3c3a68d17.JPG)
> 
> Hi guys, I get the same error but for me it's hard to understand exactly what you mean with run update in a brand new blank folder etc ..
> 
> can you specifiy it step by step please ?
> 
> Would be a great help !

What this means is that you can create a new folder and just copy the file update_windows.bat into it and run it.

**Comment by GrisMouche** [comment]
Same issue, and every time when i try to update the requirements it said to me i still have not merge a branch with so cannnot track informations about it.

**Comment by robbe1828** [comment]
Thanks for your reply Alex

Can you send me the link to the file?
I dont find it on github

Op zondag 19 november 2023 schreef alex9441 ***@***.***>:

**Comment by alex9441** [comment]
@robbe1828  @GrisMouche  
I suggest you do a complete reinstallation, please refer to this document https://github.com/oobabooga/text-generation-webui/wiki/Migrating-an-old-one%E2%80%90click-install

**Comment by Bec-k** [comment]
Same problem here, helped above solution with specified version `pip install gradio==3.50`
