### ISSUE TITLE
Collab ImportError: libcudart.so.12

### ISSUE THREAD

**Issue by RCLauri** [oobabooga/text-generation-webui#4517]
### Describe the bug
Colab stopped working.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Colab

### Logs

```shell
/content/text-generation-webui
python server.py --model TheBloke_Wizard-Vicuna-13B-Uncensored-SuperHOT-8K-GPTQ --loader exllamav2 --settings settings-colab.json --share --public-api-id Tunnel_ID --groupsize 128 --wbits 4 --extensions gallery --extensions openai
2023-11-08 21:08:58 INFO:Loading settings from settings-colab.json...
2023-11-08 21:08:58 INFO:Loading TheBloke_Wizard-Vicuna-13B-Uncensored-SuperHOT-8K-GPTQ...
Traceback (most recent call last):
  File "/content/text-generation-webui/server.py", line 223, in <module>
    shared.model, shared.tokenizer = load_model(model_name)
  File "/content/text-generation-webui/modules/models.py", line 85, in load_model
    output = load_func_map[loader](model_name)
  File "/content/text-generation-webui/modules/models.py", line 354, in ExLlamav2_loader
    from modules.exllamav2 import Exllamav2Model
  File "/content/text-generation-webui/modules/exllamav2.py", line 6, in <module>
    from exllamav2 import (
  File "/usr/local/lib/python3.10/dist-packages/exllamav2/__init__.py", line 3, in <module>
    from exllamav2.model import ExLlamaV2
  File "/usr/local/lib/python3.10/dist-packages/exllamav2/model.py", line 17, in <module>
    from exllamav2.cache import ExLlamaV2CacheBase
  File "/usr/local/lib/python3.10/dist-packages/exllamav2/cache.py", line 2, in <module>
    from exllamav2.ext import exllamav2_ext as ext_c
  File "/usr/local/lib/python3.10/dist-packages/exllamav2/ext.py", line 14, in <module>
    import exllamav2_ext
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
```

### System Info

```shell
NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
```

**Comment by nomadflamingo** [comment]
The same error occurs when loading [https://huggingface.co/TheBloke/Phind-CodeLlama-34B-v2-AWQ](https://huggingface.co/TheBloke/Phind-CodeLlama-34B-v2-AWQ) model using AutoAWQ loader.

My guess is that colab doesn't install the cuda runtime correctly, since this was the issue with #4195.

**Comment by NEEToku** [comment]
Yeah downgrading triton to 2.0.0 didn't work for me either. Gonna have to wait on Colab on this one if your gues is right.

**Comment by nomadflamingo** [comment]
Update: I kinda solved the issue if I add the line `!pip install triton==2.0.0 --upgrade` right above `!pip install -r extensions/api/requirements.txt --upgrade` to the notebook. Not sure why it works this time, but I was able to load both mine and yours model.

**Comment by NEEToku** [comment]
That did it for me thanks a lot!

**Comment by nomadflamingo** [comment]
I also came up with an alternative solution that doesn't downgrade triton and pytorch by adding cuda installation cell to the colab right above the "Launch the Web UI" section:

```
!wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
!mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600
!wget https://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda-repo-ubuntu2204-11-8-local_11.8.0-520.61.05-1_amd64.deb
!dpkg -i cuda-repo-ubuntu2204-11-8-local_11.8.0-520.61.05-1_amd64.deb
!cp /var/cuda-repo-ubuntu2204-11-8-local/cuda-*-keyring.gpg /usr/share/keyrings/
!apt-get update
!apt-get -y install cuda
```

If you find any other problems that come with downgrading triton and pytorch, try using this method instead.

**Comment by casper-hansen** [comment]
`pip install https://github.com/casper-hansen/AutoAWQ/releases/download/v0.1.7/autoawq-0.1.7+cu118-cp310-cp310-linux_x86_64.whl`

**Comment by casper-hansen** [comment]
Google Colab is using old dependencies, which you can still get from the GitHub release.

```
pip install https://github.com/casper-hansen/AutoAWQ/releases/download/v0.1.7/autoawq-0.1.7+cu118-cp310-cp310-linux_x86_64.whl
```
