### ISSUE TITLE
ERROR:The path to the model does not exist

### ISSUE THREAD

**Issue by stefangweichinger** [oobabooga/text-generation-webui#4528]
### Describe the bug

fresh docker image does not start correctly

Same models-subdir worked with older commits.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

* git pull (currently at commit 4da00b60323120bab0b3aa8e6136e4cadbf1f1b5)
* docker-compose build
* docker-compose up

### Logs

```shell
text-generation-webui-text-generation-webui-1  | 2023-11-09 08:40:02 WARNING:
text-generation-webui-text-generation-webui-1  | You are potentially exposing the web UI to the entire internet without any access password.
text-generation-webui-text-generation-webui-1  | You can create one with the "--gradio-auth" flag like this:
text-generation-webui-text-generation-webui-1  | 
text-generation-webui-text-generation-webui-1  | --gradio-auth username:password
text-generation-webui-text-generation-webui-1  | 
text-generation-webui-text-generation-webui-1  | Make sure to replace username:password with your own.
text-generation-webui-text-generation-webui-1  | 2023-11-09 08:40:04 INFO:Loading llama-7b-4bit...
text-generation-webui-text-generation-webui-1  | 2023-11-09 08:40:04 ERROR:The path to the model does not exist. Exiting.
text-generation-webui-text-generation-webui-1  | Traceback (most recent call last):
text-generation-webui-text-generation-webui-1  |   File "/app/server.py", line 222, in <module>
text-generation-webui-text-generation-webui-1  |     shared.model, shared.tokenizer = load_model(model_name)
text-generation-webui-text-generation-webui-1  |   File "/app/modules/models.py", line 82, in load_model
text-generation-webui-text-generation-webui-1  |     raise ValueError
text-generation-webui-text-generation-webui-1  | ValueError
text-generation-webui-text-generation-webui-1 exited with code 1
```

### System Info

```shell
Fedora 39

Nvidia RTX 2060 Super

$ tree models/
models/
├── config.json
├── config-user.yaml
├── config.yaml
├── LICENSE.txt
├── llama-2-7b-chat.Q2_K.gguf
├── llama-2-7b-chat.Q3_K_L.gguf
├── llama-2-7b-chat.Q3_K_M.gguf
├── llama-2-7b-chat.Q3_K_S.gguf
├── llama-2-7b-chat.Q4_0.gguf
├── llama-2-7b-chat.Q4_K_M.gguf
├── openai_whisper-base
│   ├── added_tokens.json
│   ├── config.json
│   ├── generation_config.json
│   ├── huggingface-metadata.txt
│   ├── merges.txt
│   ├── model.safetensors
│   ├── normalizer.json
│   ├── preprocessor_config.json
│   ├── README.md
│   ├── special_tokens_map.json
│   ├── tokenizer_config.json
│   ├── tokenizer.json
│   └── vocab.json
├── openlm-research_open_llama_3b
│   ├── config.json
│   ├── generation_config.json
│   ├── huggingface-metadata.txt
│   ├── pytorch_model.bin
│   ├── README.md
│   ├── special_tokens_map.json
│   ├── tokenizer_config.json
│   └── tokenizer.model
├── README.md
├── Tap-M_Luna-AI-Llama2-Uncensored
│   ├── config.json
│   ├── generation_config.json
│   ├── huggingface-metadata.txt
│   ├── pytorch_model-00001-of-00003.bin
│   ├── pytorch_model-00002-of-00003.bin
│   ├── pytorch_model-00003-of-00003.bin
│   ├── pytorch_model.bin.index.json
│   ├── README.md
│   ├── special_tokens_map.json
│   ├── tokenizer_config.json
│   ├── tokenizer.model
│   └── trainer_state.json
├── TheBloke_Wizard-Vicuna-7B-Uncensored-GPTQ
│   ├── config.json
│   ├── generation_config.json
│   ├── huggingface-metadata.txt
│   ├── model.safetensors
│   ├── quantize_config.json
│   ├── README.md
│   ├── special_tokens_map.json
│   ├── tokenizer_config.json
│   ├── tokenizer.json
│   ├── tokenizer.model
│   └── trainer_state.json
├── tiiuae_falcon-7b
│   ├── config.json
│   ├── configuration_falcon.py
│   ├── generation_config.json
│   ├── huggingface-metadata.txt
│   ├── modeling_falcon.py
│   ├── pytorch_model-00001-of-00002.bin
│   ├── pytorch_model-00002-of-00002.bin
│   ├── pytorch_model.bin.index.json
│   ├── README.md
│   ├── special_tokens_map.json
│   ├── tokenizer_config.json
│   └── tokenizer.json
└── USE_POLICY.md

6 directories, 68 files
```

**Comment by stefangweichinger** [comment]
rolled back to https://github.com/oobabooga/text-generation-webui/tree/snapshot-2023-10-29  ... works

**Comment by TropicLegend** [comment]
I'm also having this problem
