### ISSUE TITLE
Deprecated API no longer working

### ISSUE THREAD

**Issue by ashleykleynhans** [oobabooga/text-generation-webui#4533]
### Describe the bug

Although the previous API has been deprecated in favour of the Open AI one, users still need to be able to use it while they are migrating across, but we are unable to do so.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Install the Text Generation Web UI.
2. Attempt to send API requests to the legacy blocking or non-blocking API ports.
3. Observe error.

### Logs

```shell
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.10/site-packages/websockets/legacy/server.py", line 240, in handler
    await self.ws_handler(self)
  File "/workspace/venv/lib/python3.10/site-packages/websockets/legacy/server.py", line 1186, in _ws_handler
    return await cast(
  File "/workspace/text-generation-webui/extensions/api/streaming_api.py", line 96, in _handle_connection
    await _handle_chat_stream_message(websocket, message)
  File "/workspace/text-generation-webui/extensions/api/util.py", line 155, in api_wrapper
    return await func(*args, **kwargs)
  File "/workspace/text-generation-webui/extensions/api/streaming_api.py", line 63, in _handle_chat_stream_message
    generate_params = build_parameters(body, chat=True)
  File "/workspace/text-generation-webui/extensions/api/util.py", line 77, in build_parameters
    name1, name2, _, greeting, context, _ = load_character_memoized(character, str(body.get('your_name', shared.settings['name1'])), '', instruct=False)
ValueError: too many values to unpack (expected 6)
```
```


### System Info

```shell
* Ubuntu 22.04 LTS
* CUDA 12.1.1
* Torch 2.1.0
* Docker image on RunPod
```

**Comment by dejanp777** [comment]
I get same error.

**Comment by ashleykleynhans** [comment]
@dejanp777 I've created a PR to fix it: https://github.com/oobabooga/text-generation-webui/pull/4539

Note that you will also need to change your API payloads from `instruct` to `chat`, because `instruct` has other errors.

**Comment by ashleykleynhans** [comment]
Tested and confirmed that the PR fixed it.
