### ISSUE TITLE
Open AI API not working

### ISSUE THREAD

**Issue by ashleykleynhans** [oobabooga/text-generation-webui#4534]
### Describe the bug

When sending completion requests to the Open AI API, they are not working due to an error with a tokenizer not being loaded.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Install Text Generation UI.
2. Enable Open AI compatible API.
3. Send a curl request as follows:
```
curl https://xxxxxxxxxxx-5000.proxy.runpod.net/v1/completions -H "Content-Type: application/json" -d '{
"prompt": "This is a cake recipe:\n\n1.",
"max_tokens": 200,
"temperature": 1,
"top_p": 0.9,
"seed": 10
}'
```
4. Observe tokenizer error.

### Logs

```shell
ERROR:    Exception in ASGI application

Traceback (most recent call last):
  File "/workspace/venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/workspace/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/workspace/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/workspace/venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/workspace/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/workspace/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/workspace/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/workspace/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/workspace/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/workspace/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/workspace/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/workspace/venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/workspace/venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/workspace/venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/workspace/venv/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/workspace/venv/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/workspace/text-generation-webui/extensions/openai/script.py", line 99, in openai_completions
    response = OAIcompletions.completions(to_dict(request_data), is_legacy=is_legacy)
  File "/workspace/text-generation-webui/extensions/openai/completions.py", line 505, in completions
    return deque(generator, maxlen=1).pop()
  File "/workspace/text-generation-webui/extensions/openai/completions.py", line 382, in completions_common
    token_count = len(encode(prompt)[0])
  File "/workspace/text-generation-webui/modules/text_generation.py", line 114, in encode
    raise ValueError('No tokenizer is loaded')
ValueError: No tokenizer is loaded
```
```


### System Info

```shell
* Ubuntu 22.04 LTS
* CUDA 12.1.1
* Torch 2.1.0
* Docker image on RunPod
```

**Comment by ashleykleynhans** [comment]
This one was an error on my part, the model had not been loaded which resulted in the error.  After loading the model, it works as expected.

**Comment by tamil-acog** [comment]
Hey Hi ashleykleynhans,

Where should I load the model? I mean in the webui the model is automatically loaded, but if enable api, how should I load a model?

Also, I want to run both webui and api. If the model is loaded via webui, will the API automatically pick it up?
Thanks in advance

**Comment by ashleykleynhans** [comment]
@tamil-acog Best is to load the model using the Web UI.  Once the model is loaded, the API will pick it up.

**Comment by ashleykleynhans** [comment]
You can also use the [download-mode.py](https://github.com/oobabooga/text-generation-webui/blob/main/download-model.py) script to download the model and specify the model name and loader when you start the Web UI, but I typically load the model inside the Web UI.

**Comment by tamil-acog** [comment]
Thabk you for the response. 

I would also like to load the model via WebUI.... 

So, if I start the server with "python server.py --api", both WebUI and api are accessible and I can load the model via WebUI?

**Comment by tamil-acog** [comment]
> Yes that is correct, or you can also add `--listen` to make it listen on all interfaces.

Oh ok. Thank you. Will try that.
