### ISSUE TITLE
By starting server, error text

### ISSUE THREAD

**Issue by spikezz** [oobabooga/text-generation-webui#4535]
### Describe the bug
by open the server with flag --openai and --api, the error appears

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

just by running script start_linux.sh with the flag openai and api

### Logs

```shell
ERROR:    Traceback (most recent call last):
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/site-packages/uvicorn/server.py", line 160, in startup
    server = await loop.create_server(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/asyncio/base_events.py", line 1525, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 5000): address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/site-packages/uvicorn/server.py", line 78, in serve
    await self.startup(sockets=sockets)
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/site-packages/uvicorn/server.py", line 168, in startup
    logger.error(exc)
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/logging/__init__.py", line 1518, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/logging/__init__.py", line 978, in handle
    self.emit(record)
  File "/home/spikezz/Project/text-generation-webui/modules/logging_colors.py", line 99, in new
    args[1].msg = color + args[1].msg + '\x1b[0m'  # normal
                  ~~~~~~^~~~~~~~~~~~~
TypeError: can only concatenate str (not "OSError") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/site-packages/starlette/routing.py", line 686, in lifespan
    await receive()
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/asyncio/queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

Exception in thread Thread-3 (run_server):
Traceback (most recent call last):
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/site-packages/uvicorn/server.py", line 160, in startup
    server = await loop.create_server(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/asyncio/base_events.py", line 1525, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 5000): address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/spikezz/Project/text-generation-webui/extensions/openai/script.py", line 296, in run_server
    uvicorn.run(app, host=server_addr, port=port, ssl_certfile=ssl_certfile, ssl_keyfile=ssl_keyfile)
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/site-packages/uvicorn/server.py", line 78, in serve
    await self.startup(sockets=sockets)
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/site-packages/uvicorn/server.py", line 168, in startup
    logger.error(exc)
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/logging/__init__.py", line 1518, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/home/spikezz/Project/text-generation-webui/installer_files/env/lib/python3.11/logging/__init__.py", line 978, in handle
    self.emit(record)
  File "/home/spikezz/Project/text-generation-webui/modules/logging_colors.py", line 99, in new
    args[1].msg = color + args[1].msg + '\x1b[0m'  # normal
                  ~~~~~~^~~~~~~~~~~~~
TypeError: can only concatenate str (not "OSError") to str
```

### System Info

```shell
in Ubuntu 20.04.6 LTS 64 bit
```

**Comment by spikezz** [comment]
Could be caused by the change from openai library or latest commit, but I'm not sure

**Comment by Rednorme** [comment]
The log says that the Port 5000 is already in use. Maybe try --api-port 1234 where "1234" is a free port?

**Comment by inwonakng** [comment]
Found out why, openai extension is also using the same port as the --api extension, as seen in line 289 of `extensions/openai/script.py`

```python
def run_server():
    server_addr = '0.0.0.0' if shared.args.listen else '127.0.0.1'
    port = int(os.environ.get('OPENEDAI_PORT', shared.args.api_port))
```

So running either only the API or OPENAI seems to be the solution so far, or you can set the `OPENDAI_PORT` environment variable.
