### ISSUE TITLE
GGUF Models sometimes returning empty responses

### ISSUE THREAD

**Issue by gmacgmac** [oobabooga/text-generation-webui#4540]
### Describe the bug

Mac M2 Max
With a GGUF model loaded, the model will likely respond the first time but there after, at some point soon into the interaction  the model starts returning blank.
I then ctrl+shift+backspace to remove last message and resend at which point the model responds.
Thereafter it can happen continuously but deleting the last message and resubmitting always returns response.

Is it a timeout?

### Is there an existing issue for this?
Not that I could find
- [x] I have searched the existing issues

### Reproduction

- Load GGUF Model (any) but pick for example
   - zephyr-7b-beta.Q8_0.gguf or Wizard-Vicuna-30B-Uncensored.Q5_K_M.gguf
- Load the model with n-gpu-layers = 0 or 1
- I tested with following params on and off
   - no_mul_mat_q, no-mmap, mlock, numa
- Chat with the model and at some point the response comes back empty messages on the model
   Output generated in 15.83 seconds (0.00 tokens/s, 0 tokens, context 98, seed 833788814)

See logs and screenshot

Latest Version of Oobabooga
llama-cpp-python          0.2.15                   pypi_0    pypi
Version 0.2.14 was the same

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/134940958/85f6411e-33bf-4693-b154-0c5b53a33a4d)
![image](https://github.com/oobabooga/text-generation-webui/assets/134940958/ecaf4d0c-5b4e-4610-b3b7-d417a2c868dc)
![image](https://github.com/oobabooga/text-generation-webui/assets/134940958/e7edf9b6-5946-4475-8e46-eba31732eeb1)

### Logs

```shell
llama_print_timings:        load time =     651.30 ms
llama_print_timings:      sample time =       5.33 ms /    58 runs   (    0.09 ms per token, 10892.02 tokens per second)
llama_print_timings: prompt eval time =       0.00 ms /     1 tokens (    0.00 ms per token,      inf tokens per second)
llama_print_timings:        eval time =    1717.67 ms /    58 runs   (   29.61 ms per token,    33.77 tokens per second)
llama_print_timings:       total time =    1794.90 ms
Output generated in 2.01 seconds (28.37 tokens/s, 57 tokens, context 104, seed 124011108)
Llama.generate: prefix-match hit

llama_print_timings:        load time =     651.30 ms
llama_print_timings:      sample time =       0.10 ms /     1 runs   (    0.10 ms per token,  9708.74 tokens per second)
llama_print_timings: prompt eval time =     424.02 ms /    76 tokens (    5.58 ms per token,   179.24 tokens per second)
llama_print_timings:        eval time =       0.00 ms /     1 runs   (    0.00 ms per token,      inf tokens per second)
llama_print_timings:       total time =     425.28 ms
Output generated in 0.64 seconds (0.00 tokens/s, 0 tokens, context 172, seed 1250685519)
```

### System Info

```shell
Mac M2 Max 96GB - Ventura 13.5 OS
Mac M1 Pro 16GB - Ventura 13.4 OS

Python 3.11
Latest version of Oobabooga
llama-cpp-python          0.2.15                   pypi_0    pypi
Version 0.2.14 was the same
```

**Comment by oobabooga** [comment]
It also happens to me. I don't know the cause, so I reverted everything to version 0.2.11 for now.

**Comment by Ph0rk0z** [comment]
It did not happen continuously for me. I could hit regenerate and would get a response.

**Comment by gmacgmac** [comment]
yes the regenerate works which makes me think there is a timeout occuring?
@oobabooga thanks for confirming - I've got 2 env now, with with llama-cpp-python at v0.2.11 & another for v0.2.15+ since this is needed for deepseek & some other models to get around the "vocab" error.

thanks @oobabooga for all you do

**Comment by HiroseKoichi** [comment]
0.2.17 just released and It solved the issue for me.

**Comment by gmacgmac** [comment]
i just spat tea all over my keyboard.
wow - when i went to sleep last night it was v0.2.15
and also ready 0.2.17?
and I just tested and the 33B param model ran near instantly on mac mps!!!

amazing!!

**Comment by HiroseKoichi** [comment]
> will have to test further to see if any issues crop up

It looks like 0.2.17 breaks llamacpp_HF, so unless you don't use it, 0.2.11 is still the latest version that works properly.

```
Traceback (most recent call last):
  File "/home/hirose/AI_Apps/text-generation-webui/modules/callbacks.py", line 57, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hirose/AI_Apps/text-generation-webui/modules/text_generation.py", line 355, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/hirose/AI_Apps/text-generation-webui/envs/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hirose/AI_Apps/text-generation-webui/envs/lib/python3.11/site-packages/transformers/generation/utils.py", line 1719, in generate
    return self.sample(
           ^^^^^^^^^^^^
  File "/home/hirose/AI_Apps/text-generation-webui/envs/lib/python3.11/site-packages/transformers/generation/utils.py", line 2801, in sample
    outputs = self(
              ^^^^^
  File "/home/hirose/AI_Apps/text-generation-webui/modules/llamacpp_hf.py", line 113, in __call__
    self.load_cache()
  File "/home/hirose/AI_Apps/text-generation-webui/modules/llamacpp_hf.py", line 83, in load_cache
    self.model.ctx = self.llamacpp_cache['ctx']
    ^^^^^^^^^^^^^^
AttributeError: property 'ctx' of 'Llama' object has no setter
```

**Comment by Ph0rk0z** [comment]
Yea, the fix for HF was removed when the 2.16 was backed out. It can just go back in when it's upgraded again. I think new pure llama.cpp suports min_P so that has to be added to it's params too.

**Comment by ye7iaserag** [comment]
Still same error `ERROR: byte not found in vocab: ` for DeepSeek with llama-cpp-python==0.2.17, weird that it solves the issue for some of you

**Comment by Alkohole** [comment]
@ye7iaserag
`llama-cpp-python==0.2.20`
`mul_mat_q` disabled
`cpu` enabled
Models type `deepseek` works

With `mul_mat_q` enabled, I get `ERROR: byte not found in vocab:`
