### ISSUE TITLE
LLama-2-Mistral Lora doesn't load anymore

### ISSUE THREAD

**Issue by bombel28** [oobabooga/text-generation-webui#4543]
### Describe the bug

Since todays update (last: before three weeks) update, I can't load my loras anymore. 

I use transformers as loader for this safetensors model.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load jphme_em_german_leo_mistral or models non mistral llama-2, apply lora

### Logs

```shell
2023-11-09 19:02:17 INFO:Applying the following LoRAs to jphme_em_german_leo_mistral: mistral_a
Traceback (most recent call last):
  File "C:\Users\uwe\GPT\text-generation-webui\installer_files\env\lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\uwe\GPT\text-generation-webui\installer_files\env\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\uwe\GPT\text-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "C:\Users\uwe\GPT\text-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\uwe\GPT\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 519, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\uwe\GPT\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\uwe\GPT\text-generation-webui\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\uwe\GPT\text-generation-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\uwe\GPT\text-generation-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\uwe\GPT\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\uwe\GPT\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\Users\uwe\GPT\text-generation-webui\modules\ui_model_menu.py", line 231, in load_lora_wrapper
    add_lora_to_model(selected_loras)
  File "C:\Users\uwe\GPT\text-generation-webui\modules\LoRA.py", line 20, in add_lora_to_model
    add_lora_transformers(lora_names)
  File "C:\Users\uwe\GPT\text-generation-webui\modules\LoRA.py", line 168, in add_lora_transformers
    shared.model = PeftModel.from_pretrained(shared.model, get_lora_path(lora_names[0]), adapter_name=lora_names[0], **params)
  File "C:\Users\uwe\GPT\text-generation-webui\installer_files\env\lib\site-packages\peft\peft_model.py", line 331, in from_pretrained
    model = MODEL_TYPE_TO_PEFT_MODEL_MAPPING[config.task_type](model, config, adapter_name)
  File "C:\Users\uwe\GPT\text-generation-webui\installer_files\env\lib\site-packages\peft\peft_model.py", line 973, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "C:\Users\uwe\GPT\text-generation-webui\installer_files\env\lib\site-packages\peft\peft_model.py", line 121, in __init__
    self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
  File "C:\Users\uwe\GPT\text-generation-webui\installer_files\env\lib\site-packages\peft\tuners\lora\model.py", line 111, in __init__
    super().__init__(model, config, adapter_name)
  File "C:\Users\uwe\GPT\text-generation-webui\installer_files\env\lib\site-packages\peft\tuners\tuners_utils.py", line 93, in __init__
    self.inject_adapter(self.model, adapter_name)
  File "C:\Users\uwe\GPT\text-generation-webui\installer_files\env\lib\site-packages\peft\tuners\tuners_utils.py", line 231, in inject_adapter
    self._create_and_replace(peft_config, adapter_name, target, target_name, parent, **optional_kwargs)
  File "C:\Users\uwe\GPT\text-generation-webui\installer_files\env\lib\site-packages\peft\tuners\lora\model.py", line 193, in _create_and_replace
    new_module = self._create_new_module(lora_config, adapter_name, target, **kwargs)
  File "C:\Users\uwe\GPT\text-generation-webui\installer_files\env\lib\site-packages\peft\tuners\lora\model.py", line 255, in _create_new_module
    AutoGPTQQuantLinear = get_auto_gptq_quant_linear(gptq_quantization_config)
  File "C:\Users\uwe\GPT\text-generation-webui\installer_files\env\lib\site-packages\peft\utils\other.py", line 415, in get_auto_gptq_quant_linear
    if is_auto_gptq_available():
  File "C:\Users\uwe\GPT\text-generation-webui\installer_files\env\lib\site-packages\peft\import_utils.py", line 41, in is_auto_gptq_available
    raise ImportError(
ImportError: Found an incompatible version of auto-gptq. Found version 0.4.2+cu121, but only versions above 0.5.0 are supported
```

### System Info

```shell
Win11, RTX4090
```

**Comment by lktinh2018** [comment]
Same  here :(

**Comment by FartyPants** [comment]
it says it in the error - you need to update auto-gptq
You can do it manually or wait when it will be fixed in requirements then update the whole thing.

**Comment by bombel28** [comment]
yes I know, but I was not sure about error says the truth... but yes, I've seen it and still wondering about realeasing that version with so many unfixed dependencies. But don't worry, I know you all are doing a great job and I am thankful about.

**Comment by amaze28** [comment]
This error is still happening for me.  I updated auto-gptq as follows (in Ubuntu 22.04 command line):
_pip3 install auto-gptq
Defaulting to user installation because normal site-packages is not writeable
Collecting auto-gptq
  Downloading auto_gptq-0.5.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.8 MB)
...
Installing collected packages: auto-gptq
Successfully installed auto-gptq-0.5.1_

Then I fire up text-generation-webui, attempt to load a model in Transformers (or load and then proceed to Training).  I get this same error:

_Found an incompatible version of auto-gptq. Found version 0.4.2+cu121, but only version above 0.4.99 are supported_

It seems that text-generation-webui is not seeing the updated auto-gptq? Or am I just totally missing something?  Thanks in advance for any help!

**Comment by EMRD95** [comment]
It's using the auto-gptq library from text-generation-webui\installer_files\env\Lib\site-packages
You can try to put the updated library manually, but updating will revert back to the old one.
You probably need to build from source with some options.

**Comment by amaze28** [comment]
Okay thanks for the diagnosis!  Much appreciated EMRD95.

**Comment by thr3a** [comment]
I also encountered the same error and couldn't apply LoRA, but the error was resolved when I updated the AutoGPTQ version from 0.4.2 to 0.5.1.

```
https://github.com/jllllll/AutoGPTQ/releases/download/v0.5.1/auto_gptq-0.5.1+cu121-cp310-cp310-linux_x86_64.whl; platform_system == "Linux" and platform_machine == "x86_64" and python_version == "3.10"
```

**Comment by remcovg89** [comment]
> I also encountered the same error and couldn't apply LoRA, but the error was resolved when I updated the AutoGPTQ version from 0.4.2 to 0.5.1.
> 
> ```
> https://github.com/jllllll/AutoGPTQ/releases/download/v0.5.1/auto_gptq-0.5.1+cu121-cp310-cp310-linux_x86_64.whl; platform_system == "Linux" and platform_machine == "x86_64" and python_version == "3.10"
> ```

I've changed the 3.11 line (in requirements.txt), ran the wsl_update.bat script and that solved the issue for me. Your reponse was helpfull to me.

**Comment by knight-captain** [comment]
I was able to fix this in Windows by deleting the auto-gptq directories (in \\text-generation-webui\installer_files\env\Lib\site-packages) and then using the cmd_windows.bat to `pip install auto-gptq`
Just running the pip install would fail, as version 0.4.2 existed.
