### ISSUE TITLE
exl2 not able to run 4bpw yi34b

### ISSUE THREAD

**Issue by drmcbride12** [oobabooga/text-generation-webui#4546]
### Describe the bug

Traceback (most recent call last):
  File "/content/text-generation-webui/modules/ui_model_menu.py", line 210, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/content/text-generation-webui/modules/models.py", line 85, in load_model
    output = load_func_map[loader](model_name)
  File "/content/text-generation-webui/modules/models.py", line 363, in ExLlamav2_HF_loader
    return Exllamav2HF.from_pretrained(model_name)
  File "/content/text-generation-webui/modules/exllamav2_hf.py", line 162, in from_pretrained
    config.prepare()
  File "/usr/local/lib/python3.10/dist-packages/exllamav2/config.py", line 133, in prepare
    raise ValueError(f" ## Could not find {prefix}.* in model")
ValueError:  ## Could not find model.layers.0.input_layernorm.* in model

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

download this: https://huggingface.co/royallab/Yi-34B-exl2

and run with exl2

### Logs

```shell
Traceback (most recent call last):
  File "/content/text-generation-webui/modules/ui_model_menu.py", line 210, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/content/text-generation-webui/modules/models.py", line 85, in load_model
    output = load_func_map[loader](model_name)
  File "/content/text-generation-webui/modules/models.py", line 363, in ExLlamav2_HF_loader
    return Exllamav2HF.from_pretrained(model_name)
  File "/content/text-generation-webui/modules/exllamav2_hf.py", line 162, in from_pretrained
    config.prepare()
  File "/usr/local/lib/python3.10/dist-packages/exllamav2/config.py", line 133, in prepare
    raise ValueError(f" ## Could not find {prefix}.* in model")
ValueError:  ## Could not find model.layers.0.input_layernorm.* in model
```

### System Info

```shell
t4
```

**Comment by yhyu13** [comment]
@drmcbride12  Answered here https://github.com/oobabooga/text-generation-webui/issues/4483#issuecomment-1798424858

You need build latest exllamav2 from source, or waiting textgen to bump to next release exllamav2

**Comment by jepjoo** [comment]
Here's a "Llamafied" Yi-34B model that works fine with the current version of text-generation-webui:

https://huggingface.co/LoneStriker/airoboros-2.2.1-y34b-4.0bpw-h6-exl2

LoneStriker has 3bpw and 5bpw quants available too.
