### ISSUE TITLE
Cannot load model

### ISSUE THREAD

**Issue by hkhk368** [oobabooga/text-generation-webui#4547]
### Describe the bug

Hello, I use win11+4070, it gives me this error. Would you mind to take a look? Thank you.

Traceback (most recent call last):

File "D:\ml\text-generation-webui\modules\ui_model_menu.py", line 201, in load_model_wrapper

shared.model, shared.tokenizer = load_model(shared.model_name, loader)

                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ml\text-generation-webui\modules\models.py", line 79, in load_model

output = load_func_map[loader](model_name)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ml\text-generation-webui\modules\models.py", line 225, in llamacpp_loader

model, tokenizer = LlamaCppModel.from_pretrained(model_file)

                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ml\text-generation-webui\modules\llamacpp_model.py", line 91, in from_pretrained

result.model = Llama(**params)

               ^^^^^^^^^^^^^^^
File "D:\ml\text-generation-webui\installer_files\env\Lib\site-packages\llama_cpp_cuda\llama.py", line 365, in init

assert self.model is not None

       ^^^^^^^^^^^^^^^^^^^^^^
AssertionError

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I download model from https://huggingface.co/TheBloke

### Logs

```shell
Hello, I use win11+4070, it gives me this error. Would you mind to take a look? Thank you.

Traceback (most recent call last):

File "D:\ml\text-generation-webui\modules\ui_model_menu.py", line 201, in load_model_wrapper


shared.model, shared.tokenizer = load_model(shared.model_name, loader)

                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ml\text-generation-webui\modules\models.py", line 79, in load_model


output = load_func_map[loader](model_name)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ml\text-generation-webui\modules\models.py", line 225, in llamacpp_loader


model, tokenizer = LlamaCppModel.from_pretrained(model_file)

                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ml\text-generation-webui\modules\llamacpp_model.py", line 91, in from_pretrained


result.model = Llama(**params)

               ^^^^^^^^^^^^^^^
File "D:\ml\text-generation-webui\installer_files\env\Lib\site-packages\llama_cpp_cuda\llama.py", line 365, in init


assert self.model is not None

       ^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

### System Info

```shell
win 11+4070
```

**Comment by sep332** [comment]
@hkhk368, did you figure this one out? I just ran into it today on an install that was working last week.
