### ISSUE TITLE
Using IPEX but IPEX is not installed or IPEX's version does not match current PyTorch

### ISSUE THREAD

**Issue by lamkhatinh** [oobabooga/text-generation-webui#4550]
### Describe the bug

I got this error on windows 11, please help me

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

- Load model and train lora.

### Logs

```shell
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:25<00:00,  3.21s/it]
2023-11-10 14:59:09 INFO:Loaded the model in 26.83 seconds.
2023-11-10 14:59:52 INFO:Loading JSON datasets...
Map: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 257.75 examples/s]
2023-11-10 14:59:53 INFO:Getting model ready...
2023-11-10 14:59:53 INFO:Preparing for training...
2023-11-10 14:59:53 INFO:Creating LoRA model...
2023-11-10 14:59:55 INFO:Starting training...
Training 'mistral' model using (q, v) projections
Trainable params: 13,631,488 (0.3620 %), All params: 3,765,702,656 (Model: 3,752,071,168)
2023-11-10 14:59:55 INFO:Log file 'train_dataset_sample.json' created in the 'logs' directory.
Exception in thread Thread-7 (threaded_run):
Traceback (most recent call last):
  File "D:\3.Research\research\45.Text_Generate_WebUI\text-generation-webui\installer_files\env\Lib\threading.py", line 1038, in _bootstrap_inner       
    self.run()
  File "D:\3.Research\research\45.Text_Generate_WebUI\text-generation-webui\installer_files\env\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "D:\3.Research\research\45.Text_Generate_WebUI\text-generation-webui\modules\training.py", line 696, in threaded_run
    trainer.train()
  File "D:\3.Research\research\45.Text_Generate_WebUI\text-generation-webui\installer_files\env\Lib\site-packages\transformers\trainer.py", line 1555, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\3.Research\research\45.Text_Generate_WebUI\text-generation-webui\installer_files\env\Lib\site-packages\transformers\trainer.py", line 1670, in _inner_training_loop
    model = self._wrap_model(self.model_wrapped)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\3.Research\research\45.Text_Generate_WebUI\text-generation-webui\installer_files\env\Lib\site-packages\transformers\trainer.py", line 1337, in _wrap_model
    model = self.ipex_optimize_model(model, training, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\3.Research\research\45.Text_Generate_WebUI\text-generation-webui\installer_files\env\Lib\site-packages\transformers\trainer.py", line 1313, in ipex_optimize_model
    raise ImportError(
ImportError: Using IPEX but IPEX is not installed or IPEX's version does not match current PyTorch, please refer to https://github.com/intel/intel-extension-for-pytorch.
2023-11-10 14:59:55 INFO:Training complete, saving...
2023-11-10 14:59:56 INFO:Training complete!
```

### System Info

```shell
Windows 11
```

**Comment by Ender436** [comment]
I'm having the same exact problem. Any progress?

**Comment by lamkhatinh** [comment]
In
D:\3.Research\research\45.Text_Generate_WebUI\text-generation-webui\installer_files\env\Lib\site-packages\transformers\trainer.p

<img width="594" alt="Screenshot 2023-11-15 at 08 37 29" src="https://github.com/oobabooga/text-generation-webui/assets/126752303/2902dfee-6585-41fa-b8b0-bd65d14eecdc">

Add line 371 as image.

**Comment by Ender436** [comment]
Thank you, that seems to have fixed it! Would enabling that and getting it to work permit you to train on cpu?

**Comment by lamkhatinh** [comment]
Acctually it's workaround method to deal with that problem to wait intel upgrade that lib to version compatible with torch I think.
But I don't think we should training on CPU.

**Comment by Ender436** [comment]
Ok, thanks for the help

**Comment by teddybear082** [comment]
Thank you for the workaround this fixed this issue for me!

**Comment by stefangweichinger** [comment]
I see that error in a docker-based setup on linux. Can't find that `trainer.p` in my local project-dir, I assume it is somewhere in the layers of the docker image? I will try to dig that up somehow.

I use nvidia-GPU for loading the model, so far I assumed the system is learning on the GPU anyway (?)

**Comment by GravermanDev** [comment]
@stefangweichinger it was misspelled, they probably meant ``trainer.py``
