### ISSUE TITLE
ImportError: DLL load failed while importing exllama_ext

### ISSUE THREAD

**Issue by szriru** [oobabooga/text-generation-webui#4554]
### Describe the bug

Cannot load models with a model loader, ExLlma_HF, ExLlmav2_HF.

Someone help me please.

After updating to the latest version, snapshot-2023-11-05( I don't know this is the main cause.), I cannot load models with the model loaders.
I tried
- Downgrading version by source code from the releases.
- Installing exllama from wheel. https://github.com/turboderp/exllama
- open cmd_windows.bat -> ```pip install -r requirements.txt```
- upgrading cuda toolkit to the latest

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I'm sorry but I don't know how to reproduce.
Just load with a model loader, ExLlma_HF or ExLlmav2_HF.

### Logs

```shell
Traceback (most recent call last):
  File "C:\text-generation-webui\modules\exllama_hf.py", line 14, in <module>
    from exllama.model import ExLlama, ExLlamaCache, ExLlamaConfig
  File "C:\text-generation-webui\installer_files\env\lib\site-packages\exllama\__init__.py", line 1, in <module>
    from . import cuda_ext, generator, model, tokenizer
  File "C:\text-generation-webui\installer_files\env\lib\site-packages\exllama\cuda_ext.py", line 9, in <module>
    import exllama_ext
ImportError: DLL load failed while importing exllama_ext: 指定されたモジュールが見つかりません。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\text-generation-webui\modules\ui_model_menu.py", line 209, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "C:\text-generation-webui\modules\models.py", line 84, in load_model
    output = load_func_map[loader](model_name)
  File "C:\text-generation-webui\modules\models.py", line 346, in ExLlama_HF_loader
    from modules.exllama_hf import ExllamaHF
  File "C:\text-generation-webui\modules\exllama_hf.py", line 21, in <module>
    from model import ExLlama, ExLlamaCache, ExLlamaConfig
  File "C:\text-generation-webui\repositories\exllama\model.py", line 12, in <module>
    import cuda_ext
  File "C:\text-generation-webui\repositories\exllama\cuda_ext.py", line 43, in <module>
    exllama_ext = load(
  File "C:\text-generation-webui\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 1308, in load
    return _jit_compile(
  File "C:\text-generation-webui\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 1736, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "C:\text-generation-webui\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 2136, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: DLL load failed while importing exllama_ext: 指定されたモジュールが見つかりません。
```

### System Info

```shell
windows 11
intel 12900KF
RTX4090
cuda 12.3
```

**Comment by szriru** [comment]
never mind.
re-installing of all of requirements solved it.

1. Delete "text-generation-webui\installer_files\env" folder
2. lauch start_windows.bat
3. wait to finish all of installing.
