### ISSUE TITLE
OpenAI Extension Not Loading - Module not found.

### ISSUE THREAD

**Issue by cttechcorp** [oobabooga/text-generation-webui#4562]
### Describe the bug

OpenAI extension is not loading for me.    I have verified the requirements are installed, however it complains that sse_starlette is missing.  Not sure if there is a version mismatch or other dependency that I am missing.

Log:

`2023-11-11 14:53:05 INFO:Loading settings from settings.yaml...
2023-11-11 14:53:05 INFO:Loading TheBloke_Speechless-Llama2-Hermes-Orca-Platypus-WizardLM-13B-GPTQ...
2023-11-11 14:53:10 INFO:Loaded the model in 5.35 seconds.
2023-11-11 14:53:10 INFO:Loading the extension "openai"...
2023-11-11 14:53:10 ERROR:Failed to load the extension "openai".
Traceback (most recent call last):
  File "/home/administrator/text-generation-webui/modules/extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "/home/administrator/text-generation-webui/extensions/openai/script.py", line 25, in <module>
    from sse_starlette import EventSourceResponse
ModuleNotFoundError: No module named 'sse_starlette'
/home/administrator/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/components/dropdown.py:231: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: llama or set allow_custom_value=True.
  warnings.warn(
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

CMD_FLAGS.txt:
--listen --model TheBloke_Speechless-Llama2-Hermes-Orca-Platypus-WizardLM-13B-GPTQ --extensions openai --gradio-auth username:password

Started with ./start_linux.sh script.

### Screenshot

```
(textgen) administrator@athena:~/text-generation-webui$ pip list | grep star
sse-starlette                                1.6.5
starlette                                    0.27.0
(textgen) administrator@athena:~/text-generation-webui$

```

### Logs

```shell
raceback (most recent call last):
  File "/home/administrator/text-generation-webui/modules/extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "/home/administrator/text-generation-webui/extensions/openai/script.py", line 25, in <module>
    from sse_starlette import EventSourceResponse
ModuleNotFoundError: No module named 'sse_starlette'
```

### System Info

```shell
Ubuntu VM running on TrueNAS Scale (QEMU)
nVidia Tesla P100 x 4
```

**Comment by cttechcorp** [comment]
I can see a mismatch between the names  sse_starlette and sse-starlette.   Will try changing that in script.py.
