### ISSUE TITLE
'Llama' object has no attribute 'named_modules' - When try to apply Lora

### ISSUE THREAD

**Issue by cuneyttyler** [oobabooga/text-generation-webui#4569]
### Describe the bug

I'm trying to apply lora or fine-tune a gguf llama model. In the former, ''LlamaCppModel' object has no attribute 'named_modules'' error occurs, in the latter, 'LlamaCppModel' object has no attribute 'named_parameters'. I inspected the code and found a few other issues which I mention later in another post maybe. Currently issue arises from Peft package expecting a torch model. Because named_parameters() and named_modules() functions are included in torch models. But text-generation-webui code doesn't convert this llamacppmodel or llama model objects to torch models...

What should be done in order to successfully load a lora or fine-tune a model. Am I doing something wrong?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

- Load a llama gguf model with llama.cpp. Apply a lora
- Load a llama gguf model with llama.cpp. Start training(fine-tuning).

### Logs

```shell
Traceback (most recent call last):
  File "D:\Programs\text-generation-webui\installer_files\env\Lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\text-generation-webui\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\text-generation-webui\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\Programs\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "D:\Programs\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "D:\Programs\text-generation-webui\modules\ui_model_menu.py", line 230, in load_lora_wrapper
    add_lora_to_model(selected_loras)
  File "D:\Programs\text-generation-webui\modules\LoRA.py", line 20, in add_lora_to_model
    add_lora_transformers(lora_names)
  File "D:\Programs\text-generation-webui\modules\LoRA.py", line 168, in add_lora_transformers
    shared.model = PeftModel.from_pretrained(shared.model, get_lora_path(lora_names[0]), adapter_name=lora_names[0], **params)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\text-generation-webui\installer_files\env\Lib\site-packages\peft\peft_model.py", line 277, in from_pretrained
    model = MODEL_TYPE_TO_PEFT_MODEL_MAPPING[config.task_type](model, config, adapter_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\text-generation-webui\installer_files\env\Lib\site-packages\peft\peft_model.py", line 889, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "D:\Programs\text-generation-webui\installer_files\env\Lib\site-packages\peft\peft_model.py", line 111, in __init__
    self.base_model = PEFT_TYPE_TO_MODEL_MAPPING[peft_config.peft_type](
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\text-generation-webui\installer_files\env\Lib\site-packages\peft\tuners\lora.py", line 274, in __init__
    super().__init__(model, config, adapter_name)
  File "D:\Programs\text-generation-webui\installer_files\env\Lib\site-packages\peft\tuners\tuners_utils.py", line 88, in __init__
    self.inject_adapter(self.model, adapter_name)
  File "D:\Programs\text-generation-webui\installer_files\env\Lib\site-packages\peft\tuners\tuners_utils.py", line 199, in inject_adapter
    key_list = [key for key, _ in model.named_modules()]
                                  ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Llama' object has no attribute 'named_modules'


This says 'Llama' object because I modified the code to return result.model in load_pretrained function of llamacpp_model.py file.
```

### System Info

```shell
ASUS ROG GL553v
Nvidia GeForce 1050
Intel i7 CPU
Windows 10
```

**Comment by Ph0rk0z** [comment]
Can't use GGUF with PEFT. Training has to be done through native llama.cpp if you want to go that route.

**Comment by cuneyttyler** [comment]
Okay, thanks. Closing.

**Comment by cuneyttyler** [comment]
Okay thanks, closing.
