### ISSUE TITLE
Lora training issue? ("Using IPEX but IPEX is not installed or IPEX's version does not match current PyTorch")

### ISSUE THREAD

**Issue by teddybear082** [oobabooga/text-generation-webui#4570]
### Describe the bug

- Loaded tinyllama (https://huggingface.co/PY007/TinyLlama-1.1B-Chat-v0.3/tree/main) to textgenwebui

- Saved training data as txt file in training folder

- Opened training window

- Chose raw text file

- Clicked started lora training

- text gen's UI reported "Done! LoRA saved to loras/tiny_llama_skyrim_lora_2.

- Before testing your new LoRA, make sure to first reload the model, as it is currently dirty from training."

- However, this was done in only a few seconds which seemed extremely odd

In looking at textgen's command window the following error appeared:

```
2023-11-12 10:07:53 INFO:Loading raw text file dataset...
2023-11-12 10:08:08 INFO:Getting model ready...
2023-11-12 10:08:08 INFO:Preparing for training...
2023-11-12 10:08:08 INFO:Creating LoRA model...
2023-11-12 10:08:10 INFO:Starting training...
Training 'llama' model using (q, v) projections
Trainable params: 4,505,600 (0.4079 %), All params: 1,104,566,272 (Model: 1,100,060,672)
2023-11-12 10:08:11 INFO:Log file 'train_dataset_sample.json' created in the 'logs' directory.
Exception in thread Thread-14 (threaded_run):
Traceback (most recent call last):
  File "C:\Users\Willi\Documents\GitHub\text-generation-webui\installer_files\env\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\Willi\Documents\GitHub\text-generation-webui\installer_files\env\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Willi\Documents\GitHub\text-generation-webui\modules\training.py", line 696, in threaded_run
    trainer.train()
  File "C:\Users\Willi\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\transformers\trainer.py", line 1555, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Willi\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\transformers\trainer.py", line 1670, in _inner_training_loop
    model = self._wrap_model(self.model_wrapped)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Willi\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\transformers\trainer.py", line 1337, in _wrap_model
    model = self.ipex_optimize_model(model, training, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Willi\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\transformers\trainer.py", line 1313, in ipex_optimize_model
    raise ImportError(
ImportError: Using IPEX but IPEX is not installed or IPEX's version does not match current PyTorch, please refer to https://github.com/intel/intel-extension-for-pytorch.
2023-11-12 10:08:11 INFO:Training complete, saving...
2023-11-12 10:08:11 INFO:Training complete!
2023-11-12 10:11:55 INFO:Loading PY007_TinyLlama-1.1B-Chat-v0.3...
2023-11-12 10:11:57 INFO:Loaded the model in 1.34 seconds.
2023-11-12 10:12:02 INFO:Applying the following LoRAs to PY007_TinyLlama-1.1B-Chat-v0.3: tiny_llama_skyrim_lora
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

See above

### Logs

```shell
See above
```

### System Info

```shell
Windows 11
Asus Dual RTX 3070
32 gb ram
Ryzen 5600x
```

**Comment by teddybear082** [comment]
closing I did now find this is a duplicate.

**Comment by moritzschaefer** [comment]
solution is here: https://github.com/oobabooga/text-generation-webui/issues/4447#issuecomment-1793722889
