### ISSUE TITLE
"Found no NVIDIA driver on your system"

### ISSUE THREAD

**Issue by CrazyKrow** [oobabooga/text-generation-webui#458]
### Describe the bug

I'm trying to install the webui on wsl but no luck. I get the error "RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx" 
I tried reinstalling multiple times and I always get cuda errors. I'm using wsl 1 on windows 10. 
My install on windows works fine, its only when I try to do it with wsl that is the problem. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I followed the installation steps on README.md, I used "conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia" instead of "pip3 install torch torchvision torchaudio" because it would let me install otherwise.

### Logs

```shell
python server.py
Loading llama-7b-hf...
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████| 33/33 [00:16<00:00,  1.98it/s]
Traceback (most recent call last):
  File "/home/crazykrow/text-generation-webui/server.py", line 241, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/crazykrow/text-generation-webui/modules/models.py", line 56, in load_model
    model = model.cuda()
  File "/home/crazykrow/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/crazykrow/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/crazykrow/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/crazykrow/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/crazykrow/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/crazykrow/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

### System Info

```shell
Windows 10, WSL v1, 3090Ti, 32GB ram
```

**Comment by LTSarc** [comment]
There's a more permanent fix [HERE:](https://github.com/microsoft/WSL/issues/5548#issuecomment-1292858815)

It's very hacky but works and doesn't have to be redone every invocation or restart.

**Comment by richardrl** [comment]
Just found this same issue when using pytorch.

Thanks @jllllll for the solution!

**Comment by Ashbarr13** [comment]
I'm experiencing the same issue and I'm on MacBook

**Comment by MLSci** [comment]
I'm experiencing the same issue and I'm on distrobox (Fedora)
