### ISSUE TITLE
Failed to load the extension "openai" - No module named 'sse_starlette'

### ISSUE THREAD

**Issue by Thireus** [oobabooga/text-generation-webui#4585]
### Describe the bug

The following dependency is missing in requirements.txt files: sse_starlette

`pip install sse_starlette` solves the issue.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

`python server.py --extension openai`

### Logs

```shell
2023-11-13 21:28:32 ERROR:Failed to load the extension "openai".
Traceback (most recent call last):
  File "/home/user/text-generation-webui/modules/extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "/home/user/text-generation-webui/extensions/openai/script.py", line 25, in <module>
    from sse_starlette import EventSourceResponse
ModuleNotFoundError: No module named 'sse_starlette'
```

**Comment by Thireus** [comment]
Duplicate of #4562, which was closed but needs to be reopened I suppose.

**Comment by siim-m** [comment]
Ran into this as well but noticed the extension has its own `requirements.txt` file [here](https://github.com/oobabooga/text-generation-webui/blob/main/extensions/openai/requirements.txt). Maybe just needs to be more clearly documented?

**Comment by marijnbent** [comment]
_1

**Comment by marijnbent** [comment]
> Ran into this as well but noticed the extension has its own `requirements.txt` file [here](https://github.com/oobabooga/text-generation-webui/blob/main/extensions/openai/requirements.txt). Maybe just needs to be more clearly documented?

Thanks! Running `pip3 install -r extensions/openai/requirements.txt` solved it for me.
