### ISSUE TITLE
Invalid argument: 'models/llama-7b/pytorch_model-00001-of-00033.bin'

### ISSUE THREAD

**Issue by EugeoSynthesisThirtyTwo** [oobabooga/text-generation-webui#459]
### Describe the bug

When I start the server, it deletes the file 'models/llama-7b/pytorch_model-00001-of-00033.bin', and of course it does not find it afterward.

![image](https://user-images.githubusercontent.com/24735555/226440894-0e885898-8164-4205-9ee9-b391954bbe9a.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1/ Install [LLaMA-7B](https://github.com/oobabooga/text-generation-webui/wiki/LLaMA-model)
2/ Start the server with LLaMA-7B in 8 bits mode:
`python server.py --auto-devices --no-stream --cai-chat --model llama-7b --load-in-8bit --gpu-memory 15 --listen`

### Logs

```shell
Loading checkpoint shards:   0%|                                                                                                                                                                                      | 0/33 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/home/armaguedin/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/modeling_utils.py", line 415, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "/home/armaguedin/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/armaguedin/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/armaguedin/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
OSError: [Errno 22] Invalid argument: 'models/llama-7b/pytorch_model-00001-of-00033.bin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/Armaguedin/Documents/dev/python/oobabooga/text-generation-webui/server.py", line 241, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/mnt/c/Users/Armaguedin/Documents/dev/python/oobabooga/text-generation-webui/modules/models.py", line 159, in load_model
    model = AutoModelForCausalLM.from_pretrained(checkpoint, **params)
  File "/home/armaguedin/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "/home/armaguedin/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2646, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/armaguedin/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2955, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "/home/armaguedin/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/modeling_utils.py", line 418, in load_state_dict
    with open(checkpoint_file) as f:
OSError: [Errno 22] Invalid argument: 'models/llama-7b/pytorch_model-00001-of-00033.bin'
```

### System Info

```shell
Windows 10
WSL with Ubuntu 22.04
RTX 3080 Ti Laptop GPU
```

**Comment by CrazyKrow** [comment]
it gets deleted because of your antivirus, it started happening today to me as well

**Comment by EugeoSynthesisThirtyTwo** [comment]
> it gets deleted because of your antivirus, it started happening today to me as well, it detects a trojan inside the .bin file, probably a false positive

Is there a way to tell windows defender "this directory is fine" ? I don't want to disable windows defender completely

**Comment by CrazyKrow** [comment]
yeah, you can exclude files. https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26#:~:text=Go%20to%20Start%20%3E%20Settings%20%3E%20Update,%2C%20file%20types%2C%20or%20process.
