### ISSUE TITLE
RuntimeError: probability tensor and CUDA error: no kernel image is available

### ISSUE THREAD

**Issue by DrAgonStranger** [oobabooga/text-generation-webui#4594]
### Describe the bug

Hello everyone, new guy here. Just installed everything and upon loading any AWQ model and trying to talk with it, the model gives out an error (RuntimeError: probability tensor contains either `inf`, `nan` or element < 0) and the bot himself says only one word. Upon second try usually bot goes silent and may give out another error message (RuntimeError: CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect)

I have tried two models until now (currently TheBloke/Llama-2-13B-chat-AWQ) and every one of them gave out the same result. Maybe I am doing something wrong or anyone has ever had the same problem before? Tried searching, but honestly found nothing of use.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Load a model
2. Try to speak to a bot
3. Try speaking again

### Screenshot

![File1](https://github.com/oobabooga/text-generation-webui/assets/53942456/968a3d08-1e08-44ce-8b17-9633f951c7aa)
![File2](https://github.com/oobabooga/text-generation-webui/assets/53942456/0207b3c6-f48d-44f1-8390-77437d0cfe16)
![File3](https://github.com/oobabooga/text-generation-webui/assets/53942456/b9b31f5b-0e59-411f-b79b-a74861dc2f40)

### Logs

```shell
bin C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121_nocublaslt.dll
2023-11-14 19:15:00 INFO:Loading the extension "gallery"...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
2023-11-14 19:17:31 INFO:Deleted logs\chat\Assistant\20231114-18-48-52.json.
C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\components\dropdown.py:231: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 4 or set allow_custom_value=True.
  warnings.warn(
C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\components\dropdown.py:231: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 128 or set allow_custom_value=True.
  warnings.warn(
C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\components\dropdown.py:231: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: llama or set allow_custom_value=True.
  warnings.warn(
2023-11-14 19:17:53 INFO:Loading TheBloke_Llama-2-13B-chat-AWQ...
Replacing layers...: 100%|█████████████████████████████████████████████████████████████| 40/40 [00:05<00:00,  6.80it/s]
Fusing layers...: 100%|████████████████████████████████████████████████████████████████| 40/40 [00:06<00:00,  5.93it/s]
2023-11-14 19:18:15 INFO:Loaded the model in 21.48 seconds.
Traceback (most recent call last):
  File "C:\Users\docto\Desktop\text-generation-webui-main\modules\callbacks.py", line 57, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\docto\Desktop\text-generation-webui-main\modules\text_generation.py", line 355, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\awq\models\base.py", line 37, in generate
    return self.model.generate(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\generation\utils.py", line 1719, in generate
    return self.sample(
           ^^^^^^^^^^^^
  File "C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\generation\utils.py", line 2837, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
Output generated in 2.27 seconds (0.44 tokens/s, 1 tokens, context 68, seed 1487377245)
Traceback (most recent call last):
  File "C:\Users\docto\Desktop\text-generation-webui-main\modules\callbacks.py", line 57, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\docto\Desktop\text-generation-webui-main\modules\text_generation.py", line 355, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\awq\models\base.py", line 37, in generate
    return self.model.generate(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\generation\utils.py", line 1719, in generate
    return self.sample(
           ^^^^^^^^^^^^
  File "C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\generation\utils.py", line 2837, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
Output generated in 0.97 seconds (0.00 tokens/s, 0 tokens, context 78, seed 1384363334)
Traceback (most recent call last):
  File "C:\Users\docto\Desktop\text-generation-webui-main\modules\callbacks.py", line 57, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\docto\Desktop\text-generation-webui-main\modules\text_generation.py", line 355, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\awq\models\base.py", line 37, in generate
    return self.model.generate(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\generation\utils.py", line 1719, in generate
    return self.sample(
           ^^^^^^^^^^^^
  File "C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\generation\utils.py", line 2801, in sample
    outputs = self(
              ^^^^^
  File "C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\models\llama\modeling_llama.py", line 1034, in forward
    outputs = self.model(
              ^^^^^^^^^^^
  File "C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\awq\modules\fused\model.py", line 39, in forward
    h, _, past_key_value = layer(h, None, attention_mask=mask, is_causal=is_causal)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\awq\modules\fused\block.py", line 27, in forward
    attn_output, _, past_key_value = self.attn.forward(
                                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\docto\Desktop\text-generation-webui-main\installer_files\env\Lib\site-packages\awq\modules\fused\attn.py", line 192, in forward
    attention_weight = output.transpose(1, 2).contiguous().view(bsz, seqlen, -1)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Output generated in 0.42 seconds (0.00 tokens/s, 0 tokens, context 90, seed 226533002)
```

### System Info

```shell
OS: Windows 10 Home
GPU 1: Intel(R) HD Graphics 530
GPU 2: NVIDIA GeForce GTX 1070
```

**Comment by Hanabi111** [comment]
Have the exact same issue with a fresh install on windows 10 with a GTX 1080TI. I've only gotten the first error once but I get `RuntimeError: CUDA error: no kernel image is available for execution on the device` every time.

**Comment by Ph0rk0z** [comment]
You have to compile it from scratch. Technically it doesn't support pascal. You can try to edit the project file in autoAWQ that sets higher compute as a requirement. Then cross your fingers and hope it works.

**Comment by casper-hansen** [comment]
Your GPU is not supported for AutoAWQ. You need RTX 2000 and up.

**Comment by barrymac** [comment]
I'm getting this one on a server with 4x Tesla V100 SXM2 32GB GPUS . I hope this doesn't mean no AutoAWQ for me! Hopefully someone will be able to add support for these cards in future. They are quite decent cards and available on the second hand market these days.

**Comment by lugangqi** [comment]
My M40 24g runs ExLlama the same way, 4060ti 16g works fine under cuda12.4. M40 seems that the author did not update the kernel compatible with it, I also asked for help under the ExLlama2 author yesterday, I do not know whether the author to fix this compatibility problem, M40 and 980ti with the same architecture core computing power 5.2 to meet cuda12.4
