### ISSUE TITLE
Recieving error when trying to load models

### ISSUE THREAD

**Issue by SpecialistSteak** [oobabooga/text-generation-webui#4602]
### Describe the bug

Whenever I try to load in a valid model, such as GPT4-Chan or Pygmalion, they give me the following error (see log at bottom).

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

1. Download the webui
2. Click the windows webui start file
3. Download all the .torrent gpt4chan files into the proper folder as per instructions, then run the command to install the eleuther-6B-transformer in the main folder
4. download `mayaeary/pygmalion-6b_dev-4bit-128g` using the built in download tool on the model page
5. try loading either of the 2 models
6. see same output as me

### Logs

```shell
'2023-11-15 10:17:36 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "E:\text-generation-webui-main\modules\ui_model_menu.py", line 210, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\text-generation-webui-main\modules\models.py", line 85, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\text-generation-webui-main\modules\models.py", line 148, in huggingface_loader
    model = LoaderClass.from_pretrained(path_to_model, **params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\models\auto\auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\modeling_utils.py", line 2992, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory models\mayaeary_pygmalion-6b_dev-4bit-128g.'
```

### System Info

```shell
Windows 11, Nvidia GTX 1650 Portable 4GB VRAM, Intel i5 9th gen
```

**Comment by Ph0rk0z** [comment]
Try with a different loader like autogptq instead of transformers.

**Comment by Ph0rk0z** [comment]
You didn't install all your requirements it seems.

>ModuleNotFoundError: No module named 'auto_gptq'

**Comment by itsadityaaaa** [comment]
I just downloaded oobabooga in cpu and dowloaded the yarn-mistral-7b-128k.Q4_K_M.gguf model but whenever i am trying to run the model i am getting below error:

![Image](https://github.com/user-attachments/assets/1ac24f50-3f2e-4663-8a39-b56e26554cda)

![Image](https://github.com/user-attachments/assets/660a273d-71de-4204-aaed-55ca6136b574)

error in text **************

Traceback (most recent call last):

File "E:\Draft2books\oobabooba\one-click-installers-oobabooga-windows\text-generation-webui\modules\ui_model_menu.py", line 214, in load_model_wrapper


shared.model, shared.tokenizer = load_model(selected_model, loader)
File "E:\Draft2books\oobabooba\one-click-installers-oobabooga-windows\text-generation-webui\modules\models.py", line 90, in load_model


output = load_func_map[loader](model_name)
File "E:\Draft2books\oobabooba\one-click-installers-oobabooga-windows\text-generation-webui\modules\models.py", line 280, in llamacpp_loader


model, tokenizer = LlamaCppModel.from_pretrained(model_file)
File "E:\Draft2books\oobabooba\one-click-installers-oobabooga-windows\text-generation-webui\modules\llamacpp_model.py", line 67, in from_pretrained


Llama = llama_cpp_lib().Llama
File "E:\Draft2books\oobabooba\one-click-installers-oobabooga-windows\text-generation-webui\modules\llama_cpp_python_hijack.py", line 46, in llama_cpp_lib


return_lib = importlib.import_module(lib_name)
File "E:\Draft2books\oobabooba\one-click-installers-oobabooga-windows\installer_files\env\lib\importlib_init_.py", line 126, in import_module


return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1050, in _gcd_import

File "", line 1027, in _find_and_load

File "", line 1006, in _find_and_load_unlocked

File "", line 688, in _load_unlocked

File "", line 883, in exec_module

File "", line 241, in _call_with_frames_removed

File "E:\Draft2books\oobabooba\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\llama_cpp_cuda_init_.py", line 1, in


from .llama_cpp import *
File "E:\Draft2books\oobabooba\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\llama_cpp_cuda\llama_cpp.py", line 38, in


_lib = load_shared_library(_lib_base_name, _base_path)
File "E:\Draft2books\oobabooba\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\llama_cpp_cuda_ctypes_extensions.py", line 56, in load_shared_library


os.add_dll_directory(os.path.join(os.environ["CUDA_PATH"], "bin"))
File "E:\Draft2books\oobabooba\one-click-installers-oobabooga-windows\installer_files\env\lib\os.py", line 1118, in add_dll_directory


cookie = nt._add_dll_directory(path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'E:\Draft2books\oobabooba\one-click-installers-oobabooga-windows\installer_files\env\bin'
