### ISSUE TITLE
Error loading openai

### ISSUE THREAD

**Issue by DataBassGit** [oobabooga/text-generation-webui#4610]
### Describe the bug

Recently updated and now the API doesn't start. I'm getting the following error:

2023-11-15 15:26:56 INFO:Loading the extension "openai"...
2023-11-15 15:26:56 ERROR:Failed to load the extension "openai".
Traceback (most recent call last):
  File "C:\AI\text-generation-webui-main\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "C:\AI\text-generation-webui-main\extensions\openai\script.py", line 25, in <module>
    from sse_starlette import EventSourceResponse
ModuleNotFoundError: No module named 'sse_starlette'

I tried running a pip install for sse_starlette, but I didn't think that would work since this is operating inside a conda env. This is probably a quick fix I imagine, but I'm drawing a blank.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Not sure it's reproducable.

### Logs

```shell
2023-11-15 15:26:56 INFO:Loading the extension "openai"...
2023-11-15 15:26:56 ERROR:Failed to load the extension "openai".
Traceback (most recent call last):
  File "C:\AI\text-generation-webui-main\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "C:\AI\text-generation-webui-main\extensions\openai\script.py", line 25, in <module>
    from sse_starlette import EventSourceResponse
ModuleNotFoundError: No module named 'sse_starlette'
```

### System Info

```shell
GPU: NVIDIA 1660ti
Ram: 16gb
OS: Win 10
```

**Comment by tonyzehs** [comment]
Same here. Started happening after latest update.

**Comment by tonyzehs** [comment]
Clicking on cmd_windows.bat and run [pip install sse_starlette] fixed it for me. Maybe the devs didnt update the requirements.txt in a recent update.

**Comment by yhyu13** [comment]
@oobabooga 

The env variable INSTALL_EXTENSIONS=yes is not yet for update/start_xxx.bat/.sh scripts, so that the one_click.py has ignored installing py packages for extensions. https://github.com/oobabooga/text-generation-webui/blob/8a2af87d3a39daa7414008a96d1a54e51c3af3de/one_click.py#L248

**Comment by oobabooga** [comment]
This is intentional, as installing extensions requirements on every update takes a long time and has caused dependency hells in the past. It is a limitation of the one-click installer.

It can be solved by running the `cmd_` script for your OS and pasting this command (which in practice is equivalent to what @tonyzehs suggested):

Linux/Mac:

```
pip install -r extensions/openai/requirements.txt --upgrade
```

Windows:

```
pip install -r extensions\openai\requirements.txt --upgrade
```

**Comment by DataBassGit** [comment]
Yeah. That seems to have worked, or more specifically updating the missing dependency. The cmd_x.bat was what I needed. Thanks for the help.

**Comment by ImpulseMirror** [comment]
> This is intentional, as installing extensions requirements on every update takes a long time and has caused dependency hells in the past. It is a limitation of the one-click installer.
> 
> It can be solved by running the `cmd_` script for your OS and pasting this command (which in practice is equivalent to what @tonyzehs suggested):
> 
> Linux/Mac:
> 
> ```
> pip install -r extensions/openai/requirements.txt --upgrade
> ```
> 
> Windows:
> 
> ```
> pip install -r extensions\openai\requirements.txt --upgrade
> ```

The suggested fix works but shouldn't this be part of the refresh process if you've got the api option enabled? Seems very not 'one click' if I've got to find this post and manually update the requirements myself. 🤷‍♂️
