### ISSUE TITLE
Unable to use Stable Diffusion API feature to generate images.

### ISSUE THREAD

**Issue by WetDogma** [oobabooga/text-generation-webui#4612]
### Describe the bug

Hey there, when trying to use my Stable Diffusion through Oobabooga, it no longer works. Have never had this issue until a few hours ago. I've reinstalled both Ooba and SD, and still the same result. Ooba does recognise that the API is there, when I hit enter in the window where you enter the key. Otherwise, the API is most definitely open at SD's end. Really confused as to what's happening here.

I doubt it makes a difference, but I'm using SD through NextUI, what I've always used for this purpose.

Thanks

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Attempting to use the SD API feature.

### Logs

```shell
Prompting the image generator via the API on http://(API)...
Traceback (most recent call last):
  File "E:\FAKEFOLDER\text-generation-webui\installer_files\env\Lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\FAKEFOLDER\text-generation-webui\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\FAKEFOLDER\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\FAKEFOLDER\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\FAKEFOLDER\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\FAKEFOLDER\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\FAKEFOLDER\text-generation-webui\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\FAKEFOLDER\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "E:\FAKEFOLDER\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\FAKEFOLDER\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "E:\FAKEFOLDER\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "E:\FAKEFOLDER\text-generation-webui\modules\chat.py", line 336, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True)):
  File "E:\FAKEFOLDER\text-generation-webui\modules\chat.py", line 304, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "E:\FAKEFOLDER\text-generation-webui\modules\chat.py", line 272, in chatbot_wrapper
    output['visible'][-1][1] = apply_extensions('output', output['visible'][-1][1], state, is_chat=True)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\FAKEFOLDER\text-generation-webui\modules\extensions.py", line 224, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\FAKEFOLDER\text-generation-webui\modules\extensions.py", line 82, in _apply_string_extensions
    text = func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\FAKEFOLDER\text-generation-webui\extensions\sd_api_pictures\script.py", line 219, in output_modifier
    string = get_SD_pictures(string, state['character_menu']) + "\n" + text
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\FAKEFOLDER\text-generation-webui\extensions\sd_api_pictures\script.py", line 158, in get_SD_pictures
    response.raise_for_status()
  File "E:\FAKEFOLDER\text-generation-webui\installer_files\env\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://(API)/sdapi/v1/txt2img
```

### System Info

```shell
Windows, Nvidia 4090
```

**Comment by WetDogma** [comment]
This was an issue with an update with NextUI
