### ISSUE TITLE
Feature Request: Generate and replicate seeds to reproduce text

### ISSUE THREAD

**Issue by GenTxt** [oobabooga/text-generation-webui#463]
Attempted to find the best method for generating and replicating seeds through 'server.py' and 'api-example.py' but cannot replicate text results or find where the scripts generate seeds.

Best example for generating and replicating seeds as per https://github.com/AUTOMATIC1111

Feature should appear on interface and same option using current 'api-example.py' and/or 'server.py' (unless there's a better way?)

Reason for request is to have the same level of output reproducability as per stable-diffusion-webui

The following are examples of many possible solutions.

Currently these snippets work in other text generation scripts but cannot find where to apply them in text-generation-webui.

1. generate best seeds here:

#torch.seed()
#SEED=torch.seed()
#print(SEED)

 2. copy seed above here and comment out code above

seed = 6404812195821871557
print(seed)
torch.manual_seed(seed)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(seed) 

Cheers,

**Comment by BadisG** [comment]
Yeah same. I would love to get the possibility to manipulate the seed for tests, especially for the Lora VS non Lora one.
https://github.com/oobabooga/text-generation-webui/issues/332#issuecomment-1475296375

**Comment by ill13** [comment]
I tested this and it looked like it worked. I asked the same exact questions 3 timed and got the exact same answer three times. However it 'broke' chat logging and `--verbose` output, so I don't have verification.

Enabling `--chat` caused these errors:

```
To create a public link, set `share=True` in `launch()`.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\starlette\middleware\errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\starlette\middleware\cors.py", line 76, in __call__
    await self.app(scope, receive, send)
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\starlette\routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\starlette\routing.py", line 82, in app
    await func(session)
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\fastapi\routing.py", line 289, in app
    await dependant.call(**values)
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\gradio\routes.py", line 483, in join_queue
    if blocks.dependencies[event.fn_index].get("every", 0):
IndexError: list index out of range
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\starlette\middleware\errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\starlette\middleware\cors.py", line 76, in __call__
    await self.app(scope, receive, send)
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\starlette\routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\starlette\routing.py", line 82, in app
    await func(session)
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\fastapi\routing.py", line 289, in app
    await dependant.call(**values)
  File "C:\code\textgen_working\installer_files\env\lib\site-packages\gradio\routes.py", line 483, in join_queue
    if blocks.dependencies[event.fn_index].get("every", 0):
IndexError: list index out of range
```

**Comment by wywywywy** [comment]
PR is now merged

**Comment by BadisG** [comment]
> PR is now merged

Great job! Seed is an important parameter and I'm happy I can manipulate it now 😄

**Comment by ndkling** [comment]
Dumb question.  How can I find the seed that was used for the generation of text that I like?

**Comment by GenTxt** [comment]
Fixed here:

https://github.com/mcmonkey4eva/text-generation-webui/tree/seed-fix

Thanks to both
