### ISSUE TITLE
Whenever I try to generate, I get a `TypeError: Llama.create_completion() got an unexpected keyword argument 'seed'`

### ISSUE THREAD

**Issue by lyssieth** [oobabooga/text-generation-webui#4631]
### Describe the bug

After updating to the latest version as of today (commit sha f889302d2427c03a3c15925dd097c6213845660c), every time I try to generate anything it throws the following error:

```
Traceback (most recent call last):
  File "/home/{user}/Ai/text-gen/modules/callbacks.py", line 57, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/{user}/Ai/text-gen/modules/llamacpp_model.py", line 121, in generate
    completion_chunks = self.model.create_completion(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Llama.create_completion() got an unexpected keyword argument 'seed'
Output generated in 0.25 seconds (0.00 tokens/s, 0 tokens, context 58, seed 167886416)
```

I'm using a GGUF model loaded by `llama.cpp`; I don't think which model exactly is relevant as I tested with two.  
I don't know whether the fact that I'm on an AMD GPU is relevant to the issue.

Considering it was working ~10 hours ago, it seems that this is a recent change that caused this.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Update to `f889302d2427c03a3c15925dd097c6213845660c`
2. Load a GGUF model with `llama.cpp` (seemingly irrelevant which model/what parameters)
3. Try to generate anything in the chat.

### Screenshot

N/A

### Logs

```shell
Traceback (most recent call last):
  File "/home/lys/Ai/text-gen/modules/callbacks.py", line 57, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lys/Ai/text-gen/modules/llamacpp_model.py", line 121, in generate
    completion_chunks = self.model.create_completion(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Llama.create_completion() got an unexpected keyword argument 'seed'
Output generated in 0.25 seconds (0.00 tokens/s, 0 tokens, context 58, seed 167886416)
```

### System Info

```shell
OS: Arch Linux (6.6.1 zen)
GPU: AMD 7900 XTX
```

**Comment by theodorDiaconu** [comment]
I have the same issue, Windows, 3090. With this model: https://huggingface.co/TheBloke/Amethyst-13B-Mistral-GGUF/tree/main?not-for-all-audiences=true

**Comment by freddybc** [comment]
A reinstall of llama-cpp-python solved this for me. Upgraded to 0.2.18.

**Comment by DespairWorld** [comment]
same here

**Comment by Bec-k** [comment]
Same here, Ubuntu 22.04, using latest main branch with commit 4737a5a8208ff0a810430cb10a1f040f5e2be791

**Comment by KevinFanwave** [comment]
can you show us the steps to fix?

**Comment by KevinFanwave** [comment]
Using C transformers works for me
