### ISSUE TITLE
Docker install fails. Can't find requirements.txt

### ISSUE THREAD

**Issue by fahadshery** [oobabooga/text-generation-webui#4633]
### Describe the bug

Hi,

Here is my docker compose:
```bash
version: "3.3"
services:
  text-generation-webui:
    build:
      context: .
      args:
        # specify which cuda version your card supports: https://developer.nvidia.com/cuda-gpus
        TORCH_CUDA_ARCH_LIST: ${TORCH_CUDA_ARCH_LIST:-6.1}
        WEBUI_VERSION: ${WEBUI_VERSION:-HEAD}
    env_file: .env
    ports:
      - "${HOST_PORT:-7860}:${CONTAINER_PORT:-7860}"
      - "${HOST_API_PORT:-5000}:${CONTAINER_API_PORT:-5000}"
      - "${HOST_API_STREAM_PORT:-5005}:${CONTAINER_API_STREAM_PORT:-5005}"
    stdin_open: true
    tty: true
    volumes:
      - ./characters:/app/characters
      - ./extensions:/app/extensions
      - ./loras:/app/loras
      - ./models:/app/models
      - ./presets:/app/presets
      - ./prompts:/app/prompts
      - ./softprompts:/app/softprompts
      - ./training:/app/training
      - ./cloudflared:/etc/cloudflared
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
```

I followed the instructions in the YouTube video. 
It can't seem to find the `requirements.txt` file.

Couldn't see where it is referred to since everything related to docker lives inside the `docker` folder.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Clone the repo
2. Make sure you change the CUDA version according to your GPU
3. do a docker compose up

### Logs

```shell
Getting the following error:

chatgpt:~/text-generation-webui/docker$ docker compose up
[+] Building 1.4s (22/26)                                                                                                                                          docker:default
 => [text-generation-webui internal] load build definition from Dockerfile                                                                                                   0.0s
 => => transferring dockerfile: 3.02kB                                                                                                                                       0.0s
 => [text-generation-webui internal] load .dockerignore                                                                                                                      0.0s
 => => transferring context: 124B                                                                                                                                            0.0s
 => [text-generation-webui internal] load metadata for docker.io/nvidia/cuda:12.1.0-runtime-ubuntu22.04                                                                      1.2s
 => [text-generation-webui internal] load metadata for docker.io/nvidia/cuda:12.1.0-devel-ubuntu22.04                                                                        1.0s
 => [text-generation-webui internal] load build context                                                                                                                      0.0s
 => => transferring context: 1.14kB                                                                                                                                          0.0s
 => CANCELED [text-generation-webui builder 1/6] FROM docker.io/nvidia/cuda:12.1.0-devel-ubuntu22.04@sha256:a9b9ca3a5d74c477e49a41b1b741a3fedbe5af57a1bcbe923633c8ead85cd9d  0.1s
 => => resolve docker.io/nvidia/cuda:12.1.0-devel-ubuntu22.04@sha256:a9b9ca3a5d74c477e49a41b1b741a3fedbe5af57a1bcbe923633c8ead85cd9d9                                        0.0s
 => => sha256:a9b9ca3a5d74c477e49a41b1b741a3fedbe5af57a1bcbe923633c8ead85cd9d9 743B / 743B                                                                                   0.0s
 => => sha256:21a1267666ddc41acb51ccf19b7d70c238d7ddc2d2aedf2e2105cff13d195e63 2.63kB / 2.63kB                                                                               0.0s
 => CANCELED [text-generation-webui stage-1  1/15] FROM docker.io/nvidia/cuda:12.1.0-runtime-ubuntu22.04@sha256:2a32de5cd8bacaa9d9c9ca3e0e9cfc57daa126aa9c4afc1e1b8c83f9f1d  0.1s
 => => resolve docker.io/nvidia/cuda:12.1.0-runtime-ubuntu22.04@sha256:2a32de5cd8bacaa9d9c9ca3e0e9cfc57daa126aa9c4afc1e1b8c83f9f1dc7210                                      0.0s
 => => sha256:2a32de5cd8bacaa9d9c9ca3e0e9cfc57daa126aa9c4afc1e1b8c83f9f1dc7210 743B / 743B                                                                                   0.0s
 => => sha256:3a68966e10a2c1d5af717e956a4840cb27ca56b325ae09a07959ed90fe3ac614 15.13kB / 15.13kB                                                                             0.0s
 => => sha256:4fc0adcd38976b2149095d0575db047eddcbc49cfdac9ced2fb5dbd0604f5383 2.21kB / 2.21kB                                                                               0.0s
 => CACHED [text-generation-webui stage-1  2/15] RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,rw apt-get update &&     apt-get install --no-install-recommen  0.0s
 => CACHED [text-generation-webui stage-1  3/15] RUN --mount=type=cache,target=/root/.cache/pip,rw pip3 install virtualenv                                                   0.0s
 => CACHED [text-generation-webui stage-1  4/15] RUN mkdir /app                                                                                                              0.0s
 => CACHED [text-generation-webui stage-1  5/15] WORKDIR /app                                                                                                                0.0s
 => CACHED [text-generation-webui stage-1  6/15] RUN test -n "HEAD" && git reset --hard HEAD || echo "Using provided webui source"                                           0.0s
 => CACHED [text-generation-webui stage-1  7/15] RUN virtualenv /app/venv                                                                                                    0.0s
 => CACHED [text-generation-webui stage-1  8/15] RUN --mount=type=cache,target=/root/.cache/pip,rw     . /app/venv/bin/activate &&     pip3 install --upgrade pip setuptool  0.0s
 => CACHED [text-generation-webui builder 2/6] RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,rw apt-get update &&     apt-get install --no-install-recommends  0.0s
 => CACHED [text-generation-webui builder 3/6] RUN git clone --depth=1 https://github.com/oobabooga/GPTQ-for-LLaMa /build                                                    0.0s
 => CACHED [text-generation-webui builder 4/6] WORKDIR /build                                                                                                                0.0s
 => CACHED [text-generation-webui builder 5/6] RUN --mount=type=cache,target=/root/.cache/pip,rw     python3 -m venv /build/venv &&     . /build/venv/bin/activate &&     p  0.0s
 => CACHED [text-generation-webui builder 6/6] RUN . /build/venv/bin/activate &&     python3 setup_cuda.py bdist_wheel -d .                                                  0.0s
 => CACHED [text-generation-webui stage-1  9/15] COPY --from=builder /build /app/repositories/GPTQ-for-LLaMa                                                                 0.0s
 => CACHED [text-generation-webui stage-1 10/15] RUN --mount=type=cache,target=/root/.cache/pip,rw     . /app/venv/bin/activate &&     pip3 install /app/repositories/GPTQ-  0.0s
 => ERROR [text-generation-webui stage-1 11/15] COPY requirements.txt /app/requirements.txt                                                                                  0.0s
------
 > [text-generation-webui stage-1 11/15] COPY requirements.txt /app/requirements.txt:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref ee534932-d69d-4c19-9daa-11c1620ec17f::la5sr69ti5fmqitp286epg2yn: "/requirements.txt": not found
```

### System Info

```shell
cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

 NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2
```

**Comment by fahadshery** [comment]
So I copied `requirements.txt` into the `docker` folder and re-ran `docker compose up`. It gave the following error:
```
1687.4   × python setup.py egg_info did not run successfully.
1687.4   │ exit code: 1
1687.4   ╰─> [11 lines of output]
1687.4       /app/venv/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
1687.4         device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
1687.4       No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
1687.4       Traceback (most recent call last):
1687.4         File "<string>", line 2, in <module>
1687.4         File "<pip-setuptools-caller>", line 34, in <module>
1687.4         File "/tmp/pip-install-iwm46ufo/xformers_1c3d9c8a106248f1ad9162d9840b7d03/setup.py", line 239, in <module>
1687.4           ext_modules=get_extensions(),
1687.4         File "/tmp/pip-install-iwm46ufo/xformers_1c3d9c8a106248f1ad9162d9840b7d03/setup.py", line 157, in get_extensions
1687.4           raise RuntimeError(
1687.4       RuntimeError: CUTLASS submodule not found. Did you forget to run `git submodule update --init --recursive` ?
1687.4       [end of output]
1687.4
1687.4   note: This error originates from a subprocess, and is likely not a problem with pip.
1687.4 error: metadata-generation-failed
1687.4
1687.4 × Encountered error while generating package metadata.
1687.4 ╰─> See above for output.
1687.4
1687.4 note: This is an issue with the package mentioned above, not pip.
1687.4 hint: See above for details.
------
failed to solve: process "/bin/sh -c . /app/venv/bin/activate &&     pip3 install --upgrade pip setuptools wheel ninja &&     pip3 install torch --index-url https://download.pytorch.org/whl/cu121 &&     pip3 install torchvision torchaudio sentence_transformers xformers" did not complete successfully: exit code: 1
```
apparently it couldn't find `cuda`

**Comment by RostStepaniuk** [comment]
yes I faced the same problem

**Comment by MindSetFPS** [comment]
had the same problem but with CMD_FLAGS.txt 

`pc@nvidia:~/Documents/projects/text-generation-webui-compose/text-generation-webui$ docker compose -f docker/nvidia/docker-compose.yml up -d
[+] Building 1.1s (12/13)                                                                                                                                             docker:default
 => [text-generation-webui internal] load build definition from Dockerfile                                                                                                      0.1s
 => => transferring dockerfile: 1.12kB                                                                                                                                          0.0s
 => [text-generation-webui internal] load metadata for docker.io/library/ubuntu:22.04                                                                                           0.9s
 => [text-generation-webui internal] load .dockerignore                                                                                                                         0.1s
 => => transferring context: 2B                                                                                                                                                 0.0s
 => [text-generation-webui stage-0 1/9] FROM docker.io/library/ubuntu:22.04@sha256:e9569c25505f33ff72e88b2990887c9dcf230f23259da296eb814fc2b41af999                             0.0s
 => [text-generation-webui internal] load build context                                                                                                                         0.0s
 => => transferring context: 2B                                                                                                                                                 0.0s
 => CACHED [text-generation-webui stage-0 2/9] WORKDIR /builder                                                                                                                 0.0s
 => CACHED [text-generation-webui stage-0 3/9] RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,rw     apt update &&     apt install --no-install-recommends -y git  0.0s
 => CACHED [text-generation-webui stage-0 4/9] WORKDIR /home/app/                                                                                                               0.0s
 => CACHED [text-generation-webui stage-0 5/9] RUN git clone https://github.com/oobabooga/text-generation-webui.git                                                             0.0s
 => CACHED [text-generation-webui stage-0 6/9] WORKDIR /home/app/text-generation-webui                                                                                          0.0s
 => CACHED [text-generation-webui stage-0 7/9] RUN GPU_CHOICE=A USE_CUDA118=FALSE LAUNCH_AFTER_INSTALL=FALSE INSTALL_EXTENSIONS=TRUE ./start_linux.sh --verbose                 0.0s
 => ERROR [text-generation-webui stage-0 8/9] COPY CMD_FLAGS.txt /home/app/text-generation-webui/                                                                               0.0s
------
 > [text-generation-webui stage-0 8/9] COPY CMD_FLAGS.txt /home/app/text-generation-webui/:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref c94c5fe3-5dac-41b2-8b5e-b0b99ccd9468::lrlbt8970zw32qd3h65r69o8e: "/CMD_FLAGS.txt": not found
`

**Comment by MindSetFPS** [comment]
had a a similar problem but with CMD_FLAGS.txt
```shell
pc@nvidia:~/Documents/projects/text-generation-webui-compose/text-generation-webui$ docker compose -f docker/nvidia/docker-compose.yml up -d
[+] Building 1.1s (12/13)                                                                                                                                             docker:default
 => [text-generation-webui internal] load build definition from Dockerfile                                                                                                      0.1s
 => => transferring dockerfile: 1.12kB                                                                                                                                          0.0s
 => [text-generation-webui internal] load metadata for docker.io/library/ubuntu:22.04                                                                                           0.9s
 => [text-generation-webui internal] load .dockerignore                                                                                                                         0.1s
 => => transferring context: 2B                                                                                                                                                 0.0s
 => [text-generation-webui stage-0 1/9] FROM docker.io/library/ubuntu:22.04@sha256:e9569c25505f33ff72e88b2990887c9dcf230f23259da296eb814fc2b41af999                             0.0s
 => [text-generation-webui internal] load build context                                                                                                                         0.0s
 => => transferring context: 2B                                                                                                                                                 0.0s
 => CACHED [text-generation-webui stage-0 2/9] WORKDIR /builder                                                                                                                 0.0s
 => CACHED [text-generation-webui stage-0 3/9] RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,rw     apt update &&     apt install --no-install-recommends -y git  0.0s
 => CACHED [text-generation-webui stage-0 4/9] WORKDIR /home/app/                                                                                                               0.0s
 => CACHED [text-generation-webui stage-0 5/9] RUN git clone https://github.com/oobabooga/text-generation-webui.git                                                             0.0s
 => CACHED [text-generation-webui stage-0 6/9] WORKDIR /home/app/text-generation-webui                                                                                          0.0s
 => CACHED [text-generation-webui stage-0 7/9] RUN GPU_CHOICE=A USE_CUDA118=FALSE LAUNCH_AFTER_INSTALL=FALSE INSTALL_EXTENSIONS=TRUE ./start_linux.sh --verbose                 0.0s
 => ERROR [text-generation-webui stage-0 8/9] COPY CMD_FLAGS.txt /home/app/text-generation-webui/                                                                               0.0s
------
 > [text-generation-webui stage-0 8/9] COPY CMD_FLAGS.txt /home/app/text-generation-webui/:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref c94c5fe3-5dac-41b2-8b5e-b0b99ccd9468::lrlbt8970zw32qd3h65r69o8e: "/CMD_FLAGS.txt": not found

```

**Comment by HRezaei** [comment]
> had a a similar problem but with CMD_FLAGS.txt

I encounter the same. :(

**Comment by cazubris** [comment]
all i ran into the CMD_FLAGS.txt issue, i took the docker-compose.yml, DOCKERFILE and my .env file and copied them to the base text-generation-ui folder (where CMD_FLAGS.txt is) and ran docker compose from that base folder. Its running w/o the same errors at least.

**Comment by TiddlyWiddly** [comment]
> all i ran into the CMD_FLAGS.txt issue, i took the docker-compose.yml, DOCKERFILE and my .env file and copied them to the base text-generation-ui folder (where CMD_FLAGS.txt is) and ran docker compose from that base folder. Its running w/o the same errors at least.

This worked for me, pfft.

**Comment by m0xsec** [comment]
> all i ran into the CMD_FLAGS.txt issue, i took the docker-compose.yml, DOCKERFILE and my .env file and copied them to the base text-generation-ui folder (where CMD_FLAGS.txt is) and ran docker compose from that base folder. Its running w/o the same errors at least.

ha that worked for me too lol
