### ISSUE TITLE
ImportError: Using IPEX but IPEX is not installed or IPEX's version does not match current PyTorch - when running training on NVidia GPU (not on Intel arc)

### ISSUE THREAD

**Issue by huboz0r** [oobabooga/text-generation-webui#4661]
### Describe the bug

When starting training i get the error:
```
2023-11-19 16:39:53 INFO:Starting training...
Training 'mistral' model using (q, v) projections
Trainable params: 54,525,952 (0.7473 %), All params: 7,296,258,048 (Model: 7,241,732,096)
2023-11-19 16:39:53 INFO:Log file 'train_dataset_sample.json' created in the 'logs' directory.
Exception in thread Thread-7 (threaded_run):
Traceback (most recent call last):
  File "C:\path\to\text-generation-webui\installer_files\env\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\path\to\text-generation-webui\installer_files\env\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\path\to\text-generation-webui\modules\training.py", line 696, in threaded_run
    trainer.train()
  File "C:\path\to\text-generation-webui\installer_files\env\Lib\site-packages\transformers\trainer.py", line 1555, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\path\to\text-generation-webui\installer_files\env\Lib\site-packages\transformers\trainer.py", line 1670, in _inner_training_loop
    model = self._wrap_model(self.model_wrapped)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\path\to\text-generation-webui\installer_files\env\Lib\site-packages\transformers\trainer.py", line 1337, in _wrap_model
    model = self.ipex_optimize_model(model, training, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\path\to\text-generation-webui\installer_files\env\Lib\site-packages\transformers\trainer.py", line 1313, in ipex_optimize_model
    raise ImportError(
ImportError: Using IPEX but IPEX is not installed or IPEX's version does not match current PyTorch, please refer to https://github.com/intel/intel-extension-for-pytorch.
```
Log lines above  ImportError suggest it is trying to trained an ipex_optimize_model. I have tested also tested this on Llama2-13B with model loader and training settings that have worked well in previous versions of text-generation-ui. In the current version, this training results in the error mentioned. During installation i chose option A (Nvidia GPU). I reinstalled to doublecheck this setting and check any dependency issues. Interference works well, it is just the training that gives this error in the latest version.

For completeness sake: I am running my NVidia GPU on a 12700k GPU. This CPU has integrated graphics, with the latest intel drivers installed. Not sure if this is relevant, since i am running text-generation-ui on my nvidia GPU and the model seems to load fine to the correct graphics card. I replaced the actual paths in the logs files with C:\path\to. Training on raw text.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load model in Transformers in Model tab. Start training in training tab on raw text.

### Logs

```shell
2023-11-19 16:39:53 INFO:Starting training...
Training 'mistral' model using (q, v) projections
Trainable params: 54,525,952 (0.7473 %), All params: 7,296,258,048 (Model: 7,241,732,096)
2023-11-19 16:39:53 INFO:Log file 'train_dataset_sample.json' created in the 'logs' directory.
Exception in thread Thread-7 (threaded_run):
Traceback (most recent call last):
  File "C:\path\to\text-generation-webui\installer_files\env\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\path\to\text-generation-webui\installer_files\env\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\path\to\text-generation-webui\modules\training.py", line 696, in threaded_run
    trainer.train()
  File "C:\path\to\text-generation-webui\installer_files\env\Lib\site-packages\transformers\trainer.py", line 1555, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\path\to\text-generation-webui\installer_files\env\Lib\site-packages\transformers\trainer.py", line 1670, in _inner_training_loop
    model = self._wrap_model(self.model_wrapped)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\path\to\text-generation-webui\installer_files\env\Lib\site-packages\transformers\trainer.py", line 1337, in _wrap_model
    model = self.ipex_optimize_model(model, training, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\path\to\text-generation-webui\installer_files\env\Lib\site-packages\transformers\trainer.py", line 1313, in ipex_optimize_model
    raise ImportError(
ImportError: Using IPEX but IPEX is not installed or IPEX's version does not match current PyTorch, please refer to https://github.com/intel/intel-extension-for-pytorch.
```

### System Info

```shell
Windows 11, Nvidia 3090, 12700k CPU
```

**Comment by huboz0r** [comment]
I posted a double issue. There is a workaround for this explained in the issue posted here: [https://github.com/oobabooga/text-generation-webui/issues/4550](https://github.com/oobabooga/text-generation-webui/issues/4550), by disabling ipex.
