### ISSUE TITLE
ERROR:Failed to load the extension "openai"

### ISSUE THREAD

**Issue by tsngsn** [oobabooga/text-generation-webui#4663]
### Describe the bug

After updating to the latest version, openai extension no longer load even after installing the requirements.txt again

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Ran pip install -r extensions\openai\requirements.txt --upgrade again but still get the error.

### Logs

```shell
2023-11-20 01:37:29 ERROR:Failed to load the extension "openai".
Traceback (most recent call last):
  File "E:\Apps\text-generation-webui-snapshot-2023-10-22\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "E:\Apps\text-generation-webui-snapshot-2023-10-22\extensions\openai\script.py", line 19, in <module>
    import extensions.openai.logits as OAIlogits
ModuleNotFoundError: No module named 'extensions.openai.logits'
```

### System Info

```shell
Win 11, NVIDIA 3060 Ti
```

**Comment by Ronny-apo** [comment]
Yep, it seems like the logits.py file is missing through this pr #4650.

**Comment by ashleykleynhans** [comment]
This issue us happening with TheBloke's template running Ubuntu 22.04 Linux on RunPod as well.

**Comment by ashleykleynhans** [comment]
Its been fixed with [this commit](https://github.com/oobabooga/text-generation-webui/commit/f0d66cf817ed4d1698556af08369b99a2180ffe5).

**Comment by tsngsn** [comment]
> Its been fixed with [this commit](https://github.com/oobabooga/text-generation-webui/commit/f0d66cf817ed4d1698556af08369b99a2180ffe5).

Thanks for the heads-up. The extension loads properly now.

**Comment by heartlocket** [comment]
I just downloaded a fresh install of text gen today and i am running into a similar issue: 

2023-11-22 12:17:13 INFO:Loading the extension "openai"...
2023-11-22 12:17:13 ERROR:Failed to load the extension "openai".
Traceback (most recent call last):
  File "C:\Users\heart\Desktop\DEV\text-generation-webui\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "C:\Users\heart\Desktop\DEV\text-generation-webui\extensions\openai\script.py", line 7, in <module>
    import speech_recognition as sr
ModuleNotFoundError: No module named 'speech_recognition'
