### ISSUE TITLE
Docker install, can't find cuda. Error: No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'

### ISSUE THREAD

**Issue by fahadshery** [oobabooga/text-generation-webui#4665]
### Describe the bug

I have cuda installed and working:
<img width="719" alt="image" src="https://github.com/oobabooga/text-generation-webui/assets/7301267/2c7cde02-41cc-4dea-9d73-87baece522a1">

GPU is available inside docker:
![image](https://github.com/oobabooga/text-generation-webui/assets/7301267/2308f5c3-6776-4a83-bf4a-751b7a09ba26)

I can run h2ogpt with GPTQ models no issues. 
But following Docker install. I am getting the following error:

```
124.8 INFO: pip is still looking at multiple versions of xformers to determine which version is compatible with other requirements. This could take a while.
124.8   Using cached xformers-0.0.16-cp310-cp310-manylinux2014_x86_64.whl (50.9 MB)
125.7   Using cached xformers-0.0.13.tar.gz (292 kB)
125.9   Preparing metadata (setup.py): started
129.6   Preparing metadata (setup.py): finished with status 'error'
129.6   error: subprocess-exited-with-error
129.6
129.6   × python setup.py egg_info did not run successfully.
129.6   │ exit code: 1
129.6   ╰─> [11 lines of output]
129.6       /app/venv/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
129.6         device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
129.6       No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
129.6       Traceback (most recent call last):
129.6         File "<string>", line 2, in <module>
129.6         File "<pip-setuptools-caller>", line 34, in <module>
129.6         File "/tmp/pip-install-vxbjaze1/xformers_faa78cb950dd4536bde4c3e2208a8c6c/setup.py", line 239, in <module>
129.6           ext_modules=get_extensions(),
129.6         File "/tmp/pip-install-vxbjaze1/xformers_faa78cb950dd4536bde4c3e2208a8c6c/setup.py", line 157, in get_extensions
129.6           raise RuntimeError(
129.6       RuntimeError: CUTLASS submodule not found. Did you forget to run `git submodule update --init --recursive` ?
129.6       [end of output]
129.6
129.6   note: This error originates from a subprocess, and is likely not a problem with pip.
129.6 error: metadata-generation-failed
129.6
129.6 × Encountered error while generating package metadata.
129.6 ╰─> See above for output.
129.6
129.6 note: This is an issue with the package mentioned above, not pip.
129.6 hint: See above for details.
------
failed to solve: process "/bin/sh -c . /app/venv/bin/activate &&     pip3 install --upgrade pip setuptools wheel ninja &&     pip3 install torch --index-url https://download.pytorch.org/whl/cu121 &&     pip3 install torchvision torchaudio sentence_transformers xformers" did not complete successfully: exit code: 1
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Install docker and setup nvidia for docker. 

Follow instructions to setup Docker install

### Logs

```shell
119.9   Using cached xformers-0.0.19-cp310-cp310-manylinux2014_x86_64.whl (108.2 MB)
121.3   Using cached xformers-0.0.18-cp310-cp310-manylinux2014_x86_64.whl (123.8 MB)
123.0 Collecting pyre-extensions==0.0.23 (from xformers)
123.0   Using cached pyre_extensions-0.0.23-py3-none-any.whl (11 kB)
123.0 Collecting xformers
123.0   Using cached xformers-0.0.17-cp310-cp310-manylinux2014_x86_64.whl (123.6 MB)
124.8 INFO: pip is still looking at multiple versions of xformers to determine which version is compatible with other requirements. This could take a while.
124.8   Using cached xformers-0.0.16-cp310-cp310-manylinux2014_x86_64.whl (50.9 MB)
125.7   Using cached xformers-0.0.13.tar.gz (292 kB)
125.9   Preparing metadata (setup.py): started
129.6   Preparing metadata (setup.py): finished with status 'error'
129.6   error: subprocess-exited-with-error
129.6
129.6   × python setup.py egg_info did not run successfully.
129.6   │ exit code: 1
129.6   ╰─> [11 lines of output]
129.6       /app/venv/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
129.6         device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
129.6       No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
129.6       Traceback (most recent call last):
129.6         File "<string>", line 2, in <module>
129.6         File "<pip-setuptools-caller>", line 34, in <module>
129.6         File "/tmp/pip-install-vxbjaze1/xformers_faa78cb950dd4536bde4c3e2208a8c6c/setup.py", line 239, in <module>
129.6           ext_modules=get_extensions(),
129.6         File "/tmp/pip-install-vxbjaze1/xformers_faa78cb950dd4536bde4c3e2208a8c6c/setup.py", line 157, in get_extensions
129.6           raise RuntimeError(
129.6       RuntimeError: CUTLASS submodule not found. Did you forget to run `git submodule update --init --recursive` ?
129.6       [end of output]
129.6
129.6   note: This error originates from a subprocess, and is likely not a problem with pip.
129.6 error: metadata-generation-failed
129.6
129.6 × Encountered error while generating package metadata.
129.6 ╰─> See above for output.
129.6
129.6 note: This is an issue with the package mentioned above, not pip.
129.6 hint: See above for details.
------
failed to solve: process "/bin/sh -c . /app/venv/bin/activate &&     pip3 install --upgrade pip setuptools wheel ninja &&     pip3 install torch --index-url https://download.pytorch.org/whl/cu121 &&     pip3 install torchvision torchaudio sentence_transformers xformers" did not complete successfully: exit code: 1
```

### System Info

```shell
cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by drew9781** [comment]
Hey! I had this issue last night, but wasn't sure if it was just me. 
I was able to get it working with this diff:
` git diff
diff --git a/docker/Dockerfile b/docker/Dockerfile
index 722bc8f..1a37a5f 100644
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -12,7 +12,7 @@ RUN --mount=type=cache,target=/root/.cache/pip,rw \
     python3 -m venv /build/venv && \
     . /build/venv/bin/activate && \
     pip3 install --upgrade pip setuptools wheel ninja && \
-    pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 && \
+    pip3 install torch torchvision torchaudio xformers --index-url https://download.pytorch.org/whl/cu121 && \
     pip3 install -r requirements.txt

 # https://developer.nvidia.com/cuda-gpus
@@ -44,8 +44,8 @@ RUN virtualenv /app/venv
 RUN --mount=type=cache,target=/root/.cache/pip,rw \
     . /app/venv/bin/activate && \
     pip3 install --upgrade pip setuptools wheel ninja && \
-    pip3 install torch --index-url https://download.pytorch.org/whl/cu121 && \
-    pip3 install torchvision torchaudio sentence_transformers xformers
+    pip3 install torch xformers --index-url https://download.pytorch.org/whl/cu121 && \
+    pip3 install torchvision torchaudio sentence_transformers

 # Copy and install GPTQ-for-LLaMa
 COPY --from=builder /build /app/repositories/GPTQ-for-LLaMa`
 
 I eventually traced it back to some old issue on xformer's github repo.
 The diff forces pip to install xformers with a specific cuda driver version, and solves it.

**Comment by oobabooga** [comment]
@drew9781 could you send a PR?

**Comment by drew9781** [comment]
https://github.com/oobabooga/text-generation-webui/pull/4670 
;)
