### ISSUE TITLE
M2 Mac opeRuntimeError: MPS backend out of memory

### ISSUE THREAD

**Issue by dshaikhtheknot** [oobabooga/text-generation-webui#4676]
### Describe the bug

I have following this [tutorial](https://www.youtube.com/watch?v=k2FHUP0krqg) 
When I load model TheBloke_Llama-2-13B-Chat-fp16 I get the following error:
`Traceback (most recent call last):

File "/Users/dshaikh/Development/llama/text-generation-webui/modules/ui_model_menu.py", line 206, in load_model_wrapper

shared.model, shared.tokenizer = load_model(shared.model_name, loader)

                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/dshaikh/Development/llama/text-generation-webui/modules/models.py", line 84, in load_model

output = load_func_map[loader](model_name)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/dshaikh/Development/llama/text-generation-webui/modules/models.py", line 144, in huggingface_loader

model = model.to(device)

        ^^^^^^^^^^^^^^^^
File "/Users/dshaikh/anaconda3/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2179, in to

return super().to(*args, **kwargs)

       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/dshaikh/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1152, in to

return self._apply(convert)

       ^^^^^^^^^^^^^^^^^^^^
File "/Users/dshaikh/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 802, in _apply

module._apply(fn)
File "/Users/dshaikh/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 802, in _apply

module._apply(fn)
File "/Users/dshaikh/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 802, in _apply

module._apply(fn)
[Previous line repeated 2 more times]

File "/Users/dshaikh/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 825, in _apply

param_applied = fn(param)

                ^^^^^^^^^
File "/Users/dshaikh/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1150, in convert

return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)

       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: MPS backend out of memory (MPS allocated: 18.01 GB, other allocations: 384.00 KB, max allowed: 18.13 GB). Tried to allocate 135.00 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).`

I was reading that you can get by this error by adding parameters, but since the model is loaded through an interface, Im not sure how to get over this.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Execute this commands:
conda create -n textgen python=3.10.9
conda activate textgen
install pytorch: pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117
git clone https://github.com/oobabooga/text-generation-webui
cd text-generation-webui
pip install -r requirements.txt
python server.py
# download model
# refresh model list
# load model

### Logs

```shell
Traceback (most recent call last):

File "/Users/dshaikh/Development/llama/text-generation-webui/modules/ui_model_menu.py", line 206, in load_model_wrapper


shared.model, shared.tokenizer = load_model(shared.model_name, loader)

                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/dshaikh/Development/llama/text-generation-webui/modules/models.py", line 84, in load_model


output = load_func_map[loader](model_name)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/dshaikh/Development/llama/text-generation-webui/modules/models.py", line 144, in huggingface_loader


model = model.to(device)

        ^^^^^^^^^^^^^^^^
File "/Users/dshaikh/anaconda3/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2179, in to


return super().to(*args, **kwargs)

       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/dshaikh/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1152, in to


return self._apply(convert)

       ^^^^^^^^^^^^^^^^^^^^
File "/Users/dshaikh/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 802, in _apply


module._apply(fn)
File "/Users/dshaikh/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 802, in _apply


module._apply(fn)
File "/Users/dshaikh/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 802, in _apply


module._apply(fn)
[Previous line repeated 2 more times]

File "/Users/dshaikh/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 825, in _apply


param_applied = fn(param)

                ^^^^^^^^^
File "/Users/dshaikh/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1150, in convert


return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)

       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: MPS backend out of memory (MPS allocated: 18.01 GB, other allocations: 384.00 KB, max allowed: 18.13 GB). Tried to allocate 135.00 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
```

### System Info

```shell
M2 16GB RAM, OS Sonoroama
```

**Comment by lufixSch** [comment]
Since the tutorial was created some things have changed especially for mac. You can just use the start_macos.sh script instead of installing manually.
If you want to install manually you need to install the right torch for MacOS (not the cuda one) and the requirements_apple_silicon.txt.

In any case you will not be able to run a fp16 13B model on 16GB of RAM. The whole model needs to fit into the RAM and the model you tried is way larger than that. Try a quantized version instead.
