### ISSUE TITLE
No models loads after latest update - Help please?

### ISSUE THREAD

**Issue by Webslug** [oobabooga/text-generation-webui#4691]
### Describe the bug

I recently updated and no models will load any longer.  Can anyone help or should I reinstall?  

Traceback (most recent call last):
File "D:\AI\UI\text-generation-webui\modules\ui_model_menu.py", line 209, in load_model_wrapper
shared.model, shared.tokenizer = load_model(shared.model_name, loader)

File "D:\AI\UI\text-generation-webui\modules\models.py", line 85, in load_model
output = load_func_map[loader](model_name)

File "D:\AI\UI\text-generation-webui\modules\models.py", line 306, in AutoAWQ_loader
from awq import AutoAWQForCausalLM

File "D:\AI\UI\installer_files\env\lib\site-packages\awq_init_.py", line 2, in
from awq.models.auto import AutoAWQForCausalLM

File "D:\AI\UI\installer_files\env\lib\site-packages\awq\models_init_.py", line 1, in
from .mpt import MptAWQForCausalLM

File "D:\AI\UI\installer_files\env\lib\site-packages\awq\models\mpt.py", line 1, in

from .base import BaseAWQForCausalLM

File "D:\AI\UI\installer_files\env\lib\site-packages\awq\models\base.py", line 12, in

from awq.quantize.quantizer import AwqQuantizer

File "D:\AI\UI\installer_files\env\lib\site-packages\awq\quantize\quantizer.py", line 11, in

from awq.modules.linear import WQLinear_GEMM, WQLinear_GEMV

File "D:\AI\UI\installer_files\env\lib\site-packages\awq\modules\linear.py", line 4, in

import awq_inference_engine  # with CUDA kernels

ImportError: DLL load failed while importing awq_inference_engine: The specified module could not be found.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I've tried to restart the program several times and load various models.  They all do not load any more.

### Logs

```shell
Traceback (most recent call last):

File "D:\AI\UI\text-generation-webui\modules\ui_model_menu.py", line 209, in load_model_wrapper

shared.model, shared.tokenizer = load_model(shared.model_name, loader)

File "D:\AI\UI\text-generation-webui\modules\models.py", line 85, in load_model

output = load_func_map[loader](model_name)

File "D:\AI\UI\text-generation-webui\modules\models.py", line 306, in AutoAWQ_loader

from awq import AutoAWQForCausalLM

File "D:\AI\UI\installer_files\env\lib\site-packages\awq_init_.py", line 2, in

from awq.models.auto import AutoAWQForCausalLM

File "D:\AI\UI\installer_files\env\lib\site-packages\awq\models_init_.py", line 1, in

from .mpt import MptAWQForCausalLM

File "D:\AI\UI\installer_files\env\lib\site-packages\awq\models\mpt.py", line 1, in

from .base import BaseAWQForCausalLM

File "D:\AI\UI\installer_files\env\lib\site-packages\awq\models\base.py", line 12, in

from awq.quantize.quantizer import AwqQuantizer

File "D:\AI\UI\installer_files\env\lib\site-packages\awq\quantize\quantizer.py", line 11, in

from awq.modules.linear import WQLinear_GEMM, WQLinear_GEMV

File "D:\AI\UI\installer_files\env\lib\site-packages\awq\modules\linear.py", line 4, in

import awq_inference_engine  # with CUDA kernels

ImportError: DLL load failed while importing awq_inference_engine: The specified module could not be found.
```

### System Info

```shell
GTX 3060
```

**Comment by jdunne525** [comment]
I have a similar problem.  Unable to load a model with llamacpp with this latest version (snapshot-2023-11-19).  In my case I tried to load wizardcoder-15B-Q4_1.gguf on Windows 10 with an RTX 2080.

2023-11-21 20:25:59 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "G:\programs\oobabooga_textgen\text-generation-webui-main\modules\ui_model_menu.py", line 209, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\programs\oobabooga_textgen\text-generation-webui-main\modules\models.py", line 85, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\programs\oobabooga_textgen\text-generation-webui-main\modules\models.py", line 249, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\programs\oobabooga_textgen\text-generation-webui-main\modules\llamacpp_model.py", line 90, in from_pretrained
    result.model = Llama(**params)
                   ^^^^^^^^^^^^^^^
  File "G:\programs\oobabooga_textgen\text-generation-webui-main\installer_files\env\Lib\site-packages\llama_cpp_cuda\llama.py", line 923, in __init__
    self._n_vocab = self.n_vocab()
                    ^^^^^^^^^^^^^^
  File "G:\programs\oobabooga_textgen\text-generation-webui-main\installer_files\env\Lib\site-packages\llama_cpp_cuda\llama.py", line 2184, in n_vocab
    return self._model.n_vocab()
           ^^^^^^^^^^^^^^^^^^^^^
  File "G:\programs\oobabooga_textgen\text-generation-webui-main\installer_files\env\Lib\site-packages\llama_cpp_cuda\llama.py", line 250, in n_vocab
    assert self.model is not None
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError

Exception ignored in: <function LlamaCppModel.__del__ at 0x00000290EFE068E0>
Traceback (most recent call last):
  File "G:\programs\oobabooga_textgen\text-generation-webui-main\modules\llamacpp_model.py", line 49, in __del__
    self.model.__del__()
    ^^^^^^^^^^
AttributeError: 'LlamaCppModel' object has no attribute 'model'

**Comment by casper-hansen** [comment]
This is most likely an environment issue when installing. What happens if you run the following:

```
pip install -v autoawq
```

**Comment by shexian02** [comment]
> This is most likely an environment issue when installing. What happens if you run the following:
> 
> ```
> pip install -v autoawq
> ```

I had the similar situation.
When I install autoawq with your command, it seems everything is ok

Using pip 23.3 from D:\Anaconda\envs\yi_env\lib\site-packages\pip (python 3.10)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: autoawq in d:\anaconda\envs\yi_env\lib\site-packages (0.1.7)
Requirement already satisfied: torch>=2.0.1 in d:\anaconda\envs\yi_env\lib\site-packages (from autoawq) (2.0.1)
Requirement already satisfied: transformers>=4.35.0 in d:\anaconda\envs\yi_env\lib\site-packages (from autoawq) (4.35.2)
Requirement already satisfied: tokenizers>=0.12.1 in d:\anaconda\envs\yi_env\lib\site-packages (from autoawq) (0.15.0)
Requirement already satisfied: accelerate in d:\anaconda\envs\yi_env\lib\site-packages (from autoawq) (0.24.1)
Requirement already satisfied: sentencepiece in d:\anaconda\envs\yi_env\lib\site-packages (from autoawq) (0.1.99)
Requirement already satisfied: lm-eval in d:\anaconda\envs\yi_env\lib\site-packages (from autoawq) (0.3.0)
Requirement already satisfied: texttable in d:\anaconda\envs\yi_env\lib\site-packages (from autoawq) (1.7.0)
Requirement already satisfied: toml in d:\anaconda\envs\yi_env\lib\site-packages (from autoawq) (0.10.2)
Requirement already satisfied: attributedict in d:\anaconda\envs\yi_env\lib\site-packages (from autoawq) (0.3.0)
Requirement already satisfied: protobuf in d:\anaconda\envs\yi_env\lib\site-packages (from autoawq) (3.20.3)
Requirement already satisfied: torchvision in d:\anaconda\envs\yi_env\lib\site-packages (from autoawq) (0.15.2)
Requirement already satisfied: tabulate in d:\anaconda\envs\yi_env\lib\site-packages (from autoawq) (0.9.0)
Requirement already satisfied: huggingface_hub<1.0,>=0.16.4 in d:\anaconda\envs\yi_env\lib\site-packages (from tokenizers>=0.12.1->autoawq) (0.19.4)
Requirement already satisfied: filelock in d:\anaconda\envs\yi_env\lib\site-packages (from torch>=2.0.1->autoawq) (3.13.1)
Requirement already satisfied: typing-extensions in d:\anaconda\envs\yi_env\lib\site-packages (from torch>=2.0.1->autoawq) (4.7.1)
Requirement already satisfied: sympy in d:\anaconda\envs\yi_env\lib\site-packages (from torch>=2.0.1->autoawq) (1.11.1)
Requirement already satisfied: networkx in d:\anaconda\envs\yi_env\lib\site-packages (from torch>=2.0.1->autoawq) (3.1)
Requirement already satisfied: jinja2 in d:\anaconda\envs\yi_env\lib\site-packages (from torch>=2.0.1->autoawq) (3.1.2)
Requirement already satisfied: numpy>=1.17 in d:\anaconda\envs\yi_env\lib\site-packages (from transformers>=4.35.0->autoawq) (1.26.0)
Requirement already satisfied: packaging>=20.0 in d:\anaconda\envs\yi_env\lib\site-packages (from transformers>=4.35.0->autoawq) (23.2)
Requirement already satisfied: pyyaml>=5.1 in d:\anaconda\envs\yi_env\lib\site-packages (from transformers>=4.35.0->autoawq) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in d:\anaconda\envs\yi_env\lib\site-packages (from transformers>=4.35.0->autoawq) (2023.10.3)
Requirement already satisfied: requests in d:\anaconda\envs\yi_env\lib\site-packages (from transformers>=4.35.0->autoawq) (2.31.0)
Requirement already satisfied: safetensors>=0.3.1 in d:\anaconda\envs\yi_env\lib\site-packages (from transformers>=4.35.0->autoawq) (0.4.0)
Requirement already satisfied: tqdm>=4.27 in d:\anaconda\envs\yi_env\lib\site-packages (from transformers>=4.35.0->autoawq) (4.66.1)
Requirement already satisfied: psutil in d:\anaconda\envs\yi_env\lib\site-packages (from accelerate->autoawq) (5.9.6)
Requirement already satisfied: rootpath>=0.1.0 in d:\anaconda\envs\yi_env\lib\site-packages (from attributedict->autoawq) (0.1.1)
Requirement already satisfied: inspecta>=0.1.0 in d:\anaconda\envs\yi_env\lib\site-packages (from attributedict->autoawq) (0.1.3)
Requirement already satisfied: colour-runner>=0.0.5 in d:\anaconda\envs\yi_env\lib\site-packages (from attributedict->autoawq) (0.1.1)
Requirement already satisfied: deepdiff>=3.3.0 in d:\anaconda\envs\yi_env\lib\site-packages (from attributedict->autoawq) (6.7.1)
Requirement already satisfied: tox>=3.0.0 in d:\anaconda\envs\yi_env\lib\site-packages (from attributedict->autoawq) (4.11.4)
Requirement already satisfied: coverage>=4.5.2 in d:\anaconda\envs\yi_env\lib\site-packages (from attributedict->autoawq) (7.3.2)
Requirement already satisfied: codecov>=2.0.15 in d:\anaconda\envs\yi_env\lib\site-packages (from attributedict->autoawq) (2.1.13)
Requirement already satisfied: datasets>=2.0.0 in d:\anaconda\envs\yi_env\lib\site-packages (from lm-eval->autoawq) (2.13.0)
Requirement already satisfied: jsonlines in d:\anaconda\envs\yi_env\lib\site-packages (from lm-eval->autoawq) (4.0.0)
Requirement already satisfied: numexpr in d:\anaconda\envs\yi_env\lib\site-packages (from lm-eval->autoawq) (2.8.7)
Requirement already satisfied: openai>=0.6.4 in d:\anaconda\envs\yi_env\lib\site-packages (from lm-eval->autoawq) (1.3.6)
Requirement already satisfied: pybind11>=2.6.2 in d:\anaconda\envs\yi_env\lib\site-packages (from lm-eval->autoawq) (2.11.1)
Requirement already satisfied: pycountry in d:\anaconda\envs\yi_env\lib\site-packages (from lm-eval->autoawq) (22.3.5)
Requirement already satisfied: pytablewriter in d:\anaconda\envs\yi_env\lib\site-packages (from lm-eval->autoawq) (1.2.0)
Requirement already satisfied: rouge-score>=0.0.4 in d:\anaconda\envs\yi_env\lib\site-packages (from lm-eval->autoawq) (0.1.2)
Requirement already satisfied: sacrebleu==1.5.0 in d:\anaconda\envs\yi_env\lib\site-packages (from lm-eval->autoawq) (1.5.0)
Requirement already satisfied: scikit-learn>=0.24.1 in d:\anaconda\envs\yi_env\lib\site-packages (from lm-eval->autoawq) (1.3.2)
Requirement already satisfied: sqlitedict in d:\anaconda\envs\yi_env\lib\site-packages (from lm-eval->autoawq) (2.1.0)
Requirement already satisfied: tqdm-multiprocess in d:\anaconda\envs\yi_env\lib\site-packages (from lm-eval->autoawq) (0.0.11)
Requirement already satisfied: zstandard in d:\anaconda\envs\yi_env\lib\site-packages (from lm-eval->autoawq) (0.22.0)
Requirement already satisfied: portalocker in d:\anaconda\envs\yi_env\lib\site-packages (from sacrebleu==1.5.0->lm-eval->autoawq) (2.8.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in d:\anaconda\envs\yi_env\lib\site-packages (from torchvision->autoawq) (10.0.1)
Requirement already satisfied: blessings in d:\anaconda\envs\yi_env\lib\site-packages (from colour-runner>=0.0.5->attributedict->autoawq) (1.7)
Requirement already satisfied: pygments in d:\anaconda\envs\yi_env\lib\site-packages (from colour-runner>=0.0.5->attributedict->autoawq) (2.17.2)
Requirement already satisfied: pyarrow>=8.0.0 in d:\anaconda\envs\yi_env\lib\site-packages (from datasets>=2.0.0->lm-eval->autoawq) (14.0.1)
Requirement already satisfied: dill<0.3.7,>=0.3.0 in d:\anaconda\envs\yi_env\lib\site-packages (from datasets>=2.0.0->lm-eval->autoawq) (0.3.6)
Requirement already satisfied: pandas in d:\anaconda\envs\yi_env\lib\site-packages (from datasets>=2.0.0->lm-eval->autoawq) (2.1.3)
Requirement already satisfied: xxhash in d:\anaconda\envs\yi_env\lib\site-packages (from datasets>=2.0.0->lm-eval->autoawq) (3.4.1)
Requirement already satisfied: multiprocess in d:\anaconda\envs\yi_env\lib\site-packages (from datasets>=2.0.0->lm-eval->autoawq) (0.70.14)
Requirement already satisfied: fsspec>=2021.11.1 in d:\anaconda\envs\yi_env\lib\site-packages (from fsspec[http]>=2021.11.1->datasets>=2.0.0->lm-eval->autoawq) (2023.10.0)
Requirement already satisfied: aiohttp in d:\anaconda\envs\yi_env\lib\site-packages (from datasets>=2.0.0->lm-eval->autoawq) (3.9.0)
Requirement already satisfied: ordered-set<4.2.0,>=4.0.2 in d:\anaconda\envs\yi_env\lib\site-packages (from deepdiff>=3.3.0->attributedict->autoawq) (4.1.0)
Requirement already satisfied: six>=1.11.0 in d:\anaconda\envs\yi_env\lib\site-packages (from inspecta>=0.1.0->attributedict->autoawq) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in d:\anaconda\envs\yi_env\lib\site-packages (from inspecta>=0.1.0->attributedict->autoawq) (2.3.0)
Requirement already satisfied: anyio<4,>=3.5.0 in d:\anaconda\envs\yi_env\lib\site-packages (from openai>=0.6.4->lm-eval->autoawq) (3.7.1)
Requirement already satisfied: distro<2,>=1.7.0 in d:\anaconda\envs\yi_env\lib\site-packages (from openai>=0.6.4->lm-eval->autoawq) (1.8.0)
Requirement already satisfied: httpx<1,>=0.23.0 in d:\anaconda\envs\yi_env\lib\site-packages (from openai>=0.6.4->lm-eval->autoawq) (0.25.2)
Requirement already satisfied: pydantic<3,>=1.9.0 in d:\anaconda\envs\yi_env\lib\site-packages (from openai>=0.6.4->lm-eval->autoawq) (2.5.1)
Requirement already satisfied: sniffio in d:\anaconda\envs\yi_env\lib\site-packages (from openai>=0.6.4->lm-eval->autoawq) (1.3.0)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\anaconda\envs\yi_env\lib\site-packages (from requests->transformers>=4.35.0->autoawq) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda\envs\yi_env\lib\site-packages (from requests->transformers>=4.35.0->autoawq) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda\envs\yi_env\lib\site-packages (from requests->transformers>=4.35.0->autoawq) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda\envs\yi_env\lib\site-packages (from requests->transformers>=4.35.0->autoawq) (2023.11.17)
Requirement already satisfied: coloredlogs>=10.0 in d:\anaconda\envs\yi_env\lib\site-packages (from rootpath>=0.1.0->attributedict->autoawq) (15.0.1)
Requirement already satisfied: absl-py in d:\anaconda\envs\yi_env\lib\site-packages (from rouge-score>=0.0.4->lm-eval->autoawq) (2.0.0)
Requirement already satisfied: nltk in d:\anaconda\envs\yi_env\lib\site-packages (from rouge-score>=0.0.4->lm-eval->autoawq) (3.8.1)
Requirement already satisfied: scipy>=1.5.0 in d:\anaconda\envs\yi_env\lib\site-packages (from scikit-learn>=0.24.1->lm-eval->autoawq) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in d:\anaconda\envs\yi_env\lib\site-packages (from scikit-learn>=0.24.1->lm-eval->autoawq) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in d:\anaconda\envs\yi_env\lib\site-packages (from scikit-learn>=0.24.1->lm-eval->autoawq) (3.2.0)
Requirement already satisfied: cachetools>=5.3.1 in d:\anaconda\envs\yi_env\lib\site-packages (from tox>=3.0.0->attributedict->autoawq) (5.3.2)
Requirement already satisfied: chardet>=5.2 in d:\anaconda\envs\yi_env\lib\site-packages (from tox>=3.0.0->attributedict->autoawq) (5.2.0)
Requirement already satisfied: colorama>=0.4.6 in d:\anaconda\envs\yi_env\lib\site-packages (from tox>=3.0.0->attributedict->autoawq) (0.4.6)
Requirement already satisfied: platformdirs>=3.10 in d:\anaconda\envs\yi_env\lib\site-packages (from tox>=3.0.0->attributedict->autoawq) (4.0.0)
Requirement already satisfied: pluggy>=1.3 in d:\anaconda\envs\yi_env\lib\site-packages (from tox>=3.0.0->attributedict->autoawq) (1.3.0)
Requirement already satisfied: pyproject-api>=1.6.1 in d:\anaconda\envs\yi_env\lib\site-packages (from tox>=3.0.0->attributedict->autoawq) (1.6.1)
Requirement already satisfied: tomli>=2.0.1 in d:\anaconda\envs\yi_env\lib\site-packages (from tox>=3.0.0->attributedict->autoawq) (2.0.1)
Requirement already satisfied: virtualenv>=20.24.3 in d:\anaconda\envs\yi_env\lib\site-packages (from tox>=3.0.0->attributedict->autoawq) (20.24.7)
Requirement already satisfied: MarkupSafe>=2.0 in d:\anaconda\envs\yi_env\lib\site-packages (from jinja2->torch>=2.0.1->autoawq) (2.1.1)
Requirement already satisfied: attrs>=19.2.0 in d:\anaconda\envs\yi_env\lib\site-packages (from jsonlines->lm-eval->autoawq) (23.1.0)
Requirement already satisfied: setuptools in d:\anaconda\envs\yi_env\lib\site-packages (from pycountry->lm-eval->autoawq) (68.0.0)
Requirement already satisfied: DataProperty<2,>=1.0.1 in d:\anaconda\envs\yi_env\lib\site-packages (from pytablewriter->lm-eval->autoawq) (1.0.1)
Requirement already satisfied: mbstrdecoder<2,>=1.0.0 in d:\anaconda\envs\yi_env\lib\site-packages (from pytablewriter->lm-eval->autoawq) (1.1.3)
Requirement already satisfied: pathvalidate<4,>=2.3.0 in d:\anaconda\envs\yi_env\lib\site-packages (from pytablewriter->lm-eval->autoawq) (3.2.0)
Requirement already satisfied: tabledata<2,>=1.3.1 in d:\anaconda\envs\yi_env\lib\site-packages (from pytablewriter->lm-eval->autoawq) (1.3.3)
Requirement already satisfied: tcolorpy<1,>=0.0.5 in d:\anaconda\envs\yi_env\lib\site-packages (from pytablewriter->lm-eval->autoawq) (0.1.4)
Requirement already satisfied: typepy<2,>=1.3.2 in d:\anaconda\envs\yi_env\lib\site-packages (from typepy[datetime]<2,>=1.3.2->pytablewriter->lm-eval->autoawq) (1.3.2)
Requirement already satisfied: mpmath>=0.19 in d:\anaconda\envs\yi_env\lib\site-packages (from sympy->torch>=2.0.1->autoawq) (1.3.0)
Requirement already satisfied: exceptiongroup in d:\anaconda\envs\yi_env\lib\site-packages (from anyio<4,>=3.5.0->openai>=0.6.4->lm-eval->autoawq) (1.2.0)
Requirement already satisfied: humanfriendly>=9.1 in d:\anaconda\envs\yi_env\lib\site-packages (from coloredlogs>=10.0->rootpath>=0.1.0->attributedict->autoawq) (10.0)
Requirement already satisfied: multidict<7.0,>=4.5 in d:\anaconda\envs\yi_env\lib\site-packages (from aiohttp->datasets>=2.0.0->lm-eval->autoawq) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in d:\anaconda\envs\yi_env\lib\site-packages (from aiohttp->datasets>=2.0.0->lm-eval->autoawq) (1.9.3)
Requirement already satisfied: frozenlist>=1.1.1 in d:\anaconda\envs\yi_env\lib\site-packages (from aiohttp->datasets>=2.0.0->lm-eval->autoawq) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in d:\anaconda\envs\yi_env\lib\site-packages (from aiohttp->datasets>=2.0.0->lm-eval->autoawq) (1.3.1)
Requirement already satisfied: async-timeout<5.0,>=4.0 in d:\anaconda\envs\yi_env\lib\site-packages (from aiohttp->datasets>=2.0.0->lm-eval->autoawq) (4.0.3)
Requirement already satisfied: httpcore==1.* in d:\anaconda\envs\yi_env\lib\site-packages (from httpx<1,>=0.23.0->openai>=0.6.4->lm-eval->autoawq) (1.0.2)
Requirement already satisfied: h11<0.15,>=0.13 in d:\anaconda\envs\yi_env\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai>=0.6.4->lm-eval->autoawq) (0.14.0)
Requirement already satisfied: annotated-types>=0.4.0 in d:\anaconda\envs\yi_env\lib\site-packages (from pydantic<3,>=1.9.0->openai>=0.6.4->lm-eval->autoawq) (0.6.0)
Requirement already satisfied: pydantic-core==2.14.3 in d:\anaconda\envs\yi_env\lib\site-packages (from pydantic<3,>=1.9.0->openai>=0.6.4->lm-eval->autoawq) (2.14.3)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.0 in d:\anaconda\envs\yi_env\lib\site-packages (from typepy[datetime]<2,>=1.3.2->pytablewriter->lm-eval->autoawq) (2.8.2)
Requirement already satisfied: pytz>=2018.9 in d:\anaconda\envs\yi_env\lib\site-packages (from typepy[datetime]<2,>=1.3.2->pytablewriter->lm-eval->autoawq) (2023.3.post1)
Requirement already satisfied: distlib<1,>=0.3.7 in d:\anaconda\envs\yi_env\lib\site-packages (from virtualenv>=20.24.3->tox>=3.0.0->attributedict->autoawq) (0.3.7)
Requirement already satisfied: click in d:\anaconda\envs\yi_env\lib\site-packages (from nltk->rouge-score>=0.0.4->lm-eval->autoawq) (8.1.7)
Requirement already satisfied: tzdata>=2022.1 in d:\anaconda\envs\yi_env\lib\site-packages (from pandas->datasets>=2.0.0->lm-eval->autoawq) (2023.3)
Requirement already satisfied: pywin32>=226 in d:\anaconda\envs\yi_env\lib\site-packages (from portalocker->sacrebleu==1.5.0->lm-eval->autoawq) (306)
Requirement already satisfied: pyreadline3 in d:\anaconda\envs\yi_env\lib\site-packages (from humanfriendly>=9.1->coloredlogs>=10.0->rootpath>=0.1.0->attributedict->autoawq) (3.4.1)

**Comment by jdunne525** [comment]
For me, I got an error when I tried that command.  The relevant bit was this:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.1.0+cu118 requires torch==2.1.0+cu118, but you have torch 2.1.1 which is incompatible.
```

So I uninstalled torch and torch audio, then ran the command again:
`pip install -v autoawq again`

Now I seem to have regular torch and torchaudio instead of the cu118 versions.

That worked, but didn't fix the error loading the model.  It seems that I was supposed to have a cu118 version, but it didn't fully install for some reason.  This seems like it's related to my issue.

**Comment by Urammar** [comment]
For whatever its worth, im having the exact same issue as these guys, with the same steps giving me the same results. All requirements satisfied, running the latest version.

**Comment by casper-hansen** [comment]
> For whatever its worth, im having the exact same issue as these guys, with the same steps giving me the same results. All requirements satisfied, running the latest version.

Make sure you meet the following requirements :)

- If on windows, must use WSL 2
- CUDA toolkit 12.1
- Graphics card of RTX 2000-series or newer (compute capability 7.5)
- A fresh conda environment with CUDA dependencies correctly installed

**Comment by jdunne525** [comment]
I believe the issue is related to having a python installation with certain python modules already loaded which are incompatible with what oobabooga is trying to install. I think if I uninstall and reinstall python then install oobabooga, it might work, but I haven't had a chance to try that yet.

I'm no expert, but I believe oobabooga should use a python virtual environment to solve this instead of using the system python.
