### ISSUE TITLE
unable to load multimodal model with error KeyError: 'llava' (liuhaotian_llava-v1.5-7b)

### ISSUE THREAD

**Issue by ThatCoffeeGuy** [oobabooga/text-generation-webui#4692]
### Describe the bug

unable to load freshly downloaded multimodal model with error KeyError: 'llava'

Following the [instructions](https://github.com/oobabooga/text-generation-webui/tree/main/extensions/multimodal), after downloading the model, I am facing this issue:

```
sadmin@aiml:~/text-generation-webui$ ./start_linux.sh --listen --api --verbose --model liuhaotian_llava-v1.5-7b --multimodal-pipeline llava-v1.5-7b --load-in-4bit
2023-11-21 16:21:00 WARNING:
You are potentially exposing the web UI to the entire internet without any access password.
You can create one with the "--gradio-auth" flag like this:

--gradio-auth username:password

Make sure to replace username:password with your own.
2023-11-21 16:21:02 INFO:Loading liuhaotian_llava-v1.5-7b...
Traceback (most recent call last):
  File "/home/sadmin/text-generation-webui/server.py", line 223, in <module>
    shared.model, shared.tokenizer = load_model(model_name)
  File "/home/sadmin/text-generation-webui/modules/models.py", line 85, in load_model
    output = load_func_map[loader](model_name)
  File "/home/sadmin/text-generation-webui/modules/models.py", line 142, in huggingface_loader
    config = AutoConfig.from_pretrained(path_to_model, trust_remote_code=params['trust_remote_code'])
  File "/home/sadmin/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1064, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/home/sadmin/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 761, in __getitem__
    raise KeyError(key)
KeyError: 'llava'
```

If I run it without the model, the extension installs the required libraries it seems (and a file about 1.5GB) but with the model specified, it crashes with the keyerror. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I believe the description has all the information on how to reproduce this. 

I am using: https://huggingface.co/liuhaotian/llava-v1.5-7b

### Logs

```shell
sadmin@aiml:~/text-generation-webui$ ./start_linux.sh --listen --api --verbose --model liuhaotian_llava-v1.5-7b --multimodal-pipeline llava-v1.5-7b --load-in-4bit
2023-11-21 16:21:00 WARNING:
You are potentially exposing the web UI to the entire internet without any access password.
You can create one with the "--gradio-auth" flag like this:

--gradio-auth username:password

Make sure to replace username:password with your own.
2023-11-21 16:21:02 INFO:Loading liuhaotian_llava-v1.5-7b...
Traceback (most recent call last):
  File "/home/sadmin/text-generation-webui/server.py", line 223, in <module>
    shared.model, shared.tokenizer = load_model(model_name)
  File "/home/sadmin/text-generation-webui/modules/models.py", line 85, in load_model
    output = load_func_map[loader](model_name)
  File "/home/sadmin/text-generation-webui/modules/models.py", line 142, in huggingface_loader
    config = AutoConfig.from_pretrained(path_to_model, trust_remote_code=params['trust_remote_code'])
  File "/home/sadmin/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1064, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/home/sadmin/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 761, in __getitem__
    raise KeyError(key)
KeyError: 'llava'
```

### System Info

```shell
Ubuntu, RTX 3090.
```

edit: I use thebloke's version of 13b:main, it loasd well, but after inserting an image the whole thing crashes with:

ValueError: The embed_tokens method has not been found for this loader.

edit2: after enabling trust-remote-code, I get RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 5120 but got size 4096 for tensor number 1 in the list for AutoGPTQ.

edit3: seems I forgot to change multimodal to 13b.

edit4: It works like this now:

![image](https://github.com/oobabooga/text-generation-webui/assets/24213618/7c09206a-c008-43bf-b3c8-228386e73e6f)

**Comment by psdwizzard** [comment]
how did you solve this I am trying that model but and I added the flags to CMD_FLAGs.txt but it still wont launch

# --listen --api --chat --trust-remote-code --model TheBloke_llava-v1.5-13B-GPTQ_gptq-4bit-32g-actorder_True --multimodal-pipeline llava-v1.5-13b --disable_exllama --loader autogptq


thanks for the help

**Comment by theoden8** [comment]
I have the same issue when using liuhaotian_llava-v1.5-13b with llava-v1.5-13b pipeline

**Comment by psdwizzard** [comment]
did not help but thanks

**Comment by theoden8** [comment]
@psdwizzard that's strange. The CONFIG_MAPPING variable just doesn't have llava key, so changing model_type to llama helps to access key that works, right?

**Comment by claudius-kienle** [comment]
> @psdwizzard that's strange. The CONFIG_MAPPING variable just doesn't have llava key, so changing model_type to llama helps to access key that works, right?

The issue might be that you trying to load a llava model with a too old version of the `transformers` package. The `llava` model was added in `transformers` version `4.36.0` (https://github.com/huggingface/transformers/commit/44b5506d29326c6f2ae672e78d2df78ec55939d9)
