### ISSUE TITLE
One click installer failing on Mac (Apple Silicon M1 Max)

### ISSUE THREAD

**Issue by CyborgArmy83** [oobabooga/text-generation-webui#4693]
### Describe the bug

I've tried running the one click installer but cannot get it to work on my M1 Max.
I followed the steps closely and it used to work perfectly around two months ago, but now I cannot get the installation to succeed. It also doesn't ask anymore which kind of CPU I have (I had to manually dial a number before)

Seems like there is something buggy with the installer, any help is appreciated! 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. clone the main rep.
2. run: sh start_macos.sh 
3. Installer fails 

### Logs

```shell
john83@mac o % sh start_macos.sh
Downloading Miniconda from https://repo.anaconda.com/miniconda/Miniconda3-py310_23.3.1-0-MacOSX-arm64.sh to /Users/john83/downloads/o/installer_files/miniconda_installer.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 42.6M  100 42.6M    0     0  6872k      0  0:00:06  0:00:06 --:--:-- 7641k
PREFIX=/Users/john83/downloads/o/installer_files/conda
Unpacking payload ...
                                                                                
Installing base environment...


Downloading and Extracting Packages


Downloading and Extracting Packages

Preparing transaction: done
Executing transaction: - 
done
installation finished.
Miniconda version:
conda 23.3.1
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.3.1
  latest version: 23.10.0

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.10.0



## Package Plan ##

  environment location: /Users/john83/downloads/o/installer_files/env

  added / updated specs:
    - python=3.11


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2023.08.22 |       hca03da5_0         124 KB
    libffi-3.4.4               |       hca03da5_0         120 KB
    openssl-3.0.12             |       h1a28f6b_0         4.3 MB
    pip-23.3                   |  py311hca03da5_0         3.3 MB
    python-3.11.5              |       hb885b13_0        15.4 MB
    setuptools-68.0.0          |  py311hca03da5_0         1.2 MB
    sqlite-3.41.2              |       h80987f9_0         1.1 MB
    wheel-0.41.2               |  py311hca03da5_0         142 KB
    xz-5.4.2                   |       h80987f9_0         369 KB
    ------------------------------------------------------------
                                           Total:        26.2 MB

The following NEW packages will be INSTALLED:

  bzip2              pkgs/main/osx-arm64::bzip2-1.0.8-h620ffc9_4 
  ca-certificates    pkgs/main/osx-arm64::ca-certificates-2023.08.22-hca03da5_0 
  libffi             pkgs/main/osx-arm64::libffi-3.4.4-hca03da5_0 
  ncurses            pkgs/main/osx-arm64::ncurses-6.4-h313beb8_0 
  openssl            pkgs/main/osx-arm64::openssl-3.0.12-h1a28f6b_0 
  pip                pkgs/main/osx-arm64::pip-23.3-py311hca03da5_0 
  python             pkgs/main/osx-arm64::python-3.11.5-hb885b13_0 
  readline           pkgs/main/osx-arm64::readline-8.2-h1a28f6b_0 
  setuptools         pkgs/main/osx-arm64::setuptools-68.0.0-py311hca03da5_0 
  sqlite             pkgs/main/osx-arm64::sqlite-3.41.2-h80987f9_0 
  tk                 pkgs/main/osx-arm64::tk-8.6.12-hb8d0fd4_0 
  tzdata             pkgs/main/noarch::tzdata-2023c-h04d1e81_0 
  wheel              pkgs/main/osx-arm64::wheel-0.41.2-py311hca03da5_0 
  xz                 pkgs/main/osx-arm64::xz-5.4.2-h80987f9_0 
  zlib               pkgs/main/osx-arm64::zlib-1.2.13-h5a0b063_0 



Downloading and Extracting Packages
                                                                                
Preparing transaction: done                                                     
Verifying transaction: done                                                     
Executing transaction: done                                                     
#                                                                               
# To activate this environment, use                                             
#                                                                               
#     $ conda activate /Users/john83/downloads/o/installer_files/env             
#                                                                               
# To deactivate an active environment, use
#
#     $ conda deactivate



*******************************************************************
* WARNING: You haven't downloaded any model yet.
* Once the web UI launches, head over to the "Model" tab and download one.
*******************************************************************


Traceback (most recent call last):
  File "/Users/john83/Downloads/o/server.py", line 5, in <module>
    from modules.block_requests import OpenMonkeyPatch, RequestBlocker
  File "/Users/john83/Downloads/o/modules/block_requests.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
john83@mac o %
```

### System Info

```shell
Apple M1 Max, latest Sonoma
```

**Comment by lufixSch** [comment]
Maybe the issue is related to #4537. Its a pretty long discussion [this](https://github.com/oobabooga/text-generation-webui/issues/4537#issuecomment-1812391770) comment is the important one for you.

The short version: SYSTEM_VERSION_COMPAT=0 ./start_macos.sh

**Comment by easp** [comment]
Same issue, SYSTEM_VERSION_COMPAT=0 ./start_macos.sh doesn't help.

It seems like the requirements* files aren't being used at all.

**Comment by lufixSch** [comment]
Maybe the installation failed when on you first try and now the startup script thinks everything is installed.

Try running `./update_macos.sh` this should force a reinstall of the requirements.

**Comment by easp** [comment]
Thanks. I wondered about that and so before posting my comment I deleted the whole text-generation-webui directory and then cloned it again and tried with SYSTEM_VERSION_COMPAT=0 ./start_macos.sh. I ended up activating the environment and installing the requirements manually.

Started fresh again and then tried ./update_macos.sh . The output
```
Already up to date.
Traceback (most recent call last):
  File "/Users/eas/Library/Mobile Documents/com~apple~CloudDocs/prj/text-generation-webui/one_click.py", line 377, in <module>
    update_requirements()
  File "/Users/eas/Library/Mobile Documents/com~apple~CloudDocs/prj/text-generation-webui/one_click.py", line 268, in update_requirements
    torver = torch_version()
             ^^^^^^^^^^^^^^^
  File "/Users/eas/Library/Mobile Documents/com~apple~CloudDocs/prj/text-generation-webui/one_click.py", line 83, in torch_version
    from torch import __version__ as torver
ModuleNotFoundError: No module named 'torch'```

**Comment by lufixSch** [comment]
> Thanks. I wondered about that and so before posting my comment I deleted the whole text-generation-webui directory and then cloned it again and tried with SYSTEM_VERSION_COMPAT=0 ./start_macos.sh.

That is really strange behavior. I have no idea how that happens. Do you by any chance still have the complete output of that?

> Started fresh again and then tried ./update_macos.sh 

You can not run `update_macos.sh` without running `start_macos.sh` at least once. `update_macos.sh` will only install the `requirements*.txt` but skip the installation of base packages like torch

**Comment by easp** [comment]
> That is really strange behavior. I have no idea how that happens. Do you by any chance still have the complete output of that?

```
 prj % rm -rf text-generation-webui
 prj % git clone https://github.com/oobabooga/text-generation-webui.git
Cloning into 'text-generation-webui'...
remote: Enumerating objects: 14356, done.
remote: Counting objects: 100% (1807/1807), done.
remote: Compressing objects: 100% (290/290), done.
remote: Total 14356 (delta 1609), reused 1640 (delta 1516), pack-reused 12549
Receiving objects: 100% (14356/14356), 25.74 MiB | 50.69 MiB/s, done.
Resolving deltas: 100% (9935/9935), done.
 prj % cd text-generation-webui 
 text-generation-webui % SYSTEM_VERSION_COMPAT=0 ./start_macos.sh                        
Downloading Miniconda from https://repo.anaconda.com/miniconda/Miniconda3-py310_23.3.1-0-MacOSX-arm64.sh to /Users/someguy/prj/text-generation-webui/installer_files/miniconda_installer.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 42.6M  100 42.6M    0     0  43.7M      0 --:--:-- --:--:-- --:--:-- 43.9M
PREFIX=/Users/someguy/prj/text-generation-webui/installer_files/conda
Unpacking payload ...
                                                                                                                                    
Installing base environment...


Downloading and Extracting Packages


Downloading and Extracting Packages

Preparing transaction: done
Executing transaction: | 
done
installation finished.
Miniconda version:
conda 23.3.1
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.3.1
  latest version: 23.10.0

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.10.0



## Package Plan ##

  environment location: /Users/someguy/prj/text-generation-webui/installer_files/env

  added / updated specs:
    - python=3.11


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2023.08.22 |       hca03da5_0         124 KB
    libffi-3.4.4               |       hca03da5_0         120 KB
    openssl-3.0.12             |       h1a28f6b_0         4.3 MB
    pip-23.3.1                 |  py311hca03da5_0         3.3 MB
    python-3.11.5              |       hb885b13_0        15.4 MB
    setuptools-68.0.0          |  py311hca03da5_0         1.2 MB
    sqlite-3.41.2              |       h80987f9_0         1.1 MB
    wheel-0.41.2               |  py311hca03da5_0         142 KB
    xz-5.4.2                   |       h80987f9_0         369 KB
    ------------------------------------------------------------
                                           Total:        26.2 MB

The following NEW packages will be INSTALLED:

  bzip2              pkgs/main/osx-arm64::bzip2-1.0.8-h620ffc9_4 
  ca-certificates    pkgs/main/osx-arm64::ca-certificates-2023.08.22-hca03da5_0 
  libffi             pkgs/main/osx-arm64::libffi-3.4.4-hca03da5_0 
  ncurses            pkgs/main/osx-arm64::ncurses-6.4-h313beb8_0 
  openssl            pkgs/main/osx-arm64::openssl-3.0.12-h1a28f6b_0 
  pip                pkgs/main/osx-arm64::pip-23.3.1-py311hca03da5_0 
  python             pkgs/main/osx-arm64::python-3.11.5-hb885b13_0 
  readline           pkgs/main/osx-arm64::readline-8.2-h1a28f6b_0 
  setuptools         pkgs/main/osx-arm64::setuptools-68.0.0-py311hca03da5_0 
  sqlite             pkgs/main/osx-arm64::sqlite-3.41.2-h80987f9_0 
  tk                 pkgs/main/osx-arm64::tk-8.6.12-hb8d0fd4_0 
  tzdata             pkgs/main/noarch::tzdata-2023c-h04d1e81_0 
  wheel              pkgs/main/osx-arm64::wheel-0.41.2-py311hca03da5_0 
  xz                 pkgs/main/osx-arm64::xz-5.4.2-h80987f9_0 
  zlib               pkgs/main/osx-arm64::zlib-1.2.13-h5a0b063_0 



Downloading and Extracting Packages
                                                                                                                                    
Preparing transaction: done                                                                                                         
Verifying transaction: done                                                                                                         
Executing transaction: done                                                                                                         
#                                                                                                                                   
# To activate this environment, use                                                                                                 
#                                                                                                                                   
#     $ conda activate /Users/someguy/prj/text-generation-webui/installer_files/env                                                     
#                                                                                                                                   
# To deactivate an active environment, use
#
#     $ conda deactivate



*******************************************************************
* WARNING: You haven't downloaded any model yet.
* Once the web UI launches, head over to the "Model" tab and download one.
*******************************************************************


Traceback (most recent call last):
  File "/Users/someguy/Library/Mobile Documents/com~apple~CloudDocs/prj/text-generation-webui/server.py", line 5, in <module>
    from modules.block_requests import OpenMonkeyPatch, RequestBlocker
  File "/Users/someguy/Library/Mobile Documents/com~apple~CloudDocs/prj/text-generation-webui/modules/block_requests.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by lufixSch** [comment]
Sorry for taking so long to answer. It looks like the complete install sequence is being skipped. But I'm unsure why this happens.

Could you check the `installer_files` directory for me?
```bash
ls -al installer_files/env
ls -al installer_files/lib/python3.11/site-packages/torch
```

Another idea would be to check the output of the function which is used to detect if the install sequence should be triggered. If you feel comfortable editing the `one_click.py`. 
Add `print(f"DEBUG PRINT: {site_packages_path}")` after line 104. It should look something like this:

```python
for sitedir in site.getsitepackages():
        if "site-packages" in sitedir and conda_env_path in sitedir:
            site_packages_path = sitedir
            break

print(f"DEBUG PRINT: {site_packages_path}")

if site_packages_path:
```

**Comment by easp** [comment]
Here are the directory listings. I'll try the second suggestion later.

```% ls -al installer_files/env
total 16
drwxr-xr-x@  10 eas  staff   320 Nov 25 18:45 .
drwxr-xr-x@   6 eas  staff   192 Nov 25 18:46 ..
-rw-r--r--@   1 eas  staff  6148 Nov 30 14:17 .DS_Store
drwxr-xr-x@  71 eas  staff  2272 Nov 25 18:45 bin
drwxr-xr-x@  18 eas  staff   576 Nov 25 18:44 conda-meta
drwxr-xr-x@ 113 eas  staff  3616 Nov 25 18:43 include
drwxr-xr-x@  91 eas  staff  2912 Nov 25 18:45 lib
drwxr-xr-x@   3 eas  staff    96 Nov 25 16:43 man
drwxr-xr-x@   9 eas  staff   288 Nov 25 18:42 share
drwxr-xr-x@   9 eas  staff   288 Nov 25 18:41 ssl
% ls -al installer_files/lib/python3.11/site-packages/torch
ls: installer_files/lib/python3.11/site-packages/torch: No such file or directory
% ls -al installer_files 
total 87344
drwxr-xr-x@  6 eas  staff       192 Nov 25 18:46 .
drwxr-xr-x@ 84 eas  staff      2688 Nov 25 18:46 ..
-rw-r--r--@  1 eas  staff      6148 Nov 30 14:17 .DS_Store
drwxr-xr-x@ 19 eas  staff       608 Nov 25 18:46 conda
drwxr-xr-x@ 10 eas  staff       320 Nov 25 18:45 env
-rwxr-xr-x@  1 eas  staff  44711048 Nov 25 16:26 miniconda_installer.sh```

**Comment by lufixSch** [comment]
Thanks but I messed up the second command.
It should be ls -al installer_files/env/lib/python3.11/site-packages/torch

**Comment by easp** [comment]
Same result
```
% ls -al installer_files/env/lib/python3.11/site-packages/torch 
ls: installer_files/env/lib/python3.11/site-packages/torch: No such file or directory
```
Looks like the installer didn't get very far:
```
% ls -al installer_files/env/lib/python3.11/site-packages 
total 32
drwxr-xr-x@  13 eas  staff   416 Nov 25 16:55 .
drwxr-xr-x@ 211 eas  staff  6752 Nov 25 18:41 ..
-rw-r--r--@   1 eas  staff  6148 Nov 30 14:17 .DS_Store
-rw-rw-r--    2 eas  staff   119 Sep 11 06:36 README.txt
drwxr-xr-x@   5 eas  staff   160 Nov 25 17:17 _distutils_hack
-rw-rw-r--    2 eas  staff   151 Jul 25 06:14 distutils-precedence.pth
drwxr-xr-x@   9 eas  staff   288 Nov 25 17:17 pip
drwxr-xr-x@   8 eas  staff   256 Nov 25 17:17 pip-23.3.1-py3.11.egg-info
drwxr-xr-x@   6 eas  staff   192 Nov 25 17:17 pkg_resources
drwxr-xr-x@  49 eas  staff  1568 Nov 25 17:17 setuptools
drwxr-xr-x@   8 eas  staff   256 Nov 25 17:17 setuptools-68.0.0-py3.11.egg-info
drwxr-xr-x@  13 eas  staff   416 Nov 25 17:17 wheel
drwxr-xr-x@   7 eas  staff   224 Nov 25 17:17 wheel-0.41.2.dist-info
```

**Comment by mongolu** [comment]
I see a lot of activity in this issue which is about errors on Mac.
Just a question: have you tried to use Docker? It may help because it uses a Linux distro which could prove not to raise errors.
And it's pretty simple to use it also

**Comment by easp** [comment]
@mongolu. Thanks for the suggestion. MacOS is UNIX(tm) but its not Linux and Docker depends on Linux-isms. Therefore Docker on MacOS runs in a linux VM. MacOS's hypervisor doesn't currently support GPU passthrough so running this in Docker on Mac wouldn't have GPU acceleration. 

That wouldn't actually be as horrible as it is on PCs since the Apple Silicon Macs have higher memory bandwidth than consumer-grade PCs (but less than a typical NVIDIA GPU). Still, I'd rather have the GPU acceleration. Someone put the effort into making a MacOS-specific install script. It's worth some effort to make it more reliable.

**Comment by mongolu** [comment]
Didn't know that, thought in this era all major OSes could use Docker at full potential.
Well, I hope you get it sorted out. Cheers!

**Comment by santanaluiz** [comment]
same problem

**Comment by easp** [comment]
@lufixSch 

I added that line in the one_click.py. The line numbers didn't match and there were two functions -- is_installed() and torch_version() -- with code matching the context you provided, so I added it to both. Looks like only one of the functions was called.

This is the output 

```
% ./start_macos.sh 
Downloading Miniconda from https://repo.anaconda.com/miniconda/Miniconda3-py310_23.3.1-0-MacOSX-arm64.sh to /Users/ME/prj/text-generation-webui/installer_files/miniconda_installer.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 42.6M  100 42.6M    0     0  33.4M      0  0:00:01  0:00:01 --:--:-- 33.5M
PREFIX=/Users/ME/prj/text-generation-webui/installer_files/conda
Unpacking payload ...
                                                                                                                                 
Installing base environment...


Downloading and Extracting Packages


Downloading and Extracting Packages

Preparing transaction: done
Executing transaction: - 
done
installation finished.
Miniconda version:
conda 23.3.1
Retrieving notices: ...working... /Users/ME/prj/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'conda.anaconda.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
done
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/ME/prj/text-generation-webui/installer_files/env

  added / updated specs:
    - python=3.11


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bzip2-1.0.8                |       h93a5062_5         119 KB  conda-forge
    ca-certificates-2023.11.17 |       hf0a4a13_0         151 KB  conda-forge
    libexpat-2.5.0             |       hb7217d7_1          62 KB  conda-forge
    libffi-3.4.2               |       h3422bc3_5          38 KB  conda-forge
    libsqlite-3.44.2           |       h091b4b1_0         796 KB  conda-forge
    libzlib-1.2.13             |       h53f4e23_5          47 KB  conda-forge
    ncurses-6.4                |       h463b476_2         776 KB  conda-forge
    openssl-3.2.0              |       h0d3ecfb_1         2.7 MB  conda-forge
    pip-23.3.1                 |     pyhd8ed1ab_0         1.3 MB  conda-forge
    python-3.11.6              |h47c9636_0_cpython        13.9 MB  conda-forge
    readline-8.2               |       h92ec313_1         244 KB  conda-forge
    setuptools-68.2.2          |     pyhd8ed1ab_0         454 KB  conda-forge
    tk-8.6.13                  |       h5083fa2_1         3.0 MB  conda-forge
    tzdata-2023c               |       h71feb2d_0         115 KB  conda-forge
    wheel-0.42.0               |     pyhd8ed1ab_0          56 KB  conda-forge
    xz-5.2.6                   |       h57fd34a_0         230 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        24.0 MB

The following NEW packages will be INSTALLED:

  bzip2              conda-forge/osx-arm64::bzip2-1.0.8-h93a5062_5 
  ca-certificates    conda-forge/osx-arm64::ca-certificates-2023.11.17-hf0a4a13_0 
  libexpat           conda-forge/osx-arm64::libexpat-2.5.0-hb7217d7_1 
  libffi             conda-forge/osx-arm64::libffi-3.4.2-h3422bc3_5 
  libsqlite          conda-forge/osx-arm64::libsqlite-3.44.2-h091b4b1_0 
  libzlib            conda-forge/osx-arm64::libzlib-1.2.13-h53f4e23_5 
  ncurses            conda-forge/osx-arm64::ncurses-6.4-h463b476_2 
  openssl            conda-forge/osx-arm64::openssl-3.2.0-h0d3ecfb_1 
  pip                conda-forge/noarch::pip-23.3.1-pyhd8ed1ab_0 
  python             conda-forge/osx-arm64::python-3.11.6-h47c9636_0_cpython 
  readline           conda-forge/osx-arm64::readline-8.2-h92ec313_1 
  setuptools         conda-forge/noarch::setuptools-68.2.2-pyhd8ed1ab_0 
  tk                 conda-forge/osx-arm64::tk-8.6.13-h5083fa2_1 
  tzdata             conda-forge/noarch::tzdata-2023c-h71feb2d_0 
  wheel              conda-forge/noarch::wheel-0.42.0-pyhd8ed1ab_0 
  xz                 conda-forge/osx-arm64::xz-5.2.6-h57fd34a_0 



Downloading and Extracting Packages
                                                                                                                                 
Preparing transaction: done                                                                                                      
Verifying transaction: done                                                                                                      
Executing transaction: done                                                                                                      
#                                                                                                                                
# To activate this environment, use                                                                                              
#                                                                                                                                
#     $ conda activate /Users/ME/prj/text-generation-webui/installer_files/env                                                  
#                                                                                                                                
# To deactivate an active environment, use                                                                                       
#                                                                                                                                
#     $ conda deactivate                                                                                                         
                                                                                                                                 
DEBUG PRINT: None                                                                                                                
                                                                                                                                 
                                                                                                                                 
*******************************************************************
* WARNING: You haven't downloaded any model yet.
* Once the web UI launches, head over to the "Model" tab and download one.
*******************************************************************


Traceback (most recent call last):
  File "/Users/ME/Library/Mobile Documents/com~apple~CloudDocs/prj/text-generation-webui/server.py", line 5, in <module>
    from modules.block_requests import OpenMonkeyPatch, RequestBlocker
  File "/Users/ME/Library/Mobile Documents/com~apple~CloudDocs/prj/text-generation-webui/modules/block_requests.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by easp** [comment]
@mongolu Thanks for that link. I've tried it out before and it seems good.

I wanted to try out text-generation-webui since a lot of people seem to be using it.

**Comment by lufixSch** [comment]
> I added that line in the one_click.py. The line numbers didn't match and there were two functions -- is_installed() and torch_version() -- with code matching the context you provided, so I added it to both. Looks like only one of the functions was called.

Maybe something was changed in the last update. `is_installed()` was the right function. It looks like the `site_packages` directory is not located.

@easp do you by any chance use a unusual python setup? Like different python versions, virtual environments or an alias for the `python` or `python3` command?

**Comment by easp** [comment]
I remembered that I'd previously tried deactivating my base conda environment before running the installer, but forgot to do it before trying the install again and posting the output above. 

I just deactivated the conda environment, deleted the downloaded repos, cloned it again, added that debug line again and reran start_macos.sh and got the same result.

As to my non-conda python environment. It looks like I have a python3 installed by homebrew (which isn't particularly unusual).  It does look like "CONDA_PYTHON_EXE=/Users/eas/miniforge3/bin/python" remains set even if I deactivate the base conda environment. Tried unsetting it, deleting ./installer_files and running start_macos.sh again. No improvement.

**Comment by dkrantsberg** [comment]
I had the same issue when doing the manual installation. 

This apparently happened b/c I had python installed with homebrew and some of the packages (including `requests`) got already installed under  /opt/homebrew/lib/python3.11/site-packages/* . 

I was able to solve it with the following
1. `pip uninstall -r requirements_apple_silicon.txt -y` to uninstall all the required packages from the /homebrew/.. dir. 
2. `python -m pip uninstall -r requirements_apple_silicon.txt` to install all the packages to the conda managed environment

Make sure that in step 1 `pip` is located under /homebew/bin and in step 2 `python` is located under the conda managed folder. Use `which pip` and `which python` commands to check.

**Comment by lufixSch** [comment]
@easp Thad sounds like a pretty standard setup. The installation script should have no problem with an active conda base environment or a home brew installation of python.

I still have some more Ideas for debugging like logging `site.getsitepackages()` or activating the venv and checking everything manually but maybe @oobabooga knows whats happening without trying all that.
An easy workaround would be to just activate the venv and install the requirements manually.
