### ISSUE TITLE
The server errors out if http_proxy is defined in the environment

### ISSUE THREAD

**Issue by gerroon** [oobabooga/text-generation-webui#4714]
### Describe the bug

I have http proxy (privoxy) defined in the environment for internet access. This seems to cause the server to fail during startup

This is my windows env for it
`set http_proxy=http://192.168.1.100:8118`

I can start ComfyUI from the same env and it does not have an issue. Not sure maybe a gradio problem?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Add http_proxy to your shell/windows environment

### Logs

```shell
bin c:\oobabooga_text-generation-webui\installer_files\env\Lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so
c:\oobabooga_text-generation-webui\installer_files\env\Lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
function 'cadam32bit_grad_fp32' not found
2023-11-23 11:22:58 INFO:Loading the extension "gallery"...
Running on local URL:  http://0.0.0.0:7860
Traceback (most recent call last):
  File "c:\oobabooga_text-generation-webui\server.py", line 236, in <module>
    create_interface()
  File "c:\oobabooga_text-generation-webui\server.py", line 147, in create_interface
    shared.gradio['interface'].launch(
  File "c:\oobabooga_text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 2115, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.
```

### System Info

```shell
Windows 11, RTX 2070
```

**Comment by yzx1208** [comment]
TypeError: replace() argument 1 must be str, not bytes
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\Users\DEMON\Downloads\Compressed\text-generation-webui-snapshot-2024-01-07-cpu\server.py:254 in <module>          │
│                                                                                                                      │
│   253         # Launch the web UI                                                                                    │
│ ❱ 254         create_interface()                                                                                     │
│   255         while True:                                                                                            │
│                                                                                                                      │
│ C:\Users\DEMON\Downloads\Compressed\text-generation-webui-snapshot-2024-01-07-cpu\server.py:162 in create_interface  │
│                                                                                                                      │
│   161     with OpenMonkeyPatch():                                                                                    │
│ ❱ 162         shared.gradio['interface'].launch(                                                                     │
│   163             prevent_thread_lock=True,                                                                          │
│                                                                                                                      │
│ C:\Users\DEMON\Downloads\Compressed\text-generation-webui-snapshot-2024-01-07-cpu\installer_files\env\Lib\site-packa │
│ ges\gradio\blocks.py:2115 in launch                                                                                  │
│                                                                                                                      │
│   2114         ):                                                                                                    │
│ ❱ 2115             raise ValueError(                                                                                 │
│   2116                 "When localhost is not accessible, a shareable link must be created. Ple                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your
proxy settings to allow access to localhost.
请按任意键继续. . .
