### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'perplexities_list'

### ISSUE THREAD

**Issue by swumagic** [oobabooga/text-generation-webui#4726]
### Describe the bug

Traceback (most recent call last):
  File "D:\airj\text-generation-webui\text-generation-webui\modules\callbacks.py", line 57, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "D:\airj\text-generation-webui\text-generation-webui\modules\llamacpp_model.py", line 141, in generate
    completion_chunks = self.model.create_completion(
TypeError: Llama.create_completion() got an unexpected keyword argument 'min_p'
Output generated in 0.64 seconds (0.00 tokens/s, 0 tokens, context 6907, seed 298389553)
Traceback (most recent call last):
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 519, in async_iteration
    return await iterator.__anext__()
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "D:\airj\text-generation-webui\text-generation-webui\modules\chat.py", line 342, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True)):
  File "D:\airj\text-generation-webui\text-generation-webui\modules\chat.py", line 310, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "D:\airj\text-generation-webui\text-generation-webui\modules\chat.py", line 278, in chatbot_wrapper
    output['visible'][-1][1] = apply_extensions('output', output['visible'][-1][1], state, is_chat=True)
  File "D:\airj\text-generation-webui\text-generation-webui\modules\extensions.py", line 224, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "D:\airj\text-generation-webui\text-generation-webui\modules\extensions.py", line 82, in _apply_string_extensions
    text = func(*args, **kwargs)
  File "D:\airj\text-generation-webui\text-generation-webui\extensions\perplexity_colors\script.py", line 103, in output_modifier
    perplexities = ppl_logits_processor.perplexities_list[:-1]
AttributeError: 'NoneType' object has no attribute 'perplexities_list'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

AttributeError: 'NoneType' object has no attribute 'perplexities_list'

### Logs

```shell
Traceback (most recent call last):
  File "D:\airj\text-generation-webui\text-generation-webui\modules\callbacks.py", line 57, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "D:\airj\text-generation-webui\text-generation-webui\modules\llamacpp_model.py", line 141, in generate
    completion_chunks = self.model.create_completion(
TypeError: Llama.create_completion() got an unexpected keyword argument 'min_p'
Output generated in 0.64 seconds (0.00 tokens/s, 0 tokens, context 6907, seed 298389553)
Traceback (most recent call last):
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 519, in async_iteration
    return await iterator.__anext__()
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "D:\airj\text-generation-webui\text-generation-webui\modules\chat.py", line 342, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True)):
  File "D:\airj\text-generation-webui\text-generation-webui\modules\chat.py", line 310, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "D:\airj\text-generation-webui\text-generation-webui\modules\chat.py", line 278, in chatbot_wrapper
    output['visible'][-1][1] = apply_extensions('output', output['visible'][-1][1], state, is_chat=True)
  File "D:\airj\text-generation-webui\text-generation-webui\modules\extensions.py", line 224, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "D:\airj\text-generation-webui\text-generation-webui\modules\extensions.py", line 82, in _apply_string_extensions
    text = func(*args, **kwargs)
  File "D:\airj\text-generation-webui\text-generation-webui\extensions\perplexity_colors\script.py", line 103, in output_modifier
    perplexities = ppl_logits_processor.perplexities_list[:-1]
AttributeError: 'NoneType' object has no attribute 'perplexities_list'
```

### System Info

```shell
win11,4090，py310.11
```

**Comment by whitepapercg** [comment]
We can use logits in web-ui and API but not this extension, I couldn't figure out definitively what the cause of the error is

**Comment by Anaeijon** [comment]
I can confirm this bug.

I did a minimal amount of debugging and found, that `logits_processor_modifier(logits_processor_list, input_ids)` never gets called.
