### ISSUE TITLE
GPU Memory Limit not working?

### ISSUE THREAD

**Issue by ENjoyBlue2021** [oobabooga/text-generation-webui#473]
### Describe the bug

I'm calling the following: (loading llama 13b on a 1080ti)
python server.py --chat --gptq-bits=4 --no-stream --gpu-memory 7000MiB

However it doesnt seem to limit to 7gb at all.
Same with --gpu-memory  7

As seen below it uses to much vram.
This is causing errors when the context is getting longer for me.
Shouldnt python not get more than 7gb of vram?

Not sure if relevant but --no-stream doesnt seem to work either. I can see ,after a bit of waiting, the tokens flowing in.
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.86.01    Driver Version: 515.86.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| 43%   63C    P2    91W / 250W |  11068MiB / 11264MiB |      7%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1235      G   /usr/lib/xorg/Xorg                828MiB |
|    0   N/A  N/A      1937      G   /usr/bin/kwin_x11                 106MiB |
|    0   N/A  N/A      1994      G   /usr/bin/plasmashell              147MiB |
|    0   N/A  N/A      2508      G   ...RendererForSitePerProcess      180MiB |
|    0   N/A  N/A      3262      G   ...954848035529582202,131072      182MiB |
|    0   N/A  N/A     40336      G   ...wnloads/Telegram/Telegram        3MiB |
|    0   N/A  N/A    233109      C   python                           9609MiB |
+-----------------------------------------------------------------------------+

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

calling:
python server.py --chat --gptq-bits=4 --no-stream --gpu-memory 7000MiB

with a 1080ti and a bit of existing conversation history

### Logs

```shell
To create a public link, set `share=True` in `launch()`.
Exception in thread Thread-4 (gentask):
Traceback (most recent call last):
  File "/media/w/PhoenixSSD/oobabooga/miniconda/envs/textgen/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/media/w/PhoenixSSD/oobabooga/miniconda/envs/textgen/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/media/w/PhoenixSSD/oobabooga/text-generation-webui/modules/callbacks.py", line 65, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/media/w/PhoenixSSD/oobabooga/text-generation-webui/modules/text_generation.py", line 204, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/w/.local/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/w/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 1452, in generate
    return self.sample(
  File "/home/w/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 2468, in sample
    outputs = self(
  File "/home/w/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/w/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/w/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 765, in forward
    outputs = self.model(
  File "/home/w/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/w/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/w/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 614, in forward
    layer_outputs = decoder_layer(
  File "/home/w/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/w/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/w/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 309, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/w/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/w/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/w/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 224, in forward
    key_states = torch.cat([past_key_value[0], key_states], dim=2)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 12.00 MiB (GPU 0; 10.88 GiB total capacity; 8.20 GiB already allocated; 44.38 MiB free; 8.79 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
^[[A^CTraceback (most recent call last):
  File "/media/w/PhoenixSSD/oobabooga/text-generation-webui/server.py", line 469, in <module>
    time.sleep(0.5)
KeyboardInterrupt
```

### System Info

```shell
1080 ti
ubuntu
```

**Comment by oobabooga** [comment]
Just reduce the number. `--gpu-memory` refers to the model memory allocation, but more memory is allocated afterwards for the prompt during generation

https://github.com/oobabooga/text-generation-webui/wiki/Low-VRAM-guide

**Comment by jasperan** [comment]
Thanks @oobabooga this guide worked
