### ISSUE TITLE
[API] ASGI Exception when attempting to run lang-chain output formatting

### ISSUE THREAD

**Issue by ImpulseMirror** [oobabooga/text-generation-webui#4732]
### Describe the bug

When attempting to use lang-chain prompt output formatting the model returns the exception
raise InvalidRequestError(message="functions is not supported.", param='functions')
https://python.langchain.com/docs/expression_language/cookbook/prompt_llm_parser

Running this against the hosted ChatGPT API returns json as expected but running against a local instance model returns the above error. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

`from langchain.chat_models import ChatOpenAI
from langchain.prompts import ChatPromptTemplate

def get_foobuzzjson(buzz):
    prompt = ChatPromptTemplate.from_template(f"create json for : {buzz}")
    model = ChatOpenAI()
    chain = prompt | model

    functions = [
        {
            "name": "object",
            "description": "object json",
            "parameters": {
                "type": "object",
                "properties": {
                    "object_name": {"type": "string", "description": "name of object"},
                },
                "required": ["object"],
            },
        }
    ]
    chain = prompt | model.bind(function_call={"name": "object"}, functions=functions)
    resp = chain.invoke({"foo": buzz}, config={})
    print(resp)`

### Logs

```shell
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\fastapi\applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\fastapi\routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\fastapi\routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "X:\text-generation-webui\extensions\openai\script.py", line 128, in openai_chat_completions
    response = OAIcompletions.chat_completions(to_dict(request_data), is_legacy=is_legacy)
  File "X:\text-generation-webui\extensions\openai\completions.py", line 496, in chat_completions
    return deque(generator, maxlen=1).pop()
  File "X:\text-generation-webui\extensions\openai\completions.py", line 174, in chat_completions_common
    raise InvalidRequestError(message="functions is not supported.", param='functions')
extensions.openai.errors.InvalidRequestError
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\fastapi\applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\fastapi\routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\fastapi\routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "X:\text-generation-webui\extensions\openai\script.py", line 128, in openai_chat_completions
    response = OAIcompletions.chat_completions(to_dict(request_data), is_legacy=is_legacy)
  File "X:\text-generation-webui\extensions\openai\completions.py", line 496, in chat_completions
    return deque(generator, maxlen=1).pop()
  File "X:\text-generation-webui\extensions\openai\completions.py", line 174, in chat_completions_common
    raise InvalidRequestError(message="functions is not supported.", param='functions')
extensions.openai.errors.InvalidRequestError
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\fastapi\applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\fastapi\routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "X:\text-generation-webui\installer_files\env\lib\site-packages\fastapi\routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "X:\text-generation-webui\extensions\openai\script.py", line 128, in openai_chat_completions
    response = OAIcompletions.chat_completions(to_dict(request_data), is_legacy=is_legacy)
  File "X:\text-generation-webui\extensions\openai\completions.py", line 496, in chat_completions
    return deque(generator, maxlen=1).pop()
  File "X:\text-generation-webui\extensions\openai\completions.py", line 174, in chat_completions_common
    raise InvalidRequestError(message="functions is not supported.", param='functions')
extensions.openai.errors.InvalidRequestError
```

### System Info

```shell
Windows 11 Pro 64-bit
GPU: EVGA RTX 3080TI
```

**Comment by makiJanus** [comment]
I have the same issue, did you find any solution? In my case I'm trying to run the langchain schema example

`
from langchain.chains import create_extraction_chain
from langchain.chat_models import ChatOpenAI

# Schema
schema = {
    "properties": {
        "name": {"type": "string"},
        "height": {"type": "integer"},
        "hair_color": {"type": "string"},
    },
    "required": ["name", "height"],
}

# Input
inp = """Alex is 5 feet tall. Claudia is 1 feet taller Alex and jumps higher than him. Claudia is a brunette and Alex is blonde."""

llm = ChatOpenAI(temperature=0, base_url="http://localhost:5000/v1/",api_key="sk-111111111111111111111111111111111111111111111111", )

chain = create_extraction_chain(schema, llm)
chain.run(inp)
`

**Comment by adaaaaaa** [comment]
i have the same issue...
do you solve this ?

**Comment by makiJanus** [comment]
> i have the same issue... do you solve this ?

Yes, with langchain's openai library you can load models with the official chatgpt API rigth? But it is also possible to use any other compatible endpoint, like the ooba text generator open ai conpatible api, with that as starting point you can use structured output parsers, prompt templates and response schemas to have a output formatting, take into consideration that the consistency will depend of the quality of the model, and you may need to take other actios to ensure the stability of the output, sadly I cant share the code cause the project that I did was for a client, but I can share the libraries and how to load ooba open ai api in langchain:

```python
from langchain.prompts import PromptTemplate
from langchain.output_parsers import StructuredOutputParser, ResponseSchema
from langchain.llms import OpenAI
from langchain.prompts import PromptTemplate

API_BASE_URL = "http://localhost:5000/v1/"
API_KEY = "sk-111111111111111111111111111111111111111111111111"

llm = OpenAI(openai_api_base=API_BASE_URL, openai_api_key=API_KEY, stop=["}\n```"])
```

Then you need to create parsers and response schemas to generate an structured output, use the examples of the langchain documentation as reference, good luck!!
