### ISSUE TITLE
training broken on latest

### ISSUE THREAD

**Issue by SlimeQ** [oobabooga/text-generation-webui#4735]
### Describe the bug

Just updated (Windows 11) and am now getting a weird error when training.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1) Update
2) Train with Raw Text file

### Logs

```shell
2023-11-25 22:54:03 INFO:Log file 'train_dataset_sample.json' created in the 'logs' directory.
Exception in thread Thread-9 (threaded_run):
Traceback (most recent call last):
  File "C:\Users\slimeq\ooba\text-generation-webui\installer_files\env\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\slimeq\ooba\text-generation-webui\installer_files\env\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\slimeq\ooba\text-generation-webui\modules\training.py", line 696, in threaded_run
    trainer.train()
  File "C:\Users\slimeq\ooba\text-generation-webui\installer_files\env\Lib\site-packages\transformers\trainer.py", line 1555, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\slimeq\ooba\text-generation-webui\installer_files\env\Lib\site-packages\transformers\trainer.py", line 1569, in _inner_training_loop
    train_dataloader = self.get_train_dataloader()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\slimeq\ooba\text-generation-webui\installer_files\env\Lib\site-packages\transformers\trainer.py", line 825, in get_train_dataloader
    dataloader_params["sampler"] = self._get_train_sampler()
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\slimeq\ooba\text-generation-webui\installer_files\env\Lib\site-packages\transformers\trainer.py", line 796, in _get_train_sampler
    return RandomSampler(self.train_dataset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\slimeq\ooba\text-generation-webui\installer_files\env\Lib\site-packages\torch\utils\data\sampler.py", line 140, in __init__
    raise ValueError(f"num_samples should be a positive integer value, but got num_samples={self.num_samples}")
ValueError: num_samples should be a positive integer value, but got num_samples=0
```

### System Info

```shell
Windows 11
3080ti Mobile
```

**Comment by SlimeQ** [comment]
The issue here was actually that I had both a txt file and an empty folder of the same name. The folder didn't show up initially, so I moved the txt file out of it but didn't delete it. Then it showed up, but loaded the folder instead.

**Comment by SlimeQ** [comment]
spoke too soon

**Comment by alessandro-bonfatti-pv** [comment]
Is there a solution? I just reproduced it.

**Comment by KPCOFGS** [comment]
Same problem on Training Lora using a custom template and my train.json and test.json,
