### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory

### ISSUE THREAD

**Issue by tsngsn** [oobabooga/text-generation-webui#4741]
### Describe the bug

I used to be able to load 2.4bpw exl2 quants of 70B models in my 24GB VRAM (4k context, 8 bit cache). Now, I keep getting CUDA out of memory error.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I have re-downloaded several 2.4bpw 70Bs and tried both ExLlamav2_HF and the normal ExLlama.

### Logs

```shell
2023-11-27 13:53:43 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "E:\Apps\text-generation-webui-snapshot-2023-10-22\modules\ui_model_menu.py", line 209, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Apps\text-generation-webui-snapshot-2023-10-22\modules\models.py", line 85, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Apps\text-generation-webui-snapshot-2023-10-22\modules\models.py", line 370, in ExLlamav2_HF_loader
    return Exllamav2HF.from_pretrained(model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Apps\text-generation-webui-snapshot-2023-10-22\modules\exllamav2_hf.py", line 169, in from_pretrained
    return Exllamav2HF(config)
           ^^^^^^^^^^^^^^^^^^^
  File "E:\Apps\text-generation-webui-snapshot-2023-10-22\modules\exllamav2_hf.py", line 44, in __init__
    self.ex_model.load(split)
  File "E:\Apps\text-generation-webui-snapshot-2023-10-22\installer_files\env\Lib\site-packages\exllamav2\model.py", line 239, in load
    for item in f: return item
  File "E:\Apps\text-generation-webui-snapshot-2023-10-22\installer_files\env\Lib\site-packages\exllamav2\model.py", line 258, in load_gen
    module.load()
  File "E:\Apps\text-generation-webui-snapshot-2023-10-22\installer_files\env\Lib\site-packages\exllamav2\mlp.py", line 46, in load
    self.gate_proj.load()
  File "E:\Apps\text-generation-webui-snapshot-2023-10-22\installer_files\env\Lib\site-packages\exllamav2\linear.py", line 45, in load
    if w is None: w = self.load_weight()
                      ^^^^^^^^^^^^^^^^^^
  File "E:\Apps\text-generation-webui-snapshot-2023-10-22\installer_files\env\Lib\site-packages\exllamav2\module.py", line 80, in load_weight
    qtensors = self.load_multi(["q_weight", "q_invperm", "q_scale", "q_scale_max", "q_groups", "q_perm"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Apps\text-generation-webui-snapshot-2023-10-22\installer_files\env\Lib\site-packages\exllamav2\module.py", line 70, in load_multi
    tensors[k] = st.get_tensor(self.key + "." + k).to(self.device())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 MiB. GPU 0 has a total capacty of 24.00 GiB of which 6.51 GiB is free. Of the allocated memory 15.96 GiB is allocated by PyTorch, and 270.19 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### System Info

```shell
Win 11, RTX 3090
```

**Comment by FryJay** [comment]
Not the exact same issue but I recently updated (I'm not sure what version I was previously using but it would have been at least a week or two old I think) and suddenly my settings for a model didn't work any more and I was getting this error. Loading a 34B Yi model on my 3090/3060 combo, I used to use 14,10 as my gpu-split value and suddenly that stopped working after updating. I managed to fix it by adjusting the split but it kind of indicated something had changed.

**Comment by tsngsn** [comment]
Agreed, something definitely changed. However, my 2.4bpw exl2 models started to load again just now. I can even use up to 8k context with the 8-bit cache option enabled. Not sure what changed again, but I'm closing this thread for now since my issue seemed to resolve itself overnight.
