### ISSUE TITLE
Installation Issue using WSL

### ISSUE THREAD

**Issue by ExpansiveWaste** [oobabooga/text-generation-webui#475]
### Describe the bug

After creating the textgen conda env and activating it, I'm met with the below errors when trying to install PyTorch using the recommended "pip3 install torch torchvision torchaudio"
Seems that the python version in the textgen env is not compatible as I'm able to run the command when I'm in the base conda env.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

conda activate textgen
pip3 install torch torchvision torchaudio

### Logs

```shell
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f1782873ee0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/torch/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f17826cc250>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/torch/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f17826cc6a0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/torch/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f17826cc850>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/torch/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f17826cca00>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/torch/
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch
```

### System Info

```shell
Nvidia GeForce RTX 2080Ti driver 531.29 
Using the latest WSL Ubuntu on Windows 10, OS build 19044.2728
```

**Comment by wywywywy** [comment]
Assuming you have CUDA 11.8 installed, try this `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`

**Comment by ExpansiveWaste** [comment]
Thanks but that gives a similar error:

`Looking in indexes: https://download.pytorch.org/whl/cu118
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ffade328160>: Failed to establish a new connection: [Errno -2] Name or service not known')': /whl/cu118/torch/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ffade328490>: Failed to establish a new connection: [Errno -2] Name or service not known')': /whl/cu118/torch/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ffade328640>: Failed to establish a new connection: [Errno -2] Name or service not known')': /whl/cu118/torch/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ffade3287f0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /whl/cu118/torch/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ffade3289a0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /whl/cu118/torch/
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch`

When you assume I have CUDA 11.8 installed, do you mean on my Windows system? I see I'm actually running CUDA 12.1 when I type `nvidia-smi` through my windows terminal.

**Comment by ExpansiveWaste** [comment]
It does.
```
*   Trying 172.217.169.78:80...
* Connected to google.com (172.217.169.78) port 80 (#0)
```

**Comment by wywywywy** [comment]
And can it talk to pytorch.org? `curl -v https://download.pytorch.org/whl/cu118`

**Comment by ExpansiveWaste** [comment]
Yes, it can.
```
*   Trying 108.156.46.108:443...
* Connected to download.pytorch.org (108.156.46.108) port 443 (#0)
```

**Comment by wywywywy** [comment]
Last thing to try, upgrade pip and then try the install again. `pip3 install --upgrade pip`

If it doesn't work I'm out of ideas, sorry.

**Comment by ExpansiveWaste** [comment]
Thanks for your help.
Even running the `pip3 install --upgrade pip` gives me the same error as if it can't connect. Strange thing is that if I'm in the base conda env I can run pip3 commands.
I'll try again.

**Comment by ExpansiveWaste** [comment]
No proxy.
Instead of pip3 install, I used the conda install command. All went well until runtime...

```
Traceback (most recent call last):
  File "/home/desktop/text-generation-webui/server.py", line 11, in <module>
    import torch
  File "/home/desktop/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
ImportError: /home/desktop/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so: undefined symbol: cudaGraphInstantiateWithFlags, version libcudart.so.11.0
```
I used the "dirty fix", but changed the CUDA version to match the one I installed:
```
cd /home/yourname/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/
cp libbitsandbytes_cuda117.so libbitsandbytes_cpu.so
cd -
```

**Comment by pingpongching** [comment]
This worked for me:
```
sudo apt-get update
sudo apt-get upgrade
sudo apt install python3-pip
```
seems like the pip provided with WSL Ubuntu is borked from the start

**Comment by ExpansiveWaste** [comment]
Thanks. I ended up using the windows one click installer. The newest update made it work for me.
