### ISSUE TITLE
Broken for CPU only prob_topk = torch.softmax(sorted_logits, dim=0).to('cuda') 

### ISSUE THREAD

**Issue by vmajor** [oobabooga/text-generation-webui#4763]
### Describe the bug

When attempting to use CPU only with --cpu flag, textgen still forges ahead with the CUDA pathway, failing when inference starts with this being the likely culprit:

```
File "/media/xxxx/ai/code/text-generation-webui/modules/sampler_hijack.py", line 143, in __call__
    prob_topk = torch.softmax(sorted_logits, dim=0).to('cuda')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/xxxx/ai/code/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/cuda/__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Output generated in 2.92 seconds (0.00 tokens/s, 0 token
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

set --cpu flag, start textgen with start_linux.sh, load a transformers model, try to use it.

### Logs

```shell
2023-11-29 13:08:15 INFO:Loading orca2-26B-self-merge...
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████| 3/3 [00:34<00:00, 11.53s/it]
2023-11-29 13:08:50 INFO:TRUNCATION LENGTH: 4096
2023-11-29 13:08:50 INFO:INSTRUCTION TEMPLATE: Alpaca
2023-11-29 13:08:50 INFO:Loaded the model in 34.95 seconds.
Traceback (most recent call last):
  File "/media/xxxx/ai/code/text-generation-webui/modules/callbacks.py", line 57, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/xxxxx/ai/code/text-generation-webui/modules/text_generation.py", line 355, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/media/xxxxx/ai/code/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/media/xxxx/ai/code/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/generation/utils.py", line 1652, in generate
    return self.sample(
           ^^^^^^^^^^^^
  File "/media/xxxxx/ai/code/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/generation/utils.py", line 2748, in sample
    next_token_scores = logits_warper(input_ids, next_token_scores)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/xxxxx/ai/code/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/generation/logits_process.py", line 97, in __call__
    scores = processor(input_ids, scores)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/xxxxx/ai/code/text-generation-webui/modules/sampler_hijack.py", line 143, in __call__
    prob_topk = torch.softmax(sorted_logits, dim=0).to('cuda')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/xxxxx/ai/code/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/cuda/__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Output generated in 2.92 seconds (0.00 tokens/s, 0 tokens, context 60, seed 1500165273)
```
```


### System Info

```shell
Ubuntu 23.04
CPU
```

**Comment by vmajor** [comment]
Fixed by manual reinstallation of requirements_cpu_only.txt
