### ISSUE TITLE
Superbooga UnicodeDecodeError

### ISSUE THREAD

**Issue by Zawszy** [oobabooga/text-generation-webui#4770]
### Describe the bug

UnicodeDecodeError when running both superbooga v1 and v2.

Error is caused when a pdf file is loaded. No error when launching with the extension.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

pip install -r requirements.txt

restart with superbooga enabled in extensions

Upload pdf file under file upload.

Click load data.

### Logs

```shell
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Closing server running on port: 7860
2023-11-30 12:27:38 INFO:Loading the extension "gallery"...
2023-11-30 12:27:38 INFO:Loading the extension "superboogav2"...
2023-11-30 12:27:39 DEBUG:Creating Sentence Embedder...
2023-11-30 12:27:40 DEBUG:Loading hyperparameters...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/home/zeyi/miniconda3/envs/textgen/lib/python3.11/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeyi/miniconda3/envs/textgen/lib/python3.11/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeyi/miniconda3/envs/textgen/lib/python3.11/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeyi/miniconda3/envs/textgen/lib/python3.11/site-packages/gradio/blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeyi/miniconda3/envs/textgen/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeyi/miniconda3/envs/textgen/lib/python3.11/site-packages/gradio/utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeyi/miniconda3/envs/textgen/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeyi/miniconda3/envs/textgen/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/zeyi/miniconda3/envs/textgen/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeyi/miniconda3/envs/textgen/lib/python3.11/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/home/zeyi/miniconda3/envs/textgen/lib/python3.11/site-packages/gradio/utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/home/zeyi/text-generation-webui/extensions/superboogav2/script.py", line 49, in _feed_file_into_collector
    text = file.decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 10: invalid continuation byte
```

### System Info

```shell
On Ubuntu, GTX 4070TI
```

**Comment by Summer-FF** [comment]
I have the same exact issue while loading pdf files through both file and url input.
+1
