### ISSUE TITLE
Cuda Out of Memory on High VRAM setup for Training

### ISSUE THREAD

**Issue by EntryRadar** [oobabooga/text-generation-webui#4785]
### Describe the bug

I have a high VRAM setup and am getting getting this issue, I've played around with reducing the GPU memory and setting:

` --gpu-memory 25000MiB` in CMD_FLAGS.txt

I've looked at a bunch of these threads But I'm still having issues. Any idea what I should do next? 

Thank you so much for all your hard work on this, it's allowing semi-technical folk like me dip my feet in all this.

Here is my setup:

45 GB RAM
15 vCores (2.9 GHz)
300 GB SSD
Tesla V100S

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

I've moved CPU and GPU settings all around

### Logs

Here was the key final line:
```
**torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 112.00 MiB. GPU 0 has a total capacty of 31.74 GiB of which 39.12 MiB is free. Including non-PyTorch memory, this process has 31.70 GiB memory in use. Of the allocated memory 29.38 GiB is allocated by PyTorch, and 1.95 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF**
```

Here is the rest of the log:

```shell
-12-02 01:31:25 INFO:Starting training...
Training 'mistral' model using (q, v) projections
Trainable params: 109,051,904 (1.4835 %), All params: 7,350,784,000 (Model: 7,241,732,096)
2023-12-02 01:31:25 INFO:Log file 'train_dataset_sample.json' created in the 'logs' directory.
wandb: Tracking run with wandb version 0.16.0
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
Exception in thread Thread-4 (threaded_run):
Traceback (most recent call last):
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/text-generation-webui/modules/training.py", line 696, in threaded_run
    trainer.train()
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/trainer.py", line 1860, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/trainer.py", line 2725, in training_step
    loss = self.compute_loss(model, inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/trainer.py", line 2748, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/accelerate/utils/operations.py", line 659, in forward
    return model_forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/accelerate/utils/operations.py", line 647, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/peft/peft_model.py", line 1003, in forward
    return self.base_model(
           ^^^^^^^^^^^^^^^^
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/peft/tuners/tuners_utils.py", line 107, in forward
    return self.model.forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/models/mistral/modeling_mistral.py", line 1009, in forward
    outputs = self.model(
              ^^^^^^^^^^^
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/models/mistral/modeling_mistral.py", line 897, in forward
    layer_outputs = decoder_layer(
                    ^^^^^^^^^^^^^^
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/models/mistral/modeling_mistral.py", line 639, in forward
    hidden_states = self.mlp(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/models/mistral/modeling_mistral.py", line 175, in forward
    return self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))
                                      ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

### System Info

```shell
Here is my setup:


45 GB RAM
15 vCores (2.9 GHz)
300 GB SSD
Tesla V100S
```
```

**Comment by yhyu13** [comment]
@EntryRadar 

What is your LoRA Rank and micro batch size? Checkout the param description on how they affect LoRA size and VRAM usage, they are pretty detailed

Try LoRA Rank=4, LoRA Alpha=8, batch = 4, micro batch = 1, this is kind of the minimal LoRA setting
