### ISSUE TITLE
Failed to load coqui_tts on MacOS

### ISSUE THREAD

**Issue by jcluff-prgx** [oobabooga/text-generation-webui#4787]
### Describe the bug

Unable to load the coqui_tts after installing the requirements

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1) Install coqui extension on MacOS
2) enable extension in Textgen-web-ui

### Logs

```shell
2023-12-01 20:28:57 ERROR:Failed to load the extension "coqui_tts".
Traceback (most recent call last):
  File "/Users/me/llm/text-generation-webui/modules/extensions.py", line 41, in load_extensions
    extension.setup()
  File "/Users/me/llm/text-generation-webui/extensions/coqui_tts/script.py", line 180, in setup
    model = load_model()
            ^^^^^^^^^^^^
  File "/Users/me/llm/text-generation-webui/extensions/coqui_tts/script.py", line 76, in load_model
    model = TTS(params["model_name"]).to(params["device"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/llm/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/llm/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/Users/me/llm/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/Users/me/llm/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/Users/me/llm/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/Users/me/llm/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/llm/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/cuda/__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
```

### System Info

```shell
MacOS 12.6
Macbook Pro 16, 2021
Apple M1 Pro
16gb RAM
```

**Comment by CyborgArmy83** [comment]
Also an issue here on my Apple silicon device.

**Log:**
`
john83@mac ooba-webui % sh start_macos.sh
15:33:32-153670 INFO     Starting Text generation web UI                        
15:33:32-155748 INFO     Loading the extension "gallery"                        
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Closing server running on port: 7860
15:33:44-883686 INFO     Loading the extension "gallery"                        
15:33:44-888179 INFO     Loading the extension "coqui_tts"                      
[XTTS] Loading XTTS...
 > tts_models/multilingual/multi-dataset/xtts_v2 is already downloaded.
 > Using model: xtts
15:34:11-110527 ERROR    Failed to load the extension "coqui_tts".                                                                                                                                                  
Traceback (most recent call last):
  File "/Users/john/Downloads/ooba-webui/modules/extensions.py", line 46, in load_extensions
    extension.setup()
  File "/Users/john/Downloads/ooba-webui/extensions/coqui_tts/script.py", line 168, in setup
    model = load_model()
            ^^^^^^^^^^^^
  File "/Users/john/Downloads/ooba-webui/extensions/coqui_tts/script.py", line 64, in load_model
    model = TTS(params["model_name"]).to(params["device"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Downloads/ooba-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Downloads/ooba-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/Users/john/Downloads/ooba-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/Users/john/Downloads/ooba-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/Users/john/Downloads/ooba-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/Users/john/Downloads/ooba-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Downloads/ooba-webui/installer_files/env/lib/python3.11/site-packages/torch/cuda/__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
`

**Comment by spoonyv** [comment]
I never could get this to work. FWIW alltalk_tts on Mac is working very well.

**Comment by spoonyv** [comment]
working now thank you
