### ISSUE TITLE
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None) asyncio (Windows)

### ISSUE THREAD

**Issue by erew123** [oobabooga/text-generation-webui#4788]
### Describe the bug

Pretty sure this is a windows only issue (from any research on the internet)

2023-12-02 03:15:36 ERROR:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\AI\text-generation-webui\installer_files\env\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\AI\text-generation-webui\installer_files\env\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load up the text-generation-webui on windows 

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/35898566/a39ec8e7-78f1-46d1-b137-92842ae7c565)
![image](https://github.com/oobabooga/text-generation-webui/assets/35898566/b1029de9-6c91-4ccd-8d3f-95506573e8b6)

### Logs

```shell
2023-12-02 03:15:36 ERROR:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\AI\text-generation-webui\installer_files\env\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\AI\text-generation-webui\installer_files\env\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

### System Info

```shell
Windows 11. Nothing special about it. Tested with being fully up to date as of 2nd December. Google Chrome too (which may be somehow related, based on reports I saw on the internet that Edge doesnt cause this issue).

I however found someone listing a possible solution to this:

https://stackoverflow.com/questions/62412754/python-asyncio-errors-oserror-winerror-6-the-handle-is-invalid-and-runtim

Which seems to be related to this https://docs.python.org/3/library/asyncio-policy.html

I thought it could have been related to the extension I wrote, but I disabled the extension (as you can see in the screenshot) 

It doesn't seem to cause any problems, its just annoying. I think it started maybe 1-2 months ago (at a guess).
```

**Comment by erew123** [comment]
It appears to be related to "Gallery"

No longer getting the issue with that disabled!!

![image](https://github.com/oobabooga/text-generation-webui/assets/35898566/28dd64ba-ca68-4cb8-861f-60c96fae8368)
![image](https://github.com/oobabooga/text-generation-webui/assets/35898566/0d3b4d95-58d8-4653-9e7b-5769c70bdeb4)

**Comment by Desm0nt** [comment]
Same bug with mixtral model. First call to model with long (about 3k+) context in dialogue produce this problem. If I regenerate response after this - it generates fine, but when I send next request (with context increased by previous response) - it's again fail with same error.

**Comment by HsirhC** [comment]
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 84, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
