### ISSUE TITLE
[Bug]: The model can be loaded but cannot be inferred

### ISSUE THREAD

**Issue by 3058132083** [oobabooga/text-generation-webui#4798]
### Describe the bug

![image](https://github.com/AUTOMATIC1111/stable-diffusion-webui/assets/52588960/dfed208f-8a1b-4cbd-bbc3-24795089ecdb)
The AWQ model loaded successfully，but When I try to talk to it, it doesn't generate a conversation properly.
I also can't load GPTQ models.
![image](https://github.com/AUTOMATIC1111/stable-diffusion-webui/assets/52588960/faabcfaa-a899-47b1-b03d-694a20e66411)
Only unquantized models can be used properly

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

IDK

### Logs

```shell
INFO:     Started server process [9356]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:5000 (Press CTRL+C to quit)
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
2023-12-03 18:55:43 INFO:Loading Nous-Capybara-34B-AWQ...
Replacing layers...: 100%|█████████████████████████████████████████████████████████████| 60/60 [00:06<00:00,  9.57it/s]
2023-12-03 18:56:03 INFO:TRUNCATION LENGTH: 200000
2023-12-03 18:56:03 INFO:INSTRUCTION TEMPLATE: Alpaca
2023-12-03 18:56:03 INFO:Loaded the model in 20.11 seconds.
Traceback (most recent call last):
  File "C:\Users\30581\Documents\text-generation-webui\modules\callbacks.py", line 57, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\modules\text_generation.py", line 355, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Users\30581\Documents\text-generation-webui\installer_files\env\Lib\site-packages\awq\models\base.py", line 41, in generate
    return self.model.generate(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\installer_files\env\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\installer_files\env\Lib\site-packages\transformers\generation\utils.py", line 1719, in generate
    return self.sample(
           ^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\installer_files\env\Lib\site-packages\transformers\generation\utils.py", line 2801, in sample
    outputs = self(
              ^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\installer_files\env\Lib\site-packages\accelerate\hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\installer_files\env\Lib\site-packages\transformers\models\llama\modeling_llama.py", line 1034, in forward
    outputs = self.model(
              ^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\installer_files\env\Lib\site-packages\transformers\models\llama\modeling_llama.py", line 922, in forward
    layer_outputs = decoder_layer(
                    ^^^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\installer_files\env\Lib\site-packages\accelerate\hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\installer_files\env\Lib\site-packages\transformers\models\llama\modeling_llama.py", line 686, in forward
    hidden_states = self.mlp(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\installer_files\env\Lib\site-packages\accelerate\hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\installer_files\env\Lib\site-packages\transformers\models\llama\modeling_llama.py", line 258, in forward
    down_proj = self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))
                                           ^^^^^^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\installer_files\env\Lib\site-packages\accelerate\hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\installer_files\env\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\installer_files\env\Lib\site-packages\awq\modules\linear.py", line 105, in forward
    out = awq_inference_engine.gemm_forward_cuda(x.reshape(-1, x.shape[-1]), self.qweight, self.scales, self.qzeros, 8)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Output generated in 1.67 seconds (0.00 tokens/s, 0 tokens, context 10, seed 1902560545)


when loading GPTQ models：

2023-12-03 19:05:59 INFO:Loading GPTQ-34B-4Bit...
2023-12-03 19:06:24 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "C:\Users\30581\Documents\text-generation-webui\modules\ui_model_menu.py", line 209, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\modules\models.py", line 85, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\modules\models.py", line 357, in ExLlama_HF_loader
    return ExllamaHF.from_pretrained(model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\modules\exllama_hf.py", line 174, in from_pretrained
    return ExllamaHF(config)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\modules\exllama_hf.py", line 31, in __init__
    self.ex_model = ExLlama(self.ex_config)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30581\Documents\text-generation-webui\installer_files\env\Lib\site-packages\exllama\model.py", line 906, in __init__
    temp_dq = torch.zeros((1, max_dq_buffer_size), dtype = torch.float16, device = dev)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### System Info

```shell
Driver Version: 546.12
CUDA Version: 12.1
GPU0:RTX 4090(24GB)
GPU1:TESLA M40(24GB)
Windows 11 PRO Insider Preview 23H2 26002.1000
Windows Feature Experience Pack 1000.26002.1000.0
CPU 12th Gen Intel(R) Core(TM) i9-12900KS   3.40 GHz
MEMORY 64.0 GB (63.7 GB available)
```

**Comment by 3058132083** [comment]
I can use the unquantized model normally, but it runs very slowly because I have to load it into RAM due to the lack of VRAM
The quantized model doesn't load, even though I'm using the same loader
![image](https://github.com/oobabooga/text-generation-webui/assets/52588960/bf7f94a5-f85e-46bd-a6b7-9c9e4ed0e9d5)

**Comment by Ph0rk0z** [comment]
The pre-compiled wheel that requirements installs will never work because it contains no kernel for maxwell. 

There's no other way to make it work and it's not really a bug. You just have a poorly supported GPU. Try compiling gptq-for-llama yourself and maybe it will build a maxwell kernel and then *maybe* it will work.

**Comment by softwareinthewild** [comment]
Might be related... just found this Oct 21st commit doubles VRam specifically for GPTQ.
    Sat Oct 21 20:45:38 2023 -0700
    09f807a Use ExLlama_HF for GPTQ models by default
Try changing modules/models_settings.py
        loader = 'ExLlama_HF'
back to
        loader = 'AutoGPTQ'
temporarily and see what happens.
