### ISSUE TITLE
8-bit mode on older GPUs

### ISSUE THREAD

**Issue by nonetrix** [oobabooga/text-generation-webui#48]
When running ```python server.py --load-in-8bit --auto-devices``` it crashes with this, perhaps this related to a dependency? 

```
(textgen)
text-generation-webui on  main [?] via 🐍 v3.10.9 via 🅒 textgen took 33m49s
❯ python server.py --load-in-8bit --auto-devices
Loading gpt-j-6B...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
Traceback (most recent call last):
  File "/home/noah/Documents/textgen/text-generation-webui/server.py", line 367, in <module>
    model, tokenizer = load_model(model_name)
  File "/home/noah/Documents/textgen/text-generation-webui/server.py", line 151, in load_model
    model = eval(command)
  File "<string>", line 1, in <module>
  File "/home/noah/.conda/envs/textgen/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 463, in from_pretrained
    return model_class.from_pretrained(
  File "/home/noah/.conda/envs/textgen/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2279, in from_pretrained
    from .utils.bitsandbytes import get_keys_to_not_convert, replace_8bit_linear
  File "/home/noah/.conda/envs/textgen/lib/python3.10/site-packages/transformers/utils/bitsandbytes.py", line 10, in <module>
    import bitsandbytes as bnb
  File "/home/noah/.conda/envs/textgen/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 7, in <module>
    from .autograd._functions import (
  File "/home/noah/.conda/envs/textgen/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 8, in <module>
    import bitsandbytes.functional as F
  File "/home/noah/.conda/envs/textgen/lib/python3.10/site-packages/bitsandbytes/functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/home/noah/.conda/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 13, in <module>
    setup.run_cuda_setup()
  File "/home/noah/.conda/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 91, in run_cuda_setup
    binary_name, cudart_path, cuda, cc, cuda_version_string = evaluate_cuda_setup()
  File "/home/noah/.conda/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 394, in evaluate_cuda_setup
    has_cublaslt = is_cublasLt_compatible(cc)
  File "/home/noah/.conda/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 151, in is_cublasLt_compatible
    cuda_setup.add_log_entry("WARNING: Compute capability < 7.5 detected! Proceeding to load CPU-only library...", is_warning=True)
NameError: name 'cuda_setup' is not defined. Did you mean: 'CUDASetup'?
(textgen)
text-generation-webui on  main [?] via 🐍 v3.10.9 via 🅒 textgen took 15s
❯
```

System info
```
                   -`                    noah@noah-b450aorusprowifi
                  .o+`                   --------------------------
                 `ooo/                   OS: EndeavourOS Linux x86_64
                `+oooo:                  Host: B450 AORUS PRO WIFI
               `+oooooo:                 Kernel: 6.1.8-arch1-1
               -+oooooo+:                Uptime: 1 hour, 9 mins
             `/:-:++oooo+:               Packages: 993 (pacman), 35 (flatpak)
            `/++++/+++++++:              Shell: zsh 5.9
           `/++++++++++++++:             Resolution: 1920x1080
          `/+++ooooooooooooo/`           DE: Plasma 5.26.5
         ./ooosssso++osssssso+`          WM: KWin
        .oossssso-````/ossssss+`         WM Theme: Breeze
       -osssssso.      :ssssssso.        Theme: [Plasma], Breeze [GTK2/3]
      :osssssss/        osssso+++.       Icons: [Plasma], breeze-dark [GTK2/3]
     /ossssssss/        +ssssooo/-       Terminal: alacritty
   `/ossssso+/:-        -:/+osssso+-     Terminal Font: JetBrains Mono Nerd Font
  `+sso+:-`                 `.-/+oso:    CPU: AMD Ryzen 7 3700X (16) @ 3.600GHz
 `++:.                           `-/+/   GPU: NVIDIA GeForce GTX 1080
 .`                                 `/   Memory: 2738MiB / 32020MiB

```

**Comment by oobabooga** [comment]
These are the bitsandbytes requirements: 

```
LLM.int8(): NVIDIA Turing (RTX 20xx; T4) or Ampere GPU (RTX 30xx; A4-A100); (a GPU from 2018 or older).
```

https://github.com/TimDettmers/bitsandbytes#requirements--installation

I think that `GTX 1080` is not supported.

**Comment by nonetrix** [comment]
Oh I had similar issue with sd-scripts I think you just need to install a custom version

**Comment by nonetrix** [comment]
Doing ```pip install bitsandbytes-cuda113``` which is what I did to fix sd-scripts got me this
```
Loading gpt-j-6B...
==============================WARNING: DEPRECATED!==============================
WARNING! This version of bitsandbytes is deprecated. Please switch to `pip install bitsandbytes` and the new repo: https://github.com/TimDettmers/bitsandbytes
==============================WARNING: DEPRECATED!==============================
Traceback (most recent call last):
  File "/home/noah/Documents/textgen/text-generation-webui/server.py", line 367, in <module>
    model, tokenizer = load_model(model_name)
  File "/home/noah/Documents/textgen/text-generation-webui/server.py", line 151, in load_model
    model = eval(command)
  File "<string>", line 1, in <module>
  File "/home/noah/.conda/envs/textgen/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 463, in from_pretrained
    return model_class.from_pretrained(
  File "/home/noah/.conda/envs/textgen/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2288, in from_pretrained
    model = replace_8bit_linear(
  File "/home/noah/.conda/envs/textgen/lib/python3.10/site-packages/transformers/utils/bitsandbytes.py", line 115, in replace_8bit_linear
    replace_8bit_linear(module, threshold, modules_to_not_convert)
  File "/home/noah/.conda/envs/textgen/lib/python3.10/site-packages/transformers/utils/bitsandbytes.py", line 115, in replace_8bit_linear
    replace_8bit_linear(module, threshold, modules_to_not_convert)
  File "/home/noah/.conda/envs/textgen/lib/python3.10/site-packages/transformers/utils/bitsandbytes.py", line 115, in replace_8bit_linear
    replace_8bit_linear(module, threshold, modules_to_not_convert)
  [Previous line repeated 1 more time]
  File "/home/noah/.conda/envs/textgen/lib/python3.10/site-packages/transformers/utils/bitsandbytes.py", line 119, in replace_8bit_linear
    model._modules[name] = bnb.nn.Linear8bitLt(
AttributeError: module 'bitsandbytes.nn' has no attribute 'Linear8bitLt'
(textgen)
text-generation-webui on  main [?] via 🐍 v3.10.9 via 🅒 textgen took 18s
❯
```

**Comment by oobabooga** [comment]
This looks like an older version. The requirements for large language model quantization and general quantization quantization are different, so I think that it might not be possible to get this to work.

Take a look at deepspeed instead. This is the command I have tested:

```
deepspeed --num_gpus=1 server.py --cai-chat --deepspeed --model pygmalion-6b-original --listen
```

https://github.com/oobabooga/text-generation-webui/issues/40

**Comment by nonetrix** [comment]
That works but just runs out of memory instead

**Comment by lolxdmainkaisemaanlu** [comment]
@oobabooga Do you think this [https://github.com/TimDettmers/bitsandbytes/releases/tag/0.37.0](Int8 Matmul backward for all GPUs) help with getting this to run in 8bit on older GPUs?

**Comment by oobabooga** [comment]
@lolxdmainkaisemaanlu definitely yes. With this latest bitsandbytes version I was able to load the model in 8bit mode on a GTX 1650, but text generation failed with

```
cuBLAS API failed with status 15
Exception: cublasLt ran into an error!
```

This is probably fixable.

**Comment by lolxdmainkaisemaanlu** [comment]
> @lolxdmainkaisemaanlu definitely yes. With this latest bitsandbytes version I was able to load the model in 8bit mode on a GTX 1650, but text generation failed with
> 
> ```
> cuBLAS API failed with status 15
> Exception: cublasLt ran into an error!
> ```
> 
> This is probably fixable.

I got the same cublast error in issue #42 which is closed now... But I was getting this error even before the latest bitsandbytes version was out...

**Comment by Ph0rk0z** [comment]
I'm going to see what happens on linux since this dropped.

**Comment by Ph0rk0z** [comment]
So does anyone know what is exactly happening with this error? Is the casting not done properly in BitsandBytes? Is it a bug in torch itself and performing operations on the now smaller 8bit values?

```
next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either inf, nan or element < 0
```

**Comment by Ph0rk0z** [comment]
Here are some hints from kobold.. the 8 bit threshold has to be reduced: https://github.com/archytasos/KoboldAI-Client/commit/8336f38e916334c56d3e6d2b6b6e0ef1980fdb3a

It is insanely slow when I tried on kobold and memory balloons up while generating due to this "fix". Maybe its simply a manner of adding a parameter to the relevant files here.

**Comment by Ph0rk0z** [comment]
Ok.. we are doing it wrong. Set that threshold to 1 and 8bits is usable on pascal GPU.

**Comment by oobabooga** [comment]
@Ph0rk0z Do you mean 

`load_in_8bit_threshold=1`

or

`llm_int8_threshold=1`

?

**Comment by plhosk** [comment]
Not sure if this is expected but I get garbage output when I try to split the Llama 4bit model across 2 GPUs of different generations, 3060ti and 980ti. If I lower the max tokens to around 100 the output is coherent but at 200 it starts off ok then enters a repeating loop of nonsense.

Params:
 --model llama-13b --load-in-4bit --gpu-memory 5 5

**Comment by nonetrix** [comment]
> Ok.. we are doing it wrong. Set that threshold to 1 (try higher too) and 8bits is usable on pascal GPU.

Good to hear, does that mean this can be fixed soonish I assume?

**Comment by nonetrix** [comment]
I think this still hasn't been fixed

**Comment by Ph0rk0z** [comment]
The "fix" is to https://github.com/Ph0rk0z/text-generation-webui-testing/commit/320f9aaccde4a3b980e1bc8cac6bf1aba06f089d

and use .8-1.5 and cross fingers.

**Comment by CarlKenner** [comment]
It works for me on Windows on my GTX 970.
