### ISSUE TITLE
cannot import name exllamav2

### ISSUE THREAD

**Issue by St33lMouse** [oobabooga/text-generation-webui#4804]
### Describe the bug

This bug appears after updating ooba and trying to load a model with exllamav2.

ImportError: cannot import name 'ExLlamaV2Cache_8bit' from 'exllamav2' (/usr/local/lib/python3.10/dist-packages/exllamav2/init.py)

This bug was closed a few weeks ago, but it is still in place. The general advice was to update exllamav2, so I did a pip uninstall and reinstall, and tried downloading and installing from the wheel, but no luck. It looks like some people got a docker image to work, but I'm on Linux and don't even know what docker is :)

So for whatever reason I couldn't seem to figure out how to properly update exllamav2, but if anyone else suffers this issue, there are some changes you can make to exllamav2.py that will fix the problem. It's sub-optimal, obviously, but it does fix the issue.

https://github.com/oobabooga/text-generation-webui/issues/4479

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Just update and try to run a model with exllamav2

### Logs

```shell
`Traceback (most recent call last):

File "/workspace/text-generation-webui/modules/ui_model_menu.py", line 208, in load_model_wrapper

shared.model, shared.tokenizer = load_model(shared.model_name, loader)
File "/workspace/text-generation-webui/modules/models.py", line 84, in load_model

output = load_func_maploader
File "/workspace/text-generation-webui/modules/models.py", line 348, in ExLlamav2_loader

from modules.exllamav2 import Exllamav2Model
File "/workspace/text-generation-webui/modules/exllamav2.py", line 6, in

from exllamav2 import (
ImportError: cannot import name 'ExLlamaV2Cache_8bit' from 'exllamav2' (/usr/local/lib/python3.10/dist-packages/exllamav2/init.py)`
```

### System Info

```shell
ubuntu 22.04, 2 x 3090 cards, 64 gigs ram, python 3.10, cuda 12.1
```

**Comment by nviraj** [comment]
Facing this on Windows as well with the latest version. Don't think this issue should be closed automatically.

OS Info
```
Microsoft Windows 11 Pro
Version	10.0.22631 Build 22631
```

```
14:15:32-790332 INFO     Loading "LoneStriker_deepseek-coder-7b-instruct-v1.5-6.0bpw-h6-exl2"
14:15:32-795358 ERROR    Failed to load the model.
Traceback (most recent call last):
  File "D:\Apps\PortableApps\text-generation-webui\modules\ui_model_menu.py", line 245, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Apps\PortableApps\text-generation-webui\modules\models.py", line 87, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Apps\PortableApps\text-generation-webui\modules\models.py", line 378, in ExLlamav2_HF_loader
    from modules.exllamav2_hf import Exllamav2HF
  File "D:\Apps\PortableApps\text-generation-webui\modules\exllamav2_hf.py", line 7, in <module>
    from exllamav2 import (
ImportError: cannot import name 'ExLlamaV2Cache_Q4' from 'exllamav2' (D:\Apps\PortableApps\text-generation-webui\installer_files\env\Lib\site-packages\exllamav2\__init__.py)
```

**Comment by nviraj** [comment]
After going through a couple of issues, I think update wizard is to blame. This is what I had to do to fix the issue.

Run these in cmd.sh/bat. Check command outputs for 1, 2. Use the correct cuda version for installation command 3. Command 4 is to verify everything is detected correctly.
```
nvidia-smi
nvcc --version
conda install -c "nvidia/label/cuda-12.1.1" cuda-toolkit cuda
python -m torch.utils.collect_env
```

And then run update_wizard.bat/sh a couple of times to pick up all the missing dependencies + update existing ones.
