### ISSUE TITLE
Cuda out of memory Error when try to load the Model 

### ISSUE THREAD

**Issue by Alexbabylon** [oobabooga/text-generation-webui#4812]
### Describe the bug

HI 
I try to run Webui model but show this Error ..anyone have any idea why please
Window 11
EGPU Nvidia GeForce 3090 

<img width="958" alt="2023-12-04_18-34-02" src="https://github.com/oobabooga/text-generation-webui/assets/128872360/4a5d940f-6165-4961-b2be-b91f47f748cf">
 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Just try to run the model 

### Screenshot

<img width="958" alt="2023-12-04_18-34-02" src="https://github.com/oobabooga/text-generation-webui/assets/128872360/6ef0390b-1fc0-49ad-8f76-b96fd31aafd7">

### Logs

```shell
2023-12-04 18:32:31 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "C:\text-generation-webui-main\text-generation-webui-main\modules\ui_model_menu.py", line 209, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui-main\text-generation-webui-main\modules\models.py", line 85, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui-main\text-generation-webui-main\modules\models.py", line 311, in AutoAWQ_loader
    model = AutoAWQForCausalLM.from_quantized(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\awq\models\auto.py", line 52, in from_quantized
    return AWQ_CAUSAL_LM_MODEL_MAP[model_type].from_quantized(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\awq\models\base.py", line 182, in from_quantized
    self.fuse_layers(model)
  File "C:\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\awq\models\mistral.py", line 21, in fuse_layers
    fuser.fuse_transformer()
  File "C:\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\awq\models\mistral.py", line 111, in fuse_transformer
    blocks.append(LlamaLikeBlock(
                  ^^^^^^^^^^^^^^^
  File "C:\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\awq\modules\fused\block.py", line 16, in __init__
    self.attn = QuantAttentionFused(
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\awq\modules\fused\attn.py", line 110, in __init__
    self.cache = WindowedCache(
                 ^^^^^^^^^^^^^^
  File "C:\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\awq\modules\fused\cache.py", line 10, in __init__
    self.v = torch.zeros(cache_v_shape).to(device).half()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 MiB. GPU 1 has a total capacty of 4.00 GiB of which 0 bytes is free. Of the allocated memory 3.36 GiB is allocated by PyTorch, and 94.15 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### System Info

```shell
Windows 11
```

**Comment by gpapp** [comment]
This is still an issue, no AWQ models can be loaded when using cuda
