### ISSUE TITLE
error loading model

### ISSUE THREAD

**Issue by stupidratcreature1000** [oobabooga/text-generation-webui#4821]
### Describe the bug

When I load this model https://huggingface.co/Kooten/Noromaid-20b-v0.1.1-6bpw-h8-exl2/tree/main it gives me an error

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

load the model

### Logs

```shell
Traceback (most recent call last):
File "/Users/colin/text-generation-webui/installer_files/env/lib/python3.11/site-packages/exllamav2/ext.py", line 14, in

import exllamav2_ext
ModuleNotFoundError: No module named 'exllamav2_ext'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/Users/colin/text-generation-webui/modules/ui_model_menu.py", line 209, in load_model_wrapper

shared.model, shared.tokenizer = load_model(shared.model_name, loader)

                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/colin/text-generation-webui/modules/models.py", line 85, in load_model

output = load_func_map[loader](model_name)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/colin/text-generation-webui/modules/models.py", line 369, in ExLlamav2_HF_loader

from modules.exllamav2_hf import Exllamav2HF
File "/Users/colin/text-generation-webui/modules/exllamav2_hf.py", line 7, in

from exllamav2 import (
File "/Users/colin/text-generation-webui/installer_files/env/lib/python3.11/site-packages/exllamav2/init.py", line 3, in

from exllamav2.model import ExLlamaV2
File "/Users/colin/text-generation-webui/installer_files/env/lib/python3.11/site-packages/exllamav2/model.py", line 17, in

from exllamav2.cache import ExLlamaV2CacheBase
File "/Users/colin/text-generation-webui/installer_files/env/lib/python3.11/site-packages/exllamav2/cache.py", line 2, in

from exllamav2.ext import exllamav2_ext as ext_c
File "/Users/colin/text-generation-webui/installer_files/env/lib/python3.11/site-packages/exllamav2/ext.py", line 126, in

exllamav2_ext = load \

                ^^^^^^
File "/Users/colin/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1308, in load

return _jit_compile(

       ^^^^^^^^^^^^^
File "/Users/colin/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1736, in _jit_compile

return _import_module_from_library(name, build_directory, is_python_module)

       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/colin/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2136, in _import_module_from_library

module = importlib.util.module_from_spec(spec)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen(/Users/colin/Library/Caches/torch_extensions/py311_cpu/exllamav2_ext/exllamav2_ext.so, 0x0002): tried: '/Users/colin/Library/Caches/torch_extensions/py311_cpu/exllamav2_ext/exllamav2_ext.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/colin/Library/Caches/torch_extensions/py311_cpu/exllamav2_ext/exllamav2_ext.so' (no such file), '/Users/colin/Library/Caches/torch_extensions/py311_cpu/exllamav2_ext/exllamav2_ext.so' (no such file)
```

### System Info

```shell
M3 pro MacBook Pro
```

**Comment by NoMeGitH** [comment]
I also encountered the same error, is there any way to avoid it temporarily

**Comment by TheLounger** [comment]
It's not really clear from the exllamav2 repo, but I think it only supports CUDA and ROCm. They also don't make Mac [releases](https://github.com/turboderp/exllamav2/releases).
