### ISSUE TITLE
TRANSFORMERS_CACHE missing from docker setup?

### ISSUE THREAD

**Issue by stefangweichinger** [oobabooga/text-generation-webui#4847]
### Describe the bug

Rebuilt after checking out snapshot-2023-12-03

Container starts at first but fails.

I understand that the first messages are WARNINGs: maybe it doesn't fail because of them.
I 'd like to know how to set TRANSFORMERS_CACHE correctly ...

Then that `presets/simple-1.yaml` error: I use the provided `docker-compose.yml` with volume `presets` and the file exists in the directory. pls advise. tia.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

git checkout 96df4f10b912d8823376b7dc01f5421f8bf353a9
docker-compose build
docker-compose up

### Logs

```shell
text-generation-webui-text-generation-webui-1  | 2023-12-08 10:18:46 WARNING:Matplotlib created a temporary cache directory at /tmp/matplotlib-4073z0v0 because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
text-generation-webui-text-generation-webui-1  | 2023-12-08 10:18:47 WARNING:
text-generation-webui-text-generation-webui-1  | You are potentially exposing the web UI to the entire internet without any access password.
text-generation-webui-text-generation-webui-1  | You can create one with the "--gradio-auth" flag like this:
text-generation-webui-text-generation-webui-1  | 
text-generation-webui-text-generation-webui-1  | --gradio-auth username:password
text-generation-webui-text-generation-webui-1  | 
text-generation-webui-text-generation-webui-1  | Make sure to replace username:password with your own.
text-generation-webui-text-generation-webui-1  | There was a problem when trying to write in your cache folder (/.cache/huggingface/hub). You should set the environment variable TRANSFORMERS_CACHE to a writable directory.
text-generation-webui-text-generation-webui-1  | 2023-12-08 10:18:50 INFO:Loading the extension "gallery"...
text-generation-webui-text-generation-webui-1  | Traceback (most recent call last):
text-generation-webui-text-generation-webui-1  |   File "/app/server.py", line 236, in <module>
text-generation-webui-text-generation-webui-1  |     create_interface()
text-generation-webui-text-generation-webui-1  |   File "/app/server.py", line 117, in create_interface
text-generation-webui-text-generation-webui-1  |     ui_parameters.create_ui(shared.settings['preset'])  # Parameters tab
text-generation-webui-text-generation-webui-1  |   File "/app/modules/ui_parameters.py", line 11, in create_ui
text-generation-webui-text-generation-webui-1  |     generate_params = presets.load_preset(default_preset)
text-generation-webui-text-generation-webui-1  |   File "/app/modules/presets.py", line 49, in load_preset
text-generation-webui-text-generation-webui-1  |     with open(Path(f'presets/{name}.yaml'), 'r') as infile:
text-generation-webui-text-generation-webui-1  | FileNotFoundError: [Errno 2] No such file or directory: 'presets/simple-1.yaml'
```

### System Info

```shell
Fedora39 workstation
NVIDIA GeForce RTX 2060 Super
```

**Comment by stefangweichinger** [comment]
let me add that `docker/Dockerfile` is missing in the latest commits. Just checked out latest commit, build fails:

```
$ docker-compose build 
[+] Building 0.1s (2/2) FINISHED                                                                                                    docker:default
 => [text-generation-webui internal] load build definition from Dockerfile                                                                    0.1s
 => => transferring dockerfile: 52B                                                                                                           0.0s
 => [text-generation-webui internal] load .dockerignore                                                                                       0.1s
 => => transferring context: 204B                                                                                                             0.0s
failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount1539677130/docker/Dockerfile: no such file or directory
sgw@fedora:~/text-generation-webui$ ls docker
docker-compose.yml  nvidia
```

I cp the file from an earlier commit and build from scratch.

**Comment by chrisbward** [comment]
reboot didn't work - same issue
