### ISSUE TITLE
Can't load any model

### ISSUE THREAD

**Issue by AZmisc** [oobabooga/text-generation-webui#4855]
### Describe the bug

I get the following message when installing TGW and as the result TGW doesn't work. When I attempt to load a model I also get an error message.

 Error during installation:
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
openai-whisper 20230918 requires tiktoken==0.3.3, but you have tiktoken 0.5.2 which is incompatible.`

Error while loading model:
`2023-12-09 16:40:51 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "C:\AI\text-generation-webui\modules\ui_model_menu.py", line 209, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\text-generation-webui\modules\models.py", line 88, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\text-generation-webui\modules\models.py", line 314, in AutoAWQ_loader
    model = AutoAWQForCausalLM.from_quantized(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\text-generation-webui\installer_files\env\Lib\site-packages\awq\models\auto.py", line 52, in from_quantized
    return AWQ_CAUSAL_LM_MODEL_MAP[model_type].from_quantized(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\text-generation-webui\installer_files\env\Lib\site-packages\awq\models\base.py", line 171, in from_quantized
    load_checkpoint_and_dispatch(
  File "C:\AI\text-generation-webui\installer_files\env\Lib\site-packages\accelerate\big_modeling.py", line 545, in load_checkpoint_and_dispatch
    load_checkpoint_in_model(
  File "C:\AI\text-generation-webui\installer_files\env\Lib\site-packages\accelerate\utils\modeling.py", line 1437, in load_checkpoint_in_model
    checkpoint = load_state_dict(checkpoint_file, device_map=device_map)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\text-generation-webui\installer_files\env\Lib\site-packages\accelerate\utils\modeling.py", line 1195, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer`

Thank you and sorry to bother you.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

To reproduce the error install TGW on a system with tiktoken 0.5.2 and then attempt to load a model. 

### Screenshot

Attached.
![tt052](https://github.com/oobabooga/text-generation-webui/assets/47092625/36c6e57c-2453-4f9a-b654-9a9c9181f2db)

### Logs

```shell
2023-12-09 16:40:40 INFO:Loading TheBloke_MLewdBoros-L2-13B-AWQ...
Replacing layers...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 40/40 [00:03<00:00, 10.61it/s]
2023-12-09 16:40:51 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "C:\AI\text-generation-webui\modules\ui_model_menu.py", line 209, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\text-generation-webui\modules\models.py", line 88, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\text-generation-webui\modules\models.py", line 314, in AutoAWQ_loader
    model = AutoAWQForCausalLM.from_quantized(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\text-generation-webui\installer_files\env\Lib\site-packages\awq\models\auto.py", line 52, in from_quantized
    return AWQ_CAUSAL_LM_MODEL_MAP[model_type].from_quantized(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\text-generation-webui\installer_files\env\Lib\site-packages\awq\models\base.py", line 171, in from_quantized
    load_checkpoint_and_dispatch(
  File "C:\AI\text-generation-webui\installer_files\env\Lib\site-packages\accelerate\big_modeling.py", line 545, in load_checkpoint_and_dispatch
    load_checkpoint_in_model(
  File "C:\AI\text-generation-webui\installer_files\env\Lib\site-packages\accelerate\utils\modeling.py", line 1437, in load_checkpoint_in_model
    checkpoint = load_state_dict(checkpoint_file, device_map=device_map)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\text-generation-webui\installer_files\env\Lib\site-packages\accelerate\utils\modeling.py", line 1195, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
```

### System Info

```shell
Windows 11 Home
Intel i7, 13th gen
Nvidia 4070ti.
```

**Comment by AZmisc** [comment]
This got resolved on its own :)

I went back to Hugginface, downloaded another model, loaded it, and the new model worked.

All set, thanks! Issue closed.

**Comment by AZmisc** [comment]
This got resolved on its own :)

I went back to Hugginface, downloaded another model, loaded it, and the new model worked.

All set, thanks! Issue closed.
