### ISSUE TITLE
ERROR:Failed to load the model.

### ISSUE THREAD

**Issue by fsiek** [oobabooga/text-generation-webui#4857]
### Describe the bug

Will not load models. Tried different models but getting only models with pytorch_model.bin to work.
Models with safetensors will not load.
Example: [https://huggingface.co/Monero/oasst-alpaca13b-4epoch-4bit-128g](https://huggingface.co/Monero/oasst-alpaca13b-4epoch-4bit-128g)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Start webui
2. Under models, download Monero/oasst-alpaca13b-4epoch-4bit-128g
3. Reload list
4. Select Monero_oasst-alpaca13b-4epoch-4bit-128g
5. Load

### Screenshot

![Step1](https://github.com/oobabooga/text-generation-webui/assets/32448348/99f9fd51-49b2-4184-9262-9f186e4c0e52)

![Step2](https://github.com/oobabooga/text-generation-webui/assets/32448348/830ac32c-6dd4-429c-baf2-8b3001e50ac6)

![Step3](https://github.com/oobabooga/text-generation-webui/assets/32448348/56365329-fb00-4697-9934-d7aa9d0b6994)

### Logs

```shell
bin D:\AI\text-generation-webui-main\installer_files\env\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll
2023-12-09 12:04:57 INFO:Loading the extension "gallery"...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Downloading the model to models\Monero_oasst-alpaca13b-4epoch-4bit-128g
100%|█████████████████████████████████████████████████████████████████████████████████████████| 21.0  /21.0   21.0kiB/s
100%|████████████████████████████████████████████████████████████████████████████████████████████| 593   /593    ?iB/s
100%|████████████████████████████████████████████████████████████████████████████████████████████| 96.0  /96.0   ?iB/s
100%|████████████████████████████████████████████████████████████████████████████████████████████| 986   /986    ?iB/s
100%|████████████████████████████████████████████████████████████████████████████████████████████| 329   /329    ?iB/s
100%|████████████████████████████████████████████████████████████████████████████████████████████| 132   /132    ?iB/s
100%|█████████████████████████████████████████████████████████████████████████████████████████| 295k  /295k   1.06MiB/s
100%|█████████████████████████████████████████████████████████████████████████████████████████| 500k  /500k   3.19MiB/s
100%|█████████████████████████████████████████████████████████████████████████████████████████| 7.45G /7.45G  38.2MiB/s
2023-12-09 12:10:16 INFO:Loading Monero_oasst-alpaca13b-4epoch-4bit-128g...
2023-12-09 12:10:16 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "D:\AI\text-generation-webui-main\modules\ui_model_menu.py", line 209, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\text-generation-webui-main\modules\models.py", line 88, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\text-generation-webui-main\modules\models.py", line 159, in huggingface_loader
    model = LoaderClass.from_pretrained(path_to_model, **params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\models\auto\auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\modeling_utils.py", line 2992, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory models\Monero_oasst-alpaca13b-4epoch-4bit-128g.
```

### System Info

```shell
Windows 10
64GB Ram
AMD Ryzen 5800
NVidia RTX4080
```

**Comment by Soumendraprasad** [comment]
@fsiek , I am also facing similar type of issue . But in my case Though I have successfully downloaded the model & it was written done! , Still there is no model name is showing in dropdown box of model  loading section . In get the file list section it is showing that all the files are successfully downloaded , but still there is no model name showing on model loading section . Below is the image of that problem . I am sorry but I can't share the model name publicly .
![textgen_err](https://github.com/oobabooga/text-generation-webui/assets/102607452/1c2a4a2f-3d1d-4c3f-ab18-c8d1bfa73dcc)

**Comment by fsiek** [comment]
On the right side of the dropdown box, you will find a button to reload the dropdown list. After a click on that button, the new name should appear in the list.

This application is new to me, too. I don't know, why this is needed because after downloading the application could reload the list automtically.

**Comment by Soumendraprasad** [comment]
@fsiek , I did that but still it is not showing any name

**Comment by fsiek** [comment]
Check if a new folder was created in the models folder and the folder name has no spaces. Oobabooga don't like space in file or folder names.

**Comment by TheLounger** [comment]
You're trying to load a GPTQ model with the Transformers library.
Normally Ooba selects the proper loader for your model, at startup at least.
So, you just have to select a proper loader for GPTQ, and read [the docs](https://github.com/oobabooga/text-generation-webui/wiki/04-%E2%80%90-Model-Tab#model-loaders) 😉

**Comment by Soumendraprasad** [comment]
@TheLounger , I manually downloaded my model(.bin file) in model folder . then now  it is showing the model in dropdown , but now the issue is coming that while loading the model (pytorch_model-00001-of-00002.bin) file , it is giving the following error .
`2023-12-10 05:21:01 INFO:Loading pytorch_model-00001-of-00002.bin...
2023-12-10 05:21:09 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/transformers/configuration_utils.py", line 707, in _get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "/usr/local/lib/python3.9/dist-packages/transformers/configuration_utils.py", line 802, in _dict_from_json_file
    text = reader.read()
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 128: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sky/textgen/modules/ui_model_menu.py", line 209, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/home/sky/textgen/modules/models.py", line 85, in load_model
    output = load_func_map[loader](model_name)
  File "/home/sky/textgen/modules/models.py", line 143, in huggingface_loader
    config = AutoConfig.from_pretrained(path_to_model, trust_remote_code=params['trust_remote_code'])
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/auto/configuration_auto.py", line 1048, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/configuration_utils.py", line 622, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/configuration_utils.py", line 710, in _get_config_dict
    raise EnvironmentError(
OSError: It looks like the config file at 'models/pytorch_model-00001-of-00002.bin' is not a valid JSON file.`
![d3](https://github.com/oobabooga/text-generation-webui/assets/102607452/71afcb13-651e-4043-9c64-e1f8260a9864)

**Comment by RcKaslana** [comment]
I get the same error, dose anyone can help?
