### ISSUE TITLE
After #4837, some models broken when using HF or exllama2_HF loaders (Qwen, SUS, maybe others)

### ISSUE THREAD

**Issue by cedonley** [oobabooga/text-generation-webui#4864]
### Describe the bug

Issues seem to be in the same part of the code:

Qwen - no generation is possible due an error when calling its custom tokenizer.
SUS-34b - gives extra spaces on every space when using exllama2_HF, but proper spacing if just using base exllama.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

For QWEN: Load Qwen-14-Chat (or Int4) via HF loader, then try to do inference. Error occurs immediately.
For SUS-34b: Load SUS-34b using exllama2_HF loader, then try to do any inference. Extra spaces ALWAYS appear.

### Logs

```shell
Traceback (most recent call last):
  File "text-generation-webui/modules/text_generation.py", line 364, in generate_reply_HF
    new_content = get_reply_from_output_ids(output, state, starting_from=starting_from)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "text-generation-webui/modules/text_generation.py", line 268, in get_reply_from_output_ids
    if hasattr(shared.tokenizer, 'convert_ids_to_tokens') and len(output_ids) > starting_from and shared.tokenizer.convert_ids_to_tokens(int(output_ids[starting_from])).startswith('▁'):
                                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

### System Info

```shell
Ubuntu 22.04, CUDA 12.1, 2xRTX3090
```

**Comment by sagzeii** [comment]
I modified the code from shared.tokenizer.convert_ids_to_tokens(int(output_ids[starting_from])).startswith('▁'): to shared.tokenizer.convert_ids_to_tokens(int(output_ids[starting_from]))[0] == '▁', and it worked

**Comment by glloyd0314** [comment]
Model Qwen-14B, [sagzeii](https://github.com/sagzeii)'s comment worked for me.
