### ISSUE TITLE
chat and completions openAPI returns KeyError('temperature_last') error

### ISSUE THREAD

**Issue by flywhc** [oobabooga/text-generation-webui#4869]
### Describe the bug

I followed instructionsin the wiki "12 ‐ OpenAI API". I can successfully call /models to get list of models but always get KeyError('temperature_last') error when calling /chat/completions.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I am using Windows 11
1. clone the repository and run start_windows.bat
2. exit and run command:
```
python server.py --listen --verbose --api
2023-12-11 01:37:21 WARNING:
You are potentially exposing the web UI to the entire internet without any access password.
You can create one with the "--gradio-auth" flag like this:

--gradio-auth username:password

Make sure to replace username:password with your own.
bin C:\AIGC\text-generation-webui\installer_files\env\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll
2023-12-11 01:37:22 INFO:Loading the extension "openai"...
2023-12-11 01:37:22 INFO:Loading the extension "gallery"...
OpenAI compatible API ready at: OPENAI_API_BASE=http://0.0.0.0:5001/v1
Running on local URL:  http://0.0.0.0:7860
```
You can see the port is 5001 instead of 5000 in the wiki. - Wiki is wrong.

3. download and load a model deepseek-ai/deepseek-llm-7b-chat - I also tried many other models.
Test it in Chat tab and it works fine.

4. run curl command (copied from wiki):
`curl http://127.0.0.1:5001/v1/chat/completions -H "Content-Type: application/json" -d "{\"messages\": [{\"role\": \"user\",\"content\": \"Hello!\"}],\"mode\": \"instruct\",\"instruction_template\": \"Alpaca\" }"
`
Result:
`{"error": {"message": "KeyError('temperature_last')", "code": 500, "type": "OpenAIError", "param": ""}}
`
5. use postman to call {{baseUrl}}/chat/completions
```
{
  "messages": [
    {
      "role": "user",
      "content": "Hello! Who are you?"
    }
  ]
}

```

Response HTTP500
```
{
    "error": {
        "message": "KeyError('temperature_last')",
        "code": 500,
        "type": "OpenAIError",
        "param": ""
    }
}

```

6. use postman to list model: GET {{baseUrl}}/models
Response HTTP200:
```
{
    "object": "list",
    "data": [
        {
            "id": "deepseek-ai_deepseek-llm-7b-chat",
            "object": "model",
            "owned_by": "user",
            "permission": []
        }
}

```

### Logs

```shell
<|system-message|>

### Instruction:
Hello! Who are you?

### Response:

--------------------

OpenAIError KeyError('temperature_last')
Traceback (most recent call last):
  File "C:\AIGC\text-generation-webui\extensions\openai\script.py", line 114, in wrapper
    func(self)
  File "C:\AIGC\text-generation-webui\extensions\openai\script.py", line 237, in do_POST
    response = OAIcompletions.chat_completions(body, is_legacy=is_legacy)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AIGC\text-generation-webui\extensions\openai\completions.py", line 287, in chat_completions
    for a in generator:
  File "C:\AIGC\text-generation-webui\modules\text_generation.py", line 30, in generate_reply
    for result in _generate_reply(*args, **kwargs):
  File "C:\AIGC\text-generation-webui\modules\text_generation.py", line 80, in _generate_reply
    for reply in generate_func(question, original_question, seed, state, stopping_strings, is_chat=is_chat):
  File "C:\AIGC\text-generation-webui\modules\text_generation.py", line 277, in generate_reply_HF
    generate_params[k] = state[k]
                         ~~~~~^^^
KeyError: 'temperature_last'

127.0.0.1 - - [11/Dec/2023 01:44:07] "POST /v1/chat/completions HTTP/1.1" 500 -
```

### System Info

```shell
Windows 11
2* Nvidia 2080Ti 22G
```

**Comment by flywhc** [comment]
Cannot repro this issue in commit7be09836fc721e6f23cf1cc27523c92185b20d8a
