### ISSUE TITLE
 error "json.decoder.JSONDecodeError" at startup server.py

### ISSUE THREAD

**Issue by hherpa** [oobabooga/text-generation-webui#4889]
### Describe the bug

I used to run wizardcoder-13b in google colab and everything was great, but today at launch (I want to note that I didn't change anything inside) I got this error:
```
Traceback (most recent call last):
  File "/content/text-generation-webui/server.py", line 232, in <module>
    model_settings = get_model_metadata(model_name)
  File "/content/text-generation-webui/modules/models_settings.py", line 39, in get_model_metadata
    hf_metadata = json.loads(open(path, 'r').read())
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I used this google colab - [link](https://colab.research.google.com/drive/15A_wveSRBLkKruZR5iu1ArmabmwRGg18?authuser=2#scrollTo=kPmAGXt0Z-SI)
it performs the following steps:

1. Installation text-generation-webui:
```
import torch
from pathlib import Path

if Path.cwd().name != 'text-generation-webui':
  print("Installing the webui...")

  !git clone https://github.com/oobabooga/text-generation-webui
  %cd text-generation-webui

  torver = torch.__version__
  print(f"TORCH: {torver}")
  is_cuda118 = '+cu118' in torver  # 2.1.0+cu118
  is_cuda117 = '+cu117' in torver  # 2.0.1+cu117

  textgen_requirements = open('requirements.txt').read().splitlines()
  if is_cuda117:
      textgen_requirements = [req.replace('+cu121', '+cu117').replace('+cu122', '+cu117').replace('torch2.1', 'torch2.0') for req in textgen_requirements]
  elif is_cuda118:
      textgen_requirements = [req.replace('+cu121', '+cu118').replace('+cu122', '+cu118') for req in textgen_requirements]
  with open('temp_requirements.txt', 'w') as file:
      file.write('\n'.join(textgen_requirements))

  !pip install -r extensions/api/requirements.txt --upgrade
  !pip install -r temp_requirements.txt --upgrade

  print("\033[1;32;1m\n --> If you see a warning about \"previously imported packages\", just ignore it.\033[0;37;0m")
  print("\033[1;32;1m\n --> There is no need to restart the runtime.\n\033[0;37;0m")

  try:
    import flash_attn
  except:
    !pip uninstall -y flash_attn
```
2. use CD:
```
cd models
```
```
mkdir wizardcoder-13b
```
```
cd wizardcoder-13b
```
3. Installing models:
```
!wget https://huggingface.co/TheBloke/WizardCoder-Python-13B-V1.0-GGUF/resolve/main/wizardcoder-python-13b-v1.0.Q4_K_M.gguf
```
```
!wget https://huggingface.co/TheBloke/WizardCoder-Python-13B-V1.0-GGUF/blob/main/config.json
```
4. Installing requirements:
```
cd ..
```
```
cd ..
```
```
!pip install tiktoken sentence_transformers SpeechRecognition
!pip install sse_starlette
!pip install flask_cloudflared
```
5. Launch:
```
!python server.py --share --model wizardcoder-13b --extensions openai --n-gpu-layers 125 --n_ctx 5000 --public-api
```

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/146547175/2aa606e5-3049-4039-a6b6-ae58423bbfa1)

### Logs

```shell
no
```

### System Info

```shell
System info: google colab
```

**Comment by Tql-ws1** [comment]
I tried to reproduce the situation on my local host, but it can load normally without a config.json file. Have you checked if there is any problem with the format of config.json? I am currently using version c54d1da of the text-generation-webui.
