### ISSUE TITLE
Loading AWQ Model Results in TypeError - models_config.py

### ISSUE THREAD

**Issue by reynolds087** [oobabooga/text-generation-webui#4904]
### Describe the bug

I have experienced this with two models now. In this case TheBloke/AmberChat-AWQ
After downloading through the webUI, I attempt to load the model and receive the following error:

TypeError: AwqConfig.init() got an unexpected keyword argument 'modules_to_not_convert'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Download this model, select AutoAWQ and load.

### Logs

```shell
Whether to load the model as soon as it is selected in the Model dropdown.
Autoload the model
Download model or LoRA
Enter the Hugging Face username/model path, for instance: facebook/galactica-125m. To specify a branch, add it at the end after a ":" character like this: facebook/galactica-125m:main. To download a single file, enter its name in the second box.
Textbox

Traceback (most recent call last):

File "E:\Programs\text-generation-webui\modules\ui_model_menu.py", line 209, in load_model_wrapper

shared.model, shared.tokenizer = load_model(shared.model_name, loader)

                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "E:\Programs\text-generation-webui\modules\models.py", line 88, in load_model

output = load_func_map[loader](model_name)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "E:\Programs\text-generation-webui\modules\models.py", line 314, in AutoAWQ_loader

model = AutoAWQForCausalLM.from_quantized(

        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "E:\Programs\text-generation-webui\installer_files\env\Lib\site-packages\awq\models\auto.py", line 52, in from_quantized

return AWQ_CAUSAL_LM_MODEL_MAP[model_type].from_quantized(

       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "E:\Programs\text-generation-webui\installer_files\env\Lib\site-packages\awq\models\base.py", line 154, in from_quantized

model_weights_path, config, quant_config = self._load_config(

                                           ^^^^^^^^^^^^^^^^^^

File "E:\Programs\text-generation-webui\installer_files\env\Lib\site-packages\awq\models\base.py", line 206, in _load_config

quant_config = AwqConfig.from_pretrained(model_path)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "E:\Programs\text-generation-webui\installer_files\env\Lib\site-packages\awq\models_config.py", line 68, in from_pretrained

quant_config = cls(**loaded_config)

               ^^^^^^^^^^^^^^^^^^^^

TypeError: AwqConfig.init() got an unexpected keyword argument 'modules_to_not_convert'
```

### System Info

```shell
Nvidia 4090, Windows 11 Pro
```

**Comment by jpeig** [comment]
Have the same issue. +1

**Comment by YakuzaSuske** [comment]
That happened to me with Mistral 7B but just load it using transformers and it "should" work fine. At least for me it did.

**Comment by HydeHat** [comment]
I am having the same problem, any AWQ files I downloaded before this week work. Any new downloads fail to load. they will load with transformers but run very slowly. It does seem to be on Minstral 7B but older copies based in minstral 7b seam to work.

**Comment by kalle07** [comment]
same error with latest autoAWQ
(and most models run very fine)

but
TheBloke_MelloGPT-AWQ -> dont
TheBloke_supermario-v2-AWQ -> dont 

error:
......
Traceback (most recent call last):
  File "e:\text-generation-webui\modules\ui_model_menu.py", line 210, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
  File "e:\text-generation-webui\modules\models.py", line 89, in load_model
    output = load_func_map[loader](model_name)
  File "e:\text-generation-webui\modules\models.py", line 320, in AutoAWQ_loader
    model = AutoAWQForCausalLM.from_quantized(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\awq\models\auto.py", line 52, in from_quantized
    return AWQ_CAUSAL_LM_MODEL_MAP[model_type].from_quantized(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\awq\models\base.py", line 154, in from_quantized
    model_weights_path, config, quant_config = self._load_config(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\awq\models\base.py", line 206, in _load_config
    quant_config = AwqConfig.from_pretrained(model_path)
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\awq\models\_config.py", line 68, in from_pretrained
    quant_config = cls(**loaded_config)
TypeError: AwqConfig.__init__() got an unexpected keyword argument 'modules_to_not_convert'
.....

btw 
tts is not compatible with the new transformer version !

**Comment by mercuryyy** [comment]
Any update on this?

**Comment by lpohl** [comment]
Building Docker (nvidia) with autoawq==0.1.8 (requirements.txt) works for me, but I also needed python 3.11 which I did via miniconda.
[Dockerfile.txt](https://github.com/oobabooga/text-generation-webui/files/13760373/Dockerfile.txt)

**Comment by Aledar** [comment]
I believe this issue is fixed in this commit https://github.com/oobabooga/text-generation-webui/commit/92d5e64a82bd68ca822c5d7da40307a9b48ba83f where AutoAWQ requirement is updated to 0.1.8

Had the same error when trying to load TheBloke_WizardCoder-33B-V1.1-AWQ. 

Read Ipohl's comment, realised I was running on an older version (by a couple weeks). I'm running via 'text-generation-webui-docker' using docker compose so pulled the latest image using `docker compose pull` and then recreated stack using `docker compose up -d` (update method will depend on how your instance is installed)

Started working after updating.
