### ISSUE TITLE
start_macos.sh causes ImportError: cannot import name 'is_torch_xpu_available' from 'transformers' 

### ISSUE THREAD

**Issue by palimondo** [oobabooga/text-generation-webui#4913]
### Describe the bug

After updating to latest main branch, stuff is broken.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Update to latest main, using git pull
run ./start_macos.sh

### Logs

```shell
./start_macos.sh
Traceback (most recent call last):
  File "/Users/palimondo/Developer/text-generation-webui/server.py", line 35, in <module>
    from modules import (
  File "/Users/palimondo/Developer/text-generation-webui/modules/chat.py", line 20, in <module>
    from modules.text_generation import (
  File "/Users/palimondo/Developer/text-generation-webui/modules/text_generation.py", line 12, in <module>
    from transformers import LogitsProcessorList, is_torch_xpu_available
ImportError: cannot import name 'is_torch_xpu_available' from 'transformers' (/Users/palimondo/Developer/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/__init__.py)
```

### System Info

```shell
macOS 14.1.2 (23B92)
git rev-parse main
3e0c11a7587c9b026652ece390e85f063b72df22
```

**Comment by michnaugh1** [comment]
Same issue here. M2 Mac Mini. MacOS 14.2.

**Comment by palimondo** [comment]
```
git pull
Already up to date.

git rev-parse main
11288d11d42f0be9a9d079c03d34c573a5cc696d

./start_macos.sh
Traceback (most recent call last):
  File "/Users/palimondo/Developer/text-generation-webui/server.py", line 6, in <module>
    import modules.one_click_installer_check
  File "/Users/palimondo/Developer/text-generation-webui/modules/one_click_installer_check.py", line 3, in <module>
    from modules.logging_colors import logger
  File "/Users/palimondo/Developer/text-generation-webui/modules/logging_colors.py", line 67, in <module>
    setup_logging()
  File "/Users/palimondo/Developer/text-generation-webui/modules/logging_colors.py", line 30, in setup_logging
    from rich.console import Console
ModuleNotFoundError: No module named 'rich'
```

**Comment by fivecanal5** [comment]
I'm also getting the No module named 'rich' error. Manually installing rich with "python -m pip install rich" as per [https://pypi.org/project/rich/ ](url) fixed it.

**Comment by palimondo** [comment]
Manually installing it with `python3` (there's no `python` on recent mac OS versions) does not resolve the issue for me, as it reports it's already installed. Does anybody actively maintain the mac port?!

**Comment by smytjf11** [comment]
I have the same behavior on Windows with start_windows.sh, and manually running server.py

```
C:\Users\smytj\Documents\MLTools\text-generation-webui>python server.py --api
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\smytj\Documents\MLTools\text-generation-webui\server.py:39 in <module>                                     │
│                                                                                                                     │
│    38 import modules.extensions as extensions_module                                                                │
│ >  39 from modules import (                                                                                         │
│    40     chat,                                                                                                     │
│                                                                                                                     │
│ C:\Users\smytj\Documents\MLTools\text-generation-webui\modules\chat.py:21 in <module>                               │
│                                                                                                                     │
│    20 from modules.logging_colors import logger                                                                     │
│ >  21 from modules.text_generation import (                                                                         │
│    22     generate_reply,                                                                                           │
│                                                                                                                     │
│ C:\Users\smytj\Documents\MLTools\text-generation-webui\modules\text_generation.py:13 in <module>                    │
│                                                                                                                     │
│    12 import transformers                                                                                           │
│ >  13 from transformers import LogitsProcessorList, is_torch_xpu_available                                          │
│    14                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ImportError: cannot import name 'is_torch_xpu_available' from 'transformers'
(C:\Users\smytj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Pyt
hon311\site-packages\transformers\__init__.py)
```

If I try to run the one click installer, I get a Conda error that seems unrelated. 

```
C:\Users\smytj\Documents\MLTools\text-generation-webui>python one_click.py
Traceback (most recent call last):
  File "C:\Users\smytj\Documents\MLTools\text-generation-webui\one_click.py", line 367, in <module>
    check_env()
  File "C:\Users\smytj\Documents\MLTools\text-generation-webui\one_click.py", line 117, in check_env
    if os.environ["CONDA_DEFAULT_ENV"] == "base":
       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'CONDA_DEFAULT_ENV'
```
