### ISSUE TITLE
Loading models don't work

### ISSUE THREAD

**Issue by Cryptic1526** [oobabooga/text-generation-webui#4919]
### Describe the bug

I installed this for the first time and I'm really new to all this. I installed everything like the tutorials but no models are working, I tried like 5 different ones from TheBloke but none of them work. I looked at other issues but online and in the github issues, but they were either different enough, or their solutions didn't work for me.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I guess just try load any model

### Screenshot

![Screenshot 2023-12-15 003259](https://github.com/oobabooga/text-generation-webui/assets/119151348/ff898656-5f33-428a-98ab-b14664b97346)
![Screenshot 2023-12-15 003232](https://github.com/oobabooga/text-generation-webui/assets/119151348/c295bda6-2b81-4746-924e-57b0c92f4a39)
![Screenshot 2023-12-15 003244](https://github.com/oobabooga/text-generation-webui/assets/119151348/4b27b81b-31e7-4bca-918c-a123dea49ba1)

### Logs

```shell
Traceback (most recent call last):
  File "C:\FakePath\text-generation-webui\modules\ui_model_menu.py", line 208, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FakePath\text-generation-webui\modules\models.py", line 89, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FakePath\text-generation-webui\modules\models.py", line 315, in AutoAWQ_loader
    model = AutoAWQForCausalLM.from_quantized(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FakePath\text-generation-webui\installer_files\env\Lib\site-packages\awq\models\auto.py", line 52, in from_quantized
    return AWQ_CAUSAL_LM_MODEL_MAP[model_type].from_quantized(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FakePath\text-generation-webui\installer_files\env\Lib\site-packages\awq\models\base.py", line 182, in from_quantized
    self.fuse_layers(model)
  File "C:\FakePath\text-generation-webui\installer_files\env\Lib\site-packages\awq\models\mistral.py", line 21, in fuse_layers
    fuser.fuse_transformer()
  File "C:\FakePath\text-generation-webui\installer_files\env\Lib\site-packages\awq\models\mistral.py", line 111, in fuse_transformer
    blocks.append(LlamaLikeBlock(
                  ^^^^^^^^^^^^^^^
  File "C:\FakePath\text-generation-webui\installer_files\env\Lib\site-packages\awq\modules\fused\block.py", line 15, in __init__
    self.norm_1 = norm_1.to(dev)
                  ^^^^^^^^^^^^^^
  File "C:\FakePath\text-generation-webui\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1160, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\FakePath\text-generation-webui\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "C:\FakePath\text-generation-webui\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### System Info

```shell
Windows 11 Home
NVIDIA RTX 3050
AMD Ryzen 5 5600H with Radeon Graphics (3.30 GHz), 16.0 GB RAM (15.3 GB usable)
```

**Comment by Cryptic1526** [comment]
Also I'd like to add that it's not me loading the model wrong I think, I tried it with AWQ models and tried loading them with AutoAWQ, so I don't think it's that. @oobabooga

**Comment by xwatcherx** [comment]
Have the same issue, hope someone help us
