### ISSUE TITLE
Error allocating RAM using CPU

### ISSUE THREAD

**Issue by PeterDaGrape** [oobabooga/text-generation-webui#492]
### Describe the bug

Ive just reinstalled text-generation-webui following the guide: [](https://www.tomshardware.com/news/running-your-own-chatbot-on-a-single-gpu ) and whenever I run the code im getting the error: RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 90177536 bytes. I know that I have enough ram for that, however it still fails, I cannot test on GPU as i am currently away from it, currently downloading a smaller model to test to make sure the rest of it is working, probably something to do with GPTQ though so I will check over there as well

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Just following the guide in https://www.tomshardware.com/news/running-your-own-chatbot-on-a-single-gpu, likely just my hardware being weird though

### Logs

```shell
(llama4bit) PS C:\Users\Peter\llama\text-generation-webui> python server.py --gptq-bits 4 --cpu
The following models are available:

1. llama-7b
2. pygmalion-2.7b

Which one do you want to load? 1-2

1

Loading llama-7b...
CUDA extension not installed.
Traceback (most recent call last):
  File "C:\Users\Peter\llama\text-generation-webui\server.py", line 241, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\Peter\llama\text-generation-webui\modules\models.py", line 101, in load_model
    model = load_quantized(model_name)
  File "C:\Users\Peter\llama\text-generation-webui\modules\GPTQ_loader.py", line 64, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.gptq_bits)
  File "C:\Users\Peter\llama\text-generation-webui\repositories\GPTQ-for-LLaMa\llama.py", line 231, in load_quant
    model = LlamaForCausalLM(config)
  File "C:\Users\Peter\miniconda3\envs\llama4bit\lib\site-packages\transformers\models\llama\modeling_llama.py", line 652, in __init__
    self.model = LlamaModel(config)
  File "C:\Users\Peter\miniconda3\envs\llama4bit\lib\site-packages\transformers\models\llama\modeling_llama.py", line 457, in __init__
    self.layers = nn.ModuleList([LlamaDecoderLayer(config) for _ in range(config.num_hidden_layers)])
  File "C:\Users\Peter\miniconda3\envs\llama4bit\lib\site-packages\transformers\models\llama\modeling_llama.py", line 457, in <listcomp>
    self.layers = nn.ModuleList([LlamaDecoderLayer(config) for _ in range(config.num_hidden_layers)])
  File "C:\Users\Peter\miniconda3\envs\llama4bit\lib\site-packages\transformers\models\llama\modeling_llama.py", line 274, in __init__
    self.mlp = LlamaMLP(
  File "C:\Users\Peter\miniconda3\envs\llama4bit\lib\site-packages\transformers\models\llama\modeling_llama.py", line 146, in __init__
    self.down_proj = nn.Linear(intermediate_size, hidden_size, bias=False)
  File "C:\Users\Peter\miniconda3\envs\llama4bit\lib\site-packages\torch\nn\modules\linear.py", line 96, in __init__
    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 90177536 bytes.
```

### System Info

```shell
i5 7360U 8GB Ram, enough storage as well for swap space
```

**Comment by PeterDaGrape** [comment]
@oobabooga I never found out why it couldn't allocate the memory, I just gave up and went over to WSL, and also my issue may be related to the fact I have very little ram in my system

**Comment by Snimm** [comment]
@PeterDaGrape @oobabooga  I have the same problem. I have RTX 3060 12 GB and 16 GB RAM. So does using it in WSL or Ubuntu solve the issue?
