### ISSUE TITLE
Why it always occurs before truly shutting it up?

### ISSUE THREAD

**Issue by AimoneAndex** [oobabooga/text-generation-webui#4943]
When I use Ctrl+C to end a command, the following error always occurs before asking "Do you want to terminate the process?". I don't know where the configuration issue is.
log:
Exception ignored in: <function _LlamaContext.__del__ at 0x0000027970E7B100>
Traceback (most recent call last):
  File "D:\llama\text-generation-webui\installer_files\env\Lib\site-packages\llama_cpp\llama.py", line 422, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function _LlamaModel.__del__ at 0x0000027970E7A0C0>
Traceback (most recent call last):
  File "D:\llama\text-generation-webui\installer_files\env\Lib\site-packages\llama_cpp\llama.py", line 240, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function _LlamaBatch.__del__ at 0x00000279710C05E0>
Traceback (most recent call last):
  File "D:\llama\text-generation-webui\installer_files\env\Lib\site-packages\llama_cpp\llama.py", line 670, in __del__
TypeError: 'NoneType' object is not callable

**Comment by AimoneAndex** [comment]
Anyone here？
