### ISSUE TITLE
fail to load Mixtral-8x7B-v0.1-GPTQ

### ISSUE THREAD

**Issue by AlexDeng-AI** [oobabooga/text-generation-webui#4960]
### Describe the bug

I load Mixtral-8x7B-v0.1-GPTQ using loader AutoGPTQ, but error occurs as follow:
2023-12-17 18:20:44 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/home/chao/work/text-generation-webui/modules/ui_model_menu.py", line 209, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chao/work/text-generation-webui/modules/models.py", line 89, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chao/work/text-generation-webui/modules/models.py", line 385, in AutoGPTQ_loader
    return modules.AutoGPTQ_loader.load_quantized(model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chao/work/text-generation-webui/modules/AutoGPTQ_loader.py", line 59, in load_quantized
    model = AutoGPTQForCausalLM.from_quantized(path_to_model, **params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chao/miniconda3/envs/textgen/lib/python3.11/site-packages/auto_gptq/modeling/auto.py", line 129, in from_quantized
    return quant_func(
           ^^^^^^^^^^^
  File "/home/chao/miniconda3/envs/textgen/lib/python3.11/site-packages/auto_gptq/modeling/_base.py", line 946, in from_quantized
    accelerate.utils.modeling.load_checkpoint_in_model(
  File "/home/chao/miniconda3/envs/textgen/lib/python3.11/site-packages/accelerate/utils/modeling.py", line 1494, in load_checkpoint_in_model
    set_module_tensor_to_device(
  File "/home/chao/miniconda3/envs/textgen/lib/python3.11/site-packages/auto_gptq/utils/patch_utils.py", line 53, in set_module_tensor_to_device_patched
    raise ValueError(
ValueError: Trying to set a tensor of shape torch.Size([384, 14336]) in "qweight" (which has shape torch.Size([512, 14336])), this look incorrect.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

step 1: download Mixtral-8x7B-v0.1-GPTQ
step 2: select Mixtral-8x7B-v0.1-GPTQ
step 3: click load button

### Logs

```shell
warnings.warn(
2023-12-17 18:20:22 INFO:Loading Mixtral-8x7B-v0.1-GPTQ...
2023-12-17 18:20:23 INFO:The AutoGPTQ params are: {'model_basename': 'model', 'device': 'cuda:0', 'use_triton': False, 'inject_fused_attention': True, 'inject_fused_mlp': True, 'use_safetensors': True, 'trust_remote_code': False, 'max_memory': None, 'quantize_config': None, 'use_cuda_fp16': True, 'disable_exllama': False, 'disable_exllamav2': False}
2023-12-17 18:20:23 WARNING:You have activated both exllama and exllamav2 kernel. Setting disable_exllama to True and keeping disable_exllamav2 to False
2023-12-17 18:20:44 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/home/chao/work/text-generation-webui/modules/ui_model_menu.py", line 209, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chao/work/text-generation-webui/modules/models.py", line 89, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chao/work/text-generation-webui/modules/models.py", line 385, in AutoGPTQ_loader
    return modules.AutoGPTQ_loader.load_quantized(model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chao/work/text-generation-webui/modules/AutoGPTQ_loader.py", line 59, in load_quantized
    model = AutoGPTQForCausalLM.from_quantized(path_to_model, **params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chao/miniconda3/envs/textgen/lib/python3.11/site-packages/auto_gptq/modeling/auto.py", line 129, in from_quantized
    return quant_func(
           ^^^^^^^^^^^
  File "/home/chao/miniconda3/envs/textgen/lib/python3.11/site-packages/auto_gptq/modeling/_base.py", line 946, in from_quantized
    accelerate.utils.modeling.load_checkpoint_in_model(
  File "/home/chao/miniconda3/envs/textgen/lib/python3.11/site-packages/accelerate/utils/modeling.py", line 1494, in load_checkpoint_in_model
    set_module_tensor_to_device(
  File "/home/chao/miniconda3/envs/textgen/lib/python3.11/site-packages/auto_gptq/utils/patch_utils.py", line 53, in set_module_tensor_to_device_patched
    raise ValueError(
ValueError: Trying to set a tensor of shape torch.Size([384, 14336]) in "qweight" (which has shape torch.Size([512, 14336])), this look incorrect.
```

### System Info

```shell
debian 11
```

**Comment by SEVENID** [comment]
What's version do you use? 
See also: #4897 https://github.com/oobabooga/text-generation-webui/pull/4882

**Comment by killfrenzy96** [comment]
I'm also unable to load Mixtral 8x7B GPTQ using AutoGPTQ. I'm using the 3bit 128g version from:
https://huggingface.co/TheBloke/Mixtral-8x7B-v0.1-GPTQ

The WebUI crashes without displaying any further errors when loading the model. A fresh install of the WebUI produces the same results. Other models load and function correctly, including Mixtral 8x7B GGUF using llama.cpp.

Running Windows 10 and a RTX 4090. NVIDIA driver version 546.17.

Logs:
```
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
C:\Programs\text-generation-webui\installer_files\env\Lib\site-packages\gradio\components\dropdown.py:231: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 3 or set allow_custom_value=True.
  warnings.warn(
C:\Programs\text-generation-webui\installer_files\env\Lib\site-packages\gradio\components\dropdown.py:231: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 128 or set allow_custom_value=True.
  warnings.warn(
2023-12-18 04:51:12 INFO:Loading Mixtral-8x7B-v0.1-GPTQ-3b-128g...
2023-12-18 04:51:13 INFO:The AutoGPTQ params are: {'model_basename': 'model', 'device': 'cuda:0', 'use_triton': False, 'inject_fused_attention': True, 'inject_fused_mlp': True, 'use_safetensors': True, 'trust_remote_code': False, 'max_memory': {0: '23000MiB', 'cpu': '99GiB'}, 'quantize_config': None, 'use_cuda_fp16': True, 'disable_exllama': False, 'disable_exllamav2': True}
Press any key to continue . . .
```
![](https://i.imgur.com/A5ASwsX.png)

**Comment by barrymac** [comment]
This works for me now with the latest version. No other pip modules needed to be installed. The model took about 1003 seconds to load first time on my 4x V100 SXM2 GPUs to load.

**Comment by AlexDeng-AI** [comment]
Thanks, I will try it.

**Comment by AlexDeng-AI** [comment]
> This works for me now with the latest version. No other pip modules needed to be installed. The model took about 1003 seconds to load first time on my 4x V100 SXM2 GPUs to load. 

Thanks. I will try it.

**Comment by SaidTorres3** [comment]
> I'm also unable to load Mixtral 8x7B GPTQ using AutoGPTQ. I'm using the 3bit 128g version from: https://huggingface.co/TheBloke/Mixtral-8x7B-v0.1-GPTQ
> 
> The WebUI crashes without displaying any further errors when loading the model. A fresh install of the WebUI produces the same results. Other models load and function correctly, including Mixtral 8x7B GGUF using llama.cpp.
> 
> Running Windows 10 and a RTX 4090. NVIDIA driver version 546.17.
> 
> Logs:
> 
> ```
> Running on local URL:  http://127.0.0.1:7860
> 
> To create a public link, set `share=True` in `launch()`.
> C:\Programs\text-generation-webui\installer_files\env\Lib\site-packages\gradio\components\dropdown.py:231: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 3 or set allow_custom_value=True.
>   warnings.warn(
> C:\Programs\text-generation-webui\installer_files\env\Lib\site-packages\gradio\components\dropdown.py:231: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 128 or set allow_custom_value=True.
>   warnings.warn(
> 2023-12-18 04:51:12 INFO:Loading Mixtral-8x7B-v0.1-GPTQ-3b-128g...
> 2023-12-18 04:51:13 INFO:The AutoGPTQ params are: {'model_basename': 'model', 'device': 'cuda:0', 'use_triton': False, 'inject_fused_attention': True, 'inject_fused_mlp': True, 'use_safetensors': True, 'trust_remote_code': False, 'max_memory': {0: '23000MiB', 'cpu': '99GiB'}, 'quantize_config': None, 'use_cuda_fp16': True, 'disable_exllama': False, 'disable_exllamav2': True}
> Press any key to continue . . .
> ```
> 
> ![](https://camo.githubusercontent.com/25a6592d891a6ae3151b6be3c3f83a028123e4352a89085941230596e9c105d1/68747470733a2f2f692e696d6775722e636f6d2f413541537773582e706e67)

Same problem, is still happening.

**Comment by JamesGoldenPlow** [comment]
Same exact problem here.

**Comment by antoineprobst** [comment]
Same problem. "The WebUI crashes without displaying any further errors when loading the model. A fresh install of the WebUI produces the same results."

**Comment by TheSenorrPomidor** [comment]
У меня версия v3.12 text-generation-webui + v0.45.0 llama-cpp-binaries модель TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF и та же ошибка: 
```
21:06:30-531766 INFO     Loading "mixtral-8x7b-instruct-v0.1.Q2_K.gguf"
21:06:30-534036 INFO     Using gpu_layers=15 | ctx_size=8192 | cache_type=fp16
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3080, compute capability 8.6, VMM: yes
build: 1 (9961d24) with cc (Ubuntu 11.4.0-1ubuntu1~22.04.2) 11.4.0 for x86_64-linux-gnu
system info: n_threads = 6, n_threads_batch = 6, total_threads = 6
system_info: n_threads = 6 (n_threads_batch = 6) / 6 | CUDA : ARCHS = 500,520,530,600,610,620,700,720,750,800,860,870,890,900 | USE_GRAPHS = 1 | PEER_MAX_BATCH_SIZE = 128 | CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | AVX2 = 1 | F16C = 1 | FMA = 1 | BMI2 = 1 | LLAMAFILE = 1 | OPENMP = 1 | REPACK = 1 |
Web UI is disabled
main: binding port with default address family
main: HTTP server is listening, hostname: 127.0.0.1, port: 50683, http threads: 5
main: loading model
llama_model_load_from_file_impl: using device CUDA0 (NVIDIA GeForce RTX 3080) - 9073 MiB free
llama_model_loader: loaded meta data with 26 key-value pairs and 995 tensors from user_data/models/mixtral-8x7b-instruct-v0.1.Q2_K.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = mistralai_mixtral-8x7b-instruct-v0.1
llama_model_loader: - kv   2:                       llama.context_length u32              = 32768
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   9:                         llama.expert_count u32              = 8
llama_model_loader: - kv  10:                    llama.expert_used_count u32              = 2
llama_model_loader: - kv  11:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  12:                       llama.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  13:                          general.file_type u32              = 10
llama_model_loader: - kv  14:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  15:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  16:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  17:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  18:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  19:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  20:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  21:            tokenizer.ggml.padding_token_id u32              = 0
llama_model_loader: - kv  22:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  23:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  24:                    tokenizer.chat_template str              = {{ bos_token }}{% for message in mess...
llama_model_loader: - kv  25:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type  f16:   32 tensors
llama_model_loader: - type q8_0:   64 tensors
llama_model_loader: - type q2_K:  801 tensors
llama_model_loader: - type q3_K:   32 tensors
llama_model_loader: - type q6_K:    1 tensors
print_info: file format = GGUF V3 (latest)
print_info: file type   = Q2_K - Medium
print_info: file size   = 14.57 GiB (2.68 BPW)
load: special_eos_id is not in special_eog_ids - the tokenizer config may be incorrect
load: printing all EOG tokens:
load:   - 2 ('</s>')
load: special tokens cache size = 3
load: token to piece cache size = 0.1637 MB
print_info: arch             = llama
print_info: vocab_only       = 0
print_info: n_ctx_train      = 32768
print_info: n_embd           = 4096
print_info: n_layer          = 32
print_info: n_head           = 32
print_info: n_head_kv        = 8
print_info: n_rot            = 128
print_info: n_swa            = 0
print_info: is_swa_any       = 0
print_info: n_embd_head_k    = 128
print_info: n_embd_head_v    = 128
print_info: n_gqa            = 4
print_info: n_embd_k_gqa     = 1024
print_info: n_embd_v_gqa     = 1024
print_info: f_norm_eps       = 0.0e+00
print_info: f_norm_rms_eps   = 1.0e-05
print_info: f_clamp_kqv      = 0.0e+00
print_info: f_max_alibi_bias = 0.0e+00
print_info: f_logit_scale    = 0.0e+00
print_info: f_attn_scale     = 0.0e+00
print_info: n_ff             = 14336
print_info: n_expert         = 8
print_info: n_expert_used    = 2
print_info: causal attn      = 1
print_info: pooling type     = 0
print_info: rope type        = 0
print_info: rope scaling     = linear
print_info: freq_base_train  = 1000000.0
print_info: freq_scale_train = 1
print_info: n_ctx_orig_yarn  = 32768
print_info: rope_finetuned   = unknown
print_info: model type       = 8x7B
print_info: model params     = 46.70 B
print_info: general.name     = mistralai_mixtral-8x7b-instruct-v0.1
print_info: vocab type       = SPM
print_info: n_vocab          = 32000
print_info: n_merges         = 0
print_info: BOS token        = 1 '<s>'
print_info: EOS token        = 2 '</s>'
print_info: UNK token        = 0 '<unk>'
print_info: PAD token        = 0 '<unk>'
print_info: LF token         = 13 '<0x0A>'
print_info: EOG token        = 2 '</s>'
print_info: max token length = 48
load_tensors: loading model tensors, this can take a while... (mmap = true)
llama_model_load: error loading model: missing tensor 'blk.0.ffn_down_exps.weight'
llama_model_load_from_file_impl: failed to load model
common_init_from_params: failed to load model 'user_data/models/mixtral-8x7b-instruct-v0.1.Q2_K.gguf', try reducing --n-gpu-layers if you're running out of VRAM
main: exiting due to model loading error
21:06:31-536686 ERROR    Error loading the model with llama.cpp: Server process terminated unexpectedly with exit code:
                         1
```
