### ISSUE TITLE
NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by ascyphermoonshot** [oobabooga/text-generation-webui#4965]
### Describe the bug

When I try to train this model https://huggingface.co/pansophic/rocket-3B on this dataset https://ia904606.us.archive.org/26/items/alpaca_format/alpaca_format.json I get an error message that says

`NotImplementedError: Cannot copy out of meta tensor; no data!`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load the model in transformers after having accepted the repo and logged in to huggingface-cli

Set up LORA training job

Start training 

### Screenshot

![IMG-20231217-WA0001](https://github.com/oobabooga/text-generation-webui/assets/102254539/821a3f7f-78f8-4b77-9777-b5729e5428aa)

### Logs

```shell
(base) omar@The-Machine:~/text-generation-webui$ bash start_linux.sh --listen --trust-remote-code
2023-12-17 15:53:39 WARNING:trust_remote_code is enabled. This is dangerous.
2023-12-17 15:53:39 WARNING:
You are potentially exposing the web UI to the entire internet without any access password.
You can create one with the "--gradio-auth" flag like this:

--gradio-auth username:password

Make sure to replace username:password with your own.
2023-12-17 15:53:42 INFO:Loading settings from settings.yaml...
2023-12-17 15:53:42 INFO:Loading the extension "gallery"...
2023-12-17 15:53:42 INFO:Loading the extension "long_replies"...
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
2023-12-17 15:55:02 INFO:Loading pansophic_rocket-3B...
2023-12-17 15:55:03 INFO:TRUNCATION LENGTH: 4096
2023-12-17 15:55:03 INFO:INSTRUCTION TEMPLATE: Alpaca
2023-12-17 15:55:03 INFO:Loaded the model in 1.24 seconds.
2023-12-17 15:55:34 WARNING:LoRA training has only currently been validated for LLaMA, OPT, GPT-J, and GPT-NeoX models. (Found model type: StableLMEpochForCausalLM)
2023-12-17 15:55:39 INFO:Loading JSON datasets...
Downloading data files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17772.47it/s]
Extracting data files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1878.33it/s]
Generating train split: 247655 examples [00:01, 159846.39 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 247655/247655 [02:22<00:00, 1735.84 examples/s]
2023-12-17 15:58:03 INFO:Getting model ready...
2023-12-17 15:58:04 INFO:Preparing for training...
2023-12-17 15:58:04 INFO:Creating LoRA model...
Traceback (most recent call last):
  File "/home/omar/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/omar/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/omar/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/omar/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/omar/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/omar/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/omar/text-generation-webui/installer_files/env/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/omar/text-generation-webui/installer_files/env/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/omar/text-generation-webui/installer_files/env/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/omar/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/home/omar/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/home/omar/text-generation-webui/modules/training.py", line 607, in do_train
    trainer = transformers.Trainer(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/omar/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/trainer.py", line 481, in __init__
    self._move_model_to_device(model, args.device)
  File "/home/omar/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/trainer.py", line 716, in _move_model_to_device
    model = model.to(device)
            ^^^^^^^^^^^^^^^^
  File "/home/omar/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/omar/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/omar/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/omar/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 6 more times]
  File "/home/omar/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/home/omar/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError: Cannot copy out of meta tensor; no data!
```

### System Info

```shell
Operating System: Ubuntu 22.04.3 LTS x86_64

CPU: AMD Ryzen 5 4600H with Radeon Graphics (12 cores) @ 3.000GHz

GPU:
NVIDIA GeForce GTX 1050 3 GB Max-Q

AMD ATI 05:00.0 Renoir

Memory: 16 GB RAM (929 MiB used)

Kernel: 6.2.0-39-generic

Shell: Bash 5.1.16

Packages: 2469 (dpkg), 18 (snap)
Disk: 75GB / 98GB (81% used)
```

**Comment by platima** [comment]
I get this when I run out of VRAM, tried watching resource consumption whilst running that process?
