### ISSUE TITLE
Error loading Mixtral Exl2 quant

### ISSUE THREAD

**Issue by truenorth8** [oobabooga/text-generation-webui#4981]
### Describe the bug

Loading an exl2 mixtral model results in an error:
> ValueError: ## Could not find model.layers.0.mlp.down_proj.* in model

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

checkout commit (latest) https://github.com/oobabooga/text-generation-webui/commit/b28020a9e444ce9a3a872b7b507d771b8e653198

- download `turboderp/Mixtral-8x7B-exl2:5.0bpw` or any other exl2 model from HF
- select the model in the "Model" list
- click "Load"
-> ValueError: ## Could not find model.layers.0.mlp.down_proj.* in model

I have tried a number of exl2 models, they all give the same error.
GGFUs are fine

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/123232491/4532f75c-9b22-43cb-af3f-26095c225979)

### Logs

```shell
Traceback (most recent call last):
File "/workspace/text-generation-webui/modules/ui_model_menu.py", line 210, in load_model_wrapper
shared.model, shared.tokenizer = load_model(selected_model, loader)
File "/workspace/text-generation-webui/modules/models.py", line 89, in load_model
output = load_func_map[loader](model_name)
File "/workspace/text-generation-webui/modules/models.py", line 411, in ExLlamav2_HF_loader
return Exllamav2HF.from_pretrained(model_name)
File "/workspace/text-generation-webui/modules/exllamav2_hf.py", line 162, in from_pretrained
config.prepare()
File "/usr/local/lib/python3.10/dist-packages/exllamav2/config.py", line 156, in prepare
raise ValueError(f" ## Could not find {prefix}.* in model")
ValueError: ## Could not find model.layers.0.mlp.down_proj.* in model
```

### System Info

```shell
RTX A6000 on runpod

Docker image
> thebloke/cuda11.8.0-ubuntu22.04-oneclick:latest
```

**Comment by truenorth8** [comment]
I was told this is likely due to an outdated exllama module in oobabooga
