### ISSUE TITLE
from rich.console import Console ModuleNotFoundError: No module named 'rich'

### ISSUE THREAD

**Issue by mongolu** [oobabooga/text-generation-webui#5013]
### Describe the bug

seems it needs `rich `to be pip installed

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

  File "/app/text-generation-webui/modules/logging_colors.py", line 30, in setup_logging
    from rich.console import Console
ModuleNotFoundError: No module named 'rich'

### Logs

```shell
# All requested packages already installed.
There are no unused tarball(s) to remove.
Will remove 1 index cache(s).
There are no unused package(s) to remove.
There are no tempfile(s) to remove.
There are no logfile(s) to remove.
Files removed: 70
Done!
Traceback (most recent call last):
  File "/app/text-generation-webui/server.py", line 6, in <module>
    import modules.one_click_installer_check
  File "/app/text-generation-webui/modules/one_click_installer_check.py", line 3, in <module>
    from modules.logging_colors import logger
  File "/app/text-generation-webui/modules/logging_colors.py", line 67, in <module>
    setup_logging()
  File "/app/text-generation-webui/modules/logging_colors.py", line 30, in setup_logging
    from rich.console import Console
ModuleNotFoundError: No module named 'rich'
```

### System Info

```shell
ubuntu 22.04
```

**Comment by mongolu** [comment]
solved with #258c695

**Comment by Zaithe** [comment]
Got this error in the latest version after updating, as a fix i just manually copied the files to text-generation-webui\installer_files\env\Lib

**Comment by didhd** [comment]
Also having this error
