### ISSUE TITLE
Unable to load a the wizard vicuna model in my text generation webui.

### ISSUE THREAD

**Issue by 4yu5h-crtl** [oobabooga/text-generation-webui#5020]
22:17:04-528730 INFO     Loading TheBloke_Wizard-Vicuna-30B-Uncensored-GPTQ
22:17:06-425349 ERROR    Failed to load the model.
Traceback (most recent call last):
  File "E:\text-generation-webui-main\modules\ui_model_menu.py", line 214, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\text-generation-webui-main\modules\models.py", line 90, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\text-generation-webui-main\modules\models.py", line 399, in ExLlama_HF_loader
    return ExllamaHF.from_pretrained(model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\text-generation-webui-main\modules\exllama_hf.py", line 174, in from_pretrained
    return ExllamaHF(config)
           ^^^^^^^^^^^^^^^^^
  File "E:\text-generation-webui-main\modules\exllama_hf.py", line 31, in __init__
    self.ex_model = ExLlama(self.ex_config)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\text-generation-webui-main\installer_files\env\Lib\site-packages\exllama\model.py", line 743, in __init__
    with safe_open(path, framework = "pt", device = "cpu") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

WHENEVER I TRY TO LOAD THE MODEL THE ABOVE MESSAGE APPEARS AND STOPS. WELL THE ISSUE IS NOT ONLY I CASE OF VICUNA MODEL IT APPEARS IN WHICHEVER MODEL I TRY..............PLEASE HELP ME SOLVE THIS ISSUE.

**Comment by randomtask2000** [comment]
I have the same issue

**Comment by CodeDevMasterPro** [comment]
+1

**Comment by AIDrawing** [comment]
+1

**Comment by RuntimeRacer** [comment]
Anyone figured what the solution to this is? I have a Workstation at home where textgen works fine; however on my Laptop with eGPU (3090) it would just refuse to run with exactly this error.
I even copied over the conda env from my workstation to it; and driver + local CUDA install uses same version. Something is heavily off..

```"D:\projects\Project Harmony.AI\text-generation-webui-harmony-ai\server.py" --listen-port 9000 --model SOLAR-10.7B-Instruct-v1.0-laser-exl2 --api --api-port 9001 --auto-devices 
11:07:03-289004 INFO     Starting Text generation web UI                       
11:07:03-301971 INFO     Loading "SOLAR-10.7B-Instruct-v1.0-laser-exl2"        
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ D:\projects\Project                                                         │
│ Harmony.AI\text-generation-webui-harmony-ai\server.py:241 in <module>       │
│                                                                             │
│   240         # Load the model                                              │
│ > 241         shared.model, shared.tokenizer = load_model(model_name)       │
│   242         if shared.args.lora:                                          │
│                                                                             │
│ D:\projects\Project                                                         │
│ Harmony.AI\text-generation-webui-harmony-ai\modules\models.py:87 in         │
│ load_model                                                                  │
│                                                                             │
│    86     shared.args.loader = loader                                       │
│ >  87     output = load_func_map[loader](model_name)                        │
│    88     if type(output) is tuple:                                         │
│                                                                             │
│ D:\projects\Project                                                         │
│ Harmony.AI\text-generation-webui-harmony-ai\modules\models.py:380 in        │
│ ExLlamav2_HF_loader                                                         │
│                                                                             │
│   379                                                                       │
│ > 380     return Exllamav2HF.from_pretrained(model_name)                    │
│   381                                                                       │
│                                                                             │
│ D:\projects\Project                                                         │
│ Harmony.AI\text-generation-webui-harmony-ai\modules\exllamav2_hf.py:170 in  │
│ from_pretrained                                                             │
│                                                                             │
│   169                                                                       │
│ > 170         return Exllamav2HF(config)                                    │
│   171                                                                       │
│                                                                             │
│ D:\projects\Project                                                         │
│ Harmony.AI\text-generation-webui-harmony-ai\modules\exllamav2_hf.py:44 in   │
│ __init__                                                                    │
│                                                                             │
│    43                                                                       │
│ >  44         self.ex_model.load(split)                                     │
│    45         self.generation_config = GenerationConfig()                   │
│                                                                             │
│                           ... 2 frames hidden ...                           │
│                                                                             │
│ C:\Users\Dominik\anaconda3\envs\textgen\Lib\site-packages\exllamav2\embeddi │
│ ng.py:22 in load                                                            │
│                                                                             │
│   21                                                                        │
│ > 22         w = self.load_weight()                                         │
│   23         assert isinstance(w, nn.Parameter)                             │
│                                                                             │
│ C:\Users\Dominik\anaconda3\envs\textgen\Lib\site-packages\exllamav2\module. │
│ py:116 in load_weight                                                       │
│                                                                             │
│   115             else:                                                     │
│ > 116                 tensors = self.load_multi(["weight"], override_key =  │
│   117                 tensor = tensors["weight"].half()                     │
│                                                                             │
│ C:\Users\Dominik\anaconda3\envs\textgen\Lib\site-packages\exllamav2\module. │
│ py:77 in load_multi                                                         │
│                                                                             │
│    76                 else:                                                 │
│ >  77                     tensors[k] = stfile.get_tensor(key + "." + k, dev │
│    78                                                                       │
│                                                                             │
│ C:\Users\Dominik\anaconda3\envs\textgen\Lib\site-packages\exllamav2\fastten │
│ sors.py:116 in get_tensor                                                   │
│                                                                             │
│   115         if not_fast or not self.fast:                                 │
│ > 116             f = self.get_cm(device)                                   │
│   117             # with safe_open(self.filename, framework = "pt", device  │
│                                                                             │
│ C:\Users\Dominik\anaconda3\envs\textgen\Lib\site-packages\exllamav2\fastten │
│ sors.py:107 in get_cm                                                       │
│                                                                             │
│   106                                                                       │
│ > 107         f = safe_open(self.filename, framework = "pt", device = devic │
│   108         f.__enter__()                                                 │
└─────────────────────────────────────────────────────────────────────────────┘
SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

Process finished with exit code 1```

**Comment by 4yu5h-crtl** [comment]
> Anyone figured what the solution to this is? I have a Workstation at home where textgen works fine; however on my Laptop with eGPU (3090) it would just refuse to run with exactly this error.
> I even copied over the conda env from my workstation to it; and driver + local CUDA install uses same version. Something is heavily off..
> 
> ```"D:\projects\Project Harmony.AI\text-generation-webui-harmony-ai\server.py" --listen-port 9000 --model SOLAR-10.7B-Instruct-v1.0-laser-exl2 --api --api-port 9001 --auto-devices 
> 11:07:03-289004 INFO     Starting Text generation web UI                       
> 11:07:03-301971 INFO     Loading "SOLAR-10.7B-Instruct-v1.0-laser-exl2"        
> ┌───────────────────── Traceback (most recent call last) ─────────────────────┐
> │ D:\projects\Project                                                         │
> │ Harmony.AI\text-generation-webui-harmony-ai\server.py:241 in <module>       │
> │                                                                             │
> │   240         # Load the model                                              │
> │ > 241         shared.model, shared.tokenizer = load_model(model_name)       │
> │   242         if shared.args.lora:                                          │
> │                                                                             │
> │ D:\projects\Project                                                         │
> │ Harmony.AI\text-generation-webui-harmony-ai\modules\models.py:87 in         │
> │ load_model                                                                  │
> │                                                                             │
> │    86     shared.args.loader = loader                                       │
> │ >  87     output = load_func_map[loader](model_name)                        │
> │    88     if type(output) is tuple:                                         │
> │                                                                             │
> │ D:\projects\Project                                                         │
> │ Harmony.AI\text-generation-webui-harmony-ai\modules\models.py:380 in        │
> │ ExLlamav2_HF_loader                                                         │
> │                                                                             │
> │   379                                                                       │
> │ > 380     return Exllamav2HF.from_pretrained(model_name)                    │
> │   381                                                                       │
> │                                                                             │
> │ D:\projects\Project                                                         │
> │ Harmony.AI\text-generation-webui-harmony-ai\modules\exllamav2_hf.py:170 in  │
> │ from_pretrained                                                             │
> │                                                                             │
> │   169                                                                       │
> │ > 170         return Exllamav2HF(config)                                    │
> │   171                                                                       │
> │                                                                             │
> │ D:\projects\Project                                                         │
> │ Harmony.AI\text-generation-webui-harmony-ai\modules\exllamav2_hf.py:44 in   │
> │ __init__                                                                    │
> │                                                                             │
> │    43                                                                       │
> │ >  44         self.ex_model.load(split)                                     │
> │    45         self.generation_config = GenerationConfig()                   │
> │                                                                             │
> │                           ... 2 frames hidden ...                           │
> │                                                                             │
> │ C:\Users\Dominik\anaconda3\envs\textgen\Lib\site-packages\exllamav2\embeddi │
> │ ng.py:22 in load                                                            │
> │                                                                             │
> │   21                                                                        │
> │ > 22         w = self.load_weight()                                         │
> │   23         assert isinstance(w, nn.Parameter)                             │
> │                                                                             │
> │ C:\Users\Dominik\anaconda3\envs\textgen\Lib\site-packages\exllamav2\module. │
> │ py:116 in load_weight                                                       │
> │                                                                             │
> │   115             else:                                                     │
> │ > 116                 tensors = self.load_multi(["weight"], override_key =  │
> │   117                 tensor = tensors["weight"].half()                     │
> │                                                                             │
> │ C:\Users\Dominik\anaconda3\envs\textgen\Lib\site-packages\exllamav2\module. │
> │ py:77 in load_multi                                                         │
> │                                                                             │
> │    76                 else:                                                 │
> │ >  77                     tensors[k] = stfile.get_tensor(key + "." + k, dev │
> │    78                                                                       │
> │                                                                             │
> │ C:\Users\Dominik\anaconda3\envs\textgen\Lib\site-packages\exllamav2\fastten │
> │ sors.py:116 in get_tensor                                                   │
> │                                                                             │
> │   115         if not_fast or not self.fast:                                 │
> │ > 116             f = self.get_cm(device)                                   │
> │   117             # with safe_open(self.filename, framework = "pt", device  │
> │                                                                             │
> │ C:\Users\Dominik\anaconda3\envs\textgen\Lib\site-packages\exllamav2\fastten │
> │ sors.py:107 in get_cm                                                       │
> │                                                                             │
> │   106                                                                       │
> │ > 107         f = safe_open(self.filename, framework = "pt", device = devic │
> │   108         f.__enter__()                                                 │
> └─────────────────────────────────────────────────────────────────────────────┘
> SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
> 
> Process finished with exit code 1
> ```

Well actually rather than solving the problem I found an alternative for running these on the local machine 😅. It's with the help of a software called LM Studio you can run whichever model you want there it works fine for me when my own configuration is i7 6th gen with nvidia t400

**Comment by RuntimeRacer** [comment]
Ok well, I think it's probably something really weird with OS Dependency environment or smth., but I'll check LM-Studio, too, thanks
