### ISSUE TITLE
Cannot load the LLama 2 13B chat GPTQ

### ISSUE THREAD

**Issue by mistrjirka** [oobabooga/text-generation-webui#5021]
### Describe the bug

I tried to load the model https://huggingface.co/TheBloke/Llama-2-13B-chat-GPTQ (the example in model documentation). It fails quitely and without any errors the program just shutdowns. I do not know how to even start debugging this.
I also tried the https://huggingface.co/lmsys/vicuna-7b-v1.5 (example in model documentation) and I am able to run it on CPU with and withou quantization but on GPU the memory runs out without quantization and with quantization This appears: Warning: "The installed version of bitsandbytes was compiled without GPU support.", the model then just freezes and does not load. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load the model https://huggingface.co/TheBloke/Llama-2-13B-chat-GPTQ

### Screenshot

![Snímek obrazovky pořízený 2023-12-20 18-31-02](https://github.com/oobabooga/text-generation-webui/assets/32205472/2ef24d8b-8ef3-4467-8967-6159feed83a7)

### Logs

```shell
18:22:08-484106 INFO     Starting Text generation web UI                        
18:22:08-486854 INFO     Loading the extension "gallery"                        
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
18:22:41-901677 INFO     Loading TheBloke_Llama-2-13B-chat-GPTQ 

Then the program ends I have not found any other log
```

### System Info

```shell
Manjaro kernel 6.6.7
bitsandbytes==0.41.3
Ryzen 7 5800X 
64GB RAM
RX 7800XT 16GB
I installed rocm and enabled the rocm in the one_click.py acording to the documentation.
```

**Comment by lufixSch** [comment]
`bitsandbytes` has no ROCm support by default. Did you install a version that supports ROCm manually?

If not, `bitsandbytes==0.38.1` needs to be installed to ensure that the WebUI starts without errors (`bitsandbytes` still wont be usable)

As for the GPTQ loader: What loader are you using? AutoGPTQ, Exllama, Exllamav2 ...
Could you check your GPU usage (and VRAM) while loading the model. For example with `nvtop`?

**Comment by lufixSch** [comment]
Maybe this is the same issue as in #5076

**Comment by mistrjirka** [comment]
> `bitsandbytes` has no ROCm support by default. Did you install a version that supports ROCm manually?
> 
> If not, `bitsandbytes==0.38.1` needs to be installed to ensure that the WebUI starts without errors (`bitsandbytes` still wont be usable)
> 
> As for the GPTQ loader: What loader are you using? AutoGPTQ, Exllama, Exllamav2 ... Could you check your GPU usage (and VRAM) while loading the model. For example with `nvtop`?

Thank you for your response. I will try it when I am able to and inform you if that works.

**Comment by mistrjirka** [comment]
> `bitsandbytes` has no ROCm support by default. Did you install a version that supports ROCm manually?
> 
> If not, `bitsandbytes==0.38.1` needs to be installed to ensure that the WebUI starts without errors (`bitsandbytes` still wont be usable)
> 
> As for the GPTQ loader: What loader are you using? AutoGPTQ, Exllama, Exllamav2 ... Could you check your GPU usage (and VRAM) while loading the model. For example with `nvtop`?

Yeah, when the bitsandbytes is 0.38.1 it crashes on ValueError: 4-bit quantization requires bitsandbytes>=0.39.0 - please upgrade your bitsandbytes version. When I do that (for example 0.39.0) a similar issue occurs:
`serWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/jirka/programy/llama/text-generation-webui/installer_files/env/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
` and then it is just stuck doing nothing (graphics pipeline doing also nothing)
. The loader of GPTQ was ExLlama_HF. AUTOGPTQ times out but loads memory to up to 8GB and displays this:
`
To create a public link, set `share=True` in `launch()`.
19:38:35-372241 INFO     Loading TheBloke_Llama-2-13B-chat-GPTQ                                             
19:38:35-752185 INFO     The AutoGPTQ params are: {'model_basename': 'model', 'device': 'cuda:0',           
                         'use_triton': False, 'inject_fused_attention': True, 'inject_fused_mlp': True,     
                         'use_safetensors': True, 'trust_remote_code': False, 'max_memory': None,           
                         'quantize_config': None, 'use_cuda_fp16': True, 'disable_exllama': False,          
                         'disable_exllamav2': False}                                                        
[jirka@jiri-pc text-generation-webui]$ 
`
"GPTQ for llama" loads with these errors and then crashes on chat. 
`To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/home/jirka/programy/llama/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jirka/programy/llama/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jirka/programy/llama/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jirka/programy/llama/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jirka/programy/llama/text-generation-webui/installer_files/env/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jirka/programy/llama/text-generation-webui/installer_files/env/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/jirka/programy/llama/text-generation-webui/installer_files/env/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jirka/programy/llama/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/home/jirka/programy/llama/text-generation-webui/modules/models_settings.py", line 201, in update_model_parameters
    value = int(value)
            ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
19:46:21-084732 INFO     Loading TheBloke_Llama-2-13B-chat-GPTQ                                             
19:46:21-092090 INFO     Found the following quantized model:                                               
                         models/TheBloke_Llama-2-13B-chat-GPTQ/model.safetensors                            
19:46:26-338498 INFO     LOADER: GPTQ-for-LLaMa                                                             
19:46:26-339213 INFO     TRUNCATION LENGTH: 4096                                                            
19:46:26-339640 INFO     INSTRUCTION TEMPLATE: Llama-v2                                                     
19:46:26-340037 INFO     Loaded the model in 5.25 seconds.                                                  
19:46:49-361200 INFO     Deleted logs/chat/Assistant/20231220-17-29-39.json.   `
When the GPTQ-for-llama has set parameters wbits 4 groupsize 128 modeltype llama it loads without errors but on chat it tries to respond and then silently crashes.

**Comment by lufixSch** [comment]
Okay lets go through this step by step.

### Transformer
Okay first you wont be able to load *https://huggingface.co/lmsys/vicuna-7b-v1.5* or any other model with transformer and quantization as there is no `bitsandbytes` version with ROCm support.

As I said before:
> bitsandbytes==0.38.1 needs to be installed to ensure that the WebUI starts without errors (bitsandbytes still wont be usable)

### GPTQ for LLama, AutoGPTQ

GPTQ for llama as well as AutoGPTQ require you to specify wbits and groupsize otherwise they wont work. Apart from that I would try to avoid them as they are old, not really maintained anymore and have bad ROCm support.

### Exllama, ExllamaV2

ExllamaV2 is the fastest loader for GPTQ and the only one under active development (e.g. support for newest models and so on). It also has native ROCm support. Try this instead of exllama.

If this does not work out of the box try installing the prebuild wheels or building it from source as described in this comment https://github.com/oobabooga/text-generation-webui/issues/3759#issuecomment-1875775481

> `You are running ExLlamaV2 without flash-attention`

This error is expected as there is no `flash-attention` support for ROCm at the moment. You can ignore that.

### llama.cpp

If you are not bound to using GPTQ models try GGUF with `llama.cpp`. From my experience this one always works on AMD.

All in all I'm really unsure what is causing the problems as every loader just crashes without any feedback. It really looks like there is something wrong with your drivers or ROCm install. Trying llama.cpp and exllamav2 could give us more information.
Some other information that could help:
- How did you install ROCm?
- what is the output of `rocminfo`?
- gpu usage during the process (loading a model, generating text.) There is an issue with 7xxx GPUs in ROCm which produces 100% GPU usage in idle (While/After loading a model). Which can also cause crashes similar to what you are experiencing.

**Comment by mistrjirka** [comment]
> Okay lets go through this step by step.
> ### Transformer
> 
> Okay first you wont be able to load _https://huggingface.co/lmsys/vicuna-7b-v1.5_ or any other model with transformer and quantization as there is no `bitsandbytes` version with ROCm support.
> 
> As I said before:
> 
> > bitsandbytes==0.38.1 needs to be installed to ensure that the WebUI starts without errors (bitsandbytes still wont be usable)
> 
> ### GPTQ for LLama, AutoGPTQ
> 
> GPTQ for llama as well as AutoGPTQ require you to specify wbits and groupsize otherwise they wont work. Apart from that I would try to avoid them as they are old, not really maintained anymore and have bad ROCm support.
> ### Exllama, ExllamaV2
> 
> ExllamaV2 is the fastest loader for GPTQ and the only one under active development (e.g. support for newest models and so on). It also has native ROCm support. Try this instead of exllama.
> 
> If this does not work out of the box try installing the prebuild wheels or building it from source as described in this comment [#3759 (comment)](https://github.com/oobabooga/text-generation-webui/issues/3759#issuecomment-1875775481)
> 
> > `You are running ExLlamaV2 without flash-attention`
> 
> This error is expected as there is no `flash-attention` support for ROCm at the moment. You can ignore that.
> ### llama.cpp
> 
> If you are not bound to using GPTQ models try GGUF with `llama.cpp`. From my experience this one always works on AMD.
> 
> All in all I'm unsure what is causing the problems as every loader just crashes without any feedback. It looks like there is something wrong with your drivers or ROCm install. Trying llama.cpp and exllamav2 could give us more information. Some other information that could help:
> 
>     * How did you install ROCm?
> 
>     * what is the output of `rocminfo`?
> 
>     * gpu usage during the process (loading a model, generating text.) There is an issue with 7xxx GPUs in ROCm which produces 100% GPU usage in idle (While/After loading a model). Which can also cause crashes similar to what you are experiencing.

I did try the vicuna-7b-v1.5 and it silently fails a few minutes after successfully loading checkpoint shards log output:
![Snímek obrazovky pořízený 2024-01-03 20-39-32](https://github.com/oobabooga/text-generation-webui/assets/32205472/4393c504-f1e7-44ef-8780-b9d1b2215389)
I tried the llama.cpp and it failed in very similar way: 
![Snímek obrazovky pořízený 2024-01-03 21-11-22](https://github.com/oobabooga/text-generation-webui/assets/32205472/33567db3-6584-4b5b-bb8e-ecb7f4df4d81)
I will try the EXLLAMA V2 tomorrow.
### ROCM
I installed ROCM on my Manjaro desktop using this tutorial: https://github.com/rocm-arch/rocm-arch
ROCMinfo has some bugged links but after running /opt/rocm/bin/rocminfo. It seems to work but I do not know how to properly test that it actually works
I got: 
`ROCk module is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
Mwaitx:                  DISABLED
DMAbuf Support:          YES

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD Ryzen 7 5800X 8-Core Processor 
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD Ryzen 7 5800X 8-Core Processor 
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   3800                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            16                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    65767952(0x3eb8a10) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    65767952(0x3eb8a10) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    65767952(0x3eb8a10) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    gfx1101                            
  Uuid:                    GPU-515cfec24fa840ed               
  Marketing Name:          AMD Radeon RX 7800 XT              
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      32(0x20) KB                        
    L2:                      4096(0x1000) KB                    
    L3:                      65536(0x10000) KB                  
  Chip ID:                 29822(0x747e)                      
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   2124                               
  BDFID:                   10240                              
  Internal Node ID:        1                                  
  Compute Unit:            60                                 
  SIMDs per CU:            2                                  
  Shader Engines:          3                                  
  Shader Arrs. per Eng.:   2                                  
  WatchPts on Addr. Ranges:4                                  
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          32(0x20)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    1024(0x400)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 528                                
  SDMA engine uCode::      20                                 
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    16760832(0xffc000) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS:                     
      Size:                    16760832(0xffc000) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx1101         
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done *** `

**Comment by liammcdermott** [comment]
I have a similar setup, with a discrete card and another GPU integrated with the CPU. Apologies if you have already tried this, but what worked for me is ensuring the integrated GPU doesn't receive any RoCM workload.

The way I found to do this: under the Model tab there's a field called `tensor_split`. I set that to `1,0`. Though depending on the order Linux happens to have loaded the GPUs, `0,1` might work better for you.

![Screenshot_20240113_140231](https://github.com/oobabooga/text-generation-webui/assets/5082004/28c47bd5-5f62-44c4-bd53-d39c77fc2131)

You may also want to check into how that field actually works as -- while `1,0` works for me -- I have no idea if my setting is optimal. Maybe `100,0` might work better, or worse? I don't know.

**Comment by mistrjirka** [comment]
> I have a similar setup, with a discrete card and another GPU integrated with the CPU. Apologies if you have already tried this, but what worked for me is ensuring the integrated GPU doesn't receive any RoCM workload.
> 
> The way I found to do this: under the Model tab there's a field called `tensor_split`. I set that to `1,0`. Though depending on the order Linux happens to have loaded the GPUs, `0,1` might work better for you.
> 
> ![Screenshot_20240113_140231](https://private-user-images.githubusercontent.com/5082004/296510493-28c47bd5-5f62-44c4-bd53-d39c77fc2131.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNDA1NjEsIm5iZiI6MTcwNTI0MDI2MSwicGF0aCI6Ii81MDgyMDA0LzI5NjUxMDQ5My0yOGM0N2JkNS01ZjYyLTQ0YzQtYmQ1My1kMzljNzdmYzIxMzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTRUMTM1MTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjgzZjVlZTRmMDVkNzU3MTIwYjMyZGQ1Yzk4OWY1N2FmZGExM2FkMmM2ZTRiZjc5NDZjZGEyYzE2ZDgyY2RmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TuFIVDZ5yYbzvGp45gp1N_eS_4W8jNYECmfCzsfVyhA)
> 
> You may also want to check into how that field actually works as -- while `1,0` works for me -- I have no idea if my setting is optimal. Maybe `100,0` might work better, or worse? I don't know.

Hi, Thank you for answer I will try this. I do not have any integrated GPU so that might not be a problem, but I will try it anyway. I think that I will reinstall my system because it went through multiple very very different GPUs and setups so something deep down might be f**ked. Sadly I will have time for this in about a month.

**Comment by lufixSch** [comment]
@mistrjirka I just looked again at your output of llama.cpp and saw this minor detail:

> Device 0: AMD Radeon 7800 XT, compute capability 10.3

Did you set `HSA_OVERRIDE_GFX_VERSION=10.3.0`? This should be matching the gfx version of your GPU and is not needed at all for 7xxx GPUs as they are natively supported by ROCm.

**Comment by lufixSch** [comment]
@liammcdermott Yes this is a common issue as ROCm does not support iGPUs at all. The ROCm documentation even suggests to deactivate the iGPU in your BIOS (but if it works for you without doing so even better)

I found the best way to check which GPU has which ID is, by using `nvtop`. `rocm-smi` doesn't seem to give me the right order for my GPUs. Did you by chance find a better way?

You could also try `CUDA_VISIBLE_DEVICES=1` or `HIP_VISIBLE_DEVICES=1` as environment variable (don't be confused by *cuda* in the variable name it's just an alias for compatibility). They both change which devices (and in which order) are visible to tools using ROCm.
The ROCm documentation suggests that this will not work but its worth a try as `tensor_split` does the exact same thing.

**Comment by mistrjirka** [comment]
I manged to kinda solve it. Thank you for the answer. The HSA_OVERRIDE_GFX_VERSION was not set. But the value is not supposed to be 10.3 but 11.0.0. So if you have this problem set it to 11.0.0. But the problem with bitsandbytes still remains and I think it could be solved by changing the requirments file for amd gpu. 

> @mistrjirka I just looked again at your output of llama.cpp and saw this minor detail:
> 
> > Device 0: AMD Radeon 7800 XT, compute capability 10.3
> 
> Did you set `HSA_OVERRIDE_GFX_VERSION=10.3.0`? This should be matching the gfx version of your GPU and is not needed at all for 7xxx GPUs as they are natively supported by ROCm.

**Comment by lufixSch** [comment]
@mistrjirka I think you misunderstood me. But you still came to the right conclusion :)

Just to make this clear again:

> Device 0: AMD Radeon 7800 XT, compute capability 10.3

This llama.cpp output from you suggests that llama cpp detects your device as gfx1030 which is, as you found out yourself, the wrong version. By setting `HSA_OVERRIDE_GFX_VERSION=11.0.0` you enforce the right version (gfx1100) but setting this environment variable should **not** be necessary at all for the 7800 XT. Llama.cpp should detect gfx1100 automatically.
That's why I thought, you might have set `HSA_OVERRIDE_GFX_VERSION=10.3.0` somewhere in your environment. Even though you found a workaround I would try too find out where this is coming from because this could also mess with other GPU/ML related tasks, programs and so on.

> But the problem with bitsandbytes still remains and I think it could be solved by changing the requirments file for amd gpu.

I'm not sure I understand what you mean. What could be changed to fix this?

**Comment by mistrjirka** [comment]
> @mistrjirka I think you misunderstood me. But you still came to the right conclusion :)
> 
> Just to make this clear again:
> 
> > Device 0: AMD Radeon 7800 XT, compute capability 10.3
> 
> This llama.cpp output from you suggests that llama cpp detects your device as gfx1030 which is, as you found out yourself, the wrong version. By setting `HSA_OVERRIDE_GFX_VERSION=11.0.0` you enforce the right version (gfx1100) but setting this environment variable should **not** be necessary at all for the 7800 XT. Llama.cpp should detect gfx1100 automatically. That's why I thought, you might have set `HSA_OVERRIDE_GFX_VERSION=10.3.0` somewhere in your environment. Even though you found a workaround I would try too find out where this is coming from because this could also mess with other GPU/ML related tasks, programs and so on.
> 
> > But the problem with bitsandbytes still remains and I think it could be solved by changing the requirments file for amd gpu.
> 
> I'm not sure I understand what you mean. What could be changed to fix this?

Ok, so the current state now is that most of the GPU acceleration now works but what does not work is the quantization. That is because it is done by bitsandbytes which does not support ROCm, I tried the ROCm test branch but it does not seem to work (it throws some random error if that would be useful I can find it). I think that until the bits and bytes library does not support ROCm I won't be able to get the quantization working. Or am I wrong?

**Comment by lufixSch** [comment]
I really haven't tried Bitsandbytes for a long time but there is a link (and install command) to a version which someone claimed they got running in #3759.

> I think that until the bits and bytes library does not support ROCm I won't be able to get the quantization working

If you mean loading for example fp16 models with the Huggingface transformer library in 4 or 8 bit then no this will only work with bitsandbytes.

But if you only want to run models there are other far better quantizations (gguf, exl2, gptq ...). They are usually smaller, faster and higher quality than using bitsandbytes.
