### ISSUE TITLE
Autogptq text generation

### ISSUE THREAD

**Issue by jesulo** [oobabooga/text-generation-webui#5032]
Hi, I would like to know in which code file the text generation of the autogptq model is being done.

Regards

**Comment by Ph0rk0z** [comment]
https://github.com/oobabooga/text-generation-webui/blob/main/modules/AutoGPTQ_loader.py

**Comment by jesulo** [comment]
There just load model, where use model.generate or pipeline for autogptq model?

**Comment by Ph0rk0z** [comment]
It uses all one pipeline for the most part, that the model/tokenizer is passed to.

**Comment by jesulo** [comment]
I have issue intalling autogpt in rhel 8 ppc64le...
in docker.
pip3 install auto-gptq --extra-index-url https://huggingface.github.io/autogptq-index/whl/cu118/

error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [19 lines of output]
python: can't open file '/tmp/pip-install-mq0hh9__/auto-gptq_ad9386319bae45eea27a8ef6f79b46f3/./autogptq_extension/qigen/generate.py': [Errno 2] No such file or directory
Traceback (most recent call last):
File "/tmp/pip-install-mq0hh9__/auto-gptq_ad9386319bae45eea27a8ef6f79b46f3/setup.py", line 109, in
subprocess.check_output(["python", "./autogptq_extension/qigen/generate.py", "--module", "--search", "--p", str(p)])
File "/opt/anaconda/envs/vicuna/lib/python3.9/subprocess.py", line 424, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "/opt/anaconda/envs/vicuna/lib/python3.9/subprocess.py", line 528, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', './autogptq_extension/qigen/generate.py', '--module', '--search', '--p', '160']' returned non-zero exit status 2.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/tmp/pip-install-mq0hh9__/auto-gptq_ad9386319bae45eea27a8ef6f79b46f3/setup.py", line 111, in <module>
      raise Exception(f"Generating QiGen kernels failed with the error shown above.")
  Exception: Generating QiGen kernels failed with the error shown above.
  Generating qigen kernels...
  [end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers.git /tmp/pip-req-build-89lnfo0w

**Comment by Ph0rk0z** [comment]
Makes sense that CPU module for autogptq fails on PPC system. I think that's what the qigen is.. i would comment it out from building.

**Comment by jesulo** [comment]
How can I do that?

**Comment by Ph0rk0z** [comment]
You would edit autogptq source, start where it fails, line 111 in setup.py.. 

I don't use docker and I bare metal it so no clue on how to fix it there.

**Comment by jesulo** [comment]
need comment  subprocess.check_output ?

if BUILD_CUDA_EXT:
    from torch.utils import cpp_extension
       
    if platform.system() != "Windows" and platform.machine() != "aarch64" and not DISABLE_QIGEN:
        print("Generating qigen kernels...")
        cores_info = subprocess.run("cat /proc/cpuinfo | grep cores | head -1", shell=True, check=True, text=True, stdout=subprocess.PIPE).stdout.split(" ")
        if (len(cores_info) == 3 and cores_info[1].startswith("cores")) or (len(cores_info) == 2):
            p = int(cores_info[-1])
        else:
            p = os.cpu_count()
        try:
            subprocess.check_output(["python", "./autogptq_extension/qigen/generate.py", "--module", "--search", "--p", str(p)])
        except subprocess.CalledProcessError as e:
            raise Exception(f"Generating QiGen kernels failed with the error shown above.")

**Comment by Ph0rk0z** [comment]
Probably want to pass it DISABLE_QIGEN

**Comment by jesulo** [comment]
Thanks you, now I have.. 
Cloning into 'AutoGPTQ'...
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      <jemalloc>: Unsupported system page size
      g++: error: unrecognized command line option ‘-mavx’; did you mean ‘-mads’?
      g++: error: unrecognized command line option ‘-mfma’; did you mean ‘-memb’?
      g++: error: unrecognized command line option ‘-mavx2’
      g++: error: unrecognized command line option ‘-march=native’; did you mean ‘-mcpu=native’?
      Traceback (most recent call last):
        File "/FastChat/AutoGPTQ/./autogptq_extension/qigen/generate.py", line 1475, in <module>
          gen_module_search(args.r, args.p, [2,3,4])
        File "/FastChat/AutoGPTQ/./autogptq_extension/qigen/generate.py", line 1418, in gen_module_search
          gen_and_compile(n,m,t,n,mb,tb,1,mu,tu,p,u,bits=bits, gs=gs, module=True)
        File "/FastChat/AutoGPTQ/./autogptq_extension/qigen/generate.py", line 799, in gen_and_compile
          subprocess.check_output(["g++", "-O3", "-o", "./autogptq_extension/qigen/mmm", "./autogptq_extension/qigen/mmm.cpp", "-mavx", "-mfma", "-mavx2", "-ftree-vectorize", "-fno-signaling-nans", "-fno-trapping-math", "-march=native", "-fopenmp"])
        File "/opt/anaconda/envs/vicuna/lib/python3.9/subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/opt/anaconda/envs/vicuna/lib/python3.9/subprocess.py", line 528, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['g++', '-O3', '-o', './autogptq_extension/qigen/mmm', './autogptq_extension/qigen/mmm.cpp', '-mavx', '-mfma', '-mavx2', '-ftree-vectorize', '-fno-signaling-nans', '-fno-trapping-math', '-march=native', '-fopenmp']' returned non-zero exit status 1.
      Traceback (most recent call last):
        File "/FastChat/AutoGPTQ/setup.py", line 109, in <module>
          subprocess.check_output(["python", "./autogptq_extension/qigen/generate.py", "--module", "--search", "--p", str(p)])
        File "/opt/anaconda/envs/vicuna/lib/python3.9/subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/opt/anaconda/envs/vicuna/lib/python3.9/subprocess.py", line 528, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['python', './autogptq_extension/qigen/generate.py', '--module', '--search', '--p', '160']' returned non-zero exit status 1.

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/FastChat/AutoGPTQ/setup.py", line 111, in <module>
          raise Exception(f"Generating QiGen kernels failed with the error shown above.")
      Exception: Generating QiGen kernels failed with the error shown above.
      Generating qigen kernels...
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by Ph0rk0z** [comment]
Heh.. if it doesn't play nice I guess you will have to edit setup.py further so it doesn't try to compile Qigen kernels at all. Last time I did this it broke for me on x86 and I had to do the same.

can be as simple as DISABLE_QIGEN = 1 instead of DISABLE_QIGEN = int(os.environ.get('DISABLE_QIGEN', '0')) == 1

if not just comment all the QIgen stuff out, it's only blocks where it compiles the ccp_ext

**Comment by jesulo** [comment]
DISABLE_QIGEN solve my issue, thanks @Ph0rk0z

**Comment by AminDar** [comment]
I tried also the following commend but got the same error:

DISABLE_QIGEN=1 pip install auto-gptq --no-build-isolation

```

error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      python: can't open file '/tmp/pip-install-rxprqurt/auto-gptq_e9b0609e064d4da59c2f3f85a3fa3376/./autogptq_extension/qigen/generate.py': [Errno 2] No such file or directory
      Traceback (most recent call last):
        File "/tmp/pip-install-rxprqurt/auto-gptq_e9b0609e064d4da59c2f3f85a3fa3376/setup.py", line 109, in <module>
          subprocess.check_output(["python", "./autogptq_extension/qigen/generate.py", "--module", "--search", "--p", str(p)])
        File "/home/**/anaconda3/envs/llms/lib/python3.12/subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/**/anaconda3/envs/llms/lib/python3.12/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['python', './autogptq_extension/qigen/generate.py', '--module', '--search', '--p', '4']' returned non-zero exit status 2.
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-rxprqurt/auto-gptq_e9b0609e064d4da59c2f3f85a3fa3376/setup.py", line 111, in <module>
          raise Exception(f"Generating QiGen kernels failed with the error shown above.")
      Exception: Generating QiGen kernels failed with the error shown above.
      Generating qigen kernels...
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

```


```

torch-cuda versions:


torch.cuda.is_available()
True

 torch.__version__
'2.2.1'

torch._C._cuda_getCompiledVersion()
12010


```
