### ISSUE TITLE
auto AWQ device

### ISSUE THREAD

**Issue by kalle07** [oobabooga/text-generation-webui#5053]
### Describe the bug

since last 2 weeks i made an update most AWQ run ok

now i get an error on all AWQs

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

-

### Logs

```shell
2:12:58-169818 INFO     Loading TheBloke_dragon-mistral-7B-v0-AWQ
Replacing layers...: 100%|█████████████████████████████████████████████████████████████| 32/32 [00:04<00:00,  7.66it/s]
Fusing layers...: 100%|████████████████████████████████████████████████████████████████| 32/32 [00:00<00:00, 93.57it/s]
22:13:05-570985 INFO     Replaced attention with xformers_attention
22:13:05-570985 INFO     LOADER: AutoAWQ
22:13:05-570985 INFO     TRUNCATION LENGTH: 32768
22:13:05-570985 INFO     INSTRUCTION TEMPLATE: Alpaca
22:13:05-577490 INFO     Loaded the model in 7.41 seconds.
e:\text-generation-webui\installer_files\env\lib\site-packages\transformers\generation\utils.py:1636: UserWarning: You are calling .generate() with the `input_ids` being on a device type different than your model's device. `input_ids` is on cpu, whereas the model is on cuda. You may experience unexpected behaviors or slower generation. Please make sure that you have put `input_ids` to the correct device by calling for example input_ids = input_ids.to('cuda') before running `.generate()`.
  warnings.warn(
Traceback (most recent call last):
  File "e:\text-generation-webui\modules\text_generation.py", line 343, in generate_reply_HF
    output = shared.model.generate(**generate_params)[0]
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\awq\models\base.py", line 41, in generate
    return self.model.generate(*args, **kwargs)
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1764, in generate
    return self.sample(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 2861, in sample
    outputs = self(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\transformers\models\mistral\modeling_mistral.py", line 1053, in forward
    outputs = self.model(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\awq\modules\fused\model.py", line 31, in forward
    h = self.embedding(input_ids)
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\torch\nn\modules\sparse.py", line 162, in forward
    return F.embedding(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\torch\nn\functional.py", line 2233, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)
Output generated in 0.31 seconds (0.00 tokens/s, 0 tokens, context 110, seed 1581121223)
```

### System Info

```shell
Win10
RTX 4060
```

**Comment by yhyu13** [comment]
Try update to latest autoawq, and not using xformer int he same time?

**Comment by kalle07** [comment]
thy ;) 
but why not in big letters "dont work with xformers" if you use AWQ    :D

**Comment by kalle07** [comment]
updated all .. some models still not work.

error:

14:29:11-486448 WARNING  Auto-assiging --gpu-memory 15 for your GPU to try to prevent out-of-memory errors. You can
                         manually set other values.
14:29:11-486448 ERROR    Failed to load the model.
Traceback (most recent call last):
  File "e:\text-generation-webui\modules\ui_model_menu.py", line 214, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
  File "e:\text-generation-webui\modules\models.py", line 90, in load_model
    output = load_func_map[loader](model_name)
  File "e:\text-generation-webui\modules\models.py", line 321, in AutoAWQ_loader
    model = AutoAWQForCausalLM.from_quantized(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\awq\models\auto.py", line 52, in from_quantized
    return AWQ_CAUSAL_LM_MODEL_MAP[model_type].from_quantized(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\awq\models\base.py", line 154, in from_quantized
    model_weights_path, config, quant_config = self._load_config(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\awq\models\base.py", line 206, in _load_config
    quant_config = AwqConfig.from_pretrained(model_path)
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\awq\models\_config.py", line 68, in from_pretrained
    quant_config = cls(**loaded_config)
TypeError: AwqConfig.__init__() got an unexpected keyword argument 'modules_to_not_convert'


WHY please WHY AWQ is such as unstable and GGUF and GPTQ works  ???
