### ISSUE TITLE
AttributeError: module 'modules.chat' has no attribute 'get_turn_substrings'

### ISSUE THREAD

**Issue by phr00t** [oobabooga/text-generation-webui#5072]
### Describe the bug

I loaded a 10.7 SOLAR model with llama.cpp. I had it all running on my 8GB RTX 3080 using the "tensorcores" checkbox.

I asked the model "I have 4 apples today. I ate 3 apples yesterday, but none today. How many apples do I have today?"

It responded something kinda dumb, like "Since you have 4 apples today and you ate 3 apples yesterday, you still have the remaining 1 apple from yesterday. Therefore, adding today's 4 apples and the remaining 1 apple, you have a total of 4 + 1 = 5 apples today."

However, when the response finished, I got a crash in the logs section.

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

See "describe the bug", which includes steps I took to get the error.

### Logs

```shell
llama_print_timings:        load time =   25133.96 ms
llama_print_timings:      sample time =       2.06 ms /    63 runs   (    0.03 ms per token, 30508.47 tokens per second)
llama_print_timings: prompt eval time =   25133.85 ms /    83 tokens (  302.82 ms per token,     3.30 tokens per second)
llama_print_timings:        eval time =    3455.74 ms /    62 runs   (   55.74 ms per token,    17.94 tokens per second)
llama_print_timings:       total time =   28760.33 ms
Output generated in 29.50 seconds (2.10 tokens/s, 62 tokens, context 83, seed 1180510178)
Traceback (most recent call last):
  File "D:\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "D:\text-generation-webui-main\modules\chat.py", line 364, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True, for_ui=True)):
  File "D:\text-generation-webui-main\modules\chat.py", line 332, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message, for_ui=for_ui):
  File "D:\text-generation-webui-main\modules\chat.py", line 275, in chatbot_wrapper
    for j, reply in enumerate(generate_reply(prompt, state, stopping_strings=stopping_strings, is_chat=True, for_ui=for_ui)):
  File "D:\text-generation-webui-main\modules\text_generation.py", line 31, in generate_reply
    for result in _generate_reply(*args, **kwargs):
  File "D:\text-generation-webui-main\modules\text_generation.py", line 81, in _generate_reply
    for reply in generate_func(question, original_question, seed, state, stopping_strings, is_chat=is_chat):
  File "D:\text-generation-webui-main\extensions\llm_web_search\script.py", line 311, in custom_generate_reply
    substring_dict = chat.get_turn_substrings(state, instruct=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'modules.chat' has no attribute 'get_turn_substrings'
```

### System Info

```shell
Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz   2.21 GHz
NVIDIA RTX 3080 8GB
Windows 10 x64
```

**Comment by phr00t** [comment]
Oh snap this is an LLM Web Search error, my bad!
