### ISSUE TITLE
SuperboogaV2 

### ISSUE THREAD

**Issue by sidewaysthought** [oobabooga/text-generation-webui#5090]
### Describe the bug

With a fresh install after installing superboogav2's requirements.txt, starting TGWUI produces an error indicating that superboogav2 needs to use either a new library, or use an older version of a library.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Perform a fresh one-click install of TGWUI
On Windows, launch cmd_windows.bat
Change to the extensions/superboogav2 
Enter ```pip install -r requirements.txt```
Type exit to leave conda.
Launch using start_windows.bat

### Logs

```shell
20:27:11-680836 ERROR    Failed to load the extension "superboogav2".
Traceback (most recent call last):
  File "D:\AI\text-generation-webui-main\modules\extensions.py", line 37, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "D:\AI\text-generation-webui-main\extensions\superboogav2\script.py", line 20, in <module>
    from .chromadb import make_collector
  File "D:\AI\text-generation-webui-main\extensions\superboogav2\chromadb.py", line 2, in <module>
    import chromadb
  File "D:\AI\text-generation-webui-main\installer_files\env\Lib\site-packages\chromadb\__init__.py", line 1, in <module>
    import chromadb.config
  File "D:\AI\text-generation-webui-main\installer_files\env\Lib\site-packages\chromadb\config.py", line 1, in <module>
    from pydantic import BaseSettings
  File "D:\AI\text-generation-webui-main\installer_files\env\Lib\site-packages\pydantic\__init__.py", line 363, in __getattr__
    return _getattr_migration(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\text-generation-webui-main\installer_files\env\Lib\site-packages\pydantic\_migration.py", line 296, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.5/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.5/u/import-error
```

### System Info

```shell
Windows 11 Pro x64, RTX 3060TI
```

**Comment by shamio** [comment]
Please refer to this issue that i had a been solved here https://github.com/oobabooga/text-generation-webui/issues/5063#issuecomment-1869165951. Maybe it fixes your issue too.

**Comment by sidewaysthought** [comment]
I checked and it looks like two distinct things, but it looks like oobabooga found a duplicate issue which directly addresses what I submitted. Thank you!

________________________________
