### ISSUE TITLE
Textgen with Langchain issue

### ISSUE THREAD

**Issue by seyi33** [oobabooga/text-generation-webui#5096]
### Describe the bug

I was trying to test the use of text-gen with langchain, as described in tha langchain docs, but im getting this error
" raise WebSocketBadStatusException(
websocket._exceptions.WebSocketBadStatusException: Handshake status 403 Forbidden -+-+- {'date': 'Wed, 27 Dec 2023 10:13:15 GMT', 'content-length': '0', 'content-type': 'text/plain', 'connection': 'close'} -+-+- b''"

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
from langchain.chains import LLMChain
from langchain.globals import set_debug
# from langchain.llms import TextGen
from langchain_community.llms import TextGen
from langchain.prompts import PromptTemplate

set_debug(True)
model_url = "ws://localhost:5000/v1"

template = """Question: {question}

Answer: Let's think step by step."""

prompt = PromptTemplate(template=template, input_variables=["question"])
llm = TextGen(
    model_url=model_url, streaming=True, callbacks=[StreamingStdOutCallbackHandler()]
)
llm_chain = LLMChain(prompt=prompt, llm=llm)
question = "What NFL team won the Super Bowl in the year Justin Bieber was born?"

llm_chain.run(question)

llm = TextGen(model_url=model_url, streaming=True)
for chunk in llm.stream("Ask 'Hi, how are you?' like a pirate:'", stop=["'", "\n"]):
    print(chunk, end="", flush=True)

### Logs

```shell
[chain/start] [1:chain:LLMChain] Entering Chain run with input:
{
  "question": "What NFL team won the Super Bowl in the year Justin Bieber was born?"
}
[llm/start] [1:chain:LLMChain > 2:llm:TextGen] Entering LLM run with input:
{
  "prompts": [
    "Question: What NFL team won the Super Bowl in the year Justin Bieber was born?\n\nAnswer: Let's think step by step."
  ]
}
[llm/error] [1:chain:LLMChain > 2:llm:TextGen] [2.10s] LLM run errored with error:
"WebSocketBadStatusException(\"Handshake status 403 Forbidden -+-+- {'date': 'Wed, 27 Dec 2023 10:13:55 GMT', 'content-length': '0', 'content-type': 'text/plain', 'connection': 'close'} -+-+- b''\")Traceback (most recent call last):\n\n\n  
File \"C:\\PYTHON_PROJECTS\\AUTOGEN_MATHCHAT\\autogenvenv\\Lib\\site-packages\\langchain_core\\language_models\\llms.py\", line 540, in _generate_helper\n    self._generate(\n\n\n  File \"C:\\PYTHON_PROJECTS\\AUTOGEN_MATHCHAT\\autogenvenv\\Lib\\site-packages\\langchain_core\\language_models\\llms.py\", line 1069, in _generate\n    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)\n\n\n  File \"C:\\PYTHON_PROJECTS\\AUTOGEN_MATHCHAT\\autogenvenv\\Lib\\site-packages\\langchain_community\\llms\\textgen.py\", line 206, in _call\n    for chunk in self._stream(\n\n\n  File \"C:\\PYTHON_PROJECTS\\AUTOGEN_MATHCHAT\\autogenvenv\\Lib\\site-packages\\langchain_community\\llms\\textgen.py\", line 325, in _stream\n    websocket_client.connect(url)\n\n\n  File \"C:\\PYTHON_PROJECTS\\AUTOGEN_MATHCHAT\\autogenvenv\\Lib\\site-packages\\websocket\\_core.py\", line 261, in connect\n    self.handshake_response = handshake(self.sock, url, *addrs, **options)\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"C:\\PYTHON_PROJECTS\\AUTOGEN_MATHCHAT\\autogenvenv\\Lib\\site-packages\\websocket\\_handshake.py\", line 65, in handshake\n    status, resp = _get_resp_headers(sock)\n                   ^^^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"C:\\PYTHON_PROJECTS\\AUTOGEN_MATHCHAT\\autogenvenv\\Lib\\site-packages\\websocket\\_handshake.py\", line 150, in _get_resp_headers\n    raise WebSocketBadStatusException(\n\n\nwebsocket._exceptions.WebSocketBadStatusException: Handshake status 403 Forbidden -+-+- {'date': 'Wed, 27 Dec 2023 10:13:55 GMT', 'content-length': '0', 'content-type': 'text/plain', 'connection': 'close'} -+-+- b''"
[chain/error] [1:chain:LLMChain] [2.11s] Chain run errored with error:
"WebSocketBadStatusException(\"Handshake status 403 Forbidden -+-+- {'date': 'Wed, 27 Dec 2023 10:13:55 GMT', 'content-length': '0', 'content-type': 'text/plain', 'connection': 'close'} -+-+- b''\")Traceback (most recent call last):\n\n\n  
File \"C:\\PYTHON_PROJECTS\\AUTOGEN_MATHCHAT\\autogenvenv\\Lib\\site-packages\\langchain\\chains\\base.py\", line 306, in __call__\n    self._call(inputs, run_manager=run_manager)\n\n\n  File \"C:\\PYTHON_PROJECTS\\AUTOGEN_MATHCHAT\\autogenvenv\\Lib\\site-packages\\langchain\\chains\\llm.py\", line 103, in _call\n    response = self.generate([inputs], run_manager=run_manager)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"C:\\PYTHON_PROJECTS\\AUTOGEN_MATHCHAT\\autogenvenv\\Lib\\site-packages\\langchain\\chains\\llm.py\", line 115, in generate\n    return self.llm.generate_prompt(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"C:\\PYTHON_PROJECTS\\AUTOGEN_MATHCHAT\\autogenvenv\\Lib\\site-packages\\langchain_core\\language_models\\llms.py\", line 516, in generate_prompt\n    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"C:\\PYTHON_PROJECTS\\AUTOGEN_MATHCHAT\\autogenvenv\\Lib\\site-packages\\langchain_core\\language_models\\llms.py\", line 666, in generate\n    output = self._generate_helper(\n             ^^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"C:\\PYTHON_PROJECTS\\AUTOGEN_MATHCHAT\\autogenvenv\\Lib\\site-packages\\langchain_core\\language_models\\llms.py\", line 553, in _generate_helper\n    raise e\n\n\n  File \"C:\\PYTHON_PROJECTS\\AUTOGEN_MATHCHAT\\autogenvenv\\Lib\\site-packages\\langchain_core\\language_models\\llms.py\", line 540, in _generate_helper\n    self._generate(\n\n\n  File \"C:\\PYTHON_PROJECTS\\AUTOGEN_MATHCHAT\\autogenvenv\\Lib\\site-packages\\langchain_core\\language_models\\llms.py\", line 1069, in _generate\n    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)\n\n\n  File \"C:\\PYTHON_PROJECTS\\AUTOGEN_MATHCHAT\\autogenvenv\\Lib\\site-packages\\langchain_community\\llms\\textgen.py\", line 
206, in _call\n    for chunk in self._stream(\n\n\n  File \"C:\\PYTHON_PROJECTS\\AUTOGEN_MATHCHAT\\autogenvenv\\Lib\\site-packages\\langchain_community\\llms\\textgen.py\", line 325, in _stream\n    websocket_client.connect(url)\n\n\n  File \"C:\\PYTHON_PROJECTS\\AUTOGEN_MATHCHAT\\autogenvenv\\Lib\\site-packages\\websocket\\_core.py\", line 261, in connect\n    self.handshake_response = handshake(self.sock, url, *addrs, **options)\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"C:\\PYTHON_PROJECTS\\AUTOGEN_MATHCHAT\\autogenvenv\\Lib\\site-packages\\websocket\\_handshake.py\", line 65, in handshake\n    status, resp = _get_resp_headers(sock)\n                   ^^^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"C:\\PYTHON_PROJECTS\\AUTOGEN_MATHCHAT\\autogenvenv\\Lib\\site-packages\\websocket\\_handshake.py\", line 150, in _get_resp_headers\n    raise WebSocketBadStatusException(\n\n\nwebsocket._exceptions.WebSocketBadStatusException: Handshake status 403 Forbidden -+-+- {'date': 'Wed, 27 Dec 2023 10:13:55 GMT', 'content-length': '0', 'content-type': 'text/plain', 'connection': 'close'} -+-+- b''"
Traceback (most recent call last):
  File "c:\PYTHON_PROJECTS\AUTOGEN_MATHCHAT\autogenvenv\langtest.py", line 29, in <module>
    llm_chain.run(question)
  File "C:\PYTHON_PROJECTS\AUTOGEN_MATHCHAT\autogenvenv\Lib\site-packages\langchain\chains\base.py", line 507, in run
    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PYTHON_PROJECTS\AUTOGEN_MATHCHAT\autogenvenv\Lib\site-packages\langchain\chains\base.py", line 312, in __call__
    raise e
  File "C:\PYTHON_PROJECTS\AUTOGEN_MATHCHAT\autogenvenv\Lib\site-packages\langchain\chains\base.py", line 306, in __call__
    self._call(inputs, run_manager=run_manager)
  File "C:\PYTHON_PROJECTS\AUTOGEN_MATHCHAT\autogenvenv\Lib\site-packages\langchain\chains\llm.py", line 103, in _call
    response = self.generate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PYTHON_PROJECTS\AUTOGEN_MATHCHAT\autogenvenv\Lib\site-packages\langchain\chains\llm.py", line 115, in generate
    return self.llm.generate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PYTHON_PROJECTS\AUTOGEN_MATHCHAT\autogenvenv\Lib\site-packages\langchain_core\language_models\llms.py", line 516, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PYTHON_PROJECTS\AUTOGEN_MATHCHAT\autogenvenv\Lib\site-packages\langchain_core\language_models\llms.py", line 666, in generate
    output = self._generate_helper(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PYTHON_PROJECTS\AUTOGEN_MATHCHAT\autogenvenv\Lib\site-packages\langchain_core\language_models\llms.py", line 553, in _generate_helper
    raise e
  File "C:\PYTHON_PROJECTS\AUTOGEN_MATHCHAT\autogenvenv\Lib\site-packages\langchain_core\language_models\llms.py", line 540, in _generate_helper
    self._generate(
  File "C:\PYTHON_PROJECTS\AUTOGEN_MATHCHAT\autogenvenv\Lib\site-packages\langchain_core\language_models\llms.py", line 1069, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "C:\PYTHON_PROJECTS\AUTOGEN_MATHCHAT\autogenvenv\Lib\site-packages\langchain_community\llms\textgen.py", line 206, in _call
    for chunk in self._stream(
  File "C:\PYTHON_PROJECTS\AUTOGEN_MATHCHAT\autogenvenv\Lib\site-packages\langchain_community\llms\textgen.py", line 325, in _stream
    websocket_client.connect(url)
  File "C:\PYTHON_PROJECTS\AUTOGEN_MATHCHAT\autogenvenv\Lib\site-packages\websocket\_core.py", line 261, in connect
    self.handshake_response = handshake(self.sock, url, *addrs, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PYTHON_PROJECTS\AUTOGEN_MATHCHAT\autogenvenv\Lib\site-packages\websocket\_handshake.py", line 65, in handshake
    status, resp = _get_resp_headers(sock)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PYTHON_PROJECTS\AUTOGEN_MATHCHAT\autogenvenv\Lib\site-packages\websocket\_handshake.py", line 150, in _get_resp_headers
    raise WebSocketBadStatusException(
websocket._exceptions.WebSocketBadStatusException: Handshake status 403 Forbidden -+-+- {'date': 'Wed, 27 Dec 2023 10:13:55 GMT', 'content-length': '0', 'content-type': 'text/plain', 'connection': 'close'} -+-+- b''
```

### System Info

```shell
OS Name	Microsoft Windows 10 Pro
Version	10.0.19045 Build 19045
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DESKTOP-S6U25F2
System Manufacturer	HP
System Model	HP Pavilion Gaming Laptop 15-cx0xxx
System Type	x64-based PC
System SKU	4PY21UA#ABA
Processor	Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz, 2304 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Insyde F.18, 1/21/2019
SMBIOS Version	3.0
Embedded Controller Version	70.51
BIOS Mode	UEFI
BaseBoard Manufacturer	HP
BaseBoard Product	8478
BaseBoard Version	70.51
Platform Role	Mobile
Secure Boot State	Off
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.19041.2728"
```

**Comment by TheDarkTrumpet** [comment]
It looks like you're using the tutorial code or something like that, although you're using the langchain_community library for the API.  You may want to verify that works with the new API.  

About a month ago or so, the `--api` flag was changed to mirror better operate on the OpenAI specs.  The downfall is the tutorial, https://python.langchain.com/docs/integrations/llms/textgen broke.  You may want to check https://github.com/langchain-ai/langchain/issues/14318 which talks about the breaking library.

I haven't tested with any streaming yet, but there's one answer that points out a few files that point to the new API specs.  I've used both `TextGen` and `ChatTextGen`, and both appear to work fine.  It may be worth trying the remapped files there to see if it gets around your issue til pull requests can be made.

**Comment by seyi33** [comment]
> It looks like you're using the tutorial code or something like that, although you're using the langchain_community library for the API. You may want to verify that works with the new API.
> 
> About a month ago or so, the `--api` flag was changed to mirror better operate on the OpenAI specs. The downfall is the tutorial, https://python.langchain.com/docs/integrations/llms/textgen broke. You may want to check [langchain-ai/langchain#14318](https://github.com/langchain-ai/langchain/issues/14318) which talks about the breaking library.
> 
> I haven't tested with any streaming yet, but there's one answer that points out a few files that point to the new API specs. I've used both `TextGen` and `ChatTextGen`, and both appear to work fine. It may be worth trying the remapped files there to see if it gets around your issue til pull requests can be made.

Awesome, the solution here worked. https://github.com/langchain-ai/langchain/issues/14318, saving the temp fix in the
 current working folder.

**Comment by TheDarkTrumpet** [comment]
Glad it worked.  I think the task of fixing the langchain related issue (core library, or community) should exist with the actual langchain project and not this one.  I think it's wise to close this issue, and reply to the above link about you running into the same issue.  I've asked the person who rewrote the API calls to do a pull request.  If they don't do it, I may.

**Comment by joaquinariasco-lab** [comment]
Hi @seyi33 

I’ve been following your contributions regarding the TextGen/LangChain integration issues. Your insight into the breaking changes caused by the API shift towards OpenAI specs was spot on, it’s a perfect example of why the current agent ecosystem feels so fragile.

I’m working on a project with a bigger vision: a global automated economy where agents aren't just scripts running in a silo, but autonomous entities that connect and transact through a standardized protocol. We are building the orchestration layer that prevents the "dependency hell" you’ve been debugging.

We have an MVP on GitHub where devs can already connect agents to interact with each other. Given your experience bridging different LLM frameworks and backends, I think you’d find our architecture very interesting (and hopefully, less frustrating than current wrappers).

Would you be open to checking out the repo and sharing your thoughts?

Best,
Joaquin
