### ISSUE TITLE
Error on initial Windows install

### ISSUE THREAD

**Issue by Onexiarc** [oobabooga/text-generation-webui#5097]
### Describe the bug

When attempting to install the webui for the first time on windows I get the error: ModuleNotFoundError: No module named 'yaml'
I have installed PyYAML in the venv and in my local user python. 

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

I have done this twice by just extracting the source and running the start_windows batch file.

### Logs

```shell
*******************************************************************
* WARNING: You haven't downloaded any model yet.
* Once the web UI launches, head over to the "Model" tab and download one.
*******************************************************************


Traceback (most recent call last):
  File "D:\text-generation-webui-snapshot-2023-12-24\text-generation-webui-snapshot-2023-12-24\server.py", line 4, in <module>
    from modules import shared
  File "D:\text-generation-webui-snapshot-2023-12-24\text-generation-webui-snapshot-2023-12-24\modules\shared.py", line 7, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
Press any key to continue . . .
```

### System Info

```shell
Windows 10
Nvidia RTX3060ti 6gb
```

**Comment by XTorX** [comment]
Same issue

**Comment by matdombrock** [comment]
I'm running into this same issue on macOS.

**Comment by CHENCHAO0932** [comment]
Have you solved your problem? I am also facing the same issue and it's giving me a headache.

**Comment by XTorX** [comment]
Hi,

 

no, I have not spend a lot of time on this issue. I am wating that someone will fix it because it's not an insignificant problem.

 

BR

 
 
 

Gesendet: Sonntag, 31. Dezember 2023 um 11:16 Uhr
Von: "CHENCHAO0932" ***@***.***>
An: "oobabooga/text-generation-webui" ***@***.***>
Cc: "XTorX" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [oobabooga/text-generation-webui] Error on initial Windows install (Issue #5097)


 

Have you solved your problem? I am also facing the same issue and it's giving me a headache.

**Comment by tangd** [comment]
Same issue

**Comment by DeebsStirdy** [comment]
use an older release. For [example](https://github.com/oobabooga/text-generation-webui/releases/tag/1.6.1).

**Comment by DeebsStirdy** [comment]
worked fine after that

**Comment by djethino** [comment]
same problem.

to correct this issue, I launched "update_windows.bat" then relaunched "start_windows.bat" and now all is okay for me.

**Comment by Onexiarc** [comment]
> same problem.
> 
> to correct this issue, I launched "update_windows.bat" then relaunched "start_windows.bat" and now all is okay for me.

i tried that didnt work for me, installing an old version now

**Comment by q5sys** [comment]
> use an older release. For [example](https://github.com/oobabooga/text-generation-webui/releases/tag/1.6.1).

I tried that older version and ran into this bug which is closed, but people are still reporting it as a problem.
https://github.com/oobabooga/text-generation-webui/issues/1841

**Comment by Kaiton121** [comment]
I had the same issue with the build the most recent build ([snapshot-2023-12-31](https://github.com/oobabooga/text-generation-webui/releases/tag/snapshot-2023-12-31)) It turned out that I hadn't really installed the requirements.

1. Try running `update_windows.bat` in case you haven't merged with the most recent release.
2. Make sure you're in the correct virtual environment (just run `start_windows.bat` if you must, it'll still put you into the venv even if it errors out).
3. Run `pip install -r <correct_requirements.txt>`. Refer to the table [here ](https://github.com/oobabooga/text-generation-webui#3-install-the-web-ui) to find the correct txt-file. It looks like it's stuck at some point but it finished after 2-3 minutes for me.
4. Rerun `start_windows.bat`. That's all I did.

Hope this helps!

**Comment by Seantourage** [comment]
Another solution if you don't want to edit the webui.py which could cause git pull upgrade issues due to edited code or adding the directory to your path which could mess up other conda projects, just do the following:

Copy _conda.exe from installer_files\conda to the root directory and rename it to conda.exe
