### ISSUE TITLE
'charmap' codec can't decode byte 0x81 in position 125: character maps to <undefined>

### ISSUE THREAD

**Issue by XeonG** [oobabooga/text-generation-webui#5120]
### Describe the bug

Latest version.. .trying to run https://huggingface.co/LoneStriker/deepseek-coder-33b-instruct-3.0bpw-h6-exl2

Get the error in logs

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

 .trying to run https://huggingface.co/LoneStriker/deepseek-coder-33b-instruct-3.0bpw-h6-exl2

### Logs

```shell
To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\Projects\AI\text-generation-webui\installer_files\env\lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Projects\AI\text-generation-webui\installer_files\env\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Projects\AI\text-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "C:\Projects\AI\text-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Projects\AI\text-generation-webui\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Projects\AI\text-generation-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Projects\AI\text-generation-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Projects\AI\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "C:\Projects\AI\text-generation-webui\modules\models_settings.py", line 227, in apply_model_settings_to_state
    model_settings = get_model_metadata(model)
  File "C:\Projects\AI\text-generation-webui\modules\models_settings.py", line 115, in get_model_metadata
    metadata = json.loads(open(path, 'r').read())
  File "C:\Projects\AI\text-generation-webui\installer_files\env\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 125: character maps to <undefined>
```

### System Info

```shell
3700x 80gb 4900rtx
```

**Comment by marktaiwan** [comment]
I encountered the same error trying to load `TheBloke/dolphin-2.6-mistral-7B-GPTQ`. I'm not much of a programmer, so I just asked Bing AI:
<details><summary>Open transcript</summary>

#### Me:

> I'm trying to debug an error I'm getting in python, the error message is
> ```
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2149: character maps to <undefined>
> ```
> The hex sequence in the offending file from position 2147-2150 is as follows: `E2 80 9D 22`.
> Can you maybe see why it might cause the error?

#### Bing:

> I'm sorry to hear that you are having trouble with your python code. 😕
> 
> The error message indicates that you are trying to decode a byte sequence that is not valid in the 'charmap' codec, which is usually an alias for 'cp1252' on Windows systems¹. The byte 0x9d is not a defined character in 'cp1252', so it cannot be decoded and causes an exception².
> 
> The hex sequence `E2 80 9D 22` is actually a valid UTF-8 encoding for the character '”' (U+201D) followed by a double quote '"' (U+0022)³. However, if you try to decode it as 'cp1252', you will get the error you mentioned.
> 
> To fix this error, you need to specify the correct encoding when you open the file, such as:
> 
> ```python
> file = open(filename, encoding="utf-8")
> ```
> 
> This will tell python to use UTF-8 to decode the file contents, and avoid the UnicodeDecodeError. Alternatively, you can use the 'errors' argument to ignore or replace the invalid bytes, such as:
> 
> ```python
> file = open(filename, errors="ignore")
> ```
> 
> or
> 
> ```python
> file = open(filename, errors="replace")
> ```
> 
> However, this may result in some data loss or corruption, so it is better to use the correct encoding if possible.
> 
> I hope this helps you solve your problem. 😊

</details> 

Following its advice, I edited line 115 from `models_settings.py` https://github.com/oobabooga/text-generation-webui/blob/3fd707380868ad6a2ba57aaed4c96799c2441d99/modules/models_settings.py#L115
to
```python
metadata = json.loads(open(path, 'r', encoding='utf-8').read())
```
And that fixed it for me.

**Comment by XeonG** [comment]
ah thanks yeah found it here https://github.com/oobabooga/text-generation-webui/issues/4947#issuecomment-1871623484 aswel
