### ISSUE TITLE
CUDA assertion error with AUTOGPTQ

### ISSUE THREAD

**Issue by banjaminicc** [oobabooga/text-generation-webui#5159]
### Describe the bug

As title, assertion error when attempting to run 
```
TheBloke_dolphin-2.7-mixtral-8x7b-GPTQ_gptq-4bit-128g-actorder_True
```
Exllama works when running the same model however with the warning of flash-attention not being installed
AWQ fails but with a different error

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run any GPTQ model with AUTOGPTQ

### Logs

```shell
Traceback (most recent call last):
  File "F:\text-generation-webui-snapshot-2023-12-31\modules\ui_model_menu.py", line 213, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\text-generation-webui-snapshot-2023-12-31\modules\models.py", line 87, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\text-generation-webui-snapshot-2023-12-31\modules\models.py", line 376, in AutoGPTQ_loader
    return modules.AutoGPTQ_loader.load_quantized(model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\text-generation-webui-snapshot-2023-12-31\modules\AutoGPTQ_loader.py", line 59, in load_quantized
    model = AutoGPTQForCausalLM.from_quantized(path_to_model, **params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\text-generation-webui-snapshot-2023-12-31\installer_files\env\Lib\site-packages\auto_gptq\modeling\auto.py", line 129, in from_quantized
    return quant_func(
           ^^^^^^^^^^^
  File "F:\text-generation-webui-snapshot-2023-12-31\installer_files\env\Lib\site-packages\auto_gptq\modeling\_base.py", line 1040, in from_quantized
    model = autogptq_post_init(model, use_act_order=quantize_config.desc_act)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\text-generation-webui-snapshot-2023-12-31\installer_files\env\Lib\site-packages\auto_gptq\modeling\_utils.py", line 380, in autogptq_post_init
    submodule.post_init(temp_dq = model.device_tensors[device])
  File "F:\text-generation-webui-snapshot-2023-12-31\installer_files\env\Lib\site-packages\auto_gptq\nn_modules\qlinear\qlinear_exllamav2.py", line 140, in post_init
    assert self.qweight.device.type == "cuda"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```
```


### System Info

```shell
Specs are Ryzen 3700x with a RTX 3060
```

**Comment by iarbel84** [comment]
Any news on this? Getting the same error

**Comment by DiddyC** [comment]
same issue here

**Comment by TheKola** [comment]
Solved for me by upgrading the transformers package
`pip install transformers --upgrade`

**Comment by iarbel84** [comment]
I solved it by passing a GPTQConfig and explicitly setting `use_exllama=False`. I assume the big is due to this model not supporting exllama kernels, while the default config ia to use exllama
