### ISSUE TITLE
ERROR - Failed to load the extension "coqui_tts"

### ISSUE THREAD

**Issue by Sierra144** [oobabooga/text-generation-webui#5167]
### Describe the bug

I tried to launch the coqui_tts extension but have this bug during the launch of the oobabooga web-ui. I follow all the instructions available and don't know what is wrong. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

12:54:16-841139 ERROR    Could not import the requirements for 'coqui_tts'. Make sure to install the requirements for
                         the extension.

                         Linux / Mac:

                         pip install -r extensions/coqui_tts/requirements.txt --upgrade

                         Windows:

                         pip install -r extensions\coqui_tts\requirements.txt --upgrade

                         If you used the one-click installer, paste the command above in the terminal window opened
                         after launching the cmd script for your OS.
12:54:16-844196 ERROR    Failed to load the extension "coqui_tts".

### Screenshot

<img width="847" alt="image" src="https://github.com/oobabooga/text-generation-webui/assets/153828450/f9277f78-f46d-466d-be2e-420c85e60429">

<img width="860" alt="image" src="https://github.com/oobabooga/text-generation-webui/assets/153828450/b07f39f7-fe9a-4df7-86a9-aa2f59978dde">

### Logs

```shell
*******************************************************************
* WARNING: You haven't downloaded any model yet.
* Once the web UI launches, head over to the "Model" tab and download one.
*******************************************************************


12:54:16-826062 INFO     Starting Text generation web UI
12:54:16-830088 INFO     Loading settings from settings.yaml
12:54:16-836272 INFO     Loading the extension "gallery"
12:54:16-838627 INFO     Loading the extension "coqui_tts"
12:54:16-841139 ERROR    Could not import the requirements for 'coqui_tts'. Make sure to install the requirements for
                         the extension.

                         Linux / Mac:

                         pip install -r extensions/coqui_tts/requirements.txt --upgrade

                         Windows:

                         pip install -r extensions\coqui_tts\requirements.txt --upgrade

                         If you used the one-click installer, paste the command above in the terminal window opened
                         after launching the cmd script for your OS.
12:54:16-844196 ERROR    Failed to load the extension "coqui_tts".
Traceback (most recent call last):
  File "S:\TextGen_AI\text-generation-webui-main\modules\extensions.py", line 37, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "S:\TextGen_AI\text-generation-webui-main\extensions\coqui_tts\script.py", line 9, in <module>
    from TTS.api import TTS
ModuleNotFoundError: No module named 'TTS'
12:54:16-846622 INFO     Loading the extension "openai"
12:54:16-951654 INFO     OpenAI-compatible API URL:
```

### System Info

```shell
Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz 3.60 GHz
Installed RAM 32.0 GB
System type 64-bit operating system, x64 processor
GPU : NVIDIA GeForce RTX 2080 SUPER
```

**Comment by jangins101** [comment]
From what I can tell, this error happens because the Python exe being used is different than the primary system version (in my case, it was using the version installed within this project folder, at `..\..\installer_files\env\python.exe` relative to the coqui_tts folder under *modules*). 

In the main `script.py` file, I added this to the top (to see where the python executable resides):
```python
import sys
print(sys.executable)
```

After reloading from the UI, the terminal showed me the python path. I just took that and had it install the dependencies using `..\..\installer_files\env\python.exe -m pip install -r .\requirements.txt`. 

After reloading from the UI again, I no longer received this error message and it moved on and loaded successfully.

**Comment by SgtEpsilon** [comment]
> In the main `script.py` file, I added this to the top (to see where the python executable resides):
> 
> ```python
> import sys
> print(sys.executable)
> ```
> 
> After reloading from the UI, the terminal showed me the python path. I just took that and had it install the dependencies using `..\..\installer_files\env\python.exe -m pip install -r .\requirements.txt`.
> 
> After reloading from the UI again, I no longer received this error message and it moved on and loaded successfully.

I can't find the ```script.py``` file that you're referring to

**Comment by Galaxia-mk** [comment]
> > In the main `script.py` file, I added this to the top (to see where the python executable resides):
> > ```python
> > import sys
> > print(sys.executable)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After reloading from the UI, the terminal showed me the python path. I just took that and had it install the dependencies using `..\..\installer_files\env\python.exe -m pip install -r .\requirements.txt`.
> > After reloading from the UI again, I no longer received this error message and it moved on and loaded successfully.
> 
> I can't find the `script.py` file that you're referring to

What he seems to be referring to is the script.py file that's located in text-generation-webui-main/extensions/coqui_tts/

I am trying to resolve the same error at the moment. Even after reinstalling the pc it wasn't solved surprisingly.
![Screenshot_20240123_192807](https://github.com/oobabooga/text-generation-webui/assets/110353717/e5d74970-731e-4d45-b6bb-5bf08e3a7191)

**Comment by Galaxia-mk** [comment]
> From what I can tell, this error happens because the Python exe being used is different than the primary system version (in my case, it was using the version installed within this project folder, at `..\..\installer_files\env\python.exe` relative to the coqui_tts folder under _modules_).
> 
> In the main `script.py` file, I added this to the top (to see where the python executable resides):
> 
> ```python
> import sys
> print(sys.executable)
> ```
> 
> After reloading from the UI, the terminal showed me the python path. I just took that and had it install the dependencies using `..\..\installer_files\env\python.exe -m pip install -r .\requirements.txt`.
> 
> After reloading from the UI again, I no longer received this error message and it moved on and loaded successfully.

When i try this it tells me "ERROR: Could not open requirements file: [Errno 2] No such file or directory: '.requirements.txt'"

**Comment by SgtEpsilon** [comment]
> What he seems to be referring to is the script.py file that's located in text-generation-webui-main/extensions/coqui_tts/

That makes more sense now

**Comment by jangins101** [comment]
Sorry @SgtEpsilon, I should've included more context for the path. Thanks @Galaxia-mk for the assist.

**Comment by sgtwtf** [comment]
This seems old but not marked solved. I have this issue today and I was able to solve. ran "cmd_windows.bat" and installed the requirments.txt from "text-generation-webui\extensions\coqui_tts"
