### ISSUE TITLE
 Failed to load  superboogav2 chromadb.py", line 2, in <module>     import chromadb

### ISSUE THREAD

**Issue by sandyis** [oobabooga/text-generation-webui#5173]
### Describe the bug

@HideLord 
superboogav2 is not able to find chromadb , chromadb is installed as can been seen below 

:~/text-generation-webui-main$ pip list | grep -i chroma
chroma-hnswlib                           0.7.3
chromadb                                 0.3.18

```
pip install -r extensions/superboogav2/requirements.txt --upgrade
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: beautifulsoup4==4.12.2 in /home/test/.local/lib/python3.10/site-packages (from -r extensions/superboogav2/requirements.txt (line 1)) (4.12.2)
Collecting chromadb==0.3.18
  Downloading chromadb-0.3.18-py3-none-any.whl (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.3/46.3 KB 2.5 MB/s eta 0:00:00
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

execute this  `pip install -r extensions/superboogav2/requirements.txt --upgrade` and restart `bash start_linux.sh --listen --api`

### Logs

```shell
:~/text-generation-webui-main$ bash start_linux.sh --listen --api
22:52:05-810308 INFO     Starting Text generation web UI
22:52:05-812951 WARNING
                         You are potentially exposing the web UI to the entire internet without any access password.
                         You can create one with the "--gradio-auth" flag like this:

                         --gradio-auth username:password

                         Make sure to replace username:password with your own.
22:52:05-814277 INFO     Loading settings from settings.yaml
22:52:05-817575 INFO     Loading the extension "openai"
22:52:05-880734 INFO     OpenAI-compatible API URL:

                         http://0.0.0.0:5000

22:52:05-881356 INFO     Loading the extension "gallery"
22:52:05-885992 INFO     Loading the extension "Training_PRO"
22:52:06-170737 INFO     Loading the extension "superboogav2"

23:17:21-616016 ERROR    Could not import the requirements for 'superboogav2'. Make sure to install the requirements for the extension.

                         Linux / Mac:

                         pip install -r extensions/superboogav2/requirements.txt --upgrade

                         Windows:

                         pip install -r extensions\superboogav2\requirements.txt --upgrade

                         If you used the one-click installer, paste the command above in the terminal window opened after launching the cmd script for your OS.
23:17:21-617588 ERROR    Failed to load the extension "superboogav2".
Traceback (most recent call last):
  File "/home/test/text-generation-webui-main/modules/extensions.py", line 37, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "/home/test/text-generation-webui-main/extensions/superboogav2/script.py", line 20, in <module>
    from .chromadb import make_collector
  File "/home/test/text-generation-webui-main/extensions/superboogav2/chromadb.py", line 2, in <module>
    import chromadb

```
```


### System Info

```shell
nvdia T4
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

**Comment by cbolich** [comment]
same issue, tried installing manually but didn't seem to work

**Comment by sandyis** [comment]
Command needs to be run in the virtual ENV of the application which can be started as below 

```
~/text-generation-webui-main$ bash cmd_linux.sh
(/home/test/text-generation-webui-main/installer_files/env) test@testai:~/text-generation-webui-main$ pip install -r extensions/superboogav2/requirements.txt --upgrade
```

now getting some other error investigating will close this
