### ISSUE TITLE
yaml error

### ISSUE THREAD

**Issue by leejw51** [oobabooga/text-generation-webui#5175]
### Describe the bug

when start_linux.sh,
yaml error 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

start_linux.sh

### Logs

```shell
ModuleNotFoundError: No module named 'yaml'
```

### System Info

```shell
linux
```

**Comment by laishuzhong** [comment]
the same bug yaml version can't match python 3.11

**Comment by tk666ttkk** [comment]
能不能来个人解决一下啊，can somebody fix this bug？
i run the start_windows.bat firsttime,but i fail it. when i start_windows.bat next time,it will always be this bug,

**Comment by davidgutierrezpalma** [comment]
I have the same issue in macOS (Apple Silicon).

**Comment by tangd** [comment]
try：
python -m pip install pyyaml

**Comment by davidgutierrezpalma** [comment]
@tangd thanks for your the reply.

After executing the proposed command, the error disappeared... but now I have a similar error:

ModuleNotFoundError: No module named 'rich'

Both packages seem to appear in the requirements_apple_silicon.txt file, so my guess the bash script isn't installing all the dependencies. Once I executed this line after conda activate "$INSTALL_ENV_DIR":

pip install -r "requirements_apple_silicon.txt" 

All the dependencies were installed and the server was launched successfully.

**Comment by nasuadachi** [comment]
There is a conflict when using "pip install -r "requirements_apple_silicon.txt"" on mac os 14.2.1
Is it better to create a virtual environment (venv?)?

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
rembg 2.0.30 requires asyncer~=0.0.2, which is not installed.
rembg 2.0.30 requires filetype~=1.2.0, which is not installed.
rembg 2.0.30 requires imagehash~=4.3.1, which is not installed.
spyder 5.4.1 requires pyqt5<5.16, which is not installed.
spyder 5.4.1 requires pyqtwebengine<5.16, which is not installed.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.4 which is incompatible.
rembg 2.0.30 requires click~=8.1.3, but you have click 8.0.4 which is incompatible.
rembg 2.0.30 requires fastapi~=0.87.0, but you have fastapi 0.94.0 which is incompatible.
rembg 2.0.30 requires numpy~=1.23.5, but you have numpy 1.24.4 which is incompatible.
rembg 2.0.30 requires onnxruntime~=1.13.1, but you have onnxruntime 1.14.1 which is incompatible.
rembg 2.0.30 requires opencv-python-headless~=4.6.0.66, but you have opencv-python-headless 4.8.0.76 which is incompatible.
rembg 2.0.30 requires pillow~=9.3.0, but you have pillow 9.5.0 which is incompatible.
rembg 2.0.30 requires pooch~=1.6.0, but you have pooch 1.4.0 which is incompatible.
rembg 2.0.30 requires scikit-image~=0.19.3, but you have scikit-image 0.21.0 which is incompatible.
rembg 2.0.30 requires scipy~=1.9.3, but you have scipy 1.10.0 which is incompatible.
rembg 2.0.30 requires uvicorn~=0.20.0, but you have uvicorn 0.22.0 which is incompatible.
rembg 2.0.30 requires watchdog~=2.1.9, but you have watchdog 2.1.6 which is incompatible.
tensorflow-macos 2.13.0 requires numpy<=1.24.3,>=1.22, but you have numpy 1.24.4 which is incompatible.
tensorflow-macos 2.13.0 requires typing-extensions<4.6.0,>=3.6.6, but you have typing-extensions 4.9.0 which is incompatible.
Successfully installed DataProperty-1.0.1 accelerate-0.25.0 bitsandbytes-0.41.1 cramjam-2.7.0 datasets-2.16.1 dill-0.3.7 diskcache-5.6.3 distro-1.9.0 docker-pycreds-0.4.0 exllamav2-0.0.11 fastparquet-2023.10.1 fsspec-2023.10.0 gradio-3.50.2 gradio-client-0.6.1 hqq-0.1.2 huggingface-hub-0.20.2 jsonlines-4.0.0 llama-cpp-python-0.2.26 lm_eval-0.3.0 mbstrdecoder-1.1.3 multiprocess-0.70.15 ninja-1.11.1.1 numpy-1.24.4 openai-1.7.1 optimum-1.16.1 pathvalidate-3.2.0 peft-0.7.1 pyarrow-14.0.2 pyarrow-hotfix-0.6 pybind11-2.11.1 pycountry-23.12.11 pytablewriter-1.2.0 rouge-score-0.1.2 sacrebleu-1.5.0 safetensors-0.4.1 sentry-sdk-1.39.2 setproctitle-1.3.3 sqlitedict-2.1.0 tabledata-1.3.3 tcolorpy-0.1.4 tokenizers-0.15.0 tqdm-multiprocess-0.0.11 transformers-4.36.2 typepy-1.3.2 typing-extensions-4.9.0 wandb-0.16.2 xxhash-3.4.1
```

**Comment by nasuadachi** [comment]
mac os 14.2.1 , Apple silicon M1 max


% ./cmd_macos.sh
bash-5.2$ pip install -r "re^Cirements_apple_silicon.txt"
bash-5.2$ ./start_macos.sh 

many many error ...
```
*******************************************************************
* WARNING: You haven't downloaded any model yet.
* Once the web UI launches, head over to the "Model" tab and download one.
*******************************************************************


18:46:27-098972 INFO     Starting Text generation web UI                                                                             
18:46:27-100721 INFO     Loading the extension "gallery"                                                                             
Running on local URL:  http://127.0.0.1:7860
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Volumes/SSD/git/text-generation-webui/installer_files/env/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

TypeError: replace() argument 1 must be str, not bytes
╭──────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────╮
│ /Volumes/SSD/git/text-generation-webui/server.py:254 in <module>                                                            │
│                                                                                                                                   │
│   253         # Launch the web UI                                                                                                 │
│ ❱ 254         create_interface()                                                                                                  │
│   255         while True:                                                                                                         │
│                                                                                                                                   │
│ /Volumes/SSD/git/text-generation-webui/server.py:162 in create_interface                                                    │
│                                                                                                                                   │
│   161     with OpenMonkeyPatch():                                                                                                 │
│ ❱ 162         shared.gradio['interface'].launch(                                                                                  │
│   163             prevent_thread_lock=True,                                                                                       │
│                                                                                                                                   │
│ /Volumes/SSD/git/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/blocks.py:2115 in launch     │
│                                                                                                                                   │
│   2114         ):                                                                                                                 │
│ ❱ 2115             raise ValueError(                                                                                              │
│   2116                 "When localhost is not accessible, a shareable link must be created. Ple                                   │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to
allow access to localhost.
```

**Comment by tangd** [comment]
I tried to comment out line 39 to 47 in file modules/block_requests.py and wrote line 47 to line 48.

**Comment by tangd** [comment]
> mac os 14.2.1 , Apple silicon M1 max
> 
> % ./cmd_macos.sh bash-5.2$ pip install -r "re^Cirements_apple_silicon.txt" bash-5.2$ ./start_macos.sh
> 
> many many error ...
> 
> ```
> *******************************************************************
> * WARNING: You haven't downloaded any model yet.
> * Once the web UI launches, head over to the "Model" tab and download one.
> *******************************************************************
> 
> 
> 18:46:27-098972 INFO     Starting Text generation web UI                                                                             
> 18:46:27-100721 INFO     Loading the extension "gallery"                                                                             
> Running on local URL:  http://127.0.0.1:7860
> ERROR:    Exception in ASGI application
> Traceback (most recent call last):
>   File "/Volumes/SSD/git/text-generation-webui/installer_files/env/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
>     result = await app(  # type: ignore[func-returns-value]
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> TypeError: replace() argument 1 must be str, not bytes
> ╭──────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────╮
> │ /Volumes/SSD/git/text-generation-webui/server.py:254 in <module>                                                            │
> │                                                                                                                                   │
> │   253         # Launch the web UI                                                                                                 │
> │ ❱ 254         create_interface()                                                                                                  │
> │   255         while True:                                                                                                         │
> │                                                                                                                                   │
> │ /Volumes/SSD/git/text-generation-webui/server.py:162 in create_interface                                                    │
> │                                                                                                                                   │
> │   161     with OpenMonkeyPatch():                                                                                                 │
> │ ❱ 162         shared.gradio['interface'].launch(                                                                                  │
> │   163             prevent_thread_lock=True,                                                                                       │
> │                                                                                                                                   │
> │ /Volumes/SSD/git/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/blocks.py:2115 in launch     │
> │                                                                                                                                   │
> │   2114         ):                                                                                                                 │
> │ ❱ 2115             raise ValueError(                                                                                              │
> │   2116                 "When localhost is not accessible, a shareable link must be created. Ple                                   │
> ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
> ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to
> allow access to localhost.
> ```

I tried to comment out line 39 to 47 in file modules/block_requests.py and wrote line 47 to line 48.

**Comment by tangd** [comment]
> > mac os 14.2.1 , Apple silicon M1 max
> > % ./cmd_macos.sh bash-5.2$ pip install -r "re^Cirements_apple_silicon.txt" bash-5.2$ ./start_macos.sh
> > many many error ...
> > ```
> > *******************************************************************
> > * WARNING: You haven't downloaded any model yet.
> > * Once the web UI launches, head over to the "Model" tab and download one.
> > *******************************************************************
> > 
> > 
> > 18:46:27-098972 INFO     Starting Text generation web UI                                                                             
> > 18:46:27-100721 INFO     Loading the extension "gallery"                                                                             
> > Running on local URL:  http://127.0.0.1:7860
> > ERROR:    Exception in ASGI application
> > Traceback (most recent call last):
> >   File "/Volumes/SSD/git/text-generation-webui/installer_files/env/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
> >     result = await app(  # type: ignore[func-returns-value]
> >              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > 
> > TypeError: replace() argument 1 must be str, not bytes
> > ╭──────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────╮
> > │ /Volumes/SSD/git/text-generation-webui/server.py:254 in <module>                                                            │
> > │                                                                                                                                   │
> > │   253         # Launch the web UI                                                                                                 │
> > │ ❱ 254         create_interface()                                                                                                  │
> > │   255         while True:                                                                                                         │
> > │                                                                                                                                   │
> > │ /Volumes/SSD/git/text-generation-webui/server.py:162 in create_interface                                                    │
> > │                                                                                                                                   │
> > │   161     with OpenMonkeyPatch():                                                                                                 │
> > │ ❱ 162         shared.gradio['interface'].launch(                                                                                  │
> > │   163             prevent_thread_lock=True,                                                                                       │
> > │                                                                                                                                   │
> > │ /Volumes/SSD/git/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/blocks.py:2115 in launch     │
> > │                                                                                                                                   │
> > │   2114         ):                                                                                                                 │
> > │ ❱ 2115             raise ValueError(                                                                                              │
> > │   2116                 "When localhost is not accessible, a shareable link must be created. Ple                                   │
> > ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
> > ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to
> > allow access to localhost.
> > ```
> 
> I tried to comment out line 39 to 47 in file modules/block_requests.py and wrote line 47 to line 48.

<img width="663" alt="image" src="https://github.com/oobabooga/text-generation-webui/assets/3350120/c4c06bf4-4b4a-4892-b4b9-1ed69b574616">

**Comment by sdwcn** [comment]
same, after yaml error, got "ModuleNotFoundError: No module named 'rich'"

**Comment by jrruethe** [comment]
I ended up doing `pip install -r requirements.txt` to get past this. I did it with the conda env set.

**Comment by sdwcn** [comment]
@jrruethe tks for the tips,  however i ran into another error:
I reinstall by running "./start_linux.sh" after clean up  installer_files folder
After "ModuleNotFoundError: No module named 'yaml'" poped up, running "pip install -r requirements.txt"  give me this error  which is weried:
my env is centos 7
<img width="491" alt="2024-01-18 141031" src="https://github.com/oobabooga/text-generation-webui/assets/4686367/fb990516-acd1-4104-b53b-f0da0c441dc4">

Any clues will be appreciated!

**Comment by nhaus12** [comment]
I added the following to `wsl.sh`, which is run by `start_wsl.bat` (as I am using WSL):

```
# Originally in wsl.sh
conda activate "$INSTALL_ENV_DIR"

# ADDED: install requirements
conda update -n base -c defaults conda
conda install pip
pip install -r $INSTALL_DIR/requirements_amd.txt
```

Obviously the file/script in which you make these changes, and the specific requirements file to use, will depend on your environment/system.

**Comment by Jason-Chen-2017** [comment]
> > > mac os 14.2.1 , Apple silicon M1 max
> > > % ./cmd_macos.sh bash-5.2$ pip install -r "re^Cirements_apple_silicon.txt" bash-5.2$ ./start_macos.sh
> > > many many error ...
> > > ```
> > > *******************************************************************
> > > * WARNING: You haven't downloaded any model yet.
> > > * Once the web UI launches, head over to the "Model" tab and download one.
> > > *******************************************************************
> > > 
> > > 
> > > 18:46:27-098972 INFO     Starting Text generation web UI                                                                             
> > > 18:46:27-100721 INFO     Loading the extension "gallery"                                                                             
> > > Running on local URL:  http://127.0.0.1:7860
> > > ERROR:    Exception in ASGI application
> > > Traceback (most recent call last):
> > >   File "/Volumes/SSD/git/text-generation-webui/installer_files/env/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
> > >     result = await app(  # type: ignore[func-returns-value]
> > >              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > 
> > > TypeError: replace() argument 1 must be str, not bytes
> > > ╭──────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────╮
> > > │ /Volumes/SSD/git/text-generation-webui/server.py:254 in <module>                                                            │
> > > │                                                                                                                                   │
> > > │   253         # Launch the web UI                                                                                                 │
> > > │ ❱ 254         create_interface()                                                                                                  │
> > > │   255         while True:                                                                                                         │
> > > │                                                                                                                                   │
> > > │ /Volumes/SSD/git/text-generation-webui/server.py:162 in create_interface                                                    │
> > > │                                                                                                                                   │
> > > │   161     with OpenMonkeyPatch():                                                                                                 │
> > > │ ❱ 162         shared.gradio['interface'].launch(                                                                                  │
> > > │   163             prevent_thread_lock=True,                                                                                       │
> > > │                                                                                                                                   │
> > > │ /Volumes/SSD/git/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/blocks.py:2115 in launch     │
> > > │                                                                                                                                   │
> > > │   2114         ):                                                                                                                 │
> > > │ ❱ 2115             raise ValueError(                                                                                              │
> > > │   2116                 "When localhost is not accessible, a shareable link must be created. Ple                                   │
> > > ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
> > > ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to
> > > allow access to localhost.
> > > ```
> > 
> > 
> > I tried to comment out line 39 to 47 in file modules/block_requests.py and wrote line 47 to line 48.
> 
> <img alt="image" width="663" src="https://private-user-images.githubusercontent.com/3350120/295871220-c4c06bf4-4b4a-4892-b4b9-1ed69b574616.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NDUwNDUsIm5iZiI6MTcwNjQ0NDc0NSwicGF0aCI6Ii8zMzUwMTIwLzI5NTg3MTIyMC1jNGMwNmJmNC00YjRhLTQ4OTItYjRiOS0xZWQ2OWI1NzQ2MTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjhUMTIyNTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjQwYzUyNGUzN2I5MjExZmMxNDJlOTBmYTc2YjRhNTAxMTgzMzM4NDExYWE5MzI0NzBkZjhlNGJmMTFkM2E4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.45EPUYOiHIdclYAya2_gQysbnmgEYu4iCqiwBeSNZBE">



comment out line 39 to 47 in file modules/block_requests.py and wrote line 47 to line 48  works for me:


modules/block_requests.py


# Kindly provided by our friend WizardLM-30B
def my_open(*args, **kwargs):
    filename = str(args[0])
    # if filename.endswith('index.html'):
    #     with original_open(*args, **kwargs) as f:
    #         file_contents = f.read()
    #
    #     file_contents = file_contents.replace(b'\t\t<script\n\t\t\tsrc="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/4.3.7/iframeResizer.contentWindow.min.js"\n\t\t\tasync\n\t\t></script>', b'')
    #     file_contents = file_contents.replace(b'cdnjs.cloudflare.com', b'127.0.0.1')
    #     return io.BytesIO(file_contents)
    # else:
    #     return original_open(*args, **kwargs)

    return original_open(*args, **kwargs)
