### ISSUE TITLE
Can't download GGUF model branches

### ISSUE THREAD

**Issue by AlanTuring42** [oobabooga/text-generation-webui#5176]
### Describe the bug

Can't download `GGUF` models branches on Colab. I think it's just because of the blob vs main tree thing.

Most of the  GGUF model branches is in like this format for example: `[dolphin-2.5-mixtral-8x7b.Q3_K_M.gguf](https://huggingface.co/TheBloke/dolphin-2.5-mixtral-8x7b-GGUF/blob/main/dolphin-2.5-mixtral-8x7b.Q3_K_M.gguf)` **Unlike** `[gptq-4bit-128g-actorder_True](https://huggingface.co/TheBloke/dolphin-2.5-mixtral-8x7b-GPTQ/tree/gptq-4bit-128g-actorder_True)`

I dunno /tree/main part of the URL is typically used in github to navigate to the main branch of a repository. However, in the context of Hugging Face model URLs, it’s not necessary and could be causing the error from download-model.py.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Try to download `dolphin-2.5-mixtral-8x7b.Q3_K_M.gguf` branch from https://huggingface.co/TheBloke/dolphin-2.5-mixtral-8x7b-GGUF on colab.

### Logs

```shell
Traceback (most recent call last):
  File "/content/text-generation-webui/download-model.py", line 295, in <module>
    links, sha256, is_lora, is_llamacpp = downloader.get_download_links_from_huggingface(model, branch, text_only=args.text_only, specific_file=specific_file)
  File "/content/text-generation-webui/download-model.py", line 74, in get_download_links_from_huggingface
    r.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/TheBloke/dolphin-2.5-mixtral-8x7b-GGUF/tree/dolphin-2.5-mixtral-8x7b.Q3_K_M.gguf
python server.py --share --model TheBloke_dolphin-2.5-mixtral-8x7b-GGUF_dolphin-2.5-mixtral-8x7b.Q3_K_M.gguf 
07:44:14-102203 INFO     Starting Text generation web UI                                            
07:44:14-123348 INFO     Loading                                                                    
                         TheBloke_dolphin-2.5-mixtral-8x7b-GGUF_dolphin-2.5-mixtral-8x7b.Q3_K_M.gguf
07:44:14-127644 ERROR    The path to the model does not exist. Exiting.                             
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /content/text-generation-webui/server.py:241 in <module>                                         │
│                                                                                                  │
│   240         # Load the model                                                                   │
│ ❱ 241         shared.model, shared.tokenizer = load_model(model_name)                            │
│   242         if shared.args.lora:                                                               │
│                                                                                                  │
│ /content/text-generation-webui/modules/models.py:84 in load_model                                │
│                                                                                                  │
│    83                 logger.error('The path to the model does not exist. Exiting.')             │
│ ❱  84                 raise ValueError                                                           │
│    85                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError
```

### System Info

```shell
Colab
```

**Comment by phiharri** [comment]
It would be useful to include the exact command causing the error, perhaps the syntax is wrong. This works for me:
```
$ python download-model.py https://huggingface.co/TheBloke/dolphin-2.5-mixtral-8x7b-GGUF --specific-file dolphin-2.5-mixtral-8x7b.Q3_K_M.gguf
Downloading dolphin-2.5-mixtral-8x7b.Q3_K_M.gguf to models
  1%|▋                                                                                                 | 130M  /20.4G  110MiB/s
```

**Comment by AlanTuring1978** [comment]
> It would be useful to include the exact command causing the error, perhaps the syntax is wrong. This works for me:
> 
> ```
> $ python download-model.py https://huggingface.co/TheBloke/dolphin-2.5-mixtral-8x7b-GGUF --specific-file dolphin-2.5-mixtral-8x7b.Q3_K_M.gguf
> Downloading dolphin-2.5-mixtral-8x7b.Q3_K_M.gguf to models
>   1%|▋                                                                                                 | 130M  /20.4G  110MiB/s
> ```

@phiharri mate it was on colab actually link: https://colab.research.google.com/github/oobabooga/text-generation-webui/blob/main/Colab-TextGen-GPU.ipynb

**Comment by AlanTuring1978** [comment]
@phiharri mate it was on colab actually, just followed the official code

**Comment by AlanTuring1978** [comment]
@phiharri mate it was on colab actually, just followed the official link 😅
