### ISSUE TITLE
How to load ChatGLM in 4-bit?

### ISSUE THREAD

**Issue by XinyongGuo** [oobabooga/text-generation-webui#5190]
### Describe the bug

I want to load this model in 8G VRAM. But it  seems that they have different quantize.

Shall I copy Tokenizer class ChatGLMTokenizer from "models\THUDM_chatglm3-6btokenization_chatglm.py" into text-generation-webui-snapshot-2023-11-05\modules\models.py?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

![微信图片_20240107145234](https://github.com/oobabooga/text-generation-webui/assets/103313953/018ee21d-3d86-4cee-b846-8a9f2039f941)

### Logs

```shell
Traceback (most recent call last):

File "E:\AI\text-generation-webui-snapshot-2023-11-05\text-generation-webui-snapshot-2023-11-05\modules\ui_model_menu.py", line 209, in load_model_wrapper


shared.model, shared.tokenizer = load_model(shared.model_name, loader)

                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\AI\text-generation-webui-snapshot-2023-11-05\text-generation-webui-snapshot-2023-11-05\modules\models.py", line 92, in load_model


tokenizer = load_tokenizer(model_name, model)

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\AI\text-generation-webui-snapshot-2023-11-05\text-generation-webui-snapshot-2023-11-05\modules\models.py", line 111, in load_tokenizer


tokenizer = AutoTokenizer.from_pretrained(

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\AI\text-generation-webui-snapshot-2023-11-05\text-generation-webui-snapshot-2023-11-05\installer_files\env\Lib\site-packages\transformers\models\auto\tokenization_auto.py", line 765, in from_pretrained


raise ValueError(
ValueError: Tokenizer class ChatGLMTokenizer does not exist or is not currently imported.
```

### System Info

```shell
CPU:i3-12100F
GPU:RTX 3050
RAM:32G
system:Win10
```

**Comment by Hemerocallis319** [comment]
你是不是trust-remote-code选项没有勾选

**Comment by liluzhang** [comment]
> 你是不是trust-remote-code选项没有勾选

刚开始是有这个报错，但应该不是这个问题。
这个选项我勾不了，鼠标移过去是灰的。
我根据报错信息在代码里找到了这个flag，改成true后就能开始加载了。

**Comment by WangFengtu1996** [comment]
我这边尝试也遇到问题, 我通过命令行的方式去启动这个模型 
```
python3 server.py --model-dir=/data/models/text-generation-webui  --model chatglm2-6b-int4 --trust-remote-code --chat --listen
```
* 模型来源 https://huggingface.co/THUDM/chatglm2-6b-int4/tree/main

```
root@orin-root:/opt/text-generation-webui# python3 server.py --model-dir=/data/models/text-generation-webui  --model chatglm2-6b-int4 --trust-remote-code --
chat --listen
/usr/local/lib/python3.8/dist-packages/transformers/utils/hub.py:123: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
03:24:30-174103 INFO     Starting Text generation web UI
03:24:30-181473 WARNING  The --chat flag has been deprecated and will be removed soon. Please remove that flag.
03:24:30-183931 WARNING  trust_remote_code is enabled. This is dangerous.
03:24:30-186174 WARNING
                         You are potentially exposing the web UI to the entire internet without any access password.
                         You can create one with the "--gradio-auth" flag like this:

                         --gradio-auth username:password

                         Make sure to replace username:password with your own.
03:24:30-192057 INFO     Loading settings from settings.json
03:24:30-198016 INFO     Loading chatglm2-6b-int4
╭─────────────────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────────────────╮
│ /opt/text-generation-webui/server.py:240 in <module>                                                                                                     │
│                                                                                                                                                          │
│   239         # Load the model                                                                                                                           │
│ ❱ 240         shared.model, shared.tokenizer = load_model(model_name)                                                                                    │
│   241         if shared.args.lora:                                                                                                                       │
│                                                                                                                                                          │
│ /opt/text-generation-webui/modules/models.py:90 in load_model                                                                                            │
│                                                                                                                                                          │
│    89     shared.args.loader = loader                                                                                                                    │
│ ❱  90     output = load_func_map[loader](model_name)                                                                                                     │
│    91     if type(output) is tuple:                                                                                                                      │
│                                                                                                                                                          │
│ /opt/text-generation-webui/modules/models.py:161 in huggingface_loader                                                                                   │
│                                                                                                                                                          │
│   160     if not any([shared.args.cpu, shared.args.load_in_8bit, shared.args.load_in_4bit, sha                                                           │
│ ❱ 161         model = LoaderClass.from_pretrained(path_to_model, **params)                                                                               │
│   162         if torch.backends.mps.is_available():                                                                                                      │
│                                                                                                                                                          │
│ /usr/local/lib/python3.8/dist-packages/transformers/models/auto/auto_factory.py:561 in from_pretrained                                                   │
│                                                                                                                                                          │
│   560                 cls.register(config.__class__, model_class, exist_ok=True)                                                                         │
│ ❱ 561             return model_class.from_pretrained(                                                                                                    │
│   562                 pretrained_model_name_or_path, *model_args, config=config, **hub_kwargs,                                                           │
│                                                                                                                                                          │
│ /usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py:3462 in from_pretrained                                                            │
│                                                                                                                                                          │
│   3461             # Let's make sure we don't run the init function of buffer modules                                                                    │
│ ❱ 3462             model = cls(config, *model_args, **model_kwargs)                                                                                      │
│   3463                                                                                                                                                   │
│                                                                                                                                                          │
│                                                                 ... 2 frames hidden ...                                                                  │
│                                                                                                                                                          │
│ /data/models/huggingface/modules/transformers_modules/chatglm2-6b-int4/quantization.py:511 in quantize                                                   │
│                                                                                                                                                          │
│   510     for layer in model.layers:                                                                                                                     │
│ ❱ 511         layer.self_attention.query_key_value = QuantizedLinear(                                                                                    │
│   512             weight_bit_width=weight_bit_width,                                                                                                     │
│                                                                                                                                                          │
│ /data/models/huggingface/modules/transformers_modules/chatglm2-6b-int4/quantization.py:494 in __init__                                                   │
│                                                                                                                                                          │
│   493                                                                                                                                                    │
│ ❱ 494         self.weight = Parameter(self.weight.to(device), requires_grad=False)                                                                       │
│   495         self.weight_scale = Parameter(self.weight_scale.to(device), requires_grad=False)                                                           │
│                                                                                                                                                          │
│ /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1632 in __setattr__                                                                    │
│                                                                                                                                                          │
│   1631             remove_from(self.__dict__, self._buffers, self._modules, self._non_persisten                                                          │
│ ❱ 1632             self.register_parameter(name, value)                                                                                                  │
│   1633         elif params is not None and name in params:                                                                                               │
│                                                                                                                                                          │
│ /usr/local/lib/python3.8/dist-packages/accelerate/big_modeling.py:123 in register_empty_parameter                                                        │
│                                                                                                                                                          │
│   122             kwargs = module._parameters[name].__dict__                                                                                             │
│ ❱ 123             module._parameters[name] = param_cls(module._parameters[name].to(device), **                                                           │
│   124                                                                                                                                                    │
│                                                                                                                                                          │
│ /usr/local/lib/python3.8/dist-packages/torch/nn/parameter.py:36 in __new__                                                                               │
│                                                                                                                                                          │
│    35             # Eventually (tm), we should change the behavior for standard Tensor to matc                                                           │
│ ❱  36             return torch.Tensor._make_subclass(cls, data, requires_grad)                                                                           │
│    37                                                                                                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Only Tensors of floating point and complex dtype can require gradients
```
* 看起来是数据精度不知吃的问题  @liluzhang  @Hemerocallis319 你们这边有啥进展么？

**Comment by WangFengtu1996** [comment]
我这边还有相关的问题请教下哈，关于这种模型转换成 llama 支持的 GGUF ，技术可行性上可以么？ 然后是怎么做呢？

**Comment by WangFengtu1996** [comment]
> 我这边还有相关的问题请教下哈，关于这种模型转换成 llama 支持的 GGUF ，技术可行性上可以么？ 然后是怎么做呢？

目前看起来是llama.cpp 并不支持这个chatglm 这种模型
