### ISSUE TITLE
OpenAI API don't work

### ISSUE THREAD

**Issue by GitNeu256** [oobabooga/text-generation-webui#5194]
### Describe the bug

when trying to make a request through the OpenAI API

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

run this code that emits the API

```py
import requests

url = "http://localhost:5000/v1/chat/completions"

headers = {
    "authorization": "12984"
}

data = {
    "message": [{"role": "user",
                "content": "Say this ia a test!"}],
    "temperature": 0.7
}

r = requests.post(url, headers=headers, data = data)

print(r)
```

### Logs

```shell
Output generated in 0.50 seconds (0.00 tokens/s, 0 tokens, context 0, seed 1914272577)
Traceback (most recent call last):
  File "F:\text-generation-webui\modules\callbacks.py", line 57, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\text-generation-webui\modules\text_generation.py", line 368, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Users\ilijd\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ilijd\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\generation\utils.py", line 1583, in generate
    and torch.sum(inputs_tensor[:, -1] == generation_config.pad_token_id) > 0
                  ~~~~~~~~~~~~~^^^^^^^
IndexError: index -1 is out of bounds for dimension 1 with size 0
Output generated in 0.52 seconds (0.00 tokens/s, 0 tokens, context 0, seed 675368643)
```

### System Info

```shell
GPU: None
CPU: Intel Core i5-1035G1 1.00 GHz
RAM: 8Gb
System: Windows 10
```

**Comment by sam1am** [comment]
This is not the first time this team has pushed production-breaking changes without notice. 
And once again my entire service is melting down and on fire because of it. 
I recommend moving off of this package ASAP to something that isn't changing it's spec every other week and breaking everyone's work.

**Comment by sandyis** [comment]
which model you are using 
i have the setup working okay with GPU T4 and LLAMA2-13b
can you check transformers version you have ? `4.36.x` ?
some vlaue being passed is `0` that is causing this 


below worked for me 
```
curl http://127.0.0.1:5000/v1/chat/completions   -H "Content-Type: application/json"   -d '{
    "messages": [
      {
        "role": "user",
        "content": "Hello, what are the moons of jupiter!"
      }
    ],
    "mode": "instruct",
    "instruction_template": "Alpaca"
  }'
{"id":"chatcmpl-1704649021218089728","object":"chat.completions","created":1704649021,"model":"llama-2-13b-chat-hf","choices":[{"index":0,"finish_reason":"stop","message":{"role":"assistant","content":"Hello! There are 79 known moons of Jupiter, with the largest four being Io, Europa, Ganymede, and Callisto. These four moons are known as the Galilean moons, as they were discovered by Galileo Galilei in 1610. Io is the innermost of the four, and it is the most volcanically active object in the solar system. Europa is the second closest moon to Jupiter and is covered in a thick layer of ice, which is thought to contain a liquid water ocean beneath. Ganymede is the largest moon in the solar system, and Callisto is the outermost of the four. In addition to these four large moons, Jupiter has many smaller moons, with diameters ranging from a few kilometers to several hundred kilometers."}}],"usage":{"prompt_tokens":48,"completion_tokens":175,"total_tokens"
```

**Comment by zwilch** [comment]
information: I can not reproduce it. 10.01.2024, OpenAI API works fine.
Did ./update_linux.sh today.
