### ISSUE TITLE
TypeError: BFloat16 is not supported on MPS

### ISSUE THREAD

**Issue by b8kings0ga** [oobabooga/text-generation-webui#5216]
### Describe the bug

TypeError: BFloat16 is not supported on MPS

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

running transformer models 

### Logs

```shell
Traceback (most recent call last):
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/modules/callbacks.py", line 61, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/modules/text_generation.py", line 376, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/transformers/generation/utils.py", line 1764, in generate
    return self.sample(
           ^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/transformers/generation/utils.py", line 2861, in sample
    outputs = self(
              ^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/transformers/models/mixtral/modeling_mixtral.py", line 1222, in forward
    outputs = self.model(
              ^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/transformers/models/mixtral/modeling_mixtral.py", line 1090, in forward
    layer_outputs = decoder_layer(
                    ^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/transformers/models/mixtral/modeling_mixtral.py", line 803, in forward
    hidden_states = self.input_layernorm(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/accelerate/hooks.py", line 160, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/accelerate/hooks.py", line 294, in pre_forward
    module, name, self.execution_device, value=self.weights_map[name], fp16_statistics=fp16_statistics
                                               ~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/accelerate/utils/offload.py", line 118, in __getitem__
    return self.dataset[f"{self.prefix}{key}"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/accelerate/utils/offload.py", line 169, in __getitem__
    tensor = f.get_tensor(weight_info.get("weight_name", key))
```

### System Info

```shell
Traceback (most recent call last):
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/modules/callbacks.py", line 61, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/modules/text_generation.py", line 376, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/transformers/generation/utils.py", line 1764, in generate
    return self.sample(
           ^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/transformers/generation/utils.py", line 2861, in sample
    outputs = self(
              ^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/transformers/models/mixtral/modeling_mixtral.py", line 1222, in forward
    outputs = self.model(
              ^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/transformers/models/mixtral/modeling_mixtral.py", line 1090, in forward
    layer_outputs = decoder_layer(
                    ^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/transformers/models/mixtral/modeling_mixtral.py", line 803, in forward
    hidden_states = self.input_layernorm(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/accelerate/hooks.py", line 160, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/accelerate/hooks.py", line 294, in pre_forward
    module, name, self.execution_device, value=self.weights_map[name], fp16_statistics=fp16_statistics
                                               ~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/accelerate/utils/offload.py", line 118, in __getitem__
    return self.dataset[f"{self.prefix}{key}"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shen.li/github.com/oobabooga/text-generation-webui.git/installer_files/env/lib/python3.11/site-packages/accelerate/utils/offload.py", line 169, in __getitem__
    tensor = f.get_tensor(weight_info.get("weight_name", key))
```

**Comment by glen-fdce** [comment]
Hello, there is still same error with latest build of text-gen
