### ISSUE TITLE
Python exceptions after an API request from SillyTavern (Frostwind EXL2)

### ISSUE THREAD

**Issue by notsyncing12309** [oobabooga/text-generation-webui#5232]
### Describe the bug

When I try to make a request through SillyTavern to the API, Python exceptions are thrown and no responses are received.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Load any model
2. Connect to API from SillyTavern (Power plug icon -> Text Completion -> Default (Oobabooga) -> Connect button)
3. Make request in any chat

### Logs

```shell
04:41:31-276722 INFO     Starting Text generation web UI
04:41:31-281234 INFO     Loading the extension "openai"
04:41:31-354038 INFO     OpenAI-compatible API URL:

                         http://127.0.0.1:5000

04:41:31-354449 INFO     Loading the extension "gallery"
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
04:42:05-079389 INFO     Loading frostwind
04:42:31-461867 INFO     LOADER: ExLlamav2
04:42:31-462867 INFO     TRUNCATION LENGTH: 3072
04:42:31-463869 INFO     INSTRUCTION TEMPLATE: Alpaca
04:42:31-463869 INFO     Loaded the model in 26.38 seconds.
Exception in ASGI application
Traceback (most recent call last):
  File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\site-packages\sse_starlette\sse.py", line 247, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\site-packages\sse_starlette\sse.py", line 236, in wrap
    await func()
  File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\site-packages\sse_starlette\sse.py", line 191, in listen_for_disconnect
    message = await receive()
              ^^^^^^^^^^^^^^^
  File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 538, in receive
    await self.message_event.wait()
  File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\asyncio\locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 226c48c0c90

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
  |     return await self.app(scope, receive, send)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\site-packages\starlette\applications.py", line 116, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
  |     raise exc
  |   File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
  |     await self.app(scope, receive, send)
  |   File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\site-packages\starlette\_exception_handler.py", line 55, in wrapped_app
  |     raise exc
  |   File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\site-packages\starlette\_exception_handler.py", line 44, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\site-packages\starlette\routing.py", line 746, in __call__
  |     await route.handle(scope, receive, send)
  |   File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\site-packages\starlette\routing.py", line 288, in handle
  |     await self.app(scope, receive, send)
  |   File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\site-packages\starlette\routing.py", line 75, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\site-packages\starlette\_exception_handler.py", line 55, in wrapped_app
  |     raise exc
  |   File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\site-packages\starlette\_exception_handler.py", line 44, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\site-packages\starlette\routing.py", line 73, in app
  |     await response(scope, receive, send)
  |   File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\site-packages\sse_starlette\sse.py", line 233, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\site-packages\sse_starlette\sse.py", line 236, in wrap
    |     await func()
    |   File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\site-packages\sse_starlette\sse.py", line 221, in stream_response
    |     async for data in self.body_iterator:
    |   File "C:\Portable\text-generation-webui-main\extensions\openai\script.py", line 104, in generator
    |     for resp in response:
    |   File "C:\Portable\text-generation-webui-main\extensions\openai\completions.py", line 531, in stream_completions
    |     for resp in completions_common(body, is_legacy, stream=True):
    |   File "C:\Portable\text-generation-webui-main\extensions\openai\completions.py", line 374, in completions_common
    |     generate_params = process_parameters(body, is_legacy=is_legacy)
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Portable\text-generation-webui-main\extensions\openai\completions.py", line 107, in process_parameters
    |     encoder = tiktoken.encoding_for_model(generate_params['model'])
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\site-packages\tiktoken\model.py", line 97, in encoding_for_model
    |     return get_encoding(encoding_name_for_model(model_name))
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Portable\text-generation-webui-main\installer_files\env\Lib\site-packages\tiktoken\model.py", line 80, in encoding_name_for_model
    |     if model_name.startswith(model_prefix):
    |        ^^^^^^^^^^^^^^^^^^^^^
    | AttributeError: 'NoneType' object has no attribute 'startswith'
    +------------------------------------
```

### System Info

```shell
Windows 10
Nvidia RTX 3050 8GB
```

**Comment by Ph0rk0z** [comment]
This is logit banning or bias related. Turn those off and it will stop doing that.

**Comment by notsyncing12309** [comment]
> This is logit banning or bias related. Turn those off and it will stop doing that.

It works, thank you!

**Comment by Ph0rk0z** [comment]
hehe.. I think it's still a bug though.. tabby supports both of these

**Comment by notsyncing12309** [comment]
> hehe.. I think it's still a bug though.. tabby supports both of these
Koboldcpp also works fine with logit bias. I will reopen issue for further proceedings.

**Comment by gjdaley** [comment]
> > > This is logit banning or bias related. Turn those off and it will stop doing that.
> > 
> > 
> > It works, thank you!
> 
> Hello, how did you solve this issue? I don't have any logit bias added in ST nor do I see a place to change this in oobabooga. This issue is happening even with the default loaded character profiles. I am having the exact same errors that you had. The only difference is that I am on a 3060 with 12GB of VRAM

After hours of wrangling with this, I found that my error stemmed from having TTS (Coqui_TTS) enabled on the WebUI side. Once I unchecked "Activate TTS" in the "Chat" tab of WebUI, I was able to get prompts from ST working again.
