### ISSUE TITLE
Openai api extension not loading

### ISSUE THREAD

**Issue by GamingDaveUk** [oobabooga/text-generation-webui#5255]
### Describe the bug

openai extension is not loading.

Error is:
```
02:42:27-489783 INFO     Starting Text generation web UI
02:42:27-507661 INFO     Loading settings from settings.yaml
02:42:27-512660 INFO     Loading the extension "gallery"
02:42:27-514660 INFO     Loading the extension "openai"
02:42:27-553659 ERROR    Failed to load the extension "openai".
Traceback (most recent call last):
  File "H:\Models\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "H:\Models\extensions\openai\script.py", line 31, in <module>
    from .typing import (
  File "H:\Models\extensions\openai\typing.py", line 80, in <module>
    class ChatCompletionRequestParams(BaseModel):
  File "pydantic\main.py", line 284, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\utils.py", line 260, in pydantic.utils.generate_model_signature
TypeError: unhashable type: 'list'
Running on local URL:  http://127.0.0.1:7860
```

Attempted updating again but same error

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

update to the version live at the time of this post.
Load with the openai extension ticked

### Logs

```shell
02:42:27-489783 INFO     Starting Text generation web UI
02:42:27-507661 INFO     Loading settings from settings.yaml
02:42:27-512660 INFO     Loading the extension "gallery"
02:42:27-514660 INFO     Loading the extension "openai"
02:42:27-553659 ERROR    Failed to load the extension "openai".
Traceback (most recent call last):
  File "H:\Models\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "H:\Models\extensions\openai\script.py", line 31, in <module>
    from .typing import (
  File "H:\Models\extensions\openai\typing.py", line 80, in <module>
    class ChatCompletionRequestParams(BaseModel):
  File "pydantic\main.py", line 284, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\utils.py", line 260, in pydantic.utils.generate_model_signature
TypeError: unhashable type: 'list'
Running on local URL:  http://127.0.0.1:7860
```

### System Info

```shell
windows 11
rtx 3090
```

**Comment by timothyallan** [comment]
Copying the `extensions` folder from the latest snapshot into the project that used auto update fixes it... just don't auto update again until the issue is fixed.

**Comment by rabilrbl** [comment]
I did a temp fix by this commit

https://github.com/CySecAI/text-generation-webui/commit/2c910b12c6f4a632ca54bfdf4763e307fae289ff

**Comment by Daviljoe193** [comment]
Issue should be safe to close, since a fix (952a05a7c8645a7cbdea2e7a13a424ae0b946c2f) is now in-place, and at least for me, it seems to fix the issue entirely.

**Comment by rabilrbl** [comment]
@GamingDaveUk The issue has been fixed. Close this issue
