### ISSUE TITLE
The (trust-remote-code) option in the (Transformers) loader cannot be checked

### ISSUE THREAD

**Issue by Hemerocallis319** [oobabooga/text-generation-webui#5258]
### Describe the bug

The (trust-remote-code) option cannot be selected, resulting in the Chat model not being used

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

The (trust-remote-code) option cannot be selected, resulting in the Chat model not being used

### Screenshot

![b59fe46d734113d7737eb9182922b902](https://github.com/oobabooga/text-generation-webui/assets/155454045/36c704ab-af14-4452-9aa7-71a9d6cf74ee)

### Logs

```shell
Traceback (most recent call last):
  File "F:\text-generation-webui\modules\ui_model_menu.py", line 213, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\text-generation-webui\modules\models.py", line 87, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\text-generation-webui\modules\models.py", line 140, in huggingface_loader
    config = AutoConfig.from_pretrained(path_to_model, trust_remote_code=params['trust_remote_code'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\text-generation-webui\installer_files\env\Lib\site-packages\transformers\models\auto\configuration_auto.py", line 1085, in from_pretrained
    trust_remote_code = resolve_trust_remote_code(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\text-generation-webui\installer_files\env\Lib\site-packages\transformers\dynamic_module_utils.py", line 621, in resolve_trust_remote_code
    raise ValueError(
ValueError: Loading models\baichuan-inc_Baichuan2-13B-Chat requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.
```

### System Info

```shell
w11
cpu:13700K
gpu:RTX4080
```

**Comment by HideLord** [comment]
Above it, it says: "To enable this option, start the Web UI with the --trust-remote-code flag."
Have you tried this? Add `--trust-remote-code` to `CMD_FLAGS.txt`.
