### ISSUE TITLE
OpenAI extension + No API link

### ISSUE THREAD

**Issue by darkwarriorx0545** [oobabooga/text-generation-webui#5264]
### Describe the bug

Im getting an OpenAI extension load error, even though i didn't enable the extension. There's also no cloudflare API link, only webui.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Turn the google colab notebook on (https://colab.research.google.com/github/oobabooga/text-generation-webui/blob/main/Colab-TextGen-GPU.ipynb) with command line flags: "--share --n-gpu-layers 128 --load-in-4bit --use_double_quant --api --public-api" and with any model.

### Screenshot

![png](https://github.com/oobabooga/text-generation-webui/assets/124061850/be64bc30-ca61-4555-8a95-56dc8b9cb488)

### Logs

```shell
Traceback (most recent call last):
  File "/content/text-generation-webui/modules/extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "/content/text-generation-webui/extensions/openai/script.py", line 31, in <module>
    from .typing import (
  File "/content/text-generation-webui/extensions/openai/typing.py", line 80, in <module>
    class ChatCompletionRequestParams(BaseModel):
  File "pydantic/main.py", line 284, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/utils.py", line 260, in pydantic.utils.generate_model_signature
TypeError: unhashable type: 'list'
```

### System Info

```shell
Im using Google Colab free plan (NVIDIA T4 GPU)
```

**Comment by darkwarriorx0545** [comment]
(I cant run it on PC)

**Comment by darkwarriorx0545** [comment]
nvm i got it to work.
