### ISSUE TITLE
ModuleNotFoundError: No module named 'llama'

### ISSUE THREAD

**Issue by NolanMangalMM** [oobabooga/text-generation-webui#527]
### Describe the bug

When attempting to start the server, I get an error. It is related to the file /modules/GPTQ_loader.py , where it tries to import a module called llama and llama_inference_offload.

I have no idea what these modules are or why nobody else is having issues with them. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

git clone repo
pip install -r requirements.txt
python server.py --model llama30B --load-in-4bit

### Logs

```shell
Loading llama-30b...
Traceback (most recent call last):
  File "C:\Users\xxx\Downloads\one-click-installers-oobabooga-windows\text-generation-webui\server.py", line 234, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\xxx\Downloads\one-click-installers-oobabooga-windows\text-generation-webui\modules\models.py", line 99, in load_model
    from modules.GPTQ_loader import load_quantized
  File "C:\Users\xxx\Downloads\one-click-installers-oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 11, in <module>
    import llama
ModuleNotFoundError: No module named 'llama'
```

### System Info

```shell
Windows 11, Nvidia rtx 3090, cuda is installed and properly functioning.
```

**Comment by oobabooga** [comment]
Did you follow the instructions here?

https://github.com/oobabooga/text-generation-webui/wiki/LLaMA-model#step-1-installation
