### ISSUE TITLE
No module named 'yaml'

### ISSUE THREAD

**Issue by karsontsang23** [oobabooga/text-generation-webui#5270]
### Describe the bug

ModuleNotFoundError: No module named 'yaml'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1.download(https://github.com/oobabooga/text-generation-webui/archive/refs/heads/main.zip) the repository.
2.Run the start_windows.bat
3.Select your GPU vendor: none

### Logs

```shell
Traceback (most recent call last):
  File "D:\chingcomputer\text-generation-webui-main\server.py", line 4, in <module>
    from modules import shared
  File "D:\chingcomputer\text-generation-webui-main\modules\shared.py", line 7, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

### System Info

```shell
operating system:Windows 10   GPU model:AMD Athlon Silver 3050e with Radeon Graphics 1.40 GHz
```

**Comment by araleza** [comment]
Yep, that's what happens to me too.  My issue for it is here:

https://github.com/oobabooga/text-generation-webui/issues/5239

There's a workaround in that thread there to hand install yaml so it works for you.  But I want to know why some people have to do this.  It doesn't seem like it happens to everyone.

**Comment by Ericcccca** [comment]
I also encountered this problem,
But I solved it by installing the requirement.txt of the corresponding env in the  directory through pip.

pip install requirements_xxx.txt，it may help you.

**Comment by Cinichengbuweikong** [comment]
> I also encountered this problem, But I solved it by installing the requirement.txt of the corresponding env in the directory through pip.
> 
> pip install requirements_xxx.txt，it may help you.

you are right   just run `pip install -r requirements.txt`. (version 2024-01-21)

**Comment by thisisoscar** [comment]
I'm using an M2 Mac and I have the same problem. When I run `pip install pyyaml `I get this output:
`Requirement already satisfied: pyyaml in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (6.0.1)`

But when I run `./start_macos.sh` I get this:
```


*******************************************************************
* WARNING: You haven't downloaded any model yet.
* Once the web UI launches, head over to the "Model" tab and download one.
*******************************************************************


Traceback (most recent call last):
  File "/Users/oscarmappley/Downloads/text-generation-webui-main/server.py", line 4, in <module>
    from modules import shared
  File "/Users/oscarmappley/Downloads/text-generation-webui-main/modules/shared.py", line 8, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'```

**Comment by thisisoscar** [comment]
> I'm using an M2 Mac and I have the same problem. When I run `pip install pyyaml` I get this output:
> 
> `Requirement already satisfied: pyyaml in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (6.0.1)`
> 
> But when I run `./start_macos.sh` I get this:
> 
> ```
> 
> 
> *******************************************************************
> * WARNING: You haven't downloaded any model yet.
> * Once the web UI launches, head over to the "Model" tab and download one.
> *******************************************************************
> 
> 
> Traceback (most recent call last):
>   File "/Users/oscarmappley/Downloads/text-generation-webui-main/server.py", line 4, in <module>
>     from modules import shared
>   File "/Users/oscarmappley/Downloads/text-generation-webui-main/modules/shared.py", line 8, in <module>
>     import yaml
> ModuleNotFoundError: No module named 'yaml'
> ```

Ok so I ran it from my home directory and it worked

**Comment by dendrown** [comment]
I was having this same problem on Gentoo Linux.  Through trial and error, I found that using symlinks to my installation directory seemed to be messing up the conda environment for python.  If I do the initial run of `./start_linux.sh` after first changing to `/the/real/path/to/text-generation-webui`, everything installs successfully, and the webui starts.

After the initial installation, I can use my symlinks to get to the directory, and both `start_linux.sh` and `update_linux.sh` will run successfully, presumably because conda already has the full path stored in its environment configuration.

**Comment by PieBru** [comment]
Thanks @dendrown for pointing to this.
This solved the same issue I had on Arch Linux, where my AI Experiments are stored on `/mnt/sdb1` and used via symlink.

**Comment by truedat101** [comment]
In my case, having rye initialized in my shell is throwing off the python binary used, since rye uses shims.  I haven't figured out a way for this to coexist, and since it isn't used in the installer, and isn't helping in this case, one can remove the ${HOME}/.rye/env initialization from the shell session.

**Comment by gabrie** [comment]
When I ran start_macos.sh in the text-generation-webui path, I got this
zsh: command not found: start_macos.sh

When I ran ./start_macos.sh in the text-generation-webui path, I got this


*******************************************************************
* WARNING: You haven't downloaded any model yet.
* Once the web UI launches, head over to the "Model" tab and download one.
*******************************************************************


Traceback (most recent call last):
  File "/Volumes/Thunder_1T/TextWebUI/text-generation-webui/server.py", line 4, in <module>
    from modules import shared
  File "/Volumes/Thunder_1T/TextWebUI/text-generation-webui/modules/shared.py", line 8, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

Already did "pip install -r requirements.txt"

**Comment by charexcalibur** [comment]
Env: macbook m1max
I cloned repo to path /my/project/

❌ After ./start_macos，I got ModuleNotFoundError: No module named 'yaml' 
⭕️ When I run from home path /my/project/text-generation-webui/start_macos.sh , it works

**Comment by frankssciencemonster** [comment]
I'm also commenting, like dendrown, that symbolic links caused problems. I had this issue in both bare metal debian and a distrobox container. (I put everything in ~/docker, a symlinked folder.)

Navigating directly to the actual folder (/media/raid/docker in my case) and running the script again removed this error. Running pip directly made no difference.

**Comment by zewebdev1337** [comment]
I'm facing this issue after having to restart an instance. Apparently running start_***.sh forcefully updates the repository. 

I ran it and it asked me to run it again because of an update. Haven't been able to start after that.

**Comment by bcdzc** [comment]
In my case, this is caused by a conflict between the local conda and the built-in conda in the project. After performing the following steps, it was restored.

1. run "conda deactivate" to exit the conda env
2. delete project
3. run "git clone" again
4. run start_xxx.sh

**Comment by happylittle2010** [comment]
解决方法：删了项目，开全局魔法，重新运行

**Comment by scpedicini** [comment]
Chiming in here. I was also getting the module not found for `yaml` and have a default conda installation used on my Mac M1. 

Once I ran `conda deactivate` in my shell, I was able to clone/run mac os script without any issues. It's a little deceptive because the `start_macos_.sh` script contains:

```bash
{ conda deactivate && conda deactivate && conda deactivate; } 2> /dev/null
```

So I assumed I wouldn't have to deactivate it *manually*.

**Comment by f0ster** [comment]
This is still an issue , but is resolved by starting the bash script with the full path.
e.g.,
```
./start_linux.sh # breaks
/full/path/start_linus.sh # works 
```

**Comment by MictianManah** [comment]
•	OS: Windows 11 Pro
•	CPU: 13th Gen Intel® Core™ i9-13900K @ 3.00 GHz
•	RAM: 64.0 GB (63.8 GB usable)
•	GPU: NVIDIA RTX 4070 Ti Super
•	Storage: Lexar SSD NM790 4TB (2TB usable)

CMD Flags
--load-in-4bit
--trust-remote-code
--bf16
--ctx-size 16384
--no-cache
--extensions deep_reason LucidWebSearch Memoir session_manager llm_steer-oobabooga AutoSave alltalk_tts superboogav2 file_uploader

I did a fresh install today, tried to install Memoir through the update wizard, it did not detect it as installed, I installed it from the environment.

Traceback (most recent call last):
  File "C:\Oobabooga\server.py", line 6, in <module>
    from modules import shared
  File "C:\Oobabooga\modules\shared.py", line 9, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
Press any key to continue . . .

pip install -r requirements.txt

Issue persists

pip install pyyaml

Issue persists.
