### ISSUE TITLE
Implement the Prompt lookup decoding method (2-3x speed improvement)

### ISSUE THREAD

**Issue by BadisG** [oobabooga/text-generation-webui#5289]
Demo: https://nitter.net/joao_gante/status/1747322413006643259#m
Merged PR on Transformers: https://github.com/huggingface/transformers/pull/27775

Now that this method is officialy on the transformers repo, we could use it to improve the speed of inference, that's a huge news!

Edit: It's already there on llama.cpp
https://github.com/ggerganov/llama.cpp/tree/master/examples/lookup

**Comment by FartyPants** [comment]
It's dead simple - update transformers, then add prompt_lookup_num_tokens (int) in generate. They say good value is 10

**Comment by BadisG** [comment]
>It's dead simple to add - update transformers
For transformers, we need them to bump the version though? 

>add prompt_lookup_num_tokens in generate args
can you be a bit more specific?

**Comment by BadisG** [comment]
For the transformers update I did this
```
pip uninstall transformers
pip install git+https://github.com/huggingface/transformers.git
```

And I added this line of code ```kwargs['prompt_lookup_num_tokens'] = 10``` on the ```generate_with_callback(callback=None, *args, **kwargs)``` function on text_generation.py  (line ~370)

```
def generate_with_callback(callback=None, *args, **kwargs):
    kwargs['stopping_criteria'].append(Stream(callback_func=callback))
    kwargs['prompt_lookup_num_tokens'] = 10
    clear_torch_cache()
    with torch.no_grad():
        shared.model.generate(**kwargs)
```

But I'm stuck, got this error:

```
Traceback (most recent call last):
  File "D:\text-generation-webui\modules\callbacks.py", line 61, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui\modules\text_generation.py", line 377, in generate_with_callback
    shared.model.generate(**kwargs)
  File "D:\anaconda3\envs\textgen\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\textgen\Lib\site-packages\transformers\generation\utils.py", line 1455, in generate
    return self.assisted_decoding(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\textgen\Lib\site-packages\transformers\generation\utils.py", line 4367, in assisted_decoding
    new_logits[:, i, :] = logits_processor(candidate_input_ids[:, : cur_len + i], new_logits[:, i, :])
                                                                                  ~~~~~~~~~~^^^^^^^^^
IndexError: index 1 is out of bounds for dimension 1 with size 1
```

**Comment by oobabooga** [comment]
https://github.com/oobabooga/text-generation-webui/pull/5296

For llamacpp_HF to work it's necessary to better integrate llama.cpp with transformers by using `past_key_values` correctly in the forward call and I don't know how to do that (exllamav2_HF faces the same problem).
