### ISSUE TITLE
ModuleNotFoundError: No module named 'awq'

### ISSUE THREAD

**Issue by RoyalCyan** [oobabooga/text-generation-webui#5294]
### Describe the bug

When I load a model I get this error: `ModuleNotFoundError: No module named 'awq'`
I haven't yet tried to load other models as I have a very slow internet, but once I download others I will post an update.
During the installation proccess I made sure to pick option D (for Intel GPUs). I have already tried to reinstall, but got same results.
I have also made sure that `autoawq `is installed by running `pip install autoawq` in terminal.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Fresh install of Text generation webui
2. Try to load a module. I used "TheBloke_LLaMA2-13B-Estopia-AWQ"

### Logs

```shell
19:56:44-328915 INFO     Starting Text generation web UI
19:56:44-332636 INFO     Loading the extension "gallery"
C:\Users\Rudolf\Rakendused\AI\text-generation-webui\text-generation-webui\installer_files\env\Lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\Users\Rudolf\Rakendused\AI\text-generation-webui\text-generation-webui\installer_files\env\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
No CUDA runtime is found, using CUDA_HOME='C:\Users\Rudolf\Rakendused\AI\text-generation-webui\text-generation-webui\installer_files\env'
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
19:57:18-679312 INFO     Loading TheBloke_LLaMA2-13B-Estopia-AWQ
19:57:18-700313 ERROR    Failed to load the model.
Traceback (most recent call last):
  File "C:\Users\Rudolf\Rakendused\AI\text-generation-webui\text-generation-webui\modules\ui_model_menu.py", line 213, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rudolf\Rakendused\AI\text-generation-webui\text-generation-webui\modules\models.py", line 87, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rudolf\Rakendused\AI\text-generation-webui\text-generation-webui\modules\models.py", line 307, in AutoAWQ_loader
    from awq import AutoAWQForCausalLM
ModuleNotFoundError: No module named 'awq'
```

### System Info

```shell
OS: Windows 11 Pro N 22H2
CPU: Intel i7-12700KF
RAM: 32 GB
GPU: Intel Arc A770 16 GB
```

**Comment by Muhsigbokz** [comment]
Hey,

while I did not properly fix it, I at least managed to move to another error *on my system*. On the end of the `start_linux.sh`, I commented out the `python one_click.py` line and added some `whereis`, can it with `bash -x  start_linux.sh` and got

```
+ whereis python
python: /usr/bin/python /home/somehweredevelopment/text-generation-webui/installer_files/env/bin/python /usr/share/man/man1/python.1.gz
+ whereis pip3
pip3: /usr/bin/pip3 /home/somehwere/development/text-generation-webui/installer_files/env/bin/pip3 /home/mlw/.local/bin/pip3 /usr/share/man/man1/pip3.1.gz
```

It runs in its own venv. To install autoawq, I added the install command within the start_linux.sh, and moved to another error... but that I will have to fix for myself.
