### ISSUE TITLE
Describe this "torch.cuda.OutOfMemoryError: CUDA out of memory."

### ISSUE THREAD

**Issue by Anujjake** [oobabooga/text-generation-webui#5306]
### Describe the bug

Traceback (most recent call last):

File "C:\Users\Anuj\text-generation-webui\modules\ui_model_menu.py", line 213, in load_model_wrapper

shared.model, shared.tokenizer = load_model(selected_model, loader)

                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "C:\Users\Anuj\text-generation-webui\modules\models.py", line 87, in load_model

output = load_func_map[loader](model_name)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "C:\Users\Anuj\text-generation-webui\modules\models.py", line 389, in ExLlamav2_HF_loader

return Exllamav2HF.from_pretrained(model_name)

       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "C:\Users\Anuj\text-generation-webui\modules\exllamav2_hf.py", line 170, in from_pretrained

return Exllamav2HF(config)

       ^^^^^^^^^^^^^^^^^^^

File "C:\Users\Anuj\text-generation-webui\modules\exllamav2_hf.py", line 44, in init

self.ex_model.load(split)

File "C:\Users\Anuj.conda\envs\textgen\Lib\site-packages\exllamav2\model.py", line 244, in load

for item in f: return item

File "C:\Users\Anuj.conda\envs\textgen\Lib\site-packages\exllamav2\model.py", line 263, in load_gen

module.load()

File "C:\Users\Anuj.conda\envs\textgen\Lib\site-packages\exllamav2\moe_mlp.py", line 61, in load

self.w3[e].load()

File "C:\Users\Anuj.conda\envs\textgen\Lib\site-packages\exllamav2\linear.py", line 45, in load

if w is None: w = self.load_weight()

                  ^^^^^^^^^^^^^^^^^^

File "C:\Users\Anuj.conda\envs\textgen\Lib\site-packages\exllamav2\module.py", line 92, in load_weight

qtensors = self.load_multi(["qweight", "qzeros", "scales", "g_idx"])

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "C:\Users\Anuj.conda\envs\textgen\Lib\site-packages\exllamav2\module.py", line 75, in load_multi

tensors[k] = st.get_tensor(self.key + "." + k).to(self.device())

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 28.00 MiB. GPU 0 has a total capacty of 3.00 GiB of which 0 bytes is free. Of the allocated memory 10.98 GiB is allocated by PyTorch, and 19.06 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I'm trying to run "TheBloke_Open_Gpt4_8x7B_v0.2-GPTQ" in my Local using Text Generation. My system is running of AMD Ryzen 5 3550H with 20GB RAM and 3GB of NVIDIA Graphics. 

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/31917727/9d12ba74-e0cc-4ae2-b7dd-a908bc2c4343)

### Logs

```shell
(base) C:\Users\Anuj>conda activate textgen

(textgen) C:\Users\Anuj>cd text-generation-webui

(textgen) C:\Users\Anuj\text-generation-webui>python server.py
20:49:53-790820 INFO     Starting Text generation web UI
20:49:53-800820 INFO     Loading the extension "gallery"
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
20:50:23-725648 INFO     Loading TheBloke_Open_Gpt4_8x7B_v0.2-GPTQ
20:51:01-961475 ERROR    Failed to load the model.
Traceback (most recent call last):
  File "C:\Users\Anuj\text-generation-webui\modules\ui_model_menu.py", line 213, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anuj\text-generation-webui\modules\models.py", line 87, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anuj\text-generation-webui\modules\models.py", line 389, in ExLlamav2_HF_loader
    return Exllamav2HF.from_pretrained(model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anuj\text-generation-webui\modules\exllamav2_hf.py", line 170, in from_pretrained
    return Exllamav2HF(config)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anuj\text-generation-webui\modules\exllamav2_hf.py", line 44, in __init__
    self.ex_model.load(split)
  File "C:\Users\Anuj\.conda\envs\textgen\Lib\site-packages\exllamav2\model.py", line 244, in load
    for item in f: return item
  File "C:\Users\Anuj\.conda\envs\textgen\Lib\site-packages\exllamav2\model.py", line 263, in load_gen
    module.load()
  File "C:\Users\Anuj\.conda\envs\textgen\Lib\site-packages\exllamav2\moe_mlp.py", line 61, in load
    self.w3[e].load()
  File "C:\Users\Anuj\.conda\envs\textgen\Lib\site-packages\exllamav2\linear.py", line 45, in load
    if w is None: w = self.load_weight()
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anuj\.conda\envs\textgen\Lib\site-packages\exllamav2\module.py", line 92, in load_weight
    qtensors = self.load_multi(["qweight", "qzeros", "scales", "g_idx"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anuj\.conda\envs\textgen\Lib\site-packages\exllamav2\module.py", line 75, in load_multi
    tensors[k] = st.get_tensor(self.key + "." + k).to(self.device())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 28.00 MiB. GPU 0 has a total capacty of 3.00 GiB of which 0 bytes is free. Of the allocated memory 10.98 GiB is allocated by PyTorch, and 19.06 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### System Info

```shell
Windows 10 
AMD Ryzen 5 3550H with 20GB RAM and 3GB of NVIDIA Graphics
```

**Comment by Anujjake** [comment]
FYI I'm using Dolphin Mixtral in WSL using Ollama and it's working fine.

**Comment by araleza** [comment]
You're loading a GPTQ version of the model. Those are designed to fit fully in GPU VRAM only, and the model you've chosen is far too big for that. You should use a GGUF version of models instead.

You also have very little CPU memory (only 20GB), so this big 8x7B model you've downloaded is probably is too large for your system in general. Try finding a smaller model to use.

**Comment by coolboyqu** [comment]
> You're loading a GPTQ version of the model. Those are designed to fit fully in GPU VRAM only, and the model you've chosen is far too big for that. You should use a GGUF version of models instead.
> 
> You also have very little CPU memory (only 20GB), so this big 8x7B model you've downloaded is probably is too large for your system in general. Try finding a smaller model to use.

the same question, can I load the model on different GPU?I have 2 GPUs, but the model only load on GPU 0, and when I set gpu-split, the system raise "Insufficient space in device allocation"
