### ISSUE TITLE
Can you upgrade python llamma cpp to 0.2.31 I'm getting python loading errors on newer models

### ISSUE THREAD

**Issue by NonaSuomy** [oobabooga/text-generation-webui#5314]
### Describe the bug

https://huggingface.co/acon96/Home-3B-v2-GGUF/resolve/main/Home-3B-v2.q8_0.gguf

The v1 model loaded fine but when you try to load the v2 model you get multiple python errors.

https://github.com/abetlen/llama-cpp-python/releases/tag/v0.2.31

Maybe tell upgrade_ files to compile from source.

If not I attempted to do this myself like this for AMD GPU

```bash
mkdir code
cd code
git clone https://github.com/abetlen/llama-cpp-python
cd llama-cpp-python
git submodule update --init --recursive
rm -rf _skbuild/
CMAKE_ARGS="-DLLAMA_HIPBLAS=ON -DCMAKE_C_COMPILER=/opt/rocm/llvm/bin/clang -DCMAKE_CXX_COMPILER=/opt/rocm/llvm/bin/clang++ -DCMAKE_PREFIX_PATH=/opt/rocm -DAMDGPU_TARGETS=gfx900" FORCE_CMAKE=1 python -m pip install .
cd ../../
python one_click.py --update && echo -e "\nDone!"
```

Which worked...

```
from llama_cpp import Llama
llm = Llama(model_path="../models/Home-3B-v2.q8_0.gguf")
output = llm(
      "Q: Name the planets in the solar system? A: ", # Prompt
      max_tokens=32, # Generate up to 32 tokens
      #stop=["Q:", "\n"], # Stop generating just before the model would generate a new question
      echo=True # Echo the prompt back in the output
) # Generate a completion, can also call create_completion
print(output)
```
```
python3 llamatest.py
llama_model_loader: loaded meta data with 19 key-value pairs and 453 tensors from ../models/Home-3B-v2.q8_0.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = phi2
llama_model_loader: - kv   1:                               general.name str              = Phi2
llama_model_loader: - kv   2:                        phi2.context_length u32              = 2048
llama_model_loader: - kv   3:                      phi2.embedding_length u32              = 2560
llama_model_loader: - kv   4:                   phi2.feed_forward_length u32              = 10240
llama_model_loader: - kv   5:                           phi2.block_count u32              = 32
llama_model_loader: - kv   6:                  phi2.attention.head_count u32              = 32
llama_model_loader: - kv   7:               phi2.attention.head_count_kv u32              = 32
llama_model_loader: - kv   8:          phi2.attention.layer_norm_epsilon f32              = 0.000010
llama_model_loader: - kv   9:                  phi2.rope.dimension_count u32              = 32
llama_model_loader: - kv  10:                          general.file_type u32              = 7
llama_model_loader: - kv  11:               tokenizer.ggml.add_bos_token bool             = false
llama_model_loader: - kv  12:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  13:                      tokenizer.ggml.tokens arr[str,51200]   = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  14:                  tokenizer.ggml.token_type arr[i32,51200]   = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  15:                      tokenizer.ggml.merges arr[str,50000]   = ["Ġ t", "Ġ a", "h e", "i n", "r e",...
llama_model_loader: - kv  16:                tokenizer.ggml.bos_token_id u32              = 50296
llama_model_loader: - kv  17:                tokenizer.ggml.eos_token_id u32              = 50297
llama_model_loader: - kv  18:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:  259 tensors
llama_model_loader: - type q8_0:  194 tensors
llm_load_vocab: mismatch in special tokens definition ( 910/51200 vs 944/51200 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = phi2
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 51200
llm_load_print_meta: n_merges         = 50000
llm_load_print_meta: n_ctx_train      = 2048
llm_load_print_meta: n_embd           = 2560
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 32
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 32
llm_load_print_meta: n_embd_head_k    = 80
llm_load_print_meta: n_embd_head_v    = 80
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: n_embd_k_gqa     = 2560
llm_load_print_meta: n_embd_v_gqa     = 2560
llm_load_print_meta: f_norm_eps       = 1.0e-05
llm_load_print_meta: f_norm_rms_eps   = 0.0e+00
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 10240
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 2048
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 3B
llm_load_print_meta: model ftype      = Q8_0
llm_load_print_meta: model params     = 2.78 B
llm_load_print_meta: model size       = 2.75 GiB (8.51 BPW)
llm_load_print_meta: general.name     = Phi2
llm_load_print_meta: BOS token        = 50296 '<|im_start|>'
llm_load_print_meta: EOS token        = 50297 '<|im_end|>'
llm_load_print_meta: LF token         = 128 'Ä'
llm_load_tensors: ggml ctx size =    0.17 MiB
llm_load_tensors: offloading 0 repeating layers to GPU
llm_load_tensors: offloaded 0/33 layers to GPU
llm_load_tensors:        CPU buffer size =  2819.28 MiB
.............................................................................................
llama_new_context_with_model: n_ctx      = 512
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:        CPU KV buffer size =   160.00 MiB
llama_new_context_with_model: KV self size  =  160.00 MiB, K (f16):   80.00 MiB, V (f16):   80.00 MiB
llama_new_context_with_model: graph splits (measure): 1
llama_new_context_with_model:        CPU compute buffer size =   105.00 MiB
AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 |

llama_print_timings:        load time =     928.69 ms
llama_print_timings:      sample time =      19.07 ms /    32 runs   (    0.60 ms per token,  1678.12 tokens per second)
llama_print_timings: prompt eval time =     928.66 ms /    14 tokens (   66.33 ms per token,    15.08 tokens per second)
llama_print_timings:        eval time =    5504.37 ms /    31 runs   (  177.56 ms per token,     5.63 tokens per second)
llama_print_timings:       total time =    6560.19 ms /    45 tokens
{'id': 'cmpl-a4fb69c8-32cc-42ba-aa7e-55f28af79fa7', 'object': 'text_completion', 'created': 1705659782, 'model': '../models/Home-3B-v2.q8_0.gguf', 'choices': [{'text': 'Q: Name the planets in the solar system? A: \n\nThe eight planets in our solar system, listed by their distance from the sun, are as follows:\n\n1. Mercury\n2. Venus\n', 'index': 0, 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 14, 'completion_tokens': 32, 'total_tokens': 46}}
```

But I have no idea where to put this or how to tell text-generation-webui to use the system install of llama-cpp-python instead of the ones here 

If someone knows please let me know.

I tried to dump it in here `/home/nonasuomy/code/text-generation-webui/installer_files/env/lib/python3.11/site-packages/` replacing llamacpp_cpp_cuda but it didn't work and gave me some different errors.

Thank you.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load model v2 it will get this error load model v1 won't.

### Logs

```shell
Traceback (most recent call last):

File "/home/nonasuomy/code/text-generation-webui/modules/ui_model_menu.py", line 213, in load_model_wrapper


shared.model, shared.tokenizer = load_model(selected_model, loader)

                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/nonasuomy/code/text-generation-webui/modules/models.py", line 87, in load_model


output = load_func_map[loader](model_name)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/nonasuomy/code/text-generation-webui/modules/models.py", line 250, in llamacpp_loader


model, tokenizer = LlamaCppModel.from_pretrained(model_file)

                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/nonasuomy/code/text-generation-webui/modules/llamacpp_model.py", line 101, in from_pretrained


result.model = Llama(**params)

               ^^^^^^^^^^^^^^^
File "/home/nonasuomy/code/text-generation-webui/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda/llama.py", line 962, in init


self._n_vocab = self.n_vocab()

                ^^^^^^^^^^^^^^
File "/home/nonasuomy/code/text-generation-webui/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda/llama.py", line 2274, in n_vocab


return self._model.n_vocab()

       ^^^^^^^^^^^^^^^^^^^^^
File "/home/nonasuomy/code/text-generation-webui/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda/llama.py", line 251, in n_vocab


assert self.model is not None

       ^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```
```


### System Info

```shell
AMD Vega64 Unbuntu 22
```

**Comment by markmghali** [comment]
yes I am having the same issue. Thank you

**Comment by NonaSuomy** [comment]
@markmghali a person named @c0laborator nudged me that there is a 0.2.29 branch which is working now for me.

```
git clone https://github.com/oobabooga/text-generation-webui.git
cd text-generation-webui
git checkout -b llamacpp_0.2.29 origin/llamacpp_0.2.29
git branch
git pull
echo "--listen --api --model Home-3B-v2.q8_0.gguf --n-gpu-layers 33" >> CMD_FLAGS.txt
./start_linux.sh
```

**Comment by markmghali** [comment]
Thank you! I'll have to check it out👍
