### ISSUE TITLE
Failed to load the model

### ISSUE THREAD

**Issue by YoavOne** [oobabooga/text-generation-webui#5319]
### Describe the bug

Wile trying to load the module i get 3 errors and i get this

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

i install the module then i try to load it it fails

### Logs

```shell
06:40:09-083659 INFO     Loading TheBloke_Yarn-Mistral-7B-128k-AWQ
06:40:09-099413 ERROR    Failed to load the model.
Traceback (most recent call last):
  File "C:\Bagel\text-generation-webui\modules\ui_model_menu.py", line 213, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Bagel\text-generation-webui\modules\models.py", line 87, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Bagel\text-generation-webui\modules\models.py", line 307, in AutoAWQ_loader
    from awq import AutoAWQForCausalLM
ModuleNotFoundError: No module named 'awq'
```

### System Info

```shell
Windows 11 Pro 22H2 os build 22621.3007
Ryzen 5 5800X
32Gb ddr 4 ram running dual channel
Inetl Ark A770
```

**Comment by ResearchForumOnline** [comment]
Try other versions like the qt ones I am using ggfu versions they only seems to load for me on linux.

**Comment by sandyis** [comment]
@YoavOne can you check if `awq` is installed ?
`pip list | grep -i awq`

to install `pip install awq`

or like previous comment mentioned `ggfu` and `hf` models work for sure

**Comment by YoavOne** [comment]
ok so i have already tried pip install awq and it would give me the error message ERROR: Could not find a version that satisfies the requirement awq (from versions: none)
ERROR: No matching distribution found for awq
i have tried pip list | grep -i awq nothing happens but i believe  it might be all my mistake sins im running a newer version of phyton the latest actually version 3.12.1 instead of 3.10.6 i will se if this fixes my issue

**Comment by ResearchForumOnline** [comment]
> ok so i have already tried pip install awq and it would give me the error message ERROR: Could not find a version that satisfies the requirement awq (from versions: none) ERROR: No matching distribution found for awq i have tried pip list | grep -i awq nothing happens but i believe it might be all my mistake sins im running a newer version of phyton the latest actually version 3.12.1 instead of 3.10.6 i will se if this fixes my issue

I am noticing most of the people with issues are using Windows, linux seems like a safe bet.

**Comment by sandyis** [comment]
> ok so i have already tried pip install awq and it would give me the error message ERROR: Could not find a version that satisfies the requirement awq (from versions: none) ERROR: No matching distribution found for awq i have tried pip list | grep -i awq nothing happens but i believe it might be all my mistake sins im running a newer version of phyton the latest actually version 3.12.1 instead of 3.10.6 i will se if this fixes my issue

@YoavOne You might want to look into setting up a virtual environment, using Conda or Pyenv, that way it will be isolated from your current install. 

Note:Pyenv does not officially support Windows and does not work in Windows outside the Windows Subsystem for Linux.

**Comment by RoyalCyan** [comment]
I have the exact same issue and also running an Intel Arc A770. I have manually compiled awq-llm according to its github page and also tried to install autoawq via pip. The installation was successful but the problem remained unsolved. I still get the same error. Have you managed to solve it?

BTW GGUF models do indeed work, but extremely slowly for some reason. And off-loading to GPU doesn't work. I would rather get my GPU to run with this webui, because it would be a lot faster.
