### ISSUE TITLE
"--load-in-8bit" failed to boot in windows10 on rtx3060

### ISSUE THREAD

**Issue by Ethan-Ming** [oobabooga/text-generation-webui#532]
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
E:\LLaMs\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('E')}
  warn(msg)
E:\LLaMs\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: E:\LLaMs\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
E:\LLaMs\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/E'), WindowsPath('/LLaMs/one-click-installers-oobabooga-windows/one-click-installers-oobabooga-windows/installer_files/env/etc/xml/catalog'), WindowsPath('file')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
E:\LLaMs\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(msg)
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
E:\LLaMs\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
E:\LLaMs\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Loading binary E:\LLaMs\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: Loading binary E:\LLaMs\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: Loading binary E:\LLaMs\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Traceback (most recent call last):
  File "E:\LLaMs\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\text-generation-webui\server.py", line 234, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "E:\LLaMs\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\text-generation-webui\modules\models.py", line 159, in load_model
    model = AutoModelForCausalLM.from_pretrained(checkpoint, **params)
  File "E:\LLaMs\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "E:\LLaMs\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2503, in from_pretrained
    from .utils.bitsandbytes import get_keys_to_not_convert, replace_8bit_linear
  File "E:\LLaMs\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\transformers\utils\bitsandbytes.py", line 7, in <module>
    import bitsandbytes as bnb
  File "E:\LLaMs\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\__init__.py", line 7, in <module>
    from .autograd._functions import (
  File "E:\LLaMs\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\autograd\__init__.py", line 1, in <module>
    from ._functions import undo_layout, get_inverse_transform_indices
  File "E:\LLaMs\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\autograd\_functions.py", line 9, in <module>
    import bitsandbytes.functional as F
  File "E:\LLaMs\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "E:\LLaMs\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py", line 22, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues
Press any key to continue . . .

**Comment by RoARene317** [comment]
1. First of all , have you install CUDA toolkit and cuDNN and add into Environment path?
2. I recommend to switch to WSL for windows, it's much easier to setup.

**Comment by RoARene317** [comment]
> yes, i'm sure it's running because i needed the same thing for my Stable Diffusion extensions (which is working)
I recommend to create a different conda environment to prevent any conflict with your main environment
>Sorry if this is a noob question, but how do I use WSL? Is there any wiki or guide ?
WSL is Windows Subsystem For Linux. It's available for Windows 10 Pro. You can enable it by going into control panel >> Program and Features >> Turn Windows Features on / off >> Tick Windows Subsystem for Linux >> Wait for a couple of seconds, restart if required >> Open Microsoft Store and then search for Ubuntu >> Do the text generation using linux.

**Comment by dstults** [comment]
WSL is actually much harder to set up and use. Python works in Windows just fine. If you can't get it to work natively then odds are 70% of people going forward won't be able to use it from a clean install either.

Try installing manually, if it still fails, then report what continues to be wrong, if it's the same report back then there's definitely a problem:

1. Launch micromamba environment

Get this batch from the windows install files:
```
micromamba-cmd.bat
```

2. Clone (which you've already done most likely) and change directories

```
git clone https://github.com/oobabooga/text-generation-webui
cd text-generation-webui
```

2. Install torch

Get the proper command from here: https://pytorch.org/get-started/locally/
Note you most likely want to use the second one below:
```
REM either -- CPU
pip3 install torch torchvision torchaudio

REM or -- GPU
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117
```

4. Install requirements

```
pip install -r requirements.txt
```

If it still fails then there is a problem somewhere.
