### ISSUE TITLE
LoRa Training error on 4bit quantized

### ISSUE THREAD

**Issue by TheRealMiRRoRMaN** [oobabooga/text-generation-webui#5330]
### Describe the bug

Training error on 4bit quantized

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I tried to train a LoRa on this model:

https://huggingface.co/TheBloke/Wizard-Vicuna-13B-Uncensored-GPTQ

I realized that this has been an issue with quantized models, I also tried the bit where you change the one like in non fused but it didn't work. I'm hoping theres a fix. I also wonder if maybe theres a way to convert my old LoRa to work with the quantized model. If thats possible. 

### Logs

```shell
ile "D:\text-generation-webui-main\modules\training.py", line 544, in do_train


lora_model = get_peft_model(shared.model, config)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\MiRR0RMaN.conda\envs\textgen\Lib\site-packages\peft\mapping.py", line 133, in get_peft_model


return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)

       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\MiRR0RMaN.conda\envs\textgen\Lib\site-packages\peft\peft_model.py", line 1043, in init


super().__init__(model, peft_config, adapter_name)
File "C:\Users\MiRR0RMaN.conda\envs\textgen\Lib\site-packages\peft\peft_model.py", line 125, in init


self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)

                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\MiRR0RMaN.conda\envs\textgen\Lib\site-packages\peft\tuners\lora\model.py", line 111, in init


super().__init__(model, config, adapter_name)
File "C:\Users\MiRR0RMaN.conda\envs\textgen\Lib\site-packages\peft\tuners\tuners_utils.py", line 90, in init


self.inject_adapter(self.model, adapter_name)
File "C:\Users\MiRR0RMaN.conda\envs\textgen\Lib\site-packages\peft\tuners\tuners_utils.py", line 250, in inject_adapter


raise ValueError(
ValueError: Target modules {'q_proj', 'v_proj'} not found in the base model. Please check the target modules and try again.
```

### System Info

```shell
Win 10 with 3090 graphics card
```

**Comment by Ph0rk0z** [comment]
Are you able to inference this model? It is 8 months old. It smells like GPTQ v1.

**Comment by TheRealMiRRoRMaN** [comment]
> Are you able to inference this model? It is 8 months old. It smells like GPTQ v1.

you mean if its working? oh yes this model is working fine? i'm sorry if i misunderstood you reply, i'm not too sure what you meant?

**Comment by Ph0rk0z** [comment]
It's a very old model. There was an original version of GPTQ and there is no good way to tell without downloading it. Anyhow, you have to train with "monkeypatch" or using autogptq via transformers without exllama or exllamav2 enabled. Consider also https://github.com/johnsmith0031/alpaca_lora_4bit or axolotl.

**Comment by TheRealMiRRoRMaN** [comment]
> It's a very old model. There was an original version of GPTQ (v1) and there is no good way to tell without downloading it. Anyhow, you have to train with "monkeypatch" or using autogptq via transformers without exllama or exllamav2 enabled. Consider also https://github.com/johnsmith0031/alpaca_lora_4bit or axolotl.

I'll try all of that and get back to you. I hope I'll be able to answer that its working.

**Comment by Ph0rk0z** [comment]
Well I got no clue which one this is, you have to install the pip package from alpac_lora_4bit to use monkeypatch and which version of autogptq you got, etc.

**Comment by TheRealMiRRoRMaN** [comment]
> Well I got no clue which one this is, you have to install the pip package from alpac_lora_4bit to use monkeypatch and which version of autogptq you got, etc.

tried that just now everything went swimmingly until i started trying to start the server inside the dir just like specified there and yes the first line changed to what they said i get this:

───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ d:\alpaca_lora_4bit\text-generation-webui\server.py:1 in <module>                                                    │
│                                                                                                                      │
│ ❱   1 import custom_monkey_patch # apply monkey patch                                                                │
│     2 import os                                                                                                      │
│                                                                                                                      │
│ d:\alpaca_lora_4bit\text-generation-webui\custom_monkey_patch.py:39 in <module>                                      │
│                                                                                                                      │
│   38 # Monkey Patch                                                                                                  │
│ ❱ 39 from modules import models as modelz                                                                            │
│   40 from modules import shared                                                                                      │
│                                                                                                                      │
│ d:\alpaca_lora_4bit\text-generation-webui\modules\models.py:26 in <module>                                           │
│                                                                                                                      │
│    25 from modules.logging_colors import logger                                                                      │
│ ❱  26 from modules.models_settings import get_model_metadata                                                         │
│    27 from modules.relative_imports import RelativeImport                                                            │
│                                                                                                                      │
│ d:\alpaca_lora_4bit\text-generation-webui\modules\models_settings.py:7 in <module>                                   │
│                                                                                                                      │
│     6                                                                                                                │
│ ❱   7 from modules import chat, loaders, metadata_gguf, shared, ui                                                   │
│     8                                                                                                                │
│                                                                                                                      │
│ d:\alpaca_lora_4bit\text-generation-webui\modules\chat.py:20 in <module>                                             │
│                                                                                                                      │
│    19 from modules.logging_colors import logger                                                                      │
│ ❱  20 from modules.text_generation import (                                                                          │
│    21     generate_reply,                                                                                            │
│                                                                                                                      │
│ d:\alpaca_lora_4bit\text-generation-webui\modules\text_generation.py:25 in <module>                                  │
│                                                                                                                      │
│    24 from modules.logging_colors import logger                                                                      │
│ ❱  25 from modules.models import clear_torch_cache, local_rank                                                       │
│    26                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'clear_torch_cache' from partially initialized module 'modules.models' (most likely due
to a circular import) (d:\alpaca_lora_4bit\text-generation-webui\modules\models.py)

**Comment by sandyis** [comment]
@TheRealMiRRoRMaN this should explain `https://github.com/oobabooga/text-generation-webui/discussions/5200#discussioncomment-8042411`
model used is not compatible

**Comment by Ph0rk0z** [comment]
>I cant install triton since im on windows btw

that's gonna stop you from using autogptq.

https://github.com/oobabooga/text-generation-webui/wiki/08-%E2%80%90-Additional-Tips#using-loras-with-gptq-for-llama

**Comment by TheRealMiRRoRMaN** [comment]
> @TheRealMiRRoRMaN this should explain `https://github.com/oobabooga/text-generation-webui/discussions/5200#discussioncomment-8042411` model used is not compatible

When I do that I get:

----
C:\Users\MiRR0RMaN\AppData\Roaming\Python\Python311\site-packages\torch\utils\checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
Exception in thread Thread-6 (threaded_run):
Traceback (most recent call last):
  File "C:\Users\MiRR0RMaN\.conda\envs\textgen\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\MiRR0RMaN\.conda\envs\textgen\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "D:\text-generation-webui-main\modules\training.py", line 698, in threaded_run
    trainer.train()
  File "C:\Users\MiRR0RMaN\.conda\envs\textgen\Lib\site-packages\transformers\trainer.py", line 1555, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MiRR0RMaN\.conda\envs\textgen\Lib\site-packages\transformers\trainer.py", line 1910, in _inner_training_loop
    self.optimizer.step()
  File "C:\Users\MiRR0RMaN\.conda\envs\textgen\Lib\site-packages\accelerate\optimizer.py", line 132, in step
    self.scaler.step(self.optimizer, closure)
  File "C:\Users\MiRR0RMaN\AppData\Roaming\Python\Python311\site-packages\torch\cuda\amp\grad_scaler.py", line 413, in step
    len(optimizer_state["found_inf_per_device"]) > 0
AssertionError: No inf checks were recorded for this optimizer.
----



> > I cant install triton since im on windows btw
> 
> that's gonna stop you from using autogptq.
> 
> https://github.com/oobabooga/text-generation-webui/wiki/08-%E2%80%90-Additional-Tips#using-loras-with-gptq-for-llama

Bummer.

**Comment by Ph0rk0z** [comment]
It let you train? Because transformers uses autogptq to train lora and that requires triton last I checked.

**Comment by TheRealMiRRoRMaN** [comment]
yeah it let me train! 

> @TheRealMiRRoRMaN this should explain `https://github.com/oobabooga/text-generation-webui/discussions/5200#discussioncomment-8042411` model used is not compatible

this advice really did the trick!

**Comment by araleza** [comment]
Did you remember to load the GPTQ model with the Transformers loader, with auto-devices and disable_exllama options selected?  You can't train a 4-bit GPTQ in ooba-webui with any other loader.

**Comment by TheRealMiRRoRMaN** [comment]
Twice.
