### ISSUE TITLE
Unable to Load Model using ExLlamav2_HF on M1 MacOS Sonoma

### ISSUE THREAD

**Issue by Type-32** [oobabooga/text-generation-webui#5358]
### Describe the bug

![image](https://github.com/oobabooga/text-generation-webui/assets/87076491/d073a215-7b2d-4ea8-8d1f-8080db5a22e7)
Trying to load the TheBloke/Mythalion-13B-GPTQ Model on an M1 macOS Sonoma macbook pro with the ExLlamav2_HF loader will throw an error. Logs are pasted below. (Works fine on my Windows 11 PC but doesn't work at all on my mac.)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Clone the repository on to a macOS Sonoma with M1 Chip
2. Start the Repository
3. Download TheBloke/Mythalion-13B-GPTQ Model
4. Try load model using ExLlamav2_HF, fails
5. Restart Program
6. Load model again using ExLlamav2_HF, fails
7. Second time try load model using ExLlamav2_HF, fails with a different error

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/87076491/ebe6f375-ae8c-453f-b718-3de62352e7b7)

### Logs

```shell
00:44:47-309532 INFO     Starting Text generation web UI                        
00:44:47-313922 INFO     Loading the extension "gallery"                        
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
00:45:04-985411 INFO     Loading TheBloke_Mythalion-13B-GPTQ                    
No CUDA runtime is found, using CUDA_HOME='/Users/administrator/Documents/AI/text-generation-webui/installer_files/env'
00:45:10-827211 ERROR    Failed to load the model.                              
Traceback (most recent call last):
  File "/Users/administrator/Documents/AI/text-generation-webui/modules/ui_model_menu.py", line 213, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/administrator/Documents/AI/text-generation-webui/modules/models.py", line 87, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/administrator/Documents/AI/text-generation-webui/modules/models.py", line 387, in ExLlamav2_HF_loader
    from modules.exllamav2_hf import Exllamav2HF
  File "/Users/administrator/Documents/AI/text-generation-webui/modules/exllamav2_hf.py", line 7, in <module>
    from exllamav2 import (
  File "/Users/administrator/Documents/AI/text-generation-webui/installer_files/env/lib/python3.11/site-packages/exllamav2/__init__.py", line 3, in <module>
    from exllamav2.model import ExLlamaV2
  File "/Users/administrator/Documents/AI/text-generation-webui/installer_files/env/lib/python3.11/site-packages/exllamav2/model.py", line 17, in <module>
    from exllamav2.cache import ExLlamaV2CacheBase
  File "/Users/administrator/Documents/AI/text-generation-webui/installer_files/env/lib/python3.11/site-packages/exllamav2/cache.py", line 2, in <module>
    from exllamav2.ext import exllamav2_ext as ext_c
  File "/Users/administrator/Documents/AI/text-generation-webui/installer_files/env/lib/python3.11/site-packages/exllamav2/ext.py", line 131, in <module>
    exllamav2_ext = load \
                    ^^^^^^
  File "/Users/administrator/Documents/AI/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1308, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "/Users/administrator/Documents/AI/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/Users/administrator/Documents/AI/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1810, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "/Users/administrator/Documents/AI/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2199, in _write_ninja_file_to_build_library
    cuda_flags = common_cflags + COMMON_NVCC_FLAGS + _get_cuda_arch_flags()
                                                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/administrator/Documents/AI/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1980, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
    ~~~~~~~~~^^^^
IndexError: list index out of range


00:45:52-799363 INFO     Loading TheBloke_Mythalion-13B-GPTQ                    
00:45:52-804243 ERROR    Failed to load the model.                              
Traceback (most recent call last):
  File "/Users/administrator/Documents/AI/text-generation-webui/modules/ui_model_menu.py", line 213, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/administrator/Documents/AI/text-generation-webui/modules/models.py", line 87, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/administrator/Documents/AI/text-generation-webui/modules/models.py", line 387, in ExLlamav2_HF_loader
    from modules.exllamav2_hf import Exllamav2HF
  File "/Users/administrator/Documents/AI/text-generation-webui/modules/exllamav2_hf.py", line 7, in <module>
    from exllamav2 import (
  File "/Users/administrator/Documents/AI/text-generation-webui/installer_files/env/lib/python3.11/site-packages/exllamav2/__init__.py", line 3, in <module>
    from exllamav2.model import ExLlamaV2
  File "/Users/administrator/Documents/AI/text-generation-webui/installer_files/env/lib/python3.11/site-packages/exllamav2/model.py", line 17, in <module>
    from exllamav2.cache import ExLlamaV2CacheBase
  File "/Users/administrator/Documents/AI/text-generation-webui/installer_files/env/lib/python3.11/site-packages/exllamav2/cache.py", line 2, in <module>
    from exllamav2.ext import exllamav2_ext as ext_c
  File "/Users/administrator/Documents/AI/text-generation-webui/installer_files/env/lib/python3.11/site-packages/exllamav2/ext.py", line 131, in <module>
    exllamav2_ext = load \
                    ^^^^^^
  File "/Users/administrator/Documents/AI/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1308, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "/Users/administrator/Documents/AI/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1736, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/administrator/Documents/AI/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2136, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen(/Users/administrator/Library/Caches/torch_extensions/py311_cpu/exllamav2_ext/exllamav2_ext.so, 0x0002): tried: '/Users/administrator/Library/Caches/torch_extensions/py311_cpu/exllamav2_ext/exllamav2_ext.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/administrator/Library/Caches/torch_extensions/py311_cpu/exllamav2_ext/exllamav2_ext.so' (no such file), '/Users/administrator/Library/Caches/torch_extensions/py311_cpu/exllamav2_ext/exllamav2_ext.so' (no such file)
```

### System Info

```shell
macOS Sonoma
Apple M1
Macbook Pro 2021, 16GB RAM, 1TB SSD, pip3, Python 3.12, Node V20.11.0
```

**Comment by Ph0rk0z** [comment]
Not supported on metal.
