### ISSUE TITLE
Cannot load any model

### ISSUE THREAD

**Issue by xevilstar** [oobabooga/text-generation-webui#5363]
### Describe the bug

Dear Maintainers, gods of this program I pray you,

No matter which model I try to install i get always the same error.
I am a n00b and I am just starting to experiment with this so I think (almost certain) I might be missing something here.
It has been almost a month now and I am (so to speak) out of bullets to fire (read around desperate and banging my head against the wall painting it red )

Deeply sorry for my n00bness
xevilstar :)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Click the Model tab.
Under Download custom model or LoRA, copy and paste name/module-name from https://huggingface.co/
Click Download.
The model will start downloading. Once it's finished it will say "Done".
In the top left, click the refresh icon next to Model.
In the Model dropdown, choose the model you just downloaded

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/1389525/1b859136-d5da-4c96-8f27-e37c24345995)

### Logs

```shell
Traceback (most recent call last):

File "/opt/text-generation-webui/modules/ui_model_menu.py", line 213, in load_model_wrapper


shared.model, shared.tokenizer = load_model(selected_model, loader)

                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/text-generation-webui/modules/models.py", line 87, in load_model


output = load_func_map[loader](model_name)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/text-generation-webui/modules/models.py", line 389, in ExLlamav2_HF_loader


return Exllamav2HF.from_pretrained(model_name)

       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/text-generation-webui/modules/exllamav2_hf.py", line 170, in from_pretrained


return Exllamav2HF(config)

       ^^^^^^^^^^^^^^^^^^^
File "/opt/text-generation-webui/modules/exllamav2_hf.py", line 44, in init


self.ex_model.load(split)
File "/opt/text-generation-webui/installer_files/env/lib/python3.11/site-packages/exllamav2/model.py", line 244, in load


for item in f: return item
File "/opt/text-generation-webui/installer_files/env/lib/python3.11/site-packages/exllamav2/model.py", line 263, in load_gen


module.load()
File "/opt/text-generation-webui/installer_files/env/lib/python3.11/site-packages/exllamav2/linear.py", line 45, in load


if w is None: w = self.load_weight()

                  ^^^^^^^^^^^^^^^^^^
File "/opt/text-generation-webui/installer_files/env/lib/python3.11/site-packages/exllamav2/module.py", line 99, in load_weight


tensor = self.load_multi(["weight"])["weight"]

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/text-generation-webui/installer_files/env/lib/python3.11/site-packages/exllamav2/module.py", line 75, in load_multi


tensors[k] = st.get_tensor(self.key + "." + k).to(self.device())

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 626.00 MiB. GPU 0 has a total capacty of 7.78 GiB of which 299.12 MiB is free. Including non-PyTorch memory, this process has 7.00 GiB memory in use. Of the allocated memory 6.77 GiB is allocated by PyTorch, and 71.94 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### System Info

```shell
uname -a
Linux ghost 6.7.1 #1 SMP PREEMPT_DYNAMIC Mon Jan 22 15:27:43 CET 2024 x86_64 GNU/Linux
cat /etc/debian_version 
trixie/sid



vendor_id	: AuthenticAMD
cpu family	: 25
model		: 80
model name	: AMD Ryzen 9 5900HX with Radeon Graphics
stepping	: 0
microcode	: 0xa50000f
cpu MHz		: 400.000
cache size	: 512 KB
physical id	: 0
siblings	: 16
core id		: 7
cpu cores	: 8
apicid		: 15
initial apicid	: 15
fpu		: yes
fpu_exception	: yes
cpuid level	: 16
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm debug_swap
bugs		: sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass srso
bogomips	: 6587.68
TLB size	: 2560 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]


lspci|grep -i vga
01:00.0 VGA compatible controller: NVIDIA Corporation GA104M [GeForce RTX 3070 Mobile / Max-Q] (rev a1)
```

**Comment by mamei16** [comment]
Dear xevilstar, 
your poor NVIDIA RTX 3070 Max-Q simply doesn't have enough GPU memory to fit a model with 13 billion parameters! You now have several options:
1. If you want the whole model plus the context to fit in VRAM, I suggest trying a model with 7 billion parameters. [Here](https://blog.hglooweb.com/gptq-models-vram-usage/) is an overview to get a feel for how much VRAM different GPTQ models need. A 4-bit 7B model should be a good choice for your GPU.
2. If you can live with the model taking a longer time to respond and generate text, you can try downloading [a GGUF model with more than 7B parameters](https://huggingface.co/TheBloke/Wizard-Vicuna-13B-Uncensored-GGUF) and running the model on you CPU only, or offloading only part of the model to the GPU for computation (which should be faster than CPU only).
3. 
Hope this helps and will spare your wall from further headbutts.
