### ISSUE TITLE
Errors when using the grammar feature (llamacpp_hf)

### ISSUE THREAD

**Issue by BadisG** [oobabooga/text-generation-webui#5369]
Hello,
The grammar feature has a problem with this particular model:
https://huggingface.co/Envoid/SensualNousInstructDARETIES-CATA-LimaRP-ZlossDT-SLERP-8x7B

I used this quant:
https://huggingface.co/Artefact2/SensualNousInstructDARETIES-CATA-LimaRP-ZlossDT-SLERP-8x7B-GGUF/blob/main/SensualNousInstructDARETIES-CATA-LimaRP-ZlossDT-SLERP-8x7B-Q5_K_S.gguf

### Logs

```shell
Traceback (most recent call last):
  File "D:\text-generation-webui\modules\callbacks.py", line 61, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui\modules\text_generation.py", line 379, in generate_with_callback
    shared.model.generate(**kwargs)
  File "D:\anaconda3\envs\textgen\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Home\AppData\Roaming\Python\Python311\site-packages\transformers\generation\utils.py", line 1520, in generate
    return self.sample(
           ^^^^^^^^^^^^
  File "C:\Users\Home\AppData\Roaming\Python\Python311\site-packages\transformers\generation\utils.py", line 2630, in sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Home\AppData\Roaming\Python\Python311\site-packages\transformers\generation\logits_process.py", line 97, in __call__
    scores = processor(input_ids, scores)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui\modules\grammar\logits_process.py", line 104, in __call__
    return self.process_logits(input_ids, scores)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui\modules\grammar\logits_process.py", line 97, in process_logits
    self.filter_logits(scores, scores.device)
  File "D:\text-generation-webui\modules\grammar\logits_process.py", line 44, in filter_logits
    logits[~acceptance] = -math.inf
    ~~~~~~^^^^^^^^^^^^^
IndexError: The shape of the mask [1, 32002] at index 1 does not match the shape of the indexed tensor [1, 32000] at index 1
```

### System Info

```shell
Windows 10
```

**Comment by sgsdxzy** [comment]
I met similar problems. I think this is probably caused by tokenizer config adding extra tokens and not handled correctly.

**Comment by jld73** [comment]
I get the same error as Badis on a simple grammar: root ::= "test"
I also get the following error when using this JSON grammar: https://github.com/ggml-org/llama.cpp/blob/master/grammars/json.gbnf
```
Traceback (most recent call last):
  File "D:\LLM\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\queueing.py", line 580, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LLM\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LLM\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1928, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LLM\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1526, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LLM\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 657, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LLM\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 650, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LLM\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LLM\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\LLM\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LLM\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 633, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "D:\LLM\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 816, in gen_wrapper
    response = next(iterator)
               ^^^^^^^^^^^^^^
  File "D:\LLM\text-generation-webui-main\modules\chat.py", line 461, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True, for_ui=True)):
  File "D:\LLM\text-generation-webui-main\modules\chat.py", line 421, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message, for_ui=for_ui):
  File "D:\LLM\text-generation-webui-main\modules\chat.py", line 362, in chatbot_wrapper
    for j, reply in enumerate(generate_reply(prompt, state, stopping_strings=stopping_strings, is_chat=True, for_ui=for_ui)):
  File "D:\LLM\text-generation-webui-main\modules\text_generation.py", line 42, in generate_reply
    for result in _generate_reply(*args, **kwargs):
  File "D:\LLM\text-generation-webui-main\modules\text_generation.py", line 97, in _generate_reply
    for reply in generate_func(question, original_question, seed, state, stopping_strings, is_chat=is_chat):
  File "D:\LLM\text-generation-webui-main\modules\text_generation.py", line 388, in generate_reply_HF
    grammar = initialize_grammar(state['grammar_string'])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LLM\text-generation-webui-main\modules\grammar\grammar_utils.py", line 700, in initialize_grammar
    return IncrementalGrammarConstraint(grammar_string.strip(), start_rule_name="root", tokenizer=shared.tokenizer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LLM\text-generation-webui-main\modules\grammar\grammar_utils.py", line 463, in __init__
    super().__init__(grammar_str, start_rule_name, tokenizer)
  File "D:\LLM\text-generation-webui-main\modules\grammar\grammar_utils.py", line 369, in __init__
    while grammar_encoding[pos] != 0xFFFF:
          ~~~~~~~~~~~~~~~~^^^^^
IndexError: list index out of range
```

**Comment by jokleinn** [comment]
I am also getting this issue with an ExLlamav3_HF-loaded [QwQ-32B-Snowdrop-v0](https://huggingface.co/trashpanda-org/QwQ-32B-Snowdrop-v0), invoking inference through the API endpoint. The shape of the mask tensor vs the shape of the indexed tensor are offset from each other by some small constant value, like what Badis's error message displays.
