### ISSUE TITLE
I ran into an error, I don't understand it because I am new, maybe someone here can help me?

### ISSUE THREAD

**Issue by left1000** [oobabooga/text-generation-webui#5388]
I ran into an error, I don't understand it because I am new, maybe someone here can help me?

So I installed this webui today, I successfully loaded and ran .awq models, and .gguf models and 4bit .gptq models.....

But I cannot load at all 8bit .gptq models. And .awq models all use 4bit, which means, that I can't load any 8bit model into my vram.

I have a 4070ti 12gb vram but the models I am loading have been 7B and have fit.

Here is the error I got, even if no one here knows how to fix it, maybe someone here at least understands what the error is saying, which could help point me in the correct direction :) 

`03:49:35-218744 ERROR    Failed to load the model.
Traceback (most recent call last):
  File "V:\AI-local-LLM-chatbot-stuff-no-spaces-for-miniconda\text-generation-webui-main\modules\ui_model_menu.py", line 213, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "V:\AI-local-LLM-chatbot-stuff-no-spaces-for-miniconda\text-generation-webui-main\modules\models.py", line 87, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "V:\AI-local-LLM-chatbot-stuff-no-spaces-for-miniconda\text-generation-webui-main\modules\models.py", line 389, in ExLlamav2_HF_loader
    return Exllamav2HF.from_pretrained(model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "V:\AI-local-LLM-chatbot-stuff-no-spaces-for-miniconda\text-generation-webui-main\modules\exllamav2_hf.py", line 170, in from_pretrained
    return Exllamav2HF(config)
           ^^^^^^^^^^^^^^^^^^^
  File "V:\AI-local-LLM-chatbot-stuff-no-spaces-for-miniconda\text-generation-webui-main\modules\exllamav2_hf.py", line 44, in __init__
    self.ex_model.load(split)
  File "V:\AI-local-LLM-chatbot-stuff-no-spaces-for-miniconda\text-generation-webui-main\installer_files\env\Lib\site-packages\exllamav2\model.py", line 248, in load
    for item in f: return item
  File "V:\AI-local-LLM-chatbot-stuff-no-spaces-for-miniconda\text-generation-webui-main\installer_files\env\Lib\site-packages\exllamav2\model.py", line 266, in load_gen
    module.load()
  File "V:\AI-local-LLM-chatbot-stuff-no-spaces-for-miniconda\text-generation-webui-main\installer_files\env\Lib\site-packages\exllamav2\attn.py", line 189, in load
    self.q_proj.load()
  File "V:\AI-local-LLM-chatbot-stuff-no-spaces-for-miniconda\text-generation-webui-main\installer_files\env\Lib\site-packages\exllamav2\linear.py", line 51, in load
    self.q_handle = ext.make_q_matrix(w, self.temp_dq)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "V:\AI-local-LLM-chatbot-stuff-no-spaces-for-miniconda\text-generation-webui-main\installer_files\env\Lib\site-packages\exllamav2\ext.py", line 224, in make_q_matrix
    return ext_c.make_q_matrix(w["qweight"],
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: q_weight and gptq_qzeros have incompatible shapes`

**Comment by Ph0rk0z** [comment]
I'm not sure exllama supports 8bit currently. Try with autogptq with exllama stuff disabled.

**Comment by sandyis** [comment]
@left1000  error basic ally means that `q_weight and gptq_qzeros ` are in compatible with the model being loaded
aas @Ph0rk0z  said try something different.  More detail explanation below  curtsy AI below 

 **Error Summary:**

- **Type:** RuntimeError
- **Message:** "q_weight and gptq_qzeros have incompatible shapes"
- **Implication:** Essential arrays for model loading have mismatched dimensions, hindering the process.

**Traceback Analysis:**

- **Origin:** The error stems from a shape mismatch within the `make_q_matrix` function within the `ext.py` module, likely responsible for external model operations.

**Potential Causes and Recommended Actions:**

1. **Corrupt or Incompatible Model File:**
   - **Recommendations:**
     - Redownload the model file from a reliable source.
     - Verify model architecture compatibility with your code.
2. **Version Inconsistencies:**
   - **Recommendations:**
     - Ensure code and model file versions align.
     - Consult ExLlamav2 documentation for compatible configurations.
3. **Missing or Misplaced Files:**
   - **Recommendations:**
     - Confirm the presence and correct location of all model components.
     - Adhere to ExLlamav2's file structure guidelines.
4. **Hardware or Environment Limitations:**
   - **Recommendations:**
     - Allocate sufficient memory for model loading.
     - Verify hardware compatibility with ExLlamav2 requirements.
5. **Code Implementation Errors:**
   - **Recommendations:**
     - Meticulously review code for potential inconsistencies in model loading logic.
     - Consider isolating model loading code for focused debugging.

**Comment by groxaxo** [comment]
same error here, only works with transformers :/
Traceback (most recent call last):

File "/home/op/text-generation-webui/modules/ui_model_menu.py", line 214, in load_model_wrapper

shared.model, shared.tokenizer = load_model(selected_model, loader)

                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/op/text-generation-webui/modules/models.py", line 90, in load_model

output = load_func_map[loader](model_name)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/op/text-generation-webui/modules/models.py", line 310, in ExLlamav2_loader

model, tokenizer = Exllamav2Model.from_pretrained(model_name)

                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/op/text-generation-webui/modules/exllamav2.py", line 85, in from_pretrained

model.load_autosplit(cache)

File "/home/op/miniconda3/envs/textgen/lib/python3.11/site-packages/exllamav2/model.py", line 515, in load_autosplit

for item in f:

File "/home/op/miniconda3/envs/textgen/lib/python3.11/site-packages/exllamav2/model.py", line 616, in load_autosplit_gen

module.load()

File "/home/op/miniconda3/envs/textgen/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context

return func(*args, **kwargs)

       ^^^^^^^^^^^^^^^^^^^^^

File "/home/op/miniconda3/envs/textgen/lib/python3.11/site-packages/exllamav2/attn.py", line 246, in load

self.q_proj.load(device_context = device_context)

File "/home/op/miniconda3/envs/textgen/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context

return func(*args, **kwargs)

       ^^^^^^^^^^^^^^^^^^^^^

File "/home/op/miniconda3/envs/textgen/lib/python3.11/site-packages/exllamav2/linear.py", line 160, in load

self.q_handle = ext.make_q_matrix(w,

                ^^^^^^^^^^^^^^^^^^^^

File "/home/op/miniconda3/envs/textgen/lib/python3.11/site-packages/exllamav2/ext.py", line 396, in make_q_matrix

return ext_c.make_q_matrix(

       ^^^^^^^^^^^^^^^^^^^^

RuntimeError: q_weight and gptq_qzeros have incompatible shapes
