### ISSUE TITLE
inconsistencies in memory allocation arguments depending on CPU use

### ISSUE THREAD

**Issue by quarterturn** [oobabooga/text-generation-webui#539]
### Describe the bug

Command-line arguments used to specify memory are not consistent and documentation does not match.

Examples:
Specify just --gpu-memory - uses the values as 'GB'
```
$ python server.py --model llama-30b  --gpu-memory 14 14 --load-in-8bit --chat --listen
Loading llama-30b...
```

Specify both --gpu-memory and --cpu-memory -  ValueError exception
```
$ python server.py --model llama-30b  --gpu-memory 14 14 --cpu-memory 110 --load-in-8bit --chat --listen
Loading llama-30b...
Traceback (most recent call last):
  File "/home/qtr/text-generation-webui/server.py", line 234, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/qtr/text-generation-webui/modules/models.py", line 152, in load_model
    params['device_map'] = infer_auto_device_map(
  File "/home/qtr/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 544, in infer_auto_device_map
    max_memory = get_max_memory(max_memory)
  File "/home/qtr/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 360, in get_max_memory
    max_memory[key] = convert_file_size_to_int(max_memory[key])
  File "/home/qtr/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 73, in convert_file_size_to_int
    raise ValueError("`size` is not in a valid format. Use an integer followed by the unit, e.g., '5GB'.")
ValueError: `size` is not in a valid format. Use an integer followed by the unit, e.g., '5GB'.
```

Use 'MiB' as the memory unit - works
```
python server.py --model llama-30b  --gpu-memory 14000MiB 14000MiB --cpu-memory 110000MiB --load-in-8bit --chat --listen
Loading llama-30b...
```

So, update the help/error message to specify 'MiB' or make the code consistent.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

See description

### Logs

```shell
See description
```

### System Info

```shell
Linux pve 5.15.85-1-pve #1 SMP PVE 5.15.85-1 (2023-02-01T00:00Z) x86_64 GNU/Linux
Debian 11.6
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla P100-PCIE-16GB            On | 00000000:05:00.0 Off |                    0 |
| N/A   33C    P0               32W / 250W|  15406MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE-16GB            On | 00000000:42:00.0 Off |                    0 |
| N/A   34C    P0               31W / 250W|  15556MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
2x Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz
128GB RAM
```

**Comment by Ph0rk0z** [comment]
Try GiB too.
