### ISSUE TITLE
RuntimeError: Failed to import transformers.models.llama.modeling_llama

### ISSUE THREAD

**Issue by HeroMines** [oobabooga/text-generation-webui#5408]
### Describe the bug

When trying to load any LLaMA model in text-generation-webui with the transformers loader, I get an error message due to it failing to import the configuration module for the below reasons. This is using the latest version of Ooba.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Install Ooba
2. Download a LLaMA model (any will do)
3. Try to load it with transformers

### Screenshot

![Screenshot_2024_01_31-3](https://github.com/oobabooga/text-generation-webui/assets/22183857/882b08cb-4d12-410d-b9e2-c9a9f1ab3e81)

### Logs

```shell
Traceback (most recent call last):
  File "/root/miniconda3/envs/textgen/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1364, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/textgen/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/miniconda3/envs/textgen/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 55, in <module>
    from flash_attn import flash_attn_func, flash_attn_varlen_func
  File "/root/miniconda3/envs/textgen/lib/python3.11/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/root/miniconda3/envs/textgen/lib/python3.11/site-packages/flash_attn/flash_attn_interface.py", line 8, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /root/miniconda3/envs/textgen/lib/python3.11/site-packages/flash_attn_2_cuda.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops9_pad_enum4callERKNS_6TensorEN3c108ArrayRefINS5_6SymIntEEElNS5_8optionalIdEE

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/text-generation-webui/modules/ui_model_menu.py", line 213, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/text-generation-webui/modules/models.py", line 87, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/text-generation-webui/modules/models.py", line 235, in huggingface_loader
    model = LoaderClass.from_pretrained(path_to_model, **params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/textgen/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 565, in from_pretrained
    model_class = _get_model_class(config, cls._model_mapping)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/textgen/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 387, in _get_model_class
    supported_models = model_mapping[type(config)]
                       ~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/textgen/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 740, in __getitem__
    return self._load_attr_from_module(model_type, model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/textgen/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 754, in _load_attr_from_module
    return getattribute_from_module(self._modules[module_name], attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/textgen/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 698, in getattribute_from_module
    if hasattr(module, attr):
       ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/textgen/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1354, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/textgen/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1366, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
/root/miniconda3/envs/textgen/lib/python3.11/site-packages/flash_attn_2_cuda.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops9_pad_enum4callERKNS_6TensorEN3c108ArrayRefINS5_6SymIntEEElNS5_8optionalIdEE
```

### System Info

```shell
Runpod 4xA100 SXM
```

**Comment by Ph0rk0z** [comment]
flash attention is broken

**Comment by GiraffeRage** [comment]
Same issue here. Any resolution?

**Comment by hzhangxyz** [comment]
Same here

**Comment by utopia2077** [comment]
have some problem

**Comment by Ph0rk0z** [comment]
Gotta make sure flash attention and torch version match.

**Comment by nastasija-m** [comment]
same here

**Comment by drimeF0** [comment]
same problem

**Comment by yhyu13** [comment]
Hi, all

just install latest packages w/o cuda prebuilt version

pip install flash_attn exllamav2 transformer -U

**Comment by thiagojramos** [comment]
> Hi, all
> 
> just install latest packages w/o cuda prebuilt version
> 
> pip install flash_attn exllamav2 transformer -U

You just forgot to add the 's' at the end of 'transformers'

```shell
pip install flash_attn exllamav2 transformer -U
```

**Comment by sunaarun** [comment]
still facing this same error

**Comment by FatCatPlus** [comment]
it's the error of flash attn 2. Maybe you didn't compile correctly. By selecting abiFALSE version maybe skip this kind of error. Example file name: flash_attn-2.6.3+cu118torch2.4cxx11abiFALSE-cp310-cp310-linux_x86_64.whl

**Comment by yttinalee** [comment]
> Hi, all
> 
> just install latest packages w/o cuda prebuilt version
> 
> pip install flash_attn exllamav2 transformer -U

I met the same issue. This works for me. Thank you.

**Comment by coeuskoalemoss** [comment]
this worked for me: pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu

**Comment by Abhi2april** [comment]
> flash attention is broken

found any solution?

**Comment by vfdff** [comment]
export PYTHONPATH=$PYTHONPATH:/path/to/your/torchair/npu_tuned_model/llm/llama
```
 refer to https://gitee.com/ascend/torchair/blob/master/npu_tuned_model/llm/llama/README.md
```
