### ISSUE TITLE
edge TTS Internet connection

### ISSUE THREAD

**Issue by kalle07** [oobabooga/text-generation-webui#5425]
### Describe the bug

edge TTS Internet connection

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

why no one cares that edge TTS connect to Internet  *bing*

if ia block it the extension dont work ... 

### Logs

```shell
why no one cares that edge TTS connect to Internet  *bing*

if ia block it the extension dont work ... 



23:05:13-300146 ERROR    No speaker selected
Traceback (most recent call last):
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "e:\text-generation-webui\modules\chat.py", line 417, in redraw_html
    return chat_html_wrapper(history, name1, name2, mode, style, character, reset_cache=reset_cache)
  File "e:\text-generation-webui\modules\html_generator.py", line 309, in chat_html_wrapper
    return generate_cai_chat_html(history['visible'], name1, name2, style, character, reset_cache)
  File "e:\text-generation-webui\modules\html_generator.py", line 233, in generate_cai_chat_html
    row = [convert_to_markdown(entry) for entry in _row]
  File "e:\text-generation-webui\modules\html_generator.py", line 233, in <listcomp>
    row = [convert_to_markdown(entry) for entry in _row]
  File "e:\text-generation-webui\modules\html_generator.py", line 53, in convert_to_markdown
    string = re.sub(r'(^|[\n])&gt;', r'\1>', string)
  File "e:\text-generation-webui\installer_files\env\lib\re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
Traceback (most recent call last):
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "e:\text-generation-webui\extensions\edge_tts\script.py", line 100, in toggle_text_in_history
    if visible_reply.startswith('<audio'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "e:\text-generation-webui\modules\chat.py", line 417, in redraw_html
    return chat_html_wrapper(history, name1, name2, mode, style, character, reset_cache=reset_cache)
  File "e:\text-generation-webui\modules\html_generator.py", line 309, in chat_html_wrapper
    return generate_cai_chat_html(history['visible'], name1, name2, style, character, reset_cache)
  File "e:\text-generation-webui\modules\html_generator.py", line 233, in generate_cai_chat_html
    row = [convert_to_markdown(entry) for entry in _row]
  File "e:\text-generation-webui\modules\html_generator.py", line 233, in <listcomp>
    row = [convert_to_markdown(entry) for entry in _row]
  File "e:\text-generation-webui\modules\html_generator.py", line 53, in convert_to_markdown
    string = re.sub(r'(^|[\n])&gt;', r'\1>', string)
  File "e:\text-generation-webui\installer_files\env\lib\re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
Traceback (most recent call last):
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\aiohttp\connector.py", line 1155, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "e:\text-generation-webui\installer_files\env\lib\asyncio\base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "e:\text-generation-webui\installer_files\env\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "e:\text-generation-webui\installer_files\env\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "e:\text-generation-webui\extensions\edge_tts\script.py", line 216, in refresh
    voices = asyncio.run(edge_tts.list_voices())
  File "e:\text-generation-webui\installer_files\env\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "e:\text-generation-webui\installer_files\env\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\edge_tts\list_voices.py", line 27, in list_voices
    async with session.get(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\aiohttp\client.py", line 1167, in __aenter__
    self._resp = await self._coro
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\aiohttp\client.py", line 562, in _request
    conn = await self._connector.connect(
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\aiohttp\connector.py", line 1169, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host speech.platform.bing.com:443 ssl:<ssl.SSLContext object at 0x000002896578C0C0> [getaddrinfo failed]
```

### System Info

```shell
win10
rtx4060
```

**Comment by Ph0rk0z** [comment]
edge is a cloud TTS. I myself don't use it.

**Comment by kalle07** [comment]
i see ...
what is similar good like edge ?

**Comment by Ph0rk0z** [comment]
Xtts or styleTTS2 but you have to use GPU.

**Comment by kalle07** [comment]
thx ... so no simple extention for oobadooga ?
bark or silero are bad qualitiy or very slow even on my RTX  ^^

**Comment by Ph0rk0z** [comment]
There is one for XTTS. check on the subreddit.

**Comment by kalle07** [comment]
thx  i ll try
