### ISSUE TITLE
Cannot load llama in 4 bits on windows

### ISSUE THREAD

**Issue by sowa705** [oobabooga/text-generation-webui#543]
### Describe the bug

I cannot load any model with the webui. I have over 20GB of free memory and i get memory allocation errors

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

run `python server.py --gptq-bits 4 --model llama-13b-hf`

### Logs

```shell
Loading llama-13b-hf...
Traceback (most recent call last):
  File "C:\Users\sowa7\text-generation-webui\server.py", line 234, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\sowa7\text-generation-webui\modules\models.py", line 101, in load_model
    model = load_quantized(model_name)
  File "C:\Users\sowa7\text-generation-webui\modules\GPTQ_loader.py", line 64, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.gptq_bits)
  File "C:\Users\sowa7\text-generation-webui\repositories\GPTQ-for-LLaMa\llama.py", line 238, in load_quant
    make_quant(model, layers, wbits)
  File "C:\Users\sowa7\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 217, in make_quant
    make_quant(child, names, bits, name + '.' + name1 if name != '' else name1)
  File "C:\Users\sowa7\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 217, in make_quant
    make_quant(child, names, bits, name + '.' + name1 if name != '' else name1)
  File "C:\Users\sowa7\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 217, in make_quant
    make_quant(child, names, bits, name + '.' + name1 if name != '' else name1)
  [Previous line repeated 1 more time]
  File "C:\Users\sowa7\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 214, in make_quant
    module, attr, QuantLinear(bits, tmp.in_features, tmp.out_features)
  File "C:\Users\sowa7\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 138, in __init__
    'qweight', torch.zeros((infeatures // 256 * (bits * 8), outfeatures), dtype=torch.int)
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:81] data. DefaultCPUAllocator: not enough memory: you tried to allocate 35389440 bytes.
```

### System Info

```shell
running directly on windows 11 without WSL
Ryzen 5700X, 32GB ram + 32GB swap on ssd
RTX 3070 8GB + P40 24GB
```

**Comment by SaltyBarnacles** [comment]
Were you able to solve this issue? I am also experiencing it.

**Comment by Zambadulio** [comment]
> Were you able to solve this issue? I am also experiencing it.

X2

**Comment by SaltyBarnacles** [comment]
> > Were you able to solve this issue? I am also experiencing it.
> 
> X2

What worked for me was just closing all other programs. Make sure you don't have 2 instances running and you'll be fine.
