### ISSUE TITLE
Error on the Qwen 1.5 series (llamacpp_hf)

### ISSUE THREAD

**Issue by BadisG** [oobabooga/text-generation-webui#5449]
Hello,

https://huggingface.co/Qwen/Qwen1.5-14B-Chat-GGUF
It doesn't seem to work with llamacpp_hf (for the vanilla llamacpp it works fine though)

### Reproduction

Try Qwen1.5 GGUF on llamacpp_hf and use the ChatML prompt format
```
<|im_start|>user
Write a poem about python.<|im_end|>
<|im_start|>assistant
```

### Logs

```shell
Traceback (most recent call last):
  File "D:\text-generation-webui\modules\text_generation.py", line 398, in generate_reply_HF
    new_content = get_reply_from_output_ids(output, state, starting_from=starting_from)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui\modules\text_generation.py", line 282, in get_reply_from_output_ids
    if first_token.startswith('▁'):
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'
```

### System Info

```shell
Windows 10
RTX 3060
```

**Comment by Ph0rk0z** [comment]
Its using llama tokenizer for hf? Try to put original tokenizer in the model's folder.

**Comment by BadisG** [comment]
No, Qwen have their own tokenizer unfortunately (and somehow they never upload their tokenizer.model so...). I tried with llama's tokenizer just for the sake of it and it outputs gibberish.

**Comment by Ph0rk0z** [comment]
It's here: https://huggingface.co/Qwen/Qwen1.5-72B-Chat/tree/main
