### ISSUE TITLE
superboogav2 pydantic error

### ISSUE THREAD

**Issue by rlconst** [oobabooga/text-generation-webui#5455]
### Describe the bug

I can't enable superbooga v2

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

enable superbooga v2
run win_cmd
install dependencies `pip install -r extensions\superboogav2\requirements.txt --upgrade`
restart and enable again

### Logs

```shell
00:03:37-929471 ERROR    Failed to load the extension "superboogav2".
Traceback (most recent call last):
  File "C:\Work\text-generation-webui\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "C:\Work\text-generation-webui\extensions\superboogav2\script.py", line 20, in <module>
    from .chromadb import make_collector
  File "C:\Work\text-generation-webui\extensions\superboogav2\chromadb.py", line 2, in <module>
    import chromadb
  File "C:\Work\text-generation-webui\installer_files\env\Lib\site-packages\chromadb\__init__.py", line 1, in <module>
    import chromadb.config
  File "C:\Work\text-generation-webui\installer_files\env\Lib\site-packages\chromadb\config.py", line 1, in <module>
    from pydantic import BaseSettings
  File "C:\Work\text-generation-webui\installer_files\env\Lib\site-packages\pydantic\__init__.py", line 374, in __getattr__
    return _getattr_migration(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\text-generation-webui\installer_files\env\Lib\site-packages\pydantic\_migration.py", line 296, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.6/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.6/u/import-error
```

### System Info

```shell
win 11, not sure if other is relevant, because models and even training works
```

**Comment by rlconst** [comment]
For me it looks like un-pinned versions

**Comment by rlconst** [comment]
https://github.com/chroma-core/chroma/issues/774

**Comment by ZyoniaGroup** [comment]
Hello, I'm getting the same issue about "Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]" while enabling superboogav2. Were you able to solve this?

**Comment by joshs85** [comment]
I fixed this by adding

 pydantic>=1.4.0,<2 

to the end of extensions/superboogav2/requirements.txt

**Comment by rlconst** [comment]
@ZyoniaGroup yes, see PR https://github.com/oobabooga/text-generation-webui/pull/5456

**Comment by ZyoniaGroup** [comment]
@joshs85 @rlconst Thank you guys! Worked perfectly

**Comment by bardachef** [comment]
Hello there!
I had the same problem as you. To my surprise, the installation of pydantic package was not helpful (I tried diverse versions of it from 1.10.0 up to 1.10.4) The only thing, that helped me (I run the docker on jetson orin) was to downgrade the chromadb package in extensions/superboogav2/requirements.txt to chromadb==0.4.15. Then superboogav2 started without downloading extra pydantic package.

**Comment by DeTeRpl** [comment]
> I fixed this by adding
> 
> pydantic>=1.4.0,<2
> 
> to the end of extensions/superboogav2/requirements.txt

Worked perfectly
