### ISSUE TITLE
Cache saving may be breaking the backend

### ISSUE THREAD

**Issue by zorbathut** [oobabooga/text-generation-webui#5480]
### Describe the bug

I recently turned on caching, hoping for a performance boost. My current commandline is:

`/start_linux.sh --share --public-api --model wolfram_miqu-1-120b-Q4_K_S --cache-capacity=100000000000`

(Yes, I have enough RAM.)

Unfortunately this seems to break the backend after just a few queries. Log dump below.

The consistent part is that this always happens after `cache saved`, and it results in that same stacktrace every time I send a query via OpenAPI. My best guess is that something's breaking in the cache saving system and causing the entire environment to melt down, but I'm not sure what that is.

While I do have enough RAM for that cache, I don't have much scratch space; if it's trying to write the cache to disk, it's entirely plausible that would detonate it entirely. But I'd still expect a more useful error message, or at least, some error message besides "sorry your text generator no longer works".

Turning the cache off has restored it to normality, so, workaround achieved, but it'd be nice if I could avoid the workaround.

I'm a programmer and am happy to help troubleshoot if there's stuff you want me to try.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I'm not exactly sure what the steps are, but "turn the cache on, load a model, and do a lot of stuff via SillyTavern and see if it melts" is the closest I can come up with.

### Logs

```shell
(standard loading here)

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
INFO:     47.221.210.240:0 - "GET /v1/models HTTP/1.1" 200 OK
INFO:     47.221.210.240:0 - "GET /v1/internal/model/info HTTP/1.1" 200 OK
INFO:     47.221.210.240:0 - "POST /v1/completions HTTP/1.1" 200 OK
Llama._create_completion: cache miss

llama_print_timings:        load time =    3794.68 ms
llama_print_timings:      sample time =      56.21 ms /   341 runs   (    0.16 ms per token,  6066.97 tokens per second)
llama_print_timings: prompt eval time =   40020.96 ms /  5271 tokens (    7.59 ms per token,   131.71 tokens per second)
llama_print_timings:        eval time =   35237.16 ms /   340 runs   (  103.64 ms per token,     9.65 tokens per second)
llama_print_timings:       total time =   76396.11 ms /  5611 tokens
Llama._create_completion: cache save
Llama.save_state: saving llama state
Llama.save_state: got state size: 9460842532
Llama.save_state: allocated state
Llama.save_state: copied llama state: 3217925651
Llama.save_state: saving 3217925651 bytes of llama state
Llama._create_completion: cache saved
Output generated in 85.17 seconds (3.99 tokens/s, 340 tokens, context 5271, seed 1344617729)
INFO:     47.221.210.240:0 - "POST /v1/completions HTTP/1.1" 200 OK
Traceback (most recent call last):
  File "/workspace/text-generation-webui/modules/callbacks.py", line 61, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/text-generation-webui/modules/llamacpp_model.py", line 173, in generate
    for completion_chunk in completion_chunks:
  File "/workspace/text-generation-webui/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda/llama.py", line 868, in _create_completion
    cache_item = self.cache[prompt_tokens]
                 ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/workspace/text-generation-webui/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda/llama_cache.py", line 76,in __getitem__
    _key = self._find_longest_prefix_key(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/text-generation-webui/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda/llama_cache.py", line 68,in _find_longest_prefix_key
    for k, prefix_len in keys:
  File "/workspace/text-generation-webui/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda/llama_cache.py", line 66,in <genexpr>
    (k, llama_cpp.llama.Llama.longest_token_prefix(k, key)) for k in self.cache_state.keys()
        ^^^^^^^^^
NameError: name 'llama_cpp' is not defined
Output generated in 0.51 seconds (0.00 tokens/s, 0 tokens, context 5271, seed 490037914)
```
```


### System Info

```shell
Runpod A100 80GB, Pytorch 2.2.10, Cuda 12.1.1, Linux (I'm . . . not sure which Linux. But it's Linux.)

Running `snapshot-2024-02-04`.
```

**Comment by Trahloc** [comment]
I'm able to get this to fail quickly. An impression, a response, another impression, and failure:

`CUDA_VISIBLE_DEVICES=1 ./start_linux.sh --cfg-cache --api --bf16 --no-cache --auto-devices --force-safetensors --use_flash_attention_2 --listen --listen-host 192.168.1.194 --listen-port 7860 --chat-buttons --n-gpu-layer 128 --tensorcores --numa --loader llama.cpp --n_ctx 8192 --model nous-hermes-2-mixtral-8x7b-dpo.Q5_K_M.gguf  --cache-capacity 2GiB`

```
To create a public link, set `share=True` in `launch()`.
Llama._create_completion: cache miss
Output generated in 1.58 seconds (3.16 tokens/s, 5 tokens, context 430, seed 976807351)
Llama._create_completion: cache miss
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1354.97 ms
llama_print_timings:      sample time =      36.96 ms /   367 runs   (    0.10 ms per token,  9930.46 tokens per second)
llama_print_timings: prompt eval time =       0.00 ms /     1 tokens (    0.00 ms per token,      inf tokens per second)
llama_print_timings:        eval time =    7347.60 ms /   367 runs   (   20.02 ms per token,    49.95 tokens per second)
llama_print_timings:       total time =    7874.74 ms /   368 tokens
Llama._create_completion: cache save
Llama.save_state: saving llama state
Llama.save_state: got state size: 1139347492
Llama.save_state: allocated state
Llama.save_state: copied llama state: 104569569
Llama.save_state: saving 104569569 bytes of llama state
Llama._create_completion: cache saved
Output generated in 11.32 seconds (25.61 tokens/s, 290 tokens, context 430, seed 847975240)
Traceback (most recent call last):
  File "/home/trahloc/ai/text-generation-webui/modules/callbacks.py", line 61, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trahloc/ai/text-generation-webui/modules/llamacpp_model.py", line 174, in generate
    for completion_chunk in completion_chunks:
  File "/home/trahloc/ai/text-generation-webui/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda_tensorcores/llama.py", line 958, in _create_completion
    cache_item = self.cache[prompt_tokens]
                 ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/trahloc/ai/text-generation-webui/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda_tensorcores/llama_cache.py", line 76, in __getitem__
    _key = self._find_longest_prefix_key(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trahloc/ai/text-generation-webui/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda_tensorcores/llama_cache.py", line 68, in _find_longest_prefix_key
    for k, prefix_len in keys:
  File "/home/trahloc/ai/text-generation-webui/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda_tensorcores/llama_cache.py", line 66, in <genexpr>
    (k, llama_cpp.llama.Llama.longest_token_prefix(k, key)) for k in self.cache_state.keys()
        ^^^^^^^^^
NameError: name 'llama_cpp' is not defined
Output generated in 0.33 seconds (0.00 tokens/s, 0 tokens, context 730, seed 1542925940)
```

**Comment by sakharovaan** [comment]
The problem still persists
