### ISSUE TITLE
--autosplit flag for ExLlamaV2 commit breaks ExLlamaV2 

### ISSUE THREAD

**Issue by biship** [oobabooga/text-generation-webui#5528]
### Describe the bug

#5524 

This commit broke ExLlamaV2 for me. (previous commit works fine)

I've tried exllamav2 0.0.13 to [0.0.13.post2](https://github.com/turboderp/exllamav2/releases/tag/0.0.13.post2), all error.

Model loads fine. Errors on any message.

https://huggingface.co/Kooten/Kunoichi-DPO-v2-7B-6bpw-exl2

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

python server.py --listen --auto-launch --listen-host 127.0.0.1 --api --trust-remote-code --tensorcores --use_flash_attention_2 --tensorcores --threads 8 --threads-batch 16 --n_batch 128 --logits_all

### Logs

```shell
10:33:31-046959 INFO     Loading "Kooten_Kunoichi-DPO-v2-7B-6bpw-exl2"
10:33:34-498846 INFO     LOADER: "ExLlamav2_HF"
10:33:34-501000 INFO     TRUNCATION LENGTH: 8192
10:33:34-502556 INFO     INSTRUCTION TEMPLATE: "Alpaca"
10:33:34-503556 INFO     Loaded the model in 3.46 seconds.
Traceback (most recent call last):
  File "J:\Code\AI\LLM\Backend\text-generation-webui\modules\callbacks.py", line 61, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\Code\AI\LLM\Backend\text-generation-webui\modules\text_generation.py", line 390, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Users\nick\miniconda3\envs\textgen\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nick\miniconda3\envs\textgen\Lib\site-packages\transformers\generation\utils.py", line 1525, in generate
    return self.sample(
           ^^^^^^^^^^^^
  File "C:\Users\nick\miniconda3\envs\textgen\Lib\site-packages\transformers\generation\utils.py", line 2622, in sample
    outputs = self(
              ^^^^^
  File "J:\Code\AI\LLM\Backend\text-generation-webui\modules\exllamav2_hf.py", line 129, in __call__
    self.ex_model.forward(seq_tensor[:-1].view(1, -1), ex_cache, preprocess_only=True, loras=self.loras)
  File "C:\Users\nick\miniconda3\envs\textgen\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nick\miniconda3\envs\textgen\Lib\site-packages\exllamav2\model.py", line 569, in forward
    r, ls = self._forward(input_ids = input_ids[:, chunk_begin : chunk_end],
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nick\miniconda3\envs\textgen\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nick\miniconda3\envs\textgen\Lib\site-packages\exllamav2\model.py", line 633, in _forward
    x = module.forward(x, cache = cache, attn_params = attn_params, past_len = past_len, loras = loras)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nick\miniconda3\envs\textgen\Lib\site-packages\exllamav2\attn.py", line 370, in forward
    k_states = batch_keys.narrow(0, 0, batch_size).narrow(1, past_len, q_len)
               ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'narrow'
Output generated in 0.33 seconds (0.00 tokens/s, 0 tokens, context 1026, seed 642912080)
```

### System Info

```shell
Win x64, NVIDIA 4090, Python 3.11, cu121 & torch 2.2.0, dev branch
accelerate                        0.27.2
exllamav2                         0.0.13.post2+cu121
llama_cpp_python                  0.2.42+cpuavx2
llama_cpp_python_cuda             0.2.42+cu121
llama_cpp_python_cuda_tensorcores 0.2.42+cu121
torch                             2.2.0+cu121
torchaudio                        2.2.0+cu121
torchvision                       0.17.0+cu121
transformers                      4.37.2
```

**Comment by culturedniichan** [comment]
Same happening to me. Using ExLlama2-HF to load Noromaid Mixtral

**Comment by MikeRoz47** [comment]
Happening to me too. Interestingly, I noticed that where I was OOMing before with a particular context size, I am able to load the model with that context size now and there's plenty of memory left on the GPUs. I think it's simply not loading the context cache.

**Comment by Ph0rk0z** [comment]
Turn off lazy loading. Probably needs something like : lazy = True if shared.args.autosplit else False

**Comment by MikeRoz47** [comment]
I tried that. Got the following error:

```
Traceback (most recent call last):
  File "C:\[REDACTED]\text-generation-webui\modules\ui_model_menu.py", line 242, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\[REDACTED]\text-generation-webui\modules\models.py", line 87, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\[REDACTED]\text-generation-webui\modules\models.py", line 380, in ExLlamav2_HF_loader
    return Exllamav2HF.from_pretrained(model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\[REDACTED]\text-generation-webui\modules\exllamav2_hf.py", line 175, in from_pretrained
    return Exllamav2HF(config)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\[REDACTED]\text-generation-webui\modules\exllamav2_hf.py", line 47, in __init__
    self.ex_cache = ExLlamaV2Cache(self.ex_model, lazy=shared.args.autosplit)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\[REDACTED]\text-generation-webui\oobavenv\Lib\site-packages\exllamav2\cache.py", line 136, in __init__
    self.create_state_tensors(copy_from, lazy)
  File "C:\[REDACTED]\text-generation-webui\oobavenv\Lib\site-packages\exllamav2\cache.py", line 48, in create_state_tensors
    p_key_states = torch.zeros(self.batch_size, self.max_seq_len, self.num_key_value_heads, self.head_dim, dtype = self.dtype, device = self.model.cache_map[i]).contiguous()

                ~~~~~~~~~~~~~~~~~~~~^^^
KeyError: 0
```

Seems like the old way wants the cache created after, and the autosplit path wants the cache created lazily before. This seems to work for me - from modules/exllamav2_hf.py line 36:

```python
    def __init__(self, config: ExLlamaV2Config):
        super().__init__(PretrainedConfig())
        self.ex_config = config
        self.ex_model = ExLlamaV2(config)
        self.loras = None
        self.generation_config = GenerationConfig()

        if shared.args.autosplit:
            if shared.args.cache_8bit:
                self.ex_cache = ExLlamaV2Cache_8bit(self.ex_model, lazy=True)
            else:
                self.ex_cache = ExLlamaV2Cache(self.ex_model, lazy=True)
            self.ex_model.load_autosplit(self.ex_cache)
        else:
            split = None
            if shared.args.gpu_split:
                split = [float(alloc) for alloc in shared.args.gpu_split.split(",")]

            self.ex_model.load(split)
            if shared.args.cache_8bit:
                self.ex_cache = ExLlamaV2Cache_8bit(self.ex_model, lazy=False)
            else:
                self.ex_cache = ExLlamaV2Cache(self.ex_model, lazy=False)
```

**Comment by biship** [comment]
> EDIT: Checking the 'autosplit' checkbox, even if you only have a single GPU, appears to work as a workaround for this.

Yes, this fixed it for me too - nice find. I can't believe I didn't try this considering the commit added this...

**Comment by Urammar** [comment]
Same this is happening to me also. Breaks a ton of models. The autosplit option works for SOME models, but thats not ideal as I would like to be able to set gpu memory allocation manually as normal. This is a horrible commit

**Comment by oobabooga** [comment]
I think that this should have fixed it https://github.com/oobabooga/text-generation-webui/commit/d6bd71db7f3200c2b1ef46123c07374848aed86a

**Comment by biship** [comment]
So far so good. Hasn't failed in my testing, thanks for the quick fix.
