### ISSUE TITLE
Model loading not working

### ISSUE THREAD

**Issue by phithagod24** [oobabooga/text-generation-webui#5544]
### Describe the bug

idk what do im do

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

first download TinyLlama-1.1B-Chat-v0.3-GGUF then use llama.cpp

### Screenshot

i'm cant

### Logs

```shell
19:01:18-107485 INFO     Starting Text generation web UI
19:01:18-129483 INFO     Loading the extension "gallery"
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
19:07:44-276340 INFO     Loading "tinyllama-1.1b-chat-v0.3.Q4_K_M.gguf"
19:07:52-019931 INFO     llama.cpp weights detected: "models\tinyllama-1.1b-chat-v0.3.Q4_K_M.gguf"
19:07:52-055948 ERROR    Failed to load the model.
Traceback (most recent call last):
  File "C:\text-generation-webui-main\text-generation-webui-main\modules\ui_model_menu.py", line 242, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui-main\text-generation-webui-main\modules\models.py", line 87, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui-main\text-generation-webui-main\modules\models.py", line 250, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui-main\text-generation-webui-main\modules\llamacpp_model.py", line 63, in from_pretrained
    Llama = llama_cpp_lib().Llama
            ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'Llama'

19:12:40-691731 INFO     Loading "tinyllama-1.1b-chat-v0.3.Q4_K_M.gguf"
19:12:40-895806 INFO     llama.cpp weights detected: "models\tinyllama-1.1b-chat-v0.3.Q4_K_M.gguf"
19:12:40-903801 ERROR    Failed to load the model.
Traceback (most recent call last):
  File "C:\text-generation-webui-main\text-generation-webui-main\modules\ui_model_menu.py", line 242, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui-main\text-generation-webui-main\modules\models.py", line 87, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui-main\text-generation-webui-main\modules\models.py", line 250, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui-main\text-generation-webui-main\modules\llamacpp_model.py", line 63, in from_pretrained
    Llama = llama_cpp_lib().Llama
            ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'Llama'
```

### System Info

```shell
Processor: Pentium(R) Dual-Core  CPU E5200  @ 2.50GHz 2.50 GHz
ram: 4.00 GB
btw i'm just seeing if im can run a ai on a low end pc and i'm using windows 11 (tiny 11)
```

**Comment by saadkhan955** [comment]
Facing the same issue while trying to load the anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g model


```
00:56:06-967516 INFO     Loading "anon8231489123_gpt4-x-alpaca-13b-native-4bit-128g"
00:56:07-045093 ERROR    Failed to load the model.
Traceback (most recent call last):
  File "F:\Stable\text-generation-webui\modules\ui_model_menu.py", line 242, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Stable\text-generation-webui\modules\models.py", line 87, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Stable\text-generation-webui\modules\models.py", line 153, in huggingface_loader
    model = LoaderClass.from_pretrained(path_to_model, **params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Stable\text-generation-webui\installer_files\env\Lib\site-packages\transformers\models\auto\auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Stable\text-generation-webui\installer_files\env\Lib\site-packages\transformers\modeling_utils.py", line 3338, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory models\anon8231489123_gpt4-x-alpaca-13b-native-4bit-128g.
```


### ScreenShot

![Screenshot 2024-02-21 010248](https://github.com/oobabooga/text-generation-webui/assets/22096543/004aaf9a-65b6-45e7-8fe0-af2475c1cd90)


### System Info 

```
Processor : 12th Gen Intel(R) Core(TM) i7-12650H   2.30 GHz
Ram: 16 GB
GPU: RTX 3070
```

**Comment by bartowski1182** [comment]
@phithagod24 how did you install, it looks like llamacpp isn't installed correctly on the system

@saadkhan955 that looks more like the model you downloaded isn't in the right format, you can try either blindly changing the .pt files to .bin files and trying again, or you can convert it to the appropriate format
