### ISSUE TITLE
Error while loading the model

### ISSUE THREAD

**Issue by bckaplan** [oobabooga/text-generation-webui#5554]
### Describe the bug

When I'm trying to load Vicuna 1.5, I'm seeing the following error:

RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
/opt/conda/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops9_pad_enum4callERKNS_6TensorEN3c108ArrayRefINS5_6SymIntEEElNS5_8optionalIdEE

I tried to upgrade flash attention, but it didnt work out. Do you have any suggestions? 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

-download the LLM from interface (with huggingface link)
-refresh the models and try to load with transformers

### Logs

```shell
Full version: 

File "/opt/conda/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 55, in <module>
    from flash_attn import flash_attn_func, flash_attn_varlen_func
  File "/opt/conda/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/opt/conda/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 8, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /opt/conda/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops9_pad_enum4callERKNS_6TensorEN3c108ArrayRefINS5_6SymIntEEElNS5_8optionalIdEE

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/text_gen_webgui/text-generation-webui/modules/ui_model_menu.py", line 242, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
  File "/data/text_gen_webgui/text-generation-webui/modules/models.py", line 87, in load_model
    output = load_func_map[loader](model_name)
  File "/data/text_gen_webgui/text-generation-webui/modules/models.py", line 153, in huggingface_loader
    model = LoaderClass.from_pretrained(path_to_model, **params)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 565, in from_pretrained
    model_class = _get_model_class(config, cls._model_mapping)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 387, in _get_model_class
    supported_models = model_mapping[type(config)]
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 740, in __getitem__
    return self._load_attr_from_module(model_type, model_name)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 754, in _load_attr_from_module
    return getattribute_from_module(self._modules[module_name], attr)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 698, in getattribute_from_module
    if hasattr(module, attr):
  File "/opt/conda/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1354, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/opt/conda/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1366, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
/opt/conda/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops9_pad_enum4callERKNS_6TensorEN3c108ArrayRefINS5_6SymIntEEElNS5_8optionalIdEE
```

### System Info

```shell
Linux- Nvidia A100 (80GB)
```

**Comment by bartowski1182** [comment]
When you tried to upgrade flashattention, did you do so inside the conda env?

and did you specify that you wanted the cuda version?

**Comment by Yanhuanjin** [comment]
I am also seeing this error. It seems that the local cuda version(my, v12.3) is not suitable with the one in the installer_files folder(may by 11.7 or 8?)?

**Comment by Yanhuanjin** [comment]
> I am also seeing this error. It seems that the local cuda version(my, v12.3) is not suitable with the xxxx.so in the installer_files folder(may by 11.7 or 8?)?

I just solved this problem, make sure the python you use is the one in the installer_files/env/bin/python, because the one in my conda env is not the same, and then anything works well.

**Comment by bckaplan** [comment]
@bartowski1182 Yes, I tried in the env, but didnt specify the cuda verison
@Yanhuanjin which versions of cuda-python-flash attantion you used?

**Comment by xztJLAU** [comment]
With click flash_attent_2  button on webUI,I have same error,when i don't use it,my model run.

**Comment by Yanhuanjin** [comment]
> @bartowski1182 Yes, I tried in the env, but didnt specify the cuda verison @Yanhuanjin which versions of cuda-python-flash attantion you used?

You should uninstall the current flash-attention, and download the certain release that suits your `cuxxx & torch & py`. 
[flash-attention](https://github.com/Dao-AILab/flash-attention/release).
