### ISSUE TITLE
ImportError: libamdhip64.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ZhenyaPav** [oobabooga/text-generation-webui#5556]
### Describe the bug

I do not pull the changes often, so I cannot pinpoint the specific commit this issue appeared in, but when installing AMD requirements from the latest version, exllamav2 is failing to load any models.

Using the packages installed before, everything works fine.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. git clone https://github.com/oobabooga/text-generation-webui.git && cd text-generation-webui
2. python -m venv venv && source venv/bin/activate
3. pip install -r requirements_amd.txt
4. python server.py
5. try to load any GPTQ or exl2 model

### Logs

```shell
19:12:38-074014 ERROR    Failed to load the model.                                                      
Traceback (most recent call last):
  File "/home/zhenyapav/Projects/text-generation-webui/modules/ui_model_menu.py", line 242, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhenyapav/Projects/text-generation-webui/modules/models.py", line 87, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhenyapav/Projects/text-generation-webui/modules/models.py", line 378, in ExLlamav2_HF_loader
    from modules.exllamav2_hf import Exllamav2HF
  File "/home/zhenyapav/Projects/text-generation-webui/modules/exllamav2_hf.py", line 7, in <module>
    from exllamav2 import (
  File "/home/zhenyapav/Projects/text-generation-webui/venv/lib/python3.11/site-packages/exllamav2/__init__.py", line 3, in <module>
    from exllamav2.model import ExLlamaV2
  File "/home/zhenyapav/Projects/text-generation-webui/venv/lib/python3.11/site-packages/exllamav2/model.py", line 25, in <module>
    from exllamav2.config import ExLlamaV2Config
  File "/home/zhenyapav/Projects/text-generation-webui/venv/lib/python3.11/site-packages/exllamav2/config.py", line 2, in <module>
    from exllamav2.fasttensors import STFile
  File "/home/zhenyapav/Projects/text-generation-webui/venv/lib/python3.11/site-packages/exllamav2/fasttensors.py", line 5, in <module>
    from exllamav2.ext import exllamav2_ext as ext_c
  File "/home/zhenyapav/Projects/text-generation-webui/venv/lib/python3.11/site-packages/exllamav2/ext.py", line 15, in <module>
    import exllamav2_ext
ImportError: libamdhip64.so.5: cannot open shared object file: No such file or directory
```

### System Info

```shell
RX 7900 XT
Arch Linux
ROCm 6.0.0
```

**Comment by ZhenyaPav** [comment]
Tried installing exllamav2 from the original repo. The error changed to
`python: /usr/src/debug/hip-runtime-amd/clr-rocm-6.0.0/rocclr/thread/monitor.hpp:180: bool amd::Monitor::tryLock(): Assertion `thread != NULL && "cannot lock() from (null)"' failed.`

**Comment by erasmus74** [comment]
Having this issue.

**Comment by ZhenyaPav** [comment]
> Having this issue.

I think it's due to the fact that requirements still use rocm 5.6 wheels, while (at least on Arch) ROCm is updated to 6.0. You can fix it by manually installing
`https://github.com/turboderp/exllamav2/releases/download/v0.0.20/exllamav2-0.0.20+rocm6.0-cp311-cp311-linux_x86_64.whl`

As far as I can tell, it seems to be working flawlessly.
