### ISSUE TITLE
Issue with GPU driver or CUDA or PyTorch?

### ISSUE THREAD

**Issue by algl84** [oobabooga/text-generation-webui#5558]
### Describe the bug

Hi,

I can't seem to get any models running with web-ui. Specifically downloaded GPTQ versions but all other models fail loading as well. 

Additional screenshots show some other issues I'm running into when e.g. running easy-diffusion or telegram desktop. WarThunder on the contrary runs OK (with a couple of freezes now and then). I have the recommended GPU driver installed. Maybe a CUDA or PyTorch version issue?

Please let me know if I can provide more details and thank you for your help. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

- Download text-generation-webui
- Choose installation for GPU 
- Run text-generation-webui
- Download and load any model

### Screenshot

![nvidia-smi](https://github.com/oobabooga/text-generation-webui/assets/152185898/156c73cc-4e06-4ecd-be3f-20a842a25918)
![easydiffusion error](https://github.com/oobabooga/text-generation-webui/assets/152185898/462e9009-d28a-4f99-93a9-7668eaa97ca7)
![telegram_error](https://github.com/oobabooga/text-generation-webui/assets/152185898/921eddcc-92ea-461b-b099-802f68637852)

### Logs

```shell
14:09:36-430354 INFO     Loading "TheBloke_WizardLM-7B-uncensored-GPTQ"         
14:09:37-210420 ERROR    Failed to load the model. 
                             
Traceback (most recent call last):

  File "/X/text-generation-webui-main/modules/ui_model_menu.py", line 242, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/X/text-generation-webui-main/modules/models.py", line 87, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/X/text-generation-webui-main/modules/models.py", line 380, in ExLlamav2_HF_loader
    return Exllamav2HF.from_pretrained(model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/X/text-generation-webui-main/modules/exllamav2_hf.py", line 176, in from_pretrained
    return Exllamav2HF(config)
           ^^^^^^^^^^^^^^^^^^^
  File "/X/text-generation-webui-main/modules/exllamav2_hf.py", line 49, in __init__
    self.ex_model.load(split)

  File "/X/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/exllamav2/model.py", line 256, in load
    for item in f: x = item

  File "/X/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/exllamav2/model.py", line 274, in load_gen
    module.load()

  File "/X/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/exllamav2/attn.py", line 190, in load
    self.k_proj.load()

  File "/X/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/exllamav2/linear.py", line 51, in load
    self.q_handle = ext.make_q_matrix(w, self.temp_dq)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/X/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/exllamav2/ext.py", line 229, in make_q_matrix
    if "g_idx" in w and not (w["g_idx"] == 0).all().item():
                             ^^^^^^^^^^^^^^^
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### System Info

```shell
Linux Mint 21.3 Cinnamon 6.0.4
5.15.0-94-generic
Intel© Xeon© CPU E5-2667 v2 @ 3.30GHz × 8
62.7 GiB RAM
NVIDIA Corporation GM204GL [Quadro M4000]

nvidia-driver-535 (recommended)
Version 535.154.05-0ubuntu0.22.04.1
```

**Comment by darkvokrat** [comment]
I have this exact same issue but I'm also using multiple gpus 1x 2070 super and 1x Quadro M4000, I'm fairly un knowledgeable in torch and Cuda so I'm not sure how much I can help with this, I need someone more knowledgeable to help me with this.

I've tried the 2 different cuda versions offered at the start up but i still encounter the same issue, sometimes the model loads onto one of the gpus before loading onto the other causing it to momentarily work, then fail after a couple thousand tokens, I've tested on: TheBloke_LLaMA2-13B-Tiefighter-GPTQ, mayaeary_pygmalion-6b_dev-4bit-128g, and silicon maid, all of them have had the same issue.
