### ISSUE TITLE
start_linux.sh returns KeyError

### ISSUE THREAD

**Issue by eleius** [oobabooga/text-generation-webui#5568]
### Describe the bug

I've been using text-generation-webui on a portable USB drive for a few weeks now (arch linux, nvidia gfx), but today I decided to re-clone from git and reinstall.

However when I run start_linux.sh I now have the following error and can't install it anymore:

```
What is your GPU?

A) NVIDIA
B) AMD (Linux/MacOS only. Requires ROCm SDK 5.6 on Linux)
C) Apple M Series
D) Intel Arc (IPEX)
N) None (I want to run models in CPU mode)

Input> Traceback (most recent call last):
  File "/run/media/system/PROJECTS/AI/text-generation-webui/one_click.py", line 375, in <module>
    install_webui()
  File "/run/media/system/PROJECTS/AI/text-generation-webui/one_click.py", line 197, in install_webui
    selected_gpu = gpu_choice_to_name[choice]
                   ~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: ''
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. git clone https://github.com/oobabooga/text-generation-webui
2. run start_linux.sh

### Logs

```shell
Downloading Miniconda from https://repo.anaconda.com/miniconda/Miniconda3-py310_23.3.1-0-Linux-x86_64.sh to /run/media/system/PROJECTS/AI/text-generation-webui/installer_files/miniconda_installer.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 69.7M  100 69.7M    0     0  44.5M      0  0:00:01  0:00:01 --:--:-- 44.5M
PREFIX=/run/media/system/PROJECTS/AI/text-generation-webui/installer_files/conda
Unpacking payload ...
Extracting : pysocks-1.7.1-py310h06a4308_0.conda:  51%|▌| 25/49 [00:05<00:09,  2.62i


                                                                                    
Installing base environment...


Downloading and Extracting Packages


Downloading and Extracting Packages

Preparing transaction: done
Executing transaction: done
installation finished.
Miniconda version:
conda 23.3.1
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.3.1
  latest version: 24.1.2

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=24.1.2



## Package Plan ##

  environment location: /run/media/system/PROJECTS/AI/text-generation-webui/installer_files/env

  added / updated specs:
    - python=3.11


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2023.12.12 |       h06a4308_0         126 KB
    libffi-3.4.4               |       h6a678d5_0         142 KB
    openssl-3.0.13             |       h7f8727e_0         5.2 MB
    pip-23.3.1                 |  py311h06a4308_0         3.3 MB
    python-3.11.7              |       h955ad1f_0        32.8 MB
    setuptools-68.2.2          |  py311h06a4308_0         1.2 MB
    sqlite-3.41.2              |       h5eee18b_0         1.2 MB
    tzdata-2023d               |       h04d1e81_0         117 KB
    wheel-0.41.2               |  py311h06a4308_0         145 KB
    xz-5.4.5                   |       h5eee18b_0         646 KB
    ------------------------------------------------------------
                                           Total:        44.9 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main 
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-5.1-1_gnu 
  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h7b6447c_0 
  ca-certificates    pkgs/main/linux-64::ca-certificates-2023.12.12-h06a4308_0 
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.38-h1181459_1 
  libffi             pkgs/main/linux-64::libffi-3.4.4-h6a678d5_0 
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-11.2.0-h1234567_1 
  libgomp            pkgs/main/linux-64::libgomp-11.2.0-h1234567_1 
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-11.2.0-h1234567_1 
  libuuid            pkgs/main/linux-64::libuuid-1.41.5-h5eee18b_0 
  ncurses            pkgs/main/linux-64::ncurses-6.4-h6a678d5_0 
  openssl            pkgs/main/linux-64::openssl-3.0.13-h7f8727e_0 
  pip                pkgs/main/linux-64::pip-23.3.1-py311h06a4308_0 
  python             pkgs/main/linux-64::python-3.11.7-h955ad1f_0 
  readline           pkgs/main/linux-64::readline-8.2-h5eee18b_0 
  setuptools         pkgs/main/linux-64::setuptools-68.2.2-py311h06a4308_0 
  sqlite             pkgs/main/linux-64::sqlite-3.41.2-h5eee18b_0 
  tk                 pkgs/main/linux-64::tk-8.6.12-h1ccaba5_0 
  tzdata             pkgs/main/noarch::tzdata-2023d-h04d1e81_0 
  wheel              pkgs/main/linux-64::wheel-0.41.2-py311h06a4308_0 
  xz                 pkgs/main/linux-64::xz-5.4.5-h5eee18b_0 
  zlib               pkgs/main/linux-64::zlib-1.2.13-h5eee18b_0 



Downloading and Extracting Packages
                                                                                                                                                              
Preparing transaction: done                                                                                                                                   
Verifying transaction: done                                                                                                                                   
Executing transaction: done                                                                                                                                   
#                                                                                                                                                             
# To activate this environment, use                                                                                                                           
#                                                                                                                                                             
#     $ conda activate /run/media/system/PROJECTS/AI/text-generation-webui/installer_files/env                                                                
#                                                                                                                                                             
# To deactivate an active environment, use                                                                                                                    
#
#     $ conda deactivate


What is your GPU?

A) NVIDIA
B) AMD (Linux/MacOS only. Requires ROCm SDK 5.6 on Linux)
C) Apple M Series
D) Intel Arc (IPEX)
N) None (I want to run models in CPU mode)

Input> Traceback (most recent call last):
  File "/run/media/system/PROJECTS/AI/text-generation-webui/one_click.py", line 375, in <module>
    install_webui()
  File "/run/media/system/PROJECTS/AI/text-generation-webui/one_click.py", line 197, in install_webui
    selected_gpu = gpu_choice_to_name[choice]
                   ~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: ''
```

### System Info

```shell
AMD Ryzen 7 7735HS, 32gb, NVIDIA RTX 4050 Max-Q
```

**Comment by eleius** [comment]
I was deleting and re-cloning, but it seems simply running start_linux.sh again jumps directly to the GPU question and allows me to continue installing. Not sure about the KeyError issue above though.

**Comment by eleius** [comment]
Seems fixed in the current git version. Closing.
