### ISSUE TITLE
coqui_tts error

### ISSUE THREAD

**Issue by kalle07** [oobabooga/text-generation-webui#5591]
### Describe the bug

one month ago all working fine !!!
coqui_tts ist the only and best OFFLINE voice extention for oobadoga if not tell me a better one please   ;)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

load extention coqui_tts 

### Logs

```shell
12:58:44-519624 INFO     Loading the extension "coqui_tts"
12:58:45-869491 ERROR    Failed to load the extension "coqui_tts".
Traceback (most recent call last):
  File "e:\text-generation-webui\modules\extensions.py", line 37, in load_extensions
    extension = importlib.import_module(f"extensions.{name}.script")
  File "e:\text-generation-webui\installer_files\env\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "e:\text-generation-webui\extensions\coqui_tts\script.py", line 10, in <module>
    from TTS.api import TTS
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\TTS\api.py", line 9, in <module>
    from TTS.cs_api import CS_API
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\TTS\cs_api.py", line 12, in <module>
    from TTS.utils.audio.numpy_transforms import save_wav
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\TTS\utils\audio\__init__.py", line 1, in <module>    from TTS.utils.audio.processor import AudioProcessor
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\TTS\utils\audio\processor.py", line 10, in <module>
    from TTS.utils.audio.numpy_transforms import (
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\TTS\utils\audio\numpy_transforms.py", line 8, in <module>
    from librosa import magphase, pyin
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\lazy_loader\__init__.py", line 78, in __getattr__    attr = getattr(submod, name)
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\lazy_loader\__init__.py", line 77, in __getattr__    submod = importlib.import_module(submod_path)
  File "e:\text-generation-webui\installer_files\env\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\librosa\core\spectrum.py", line 12, in <module>
    from numba import jit
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\numba\__init__.py", line 55, in <module>
    _ensure_critical_deps()
  File "e:\text-generation-webui\installer_files\env\lib\site-packages\numba\__init__.py", line 42, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.24 or less")
ImportError: Numba needs NumPy 1.24 or less
Running on local URL:  http://127.0.0.1:7861
```

### System Info

```shell
win10
rtx4060
```

**Comment by kalle07** [comment]
hello ?!? no one uses a good offline voice extention ?

**Comment by MercyfulKing** [comment]
I'm no guru but you need to check your Numpy version, downgrade it -File "e:\text-generation-webui\installer_files\env\lib\site-packages\numba\__init__.py", line 42, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.24 or less")
