### ISSUE TITLE
Save UI defaults to settings.yaml Not working

### ISSUE THREAD

**Issue by Tobe2d** [oobabooga/text-generation-webui#5592]
### Describe the bug

When I try to activate few options and try  using Save UI defaults to settings.yaml it save empty settings.yaml

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I check few options like in the image below:

![image](https://github.com/oobabooga/text-generation-webui/assets/4099839/1aee6ff0-abb3-4052-8831-a01fa9ef8e33)

and press  Save UI defaults to settings.yaml

close the termenal and start again and it goes back as if I did not set those options
Add to that when I check settings.yaml it is totally empty file

### Logs

```shell
it does not show any log
```

### System Info

```shell
Windows 11
I9 13900
Nvidia 4090
128GB RAM
```

**Comment by SakuraRK** [comment]
I have the same problem.
Did you the "Save UI defaults to settings.yaml" show an "ERROR" and the second input tab show "./"?
I think is the problem source.

**Comment by ashleykleynhans** [comment]
I am also experiencing this issue and see the following in the log:

```
Traceback (most recent call last):
  File "/workspace/venvs/text-generation-webui/lib/python3.10/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/workspace/venvs/text-generation-webui/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/workspace/venvs/text-generation-webui/lib/python3.10/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/workspace/venvs/text-generation-webui/lib/python3.10/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/workspace/venvs/text-generation-webui/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/workspace/venvs/text-generation-webui/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/workspace/venvs/text-generation-webui/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/workspace/venvs/text-generation-webui/lib/python3.10/site-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "/workspace/text-generation-webui/modules/ui.py", line 239, in save_settings
    extension = getattr(extensions, extension_name).script
AttributeError: module 'extensions' has no attribute 'api'
```

![IMG-20240320-WA0003](https://github.com/oobabooga/text-generation-webui/assets/886709/95c540f1-be01-467f-bf45-2d9be3e3051b)

You can still click the `Save` button and it still seems to save the settings.yaml file but it shouldn't be erroring out.

**Comment by 1joshw** [comment]
i am having the same problem

**Comment by c0008** [comment]
I am using the current main branch and I still have this problem. The file modification time of settings.yaml gets updated but after restarting all extensions and command-line flags are disabled again.

Kubuntu 24.04
