### ISSUE TITLE
Error when saving dialogue

### ISSUE THREAD

**Issue by Manimap** [oobabooga/text-generation-webui#56]
Following the stuff added by the ER yesterday https://github.com/oobabooga/text-generation-webui/issues/50. 
Starting parameters :  --cai-chat --auto-devices --no-stream --bf16
OS : WIn10
Browser : Brave

I tried to save a story and all I get is this error :

Traceback (most recent call last):
  File "C:\Users\USER\miniconda3\envs\textgen\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\USER\miniconda3\envs\textgen\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "C:\Users\USER\miniconda3\envs\textgen\lib\site-packages\gradio\blocks.py", line 856, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\USER\miniconda3\envs\textgen\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\USER\miniconda3\envs\textgen\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\USER\miniconda3\envs\textgen\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\text-generation-webui\server.py", line 570, in save_history
    with open(Path(f'logs/{fname}'), 'w') as f:
OSError: [Errno 22] Invalid argument: 'logs\\Example_20230204-21:44:29.json'

**Comment by oobabooga** [comment]
It should be fixed now

https://github.com/oobabooga/text-generation-webui/commit/2207d449860a6f6ccb21dfad9fa912c0a1865d5b
