### ISSUE TITLE
Can't run AWQ model, requesting assistance.

### ISSUE THREAD

**Issue by jellytail** [oobabooga/text-generation-webui#5635]
### Describe the bug

This is my first attempt, and I'm getting an error that I can't find online.
I'm trying to run "TheBloke/Yarn-Mistral-7B-128k-AWQ"
I've tried several other models.
I haven't tried uninstalling and re-installing, could I try this just by deleting the /text-generation-webui/ folder and re-downloading?

I'm semi-technical, but unfamiliar with this AI stuff. If this is the wrong place to ask for this kind of help, then please direct me to the right place.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Tried several models with the same or similar errors.

### Logs

```shell
23:24:40-794225 INFO     Loading "TheBloke_Yarn-Mistral-7B-128k-AWQ"                                               
23:24:40-795775 ERROR    Failed to load the model.                                                                 
Traceback (most recent call last):
  File "/home/jellytail/Documents/AI/text-generation-webui/modules/ui_model_menu.py", line 242, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jellytail/Documents/AI/text-generation-webui/modules/models.py", line 87, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jellytail/Documents/AI/text-generation-webui/modules/models.py", line 298, in AutoAWQ_loader
    from awq import AutoAWQForCausalLM
ModuleNotFoundError: No module named 'awq'
```

### System Info

```shell
CPU: AMD 5800x
GPU: AMD 6600xt
RAM: 32GB
OS: Debian 12 KDE
```

**Comment by PopHorn** [comment]
Same here

**Comment by GetTuh** [comment]
Enter the venv, in my case linux:
`./cmd_linux.sh`
Install autoawq into the venv
`pip install autoawq`
Exit the venv and run the webui again
