### ISSUE TITLE
Runpod TheBloke Local LLMs One-Click is broken: ImportError: cannot import name 'ExLlamaV2Cache_Q4

### ISSUE THREAD

**Issue by WouterGlorieux** [oobabooga/text-generation-webui#5664]
### Describe the bug

Can't load models via the runpod template anymore.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Just try to load a model via the runpod template.

### Logs

```shell
Traceback (most recent call last):

File "/workspace/text-generation-webui/modules/ui_model_menu.py", line 243, in load_model_wrapper


shared.model, shared.tokenizer = load_model(selected_model, loader)
File "/workspace/text-generation-webui/modules/models.py", line 87, in load_model


output = load_func_map[loader](model_name)
File "/workspace/text-generation-webui/modules/models.py", line 378, in ExLlamav2_HF_loader


from modules.exllamav2_hf import Exllamav2HF
File "/workspace/text-generation-webui/modules/exllamav2_hf.py", line 7, in


from exllamav2 import (
ImportError: cannot import name 'ExLlamaV2Cache_Q4' from 'exllamav2' (/usr/local/lib/python3.10/dist-packages/exllamav2/init.py)
```

### System Info

```shell
Runpod - A6000
```

**Comment by ashleykleynhans** [comment]
@WouterGlorieux , you should log this in TheBloke's repo not here.

https://github.com/TheBlokeAI/dockerLLM
