### ISSUE TITLE
HQQ model loader could not accept GTX1080 Ti due to cuda compatibility

### ISSUE THREAD

**Issue by wwithoutn** [oobabooga/text-generation-webui#5665]
### Describe the bug

Good day.

Got this error when generating text using HQQ Llama 13b chat hf model (detailed log attached), before this, no error when loading the model. Using eGPU GTX1080Ti.

![Picture](https://github.com/oobabooga/text-generation-webui/assets/142209352/9a8faff3-47bf-4f61-b192-0559bf07cb20)

At the end of the paragraphe it shows `Found NVIDIA GeForce GTX 1080 Ti which is too old to be supported by the triton GPU compiler, which is used as the backend. Triton only supports devices of CUDA Capability >= 7.0, but your device is of CUDA capability 6.1`, however according to [This github link](https://gist.github.com/standaloneSA/99788f30466516dbcc00338b36ad5acf) GTX1080 Ti should be able to support CUDA 8+, 

[https://gist.github.com/standaloneSA/99788f30466516dbcc00338b36ad5acf](https://gist.github.com/standaloneSA/99788f30466516dbcc00338b36ad5acf)

Please let me know if more details I should provide.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Load the HQQ model - success with no error
2. Gen text using Chat Tab or Notebook - fail and error

### Logs

```shell
Traceback (most recent call last):

  File "/home/wa/text-generation-webui/modules/callbacks.py", line 61, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/modules/text_generation.py", line 390, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/generation/utils.py", line 1592, in generate
    return self.sample(
           ^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/generation/utils.py", line 2696, in sample
    outputs = self(
              ^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 1176, in forward
    outputs = self.model(
              ^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 1019, in forward
    layer_outputs = decoder_layer(
                    ^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 740, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
                                                          ^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 639, in forward
    query_states = self.q_proj(hidden_states)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 489, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/hqq/core/quantize.py", line 440, in forward_pytorch_compile
    @torch.compile()
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/hqq/core/quantize.py", line 434, in forward_pytorch
    def forward_pytorch(self, x):
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 655, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 727, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 383, in _convert_frame_assert
    compiled_product = _compile(
                       ^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 646, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 562, in compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 527, in transform
    tracer.run()
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2128, in run
    super().run()
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 818, in run
    and self.step()
        ^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 731, in step
    return self.step_graph_break(inst)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 796, in step_graph_break
    self.output.compile_subgraph(
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 945, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 1087, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 1159, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 1140, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/__init__.py", line 1668, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 1168, in compile_fx
    return aot_autograd(
           ^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 887, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 600, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 425, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 630, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 97, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 1100, in fw_compiler_base
    return inner_compile(
           ^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_inductor/debug.py", line 305, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 320, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 550, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_inductor/graph.py", line 1116, in compile_to_fn
    return self.compile_to_module().call
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_inductor/graph.py", line 1066, in compile_to_module
    self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()
                                                             ^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_inductor/graph.py", line 1041, in codegen
    self.scheduler = Scheduler(self.buffers)
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_inductor/scheduler.py", line 1198, in __init__
    self.nodes = [self.create_scheduler_node(n) for n in nodes]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_inductor/scheduler.py", line 1198, in <listcomp>
    self.nodes = [self.create_scheduler_node(n) for n in nodes]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_inductor/scheduler.py", line 1289, in create_scheduler_node
    group_fn = self.get_backend(node.get_device()).group_fn
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_inductor/scheduler.py", line 2154, in get_backend
    self.backends[device] = self.create_backend(device)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wa/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/_inductor/scheduler.py", line 2142, in create_backend
    raise RuntimeError(
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: Found NVIDIA GeForce GTX 1080 Ti which is too old to be supported by the triton GPU compiler, which is used as the backend. Triton only supports devices of CUDA Capability >= 7.0, but your device is of CUDA capability 6.1

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

Output generated in 0.72 seconds (0.00 tokens/s, 0 tokens, context 71, seed 2053295084)
```

### System Info

```shell
Intel 12th Gen CPU
Ubuntu 23.10
GTX1080 Ti (via eGPU)
Nvidia driver: 550.54
mobiuslabsgmbh_Llama-2-13b-chat-hf-4bit_g64-HQQ
Oobabooga dev branch
```

**Comment by Ph0rk0z** [comment]
Triton doesn't work with pascal cards. I tried it and tried to ask them to make it work but they did not.

**Comment by Juqowel** [comment]
Look at the `Compute Capability`(Microarchitecture) column, not the `CUDA Support`(CUDA SDK support).
`your device is of CUDA capability 6.1`
^That's true.

**Comment by wwithoutn** [comment]
Ok I confused between CUDA support and Compute Capability, thanks both.
