### ISSUE TITLE
Fail to load any model with autoawq, aft pull/update latest codes, says "undefined symbol"

### ISSUE THREAD

**Issue by sdwcn** [oobabooga/text-generation-webui#5674]
### Describe the bug

Fail to load any model with autoawq, aft pull/update latest codes, says "undefined symbol"

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Fail to load any model with autoawq, aft pull/update latest codes, says "undefined symbol"

### Logs

```shell
01:24:40-433953 ERROR    Failed to load the model.                                                                                                                
Traceback (most recent call last):
  File "/mnt/data/ntg/text-generation-webui/modules/ui_model_menu.py", line 243, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/ntg/text-generation-webui/modules/models.py", line 87, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/ntg/text-generation-webui/modules/models.py", line 298, in AutoAWQ_loader
    from awq import AutoAWQForCausalLM
  File "/mnt/data/ntg/text-generation-webui/installer_files/env/lib/python3.11/site-packages/awq/__init__.py", line 2, in <module>
    from awq.models.auto import AutoAWQForCausalLM
  File "/mnt/data/ntg/text-generation-webui/installer_files/env/lib/python3.11/site-packages/awq/models/__init__.py", line 1, in <module>
    from .mpt import MptAWQForCausalLM
  File "/mnt/data/ntg/text-generation-webui/installer_files/env/lib/python3.11/site-packages/awq/models/mpt.py", line 1, in <module>
    from .base import BaseAWQForCausalLM
  File "/mnt/data/ntg/text-generation-webui/installer_files/env/lib/python3.11/site-packages/awq/models/base.py", line 16, in <module>
    from awq.modules.linear import WQLinear_GEMM, WQLinear_GEMV
  File "/mnt/data/ntg/text-generation-webui/installer_files/env/lib/python3.11/site-packages/awq/modules/linear.py", line 4, in <module>
    import awq_inference_engine  # with CUDA kernels
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: /mnt/data/ntg/text-generation-webui/installer_files/env/lib/python3.11/site-packages/awq_inference_engine.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops15sum_dim_IntList4callERKNS_6TensorEN3c1016OptionalArrayRefIlEEbNS5_8optionalINS5_10ScalarTypeEEE
```

### System Info

```shell
cuda 12.2
nvidia 4090
x86_64
centos7
python 311
torch                     2.2.1+cu121
torchaudio                2.2.1+cu121
torchvision               0.17.1+cu121
flash-attn                2.5.6
autoawq                   0.1.8
autoawq_kernels           0.0.6
```

**Comment by younesbelkada** [comment]
related to: https://github.com/casper-hansen/AutoAWQ/issues/367#issuecomment-1986243134 can you try to import torch before importing awq?

**Comment by sdwcn** [comment]
> related to: [casper-hansen/AutoAWQ#367 (comment)](https://github.com/casper-hansen/AutoAWQ/issues/367#issuecomment-1986243134) can you try to import torch before importing awq?

The error is thrown when loading any awq models, I was not trying to modify original codebase in any ways, 
I pip install -r requirements.txt all default requirements :
autoawq                   0.1.8
autoawq_kernels           0.0.6

it specifically point to line:
import awq_inference_engine  # with CUDA kernels
-----------------------------------------------
^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: /mnt/data/ntg/text-generation-webui/installer_files/env/lib/python3.11/site-packages/awq_inference_engine.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops15sum_dim_IntList4callERKNS_6TensorEN3c1016OptionalArrayRefIlEEbNS5_8optionalINS5_10ScalarTypeEEE

**Comment by sdwcn** [comment]
> related to: [casper-hansen/AutoAWQ#367 (comment)](https://github.com/casper-hansen/AutoAWQ/issues/367#issuecomment-1986243134) can you try to import torch before importing awq?

# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Jun_13_19:16:58_PDT_2023
Cuda compilation tools, release 12.2, V12.2.91
Build cuda_12.2.r12.2/compiler.32965470_0

# python
Python 3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.version.cuda) 
12.1
>>> import awq_ext
>>> import awq_inference_engine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /data/ntg/text-generation-webui/installer_files/env/lib/python3.11/site-packages/awq_inference_engine.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops15sum_dim_IntList4callERKNS_6TensorEN3c1016OptionalArrayRefIlEEbNS5_8optionalINS5_10ScalarTypeEEE

---------------------------------------------
Im having 12.2, should be compatiable with cuda 12.1, as well the latest requirements.txt contains both cu121 & cu122

**Comment by CySlider** [comment]
I have the same issue.
It did work fine, then after an update I now also get this error.

**Comment by casper-hansen** [comment]
This is an environment issue. Please install torch 2.2.0 with cuda 11.8 or cuda 12.1.

**Comment by CySlider** [comment]
even when using the docker?
