### ISSUE TITLE
Model doesn't load in 4-bit, but loads in 8-bit

### ISSUE THREAD

**Issue by deadpipe** [oobabooga/text-generation-webui#5699]
### Describe the bug

Hi. I'm trying to load a model using transformers in 4-bit, but I keep getting an error. However, it does load in 8-bit, though it eats up more RAM and VRAM.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Try to load a model in 4-bit using Transformers

See attached video below:

### Screenshot

https://github.com/oobabooga/text-generation-webui/assets/142412134/37d9a148-d491-40bc-9ea9-d83dbf41875a

### Logs

```shell
When i try to load in 4bit:




Traceback (most recent call last):
  File "/home/abzu/Desktop/text-generation-webui/modules/ui_model_menu.py", line 245, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abzu/Desktop/text-generation-webui/modules/models.py", line 87, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abzu/Desktop/text-generation-webui/modules/models.py", line 235, in huggingface_loader
    model = LoaderClass.from_pretrained(path_to_model, **params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abzu/Desktop/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abzu/Desktop/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3452, in from_pretrained
    hf_quantizer.validate_environment(device_map=device_map)
  File "/home/abzu/Desktop/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/quantizers/quantizer_bnb_4bit.py", line 86, in validate_environment
    raise ValueError(
ValueError: 
                    Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit the
                    quantized model. If you want to dispatch the model on the CPU or the disk while keeping these modules
                    in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom `device_map` to
                    `from_pretrained`. Check
                    https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                    for more details.
```

### System Info

```shell
RTX 3090 24GB
RTX 3060 12GB
32 GB RAM
i7-7700k
Ubuntu 22.04 & Windows 10 (receiving same error on both OS)
```

Any help is appreciated

**Comment by deadpipe** [comment]
Does anybody have a solution?
