### ISSUE TITLE
Running start_windows.bat ends with an error

### ISSUE THREAD

**Issue by Y-PLONI** [oobabooga/text-generation-webui#5701]
### Describe the bug

Here is the bug:
`Traceback (most recent call last):
  File "C:\Users\user\Downloads\text-generation-webui-main\server.py", line 4, in <module>
    from modules import shared
  File "C:\Users\user\Downloads\text-generation-webui-main\modules\shared.py", line 8, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
Press any key to continue . . .
`
The installation itself was completed successfully. Searching the folders we see YAML installed.

The model found in the models folder is: gemma-2b.gguf from the link:
https://huggingface.co/google/gemma-2b-GGUF/tree/main

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Running start_windows.bat

### Logs

```shell
French in the post.
Do I need to add anything else?
```

### System Info

```shell
Windows 11 23H2, no GPU
```

**Comment by wwithoutn** [comment]
Same issue here, still researching if any solution

Tried and not work
- Run update_linux.sh
- Delete all files in Installer_files and re-run the start_linux.sh
- Re pull a clean text-gen-ui and run start_linux.sh

System Info
Ubuntu 23.10
eGPU GTX 1080Ti

**Comment by kalle07** [comment]
UPDATE ERROR !!! all the time   : D

**Comment by Touch-Night** [comment]
I think it's because some packages were not correctly downloaded/installed, but the .bat just went on.
