### ISSUE TITLE
trust_remote_code=True

### ISSUE THREAD

**Issue by one-pip** [oobabooga/text-generation-webui#5730]
### Describe the bug

When i lode modle with transformer, but it mentioned me error. what is problem with that?
why i can't choose truse-remote-code option?

ValueError: Loading models\TheBloke_Yi-6B-GPTQ requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option trust_remote_code=True to remove this error

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

ValueError: Loading models\TheBloke_Yi-6B-GPTQ requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option trust_remote_code=True to remove this error

### Logs

```shell
Traceback (most recent call last):

File "D:\NEW_OOBA\TANG\text-generation-webui11111111\modules\ui_model_menu.py", line 245, in load_model_wrapper


shared.model, shared.tokenizer = load_model(selected_model, loader)

                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\NEW_OOBA\TANG\text-generation-webui11111111\modules\models.py", line 87, in load_model


output = load_func_map[loader](model_name)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\NEW_OOBA\TANG\text-generation-webui11111111\modules\models.py", line 140, in huggingface_loader


config = AutoConfig.from_pretrained(path_to_model, trust_remote_code=params['trust_remote_code'])

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\NEW_OOBA\TANG\text-generation-webui11111111\installer_files\env\Lib\site-packages\transformers\models\auto\configuration_auto.py", line 1114, in from_pretrained


trust_remote_code = resolve_trust_remote_code(

                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\NEW_OOBA\TANG\text-generation-webui11111111\installer_files\env\Lib\site-packages\transformers\dynamic_module_utils.py", line 621, in resolve_trust_remote_code


raise ValueError(
ValueError: Loading models\TheBloke_Yi-6B-GPTQ requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option trust_remote_code=True to remove this error.
```

### System Info

```shell
I7
4090
WIN12
```

**Comment by Alkohole** [comment]
Run webui with key `--trust-remote-code`.
Example:
```
python3 server.py --trust-remote-code
```

**Comment by one-pip** [comment]
> Run webui with key `--trust-remote-code`. Example:
> 
> ```
> python3 server.py --trust-remote-code
> ```

thanks for instruction, but i am little knowledge about it, can you give me more details, such which file i should go to set the option trust_remote_code=True.

**Comment by Alkohole** [comment]
In the `CMD_FLAGS.txt` file, you must write `--trust-remote-code`
Example `CMD_FLAGS.txt` file:
```
# Only used by the one-click installer.
# Example:
# --listen --api
--trust-remote-code
```

**Comment by one-pip** [comment]
> In the `CMD_FLAGS.txt` file, you must write `--trust-remote-code` Example `CMD_FLAGS.txt` file:
> 
> ```
> # Only used by the one-click installer.
> # Example:
> # --listen --api
> --trust-remote-code
> ```

Thank you very much for your help, it works now.  ：）
