### ISSUE TITLE
Can only load 54 layers of Undi95/SolarMaid-v0.1.1-GGUF 4 bits on GPU (ROCm)

### ISSUE THREAD

**Issue by nonetrix** [oobabooga/text-generation-webui#5733]
### Describe the bug

For some reason with this model you are only able to load 54 layers to the GPU before it will error out with the following message
```
17:41:28-611506 ERROR    Failed to load the model.
Traceback (most recent call last):
  File "/home/noah/Documents/AI/text-generation-webui/modules/ui_model_menu.py", line 245, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noah/Documents/AI/text-generation-webui/modules/models.py", line 87, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noah/Documents/AI/text-generation-webui/modules/models.py", line 250, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noah/Documents/AI/text-generation-webui/modules/llamacpp_model.py", line 102, in from_pretrained
    result.model = Llama(**params)
                   ^^^^^^^^^^^^^^^
  File "/home/noah/Documents/AI/text-generation-webui/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda/llama.py", line 325, in __init__
    self._ctx = _LlamaContext(
                ^^^^^^^^^^^^^^
  File "/home/noah/Documents/AI/text-generation-webui/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda/_internals.py", line 265, in __init__
    raise ValueError("Failed to create llama_context")
ValueError: Failed to create llama_context

Exception ignored in: <function LlamaCppModel.__del__ at 0x7f1b48820c20>
Traceback (most recent call last):
  File "/home/noah/Documents/AI/text-generation-webui/modules/llamacpp_model.py", line 58, in __del__
    del self.model
        ^^^^^^^^^^
AttributeError: 'LlamaCppModel' object has no attribute 'model'
```
Loading exactly 54 and below works fine just anything above 54 fails even though the model has 73 layers in total

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Download the model in 4 bits
2. Try to load more than 54 layers
3. See crash

### Logs

```shell
17:41:28-611506 ERROR    Failed to load the model.
Traceback (most recent call last):
  File "/home/noah/Documents/AI/text-generation-webui/modules/ui_model_menu.py", line 245, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noah/Documents/AI/text-generation-webui/modules/models.py", line 87, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noah/Documents/AI/text-generation-webui/modules/models.py", line 250, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noah/Documents/AI/text-generation-webui/modules/llamacpp_model.py", line 102, in from_pretrained
    result.model = Llama(**params)
                   ^^^^^^^^^^^^^^^
  File "/home/noah/Documents/AI/text-generation-webui/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda/llama.py", line 325, in __init__
    self._ctx = _LlamaContext(
                ^^^^^^^^^^^^^^
  File "/home/noah/Documents/AI/text-generation-webui/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda/_internals.py", line 265, in __init__
    raise ValueError("Failed to create llama_context")
ValueError: Failed to create llama_context

Exception ignored in: <function LlamaCppModel.__del__ at 0x7f1b48820c20>
Traceback (most recent call last):
  File "/home/noah/Documents/AI/text-generation-webui/modules/llamacpp_model.py", line 58, in __del__
    del self.model
        ^^^^^^^^^^
AttributeError: 'LlamaCppModel' object has no attribute 'model'
```

### System Info
Host:
```


          ▗▄▄▄       ▗▄▄▄▄    ▄▄▄▖            noah@nixos
          ▜███▙       ▜███▙  ▟███▛            ----------
           ▜███▙       ▜███▙▟███▛             OS: NixOS 24.05.20240312.0ad13a6 (Uakari) x86_64
            ▜███▙       ▜██████▛              Host: Gigabyte Technology Co., Ltd. B450 AORUS PRO WIFI-CF
     ▟█████████████████▙ ▜████▛     ▟▙        Kernel: 6.8.0
    ▟███████████████████▙ ▜███▙    ▟██▙       Uptime: 1 hour, 21 mins
           ▄▄▄▄▖           ▜███▙  ▟███▛       Packages: 2235 (nix-system), 1073 (nix-user), 30 (flatpak)
          ▟███▛             ▜██▛ ▟███▛        Shell: zsh 5.9
         ▟███▛               ▜▛ ▟███▛         Resolution: 1920x1080, 1920x1200
▟███████████▛                  ▟██████████▙   DE: Hyprland (Wayland)
▜██████████▛                  ▟███████████▛   Theme: Catppuccin-Mocha-Standard-Sapphire-Dark [GTK2/3]
      ▟███▛ ▟▙               ▟███▛            Icons: Papirus-Dark [GTK2/3]
     ▟███▛ ▟██▙             ▟███▛             Terminal: WezTerm
    ▟███▛  ▜███▙           ▝▀▀▀▀              CPU: AMD Ryzen 7 3700X (16) @ 3.600GHz
    ▜██▛    ▜███▙ ▜██████████████████▛        GPU: AMD ATI Radeon RX 6800/6800 XT / 6900 XT
     ▜▛     ▟████▙ ▜████████████████▛         Memory: 6052MiB / 64232MiB
           ▟██████▙       ▜███▙
          ▟███▛▜███▙       ▜███▙
         ▟███▛  ▜███▙       ▜███▙
         ▝▀▀▀    ▀▀▀▀▘       ▀▀▀▘
```
Container:
```
                   -`                    noah@ai.nixos
                  .o+`                   -------------
                 `ooo/                   OS: Arch Linux x86_64
                `+oooo:                  Host: B450 AORUS PRO WIFI
               `+oooooo:                 Kernel: 6.8.0
               -+oooooo+:                Uptime: 1 hour, 22 mins
             `/:-:++oooo+:               Packages: 445 (pacman)
            `/++++/+++++++:              Shell: zsh 5.9
           `/++++++++++++++:             Resolution: 1920x1200
          `/+++ooooooooooooo/`           DE: Hyprland
         ./ooosssso++osssssso+`          Theme: Catppuccin-Mocha-Standard-Sapphire-Dark [GTK2/3]
        .oossssso-````/ossssss+`         Icons: Papirus-Dark [GTK2/3]
       -osssssso.      :ssssssso.        Terminal: WezTerm
      :osssssss/        osssso+++.       CPU: AMD Ryzen 7 3700X (16) @ 3.600GHz
     /ossssssss/        +ssssooo/-       GPU: AMD ATI Radeon RX 6800/6800 XT / 6900 XT
   `/ossssso+/:-        -:/+osssso+-     Memory: 5241MiB / 64232MiB
  `+sso+:-`                 `.-/+oso:
 `++:.                           `-/+/
 .`                                 `/
```

**Comment by nonetrix** [comment]
Sorry no idea what happened to the formatting I think Github broke something
