### ISSUE TITLE
Since separating "User" details to separate tab in Chat, API calls are broken.

### ISSUE THREAD

**Issue by AightBits** [oobabooga/text-generation-webui#5739]
### Describe the bug

Error in API calls since last update (tried both Linux and Windows installs). Seems to be related to the new "User" panel under "Chat."

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Reproduction

All API calls using /v1/chat/completions (didn't test others).

### Logs

```shell
|   File "/home/xxx/text-generation-webui-main/modules/chat.py", line 97, in generate_chat_prompt
    |     user_bio=replace_character_names(state['user_bio'], state['name1'], state['name2']),
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/xxx/text-generation-webui-main/modules/chat.py", line 636, in replace_character_names
    |     text = text.replace('{{user}}', name1).replace('{{char}}', name2)
    |            ^^^^^^^^^^^^
    | AttributeError: 'NoneType' object has no attribute 'replace'
```

### System Info

```shell
Linux, Windows
```

**Comment by JeremySunSAS** [comment]
I have same issue
Exception in ASGI application
Traceback (most recent call last):
  File "/hadoop/hdd_sdt/text-generation-webui/installer_files/env/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hadoop/hdd_sdt/text-generation-webui/installer_files/env/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hadoop/hdd_sdt/text-generation-webui/installer_files/env/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/hadoop/hdd_sdt/text-generation-webui/installer_files/env/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/hadoop/hdd_sdt/text-generation-webui/installer_files/env/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/hadoop/hdd_sdt/text-generation-webui/installer_files/env/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/hadoop/hdd_sdt/text-generation-webui/installer_files/env/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/hadoop/hdd_sdt/text-generation-webui/installer_files/env/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/hadoop/hdd_sdt/text-generation-webui/installer_files/env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/hadoop/hdd_sdt/text-generation-webui/installer_files/env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/hadoop/hdd_sdt/text-generation-webui/installer_files/env/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/hadoop/hdd_sdt/text-generation-webui/installer_files/env/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/hadoop/hdd_sdt/text-generation-webui/installer_files/env/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/hadoop/hdd_sdt/text-generation-webui/installer_files/env/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/hadoop/hdd_sdt/text-generation-webui/installer_files/env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/hadoop/hdd_sdt/text-generation-webui/installer_files/env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/hadoop/hdd_sdt/text-generation-webui/installer_files/env/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/hadoop/hdd_sdt/text-generation-webui/installer_files/env/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hadoop/hdd_sdt/text-generation-webui/installer_files/env/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hadoop/hdd_sdt/text-generation-webui/extensions/openai/script.py", line 137, in openai_chat_completions
    response = OAIcompletions.chat_completions(to_dict(request_data), is_legacy=is_legacy)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hadoop/hdd_sdt/text-generation-webui/extensions/openai/completions.py", line 536, in chat_completions
    return deque(generator, maxlen=1).pop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hadoop/hdd_sdt/text-generation-webui/extensions/openai/completions.py", line 315, in chat_completions_common
    prompt = generate_chat_prompt(user_input, generate_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hadoop/hdd_sdt/text-generation-webui/modules/chat.py", line 97, in generate_chat_prompt
    user_bio=replace_character_names(state['user_bio'], state['name1'], state['name2']),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hadoop/hdd_sdt/text-generation-webui/modules/chat.py", line 636, in replace_character_names
    text = text.replace('{{user}}', name1).replace('{{char}}', name2)
           ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by BaronOfClubs** [comment]
Temporary solution in #5722 . 
My workaround was to put an empty "user_bio" string in the API call.
```
data = {
    "mode": "chat",
    "character": character,
    "messages": history,
     "user_bio": ""
}
```

**Comment by ElioDonato** [comment]
Change the function in modules/chat.py

```python
def replace_character_names(text, name1, name2):
    text = text.replace('{{user}}', name1).replace('{{char}}', name2)
    return text.replace('<USER>', name1).replace('<BOT>', name2)
```

to

```python
def replace_character_names(text, name1, name2):
    if text is None:
        return ""
    text = text.replace('{{user}}', name1).replace('{{char}}', name2)
    return text.replace('<USER>', name1).replace('<BOT>', name2)
```

Should fix it.

**Comment by charltonh** [comment]
> Change the function in modules/chat.py
> 
> ```python
> def replace_character_names(text, name1, name2):
>     text = text.replace('{{user}}', name1).replace('{{char}}', name2)
>     return text.replace('<USER>', name1).replace('<BOT>', name2)
> ```
> 
> to
> 
> ```python
> def replace_character_names(text, name1, name2):
>     if text is None:
>         return ""
>     text = text.replace('{{user}}', name1).replace('{{char}}', name2)
>     return text.replace('<USER>', name1).replace('<BOT>', name2)
> ```
> 
> Should fix it.

This worked!!

But why has this bug gone unnoticed and this simple fix not in the repository yet?

**Comment by Wladastic** [comment]
@charltonh probably another case of coding and reviewing without actually testing or using the product the devs code on.
Could be evaded by more unit tests tbh. but noone likes to write them.

**Comment by rosx27** [comment]
> Change the function in modules/chat.py
> 
> ```python
> def replace_character_names(text, name1, name2):
>     text = text.replace('{{user}}', name1).replace('{{char}}', name2)
>     return text.replace('<USER>', name1).replace('<BOT>', name2)
> ```
> 
> to
> 
> ```python
> def replace_character_names(text, name1, name2):
>     if text is None:
>         return ""
>     text = text.replace('{{user}}', name1).replace('{{char}}', name2)
>     return text.replace('<USER>', name1).replace('<BOT>', name2)
> ```
> 
> Should fix it.

this works! thanks!

**Comment by thistleknot** [comment]
Chat completions added a new key value pair called user_bio. I swear I tried that fix and it didn't work for me, but maybe I didn't do something right. Now I simply add user_bio w "" as value

**Comment by Koesn** [comment]
> Change the function in modules/chat.py
> 
> ```python
> def replace_character_names(text, name1, name2):
>     text = text.replace('{{user}}', name1).replace('{{char}}', name2)
>     return text.replace('<USER>', name1).replace('<BOT>', name2)
> ```
> 
> to
> 
> ```python
> def replace_character_names(text, name1, name2):
>     if text is None:
>         return ""
>     text = text.replace('{{user}}', name1).replace('{{char}}', name2)
>     return text.replace('<USER>', name1).replace('<BOT>', name2)
> ```
> 
> Should fix it.

This is works for me. Thank's!
