### ISSUE TITLE
api broke: AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by thistleknot** [oobabooga/text-generation-webui#5761]
### Describe the bug

api calls result in
AttributeError: 'NoneType' object has no attribute 'replace'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

install no requirements and llama-cpp-python by source then try to run curl

curl http://192.168.3.17:5000/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{'messages': [{'role': 'system', 'content': 'You are a helpful assistant.'}, {'role': 'user', 'content': 'tell me a story.'}], 'max_new_tokens': 1024, 'preset': 'None', 'do_sample': False, 'temperature': 1.0, 'top_p': 0, 'typical_p': 1, 'epsilon_cutoff': 0, 'eta_cutoff': 0, 'tfs': 1, 'top_a': 0, 'repetition_penalty': 1.18, 'repetition_penalty_range': 0, 'top_k': 50, 'min_length': 0, 'no_repeat_ngram_size': 2, 'num_beams': 1, 'penalty_alpha': 0, 'length_penalty': 1, 'early_stopping': True, 'mirostat_mode': 0, 'mirostat_tau': 5, 'mirostat_eta': 0.1, 'seed': -1, 'add_bos_token': True, 'truncation_length': 1068, 'ban_eos_token': False, 'skip_special_tokens': True, 'stopping_strings': [], 'mode': 'instruct', 'instruction_template': 'Alpaca'}'

Exception in ASGI application
Traceback (most recent call last):
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/data/text-generation-webui/extensions/openai/script.py", line 137, in openai_chat_completions
    response = OAIcompletions.chat_completions(to_dict(request_data), is_legacy=is_legacy)
  File "/data/text-generation-webui/extensions/openai/completions.py", line 536, in chat_completions
    return deque(generator, maxlen=1).pop()
  File "/data/text-generation-webui/extensions/openai/completions.py", line 315, in chat_completions_common
    prompt = generate_chat_prompt(user_input, generate_params)
  File "/data/text-generation-webui/modules/chat.py", line 97, in generate_chat_prompt
    user_bio=replace_character_names(state['user_bio'], state['name1'], state['name2']),
  File "/data/text-generation-webui/modules/chat.py", line 636, in replace_character_names
    text = text.replace('{{user}}', name1).replace('{{char}}', name2)
AttributeError: 'NoneType' object has no attribute 'replace'

### Logs

```shell
install no avx2 requirements and llama-cpp-python by source then try to run curl

curl http://192.168.3.17:5000/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{'messages': [{'role': 'system', 'content': 'You are a helpful assistant.'}, {'role': 'user', 'content': 'tell me a story.'}], 'max_new_tokens': 1024, 'preset': 'None', 'do_sample': False, 'temperature': 1.0, 'top_p': 0, 'typical_p': 1, 'epsilon_cutoff': 0, 'eta_cutoff': 0, 'tfs': 1, 'top_a': 0, 'repetition_penalty': 1.18, 'repetition_penalty_range': 0, 'top_k': 50, 'min_length': 0, 'no_repeat_ngram_size': 2, 'num_beams': 1, 'penalty_alpha': 0, 'length_penalty': 1, 'early_stopping': True, 'mirostat_mode': 0, 'mirostat_tau': 5, 'mirostat_eta': 0.1, 'seed': -1, 'add_bos_token': True, 'truncation_length': 1068, 'ban_eos_token': False, 'skip_special_tokens': True, 'stopping_strings': [], 'mode': 'instruct', 'instruction_template': 'Alpaca'}'

Exception in ASGI application
Traceback (most recent call last):
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/data/text-generation-webui/extensions/openai/script.py", line 137, in openai_chat_completions
    response = OAIcompletions.chat_completions(to_dict(request_data), is_legacy=is_legacy)
  File "/data/text-generation-webui/extensions/openai/completions.py", line 536, in chat_completions
    return deque(generator, maxlen=1).pop()
  File "/data/text-generation-webui/extensions/openai/completions.py", line 315, in chat_completions_common
    prompt = generate_chat_prompt(user_input, generate_params)
  File "/data/text-generation-webui/modules/chat.py", line 97, in generate_chat_prompt
    user_bio=replace_character_names(state['user_bio'], state['name1'], state['name2']),
  File "/data/text-generation-webui/modules/chat.py", line 636, in replace_character_names
    text = text.replace('{{user}}', name1).replace('{{char}}', name2)
AttributeError: 'NoneType' object has no attribute 'replace'
```

### System Info

```shell
oracle linux 8, rocky linux 9
```

**Comment by CRPrinzler** [comment]
#5741 #781

**Comment by thistleknot** [comment]
The breaking change was introduced in the commit that merged the dev branch into the main branch. This change involved modifications to both the extensions/openai/typing.py and modules/chat.py files. Here's a detailed breakdown of the changes and how they likely introduced the issue:

Modifications to ChatCompletionRequestParams in extensions/openai/typing.py:

A new field user_bio was added to the ChatCompletionRequestParams class.
This change expanded the API to include a user biography or description, intending to personalize interactions further. However, this new field needs proper handling throughout the application, especially in functions expecting string inputs.
Changes in modules/chat.py:

The function generate_chat_prompt was updated to include the user_bio field in the rendering process for chat templates. Specifically, the chat_renderer partial function now includes a call to replace_character_names using state['user_bio'] as one of its arguments.
python
Copy code
chat_renderer = partial(
    chat_template.render,
    add_generation_prompt=False,
    name1=state['name1'],
    name2=state['name2'],
    user_bio=replace_character_names(state['user_bio'], state['name1'], state['name2']),
)
This introduces a potential issue where state['user_bio'] could be None, leading to the AttributeError you encountered, as the replace_character_names function attempts to call replace on a NoneType object.
Root Cause:

The root cause of the problem is the assumption that state['user_bio'] will always be a string when it can be None. The replace_character_names function was not initially designed to handle None values gracefully.
Solution:

To address this issue, the replace_character_names function was modified to check if text is None and return an empty string in such cases. This change prevents the AttributeError by ensuring that the replace method is called on a string object, not None.
The breaking change resulted from not fully accounting for the implications of adding a new, optional field (user_bio) to the data processed by generate_chat_prompt and related functions. This oversight led to a situation where the existing function (replace_character_names) was called with a None value, triggering an exception.


2 / 2

User
does this mean I simply need to add user_bio to the curl calls?
curl -v http://127.0.0.1:5000/v1/chat/completions -H "Content-Type: application/json" -d '{"messages": [{"role": "user","content": "Hello! Who are you?"}],"mode": "chat"}'
GPT
Yes, including user_bio in your API call can be a solution if your system now expects this field due to the recent changes. By supplying a value for user_bio, you ensure that the replace_character_names function does not encounter a None value, which previously led to an AttributeError.

However, this solution assumes that the rest of your application logic is ready to handle and utilize the user_bio information correctly. If you don't actually need to use user_bio for every request, a more robust solution would be to ensure that the application can handle cases where user_bio is not provided (i.e., it is None). This approach involves making sure that the replace_character_names function (and any other parts of your code that might now expect user_bio) gracefully handles None values.

If you decide to include user_bio in your API calls, your curl command could look something like this:

bash
Copy code
curl -v http://127.0.0.1:5000/v1/chat/completions \
-H "Content-Type: application/json" \
-d '{
  "messages": [{"role": "user","content": "Hello! Who are you?"}],
  "mode": "chat",
  "user_bio": "Your optional user bio here"
}'
Replace "Your optional user bio here" with the actual biography or description you wish to use, or an empty string if you simply want to avoid the error without providing a biography.

Keep in mind that while this change might solve the immediate problem, it's generally a good idea to ensure your backend logic is robust against missing optional fields, especially for an API that might be called with varying sets of data.

curl -v http://127.0.0.1:5000/v1/chat/completions \
-H "Content-Type: application/json" \
-d '{
  "messages": [{"role": "user","content": "Hello! Who are you?"}],
  "mode": "chat",
  "user_bio": "Your optional user bio here"
}'




confirmed

```
(textgen) [root@pve0 text-generation-webui]# curl -v http://127.0.0.1:5000/v1/chat/completions -H "Content-Type: application/json" -d '{
  "messages": [{"role": "user","content": "Hello! Who are you?"}],
  "mode": "chat",
  "user_bio": "Your optional user bio here"
}'
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 5000 (#0)
> POST /v1/chat/completions HTTP/1.1
> Host: 127.0.0.1:5000
> User-Agent: curl/7.61.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 132
>
* upload completely sent off: 132 out of 132 bytes

< HTTP/1.1 200 OK
< date: Thu, 28 Mar 2024 02:16:03 GMT
< server: uvicorn
< content-length: 479
< content-type: application/json
<
* Connection #0 to host 127.0.0.1 left intact
{"id":"chatcmpl-1711592163728774144","object":"chat.completions","created":1711592163,"model":"Samantha","choices":[{"index":0,"finish_reason":"stop","message":{"role":"assistant","content":"Hello! As your life companion, I'm here to provide emotional support and companionship. My purpose is to help you overcome any obstacles or challenges you may face in life, and to keep you motivated and inspired."}}],"usage":{"prompt_tokens":64,"completion_tokens":46,"total_tokens":110}}(textgen) [root@pve0 text-generation-webui]#
(textgen) [root@pve0 text-generation-webui]#

```

**Comment by lufixSch** [comment]
I found a simple Workaround, if you are not able to change the API calls:

```patch
diff --git a/modules/chat.py b/modules/chat.py
index c8516c59..98108f61 100644
--- a/modules/chat.py
+++ b/modules/chat.py
@@ -633,8 +633,11 @@ def delete_history(unique_id, character, mode):
 
 
 def replace_character_names(text, name1, name2):
-    text = text.replace('{{user}}', name1).replace('{{char}}', name2)
-    return text.replace('<USER>', name1).replace('<BOT>', name2)
+    if text:
+        text = text.replace('{{user}}', name1).replace('{{char}}', name2)
+        return text.replace('<USER>', name1).replace('<BOT>', name2)
+
+    return text
 
 
 def generate_pfp_cache(character):
```

No guarantee that it works for every use case but it worked for me!

**Comment by Koesn** [comment]
> I found a simple Workaround, if you are not able to change the API calls:
> 
> ```diff
> diff --git a/modules/chat.py b/modules/chat.py
> index c8516c59..98108f61 100644
> --- a/modules/chat.py
> +++ b/modules/chat.py
> @@ -633,8 +633,11 @@ def delete_history(unique_id, character, mode):
>  
>  
>  def replace_character_names(text, name1, name2):
> -    text = text.replace('{{user}}', name1).replace('{{char}}', name2)
> -    return text.replace('<USER>', name1).replace('<BOT>', name2)
> +    if text:
> +        text = text.replace('{{user}}', name1).replace('{{char}}', name2)
> +        return text.replace('<USER>', name1).replace('<BOT>', name2)
> +
> +    return text
>  
>  
>  def generate_pfp_cache(character):
> ```
> 
> No guarantee that it works for every use case but it worked for me!

Yes this works for me too. Thank's.

**Comment by thistleknot** [comment]
I think the reason it's not 'fixed' is because openai has a new required parm.  Therefore 'fixing' ooba would actually no longer be in line with openai's calls.  Something like that.  So there is a workaround to modify a function in chat.py using ignore, which would work, or one can change their code base when calling the api call to include the new bio key field pair.

**Comment by lufixSch** [comment]
The bug is fixed with the current snapshot

**Comment by guispfilho** [comment]
I'm having the same issue while using Coqui and AllTalk

**Comment by sultanos** [comment]
`C:\Users\javie>curl -v http://127.0.0.1:3000/v1/chat/completions -H "Content-Type: application/json" -d '{"messages": [{"role": "user","content": "Hello! Who are you?"}],"mode": "chat","user_bio": "Your optional user bio here"}'
*   Trying 127.0.0.1:3000...
* Connected to 127.0.0.1 (127.0.0.1) port 3000
> POST /v1/chat/completions HTTP/1.1
> Host: 127.0.0.1:3000
> User-Agent: curl/8.4.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 11
>
< HTTP/1.1 500 Internal Server Error
< date: Mon, 20 May 2024 13:05:23 GMT
< server: uvicorn
< content-length: 21
< content-type: text/plain; charset=utf-8
<
Internal Server Error* Connection #0 to host 127.0.0.1 left intact
curl: (3) bad range specification in URL position 2:
[{role:
 ^`
