### ISSUE TITLE
loading model errors

### ISSUE THREAD

**Issue by ARCIST-AI** [oobabooga/text-generation-webui#5764]
### Describe the bug

I recently reinstalled my os so i had to reload the webui and ive had some issues. Ive downloaded a couple of mixtral gguf models. When I load them the model loader box beneath the downloaded model box will switch to llama.cpp and i get a bunch of errors to do with llama.
<img width="1160" alt="Screenshot 2024-03-27 at 14 42 42" src="https://github.com/oobabooga/text-generation-webui/assets/96149457/d2780333-e9ad-411e-80f0-9b159d32b177">

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

load a model

### Logs

```shell
^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'Llama'

14:41:48-159727 INFO     Loading "mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf"       
14:41:48-226431 INFO     llama.cpp weights detected:                            
                         "models/mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf"        
14:41:48-230224 ERROR    Failed to load the model.                              
Traceback (most recent call last):
  File "/Users/alimac/textgen/modules/ui_model_menu.py", line 245, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alimac/textgen/modules/models.py", line 87, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alimac/textgen/modules/models.py", line 250, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alimac/textgen/modules/llamacpp_model.py", line 63, in from_pretrained
    Llama = llama_cpp_lib().Llama
            ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'Llama'
```

### System Info

```shell
Hardware Overview:

  Model Name:	Mac mini
  Model Identifier:	Macmini7,1
  Processor Name:	Dual-Core Intel Core i7
  Processor Speed:	3 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  System Firmware Version:	483.0.0.0.0
  OS Loader Version:	540.120.3~37
  SMC Version (system):	2.24f32
  Serial Number (system):	C07SR0Y3G1J2
  Hardware UUID:	D64EE4C5-FDAB-546D-8DA8-AAF69B29CB70
  Provisioning UDID:	D64EE4C5-FDAB-546D-8DA8-,AAF69B29CB70

Screenshot 2024-03-27 at 16.15.12.png
```

**Comment by MateuszUlan** [comment]
I have same issue using different model. 

![obraz](https://github.com/oobabooga/text-generation-webui/assets/125041310/9f5e1ae8-daf4-4ac2-9371-4dbf89e7bc54)

**Comment by crandev** [comment]
Same issue after installing a few moments ago on a new laptop.
There is also another bug report thread about it: https://github.com/oobabooga/text-generation-webui/issues/5765

Happens with all models and model loaders.

**Comment by Melyns** [comment]
Same here.

**Comment by TheKevinWang** [comment]
Same 2021 Macbook M1 max 15.0
