### ISSUE TITLE
Loading Model Error

### ISSUE THREAD

**Issue by MateuszUlan** [oobabooga/text-generation-webui#5765]
### Describe the bug

There is an error when trying load a model 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load model with ExLlamav2_HF Model Loader

### Screenshot

![obraz](https://github.com/oobabooga/text-generation-webui/assets/125041310/25f25e61-ea38-49fe-ae94-a44cb89878f5)

### Logs

```shell
Traceback (most recent call last):

File "/text-generation-webui/modules/ui_model_menu.py", line 245, in load_model_wrapper

shared.model, shared.tokenizer = load_model(selected_model, loader)

                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/text-generation-webui/modules/models.py", line 93, in load_model

output = load_func_map[loader](model_name)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/text-generation-webui/modules/models.py", line 384, in ExLlamav2_HF_loader

from modules.exllamav2_hf import Exllamav2HF

File "/text-generation-webui/modules/exllamav2_hf.py", line 12, in

from exllamav2 import (

ModuleNotFoundError: No module named 'exllamav2'
```

### System Info

```shell
OS: Windows 10 Enterprise 
GPU: Nvidia A6000 AdaGeneration 

Also 

I have use Windows Docker Desktop to containerize text-generation-webui
```

**Comment by Ctmax-ui** [comment]
i am also having the same problem!!, can anyone help us out

**Comment by YakuzaSuske** [comment]
I think it's an installation issue but... i don't know if it will work but... here is my copy of the modules folder. Hope that helps somehow.

[modules.zip](https://github.com/oobabooga/text-generation-webui/files/14811110/modules.zip)

**Comment by Ctmax-ui** [comment]
Sigh what a drag i am trying to learn AI & ML and now this issue!!

**Comment by HoustonDad** [comment]
Same issue here, not sure what's wrong. I tried HEAD zip and the latest release zip, neither seem to work on Ubuntu 22.04


`Downloading the model to models/TheBloke_CapybaraHermes-2.5-Mistral-7B-GPTQ
23:12:07-484568 INFO     Loading "TheBloke_CapybaraHermes-2.5-Mistral-7B-GPTQ"
23:12:07-488447 ERROR    Failed to load the model.
Traceback (most recent call last):
  File "/root/text-generation-webui-snapshot-2024-03-31/modules/ui_model_menu.py", line 245, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/text-generation-webui-snapshot-2024-03-31/modules/models.py", line 86, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/text-generation-webui-snapshot-2024-03-31/modules/models.py", line 349, in ExLlamav2_HF_loader
    from modules.exllamav2_hf import Exllamav2HF
  File "/root/text-generation-webui-snapshot-2024-03-31/modules/exllamav2_hf.py", line 7, in <module>
    from exllamav2 import (
ModuleNotFoundError: No module named 'exllamav2'`

**Comment by Ctmax-ui** [comment]
can any benevolent god help poor soul like us??

**Comment by Ctmax-ui** [comment]
the software is not working on low pc, i have i5 3 gen, 8gb ram, 256ssd, h61 board, and 720gpu should i need some upgrade to run the software??

**Comment by TheKevinWang** [comment]
same problem mac m1 max with qwen2-72b-instruct-q4_k_m.gguf
git clone and ./start-macos.sh

**Comment by Ctmax-ui** [comment]
dose the developer has any solution regarding it, please help poor soul like us.
