### ISSUE TITLE
OpenAI API with Pythagora Extension in VS Code

### ISSUE THREAD

**Issue by rwilkin** [oobabooga/text-generation-webui#5768]
### Describe the bug

When using Obbobooga as a drop-in replacement for OpenAI API with the Pythagora Extension for VS Code I get the following error when Pythagora tries to access the API
```
Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\user\text-generation-webui\installer_files\env\Lib\site-packages\sse_starlette\sse.py", line 247, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "C:\Users\user\text-generation-webui\installer_files\env\Lib\site-packages\sse_starlette\sse.py", line 236, in wrap
    await func()
  File "C:\Users\user\text-generation-webui\installer_files\env\Lib\site-packages\sse_starlette\sse.py", line 191, in listen_for_disconnect
    message = await receive()
              ^^^^^^^^^^^^^^^
  File "C:\Users\user\text-generation-webui\installer_files\env\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 535, in receive
    await self.message_event.wait()
  File "C:\Users\user\text-generation-webui\installer_files\env\Lib\asyncio\locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 1679c76e850

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "C:\Users\user\text-generation-webui\installer_files\env\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "C:\Users\user\text-generation-webui\installer_files\env\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
  |     return await self.app(scope, receive, send)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "C:\Users\user\text-generation-webui\installer_files\env\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "C:\Users\user\text-generation-webui\installer_files\env\Lib\site-packages\starlette\applications.py", line 123, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "C:\Users\user\text-generation-webui\installer_files\env\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
  |     raise exc
  |   File "C:\Users\user\text-generation-webui\installer_files\env\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "C:\Users\user\text-generation-webui\installer_files\env\Lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
  |     await self.app(scope, receive, send)
  |   File "C:\Users\user\text-generation-webui\installer_files\env\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "C:\Users\user\text-generation-webui\installer_files\env\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "C:\Users\user\text-generation-webui\installer_files\env\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "C:\Users\user\text-generation-webui\installer_files\env\Lib\site-packages\starlette\routing.py", line 758, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "C:\Users\user\text-generation-webui\installer_files\env\Lib\site-packages\starlette\routing.py", line 778, in app
  |     await route.handle(scope, receive, send)
  |   File "C:\Users\user\text-generation-webui\installer_files\env\Lib\site-packages\starlette\routing.py", line 299, in handle
  |     await self.app(scope, receive, send)
  |   File "C:\Users\user\text-generation-webui\installer_files\env\Lib\site-packages\starlette\routing.py", line 79, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "C:\Users\user\text-generation-webui\installer_files\env\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "C:\Users\user\text-generation-webui\installer_files\env\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "C:\Users\user\text-generation-webui\installer_files\env\Lib\site-packages\starlette\routing.py", line 77, in app
  |     await response(scope, receive, send)
  |   File "C:\Users\user\text-generation-webui\installer_files\env\Lib\site-packages\sse_starlette\sse.py", line 233, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "C:\Users\user\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "C:\Users\user\text-generation-webui\installer_files\env\Lib\site-packages\sse_starlette\sse.py", line 236, in wrap
    |     await func()
    |   File "C:\Users\user\text-generation-webui\installer_files\env\Lib\site-packages\sse_starlette\sse.py", line 221, in stream_response
    |     async for data in self.body_iterator:
    |   File "C:\Users\user\text-generation-webui\extensions\openai\script.py", line 127, in generator
    |     for resp in response:
    |   File "C:\Users\user\text-generation-webui\extensions\openai\completions.py", line 540, in stream_chat_completions
    |     for resp in chat_completions_common(body, is_legacy, stream=True):
    |   File "C:\Users\user\text-generation-webui\extensions\openai\completions.py", line 315, in chat_completions_common
    |     prompt = generate_chat_prompt(user_input, generate_params)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\user\text-generation-webui\modules\chat.py", line 97, in generate_chat_prompt
    |     user_bio=replace_character_names(state['user_bio'], state['name1'], state['name2']),
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\user\text-generation-webui\modules\chat.py", line 636, in replace_character_names
    |     text = text.replace('{{user}}', name1).replace('{{char}}', name2)
    |            ^^^^^^^^^^^^
    | AttributeError: 'NoneType' object has no attribute 'replace'
    +------------------------------------
```

I really have no idea what any of that means.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Install the Pythagora extension for VS Code.
2. Edit the .env file and set the OPENAI_ENDPOINT=http://192.168.1.13:5000/v1/chat/completions/
    I have also tried:
        - http://192.168.1.13:5000
        - http://localhost:5000/v1/chat/completions
        - http://localhost:5000
        - http://127.0.0.1:5000/v1/chat/completions
        - http://127.0.0.1:5000

3. Launch VS Code and open the Pythagora extension.

### Logs

```shell
Stacktrace is abaove
```

### System Info

```shell
GPU 2 x RTX 4090, Windows 11 Pro
```

**Comment by neffetzz** [comment]
Hi @rwilkin,
i will also start today trying to use "Text generation Web UI" with Pythagora. At the moment I download the model "TheBloke/Mistral-7B-Instruct-v0.2-GGUF".
The creation of an app with OpenAI and gpt4-turbo works, but costs a lot.
I also tried anthropic but sooner or later it ended up in a Error 429 (max. token reached).

Which model did you use?

**Comment by rwilkin** [comment]
Hi @neffetzz,
I tried a few different ones. 
 - cognitivecomputations/dolphin-2.8-gemma-7b
 - cognitivecomputations/dolphin-2.6-mistral-7b-dpo-laser
 - cognitivecomputations/dolphin-2.6-mixtral-8x7b
 - TheBloke/dolphin-2.5-mixtral-8x7b-GGUF
 - TheBloke/Wizard-Vicuna-30B-Uncensored-AWQ
 - TheBloke/CapybaraHermes-2.5-Mistral-7B-AWQ

I tried re-installing both Ooba and Pythagora but that didn't help. I figure I'm probably doing something wrong at this point. I just don't know what.

**Comment by rwilkin** [comment]
I think I have worked it out - it's an issue with not sending the v1/chat/completions the **user_bio** and **name1** parameters. Because they are blank the replace_character_names function in chat.py is attempting to call the replace method on a variable that is None. 

I can replicate it with the following python script
```
import requests

url = "http://127.0.0.1:5000/v1/chat/completions"

payload = {
    "messages": [
        {
            "role": "user",
            "content": "Hello!"
        }
    ],
    "mode": "chat",
    "character": "Assistant",
    "user_bio": "",  # If this is omitted we get an error - a blank string is fine
    "name1": ""  # or if this is omitted the error happens - a blank string is fine
}

print(payload)
response = requests.post(url, json=payload)
print(response.text)
```

**Comment by neffetzz** [comment]
Hi @rwilkin,

If I use your python script I got the following error message:


`requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000196208DA900>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte'))`


On https://github.com/oobabooga/text-generation-webui/wiki/12-%E2%80%90-OpenAI-API there is following info: 


![image](https://github.com/oobabooga/text-generation-webui/assets/165380191/23b3b48a-6a21-4a34-b7b0-622a581ad313)

Do you know how to use this? Or is it necessary at all?

**Comment by neffetzz** [comment]
Can you retrieve the docs from 

http://127.0.0.1:5000/docs

?

**Comment by neffetzz** [comment]
I found one of my errors. Maybe also yours?

**1. The file CMD_FLAFS.txt must be updated:**

![image](https://github.com/oobabooga/text-generation-webui/assets/165380191/03f04739-50dd-443f-902a-992226ca23f5)


like 

![image](https://github.com/oobabooga/text-generation-webui/assets/165380191/cc97f088-5451-4e69-8507-358f54697e33)

**2. Then, starting the Obbobooga and load a model.**

**3. Now, the following python code works:**


```python
import requests

url = "http://127.0.0.1:5000/v1/chat/completions"

headers = {
    "Content-Type": "application/json"
}

history = []

while True:
    user_message = input("> ")
    history.append({"role": "user", "content": user_message})
    data = {
        "mode": "chat",
        "character": "Example",
        "messages": history,
        "user_name": "Steffen",
        "user_bio": ""
    }

    response = requests.post(url, headers=headers, json=data, verify=False)
    assistant_message = response.json()['choices'][0]['message']['content']
    history.append({"role": "assistant", "content": assistant_message})
    print(assistant_message)
```

**Comment by rwilkin** [comment]
Hi @neffetzz ,

Thank you for your help, but I already hadthe --api and --listen parameter enabled and could access the api documentation.

I think the error when Pythagora accesses the api is because there is no user_bio parameter sent when Pythagora accesses the api.
I'm not really sure what to do to fix that though. It seems like a bug on Obba's side.

**Comment by neffetzz** [comment]
Did you get the same error in Pathagora?

![image](https://github.com/oobabooga/text-generation-webui/assets/165380191/e6dce3c2-f879-42a5-987b-f83aa3a7b13d)

**Comment by rwilkin** [comment]
Yeah, that was the error I got in Pythagora. The stacktrace in my first post is the error from the Ooba console.

**Comment by neffetzz** [comment]
Hi @rwilkin ,
I got it running.

I modified the file

.....\text-generation-webui-main\modules\chat.py 

in line 98

![image](https://github.com/oobabooga/text-generation-webui/assets/165380191/c52cc985-16bd-4b94-8e1c-373e3ef0f640)

**Comment by rwilkin** [comment]
Hi @neffetzz,
I made the change you showed me and I can confirm that has fixed it. 
Pythagora is working properly now with Ooba.

Thank you so much for your help.
