### ISSUE TITLE
Loading extensions from interface mode broken

### ISSUE THREAD

**Issue by generic-username0718** [oobabooga/text-generation-webui#578]
### Describe the bug

Loading extensions from interface mode broken

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

start webui without sd_api_pictures extension
check webui sd_api_pictures from "interface mode" tab
extensions section is missing

### Screenshot

![image](https://user-images.githubusercontent.com/126929561/227759018-93bbb85f-9eb3-4feb-a275-7add3cc21769.png)

### Logs

```shell
Closing server running on port: 7860
Loading the extension "character_bias"... Ok.
Loading the extension "gallery"... Ok.
/home/user/anaconda3/envs/textgen2/lib/python3.10/site-packages/gradio/deprecation.py:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
  warnings.warn(value)
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Task exception was never retrieved
future: <Task finished name='4x0ly94pxaw_47' coro=<Queue.process_events() done, defined at /home/user/anaconda3/envs/textgen2/lib/python3.10/site-packages/gradio/queueing.py:329> exception=AssertionError('No event data')>
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/textgen2/lib/python3.10/site-packages/gradio/queueing.py", line 343, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "/home/user/anaconda3/envs/textgen2/lib/python3.10/site-packages/gradio/queueing.py", line 303, in call_prediction
    assert data is not None, "No event data"
AssertionError: No event data
Closing server running on port: 7860
Loading the extension "character_bias"... Ok.
Loading the extension "gallery"... Ok.
Loading the extension "sd_api_pictures"... Ok.
/home/user/anaconda3/envs/textgen2/lib/python3.10/site-packages/gradio/deprecation.py:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
  warnings.warn(value)
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
```

### System Info

```shell
5600x
3090
```

**Comment by Brawlence** [comment]
Dupplicate of https://github.com/oobabooga/text-generation-webui/issues/558 , but you have it described in clear verbose steps

**Comment by oobabooga** [comment]
Solved here https://github.com/oobabooga/text-generation-webui/blob/main/modules/extensions.py
