### ISSUE TITLE
'LlamaGrammar' object has no attribute 'grammar'

### ISSUE THREAD

**Issue by djbritt** [oobabooga/text-generation-webui#5798]
### Describe the bug

I put this grammar into the grammar section under parameters

phrasePattern ::= "*[A-Z\xC0-\xDF]" ("[A-Za-z'.?!,:;-\xE0-\xFD\xC0-\xDF0-9 ]+" "[A-Za-z'.?!,:;-\xE0-\xFD\xC0-\xDF0-9]")* "*"

And it throws this weird error 'LlamaGrammar' object has no attribute 'grammar'

I can run oobabooga fine without grammar defined. I am on a Macbook Pro M1

I just want to have the model NEVER output chinese or russian broken symbols. This is modified from the default roleplay grammar that comes with oobabooga.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Paste in that above code into the grammar section, and try to have your model respond to you.

### Logs

```shell
from_string grammar:
phrasePattern ::= [*] [[] [A] [-] [Z] [<U+00C0>] [-] [<U+00DF>] []] phrasePattern_2 [*] 
phrasePattern_1 ::= [[] [A] [-] [Z] [a] [-] [z] ['] [.] [?] [!] [,] [:] [;] [-] [<U+00E0>] [-] [<U+00FD>] [<U+00C0>] [-] [<U+00DF>] [0] [-] [9] [ ] []] [+] [[] [A] [-] [Z] [a] [-] [z] ['] [.] [?] [!] [,] [:] [;] [-] [<U+00E0>] [-] [<U+00FD>] [<U+00C0>] [-] [<U+00DF>] [0] [-] [9] []] 
phrasePattern_2 ::= phrasePattern_1 phrasePattern_2 | 

Traceback (most recent call last):
  File "/Users/user/github/text-generation-webui/modules/callbacks.py", line 61, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/github/text-generation-webui/modules/llamacpp_model.py", line 142, in generate
    self.load_grammar(state['grammar_string'])
  File "/Users/user/github/text-generation-webui/modules/llamacpp_model.py", line 129, in load_grammar
    self.grammar = llama_cpp_lib().LlamaGrammar.from_string(string)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/github/TavernAI/tavern/lib/python3.11/site-packages/llama_cpp/llama_grammar.py", line 77, in from_string
    return cls(parsed_grammar)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/user/github/TavernAI/tavern/lib/python3.11/site-packages/llama_cpp/llama_grammar.py", line 62, in __init__
    self._start_rule_index = parsed_grammar.symbol_ids.at("root")  # type: int
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/github/TavernAI/tavern/lib/python3.11/site-packages/llama_cpp/llama_grammar.py", line 387, in at
    raise KeyError("The provided key is not found in the map.")
KeyError: 'The provided key is not found in the map.'
Exception ignored in: <function LlamaGrammar.__del__ at 0x173762660>
Traceback (most recent call last):
  File "/Users/user/github/TavernAI/tavern/lib/python3.11/site-packages/llama_cpp/llama_grammar.py", line 49, in __del__
    if self.grammar is not None:
       ^^^^^^^^^^^^
AttributeError: 'LlamaGrammar' object has no attribute 'grammar'
```

### System Info

```shell
Mac OS Monterey
Apple M1 Pro
```

**Comment by djbritt** [comment]
Has anyone seen this error? I just tried another grammar set today and it happened again.

**Comment by djbritt** [comment]
AHA!! You need a root identifier!!

This worked for me, thanks Claude

`root ::= identifier expr

identifier ::= [A-Za-z_][A-Za-z_0-9]*

expr ::= phrasePattern singleSpace quotedText singleSpace phrasePattern singleSpace quotedText singleSpace (phrasePattern singleSpace quotedText singleSpace)?

ws ::= [ \t\r\n]+`
