### ISSUE TITLE
Whisper STT broken after update

### ISSUE THREAD

**Issue by Quidam2k** [oobabooga/text-generation-webui#5805]
### Describe the bug

Tried installing AllTalk, ran into issues, so ran the update script for the webui as well as all the extensions. Now, when I use the Whisper STT extension, the results are significantly less accurate than before the update, but the real problem is not only does it not automatically submit the text after transcription, clicking Generate to do so manually.

I figured just to be safe I'd clone a new install, each with their own env the way they come. Even fresh out of the box the issue persists.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Clone the repo, start it up, enable Whisper STT, Coqui TTS, long responses. Use the Whisper input extension.

### Logs

```shell
No errors thrown, just no submission of recognized speech.
```

### System Info

```shell
Win10, 4090.
```

**Comment by Quidam2k** [comment]
I updated Gradio to 4.25.0 and that fixed the issue with not submitting text, but it then triggers another error, crashing the Whisper extension. If I then run the update process on the extension, it downgrades Gradio back to 4.23. The error when running 4.25 is a permissions error, so I tried running as admin on that one, but it didn't seem to make a difference.

Tried a bit of troubleshooting with GPT to see if I could figure it out on my own. Here are its summaries of the two errors I run into. First, the error using 4.23:

```
Title: RuntimeError: Response content longer than Content-Length in ASGI application

I'm encountering a RuntimeError indicating that the response content is longer than the Content-Length specified. This issue arises when running the application, specifically when handling certain responses. Below is the relevant portion of the traceback:

RuntimeError: Response content longer than Content-Length
  at file "B:\ai_art\text-generation-webui-main\installer_files\env\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 541, in send

This error suggests a discrepancy between the body of the HTTP response and the Content-Length header. It occurs in the context of dynamically generated content, potentially involving streaming responses or variable-sized outputs.
```

Then the one that triggers when I update Gradio to 4.25:

```
After updating Gradio to resolve a previous issue, I've encountered a PermissionError when the application tries to access a directory or file. This error appears during the processing of events in Gradio's queueing.py. The specific error message is as follows:

PermissionError: [Errno 13] Permission denied: 'B:\\ai_art\\text-generation-webui-main'

This occurs in the context of moving files to a cache within Gradio's processing utilities. It suggests that the application lacks the necessary permissions to access the specified path, even though it's attempting a valid operation within its workflow.

Details of the operation leading to the error are captured in the traceback, indicating an issue with file access permissions during postprocessing of API call results. Here is a snippet for reference:


Traceback (most recent call last):
  File "...gradio\queueing.py", line 522, in process_events
    ...
  File "...gradio\processing_utils.py", line 117, in hash_file
    with open(file_path, "rb") as f:
PermissionError: [Errno 13] Permission denied: 'B:\\ai_art\\text-generation-webui-main'

Could you provide insights or suggestions on resolving this PermissionError? The application requires access to this directory for its normal operation post-Gradio update.
```

Thanks for any assistance, and I hope these prove useful if others run into the same issue.

**Comment by Quidam2k** [comment]
So now, when I do a clean install, I get a "no module whisper found" error, so when I launch the venv via the cmd.bat file and "pip install whisper" that goes away and I get this:

Traceback (most recent call last):
  File "B:\ai_art\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\queueing.py", line 522, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "B:\ai_art\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 260, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "B:\ai_art\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1741, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "B:\ai_art\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1296, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "B:\ai_art\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "B:\ai_art\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "B:\ai_art\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "B:\ai_art\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 751, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "B:\ai_art\text-generation-webui-main\extensions\whisper_stt\script.py", line 48, in auto_transcribe
    transcription = do_stt(audio, whipser_model, whipser_language)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "B:\ai_art\text-generation-webui-main\extensions\whisper_stt\script.py", line 36, in do_stt
    transcription = r.recognize_whisper(audio_data, language=whipser_language, model=whipser_model)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "B:\ai_art\text-generation-webui-main\installer_files\env\Lib\site-packages\speech_recognition\__init__.py", line 1479, in recognize_whisper
    import whisper
  File "B:\ai_art\text-generation-webui-main\installer_files\env\Lib\site-packages\whisper.py", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "B:\ai_art\text-generation-webui-main\installer_files\env\Lib\ctypes\__init__.py", line 366, in __init__
    if '/' in name or '\\' in name:
       ^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by Quidam2k** [comment]
I discovered part of my problem with doing a "pip install whisper" which installs the wrong whisper.

But now, even when I do a clean install, then go in and use the update batch file for windows and use it to ensure whisper_stt has got all its requirements set, I'm still getting errors using the Whisper extension. Tried downgrading my Gradio, as it looks like it's supposed to be 4.23, but still no luck.

I guess I'll just wait a while and try again in a few weeks, as apparently I'm the only one this is happening to, and nothing I can do or figure out seems to put a dent in the issues getting the extension to work.

**Comment by kyosho01** [comment]
You are not alone, I've been getting errors since a recent update also.  I get a similar permissions error.  I also tried a fresh install without any success.  I probably cannot help you fix it, but I can say you are not alone.   I also did install AllTalk on my original build, and ever since then (even after a fresh install) my whisper looks different with like some audio graph thing (which wasn't there before).

I probably can't help you fix it, but here is the error I get.  Everything else with my build works great except for whisper:


```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 680, in __call__
    await self.app(scope, receive, send)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\routing.py", line 75, in app
    await response(scope, receive, send)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\responses.py", line 352, in __call__
    await send(
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\_exception_handler.py", line 50, in sender
    await send(message)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\_exception_handler.py", line 50, in sender
    await send(message)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\middleware\errors.py", line 161, in _send
    await send(message)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 511, in send
    output = self.conn.send(event=h11.EndOfMessage())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\h11\_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\h11\_connection.py", line 545, in send_with_data_passthrough
    writer(event, data_list.append)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\h11\_writers.py", line 67, in __call__
    self.send_eom(event.headers, write)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\h11\_writers.py", line 96, in send_eom
    raise LocalProtocolError("Too little data for declared Content-Length")
h11._util.LocalProtocolError: Too little data for declared Content-Length
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 680, in __call__
    await self.app(scope, receive, send)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\routing.py", line 75, in app
    await response(scope, receive, send)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\responses.py", line 352, in __call__
    await send(
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\_exception_handler.py", line 50, in sender
    await send(message)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\_exception_handler.py", line 50, in sender
    await send(message)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\starlette\middleware\errors.py", line 161, in _send
    await send(message)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 511, in send
    output = self.conn.send(event=h11.EndOfMessage())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\h11\_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\h11\_connection.py", line 545, in send_with_data_passthrough
    writer(event, data_list.append)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\h11\_writers.py", line 67, in __call__
    self.send_eom(event.headers, write)
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\h11\_writers.py", line 96, in send_eom
    raise LocalProtocolError("Too little data for declared Content-Length")
h11._util.LocalProtocolError: Too little data for declared Content-Length
Traceback (most recent call last):
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\gradio\queueing.py", line 522, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 260, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1750, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1583, in postprocess_data
    outputs_cached = processing_utils.move_files_to_cache(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\gradio\processing_utils.py", line 319, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\gradio_client\utils.py", line 975, in traverse
    return func(json_obj)
           ^^^^^^^^^^^^^^
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\gradio\processing_utils.py", line 295, in _move_to_cache
    temp_file_path = block.move_resource_to_block_cache(payload.path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 275, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\gradio\processing_utils.py", line 185, in save_file_to_cache
    temp_dir = hash_file(file_path)
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui\installer_files\env\Lib\site-packages\gradio\processing_utils.py", line 117, in hash_file
    with open(file_path, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\text-generation-webui'
```

**Comment by Quidam2k** [comment]
Thanks! I was beginning to wonder if there was something screwy with my setup. At least I know it's not just me. 

I've seen various comments about how recent updates have broken things, and suspect this'll shake out once those issues settle down. I think it might have something to do with the version of Gradio the webui uses, but don't know enough about it to be sure.

Thanks again!

**Comment by Bluesuit101** [comment]
Definitely not alone. I have tried every suggestion I could find to fix the recent 2 releases. I now have experienced probably every possible error. All related to the now broken Whisper_stt.
It started with: 
audioop.error: not a whole number of frames

Tried a few things, then started getting another error related to an "unexpected length" (I did not record this error for some reason).

And now the newest problem after updating to the 2024-04-07 release: 
PermissionError: [Errno 13] Permission denied: 'C:\\text-generation-webui'

**Comment by JackieGLQ** [comment]
My initial error was PermissionError: [Errno 13] Permission denied. Follow the prompts in Fix Whisper STT # 5856 to change audio. change to audio. stop_recording, and there is an error audioop. error: not a whole number of frames. Please find a solution

**Comment by kyosho01** [comment]
I tested the this change as well, and I also received the error about not a whole number of frames.

**Comment by kyosho01** [comment]
This is promising.  I've been testing these changes in the above pull request, and so far its looking good.

**Comment by seruko11** [comment]
This issue still seems to be present rolling back to gradio 4.25 and loading 5929 seemed to fix *most* but not all of the issues related to the whisper/gradio update in April
