### ISSUE TITLE
yield content["output"]["data"][0] KeyError: 'data'

### ISSUE THREAD

**Issue by JamesKnight0001** [oobabooga/text-generation-webui#583]
### Describe the bug

When I tried using the API it reported a error.

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

py api-example-stream.py

### Screenshot

![image](https://user-images.githubusercontent.com/80499782/227779218-10eafcac-fd52-4215-9de0-169ac6329ee4.png)

### Logs

```shell
C:\Users\irene\OneDrive\Desktop\chatbot\text-generation-webui>py api-example-stream.py
Traceback (most recent call last):
  File "C:\Users\irene\OneDrive\Desktop\chatbot\text-generation-webui\api-example-stream.py", line 94, in <module>
    asyncio.run(get_result())
  File "C:\Users\irene\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\irene\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\irene\OneDrive\Desktop\chatbot\text-generation-webui\api-example-stream.py", line 87, in get_result
    async for response in run(prompt):
  File "C:\Users\irene\OneDrive\Desktop\chatbot\text-generation-webui\api-example-stream.py", line 78, in run
    yield content["output"]["data"][0]
KeyError: 'data'
```

### System Info

```shell
Windows 10, GPU : ???
```

**Comment by treesheeptw** [comment]
Where can I change fn_index?

**Comment by mvenezia00** [comment]
Do you know why if i use 9, i get TypeError: string indices must be integers? XD

> Change the value of 'fn_index' from 12 to 11. Bizarrely, it also seems to work with all 'fn_index' values ranging from 9 to 13.

**Comment by jochepr** [comment]
Has this been resolved?

**Comment by jochepr** [comment]
> Where can I change fn_index?

In the `api-example-stream.py`

**Comment by v0xie** [comment]
> Has this been resolved?

Yes, in commit  `ff610b4`. There's also a new global named `GRADIO_FN` that defines the correct fn_index.
