### ISSUE TITLE
'NoneType' object has no attribute 'Llama'

### ISSUE THREAD

**Issue by paul0728** [oobabooga/text-generation-webui#5840]
### Describe the bug

I get this error message when I load all the models.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

load models

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/44644609/b39dcfcc-4a5f-4707-8ffb-2fbcb9572a72)

### Logs

```shell
17:41:36-379649 INFO     Starting Text generation web UI
17:41:36-379649 WARNING  trust_remote_code is enabled. This is dangerous.
17:41:36-379649 INFO     Loading the extension "openai"
17:41:36-473789 INFO     OpenAI-compatible API URL:

                         http://127.0.0.1:5000


Running on local URL:  http://127.0.0.1:7860

17:41:48-253072 INFO     Loading "sakura-13b-lnovel-v0.9-Q4_K_M.gguf"
17:41:48-492914 INFO     llama.cpp weights detected: "models\sakura-13b-lnovel-v0.9-Q4_K_M.gguf"
17:41:48-492914 ERROR    Failed to load the model.
Traceback (most recent call last):
  File "C:\translator\text-generation-webui\modules\ui_model_menu.py", line 245, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\translator\text-generation-webui\modules\models.py", line 87, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\translator\text-generation-webui\modules\models.py", line 261, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\translator\text-generation-webui\modules\llamacpp_model.py", line 63, in from_pretrained
    Llama = llama_cpp_lib().Llama
            ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'Llama'

17:42:06-878495 INFO     Loading "sakura-13b-lnovel-v0.9-Q4_K_M.gguf"
17:42:07-103952 INFO     llama.cpp weights detected: "models\sakura-13b-lnovel-v0.9-Q4_K_M.gguf"
17:42:07-110929 ERROR    Failed to load the model.
Traceback (most recent call last):
  File "C:\translator\text-generation-webui\modules\ui_model_menu.py", line 245, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\translator\text-generation-webui\modules\models.py", line 87, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\translator\text-generation-webui\modules\models.py", line 261, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\translator\text-generation-webui\modules\llamacpp_model.py", line 63, in from_pretrained
    Llama = llama_cpp_lib().Llama
            ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'Llama'
```

### System Info

```shell
OS:WIN11
GPU:3080Ti
```

**Comment by paul0728** [comment]
fixed

**Comment by lucacri** [comment]
HOW?

**Comment by a442509097** [comment]
Thanks. open "Anaconda Powershell Prompt (miniconda3)"
then 
cd I:\miniconda3
conda activate textgen
pip install llama-cpp-python
