### ISSUE TITLE
Newest Gradio prevents Whisper extension from functioning

### ISSUE THREAD

**Issue by RandomInternetPreson** [oobabooga/text-generation-webui#5850]
### Describe the bug

The latest version of gradio does not work with whisper as it is written.  Gradio is now expecting a specific file for the transcribed audio from whisper, but whisper has everything in cached memory; hence there is no file to reference and the documented errors occur.  I have tried reverting back to a previous version of gradio but textgen will not load at all.

Note that a single audio transcription will happen, but immediately there will be errors (see screenshots) and the extension will stop functioning.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Install textgen and try using the whisper extension, it will transcribe audio once and then present the errors in the screenshot and log. 

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/6488699/1f19aebc-1dcb-4390-bad5-584df2a5b126)

### Logs

```shell
Running on local URL:  http://127.0.0.1:7860

Closing server running on port: 7860
15:25:47-351032 INFO     Loading the extension "whisper_stt"                                                          

Running on local URL:  http://127.0.0.1:7860

Traceback (most recent call last):
  File "/home/myself/Desktop/OobApril10/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myself/Desktop/OobApril10/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myself/Desktop/OobApril10/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/blocks.py", line 1795, in process_api
    data = await self.postprocess_data(fn_index, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myself/Desktop/OobApril10/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/blocks.py", line 1625, in postprocess_data
    outputs_cached = await processing_utils.async_move_files_to_cache(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myself/Desktop/OobApril10/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/processing_utils.py", line 410, in async_move_files_to_cache
    return await client_utils.async_traverse(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myself/Desktop/OobApril10/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio_client/utils.py", line 1002, in async_traverse
    return await func(json_obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/myself/Desktop/OobApril10/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/processing_utils.py", line 384, in _move_to_cache
    temp_file_path = await block.async_move_resource_to_block_cache(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myself/Desktop/OobApril10/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/blocks.py", line 275, in async_move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myself/Desktop/OobApril10/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/processing_utils.py", line 188, in save_file_to_cache
    temp_dir = hash_file(file_path)
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/myself/Desktop/OobApril10/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/processing_utils.py", line 120, in hash_file
    with open(file_path, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: '/home/myself/Desktop/OobApril10/text-generation-webui'
```

### System Info

```shell
Ubuntu, msi, 4090
```

**Comment by RandomInternetPreson** [comment]
I don't really know what is happening, but I have tried reverting back to  gradio==4.23.* and now I don't get the error, instead the audio will be transcribed once.  The upon subsequent mic recordings, the audio is not transcribed, but instead the audio player is displayed.

![image](https://github.com/oobabooga/text-generation-webui/assets/6488699/9827d2bf-dda3-4a7b-896c-b76694a243be)
