### ISSUE TITLE
Inference failing using ExLlamav2 version 0.0.18

### ISSUE THREAD

**Issue by ashleykleynhans** [oobabooga/text-generation-webui#5851]
### Describe the bug

Since ExLlamav2 was upgraded to version 0.0.18 in the requirements.txt, inference using it is no longer working and fails with the error in the logs below.  Reverting to version 0.0.17 resolves the issue.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Install latest main branch (current commit is `26d822f64f2a029306b250b69dc58468662a4fc6`)
2. Download `GPTQ` model
3. Use `ExLlamav2_HF` model loader
4. Go to `Chat` tab and ask the AI a question.
5. Observe error, even though the model loaded successfully.

### Logs

```shell
21:35:11-061459 INFO     Loading "TheBloke_dolphin-2.6-mistral-7B-GPTQ"
21:35:13-842112 INFO     LOADER: "ExLlamav2"
21:35:13-843422 INFO     TRUNCATION LENGTH: 32768
21:35:13-844234 INFO     INSTRUCTION TEMPLATE: "Alpaca"
21:35:13-845014 INFO     Loaded the model in 2.78 seconds.
Traceback (most recent call last):
  File "/workspace/text-generation-webui/modules/text_generation.py", line 429, in generate_reply_custom
    for reply in shared.model.generate_with_streaming(question, state):
  File "/workspace/text-generation-webui/modules/exllamav2.py", line 140, in generate_with_streaming
    self.generator.begin_stream(ids, settings, loras=self.loras)
  File "/workspace/venvs/text-generation-webui/lib/python3.10/site-packages/exllamav2/generator/streaming.py", line 198, in begin_stream
    self.begin_stream_ex(input_ids,
  File "/workspace/venvs/text-generation-webui/lib/python3.10/site-packages/exllamav2/generator/streaming.py", line 296, in begin_stream_ex
    self._gen_begin_reuse(input_ids, gen_settings)
  File "/workspace/venvs/text-generation-webui/lib/python3.10/site-packages/exllamav2/generator/streaming.py", line 624, in _gen_begin_reuse
    self._gen_begin(in_tokens, gen_settings)
  File "/workspace/venvs/text-generation-webui/lib/python3.10/site-packages/exllamav2/generator/streaming.py", line 586, in _gen_begin
    self.model.forward(self.sequence_ids[:, :-1],
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/venvs/text-generation-webui/lib/python3.10/site-packages/exllamav2/model.py", line 694, in forward
    r, ls = self._forward(input_ids = input_ids[:, chunk_begin : chunk_end],
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/venvs/text-generation-webui/lib/python3.10/site-packages/exllamav2/model.py", line 776, in _forward
    x = module.forward(x, cache = cache, attn_params = attn_params, past_len = past_len, loras = loras, **kwargs)
  File "/workspace/venvs/text-generation-webui/lib/python3.10/site-packages/exllamav2/attn.py", line 596, in forward
    attn_output = flash_attn_func(q_states, k_states, v_states, causal = True)
  File "/workspace/venvs/text-generation-webui/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 825, in flash_attn_func
    return FlashAttnFunc.apply(
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/workspace/venvs/text-generation-webui/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 507, in forward
    out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = _flash_attn_forward(
  File "/workspace/venvs/text-generation-webui/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 51, in _flash_attn_forward
    out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = flash_attn_cuda.fwd(
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### System Info

* Ubuntu 22.04 LTS
* Nvidia A5000 GPU on Runpod
* CUDA 12.1

**Comment by plutoniumm** [comment]
Yeah I think Exllama by itself is also not working, it seems like some CUDA version issue

**Comment by ashleykleynhans** [comment]
> Yeah I think Exllama by itself is also not working, it seems like some CUDA version issue

I am using CUDA 12.1, ExLlamav2 0.0.17 works fine but ExLlamav2 0.0.18 is not working.

**Comment by p-e-w** [comment]
Same problem with CUDA 12.2 on Ubuntu 22.04.

**Comment by rodti** [comment]
+1

**Comment by ashleykleynhans** [comment]
ExLlamaV2 0.0.19 resolves the issue, I opened a PR to bump ExLLamaV2 to 0.0.19 in the requirements.txt file.
