### ISSUE TITLE
When training, LlamaCppModel.encode() got an unexpected keyword argument 'truncation'

### ISSUE THREAD

**Issue by thelabcat** [oobabooga/text-generation-webui#5854]
### Describe the bug

I cannot train a LLaMa LoRA because of what appears to be a coding mistake.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Load LLaMa 2 13b with the llama.cpp loader. I used 16 or 8 GPU layers, Tensorcores enabled. Other settings were default.
2. Create a raw text training file, save it to training/datasets, and load it in the Training tab.
3. Give the new LoRA a name.
4. Click "Start LoRA Training".
After a few seconds, the WebUI will show (ERROR) and the included traceback is printed to the console.

### Logs

```
15:01:18-914753 WARNING  LoRA training has only currently been validated for    
                         LLaMA, OPT, GPT-J, and GPT-NeoX models. (Found model   
                         type: LlamaCppModel)                                   
15:01:23-916330 INFO     Loading raw text file dataset                          
Traceback (most recent call last):
  File "/home/wilbur/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/queueing.py", line 561, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wilbur/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/route_utils.py", line 260, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wilbur/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/blocks.py", line 1741, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wilbur/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/blocks.py", line 1308, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wilbur/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/utils.py", line 575, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wilbur/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/utils.py", line 568, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wilbur/text-generation-webui/installer_files/env/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wilbur/text-generation-webui/installer_files/env/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/wilbur/text-generation-webui/installer_files/env/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wilbur/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/utils.py", line 551, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/home/wilbur/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/utils.py", line 734, in gen_wrapper
    response = next(iterator)
               ^^^^^^^^^^^^^^
  File "/home/wilbur/text-generation-webui/modules/training.py", line 456, in do_train
    train_data = Dataset.from_list([tokenize(x) for x in text_chunks])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wilbur/text-generation-webui/modules/training.py", line 456, in <listcomp>
    train_data = Dataset.from_list([tokenize(x) for x in text_chunks])
                                    ^^^^^^^^^^^
  File "/home/wilbur/text-generation-webui/modules/training.py", line 374, in tokenize
    input_ids = encode(prompt, True)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/wilbur/text-generation-webui/modules/training.py", line 362, in encode
    result = shared.tokenizer.encode(text, truncation=True, max_length=cutoff_len)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LlamaCppModel.encode() got an unexpected keyword argument 'truncation'
```

### System Info

```
OS: Fedora 39 x86-64
GPU: NVidia RTX 2060 SUPER
```

**Comment by potesd** [comment]
I'm getting the same error.

**Comment by v1-valux** [comment]
Same error here. 

- Loaded leo-hessianai-7B-chat-bilingual-GGUF with llama.cpp.
- 20 GPU layers, tested with Tensorcores enabled/disabled, Other settings default.
- Data Format according to model-page on [huggingface](https://huggingface.co/LeoLM/leo-hessianai-7b-chat-bilingual#prompting--prompt-template)

**Comment by thelabcat** [comment]
@oobabooga

**Comment by oobabooga** [comment]
LoRA training requires a model loaded with the Transformers loader. See the [training docs](https://github.com/oobabooga/text-generation-webui/wiki/05-%E2%80%90-Training-Tab).
