### ISSUE TITLE
error when start_windows.bat run

### ISSUE THREAD

**Issue by YondSun** [oobabooga/text-generation-webui#5882]
### Describe the bug

  Building wheel for grpcio (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [2495 lines of output]
      D:\AI-TextWebUI\installer_files\pip-install-cmgniaxb\grpcio_f31f01eb85c5445784baff304e9f8247\setup.py:42: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        import pkg_resources
      ASM Builds for BoringSSL currently not supported on: win-amd64
      Found cython-generated files...
      running bdist_wheel
      running build
      running build_py
      running build_project_metadata
      creating python_build
      creating python_build\lib.win-amd64-cpython-311
      creating python_build\lib.win-amd64-cpython-311\grpc
      copying src\python\grpcio\grpc\_auth.py -> python_build\lib.win-amd64-cpython-311\grpc
      copying src\python\grpcio\grpc\_channel.py -> python_build\lib.win-amd64-cpython-311\grpc
      copying src\python\grpcio\grpc\_common.py -> python_build\lib.win-amd64-cpython-311\grpc
      copying src\python\grpcio\grpc\_compression.py -> python_build\lib.win-amd64-cpython-311\grpc
      copying src\python\grpcio\grpc\_grpcio_metadata.py -> python_build\lib.win-amd64-cpython-311\grpc
      copying src\python\grpcio\grpc\_interceptor.py -> python_build\lib.win-amd64-cpython-311\grpc
      copying src\python\grpcio\grpc\_plugin_wrapping.py -> python_build\lib.win-amd64-cpython-311\grpc
      copying src\python\grpcio\grpc\_runtime_protos.py -> python_build\lib.win-amd64-cpython-311\grpc
      copying src\python\grpcio\grpc\_server.py -> python_build\lib.win-amd64-cpython-311\grpc
      copying src\python\grpcio\grpc\_simple_stubs.py -> python_build\lib.win-amd64-cpython-311\grpc
      copying src\python\grpcio\grpc\_utilities.py -> python_build\lib.win-amd64-cpython-311\grpc
      copying src\python\grpcio\grpc\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc
      creating python_build\lib.win-amd64-cpython-311\grpc\aio
      copying src\python\grpcio\grpc\aio\_base_call.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
      copying src\python\grpcio\grpc\aio\_base_channel.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
      copying src\python\grpcio\grpc\aio\_base_server.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
      copying src\python\grpcio\grpc\aio\_call.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
      copying src\python\grpcio\grpc\aio\_channel.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
      copying src\python\grpcio\grpc\aio\_interceptor.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
      copying src\python\grpcio\grpc\aio\_metadata.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
      copying src\python\grpcio\grpc\aio\_server.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
      copying src\python\grpcio\grpc\aio\_typing.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
      copying src\python\grpcio\grpc\aio\_utils.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
      copying src\python\grpcio\grpc\aio\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
      creating python_build\lib.win-amd64-cpython-311\grpc\beta
      copying src\python\grpcio\grpc\beta\implementations.py -> python_build\lib.win-amd64-cpython-311\grpc\beta
      copying src\python\grpcio\grpc\beta\interfaces.py -> python_build\lib.win-amd64-cpython-311\grpc\beta
      copying src\python\grpcio\grpc\beta\utilities.py -> python_build\lib.win-amd64-cpython-311\grpc\beta
      copying src\python\grpcio\grpc\beta\_client_adaptations.py -> python_build\lib.win-amd64-cpython-311\grpc\beta
      copying src\python\grpcio\grpc\beta\_metadata.py -> python_build\lib.win-amd64-cpython-311\grpc\beta
      copying src\python\grpcio\grpc\beta\_server_adaptations.py -> python_build\lib.win-amd64-cpython-311\grpc\beta
      copying src\python\grpcio\grpc\beta\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\beta
      creating python_build\lib.win-amd64-cpython-311\grpc\experimental
      copying src\python\grpcio\grpc\experimental\gevent.py -> python_build\lib.win-amd64-cpython-311\grpc\experimental
      copying src\python\grpcio\grpc\experimental\session_cache.py -> python_build\lib.win-amd64-cpython-311\grpc\experimental
      copying src\python\grpcio\grpc\experimental\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\experimental
      creating python_build\lib.win-amd64-cpython-311\grpc\framework
      copying src\python\grpcio\grpc\framework\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\framework
      creating python_build\lib.win-amd64-cpython-311\grpc\_cython
      copying src\python\grpcio\grpc\_cython\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\_cython
      creating python_build\lib.win-amd64-cpython-311\grpc\experimental\aio
      copying src\python\grpcio\grpc\experimental\aio\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\experimental\aio
      creating python_build\lib.win-amd64-cpython-311\grpc\framework\common
      copying src\python\grpcio\grpc\framework\common\cardinality.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\common
      copying src\python\grpcio\grpc\framework\common\style.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\common
      copying src\python\grpcio\grpc\framework\common\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\common
      creating python_build\lib.win-amd64-cpython-311\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\abandonment.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\callable_util.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\future.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\logging_pool.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\stream.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\stream_util.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\foundation
      creating python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces
      copying src\python\grpcio\grpc\framework\interfaces\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces
      creating python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces\base
      copying src\python\grpcio\grpc\framework\interfaces\base\base.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces\base
      copying src\python\grpcio\grpc\framework\interfaces\base\utilities.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces\base
      copying src\python\grpcio\grpc\framework\interfaces\base\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces\base
      creating python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces\face
      copying src\python\grpcio\grpc\framework\interfaces\face\face.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces\face
      copying src\python\grpcio\grpc\framework\interfaces\face\utilities.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces\face
      copying src\python\grpcio\grpc\framework\interfaces\face\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces\face
      creating python_build\lib.win-amd64-cpython-311\grpc\_cython\_cygrpc
      copying src\python\grpcio\grpc\_cython\_cygrpc\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\_cython\_cygrpc
      creating python_build\lib.win-amd64-cpython-311\grpc\_cython\_credentials
      copying src\python\grpcio\grpc\_cython\_credentials\roots.pem -> python_build\lib.win-amd64-cpython-311\grpc\_cython\_credentials
      running build_ext
      Non-fatal exception:Traceback (most recent call last):
        File "D:\AI-TextWebUI\installer_files\pip-install-cmgniaxb\grpcio_f31f01eb85c5445784baff304e9f8247\src\python\grpcio\commands.py", line 231, in compiler_ok_with_extra_std
          cc_test = subprocess.Popen(['cc', '-x', 'c', '-std=c++11', '-'],
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\AI-TextWebUI\installer_files\env\Lib\subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "D:\AI-TextWebUI\installer_files\env\Lib\subprocess.py", line 1538, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 2] 系统找不到指定的文件。

There is a long error message at the end, but it is too much to paste.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

the first time run  start_windows.bat

### Logs

```shell
Building wheel for grpcio (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [2495 lines of output]
      D:\AI-TextWebUI\installer_files\pip-install-cmgniaxb\grpcio_f31f01eb85c5445784baff304e9f8247\setup.py:42: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        import pkg_resources
      ASM Builds for BoringSSL currently not supported on: win-amd64
      Found cython-generated files...
      running bdist_wheel
      running build
      running build_py
      running build_project_metadata
      creating python_build
      creating python_build\lib.win-amd64-cpython-311
      creating python_build\lib.win-amd64-cpython-311\grpc
      copying src\python\grpcio\grpc\_auth.py -> python_build\lib.win-amd64-cpython-311\grpc
      copying src\python\grpcio\grpc\_channel.py -> python_build\lib.win-amd64-cpython-311\grpc
      copying src\python\grpcio\grpc\_common.py -> python_build\lib.win-amd64-cpython-311\grpc
      copying src\python\grpcio\grpc\_compression.py -> python_build\lib.win-amd64-cpython-311\grpc
      copying src\python\grpcio\grpc\_grpcio_metadata.py -> python_build\lib.win-amd64-cpython-311\grpc
      copying src\python\grpcio\grpc\_interceptor.py -> python_build\lib.win-amd64-cpython-311\grpc
      copying src\python\grpcio\grpc\_plugin_wrapping.py -> python_build\lib.win-amd64-cpython-311\grpc
      copying src\python\grpcio\grpc\_runtime_protos.py -> python_build\lib.win-amd64-cpython-311\grpc
      copying src\python\grpcio\grpc\_server.py -> python_build\lib.win-amd64-cpython-311\grpc
      copying src\python\grpcio\grpc\_simple_stubs.py -> python_build\lib.win-amd64-cpython-311\grpc
      copying src\python\grpcio\grpc\_utilities.py -> python_build\lib.win-amd64-cpython-311\grpc
      copying src\python\grpcio\grpc\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc
      creating python_build\lib.win-amd64-cpython-311\grpc\aio
      copying src\python\grpcio\grpc\aio\_base_call.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
      copying src\python\grpcio\grpc\aio\_base_channel.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
      copying src\python\grpcio\grpc\aio\_base_server.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
      copying src\python\grpcio\grpc\aio\_call.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
      copying src\python\grpcio\grpc\aio\_channel.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
      copying src\python\grpcio\grpc\aio\_interceptor.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
      copying src\python\grpcio\grpc\aio\_metadata.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
      copying src\python\grpcio\grpc\aio\_server.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
      copying src\python\grpcio\grpc\aio\_typing.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
      copying src\python\grpcio\grpc\aio\_utils.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
      copying src\python\grpcio\grpc\aio\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
      creating python_build\lib.win-amd64-cpython-311\grpc\beta
      copying src\python\grpcio\grpc\beta\implementations.py -> python_build\lib.win-amd64-cpython-311\grpc\beta
      copying src\python\grpcio\grpc\beta\interfaces.py -> python_build\lib.win-amd64-cpython-311\grpc\beta
      copying src\python\grpcio\grpc\beta\utilities.py -> python_build\lib.win-amd64-cpython-311\grpc\beta
      copying src\python\grpcio\grpc\beta\_client_adaptations.py -> python_build\lib.win-amd64-cpython-311\grpc\beta
      copying src\python\grpcio\grpc\beta\_metadata.py -> python_build\lib.win-amd64-cpython-311\grpc\beta
      copying src\python\grpcio\grpc\beta\_server_adaptations.py -> python_build\lib.win-amd64-cpython-311\grpc\beta
      copying src\python\grpcio\grpc\beta\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\beta
      creating python_build\lib.win-amd64-cpython-311\grpc\experimental
      copying src\python\grpcio\grpc\experimental\gevent.py -> python_build\lib.win-amd64-cpython-311\grpc\experimental
      copying src\python\grpcio\grpc\experimental\session_cache.py -> python_build\lib.win-amd64-cpython-311\grpc\experimental
      copying src\python\grpcio\grpc\experimental\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\experimental
      creating python_build\lib.win-amd64-cpython-311\grpc\framework
      copying src\python\grpcio\grpc\framework\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\framework
      creating python_build\lib.win-amd64-cpython-311\grpc\_cython
      copying src\python\grpcio\grpc\_cython\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\_cython
      creating python_build\lib.win-amd64-cpython-311\grpc\experimental\aio
      copying src\python\grpcio\grpc\experimental\aio\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\experimental\aio
      creating python_build\lib.win-amd64-cpython-311\grpc\framework\common
      copying src\python\grpcio\grpc\framework\common\cardinality.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\common
      copying src\python\grpcio\grpc\framework\common\style.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\common
      copying src\python\grpcio\grpc\framework\common\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\common
      creating python_build\lib.win-amd64-cpython-311\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\abandonment.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\callable_util.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\future.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\logging_pool.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\stream.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\stream_util.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\foundation
      creating python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces
      copying src\python\grpcio\grpc\framework\interfaces\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces
      creating python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces\base
      copying src\python\grpcio\grpc\framework\interfaces\base\base.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces\base
      copying src\python\grpcio\grpc\framework\interfaces\base\utilities.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces\base
      copying src\python\grpcio\grpc\framework\interfaces\base\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces\base
      creating python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces\face
      copying src\python\grpcio\grpc\framework\interfaces\face\face.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces\face
      copying src\python\grpcio\grpc\framework\interfaces\face\utilities.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces\face
      copying src\python\grpcio\grpc\framework\interfaces\face\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces\face
      creating python_build\lib.win-amd64-cpython-311\grpc\_cython\_cygrpc
      copying src\python\grpcio\grpc\_cython\_cygrpc\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\_cython\_cygrpc
      creating python_build\lib.win-amd64-cpython-311\grpc\_cython\_credentials
      copying src\python\grpcio\grpc\_cython\_credentials\roots.pem -> python_build\lib.win-amd64-cpython-311\grpc\_cython\_credentials
      running build_ext
      Non-fatal exception:Traceback (most recent call last):
        File "D:\AI-TextWebUI\installer_files\pip-install-cmgniaxb\grpcio_f31f01eb85c5445784baff304e9f8247\src\python\grpcio\commands.py", line 231, in compiler_ok_with_extra_std
          cc_test = subprocess.Popen(['cc', '-x', 'c', '-std=c++11', '-'],
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\AI-TextWebUI\installer_files\env\Lib\subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "D:\AI-TextWebUI\installer_files\env\Lib\subprocess.py", line 1538, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 2] 系统找不到指定的文件。

There is a long error message at the end, but it is too much to paste.
```

### System Info

```shell
win10,RTX4090
```

**Comment by sandyis** [comment]
@YondSun please check you C++ or equivalent compiler, may need upgrade 
what is the python version ? basically it was trying to build the Wheels package but could not

**Comment by louanfontenele** [comment]
Same with me.

**Comment by louanfontenele** [comment]
Anyway to fix it @oobabooga ?
