### ISSUE TITLE
Auto-Split Error for GPTQ on Nvidia

### ISSUE THREAD

**Issue by Zaxl445** [oobabooga/text-generation-webui#5894]
### Describe the bug

When loading any GPTQ model and running it off of auto split, (ExLamav2_HF and any other loader) the first error of "'ook' is not recognized as an internal or external command," occurs. This leads to a program crash. After restarting the program and trying to load the GPTQ again the logs attached occur. Then the program proceeds to crash, when attempting to reload any model type. 

Note: This does NOT occur when using single GPU. I have disabled both the 4070S and 3090. When running on either independently it works perfect. Only occurs with auto split enabled.
I have also done full reinstalls and tested it on different drives. As well as restarting my computer for each time. I have also tested different models.

This WORKED yesterday which is why I am confused with it not working now. I have also done a full driver reinstall and rolled back textgen to a march snapshot.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Install Text gen web ui
Install for Nvidia Gpu
Attempt to load model with autosplit

### Logs

```shell
Traceback (most recent call last):

File "C:\Users\ZachA\text-generation-webui-snapshot-2024-03-17\modules\ui_model_menu.py", line 248, in load_model_wrapper


shared.model, shared.tokenizer = load_model(selected_model, loader)

                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ZachA\text-generation-webui-snapshot-2024-03-17\modules\models.py", line 94, in load_model


output = load_func_map[loader](model_name)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ZachA\text-generation-webui-snapshot-2024-03-17\modules\models.py", line 374, in ExLlamav2_HF_loader


return Exllamav2HF.from_pretrained(model_name)

       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ZachA\text-generation-webui-snapshot-2024-03-17\modules\exllamav2_hf.py", line 181, in from_pretrained


return Exllamav2HF(config)

       ^^^^^^^^^^^^^^^^^^^
File "C:\Users\ZachA\text-generation-webui-snapshot-2024-03-17\modules\exllamav2_hf.py", line 60, in init


self.ex_model.load_autosplit(self.ex_cache)
File "C:\Users\ZachA\text-generation-webui-snapshot-2024-03-17\installer_files\env\Lib\site-packages\exllamav2\model.py", line 349, in load_autosplit


for item in f: x = item
File "C:\Users\ZachA\text-generation-webui-snapshot-2024-03-17\installer_files\env\Lib\site-packages\exllamav2\model.py", line 476, in load_autosplit_gen


raise RuntimeError("Insufficient VRAM for model and cache")
RuntimeError: Insufficient VRAM for model and cache
```

### System Info

```shell
System Spec:
i7-11700kf
3090
4070 Super
48Gb Ram
Running off NVME
```

**Comment by Zaxl445** [comment]
Going to attempt to troubleshoot more.

**Comment by Ph0rk0z** [comment]
What model are you running because it says:


```
raise RuntimeError("Insufficient VRAM for model and cache")
RuntimeError: Insufficient VRAM for model and cache
```

**Comment by Zaxl445** [comment]
This occurs for me on any Mixtral-Instruct-8x7b GPTQ Model. Models tested currently fill 11.7Gb on my 4070S, but only 9.8gb on my 3090. When it hits that 9.8gb limit, it proceeds to fail. Which is why I tested the gpu's independently. Further note this is only occurring for me on Mixtral models.

**Comment by Ph0rk0z** [comment]
Might be stuck splitting manually?

**Comment by Zaxl445** [comment]
How would I do that? And what's weird to me is that it did work, but is now failing.

**Comment by Zaxl445** [comment]
I am 95% sure it has to be an issue with some level of memory fragmentation when it hits the second gpu. I tested it with a 55b gptq out of curiosity that isn't mixtral. The same thing happened. I am going to go test it on kobold to see if it is a personal issue or a local one to textgen.

**Comment by Zaxl445** [comment]
Development: I specifically loaded the 04-14 snapshot, and it worked off of that snapshot. However it does not work with main.

**Comment by Ph0rk0z** [comment]
It has been sucking for autosplit in my experience lately too. A lot of models have to be done manually. I think there is a parameter to set reserved memory on each GPU but it's not exposed in textgen.
