### ISSUE TITLE
No reply is generated by the model

### ISSUE THREAD

**Issue by Terrorrai** [oobabooga/text-generation-webui#5913]
### Describe the bug

After any model loads, i get no reply from the system, with this error message.
I tried re-installing, but that did not do the trick

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Just prompting any response

### Logs

```shell
Traceback (most recent call last):
  File "E:\AI\Ooga\text-generation-webui\modules\callbacks.py", line 61, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\Ooga\text-generation-webui\modules\text_generation.py", line 382, in generate_with_callback
    shared.model.generate(**kwargs)
  File "E:\AI\Ooga\text-generation-webui\installer_files\env\Lib\site-packages\awq\models\base.py", line 110, in generate
    return self.model.generate(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\Ooga\text-generation-webui\installer_files\env\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\Ooga\text-generation-webui\installer_files\env\Lib\site-packages\transformers\generation\utils.py", line 1622, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "E:\AI\Ooga\text-generation-webui\installer_files\env\Lib\site-packages\transformers\generation\utils.py", line 2788, in _sample
    model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\Ooga\text-generation-webui\installer_files\env\Lib\site-packages\transformers\models\llama\modeling_llama.py", line 1262, in prepare_inputs_for_generation
    past_key_values = getattr(getattr(self.model.layers[0], "self_attn", {}), "past_key_value", None)
                                      ^^^^^^^^^^^^^^^^^
  File "E:\AI\Ooga\text-generation-webui\installer_files\env\Lib\site-packages\torch\nn\modules\module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'LlamaLikeModel' object has no attribute 'layers'
Output generated in 1.30 seconds (0.00 tokens/s, 0 tokens, context 76, seed 1355285154)
```

### System Info

```shell
Nvidia 4070TI
Intel I7 13700KF
Windows 11
Kingston Fury 64GB 6000
```

**Comment by SSELDOG** [comment]
Same problem, no response, just this error:

![Screenshot 2024-04-28 205031](https://github.com/oobabooga/text-generation-webui/assets/10354933/9dbd6582-09d0-4e5f-b90d-659de357edf1)

System Info:
Nvidia 4070TI
Intel I7 4790K
Windows 10
32 GB

**Comment by wsteven-son** [comment]
Getting same error with AWQ, gguf inference working properly
