### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by VladTheDestructor** [oobabooga/text-generation-webui#5925]
### Describe the bug

opened start_windows.bat , few minutes later downloading stopped with error. same thing happens when i open update wizard with the same error. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

just start installation

### Logs

```shell
//this error appears while installing
ERROR: Wheel 'rouge-score' located at C:\users\владик\appdata\local\pip\cache\wheels\1e\19\43\8a442dc83660ca25e163e1bd1f89919284ab0d0c1475475148\rouge_score-0.1.2-py3-none-any.whl is invalid. 


//getting this error after opening start_windows once again after failed installation
Traceback (most recent call last):
  File "E:\_AI\text-generation-webui\server.py", line 4, in <module>
    from modules import shared
  File "E:\_AI\text-generation-webui\modules\shared.py", line 8, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

### System Info

```shell
nvidia gforce rtx3090 laptop gpu, windows 10
```

**Comment by geeky-devil** [comment]
Which environment are you  using?
the conda env which gets installed or any other?

**Comment by RedBigz** [comment]
Oh hey! Just had the exact same issue at the exact same time, somehow.
rm -rf your files, clone a new repo, then restart your pc/open a new terminal, then run ./start_<windows/linux>.<bat/sh>.
That fixed my problem on Ubuntu 22.04.

**Comment by TechWarriorinProcess** [comment]
> Oh hey! Just had the exact same issue at the exact same time, somehow. rm -rf your files, clone a new repo, then restart your pc/open a new terminal, then run ./start_<windows/linux>.<bat/sh>. That fixed my problem on Ubuntu 22.04.

Still ends in the same error

**Comment by TechWarriorinProcess** [comment]
> > > Oh hey! Just had the exact same issue at the exact same time, somehow. rm -rf your files, clone a new repo, then restart your pc/open a new terminal, then run ./start_<windows/linux>.<bat/sh>. That fixed my problem on Ubuntu 22.04.
> > 
> > 
> > Still ends in the same error
> > when I run the installation script start_linux.sh this error occurs
> > ` Ignoring gptq-for-llama: markers 'platform_system == "Linux" and platform_machine == "x86_64" and python_version == "3.11"' don't match your environment Ignoring gptq-for-llama: markers 'platform_system == "Linux" and platform_machine == "x86_64" and python_version == "3.10"' don't match your environment Collecting accelerate==0.27.* (from -r temp_requirements.txt (line 1)) Using cached accelerate-0.27.2-py3-none-any.whl.metadata (18 kB) Collecting aqlm==1.1.3 (from aqlm[cpu,gpu]==1.1.3->-r temp_requirements.txt (line 2)) Using cached aqlm-1.1.3-py3-none-any.whl.metadata (1.7 kB) ERROR: Could not find a version that satisfies the requirement bitsandbytes==0.43.* (from versions: 0.31.8, 0.32.0, 0.32.1, 0.32.2, 0.32.3, 0.33.0, 0.33.1, 0.34.0, 0.35.0, 0.35.1, 0.35.2, 0.35.3, 0.35.4, 0.36.0, 0.36.0.post1, 0.36.0.post2, 0.37.0, 0.37.1, 0.37.2, 0.38.0, 0.38.0.post1, 0.38.0.post2, 0.38.1, 0.39.0, 0.39.1, 0.40.0, 0.40.0.post1, 0.40.0.post2, 0.40.0.post3, 0.40.0.post4, 0.40.1, 0.40.1.post1, 0.40.2, 0.41.0, 0.41.1, 0.41.2, 0.41.2.post1, 0.41.2.post2, 0.41.3, 0.41.3.post1, 0.41.3.post2, 0.42.0) ERROR: No matching distribution found for bitsandbytes==0.43.* Command '. "/home/ubuntu/text-generation-webui/installer_files/conda/etc/profile.d/conda.sh" && conda activate "/home/ubuntu/text-generation-webui/installer_files/env" && python -m pip install -r temp_requirements.txt --upgrade' failed with exit status code '1'.
> > Exiting now. Try running the start/update script again.`
> > (I didn't try the update script yet, if it's a different one from the start_linux.sh file)
> > when I want to start the server.py file (like it normaly would after the installation I think) this error happens
> > ubuntu@ubuntu-vps:~/text-generation-webui$ . server.py Command 'import' not found, but can be installed with: sudo apt install graphicsmagick-imagemagick-compat # version 1.4+really1.3.38-1ubuntu0.1, or sudo apt install imagemagick-6.q16 # version 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3 sudo apt install imagemagick-6.q16hdri # version 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3 Command 'import' not found, but can be installed with: sudo apt install graphicsmagick-imagemagick-compat # version 1.4+really1.3.38-1ubuntu0.1, or sudo apt install imagemagick-6.q16 # version 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3 sudo apt install imagemagick-6.q16hdri # version 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3 Command 'from' not found, but can be installed with: sudo apt install mailutils Command 'import' not found, but can be installed with: sudo apt install graphicsmagick-imagemagick-compat # version 1.4+really1.3.38-1ubuntu0.1, or sudo apt install imagemagick-6.q16 # version 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3 sudo apt install imagemagick-6.q16hdri # version 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3 Command 'import' not found, but can be installed with: sudo apt install graphicsmagick-imagemagick-compat # version 1.4+really1.3.38-1ubuntu0.1, or sudo apt install imagemagick-6.q16 # version 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3 sudo apt install imagemagick-6.q16hdri # version 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3 Command 'from' not found, but can be installed with: sudo apt install mailutils Command 'from' not found, but can be installed with: sudo apt install mailutils os.environ[GRADIO_ANALYTICS_ENABLED]: command not found os.environ[BITSANDBYTES_NOWELCOME]: command not found -bash: server.py: line 14: syntax error near unexpected token `'ignore',' -bash: server.py: line 14: `warnings.filterwarnings('ignore', category=UserWarning, message='TypedStorage is `deprecated')'
> 
> The requirements are not properly mentioned i guess, cause it say it can't find any matching distribution for bitsandbytes( check the error log and download one those).
> 
> Also how are you running the server.py file again?

Okey I will try out and download the bitsandbytes manually 


server.py I am just running like this

ubuntu@ubuntu-vps:~/text-generation-webui$ . server.py

**Comment by geeky-devil** [comment]
> > > > Oh hey! Just had the exact same issue at the exact same time, somehow. rm -rf your files, clone a new repo, then restart your pc/open a new terminal, then run ./start_<windows/linux>.<bat/sh>. That fixed my problem on Ubuntu 22.04.
> > > 
> > > 
> > > Still ends in the same error
> > > when I run the installation script start_linux.sh this error occurs
> > > ` Ignoring gptq-for-llama: markers 'platform_system == "Linux" and platform_machine == "x86_64" and python_version == "3.11"' don't match your environment Ignoring gptq-for-llama: markers 'platform_system == "Linux" and platform_machine == "x86_64" and python_version == "3.10"' don't match your environment Collecting accelerate==0.27.* (from -r temp_requirements.txt (line 1)) Using cached accelerate-0.27.2-py3-none-any.whl.metadata (18 kB) Collecting aqlm==1.1.3 (from aqlm[cpu,gpu]==1.1.3->-r temp_requirements.txt (line 2)) Using cached aqlm-1.1.3-py3-none-any.whl.metadata (1.7 kB) ERROR: Could not find a version that satisfies the requirement bitsandbytes==0.43.* (from versions: 0.31.8, 0.32.0, 0.32.1, 0.32.2, 0.32.3, 0.33.0, 0.33.1, 0.34.0, 0.35.0, 0.35.1, 0.35.2, 0.35.3, 0.35.4, 0.36.0, 0.36.0.post1, 0.36.0.post2, 0.37.0, 0.37.1, 0.37.2, 0.38.0, 0.38.0.post1, 0.38.0.post2, 0.38.1, 0.39.0, 0.39.1, 0.40.0, 0.40.0.post1, 0.40.0.post2, 0.40.0.post3, 0.40.0.post4, 0.40.1, 0.40.1.post1, 0.40.2, 0.41.0, 0.41.1, 0.41.2, 0.41.2.post1, 0.41.2.post2, 0.41.3, 0.41.3.post1, 0.41.3.post2, 0.42.0) ERROR: No matching distribution found for bitsandbytes==0.43.* Command '. "/home/ubuntu/text-generation-webui/installer_files/conda/etc/profile.d/conda.sh" && conda activate "/home/ubuntu/text-generation-webui/installer_files/env" && python -m pip install -r temp_requirements.txt --upgrade' failed with exit status code '1'. Exiting now. Try running the start/update script again.`
> > > (I didn't try the update script yet, if it's a different one from the start_linux.sh file)
> > > when I want to start the server.py file (like it normaly would after the installation I think) this error happens
> > > ubuntu@ubuntu-vps:~/text-generation-webui$ . server.py Command 'import' not found, but can be installed with: sudo apt install graphicsmagick-imagemagick-compat # version 1.4+really1.3.38-1ubuntu0.1, or sudo apt install imagemagick-6.q16 # version 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3 sudo apt install imagemagick-6.q16hdri # version 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3 Command 'import' not found, but can be installed with: sudo apt install graphicsmagick-imagemagick-compat # version 1.4+really1.3.38-1ubuntu0.1, or sudo apt install imagemagick-6.q16 # version 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3 sudo apt install imagemagick-6.q16hdri # version 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3 Command 'from' not found, but can be installed with: sudo apt install mailutils Command 'import' not found, but can be installed with: sudo apt install graphicsmagick-imagemagick-compat # version 1.4+really1.3.38-1ubuntu0.1, or sudo apt install imagemagick-6.q16 # version 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3 sudo apt install imagemagick-6.q16hdri # version 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3 Command 'import' not found, but can be installed with: sudo apt install graphicsmagick-imagemagick-compat # version 1.4+really1.3.38-1ubuntu0.1, or sudo apt install imagemagick-6.q16 # version 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3 sudo apt install imagemagick-6.q16hdri # version 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3 Command 'from' not found, but can be installed with: sudo apt install mailutils Command 'from' not found, but can be installed with: sudo apt install mailutils os.environ[GRADIO_ANALYTICS_ENABLED]: command not found os.environ[BITSANDBYTES_NOWELCOME]: command not found -bash: server.py: line 14: syntax error near unexpected token `'ignore',' -bash: server.py: line 14: `warnings.filterwarnings('ignore', category=UserWarning, message='TypedStorage is `deprecated')'
> > 
> > 
> > The requirements are not properly mentioned i guess, cause it say it can't find any matching distribution for bitsandbytes( check the error log and download one those).
> > Also how are you running the server.py file again?
> 
> Okey I will try out and download the bitsandbytes manually
> 
> server.py I am just running like this
> 
> ubuntu@ubuntu-vps:~/text-generation-webui$ . server.py
> 
> ---------------EDIT------------------------
> 
> I wanted to install the bitsandbytes package, but now I can't use conda anymore and it seems the installing file didn't install conda.
> 
> ----------------EDIT---------------------------
> 
> Okey fuck this so that's what I have done:
> 
> * Cloned a third time (because conda still was not working, even if I restarted the ssh connection)
> * searched for the conda.sh file and runned it so conda was working again
> * tried to rename the env (because there is no fucking env name just the path, which annoys me) couldn't solve it (it's easy I know I just wasted time and also explore condas file)
> * then I tried to install the requirement.txt with conda (didn't work, also did comment all links)
> * so then pip is the right thing and not conda (same error with the bitsandbytes package)
> * somewhere between i updated the whole conda env (maybe I should not have done that right?)
> * I installed bitsandbytes manuel (ah yes I couldn't do it first because conda was not updated)
> * uncommented it from the requirement.txt
> * let pip do it thing
> * next package error:
> 
> ERROR: Ignored the following versions that require a different python version: 0.52.0 Requires-Python >=3.6,<3.9; 0.52.0rc3 Requires-Python >=3.6,<3.9; 0.53.0 Requires-Python >=3.6,<3.10; 0.53.0rc1.post1 Requires-Python >=3.6,<3.10; 0.53.0rc2 Requires-Python >=3.6,<3.10; 0.53.0rc3 Requires-Python >=3.6,<3.10; 0.53.1 Requires-Python >=3.6,<3.10; 0.54.0 Requires-Python >=3.7,<3.10; 0.54.0rc2 Requires-Python >=3.7,<3.10; 0.54.0rc3 Requires-Python >=3.7,<3.10; 0.54.1 Requires-Python >=3.7,<3.10; 0.55.0 Requires-Python >=3.7,<3.11; 0.55.0rc1 Requires-Python >=3.7,<3.11; 0.55.1 Requires-Python >=3.7,<3.11; 0.55.2 Requires-Python >=3.7,<3.11 ERROR: Could not find a version that satisfies the requirement autoawq==0.2.3 (from versions: none) ERROR: No matching distribution found for autoawq==0.2.3

As i suspected , you are running the script the wrong way
its a python file so u need to run it with python like this
```python server.py```
i actually missed the bash log there
![image](https://github.com/oobabooga/text-generation-webui/assets/73377915/df507e8b-5010-46dd-b6e2-50477f668284)
you can see that bash says unexpected token server.py
bash executes files with .sh format as far as i know

also for the later part ,there seems to be issue with the requirements.txt.

just remove everything (conda and stuff), install python 3.10 , 
install the requirements.txt 
```
pip install -r requirements.txt
``` 
then launch the server.py file
```
python server.py
```

for the autoawq , i dont know why it threw and error.

**Comment by sdfdger** [comment]
+1
