### ISSUE TITLE
PHI-3 128K GGUF - Model Fails to Load

### ISSUE THREAD

**Issue by dmsweetser** [oobabooga/text-generation-webui#5930]
### Describe the bug

I'm attempting to load https://huggingface.co/QuantFactory/Phi-3-mini-128k-instruct-GGUF with default options and I receive this error:

Traceback (most recent call last):

File "C:\Files\text-generation-web-ui\modules\ui_model_menu.py", line 247, in load_model_wrapper

shared.model, shared.tokenizer = load_model(selected_model, loader)

                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Files\text-generation-web-ui\modules\models.py", line 94, in load_model

output = load_func_map[loader](model_name)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Files\text-generation-web-ui\modules\models.py", line 271, in llamacpp_loader

model, tokenizer = LlamaCppModel.from_pretrained(model_file)

                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Files\text-generation-web-ui\modules\llamacpp_model.py", line 77, in from_pretrained

result.model = Llama(**params)

               ^^^^^^^^^^^^^^^
File "C:\Files\text-generation-web-ui\installer_files\env\Lib\site-packages\llama_cpp\llama.py", line 323, in init

self._model = _LlamaModel(

              ^^^^^^^^^^^^
File "C:\Files\text-generation-web-ui\installer_files\env\Lib\site-packages\llama_cpp_internals.py", line 55, in init

raise ValueError(f"Failed to load model from file: {path_model}")
ValueError: Failed to load model from file: models\Phi-3-mini-128k-instruct.Q4_K_M.gguf

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Download and load the model:

https://huggingface.co/QuantFactory/Phi-3-mini-128k-instruct-GGUF/resolve/main/Phi-3-mini-128k-instruct.Q4_K_M.gguf?download=true

### Logs

```shell
Traceback (most recent call last):

File "C:\Files\text-generation-web-ui\modules\ui_model_menu.py", line 247, in load_model_wrapper


shared.model, shared.tokenizer = load_model(selected_model, loader)

                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Files\text-generation-web-ui\modules\models.py", line 94, in load_model


output = load_func_map[loader](model_name)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Files\text-generation-web-ui\modules\models.py", line 271, in llamacpp_loader


model, tokenizer = LlamaCppModel.from_pretrained(model_file)

                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Files\text-generation-web-ui\modules\llamacpp_model.py", line 77, in from_pretrained


result.model = Llama(**params)

               ^^^^^^^^^^^^^^^
File "C:\Files\text-generation-web-ui\installer_files\env\Lib\site-packages\llama_cpp\llama.py", line 323, in init


self._model = _LlamaModel(

              ^^^^^^^^^^^^
File "C:\Files\text-generation-web-ui\installer_files\env\Lib\site-packages\llama_cpp_internals.py", line 55, in init


raise ValueError(f"Failed to load model from file: {path_model}")
ValueError: Failed to load model from file: models\Phi-3-mini-128k-instruct.Q4_K_M.gguf
```

### System Info

```shell
Windows 10
NVIDIA GTX 1660 Super
```

**Comment by LVPS24** [comment]
Same error with https://huggingface.co/pjh64/Phi-3-mini-128K-Instruct.gguf

**Comment by Malrama** [comment]
That's because the .gguf files do seem to be corrupted or bad. The gguf files from here work flawless https://huggingface.co/PrunaAI/Phi-3-mini-128k-instruct-GGUF-Imatrix-smashed

**Comment by dmsweetser** [comment]
It looks like they are still working on the 128k variant in llama.cpp:

https://github.com/ggerganov/llama.cpp/issues/6849

**Comment by dmsweetser** [comment]
One other note - I am seeing that I can load https://huggingface.co/PrunaAI/Phi-3-mini-128k-instruct-GGUF-Imatrix-smashed, but there are irregularities when I use a larger prompt. I suspect this is related to the llama.cpp remaining work.

**Comment by dmsweetser** [comment]
I found this issue, where mistral.rs has implemented LongRoPE in Rust:

https://github.com/huggingface/candle/issues/2123

Here's the source:

https://github.com/EricLBuehler/mistral.rs/blob/6334b30fdf6447fa787dcbedb032fb825c22ae1f/mistralrs-core/src/models/layers.rs#L84

I had ChatGPT (aka ClosedAI) convert this for me because I don't know Rust OR C++:

#include <vector>
#include <cmath>
#include <tensor.h> // Assuming the existence of a "Tensor" class for tensor operations

enum ScaledRopeType { Su, Yarn }; // Define ScaledRopeType enum

struct ScaledRopeParams {
    std::vector<float> short_factor;
    std::vector<float> long_factor;
    ScaledRopeType scaling_type;
};

struct PhiRotaryEmbedding {
    Tensor short_cos;
    Tensor short_sin;
    std::optional<Tensor> long_cos;
    std::optional<Tensor> long_sin;
    int original_max_position_embeddings;

    static PhiRotaryEmbedding new(DType dtype, const Config& cfg, const Device& dev) {
        std::optional<ScaledRopeParams> scaled_params;
        // Initialize scaled_params if cfg.rope_scaling has value
        if (cfg.rope_scaling) {
            scaled_params = ScaledRopeParams{
                cfg.rope_scaling->short_factor,
                cfg.rope_scaling->long_factor,
                cfg.rope_scaling->scaling_type
            };
        }
        int max_seq_len = cfg.max_position_embeddings;
        int dim = cfg.head_dim();

        if (scaled_params) {
            // Calculate scale
            double scale = static_cast<double>(cfg.max_position_embeddings) / static_cast<double>(cfg.original_max_position_embeddings);
            double scaling_factor = (scale <= 1.0) ? 1.0 : 
                (scaled_params->scaling_type == ScaledRopeType::Su) ?
                    (1.0 + std::log(scale) / std::log(static_cast<double>(cfg.original_max_position_embeddings))) : 
                    (0.1 * std::log(scale) + 1.0);

            // Calculate inv freqs for short, long
            std::vector<float> inv_freq_long(dim / 2);
            for (int k = 0, i = 0; k < dim; k += 2, ++i) {
                inv_freq_long[i] = 1.0f / (scaled_params->long_factor[i] * std::pow(cfg.rope_theta, static_cast<float>(i) / static_cast<float>(dim)));
            }
            std::vector<float> inv_freq_short(dim / 2);
            for (int k = 0, i = 0; k < dim; k += 2, ++i) {
                inv_freq_short[i] = 1.0f / (scaled_params->short_factor[i] * std::pow(cfg.rope_theta, static_cast<float>(i) / static_cast<float>(dim)));
            }
            int inv_freq_len = inv_freq_long.size();

            Tensor t = Tensor::arange(0u32, max_seq_len, dev).to_dtype(dtype).reshape({ max_seq_len, 1 });

            // Calculate sin,cos for long
            Tensor inv_freq_long_tensor = Tensor::from_vec(inv_freq_long, { 1, inv_freq_len }, dev).to_dtype(dtype);
            Tensor freqs_long = t.matmul(inv_freq_long_tensor);
            Tensor long_sin = freqs_long.sin().mul(scaling_factor);
            Tensor long_cos = freqs_long.cos().mul(scaling_factor);

            // Calculate sin,cos for short
            Tensor inv_freq_short_tensor = Tensor::from_vec(inv_freq_short, { 1, inv_freq_len }, dev).to_dtype(dtype);
            Tensor freqs_short = t.matmul(inv_freq_short_tensor);
            Tensor short_sin = freqs_short.sin().mul(scaling_factor);
            Tensor short_cos = freqs_short.cos().mul(scaling_factor);

            return PhiRotaryEmbedding {
                short_cos,
                short_sin,
                long_cos,
                long_sin,
                cfg.original_max_position_embeddings
            };
        } else {
            std::vector<float> inv_freq(dim / 2);
            for (int i = 0; i < dim; i += 2) {
                inv_freq[i / 2] = 1.0f / std::pow(cfg.rope_theta, static_cast<float>(i) / static_cast<float>(dim));
            }
            int inv_freq_len = inv_freq.size();
            Tensor inv_freq_tensor = Tensor::from_vec(inv_freq, { 1, inv_freq_len }, dev).to_dtype(dtype);
            Tensor t = Tensor::arange(0u32, max_seq_len, dev).to_dtype(dtype).reshape({ max_seq_len, 1 });
            Tensor freqs = t.matmul(inv_freq_tensor);
            Tensor sin = freqs.sin();
            Tensor cos = freqs.cos();
            return PhiRotaryEmbedding {
                cos,
                sin,
                std::nullopt,
                std::nullopt,
                cfg.original_max_position_embeddings
            };
        }
    }

    std::pair<const Tensor&, const Tensor&> get_long_or_short_sin_cos(const std::vector<size_t>& seqlen_offsets) const {
        if (!long_cos.has_value()) {
            return { short_sin, short_cos };
        }
        size_t seq_len = *std::max_element(seqlen_offsets.begin(), seqlen_offsets.end()) + 1;
        if (seq_len > original_max_position_embeddings) {
            return { *long_sin, *long_cos };
        } else {
            return { short_sin, short_cos };
        }
    }

    std::pair<Tensor, Tensor> forward(const Tensor& q, const Tensor& k, const std::vector<size_t>& seqlen_offsets) const {
        auto [_b_sz, _h, seq_len, _n_embd] = q.dims4();
        std::vector<Tensor> q_embeds;
        std::vector<Tensor> k_embeds;
        auto [sin, cos] = get_long_or_short_sin_cos(seqlen_offsets);
        for (auto offset : seqlen_offsets) {
            Tensor cos_chunk = cos.narrow(0, offset, seq_len);
            Tensor sin_chunk = sin.narrow(0, offset, seq_len);
            Tensor q_embed = candle_nn::rotary_emb::rope(q.contiguous(), cos_chunk, sin_chunk);
            Tensor k_embed = candle_nn::rotary_emb::rope(k.contiguous(), cos_chunk, sin_chunk);
            q_embeds.push_back(q_embed);
            k_embeds.push_back(k_embed);
        }
        return { Tensor::cat(q_embeds, 0), Tensor::cat(k_embeds, 0) };
    }
};


Looks great to me.
