### ISSUE TITLE
Import Error Using model loader ExLlamav2

### ISSUE THREAD

**Issue by weirdozumbo** [oobabooga/text-generation-webui#5940]
### Describe the bug

Every time I try to load my GPTQ model using ExLlamav2, or the HF variant I get an import error 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

used linux one-click installer and selected the AMD option

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/43104929/092c72f9-8819-4229-882f-049f680ece1a)

### Logs

```shell
Traceback (most recent call last):

File "/home/luked/text-generation-webui/modules/ui_model_menu.py", line 247, in load_model_wrapper

shared.model, shared.tokenizer = load_model(selected_model, loader)

                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/luked/text-generation-webui/modules/models.py", line 94, in load_model

output = load_func_map[loader](model_name)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/luked/text-generation-webui/modules/models.py", line 372, in ExLlamav2_HF_loader

from modules.exllamav2_hf import Exllamav2HF

File "/home/luked/text-generation-webui/modules/exllamav2_hf.py", line 7, in

from exllamav2 import (

File "/home/luked/text-generation-webui/installer_files/env/lib/python3.11/site-packages/exllamav2/init.py", line 3, in

from exllamav2.model import ExLlamaV2

File "/home/luked/text-generation-webui/installer_files/env/lib/python3.11/site-packages/exllamav2/model.py", line 23, in

from exllamav2.config import ExLlamaV2Config

File "/home/luked/text-generation-webui/installer_files/env/lib/python3.11/site-packages/exllamav2/config.py", line 3, in

from exllamav2.fasttensors import STFile

File "/home/luked/text-generation-webui/installer_files/env/lib/python3.11/site-packages/exllamav2/fasttensors.py", line 6, in

from exllamav2.ext import exllamav2_ext as ext_c

File "/home/luked/text-generation-webui/installer_files/env/lib/python3.11/site-packages/exllamav2/ext.py", line 19, in

import exllamav2_ext

ImportError: /home/luked/text-generation-webui/installer_files/env/lib/python3.11/site-packages/exllamav2_ext.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN3c107WarningC1ENS_7variantIJNS0_11UserWarningENS0_18DeprecationWarningEEEERKNS_14SourceLocationESsb
```

### System Info

```shell
(GPU) AMD RX 7900 XTX
(CPU) AMD RYZEN 7 5800X
(RAM) 32GB DDR4
(OS) Ubuntu 22.04.4 LTS
```

**Comment by mamei16** [comment]
Same here, also using an AMD card. A temporary workaround before the problem is fixed is to re-install exllamav2 manually. I did the following from within the `text-generation-webui` folder:
1. `git clone https://github.com/turboderp/exllamav2`
2. `conda activate installer_files/env`
3. `cd exllamav2`
4. `pip install .`

After that, you can remove the `exllamav2` folder again.

**Comment by VirtualValence** [comment]
> Same here, also using an AMD card. A temporary workaround before the problem is fixed is to re-install exllamav2 manually. I did the following from within the `text-generation-webui` folder:
> 
>     1. `git clone https://github.com/turboderp/exllamav2`
> 
>     2. `conda activate installer_files/env`
> 
>     3. `cd exllamav2`
> 
>     4. `pip install .`
> 
> 
> After that, you can remove the `exllamav2` folder again.

I ran the `cmd_linux` script to get into the venv instead of the conda command, worked all the same and no more errors, thanks!
