### ISSUE TITLE
CUDA out of memory, ( cuda all updated, gpu working) issue

### ISSUE THREAD

**Issue by makrse** [oobabooga/text-generation-webui#5969]
### Describe the bug

Its when I tried to use some local llm in AutoGPTQ, example:

TheBloke_samantha-falcon-7B-GPTQ
TheBloke_WizardLM-Uncensored-Falcon-7B-GPTQ

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

![imagen_2024-05-01_184009752](https://github.com/oobabooga/text-generation-webui/assets/131285038/42c6535e-5c4f-4ecc-a838-4bf1fa194dd5)

### Screenshot

![imagen_2024-05-01_183833537](https://github.com/oobabooga/text-generation-webui/assets/131285038/5e97fd07-976e-4909-abec-86ce9608eebc)

### Logs

```shell
18:35:31-847027 INFO     Loading "TheBloke_samantha-falcon-7B-GPTQ"
18:35:31-851017 INFO     The AutoGPTQ params are: {'model_basename': 'model', 'device': 'cuda:0', 'use_triton': False,
                         'inject_fused_attention': True, 'inject_fused_mlp': True, 'use_safetensors': True,
                         'trust_remote_code': True, 'max_memory': {0: '4100MiB', 'cpu': '99GiB'}, 'quantize_config':
                         None, 'use_cuda_fp16': False, 'disable_exllama': False, 'disable_exllamav2': False}
18:35:35-585792 ERROR    Failed to load the model.
Traceback (most recent call last):
  File "D:\text-generation-webui\modules\ui_model_menu.py", line 247, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI-World\text-generation-webui\modules\models.py", line 94, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui\modules\models.py", line 362, in AutoGPTQ_loader
    return modules.AutoGPTQ_loader.load_quantized(model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui\modules\AutoGPTQ_loader.py", line 59, in load_quantized
    model = AutoGPTQForCausalLM.from_quantized(path_to_model, **params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui\installer_files\env\Lib\site-packages\auto_gptq\modeling\auto.py", line 129, in from_quantized
    return quant_func(
           ^^^^^^^^^^^
  File "D:\text-generation-webui\installer_files\env\Lib\site-packages\auto_gptq\modeling\_base.py", line 946, in from_quantized
    accelerate.utils.modeling.load_checkpoint_in_model(
  File "D:\text-generation-webui\installer_files\env\Lib\site-packages\accelerate\utils\modeling.py", line 1568, in load_checkpoint_in_model
    checkpoint = load_state_dict(checkpoint_file, device_map=device_map)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui\installer_files\env\Lib\site-packages\accelerate\utils\modeling.py", line 1336, in load_state_dict
    return safe_load_file(checkpoint_file, device=list(device_map.values())[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui\installer_files\env\Lib\site-packages\safetensors\torch.py", line 313, in load_file
    result[k] = f.get_tensor(k)
                ^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 564.00 MiB. GPU 0 has a total capacity of 23.99 GiB of which 18.78 GiB is free. Of the allocated memory 3.93 GiB is allocated by PyTorch, and 32.22 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

### System Info

```shell
gpu 3090
windows 10
```

**Comment by pikmok-pc** [comment]
same here with 2080 it and ubuntu 20.04.

**Comment by darkvokrat** [comment]
Same Here with 1x 2070 super and 1x Quadro M4000
