### ISSUE TITLE
whisper_stt: not recording

### ISSUE THREAD

**Issue by alexl83** [oobabooga/text-generation-webui#599]
### Describe the bug

whisper_stt installed with no issues, unfortunately even though it's loading, pressing the "record" button dones't trigger any actual recording, not even permission is requested to the browser

Tried Safari, Firefox, Chrome on MacOS Ventura 13.2.1 - all vanilla - no filtering

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

load server.py with whisper_stt enabled in settings.json

`
python server.py --wbits 4 --cai-chat --listen --settings ~/oobabooga/settings.json --model llama-30b
`

### Screenshot

<img width="977" alt="immagine" src="https://user-images.githubusercontent.com/18349597/228022319-a18af9af-d450-43ac-9c57-dbc7329de88b.png">

### Logs

```shell
Loading settings from /home/alex/oobabooga/settings.json...
Loading llama-30b...
Found models/llama-30b/llama-30b-4bit.safetensors
Loading model ...
Done.
Loaded the model in 3.78 seconds.
Loading the extension "gallery"... Ok.
Loading the extension "llama_prompts"... Ok.
Loading the extension "whisper_stt"... Ok.
/home/alex/oobabooga/installer_files/env/lib/python3.10/site-packages/gradio/deprecation.py:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
  warnings.warn(value)
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/home/alex/oobabooga/installer_files/env/lib/python3.10/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/alex/oobabooga/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/home/alex/oobabooga/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/alex/oobabooga/installer_files/env/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/alex/oobabooga/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/alex/oobabooga/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/alex/oobabooga/text-generation-webui/extensions/whisper_stt/script.py", line 15, in do_stt
    audio_data = sr.AudioData(sample_rate=audio[0], frame_data=audio[1], sample_width=4)
TypeError: 'NoneType' object is not subscriptable
```

### System Info

```shell
AMD Ryzen 7700x
64Gb DDR5-5600
NVIDIA RTX 4090
200Gb swap
Ubuntu 22.10
miniconda environment
inference server: 192.168.1.138
remote client: 192.168.1.132
```

**Comment by oobabooga** [comment]
Most browsers block the microphone when HTTPS is disabled, which is the case for gradio during local usage.

See here how to enable the microphone:

https://stackoverflow.com/a/60109836
