### ISSUE TITLE
Seemingly no exl2 support

### ISSUE THREAD

**Issue by Blaxzter** [oobabooga/text-generation-webui#6002]
### Describe the bug

I try to load this model `huggingface-cli download hjhj3168/Llama-3-8b-Orthogonalized-exl2 --local-dir llama38b --local-dir-use-symlinks False` and receive this error:
```
15:20:16-086791 ERROR    Failed to load the model.
Traceback (most recent call last):
  File "M:\text-generation-webui\modules\ui_model_menu.py", line 249, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\text-generation-webui\modules\models.py", line 94, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\text-generation-webui\modules\models.py", line 166, in huggingface_loader
    model = LoaderClass.from_pretrained(path_to_model, **params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\text-generation-webui\installer_files\env\Lib\site-packages\transformers\models\auto\auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\text-generation-webui\installer_files\env\Lib\site-packages\transformers\modeling_utils.py", line 3155, in from_pretrained
    config.quantization_config = AutoHfQuantizer.merge_quantization_configs(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\text-generation-webui\installer_files\env\Lib\site-packages\transformers\quantizers\auto.py", line 149, in merge_quantization_configs
    quantization_config = AutoQuantizationConfig.from_dict(quantization_config)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\text-generation-webui\installer_files\env\Lib\site-packages\transformers\quantizers\auto.py", line 73, in from_dict
    raise ValueError(
ValueError: Unknown quantization type, got exl2 - supported types are: ['awq', 'bitsandbytes_4bit', 'bitsandbytes_8bit', 'gptq', 'aqlm', 'quanto']
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Clone repo
2. Run start_windows.bat
3. Restart the ui with the start_windows.bat
4. Download model with `huggingface-cli download hjhj3168/Llama-3-8b-Orthogonalized-exl2 --local-dir llama38b --local-dir-use-symlinks False` and place in models folder.
5. Try to load the model.

### Logs

```shell
15:20:16-086791 ERROR    Failed to load the model.
Traceback (most recent call last):
  File "M:\text-generation-webui\modules\ui_model_menu.py", line 249, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\text-generation-webui\modules\models.py", line 94, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\text-generation-webui\modules\models.py", line 166, in huggingface_loader
    model = LoaderClass.from_pretrained(path_to_model, **params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\text-generation-webui\installer_files\env\Lib\site-packages\transformers\models\auto\auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\text-generation-webui\installer_files\env\Lib\site-packages\transformers\modeling_utils.py", line 3155, in from_pretrained
    config.quantization_config = AutoHfQuantizer.merge_quantization_configs(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\text-generation-webui\installer_files\env\Lib\site-packages\transformers\quantizers\auto.py", line 149, in merge_quantization_configs
    quantization_config = AutoQuantizationConfig.from_dict(quantization_config)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\text-generation-webui\installer_files\env\Lib\site-packages\transformers\quantizers\auto.py", line 73, in from_dict
    raise ValueError(
ValueError: Unknown quantization type, got exl2 - supported types are: ['awq', 'bitsandbytes_4bit', 'bitsandbytes_8bit', 'gptq', 'aqlm', 'quanto']
```

### System Info

```shell
OS: Win 11
Processor: AMD Ryzen 9 7900X 12-Core Processor
GPU: NVIDIA GeForce RTX 4070 Ti SUPER
```

**Comment by Blaxzter** [comment]
For everyone who is equally dumb:
![image](https://github.com/oobabooga/text-generation-webui/assets/9212841/51d43bb6-b3cc-4877-b918-c238332aaaaf)

But a small hint if this error occurs would help :)
