### ISSUE TITLE
can't load 8B llava model

### ISSUE THREAD

**Issue by suspicious-pineapple** [oobabooga/text-generation-webui#6065]
### Describe the bug

Unable to load 8B llava model:
https://huggingface.co/xtuner/llava-llama-3-8b-v1_1-transformers

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. apply fix from #5038 
2. try loading the model
3. `AssertionError: Padding_idx must be within num_embeddings`

### Logs

```shell
Traceback (most recent call last):
  File "D:\text-generation-webui\modules\ui_model_menu.py", line 249, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui\modules\models.py", line 94, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui\modules\models.py", line 363, in GPTQ_loader
    model = modules.GPTQ_loader.load_quantized(model_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui\modules\GPTQ_loader.py", line 144, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.wbits, shared.args.groupsize, kernel_switch_threshold=threshold)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui\modules\GPTQ_loader.py", line 34, in _load_quant
    model = AutoModelForCausalLM.from_config(config, trust_remote_code=shared.args.trust_remote_code)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui\installer_files\env\Lib\site-packages\transformers\models\auto\auto_factory.py", line 437, in from_config
    return model_class._from_config(config, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui\installer_files\env\Lib\site-packages\transformers\modeling_utils.py", line 1401, in _from_config
    model = cls(config, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui\installer_files\env\Lib\site-packages\transformers\models\llama\modeling_llama.py", line 1138, in __init__
    self.model = LlamaModel(config)
                 ^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui\installer_files\env\Lib\site-packages\transformers\models\llama\modeling_llama.py", line 925, in __init__
    self.embed_tokens = nn.Embedding(config.vocab_size, config.hidden_size, self.padding_idx)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui\installer_files\env\Lib\site-packages\torch\nn\modules\sparse.py", line 134, in __init__
    assert padding_idx < self.num_embeddings, 'Padding_idx must be within num_embeddings'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Padding_idx must be within num_embeddings
```

### System Info

```shell
win10, CPU: 5700x, GPU: RTX 4070ti super
```

**Comment by Tedy50** [comment]
I think  this multimodal pipeline is not supported yet  
but it wud be nice to see it implemented.
GGUF format also already supports multimodal pipelines 
exllama seems to be missing support yet

**Comment by Touch-Night** [comment]
If you use llama.cpp's multimodal support, you cannot have custom prompt template.

**Comment by oobabooga** [comment]
Multimodal models are now supported through the llama.cpp and ExLlamaV3 loaders, both in the UI and the API. A tutorial can be found here:

https://github.com/oobabooga/text-generation-webui/wiki/Multimodal-Tutorial

<img width="600" height="884" alt="print6" src="https://github.com/user-attachments/assets/be4a8f4d-619d-49e6-86f5-012d89f8db8d" />
