### ISSUE TITLE
Model download - [Errno 101] Network is unreachable - How to configure a proxy?

### ISSUE THREAD

**Issue by Starbase12** [oobabooga/text-generation-webui#6067]
### Describe the bug

When trying to download my first LLM model I faced the issue "OSError: [Errno 101] Network is unreachable". Because of my previus made configuration I know that this must have something to do with the required proxy I have to configure. But where? Is is supported or maybe a missing feature?

When I connect the computer to a external network which doesn't requires a proxy server all works fine.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Setup Text generation web UI on a network which requires a proxy server configured to be able to access the internet and start downloading a model via the web gui or download-model.py.

### Screenshot

![Network-unreachable](https://github.com/oobabooga/text-generation-webui/assets/18394355/3527089a-3d47-4d38-a83e-3a74260f715b)

### Logs

```shell
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/git/text-generation-webui/download-model.py", line 330, in <module>
    links, sha256, is_lora, is_llamacpp = downloader.get_download_links_from_huggingface(model, branch, text_only=args.text_only, specific_file=specific_file)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/git/text-generation-webui/download-model.py", line 89, in get_download_links_from_huggingface
    r = session.get(url, timeout=10)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/git/text-generation-webui/installer_files/env/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/git/text-generation-webui/installer_files/env/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/git/text-generation-webui/installer_files/env/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/git/text-generation-webui/installer_files/env/lib/python3.11/site-packages/requests/adapters.py", line 622, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF/mixtral-8x7b-instruct-v0.1.Q5_K_M.gguf/tree/main (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fda9d469250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```

### System Info

```shell
Debian 12 (Bookworm)
```

**Comment by blackmambaza** [comment]
This seems to be a problem with your proxy configuration. It works on the proxy that I have on my network. Please close this issue and recheck your proxy settings.
