### ISSUE TITLE
Latest update broken GGUF support, it looks like

### ISSUE THREAD

**Issue by Iommed** [oobabooga/text-generation-webui#6080]
### Describe the bug

Unable to run GGUF files after update. Tested with several 120B 5_Q_M and 103B and 70b Q8_0

I have 128GB RAM. Every single one of these models ran just fine until today. Please fix. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load a GGUF file (split or unsplit) and confirm it successfully runs

### Logs

```shell
AttributeError: 'LlamaCppModel' object has no attribute 'model'
18:38:54-407569 INFO     Loading "LLama-3-Dolphin-2.9.1-120b.Q5_K_M.gguf.part1of2"
18:38:54-817661 INFO     llama.cpp weights detected: "models\LLama-3-Dolphin-2.9.1-120b.Q5_K_M.gguf.part1of2"
llama_model_load: error loading model: tensor 'blk.81.attn_q.weight' data is not within the file bounds, model is corrupted or incomplete
llama_load_model_from_file: failed to load model
18:38:54-858670 ERROR    Failed to load the model.
Traceback (most recent call last):
  File "C:\text-generation-webui-main\text-generation-webui-main\modules\ui_model_menu.py", line 249, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui-main\text-generation-webui-main\modules\models.py", line 94, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui-main\text-generation-webui-main\modules\models.py", line 272, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui-main\text-generation-webui-main\modules\llamacpp_model.py", line 103, in from_pretrained
    result.model = Llama(**params)
                   ^^^^^^^^^^^^^^^
  File "C:\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\llama_cpp_cuda\llama.py", line 338, in __init__
    self._model = _LlamaModel(
                  ^^^^^^^^^^^^
  File "C:\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\llama_cpp_cuda\_internals.py", line 57, in __init__
    raise ValueError(f"Failed to load model from file: {path_model}")
ValueError: Failed to load model from file: models\LLama-3-Dolphin-2.9.1-120b.Q5_K_M.gguf.part1of2

Exception ignored in: <function LlamaCppModel.__del__ at 0x000002874CCF23E0>
Traceback (most recent call last):
  File "C:\text-generation-webui-main\text-generation-webui-main\modules\llamacpp_model.py", line 58, in __del__
    del self.model
        ^^^^^^^^^^
AttributeError: 'LlamaCppModel' object has no attribute 'model'
18:39:02-651890 INFO     Loading "LLama-3-Dolphin-2.9.1-120b.Q5_K_M.gguf"
18:39:03-044986 INFO     llama.cpp weights detected: "models\LLama-3-Dolphin-2.9.1-120b.Q5_K_M.gguf"
llama_model_loader: loaded meta data with 30 key-value pairs and 1263 tensors from models\LLama-3-Dolphin-2.9.1-120b.Q5_K_M.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = LLama-3-Dolphin-2.9.1-120b
llama_model_loader: - kv   2:                          llama.block_count u32              = 140
llama_model_loader: - kv   3:                       llama.context_length u32              = 8192
llama_model_loader: - kv   4:                     llama.embedding_length u32              = 8192
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 28672
llama_model_loader: - kv   6:                 llama.attention.head_count u32              = 64
llama_model_loader: - kv   7:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   8:                       llama.rope.freq_base f32              = 500000.000000
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                          general.file_type u32              = 17
llama_model_loader: - kv  11:                           llama.vocab_size u32              = 128258
llama_model_loader: - kv  12:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv  13:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  14:                         tokenizer.ggml.pre str              = llama-bpe
llama_model_loader: - kv  15:                      tokenizer.ggml.tokens arr[str,128258]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  16:                  tokenizer.ggml.token_type arr[i32,128258]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  17:                      tokenizer.ggml.merges arr[str,280147]  = ["─á ─á", "─á ─á─á─á", "─á─á ─á─á", "...
llama_model_loader: - kv  18:                tokenizer.ggml.bos_token_id u32              = 128000
llama_model_loader: - kv  19:                tokenizer.ggml.eos_token_id u32              = 128256
llama_model_loader: - kv  20:            tokenizer.ggml.padding_token_id u32              = 128001
llama_model_loader: - kv  21:                    tokenizer.chat_template str              = {% if not add_generation_prompt is de...
llama_model_loader: - kv  22:               general.quantization_version u32              = 2
llama_model_loader: - kv  23:                                general.url str              = https://huggingface.co/mradermacher/L...
llama_model_loader: - kv  24:              mradermacher.quantize_version str              = 2
llama_model_loader: - kv  25:                  mradermacher.quantized_by str              = mradermacher
llama_model_loader: - kv  26:                  mradermacher.quantized_at str              = 2024-05-25T22:28:36+02:00
llama_model_loader: - kv  27:                  mradermacher.quantized_on str              = backup1
llama_model_loader: - kv  28:                         general.source.url str              = https://huggingface.co/DarqueDante/LL...
llama_model_loader: - kv  29:                  mradermacher.convert_type str              = hf
llama_model_loader: - type  f32:  281 tensors
llama_model_loader: - type q5_K:  841 tensors
llama_model_loader: - type q6_K:  141 tensors
llm_load_vocab: special tokens definition check successful ( 258/128258 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 128258
llm_load_print_meta: n_merges         = 280147
llm_load_print_meta: n_ctx_train      = 8192
llm_load_print_meta: n_embd           = 8192
llm_load_print_meta: n_head           = 64
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 140
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 8
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 28672
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 500000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 8192
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = ?B
llm_load_print_meta: model ftype      = Q5_K - Medium
llm_load_print_meta: model params     = 121.89 B
llm_load_print_meta: model size       = 80.29 GiB (5.66 BPW)
llm_load_print_meta: general.name     = LLama-3-Dolphin-2.9.1-120b
llm_load_print_meta: BOS token        = 128000 '<|begin_of_text|>'
llm_load_print_meta: EOS token        = 128256 '<|im_end|>'
llm_load_print_meta: PAD token        = 128001 '<|end_of_text|>'
llm_load_print_meta: LF token         = 128 '├ä'
llm_load_print_meta: EOT token        = 128256 '<|im_end|>'
llm_load_tensors: ggml ctx size =    1.28 MiB
ggml_backend_cuda_buffer_type_alloc_buffer: allocating 81527.62 MiB on device 0: cudaMalloc failed: out of memory
llama_model_load: error loading model: unable to allocate backend buffer
llama_load_model_from_file: failed to load model
18:39:17-629275 ERROR    Failed to load the model.
Traceback (most recent call last):
  File "C:\text-generation-webui-main\text-generation-webui-main\modules\ui_model_menu.py", line 249, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui-main\text-generation-webui-main\modules\models.py", line 94, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui-main\text-generation-webui-main\modules\models.py", line 272, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\text-generation-webui-main\text-generation-webui-main\modules\llamacpp_model.py", line 103, in from_pretrained
    result.model = Llama(**params)
                   ^^^^^^^^^^^^^^^
  File "C:\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\llama_cpp_cuda\llama.py", line 338, in __init__
    self._model = _LlamaModel(
                  ^^^^^^^^^^^^
  File "C:\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\llama_cpp_cuda\_internals.py", line 57, in __init__
    raise ValueError(f"Failed to load model from file: {path_model}")
ValueError: Failed to load model from file: models\LLama-3-Dolphin-2.9.1-120b.Q5_K_M.gguf

Exception ignored in: <function LlamaCppModel.__del__ at 0x000002874CCF23E0>
Traceback (most recent call last):
  File "C:\text-generation-webui-main\text-generation-webui-main\modules\llamacpp_model.py", line 58, in __del__
    del self.model
        ^^^^^^^^^^
AttributeError: 'LlamaCppModel' object has no attribute 'model'
```

### System Info

```shell
Ryzen 9 3900X
128GB RAM
RTX 4060 TI
```

**Comment by Iommed** [comment]
(Updated TextGen Webui was apparently trying to allocate far too much to the GPU and setting n-gpu-layers to 0 appears to have fixed this)

**Comment by cpumaxx** [comment]
I'm having this same problem, even when I'm using --n-gpu-layers=0 (or --n-gpu-layers=1)

**Comment by YakuzaSuske** [comment]
Same issue.
