### ISSUE TITLE
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'logs\\chat\\Вика Бокс '

### ISSUE THREAD

**Issue by viliamvolosv** [oobabooga/text-generation-webui#6096]
### Describe the bug

working on windows
I create a person Вика Бокс - russin language 
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'logs\\chat\\Вика Бокс '
FileNotFoundError: [WinError 3] The system cannot find the specified path

but this path is exist d:\text-generation-webui-main\text-generation-webui\logs\chat\Вика Бокс\

i think problem with rus letters or space bar in name

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Create persona with russin name and space bar 

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/1593192/07817278-5f1d-4376-a9ce-6af6206c874d)

### Logs

```shell
File "D:\text-generation-webui-main\text-generation-webui\modules\chat.py", line 472, in start_new_chat
    save_history(history, unique_id, state['character_menu'], state['mode'])
  File "D:\text-generation-webui-main\text-generation-webui\modules\chat.py", line 494, in save_history
    with open(p, 'w', encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'logs\\chat\\Вика Бокс \\20240604-15-56-16.json'
Traceback (most recent call last):
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\modules\ui_chat.py", line 255, in <lambda>
    lambda x: gr.update(choices=(histories := chat.find_all_histories(x)), value=histories[0]), gradio('interface_state'), gradio('unique_id'))
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\modules\chat.py", line 538, in find_all_histories
    histories = sorted(paths, key=lambda x: x.stat().st_mtime, reverse=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\pathlib.py", line 953, in glob
    for p in selector.select_from(self):
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\pathlib.py", line 355, in _select_from
    with scandir(parent_path) as scandir_it:
         ^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\pathlib.py", line 938, in _scandir
    return os.scandir(self)
           ^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'logs\\chat\\Вика Бокс '
Traceback (most recent call last):
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\modules\chat.py", line 472, in start_new_chat
    save_history(history, unique_id, state['character_menu'], state['mode'])
  File "D:\text-generation-webui-main\text-generation-webui\modules\chat.py", line 494, in save_history
    with open(p, 'w', encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'logs\\chat\\Вика Бокс \\20240604-15-56-17.json'
Traceback (most recent call last):
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\modules\ui_chat.py", line 255, in <lambda>
    lambda x: gr.update(choices=(histories := chat.find_all_histories(x)), value=histories[0]), gradio('interface_state'), gradio('unique_id'))
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\modules\chat.py", line 538, in find_all_histories
    histories = sorted(paths, key=lambda x: x.stat().st_mtime, reverse=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\pathlib.py", line 953, in glob
    for p in selector.select_from(self):
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\pathlib.py", line 355, in _select_from
    with scandir(parent_path) as scandir_it:
         ^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\pathlib.py", line 938, in _scandir
    return os.scandir(self)
           ^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'logs\\chat\\Вика Бокс '
Traceback (most recent call last):
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\modules\chat.py", line 472, in start_new_chat
    save_history(history, unique_id, state['character_menu'], state['mode'])
  File "D:\text-generation-webui-main\text-generation-webui\modules\chat.py", line 494, in save_history
    with open(p, 'w', encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'logs\\chat\\Вика Бокс \\20240604-15-57-03.json'
Traceback (most recent call last):
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\modules\ui_chat.py", line 255, in <lambda>
    lambda x: gr.update(choices=(histories := chat.find_all_histories(x)), value=histories[0]), gradio('interface_state'), gradio('unique_id'))
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\modules\chat.py", line 538, in find_all_histories
    histories = sorted(paths, key=lambda x: x.stat().st_mtime, reverse=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\pathlib.py", line 953, in glob
    for p in selector.select_from(self):
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\pathlib.py", line 355, in _select_from
    with scandir(parent_path) as scandir_it:
         ^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\pathlib.py", line 938, in _scandir
    return os.scandir(self)
           ^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'logs\\chat\\Вика Бокс '
Output generated in 40.27 seconds (1.66 tokens/s, 67 tokens, context 309, seed 1606568104)
Traceback (most recent call last):
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\modules\chat.py", line 553, in load_latest_history
    histories = find_all_histories(state)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\modules\chat.py", line 538, in find_all_histories
    histories = sorted(paths, key=lambda x: x.stat().st_mtime, reverse=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\pathlib.py", line 953, in glob
    for p in selector.select_from(self):
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\pathlib.py", line 355, in _select_from
    with scandir(parent_path) as scandir_it:
         ^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\pathlib.py", line 938, in _scandir
    return os.scandir(self)
           ^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'logs\\chat\\Вика Бокс '
Traceback (most recent call last):
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\modules\ui_chat.py", line 298, in <lambda>
    lambda x: gr.update(choices=(histories := chat.find_all_histories(x)), value=histories[0]), gradio('interface_state'), gradio('unique_id')).then(
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\modules\chat.py", line 538, in find_all_histories
    histories = sorted(paths, key=lambda x: x.stat().st_mtime, reverse=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\pathlib.py", line 953, in glob
    for p in selector.select_from(self):
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\pathlib.py", line 355, in _select_from
    with scandir(parent_path) as scandir_it:
         ^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\pathlib.py", line 938, in _scandir
    return os.scandir(self)
           ^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'logs\\chat\\Вика Бокс '
15:59:38-381996 ERROR    Could not find the character "None" inside characters/. No character has been loaded.
Traceback (most recent call last):
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui\modules\chat.py", line 665, in load_character
    raise ValueError
```

### System Info

```shell
Windows, gtx3600 , i7
```

**Comment by Alkohole** [comment]
Проблема в том, что у вас действительно нет папки "Вика Бокс ", у вас лишний пробел, из-за чего скрипт и не может найти эту папку.
- Или удалите пробел, который у вас идет после слова "Бокс " в окне персонажей.
- Или добавьте пробел после слова "Бокс" в имени папки.
<hr>

The problem is that you really don't have a "Вика Бокс " folder, you have an extra space, which is why the script can't find this folder.
- Or remove the space you have coming after the word "Бокс " in the character box.
- Or add a space after the word "Бокс" in the folder name.

**Comment by viliamvolosv** [comment]
> The problem is that you really don't have a "Вика Бокс " folder, you have an extra space, which is why the script can't find this folder.
> 
> * Or remove the space you have coming after the word "Бокс " in the character box.
> * Or add a space after the word "Бокс" in the folder name.

Its strange - i have folder 'Вика Бокс ' - without space in the end
"d:\text-generation-webui-main\text-generation-webui\logs\chat\Вика Бокс"

problem that all  this was creatated from UI - this why i market this as a bug

**Comment by Alkohole** [comment]
> Its strange - i have folder 'Вика Бокс ' - without space in the end
> "d:\text-generation-webui-main\text-generation-webui\logs\chat\Вика Бокс"

That's the problem, the logs clearly show that it searches for a folder With(not without) a space at the end:

```
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'logs\\chat\\Вика Бокс '
FileNotFoundError: [Errno 2] No such file or directory: 'logs\\chat\\Вика Бокс \\20240604-15-56-17.json'
```

> problem that all this was creatated from UI - this why i market this as a bug

Well my attempt to replicate your problem didn't bring any results, additional games with renaming/deleting also didn't give me an error because webui was actively recreating the right folder and history for the chat.

Are you using the latest version of webui and have you tried recreating the bot?

**Comment by viliamvolosv** [comment]
Im Using dev  branch
