### ISSUE TITLE
import TavernAI character card error

### ISSUE THREAD

**Issue by scavru** [oobabooga/text-generation-webui#611]
### Describe the bug

An error occurs when trying to upload a .webp file
```
Traceback (most recent call last):
  File "e:\2\installer_files\env\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "e:\2\installer_files\env\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "e:\2\installer_files\env\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "e:\2\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "e:\2\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "e:\2\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "e:\2\text-generation-webui\modules\chat.py", line 384, in upload_tavern_character
    decoded_string = base64.b64decode(_img.info['chara'])
KeyError: 'chara'
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

win11 установка one-click-installers-oobabooga-windows
start arguments call python server.py --auto-devices --no-cache --chat --load-in-8bit --listen --share

### Screenshot

![Снимок экрана 2023-03-28 105141](https://user-images.githubusercontent.com/47884122/228166893-a0cff5bf-0c21-4f5c-86ad-526bd251b1a0.png)

### Logs

```shell
Traceback (most recent call last):
  File "e:\2\installer_files\env\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "e:\2\installer_files\env\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "e:\2\installer_files\env\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "e:\2\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "e:\2\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "e:\2\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "e:\2\text-generation-webui\modules\chat.py", line 384, in upload_tavern_character
    decoded_string = base64.b64decode(_img.info['chara'])
KeyError: 'chara'
```

### System Info

```shell
gtx 3070
```

**Comment by oobabooga** [comment]
That's more like an enhancement. They released a new format which has not been ported here yet.
