### ISSUE TITLE
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by MamaTwoya** [oobabooga/text-generation-webui#6113]
### Describe the bug

Traceback (most recent call last):
  File "F:\gptai\text-generation-webui-snapshot-2024-04-28\modules\callbacks.py", line 61, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\gptai\text-generation-webui-snapshot-2024-04-28\modules\text_generation.py", line 376, in generate_with_callback
    shared.model.generate(**kwargs)
  File "F:\gptai\text-generation-webui-snapshot-2024-04-28\installer_files\env\Lib\site-packages\awq\models\base.py", line 110, in generate
    return self.model.generate(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\gptai\text-generation-webui-snapshot-2024-04-28\installer_files\env\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "F:\gptai\text-generation-webui-snapshot-2024-04-28\installer_files\env\Lib\site-packages\transformers\generation\utils.py", line 1559, in generate
    result = self._assisted_decoding(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\gptai\text-generation-webui-snapshot-2024-04-28\installer_files\env\Lib\site-packages\transformers\generation\utils.py", line 4718, in _assisted_decoding
    selected_tokens = torch.multinomial(probs[0, :, :], num_samples=1).squeeze(1)[None, :]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

just type anything in the webui

### Logs

```shell
03:02:50-499440 INFO     "Midnight Enigma" preset:
{   'temperature': 0.98,
    'top_p': 0.37,
    'top_k': 100,
    'repetition_penalty': 1.18}
Traceback (most recent call last):
  File "F:\gptai\text-generation-webui-snapshot-2024-04-28\modules\callbacks.py", line 61, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\gptai\text-generation-webui-snapshot-2024-04-28\modules\text_generation.py", line 376, in generate_with_callback
    shared.model.generate(**kwargs)
  File "F:\gptai\text-generation-webui-snapshot-2024-04-28\installer_files\env\Lib\site-packages\awq\models\base.py", line 110, in generate
    return self.model.generate(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\gptai\text-generation-webui-snapshot-2024-04-28\installer_files\env\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "F:\gptai\text-generation-webui-snapshot-2024-04-28\installer_files\env\Lib\site-packages\transformers\generation\utils.py", line 1559, in generate
    result = self._assisted_decoding(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\gptai\text-generation-webui-snapshot-2024-04-28\installer_files\env\Lib\site-packages\transformers\generation\utils.py", line 4718, in _assisted_decoding
    selected_tokens = torch.multinomial(probs[0, :, :], num_samples=1).squeeze(1)[None, :]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
Output generated in 12.25 seconds (0.16 tokens/s, 2 tokens, context 3369, seed 238601171)
```

### System Info

```shell
CPU: AMD Ryzen 5 5600X 6-Core Processor 3.70 GHz
GPU: Nvidia GeForce 3060 12gb
```

**Comment by MamaTwoya** [comment]
the error appeared out of nowhere, while i was chating with the ai

**Comment by RandomInternetPreson** [comment]
Hmm, I'm getting this error trying to load Gemma2 27B.

09:51:48-156429 INFO     Loaded "gemma-2-27b" in 229.33 seconds.                
09:51:48-157345 INFO     LOADER: "Transformers"                                 
09:51:48-157879 INFO     TRUNCATION LENGTH: 8192                                
09:51:48-158372 INFO     INSTRUCTION TEMPLATE: "Alpaca"                         
Traceback (most recent call last):
  File "/home/myself/Desktop/OobV191/text-generation-webui/modules/callbacks.py", line 61, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myself/Desktop/OobV191/text-generation-webui/modules/text_generation.py", line 393, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/myself/Desktop/OobV191/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/myself/Desktop/OobV191/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/generation/utils.py", line 1914, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "/home/myself/Desktop/OobV191/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/generation/utils.py", line 2693, in _sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
Output generated in 2.32 seconds (0.00 tokens/s, 0 tokens, context 68, seed 2101070983)

**Comment by RandomInternetPreson** [comment]
Hello, I don't know if you resolved this issue or not, but in my case I needed to load the model with the "bf16" checkbox checked when using the transformers loader.

Since it seems like your problem happened out of the blue when things were working fine, have you tried deleting some of the most recent files in your .cache folder (if using linux) there is also a windows .cache folder.

Sometimes when weird errors happen it can be due to the program referencing something in cache that is goofed up.  A recent example for me is Alltalk, I could not get it to load with deepseek enabled when the previous day things were working fine.

The problem was that even though oobabooga's textgen is installed in its own environment some of the stuff that we need to have textgen work uses stuff in these cache folders.  The cache should be rebuilt automatically, but if you have doubts you can rename the folders in your cache folder so you have a copy you can reference at a later point if necessary.
