### ISSUE TITLE
lora with qwen2-7B-Instruct is KeyError:'qwen2'

### ISSUE THREAD

**Issue by liutianye** [oobabooga/text-generation-webui#6148]
### Describe the bug

use text-generation-webui，I can user Chat fun noramal but when I want lora with ruozhiba databases it's error whit "KeyError:'qwen2'"

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

use text-generation-webui，I can user Chat fun noramal but when I want lora with ruozhiba databases it's error whit "KeyError:'qwen2'"

### Logs

```shell
10:54:08-969009 INFO     Getting model ready
10:54:08-972010 INFO     Preparing for training
Traceback (most recent call last):
  File "C:\lora\text-generation-webui\installer_files\env\Lib\site-packages\gradio\queueing.py", line 566, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\lora\text-generation-webui\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\lora\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\lora\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1350, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\lora\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 583, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\lora\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 576, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\lora\text-generation-webui\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\lora\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\lora\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\lora\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 559, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "C:\lora\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 742, in gen_wrapper
    response = next(iterator)
               ^^^^^^^^^^^^^^
  File "C:\lora\text-generation-webui\modules\training.py", line 522, in do_train
    target_modules=list_target_modules(model_id),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\lora\text-generation-webui\modules\training.py", line 337, in list_target_modules
    return model_to_lora_modules[model_id]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'qwen2'
```

### System Info

```shell
torch   : 2.3.1+cu121
CUDA    : True
cuDNN   : 8907
```

**Comment by oobabooga** [comment]
The training code has been rewritten in v4.0. The "Target all linear layers" checkbox works for any model architecture, so you no longer hit KeyErrors for unsupported model types. See the [release notes](https://github.com/oobabooga/text-generation-webui/releases/tag/v4.0) and [training docs](https://github.com/oobabooga/text-generation-webui/wiki/05-%E2%80%90-Training-Tab).
