### ISSUE TITLE
ModuleNotFoundError: No module named 'exllamav2'

### ISSUE THREAD

**Issue by Geiokami** [oobabooga/text-generation-webui#6163]
for months now ive gotten this error on any GPTQ models i try to load with my IPEX install. Ive tried everything i could find in the issues tab but it all seems to be for linux only.  Happens with every gpu based model and any loader for them. I can run cpu models in a cpu install just fine. I can see all the .py and .pyc module files. 

Traceback (most recent call last):

File "S:\AI\GPU-June\modules\ui_model_menu.py", line 249, in load_model_wrapper

shared.model, shared.tokenizer = load_model(selected_model, loader)

                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "S:\AI\GPU-June\modules\models.py", line 94, in load_model

output = load_func_map[loader](model_name)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "S:\AI\GPU-June\modules\models.py", line 373, in ExLlamav2_HF_loader

from modules.exllamav2_hf import Exllamav2HF

File "S:\AI\GPU-June\modules\exllamav2_hf.py", line 7, in

from exllamav2 import (

ModuleNotFoundError: No module named 'exllamav2'

I5-12400f
16GB DDR4
Arc A770 16Gb
Windows 10

**Comment by ddashizzle** [comment]
I ran into this when trying to install and run cpu_only from the "requirements_cpu_only.txt". I can run on an RTX 3080 when installing via "requirements.txt". 

My solution for my cpu only conda environment was to pip install both requirements.txt and requirements_cpu_only.txt.

It seems like the exllamav2 module is not installing with the cpu only txt. Try installing exllamav2 as listed in the requirements.txt for your version of python and see if that helps.
