### ISSUE TITLE
AMDGPU is broken on 1.8

### ISSUE THREAD

**Issue by pl752** [oobabooga/text-generation-webui#6169]
### Describe the bug

llamacpp doesn't see radeon rx6900xt, previous version worked fine, it seems it has missing dependencies (rocm 5.7.1 is installed)
in particular llama_cpp_cuda can not be imported
```
pl752@pl752-desktop:~/text-generation-webui-1.8$ source installer_files/conda/bin/activate 
(base) pl752@pl752-desktop:~/text-generation-webui-1.8$ conda activate installer_files/env/
(/home/pl752/text-generation-webui-1.8/installer_files/env) pl752@pl752-desktop:~/text-generation-webui-1.8$ python
Python 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import llama_cpp
>>> import llama_cpp_cuda
Traceback (most recent call last):
  File "/home/pl752/text-generation-webui-1.8/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda/llama_cpp.py", line 70, in _load_shared_library
    return ctypes.CDLL(str(_lib_path), **cdll_args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pl752/text-generation-webui-1.8/installer_files/env/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libhipblas.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pl752/text-generation-webui-1.8/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda/__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "/home/pl752/text-generation-webui-1.8/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda/llama_cpp.py", line 83, in <module>
    _lib = _load_shared_library(_lib_base_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pl752/text-generation-webui-1.8/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda/llama_cpp.py", line 72, in _load_shared_library
    raise RuntimeError(f"Failed to load shared library '{_lib_path}': {e}")
RuntimeError: Failed to load shared library '/home/pl752/text-generation-webui-1.8/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda/libllama.so': libhipblas.so.1: cannot open shared object file: No such file or directory
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

load any model with llamacpp_hf on amdgpu

only cpu would be utilized

### Logs

```shell
llm_load_tensors: ggml ctx size =    0.15 MiB
llm_load_tensors:        CPU buffer size =  8137.64 MiB
..........
```

### System Info

```shell
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
x86_64 ryzen 9 5900x
128gb ram, nvme
radeon rx6900xt
```

**Comment by pl752** [comment]
Also libomp.so is missing

**Comment by sandbox404** [comment]
the same with me. Despite I choose AMD version during the install, 1.8 cannot use amdgpu, it just run on CPU. I'm rolling back to snapshot-2024-04-28.

**Comment by My1** [comment]
similar things here, what is it even trying with CUDA, last time I checked CUDA is nvidia's territory.
<details><summary>Error</summary>

```
15:52:45-621600 INFO     Loading "Gemma-2-9B-It-SPPO-Iter3-Q5_K_M.gguf"                               
15:52:45-994893 INFO     llama.cpp weights detected: "models/Gemma-2-9B-It-SPPO-Iter3-Q5_K_M.gguf"    
15:52:45-998363 ERROR    Failed to load the model.                                                    
Traceback (most recent call last):
  File "/home/my1/_ki/text-generation-webui/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda/llama_cpp.py", line 75, in _load_shared_library
    return ctypes.CDLL(str(_lib_path), **cdll_args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my1/_ki/text-generation-webui/installer_files/env/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libomp.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my1/_ki/text-generation-webui/modules/ui_model_menu.py", line 248, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my1/_ki/text-generation-webui/modules/models.py", line 94, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my1/_ki/text-generation-webui/modules/models.py", line 275, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my1/_ki/text-generation-webui/modules/llamacpp_model.py", line 38, in from_pretrained
    Llama = llama_cpp_lib().Llama
            ^^^^^^^^^^^^^^^
  File "/home/my1/_ki/text-generation-webui/modules/llama_cpp_python_hijack.py", line 42, in llama_cpp_lib
    return_lib = importlib.import_module(lib_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my1/_ki/text-generation-webui/installer_files/env/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/my1/_ki/text-generation-webui/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda/__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "/home/my1/_ki/text-generation-webui/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda/llama_cpp.py", line 88, in <module>
    _lib = _load_shared_library(_lib_base_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my1/_ki/text-generation-webui/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda/llama_cpp.py", line 77, in _load_shared_library
    raise RuntimeError(f"Failed to load shared library '{_lib_path}': {e}")
RuntimeError: Failed to load shared library '/home/my1/_ki/text-generation-webui/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda/lib/libllama.so': libomp.so: cannot open shared object file: No such file or directory
```

</details>

**Comment by matoro** [comment]
This is still broken on master.

**Comment by Moyu010** [comment]
Same issue. Libomp.so is missing.

**Comment by qskousen** [comment]
This still needs to be fixed in the repo, but I was able to get around `libomp.so` missing on my Debian based distro by installing `libomp-15-dev` and then copying the `.so` file to the Conda env. Simply installing the library was not enough, it seemed unable to find the `.so` file without the copy. This is a pretty hacky workaround.

Starting inside `text-generation-webui` directory:

```
sudo apt install libomp-15-dev
cp /usr/lib/llvm-15/lib/libomp.so.5 installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda/lib/libomp.so
```

**Comment by HardAndHeavy** [comment]
Encountered this error. I created a [Dockerfile](https://github.com/oobabooga/text-generation-webui/blob/main/docker/amd/Dockerfile) according to the suggested instructions with the installation of libraries via a file start_linux.sh . Analyzing the code, I came to the conclusion that this line of code ["('tensorcores', llama_cpp_cuda_tensorcores')"](https://github.com/oobabooga/text-generation-webui/blob/main/modules/llama_cpp_python_hijack.py#L29) interferes. After commenting on it, I was able to upload the model. 

Then I rewrote the container assembly in my own way. And everything worked without errors.

As a result, I think that it is necessary to either change the code in the module. llama_cpp_python_hijack.py , or change the code in the file requirements_amd.txt .

[I went my own way](https://github.com/HardAndHeavy/text-generation-webui-rocm-docker/blob/main/Dockerfile) and started from the file requirements_cpu_only.txt and added an llama installation for amd.

**Comment by user414** [comment]
Just want to add more info for those coming on this issue. Didn't want to use a docker so went with the instruction here

https://github.com/oobabooga/text-generation-webui/issues/7326

to recompile llama.cpp. It did not work out of the box anymore, installed the full rocm 7.2.0 and needed to add the prefix "-DCMAKE_PREFIX_PATH=/opt/rocm-7.2.0" to the build command.

There was another problem somewhere in the script, there's many other LLVM version on the system and it seems somewhere in the llama.cpp build scripts it's not taking into account a system with multiple LLVM version so there was countless errors. It could also be an issue with an older LLVM installation, will likely install the latest stable LLVM 21, since rocm 7.2 comes with version 22, and see if it works then. In the end removing all LLVM versions on the system beside the one in rocm was the only way it would compile for now.
