### ISSUE TITLE
GPTQ-for-LLaMa doesn't seem to work with more than one GPU

### ISSUE THREAD

**Issue by quarterturn** [oobabooga/text-generation-webui#617]
### Describe the bug

```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 22.00 MiB (GPU 0; 15.89 GiB total capacity; 15.12 GiB already allocated; 18.12 MiB free; 15.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
i$ git show
commit cac577d99f3ebf864ec8d4701211ec94cf32c4fa (HEAD -> main, origin/main, origin/HEAD)
Author: oobabooga <112222186+oobabooga@users.noreply.github.com>
Date:   Tue Mar 28 13:25:58 2023 -0300

    Fix interface reloading

diff --git a/server.py b/server.py
index 4d9ee5e..6023451 100644
--- a/server.py
+++ b/server.py
@@ -494,7 +494,7 @@ def create_interface():
             shared.gradio['reset_interface'] = gr.Button("Apply and restart the interface", type="primary")

             shared.gradio['reset_interface'].click(set_interface_arguments, [shared.gradio[k] for k in ['interface_modes_menu', 'extensions_menu', 'cmd_arguments_menu']], None)
-            shared.gradio['reset_interface'].click(lambda : None, None, None, _js='() => {document.body.innerHTML=\'<h1 style="font-family:monospace;margin-top:20%;color:lightgray;text-align:center;">Reloading...</h1>\'; setTimeout(function(){location.reload()},2500)}')
+            shared.gradio['reset_interface'].click(lambda : None, None, None, _js='() => {document.body.innerHTML=\'<h1 style="font-family:monospace;margin-top:20%;color:lightgray;text-align:center;">Reloading...</h1>\'; setTimeout(function(){location.reload()},2500); return []}')

         if shared.args.extensions is not None:
             extensions_module.create_extensions_block()

```

command used:
```
python server.py --model llama-30b-4bit-128g  --auto-devices --gpu-memory 16 16  --chat --listen --wbits 4 --groupsize 128
```

### Logs

```shell
Traceback (most recent call last):
  File "/home/qtr/text-generation-webui/server.py", line 273, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/qtr/text-generation-webui/modules/models.py", line 101, in load_model
    model = load_quantized(model_name)
  File "/home/qtr/text-generation-webui/modules/GPTQ_loader.py", line 92, in load_quantized
    model = accelerate.dispatch_model(model, device_map=device_map, offload_buffers=True)
  File "/home/qtr/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/big_modeling.py", line 370, in dispatch_model
    attach_align_device_hook_on_blocks(
  File "/home/qtr/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 502, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/home/qtr/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 502, in attach_align_device_hook_on_blocks    attach_align_device_hook_on_blocks(
  File "/home/qtr/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 502, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/home/qtr/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 478, in attach_align_device_hook_on_blocks
    add_hook_to_module(module, hook)
  File "/home/qtr/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 155, in add_hook_to_module
    module = hook.init_hook(module)
  File "/home/qtr/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 251, in init_hook
    set_module_tensor_to_device(module, name, self.execution_device)
  File "/home/qtr/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 147, in set_module_tensor_to_device
    new_value = old_value.to(device)
```
```


### System Info

```shell
Tue Mar 28 10:43:38 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla P100-PCIE-16GB            On | 00000000:05:00.0 Off |                    0 |
| N/A   32C    P0               26W / 250W|      0MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE-16GB            On | 00000000:42:00.0 Off |                    0 |
| N/A   34C    P0               26W / 250W|      0MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

```

```
vendor_id       : GenuineIntel
cpu family      : 6
model           : 62
model name      : Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz
stepping        : 4
microcode       : 0x42e
cpu MHz         : 3200.000
cache size      : 30720 KB
physical id     : 1
siblings        : 24
core id         : 13
cpu cores       : 12
apicid          : 59
initial apicid  : 59
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d
vmx flags       : vnmi preemption_timer posted_intr invvpid ept_x_only ept_1gb flexpriority apicv tsc_offset vtpr mtf vapic ept vpid unrestricted_guest vapic_reg vid ple
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_unknown
bogomips        : 4803.46
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```

```
$ free -h
               total        used        free      shared  buff/cache   available
Mem:           125Gi       2.0Gi        22Gi        32Mi       100Gi       122Gi
Swap:          8.0Gi        13Mi       8.0Gi
```
```

**Comment by generic-username0718** [comment]
try changing

`python server.py --model llama-30b-4bit-128g  --auto-devices --gpu-memory 16 16  --chat --listen --wbits 4 --groupsize 128`
to
`python server.py --model llama-30b-4bit-128g  --gpu-memory 10 16  --chat --listen --wbits 4 --groupsize 128`

monitor your realtime memory usage using `nvidia-smi dmon -s m`

I don't know why but you allocate more layers on GPU1 than GPU0 or it throws everything and the kitchen sink at it till it crashes... 

_just my experience_

**Comment by quarterturn** [comment]
Wow... that actually worked! Thanks!
