### ISSUE TITLE
FIX for SuperboogaV2 when trying to unload databases "Clear Data" not working crashing textgen

### ISSUE THREAD

**Issue by RandomInternetPreson** [oobabooga/text-generation-webui#6181]
### Describe the bug

There is an issue with textgen when trying to unload a superboogav2 database.  Creating a database works, but unloading does not.

To fix this the following changes need to be made:

1. In your start_YOUROS_.sh/bat file for me it is start_linux.sh (open this with a text editor) go to the bottom and add this line:
LINUX:
`export ALLOW_RESET=TRUE`

so it looks like this:
![image](https://github.com/oobabooga/text-generation-webui/assets/6488699/ff5faa0f-c35a-42b1-add5-eb34dbec1635)

if you are using Windows use this line: 

`set ALLOW_RESET=TRUE`

2.  Now open chromadb.py found in the extensions/superboogav2 folder

replace:

`    def _merge_infos(self, infos: list[Info]):
        merged_infos = []
        current_info = infos[0]

        for next_info in infos[1:]:
            merged = current_info.merge_with(next_info)
            if merged is not None:
                current_info = merged
            else:
                merged_infos.append(current_info)
                current_info = next_info

        merged_infos.append(current_info)
        return merged_infos`

with 

`    def _merge_infos(self, infos: list[Info]):
        if not infos:
            return []  # Return an empty list if there are no infos to merge
    
        merged_infos = []
        current_info = infos[0]
    
        for next_info in infos[1:]:
            merged = current_info.merge_with(next_info)
            if merged is not None:
                current_info = merged
            else:
                merged_infos.append(current_info)
                current_info = next_info
    
        merged_infos.append(current_info)
        return merged_infos`

and replace:

`    def clear(self):
        with self.lock:
            self.chroma_client.reset()

            self.ids = []
            self.chroma_client.delete_collection(name=self.name)
            self.collection = self.chroma_client.create_collection(name=self.name, embedding_function=embedder)

            logger.info('Successfully cleared all records and reset chromaDB.')`

with

`    def delete(self, ids_to_delete: list[str], where: dict):
        with self.lock:
            ids_to_delete = self.collection.get(ids=ids_to_delete, where=where)['ids']
            self.collection.delete(ids=ids_to_delete, where=where)

            # Remove the deleted ids from self.ids and self.id_to_info
            ids_set = set(ids_to_delete)
            self.ids = [id_ for id_ in self.ids if id_ not in ids_set]
            for id_ in ids_to_delete:
                self.id_to_info.pop(id_, None)

            logger.info(f'Successfully deleted {len(ids_to_delete)} records from chromaDB.')`

I couldn't get the formatting correct with the code, here is the entire edited file for v1.8:

https://github.com/RandomInternetPreson/MiscFiles/blob/main/chromadb_Edited.py

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Try making a db and then deleting it when in instruct mode, you will get an error.

### Logs

```shell
13:07:57-604756 INFO     Starting Text generation web UI                        
13:07:57-606622 INFO     Loading settings from "settings.yaml"                  

Running on local URL:  http://127.0.0.1:7860

Closing server running on port: 7860
13:08:14-140297 INFO     Loading the extension "superboogav2"                   
13:08:15-864617 DEBUG    Loading hyperparameters...                             

Running on local URL:  http://127.0.0.1:7860

13:08:24-558740 INFO     Adding 4 new embeddings.                               
Traceback (most recent call last):
  File "/home/myself/Desktop/OobV18/text-generation-webui-1.8/installer_files/env/lib/python3.11/site-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myself/Desktop/OobV18/text-generation-webui-1.8/installer_files/env/lib/python3.11/site-packages/gradio/route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myself/Desktop/OobV18/text-generation-webui-1.8/installer_files/env/lib/python3.11/site-packages/gradio/blocks.py", line 1786, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myself/Desktop/OobV18/text-generation-webui-1.8/installer_files/env/lib/python3.11/site-packages/gradio/blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myself/Desktop/OobV18/text-generation-webui-1.8/installer_files/env/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myself/Desktop/OobV18/text-generation-webui-1.8/installer_files/env/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/myself/Desktop/OobV18/text-generation-webui-1.8/installer_files/env/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myself/Desktop/OobV18/text-generation-webui-1.8/installer_files/env/lib/python3.11/site-packages/gradio/utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/home/myself/Desktop/OobV18/text-generation-webui-1.8/extensions/superboogav2/script.py", line 72, in _clear_data
    collector.clear()
  File "/home/myself/Desktop/OobV18/text-generation-webui-1.8/extensions/superboogav2/chromadb.py", line 338, in clear
    self.chroma_client.reset()
  File "/home/myself/Desktop/OobV18/text-generation-webui-1.8/installer_files/env/lib/python3.11/site-packages/chromadb/api/client.py", line 406, in reset
    return self._server.reset()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/myself/Desktop/OobV18/text-generation-webui-1.8/installer_files/env/lib/python3.11/site-packages/chromadb/api/segment.py", line 780, in reset
    self._system.reset_state()
  File "/home/myself/Desktop/OobV18/text-generation-webui-1.8/installer_files/env/lib/python3.11/site-packages/chromadb/config.py", line 415, in reset_state
    raise ValueError(
ValueError: Resetting is not allowed by this configuration (to enable it, set `allow_reset` to `True` in your Settings() or include `ALLOW_RESET=TRUE` in your environment variables)
```

### System Info

```shell
Ubuntu, Nvidia 4090
```

**Comment by SeanJKelly** [comment]
At the "replacement" step within chromadb.py. Do not replace the clear function, replace/add the delete function instead
