### ISSUE TITLE
Brand new installation of Oobabooga on Ubuntu -- Error message when loading EXL2 file (despite ample VRAM).

### ISSUE THREAD

**Issue by Kaszebe** [oobabooga/text-generation-webui#6186]
### Describe the bug

I'm getting the following error message in Terminal (Ubuntu 22.04) when loading an EXL2 file:

```
/home/computer/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/transformers/generation/configuration_utils.py:525: 

UserWarning: `do_sample` is set to `False`. However, `min_p` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `min_p`.
  warnings.warn(
```
I went into that file and had to have ChatGPT help me fix it. Of course, ChatGPT screwed up and nothing worked. 

I have 98GB of VRAM available (4090, 4080, 3090, 3090, 3080) on Ubuntu/SuperMicro/EPYC CPU. 

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

Brand new install of Oobabooga on Ubuntu 22.04.  

**gpu split**: 22,22,8,16,22
**max_seq_len**: 5632

Nothing else was checked.

### Logs

```shell
11:53:58-231487 INFO     Loading "LoneStriker_Llama-3-70B-Instruct-Gradient-262k-6.0bpw-h6-exl2"                                                       
/home/computer/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/transformers/generation/configuration_utils.py:525: UserWarning: `do_sample` is set to `False`. However, `min_p` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `min_p`.
  warnings.warn(
11:54:33-984961 ERROR    Failed to load the model.                                                                                                     
Traceback (most recent call last):
  File "/home/computer/text-generation-webui-main/modules/ui_model_menu.py", line 245, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/computer/text-generation-webui-main/modules/models.py", line 94, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/computer/text-generation-webui-main/modules/models.py", line 326, in ExLlamav2_HF_loader
    return Exllamav2HF.from_pretrained(model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/computer/text-generation-webui-main/modules/exllamav2_hf.py", line 181, in from_pretrained
    return Exllamav2HF(config)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/computer/text-generation-webui-main/modules/exllamav2_hf.py", line 50, in __init__
    self.ex_model.load(split)
  File "/home/computer/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/exllamav2/model.py", line 373, in load
    for item in f:
  File "/home/computer/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/exllamav2/model.py", line 401, in load_gen
    module.load()
  File "/home/computer/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/computer/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/exllamav2/mlp.py", line 112, in load
    self.up_proj.load()
  File "/home/computer/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/computer/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/exllamav2/linear.py", line 98, in load
    if w is None: w = self.load_weight()
                      ^^^^^^^^^^^^^^^^^^
  File "/home/computer/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/exllamav2/module.py", line 107, in load_weight
    qtensors = self.load_multi(key, ["q_weight", "q_invperm", "q_scale", "q_scale_max", "q_groups", "q_perm", "bias"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/computer/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/exllamav2/module.py", line 87, in load_multi
    tensors[k] = stfile.get_tensor(key + "." + k, device = self.device())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/computer/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/exllamav2/fasttensors.py", line 204, in get_tensor
    tensor = f.get_tensor(key)
             ^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 176.00 MiB. GPU 1 has a total capacity of 15.70 GiB of which 45.25 MiB is free. Process 2157 has 239.88 MiB memory in use. Including non-PyTorch memory, this process has 15.40 GiB memory in use. Of the allocated memory 15.03 GiB is allocated by PyTorch, and 108.25 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

### System Info

```shell
SuperMicro H12SSL-NT
AMD EPYC 7F52
(32GB) 16GB DDR4-3200 1Rx8 (16Gb) RDIMM
4090, 4080, 3090, 3090, 3080 
1600w PSU
850w PSU
4tb M.2 drive

12.1 CUDA
Nvidia server 535 (issue also happened on regular 535 driver).
```

**Comment by randoentity** [comment]
Try lowering the value of 16 (GPU 1, your 3080?) in your split. Use nvidia-smi to check how much you really have left.
