### ISSUE TITLE
[ERROR] Loading multiple parts of a GGUF model

### ISSUE THREAD

**Issue by JustifYI** [oobabooga/text-generation-webui#6187]
### Describe the bug

Just downloaded "**Tess-v2.5-Qwen2-72B.Q8_0.gguf.part1of2**" and "**Tess-v2.5-Qwen2-72B.Q8_0.gguf.part2of2**" from

https://huggingface.co/mradermacher/Tess-v2.5-Qwen2-72B-GGUF/tree/main

but when I try to load it with llama.cpp I get this error:

`04:22:30-779625 INFO     Loading "Tess-v2.5-Qwen2-72B-GGUF"
04:22:30-783123 ERROR    Failed to load the model.
Traceback (most recent call last):
  File "L:\ClosedAI\ChatGPT\oobabooga-windows\text-generation-webui\modules\ui_model_menu.py", line 245, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
  File "L:\ClosedAI\ChatGPT\oobabooga-windows\text-generation-webui\modules\models.py", line 94, in load_model
    output = load_func_map[loader](model_name)
  File "L:\ClosedAI\ChatGPT\oobabooga-windows\text-generation-webui\modules\models.py", line 269, in llamacpp_loader
    model_file = sorted(Path(f'{shared.args.model_dir}/{model_name}').glob('*.gguf'))[0]
IndexError: list index out of range`

How can I load these gguf models that are splitted in multiple parts?

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

Trying to load a GGUF model that is splitted, e.g. "Tess-v2.5-Qwen2-72B.Q8_0.gguf.part1of2" and "Tess-v2.5-Qwen2-72B.Q8_0.gguf.part2of2".

### Screenshot

![gguf-multiple-error-ooba](https://github.com/oobabooga/text-generation-webui/assets/47337816/356ff216-0781-4362-9165-5cee9bbe51e2)

### Logs

```shell
04:26:04-475260 INFO     Loading "Tess-v2.5-Qwen2-72B-GGUF"
04:26:04-480140 ERROR    Failed to load the model.
Traceback (most recent call last):
  File "L:\ClosedAI\ChatGPT\oobabooga-windows\text-generation-webui\modules\ui_model_menu.py", line 245, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
  File "L:\ClosedAI\ChatGPT\oobabooga-windows\text-generation-webui\modules\models.py", line 94, in load_model
    output = load_func_map[loader](model_name)
  File "L:\ClosedAI\ChatGPT\oobabooga-windows\text-generation-webui\modules\models.py", line 269, in llamacpp_loader
    model_file = sorted(Path(f'{shared.args.model_dir}/{model_name}').glob('*.gguf'))[0]
IndexError: list index out of range
```

### System Info

```shell
CPU: Intel i9-11900K
GPU: RTX 4090 (24GB VRAM)
RAM: 64GB DDR4
OS: Windows 11
```

**Comment by JustifYI** [comment]
Just managed (thanks to ChatGPT) to solve the issue. 
You have to **merge** the parts of the models with the `copy /b` command (on Windows). For me it was:

`copy /b Tess-v2.5-Qwen2-72B.Q8_0.gguf.part1of2 + Tess-v2.5-Qwen2-72B.Q8_0.gguf.part2of2 Tess-v2.5-Qwen2-72B.Q8_0.gguf`

So after the merge you will get only one **big** .gguf file that will normally loads.

_I don't understand why there is any guide about this on Reddit or GitHub... (at least I could not find anything on Google)_
