### ISSUE TITLE
Llama-cpp-python 0.2.81 'already loaded' fails to load models

### ISSUE THREAD

**Issue by Patronics** [oobabooga/text-generation-webui#6202]
### Describe the bug

Attempting to load a model after running the update-wizard-macos today (the version from a day or two ago worked fine) fails with the stack trace log included below. 

Notably, the error message references [this new issue in llama-cpp-python](https://github.com/abetlen/llama-cpp-python/issues/1575).

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

- Run the update wizard to update software.
- Attempt to load a gguf model using the GPU and llama.cpp
- Observe that loading fails.

### Screenshot

![Screenshot 2024-07-04 at 11 10 47 PM](https://github.com/oobabooga/text-generation-webui/assets/9359101/72148b05-8a43-4d2e-9fd5-7ba6fa57b317)

### Logs

```shell
Traceback (most recent call last):
  File "/Users/patrickleiser/Documents/Programming/AI/text-generation-webui/modules/ui_model_menu.py", line 246, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
  File "/Users/patrickleiser/Documents/Programming/AI/text-generation-webui/modules/models.py", line 94, in load_model
    output = load_func_map[loader](model_name)
  File "/Users/patrickleiser/Documents/Programming/AI/text-generation-webui/modules/models.py", line 275, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
  File "/Users/patrickleiser/Documents/Programming/AI/text-generation-webui/modules/llamacpp_model.py", line 39, in from_pretrained
    LlamaCache = llama_cpp_lib().LlamaCache
  File "/Users/patrickleiser/Documents/Programming/AI/text-generation-webui/modules/llama_cpp_python_hijack.py", line 38, in llama_cpp_lib
    raise Exception(f"Cannot import 'llama_cpp_cuda' because '{imported_module}' is already imported. See issue #1575 in llama-cpp-python. Please restart the server before attempting to use a different version of llama-cpp-python.")
Exception: Cannot import 'llama_cpp_cuda' because 'llama_cpp' is already imported. See issue #1575 in llama-cpp-python. Please restart the server before attempting to use a different version of llama-cpp-python.
```

### System Info

```shell
M1 Max Macbook Pro, MacOS 14.5
```

Edit: Just realized that Ooobabooga was the one that created that issue on the llama-cpp-python project, so I guess this error was already known. Sorry if this issue is therefore somewhat redundant

**Comment by gmarkley-VI** [comment]
I am seeing the same eception:
System Info
`M3 Max Macbook Pro, MacOS 14.5`

**Comment by danielw97** [comment]
I'm also experiencing the same issue, although on Debian in my case running in cpu mode.
If there's any troubleshooting that could help with this let me know.

**Comment by phr00t** [comment]
Same here. My GPU doesn't seem to be processing GGUFs at all. Oobabooga is broken as far as I'm concerned until this is fixed.

**Comment by danielw97** [comment]
I'm also experiencing this, although on Linux in my case.
If there's any testing or troubleshooting that can be done to try to  narrow this down let me know.

**Comment by poopro** [comment]
I think oobabooga is working with [abetlen](https://github.com/abetlen). for his solution, Currently it is no solution wait. Any idea if I user previous archive will make it work agin  ? Since the work also stopped for 4 days.

**Comment by dgamer0775** [comment]
> ### Describe the bug
> Attempting to load a model after running the update-wizard-macos today (the version from a day or two ago worked fine) fails with the stack trace log included below.
> 
> Notably, the error message references [this new issue in llama-cpp-python](https://github.com/abetlen/llama-cpp-python/issues/1575).
> 
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Reproduction
> * Run the update wizard to update software.
> * Attempt to load a gguf model using the GPU and llama.cpp
> * Observe that loading fails.
> 
> ### Screenshot
> ![Screenshot 2024-07-04 at 11 10 47 PM](https://private-user-images.githubusercontent.com/9359101/346022885-72148b05-8a43-4d2e-9fd5-7ba6fa57b317.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NDQ4MzQsIm5iZiI6MTcyMDU0NDUzNCwicGF0aCI6Ii85MzU5MTAxLzM0NjAyMjg4NS03MjE0OGIwNS04YTQzLTRkMmUtOWZkNS03YmE2ZmE1N2IzMTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMTcwMjE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTAyYmY4M2RjOTNlNGQ3ODNhYjk0ODAwNWQ0NWU1MjkwOWQ5ZmZjNTAxODU5YTZiOTU3YjE0ZTRmYjU1YWExNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D3CuyAHO3IPbPJVv6Pbf1-p20Xp_8S9hWXN5HQYrxaY)
> 
> ### Logs
> ```shell
> Traceback (most recent call last):
>   File "/Users/patrickleiser/Documents/Programming/AI/text-generation-webui/modules/ui_model_menu.py", line 246, in load_model_wrapper
>     shared.model, shared.tokenizer = load_model(selected_model, loader)
>   File "/Users/patrickleiser/Documents/Programming/AI/text-generation-webui/modules/models.py", line 94, in load_model
>     output = load_func_map[loader](model_name)
>   File "/Users/patrickleiser/Documents/Programming/AI/text-generation-webui/modules/models.py", line 275, in llamacpp_loader
>     model, tokenizer = LlamaCppModel.from_pretrained(model_file)
>   File "/Users/patrickleiser/Documents/Programming/AI/text-generation-webui/modules/llamacpp_model.py", line 39, in from_pretrained
>     LlamaCache = llama_cpp_lib().LlamaCache
>   File "/Users/patrickleiser/Documents/Programming/AI/text-generation-webui/modules/llama_cpp_python_hijack.py", line 38, in llama_cpp_lib
>     raise Exception(f"Cannot import 'llama_cpp_cuda' because '{imported_module}' is already imported. See issue #1575 in llama-cpp-python. Please restart the server before attempting to use a different version of llama-cpp-python.")
> Exception: Cannot import 'llama_cpp_cuda' because 'llama_cpp' is already imported. See issue #1575 in llama-cpp-python. Please restart the server before attempting to use a different version of llama-cpp-python.
> ```
> 
> ### System Info
> ```shell
> M1 Max Macbook Pro, MacOS 14.5
> ```
> 
> Edit: Just realized that Ooobabooga was the one that created that issue on the llama-cpp-python project, so I guess this error was already known. Sorry if this issue is therefore somewhat redundant

on oobabooga webui goto models page and select a model then scroll down and check on the cpu if its unchecked, click it and check it, your issue will be resolved and model successfully load,

**Comment by phr00t** [comment]
> 
> on oobabooga webui goto models page and select a model then scroll down and check on the cpu if its unchecked, click it and check it, your issue will be resolved and model successfully load,

... but I don't want to load and run my model just on my CPU.

**Comment by oobabooga** [comment]
You can try installing version 1.8 for now: https://github.com/oobabooga/text-generation-webui/releases/tag/v1.8

AMD and Mac seem to be having issues in the latest version of llama-cpp-python. I have no idea why. The compilation workflows can be found below. if someone can find what is wrong and send a PR, that would be helpful:

https://github.com/oobabooga/llama-cpp-python-cuBLAS-wheels/tree/main/.github/workflows

**Comment by Developer-42** [comment]
@oobabooga The problem is that `start_linux.sh` runs `one_click.py`, which updates the local repository to the latest version automatically.

**Comment by gavacq** [comment]
Likewise version 1.8 isn't working from me as is on my M2.

**Comment by SomeOddCodeGuy** [comment]
Adding to this- I am also using a Mac Studio. After installing 1.9, I am now getting 

```
text-generation-webui-1.9.1/modules/llama_cpp_python_hijack.py", line 48, in llama_cpp_lib

raise Exception(f"The {module_to_purpose(imported_module)} version of llama-cpp-python is already loaded. Switching to the default version currently requires a server restart.")
Exception: The CPU version of llama-cpp-python is already loaded. Switching to the default version currently requires a server restart.
```

I then found 1.10 was available, installed it and got that same error. I then attempted to use 1.8, and am now also getting the error with it (where 1.8 used to work before I installed 1.9.1)

I have attempted to restart Mac multiple times, but it made no difference. All versions of text-generation-webui now have this issue.

Checking the cpu box will cause the model to load; it is only when attempting to use gpu to load.

At the current moment, there is no longer any means that I can find to load a gguf with text-gen on my Mac. Neither changing to older versions nor restarting the Mac will get past this error.

Confirming that I installed text-gen using "bash start_macos.sh" and chose "C" for the GPU option.

**Comment by Tolkinz** [comment]
I am having same error. M2max 30gpu, 32gb ram. 
However, with CPU checked, it works and my system monitor util shows GPU is working, and response is very fast.

16:28:21-893239 INFO     Loading "dolphin-2.6-mistral-7b.Q4_K_M.gguf"           
16:28:21-926496 INFO     llama.cpp weights detected:                            
                         "models/dolphin-2.6-mistral-7b.Q4_K_M.gguf"            
llama_model_loader: loaded meta data with 24 key-value pairs and 291 tensors from models/dolphin-2.6-mistral-7b.Q4_K_M.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = cognitivecomputations_dolphin-2.6-mis...
llama_model_loader: - kv   2:                       llama.context_length u32              = 32768
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                       llama.rope.freq_base f32              = 10000.000000
llama_model_loader: - kv  11:                          general.file_type u32              = 15
llama_model_loader: - kv  12:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  13:                      tokenizer.ggml.tokens arr[str,32001]   = ["<unk>", "<s>", "<|im_end|>", "<0x00...
llama_model_loader: - kv  14:                      tokenizer.ggml.scores arr[f32,32001]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  15:                  tokenizer.ggml.token_type arr[i32,32001]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  16:                      tokenizer.ggml.merges arr[str,58980]   = ["▁ t", "i n", "e r", "▁ a", "h e...
llama_model_loader: - kv  17:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  18:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  19:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  20:            tokenizer.ggml.padding_token_id u32              = 2
llama_model_loader: - kv  21:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  22:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  23:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q4_K:  193 tensors
llama_model_loader: - type q6_K:   33 tensors
llm_load_vocab: special tokens cache size = 260
llm_load_vocab: token to piece cache size = 0.1637 MB
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32001
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: vocab_only       = 0
llm_load_print_meta: n_ctx_train      = 32768
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_swa            = 0
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_ctx_orig_yarn  = 32768
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = Q4_K - Medium
llm_load_print_meta: model params     = 7.24 B
llm_load_print_meta: model size       = 4.07 GiB (4.83 BPW) 
llm_load_print_meta: general.name     = cognitivecomputations_dolphin-2.6-mistral-7b
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '<|im_end|>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: PAD token        = 2 '<|im_end|>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_print_meta: EOT token        = 2 '<|im_end|>'
llm_load_print_meta: max token length = 48
llm_load_tensors: ggml ctx size =    0.27 MiB
ggml_backend_metal_log_allocated_size: allocated buffer, size =  4095.06 MiB, ( 4096.69 / 21845.34)
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
llm_load_tensors:        CPU buffer size =    70.31 MiB
llm_load_tensors:      Metal buffer size =  4095.06 MiB
................................................................................................
llama_new_context_with_model: n_ctx      = 32768
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
ggml_metal_init: allocating
ggml_metal_init: found device: Apple M2 Max
ggml_metal_init: picking default device: Apple M2 Max
ggml_metal_init: using embedded metal library
ggml_metal_init: GPU name:   Apple M2 Max
ggml_metal_init: GPU family: MTLGPUFamilyApple8  (1008)
ggml_metal_init: GPU family: MTLGPUFamilyCommon3 (3003)
ggml_metal_init: GPU family: MTLGPUFamilyMetal3  (5001)
ggml_metal_init: simdgroup reduction support   = true
ggml_metal_init: simdgroup matrix mul. support = true
ggml_metal_init: hasUnifiedMemory              = true
ggml_metal_init: recommendedMaxWorkingSetSize  = 22906.50 MB
llama_kv_cache_init:      Metal KV buffer size =  4096.00 MiB
llama_new_context_with_model: KV self size  = 4096.00 MiB, K (f16): 2048.00 MiB, V (f16): 2048.00 MiB
llama_new_context_with_model:        CPU  output buffer size =     0.12 MiB
llama_new_context_with_model:      Metal compute buffer size =  2144.00 MiB
llama_new_context_with_model:        CPU compute buffer size =    72.01 MiB
llama_new_context_with_model: graph nodes  = 1030
llama_new_context_with_model: graph splits = 2
AVX = 0 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 0 | NEON = 1 | SVE = 0 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 0 | 
Model metadata: {'general.quantization_version': '2', 'tokenizer.ggml.add_eos_token': 'false', 'tokenizer.ggml.add_bos_token': 'true', 'tokenizer.ggml.padding_token_id': '2', 'tokenizer.ggml.unknown_token_id': '0', 'tokenizer.ggml.eos_token_id': '2', 'tokenizer.ggml.bos_token_id': '1', 'tokenizer.ggml.model': 'llama', 'llama.attention.head_count_kv': '8', 'llama.context_length': '32768', 'llama.attention.head_count': '32', 'llama.rope.freq_base': '10000.000000', 'llama.rope.dimension_count': '128', 'general.file_type': '15', 'llama.feed_forward_length': '14336', 'llama.embedding_length': '4096', 'llama.block_count': '32', 'general.architecture': 'llama', 'llama.attention.layer_norm_rms_epsilon': '0.000010', 'general.name': 'cognitivecomputations_dolphin-2.6-mistral-7b'}
Using fallback chat format: llama-2
16:28:22-242138 INFO     Loaded "dolphin-2.6-mistral-7b.Q4_K_M.gguf" in 0.35    
                         seconds.                                               
16:28:22-242632 INFO     LOADER: "llama.cpp"                                    
16:28:22-242895 INFO     TRUNCATION LENGTH: 32768                               
16:28:22-243144 INFO     INSTRUCTION TEMPLATE: "ChatML"                         
                                                                                
llama_print_timings:        load time =    6603.23 ms
llama_print_timings:      sample time =     134.83 ms /   133 runs   (    1.01 ms per token,   986.41 tokens per second)
llama_print_timings: prompt eval time =    6602.41 ms /   115 tokens (   57.41 ms per token,    17.42 tokens per second)
llama_print_timings:        eval time =    2640.98 ms /   132 runs   (   20.01 ms per token,    49.98 tokens per second)
llama_print_timings:       total time =    9572.89 ms /   247 tokens
Output generated in 9.80 seconds (13.47 tokens/s, 132 tokens, context 133, seed 1923848845)

**Comment by Patronics** [comment]
> Any idea if I user previous archive will make it work again? 

For anyone that has a complete backup of their filesystem (or the relevant files to the oogabooga install anyway), this is a viable solution, this is what I ended up doing; rolling back to before I ran the update wizard. 

Before doing so, I tried installing previous versions of llama-cpp-python, but that didn't seem to solve the problem (iirc I tried versions back until 0.2.78). I wonder if there could be an underlying issue in llama.cpp that's causing the problem, rather than just in llama-cpp-python?

**Comment by SomeOddCodeGuy** [comment]
> You can try installing version 1.8 for now: https://github.com/oobabooga/text-generation-webui/releases/tag/v1.8
> 
> AMD and Mac seem to be having issues in the latest version of llama-cpp-python. I have no idea why. The compilation workflows can be found below. if someone can find what is wrong and send a PR, that would be helpful:
> 
> https://github.com/oobabooga/llama-cpp-python-cuBLAS-wheels/tree/main/.github/workflows

I started thinking about this issue, so over my lunchbreak I decided to try something.I specifically deleted and re-installed version 1.10. Tried to load a GGUF and confirmed that I got the same error. 

So then I cracked open the file Modules/llama_cpp_python_hijack.py, and I proceeded just wholesale delete the following lines from it:

- 29 && 30
- 38 and 39
- 47 and 48
- 56 and 57

https://github.com/oobabooga/text-generation-webui/blob/main/modules/llama_cpp_python_hijack.py

I reloaded text-gen and can now successfully load my Llama-3-70b gguf on my Mac again. I sent a prompt to it and it is responding acceptably.

I'm sure those checks you put in had a purpose, so I'm not recommending this as an official fix or anything; but for the Mac users who are currently stuck, this is an option for any who want to forcefully bypass the current break.

I have no idea why my test last night using version 1.8 failed (see previous comment); I don't have time to check atm, but I would think that version predates the change to this file. If it does, then I can only assume it was simply user error on my part when testing last night that 1.8 also failed.

**Comment by InvectorGator** [comment]
Pull request submitted with a fix!
https://github.com/oobabooga/text-generation-webui/pull/6227

I followed SomeOddCodeGuy's suggestion and made a small tweak to the llama_cpp_python_hijack.py file, particularly swapping the if statement blocks from lines 46 through 64 and adding one variable to the check. Macs were being caught in the second-to-last statement and encountering the error there.

I used a MacBook to replicate the error and confirm the fix, and was able to load an 8b test model without issue. I have not tried running it on any other machines yet.

**Comment by WrongFerret** [comment]
> > You can try installing version 1.8 for now: https://github.com/oobabooga/text-generation-webui/releases/tag/v1.8
> > AMD and Mac seem to be having issues in the latest version of llama-cpp-python. I have no idea why. The compilation workflows can be found below. if someone can find what is wrong and send a PR, that would be helpful:
> > https://github.com/oobabooga/llama-cpp-python-cuBLAS-wheels/tree/main/.github/workflows
> 
> I started thinking about this issue, so over my lunchbreak I decided to try something.I specifically deleted and re-installed version 1.10. Tried to load a GGUF and confirmed that I got the same error.
> 
> So then I cracked open the file Modules/llama_cpp_python_hijack.py, and I proceeded just wholesale delete the following lines from it:
> 
>     * 29 && 30
> 
>     * 38 and 39
> 
>     * 47 and 48
> 
>     * 56 and 57
> 
> 
> https://github.com/oobabooga/text-generation-webui/blob/main/modules/llama_cpp_python_hijack.py
> 
> I reloaded text-gen and can now successfully load my Llama-3-70b gguf on my Mac again. I sent a prompt to it and it is responding acceptably.
> 
> Deleting all of them was overkill; I'm fairly certain it was just line 48 that was catching it for the Mac. I'm neither tensorcors nor am I CPU, so I think there was just no hope for me on the mac side of passing that check. I'm sure those checks you put in had a purpose, so I'm not recommending this as an official fix or anything; but for the Mac users who are currently stuck, this is an option for any who want to forcefully bypass the current break.
> 
> I have no idea why my test last night using version 1.8 failed (see previous comment); I don't have time to check atm, but I would think that version predates the change to this file. If it does, then I can only assume it was simply user error on my part when testing last night that 1.8 also failed.

I tried commenting out lines 47 and 48 and that worked for me. I'm using an AMD card on Linux and this was a big help for getting my install fixed.

**Comment by ZhenyaPav** [comment]
@oobabooga For the record - the issue still persists on AMD, at least in my case - I had to install llama-cpp-python and exllama from scratch, as Arch is already on ROCm 6

**Comment by waheedi** [comment]
I have created a quick fix in this PR for AMD users here: https://github.com/oobabooga/text-generation-webui/pull/6315

**Comment by mega-ice** [comment]
I can confirm that loading a model to gpu now works.
(RX 7800xt, ubuntu, rocm 6.1.2)
