### ISSUE TITLE
Cannot run Gemma2 27B with transformers loader: RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by RandomInternetPreson** [oobabooga/text-generation-webui#6213]
### Describe the bug

I've downloaded Gemma2 from HF, both the fp32 and fp16 versions behave the same way:

https://huggingface.co/google/gemma-2-27b-it/tree/main

https://huggingface.co/google/gemma-2-27b

When trying to load via the transformers loader I get this error upon first inference (the model will load without error):

``RuntimeError: probability tensor contains either `inf`, `nan` or element < 0``

If I use the `Debug Deterministic` preset, I do not get this error and there are tokens being produced, but I cannot see them. 

If in addition to `Debug Deterministic` I also uncheck `Skip special tokens` in the `paramaters` tab, the model will only output `"<pad><pad><pad><pad><pad>"`until it reaches the max response length.

I did find this issue:

https://github.com/oobabooga/text-generation-webui/issues/6113

They were getting the same error but under different conditions.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Install V1.9.1 on Ubuntu and download the huggingface model at the link provided, and try to load gemma2 via transformers, then inference with the model.

### Screenshot

![Screenshot from 2024-07-07 10-30-45](https://github.com/oobabooga/text-generation-webui/assets/6488699/3aa02d90-361a-4ee2-a6be-8ebf543a6175)

### Logs

```shell
10:14:15-869810 INFO     Starting Text generation web UI                        

Running on local URL:  http://127.0.0.1:7860

10:14:37-033542 INFO     Loading "gemma-2-27b-it"                               
10:14:37-038025 INFO     TRANSFORMERS_PARAMS=                                   
{   'low_cpu_mem_usage': True,
    'torch_dtype': torch.float16,
    'attn_implementation': 'eager',
    'device_map': 'auto',
    'max_memory': {   0: '22000MiB',
                      1: '22000MiB',
                      2: '22000MiB',
                      3: '22000MiB',
                      4: '22000MiB',
                      5: '22000MiB',
                      6: '22000MiB',
                      'cpu': '99GiB'}}

/home/myself/Desktop/OobV191/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/generation/configuration_utils.py:550: UserWarning: `do_sample` is set to `False`. However, `min_p` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `min_p`.
  warnings.warn(
Loading checkpoint shards: 100%|████████████████| 12/12 [03:55<00:00, 19.62s/it]
10:18:33-599776 INFO     Loaded "gemma-2-27b-it" in 236.57 seconds.             
10:18:33-600709 INFO     LOADER: "Transformers"                                 
10:18:33-601344 INFO     TRUNCATION LENGTH: 8192                                
10:18:33-601808 INFO     INSTRUCTION TEMPLATE: "Custom (obtained from model     
                         metadata)"                                             
Traceback (most recent call last):
  File "/home/myself/Desktop/OobV191/text-generation-webui/modules/callbacks.py", line 61, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myself/Desktop/OobV191/text-generation-webui/modules/text_generation.py", line 393, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/myself/Desktop/OobV191/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/myself/Desktop/OobV191/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/generation/utils.py", line 1914, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "/home/myself/Desktop/OobV191/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/generation/utils.py", line 2693, in _sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
Output generated in 3.38 seconds (0.00 tokens/s, 0 tokens, context 68, seed 1852633438)



Then I load debug deterministic preset and try inferencing with that:

10:21:47-206613 INFO     "Debug-deterministic" preset:                          
{   'top_k': 1,
    'do_sample': False}
/home/myself/Desktop/OobV191/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/generation/configuration_utils.py:550: UserWarning: `do_sample` is set to `False`. However, `min_p` is set to `0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `min_p`.
  warnings.warn(
Output generated in 2.89 seconds (11.41 tokens/s, 33 tokens, context 68, seed 137908724)
```

### System Info

```shell
Ubuntu, nvidia, 4090
```

**Comment by RandomInternetPreson** [comment]
Solution: I needed to check "bf16" when loading the model.  

I figured this out from this comment:
https://github.com/meta-llama/llama/issues/380#issuecomment-1656714118
