### ISSUE TITLE
latest main branch can't load models ('int' object has no attribute 'lower')

### ISSUE THREAD

**Issue by thistleknot** [oobabooga/text-generation-webui#6218]
python server.py --api --listen --n-gpu-layers 32 --threads 8 --numa --tensorcores --trust-remote-code

```
(textgen) [root@pve-m7330 text-generation-webui]# python server.py --api --listen --n-gpu-layers 32 --threads 8 --numa --tensorcores --trust-remote-code
15:30:16-661436 INFO     Starting Text generation web UI
15:30:16-664477 WARNING  trust_remote_code is enabled. This is dangerous.
15:30:16-665181 WARNING
                         You are potentially exposing the web UI to the entire internet
                         without any access password.
                         You can create one with the "--gradio-auth" flag like this:

                         --gradio-auth username:password

                         Make sure to replace username:password with your own.
15:30:16-667018 INFO     Loading the extension "openai"
15:30:16-769921 INFO     OpenAI-compatible API URL:

                         http://0.0.0.0:5000


Running on local URL:  http://0.0.0.0:7860

15:30:32-162296 INFO     Loading "2048"
15:30:32-164229 ERROR    Failed to load the model.
Traceback (most recent call last):
  File "/home/user/text-generation-webui/modules/ui_model_menu.py", line 246, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
  File "/home/user/text-generation-webui/modules/models.py", line 83, in load_model
    metadata = get_model_metadata(model_name)
  File "/home/user/text-generation-webui/modules/models_settings.py", line 34, in get_model_metadata
    if re.match(pat.lower(), model.lower()):
AttributeError: 'int' object has no attribute 'lower'

Traceback (most recent call last):
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1782, in process_api
    inputs = await self.preprocess_data(
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1474, in preprocess_data
    self.validate_inputs(fn_index, inputs)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1454, in validate_inputs
    raise ValueError(
ValueError: An event handler (update_truncation_length) didn't receive enough input values (needed: 2, got: 1).
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [<gradio.components.slider.Slider object at 0x7fe4c81e8430>, <gradio.components.state.State object at 0x7fe4ffb33d00>]
Received inputs:
    ["Traceback (most recent call last):

  File "/home/user/text-generation-webui/modules/ui_model_menu.py", line 246, in load_model_wrapper

    shared.model, shared.tokenizer = load_model(selected_model, loader)

  File "/home/user/text-generation-webui/modules/models.py", line 83, in load_model

    metadata = get_model_metadata(model_name)

  File "/home/user/text-generation-webui/modules/models_settings.py", line 34, in get_model_metadata

    if re.match(pat.lower(), model.lower()):

AttributeError: 'int' object has no attribute 'lower'"]
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1782, in process_api
    inputs = await self.preprocess_data(
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1474, in preprocess_data
    self.validate_inputs(fn_index, inputs)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1454, in validate_inputs
    raise ValueError(
ValueError: An event handler (gather_interface_values) didn't receive enough input values (needed: 124, got: 1).
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [<gradio.components.slider.Slider object at 0x7fe4c8641ab0>, <gradio.components.checkbox.Checkbox object at 0x7fe4c8340dc0>, <gradio.components.slider.Slider object at 0x7fe4c81e9300>, <gradio.components.slider.Slider object at 0x7fe4c81e86a0>, <gradio.components.slider.Slider object at 0x7fe4c81e8730>, <gradio.components.number.Number object at 0x7fe4c81e9690>, <gradio.components.slider.Slider object at 0x7fe4c8641ed0>, <gradio.components.checkbox.Checkbox object at 0x7fe4c83be6e0>, <gradio.components.checkbox.Checkbox object at 0x7fe4c83bdb10>, <gradio.components.slider.Slider object at 0x7fe4c83bc610>, <gradio.components.slider.Slider object at 0x7fe4c83be140>, <gradio.components.slider.Slider object at 0x7fe4c83be1a0>, <gradio.components.slider.Slider object at 0x7fe4c83bd600>, <gradio.components.slider.Slider object at 0x7fe4c83bfd60>, <gradio.components.slider.Slider object at 0x7fe4c8641fc0>, <gradio.components.slider.Slider object at 0x7fe4c9585150>, <gradio.components.slider.Slider object at 0x7fe4c8641f00>, <gradio.components.slider.Slider object at 0x7fe4c8641f30>, <gradio.components.slider.Slider object at 0x7fe4c83be440>, <gradio.components.slider.Slider object at 0x7fe4c83be4a0>, <gradio.components.slider.Slider object at 0x7fe4c8616710>, <gradio.components.slider.Slider object at 0x7fe4c859ebc0>, <gradio.components.slider.Slider object at 0x7fe4c8616620>, <gradio.components.slider.Slider object at 0x7fe4c8642410>, <gradio.components.slider.Slider object at 0x7fe4c81e9360>, <gradio.components.slider.Slider object at 0x7fe4c81e9330>, <gradio.components.slider.Slider object at 0x7fe4c86424d0>, <gradio.components.slider.Slider object at 0x7fe4c831b910>, <gradio.components.slider.Slider object at 0x7fe4c832b3d0>, <gradio.components.textbox.Textbox object at 0x7fe4c832b400>, <gradio.components.checkbox.Checkbox object at 0x7fe4c8641600>, <gradio.components.slider.Slider object at 0x7fe4c83bfb20>, <gradio.components.slider.Slider object at 0x7fe4c83bf040>, <gradio.components.slider.Slider object at 0x7fe4c83beb90>, <gradio.components.slider.Slider object at 0x7fe4c83bd810>, <gradio.components.textbox.Textbox object at 0x7fe4c83bfe20>, <gradio.components.textbox.Textbox object at 0x7fe4c83bfa90>, <gradio.components.slider.Slider object at 0x7fe4c83bd660>, <gradio.components.checkbox.Checkbox object at 0x7fe4c83bd270>, <gradio.components.checkbox.Checkbox object at 0x7fe4c8341780>, <gradio.components.textbox.Textbox object at 0x7fe4c83bf010>, <gradio.components.textbox.Textbox object at 0x7fe4c83bd570>, <gradio.components.slider.Slider object at 0x7fe4c81e8430>, <gradio.components.textbox.Textbox object at 0x7fe4c83bd930>, <gradio.components.checkbox.Checkbox object at 0x7fe4c81e96c0>, <gradio.components.checkbox.Checkbox object at 0x7fe4c81e87c0>, <gradio.components.slider.Slider object at 0x7fe4c83bc880>, <gradio.components.slider.Slider object at 0x7fe4c83bee30>, <gradio.components.textbox.Textbox object at 0x7fe4c859e320>, <gradio.components.textbox.Textbox object at 0x7fe4c859f640>, <gradio.components.dropdown.Dropdown object at 0x7fe4c81e8370>, <gradio.components.json_component.JSON object at 0x7fe4ffbec820>, <gradio.components.textbox.Textbox object at 0x7fe4c81e9a50>, <gradio.components.textbox.Textbox object at 0x7fe4c81e9e40>, <gradio.components.textbox.Textbox object at 0x7fe4c81e9ba0>, <gradio.components.textbox.Textbox object at 0x7fe4c81e9b40>, <gradio.components.textbox.Textbox object at 0x7fe4c81e9c00>, <gradio.components.radio.Radio object at 0x7fe4c859f6d0>, <gradio.components.textbox.Textbox object at 0x7fe4c81ea2c0>, <gradio.components.textbox.Textbox object at 0x7fe4c81ea260>, <gradio.components.textbox.Textbox object at 0x7fe4c81ea0b0>, <gradio.components.dropdown.Dropdown object at 0x7fe4c859f4f0>, <gradio.components.textbox.Textbox object at 0x7fe4c859e020>, <gradio.components.textbox.Textbox object at 0x7fe4c86166e0>, <gradio.components.textbox.Textbox object at 0x7fe4c859e2f0>, <gradio.components.textbox.Textbox object at 0x7fe4c859e440>, <gradio.components.dropdown.Dropdown object at 0x7fe4c859ebf0>, <gradio.components.dropdown.Dropdown object at 0x7fe4c8640e80>, <gradio.components.dropdown.Dropdown object at 0x7fe4c81eaa10>, <gradio.components.dropdown.Dropdown object at 0x7fe4c8641ff0>, <gradio.components.slider.Slider object at 0x7fe4c8107a60>, <gradio.components.checkbox.Checkbox object at 0x7fe4c1693f10>, <gradio.components.checkbox.Checkbox object at 0x7fe4c1692f20>, <gradio.components.checkbox.Checkbox object at 0x7fe4c1690c70>, <gradio.components.checkbox.Checkbox object at 0x7fe4c1693cd0>, <gradio.components.checkbox.Checkbox object at 0x7fe4c1682500>, <gradio.components.checkbox.Checkbox object at 0x7fe4c151cd00>, <gradio.components.checkbox.Checkbox object at 0x7fe4c151cd30>, <gradio.components.checkbox.Checkbox object at 0x7fe4c1690220>, <gradio.components.checkbox.Checkbox object at 0x7fe4c1691900>, <gradio.components.checkbox.Checkbox object at 0x7fe4c1693490>, <gradio.components.dropdown.Dropdown object at 0x7fe4c81beb90>, <gradio.components.dropdown.Dropdown object at 0x7fe4c17160e0>, <gradio.components.checkbox.Checkbox object at 0x7fe4c1691810>, <gradio.components.dropdown.Dropdown object at 0x7fe4c179eb60>, <gradio.components.dropdown.Dropdown object at 0x7fe4c179ee90>, <gradio.components.checkbox.Checkbox object at 0x7fe4c16ba230>, <gradio.components.checkbox.Checkbox object at 0x7fe4c16ba140>, <gradio.components.checkbox.Checkbox object at 0x7fe4c16b8430>, <gradio.components.checkbox.Checkbox object at 0x7fe4c16ba170>, <gradio.components.checkbox.Checkbox object at 0x7fe4c16ba110>, <gradio.components.checkbox.Checkbox object at 0x7fe4c17e5390>, <gradio.components.checkbox.Checkbox object at 0x7fe4c16459c0>, <gradio.components.checkbox.Checkbox object at 0x7fe4c1693bb0>, <gradio.components.checkbox.Checkbox object at 0x7fe4c1693d90>, <gradio.components.number.Number object at 0x7fe4c1693c40>, <gradio.components.checkbox.Checkbox object at 0x7fe4c1692110>, <gradio.components.checkbox.Checkbox object at 0x7fe4c1691d80>, <gradio.components.checkbox.Checkbox object at 0x7fe4c1693d00>, <gradio.components.slider.Slider object at 0x7fe4c1785690>, <gradio.components.slider.Slider object at 0x7fe4c1785240>, <gradio.components.slider.Slider object at 0x7fe4c1784bb0>, <gradio.components.checkbox.Checkbox object at 0x7fe4c16ba320>, <gradio.components.checkbox.Checkbox object at 0x7fe4c16ba260>, <gradio.components.checkbox.Checkbox object at 0x7fe4c16ba200>, <gradio.components.slider.Slider object at 0x7fe4c17849a0>, <gradio.components.textbox.Textbox object at 0x7fe4c1786620>, <gradio.components.slider.Slider object at 0x7fe4c1787580>, <gradio.components.textbox.Textbox object at 0x7fe4c179f610>, <gradio.components.slider.Slider object at 0x7fe4c179c8e0>, <gradio.components.slider.Slider object at 0x7fe4c17e4a00>, <gradio.components.slider.Slider object at 0x7fe4c179c5e0>, <gradio.components.slider.Slider object at 0x7fe4c1609270>, <gradio.components.checkbox.Checkbox object at 0x7fe4c16b83a0>, <gradio.components.checkbox.Checkbox object at 0x7fe4c151d8d0>, <gradio.components.checkbox.Checkbox object at 0x7fe4c16ba1d0>, <gradio.components.checkbox.Checkbox object at 0x7fe4c16ba1a0>, <gradio.components.checkbox.Checkbox object at 0x7fe4c16924a0>, <gradio.components.checkbox.Checkbox object at 0x7fe4c16900d0>, <gradio.components.checkbox.Checkbox object at 0x7fe4c1693ee0>, <gradio.components.number.Number object at 0x7fe4c16934c0>, <gradio.components.dropdown.Dropdown object at 0x7fe4c174fdf0>, <gradio.components.checkbox.Checkbox object at 0x7fe4c1693c70>, <gradio.components.slider.Slider object at 0x7fe4c81eb970>]
Received inputs:
    ["llama.cpp"]

```

### Describe the bug

can't load models

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

git pull on 2024-07-08
pip install -r requirements.txt

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/5154106/89247b34-39dc-4fc5-8790-a0bd1a91e4ea)

### Logs

```shell
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [<gradio.components.slider.Slider object at 0x7fe9f7c35c00>, <gradio.components.checkbox.Checkbox object at 0x7fe9f79baf20>, <gradio.components.slider.Slider object at 0x7fe9f57e8580>, <gradio.components.slider.Slider object at 0x7fe9f57e8430>, <gradio.components.slider.Slider object at 0x7fe9f57e8490>, <gradio.components.number.Number object at 0x7fe9f57e85b0>, <gradio.components.slider.Slider object at 0x7fe9f9380700>, <gradio.components.checkbox.Checkbox object at 0x7fe9f79ba830>, <gradio.components.checkbox.Checkbox object at 0x7fe9f79b83a0>, <gradio.components.slider.Slider object at 0x7fe9f79ba380>, <gradio.components.slider.Slider object at 0x7fe9f79bbe50>, <gradio.components.slider.Slider object at 0x7fe9f79ba4a0>, <gradio.components.slider.Slider object at 0x7fe9f79bbac0>, <gradio.components.slider.Slider object at 0x7fe9f79bb5b0>, <gradio.components.slider.Slider object at 0x7fe9f7c023e0>, <gradio.components.slider.Slider object at 0x7fe9f7b960e0>, <gradio.components.slider.Slider object at 0x7fe9f7c02320>, <gradio.components.slider.Slider object at 0x7fe9f7c36140>, <gradio.components.slider.Slider object at 0x7fe9f79bab60>, <gradio.components.slider.Slider object at 0x7fe9f79bad40>, <gradio.components.slider.Slider object at 0x7fe9f7c35540>, <gradio.components.slider.Slider object at 0x7fe9f7c361a0>, <gradio.components.slider.Slider object at 0x7fe9f7c362c0>, <gradio.components.slider.Slider object at 0x7fe9f7c362f0>, <gradio.components.slider.Slider object at 0x7fe9f57e9150>, <gradio.components.slider.Slider object at 0x7fe9f57e9120>, <gradio.components.slider.Slider object at 0x7fe9f7c36230>, <gradio.components.slider.Slider object at 0x7fe9f7913280>, <gradio.components.slider.Slider object at 0x7fe9f79131f0>, <gradio.components.textbox.Textbox object at 0x7fe9f7913100>, <gradio.components.checkbox.Checkbox object at 0x7fe9f7c35ff0>, <gradio.components.slider.Slider object at 0x7fe9f79b8550>, <gradio.components.slider.Slider object at 0x7fe9f79ada80>, <gradio.components.slider.Slider object at 0x7fe9f79b9540>, <gradio.components.slider.Slider object at 0x7fe9f79bb0d0>, <gradio.components.textbox.Textbox object at 0x7fe9f79bb5e0>, <gradio.components.textbox.Textbox object at 0x7fe9f79acc10>, <gradio.components.slider.Slider object at 0x7fe9f79badd0>, <gradio.components.checkbox.Checkbox object at 0x7fe9f79ba920>, <gradio.components.checkbox.Checkbox object at 0x7fe9f79b9630>, <gradio.components.textbox.Textbox object at 0x7fe9f79bae60>, <gradio.components.textbox.Textbox object at 0x7fe9f79bbeb0>, <gradio.components.slider.Slider object at 0x7fe9f79bba60>, <gradio.components.textbox.Textbox object at 0x7fe9f79baef0>, <gradio.components.checkbox.Checkbox object at 0x7fe9f57e8520>, <gradio.components.checkbox.Checkbox object at 0x7fe9f57e85e0>, <gradio.components.slider.Slider object at 0x7fe9f79bbaf0>, <gradio.components.slider.Slider object at 0x7fe9f79bb310>, <gradio.components.textbox.Textbox object at 0x7fe9f7b97790>, <gradio.components.textbox.Textbox object at 0x7fe9f7b97340>, <gradio.components.dropdown.Dropdown object at 0x7fe9f57e83d0>, <gradio.components.json_component.JSON object at 0x7fe9f7b96d10>, <gradio.components.textbox.Textbox object at 0x7fe9f57e9ab0>, <gradio.components.textbox.Textbox object at 0x7fe9f57e9b40>, <gradio.components.textbox.Textbox object at 0x7fe9f57e9810>, <gradio.components.textbox.Textbox object at 0x7fe9f57e97b0>, <gradio.components.textbox.Textbox object at 0x7fe9f57e9870>, <gradio.components.radio.Radio object at 0x7fe9f7b96f80>, <gradio.components.textbox.Textbox object at 0x7fe9f57e9f30>, <gradio.components.textbox.Textbox object at 0x7fe9f57e9ed0>, <gradio.components.textbox.Textbox object at 0x7fe9f57e9d20>, <gradio.components.dropdown.Dropdown object at 0x7fe9f7b96500>, <gradio.components.textbox.Textbox object at 0x7fe9f7b96620>, <gradio.components.textbox.Textbox object at 0x7fe9f7c02d10>, <gradio.components.textbox.Textbox object at 0x7fe9f7b96a10>, <gradio.components.textbox.Textbox object at 0x7fe9f7bf0c10>, <gradio.components.dropdown.Dropdown object at 0x7fe9f7b97d90>, <gradio.components.dropdown.Dropdown object at 0x7fe9f7c34eb0>, <gradio.components.dropdown.Dropdown object at 0x7fe9f57ea260>, <gradio.components.dropdown.Dropdown object at 0x7fe9f7c35cc0>, <gradio.components.slider.Slider object at 0x7fe9f5707d90>, <gradio.components.checkbox.Checkbox object at 0x7fe9f556fca0>, <gradio.components.checkbox.Checkbox object at 0x7fe9f556f9d0>, <gradio.components.checkbox.Checkbox object at 0x7fe9f556c820>, <gradio.components.checkbox.Checkbox object at 0x7fe9f556fb20>, <gradio.components.checkbox.Checkbox object at 0x7fe9f555ddb0>, <gradio.components.checkbox.Checkbox object at 0x7fe9f55bedd0>, <gradio.components.checkbox.Checkbox object at 0x7fe9f53f8a90>, <gradio.components.checkbox.Checkbox object at 0x7fe9f556f250>, <gradio.components.checkbox.Checkbox object at 0x7fe9f556d690>, <gradio.components.checkbox.Checkbox object at 0x7fe9f555e3e0>, <gradio.components.dropdown.Dropdown object at 0x7fe9f57b4f40>, <gradio.components.dropdown.Dropdown object at 0x7fe9f55f1e70>, <gradio.components.checkbox.Checkbox object at 0x7fe9f556d5a0>, <gradio.components.dropdown.Dropdown object at 0x7fe9f56752d0>, <gradio.components.dropdown.Dropdown object at 0x7fe9f565d270>, <gradio.components.checkbox.Checkbox object at 0x7fe9f5595fc0>, <gradio.components.checkbox.Checkbox object at 0x7fe9f5595ed0>, <gradio.components.checkbox.Checkbox object at 0x7fe9f5594ac0>, <gradio.components.checkbox.Checkbox object at 0x7fe9f5595f00>, <gradio.components.checkbox.Checkbox object at 0x7fe9f5595ea0>, <gradio.components.checkbox.Checkbox object at 0x7fe9f56c1180>, <gradio.components.checkbox.Checkbox object at 0x7fe9f5521ba0>, <gradio.components.checkbox.Checkbox object at 0x7fe9f556eb90>, <gradio.components.checkbox.Checkbox object at 0x7fe9f556f940>, <gradio.components.number.Number object at 0x7fe9f556fa60>, <gradio.components.checkbox.Checkbox object at 0x7fe9f556e0e0>, <gradio.components.checkbox.Checkbox object at 0x7fe9f556db10>, <gradio.components.checkbox.Checkbox object at 0x7fe9f556fee0>, <gradio.components.slider.Slider object at 0x7fe9f5675d80>, <gradio.components.slider.Slider object at 0x7fe9f5674100>, <gradio.components.slider.Slider object at 0x7fe9f5674160>, <gradio.components.checkbox.Checkbox object at 0x7fe9f55960b0>, <gradio.components.checkbox.Checkbox object at 0x7fe9f5595ff0>, <gradio.components.checkbox.Checkbox object at 0x7fe9f5595f90>, <gradio.components.slider.Slider object at 0x7fe9f5674b80>, <gradio.components.textbox.Textbox object at 0x7fe9f56773a0>, <gradio.components.slider.Slider object at 0x7fe9f5676bf0>, <gradio.components.textbox.Textbox object at 0x7fe9f5674370>, <gradio.components.slider.Slider object at 0x7fe9f56741c0>, <gradio.components.slider.Slider object at 0x7fe9f56c1660>, <gradio.components.slider.Slider object at 0x7fe9f5674340>, <gradio.components.slider.Slider object at 0x7fe9f54e1000>, <gradio.components.checkbox.Checkbox object at 0x7fe9f55941c0>, <gradio.components.checkbox.Checkbox object at 0x7fe9f53f9030>, <gradio.components.checkbox.Checkbox object at 0x7fe9f5595f60>, <gradio.components.checkbox.Checkbox object at 0x7fe9f5595f30>, <gradio.components.checkbox.Checkbox object at 0x7fe9f556dea0>, <gradio.components.checkbox.Checkbox object at 0x7fe9f556ca00>, <gradio.components.checkbox.Checkbox object at 0x7fe9f556fc70>, <gradio.components.number.Number object at 0x7fe9f556f220>, <gradio.components.dropdown.Dropdown object at 0x7fe9f5627b80>, <gradio.components.checkbox.Checkbox object at 0x7fe9f556fa00>, <gradio.components.slider.Slider object at 0x7fe9f5894be0>]
Received inputs:
    [8192, 1]
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1786, in process_api
    result = await self.call_function(
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
  File "/home/user/text-generation-webui/modules/models_settings.py", line 228, in update_model_parameters
    value = int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

### System Info

```shell
rocky linux 9
python 3.10
```

**Comment by thistleknot** [comment]
branch that still works for me

git checkout 2f71515c
