### ISSUE TITLE
TypeError: Offload_LlamaModel.forward() got an unexpected keyword argument 'position_ids' after today's commits

### ISSUE THREAD

**Issue by ye7iaserag** [oobabooga/text-generation-webui#623]
### Describe the bug

Crash on first inference when running llama with gptq latest 128 groupsize models, was working till yesterday
Pulled latest code today on both webui and gptq repo and it's crashing

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

- Pull latest commit
- Pull latest commit in `cuda` branch in llama-gptq repo
- Use this `python server.py --wbits 4 --groupsize 128 --pre_layer 2 --model llama-65b-4bit-128g --cai-chat --listen --listen-port=8888` to load llama 65b 4bit 128 group size
- The model loads normally and the UI starts
- Send any message and click generate then error

### Logs

```shell
Traceback (most recent call last):
   File "/app/modules/callbacks.py", line 64, in gentask
     ret = self.mfunc(callback=_callback, **self.kwargs)
   File "/app/modules/text_generation.py", line 222, in generate_with_callback
     shared.model.generate(**kwargs)
   File "/usr/local/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
     return func(*args, **kwargs)
   File "/usr/local/lib/python3.10/site-packages/transformers/generation/utils.py", line 1462, in generate
     return self.sample(
   File "/usr/local/lib/python3.10/site-packages/transformers/generation/utils.py", line 2478, in sample
     outputs = self(
   File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
     return forward_call(*input, **kwargs)
   File "/usr/local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 710, in forward
     outputs = self.model(
   File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
     return forward_call(*input, **kwargs)
 TypeError: Offload_LlamaModel.forward() got an unexpected keyword argument 'position_ids'
```

### System Info

```shell
docker over wsl2
```

**Comment by oobabooga** [comment]
Seems like an upstream issue in https://github.com/qwopqwop200/GPTQ-for-LLaMa

**Comment by ye7iaserag** [comment]
Fixed in https://github.com/qwopqwop200/GPTQ-for-LLaMa/commit/a7143402398ba688fb2f8f6429ee1e6b476b6720
Closing
