### ISSUE TITLE
V1.10.1 commit 0315122cf07409b601511cae2323d8b2b63bcde7 refuses to load model working previously.

### ISSUE THREAD

**Issue by sztejkat** [oobabooga/text-generation-webui#6248]
### Describe the bug

After an upgrade/clean install attempt to load model in "llama.cpp"  in CPU-only configuration system fails with log message below. Restarting it doesn't help. 

Note: possibly duplicate of #6222, however #6222 has status "closed" while it still remains as an stopping problem.

Tried to do regression check by cleaning up entire folder, git checkout, start_linux.sh, selecting N, selecting model, load model.

Regression:
v1.10.1 - fails (see log)
v1.10 - fails (see log)
v1.9 - fails with the same log as v1.10.1, except a bit information about an issue related to fix.
v1.8 - works

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

clone, 
start_linux.sh,
select CPU-only, wait...
throw in your model
Start web-ui in browser
reload models list.
Select model (which previously worked without problems)
Load

Observe errors.

### Logs

```shell
v1.10.1:
  17:24:30-698318 INFO     Loading "Noromaid-v0.1-mixtral-8x7b-Instruct-v3.q8_0.gguf"                                                               
  17:24:30-721017 INFO     llama.cpp weights detected: "models/Noromaid-v0.1-mixtral-8x7b-Instruct-v3.q8_0.gguf"                                    
  17:24:30-729975 ERROR    Failed to load the model.                                                                                                
  Traceback (most recent call last):
    File "/home/sztejkat/ai/llama2/soft/oobaboga-cpu/modules/ui_model_menu.py", line 248, in load_model_wrapper
      shared.model, shared.tokenizer = load_model(selected_model, loader)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/sztejkat/ai/llama2/soft/oobaboga-cpu/modules/models.py", line 94, in load_model
      output = load_func_map[loader](model_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/sztejkat/ai/llama2/soft/oobaboga-cpu/modules/models.py", line 275, in llamacpp_loader
      model, tokenizer = LlamaCppModel.from_pretrained(model_file)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/sztejkat/ai/llama2/soft/oobaboga-cpu/modules/llamacpp_model.py", line 39, in from_pretrained
      LlamaCache = llama_cpp_lib().LlamaCache
                   ^^^^^^^^^^^^^^^
    File "/home/sztejkat/ai/llama2/soft/oobaboga-cpu/modules/llama_cpp_python_hijack.py", line 39, in llama_cpp_lib
      raise Exception(f"Cannot import `{lib_name}` because `{imported_module}` is already imported. Switching to a different version of llama-cpp-python currently requires a server restart.")
  Exception: Cannot import `llama_cpp_cuda` because `llama_cpp` is already imported. Switching to a different version of llama-cpp-python currently requires a server restart.


v1.10
 Same as above. 

 After checking in web UI "CPU only" (why should I since there is no GPU support version) the error changes to:
....
lm_load_print_meta: max token length = 48
llm_load_tensors: ggml ctx size =    0.38 MiB
ggml_backend_cpu_buffer_type_alloc_buffer: failed to allocate buffer of size 49623482400
llama_model_load: error loading model: unable to allocate backend buffer
llama_load_model_from_file: failed to load model
17:36:24-735377 ERROR    Failed to load the model.                                                                                                
Traceback (most recent call last):
  File "/home/sztejkat/ai/llama2/soft/oobaboga-cpu/modules/ui_model_menu.py", line 248, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sztejkat/ai/llama2/soft/oobaboga-cpu/modules/models.py", line 94, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sztejkat/ai/llama2/soft/oobaboga-cpu/modules/models.py", line 275, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sztejkat/ai/llama2/soft/oobaboga-cpu/modules/llamacpp_model.py", line 85, in from_pretrained
    result.model = Llama(**params)
                   ^^^^^^^^^^^^^^^
  File "/home/sztejkat/ai/llama2/soft/oobaboga-cpu/installer_files/env/lib/python3.11/site-packages/llama_cpp/llama.py", line 358, in __init__
    self._model = self._stack.enter_context(contextlib.closing(_LlamaModel(
                                                               ^^^^^^^^^^^^
  File "/home/sztejkat/ai/llama2/soft/oobaboga-cpu/installer_files/env/lib/python3.11/site-packages/llama_cpp/_internals.py", line 54, in __init__
    raise ValueError(f"Failed to load model from file: {path_model}")
ValueError: Failed to load model from file: models/Noromaid-v0.1-mixtral-8x7b-Instruct-v3.q8_0.gguf

Exception ignored in: <function LlamaCppModel.__del__ at 0x7f4af658b600>
Traceback (most recent call last):
  File "/home/sztejkat/ai/llama2/soft/oobaboga-cpu/modules/llamacpp_model.py", line 33, in __del__
    del self.model
        ^^^^^^^^^^
AttributeError: 'LlamaCppModel' object has no attribute 'model'


v1.9
raceback (most recent call last):
  File "/home/sztejkat/ai/llama2/soft/oobaboga-cpu/modules/ui_model_menu.py", line 246, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sztejkat/ai/llama2/soft/oobaboga-cpu/modules/models.py", line 94, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sztejkat/ai/llama2/soft/oobaboga-cpu/modules/models.py", line 275, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sztejkat/ai/llama2/soft/oobaboga-cpu/modules/llamacpp_model.py", line 39, in from_pretrained
    LlamaCache = llama_cpp_lib().LlamaCache
                 ^^^^^^^^^^^^^^^
  File "/home/sztejkat/ai/llama2/soft/oobaboga-cpu/modules/llama_cpp_python_hijack.py", line 38, in llama_cpp_lib
    raise Exception(f"Cannot import 'llama_cpp_cuda' because '{imported_module}' is already imported. See issue #1575 in llama-cpp-python. Please restart the server before attempting to use a different version of llama-cpp-python.")
Exception: Cannot import 'llama_cpp_cuda' because 'llama_cpp' is already imported. See issue #1575 in llama-cpp-python. Please restart the server before attempting to use a different version of llama-cpp-python.
```

### System Info

```shell
Bare CPU, linux, no GPU present.
```

**Comment by cm8t** [comment]
I had closed my issue since it is supposedly upstream [https://github.com/abetlen/llama-cpp-python/issues/1575](url) in llama.cpp. A workaround may have been implemeted for macos, as i no longer incur the error when attempting to load gguf models.
