### ISSUE TITLE
Update dependencies for getting LLAMA 3.1 to work

### ISSUE THREAD

**Issue by reuschling** [oobabooga/text-generation-webui#6270]
Now LLAMA 3.1 is out, but sadly it is not loadable with current text-generation-webui. I tried to update transformers lib which makes the model loadable, but I further get an error when trying to use the model:
```
Traceback (most recent call last):
  File "/app/modules/callbacks.py", line 61, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "/app/modules/text_generation.py", line 393, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 1975, in generate
    self._get_logits_warper(generation_config, device=input_ids.device)
TypeError: get_logits_warper_patch() got an unexpected keyword argument 'device'
```

When I updated torch, I come into further issues and found myself in the dependency hell...

Here is some discussion about needed library versions, as a hint:
https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct/discussions/15
https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct/discussions/35

**Comment by leszekhanusz** [comment]
Release [b3472](https://github.com/ggerganov/llama.cpp/releases/tag/b3472) of llama.cpp has just been released with LLama 3.1 support.

**Comment by leszekhanusz** [comment]
Alright, now llama-cpp-python made the [release 0.2.84](https://github.com/abetlen/llama-cpp-python/blob/main/CHANGELOG.md#0284) which updated llama.cpp version to the latest commit.

**Comment by goodglitch** [comment]
Really waiting for the version bump to solve the problems with llama 3.1. Hope Oobabooga team would do it soon.

**Comment by raziel2001au** [comment]
Also waiting for this to enable loading Llama 3.1 models, more specifically, wanting to try out Lumimaid-v0.2-70B.i1-IQ2_XS on my 3090 and quantised L3.1 models seem to be running into these errors on Ooba at the moment:
_llama_model_load: error loading model: done_getting_tensors: wrong number of tensors; expected 724, got 723_

It does load and produce text on the current version of llama.cpp, so I assume once the dependencies have been updated, it should hopefully work.

**Comment by goodglitch** [comment]
> https://www.reddit.com/r/LocalLLaMA/comments/1eg5wgb/llama_31_changed_its_chat_template_again/ and reddit tipped off another change. so lots still going on behind the scenes https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct/tree/main

Changes in template may affect quality of output, but we are talking here about the problem that newly quantized models don't load at all.

**Comment by PRCbubu** [comment]
Can anyone tell me, when I'm trying to load a gguf model with .cpp and tensorcore option, I'm getting the error (even though I've RTX2080 Super)?

**Comment by goodglitch** [comment]
> Can anyone tell me, when I'm trying to load a gguf model with .cpp and tensorcore option, I'm getting the error (even though I've RTX2080 Super)?

It says that it requires llama-cpp-python to restart. So what you can do is completely shutdown oobabooga and then when you load model first time tick tensor option. It worked for me, so I think it will work for you too. Personally I do not suggest to use it, since performance gains are small but power consumption and temps rising quite substantially.

**Comment by leszekhanusz** [comment]
`llama-cpp-python` dependency has been updated to `0.2.85` in release [v1.13](https://github.com/oobabooga/text-generation-webui/releases/tag/v1.13). LLaMA 3.11 is working now! Thanks @oobabooga
