### ISSUE TITLE
AutoAWQ gone missing (model loader) and charecter not loading (for my case, out of 5 charecters, only 2 of them are loading)

### ISSUE THREAD

**Issue by PRCbubu** [oobabooga/text-generation-webui#6281]
### Describe the bug

When I start the program, it went blank screen (like, noting except for the UI elements). So, when I was trying to select the character from the dropdown menu, it was not selecting the characters, barring the two. Then I tried to edit the characters in "Parameters" option, but there also, character cannot be selected. I checked in the folder directly and found, characters are already there but for some reason, it is not getting selected.

And as for the second bug/problem, the AutoAWQ loader is missing.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1) Start the program
2) Let it load
3) *Bug/problem*

### Screenshot

This is the screenshot of the missing AutoAWQ loader.
![Screenshot_20240727_212627_Chrome](https://github.com/user-attachments/assets/d1a910fe-080f-4df4-ab11-e8946571bbf9)

### Logs

```shell
Traceback (most recent call last):
  File "D:\StableDiffution\text-generation-webui\installer_files\env\Lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StableDiffution\text-generation-webui\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StableDiffution\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StableDiffution\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StableDiffution\text-generation-webui\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StableDiffution\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\StableDiffution\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StableDiffution\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\StableDiffution\text-generation-webui\modules\chat.py", line 1131, in handle_character_menu_change
    html = redraw_html(history, state['name1'], state['name2'], state['mode'], state['chat_style'], state['character_menu'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StableDiffution\text-generation-webui\modules\chat.py", line 483, in redraw_html
    return chat_html_wrapper(history, name1, name2, mode, style, character, reset_cache=reset_cache)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StableDiffution\text-generation-webui\modules\html_generator.py", line 303, in chat_html_wrapper
    return generate_cai_chat_html(history['visible'], name1, name2, style, character, reset_cache)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StableDiffution\text-generation-webui\modules\html_generator.py", line 227, in generate_cai_chat_html
    row = [convert_to_markdown_wrapped(entry, use_cache=i != len(history) - 1) for entry in _row]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StableDiffution\text-generation-webui\modules\html_generator.py", line 227, in <listcomp>
    row = [convert_to_markdown_wrapped(entry, use_cache=i != len(history) - 1) for entry in _row]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StableDiffution\text-generation-webui\modules\html_generator.py", line 149, in convert_to_markdown_wrapped
    return convert_to_markdown.__wrapped__(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StableDiffution\text-generation-webui\modules\html_generator.py", line 76, in convert_to_markdown
    string = replace_quotes(string)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StableDiffution\text-generation-webui\modules\html_generator.py", line 63, in replace_quotes
    replaced_text = re.sub(pattern, lambda m: f'<q>{m.group(1)}{m.group(2)}{m.group(3)}</q>', text, flags=re.DOTALL)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StableDiffution\text-generation-webui\installer_files\env\Lib\re\__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
---------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\StableDiffution\text-generation-webui\installer_files\env\Lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StableDiffution\text-generation-webui\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StableDiffution\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StableDiffution\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StableDiffution\text-generation-webui\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StableDiffution\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\StableDiffution\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StableDiffution\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\StableDiffution\text-generation-webui\modules\loaders.py", line 351, in blacklist_samplers
    if loader == 'All' or sampler in loaders_samplers[loader]:
                                     ~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'AutoAWQ'
```

### System Info

```shell
ASUS ROG STRIX Laptop.
CPU: Intel i7 10875H
GPU: NVIDIA RTX 2080 Super

Settings (extensions used) in textgen:
"gallery"
"send_pictures"
"autonomics"
"alltalk_tts" (with deepspeed and low vram)
"LLM_Web_search"
"Memoir"
```

**Comment by oobabooga** [comment]
I removed intentionally because it had bad defaults. Try loading the model though the transformers loader. It will use AutoAWQ automatically.

**Comment by PRCbubu** [comment]
> I removed intentionally because it had bad defaults. Try loading the model though the transformers loader. It will use AutoAWQ automatically.

So, what about the characters not loading up properly? Like I'm not able to figure out, where it problem.

**Comment by PRCbubu** [comment]
Also, I'm getting this error now, even though there are charecters with yaml and png files in the charecter folder, Somehow these are not getting selected @oobabooga
![image](https://github.com/user-attachments/assets/19e1dc49-3401-4a59-acbb-9ad7222cbc8e)

**Comment by Sobhanysiamak** [comment]
Send

**Comment by prb8592** [comment]
I tried loading an AWQ model using the Transformers loader. It resulted in an error:
Loading an AWQ quantized model requires auto-awq library ('pip install autoawq')

Using the cmd prompt, I then tried installing autoawq using the pip command specified. This resulted in the error:
ERROR: Could not find a version that satisfies the requirement autoawq (from versions: none)
ERROR: No matching distribution found for autoawq

My system:
Windows 10
python version 3.13.0
NVIDIA GeForce RTX 3080 Ti
text-gen-webui version 1.15

**Comment by WhiteBite** [comment]
I have the same problem.

**Comment by ripnew** [comment]
got same problem 

Traceback (most recent call last):

File "S:\New_text-generation-webui\modules\ui_model_menu.py", line 232, in load_model_wrapper


shared.model, shared.tokenizer = load_model(selected_model, loader)

                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "S:\New_text-generation-webui\modules\models.py", line 93, in load_model


output = load_func_map[loader](model_name)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "S:\New_text-generation-webui\modules\models.py", line 263, in huggingface_loader


model = LoaderClass.from_pretrained(path_to_model, **params)

        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "S:\New_text-generation-webui\installer_files\env\Lib\site-packages\transformers\models\auto\auto_factory.py", line 559, in from_pretrained


return model_class.from_pretrained(

       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "S:\New_text-generation-webui\installer_files\env\Lib\site-packages\transformers\modeling_utils.py", line 3657, in from_pretrained


hf_quantizer.validate_environment(
File "S:\New_text-generation-webui\installer_files\env\Lib\site-packages\transformers\quantizers\quantizer_awq.py", line 50, in validate_environment


raise ImportError("Loading an AWQ quantized model requires auto-awq library (`pip install autoawq`)")
ImportError: Loading an AWQ quantized model requires auto-awq library (pip install autoawq)

**Comment by Dcode1999** [comment]
Same problem.

**Comment by Nerdtek** [comment]
Yes AutoAWQ doesn't work with Torch > 2.3.1 so that is probably the issue here. I tried forcing it by editing the requirements.txt file, and it wouldn't install due to the dependencies issue with torch. The installer installs torch 2.6.0 so yeah. Which means this package is useless if you want to use a GPU. OOBABOOGA any thoughts on how to resolve?

**Comment by kevin8978** [comment]
I am stuck on this...any solution so far?
