### ISSUE TITLE
Can't load TheBloke_openchat-3.5-0106-GPTQ using the Transformers model loader

### ISSUE THREAD

**Issue by bloomingseed** [oobabooga/text-generation-webui#6288]
### Describe the bug

Can't load TheBloke_openchat-3.5-0106-GPTQ using the Transformers model loader. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I. Manual installation using Conda

0. Install Conda (miniconda3)
1. Create a new conda environment with python=3.11 and activate it
2. Install Pytorch: Linux system, AMD GPU: `pip3 install torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/rocm5.6`
3. Install the web UI: CPU only, has AVX2: 
```
git clone https://github.com/oobabooga/text-generation-webui
cd text-generation-webui
pip install -r requirements_cpu_only.txt
```
II. Start the web UI & load model
1. Start server (with the previous conda env still activated): `python server.py`
2. Browse to `http://127.0.0.1:7860/`
3. Open Models tab
4. Download `TheBloke/openchat-3.5-0106-GPTQ`: Enter the name, Get file list --> Download --> Wait until finished
5. Refresh models list
6. Select `TheBloke_openchat-3.5-0106-GPTQ`
7. Choose `Transformer` as the model loader
8. Press Load

### Screenshot

![FireShot Capture 001 - Text generation web UI - 127 0 0 1](https://github.com/user-attachments/assets/790b25f4-47f1-4f01-b97b-7e0ba831db97)

### Logs

```shell
00:22:54-253301 INFO     Loading "TheBloke_openchat-3.5-0106-GPTQ"              
00:22:54-270560 INFO     TRANSFORMERS_PARAMS=                                   
{'low_cpu_mem_usage': True, 'torch_dtype': torch.bfloat16}

00:22:54-811877 ERROR    Failed to load the model.                              
Traceback (most recent call last):
  File "/home/xceeded/miniconda3/envs/textgen/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xceeded/text-generation-webui/modules/ui_model_menu.py", line 231, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xceeded/text-generation-webui/modules/models.py", line 93, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xceeded/text-generation-webui/modules/models.py", line 168, in huggingface_loader
    model = LoaderClass.from_pretrained(path_to_model, **params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xceeded/miniconda3/envs/textgen/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xceeded/miniconda3/envs/textgen/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3354, in from_pretrained
    hf_quantizer.validate_environment(
  File "/home/xceeded/miniconda3/envs/textgen/lib/python3.11/site-packages/transformers/quantizers/quantizer_gptq.py", line 52, in validate_environment
    gptq_supports_cpu = version.parse(importlib.metadata.version("auto-gptq")) > version.parse("0.4.2")
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xceeded/miniconda3/envs/textgen/lib/python3.11/importlib/metadata/__init__.py", line 1009, in version
    return distribution(distribution_name).version
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xceeded/miniconda3/envs/textgen/lib/python3.11/importlib/metadata/__init__.py", line 982, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xceeded/miniconda3/envs/textgen/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for auto-gptq
```

### System Info

```shell
- Hardware Model: Dell Inc. Vostro 3578
- Memory: 8,0 GiB
- Operating System: Ubuntu 22.04.1 LTS 64-bit
- CPU: Intel® Core™ i7-8550U CPU @ 1.80GHz × 8
- GPU: (`sudo lshw -C display` output):


  *-display                 
       description: VGA compatible controller
       product: UHD Graphics 620
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       logical name: /dev/fb0
       version: 07
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=i915 latency=0 resolution=1920,1080
       resources: irq:129 memory:d1000000-d1ffffff memory:b0000000-bfffffff ioport:f000(size=64) memory:c0000-dffff
  *-display UNCLAIMED
       description: Display controller
       product: Jet PRO [Radeon R5 M230 / R7 M260DX / Radeon 520 Mobile]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:01:00.0
       version: c3
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi cap_list
       configuration: latency=0
       resources: memory:c0000000-cfffffff memory:d0000000-d003ffff ioport:e000(size=256) memory:d0040000-d005ffff
```

**Comment by bloomingseed** [comment]
I was opting to run the models on CPU only, but I don't know if it's required to run GPTQ models on GPUs instead of CPUs.

**Comment by bloomingseed** [comment]
Actually I found out GPTQ models can't be loaded with Transformers. [Learnt from TheBloke himself](https://huggingface.co/TheBloke/medalpaca-13B-GPTQ/discussions/3#64777c23f911e9e76c650d29). 

I will close this issue and figure out how to run the model on my GPU.
