### ISSUE TITLE
Error at install (Windows - CPU only) <-> ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by Thomuss** [oobabooga/text-generation-webui#6307]
### Describe the bug

When I install the thing, I always get the same error : See logs.

I've already tried : (+ some other commands from existing issues) 
- Reinstall several times with a different version (With and without administrator rights)
- Repair and reinstall Python
- cmd_windows.bat -> pip install -r C:\****\requirements.txt | temp_requirements.txt (get the same error)
- cmd_windows.bat -> pip install --trusted-host github.com -r requirements.txt (get the same error)
- cmd_windows.bat -> pip install -r pyyaml >> pip install -r rich >> pip install -r accelerate >> pip install -r gradio (But get the same error at this point)

As for the famous "A full log can be found at..." that are supposed to be created as indicated in the logs, that doesn't happen.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

When Installing - Any version.

### Logs

```shell
Collecting importlib-resources<7.0,>=1.3 (from gradio==4.26.*->-r temp_requirements.txt (line 5))
  Using cached importlib_resources-6.4.0-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: markupsafe~=2.0 in c:\****\oobabooga\installer_files\env\lib\site-packages (from gradio==4.26.*->-r temp_requirements.txt (line 5)) (2.1.5)
Collecting matplotlib~=3.0 (from gradio==4.26.*->-r temp_requirements.txt (line 5))
  Using cached matplotlib-3.9.1.tar.gz (36.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      + meson setup C:\****\Oobabooga\installer_files\pip-install-h1nomioc\matplotlib_9b4688be1f7e4c64a935c5f764b2679b C:\****\Oobabooga\installer_files\pip-install-h1nomioc\matplotlib_9b4688be1f7e4c64a935c5f764b2679b\.mesonpy-4_a_tiap -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\****\Oobabooga\installer_files\pip-install-h1nomioc\matplotlib_9b4688be1f7e4c64a935c5f764b2679b\.mesonpy-4_a_tiap\meson-python-native-file.ini
      Le fichier sp‚cifi‚ est introuvable.
      The Meson build system
      Version: 1.5.1
      Source dir: C:\****\Oobabooga\installer_files\pip-install-h1nomioc\matplotlib_9b4688be1f7e4c64a935c5f764b2679b
      Build dir: C:\****\Oobabooga\installer_files\pip-install-h1nomioc\matplotlib_9b4688be1f7e4c64a935c5f764b2679b\.mesonpy-4_a_tiap
      Build type: native build
      Program python3 found: YES
      Project name: matplotlib
      Project version: 3.9.1
      Activating VS 17.10.5

      ..\meson.build:1:0: ERROR: Compiler cl cannot compile programs.

      A full log can be found at C:\****\Oobabooga\installer_files\pip-install-h1nomioc\matplotlib_9b4688be1f7e4c64a935c5f764b2679b\.mesonpy-4_a_tiap\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Command '"C:\****\Oobabooga\installer_files\conda\condabin\conda.bat" activate "C:\****\Oobabooga\installer_files\env" >nul && python -m pip install -r temp_requirements.txt --upgrade' failed with exit status code '1'.

Exiting now.
Try running the start/update script again.
'ook' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.


*******************************************************************
* You haven't downloaded any model yet.
* Once the web UI launches, head over to the "Model" tab and download one.
*******************************************************************


Traceback (most recent call last):
  File "C:\****\Oobabooga\server.py", line 4, in <module>
    from modules import shared
  File "C:\****\Oobabooga\modules\shared.py", line 8, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

### System Info

```shell
Microsoft Windows 10 Professionnel N x64
CPU : AMD Ryzen 7 2700X Eight-Core Processor, 3800 MHz, 8 core(s), 16 logic processor(s)
GPU : PNY GeForce GTX 1660 Ti XLR8 OC
Motherboard : TUF B450-PLUS GAMING
RAM : 16,0 Go
```

**Comment by Nekuromu** [comment]
Having this same bug, as is someone else on the Discord. I am guessing some recent change has created an install issue.

**Comment by taglux** [comment]
Same issue

**Comment by alandee** [comment]
Running the update bat file, selecting main and then extensions ( all ) resolved the issue for me.

**Comment by justjustjustjust** [comment]
same

**Comment by 1060778506** [comment]
> 运行更新 bat 文件，选择主要文件然后选择扩展（全部）解决了我的问题。

![Image](https://github.com/user-attachments/assets/18907571-4d5b-4faa-a09b-25938e812973)      双击打开这个文件，然后 选择B    》  选择 A                 是这样吗
