### ISSUE TITLE
When running the start_windows.bat file in the Windows interface, ModuleNotFoundError: No module named 'yaml' appears And I didn't see some important tool files in the download list

### ISSUE THREAD

**Issue by neptune-T** [oobabooga/text-generation-webui#6308]
### Describe the bug

When running the start_windows.bat file in the Windows interface, ModuleNotFoundError: No module named 'yaml' appears

**And I entered pip list in cmd_windows.bat and found only these file versions, no transformers,Why do I lack so many tools?:**

```
Package           Version
----------------- ------------
filelock          3.13.1
fsspec            2024.2.0
Jinja2            3.1.3
MarkupSafe        2.1.5
mpmath            1.3.0
networkx          3.2.1
numpy             1.26.3
pillow            10.2.0
pip               24.0
py-cpuinfo        9.0.0
setuptools        72.1.0
sympy             1.12
torch             2.2.2+cu118
torchaudio        2.2.2+cu118
torchvision       0.17.2+cu118
typing_extensions 4.9.0
wheel             0.43.0
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

After I cloned this file, I clicked to run cmd_windows.bat, and then after the computer model was requested, the download was completed and this prompt appeared:

 No module named 'yaml' appears

### Logs

```shell
*******************************************************************
* You haven't downloaded any model yet.
* Once the web UI launches, head over to the "Model" tab and download one.
*******************************************************************

Traceback (most recent call last):
  File "F:\language_model\text-generation-webui-main\server.py", line 4, in <module>
    from modules import shared
  File "F:\language_model\text-generation-webui-main\modules\shared.py", line 8, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

```
```


### System Info

```shell
OS:WINDOWS 11
GPU:NVIDIA GeForce RTX 3070 Laptop GPU
```

**Comment by Nekuromu** [comment]
seems related to #6307, not sure when this bug started but seems to have taken out the ability for a windows fresh install?

**Comment by noarche** [comment]
I had the same error and to resolve I ran the update and then tried to start.
