### ISSUE TITLE
Can't train LoRA for Phi-3-medium-128k-instruct (transformers)

### ISSUE THREAD

**Issue by palladium123** [oobabooga/text-generation-webui#6314]
### Describe the bug

When I attempt to use the training tab to train LoRA for the above model I get the error message as per 'Logs' below. Essentially can't train LoRA with this model, but loading the model (8-bit) and inferencing works fine. Training Llama-3 works fine. 

Advice would be much appreciated. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load model  under 'Model tab' -> training tab -> Start training LoRA (after customising parameters and loading dataset). 

### Logs
Traceback (most recent call last):
  File "H:\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\queueing.py", line 566, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1786, in process_api    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1350, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 583, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 576, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "H:\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 559, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "H:\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 742, in gen_wrapper
    response = next(iterator)
               ^^^^^^^^^^^^^^
  File "H:\text-generation-webui-main\modules\training.py", line 522, in do_train
    target_modules=list_target_modules(model_id),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\text-generation-webui-main\modules\training.py", line 337, in list_target_modules
    return model_to_lora_modules[model_id]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'phi3'

```shell
See above.
```


### System Info

```shell
Win 10
RTX 3090 - CUDA 11.8 (have old Kepler graphics card for multi monitor setup)
Transformers 4.44.0dev0 (tried 4.43 - did not work too)
```

**Comment by oobabooga** [comment]
The training code has been rewritten in v4.0. The "Target all linear layers" checkbox works for any model architecture, so you no longer hit KeyErrors for unsupported model types. See the [release notes](https://github.com/oobabooga/text-generation-webui/releases/tag/v4.0) and [training docs](https://github.com/oobabooga/text-generation-webui/wiki/05-%E2%80%90-Training-Tab).
