### ISSUE TITLE
Problems with offloading with the new 30B models

### ISSUE THREAD

**Issue by carolinacamassabdi** [oobabooga/text-generation-webui#632]
### Describe the bug

Hi, I am using the latest model files `(.safetensors)`, in particular [this alpaca model](https://huggingface.co/elinas/alpaca-30b-lora-int4).

I had no issues with the smaller models because they could fit on the GPU, now the problems are starting once I need to split between devices.

I am running the latest version of the code both from this repo and GPTQ. I have also switched to the *cuda* branch for GPTQ as advised in the latest issues (https://github.com/qwopqwop200/GPTQ-for-LLaMa/issues/96)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Here is the list of experiments I ran (In all cases the base arguments are `--model_type llama --wbits 4 --groupsize 128`)

- with `auto-devices` or no arguments: goes OOM
- if I add `--gpu-memory 10000MiB` (both with or without `--auto-devices`):

```
Traceback (most recent call last):
  File "/home/carolinacamassa/text-generation-webui/modules/callbacks.py", line 64, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/home/carolinacamassa/text-generation-webui/modules/text_generation.py", line 222, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1462, in generate
    return self.sample(
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2478, in sample
    outputs = self(
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 705, in forward
    outputs = self.model(
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 593, in forward
    layer_outputs = decoder_layer(
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 311, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 212, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 160, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 280, in pre_forward
    set_module_tensor_to_device(module, name, self.execution_device, value=self.weights_map[name])
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/utils/offload.py", line 123, in __getitem__
    return self.dataset[f"{self.prefix}{key}"]
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/utils/offload.py", line 170, in __getitem__
    weight_info = self.index[key]
	  KeyError: 'model.layers.44.self_attn.q_proj.wf1
```
- if I try with `--cpu` (no auto-devices or gpu-memory):
```
	Traceback (most recent call last):
  File "/home/carolinacamassa/text-generation-webui/modules/callbacks.py", line 64, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/home/carolinacamassa/text-generation-webui/modules/text_generation.py", line 222, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1462, in generate
    return self.sample(
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2478, in sample
    outputs = self(
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 705, in forward
    outputs = self.model(
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 593, in forward
    layerx_outputs = decoder_layer(
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 311, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 212, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/carolinacamassa/text-generation-webui/repositories/GPTQ-for-LLaMa/quant.py", line 426, in forward
    quant_cuda.vecquant4matmul(x, self.qweight, y, self.scales, self.qzeros, self.groupsize)
RuntimeError: t == DeviceType::CUDA INTERNAL ASSERT FAILED at "/home/carolinacamassa/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/include/c10/cuda/impl/CUDAGuardImpl.h":25, please report a bug to PyTorch. 
```
- the only case in which it works is by adding `--prelayer 44`, both with or without auto-devices. In that case however, the generation is super slow (0.3 tokens/s) even though the CPU is barely used. From htop it looks like just one thread is active out of 6.

### Logs

```shell
provided above
```

### System Info

```shell
> System info: 1 Tesla V100 with 16GiB, 112 GB RAM, 6 CPUs
```

**Comment by huangjiaheng** [comment]
the same，both --cpu and --auto-devices does not work.

**Comment by Titaniumtown** [comment]
I can reproduce this error with my 6900xt

**Comment by oobabooga** [comment]
It is not clear how to offload the 4-bit models. The code for that is implemented here using `accelerate` but it doesn't work properly as you have found https://github.com/oobabooga/text-generation-webui/blob/main/modules/GPTQ_loader.py#L115

**Comment by carolinacamassabdi** [comment]
Got it, thanks for the answer. I tried with a different 	VM and at least splitting between different GPUs works with no issue.

**Comment by luckyycode** [comment]
Got the same issue at 4080 16gb and --cpu-memory 40GB, I tried different parameters but it is still no go
Default prompt for 13b is 
--wbits 4 --groupsize 128 --auto-device --gpu-memory 9--listen (loading 13b here)

And for 30b I tried (I thought it could be not enough of memory)
--cpu-memory 40GB --verbose --wbits 4 --groupsize 128 --auto-device --gpu-memory 12 --gptq-pre-layer 20 --listen

still no luck, getting exact the same error as OP
