### ISSUE TITLE
Unable to upload character JSON

### ISSUE THREAD

**Issue by Good-Stevening** [oobabooga/text-generation-webui#6332]
### Describe the bug

After placing the JSON and PNG in their respective areas, and hitting the submit button to upload a character, I get the following error:

```
Traceback (most recent call last):
  File "F:\AI\Oobabooga\text-generation-webui\installer_files\env\Lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Oobabooga\text-generation-webui\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Oobabooga\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Oobabooga\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Oobabooga\text-generation-webui\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Oobabooga\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "F:\AI\Oobabooga\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Oobabooga\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "F:\AI\Oobabooga\text-generation-webui\modules\chat.py", line 814, in upload_character
    name = data['name']
           ~~~~^^^^^^^^
KeyError: 'name'
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

This happens every time I try to upload a new character, and same error with all characters I have tried.

### Screenshot

![Screenshot 2024-08-17 145740](https://github.com/user-attachments/assets/975b5d00-448b-41cc-bc95-f021e22058e6)
![Screenshot 2024-08-17 145829](https://github.com/user-attachments/assets/0e203eee-665b-4153-ba02-3c6c8911cd13)

### Logs

```shell
14:45:48-658968 INFO     Starting Text generation web UI
14:45:48-661044 INFO     Loading settings from "settings.yaml"
14:45:48-663805 INFO     Loading the extension "gallery"
14:45:48-664823 INFO     Loading the extension "openai"
14:45:48-737447 INFO     OpenAI-compatible API URL:

                         http://127.0.0.1:5000


Running on local URL:  http://127.0.0.1:7860

14:46:36-044846 INFO     Saved "F:\AI\Oobabooga\text-generation-webui\settings.yaml".
Traceback (most recent call last):
  File "F:\AI\Oobabooga\text-generation-webui\installer_files\env\Lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Oobabooga\text-generation-webui\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Oobabooga\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Oobabooga\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Oobabooga\text-generation-webui\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Oobabooga\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "F:\AI\Oobabooga\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Oobabooga\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "F:\AI\Oobabooga\text-generation-webui\modules\chat.py", line 814, in upload_character
    name = data['name']
           ~~~~^^^^^^^^
KeyError: 'name'
Traceback (most recent call last):
  File "F:\AI\Oobabooga\text-generation-webui\installer_files\env\Lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Oobabooga\text-generation-webui\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Oobabooga\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Oobabooga\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Oobabooga\text-generation-webui\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Oobabooga\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "F:\AI\Oobabooga\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Oobabooga\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "F:\AI\Oobabooga\text-generation-webui\modules\chat.py", line 814, in upload_character
    name = data['name']
           ~~~~^^^^^^^^
KeyError: 'name'
```

### System Info

```shell
Windows 11
NVIDIA RTX 4080
```

**Comment by InnocentRain** [comment]
i have the same problem, no matter what i try i get the same error
