### ISSUE TITLE
Can't load any model, Please help.

### ISSUE THREAD

**Issue by rakeshthestraight** [oobabooga/text-generation-webui#6347]
I keep getting these errors, I can run ollama without any issues so its not likely a hardware issue. Any ideas how i can resolve this?

Traceback (most recent call last):

File "H:\Ooba\text-generation-webui\modules\ui_model_menu.py", line 231, in load_model_wrapper

shared.model, shared.tokenizer = load_model(selected_model, loader)

                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "H:\Ooba\text-generation-webui\modules\models.py", line 101, in load_model

tokenizer = load_tokenizer(model_name)

            ^^^^^^^^^^^^^^^^^^^^^^^^^^
File "H:\Ooba\text-generation-webui\modules\models.py", line 127, in load_tokenizer

tokenizer = AutoTokenizer.from_pretrained(

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "H:\Ooba\text-generation-webui\installer_files\env\Lib\site-packages\transformers\models\auto\tokenization_auto.py", line 916, in from_pretrained

return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)

       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "H:\Ooba\text-generation-webui\installer_files\env\Lib\site-packages\transformers\tokenization_utils_base.py", line 2255, in from_pretrained

raise EnvironmentError(
OSError: Can't load tokenizer for 'models\chronos-t5-tiny'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'models\chronos-t5-tiny' is the correct path to a directory containing all relevant files for a T5TokenizerFast tokenizer.

**Comment by rakeshthestraight** [comment]
Uninstalled previously installed , llama.cpp, Shutdown wsl and it seems to work now.
