### ISSUE TITLE
multi-user Flag does not work

### ISSUE THREAD

**Issue by Critter74** [oobabooga/text-generation-webui#6408]
### Describe the bug

If I start the app with --multi-user flag, I get errors and dont see the answer box.
Whithout the flag, I can see answers and dont get the errors

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

- download version v1.14
- conda create -n textgen python=3.11
- conda activate textgen
- pip install -r requirements.txt
- pip install fastapi==0.112.4 // if not, I get a error
- python server.py --listen --model some_model --multi-user

### Screenshot

![image](https://github.com/user-attachments/assets/80c5a7af-a9ab-4422-be0b-87cf433a19d2)

### Logs

```shell
11:00:38-778691 INFO     LOADER: "Transformers"
11:00:38-779479 INFO     TRUNCATION LENGTH: 32768
11:00:38-780205 INFO     INSTRUCTION TEMPLATE: "Alpaca"

Running on local URL:  http://0.0.0.0:7860

Traceback (most recent call last):
  File "/home/daniel/miniconda3/envs/textgen/lib/python3.11/site-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/miniconda3/envs/textgen/lib/python3.11/site-packages/gradio/route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/miniconda3/envs/textgen/lib/python3.11/site-packages/gradio/blocks.py", line 1786, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/miniconda3/envs/textgen/lib/python3.11/site-packages/gradio/blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/miniconda3/envs/textgen/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/miniconda3/envs/textgen/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/daniel/miniconda3/envs/textgen/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 914, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/miniconda3/envs/textgen/lib/python3.11/site-packages/gradio/utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/home/daniel/text-generation-webui/modules/chat.py", line 1143, in handle_character_menu_change
    gr.update(choices=histories, value=histories[0][1]),
                                       ~~~~~~~~~^^^
IndexError: list index out of range
```

### System Info

```shell
Ubuntu 22.04
Cuda 12.4
```

**Comment by Critter74** [comment]
Solved with v1.15
