### ISSUE TITLE
Windows Installer fails as micromamba fails to install. 

### ISSUE THREAD

**Issue by indianninja2018** [oobabooga/text-generation-webui#644]
### Describe the bug

When clicking chat.exe
 it gives the option to use GPU or CPU, however it does not work due to the errors, and says this application can not be installed. downloadmodel.bat gives the error that micromamba hook not found. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Can not installin Windows from installer provided as micromamba fails to install.

### Screenshot

![2](https://user-images.githubusercontent.com/37556837/228618981-f3406630-83d4-4aa0-8dbf-a79b4e6c42e6.png)
![image](https://user-images.githubusercontent.com/37556837/228619413-596bb323-95f1-4f66-984e-59ca921202d6.png) 

### Logs

```shell
What is your GPU?

A) NVIDIA
B) None (I want to run in CPU mode)

Input> A
"Downloading Micromamba from https://github.com/mamba-org/micromamba-releases/releases/download/1.4.0-0/micromamba-win-64 to E:\oobabooga-windows\installer_files\mamba\micromamba.exe"
A subdirectory or file E:\oobabooga-windows\installer_files\mamba already exists.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
Micromamba version:
Access is denied.
Micromamba not found.
Press any key to continue . . .
```

### System Info

```shell
OS windows11 home single language, NVDIA 1060
```

**Comment by indianninja2018** [comment]
I have tried to troubleshoot it myself by downloading micromamba and putting the exe inside the installer directory. Then restarted installer.bat which proceeded with the installation. However later it gives the following error 
`Traceback (most recent call last):
  File "E:\oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa\setup_cuda.py", line 6, in <module>
    ext_modules=[cpp_extension.CUDAExtension(
  File "C:\Users\pariz\AppData\Roaming\Python\Python310\site-packages\torch\utils\cpp_extension.py", line 1048, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "C:\Users\pariz\AppData\Roaming\Python\Python310\site-packages\torch\utils\cpp_extension.py", line 1186, in library_paths
    paths.append(_join_cuda_home(lib_dir))
  File "C:\Users\pariz\AppData\Roaming\Python\Python310\site-packages\torch\utils\cpp_extension.py", line 2223, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
CUDA kernal compilation failed. Will try to install from wheel.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
Defaulting to user installation because normal site-packages is not writeable
WARNING: Requirement 'quant_cuda-0.0.0-cp310-cp310-win_amd64.whl' looks like a filename, but the file does not exist
Processing e:\oobabooga-windows\text-generation-webui\repositories\gptq-for-llama\quant_cuda-0.0.0-cp310-cp310-win_amd64.whl
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'E:\\oobabooga-windows\\text-generation-webui\\repositories\\GPTQ-for-LLaMa\\quant_cuda-0.0.0-cp310-cp310-win_amd64.whl'


[notice] A new release of pip available: 22.2.2 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
Wheel installation failed.
Press any key to continue . . .`

**Comment by jllllll** [comment]
Someone else had this issue as well. Best I can tell is that it is caused by restrictive network security. Try this installer: 
[install.txt](https://github.com/oobabooga/text-generation-webui/files/11106867/install.txt)
Rename it to `install.bat`. I added `--ssl-no-revoke` to all the curl commands.

**Comment by kw3rk** [comment]
Look for the curl command in the install.bat file and add '-k' after the '-L' flag. It allows it to download without the need for SSL certificates/skips verifying the peer. See: https://curl.se/docs/sslcerts.html

**Comment by Machiuka** [comment]
When I want to run any bat file it gives me the error: The system cannot find the path specified.
MicroMamba hook not found. When run micromamba from the oobabooga-windows it works.
