### ISSUE TITLE
silero tts and whisper stt not install

### ISSUE THREAD

**Issue by aeravel** [oobabooga/text-generation-webui#6532]
### Describe the bug

When installing Silero and Whisper it gives errors

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Launch webui
2. In extensions I include Silero and Whisper
3. I get errors and extensions do not start
4. Even when installing requirements, the error remains

### Logs

```shell
13:18:59-054424 INFO     Starting Text generation web UI

Running on local URL:  http://127.0.0.1:7860


Thanks for being a Gradio user! If you have questions or feedback, please join our Discord server and chat with us: https://discord.gg/feTf9x3ZSB
Closing server running on port: 7860
13:19:15-056856 INFO     Loading the extension "whisper_stt"
13:19:15-065068 ERROR    Could not import the requirements for 'whisper_stt'. Make sure to install the requirements for
                         the extension.

                         * To install requirements for all available extensions, launch the
                           update_wizard script for your OS and choose the B option.

                         * To install the requirements for this extension alone, launch the
                           cmd script for your OS and paste the following command in the
                           terminal window that appears:

                         Linux / Mac:

                         pip install -r extensions/whisper_stt/requirements.txt --upgrade

                         Windows:

                         pip install -r extensions\whisper_stt\requirements.txt --upgrade

13:19:15-071065 ERROR    Failed to load the extension "whisper_stt".
Traceback (most recent call last):
  File "E:\yuumekko\yuwaifu\text-generation-webui-1.16\modules\extensions.py", line 37, in load_extensions
    extension = importlib.import_module(f"extensions.{name}.script")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\yuumekko\yuwaifu\text-generation-webui-1.16\installer_files\env\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\yuumekko\yuwaifu\text-generation-webui-1.16\extensions\whisper_stt\script.py", line 9, in <module>
    import whisper
ModuleNotFoundError: No module named 'whisper'
13:19:15-074065 INFO     Loading the extension "silero_tts"
13:19:15-076065 ERROR    Could not import the requirements for 'silero_tts'. Make sure to install the requirements for
                         the extension.

                         * To install requirements for all available extensions, launch the
                           update_wizard script for your OS and choose the B option.

                         * To install the requirements for this extension alone, launch the
                           cmd script for your OS and paste the following command in the
                           terminal window that appears:

                         Linux / Mac:

                         pip install -r extensions/silero_tts/requirements.txt --upgrade

                         Windows:

                         pip install -r extensions\silero_tts\requirements.txt --upgrade

13:19:15-082065 ERROR    Failed to load the extension "silero_tts".
Traceback (most recent call last):
  File "E:\yuumekko\yuwaifu\text-generation-webui-1.16\modules\extensions.py", line 37, in load_extensions
    extension = importlib.import_module(f"extensions.{name}.script")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\yuumekko\yuwaifu\text-generation-webui-1.16\installer_files\env\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\yuumekko\yuwaifu\text-generation-webui-1.16\extensions\silero_tts\script.py", line 10, in <module>
    from extensions.silero_tts import tts_preprocessor
  File "E:\yuumekko\yuwaifu\text-generation-webui-1.16\extensions\silero_tts\tts_preprocessor.py", line 3, in <module>
    from num2words import num2words
ModuleNotFoundError: No module named 'num2words'

Running on local URL:  http://127.0.0.1:7860
```

### System Info

```shell
win10
3060 12gb
```

**Comment by Alkohole** [comment]
Do you set requirements inside the runtime environments?

**Comment by aeravel** [comment]
> Do you set requirements inside the runtime environments?

I don’t quite understand what you’re talking about.

**Comment by Alkohole** [comment]
WebUI operates in an isolated conda environment, separate from your system's main Python environment.

To install the required dependencies, follow these steps:
1. Activate the conda environment with the command:
   ```bash
   conda activate textgen
   ```  
2. Install the dependencies with the command:
   ```bash
   pip install -r <requirements.txt> --upgrade
   ```  

This will allow you to correctly configure the WebUI environment.
_(Note: If you do not activate the conda environment, the dependencies will be installed in your main Python environment, which does not interact with the conda environment.)_

You can also use the 'update_wizard' script to automatically install all requirements, as the warning says.

**Comment by RezaGlazy** [comment]
i am on colab and have the same issue
