### ISSUE TITLE
GPTQ dont work anymore

### ISSUE THREAD

**Issue by kalle07** [oobabooga/text-generation-webui#6563]
### Describe the bug

see log

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

10 gptq worked last year tody they dont

gguf work

### Logs

```shell
22:19:21-672140 INFO     Loading "TheBloke_Luban-Marcoroni-13B-v3-GPTQ"
22:19:21-682114 ERROR    Failed to load the model.
Traceback (most recent call last):
  File "e:\text-generation-webui\modules\ui_model_menu.py", line 232, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\text-generation-webui\modules\models.py", line 93, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\text-generation-webui\modules\models.py", line 313, in ExLlamav2_HF_loader
    from modules.exllamav2_hf import Exllamav2HF
  File "e:\text-generation-webui\modules\exllamav2_hf.py", line 7, in <module>
    from exllamav2 import (
  File "e:\text-generation-webui\installer_files\env\Lib\site-packages\exllamav2\__init__.py", line 3, in <module>
    from exllamav2.model import ExLlamaV2
  File "e:\text-generation-webui\installer_files\env\Lib\site-packages\exllamav2\model.py", line 35, in <module>
    from exllamav2.config import ExLlamaV2Config
  File "e:\text-generation-webui\installer_files\env\Lib\site-packages\exllamav2\config.py", line 5, in <module>
    from exllamav2.stloader import STFile, cleanup_stfiles
  File "e:\text-generation-webui\installer_files\env\Lib\site-packages\exllamav2\stloader.py", line 5, in <module>
    from exllamav2.ext import none_tensor, exllamav2_ext as ext_c
  File "e:\text-generation-webui\installer_files\env\Lib\site-packages\exllamav2\ext.py", line 291, in <module>
    ext_c = exllamav2_ext
            ^^^^^^^^^^^^^
NameError: name 'exllamav2_ext' is not defined
```

### System Info

```shell
win10
update webui 10/24
```

**Comment by SobakaFox** [comment]
Ошибка NameError: name 'exllamav2_ext' is not defined указывает на проблему с инициализацией модуля exllamav2_ext в пакете exllamav2. Эта ошибка обычно возникает из-за отсутствия компиляции или неправильной установки расширений, необходимых для работы ExLlamaV2

pip install --upgrade exllamav2

Перейдите в директорию exllamav2/ext  ----> python setup.py install

pip install torch --upgrade
pip install torchvision --upgrade

проверка версии CUDA на соответствие с версией PyTorch  ---> python -m torch.utils.collect_env

**Comment by SobakaFox** [comment]
если ничего не помогло

pip uninstall exllamav2
pip install exllamav2

удачи
