### ISSUE TITLE
OSError: Unable to load weights from pytorch checkpoint file

### ISSUE THREAD

**Issue by Rlukas514** [oobabooga/text-generation-webui#658]
### Describe the bug

Starting the web UI...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: Loading binary C:\Users\goc24\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
The following models are available:

1. 65B
2. PygmalionAI_pygmalion-6b_dev

Which one do you want to load? 1-2

2

Loading PygmalionAI_pygmalion-6b_dev...
Auto-assiging --gpu-memory 5 for your GPU to try to prevent out-of-memory errors.
You can manually set other values.
Loading checkpoint shards:   0%|                                                                 | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\goc24\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 415, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "C:\Users\goc24\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\goc24\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\goc24\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 419, in load_state_dict
    if f.read(7) == "version":
  File "C:\Users\goc24\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1778: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\goc24\Downloads\oobabooga-windows\oobabooga-windows\text-generation-webui\server.py", line 274, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\goc24\Downloads\oobabooga-windows\oobabooga-windows\text-generation-webui\modules\models.py", line 159, in load_model
    model = AutoModelForCausalLM.from_pretrained(checkpoint, **params)
  File "C:\Users\goc24\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\goc24\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2656, in from_pretrained
    ) = cls._load_pretrained_model(
  File "C:\Users\goc24\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2965, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "C:\Users\goc24\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 431, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for 'models\PygmalionAI_pygmalion-6b_dev\pytorch_model-00001-of-00002.bin' at 'models\PygmalionAI_pygmalion-6b_dev\pytorch_model-00001-of-00002.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

-

### Logs

```shell
Starting the web UI...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: Loading binary C:\Users\goc24\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
The following models are available:

1. 65B
2. PygmalionAI_pygmalion-6b_dev

Which one do you want to load? 1-2

2

Loading PygmalionAI_pygmalion-6b_dev...
Auto-assiging --gpu-memory 5 for your GPU to try to prevent out-of-memory errors.
You can manually set other values.
Loading checkpoint shards:   0%|                                                                 | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\goc24\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 415, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "C:\Users\goc24\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\goc24\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\goc24\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 419, in load_state_dict
    if f.read(7) == "version":
  File "C:\Users\goc24\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1778: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\goc24\Downloads\oobabooga-windows\oobabooga-windows\text-generation-webui\server.py", line 274, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\goc24\Downloads\oobabooga-windows\oobabooga-windows\text-generation-webui\modules\models.py", line 159, in load_model
    model = AutoModelForCausalLM.from_pretrained(checkpoint, **params)
  File "C:\Users\goc24\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\goc24\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2656, in from_pretrained
    ) = cls._load_pretrained_model(
  File "C:\Users\goc24\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2965, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "C:\Users\goc24\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 431, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for 'models\PygmalionAI_pygmalion-6b_dev\pytorch_model-00001-of-00002.bin' at 'models\PygmalionAI_pygmalion-6b_dev\pytorch_model-00001-of-00002.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
```

### System Info

```shell
Windows 11
```

**Comment by Pyroglyph** [comment]
I have the same issue with a different model: chavinlo/gpt4-x-alpaca.

Windows 11 build 22000
16GB RAM, RTX 3090

```
Starting the web UI...
Warning: --cai-chat is deprecated. Use --chat instead.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: C:\Users\User\Downloads\oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary C:\Users\User\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
Loading chavinlo_gpt4-x-alpaca...
Auto-assiging --gpu-memory 23 for your GPU to try to prevent out-of-memory errors.
You can manually set other values.
Loading checkpoint shards:   0%|                                                                   | 0/6 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\User\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 442, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "C:\Users\User\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\User\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 446, in load_state_dict
    if f.read(7) == "version":
  File "C:\Users\User\Downloads\oobabooga-windows\installer_files\env\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 389: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Downloads\oobabooga-windows\text-generation-webui\server.py", line 302, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\User\Downloads\oobabooga-windows\text-generation-webui\modules\models.py", line 170, in load_model
    model = AutoModelForCausalLM.from_pretrained(checkpoint, **params)
  File "C:\Users\User\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\User\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2736, in from_pretrained
    ) = cls._load_pretrained_model(
  File "C:\Users\User\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 3050, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "C:\Users\User\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 458, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for 'models\chavinlo_gpt4-x-alpaca\pytorch_model-00001-of-00006.bin' at 'models\chavinlo_gpt4-x-alpaca\pytorch_model-00001-of-00006.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
Press any key to continue . . .
```

**Comment by Pyroglyph** [comment]
I checked my model files and found that one of the parts that was supposed to be over 9GB was under 3GB. Redownloading that part manually from Hugging Face worked.
