### ISSUE TITLE
libbitsandbytes_cpu.so not designed to run on windows

### ISSUE THREAD

**Issue by gruevy** [oobabooga/text-generation-webui#659]
### Describe the bug

Can't even get the webui started.

Every time I update I have to copy over the libbitsandbytes_cuda116.dll and make the two changes in the main.py, and a few weeks ago when I did that it worked. Now, after applying that fix, I get an error message in windows that reads,

d:\stable diffusion\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or software vendor for support. Error status 0xc0000112f.

The console then displays the text found in the logs section below

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I deleted and did a full reinstall, problem persisted

### Logs

```shell
Starting the web UI...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
D:\stable diffusion\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('D')}
  warn(msg)
D:\stable diffusion\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: D:\stable diffusion\oobabooga\installer_files\env did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
D:\stable diffusion\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/D'), WindowsPath('/stable%20diffusion/oobabooga/installer_files/env/etc/xml/catalog'), WindowsPath('file')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
D:\stable diffusion\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(msg)
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
D:\stable diffusion\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
D:\stable diffusion\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Loading binary D:\stable diffusion\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
[WinError 193] %1 is not a valid Win32 application
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: Loading binary D:\stable diffusion\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
[WinError 193] %1 is not a valid Win32 application
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: Loading binary D:\stable diffusion\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
[WinError 193] %1 is not a valid Win32 application
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Traceback (most recent call last):
  File "D:\stable diffusion\oobabooga\text-generation-webui\server.py", line 13, in <module>
    from modules import chat, shared, training, ui
  File "D:\stable diffusion\oobabooga\text-generation-webui\modules\training.py", line 12, in <module>
    from peft import (LoraConfig, get_peft_model, get_peft_model_state_dict,
  File "D:\stable diffusion\oobabooga\installer_files\env\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "D:\stable diffusion\oobabooga\installer_files\env\lib\site-packages\peft\mapping.py", line 16, in <module>
    from .peft_model import (
  File "D:\stable diffusion\oobabooga\installer_files\env\lib\site-packages\peft\peft_model.py", line 31, in <module>
    from .tuners import LoraModel, PrefixEncoder, PromptEmbedding, PromptEncoder
  File "D:\stable diffusion\oobabooga\installer_files\env\lib\site-packages\peft\tuners\__init__.py", line 20, in <module>
    from .lora import LoraConfig, LoraModel
  File "D:\stable diffusion\oobabooga\installer_files\env\lib\site-packages\peft\tuners\lora.py", line 36, in <module>
    import bitsandbytes as bnb
  File "D:\stable diffusion\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\__init__.py", line 7, in <module>
    from .autograd._functions import (
  File "D:\stable diffusion\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\autograd\__init__.py", line 1, in <module>
    from ._functions import undo_layout, get_inverse_transform_indices
  File "D:\stable diffusion\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\autograd\_functions.py", line 9, in <module>
    import bitsandbytes.functional as F
  File "D:\stable diffusion\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "D:\stable diffusion\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\cextension.py", line 22, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues
Press any key to continue . . .
```

### System Info

```shell
Win 11, 4090
```

**Comment by AndreyRGW** [comment]
Same

**Comment by jllllll** [comment]
Make sure you are using the latest version of the installer here: https://github.com/oobabooga/one-click-installers

**Comment by gruevy** [comment]
When i tried the fresh install, I also re-downloaded the one-click installer.

**Comment by jllllll** [comment]
> When i tried the fresh install, I also re-downloaded the one-click installer.

Just wanted to clarify, as the zip linked in the releases section is out-dated.

**Comment by gruevy** [comment]
I just doublechecked and the crc32 for the files I used are the same as the one you just linked, so I'm pretty sure it's the same ones.

**Comment by jllllll** [comment]
> I just doublechecked and the crc32 for the files I used are the same as the one you just linked, so I'm pretty sure it's the same ones.

Were there any errors during the install?

**Comment by gruevy** [comment]
Huh. I just deleted and reinstalled with the files you linked to see if there were indeed any errors and this time it worked. I have no idea why, unless it's the presence of 'micromamba-cmd.bat' which wasn't there before. That or winrar was lying about the CRC. But it's running now. Thanks!

**Comment by JohnWJarrett** [comment]
I am getting this exact same error, I am not using the install script as that doesn't work for me either, I just ran a git pull and got some error about not finding the DataSet module or some such then I did a "pip install -r requirements.txt" and now I am getting the OP error...

**Comment by jllllll** [comment]
> I am getting this exact same error, I am not using the install script as that doesn't work for me either, I just ran a git pull and got some error about not finding the DataSet module or some such then I did a "pip install -r requirements.txt" and now I am getting the OP error...

I compiled a Windows-compatible version of bitsandbytes to solve these problems:
https://github.com/jllllll/bitsandbytes-windows-webui

To download and install the wheel, run this command:
```
python -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/raw/main/bitsandbytes-0.37.2-py3-none-any.whl --force-reinstall
```

**Comment by JohnWJarrett** [comment]
> > I am getting this exact same error, I am not using the install script as that doesn't work for me either, I just ran a git pull and got some error about not finding the DataSet module or some such then I did a "pip install -r requirements.txt" and now I am getting the OP error...
> 
> I compiled a Windows-compatible version of bitsandbytes to solve these problems: https://github.com/jllllll/bitsandbytes-windows-webui
> 
> To download and install the wheel, run this command:
> 
> ```
> python -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/raw/main/bitsandbytes-0.37.2-py3-none-any.whl --force-reinstall
> ```

Yes, that worked perfectly

**Comment by jackylee1** [comment]
> > I am getting this exact same error, I am not using the install script as that doesn't work for me either, I just ran a git pull and got some error about not finding the DataSet module or some such then I did a "pip install -r requirements.txt" and now I am getting the OP error...
> 
> I compiled a Windows-compatible version of bitsandbytes to solve these problems: https://github.com/jllllll/bitsandbytes-windows-webui
> 
> To download and install the wheel, run this command:
> 
> ```
> python -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/raw/main/bitsandbytes-0.37.2-py3-none-any.whl --force-reinstall
> ```
i got the error
CUDA SETUP: Loading binary C:\Users\Administrator\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll...
C:\Users\Administrator\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading llama-13b-hf...
Warning: torch.cuda.is_available() returned False.
This means that no GPU has been detected.
Falling back to CPU mode.

**Comment by jllllll** [comment]
@jackylee1 Make sure that you have the gpu version of torch. Sometimes the cpu version gets installed if you don't explicitly tell it to install the gpu version. I can see that you are using miniconda. You can use this command to ensure that you get the right version:
```
conda install pytorch[version=2,build=py3.10_cuda11.7*] pytorch-cuda=11.7 -c pytorch -c nvidia/label/cuda-11.7.0 -c nvidia
```
Other than that, there are just too many things that can cause torch to not detect cuda.

**Comment by jackylee1** [comment]
> conda install pytorch[version=2,build=py3.10_cuda11.7*] pytorch-cuda=11.7 -c pytorch -c nvidia/label/cuda-11.7.0 -c nvidia

(textgen) PS D:\OoBaboogachatglm\text-generation-webui> python server.py --model llama-13b-hf --load-in-8bit

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
C:\Users\Administrator\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\cuda_setup\main.py:141: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('C:/Users/Administrator/miniconda3/envs/textgen/bin')}
  warn(msg)
C:\Users\Administrator\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\cuda_setup\main.py:141: UserWarning: C:\Users\Administrator\miniconda3\envs\textgen did not contain cudart64_110.dll as expected! Searching further paths...
  warn(msg)
C:\Users\Administrator\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\cuda_setup\main.py:141: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('C:/Users/Administrator/miniconda3/envs/textgen/Library/mingw-w64/bin'), WindowsPath('C:/Users/Administrator/AppData/Roaming/npm'), WindowsPath('C:/Users/Administrator/miniconda3/envs/textgen/bin'), WindowsPath('C:/Users/Administrator/miniconda3/envs/textgen/Library/usr/bin')}
  warn(msg)
C:\Users\Administrator\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\cuda_setup\main.py:141: UserWarning: C:\Users\Administrator\miniconda3\envs\textgen;C:\Users\Administrator\miniconda3\envs\textgen\Library\mingw-w64\bin;C:\Users\Administrator\miniconda3\envs\textgen\Library\usr\bin;C:\Users\Administrator\miniconda3\envs\textgen\Library\bin;C:\Users\Administrator\miniconda3\envs\textgen\Scripts;C:\Users\Administrator\miniconda3\envs\textgen\bin;C:\Users\Administrator\miniconda3\condabin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\libnvvp;C:\Program Files (x86)\VMware\VMware Workstation\bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0;C:\windows\System32\OpenSSH;C:\Program Files (x86)\Common Files\Acronis\VirtualFile;C:\Program Files (x86)\Common Files\Acronis\VirtualFile64;C:\Program Files (x86)\Common Files\Acronis\FileProtector;C:\Program Files (x86)\Common Files\Acronis\FileProtector64;C:\Program Files (x86)\Common Files\Acronis\SnapAPI;d:\Program Files\Git\cmd;C:\Program Files\dotnet;C:\Program Files\NVIDIA Corporation\Nsight Compute 2023.1.0;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;d:\Program Files (x86)\Tencent\微信web开发者工具\dll;d:\Program Files\Microsoft VS Code\bin;C:\ProgramData\chocolatey\bin;D:\Program Files\maven-3.6.3\bin;C:\Program Files\Java\jdk1.8.0_131\bin;C:\Program Files\Java\jdk1.8.0_131\jre\bin;D:\Program Files\Redis;C:\Program Files\nodejs;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin;C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Scripts;C:\Users\Administrator\AppData\Local\Programs\Python\Python310;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;d:\Program Files\JetBrains\IntelliJ IDEA 2020.1\bin;.;C:\Users\Administrator\AppData\Roaming\npm;. did not contain cudart64_110.dll as expected! Searching further paths...
  warn(msg)
C:\Users\Administrator\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\cuda_setup\main.py:141: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/Users/Administrator')}
  warn(msg)
C:\Users\Administrator\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\cuda_setup\main.py:141: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/MS-RXXOBASFNEGC')}
  warn(msg)
C:\Users\Administrator\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\cuda_setup\main.py:141: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('C:/Users/Administrator/Documents/WindowsPowerShell/Modules')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
C:\Users\Administrator\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\cuda_setup\main.py:141: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(msg)
ERROR: libcudart.so could not be read from path: None!
C:\Users\Administrator\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\cuda_setup\main.py:141: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version None
CUDA SETUP: Loading binary C:\Users\Administrator\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll...
C:\Users\Administrator\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading llama-13b-hf...
Traceback (most recent call last):
  File "D:\OoBaboogachatglm\text-generation-webui\server.py", line 347, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\OoBaboogachatglm\text-generation-webui\modules\models.py", line 171, in load_model
    model = AutoModelForCausalLM.from_pretrained(checkpoint, **params)
  File "C:\Users\Administrator\miniconda3\envs\textgen\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\Administrator\miniconda3\envs\textgen\lib\site-packages\transformers\modeling_utils.py", line 2681, in from_pretrained
    raise ValueError(
ValueError:
                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you want to dispatch the model on the CPU or the disk while keeping
                        these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom
                        `device_map` to `from_pretrained`. Check
                        https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                        for more details.


i am exhausted

**Comment by jllllll** [comment]
@jackylee1 I assumed that all you were missing was Pytorch, seems like you are also missing cuda toolkit. Here is a more comprehensive command for everything you need.

```
conda install pytorch[version=2,build=py3.10_cuda11.7*] torchvision torchaudio pytorch-cuda=11.7 cuda-toolkit -c pytorch -c nvidia/label/cuda-11.7.0 -c nvidia -c conda-forge
```
This should make sure that everything is installed.

There is a reason I wrote that Windows installer. Without automation, installing all of this stuff is an exercise in frustration. Pretty much all of it was designed to be run in Linux. There are Windows versions for everything but bitsandbytes. However, they just don't work very well and often behave completely different on other systems. For instance, I don't experience the vast majority of errors that people report and I don't know why.

If the main installer didn't work for you, consider trying one of the other versions on my repo: https://github.com/jllllll/one-click-installers
They are separated into different branches. I've heard that the miniconda one tends to work better on systems that don't like the main one.

**Comment by yousonnet** [comment]
> > I am getting this exact same error, I am not using the install script as that doesn't work for me either, I just ran a git pull and got some error about not finding the DataSet module or some such then I did a "pip install -r requirements.txt" and now I am getting the OP error...
> 
> I compiled a Windows-compatible version of bitsandbytes to solve these problems: https://github.com/jllllll/bitsandbytes-windows-webui
> 
> To download and install the wheel, run this command:
> 
> ```
> python -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/raw/main/bitsandbytes-0.37.2-py3-none-any.whl --force-reinstall
> ```

it work well for me

**Comment by ernesttan1976** [comment]
I'm very frustrated with the bitsandbytes for windows. I will uninstall and switch to using Docker images and Linux.  Wasted many days on this.

**Comment by mongolu** [comment]
I are you in the need of a Dockerfile?🙂
I've made one which uses one-click-installers, with docker-compose.

**Comment by gayathrik948** [comment]
@ernesttan1976  can you please share  the dockerfile here
