### ISSUE TITLE
size mismatch for model layers

### ISSUE THREAD

**Issue by fidecastro** [oobabooga/text-generation-webui#668]
### Describe the bug

Using 4bit quantizations of Alpaca-Lora. I tried for both 13B-4bit and 30B-4bit, which are still working a previous version (cloned Mar 23).

The model seems to be inverting the dimensions (see below).

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Git clone current repository, installing GPTQ-for-LLaMa following the latest procedure (ie getting the previous-to-last version since the latest is not backwards-compatible), then running

python3 server.py --wbits 4

and then selecting the model

### Logs

```shell
Traceback (most recent call last):
  File "/ffai/textgen-alpaca-mind/server.py", line 274, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ffai/textgen-alpaca-mind/modules/models.py", line 101, in load_model
    model = load_quantized(model_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ffai/textgen-alpaca-mind/modules/GPTQ_loader.py", line 114, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.wbits, shared.args.groupsize, kernel_switch_threshold=threshold)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ffai/textgen-alpaca-mind/modules/GPTQ_loader.py", line 45, in _load_quant
    model.load_state_dict(torch.load(checkpoint))
  File "/anaconda/envs/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LlamaForCausalLM:
issing key(s) in state_dict: "model.layers.0.self_attn.k_proj.qzeros", "model.layers.0.self_attn.o_proj.qzeros", "model.layers.0.self_attn.q_proj.qzeros", "model.layers.0.self_attn.v_proj.qzeros", "model.layers.0.mlp.down_proj.qzeros", "model.layers.0.mlp.gate_proj.qzeros", "model.layers.0.mlp.up_proj.qzeros", "model.layers.1.self_attn.k_proj.qzeros", "model.layers.1.self_attn.o_proj.qzeros", "model.layers.1.self_attn.q_proj.qzeros", "model.layers.1.self_attn.v_proj.qzeros", "model.layers.1.mlp.down_proj.qzeros", "model.layers.1.mlp.gate_proj.qzeros", "model.layers.1.mlp.up_proj.qzeros", "model.layers.2.self_attn.k_proj.qzeros", 

(... goes on for all layers...)

size mismatch for model.layers.0.self_attn.k_proj.scales: copying a param with shape torch.Size([5120, 1]) from checkpoint, the shape in current model is torch.Size([1, 5120]).
	size mismatch for model.layers.0.self_attn.o_proj.scales: copying a param with shape torch.Size([5120, 1]) from checkpoint, the shape in current model is torch.Size([1, 5120]).
	size mismatch for model.layers.0.self_attn.q_proj.scales: copying a param with shape torch.Size([5120, 1]) from checkpoint, the shape in current model is torch.Size([1, 5120]).
	size mismatch for model.layers.0.self_attn.v_proj.scales: copying a param with shape torch.Size([5120, 1]) from checkpoint, the shape in current model is torch.Size([1, 5120]).
	size mismatch for model.layers.0.mlp.down_proj.scales: copying a param with shape torch.Size([5120, 1]) from checkpoint, the shape in current model is torch.Size([1, 5120]).
	size mismatch for model.layers.0.mlp.gate_proj.scales: copying a param with shape torch.Size([13824, 1]) from checkpoint, the shape in current model is torch.Size([1, 13824]).
	size mismatch for model.layers.0.mlp.up_proj.scales: copying a param with shape torch.Size([13824, 1]) from checkpoint, the shape in current model is torch.Size([1, 13824]).
	size mismatch for model.layers.1.self_attn.k_proj.scales: copying a param with shape torch.Size([5120, 1]) from checkpoint, the shape in current model is torch.Size([1, 5120]).

(... goes on for all layers)
```

### System Info

```shell
Ubuntu 22.04, Nvidia RTX4090
```

**Comment by thot-experiment** [comment]
Same issue, fresh install w/ the easy installer, moved my 4bit models over and I get this error.

**Comment by ConflyctX** [comment]
I had the same problem with the .pt file format, but by using 30B as .safetensors I was able to load the model in.

You can find the .safetensor files here:
magnet:?xt=urn:btih:rd35tusgb76k66fsd2bqclpabe46vs3f&dn=LLaMA-HF-4bit-128g&xl=65238528057&fc=28

**Comment by fidecastro** [comment]
Great @ConflyctX. I can confirm that this model version works as a solution, although I'd prefer using the Alpaca one I got.

**Comment by thot-experiment** [comment]
yeah, i can confirm that this works with the safetensors version. Is there a place I can look in the future that tracks these sorts of regressions/breaking changes.
