### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by shm007g** [oobabooga/text-generation-webui#677]
### Describe the bug

pull master branch, and server down!! can't deploy with 8-bit anymore.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

deploy with this model: https://huggingface.co/nlpcloud/instruct-gpt-j-fp16.

last week it works fine. yesterday I pull the master branch code, server down!

### Logs

```shell
python server.py --cpu --load-in-8bit --no-cache --model instruct-gpt-j-fp16 --listen --share --verbose --listen-port 5860
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "server.py", line 13, in <module>
    from modules import chat, shared, training, ui
  File "/home/oppo/work/smm/text-generation-webui/modules/chat.py", line 15, in <module>
    from modules.text_generation import (encode, generate_reply,
  File "/home/oppo/work/smm/text-generation-webui/modules/text_generation.py", line 11, in <module>
    from modules.callbacks import (Iteratorize, Stream,
  File "/home/oppo/work/smm/text-generation-webui/modules/callbacks.py", line 13, in <module>
    class _SentinelTokenStoppingCriteria(transformers.StoppingCriteria):
  File "/home/oppo/work/smm/text-generation-webui/modules/callbacks.py", line 15, in _SentinelTokenStoppingCriteria
    def __init__(self, sentinel_token_ids: list[torch.LongTensor], starting_idx: int):
TypeError: 'type' object is not subscriptable
```
```


### System Info

```shell
ubuntu 18 LTS
```

**Comment by oobabooga** [comment]
https://github.com/oobabooga/text-generation-webui/pull/678
