### ISSUE TITLE
One click install fails on windows 10

### ISSUE THREAD

**Issue by franzkruhm** [oobabooga/text-generation-webui#680]
### Describe the bug

apparently the bandaid section uses unsupported commands like mv and sed...
also attempting to start the webui ends with "no module named jaxlib"

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

run install script on a normal cmd
it fails during the bandaid section

try to start webui: "no module named jaxlib"

### Logs

```shell
Traceback (most recent call last):
  File "D:\oobabooga-windows\oobabooga-windows\text-generation-webui\server.py", line 13, in <module>
    from modules import chat, shared, training, ui
  File "D:\oobabooga-windows\oobabooga-windows\text-generation-webui\modules\chat.py", line 15, in <module>
    from modules.text_generation import (encode, generate_reply,
  File "D:\oobabooga-windows\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 8, in <module>
    import transformers
  File "C:\Users\zanfr\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "C:\Users\zanfr\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "C:\Users\zanfr\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\__init__.py", line 30, in <module>
    from .generic import (
  File "C:\Users\zanfr\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\generic.py", line 33, in <module>
    import jax.numpy as jnp
  File "C:\Users\zanfr\AppData\Local\Programs\Python\Python310\lib\site-packages\jax\__init__.py", line 21, in <module>
    from .config import config
  File "C:\Users\zanfr\AppData\Local\Programs\Python\Python310\lib\site-packages\jax\config.py", line 19, in <module>
    from jax import lib
  File "C:\Users\zanfr\AppData\Local\Programs\Python\Python310\lib\site-packages\jax\lib\__init__.py", line 23, in <module>
    import jaxlib
ModuleNotFoundError: No module named 'jaxlib'
```

### System Info

```shell
Windows 10
```

**Comment by jllllll** [comment]
Installer was just updated: https://github.com/oobabooga/one-click-installers/pull/6
Bandaid section has been removed and a wheel is now used for bitsandbytes.

**Comment by franzkruhm** [comment]
alright this solves the install issue but I still get "no module named jaxlib"

**Comment by jllllll** [comment]
> alright this solves the install issue but I still get "no module named jaxlib"

That's weird. Jaxlib should have been automatically installed as a required dependency. You can install it manually by running this command in micromamba-cmd.bat: `python -m pip install jaxlib`

**Comment by jllllll** [comment]
Looking at your logs again, and it seems like it is trying to load modules outside of the virtual environment. Are you starting the webui using the included script?

**Comment by franzkruhm** [comment]
Yes I am using the script.

**Comment by franzkruhm** [comment]
> Looking at your logs again, and it seems like it is trying to load modules outside of the virtual environment. Are you starting the webui using the included script? That script includes commands to activate the virtual environment that webui was installed with.

just tried. I get "Couldn't find a version that satisfies for the requirement jaxlib (from version: none)

**Comment by jllllll** [comment]
You may need to reinstall with a shorter file path: `D:\oobabooga-windows`

It may also be an issue with your system just not working well with Micromamba. I've seen a couple reports with similar module loading issues. You can try this alternative installer which may work better: [oobabooga-windows-miniconda](https://github.com/jllllll/one-click-installers/tree/oobabooga-windows-miniconda)

It uses Miniconda instead of Micromamba. Micromamba is still in development and is essentially still in beta. It is used here by default as it is generally faster than Miniconda.

**Comment by franzkruhm** [comment]
> You may need to reinstall with a shorter file path: `D:\oobabooga-windows`
> 
> It may also be an issue with your system just not working well with Micromamba. I've seen a couple reports with similar module loading issues. You can try this alternative installer which may work better: [oobabooga-windows-miniconda](https://github.com/jllllll/one-click-installers/tree/oobabooga-windows-miniconda)
> 
> It uses Miniconda instead of Micromamba. Micromamba is still in development and is essentially still in beta. It is used here by default as it is generally faster than Miniconda and works well on most systems.

ok the miniconda version works as expected! thanks!
