### ISSUE TITLE
replace_last_reply fails with 'TypeError: 'tuple' object does not support item assignment'

### ISSUE THREAD

**Issue by Spencer-Dawson** [oobabooga/text-generation-webui#69]
Latest Main branch code as of 2/11/23

Happens every time for me.

Running in chat mode "python3 server.py --chat"
Just add text to the Input box then hit the 'Replace last reply' button

Error message in console is

Traceback (most recent call last):
  File "/home/spencer/.local/lib/python3.10/site-packages/gradio/routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "/home/spencer/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "/home/spencer/.local/lib/python3.10/site-packages/gradio/blocks.py", line 856, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/spencer/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/spencer/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/spencer/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/spencer/Projects/text-generation-webui/server.py", line 540, in replace_last_reply
    history['visible'][-1][1] = text
TypeError: 'tuple' object does not support item assignment

**Comment by oobabooga** [comment]
This was indeed a bug. It has been fixed now.

Replacing the last reply in --chat mode is weird in that gradio's default chat widget turns outputs into html, so the message comes full of <p> tags.

**Comment by Spencer-Dawson** [comment]
I can confirm you're commit from this morning fixed it for me so consider this closed as far as I am concerned. 

You're comment about the html tags has me wondering if something should be done about the instances where the ui dumps items from the log in the input prompt though. Specifically clicking "Send last reply to input" and "Remove Last". There may be other examples that I am missing. Impersonate seems to work as intended at least. I guess that could be a seperate bug ticket.
