### ISSUE TITLE
Cannot load llama-7b-hf

### ISSUE THREAD

**Issue by franzkruhm** [oobabooga/text-generation-webui#697]
### Describe the bug

I get the following error when trying to load llama-7b-hf

`Loading llama-7b-hf...
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████| 33/33 [00:30<00:00,  1.07it/s]
Traceback (most recent call last):
  File "D:\ooba\text-generation-webui\server.py", line 275, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\ooba\text-generation-webui\modules\models.py", line 176, in load_model
    tokenizer = AutoTokenizer.from_pretrained(Path(f"{shared.args.model_dir}/{shared.model_name}/"))
  File "D:\ooba\installer_files\env\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 691, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Install on Win10 using miniconda one click installl.
Put llama-7b-hf (downloaded from huggin face)
Start webui with python server.py --listen --gpu-memory 10 --load-in-8bit --auto-devices --cai-chat

### Logs

```shell
Loading llama-7b-hf...
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████| 33/33 [00:30<00:00,  1.07it/s]
Traceback (most recent call last):
  File "D:\ooba\text-generation-webui\server.py", line 275, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\ooba\text-generation-webui\modules\models.py", line 176, in load_model
    tokenizer = AutoTokenizer.from_pretrained(Path(f"{shared.args.model_dir}/{shared.model_name}/"))
  File "D:\ooba\installer_files\env\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 691, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.
```

### System Info

```shell
Win10, 3060 12G
```

**Comment by EyeDeck** [comment]
That's the `LLaMATokenizer` / `LlamaTokenizer` thing; open up tokenizer_config.json and replace the former with the latter.

**Comment by franzkruhm** [comment]
that did it thanks!
