### ISSUE TITLE
Error on Text Generation Related to Memory Management

### ISSUE THREAD

**Issue by ZachLorenzo** [oobabooga/text-generation-webui#7]
Was able to load the Pygmalion-6b model and even got a few lines of text back and forth before I hit an error and got the below text in the Anaconda Powershell Prompt:
```Traceback (most recent call last):
  File "C:\Users\Zach\miniconda3\envs\textgen\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\Zach\miniconda3\envs\textgen\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "C:\Users\Zach\miniconda3\envs\textgen\lib\site-packages\gradio\blocks.py", line 847, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Zach\miniconda3\envs\textgen\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Zach\miniconda3\envs\textgen\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Zach\miniconda3\envs\textgen\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "I:\text-generation-webui\server.py", line 245, in cai_chatbot_wrapper
    history = chatbot_wrapper(text, tokens, inference_settings, selected_model, name1, name2, context, check)
  File "I:\text-generation-webui\server.py", line 231, in chatbot_wrapper
    reply = generate_reply(question, tokens, inference_settings, selected_model, eos_token='\n')[0]
  File "I:\text-generation-webui\server.py", line 149, in generate_reply
    output = eval(f"model.generate(input_ids, eos_token_id={n}, {preset}){cuda}")
  File "<string>", line 1, in <module>
  File "C:\Users\Zach\miniconda3\envs\textgen\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Zach\miniconda3\envs\textgen\lib\site-packages\transformers\generation\utils.py", line 1571, in generate
    return self.sample(
  File "C:\Users\Zach\miniconda3\envs\textgen\lib\site-packages\transformers\generation\utils.py", line 2534, in sample
    outputs = self(
  File "C:\Users\Zach\miniconda3\envs\textgen\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Zach\miniconda3\envs\textgen\lib\site-packages\accelerate\hooks.py", line 156, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\Users\Zach\miniconda3\envs\textgen\lib\site-packages\transformers\models\gptj\modeling_gptj.py", line 844, in forward
    lm_logits = self.lm_head(hidden_states).to(torch.float32)
  File "C:\Users\Zach\miniconda3\envs\textgen\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Zach\miniconda3\envs\textgen\lib\site-packages\accelerate\hooks.py", line 151, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "C:\Users\Zach\miniconda3\envs\textgen\lib\site-packages\accelerate\hooks.py", line 264, in pre_forward
    set_module_tensor_to_device(module, name, self.execution_device, value=self.weights_map[name])
  File "C:\Users\Zach\miniconda3\envs\textgen\lib\site-packages\accelerate\utils\modeling.py", line 123, in set_module_tensor_to_device
    new_value = value.to(device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 394.00 MiB (GPU 0; 8.00 GiB total capacity; 6.37 GiB already allocated; 0 bytes free; 6.77 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF```

Server started with command ```python server.py --cai-chat --model pygmalion-6b --auto-devices```

System specs are
Processor: i7-11700k
Graphics: GTX-1080, 8GB vRam
RAM: 32GB ram
OS: Windows 10 Enterprise LTSC

My understanding was --auto-devices would split the ram needs up so as to not need the expected amount of vRAM since clearly my card doesn't have enough. If I was wrong about what the --auto-devices command does please close this issue.

**Comment by oobabooga** [comment]
I have implemented the `--max-gpu-memory MAX_GPU_MEMORY` for this. The problem is that you have just enough space to fit the entire model into your GPU, leaving only a few MiB left for inference when you load the model with `--auto-devices`. So it's necessary to manually limit the maximum GPU usage.

Can you try this?

`python server.py --cai-chat --model pygmalion-6b --max-gpu-memory 6`

You may need to tinker with the parameter to see the largest value that you can use before the webui OOMs when you click on Generate.

**Comment by ZachLorenzo** [comment]
Thanks, this seems to have fixed it. Getting responses in a pretty reasonable time without hitting the error.
