### ISSUE TITLE
GPTQ install CUDA error with 4090

### ISSUE THREAD

**Issue by charleschen2006** [oobabooga/text-generation-webui#726]
### Describe the bug

I can not install the cuda for my 4090. 
I tried install HIP 5.3.22061,  with cuda 12.1 support, but it doesn't help.  
nvcc --version = nvcc cuda_11.7.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

mkdir repositories
cd repositories
git clone https://github.com/oobabooga/GPTQ-for-LLaMa.git -b cuda
cd GPTQ-for-LLaMa
python setup_cuda.py install

### Screenshot

![f9aecdc003661b84a1ef8df002700b0e](https://user-images.githubusercontent.com/117791582/229365934-43ca74dc-09a0-4adc-a461-729fefea678d.png)

### Logs

```shell
(textgen) charles@charles-B550I-AORUS-PRO-AX2:~/JQZX/text-generation-webui/repositories/GPTQ-for-LLaMa$ python setup_cuda.py install
Traceback (most recent call last):
  File "/home/charles/JQZX/text-generation-webui/repositories/GPTQ-for-LLaMa/setup_cuda.py", line 2, in <module>
    from torch.utils import cpp_extension
  File "/home/charles/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 19, in <module>
    from .hipify import hipify_python
  File "/home/charles/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/hipify/hipify_python.py", line 34, in <module>
    from .cuda_to_hip_mappings import CUDA_TO_HIP_MAPPINGS
  File "/home/charles/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/hipify/cuda_to_hip_mappings.py", line 34, in <module>
    rocm_path = subprocess.check_output(["hipconfig", "--rocmpath"]).decode("utf-8")
  File "/home/charles/miniconda3/envs/textgen/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/charles/miniconda3/envs/textgen/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/charles/miniconda3/envs/textgen/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/charles/miniconda3/envs/textgen/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: 'hipconfig'
```

### System Info

```shell
ubuntu 20.04.6 LTS GPU 4090 CPU 5900x
```

**Comment by jllllll** [comment]
Isn't rocm specifically for AMD GPUs? Why are you trying to compile with it?

**Comment by charleschen2006** [comment]
for there is an error. can not find hipconfig when I try to install cuda setup.

**Comment by jllllll** [comment]
This error is an issue with rocm, which you don't need because you have an nvidia gpu. If I had to guess, you installed the rocm version of torch. You need the cuda version.

**Comment by charleschen2006** [comment]
thank you anyway. 
=============================================================================================
(textgen) charles@charles-B550I-AORUS-PRO-AX2:~/JQZX/text-generation-webui$ conda install torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia/label/cuda-11.7.0 -c nvidia
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

**Comment by jllllll** [comment]
`python -m torch.utils.collect_env` will tell you about your torch installation and may hint at whats going on.

**Comment by jllllll** [comment]
I just realized that you need to add `--force-reinstall` to that conda command in order for it to reinstall torch. Sorry about that.

**Comment by charleschen2006** [comment]
(textgen) charles@charles-B550I-AORUS-PRO-AX2:~/JQZX/text-generation-webui$ python -m torch.utils.collect_env #will tell you about your torch installation and may hint at whats going on.
Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-6ubuntu2) 7.5.0
Clang version: Could not collect
CMake version: version 3.26.1
Libc version: glibc-2.31

Python version: 3.10.9 (main, Mar  8 2023, 10:47:38) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 530.30.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
架构：                           x86_64
CPU 运行模式：                   32-bit, 64-bit
字节序：                         Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU:                             24
在线 CPU 列表：                  0-23
每个核的线程数：                 2
每个座的核数：                   12
座：                             1
NUMA 节点：                      1
厂商 ID：                        AuthenticAMD
CPU 系列：                       25
型号：                           33
型号名称：                       AMD Ryzen 9 5900X 12-Core Processor
步进：                           0
Frequency boost:                 enabled
CPU MHz：                        2200.000
CPU 最大 MHz：                   3700.0000
CPU 最小 MHz：                   2200.0000
BogoMIPS：                       7386.13
虚拟化：                         AMD-V
L1d 缓存：                       384 KiB
L1i 缓存：                       384 KiB
L2 缓存：                        6 MiB
L3 缓存：                        64 MiB
NUMA 节点0 CPU：                 0-23
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
标记：                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.0
[pip3] torchvision==0.15.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit-dev           11.7.0               h1de0b5d_6    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0           py310h7f8727e_0  
[conda] mkl_fft                   1.3.1           py310hd6ae3a3_0  
[conda] mkl_random                1.2.2           py310h00e6091_0  
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] numpy-base                1.23.5          py310h8e6c178_0  
[conda] pytorch                   2.0.0           py3.10_cuda11.7_cudnn8.5.0_0    pytorch
[conda] pytorch-cuda              11.7                 h778d358_3    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     2.0.0                    pypi_0    pypi
[conda] torchaudio                2.0.0               py310_cu117    pytorch
[conda] torchtriton               2.0.0                     py310    pytorch
[conda] torchvision               0.15.0              py310_cu117    pytorch

**Comment by charleschen2006** [comment]
I re-installed the lib and it doesn't help. 
Is that HIP runtime version N/A  the key point?
================================================================================================
(textgen) charles@charles-B550I-AORUS-PRO-AX2:~/JQZX/text-generation-webui$ conda install torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia/label/cuda-11.7.0 -c nvidia --force-reinstall
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/charles/miniconda3/envs/textgen

  added / updated specs:
    - pytorch-cuda=11.7
    - torchaudio
    - torchvision



Proceed ([y]/n)? y


Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(textgen) charles@charles-B550I-AORUS-PRO-AX2:~/JQZX/text-generation-webui$ cd repositories/GPTQ-for-LLaMa/

**Comment by jllllll** [comment]
> Is that HIP runtime version N/A the key point?

The issue is that it shouldn't be using HIP at all. The reason it is trying to is because it is attempting to compile the kernels using ROCm. You shouldn't even have ROCm given that you don't use an AMD gpu. Trying to find information online about this is pretty difficult as basically nobody with an NVIDIA gpu has ROCm. The only thing I found that you can try is this:
`USE_ROCM=0 python setup_cuda.py install`

You might have to uninstall ROCm to get this to work if that command doesn't help.
