### ISSUE TITLE
If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

### ISSUE THREAD

**Issue by rzg0ld3n** [oobabooga/text-generation-webui#74]
On trying to load the web UI:

```
Loading pygmalion-6b...
Loading checkpoint shards:  50%|████████████████████████████▌                            | 1/2 [00:30<00:30, 30.71s/it]
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\textgen\lib\site-packages\transformers\modeling_utils.py", line 416, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "C:\Users\User\miniconda3\envs\textgen\lib\site-packages\torch\serialization.py", line 777, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\User\miniconda3\envs\textgen\lib\site-packages\torch\serialization.py", line 282, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\textgen\lib\site-packages\transformers\modeling_utils.py", line 420, in load_state_dict
    if f.read(7) == "version":
  File "C:\Users\User\miniconda3\envs\textgen\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1821: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Pxd\ooba\text-generation-webui\server.py", line 819, in <module>
    model, tokenizer = load_model(model_name)
  File "C:\Pxd\ooba\text-generation-webui\server.py", line 112, in load_model
    model = AutoModelForCausalLM.from_pretrained(Path(f"models/{model_name}"), low_cpu_mem_usage=True, torch_dtype=torch.bfloat16 if args.bf16 else torch.float16).cuda()
  File "C:\Users\User\miniconda3\envs\textgen\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\User\miniconda3\envs\textgen\lib\site-packages\transformers\modeling_utils.py", line 2608, in from_pretrained
    ) = cls._load_pretrained_model(
  File "C:\Users\User\miniconda3\envs\textgen\lib\site-packages\transformers\modeling_utils.py", line 2917, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "C:\Users\User\miniconda3\envs\textgen\lib\site-packages\transformers\modeling_utils.py", line 432, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for 'models\pygmalion-6b\pytorch_model-00002-of-00002.bin' at 'models\pygmalion-6b\pytorch_model-00002-of-00002.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
```

**Comment by oobabooga** [comment]
Your file is probably corrupt. Try re-downloading the model.

**Comment by rzg0ld3n** [comment]
> Your file is probably corrupt. Try re-downloading the model.

I did, but now I get a different error.

```
Traceback (most recent call last):
  File "C:\XboxGames\ooba\text-generation-webui\server.py", line 819, in <module>
    model, tokenizer = load_model(model_name)
  File "C:\XboxGames\ooba\text-generation-webui\server.py", line 150, in load_model
    model = eval(command)
  File "<string>", line 1, in <module>
  File "C:\Users\Usuario\miniconda3\envs\textgen\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\Usuario\miniconda3\envs\textgen\lib\site-packages\transformers\modeling_utils.py", line 2608, in from_pretrained
    ) = cls._load_pretrained_model(
  File "C:\Users\Usuario\miniconda3\envs\textgen\lib\site-packages\transformers\modeling_utils.py", line 2931, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "C:\Users\Usuario\miniconda3\envs\textgen\lib\site-packages\transformers\modeling_utils.py", line 675, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
  File "C:\Users\Usuario\miniconda3\envs\textgen\lib\site-packages\accelerate\utils\modeling.py", line 123, in set_module_tensor_to_device
    new_value = value.to(device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 8.00 GiB total capacity; 7.30 GiB already allocated; 0 bytes free; 7.31 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

I tried manually setting the max GPU memory, but it still gave me this error.

**Comment by Ph0rk0z** [comment]
Add the auto devices parameter.
