### ISSUE TITLE
FlexGen does not work on finetuned OPT models

### ISSUE THREAD

**Issue by Maykeye** [oobabooga/text-generation-webui#741]
### Describe the bug

I tried to use flexgen on [OPT-6B-nerys-v2](https://huggingface.co/KoboldAI/OPT-6B-nerys-v2) (finetune of OPT-6.7B)

However after converting weights,` --flexgen`  does not work 

First it tries to read the config thinking, using original model names and fails:

```console
File "/home/fella/src/sd/sd/lib/python3.10/site-packages/flexgen/opt_config.py", line 118, in get_opt_config
raise ValueError(f"Invalid model name: {name}")
ValueError: Invalid model name: koboldai_opt-6b-nerys-v2
```

Even if I change source code of flexgen package to accept koboldai_opt-6b-nerys-v2 the same way it does opt-6.7b in that place, it decides to ignore existing weights:
```console
Loading KoboldAI_OPT-6B-nerys-v2...
Load the pre-trained pytorch weights of koboldai_opt-6b-nerys-v2 from huggingface. The downloading and cpu loading can take dozens of minutes. If it seems to get stuck, you can monitor the progress by checking the memory usage of this process.
Traceback (most recent call last):
File "/home/fella/src/sd/sd/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 259, in hf_raise_for_status
response.raise_for_status()
File "/home/fella/src/sd/sd/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/facebook/koboldai_opt-6b-nerys-v2/revision/main
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Download OPT-6B-nerys-v2, 
use `convert-to-flexgen.py`,
run python server.py --model KoboldAI_OPT-6B-nerys-v2 --flexgen

### Logs

```shell
Loading KoboldAI_OPT-6B-nerys-v2...
Traceback (most recent call last):
File "/home/fella/src/llama/text-generation-webui/server.py", line 275, in <module>
shared.model, shared.tokenizer = load_model(shared.model_name)
File "/home/fella/src/llama/text-generation-webui/modules/models.py", line 80, in load_model
model = OptLM(f"facebook/{shared.model_name}", env, shared.args.model_dir, policy)
File "/home/fella/src/sd/sd/lib/python3.10/site-packages/flexgen/flex_opt.py", line 589, in __init__
config = get_opt_config(config)
File "/home/fella/src/sd/sd/lib/python3.10/site-packages/flexgen/opt_config.py", line 118, in get_opt_config
raise ValueError(f"Invalid model name: {name}")
ValueError: Invalid model name: koboldai_opt-6b-nerys-v2



---- vvv Trying dirty hack to see if lying about model name will help vvv ----


Loading KoboldAI_OPT-6B-nerys-v2...
Load the pre-trained pytorch weights of koboldai_opt-6b-nerys-v2 from huggingface. The downloading and cpu loading can take dozens of minutes. If it seems to get stuck, you can monitor the progress by checking the memory usage of this process.
Traceback (most recent call last):
File "/home/fella/src/sd/sd/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 259, in hf_raise_for_status
response.raise_for_status()
File "/home/fella/src/sd/sd/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/facebook/koboldai_opt-6b-nerys-v2/revision/main

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/home/fella/src/llama/text-generation-webui/server.py", line 275, in <module>
shared.model, shared.tokenizer = load_model(shared.model_name)
File "/home/fella/src/llama/text-generation-webui/modules/models.py", line 80, in load_model
model = OptLM(f"facebook/{shared.model_name}", env, shared.args.model_dir, policy)
File "/home/fella/src/sd/sd/lib/python3.10/site-packages/flexgen/flex_opt.py", line 637, in __init__
self.init_all_weights()
File "/home/fella/src/sd/sd/lib/python3.10/site-packages/flexgen/flex_opt.py", line 800, in init_all_weights
self.init_weight(j)
File "/home/fella/src/sd/sd/lib/python3.10/site-packages/flexgen/flex_opt.py", line 649, in init_weight
download_opt_weights(self.config.name, self.path)
File "/home/fella/src/sd/sd/lib/python3.10/site-packages/flexgen/opt_config.py", line 218, in download_opt_weights
folder = snapshot_download(hf_model_name, allow_patterns="*.bin")
File "/home/fella/src/sd/sd/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
return fn(*args, **kwargs)
File "/home/fella/src/sd/sd/lib/python3.10/site-packages/huggingface_hub/_snapshot_download.py", line 183, in snapshot_download
repo_info = _api.repo_info(
File "/home/fella/src/sd/sd/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
return fn(*args, **kwargs)
File "/home/fella/src/sd/sd/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 1814, in repo_info
return method(
File "/home/fella/src/sd/sd/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
return fn(*args, **kwargs)
File "/home/fella/src/sd/sd/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 1624, in model_info
hf_raise_for_status(r)
File "/home/fella/src/sd/sd/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 291, in hf_raise_for_status
raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-642aa1d0-2333901b25eec57d2e7aa513)
```

### System Info

```shell
Linux, 3080Ti (mobile)
```

**Comment by mayaeary** [comment]
It's issue with flexgen, there are hardcoded model names and parameters in there. You can manually edit `site-packages/flexgen/opt_config.py` to support nerys and other finetuned models.
