### ISSUE TITLE
transformers broke

### ISSUE THREAD

**Issue by loeken** [oobabooga/text-generation-webui#753]
### Describe the bug

```
text-generation-webui-text-generation-webui-1  | Traceback (most recent call last):
text-generation-webui-text-generation-webui-1  |   File "/app/server.py", line 13, in <module>
text-generation-webui-text-generation-webui-1  |     from modules import chat, shared, training, ui
text-generation-webui-text-generation-webui-1  |   File "/app/modules/chat.py", line 16, in <module>
text-generation-webui-text-generation-webui-1  |     from modules.text_generation import (encode, generate_reply,
text-generation-webui-text-generation-webui-1  |   File "/app/modules/text_generation.py", line 8, in <module>
text-generation-webui-text-generation-webui-1  |     import transformers
text-generation-webui-text-generation-webui-1  | ModuleNotFoundError: No module named 'transformers'
```

seems to be a new breaking change from transformers repo

suggested fix: set a fixed version for transformers in requirements.txt to avoid pulling in problems from transformers

i defined a version in my requirements.txt from yesterday which seemed to have fixed it
```
git+https://github.com/huggingface/transformers@c612628045822f909020f7eb6784c79700813eda
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

pip install -r requirements.txt then start the app

### Logs

```shell
text-generation-webui-text-generation-webui-1  | Traceback (most recent call last):
text-generation-webui-text-generation-webui-1  |   File "/app/server.py", line 13, in <module>
text-generation-webui-text-generation-webui-1  |     from modules import chat, shared, training, ui
text-generation-webui-text-generation-webui-1  |   File "/app/modules/chat.py", line 16, in <module>
text-generation-webui-text-generation-webui-1  |     from modules.text_generation import (encode, generate_reply,
text-generation-webui-text-generation-webui-1  |   File "/app/modules/text_generation.py", line 8, in <module>
text-generation-webui-text-generation-webui-1  |     import transformers
text-generation-webui-text-generation-webui-1  | ModuleNotFoundError: No module named 'transformers'
```

### System Info

```shell
tested on ubuntu 22.04 / nvidia 3090
```

**Comment by jllllll** [comment]
Works fine on Windows. Could be a Linux-specific issue. Maybe transformers failed to install the first time?

**Comment by XuehaiPan** [comment]
You may run:

```bash
python3 -m pip install --upgrade pip setuptools
```

before installing `tansformers`.

Results in a fresh `ubuntu:22.04` docker container:

```console
docker run -it --rm -h ubuntu --pull always ubuntu:22.04         
22.04: Pulling from library/ubuntu
Digest: sha256:67211c14fa74f070d27cc59d69a7fa9aeff8e28ea118ef3babc295a0428a6d21
Status: Image is up to date for ubuntu:22.04
root@ubuntu:/# apt update && apt install git python3-dev python3-pip -y

root@ubuntu:/# which -a python3
/usr/bin/python3
/bin/python3
root@ubuntu:/# which -a pip3
/usr/bin/pip3
/bin/pip3
root@ubuntu:/# python3 -m pip install --upgrade pip setuptools
Requirement already satisfied: pip in /usr/lib/python3/dist-packages (22.0.2)
Collecting pip
  Downloading pip-23.0.1-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 817.6 kB/s eta 0:00:00
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (59.6.0)
Collecting setuptools
  Downloading setuptools-67.6.1-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 540.5 kB/s eta 0:00:00
Installing collected packages: setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 59.6.0
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'setuptools'. No files were found to uninstall.
  Attempting uninstall: pip
    Found existing installation: pip 22.0.2
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'pip'. No files were found to uninstall.
Successfully installed pip-23.0.1 setuptools-67.6.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@ubuntu:/# which -a pip3
/usr/local/bin/pip3
/usr/bin/pip3
/bin/pip3
root@ubuntu:/# python3 -m pip install git+https://github.com/huggingface/transformers
Collecting git+https://github.com/huggingface/transformers
  Cloning https://github.com/huggingface/transformers to /tmp/pip-req-build-861hr7ct
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers /tmp/pip-req-build-861hr7ct
  Resolved https://github.com/huggingface/transformers to commit 41a2f3529c6b56866c317031375ffd3e7b8bea01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting requests
  Downloading requests-2.28.2-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 760.2 kB/s eta 0:00:00
Collecting pyyaml>=5.1
  Downloading PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (682 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 682.2/682.2 kB 845.6 kB/s eta 0:00:00
Collecting packaging>=20.0
  Downloading packaging-23.0-py3-none-any.whl (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.7/42.7 kB 656.2 kB/s eta 0:00:00
Collecting tokenizers!=0.11.3,<0.14,>=0.11.1
  Downloading tokenizers-0.13.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 757.2 kB/s eta 0:00:00
Collecting filelock
  Downloading filelock-3.10.7-py3-none-any.whl (10 kB)
Collecting huggingface-hub<1.0,>=0.11.0
  Downloading huggingface_hub-0.13.3-py3-none-any.whl (199 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.8/199.8 kB 585.2 kB/s eta 0:00:00
Collecting tqdm>=4.27
  Downloading tqdm-4.65.0-py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 kB 835.4 kB/s eta 0:00:00
Collecting numpy>=1.17
  Downloading numpy-1.24.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 702.2 kB/s eta 0:00:00
Collecting regex!=2019.12.17
  Downloading regex-2023.3.23-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (769 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 769.6/769.6 kB 923.3 kB/s eta 0:00:00
Collecting typing-extensions>=3.7.4.3
  Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting idna<4,>=2.5
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 1.8 MB/s eta 0:00:00
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.9/140.9 kB 946.7 kB/s eta 0:00:00
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (199 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.3/199.3 kB 731.3 kB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 1.0 MB/s eta 0:00:00
Building wheels for collected packages: transformers
  Building wheel for transformers (pyproject.toml) ... done
  Created wheel for transformers: filename=transformers-4.28.0.dev0-py3-none-any.whl size=6862976 sha256=41856f33d27bce8784e13460211a61e3577b32677862c225a90fb0a77442f5ca
  Stored in directory: /tmp/pip-ephem-wheel-cache-ehurp_i3/wheels/c0/14/d6/6c9a5582d2ac191ec0a483be151a4495fe1eb2a6706ca49f1b
Successfully built transformers
Installing collected packages: tokenizers, urllib3, typing-extensions, tqdm, regex, pyyaml, packaging, numpy, idna, filelock, charset-normalizer, certifi, requests, huggingface-hub, transformers
Successfully installed certifi-2022.12.7 charset-normalizer-3.1.0 filelock-3.10.7 huggingface-hub-0.13.3 idna-3.4 numpy-1.24.2 packaging-23.0 pyyaml-6.0 regex-2023.3.23 requests-2.28.2 tokenizers-0.13.2 tqdm-4.65.0 transformers-4.28.0.dev0 typing-extensions-4.5.0 urllib3-1.26.15
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@ubuntu:/# python3 -c 'import transformers; print(transformers.__version__)'
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
4.28.0.dev0
```

Also, as the warning says:

> WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

It's not recommended to use the `pip` executable installed from `apt install python3-pip`. It would always be better to use a virtual environment with `venv` or `conda`.

**Comment by loeken** [comment]
using venv did solve it for me, i do still think it might be risky to just install transformers from git but i ll close this issue as using venv solved it for me. @XuehaiPan i am not too familiar with pip but to my understanding your appraoch would result in tools being in different version then specified in the requirements.txt - while it does solve the issue i think it might cause other problems down the line.
