### ISSUE TITLE
llama.cpp implementation take too much ram (overhead)

### ISSUE THREAD

**Issue by fgdfgfthgr-fox** [oobabooga/text-generation-webui#765]
### Describe the bug

In theory, a quantized 30B llama model should only take up 19.5 GB of RAM. Hence would not be an issue for a system with 64GB of RAM. However, it's not behaving like that, as my system runs out of RAM when using an 30B model. (let along 65, which is just a disaster)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Convert the llama-30b-4bit-128g quantized model into ggml-model-q4_1, using [this](https://github.com/ggerganov/llama.cpp/pull/545) script.
2. Load the model, then try to let it generate something.
3. Watch it slowly take up way more ram than it should.

### Screenshot

![2023-04-04 22-02-03屏幕截图](https://user-images.githubusercontent.com/60460773/229758839-681869d8-f398-4669-86ca-6630aa8062b4.png)

### Logs

```shell
(textgen) fgdfgfthgr@fgdfgfthgr-MS-7C95:/mnt/7018F20D48B6C548/text-generation-webui$ python server.py --threads 6 --notebook

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: /home/fgdfgfthgr/anaconda3/envs/textgen did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('local/fgdfgfthgr-MS-7C95'), PosixPath('@/tmp/.ICE-unix/1088,unix/fgdfgfthgr-MS-7C95')}
  warn(msg)
/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/etc/xdg/xdg-cinnamon')}
  warn(msg)
/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/org/freedesktop/DisplayManager/Session0')}
  warn(msg)
/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('1'), PosixPath('0')}
  warn(msg)
/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/org/freedesktop/DisplayManager/Seat0')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 6.1
CUDA SETUP: Detected CUDA version 117
/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary /home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so...
The following models are available:

1. GALACTICA-1.3b
2. GALACTICA-6.7b
3. llama-13b
4. llama-30b-4bit-128g
5. llama-65b-4bit-128g
6. llama-7b
7. llamacpp-65b
8. llamacpp-7b
9. llamacpp_30b

Which one do you want to load? 1-9

9

Loading llamacpp_30b...
llama.cpp weights detected: models/llamacpp_30b/ggml-model-q4_1.bin

llama_model_load: loading model from 'models/llamacpp_30b/ggml-model-q4_1.bin' - please wait ...
llama_model_load: GPTQ model detected - are you sure n_parts should be 4? we normally expect it to be 1
llama_model_load: use '--n_parts 1' if necessary
llama_model_load: n_vocab = 32000
llama_model_load: n_ctx   = 512
llama_model_load: n_embd  = 6656
llama_model_load: n_mult  = 256
llama_model_load: n_head  = 52
llama_model_load: n_layer = 60
llama_model_load: n_rot   = 128
llama_model_load: f16     = 4
llama_model_load: n_ff    = 17920
llama_model_load: n_parts = 4
llama_model_load: type    = 3
llama_model_load: ggml map size = 23777.27 MB
llama_model_load: ggml ctx size = 151.25 KB
llama_model_load: mem required  = 26081.42 MB (+ 6248.00 MB per state)
llama_model_load: loading tensors from 'models/llamacpp_30b/ggml-model-q4_1.bin'
llama_model_load: model size = 23776.82 MB / num tensors = 543
llama_init_from_file: kv self size  = 1560.00 MB
/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/gradio/deprecation.py:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
  warnings.warn(value)
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/starlette/middleware/cors.py", line 76, in __call__
    await self.app(scope, receive, send)
  File "/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/fastapi/routing.py", line 289, in app
    await dependant.call(**values)
  File "/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/gradio/routes.py", line 501, in join_queue
    session_info = await asyncio.wait_for(
  File "/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/starlette/websockets.py", line 133, in receive_json
    self._raise_on_disconnect(message)
  File "/home/fgdfgfthgr/anaconda3/envs/textgen/lib/python3.10/site-packages/starlette/websockets.py", line 105, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1006
```

### System Info

```shell
CPU: Ryzen 5500
GPU: 1050ti
OS: Linux Mint 21.1
    Linux fgdfgfthgr-MS-7C95 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
RAM: 64GB of DDR4 running at 3000MHz
Python 3.9.13
GNU Make 4.3
g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
```

**Comment by fgdfgfthgr-fox** [comment]
Solved with recent updates.
