### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by Quiet-Joker** [oobabooga/text-generation-webui#781]
### Describe the bug

When  pressing the `impersonate` button using it produces an  `'NoneType' object has no attribute 'replace'` error. It seems to occur on every model i use.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Step 1: Load model
Step 2: Type to start conversation
Step 3: Press Impersonate
Step 4: Error encountered.

### Screenshot

![image](https://user-images.githubusercontent.com/63294141/229943534-dd307256-e378-4410-b5a9-1fca03780abc.png)

### Logs

```shell
Starting the web UI...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: Loading binary D:\OOBABOOGA\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
The following models are available:

1. eachadea_vicuna-13b
2. llama-13b-4bit-128g-vicuna
3. llama-13b-hf
4. llama-7b-hf

Which one do you want to load? 1-4

2

Loading llama-13b-4bit-128g-vicuna...
Loading model ...
D:\OOBABOOGA\installer_files\env\lib\site-packages\safetensors\torch.py:99: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
D:\OOBABOOGA\installer_files\env\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
D:\OOBABOOGA\installer_files\env\lib\site-packages\torch\storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
Done.
Loaded the model in 3.99 seconds.
Loading the extension "gallery"... Ok.
D:\OOBABOOGA\installer_files\env\lib\site-packages\gradio\deprecation.py:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
  warnings.warn(value)
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "D:\OOBABOOGA\installer_files\env\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\OOBABOOGA\installer_files\env\lib\site-packages\gradio\blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "D:\OOBABOOGA\installer_files\env\lib\site-packages\gradio\blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\OOBABOOGA\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\OOBABOOGA\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\OOBABOOGA\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\OOBABOOGA\installer_files\env\lib\site-packages\gradio\utils.py", line 490, in async_iteration
    return next(iterator)
  File "D:\OOBABOOGA\text-generation-webui\modules\chat.py", line 161, in impersonate_wrapper
    prompt = generate_chat_prompt(text, max_new_tokens, name1, name2, context, chat_prompt_size, impersonate=True)
  File "D:\OOBABOOGA\text-generation-webui\modules\chat.py", line 27, in generate_chat_prompt
    user_input = fix_newlines(user_input)
  File "D:\OOBABOOGA\text-generation-webui\modules\html_generator.py", line 25, in fix_newlines
    string = string.replace('\n', '\n\n')
AttributeError: 'NoneType' object has no attribute 'replace'
```
```


### System Info

```shell
Windows 10
Aorus Master RTX 3080Ti (12GB)
32GB Ram
Installed using Windows 1 click install bat file.
```

**Comment by YakuzaSuske** [comment]
Update: It seems to happen if there isn't much text to work on. After having enough text on the conversation it somewhat fixes itself and allows for impersonation. I still believe this should be looked into.

**Comment by Bubareh** [comment]
Such an error also occurs when the Google Translate module is included. It is strange because everything works perfectly in Google Colab.

**Comment by PedroPazosCurra** [comment]
Same error happens to me when running the API example with python.

**Comment by glibsonoran** [comment]
Yes I have a ComfyUI node that uses the OpenAI API that gets this same error.  It appears to be looking for a value in 'user' that's missing.

**Comment by CRPrinzler** [comment]
Fails for me as well in the same way.

**Comment by ahad1361** [comment]
I received the following error while I was trying to use the API with the snippet provided in the readme file.

  File "C:\Users\abs\text-generation-webui\modules\chat.py", line 636, in replace_character_names
    text = text.replace('{{user}}', name1).replace('{{char}}', name2)
AttributeError: 'NoneType' object has no attribute 'replace'


Is there any other  way to access the API ? I need to use python to communicate with the web ui  for my research.

**Comment by ahad1361** [comment]
I used a workaround, and changed the 
`user_bio=replace_character_names(state['user_bio'], state['name1'], state['name2']),`
to 
`user_bio=state['user_bio'],`
this seems to work now. But there must be some bigger issue.

**Comment by glibsonoran** [comment]
> I received the following error while I was trying to use the API with the snippet provided in the readme file.
> 
> File "C:\Users\abs\text-generation-webui\modules\chat.py", line 636, in replace_character_names text = text.replace('{{user}}', name1).replace('{{char}}', name2) AttributeError: 'NoneType' object has no attribute 'replace'
> 
> Is there any other way to access the API ? I need to use python to communicate with the web ui for my research.

If you're using the Python library openai and it's object there doesn't seem to be a way to fix it in the client code (I guess you can modify Ooba TGW).  
However if you use the Ooba API with an http POST you can supply a value for the variable (user_bio) that allows it handle the string functions:

url = "http:/localhost:5000/v1/chat/completions"
 params = {
            "model": my_model,
            "messages": messages,
            "temperature": temp,
            "max_tokens": tokens,
            "user_bio": "",
            "user_name": ""
            }
******************************
payload = {**params}
        try:
            response = requests.post(url, headers=headers, json=payload, timeout=(12,120))

The downside seems to be that Ooba's 'OpenAI compatible' API only seems to process the prompt, i.e. the {"role": "user", "content": prompt} in the list of dicts.  It seems to ignore the Instruction (role: system) and Examples (role: assistant).  Making it kind of rudimentary, but it is a workaround.

**Comment by glibsonoran** [comment]
> I used a workaround, and changed the `user_bio=replace_character_names(state['user_bio'], state['name1'], state['name2']),` to `user_bio=state['user_bio'],` this seems to work now. But there must be some bigger issue.

If you wanted to leave replace_character_names() and its values alone so they could continue to do whatever they do, you could just put this line in just before the problem line:
'user_bio = "" if user_bio == None else user_bio'

That way it would act as if you had passed user_bio in as an empty string in your client code

**Comment by Cyb3rz3r0** [comment]
curl http://127.0.0.1:5000/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer MzHSlBct25ekUobQFhwE3Zk0GGdNywBZ" \
  -d '{
    "messages": [
      {
	"role": "user",
        "content": "Hello!"
      }
    ],
    "user_bio": "",
    "user_name": "",
    "mode": "chat",
    "character": "Example",
    "instruction_template": "Alpaca"
  }'

This works without modifications....

**Comment by guispfilho** [comment]
> I used a workaround, and changed the `user_bio=replace_character_names(state['user_bio'], state['name1'], state['name2']),` to `user_bio=state['user_bio'],` this seems to work now. But there must be some bigger issue.



> curl http://127.0.0.1:5000/v1/chat/completions -H "Content-Type: application/json" -H "Authorization: Bearer YOUR-API-KEY" -d '{ "messages": [ { "role": "user", "content": "Hello!" } ], "user_bio": "", "user_name": "", "mode": "chat", "character": "Example", "instruction_template": "Alpaca" }'
> 
> This works without modifications....

Which file did you guys edited?
