### ISSUE TITLE
Web-ui get confused when offload in 4 bits using --pre_layer 

### ISSUE THREAD

**Issue by nRuaif** [oobabooga/text-generation-webui#787]
### Describe the bug

Using pygmalion 4bits:

Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Start the web-ui with --cai-chat --wbit 4 --groupsize 128 --model_type gptj --pre_layer 4 result in that error

### Logs

```shell
C:\SD\oobabooga-windows\installer_files\env\lib\site-packages\transformers\generation\utils.py:1405: UserWarning: You are calling .generate() with the input_ids being on a device type different than your model's device. input_ids is on cuda, whereas the model is on cpu. You may experience unexpected behaviors or slower generation. Please make sure that you have put input_ids to the correct device by calling for example input_ids = input_ids.to('cpu') before running .generate().
  warnings.warn(
Traceback (most recent call last):
  File "C:\SD\oobabooga-windows\text-generation-webui\modules\callbacks.py", line 64, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "C:\SD\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 224, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\SD\oobabooga-windows\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\SD\oobabooga-windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1485, in generate
    return self.sample(
  File "C:\SD\oobabooga-windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 2524, in sample
    outputs = self(
  File "C:\SD\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\SD\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\gptj\modeling_gptj.py", line 852, in forward
    transformer_outputs = self.transformer(
  File "C:\SD\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\SD\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\gptj\modeling_gptj.py", line 632, in forward
    inputs_embeds = self.wte(input_ids)
  File "C:\SD\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\SD\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\sparse.py", line 162, in forward
    return F.embedding(
  File "C:\SD\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
Output generated in 1.84 seconds (0.00 tokens/s, 0 tokens, context 32)
```

### System Info

```shell
GTX 1650 4gb
i3 10105F
16gb DDR4 ram running at 3000MT
```

**Comment by oobabooga** [comment]
`--pre_layer` is based on [llama_inference_offload.py](https://github.com/qwopqwop200/GPTQ-for-LLaMa/blob/triton/llama_inference_offload.py), which only works for llama models

Try this instead

> python server.py --model mayaeary_pygmalion-6b-4bit-128g --wbits 4 --groupsize 128 --auto-devices --gpu-memory 2000MiB
