### ISSUE TITLE
Errors after latest pull.

### ISSUE THREAD

**Issue by bbecausereasonss** [oobabooga/text-generation-webui#807]
### Describe the bug

Bug happens when I click generate in any mode.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Git pull. Load model.

call python server.py --model vicuna-13b-GPTQ-4bit-128g --wbits 4 --groupsize 128 --chat --verbose --share --disk --gpu-memory 18 --model_type LLaMA --extensions long_term_memory whisper_stt llama_prompts

Generate

### Logs

```shell
for history in chatbot_wrapper(text, max_new_tokens, do_sample, temperature, top_p, typical_p, repetition_penalty, encoder_repetition_penalty, top_k, min_length, no_repeat_ngram_size, num_beams, penalty_alpha, length_penalty, early_stopping, seed, name1, name2, context, stop_at_newline, chat_prompt_size, chat_generation_attempts, regenerate=False, mode=mode, end_of_turn=end_of_turn):
  File "C:\Users\xxxx\Deep\text-diffusion-webui\text-generation-webui\modules\chat.py", line 119, in chatbot_wrapper
    prompt = custom_generate_chat_prompt(text, max_new_tokens, name1, name2, context, chat_prompt_size, is_instruct, end_of_turn=end_of_turn)
TypeError: custom_generate_chat_prompt() got an unexpected keyword argument 'end_of_turn'
Closing server running on port: 7860
Loading the extension "long_term_memory"... Ok.
Loading the extension "whisper_stt"... Ok.
Loading the extension "gallery"... Ok.
C:\Users\xxxx\Deep\text-diffusion-webui\installer_files\env\lib\site-packages\gradio\deprecation.py:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
  warnings.warn(value)
Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://e6a5e8d7d2d239dac2.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
Traceback (most recent call last):
  File "C:\Users\xxxx\Deep\text-diffusion-webui\installer_files\env\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\xxxx\Deep\text-diffusion-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "C:\Users\xxxx\Deep\text-diffusion-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\xxxx\Deep\text-diffusion-webui\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\xxxx\Deep\text-diffusion-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\xxxx\Deep\text-diffusion-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\xxxx\Deep\text-diffusion-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 490, in async_iteration
    return next(iterator)
  File "C:\Users\xxxx\Deep\text-diffusion-webui\text-generation-webui\modules\chat.py", line 185, in cai_chatbot_wrapper
    for history in chatbot_wrapper(text, max_new_tokens, do_sample, temperature, top_p, typical_p, repetition_penalty, encoder_repetition_penalty, top_k, min_length, no_repeat_ngram_size, num_beams, penalty_alpha, length_penalty, early_stopping, seed, name1, name2, context, stop_at_newline, chat_prompt_size, chat_generation_attempts, regenerate=False, mode=mode, end_of_turn=end_of_turn):
  File "C:\Users\xxxx\Deep\text-diffusion-webui\text-generation-webui\modules\chat.py", line 119, in chatbot_wrapper
    prompt = custom_generate_chat_prompt(text, max_new_tokens, name1, name2, context, chat_prompt_size, is_instruct, end_of_turn=end_of_turn)
TypeError: custom_generate_chat_prompt() got an unexpected keyword argument 'end_of_turn'
Traceback (most recent call last):
  File "C:\Users\xxxx\Deep\text-diffusion-webui\installer_files\env\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\xxxx\Deep\text-diffusion-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "C:\Users\xxxx\Deep\text-diffusion-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\xxxx\Deep\text-diffusion-webui\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\xxxx\Deep\text-diffusion-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\xxxx\Deep\text-diffusion-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\xxxx\Deep\text-diffusion-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 490, in async_iteration
    return next(iterator)
  File "C:\Users\xxxx\Deep\text-diffusion-webui\text-generation-webui\modules\chat.py", line 185, in cai_chatbot_wrapper
    for history in chatbot_wrapper(text, max_new_tokens, do_sample, temperature, top_p, typical_p, repetition_penalty, encoder_repetition_penalty, top_k, min_length, no_repeat_ngram_size, num_beams, penalty_alpha, length_penalty, early_stopping, seed, name1, name2, context, stop_at_newline, chat_prompt_size, chat_generation_attempts, regenerate=False, mode=mode, end_of_turn=end_of_turn):
  File "C:\Users\xxxx\Deep\text-diffusion-webui\text-generation-webui\modules\chat.py", line 119, in chatbot_wrapper
    prompt = custom_generate_chat_prompt(text, max_new_tokens, name1, name2, context, chat_prompt_size, is_instruct, end_of_turn=end_of_turn)
TypeError: custom_generate_chat_prompt() got an unexpected keyword argument 'end_of_turn'
```

### System Info

```shell
WIN10x64, Chrome
```

**Comment by bbecausereasonss** [comment]
Also get this before loading model.

C:\Users\vdrut\Deep\text-diffusion-webui\installer_files\env\lib\site-packages\safetensors\torch.py:99: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
C:\Users\vdrut\Deep\text-diffusion-webui\installer_files\env\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
C:\Users\vdrut\Deep\text-diffusion-webui\installer_files\env\lib\site-packages\torch\storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)

**Comment by bbecausereasonss** [comment]
It was the long-term-memory extension.
