### ISSUE TITLE
Illegal memory access was encountered?

### ISSUE THREAD

**Issue by SakeButIDontDrink** [oobabooga/text-generation-webui#81]
Hello all, when using Pygmalion6b with --load-in-8bit I am able to launch the ui and everything, but when I send a message I get this error. I got the same error when loading the 2.7b model as well, so I doubt it's a lack of memory error? I could be wrong bc I'm very new to this whole thing.

I'm not sure how to fix this or what even causes it.

Running on a 2070super with 8gb VRAM 16Gb laptop memory with the params
call python server.py --model pygmalion-6b --auto-devices --no-stream --cai-chat --load-in-8bit

```Traceback (most recent call last):
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\gradio\routes.py", line 374, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\gradio\blocks.py", line 1017, in process_api
    result = await self.call_function(
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\gradio\blocks.py", line 849, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\gradio\utils.py", line 453, in async_iteration
    return next(iterator)
  File "C:\AI\oobabooga\text-generation-webui\server.py", line 614, in cai_chatbot_wrapper
    for _history in chatbot_wrapper(text, tokens, do_sample, max_new_tokens, temperature, top_p, typical_p, repetition_penalty, top_k, min_length, no_repeat_ngram_size, num_beams, penalty_alpha, length_penalty, early_stopping, name1, name2, context, check, chat_prompt_size, picture):
  File "C:\AI\oobabooga\text-generation-webui\server.py", line 589, in chatbot_wrapper
    for reply in generate_reply(question, tokens, do_sample, max_new_tokens, temperature, top_p, typical_p, repetition_penalty, top_k, min_length, no_repeat_ngram_size, num_beams, penalty_alpha, length_penalty, early_stopping, eos_token=eos_token, stopping_string=f"\n{name1}:"):
  File "C:\AI\oobabooga\text-generation-webui\server.py", line 356, in generate_reply
    output = eval(f"model.generate({', '.join(generate_params)}){cuda}")[0]
  File "<string>", line 1, in <module>
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1448, in generate
    return self.sample(
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 2464, in sample
    outputs = self(
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\accelerate\hooks.py", line 156, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\transformers\models\gptj\modeling_gptj.py", line 842, in forward
    transformer_outputs = self.transformer(
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\accelerate\hooks.py", line 156, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\transformers\models\gptj\modeling_gptj.py", line 676, in forward
    outputs = block(
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\accelerate\hooks.py", line 156, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\transformers\models\gptj\modeling_gptj.py", line 301, in forward
    attn_outputs = self.attn(
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\accelerate\hooks.py", line 156, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\transformers\models\gptj\modeling_gptj.py", line 202, in forward
    query = self.q_proj(hidden_states)
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\accelerate\hooks.py", line 156, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\nn\modules.py", line 242, in forward
    out = bnb.matmul(x, self.weight, bias=self.bias, state=self.state)
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\autograd\_functions.py", line 488, in matmul
    return MatMul8bitLt.apply(A, B, out, bias, state)
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\autograd\_functions.py", line 303, in forward
    CA, CAt, SCA, SCAt, coo_tensorA = F.double_quant(A.to(torch.float16), threshold=state.threshold)
  File "C:\AI\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\functional.py", line 1634, in double_quant
    nnz = nnz_row_ptr[-1].item()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.```

**Comment by Dakoteus** [comment]
I have this too no a 2080 super with 8gb vram & 32gb ram
