### ISSUE TITLE
Try to build llama 30b model 4-bit and get stucked while python setup_cuda.py install

### ISSUE THREAD

**Issue by silent780** [oobabooga/text-generation-webui#821]
### Describe the bug

I followed the instruction about build the env for llama 30b model 4-bit model, and get a strange Error as follow :
RuntimeError:
The detected CUDA version (12.0) mismatches the version that was used to compile
PyTorch (11.7). Please make sure to use the same CUDA versions.

but somehow my conda env is build by cuda-11.7, the nvcc -V shows as follow:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_19:00:59_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0

Can anyone help me to fix this out? Is this the bug of setup_cuda.py 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

run: python setup_cuda.py install

### Screenshot

![image](https://user-images.githubusercontent.com/112534945/230284777-daae240b-0ff9-4ca1-a660-db1c2fd54570.png)

### Logs

```shell
running bdist_egg
running egg_info
writing quant_cuda.egg-info\PKG-INFO
writing dependency_links to quant_cuda.egg-info\dependency_links.txt
writing top-level names to quant_cuda.egg-info\top_level.txt
reading manifest file 'quant_cuda.egg-info\SOURCES.txt'
writing manifest file 'quant_cuda.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
C:\Users\glx\.conda\envs\textgen\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。     
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
Traceback (most recent call last):
  File "C:\code\LLAMA\text-generation-webui\repositories\GPTQ-for-LLaMa\setup_cuda.py", line 4, in <module>
    setup(
  File "C:\Users\glx\.conda\envs\textgen\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\glx\.conda\envs\textgen\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "C:\Users\glx\.conda\envs\textgen\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Users\glx\.conda\envs\textgen\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Users\glx\.conda\envs\textgen\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "C:\Users\glx\.conda\envs\textgen\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\glx\.conda\envs\textgen\lib\site-packages\setuptools\command\install.py", line 74, in run
    self.do_egg_install()
  File "C:\Users\glx\.conda\envs\textgen\lib\site-packages\setuptools\command\install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\glx\.conda\envs\textgen\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Users\glx\.conda\envs\textgen\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "C:\Users\glx\.conda\envs\textgen\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\glx\.conda\envs\textgen\lib\site-packages\setuptools\command\bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\glx\.conda\envs\textgen\lib\site-packages\setuptools\command\bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "C:\Users\glx\.conda\envs\textgen\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Users\glx\.conda\envs\textgen\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "C:\Users\glx\.conda\envs\textgen\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\glx\.conda\envs\textgen\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
    self.run_command('build_ext')
  File "C:\Users\glx\.conda\envs\textgen\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Users\glx\.conda\envs\textgen\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "C:\Users\glx\.conda\envs\textgen\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\glx\.conda\envs\textgen\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "C:\Users\glx\.conda\envs\textgen\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
    self.build_extensions()
  File "C:\Users\glx\.conda\envs\textgen\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
    _check_cuda_version(compiler_name, compiler_version)
  File "C:\Users\glx\.conda\envs\textgen\lib\site-packages\torch\utils\cpp_extension.py", line 386, in _check_cuda_version
    raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
RuntimeError:
The detected CUDA version (12.0) mismatches the version that was used to compile
PyTorch (11.7). Please make sure to use the same CUDA versions.
```

### System Info

```shell
win10 with gtx-4090
```

**Comment by catalpaaa** [comment]
try `conda install -c conda-forge cudatoolkit=11.7 cudatoolkit-dev=11.7`

**Comment by silent780** [comment]
> try `conda install -c conda-forge cudatoolkit=11.7 cudatoolkit-dev=11.7`

thank you for your reply, I used the command and here comes a new error report:

  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 1106, in print_conda_exception
    stderrlog.error("\n%r\n", exc_val)
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1589, in _log
    self.handle(record)
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1598, in handle
    if (not self.disabled) and self.filter(record):
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 806, in filter
    result = f.filter(record)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\gateways\logging.py", line 50, in filter
    record.msg = record.msg % new_args
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\__init__.py", line 107, in __repr__
    errs.append(e.__repr__())
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\__init__.py", line 64, in __repr__
    return '%s: %s' % (self.__class__.__name__, str(self))
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\__init__.py", line 68, in __str__
    return str(self.message % self._kwargs)
ValueError: unsupported format character 'T' (0x54) at index 966

**Comment by catalpaaa** [comment]
> ValueError: unsupported format character 'T' (0x54) at index 966

something is wrong with your anaconda, not sure what
