### ISSUE TITLE
I'm getting low tokens per seconds, how do I fix this?

### ISSUE THREAD

**Issue by Njasa2k** [oobabooga/text-generation-webui#824]
### Describe the bug

I am getting low tokens per second, it is about 0.06 tokens/s, how do I massively increase the speed? I am running https://huggingface.co/Bradarr/gpt4-x-alpaca-13b-native-ggml-model-q4_0/tree/main 13B model on a RTX 2070.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

call python server.py --chat --auto-devices

### Logs

```shell
Starting the web UI...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: Loading binary C:\Users\user\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll...
C:\Users\user\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading 13B...
llama.cpp weights detected: models\13B\ggml-model-q4_0.bin

llama_model_load: loading model from 'models\13B\ggml-model-q4_0.bin' - please wait ...
llama_model_load: n_vocab = 32001
llama_model_load: n_ctx   = 512
llama_model_load: n_embd  = 5120
llama_model_load: n_mult  = 256
llama_model_load: n_head  = 40
llama_model_load: n_layer = 40
llama_model_load: n_rot   = 128
llama_model_load: f16     = 2
llama_model_load: n_ff    = 13824
llama_model_load: n_parts = 2
llama_model_load: type    = 2
llama_model_load: ggml map size = 7759.84 MB
llama_model_load: ggml ctx size = 101.25 KB
llama_model_load: mem required  = 9807.93 MB (+ 3216.00 MB per state)
llama_model_load: loading tensors from 'models\13B\ggml-model-q4_0.bin'
llama_model_load: model size =  7759.40 MB / num tensors = 363
llama_init_from_file: kv self size  =  800.00 MB
Loading the extension "gallery"... Ok.
C:\Users\user\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\gradio\deprecation.py:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
  warnings.warn(value)
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Output generated in 179.87 seconds (0.06 tokens/s, 11 tokens, context 210)
```

### System Info

```shell
Windows, Nvidia RTX 2070 with Q-Max design, 8GB VRAM, 64GB RAM
```

**Comment by catalpaaa** [comment]
the model starts with ggml, its running on cpu. try a different model like the cuda version in https://huggingface.co/anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g, which uses gptq to speed up generation

**Comment by catalpaaa** [comment]
follow https://github.com/oobabooga/text-generation-webui/wiki/LLaMA-model#4-bit-mode

**Comment by ninjasaid2k** [comment]
I'm getting this error
`OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\ninja\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\lib\c10_cuda.dll" or one of its dependencies.`
when I try to follow the steps.

**Comment by catalpaaa** [comment]
> I'm getting this error
> 
> ```
> C:\Users\user\Downloads\oobabooga-windows\oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa>python setup_cuda.py install
> Traceback (most recent call last):
>   File "C:\Users\user\Downloads\oobabooga-windows\oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa\setup_cuda.py", line 2, in <module>
>     from torch.utils import cpp_extension
>   File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\__init__.py", line 122, in <module>
>     raise err
> OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\lib\c10_cuda.dll" or one of its dependencies.
> ```
> 
> when I try to follow the steps and get to the `python setup_cuda.py install` part.

double check you env

**Comment by ninjasaid2k** [comment]
what am I looking for in C:\Users\user\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env ?

**Comment by catalpaaa** [comment]
> what am I looking for in C:\Users\user\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env ?

sry im nor familiar with windows setup

**Comment by ninjasaid2k** [comment]
@catalpaaa 
I'm getting an error for no module for torch:

```
(textgen) C:\Users\user\oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa>python setup_cuda.py install
Traceback (most recent call last):
  File "C:\Users\user\oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa\setup_cuda.py", line 2, in <module>
    from torch.utils import cpp_extension
ModuleNotFoundError: No module named 'torch'

(textgen) C:\Users\user\oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa>
```
what do I do?
