### ISSUE TITLE
ModuleNotFoundError: No module named 'gradio' - after windows one click install

### ISSUE THREAD

**Issue by iceandstorm** [oobabooga/text-generation-webui#835]
### Describe the bug

Sadly, after the Windows 1 click install, the web-ui does not start:

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

try starting the web-ui

### Logs

```shell
Starting the web UI...
Traceback (most recent call last):
  File "C:\Projects\Text\oobabooga-windows\text-generation-webui\server.py", line 14, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
Press any key to continue . . .
```

### System Info

```shell
OS Name	Microsoft Windows 10 Pro
Processor	AMD Ryzen 5 7600X 6-Core Processor, 4701 Mhz, 6 Core(s), 12 Logical Processor(s)
Installed Physical Memory (RAM)	64,0 GB
Name	NVIDIA GeForce RTX 4090
```

**Comment by Macegac** [comment]
ditto

**Comment by PixelatedJack** [comment]
I have the same issue!

**Comment by PixelatedJack** [comment]
I have the same issue!



> ### Describe the bug
> Sadly, after the Windows 1 click install, the web-ui does not start:
> 
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Reproduction
> try starting the web-ui
> 
> ### Screenshot
> _No response_
> 
> ### Logs
> ```shell
> Starting the web UI...
> Traceback (most recent call last):
>   File "C:\Projects\Text\oobabooga-windows\text-generation-webui\server.py", line 14, in <module>
>     import gradio as gr
> ModuleNotFoundError: No module named 'gradio'
> Press any key to continue . . .
> ```
> 
> ### System Info
> ```shell
> OS Name	Microsoft Windows 10 Pro
> Processor	AMD Ryzen 5 7600X 6-Core Processor, 4701 Mhz, 6 Core(s), 12 Logical Processor(s)
> Installed Physical Memory (RAM)	64,0 GB
> Name	NVIDIA GeForce RTX 4090
> ```

**Comment by Username69992872** [comment]
same problem here! looks like gradio is not existend in the env folder because the main python version has it allready.

**Comment by NNiX1** [comment]
yep having same problem

**Comment by oobabooga** [comment]
cc @jllllll

**Comment by CeterPushing** [comment]
You can open a command-line attached to the virtual environment by running the "micromamba-cmd" script.
pip install gradio

This, for me lead to more dependencies needing to be installed, launch "micromamba-cmd" and do a pip install 'insert missing library' I think there was like three that needed to be manually installed and I was able to launch start-webui.bat successfully, or wait for a fix. Cheers!

**Comment by oobabooga** [comment]
The install script already installs

```
python -m pip install -r requirements.txt --upgrade
```

which includes `gradio==3.24.1`, so I don't know how that is possible.

**Comment by christianKossmann2741** [comment]
> You can open a command-line attached to the virtual environment by running the "micromamba-cmd" script. pip install gradio
> 
> This, for me lead to more dependencies needing to be installed, launch "micromamba-cmd" and do a pip install 'insert missing library' I think there was like three that needed to be manually installed and I was able to launch start-webui.bat successfully, or wait for a fix. Cheers!

Nice, it worked for me. The missing modules were gradio, markdown and peft. After manually installing them here in micromamba-cmd it worked. I mean now I'm having other issue, but it seems unrelated

**Comment by Username69992872** [comment]
> 

that worked it seems, but another Error occours than:
```
ImportError:
LlamaConverter requires the protobuf library but it was not found in your environment. Checkout the instructions on the
installation page of its repo: https://github.com/protocolbuffers/protobuf/tree/master/python#installation and follow the ones
that match your environment. Please note that you may need to restart your runtime after installation.
```

**Comment by christianKossmann2741** [comment]
> > 
> 
> that worked it seems, but another Error occours than:
> 
> ```
> ImportError:
> LlamaConverter requires the protobuf library but it was not found in your environment. Checkout the instructions on the
> installation page of its repo: https://github.com/protocolbuffers/protobuf/tree/master/python#installation and follow the ones
> that match your environment. Please note that you may need to restart your runtime after installation.
> ```

I think I also saw this error when I tried to load the galactica model, but now when I try to open the opt I'm having this one:


`Loading facebook_opt-6.7b...
Could not find the quantized model in .pt or .safetensors format, exiting...
Press any key to continue . . .`

**Comment by NNiX1** [comment]
after pip install gradio, markdown and peft  i got error with protobuf like guys above me then  i did pip install protobuf then i started again install.bat and i finally got in

**Comment by Exozze** [comment]
Same issue...
Win 10 Pro, 32GB RAM i9-10900K, RTX 4090

**Comment by oobabooga** [comment]
> > 
> 
> that worked it seems, but another Error occours than:
> 
> ```
> ImportError:
> LlamaConverter requires the protobuf library but it was not found in your environment. Checkout the instructions on the
> installation page of its repo: https://github.com/protocolbuffers/protobuf/tree/master/python#installation and follow the ones
> that match your environment. Please note that you may need to restart your runtime after installation.
> ```

What model is giving this error?

**Comment by Username69992872** [comment]
> > > 
> > 
> > 
> > that worked it seems, but another Error occours than:
> > ```
> > ImportError:
> > LlamaConverter requires the protobuf library but it was not found in your environment. Checkout the instructions on the
> > installation page of its repo: https://github.com/protocolbuffers/protobuf/tree/master/python#installation and follow the ones
> > that match your environment. Please note that you may need to restart your runtime after installation.
> > ```
> 
> What model is giving this error?

vicuna-13b-GPTQ-4bit-128g

**Comment by taylor-ennen** [comment]
>   File "T:\projects\oobabooga-windows\text-generation-webui\server.py", line 14, in <module>
>     import gradio as gr
> ModuleNotFoundError: No module named 'gradio'

Also was getting this error.
To fix this in a one liner

`pip install markdown peft protobuf`
After running the **micromamba-cmd.bat** file again to open the command line inside of the env. 
![image](https://user-images.githubusercontent.com/70374690/230484633-97bd5089-9868-43ef-b0b8-b640e69ac139.png)
You can make sure you're in your env like so!

I have Choco installed. So you may have to run.

`python3 -m pip install markdown peft protobuf`

YMMV just looking to help other from this [YT video](https://www.youtube.com/watch?v=cCQdzqAHcFk&ab_channel=Aitrepreneur) on lunch but this may not fix everyone's use case.

**Comment by oobabooga** [comment]
protobuf is not necessary at all. Make sure that you have the up to date transformers and the up to date copy of this repository.

**Comment by iceandstorm** [comment]
After reinstalling the four things mentioned above, it did work.

**Comment by oobabooga** [comment]
The real error was llamacpp-python failing to install on Windows and preventing the requirements.txt from being fully installed. This change should have fixed it

https://github.com/oobabooga/text-generation-webui/commit/58ed87e5d9dd864e38d346274e6455a4a041e203

**Comment by mockinbirdy** [comment]
This issues is still persistent. Same error.

**Comment by 2-fly-4-ai** [comment]
issue persists.

**Comment by jllllll** [comment]
> issue persists.

This error indicates that something failed to install and interrupted the install process.
Unless you provide a log of the installation, we can't know what went wrong.
