### ISSUE TITLE
CUDA extension not installed.

### ISSUE THREAD

**Issue by CRCODE22** [oobabooga/text-generation-webui#836]
### Describe the bug

I get this error:
CUDA extension not installed.
ModuleNotFoundError: No module named 'safetensors'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I used the automatic installer to install everything.
Then I run start-webui.bat

### Logs

```shell
(E:\one-click-installers\installer_files\env) E:\one-click-installers>start-webui
Starting the web UI...
Loading vicuna-13b-GPTQ-4bit-128g...
CUDA extension not installed.
Loading model ...
Traceback (most recent call last):
  File "E:\one-click-installers\text-generation-webui\server.py", line 276, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "E:\one-click-installers\text-generation-webui\modules\models.py", line 102, in load_model
    model = load_quantized(model_name)
  File "E:\one-click-installers\text-generation-webui\modules\GPTQ_loader.py", line 114, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.wbits, shared.args.groupsize, kernel_switch_threshold=threshold)
  File "E:\one-click-installers\text-generation-webui\modules\GPTQ_loader.py", line 42, in _load_quant
    from safetensors.torch import load_file as safe_load
ModuleNotFoundError: No module named 'safetensors'
```

### System Info

```shell
Windows 11, Nvidia 3060 12GB
```

**Comment by IAteYourCookies** [comment]
i have the same error

**Comment by thot-experiment** [comment]
Try reinstalling completely fresh with the oneclick installer, this solved the problem for me. The issue appears to be that the GPTQ/CUDA setup only happens if there is no GPTQ folder inside `repositiories`, so if you're reinstalling atop an existing installation (attempting to reinit a fresh micromamba by deleting the dir for example) the necessary steps will not take place when re-running `install.bat`
