### ISSUE TITLE
Chat keeps reusing last input

### ISSUE THREAD

**Issue by practicaldreamer** [oobabooga/text-generation-webui#854]
### Describe the bug

Experiencing a pretty major bug in chat mode. Every other response uses last input... see screenshot

If I `git reset d0f9625 --hard` it doesn't do this btw...

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Launch with:
`python3 server.py --wbits 4 --gpu-memory 15 19 --listen --model llama-65b --verbose --chat`

See screenshot...

### Screenshot

![image](https://user-images.githubusercontent.com/78515588/230515668-7b3c483a-e979-4965-ab34-b950cb3f1189.png)

### Logs

```shell
(textgen2) user@user-System-Product-Name:~/Documents/ooba/2/text-generation-webui$ python3 server.py --wbits 4 --gpu-memory 15 19 --listen --model llama-65b --verbose --chat

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: /home/user/anaconda3/envs/textgen2/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/user/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
Loading settings from settings.json...
Loading llama-65b...
Found models/llama-65b-4bit.safetensors
Loading model ...
Done.
Using the following device map for the 4-bit model: {'model.embed_tokens': 0, 'model.layers.0': 0, 'model.layers.1': 0, 'model.layers.2': 0, 'model.layers.3': 0, 'model.layers.4': 0, 'model.layers.5': 0, 'model.layers.6': 0, 'model.layers.7': 0, 'model.layers.8': 0, 'model.layers.9': 0, 'model.layers.10': 0, 'model.layers.11': 0, 'model.layers.12': 0, 'model.layers.13': 0, 'model.layers.14': 0, 'model.layers.15': 0, 'model.layers.16': 0, 'model.layers.17': 0, 'model.layers.18': 0, 'model.layers.19': 0, 'model.layers.20': 0, 'model.layers.21': 0, 'model.layers.22': 0, 'model.layers.23': 0, 'model.layers.24': 0, 'model.layers.25': 0, 'model.layers.26': 0, 'model.layers.27': 0, 'model.layers.28': 0, 'model.layers.29': 0, 'model.layers.30': 0, 'model.layers.31': 0, 'model.layers.32': 0, 'model.layers.33': 0, 'model.layers.34': 0, 'model.layers.35': 0, 'model.layers.36': 1, 'model.layers.37': 1, 'model.layers.38': 1, 'model.layers.39': 1, 'model.layers.40': 1, 'model.layers.41': 1, 'model.layers.42': 1, 'model.layers.43': 1, 'model.layers.44': 1, 'model.layers.45': 1, 'model.layers.46': 1, 'model.layers.47': 1, 'model.layers.48': 1, 'model.layers.49': 1, 'model.layers.50': 1, 'model.layers.51': 1, 'model.layers.52': 1, 'model.layers.53': 1, 'model.layers.54': 1, 'model.layers.55': 1, 'model.layers.56': 1, 'model.layers.57': 1, 'model.layers.58': 1, 'model.layers.59': 1, 'model.layers.60': 1, 'model.layers.61': 1, 'model.layers.62': 1, 'model.layers.63': 1, 'model.layers.64': 1, 'model.layers.65': 1, 'model.layers.66': 1, 'model.layers.67': 1, 'model.layers.68': 1, 'model.layers.69': 1, 'model.layers.70': 1, 'model.layers.71': 1, 'model.layers.72': 1, 'model.layers.73': 1, 'model.layers.74': 1, 'model.layers.75': 1, 'model.layers.76': 1, 'model.layers.77': 1, 'model.layers.78': 1, 'model.layers.79': 1, 'model.norm': 1, 'lm_head': 1}
Loaded the model in 12.09 seconds.
Loading the extension "gallery"... Ok.
/home/user/anaconda3/envs/textgen2/lib/python3.10/site-packages/gradio/deprecation.py:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
  warnings.warn(value)
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/textgen2/lib/python3.10/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/anaconda3/envs/textgen2/lib/python3.10/site-packages/gradio/blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "/home/user/anaconda3/envs/textgen2/lib/python3.10/site-packages/gradio/blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/user/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/user/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/user/anaconda3/envs/textgen2/lib/python3.10/site-packages/gradio/utils.py", line 490, in async_iteration
    return next(iterator)
  File "/home/user/Documents/ooba/2/text-generation-webui/modules/chat.py", line 201, in cai_chatbot_wrapper
    for history in chatbot_wrapper(text, generate_state, name1, name2, context, mode, end_of_turn):
  File "/home/user/Documents/ooba/2/text-generation-webui/modules/chat.py", line 128, in chatbot_wrapper
    prompt = generate_chat_prompt(text, generate_state['max_new_tokens'], name1, name2, context, generate_state['chat_prompt_size'], **kwargs)
  File "/home/user/Documents/ooba/2/text-generation-webui/modules/chat.py", line 54, in generate_chat_prompt
    user_input = fix_newlines(user_input)
  File "/home/user/Documents/ooba/2/text-generation-webui/modules/html_generator.py", line 28, in fix_newlines
    string = string.replace('\n', '\n\n')
AttributeError: 'NoneType' object has no attribute 'replace'


The following is a conversation with an AI assistant. The assistant is helpful, creative, clever, and very friendly.
Human: Hello, who are you?
AI:
--------------------

Output generated in 4.49 seconds (3.79 tokens/s, 17 tokens, context 39)


The following is a conversation with an AI assistant. The assistant is helpful, creative, clever, and very friendly.
Human: Hello, who are you?
AI:
--------------------

Output generated in 3.54 seconds (4.81 tokens/s, 17 tokens, context 39)


The following is a conversation with an AI assistant. The assistant is helpful, creative, clever, and very friendly.
Human: Hello, who are you?
AI: I am your personal assistant. What can I do for you today?
Human: What is RAM?
AI:
--------------------

Output generated in 7.10 seconds (6.34 tokens/s, 45 tokens, context 64)


The following is a conversation with an AI assistant. The assistant is helpful, creative, clever, and very friendly.
Human: Hello, who are you?
AI: I am your personal assistant. What can I do for you today?
Human: What is RAM?
AI: Random Access Memory (RAM) is the hardware in a computing device where the operating system (OS), application programs and data in current use are kept so they can be quickly reached by the computer's processor.
Human: What is RAM?
AI:
--------------------

Output generated in 22.97 seconds (8.18 tokens/s, 188 tokens, context 117)


The following is a conversation with an AI assistant. The assistant is helpful, creative, clever, and very friendly.
Human: Hello, who are you?
AI: I am your personal assistant. What can I do for you today?
Human: What is RAM?
AI: Random Access Memory (RAM) is the hardware in a computing device where the operating system (OS), application programs and data in current use are kept so they can be quickly reached by the computer's processor.
Human: What is RAM?
AI: Random access memory (RAM) is a type of computer memory that can be accessed randomly; that is, any byte of memory can be accessed without touching the preceding bytes. RAM is the most common type of memory found in computers and other devices, such as printers. There are two main types of RAM: Static random-access memory (SRAM) and dynamic random-access memory (DRAM). SRAM retains its contents as long as power is being supplied to it, and DRAM needs to be refreshed thousands of times per second to avoid losing its content. Because of this refresh process, DRAM is slower than SRAM. However, DRAM uses less transistors and takes up less space on integrated circuits, making it much cheaper. As a result, modern computers generally have several gigabytes of DRAM, while only having a few megabytes of SRAM.
Human: What is the capital of Florida?
AI:
--------------------

Output generated in 3.80 seconds (2.11 tokens/s, 8 tokens, context 316)


The following is a conversation with an AI assistant. The assistant is helpful, creative, clever, and very friendly.
Human: Hello, who are you?
AI: I am your personal assistant. What can I do for you today?
Human: What is RAM?
AI: Random Access Memory (RAM) is the hardware in a computing device where the operating system (OS), application programs and data in current use are kept so they can be quickly reached by the computer's processor.
Human: What is RAM?
AI: Random access memory (RAM) is a type of computer memory that can be accessed randomly; that is, any byte of memory can be accessed without touching the preceding bytes. RAM is the most common type of memory found in computers and other devices, such as printers. There are two main types of RAM: Static random-access memory (SRAM) and dynamic random-access memory (DRAM). SRAM retains its contents as long as power is being supplied to it, and DRAM needs to be refreshed thousands of times per second to avoid losing its content. Because of this refresh process, DRAM is slower than SRAM. However, DRAM uses less transistors and takes up less space on integrated circuits, making it much cheaper. As a result, modern computers generally have several gigabytes of DRAM, while only having a few megabytes of SRAM.
Human: What is the capital of Florida?
AI: Tallahassee.
Human: Who framed Roger Rabbit?
AI:
--------------------

Output generated in 3.92 seconds (2.04 tokens/s, 8 tokens, context 335)


The following is a conversation with an AI assistant. The assistant is helpful, creative, clever, and very friendly.
Human: Hello, who are you?
AI: I am your personal assistant. What can I do for you today?
Human: What is RAM?
AI: Random Access Memory (RAM) is the hardware in a computing device where the operating system (OS), application programs and data in current use are kept so they can be quickly reached by the computer's processor.
Human: What is RAM?
AI: Random access memory (RAM) is a type of computer memory that can be accessed randomly; that is, any byte of memory can be accessed without touching the preceding bytes. RAM is the most common type of memory found in computers and other devices, such as printers. There are two main types of RAM: Static random-access memory (SRAM) and dynamic random-access memory (DRAM). SRAM retains its contents as long as power is being supplied to it, and DRAM needs to be refreshed thousands of times per second to avoid losing its content. Because of this refresh process, DRAM is slower than SRAM. However, DRAM uses less transistors and takes up less space on integrated circuits, making it much cheaper. As a result, modern computers generally have several gigabytes of DRAM, while only having a few megabytes of SRAM.
Human: What is the capital of Florida?
AI: Tallahassee.
Human: Who framed Roger Rabbit?
AI: Bob Hoskins.
Human: Who framed Roger Rabbit?
AI:
```

### System Info

```shell
...-:::::-...                 user@user-System-Product-Name 
          .-MMMMMMMMMMMMMMM-.              ----------------------------- 
      .-MMMM`..-:::::::-..`MMMM-.          OS: Linux Mint 21.1 x86_64 
    .:MMMM.:MMMMMMMMMMMMMMM:.MMMM:.        Kernel: 5.15.0-69-generic 
   -MMM-M---MMMMMMMMMMMMMMMMMMM.MMM-       Uptime: 1 day, 19 hours, 27 mins 
 `:MMM:MM`  :MMMM:....::-...-MMMM:MMM:`    Packages: 2766 (dpkg), 9 (flatpak) 
 :MMM:MMM`  :MM:`  ``    ``  `:MMM:MMM:    Shell: bash 5.1.16 
.MMM.MMMM`  :MM.  -MM.  .MM-  `MMMM.MMM.   Resolution: 2560x1440 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:   DE: Cinnamon 5.6.8 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM:MMM:   WM: Mutter (Muffin) 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:   WM Theme: Mint-Y-Dark-Aqua (Mint-Y) 
.MMM.MMMM`  :MM:--:MM:--:MM:  `MMMM.MMM.   Theme: Mint-Y-Dark-Red [GTK2/3] 
 :MMM:MMM-  `-MMMMMMMMMMMM-`  -MMM-MMM:    Icons: Mint-Y-Aqua [GTK2/3] 
  :MMM:MMM:`                `:MMM:MMM:     Terminal: gnome-terminal 
   .MMM.MMMM:--------------:MMMM.MMM.      CPU:AMD Ryzen 5 5600X (12)@ 3.700G 
     '-MMMM.-MMMMMMMMMMMMMMM-.MMMM-'       GPU: NVIDIA GeForce RTX 3090 
       '.-MMMM``--:::::--``MMMM-.'         GPU: NVIDIA GeForce RTX 3090 
            '-MMMMMMMMMMMMM-'              Memory: 4262MiB / 80344MiB 
               ``-:::::-``
```

**Comment by oobabooga** [comment]
I can't reproduce

```
This is a conversation with your Assistant. The Assistant is very helpful and is eager to chat with you and answer your questions.
You: Hello, who are you?
Assistant: I'm the Assistant. I have been assigned to this task by the Director of the Office of the Director of the Department of the Interior. I will be working in the office as an assistant for the duration of the project.
You: What is RAM?
Assistant: RAM stands for RAM Storage.
You: What is the capital of Florida?
Assistant: It's the capital of Florida.
You: What year are we in?
Assistant: We are in 2012.
You: What is the number 10?
Assistant: It's the number 10.
You: What is the number 11?
Assistant: It's the number 11.
You: What is the number 12?
Assistant: It's the number 12.
You: What is the number 13?
Assistant:

```

**Comment by oobabooga** [comment]
Does this happen with small models?

**Comment by practicaldreamer** [comment]
> I can't reproduce
> 
> ```
> This is a conversation with your Assistant. The Assistant is very helpful and is eager to chat with you and answer your questions.
> You: Hello, who are you?
> Assistant: I'm the Assistant. I have been assigned to this task by the Director of the Office of the Director of the Department of the Interior. I will be working in the office as an assistant for the duration of the project.
> You: What is RAM?
> Assistant: RAM stands for RAM Storage.
> You: What is the capital of Florida?
> Assistant: It's the capital of Florida.
> You: What year are we in?
> Assistant: We are in 2012.
> You: What is the number 10?
> Assistant: It's the number 10.
> You: What is the number 11?
> Assistant: It's the number 11.
> You: What is the number 12?
> Assistant: It's the number 12.
> You: What is the number 13?
> Assistant:
> ```

Odd... maybe it's something with me
I'll try llama-7b without GPTQ or any fancy stuff first then proceed to nuke my environment and make a new one

**Comment by practicaldreamer** [comment]
>python3 server.py --gpu-memory 15 19 --listen --model llama-7b --verbose --chat

![image](https://user-images.githubusercontent.com/78515588/230524025-cac8bf49-9f24-47c2-989e-6817e5e128e8.png)

... huh... it's not doing it on 7b at 16bit... I'll keep looking into this

**Comment by practicaldreamer** [comment]
It's on mobile... sorry pretty crucial detail I forgot to add... 

![image](https://user-images.githubusercontent.com/78515588/230525103-a072a76d-d659-43c5-a5c6-a3c061977027.png)

Using same prompt as above (7b)

**Comment by oobabooga** [comment]
Are you maybe clicking on the Submit button twice? The second click will be queued and used as input again.

**Comment by practicaldreamer** [comment]
> Are you maybe clicking on the Submit button twice? The second click will be queued and used as input again.

Negative. Sometimes the initial response seems to turn up empty though I can't reproduce this consistently I've yet to see it happen on desktop.

Output generated in 2.92 seconds (29.09 tokens/s, 85 tokens, context 39)
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/textgen2/lib/python3.10/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/anaconda3/envs/textgen2/lib/python3.10/site-packages/gradio/blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "/home/user/anaconda3/envs/textgen2/lib/python3.10/site-packages/gradio/blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/user/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/user/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/user/anaconda3/envs/textgen2/lib/python3.10/site-packages/gradio/utils.py", line 490, in async_iteration
    return next(iterator)
  File "/home/user/Documents/ooba/2/text-generation-webui/modules/chat.py", line 201, in cai_chatbot_wrapper
    for history in chatbot_wrapper(text, generate_state, name1, name2, context, mode, end_of_turn):
  File "/home/user/Documents/ooba/2/text-generation-webui/modules/chat.py", line 128, in chatbot_wrapper
    prompt = generate_chat_prompt(text, generate_state['max_new_tokens'], name1, name2, context, generate_state['chat_prompt_size'], **kwargs)
  File "/home/user/Documents/ooba/2/text-generation-webui/modules/chat.py", line 54, in generate_chat_prompt
    user_input = fix_newlines(user_input)
  File "/home/user/Documents/ooba/2/text-generation-webui/modules/html_generator.py", line 28, in fix_newlines
    string = string.replace('\n', '\n\n')
AttributeError: 'NoneType' object has no attribute 'replace'

This is on an iOS 16.4 running Chrome. I also tried Safari on my iPhone and had the same result... I'm pretty sure it's a bug on the mobile site. I'll attempt to replicate the observed issue in a completely new conda env to see if it helps

**Comment by oobabooga** [comment]
That's really weird. Do keep me updated.

**Comment by practicaldreamer** [comment]
Man I'm stumped... here's how I setup a new venv:
```
#Conda Setup
conda create -n textgen3 python=3.10.9
conda activate textgen3
#webui Setup
git clone https://github.com/oobabooga/text-generation-webui
cd text-generation-webui/
pip3 install torch torchvision torchaudio
pip install -r requirements.txt
#bnb dirty fix
cd /home/user/anaconda3/envs/textgen3/lib/python3.10/site-packages/bitsandbytes
cp libbitsandbytes_cuda120.so libbitsandbytes_cpu.so
cd -
conda install cudatoolkit
#model symlink
rm -rf models
rm -rf loras
ln -s /home/user/Documents/models /home/user/Documents/ooba/3/text-generation-webui
ln -s /home/user/Documents/loras /home/user/Documents/ooba/3/text-generation-webui
#launching webui
python server.py --gpu-memory 15 19 --listen --model llama-7b --verbose --chat
```
Then I:
1. Opened an incognito window on the Chrome app on my iPhone to <serverIP>:7860
2. Entered `Hello, who are you?` and hit "Generate"
3. Entered `What is RAM?` and hit "Generate"
4. Entered `What is the capital of Florida?` and hit "Generate"
5. Hit "Clear History" and confirmed
6. Entered `Hello, who are you?` and hit "Generate"

![image](https://user-images.githubusercontent.com/78515588/230536513-ae38f364-8a9c-4b72-bc12-b375721de965.png)

**Comment by oobabooga** [comment]
So it only happens after clear history?

**Comment by practicaldreamer** [comment]
> So it only happens after clear history?

...testing

**Comment by practicaldreamer** [comment]
1. I start the server back up with python `server.py --gpu-memory 15 19 --listen --model llama-7b --verbose --chat`
2. I return to the incognito tab on my iPhone
3. I type `Hello, who are you?` and hit "Generate"
4. I do not see **any** response on my iPhone other than clearing the input field and the following error appears in the terminal
```
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/textgen3/lib/python3.10/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/anaconda3/envs/textgen3/lib/python3.10/site-packages/gradio/blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "/home/user/anaconda3/envs/textgen3/lib/python3.10/site-packages/gradio/blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/user/anaconda3/envs/textgen3/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/anaconda3/envs/textgen3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/user/anaconda3/envs/textgen3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/user/anaconda3/envs/textgen3/lib/python3.10/site-packages/gradio/utils.py", line 490, in async_iteration
    return next(iterator)
  File "/home/user/Documents/ooba/3/text-generation-webui/modules/chat.py", line 201, in cai_chatbot_wrapper
    for history in chatbot_wrapper(text, generate_state, name1, name2, context, mode, end_of_turn):
  File "/home/user/Documents/ooba/3/text-generation-webui/modules/chat.py", line 128, in chatbot_wrapper
    prompt = generate_chat_prompt(text, generate_state['max_new_tokens'], name1, name2, context, generate_state['chat_prompt_size'], **kwargs)
  File "/home/user/Documents/ooba/3/text-generation-webui/modules/chat.py", line 54, in generate_chat_prompt
    user_input = fix_newlines(user_input)
  File "/home/user/Documents/ooba/3/text-generation-webui/modules/html_generator.py", line 28, in fix_newlines
    string = string.replace('\n', '\n\n')
AttributeError: 'NoneType' object has no attribute 'replace'
```
5. I enter `Hello who are you?` and hit "Generate" ✔️
6. I enter `What is RAM?` and hit "Generate" ✔️
7. I enter `What is the capital of Florida` and hit "Generate" ✔️
8. I enter `How do I drive from California to Canada?` and hit "Generate" ✔️
9. I enter `What is the average wind speed of an unladen swallow?` and hit "Generate" ❌

![image](https://user-images.githubusercontent.com/78515588/230538525-69f1347f-6cff-4e70-9e4a-0126211b0563.png)

My current theory is that something changed on gradio as it only occurs on the mobile app... I'll be sticking on d0f9625 for right now... it's late here... I might try reverting to whatever gradio version was present in the d0f9625 commit... if I find anything else out I'll put it here... for now I'm totally stumped... 

Thanks again for all you do 🤗

An equally possible theory is your current commit doesn't appreciate British humor...

**Comment by tensiondriven** [comment]
I've been seeing some weirdness in Gradio today on iPhone only after updating to latest master - It isn't anything obvious that I can see, though I didn't look into it in much detail.

Perhaps its time to start pinning more requirements, then we can selectively bring in updates when it's warranted.  That way, we won't be subject to dependencies breaking the app.

**Comment by oobabooga** [comment]
Gradio is already pinned (to the latest version, but still).

**Comment by practicaldreamer** [comment]
0dc6fa0 `Use gr.State() to store the user input` is the commit that caused this to break. I'm sure of it

I loaded 5f3f3fa (the one right before it) and this bug doesn't occur

Still looking into what specifically changed...

**Comment by practicaldreamer** [comment]
Patched with https://github.com/oobabooga/text-generation-webui/commit/a6a00cb82f6127e0497917aca8803ecf9db220cc
