### ISSUE TITLE
Silero TTS Fails to load on fresh installation

### ISSUE THREAD

**Issue by upq** [oobabooga/text-generation-webui#876]
### Describe the bug

text-generation-ui fails to start when the extention silero_tts is enabled.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Fresh installation following the readme instructions is enough.

### Logs

```shell
:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
  warnings.warn(value)
Traceback (most recent call last):
  File "/mnt/d/Development/text-generation-webui/server.py", line 591, in <module>
    create_interface()
  File "/mnt/d/Development/text-generation-webui/server.py", line 550, in create_interface
    extensions_module.create_extensions_block()
  File "/mnt/d/Development/text-generation-webui/modules/extensions.py", line 75, in create_extensions_block
    extension.ui()
  File "/mnt/d/Development/text-generation-webui/extensions/silero_tts/script.py", line 153, in ui
    convert_confirm.click(remove_tts_from_history, [shared.gradio['name1'], shared.gradio['name2']], shared.gradio['display'])
KeyError: 'name1'
```
```


### System Info

```shell
WSL on Windows 11
2x Nvidia 3090ti
RYZEN 7950x
```

**Comment by oobabooga** [comment]
Silero currently only works in chat mode
