### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'Resampling'

### ISSUE THREAD

**Issue by kelheor** [oobabooga/text-generation-webui#884]
### Describe the bug

After update I'm getting this error when I'm trying to load server
`AttributeError: module 'PIL.Image' has no attribute 'Resampling'`

If I remove all characters from characters folder then issue dissapears.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Start server with custom characters with images in characters folder (you can test it with characters from  https://booru.plus/+pygmalion but it seems it won't start even with built in Example character)

### Logs

```shell
Loading the extension "gallery"... Ok.
Traceback (most recent call last):
  File "C:\text-generation-webui\text-generation-webui\server.py", line 584, in <module>
    create_interface()
  File "C:\text-generation-webui\text-generation-webui\server.py", line 550, in create_interface
    extensions_module.create_extensions_block()
  File "C:\text-generation-webui\text-generation-webui\modules\extensions.py", line 75, in create_extensions_block
    extension.ui()
  File "C:\text-generation-webui\text-generation-webui\extensions\gallery\script.py", line 91, in ui
    samples=generate_html(),
  File "C:\text-generation-webui\text-generation-webui\extensions\gallery\script.py", line 71, in generate_html
    image_html = f'<img src="file/{get_image_cache(path)}">'
  File "C:\text-generation-webui\text-generation-webui\modules\html_generator.py", line 123, in get_image_cache
    img = make_thumbnail(Image.open(path))
  File "C:\text-generation-webui\text-generation-webui\modules\html_generator.py", line 109, in make_thumbnail
    image = image.resize((350, round(image.size[1] / image.size[0] * 350)), Image.Resampling.LANCZOS)
  File "C:\Users\kelhe\AppData\Roaming\Python\Python310\site-packages\PIL\Image.py", line 65, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'PIL.Image' has no attribute 'Resampling'
```

### System Info

```shell
Ryzen 5950x
4090 24Gb
128Gb RAM
Windows 11
```

**Comment by ZeroDivisionDev** [comment]
I've solved this issue by upgrading Pillow :
```
python3 -m pip install --upgrade pip
python3 -m pip install --upgrade Pillow
```

**Comment by kelheor** [comment]
> I've solved this issue by upgrading Pillow :
> 
> ```
> python3 -m pip install --upgrade pip
> python3 -m pip install --upgrade Pillow
> ```

For me it didn't work

**Comment by kelheor** [comment]
This thing worked for me:
`pip install Pillow==9.1.0`
It installed Pillow version 9.4.0 however. But it also works.
