### ISSUE TITLE
Trying to load 30B with 2 GPUs + --pre_layer does not seem to work

### ISSUE THREAD

**Issue by ENjoyBlue2021** [oobabooga/text-generation-webui#886]
### Describe the bug

Its weird because I can load the 13B version and it splits across the GPUs. (no pre_layer)
I have a 1080TI and a 1080.
I need the pre_layer to not run out of memory. Am I doing something wrong?
It seems that only the first GPU is used.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

`python server.py --wbits 4 --auto-devices --gpu-memory 9000Mib 8000MiB --pre_layer 40`
This makes me just run out of memory. (on the first gpu. no matter how low i set the first one)

`python server.py --wbits 4 --auto-devices --gpu-memory 5000Mib 8000MiB --pre_layer 30`
This "works" (cant generate, see error log) but the loaded memory looks like in the screenshot. So only gpu 1
Am I doing something wrong or does --gpu-memory not work with pre_layer?

Used alpaca-30b-4bit.safetensors from https://huggingface.co/elinas/alpaca-30b-lora-int4/tree/main
in case its relevant.

### Screenshot

![Screenshot_20230408_001447](https://user-images.githubusercontent.com/98739594/230635225-6f669ead-5f8e-46ba-aa27-3a42f764ff51.png)

### Logs

```shell
`python server.py --wbits 4 --auto-devices --gpu-memory 5000Mib 8000MiB --pre_layer 30`
I assume this error is caused because no more memory in gpu 1 like in the screenshot.
Happens if I try to prompt something.

Traceback (most recent call last):
  File "/media/w/PhoenixSSD/oobabooga/text-generation-webui/modules/callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/media/w/PhoenixSSD/oobabooga/text-generation-webui/modules/text_generation.py", line 232, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/w/.local/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/media/w/PhoenixSSD/oobabooga/miniconda/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1462, in generate
    return self.sample(
  File "/media/w/PhoenixSSD/oobabooga/miniconda/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2478, in sample
    outputs = self(
  File "/home/w/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/w/PhoenixSSD/oobabooga/miniconda/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 765, in forward
    outputs = self.model(
  File "/home/w/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/w/PhoenixSSD/oobabooga/text-generation-webui/repositories/GPTQ-for-LLaMa/llama_inference_offload.py", line 162, in forward
    layer_outputs = decoder_layer(
  File "/home/w/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: LlamaDecoderLayer.forward() got an unexpected keyword argument 'position_ids'
Output generated in 0.33 seconds (0.00 tokens/s, 0 tokens, context 48)
^CTraceback (most recent call last):
  File "/media/w/PhoenixSSD/oobabooga/text-generation-webui/server.py", line 587, in <module>
```

### System Info

```shell
1080 TI + 1080.
Linux Ubuntu
```

**Comment by catalpaaa** [comment]
I think per layer is single gpu only, try --gpu-memory x y

**Comment by oobabooga** [comment]
It's as @catalpaaa said
