### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by dwchx** [oobabooga/text-generation-webui#893]
Traceback (most recent call last):
  File "A:\Program Files (x86)\oobabooga-windows\text-generation-webui\server.py", line 290, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "A:\Program Files (x86)\oobabooga-windows\text-generation-webui\modules\models.py", line 176, in load_model
    tokenizer = AutoTokenizer.from_pretrained(Path(f"{shared.args.model_dir}/{shared.model_name}/"))
  File "A:\Program Files (x86)\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 694, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "A:\Program Files (x86)\oobabooga-windows\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py", line 1811, in from_pretrained
    return cls._from_pretrained(
  File "A:\Program Files (x86)\oobabooga-windows\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py", line 1965, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "A:\Program Files (x86)\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\gpt2\tokenization_gpt2_fast.py", line 140, in __init__
    super().__init__(
  File "A:\Program Files (x86)\oobabooga-windows\installer_files\env\lib\site-packages\transformers\tokenization_utils_fast.py", line 117, in __init__
    slow_tokenizer = self.slow_tokenizer_class(*args, **kwargs)
  File "A:\Program Files (x86)\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\gpt2\tokenization_gpt2.py", line 188, in __init__
    with open(vocab_file, encoding="utf-8") as vocab_handle:
**TypeError: expected str, bytes or os.PathLike object, not NoneType**

I am getting this error every time I try to start gpt4chan, I am using "gpt4chan_model_float16"

**Comment by DumoeDss** [comment]
Did you solve it?

**Comment by ksylvan** [comment]
@DumoeDss @dwchx I just ran into this and solved it finally: https://github.com/oobabooga/text-generation-webui/issues/1620
