### ISSUE TITLE
Unable to load models

### ISSUE THREAD

**Issue by Steelman14aUA** [oobabooga/text-generation-webui#896]
### Describe the bug

Loading vicuna-13b-4bit-128g...
Loading model ...
Traceback (most recent call last):
  File "D:\GPT_Vicuna\oobabooga-windows\text-generation-webui\server.py", line 290, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\GPT_Vicuna\oobabooga-windows\text-generation-webui\modules\models.py", line 102, in load_model
    model = load_quantized(model_name)
  File "D:\GPT_Vicuna\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 132, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.wbits, shared.args.groupsize, kernel_switch_threshold=threshold)
  File "D:\GPT_Vicuna\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 61, in _load_quant
    model.load_state_dict(torch.load(checkpoint), strict = False)
  File "D:\GPT_Vicuna\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\GPT_Vicuna\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: unpickling stack underflow
Press any key to continue . . .

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Everytime

### Logs

```shell
Starting the web UI...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: D:\GPT_Vicuna\oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 6.1
CUDA SETUP: Detected CUDA version 117
D:\GPT_Vicuna\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:141: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary D:\GPT_Vicuna\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117_nocublaslt.dll...
The following models are available:

1. facebook_galactica-125m
2. facebook_opt-6.7b
3. vicuna-13b-4bit-128g
4. vicuna-13b-4bit-128g.safetensor
5. vicuna-13b-4bit-128g.safetensors

Which one do you want to load? 1-5

3

Loading vicuna-13b-4bit-128g...
Loading model ...
Traceback (most recent call last):
  File "D:\GPT_Vicuna\oobabooga-windows\text-generation-webui\server.py", line 290, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\GPT_Vicuna\oobabooga-windows\text-generation-webui\modules\models.py", line 102, in load_model
    model = load_quantized(model_name)
  File "D:\GPT_Vicuna\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 132, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.wbits, shared.args.groupsize, kernel_switch_threshold=threshold)
  File "D:\GPT_Vicuna\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 61, in _load_quant
    model.load_state_dict(torch.load(checkpoint), strict = False)
  File "D:\GPT_Vicuna\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\GPT_Vicuna\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: unpickling stack underflow
Press any key to continue . . .
```

### System Info

```shell
1080ti
```

**Comment by catalpaaa** [comment]
i dont think 1080ti support 4int instruction set

**Comment by jllllll** [comment]
I use a 1080ti and have no trouble loading 4-bit models. There is probably something wrong with that particular model causing it to be incompatible with webui.
