### ISSUE TITLE
vicuna not working-CUDA extension not installed-name 'quant_cuda' is not defined

### ISSUE THREAD

**Issue by kotaxyz** [oobabooga/text-generation-webui#898]
### Describe the bug

im not able to generate using vicuna model i was able to generate with opt 1.3b but this one dosnt seem to work

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

run start-webui.bat file
with call python server.py --auto-devices --cai-chat --wbits 4 --groupsize 128 argument

### Screenshot

![error](https://user-images.githubusercontent.com/105466290/230686379-7bb53716-c879-4a98-88e2-981f6d03857b.png)

### Logs

```shell
Starting the web UI...
Warning: --cai-chat is deprecated. Use --chat instead.
Loading vicuna-13b-GPTQ-4bit-128g...
CUDA extension not installed.
Loading model ...
C:\Users\Genesis\oobabooga-windows\installer_files\env\lib\site-packages\safetensors\torch.py:99: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
C:\Users\Genesis\oobabooga-windows\installer_files\env\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
C:\Users\Genesis\oobabooga-windows\installer_files\env\lib\site-packages\torch\storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
Done.
Loaded the model in 90.17 seconds.
Loading the extension "gallery"... Ok.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\Users\Genesis\oobabooga-windows\text-generation-webui\modules\callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "C:\Users\Genesis\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 231, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Users\Genesis\oobabooga-windows\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Genesis\oobabooga-windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1485, in generate
    return self.sample(
  File "C:\Users\Genesis\oobabooga-windows\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 2524, in sample
    outputs = self(
  File "C:\Users\Genesis\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Genesis\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "C:\Users\Genesis\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Genesis\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 577, in forward
    layer_outputs = decoder_layer(
  File "C:\Users\Genesis\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Genesis\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "C:\Users\Genesis\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Genesis\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 196, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "C:\Users\Genesis\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Genesis\oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 426, in forward
    quant_cuda.vecquant4matmul(x, self.qweight, y, self.scales, self.qzeros, self.groupsize)
NameError: name 'quant_cuda' is not defined
Output generated in 13.86 seconds (0.00 tokens/s, 0 tokens, context 43)
```

### System Info

```shell
WINDOWS 10 64BIT
GTX 1070 8GB
16 GB RAM
```

**Comment by catalpaaa** [comment]
have you run `python setup_cuda.py install`, if not follow https://github.com/oobabooga/text-generation-webui/wiki/LLaMA-model#step-1-install-gptq-for-llama

**Comment by kotaxyz** [comment]
thanks for your reply , i think its a thing that has to do with my gpu low vram because its a 13b lm i tried so many ways but didnt work

**Comment by dsk77** [comment]
I get this

python setup_cuda.py install
Traceback (most recent call last):
  File "D:\AI\oobabooga-windows\oobabooga-windows\oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa\setup_cuda.py", line 2, in <module>
    from torch.utils import cpp_extension
ModuleNotFoundError: No module named 'torch'

**Comment by catalpaaa** [comment]
> I get this
> 
> python setup_cuda.py install Traceback (most recent call last): File "D:\AI\oobabooga-windows\oobabooga-windows\oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa\setup_cuda.py", line 2, in from torch.utils import cpp_extension ModuleNotFoundError: No module named 'torch'

that means you dont even have the basic env setup yet, follow https://github.com/oobabooga/text-generation-webui#0-install-conda
