### ISSUE TITLE
Cannot use on non system drive w11

### ISSUE THREAD

**Issue by drmcbride12** [oobabooga/text-generation-webui#905]
### Describe the bug

Shows error message when not running on my system drive

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

have 2 drives and install all dependencies on the other one

### Logs

```shell
The filename, directory name, or volume label syntax is incorrect.
Starting the web UI...
Warning: --cai-chat is deprecated. Use --chat instead.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
D:\noah\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('D')}
  warn(msg)
D:\noah\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: D:\noah\oobabooga-windows\installer_files\env did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
D:\noah\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('file'), WindowsPath('/D'), WindowsPath('/noah/oobabooga-windows/installer_files/env/etc/xml/catalog')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
D:\noah\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(msg)
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
D:\noah\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
D:\noah\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Loading binary D:\noah\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: Loading binary D:\noah\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: Loading binary D:\noah\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Traceback (most recent call last):
  File "D:\noah\oobabooga-windows\text-generation-webui\server.py", line 18, in <module>
    from modules import api, chat, shared, training, ui
  File "D:\noah\oobabooga-windows\text-generation-webui\modules\training.py", line 12, in <module>
    from peft import (LoraConfig, get_peft_model, get_peft_model_state_dict,
  File "D:\noah\oobabooga-windows\installer_files\env\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "D:\noah\oobabooga-windows\installer_files\env\lib\site-packages\peft\mapping.py", line 16, in <module>
    from .peft_model import (
  File "D:\noah\oobabooga-windows\installer_files\env\lib\site-packages\peft\peft_model.py", line 31, in <module>
    from .tuners import LoraModel, PrefixEncoder, PromptEmbedding, PromptEncoder
  File "D:\noah\oobabooga-windows\installer_files\env\lib\site-packages\peft\tuners\__init__.py", line 20, in <module>
    from .lora import LoraConfig, LoraModel
  File "D:\noah\oobabooga-windows\installer_files\env\lib\site-packages\peft\tuners\lora.py", line 36, in <module>
    import bitsandbytes as bnb
  File "D:\noah\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\__init__.py", line 7, in <module>
    from .autograd._functions import (
  File "D:\noah\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\autograd\__init__.py", line 1, in <module>
    from ._functions import undo_layout, get_inverse_transform_indices
  File "D:\noah\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\autograd\_functions.py", line 9, in <module>
    import bitsandbytes.functional as F
  File "D:\noah\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "D:\noah\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py", line 22, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues
Press any key to continue . . .
```

### System Info

```shell
gtx 970 and 1660 
i7 12700kf
128gb ram
2 drives 1tb each nvme and hdd
```

**Comment by bloodsign** [comment]
This used to work on non system drive, after I updated to latest version, I'm getting the same error.

**Comment by jllllll** [comment]
Did you use the latest installer? Did you get any errors when installing?

This is an error caused by bitsandbytes not supporting Windows. The installer is supposed to install a custom Windows-compatible version. Whether or not it is on the system drive shouldn't matter.

You can install the custom bitsandbytes by opening `micromamba-cmd.bat` and entering:
```
python -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/raw/main/bitsandbytes-0.37.2-py3-none-any.whl --force-reinstall
```

**Comment by bloodsign** [comment]
@jllllll 
okay, I made a new installation, sadly, 
https://github.com/oobabooga/text-generation-webui/issues/908
there seems to be a couple of download error cropping up. Maybe there's a url change or something and the installation is failing for fresh installs.

**Comment by drmcbride12** [comment]
oh my god jlllllll thank you so much I was preparing to install a seperate windows install jsut to make it work I love you
