### ISSUE TITLE
function with index 12 not defined when using main/api-example-stream.py

### ISSUE THREAD

**Issue by GiusTex** [oobabooga/text-generation-webui#921]
### Describe the bug

I run the webui with --listen (and other things: --auto-devices --bf16 --model vicuna-13b-GPTQ-4bit-128g --model_type LLaMA  --groupsize 128 --wbits 4), then I run api-example-stream.py but I get the error AssertionError: function with index 12 not defined.
If I close the webui I get an error that says something like it can't connect with the remote pc, so the server address/link should be right. If I connect to the same address (http://127.0.0.1:7860) I can write and get answers in the normal webui.
My parameters:
```shell
def random_hash():
    letters = string.ascii_lowercase + string.digits
    return ''.join(random.choice(letters) for i in range(9))

async def run(context):
    server = "127.0.0.1"
    params = {
        'max_new_tokens': 200,
        'do_sample': True,
        'temperature': 1.99,
        'top_p': 0.18,
        'typical_p': 1,
        'repetition_penalty': 1.15,
        'encoder_repetition_penalty': 1.0,
        'top_k': 30,
        'min_length': 0,
        'no_repeat_ngram_size': 0,
        'num_beams': 1,
        'penalty_alpha': 0,
        'length_penalty': 1,
        'early_stopping': False,
        'seed': -1,
    }
...code...
"fn_index": 12
...code...
prompt = "Tell me the fact of the day"
...code...
```
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

python api-example-stream.py

### Logs
```shell
Traceback (most recent call last):
  File "C:\Users\wgius\Desktop\TextGenerationWebui\installer_files\env\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\wgius\Desktop\TextGenerationWebui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "C:\Users\wgius\Desktop\TextGenerationWebui\installer_files\env\lib\site-packages\gradio\blocks.py", line 879, in call_function
    assert block_fn.fn, f"function with index {fn_index} not defined."
AssertionError: function with index 12 not defined.
```
### System Info

```shell
System: Windows 11
GPU: Nvidia rtx 3060
```
### Update:
tsangberg says one need to find the [correct fn_index](https://www.reddit.com/r/Oobabooga/comments/128hl6l/comment/jej7lfq/?utm_source=share&utm_medium=web2x&context=3) in [web developer mode in his browser](https://www.reddit.com/r/Oobabooga/comments/128hl6l/comment/jej04ff/?utm_source=share&utm_medium=web2x&context=3), so I'm looking for this fn index now.

I can't find it, I think I'll use api-example.py (without --chat, it doesn't support it).

**Comment by GiusTex** [comment]
Just in case, this is the printed "content":
{'msg': 'send_hash'}
{'msg': 'estimation', 'rank': 0, 'queue_size': 1, 'avg_event_process_time': 0.6050062256474649, 'avg_event_concurrent_process_time': 0.6050062256474649, 'rank_eta': 0.6050062256474649, 'queue_eta': 0.0}
{'msg': 'send_data'}
{'msg': 'process_starts'}
{'msg': 'process_completed', 'output': {'data': [], 'is_generating': False, 'duration': 0.001001119613647461, 'average_duration': 0.000397186279296875}, 'success': True}

'is_generating': False, ' is worrying me

**Comment by GiusTex** [comment]
Above I said that if I set: content["output"]["data"] = ["this is a test speech"] it works, so I'm trying to understand if the problem lies where text output is stored. Chatgpt says the text is stored in "data", line 58 of main script:

await websocket.send(json.dumps({
    "session_hash": session,
    "fn_index": 12,
    "data": [
        payload # (context, params)
    ]
}))

so maybe the problem is in that block: text isn't generated, so data is empty and content["output"]["data"] is empty too, and the script can't select the first [0] item of the list
