### ISSUE TITLE
Web UI not starting

### ISSUE THREAD

**Issue by Dan00tz** [oobabooga/text-generation-webui#936]
### Describe the bug

![image](https://user-images.githubusercontent.com/996996/230746077-3be4a8c4-d901-475f-ba71-7ed2f91477ca.png)

Default installation without tampering the launch options.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Default installation.

### Logs

```shell
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: F:\GPT\oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 6.1
CUDA SETUP: Detected CUDA version 117
F:\GPT\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:141: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary F:\GPT\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117_nocublaslt.dll...
Loading anon8231489123_vicuna-13b-GPTQ-4bit-128g...
Traceback (most recent call last):
  File "F:\GPT\oobabooga-windows\text-generation-webui\server.py", line 302, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "F:\GPT\oobabooga-windows\text-generation-webui\modules\models.py", line 102, in load_model
    model = load_quantized(model_name)
  File "F:\GPT\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 135, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.wbits, shared.args.groupsize, kernel_switch_threshold=threshold)
  File "F:\GPT\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 54, in _load_quant
    make_quant(**make_quant_kwargs)
  File "F:\GPT\oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 446, in make_quant
    make_quant(child, names, bits, groupsize, faster, name + '.' + name1 if name != '' else name1, kernel_switch_threshold=kernel_switch_threshold)
  File "F:\GPT\oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 446, in make_quant
    make_quant(child, names, bits, groupsize, faster, name + '.' + name1 if name != '' else name1, kernel_switch_threshold=kernel_switch_threshold)
  File "F:\GPT\oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 446, in make_quant
    make_quant(child, names, bits, groupsize, faster, name + '.' + name1 if name != '' else name1, kernel_switch_threshold=kernel_switch_threshold)
  [Previous line repeated 1 more time]
  File "F:\GPT\oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 443, in make_quant
    module, attr, QuantLinear(bits, groupsize, tmp.in_features, tmp.out_features, faster=faster, kernel_switch_threshold=kernel_switch_threshold)
  File "F:\GPT\oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 154, in __init__
    'qweight', torch.zeros((infeatures // 32 * bits, outfeatures), dtype=torch.int)
RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 35389440 bytes.
Press any key to continue . . .
```

### System Info

```shell
GPU GTX 1070
Windows 11
16GB RAM
I7-7700K
```

**Comment by ehamawy** [comment]
same issue, bump

**Comment by CyrisXD** [comment]
Same issue here, tried various fixes but nothing seems to work. Trying to load the gpt-x-alpaca-13b-native-4bit-128g-cuda.pt model.

**Comment by Samogub** [comment]
same issue 
1660 ti 6gb
16ram
i think i cant launch cuz 6gb vram =)

**Comment by skippyssk** [comment]
I don't know how many people this will help, but I got the error because I was running Stable Diffusion at the same time.

**Comment by jllllll** [comment]
That model requires at least 9gb of free VRAM. If you have that, try adding `--pre_layer 4`. A small number like that may get it to load.

**Comment by CyrisXD** [comment]
@jllllll Thanks, but `--pre_layer 4` didn't work for me.

**Comment by jllllll** [comment]
@CyrisXD You will need a larger number due to your GPU not having enough VRAM: `--pre_layer 9`

**Comment by CyrisXD** [comment]
@jllllll Mmm doesn't work either. I've tried everything I can find and just can't get it to work. 

This is how I'm trying to run it: 

`call python server.py --auto-devices --chat --pre_layer 9 --wbits 4 --groupsize 128 --model gpt4-x-alpaca-13b-native-4bit-128g`

**Comment by jllllll** [comment]
@CyrisXD Oops I got it backwards. Also, remove `--auto-devices`.

`--pre_layer 41`

**Comment by CyrisXD** [comment]
@jllllll Unfortunately same result. I might just not be able to run this model with 8GB VRAM. 

`not enough memory: you tried to allocate 655380480 bytes.`

**Comment by jllllll** [comment]
@CyrisXD
The model has 40 layers and each layer is about 0.222 gb in size. `--pre_layer` determines the number of layers to put in VRAM.

Check task manager to see how much VRAM you have available. This could also just be a bug.

**Comment by CyrisXD** [comment]
@jllllll It may be a bug, good point. I notice the VRAM doesn't jump at all. The script just throws this error: 

```
Loading gpt4-x-alpaca-13b-native-4bit-128g...
Loading model ...
Traceback (most recent call last):
  File "D:\ChatGPT Models\text-generation-webui\server.py", line 302, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\ChatGPT Models\text-generation-webui\modules\models.py", line 102, in load_model
    model = load_quantized(model_name)
  File "D:\ChatGPT Models\text-generation-webui\modules\GPTQ_loader.py", line 132, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.wbits, shared.args.groupsize, shared.args.pre_layer)
  File "D:\ChatGPT Models\text-generation-webui\repositories\GPTQ-for-LLaMa\llama_inference_offload.py", line 228, in load_quant
    model.load_state_dict(torch.load(checkpoint))
  File "D:\ChatGPT Models\installer_files\env\lib\site-packages\torch\serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "D:\ChatGPT Models\installer_files\env\lib\site-packages\torch\serialization.py", line 1172, in _load
    result = unpickler.load()
  File "D:\ChatGPT Models\installer_files\env\lib\site-packages\torch\serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "D:\ChatGPT Models\installer_files\env\lib\site-packages\torch\serialization.py", line 1112, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage)._typed_storage()._untyped_storage
RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 655380480 bytes.
Press any key to continue . . .
```

**Comment by jllllll** [comment]
@CyrisXD Open `micromama-cmd.bat` and enter this command: `python -m torch.utils.collect_env`

Post the output. It will give details on your Torch installation.

**Comment by CyrisXD** [comment]
@jllllll Here is the output: 

```
Collecting environment information...
Traceback (most recent call last):
  File "D:\ChatGPT Models\installer_files\env\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\ChatGPT Models\installer_files\env\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\ChatGPT Models\installer_files\env\lib\site-packages\torch\utils\collect_env.py", line 602, in <module>
    main()
  File "D:\ChatGPT Models\installer_files\env\lib\site-packages\torch\utils\collect_env.py", line 585, in main
    output = get_pretty_env_info()
  File "D:\ChatGPT Models\installer_files\env\lib\site-packages\torch\utils\collect_env.py", line 580, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "D:\ChatGPT Models\installer_files\env\lib\site-packages\torch\utils\collect_env.py", line 422, in get_env_info
    pip_version, pip_list_output = get_pip_packages(run_lambda)
  File "D:\ChatGPT Models\installer_files\env\lib\site-packages\torch\utils\collect_env.py", line 394, in get_pip_packages
    out = run_with_pip(sys.executable + ' -mpip')
  File "D:\ChatGPT Models\installer_files\env\lib\site-packages\torch\utils\collect_env.py", line 382, in run_with_pip
    for line in out.splitlines()
AttributeError: 'NoneType' object has no attribute 'splitlines'
```

**Comment by jllllll** [comment]
@CyrisXD Well, that shouldn't have happened. I would suggest reinstalling in a new folder (without spaces) using the latest installer:
https://github.com/oobabooga/one-click-installers

You could also try this command to reinstall Torch:
```
python -m pip install https://download.pytorch.org/whl/cu117/torch-2.0.0%2Bcu117-cp310-cp310-win_amd64.whl --force-reinstall
```

**Comment by shalevc1098** [comment]
i have this issue either

**Comment by CyrisXD** [comment]
@jllllll Ok after reinstalling Torch I am able to run `micromama-cmd.bat` and here is the new output:

```
(D:\ChatGPT Models\installer_files\env) D:\ChatGPT Models>python3 -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 2.0.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: True
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3070
Nvidia driver version: 528.24
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2100
DeviceID=CPU0
Family=198
L2CacheSize=10240
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2100
Name=12th Gen Intel(R) Core(TM) i7-12700
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] torch==2.0.0+cu117
[conda] Could not collect
```

If nothing is obvious here, then I'll try a full re-install. 
Thank you for all the help so far.

**Comment by jllllll** [comment]
@CyrisXD If reinstalling Torch fixed that command, then your Torch install must have been broken somehow. I would try running the model again and seeing if it works now. If not, then reinstall.

**Comment by CyrisXD** [comment]
@jllllll Nope, didn't work. Tried reinstalling from scratch and same thing, `not enough memory: you tried to allocate 13107200 bytes.`

I'm out of ideas at this stage.

**Comment by jllllll** [comment]
It works for me. I've tried all sorts of things to try and figure this out. All GPTQ models load fine on my system. I even tried updating GPTQ-for-LLaMa to the latest version. Still can't get it to produce this error.

If you want to try updating to the latest GPTQ-for-LLaMa, then open `micromamba-cmd.bat` and enter these in order:
```
cd ".\text-generation-webui\repositories"
rd /q /s ".\GPTQ-for-LLaMa\" >nul
git clone https://github.com/qwopqwop200/GPTQ-for-LLaMa.git -b cuda
cd GPTQ-for-LLaMa
git revert -n b55bd46b602ad497e0cbfe2ec2c7cce80013cebd
python -m pip install -r requirements.txt
python -m pip install https://github.com/jllllll/GPTQ-for-LLaMa-Wheels/raw/main/610fdae6588c2b17bcf2726cacaaf795cd45077e/quant_cuda-0.0.0-cp310-cp310-win_amd64.whl --force-reinstall
```
If you want to try compiling GPTQ-for-LLaMa yourself, then replace the last command with this:
```
python -m pip uninstall quant_cuda
python setup_cuda.py install
```

**Comment by jllllll** [comment]
Also, watch your RAM in task manager as you try to load the model. It may be loading to RAM first before transferring to VRAM.

**Comment by jllllll** [comment]
@johnswan bitsandbytes does not support Windows. The installer uses a custom Windows-compatible version. If you were not using the latest installer, then you may not have gotten that version.

**Comment by jllllll** [comment]
@johnswan https://github.com/oobabooga/one-click-installers

I also have alternative versions of it on my repo. I would recommend the Miniconda one if you are having issues with the normal installer: https://github.com/jllllll/one-click-installers/tree/oobabooga-windows-miniconda

**Comment by jllllll** [comment]
@johnswan That is why I linked you to the Miniconda branch of my repo. Clone it with this command:
`git clone https://github.com/jllllll/one-click-installers.git -b oobabooga-windows-miniconda`

**Comment by Jeetkarsh** [comment]
![Screenshot 2023-04-09 at 11 47 56 PM](https://user-images.githubusercontent.com/10086516/230789746-e06af389-04e8-47a8-a20c-f6591ee42ef2.png)
Same issue with me, model loaded all well on terminal but nothing on GUI

**Comment by jllllll** [comment]
@johnswan Ok, there is definitely something wrong with your install if it can't even run pip. The _ctypes module that those errors are referring to is located in `\installer_files\env\DLLs`. Make sure that folder exists and isn't empty. If _ctypes is in there, then there is something wrong with CMD or your system. I am currently working on a new powershell version of the installer that should be more reliable than CMD. Here is an early version that seems to work on my system:
[powershell-one-click-installer.zip](https://github.com/oobabooga/text-generation-webui/files/11186867/powershell-one-click-installer.zip)


@Jeetkarsh In your case, you can see `CUDA extension not installed.` in that log. You need GPTQ-for-LLaMa and to make sure to compile and install it's CUDA kernels. The kernels are what that error is referring to.

**Comment by bbecausereasonss** [comment]
Hmmm, this python -m pip install https://github.com/jllllll/GPTQ-for-LLaMa-Wheels/raw/main/quant_cuda-0.0.0-cp310-cp310-win_amd64.whl --force-reinstall

has not fixed the recent errors loading some models >

**Comment by Marfnl** [comment]
I Had the same error but here is what works for me:
`call python server.py --chat --auto-devices --wbits 4 --groupsize 128`

**Comment by jllllll** [comment]
@Disorbs Your Torch version is way out of date. You need Torch 2.0.0 and you have 1.13.1. As far as I'm aware, GPTQ-for-LLaMa is made using 2.0.0.

**Comment by Disorbs** [comment]
> 

added 2.0.0 and re-did it looks good again but still the same cuda extension not found.
Successfully installed quant-cuda-0.0.0

**Comment by Death-777** [comment]
I'm not sure this will actually help any of you with your problem but I was getting this error before with Vicuna and GPT4xAlpaca-13b too and I set my virtual memory to "System managed size" for all my drives and it could finally load them. I hope it helps because I was really struggling to get any quantized models to load before that change, no matter what I did.

**Comment by CyrisXD** [comment]
@Death-777 This helped, thank you! 

I've managed to get it working. In my case I had the model and files loading from my `D:` drive where it's memory management was set to 'none'. 

I followed [this tutorial ](https://mcci.com/support/guides/how-to-change-the-windows-pagefile-size/) on how to set the Windows PageFile size on my D: drive. I set it to `System Managed Size` and now the model loads correctly.

**Comment by jashjasani** [comment]
Windows + R and search this "SystemPropertiesAdvanced.exe" without ",
In the Performance tab click Settings and go to Advance In the Virtual Memory tab click Change, and
turn off the "Automatically manage paging file size for all drives" Set all your Drive to System Managed Size click Set then Restart your device. I tried this and **it worked** but now I'm getting a different error  : _pickle.unpicklingerror: invalid load key, 'v'.
