### ISSUE TITLE
KeyError: 'model.layers.33.self_attn.q_proj.wf1'

### ISSUE THREAD

**Issue by Asost** [oobabooga/text-generation-webui#937]
### Describe the bug

I am attempting to use gpt4-x-alpaca-13b-native-4bit-128g; however, on multiple models I received the `KeyError: 'model.layers.33.self_attn.q_proj.wf1'` error whenever I type and run in the prompt box. It seems that on the 33rd layer it switches to my CPU. Any suggestions on how I can solve this? Other issues were of no help.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I have cloned the github, cloned the forked repository, replaced the model directory with a link to another drive (which shouldn't be the issue), and ran the python command.

### Logs

```shell
(textgen) [yuge@BeestPC text-generation-webui]$ python server.py --auto-devices --chat --wbits 4 --groupsize 128 --gpu-memory 6

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: /home/yuge/anaconda3/envs/textgen/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/yuge/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
The following models are available:

1. facebook_opt-2.7b
2. facebook_opt-6.7b
3. gpt4-x-alpaca-13b-native-4bit-128g
4. vicuna-13b-GPTQ-4bit-128g

Which one do you want to load? 1-4

3

Loading gpt4-x-alpaca-13b-native-4bit-128g...
Loading model ...
Done.
Using the following device map for the 4-bit model: {'model.embed_tokens': 0, 'model.layers.0': 0, 'model.layers.1': 0, 'model.layers.2': 0, 'model.layers.3': 0, 'model.layers.4': 0, 'model.layers.5': 0, 'model.layers.6': 0, 'model.layers.7': 0, 'model.layers.8': 0, 'model.layers.9': 0, 'model.layers.10': 0, 'model.layers.11': 0, 'model.layers.12': 0, 'model.layers.13': 0, 'model.layers.14': 0, 'model.layers.15': 0, 'model.layers.16': 0, 'model.layers.17': 0, 'model.layers.18': 0, 'model.layers.19': 0, 'model.layers.20': 0, 'model.layers.21': 0, 'model.layers.22': 0, 'model.layers.23': 0, 'model.layers.24': 0, 'model.layers.25': 0, 'model.layers.26': 0, 'model.layers.27': 0, 'model.layers.28': 0, 'model.layers.29': 0, 'model.layers.30': 0, 'model.layers.31': 0, 'model.layers.32': 0, 'model.layers.33': 'cpu', 'model.layers.34': 'cpu', 'model.layers.35': 'cpu', 'model.layers.36': 'cpu', 'model.layers.37': 'cpu', 'model.layers.38': 'cpu', 'model.layers.39': 'cpu', 'model.norm': 'cpu', 'lm_head': 'cpu'}
Loaded the model in 57.89 seconds.
Loading the extension "gallery"... Ok.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/DATA/github/text-generation-webui/modules/callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/DATA/github/text-generation-webui/modules/text_generation.py", line 231, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/yuge/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/yuge/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1485, in generate
    return self.sample(
  File "/home/yuge/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2524, in sample
    outputs = self(
  File "/home/yuge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yuge/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/yuge/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "/home/yuge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yuge/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 577, in forward
    layer_outputs = decoder_layer(
  File "/home/yuge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yuge/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/yuge/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/yuge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yuge/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/yuge/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 196, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "/home/yuge/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yuge/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 160, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "/home/yuge/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 280, in pre_forward
    set_module_tensor_to_device(module, name, self.execution_device, value=self.weights_map[name])
  File "/home/yuge/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/utils/offload.py", line 123, in __getitem__
    return self.dataset[f"{self.prefix}{key}"]
  File "/home/yuge/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/utils/offload.py", line 170, in __getitem__
    weight_info = self.index[key]
KeyError: 'model.layers.33.self_attn.q_proj.wf1'
```

### System Info

```shell
Manjaro Linux x86_64 
Intel i7 87000k
Nvidia RTX 2080
```

**Comment by IDEDARY** [comment]
Yes, I experienced the same issue. So far only adding `--pre_layer 2` parameter to starting bat solved the issue. But it is very slow. Hope somebody will find better solution.

**Comment by Fire-Input** [comment]
As @IDEDARY mention, I used `--pre_layer 35` and it works, its still slow, but not as slow as `--pre_layer 2`
Any higher and I run out of vram.

Command: python server.py --chat --auto-devices --wbits 4 --pre_layer 35 --groupsize 128

Specs
CPU: i9-11900k
GPU: 3070Ti 8GB

Prompt: What is a Llama?
Response: A lama is a type of mammal found primarily in South America, characterized by its thick fur and remarkable agility. They are known for their intelligence, strength, and unique ability to work together as a team.

Output Speed: Output generated in 21.90 seconds (2.10 tokens/s, 46 tokens, context 165)

**Comment by Pythonpa** [comment]
Yes,have the same error

**Comment by Asost** [comment]
I was able to resolve it with the --pre_layers. I realized that I read the other issue thread incorrectly and that was the solution. Thank you all for your time.
