### ISSUE TITLE
api example errors

### ISSUE THREAD

**Issue by elwolf6** [oobabooga/text-generation-webui#95]
```
Traceback (most recent call last):
  File "/home/luis/.conda/envs/textgen/lib/python3.10/site-packages/gradio/routes.py", line 374, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/luis/.conda/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1015, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/home/luis/.conda/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 913, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range
```

**Comment by elwolf6** [comment]
this is with --cai-chat u can "fix" by adding the name1, name2, context, stop_at_newline, and chat_prompt_Size_max to the payload but it returns a bunch of html and never actually prompts the model

**Comment by oobabooga** [comment]
As instructed in the source for the api example, you should start the script with

`python server.py --model MODEL --listen --no-stream`

Chat mode creates a history variable that is inaccessible from within the API.
