### ISSUE TITLE
"No such file or directory:"

### ISSUE THREAD

**Issue by JerkWaag** [oobabooga/text-generation-webui#953]
### Describe the bug

I was trying to launch the "gpt4-x-alpaca-13b-native-4bit-128g" and I got this error

Does anyone know how to fix this?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Launch the "start-webui.bat" file and select the "gpt4-x-alpaca-13b-native-4bit-128g" and errors start piling.

### Screenshot

![bild_2023-04-09_135317201](https://user-images.githubusercontent.com/130288782/230770989-8298adee-2481-4711-9d6d-4db9f24e2fb1.png)
![image](https://user-images.githubusercontent.com/130288782/230770998-2030bc21-4a08-4617-a337-749365b40083.png)

### Logs

```shell
Starting the web UI...
Warning: --cai-chat is deprecated. Use --chat instead.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: Loading binary C:\GPT Model\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll...
C:\GPT Model\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
The following models are available:

1. facebook_opt-6.7b
2. gpt4-x-alpaca-13b-native-4bit-128g
3. vicuna-13b-GPTQ-4bit-128g

Which one do you want to load? 1-3

2

Loading gpt4-x-alpaca-13b-native-4bit-128g...
Warning: torch.cuda.is_available() returned False.
This means that no GPU has been detected.
Falling back to CPU mode.

Loading checkpoint shards:   0%|                                                                 | 0/6 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\GPT Model\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 442, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "C:\GPT Model\installer_files\env\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\GPT Model\installer_files\env\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\GPT Model\installer_files\env\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models\\gpt4-x-alpaca-13b-native-4bit-128g\\pytorch_model-00001-of-00006.bin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\GPT Model\text-generation-webui\server.py", line 302, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\GPT Model\text-generation-webui\modules\models.py", line 170, in load_model
    model = AutoModelForCausalLM.from_pretrained(checkpoint, **params)
  File "C:\GPT Model\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "C:\GPT Model\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2736, in from_pretrained
    ) = cls._load_pretrained_model(
  File "C:\GPT Model\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 3050, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "C:\GPT Model\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 445, in load_state_dict
    with open(checkpoint_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models\\gpt4-x-alpaca-13b-native-4bit-128g\\pytorch_model-00001-of-00006.bin'
Press any key to continue . . .
```

### System Info

```shell
Win 11 AMD Radeon RX 6700 XT
```

**Comment by mzhadigerov** [comment]
Hi! Did you find a solution for this?
