### ISSUE TITLE
Error loading RWKV-4-Raven-7B-v7-Eng-20230404-ctx4096 language model

### ISSUE THREAD

**Issue by Njasa2k** [oobabooga/text-generation-webui#974]
### Describe the bug

When attempting to load the RWKV-4-Raven-7B-v7-Eng-20230404-ctx4096 language model using the provided script, an error occurs during the compilation process for the Torch C++ extension. Specifically, the error message states that the "cl" compiler cannot be found, and the script fails to generate the necessary build files for the extension.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

To reproduce this issue, simply attempt to load the RWKV-4-Raven-7B-v7-Eng-20230404-ctx4096 model using the provided script on a Windows-based system with the necessary dependencies installed.

### Logs

```shell
Starting the web UI...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: C:\Users\user\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary C:\Users\user\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
The following models are available:

1. llama-13b-4bit-128g
2. RWKV-4-Raven-14B-v8-Eng-20230408-ctx4096
3. RWKV-4-Raven-7B-v7-Eng-20230404-ctx4096

Which one do you want to load? 1-3

3

Loading RWKV-4-Raven-7B-v7-Eng-20230404-ctx4096...
Using C:\Users\user\AppData\Local\torch_extensions\torch_extensions\Cache\py310_cu117 as PyTorch extensions root...
C:\Users\user\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
Detected CUDA files, patching ldflags
Emitting ninja build file C:\Users\user\AppData\Local\torch_extensions\torch_extensions\Cache\py310_cu117\wkv_cuda\build.ninja...
INFO: Could not find files for the given pattern(s).
Traceback (most recent call last):
  File "C:\Users\user\Downloads\oobabooga-windows\oobabooga-windows\text-generation-webui\server.py", line 302, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\user\Downloads\oobabooga-windows\oobabooga-windows\text-generation-webui\modules\models.py", line 91, in load_model
    from modules.RWKV import RWKVModel, RWKVTokenizer
  File "C:\Users\user\Downloads\oobabooga-windows\oobabooga-windows\text-generation-webui\modules\RWKV.py", line 15, in <module>
    from rwkv.model import RWKV
  File "C:\Users\user\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\rwkv\model.py", line 29, in <module>
    load(
  File "C:\Users\user\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "C:\Users\user\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\user\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 1611, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "C:\Users\user\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 2048, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "C:\Users\user\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 2188, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
  File "C:\Users\user\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\user\Downloads\oobabooga-windows\oobabooga-windows\installer_files\env\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.
Press any key to continue . . .
```

### System Info

```shell
Windows, Nvidia RTX 2070 with Q-Max design, 8GB VRAM, 64GB RAM
```

**Comment by BarfingLemurs** [comment]
@ninjasaid2k No issue here, on pureblood linux. must be windows issue then?

```
python server.py --wbits 8

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: /home/ubuntu/miniconda3/envs/textgen/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/ubuntu/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
The following models are available:

1. gpt-x-alpaca-13b-native
2. RWKV-4-Raven-3B-v8-Eng-20230408-ctx4096
3. RWKV-4-Raven-7B-v8-Eng-20230408-ctx4096

Which one do you want to load? 1-3

3

Loading RWKV-4-Raven-7B-v8-Eng-20230408-ctx4096...
RWKV_JIT_ON 1 RWKV_CUDA_ON 0 RESCALE_LAYER 6

Loading models/RWKV-4-Raven-7B-v8-Eng-20230408-ctx4096.pth ...
Strategy: (total 32+1=33 layers)
* cuda [float16, float16], store 33 layers
0-cuda-float16-float16 1-cuda-float16-float16 2-cuda-float16-float16 3-cuda-float16-float16 4-cuda-float16-float16 5-cuda-float16-float16 6-cuda-float16-float16 7-cuda-float16-float16 8-cuda-float16-float16 9-cuda-float16-float16 10-cuda-float16-float16 11-cuda-float16-float16 12-cuda-float16-float16 13-cuda-float16-float16 14-cuda-float16-float16 15-cuda-float16-float16 16-cuda-float16-float16 17-cuda-float16-float16 18-cuda-float16-float16 19-cuda-float16-float16 20-cuda-float16-float16 21-cuda-float16-float16 22-cuda-float16-float16 23-cuda-float16-float16 24-cuda-float16-float16 25-cuda-float16-float16 26-cuda-float16-float16 27-cuda-float16-float16 28-cuda-float16-float16 29-cuda-float16-float16 30-cuda-float16-float16 31-cuda-float16-float16 32-cuda-float16-float16 
emb.weight                        f16      cpu  50277  4096 
blocks.0.ln1.weight               f16   cuda:0   4096       
blocks.0.ln1.bias                 f16   cuda:0   4096       
blocks.0.ln2.weight               f16   cuda:0   4096       
blocks.0.ln2.bias                 f16   cuda:0   4096       
blocks.0.att.time_decay           f32   cuda:0   4096       
blocks.0.att.time_first           f32   cuda:0   4096       
blocks.0.att.time_mix_k           f16   cuda:0   4096       
blocks.0.att.time_mix_v           f16   cuda:0   4096       
blocks.0.att.time_mix_r           f16   cuda:0   4096       
blocks.0.att.key.weight           f16   cuda:0   4096  4096 
blocks.0.att.value.weight         f16   cuda:0   4096  4096 
blocks.0.att.receptance.weight    f16   cuda:0   4096  4096 
blocks.0.att.output.weight        f16   cuda:0   4096  4096 
blocks.0.ffn.time_mix_k           f16   cuda:0   4096       
blocks.0.ffn.time_mix_r           f16   cuda:0   4096       
blocks.0.ffn.key.weight           f16   cuda:0   4096 16384 
blocks.0.ffn.receptance.weight    f16   cuda:0   4096  4096 
blocks.0.ffn.value.weight         f16   cuda:0  16384  4096 
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
blocks.31.ln1.weight              f16   cuda:0   4096       
blocks.31.ln1.bias                f16   cuda:0   4096       
blocks.31.ln2.weight              f16   cuda:0   4096       
blocks.31.ln2.bias                f16   cuda:0   4096       
blocks.31.att.time_decay          f32   cuda:0   4096       
blocks.31.att.time_first          f32   cuda:0   4096       
blocks.31.att.time_mix_k          f16   cuda:0   4096       
blocks.31.att.time_mix_v          f16   cuda:0   4096       
blocks.31.att.time_mix_r          f16   cuda:0   4096       
blocks.31.att.key.weight          f16   cuda:0   4096  4096 
blocks.31.att.value.weight        f16   cuda:0   4096  4096 
blocks.31.att.receptance.weight   f16   cuda:0   4096  4096 
blocks.31.att.output.weight       f16   cuda:0   4096  4096 
blocks.31.ffn.time_mix_k          f16   cuda:0   4096       
blocks.31.ffn.time_mix_r          f16   cuda:0   4096       
blocks.31.ffn.key.weight          f16   cuda:0   4096 16384 
blocks.31.ffn.receptance.weight   f16   cuda:0   4096  4096 
blocks.31.ffn.value.weight        f16   cuda:0  16384  4096 
ln_out.weight                     f16   cuda:0   4096       
ln_out.bias                       f16   cuda:0   4096       
head.weight                       f16   cuda:0   4096 50277 
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Output generated in 8.17 seconds (24.47 tokens/s, 200 tokens, context 21)
```

**Comment by ninjasaid2k** [comment]
> Do you have installed Visual Studio Build Tools, Desktop development with C++. cl you are missing is part of this package.

Yes I have that on my laptop.

**Comment by ctspry** [comment]
You can also use the "x64 Native Tools Command Prompt for VS 2019" shortcut on Windows, then `cd` to wherever you have text-generation-webui installed, then run start-webui.bat (edited with the parameters changed for RMKV). 

This is what I do and it works well with `--rwkv-cuda-on`.
