### ISSUE TITLE
CUDA SETUP: Required library version not found: libsbitsandbytes_cpu.so. Maybe you need to compile it from source?

### ISSUE THREAD

**Issue by pkp24** [oobabooga/text-generation-webui#978]
I've been trying to look everywhere on how to fix this and things have only gotten worse so I went back to default. I've only got the model "decapoda-research_llama-30b-hf" installed. I have 32 Gb of ram, an RTX 3090, and an intel CPU.

I ran
`python server.py`

And got

```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: Required library version not found: libsbitsandbytes_cpu.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...
/home/pkp24/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading decapoda-research_llama-30b-hf...
Traceback (most recent call last):
  File "/home/pkp24/text-generation-webui/server.py", line 302, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/pkp24/text-generation-webui/modules/models.py", line 50, in load_model
    model = AutoModelForCausalLM.from_pretrained(Path(f"{shared.args.model_dir}/{shared.model_name}"), device_map='auto', load_in_8bit=True)
  File "/home/pkp24/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "/home/pkp24/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2681, in from_pretrained
    raise ValueError(
ValueError:
                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you want to dispatch the model on the CPU or the disk while keeping
                        these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom
                        `device_map` to `from_pretrained`. Check
                        https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                        for more details.
```

I also tried `python server.py --auto-devices`

and got 
```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: Required library version not found: libsbitsandbytes_cpu.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...
/home/pkp24/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading decapoda-research_llama-30b-hf...
Warning: torch.cuda.is_available() returned False.
This means that no GPU has been detected.
Falling back to CPU mode.
```

**Comment by jllllll** [comment]
Check to see if you got the cpu version of torch:
`python -m torch.utils.collect_env`

**Comment by Polydick** [comment]
How to use this model online? h2o.ai removed it
