### ISSUE TITLE
CPU install mode DO NOT WORK! and result in "ModuleNotFoundError: No module named 'llama_inference_offload'"

### ISSUE THREAD

**Issue by ZenbladeJS** [oobabooga/text-generation-webui#979]
### Describe the bug

After extensive testing on multiple devices, this tool may ONLY work on NVidia GPU-supported devices run under the NVida install mode as I have not been able to test on a device with an AMD GPU. Trying to install it in any other manner results in the following error:

Traceback (most recent call last):
  File "C:\Users\zenbl\OneDrive\Desktop\oobabooga-windows\text-generation-webui\server.py", line 302, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\zenbl\OneDrive\Desktop\oobabooga-windows\text-generation-webui\modules\models.py", line 100, in load_model
    from modules.GPTQ_loader import load_quantized
  File "C:\Users\zenbl\OneDrive\Desktop\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 14, in <module>
    import llama_inference_offload
ModuleNotFoundError: No module named 'llama_inference_offload'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Attempt to install and run this program in CPU mode or AMD mode on either Linux or Windows.

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\zenbl\OneDrive\Desktop\oobabooga-windows\text-generation-webui\server.py", line 302, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\zenbl\OneDrive\Desktop\oobabooga-windows\text-generation-webui\modules\models.py", line 100, in load_model
    from modules.GPTQ_loader import load_quantized
  File "C:\Users\zenbl\OneDrive\Desktop\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 14, in <module>
    import llama_inference_offload
ModuleNotFoundError: No module named 'llama_inference_offload'
```

### System Info

```shell
Device #1:
OS: Windows 11 (64 bit)
CPU: AMD Ryzen 5 5600X 6-Core Processor
Ram: 24GB
Storage: 1TB SSD
GPU: NVIDIA GeForce RTX 3070 Ti

Device #2:
OS: Windows 11 (64 bit)
CPU: 12th Gen Intel(R) Core(TM) i7-1280P 
Ram: 16GB
Storage: 1TB SSD
GPU: INTEL Iris XE

Device #3:
OS: Ubuntu
CPU: AMD Ryzen™ 5 3600
Ram: 64 GB
Storage: 1TB
GPU: None
```

**Comment by necessities** [comment]
Also getting this issue when installed for cpu

ModuleNotFoundError: No module named 'llama_inference_offload'

More people reporting it here: https://huggingface.co/anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g/discussions/6

**Comment by devonfae** [comment]
In your start-webui.bat, do you have GPTQ flags like "--wbits 4" or "--groupsize 128"? Try removing those flags.
You may also need to install llama-cpp-python if you want to use ggml models, which are optimized to run on cpu. there are instructions for that here: https://github.com/oobabooga/text-generation-webui/wiki/llama.cpp-models#using-llamacpp-in-the-web-ui
After doing those two things I was able to bypass this error and load ggml*.bin format models.

**Comment by necessities** [comment]
Going to try that and update!

**Comment by ZenbladeJS** [comment]
> In your start-webui.bat, do you have GPTQ flags like "--wbits 4" or "--groupsize 128"? Try removing those flags. You may also need to install llama-cpp-python if you want to use ggml models, which are optimized to run on cpu. there are instructions for that here: https://github.com/oobabooga/text-generation-webui/wiki/llama.cpp-models#using-llamacpp-in-the-web-ui After doing those two things I was able to bypass this error and load ggml*.bin format models.

When I try that I get this:
Traceback (most recent call last):
  File "C:\Users\zenbl\alpaca\text-generation-webui\server.py", line 302, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\zenbl\alpaca\text-generation-webui\modules\models.py", line 106, in load_model
    from modules.llamacpp_model_alternative import LlamaCppModel
  File "C:\Users\zenbl\alpaca\text-generation-webui\modules\llamacpp_model_alternative.py", line 9, in <module>
    from llama_cpp import Llama
  File "C:\Users\zenbl\alpaca\installer_files\env\lib\site-packages\llama_cpp\__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "C:\Users\zenbl\alpaca\installer_files\env\lib\site-packages\llama_cpp\llama_cpp.py", line 46, in <module>
    _lib = _load_shared_library(_lib_base_name)
  File "C:\Users\zenbl\alpaca\installer_files\env\lib\site-packages\llama_cpp\llama_cpp.py", line 40, in _load_shared_library
    raise FileNotFoundError(f"Shared library with base name '{lib_base_name}' not found")
FileNotFoundError: Shared library with base name 'llama' not found

**Comment by devonfae** [comment]
I also had that error with the version suggested (0.1.23) but if you install the latest version, 0.1.27, it works fine. You can do "pip install llama-cpp-python --upgrade" to switch to the newer version.
The ggml models should be in a folder with whatever name you like in your models directory. (they'll be referred to by the name of the folder, so I named mine "vicuna", "alpaca", etc). The only file inside that folder is the model weights in ggml format. the filename should start with "ggml" and have a .bin extension. You can find a lot of them on huggingface if you search for ggml.
It's less performance than running through llama.cpp directly, though. But hopefully that gap narrows as development continues.

**Comment by adamf1979** [comment]
Attempting to install and run this program in CPU mode as well:
Removing the args --wbits 4 --groupsize 128 and doing pip install llama-cpp-python worked for getting the facebook_opt-6.7b model running, which was previously tossing the same error to me. I have yet to check on all the other base models that are available.

The only active args I have added in to start-webui.bat is: --auto-devices --chat

Side notes: 
The args: --wbits 4 --groupsize 128 were instructed to be added in for running the model: vicuna-13b-GPTQ-4bit-128g, which I still can not get running in CPU mode but that is tossing an unrelated error that I haven't figured out yet.

**Comment by ZenbladeJS** [comment]
> I also had that error with the version suggested (0.1.23) but if you install the latest version, 0.1.27, it works fine. You can do "pip install llama-cpp-python --upgrade" to switch to the newer version. The ggml models should be in a folder with whatever name you like in your models directory. (they'll be referred to by the name of the folder, so I named mine "vicuna", "alpaca", etc). The only file inside that folder is the model weights in ggml format. the filename should start with "ggml" and have a .bin extension. You can find a lot of them on huggingface if you search for ggml. It's less performance than running through llama.cpp directly, though. But hopefully that gap narrows as development continues.

After doing this and @devonfae 's comment before that and bypassing some issues with the installation of llama-cpp-python, I did finally get it to work.

**Comment by JSLinked** [comment]
@ZenbladeJS - apologies but for less technical types, where/how do you add "pip install llama-cpp-python --upgrade"

**Comment by ZenbladeJS** [comment]
> @ZenbladeJS - apologies but for less technical types, where/how do you add "pip install llama-cpp-python --upgrade"
@JSLinked 

It might not actually be necessary to do that, I have been helping other people with getting CPU mode to work. It is more important that you make sure the command to run the server (located in start-webui.bat or start-webui.sh for linux) is something along the lines of:

call python server.py --auto-devices --chat --model [model folder name]

for windows users  or 

python server.py --auto-devices --chat --model [model folder name]

for linux users.

And make sure that the only think in the model folder is the ggml-[model name].bin
For alpaca I recommend the 7b parameter one that can be found here: https://huggingface.co/Sosaka/Alpaca-native-4bit-ggml/blob/main/ggml-alpaca-7b-q4.bin

However if and only if after doing all of that you still get the error message this post was made then assuming you're running Windows put the following line before the python server.py line should temporarily be:

call pip install llama-cpp-python --upgrade

**Comment by JSLinked** [comment]
Tried all that. Still no success. Have attached a screenshot of the errors to see if that helps.
![cmd-screenshot](https://user-images.githubusercontent.com/115443488/231119210-a4441fd0-c114-409d-abb9-2e11cd6e3609.png)

**Comment by answerecho** [comment]
> 
I tried this fix and then I tried downloading the model from hugging face inside of the web gui (running cpu mode) without the model argument (which works but doesn't show any models), and then tried putting the name of the model directory directly or just the name like you originally had and got something like this either way: `Starting the web UI...
C:\Users\ourun\Desktop\oobabooga-windows\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading \anon8231489123_gpt4-x-alpaca-13b-native-4bit-128g\gpt-x-alpaca-13b-native-4bit-128g...
Traceback (most recent call last):
  File "C:\Users\ourun\Desktop\oobabooga-windows\oobabooga-windows\text-generation-webui\server.py", line 905, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\ourun\Desktop\oobabooga-windows\oobabooga-windows\text-generation-webui\modules\models.py", line 125, in load_model
    from modules.GPTQ_loader import load_quantized
  File "C:\Users\ourun\Desktop\oobabooga-windows\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 14, in <module>
    import llama_inference_offload
ModuleNotFoundError: No module named 'llama_inference_offload'
Press any key to continue . . .
`
However the gui works without adding the --model argument, but breaks whenever I add the module argument

**Comment by matthew-mcallister** [comment]
Why is this issue closed? The bug still exists.
