### ISSUE TITLE
Can we get RWKV model family support?

### ISSUE THREAD

**Issue by ye7iaserag** [oobabooga/text-generation-webui#98]
A very promising RNN based model, instead of transformers, claiming more lean memory consumption and faster inference 

Here is the 14b card
https://huggingface.co/BlinkDL/rwkv-4-pile-14b

**Comment by Slug-Cat** [comment]
That would be quite interesting

**Comment by oobabooga** [comment]
The lack of huggingface integration makes this challenging, but it should be possible.

**Comment by ye7iaserag** [comment]
Here is client code from the author https://github.com/BlinkDL/ChatRWKV

**Comment by BlinkDL** [comment]
Here is the API for RWKV: https://github.com/BlinkDL/ChatRWKV/blob/main/v2/api_demo.py
Very simple to use :)

**Comment by BlinkDL** [comment]
ChatRWKV v2: with "stream" and "split" strategies. 3G VRAM is enough to run RWKV 14B :)
RWKV v2 API https://github.com/BlinkDL/ChatRWKV/blob/main/v2/api_demo.py
```
os.environ["RWKV_JIT_ON"] = '1'
from rwkv.model import RWKV                         # everything in /v2/rwkv folder
model = RWKV(model='/fsx/BlinkDL/HF-MODEL/rwkv-4-pile-1b5/RWKV-4-Pile-1B5-20220903-8040', strategy='cuda fp16')

out, state = model.forward([187, 510, 1563, 310, 247], None)   # use 20B_tokenizer.json
print(out.detach().cpu().numpy())                   # get logits
out, state = model.forward([187, 510], None)
out, state = model.forward([1563], state)           # RNN has state (use deepcopy if you want to clone it)
out, state = model.forward([310, 247], state)
print(out.detach().cpu().numpy())                   # same result as above
```

**Comment by BlinkDL** [comment]
> @BlinkDL is it possible to construct a wrapper to the model that simply does something like this?
> 
> ```
> prompt = "What I would like to say is: "
> completion = model_RWKV.generate(prompt, max_new_tokens=20)
> print(completion)
> ```
> 
> That would be very helpful.

Sure. How about temp, top-p, top-k stuffs?

**Comment by oobabooga** [comment]
Those things are nice, but not essential at first. FlexGen for instance has departed from HuggingFace classes but still provided a `model.generate` function that was trivial to use for clueless people (like me).

**Comment by BlinkDL** [comment]
> Those things are nice, but not essential at first. FlexGen for instance has departed from HuggingFace classes but still provided a `model.generate` function that was trivial to use for clueless people (like me).

updated https://github.com/BlinkDL/ChatRWKV/blob/main/v2/api_demo.py

```
def generate(prompt, max_new_tokens, state=None):
    out = ''
    all_tokens = []
    for i in range(max_new_tokens):
        out, state = model.forward(tokenizer.encode(prompt) if i == 0 else [token], state)
        token = tokenizer.sample_logits(out, None, None, temperature=1.0, top_p=0.8)
        all_tokens += [token]
        tmp = tokenizer.decode(all_tokens)
        if '\ufffd' not in tmp: # is it a valid utf-8 string?
            out = tmp
    return out

prompt = "What I would like to say is: "
print(prompt, end='')
completion = generate(prompt, max_new_tokens=20)
print(completion)
```

**Comment by BlinkDL** [comment]
I added some tips to https://github.com/BlinkDL/ChatRWKV/blob/main/v2/api_demo.py

**Comment by oobabooga** [comment]
Very nice, @BlinkDL! Thank you for this. I will try incorporating it into the web UI later.

**Comment by BlinkDL** [comment]
Now ChatRWKV is fast at preprocessing the context if you set os.environ["RWKV_CUDA_ON"] = '1' before loading it :)

It will use ninja to compile a cuda kernel. You can distribute the compiled kernels to those without compiler.

**Comment by oobabooga** [comment]
We have a first successful run: https://github.com/oobabooga/text-generation-webui/commit/ebc64a408c1c36df98a4487eefc10a3876500e6c

![first-run](https://user-images.githubusercontent.com/112222186/221735781-57c0a2e9-22e3-4230-bd72-f26b2804d072.png)

I am very impressed with the coherence of the model so far, even though I have used the smallest version.  

@BlinkDL I have a few questions:

- What are `alpha_frequency` and `alpha_presence` in terms of Hugging Face parameters? These are the parameters that I am using at the moment:

> max_new_tokens, do_sample, temperature, top_p, typical_p, repetition_penalty, top_k, min_length, no_repeat_ngram_size, num_beams, penalty_alpha, length_penalty, early_stopping, eos_token

- Is there a way of adding the library to my project other than cloning the repository and importing from the `rwkv` folder?

**Comment by BlinkDL** [comment]
For alpha_frequency and alpha_presence, see "Frequency and presence penalties":
https://platform.openai.com/docs/api-reference/parameter-details

Please clone and import until I make the pip package :) Too busy at the moment, but I will do it.

**Comment by BlinkDL** [comment]
The pip package is here :)
https://pypi.org/project/rwkv/

**Comment by Ph0rk0z** [comment]
That 3g of memory is all GPU? Or is it offloaded? Would this scale to a 60B model and fit in a single GPU?

**Comment by oobabooga** [comment]
Much easier with the pip package. Some more tweaks and I should be able to merge the PR.

**Comment by oobabooga** [comment]
I have merged the PR the RWKV models now work in the web UI. Some comments:

1. I have made succesful tests with `RWKV-4-Pile-7B-20221115-8047.pth` and `RWKV-4-Pile-169M-20220807-8023.pth`. I ran out of GPU memory with `RWKV-4-Pile-14B-20230213-8019.pth` (RTX 3090).
2. To install a model, just place .pth and the `20B_tokenizer.json` file inside the `models` folder.
3. In order to make the process of loading the model more familar, I created a RWKV module with the following methods: `RWKVModel.from_pretrained` and `RWKVModel.generate`. Source code: https://github.com/oobabooga/text-generation-webui/blob/main/modules/RWKV.py
4. Only the `top_p` and `temperature` parameters can be changed in the interface for now. I am reluctant to add `alpha_frequency` and `alpha_presence` sliders because these parameters are used exclusively by RWKV and this change would break the API. They are left hardcoded to the default values of 0.25.
5. It is possible to run the models in CPU mode with `--cpu`. By default, they are loaded to the GPU.
6. The best way to try the models is with `python server.py --no-stream`. That is, without `--chat`, `--cai-chat`, etc.

This is the full code for the PR: https://github.com/oobabooga/text-generation-webui/pull/149/files

There is probably lots of room for improvement.

**Comment by BlinkDL** [comment]
Please use rwkv==0.0.6 (fix a bug with temperature for CPU)

You can use "strategies" to load 14B on 3090. For example 'cuda fp16 *30 -> cpu fp32' [try increasing 30, for better speed, until you run out of VRAM]

**Comment by oobabooga** [comment]
> Please use rwkv==0.0.6

Done. I have added a new flag to let users specify their custom strategies manually:

```
  --rwkv-strategy RWKV_STRATEGY             The strategy to use while loading RWKV models. Examples: "cpu fp32", "cuda fp16", "cuda fp16 *30 -> cpu fp32".
```

As you suggested, `"cuda fp16 *30 -> cpu fp32"` allowed me to get a response from the 14b model with 24GB VRAM.

**Comment by oobabooga** [comment]
My streaming implementation is probably really dumb and much slower than it could be:

```python
            for i in range(max_new_tokens//8):
                reply = shared.model.generate(question, token_count=8, temperature=temperature, top_p=top_p)
                yield formatted_outputs(reply, shared.model_name)
                question = reply

```

It would be best to use the `callback` argument but I haven't figured out how yet.

**Comment by ye7iaserag** [comment]
@BlinkDL You said earlier `ChatRWKV v2: with "stream" and "split" strategies. 3G VRAM is enough to run RWKV 14B`
Yet @oobabooga said it went OOM on a 3090 (24GB of vram)
What am I missing?

**Comment by BlinkDL** [comment]
> @BlinkDL You said earlier `ChatRWKV v2: with "stream" and "split" strategies. 3G VRAM is enough to run RWKV 14B` Yet @oobabooga said it went OOM on a 3090 (24GB of vram) What am I missing?

see the post above you.
"As you suggested, "cuda fp16 *30 -> cpu fp32" allowed me to get a response from the 14b model with 24GB VRAM."

**Comment by Ph0rk0z** [comment]
If it replies faster/better than a regular 13b even with the split, it's still something. Plus the faster time to train. But I guess miracles we will not get.

**Comment by BlinkDL** [comment]
> If it replies faster/better than a regular 13b even with the split, it's still something. Plus the faster time to train. But I guess miracles we will not get.

Why not? RWKV is faster than regular 13b and better on many tasks.

**Comment by ye7iaserag** [comment]
@BlinkDL but its 24gb not 3gb, i really wanned to run that on 3080ti which only has 12gbs

**Comment by BlinkDL** [comment]
> @BlinkDL but its 24gb not 3gb, i really wanned to run that on 3080ti which only has 12gbs

"cuda fp16 *12 -> cpu fp32" [try increasing 12, for better speed, until you run out of VRAM]

**Comment by Ph0rk0z** [comment]
Tried the 14b. The coherence is excellent but the reply times were in the 160s range.

Loaded it like this:
```
python server.py --no-stream --model rwkv-4-pile-14b --rwkv-strategy "cuda fp16 *30 -> cpu fp32"
python server.py --cai-chat --no-stream --model rwkv-4-pile-14b --rwkv-strategy "cuda fp16 *30 -> cpu fp32"
```
Used about 20gb of vram/20gb ram. During generation it only used a single core and the GPU was mostly idle. Was that a bug?
I think either using more GPU time or cores would tremendously help.

![rwkv](https://user-images.githubusercontent.com/59298527/222633501-e3104bec-9cd9-4cb4-9f00-17e9bdbaa906.png)

**Comment by BlinkDL** [comment]
Hi :) As I said before, [try increasing 30, for better speed, until you run out of VRAM].

Increase the "30" in cuda fp16 *30 to compute more layers on your GPU.

I notice Pytorch is buggy on some CPUs where it can only use single CPU thread (so extremely slow).

In this case, try "cuda fp16 *30+" to stream all layers on your GPU. Increase the "30" for better speed, until you run out of VRAM.

**Comment by BlinkDL** [comment]
Moreover, set os.environ["RWKV_CUDA_ON"] = '1' in https://github.com/oobabooga/text-generation-webui/blob/main/modules/RWKV.py for 10x speedup of reply time

**Comment by Ph0rk0z** [comment]
Using flexgen my AMD cpu pegs all cores. Is it the CPU brand or https://wiki.python.org/moin/GlobalInterpreterLock ?

I tried the cuda setting and GPU does appear to be used more. Not solid as by other models where it starts whining, but the line in the monitoring tool stays at the top with some dips. Had to turn down the layers to 29 to be able to use context in chat mode.

Generation goes down by half but is still in the 70s range. With zero context I saw 40 or 50s. I think if it's possible to solve the CPU problem, this model will be really awesome. The replies are great and I'm downloading a smaller one to test on GPU only.

BTW, to get that kernel to compile I had to download the cuda toolkit and do:

`sudo ln -s /usr/local/cuda/lib64/libcudart.so /usr/lib/libcudart.so`

There is no timing feature yet for the generations so I have to watch the seconds tick, but I'm sure that will come with time, especially when performance go up.

For context, this is opt-13b with CPU weights and GPU attention + activation.

```
Output generated in 12.53 seconds (0.80 it/s, 80 tokens)
Output generated in 10.57 seconds (0.95 it/s, 80 tokens)
Output generated in 10.50 seconds (0.95 it/s, 80 tokens)
```

**Comment by BlinkDL** [comment]
It's purely pytorch issue because the CPU utilization is fine for most Intel CPUs and AMD server CPUs. I will ask pytorch guys.

Please see whether "cuda fp16 *29+" will be faster than "cuda fp16 *29 -> cpu fp32" in your case.

Yes and ctx4096 models run at same speed as ctx1024 models. I am finetuning 7B to ctx8k and 14B to 16k :)

**Comment by Ph0rk0z** [comment]
"cuda fp16 *29+" was slightly faster and appeared to use slightly more GPU even without the RWKV_CUDA_ON.

Memory usage was the same.

I'll see how the 7b performs.

**Comment by oobabooga** [comment]
I have been trying to compile the CUDA kernel with 

```
os.environ["RWKV_CUDA_ON"] = '1'
```

but am getting this error:

```
gcc: fatal error: cannot execute 'cc1plus': execvp: No such file or directory
```

even though I have `build-essential` installed already.

Once I figure this out this I will write some proper documentation for RWKV in the wiki.

**Comment by Ph0rk0z** [comment]
Do you have g++ installed?

What does: `g++ --print-prog-name=cc1plus` say?
Mine outputs` /usr/lib/gcc/x86_64-linux-gnu/9/cc1plus`


I did some more testing, speed is improved slightly. That cuda preprocess does very little.


```
80 tokens. no cuda 14b (4096) max 2k context
Output generated in 66.62 seconds.

80 tokens. cuda 14b (4096) max 2k context
Output generated in 60.47 seconds.
Output generated in 58.11 seconds.
Output generated in 58.21 seconds.
Output generated in 56.78 seconds.
Output generated in 58.66 seconds.
Output generated in 56.90 seconds.


```

All in all this model handles 4096 context good enough. Maybe the limits should be raised.

**Comment by BlinkDL** [comment]
> All in all this model handles 4096 context good enough. Maybe the limits should be raised.
RWKV-ctx4096 models can handle ctx4k :)

The difference between cuda and non-cuda is huge if you are running full model on GPU.

From someone:
The current generation speed for RWKV 14B for a batch size of 1 and INT8 quantization (no quality loss compared to bf16) is 5.5 tokens/s on an EPYC 7313 CPU. On a RTX A6000 GPU it is 37 tokens/s with a max VRAM of 15 GB.

**Comment by Ph0rk0z** [comment]
Have to spend another $2k USD for epyc from CN or a dell SXM box. Right now I have to do as AvE says and.... use the quadro I got.

**Comment by BlinkDL** [comment]
> Have to spend another $2k USD for epyc from CN or a dell SXM box. Right now I have to do as AvE says and.... use the quadro I got.

Or you can use two cheap GPUs with lots of VRAM...

**Comment by BlinkDL** [comment]
> Have to spend another $2k USD for epyc from CN or a dell SXM box. Right now I have to do as AvE says and.... use the quadro I got.

Please git pull ChatRWKV & [pip install rwkv --upgrade] (to 0.0.7) and see if RAM usage during loading is reduced.
@oobabooga pls try rwkv 0.0.7 too

**Comment by oobabooga** [comment]
Seems to be working as expected. https://github.com/oobabooga/text-generation-webui/commit/145c725c395f1bfbb448217ef5bb98412ed9f3ce

**Comment by BlinkDL** [comment]
Please use ctx4096 models for 3B / 7B / 14B by default. They are better :)
https://huggingface.co/BlinkDL/rwkv-4-pile-3b/blob/main/RWKV-4-Pile-3B-20221110-ctx4096.pth
https://huggingface.co/BlinkDL/rwkv-4-pile-7b/blob/main/RWKV-4-Pile-7B-20230109-ctx4096.pth
https://huggingface.co/BlinkDL/rwkv-4-pile-14b/blob/main/RWKV-4-Pile-14B-20230228-ctx4096-test663.pth

**Comment by BlinkDL** [comment]
INT8 is here :) slow but faster than CPU.
https://pypi.org/project/rwkv/

**Comment by oobabooga** [comment]
It works, I have managed to load the 14B model with about 16GB VRAM using `--rwkv-strategy "cuda fp16i8"`.

I have written a little guide about how to use RWKV with the web UI with the information that I have so far: https://github.com/oobabooga/text-generation-webui/wiki/RWKV-model

I have also added a `--rwkv-cuda-on`flag  that sets `RWKV_CUDA_ON` to `1` before loading the model. It doesn't work for me though. First I had an error telling me that `cc1plus` didn't exist even though I have `build-essential` installed on my system, so I created a symlink for `cc1plus` manuallly from `/usr/lib/gcc/x86_64-linux-gnu/11/cc1plus` to `/usr/local/bin`. Now I get "file not found" for

```
  111 | #include <new>
      |          ^~~~~

```

I'm still trying...

**Comment by BlinkDL** [comment]
> It works, I have managed to load the 14B model with about 16GB VRAM using `--rwkv-strategy "cuda fp16i8"`.

For better speed, try sth like 'cuda fp16i8 *10 -> cuda fp16' (increase 10 for better speed)

```
# Basic Strategy Guide:
# 100% VRAM = 'cuda fp16'                   # all layers cuda fp16
#  97% VRAM = 'cuda fp16i8 *1 -> cuda fp16' # first 1 layer  cuda fp16i8, then cuda fp16
#  95% VRAM = 'cuda fp16i8 *2 -> cuda fp16' # first 2 layers cuda fp16i8, then cuda fp16
#  93% VRAM = 'cuda fp16i8 *3 -> cuda fp16' # first 3 layers cuda fp16i8, then cuda fp16
#  ...
#  50% VRAM = 'cuda fp16i8'                 # all layers cuda fp16i8
#  48% VRAM = 'cuda fp16i8 -> cpu fp32 *1'  # most layers cuda fp16i8, last 1 layer  cpu fp32
#  46% VRAM = 'cuda fp16i8 -> cpu fp32 *2'  # most layers cuda fp16i8, last 2 layers cpu fp32
#  44% VRAM = 'cuda fp16i8 -> cpu fp32 *3'  # most layers cuda fp16i8, last 3 layers cpu fp32
#  ...
#   0% VRAM = 'cpu fp32'                    # all layers cpu fp32
```NOTE: streaming fp16i8 is very slow. use this for stream mode:
```
'cuda fp16i8 *10 -> cuda fp16 *0+' = first 10 layers cuda fp16i8, then fp16 stream the rest to it (increase 10 for better speed)
```

**Comment by Ph0rk0z** [comment]
So best strategy is to load as few int8 layers as possible?

**Comment by BlinkDL** [comment]
> So best strategy is to load as few int8 layers as possible?

Yes. They are much slower than fp16 layers at the moment (will be faster than fp16 when we use CUDA for it).

**Comment by oobabooga** [comment]
I have implemented proper streaming for RWKV https://github.com/oobabooga/text-generation-webui/commit/19a34941ed9daeeb93ab951645b61957e4df5376. It is now possible to do

```
for reply in shared.model.generate_with_streaming(context=question, token_count=max_new_tokens, temperature=temperature, top_p=top_p, top_k=top_k):
    yield formatted_outputs(reply, shared.model_name)
```

and get yield the partial replies to the UI in real time without the need to call `shared.model.generate` multiple times with `token_count=8`. This makes streaming extremely fast for this model, much faster than for HF models, since they do not support callbacks.

Now that we already have proper streaming, `top_k`, `top_p`, and `temperature`, the only thing I am missing to get the most out of this model is a `repetition_penalty` parameter.

**Comment by KnutJaegersberg** [comment]
I was trying to use quantized models RWKV-4-Pile-14B.pqth and RWKV/RWKV-4-Pile-7B-Instruct.pqth
It throws an exception, seems to expect pth files only.

**Comment by BlinkDL** [comment]
> I was trying to use quantized models RWKV-4-Pile-14B.pqth and RWKV/RWKV-4-Pile-7B-Instruct.pqth It throws an exception, seems to expect pth files only.

yeah please only use pth because my code will do the quantization instead

**Comment by Ph0rk0z** [comment]
Tried it. Works fine in 8bit on old GPU and reduces memory a bunch. Feels slower as it takes me over 100s to generate now whichever way I load it. Between 8bit and CPU offload there is now a 10% difference. The speed measurement stopped outputting too and I'm left watching the clock.

I do like the multi process model loading. After the first time the model re-loads very fast.

**Comment by KnutJaegersberg** [comment]
I found some of those models with qpth on the hub. Have not seen unquantized alternatives for 7B instruct?! 
So is there an 8 bit mode for RWKV?

**Comment by BlinkDL** [comment]
> Tried it. Works fine in 8bit on old GPU and reduces memory a bunch. Feels slower as it takes me over 100s to generate now whichever way I load it. Between 8bit and CPU offload there is now a 10% difference. The speed measurement stopped outputting too and I'm left watching the clock.

Can you see the CUDA kernel being compiled by ninja?
Like this at program start:
```
Using /fsx/BlinkDL/.cache/torch_extensions as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /fsx/BlinkDL/.cache/torch_extensions/wkv_cuda/build.ninja...
Building extension module wkv_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module wkv_cuda...
```

**Comment by Ph0rk0z** [comment]
Yes, it compiled a new cuda kernel when I first ran it. It is definitely using it. I think the bits and bytes is slightly faster on my card when I solved the NaN error. Maybe you don't notice it on a newer architecture.

**Comment by BlinkDL** [comment]
Please update ChatRWKV v2 & pip rwkv package (0.3.0) for 2x faster f16i8 (and less VRAM) and fast f16i8+ streaming.

**Comment by oobabooga** [comment]
Done https://github.com/oobabooga/text-generation-webui/commit/441e993c51ac100fa4565419791cd9a88fd8d3df

**Comment by jurandfantom** [comment]
Hi everybody, hope somebody take look at this. Would be possible to write down steep by steep solution for people like me who have no clue about code and how to wrangle and find solution by ourselfs? 
Atm i stuck with following error.
![23,03,13 - 02,26,50 - 7368 a](https://user-images.githubusercontent.com/30580568/224594518-dfc37d27-16bd-49b9-9c23-0212356051be.png)




Everything was done according to tutorials, articles and even discord KoboldAI RWKV room. 
Most suggested and updated model is placed in subfolder alongside with tokenizer.
No name changed for tokenizer
TGW installed according to manual command method instead one click windows
Freshly reinstalled whole python (anaconda, miniconda), pip and what was possible to avoid any issues during installation.

![23,03,13 - 02,20,46 - 7367 a](https://user-images.githubusercontent.com/30580568/224593435-de789fd3-23b6-498c-a8aa-19a55ccb91f4.png)

**Comment by oobabooga** [comment]
Try removing `--rwkv-cuda-on` and see if it works. This flag executes an additional compilation step that has requirements like a C++ compiler and some CUDA headers.

**Comment by jurandfantom** [comment]
such thing was already tested (o hi oobabooga - really appreciate that you take time to help me - I saw all your previous posts :) )

![image](https://user-images.githubusercontent.com/30580568/224597795-cd09359f-f077-466e-8444-eabe8e0901bf.png)

**Comment by oobabooga** [comment]
Can you try updating to see if this fixed it? https://github.com/oobabooga/text-generation-webui/commit/77294b27ddce0c098a8f51b8cd9bd8c151a506f8

I think that the path that was being passed to RWKV was broken on Windows.

**Comment by jurandfantom** [comment]
I can update (but installation was made 1h ago so not sure there will be anything to update). To be sure, what method of update you suggest? just "git pull" or something different? I see you pasted number, but except fact of click it, I have no clue what to do with it. (its 3am for me so I will go in next 15 minutes - will wait till your next reply )

**Comment by oobabooga** [comment]
Just a simple `git pull` is enough.

**Comment by jurandfantom** [comment]
![image](https://user-images.githubusercontent.com/30580568/224600216-80638bda-5f85-4f58-8d09-59952101288b.png)

Quite solid download, but message didn't change. I gonna go and will check for other suggestions - sorry for cause issues. In theory everything should work so no clue (I "even" started it from command line instead .bat, but that dosn't change anything )

![image](https://user-images.githubusercontent.com/30580568/224600263-ae1fd59a-18c7-4bc3-b6a8-ec4b683ef371.png)

**Comment by BlinkDL** [comment]
Update ChatRWKV v2 & pip rwkv package (0.4.0) for 2x speed in all modes @oobabooga

**Comment by Ph0rk0z** [comment]
I had to up i8 layers to 18 to keep my 2k context but speed is better than 8bit or 4bit llama 13b.

```
14b streaming 

Output generated in 16.61 seconds (1.63 tokens/s, 27 tokens)
Output generated in 11.99 seconds (1.83 tokens/s, 22 tokens)
Output generated in 16.14 seconds (2.11 tokens/s, 34 tokens)
```

llama 13 responds in ~30 sec and the 30b responds in ~60sec so really 2x speed.

**Comment by BlinkDL** [comment]
@oobabooga new and better RWKV 14B ctx8192 https://huggingface.co/BlinkDL/rwkv-4-pile-14b/blob/main/RWKV-4-Pile-14B-20230313-ctx8192-test1050.pth

(there is 7B ctx8192 too but not as good as ctx4096 yet when ctxlen < 3k)

**Comment by BlinkDL** [comment]
Update ChatRWKV v2 & pip rwkv package (0.5.0) and set os.environ["RWKV_CUDA_ON"] = '1' 
for 1.5x speed f16i8 (and 10% less VRAM, now 14686MB for 14B instead of 16462M - so you can put more layers on GPU)
PLEAES VERIFY THE GENERATION QUALITY IS UNCHANGED.
@Ph0rk0z

**Comment by Ph0rk0z** [comment]
New one is blocked by https://github.com/BlinkDL/ChatRWKV/issues/38

**Comment by ye7iaserag** [comment]
got it working with 
```
python server.py --cai-chat --listen --listen-port=8888 --model=RWKV-4-Pile-14B-20230228-ctx4096-test663.pth --rwkv-cuda-on --rwkv-strategy="cuda fp16i8 *25 -> cpu fp32"
```
on a 3080ti with 12gb of varam and 64gb of ram
Thanks a lot @BlinkDL and @oobabooga

**Comment by BlinkDL** [comment]
> on a 3080ti with 12gb of varam and 64gb of ram Thanks a lot @BlinkDL and @oobabooga
Latest model: https://huggingface.co/BlinkDL/rwkv-4-pile-14b/blob/main/RWKV-4-Pile-14B-20230313-ctx8192-test1050.pth
:)

**Comment by ye7iaserag** [comment]
> > on a 3080ti with 12gb of varam and 64gb of ram Thanks a lot @BlinkDL and @oobabooga
> 
> Latest model: https://huggingface.co/BlinkDL/rwkv-4-pile-14b/blob/main/RWKV-4-Pile-14B-20230313-ctx8192-test1050.pth :)

Yes downloading now after I saw your reddit post, and I asked there what's the difference between this version and the previous one?

**Comment by BlinkDL** [comment]
Update ChatRWKV v2 & pip rwkv package (0.6.0):

The os.environ["RWKV_CUDA_ON"] = '1' mode is now 10% faster for f16i8 on all GPUs, and supports old GPUs.

Supports "chunk_len" in PIPELINE_ARGS, which can split long inputs into chunks to save VRAM (shorter -> slower).
Default = 256  @oobabooga

**Comment by BlinkDL** [comment]
> New one is blocked by [BlinkDL/ChatRWKV#38](https://github.com/BlinkDL/ChatRWKV/issues/38)

fixed in latest version :)

**Comment by Ph0rk0z** [comment]
After I update transformers it's loading using a single core again and it is abysmal. Performance is also as you see since only one CPU is used now.

```
0.6.0
Output generated in 90.31 seconds (0.13 tokens/s, 12 tokens)
Output generated in 86.88 seconds (0.12 tokens/s, 10 tokens)
Output generated in 23.34 seconds (0.47 tokens/s, 11 tokens)
Output generated in 24.15 seconds (0.41 tokens/s, 10 token

0.4.2
Output generated in 9.00 seconds (1.00 tokens/s, 9 tokens)
Output generated in 5.08 seconds (1.97 tokens/s, 10 tokens)
Output generated in 3.86 seconds (1.56 tokens/s, 6 tokens)
Output generated in 6.61 seconds (2.12 tokens/s, 14 tokens)
Output generated in 17.30 seconds (2.60 tokens/s, 45 tokens)
```

I even tried clearing the chat :( no help.

**Comment by BlinkDL** [comment]
Update ChatRWKV v2 & pip rwkv package (0.7.0):
Use v2/convert_model.py to convert a model for a strategy, for faster loading & saves CPU RAM. 

@Ph0rk0z what is the problematic transformers version

**Comment by Ph0rk0z** [comment]
Transformers went from using multiple cores during GPTQ and model loading to single core but I did a test and it proves performance is better at least for llama. BTW I was meaning to ask why I can't get deterministic result from RWKV?

I will test the perf of the new update. in a minute.

**Comment by BlinkDL** [comment]
> BTW I was meaning to ask why I can't get deterministic result from RWKV?

Non-deterministic if you use the CUDA kernel because of non-deterministic float point computation orders

**Comment by Ph0rk0z** [comment]
Ahh. that makes some sense. Time to check it.

**Comment by Ph0rk0z** [comment]
For my Pascal based card at least there is no difference. 

```
0.7.0 
Output generated in 92.55 seconds (0.23 tokens/s, 21 tokens)
Output generated in 83.81 seconds (0.19 tokens/s, 16 tokens)
Output generated in 84.42 seconds (0.08 tokens/s, 7 tokens)

0.4.2 - today
Output generated in 8.07 seconds (0.87 tokens/s, 7 tokens)
Output generated in 4.38 seconds (1.82 tokens/s, 8 tokens)
Output generated in 3.82 seconds (1.57 tokens/s, 6 tokens)
Output generated in 11.94 seconds (2.51 tokens/s, 30 tokens)

```

90s is same response time as offloaded 30b model. I think fix for older GPU made it run very slow.

**Comment by BlinkDL** [comment]
> 90s is same response time as offloaded 30b model. I think fix for older GPU made it run very slow.

Can you benchmark 0.5.0 0.6.0 0.6.1 0.6.2 so that I can find the issue?

**Comment by Slug-Cat** [comment]
I am unable to use the --rwkv-cuda-on option, as I get this error:
`Traceback (most recent call last):
  File "E:\oobabooga\text-generation-webui\server.py", line 241, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "E:\oobabooga\text-generation-webui\modules\models.py", line 90, in load_model
    from modules.RWKV import RWKVModel, RWKVTokenizer
  File "E:\oobabooga\text-generation-webui\modules\RWKV.py", line 15, in <module>
    from rwkv.model import RWKV
  File "E:\oobabooga\installer_files\env\lib\site-packages\rwkv\model.py", line 29, in <module>
    load(
  File "E:\oobabooga\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "E:\oobabooga\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 1508, in _jit_compile
    _write_ninja_file_and_build_library(
  File "E:\oobabooga\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 1592, in _write_ninja_file_and_build_library
    verify_ninja_availability()
  File "E:\oobabooga\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py", line 1648, in verify_ninja_availability
    raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions`

**Comment by BlinkDL** [comment]
> The problem started when you changed the int8 multiplication to something unsupported. The fix for that is too slow so I have been using 0.4.2.

We will try a fp32i8 kernel soon (similar VRAM usage as fp16i8)

**Comment by BarfingLemurs** [comment]
can we use this on this webui with longer context length than 2048? I would like to see if I could summarize a long article.
