### ISSUE TITLE
Web UI doesnt start

### ISSUE THREAD

**Issue by IAteYourCookies** [oobabooga/text-generation-webui#980]
### Describe the bug

When i try to start the UI, it just doesnt start ... i have tried reinstalling like 5 times already but i never got it to start even once
(I used 1 click install - i ran it in conda)
I try to run: gpt4-x-alpaca

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I have no idea if it is just my pc but i just normally clicked the install.bat and tried to run it later using the start-webui.bat

### Logs

```shell
Starting the web UI...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: Loading binary E:\Users\cookiez\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll...
E:\Users\cookiez\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading gpt4-x-alpaca-13b-native-4bit-128g...
CUDA extension not installed.
Loading model ...
Done.
Traceback (most recent call last):
  File "E:\Users\cookiez\oobabooga-windows\text-generation-webui\server.py", line 302, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "E:\Users\cookiez\oobabooga-windows\text-generation-webui\modules\models.py", line 102, in load_model
    model = load_quantized(model_name)
  File "E:\Users\cookiez\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 153, in load_quantized
    model = model.to(torch.device('cuda:0'))
  File "E:\Users\cookiez\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 1888, in to
    return super().to(*args, **kwargs)
  File "C:\Users\cookiez\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 987, in to
    return self._apply(convert)
  File "C:\Users\cookiez\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 639, in _apply
    module._apply(fn)
  File "C:\Users\cookiez\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 639, in _apply
    module._apply(fn)
  File "C:\Users\cookiez\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 662, in _apply
    param_applied = fn(param)
  File "C:\Users\cookiez\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 985, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "C:\Users\cookiez\AppData\Roaming\Python\Python310\site-packages\torch\cuda\__init__.py", line 221, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Press any key to continue . . .
```

### System Info

```shell
Ryzen 5 2600X
Rtx 3060 12GB
64GB ram
Windows 10
```

**Comment by jllllll** [comment]
The installer has been updated since you used it. I would highly recommend fully re-installing using the latest installer:
https://github.com/oobabooga/one-click-installers

**Comment by arvz** [comment]
I've run into the same problem and have double checked I'm using the latest one-click installer, logs look pretty much the same as  @IAteYourCookies's

**Comment by himansharma21** [comment]
Could you run the following within the Python enviroment you're using for textgen-webui in Python: 

```
import torch 
torch.cuda.is_available()
```

**Comment by IAteYourCookies** [comment]
It is available ... gives out True

**Comment by jllllll** [comment]
@IAteYourCookies I have updated the installer quite a bit since last time (again): https://github.com/jllllll/one-click-installers

I noticed in your initial report that you mentioned running the installer in conda. Don't do that. That's probably going to cause issues. Especially since I have changed the installer to use Miniconda. Make sure you install in an empty folder (no installer_files or text-generation-webui).
