### ISSUE TITLE
An error with latest build, don't know what's going on.

### ISSUE THREAD

**Issue by JohnWJarrett** [oobabooga/text-generation-webui#981]
### Describe the bug

So, decided to test out the Complex_memory addon, installed it, added a couple of memories for a custom char, enter a message and get hit with an error, restart, get latest build, say hello to the default char, get same error...

Here is my load string "--auto-devices --chat --listen --listen-port 8888 --extension sd_api_pictures send_pictures complex_memory --auto-launch --model OPT-2.7B-Erebus --verbose"

Here is the error:
"TypeError: custom_generate_chat_prompt() got an unexpected keyword argument '_continue'"

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load in with above string,
Say something to the bot
...
Profit?

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\Kitten\miniconda3\envs\textgen\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Kitten\miniconda3\envs\textgen\lib\site-packages\gradio\blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "C:\Users\Kitten\miniconda3\envs\textgen\lib\site-packages\gradio\blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Kitten\miniconda3\envs\textgen\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Kitten\miniconda3\envs\textgen\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Kitten\miniconda3\envs\textgen\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Kitten\miniconda3\envs\textgen\lib\site-packages\gradio\utils.py", line 490, in async_iteration
    return next(iterator)
  File "G:\oobabooga-windows\text-generation-webui\modules\chat.py", line 224, in cai_chatbot_wrapper
    for history in chatbot_wrapper(text, generate_state, name1, name2, context, mode, end_of_turn):
  File "G:\oobabooga-windows\text-generation-webui\modules\chat.py", line 146, in chatbot_wrapper
    prompt = custom_generate_chat_prompt(text, generate_state['max_new_tokens'], name1, name2, context, generate_state['chat_prompt_size'], **kwargs)
TypeError: custom_generate_chat_prompt() got an unexpected keyword argument '_continue'
```

### System Info

```shell
i7-8700K
32GB RAM
2080 Super (8GB)
Win 11
```

**Comment by oobabooga** [comment]
It should be the same fix as in here. I recommend creating a new issue in the extension repository

https://github.com/wawawario2/long_term_memory/issues/14#issuecomment-1500784643

**Comment by JohnWJarrett** [comment]
> It should be the same fix as in here. I recommend creating a new issue in the extension repository
> 
> [wawawario2#14 (comment)](https://github.com/wawawario2/long_term_memory/issues/14#issuecomment-1500784643)

Wait, that's for LTM, I am using Complex_Memory... So... I don't know where to do the fix, eh, I'll just uninstall it I guess...

**Comment by JohnWJarrett** [comment]
Turns out, it was an easier fix that with LTM, I just changed line 19 (of the script file) from
"def custom_generate_chat_prompt(user_input, max_new_tokens, name1, name2, context, chat_prompt_size, is_instruct, end_of_turn="", impersonate=False, also_return_rows=False):"
To
"def custom_generate_chat_prompt(user_input, max_new_tokens, name1, name2, context, chat_prompt_size, is_instruct, end_of_turn="", impersonate=False, also_return_rows=False, **kwargs):"
