### ISSUE TITLE
AttributeError: can't set attribute 'eos_token_id'

### ISSUE THREAD

**Issue by bbecausereasonss** [oobabooga/text-generation-webui#984]
### Describe the bug

Not sure what this is. Trying to load gpt4-x-alpaca-13b-native-4bit-128g-cuda, which was loading prior to this commit.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

call python server.py --model gpt4-x-alpaca-13b-native-4bit-128g-cuda --wbits 4 --groupsize 128 --model_type llama --chat --share --disk --gpu-memory 18

Error.

### Logs

```shell
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: Loading binary C:\Users\xxxx\Deep\text-diffusion-webui\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Loading gpt4-x-alpaca-13b-native-4bit-128g-cuda...
Loading model ...
Done.
Using the following device map for the 4-bit model: {'': 0}
Traceback (most recent call last):
  File "C:\Users\xxxx\Deep\text-diffusion-webui\text-generation-webui\server.py", line 302, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\xxxx\Deep\text-diffusion-webui\text-generation-webui\modules\models.py", line 177, in load_model
    tokenizer.eos_token_id = 2
AttributeError: can't set attribute 'eos_token_id'
Press any key to continue . . .
```

### System Info

```shell
Win11,x64 1click install Ooba (latest commit)
```

**Comment by bbecausereasonss** [comment]
Also a different error when loading 30b.

CUDA SETUP: Loading binary C:\Users\xxxx\Deep\text-diffusion-webui\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Loading elinas_alpaca-30b-lora-int4...
Loading model ...
C:\Users\xxxx\Deep\text-diffusion-webui\installer_files\env\lib\site-packages\safetensors\torch.py:99: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
C:\Users\xxxx\Deep\text-diffusion-webui\installer_files\env\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
C:\Users\xxxx\Deep\text-diffusion-webui\installer_files\env\lib\site-packages\torch\storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)

**Comment by oobabooga** [comment]
Your exact command works for me. Can you try updating transformers?

```
pip install -U git+https://github.com/huggingface/transformers
```

Since you are using the 1-click installer, paste that into the micromamba-cmd.bat prompt.

**Comment by bbecausereasonss** [comment]
Just did that and I think it updated/reinstalled transformers. Unfortunately getting the same errors :/

I'm still on the last branch of your reco'd GPTQ maybe thats the issue? was there an update? I'm on the one you recommended to roll back to.

**Comment by oobabooga** [comment]
Try updating to see if it works after this commit

https://github.com/oobabooga/text-generation-webui/commit/dba2000d2bf605dc0787e63b1cfb3e6c7722e4bd

**Comment by BadisG** [comment]
@bbecausereasonss uninstall transformers first, the pip command doesn't do a clean remove if you just try to update it

```pip uninstall transformers
pip install -U git+https://github.com/huggingface/transformers
```

**Comment by bbecausereasonss** [comment]
> 

That actually seems to have thrown an error earlier now.

Starting the web UI...
Traceback (most recent call last):
  File "C:\Users\xxxx\Deep\text-diffusion-webui\text-generation-webui\server.py", line 18, in <module>
    from modules import api, chat, shared, training, ui
  File "C:\Users\xxxx\Deep\text-diffusion-webui\text-generation-webui\modules\api.py", line 6, in <module>
    from modules.text_generation import generate_reply
  File "C:\Users\xxxx\Deep\text-diffusion-webui\text-generation-webui\modules\text_generation.py", line 14, in <module>
    from modules.models import clear_torch_cache, local_rank
  File "C:\Users\xxxx\Deep\text-diffusion-webui\text-generation-webui\modules\models.py", line 189
    continue
    ^^^^^^^^
SyntaxError: 'continue' not properly in loop

**Comment by VldmrB** [comment]
Same token setting error, last pull prior to this one was March 29th.
`transformers` re-install didn't help either. Haven't updated anything else, so same question as above, I guess.
Using 8-bit 13b, so shouldn't have been a problem? Commenting out the token eos setting lets it get past that, but I'm having another issue which could be caused by my local merged changes, so probably not worth sharing.

**Comment by bbecausereasonss** [comment]
Just did that and I think it updated/reinstalled transformers. Unfortunately, getting the same errors :/

> @bbecausereasonss uninstall transformers first, the pip command doesn't do a clean remove if you just try to update it
> 
> ```
> pip uninstall transformers
> pip install -U git+https://github.com/huggingface/transformers
> ```

Nope. Didn't help. The last commit made it worse actually.

Starting the web UI...
Traceback (most recent call last):
  File "C:\Users\xxxx\Deep\text-diffusion-webui\text-generation-webui\server.py", line 18, in <module>
    from modules import api, chat, shared, training, ui
  File "C:\Users\xxxx\Deep\text-diffusion-webui\text-generation-webui\modules\api.py", line 6, in <module>
    from modules.text_generation import generate_reply
  File "C:\Users\xxxx\Deep\text-diffusion-webui\text-generation-webui\modules\text_generation.py", line 14, in <module>
    from modules.models import clear_torch_cache, local_rank
  File "C:\Users\xxxx\Deep\text-diffusion-webui\text-generation-webui\modules\models.py", line 189
    continue
    ^^^^^^^^
SyntaxError: 'continue' not properly in loop

**Comment by oobabooga** [comment]
Oops, try replacing continue with pass https://github.com/oobabooga/text-generation-webui/commit/1911504f8205bfae5203185d89d7860a0f930974

**Comment by bbecausereasonss** [comment]
> Oops, try replacing continue with pass [1911504](https://github.com/oobabooga/text-generation-webui/commit/1911504f8205bfae5203185d89d7860a0f930974)

mine already says pass, still getting error.

**Comment by VldmrB** [comment]
After a clean transformers reinstall as per https://github.com/oobabooga/text-generation-webui/issues/984#issuecomment-1501320086, it seems to work fine anyway.
Maybe throwing a warning/error in that try/except would be helpful.

**Comment by bbecausereasonss** [comment]
Soke to soon, my 30B model is still not loading... but the 4bit quantized one was.

CUDA SETUP: Loading binary C:\Users\xxxxDeep\text-diffusion-webui\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Loading elinas_alpaca-30b-lora-int4...
Found the following quantized model: models\elinas_alpaca-30b-lora-int4\alpaca-30b-4bit-128g.safetensors
Loading model ...
C:\Users\xxxxDeep\Deep\text-diffusion-webui\installer_files\env\lib\site-packages\safetensors\torch.py:99: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
C:\Users\xxxxDeep\Deep\text-diffusion-webui\installer_files\env\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
C:\Users\xxxxDeep\Deep\text-diffusion-webui\installer_files\env\lib\site-packages\torch\storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)

**Comment by bbecausereasonss** [comment]
> After a clean transformers reinstall as per [#984 (comment)](https://github.com/oobabooga/text-generation-webui/issues/984#issuecomment-1501320086), it seems to work fine anyway. Maybe throwing a warning/error in that try/except would be helpful.

Not for me,  I did a clean re-install.

**Comment by bbecausereasonss** [comment]
Still getting the error :/

storage = cls(wrap_storage=untyped_storage)

**Comment by bbecausereasonss** [comment]
What's odd is it's loading other models but still passing the same error. However the 30b model just fails.

storage = cls(wrap_storage=untyped_storage)
Done.
Using the following device map for the 4-bit model: {'': 0}
Loaded the model in 63.70 seconds.
Loading the extension "gallery"... Ok.
Running on local URL:  http://127.0.0.1:7861
Running on public URL: https://23bd01ca81393d677a.gradio.live

This is the gozfarb_llama-13b-pretrained-sft-do2-4bit-128g loaded after error.

Fails on elinas_alpaca-30b-lora-int4

**Comment by oobabooga** [comment]
You are probably using a model that was converted with another version of gptq-for-llama.

**Comment by bbecausereasonss** [comment]
> You are probably using a model that was converted with another version of gptq-for-llama.

That's probably it, since all other models work fine. Anything I can do?

**Comment by bbecausereasonss** [comment]
> USBHost

This is the one I'm trying to run and it was running fine a few commits ago, I didn't change my GPTQ, so I'm a bit confused.

https://huggingface.co/elinas/alpaca-30b-lora-int4

**Comment by syntec11** [comment]
@bbecausereasonss 
I had this error too.  It worked fine for any of the 13b models I had, but not for the 30b ones (despite 4090, 48gig ram, Windows 10 as well).
What I tried today was manually setting my page file.  Boosted it way the hell up to start at 25000 and max out at 75000.
Doing that gave me the magic "done" and the url for the web ui, and tokens are flowing freely.
