### ISSUE TITLE
convert-to-safetensors works but convert-to-flexgen doesn't

### ISSUE THREAD

**Issue by Slug-Cat** [oobabooga/text-generation-webui#99]
Running 
`python convert-to-safetensors.py [path] `
works as expected, but when I try to run 
`python convert-to-flexgen.py [path]`
it gives the following error:
```
Loading PygmalionAI_pygmalion-2.7b...
Saving the converted model to models\PygmalionAI_pygmalion-2.7b-np...
Traceback (most recent call last):
  File "E:\oobabooga\text-generation-webui\convert-to-flexgen.py", line 59, in <module>
    for name, param in tqdm(list(model.model.named_parameters())):
  File "E:\oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GPTNeoForCausalLM' object has no attribute 'model'
```
A folder is created at the specified location, but no model is saved.

**Comment by oobabooga** [comment]
Flexgen only works for OPT models at the moment. I will write some proper documentation for this once I finish figuring it out, but since you are interested, you can try:

`python convert-to-flexgen.py models/opt-1.3b/`

And then

`python server.py --model opt-1.3b --listen --flexgen`

It is necessary to install flexgen first. The results are quite amazing. I have managed to run opt-6.7b with about 2GB VRAM.

**Comment by Slug-Cat** [comment]
Oh, that's quite unfortunate. I'll give that a go, though, the tech seems quite capable from what I've read. Any idea if GPT support is planned?

**Comment by oobabooga** [comment]
This looks like a demo made by academics for a paper. It supports just 2 generation parameters (do_sample and temperature), and just 1 model (OPT). I guess it will be picked up by HuggingFace and generalized at some point, but we can only speculate.

**Comment by Slug-Cat** [comment]
> Flexgen only works for OPT models at the moment. I will write some proper documentation for this once I finish figuring it out, but since you are interested, you can try:
> 
> `python convert-to-flexgen.py models/opt-1.3b/`
> 
> And then
> 
> `python server.py --model opt-1.3b --listen --flexgen`
> 
> It is necessary to install flexgen first. The results are quite amazing. I have managed to run opt-6.7b with about 2GB VRAM.

I tried this, but after isntalling FlexGen, converting 1.3b, and trying to run the UI in FlexGen mode all it did was take up all shared GPU memory (but none dedicated?) and generate nothing. Not sure what the deal is.

**Comment by Ph0rk0z** [comment]
Set percentages.
